#!/usr/bin/env bash
# library-stats.sh — recompute live QSP-library metrics from the repo root.
# Usage: bash talks/ksmb2026/scripts/library-stats.sh [repo_root]
# Emits a YAML block to stdout (suitable for talks/ksmb2026/_vars.yml) and a
# human-readable summary to stderr.
set -euo pipefail

ROOT="${1:-$(git -C "$(dirname "$0")" rev-parse --show-toplevel 2>/dev/null || echo "$PWD")}"
cd "$ROOT"

# --- Count disease model directories: any top-level dir holding a *_qsp*.dot ---
mapfile -t MODEL_DIRS < <(
  for d in */; do
    d=${d%/}
    [ "$d" = "talks" ] && continue
    if ls "$d"/*_qsp*.dot >/dev/null 2>&1; then echo "$d"; fi
  done | sort
)
N_MODELS=${#MODEL_DIRS[@]}

# --- References (PubMed links) ---
N_REFS=$(grep -rhoE 'https://pubmed[^ )]*' --include='*references.md' . 2>/dev/null | wc -l | tr -d ' ')
N_REF_FILES=$(find . -name '*references.md' | wc -l | tr -d ' ')

# --- Graphviz pathway clusters ---
N_CLUSTERS=$(grep -rho 'subgraph cluster' --include='*.dot' . 2>/dev/null | wc -l | tr -d ' ')
N_DOT=$(find . -name '*_qsp*.dot' | wc -l | tr -d ' ')

# --- mrgsolve ODE systems ---
N_ODE=$(find . \( -name '*_mrgsolve_model.R' -o -name '*_model.R' \) ! -path './talks/*' | wc -l | tr -d ' ')

# --- Derived ---
REFS_PER=$(awk "BEGIN{ if($N_MODELS>0) printf \"%.0f\", $N_REFS/$N_MODELS; else print 0 }")
CL_PER=$(awk "BEGIN{ if($N_MODELS>0) printf \"%.1f\", $N_CLUSTERS/$N_MODELS; else print 0 }")

{
  echo "## QSP Disease Model Library — live statistics"
  echo "models:            $N_MODELS"
  echo "reference_files:   $N_REF_FILES"
  echo "references:        $N_REFS"
  echo "refs_per_model:    $REFS_PER"
  echo "dot_maps:          $N_DOT"
  echo "clusters:          $N_CLUSTERS"
  echo "clusters_per_model:$CL_PER"
  echo "ode_systems:       $N_ODE"
} >&2

# YAML for _vars.yml (stdout)
cat <<YAML
# Auto-generated by scripts/library-stats.sh — bump on the talk day by re-running.
n_models: $N_MODELS
n_references: $N_REFS
refs_per_model: $REFS_PER
n_clusters: $N_CLUSTERS
clusters_per_model: $CL_PER
n_ode_systems: $N_ODE
YAML
