##  Anemia of Chronic Kidney Disease (ACKD) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Anemia of CKD (renal anemia) — progressive nephron loss and
##             tubulointerstitial fibrosis drive transdifferentiation/loss of
##             peritubular REP (renal EPO-producing) cells -> relative
##             erythropoietin deficiency (EPO "inappropriately normal" for the
##             degree of anemia, because the renal hypoxic drive is additionally
##             BLUNTED by the reduced tubular workload of a shrinking nephron
##             mass). Superimposed on this are (i) hepcidin-mediated FUNCTIONAL
##             iron deficiency — HAMP is driven up by IL-6/STAT3 inflammation
##             AND by loss of renal hepcidin clearance, so ferroportin is
##             degraded, recycled macrophage iron is trapped and duodenal
##             absorption is capped; (ii) shortened RBC lifespan from uremic
##             eryptosis and dialysis/GI blood loss; (iii) direct cytokine
##             suppression of BFU-E/CFU-E and of EPOR-JAK2-STAT5 signalling,
##             i.e. ESA hyporesponsiveness.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 30 ODE compartments —
##             * PK  : ESA SC depot + central (epoetin / darbepoetin /
##                     methoxy-PEG-epoetin beta by parameter switch), oral
##                     HIF-PHI gut + plasma (roxadustat / daprodustat /
##                     vadadustat), oral iron lumen pool, IV iron colloid pool.
##             * PD  : REP-cell pool, HIF-2alpha activity, plasma EPO,
##                     erythroid progenitor + 2 erythroblast transit
##                     compartments, blood reticulocytes, circulating RBC.
##             * Iron: transferrin-bound iron, storage iron, TIBC, hepcidin-25,
##                     erythroferrone, non-transferrin-bound (labile) iron.
##             * Systemic: IL-6, hs-CRP, FGF23, phosphate, LDL-C, mean
##                     arterial pressure, cumulative thrombotic hazard,
##                     FACIT-Fatigue, LV mass index, eGFR.
##  Time     : days (default horizon 365 d — long enough for a full titration
##             cycle, LVMI remodelling and an eGFR trajectory).
##  Units    : Hb g/dL · RBC 10^12/L · reticulocytes and marrow pools 10^9/L ·
##             serum iron & TIBC ug/dL · storage iron mg · hepcidin ng/mL ·
##             IL-6 pg/mL · CRP mg/L · phosphate & LDL mg/dL · MAP mmHg ·
##             eGFR mL/min/1.73m2 · drug amounts in dose-proportional "au"
##             (1 au ESA = 150 U/kg epoetin alfa equivalent; 1 au HIF-PHI =
##             100 mg roxadustat equivalent), the library's standard surrogate
##             when the disease-relevant PD, not the plasma assay, is the
##             object of interest. IV/oral iron are dosed in real mg.
##
##  SELF-CALIBRATING BASELINE
##  -------------------------
##  Rather than hard-coding 30 initial conditions, [MAIN] solves the baseline
##  steady state analytically from the patient descriptors (EGFR0, BASE_HB,
##  FIB, BLUNT, IL6_DRIVE, URE, BLOODLOSS, TSAT0, FERRITIN0, HEPC_BASE ...) and
##  back-calculates the production constants (KIN_PROG, KIN_HEPC, KIN_IL6,
##  KIN_TIBC, KIN_CRP, KIN_LDL, KIN_MAP, KIN_LVMI, KDEP, LOSS_FE) that make
##  that state stationary. Change a patient descriptor and the model still
##  starts in balance — the only intended drift in the untreated arm is the one
##  that is real: eGFR decline -> REP loss -> falling EPO -> falling Hb.
##  Iron balance is closed exactly: obligate loss is set equal to baseline
##  absorption, so any NET iron deficit in a scenario comes from a mechanism
##  the model actually represents (dialysis/GI loss, hepcidin trapping, or an
##  ESA/HIF-PHI-driven surge in erythroid iron demand) — never from bookkeeping.
##
##  Scenarios: 13 prebuilt — see ACKD_simulate_scenarios() at the bottom.
##
##  Anchors  :
##    * Eschbach 1987 NEJM 316:73 — first correction of ESKD anemia with rHuEPO
##      (dose-dependent Hct rise, iron demand unmasked).
##    * Normal Hematocrit Trial (Besarab 1998 NEJM 339:584), CHOIR (Singh 2006
##      NEJM 355:2085), CREATE (Drueke 2006 NEJM 355:2071), TREAT (Pfeffer 2009
##      NEJM 361:2019) — Hb normalisation targets give NO benefit and excess
##      stroke/thrombosis/access loss; drives the safety block of this model.
##    * KDIGO 2012 Anemia Guideline — Hb target 10-11.5 g/dL, start ESA <10,
##      TSAT >20% / ferritin >100 (non-dialysis) or >200 (dialysis) iron
##      thresholds; encoded in the titration logic and the endpoint flags.
##    * PIVOTAL (Macdougall 2019 NEJM 380:447) — proactive high-dose IV iron in
##      HD is ESA-sparing and non-inferior for MACE; scenario 5.
##    * Roxadustat: Chen 2019 NEJM 381:1011 (dialysis) & 381:1001 (ND);
##      daprodustat: ASCEND-D / ASCEND-ND (Singh 2021 NEJM 385:2325 / 2313);
##      vadadustat: INNO2VATE / PRO2TECT (Eckardt / Chertow 2021 NEJM 384:1601
##      / 1589) — HIF-PHIs raise Hb with only modest (near-physiological) EPO
##      excursions, lower hepcidin, raise TIBC and LOWER LDL-C; scenarios 6-7,
##      10 and the PHI block of the map.
##    * Kautz 2014 Nat Genet 46:678 (erythroferrone) and Nemeth 2004 Science
##      306:2090 / JCI 113:1271 (hepcidin-ferroportin, IL-6-STAT3) — the iron
##      restriction machinery.
##    * Krzyzanski & Perez-Ruixo 2007 Pharm Res 24:758 and Uehlinger 1992 Clin
##      Pharmacol Ther 51:76 — precedent lifespan/transit PK-PD structures for
##      EPO-driven erythropoiesis, which this model's PROG->EB1->EB2->RET->RBC
##      chain follows.
##    * Wolf 2020 JAMA 323:432 (PHOSPHARE-IDA) — ferric carboxymaltose raises
##      FGF23 and causes hypophosphatemia; scenario 12.
##  Disclaimer: For research / education / hypothesis generation only. Not a
##              substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of the anemia of chronic kidney disease. Couples (1) nephron loss ->
REP-cell attrition -> blunted HIF-2alpha/EPO output, (2) the hepcidin-
ferroportin-erythroferrone iron-restriction axis with loss of renal hepcidin
clearance, (3) inflammation-driven ESA hyporesponsiveness, and (4) a transit
model of erythropoiesis with an iron-availability gate, to the pharmacology of
ESAs, HIF prolyl-hydroxylase inhibitors, oral and IV iron, anti-IL-6 adjuncts
and transfusion — reporting Hb, reticulocytes, TSAT/ferritin/hepcidin,
FACIT-Fatigue, LV mass index, LDL-C, phosphate, blood pressure and a
cumulative thrombotic hazard index.

[PLUGIN] Rcpp

[SET] end = 365, delta = 1

[GLOBAL]
// Derived constants shared between [MAIN], [ODE] and [TABLE].
// They are back-calculated in [MAIN] from the patient descriptors so that the
// baseline state supplied as initial conditions is genuinely stationary.
double KIN_PROG;   // progenitor influx that holds the erythroid chain at baseline
double KIN_HEPC;   // HAMP transcription rate holding HEPC at HEPC_BASE
double KIN_IL6;    // IL-6 production holding IL6 at IL6_BASE * IL6_DRIVE
double KIN_CRP;    // CRP production per unit IL-6
double KIN_TIBC;   // transferrin synthesis holding TIBC at TIBC0
double KIN_ERFE;   // erythroferrone production (normalised to 1 at baseline)
double KIN_FGF;    // FGF23 production (normalised to 1 at baseline)
double KIN_PHOS;   // phosphate input holding PHOS at PHOS0
double KIN_LDL;    // LDL input holding LDL at LDL0
double KIN_MAP;    // MAP set-point input holding MAP at MAP0
double KIN_LVMI;   // LV mass input holding LVMI at LVMI0
double KDEP;       // plasma -> store iron deposition rate constant
double LOSS_FE;    // obligate iron loss (== baseline absorption: closed balance)
double store0;     // baseline storage iron (mg), reference for the BMP6-SMAD drive
double eb_ref;     // baseline erythroblast mass, reference for the ERFE drive

[PARAM] @annotated
//--------------------------------------------------------------------------
// Patient / disease descriptors  (the "virtual patient")
//--------------------------------------------------------------------------
EGFR0        : 20    : mL/min/1.73m2, baseline eGFR (CKD G4 by default)
EGFR_SLOPE   : 2.5   : mL/min/1.73m2 per year, intrinsic eGFR decline
BASE_HB      : 9.5   : g/dL, presenting hemoglobin
FIB          : 0.6   : 0-1, tubulointerstitial fibrosis / REP-transdifferentiation severity
BLUNT        : 0.7   : 0-1, blunting of the renal hypoxic EPO drive in CKD (the key CKD defect)
DIALYSIS     : 0     : 1 = maintenance hemodialysis (adds circuit blood + iron loss)
URE          : 0.5   : 0-1, uremic-toxin burden shortening RBC lifespan (eryptosis)
BLOODLOSS    : 0.0005: 1/day, fractional RBC loss (GI / phlebotomy; HD adds more)
IL6_DRIVE    : 1.0   : multiplier on inflammatory burden (3-5 = inflammatory hyporesponder)
PTH_SEV      : 0.2   : 0-1, secondary hyperparathyroidism / marrow fibrosis severity
NUTR         : 0     : 0-1, B12 / folate / protein-energy deficit severity
ANTI_IL6     : 0     : 1 = anti-IL-6(R) adjunct on board
WT           : 70    : kg, body weight (for ESA U/kg reporting only)
INIT_FROM_PARAM: 1   : 1 = [MAIN] sets initial conditions from the descriptors below;
//                     set to 0 to RESUME from an init() state (needed by any
//                     block-wise titration loop, which must carry state forward)

//--------------------------------------------------------------------------
// Baseline biomarker anchors (used to self-calibrate production constants)
//--------------------------------------------------------------------------
TSAT0        : 24    : %, baseline transferrin saturation
TIBC0        : 250   : ug/dL, baseline total iron binding capacity
FERRITIN0    : 147   : ng/mL, baseline serum ferritin
HEPC_BASE    : 60    : ng/mL, baseline serum hepcidin-25 (elevated in CKD)
IL6_BASE     : 8     : pg/mL, baseline IL-6 at IL6_DRIVE = 1
CRP0         : 5     : mg/L, baseline hs-CRP
PHOS0        : 4.5   : mg/dL, baseline serum phosphate
LDL0         : 100   : mg/dL, baseline LDL cholesterol
MAP0         : 95    : mmHg, baseline mean arterial pressure
LVMI0        : 120   : g/m2, baseline LV mass index

//--------------------------------------------------------------------------
// ESA PK  (defaults = epoetin alfa SC; see notes for darbepoetin / MPG-EPO)
//--------------------------------------------------------------------------
KA_ESA       : 0.35  : 1/day, SC absorption (flip-flop; epoetin 0.35, darbepoetin 0.25, MPG-EPO 0.08)
F_ESA        : 0.30  : SC bioavailability (epoetin ~0.2-0.4, darbepoetin ~0.4-0.5)
KEL_ESA      : 1.80  : 1/day, systemic elimination (epoetin 1.8, darbepoetin 0.65, MPG-EPO 0.13)
ESA_POT      : 1000  : mIU/mL EPO-equivalent per au of ESA_CENT
ESA_WK_UKG   : 0     : U/kg/week, nominal ESA dose (reporting/ERI only, no PD effect)

//--------------------------------------------------------------------------
// HIF-PHI PK / PD  (defaults = roxadustat; 1 au = 100 mg)
//--------------------------------------------------------------------------
KA_PHI       : 3.0   : 1/day, oral absorption
F_PHI        : 0.85  : oral bioavailability (reduced by co-administered phosphate binders)
KEL_PHI      : 0.55  : 1/day, elimination (roxadustat 0.55, daprodustat 3.5, vadadustat 0.7)
IC50_PHD     : 1.0   : au, PHD1/2/3 2-OG-site inhibition potency

//--------------------------------------------------------------------------
// Oxygen sensing / HIF-2alpha
//--------------------------------------------------------------------------
KIN_HIF      : 12    : 1/day, HIF-alpha synthesis (fast turnover)
KOUT_HIF     : 12    : 1/day, PHD-VHL-proteasome degradation
KHYP         : 12    : gain of the anemic hypoxic drive on HIF (intact-kidney gain)
HB_SENSE     : 10.5  : g/dL, Hb set-point of the renal O2 sensor

//--------------------------------------------------------------------------
// REP cells & erythropoietin
//--------------------------------------------------------------------------
KIN_REP      : 0.02  : 1/day, REP-cell pool replenishment
KOUT_REP     : 0.02  : 1/day, REP-cell loss
HREP         : 0.7   : exponent linking eGFR to functional REP mass
REP_FLOOR    : 0.05  : residual/extrarenal EPO-competent fraction
KIN_EPO_REN  : 50    : mIU/mL/day, maximal renal EPO synthesis capacity
KIN_EPO_HEP  : 12    : mIU/mL/day, HIF-inducible hepatic EPO capacity
GAM_HIF      : 2.5   : Hill exponent, HIF -> renal EPO transcription
GAM_HEP      : 1.5   : Hill exponent, HIF -> hepatic EPO transcription
KEL_EPO      : 2.4   : 1/day, EPO elimination (t1/2 ~7 h)
IC50_IL6_EPO : 20    : pg/mL, IL-6/NF-kB-GATA2 repression of EPO transcription

//--------------------------------------------------------------------------
// Erythropoiesis (transit chain with iron gate)
//--------------------------------------------------------------------------
EC50_EPO     : 30    : mIU/mL, EPO-equivalent EC50 for progenitor expansion
HILL_EPO     : 1.6   : Hill exponent of the EPO response
EMAX_EPO     : 0.60  : maximal fractional increase in progenitor influx
KTR           : 0.30 : 1/day, marrow transit rate (3 stages ~ 10 d)
KRET          : 0.50 : 1/day, blood reticulocyte maturation (~2 d)
LS0           : 100  : days, intrinsic RBC lifespan
LS_URE        : 0.25 : fractional lifespan shortening at URE = 1
KM_TSAT       : 12   : %, Michaelis constant of iron availability for Hb synthesis
APOP_MAX      : 0.35 : maximal ineffective-erythropoiesis (apoptotic) fraction
IC50_IL6_PROG : 25   : pg/mL, cytokine suppression of BFU-E/CFU-E
KIL6_EPOR     : 2.0  : maximal TNF/IL-6 attenuation of EPOR-JAK2-STAT5 signal transduction
IC50_EPOR     : 30   : pg/mL, cytokine potency on EPOR signal transduction
MCHC_F        : 3.05 : g/dL per 10^12/L RBC (iron-replete corpuscular Hb)

//--------------------------------------------------------------------------
// Iron kinetics
//--------------------------------------------------------------------------
PLASMA_DL     : 30   : dL, plasma volume (ug/dL <-> mg conversion)
DIET_FE       : 8.0  : mg/day, dietary iron entering the lumen
KA_FE         : 1.5  : 1/day, luminal transit
FMAX_ABS      : 0.28 : maximal fractional duodenal absorption
IC50_HEPC_ABS : 35   : ng/mL, hepcidin IC50 on enterocyte ferroportin
KHIF_ABS      : 0.9  : HIF gain on DMT1/DCYTB/ferroportin absorption
IC50_HEPC_FPN : 45   : ng/mL, hepcidin IC50 on macrophage ferroportin
FPN_REL_MAX   : 1.8  : cap on relative ferroportin activity vs baseline
FPN_FLOOR     : 0.45 : hepcidin-independent fraction of recycled iron still released
MOB_FLOOR     : 0.35 : hepcidin-independent fraction of storage-iron mobilisation
MOB_MAX       : 20.0 : mg/day, maximal storage-iron mobilisation
KM_STORE      : 400  : mg, half-saturation of the mobilisable store
FE_PER_CELL   : 0.297: mg per (10^9 RBC/L) of erythron iron
KPROC_IV      : 0.35 : 1/day, RE-macrophage processing of IV iron colloid
FIV_DIRECT    : 0.20 : fraction of processed IV iron released straight to transferrin
DIAL_FE_LOSS  : 1.5  : mg/day extra iron loss when DIALYSIS = 1
KOUT_TIBC     : 0.10 : 1/day, transferrin turnover
KHIF_TF       : 0.35 : HIF gain on transferrin (TIBC) synthesis
IC50_IL6_TF   : 40   : pg/mL, inflammatory suppression of transferrin
FERR_PER_MG   : 6.5  : mg storage iron per ng/mL of serum ferritin
FERR_APR      : 20   : ng/mL, maximal acute-phase ferritin add-on

//--------------------------------------------------------------------------
// Hepcidin / erythroferrone
//--------------------------------------------------------------------------
KOUT_HEPC     : 3.0  : 1/day, hepcidin elimination (largely renal)
HB_STORE      : 0.5  : Hill exponent, storage iron -> BMP6-SMAD -> HAMP
STOREDRV_MAX  : 2.0  : cap on the storage-iron (BMP6-SMAD) drive of HAMP
KIL6_HEPC     : 3.0  : maximal IL-6-STAT3 fold-induction of HAMP
IC50_IL6_HEPC : 10   : pg/mL, IL-6 potency on HAMP
KPHI_HEPC     : 1.2  : HIF-mediated (direct + ERFE-independent) HAMP suppression
HCL           : 0.6  : exponent of eGFR-dependent hepcidin clearance
HEPC_NONREN   : 0.35 : non-renal fraction of hepcidin clearance
KERFE         : 1.0  : ERFE potency on HAMP suppression
KOUT_ERFE     : 2.0  : 1/day, erythroferrone turnover
GAM_ERFE      : 2.0  : Hill exponent, erythroblast mass -> ERFE

//--------------------------------------------------------------------------
// Inflammation
//--------------------------------------------------------------------------
KOUT_IL6      : 4.0  : 1/day, IL-6 turnover
KUREM_IL6     : 1.2  : uremic gain on IL-6 production
KANTI_IL6     : 3.0  : potency of the anti-IL-6(R) adjunct
KOUT_CRP      : 0.8  : 1/day, CRP turnover

//--------------------------------------------------------------------------
// FGF23 / phosphate / lipids / haemodynamics
//--------------------------------------------------------------------------
KOUT_FGF      : 0.12 : 1/day, FGF23 turnover (t1/2 ~6 d, matching the duration of post-FCM hypophosphatemia)
KFCM          : 0.018: FGF23 induction per (mg/day) of processed IV iron
FCM_FLAG      : 1    : 1 = the IV iron in use is ferric carboxymaltose (FGF23-inducing)
KP_FGF        : 0.4  : phosphate feedback on FGF23
KOUT_PHOS     : 0.5  : 1/day, renal/intestinal phosphate handling
GAM_FGF       : 1.2  : exponent of FGF23 phosphaturia
KOUT_LDL      : 0.15 : 1/day, LDL turnover
KPHI_LDL      : 0.12 : HIF-mediated LDL-C lowering gain
KOUT_MAP      : 0.20 : 1/day, blood-pressure set-point turnover
KESA_BP       : 0.07 : ESA-driven fractional MAP rise (Emax)
EC50_BP       : 0.05 : au, ESA concentration for half-maximal MAP effect
KHB_BP        : 0.18 : fractional MAP rise per unit relative Hb above 11 g/dL

//--------------------------------------------------------------------------
// Safety / thrombotic hazard / labile iron
//--------------------------------------------------------------------------
HAZ0          : 0.00274: 1/day, baseline thrombotic hazard (= 1.0 event-equivalent per year)
KVISC_T       : 0.55 : hazard gain per (g/dL)^2 of Hb above 12
KESA_T        : 0.60 : hazard gain from ESA exposure (Emax)
KPHI_T        : 0.35 : hazard gain from HIF-PHI exposure (Emax)
KMAP_T        : 0.90 : hazard gain per relative MAP rise
KNTBI_T       : 0.50 : hazard gain per unit labile (non-transferrin-bound) iron
TSAT_OVER     : 60   : %, TSAT above which iron overflows into stores
KOVER_DEP     : 20   : gain of the overflow deposition that bounds TSAT below 100%
KIN_NTBI      : 0.30 : NTBI generation above TSAT 70%
KIV_NTBI      : 0.02 : NTBI generation per (mg/day) of processed IV iron
KOUT_NTBI     : 2.0  : 1/day, NTBI clearance

//--------------------------------------------------------------------------
// Patient-reported outcome / cardiac remodelling / progression
//--------------------------------------------------------------------------
FAT_MIN       : 14   : FACIT-Fatigue floor
FAT_MAX       : 44   : FACIT-Fatigue ceiling
EC50_FAT      : 10.5 : g/dL, Hb for half-maximal fatigue benefit
HILL_FAT      : 4.0  : Hill exponent of the Hb-fatigue relationship
KOUT_FAT      : 0.05 : 1/day, fatigue equilibration (lag ~3 weeks)
KOUT_LVMI     : 0.004: 1/day, LV mass remodelling
KAN_LV        : 1.5  : anemia gain on LV mass
KBP_LV        : 1.0  : blood-pressure gain on LV mass
KAN_PROG      : 0.4  : anemia acceleration of eGFR decline

//--------------------------------------------------------------------------
// Transfusion (dosed into RBC as 10^12/L increments; 1 unit ~ 0.33)
//--------------------------------------------------------------------------
TX_FE_PER_U   : 200  : mg iron delivered to stores per transfused unit-equivalent

[CMT] @annotated
ESA_SC    : ESA subcutaneous depot (au)
ESA_CENT  : ESA central compartment (au)
PHI_GUT   : HIF-PHI oral absorption depot (au)
PHI_CENT  : HIF-PHI plasma compartment (au)
FE_GUT    : Luminal iron pool available for absorption (mg)
FE_IV     : IV iron colloid awaiting RE-macrophage processing (mg)
REP       : Functional REP (renal EPO-producing) cell pool (fraction of healthy)
HIF       : HIF-2alpha transcriptional activity (relative, 1 = intact normoxic)
EPO       : Plasma endogenous erythropoietin (mIU/mL)
PROG      : BFU-E / CFU-E progenitor pool (10^9/L equivalents)
EB1       : Early erythroblast transit compartment (10^9/L)
EB2       : Late erythroblast / marrow reticulocyte transit compartment (10^9/L)
RET       : Blood reticulocytes (10^9/L)
RBC       : Circulating red cell count (10^12/L)
FE_TF     : Transferrin-bound (serum) iron (ug/dL)
FE_STORE  : Reticuloendothelial + hepatic storage iron (mg)
TIBC      : Total iron binding capacity / transferrin (ug/dL)
HEPC      : Serum hepcidin-25 (ng/mL)
ERFE      : Erythroferrone (relative, 1 = baseline)
IL6       : Interleukin-6 (pg/mL)
CRP       : High-sensitivity C-reactive protein (mg/L)
FGF23     : Fibroblast growth factor 23 (relative, 1 = baseline)
PHOS      : Serum phosphate (mg/dL)
LDL       : LDL cholesterol (mg/dL)
MAP       : Mean arterial pressure (mmHg)
NTBI      : Non-transferrin-bound / labile plasma iron (relative)
THR       : Cumulative thrombotic hazard (event-equivalents)
FATIGUE   : FACIT-Fatigue score (0-52, higher = less fatigue)
LVMI      : Left-ventricular mass index (g/m2)
EGFR      : Estimated GFR (mL/min/1.73m2)

[MAIN]
//==========================================================================
//  Self-calibrating baseline: solve the stationary state from the patient
//  descriptors, then back out the production constants that hold it.
//==========================================================================

// --- kidney, oxygen sensing, EPO -----------------------------------------
double rep0     = pow(EGFR0 / 90.0, HREP) / (1.0 + FIB);
double hypdrv0  = KHYP * fmax(0.0, (HB_SENSE - BASE_HB) / HB_SENSE) * (1.0 - BLUNT);
double hif0     = 1.0 + hypdrv0;
double il60     = IL6_BASE * IL6_DRIVE / (1.0 + KANTI_IL6 * ANTI_IL6);
double epo_ren0 = KIN_EPO_REN * (rep0 + REP_FLOOR) * pow(hif0, GAM_HIF)
                  / (1.0 + il60 / IC50_IL6_EPO);
double epo_hep0 = KIN_EPO_HEP * pow(fmax(0.0, hif0 - 1.0), GAM_HEP);
double epo0     = (epo_ren0 + epo_hep0) / KEL_EPO;

// --- iron status ---------------------------------------------------------
double fetf0    = TSAT0 * TIBC0 / 100.0;
store0          = fmax(50.0, (FERRITIN0 - FERR_APR * il60 / (il60 + 10.0)) * FERR_PER_MG);
double gate0    = TSAT0 / (TSAT0 + KM_TSAT);
double hypo0    = fmin(1.0, 0.85 + 0.15 * gate0 / 0.75);

// --- red cell mass and the erythroid chain ------------------------------
double rbc0     = BASE_HB / (MCHC_F * hypo0);
double ls0      = LS0 * (1.0 - LS_URE * URE);
double bl_tot   = BLOODLOSS + 0.0035 * DIALYSIS;
double destr0   = rbc0 / ls0 + bl_tot * rbc0;              // 10^12/L/day
double ret0     = destr0 * 1000.0 / KRET;                  // 10^9/L
double retprod0 = KRET * ret0;                             // 10^9/L/day
double apop0    = APOP_MAX * il60 / (il60 + IC50_IL6_PROG);
double eb0      = retprod0 / (KTR * gate0 * (1.0 - apop0));
double epor0    = 1.0 + KIL6_EPOR * il60 / (il60 + IC50_EPOR);
double epoe0    = epo0 / epor0;                            // EPOR-transduced signal
double drive0   = 1.0 + EMAX_EPO * pow(epoe0, HILL_EPO)
                        / (pow(EC50_EPO, HILL_EPO) + pow(epoe0, HILL_EPO));
double marrow0  = 1.0 / (1.0 + 0.5 * PTH_SEV + 0.6 * NUTR);
double infl0    = 1.0 / (1.0 + il60 / IC50_IL6_PROG);
// production constant that makes PROG stationary at eb0:
KIN_PROG        = KTR * eb0 / (drive0 * infl0 * marrow0);

// --- iron balance closure ------------------------------------------------
double fpn_act0 = 1.0 / (1.0 + HEPC_BASE / IC50_HEPC_FPN);
double absfr0   = FMAX_ABS / (1.0 + HEPC_BASE / IC50_HEPC_ABS)
                  * (1.0 + KHIF_ABS * fmax(0.0, hif0 - 1.0));
double abs0     = absfr0 * DIET_FE;                        // mg/day absorbed
double util0    = FE_PER_CELL * retprod0;                  // mg/day into erythron
double rec0     = FE_PER_CELL * destr0 * 1000.0;           // mg/day recycled
double mob0     = MOB_MAX * (store0 / (store0 + KM_STORE)); // mg/day mobilised
double over0    = 1.0 + KOVER_DEP * pow(fmax(0.0, TSAT0 - TSAT_OVER) / 40.0, 2.0);
// obligate loss set equal to baseline absorption  => closed iron balance.
// (Baseline recycling exactly equals baseline erythron utilisation, because at
//  steady state RBC destruction equals reticulocyte delivery, so plasma iron
//  balances iff absorption == obligate loss. Any NET deficit in a scenario is
//  therefore mechanistic, not a bookkeeping artefact.)
LOSS_FE         = abs0;
// deposition matched to mobilisation => stationary stores
KDEP            = mob0 / (fetf0 * PLASMA_DL / 1000.0 * over0);

// --- back-calculated production constants -------------------------------
double inflh0    = 1.0 + KIL6_HEPC * il60 / (IC50_IL6_HEPC + il60);
double rencl0    = pow(EGFR0 / 90.0, HCL) + HEPC_NONREN;
KIN_HEPC         = KOUT_HEPC * HEPC_BASE * rencl0
                   * (1.0 + KPHI_HEPC * fmax(0.0, hif0 - 1.0)) / inflh0;
KIN_IL6          = KOUT_IL6 * il60 * (1.0 + KANTI_IL6 * ANTI_IL6)
                   / (IL6_DRIVE * (1.0 + KUREM_IL6 * (1.0 - EGFR0 / 90.0)));
KIN_CRP          = KOUT_CRP * CRP0 / il60;
double tibcf0    = (1.0 + KHIF_TF * fmax(0.0, hif0 - 1.0)) / (1.0 + il60 / IC50_IL6_TF);
KIN_TIBC         = KOUT_TIBC * TIBC0 / tibcf0;
KIN_ERFE         = KOUT_ERFE;
eb_ref           = 2.0 * eb0;
KIN_FGF          = KOUT_FGF;
KIN_PHOS         = KOUT_PHOS * PHOS0;
KIN_LDL          = KOUT_LDL * LDL0 * (1.0 + KPHI_LDL * fmax(0.0, hif0 - 1.0));
KIN_MAP          = KOUT_MAP * MAP0 / (1.0 + KHB_BP * fmax(0.0, BASE_HB - 11.0) / 11.0);
double fat0      = FAT_MIN + (FAT_MAX - FAT_MIN) * pow(BASE_HB, HILL_FAT)
                   / (pow(EC50_FAT, HILL_FAT) + pow(BASE_HB, HILL_FAT));
KIN_LVMI         = KOUT_LVMI * LVMI0
                   / (1.0 + KAN_LV * fmax(0.0, 11.5 - BASE_HB) / 11.5);

//==========================================================================
//  Initial conditions
//  Guarded by INIT_FROM_PARAM: the derived constants above are ALWAYS
//  recomputed (they are patient constants), but the state is only reset when
//  INIT_FROM_PARAM = 1. Set it to 0 and supply init() to resume a trajectory —
//  otherwise these assignments silently overwrite whatever init() provided.
//==========================================================================
if (INIT_FROM_PARAM > 0.5) {
REP_0      = rep0;
HIF_0      = hif0;
EPO_0      = epo0;
PROG_0     = eb0;
EB1_0      = eb0;
EB2_0      = eb0;
RET_0      = ret0;
RBC_0      = rbc0;
FE_GUT_0   = DIET_FE / KA_FE;
FE_TF_0    = fetf0;
FE_STORE_0 = store0;
TIBC_0     = TIBC0;
HEPC_0     = HEPC_BASE;
ERFE_0     = 1.0;
IL6_0      = il60;
CRP_0      = CRP0;
FGF23_0    = 1.0;
PHOS_0     = PHOS0;
LDL_0      = LDL0;
MAP_0      = MAP0;
NTBI_0     = 0.0;
THR_0      = 0.0;
FATIGUE_0  = fat0;
LVMI_0     = LVMI0;
EGFR_0     = EGFR0;
}

[ODE]
//==========================================================================
//  Algebraic layer
//==========================================================================
double tsat    = 100.0 * FE_TF / fmax(1.0, TIBC);
double gate    = tsat / (tsat + KM_TSAT);                 // iron availability
double hypo    = fmin(1.0, 0.85 + 0.15 * gate / 0.75);    // corpuscular Hb factor
double hgb     = RBC * MCHC_F * hypo;                     // g/dL
double ferr    = FE_STORE / FERR_PER_MG + FERR_APR * IL6 / (IL6 + 10.0);

// --- oxygen sensing -----------------------------------------------------
double phd_act = 1.0 / (1.0 + PHI_CENT / IC50_PHD);       // PHD activity (drug-inhibited)
double hyp_drv = KHYP * fmax(0.0, (HB_SENSE - hgb) / HB_SENSE) * (1.0 - BLUNT);
double hif_ex  = fmax(0.0, HIF - 1.0);                    // HIF above intact-normoxic

// --- erythropoietic drive ----------------------------------------------
double epo_tot = EPO + ESA_POT * ESA_CENT;
// Inflammatory attenuation of EPOR-JAK2-STAT5 transduction: the mechanistic
// core of ESA hyporesponsiveness. It scales the DRUG signal, so a raised
// IL6_DRIVE blunts the Hb gained per unit of ESA exposure, not just baseline.
double epor_at = 1.0 + KIL6_EPOR * IL6 / (IL6 + IC50_EPOR);
double epo_eff = epo_tot / epor_at;
double drive   = 1.0 + EMAX_EPO * pow(epo_eff, HILL_EPO)
                       / (pow(EC50_EPO, HILL_EPO) + pow(epo_eff, HILL_EPO));
double infl_p  = 1.0 / (1.0 + IL6 / IC50_IL6_PROG);
double marrow  = 1.0 / (1.0 + 0.5 * PTH_SEV + 0.6 * NUTR);
double apop    = APOP_MAX * IL6 / (IL6 + IC50_IL6_PROG);

// --- red cell turnover --------------------------------------------------
double ls      = LS0 * (1.0 - LS_URE * URE);
double bl      = BLOODLOSS + 0.0035 * DIALYSIS;
double destr   = RBC / ls + bl * RBC;                     // 10^12/L/day
double retprod = KTR * EB2 * gate * (1.0 - apop);         // 10^9/L/day delivered
double demand  = KTR * EB2 * (1.0 - apop);                // iron demand if unrestricted

// --- iron fluxes (mg/day) ----------------------------------------------
double fpn_act = 1.0 / (1.0 + HEPC / IC50_HEPC_FPN);
double fpn_ref = 1.0 / (1.0 + HEPC_BASE / IC50_HEPC_FPN);
double fpn_rel = fmin(FPN_REL_MAX, fpn_act / fpn_ref);
double absfr   = FMAX_ABS / (1.0 + HEPC / IC50_HEPC_ABS)
                 * (1.0 + KHIF_ABS * hif_ex);
double fe_abs  = absfr * KA_FE * FE_GUT;
double rec_tot = FE_PER_CELL * destr * 1000.0;
// Hepcidin blockade of ferroportin is strong but NOT absolute: a floor of
// recycled iron keeps reaching transferrin and a floor of storage iron keeps
// being mobilised, otherwise high hepcidin becomes a one-way ratchet that
// buries iron in stores while the erythron starves.
double rel_eff = fmin(1.0, FPN_FLOOR + (1.0 - FPN_FLOOR) * fpn_rel);
double mob_eff = MOB_FLOOR + (1.0 - MOB_FLOOR) * fpn_rel;
double rec_rel = rec_tot * rel_eff;
double rec_trp = rec_tot - rec_rel;                       // hepcidin-trapped iron
double fe_mob  = MOB_MAX * mob_eff * (FE_STORE / (FE_STORE + KM_STORE));
double fe_util = FE_PER_CELL * retprod;
// Transferrin cannot hold more iron than TIBC: above TSAT_OVER the surplus is
// shunted into storage (and into NTBI below), which bounds TSAT below 100%.
double over_f  = 1.0 + KOVER_DEP * pow(fmax(0.0, tsat - TSAT_OVER) / 40.0, 2.0);
double fe_dep  = KDEP * FE_TF * PLASMA_DL / 1000.0 * over_f;
double iv_proc = KPROC_IV * FE_IV;
double fe_loss = LOSS_FE + DIAL_FE_LOSS * DIALYSIS;
double fe_net  = fe_abs + rec_rel + fe_mob + FIV_DIRECT * iv_proc
                 - fe_util - fe_loss - fe_dep;

//==========================================================================
//  Differential equations
//==========================================================================
// ---- 1-6  drug PK ------------------------------------------------------
dxdt_ESA_SC   = -KA_ESA * ESA_SC;
dxdt_ESA_CENT =  F_ESA * KA_ESA * ESA_SC - KEL_ESA * ESA_CENT;
dxdt_PHI_GUT  = -KA_PHI * PHI_GUT;
dxdt_PHI_CENT =  F_PHI * KA_PHI * PHI_GUT - KEL_PHI * PHI_CENT;
dxdt_FE_GUT   =  DIET_FE - KA_FE * FE_GUT;
dxdt_FE_IV    = -iv_proc;

// ---- 7-9  kidney -> oxygen sensing -> EPO ------------------------------
dxdt_REP      = KIN_REP * pow(EGFR / 90.0, HREP) / (1.0 + FIB) - KOUT_REP * REP;
dxdt_HIF      = KIN_HIF * (1.0 + hyp_drv) - KOUT_HIF * HIF * phd_act;
dxdt_EPO      = KIN_EPO_REN * (REP + REP_FLOOR) * pow(HIF, GAM_HIF)
                  / (1.0 + IL6 / IC50_IL6_EPO)
              + KIN_EPO_HEP * pow(hif_ex, GAM_HEP)
              - KEL_EPO * EPO;

// ---- 10-14  erythropoiesis --------------------------------------------
dxdt_PROG     = KIN_PROG * drive * infl_p * marrow - KTR * PROG;
dxdt_EB1      = KTR * PROG - KTR * EB1;
dxdt_EB2      = KTR * EB1  - KTR * EB2;
dxdt_RET      = retprod - KRET * RET;
dxdt_RBC      = KRET * RET / 1000.0 - destr;

// ---- 15-17  iron pools -------------------------------------------------
dxdt_FE_TF    = fe_net / (PLASMA_DL / 1000.0);
dxdt_FE_STORE = fe_dep + rec_trp + (1.0 - FIV_DIRECT) * iv_proc - fe_mob;
dxdt_TIBC     = KIN_TIBC * (1.0 + KHIF_TF * hif_ex) / (1.0 + IL6 / IC50_IL6_TF)
              - KOUT_TIBC * TIBC;

// ---- 18-19  hepcidin / erythroferrone ---------------------------------
dxdt_HEPC     = KIN_HEPC * fmin(STOREDRV_MAX, pow(FE_STORE / fmax(1.0, store0), HB_STORE))
                  * (1.0 + KIL6_HEPC * IL6 / (IC50_IL6_HEPC + IL6))
                  / ((1.0 + KERFE * fmax(0.0, ERFE - 1.0))
                     * (1.0 + KPHI_HEPC * hif_ex))
              - KOUT_HEPC * HEPC * (pow(EGFR / 90.0, HCL) + HEPC_NONREN);
dxdt_ERFE     = KIN_ERFE * pow((EB1 + EB2) / fmax(1.0, eb_ref), GAM_ERFE)
              - KOUT_ERFE * ERFE;

// ---- 20-21  inflammation ----------------------------------------------
dxdt_IL6      = KIN_IL6 * IL6_DRIVE * (1.0 + KUREM_IL6 * (1.0 - EGFR / 90.0))
                  / (1.0 + KANTI_IL6 * ANTI_IL6)
              - KOUT_IL6 * IL6;
dxdt_CRP      = KIN_CRP * IL6 - KOUT_CRP * CRP;

// ---- 22-23  FGF23 / phosphate (IV-iron safety axis) -------------------
dxdt_FGF23    = KIN_FGF * (1.0 + KFCM * FCM_FLAG * iv_proc
                             + KP_FGF * fmax(0.0, PHOS - PHOS0))
              - KOUT_FGF * FGF23;
dxdt_PHOS     = KIN_PHOS - KOUT_PHOS * PHOS * pow(fmax(0.1, FGF23), GAM_FGF);

// ---- 24-25  lipids / haemodynamics ------------------------------------
dxdt_LDL      = KIN_LDL / (1.0 + KPHI_LDL * hif_ex) - KOUT_LDL * LDL;
dxdt_MAP      = KIN_MAP * (1.0 + KESA_BP * ESA_CENT / (ESA_CENT + EC50_BP)
                             + KHB_BP * fmax(0.0, hgb - 11.0) / 11.0)
              - KOUT_MAP * MAP;

// ---- 26-27  labile iron / thrombotic hazard ---------------------------
dxdt_NTBI     = KIN_NTBI * fmax(0.0, tsat - 70.0) / 30.0
              + KIV_NTBI * iv_proc - KOUT_NTBI * NTBI;
dxdt_THR      = HAZ0 * (1.0
                + KVISC_T * pow(fmax(0.0, hgb - 12.0), 2.0)
                + KESA_T * ESA_CENT / (ESA_CENT + EC50_BP)
                + KPHI_T * PHI_CENT / (PHI_CENT + IC50_PHD)
                + KMAP_T * fmax(0.0, MAP - MAP0) / MAP0
                + KNTBI_T * NTBI);

// ---- 28-30  PRO / cardiac remodelling / progression -------------------
double fat_tgt = FAT_MIN + (FAT_MAX - FAT_MIN) * pow(hgb, HILL_FAT)
                 / (pow(EC50_FAT, HILL_FAT) + pow(hgb, HILL_FAT));
dxdt_FATIGUE  = KOUT_FAT * (fat_tgt - FATIGUE);
dxdt_LVMI     = KIN_LVMI * (1.0 + KAN_LV * fmax(0.0, 11.5 - hgb) / 11.5
                             + KBP_LV * fmax(0.0, MAP - MAP0) / MAP0)
              - KOUT_LVMI * LVMI;
dxdt_EGFR     = -(EGFR_SLOPE / 365.0)
                * (1.0 + KAN_PROG * fmax(0.0, HB_SENSE - hgb) / HB_SENSE);

[TABLE]
double tsat_o  = 100.0 * FE_TF / fmax(1.0, TIBC);
double gate_o  = tsat_o / (tsat_o + KM_TSAT);
double hypo_o  = fmin(1.0, 0.85 + 0.15 * gate_o / 0.75);
double hgb_o   = RBC * MCHC_F * hypo_o;
double hct_o   = 3.0 * hgb_o;
double ferr_o  = FE_STORE / FERR_PER_MG + FERR_APR * IL6 / (IL6 + 10.0);
double retp_o  = 100.0 * RET / (RBC * 1000.0);
double epo_o   = EPO + ESA_POT * ESA_CENT;

capture Hemoglobin        = hgb_o;
capture Hematocrit        = hct_o;
capture RBC_count         = RBC;
capture Reticulocyte_pct  = retp_o;
capture Reticulocyte_abs  = RET;
capture EPO_endogenous    = EPO;
capture EPO_total_equiv   = epo_o;
capture EPOR_attenuation  = 1.0 + KIL6_EPOR * IL6 / (IL6 + IC50_EPOR);
capture HIF_activity      = HIF;
capture REP_pool          = REP;
capture Serum_iron        = FE_TF;
capture TSAT_pct          = tsat_o;
capture TIBC_level        = TIBC;
capture Ferritin          = ferr_o;
capture Storage_iron_mg   = FE_STORE;
capture Iron_gate         = gate_o;
capture Hepcidin          = HEPC;
capture Erythroferrone    = ERFE;
capture IL6_level         = IL6;
capture CRP_level         = CRP;
capture FGF23_level       = FGF23;
capture Phosphate         = PHOS;
capture LDL_C             = LDL;
capture MAP_mmHg          = MAP;
capture NTBI_level        = NTBI;
capture Thrombotic_hazard = THR;
capture FACIT_fatigue     = FATIGUE;
capture LVMI_g_m2         = LVMI;
capture eGFR_ml_min       = EGFR;
capture ESA_conc          = ESA_CENT;
capture PHI_conc          = PHI_CENT;
// KDIGO-style endpoint flags and the ESA resistance index
capture In_target_10_115  = (hgb_o >= 10.0 && hgb_o <= 11.5) ? 1.0 : 0.0;
capture Hb_overshoot_13   = (hgb_o > 13.0) ? 1.0 : 0.0;
capture Iron_sufficient   = (tsat_o >= 20.0 && ferr_o >= 100.0) ? 1.0 : 0.0;
capture Hypophosphatemia  = (PHOS < 2.0) ? 1.0 : 0.0;
capture ERI_Ukg_g         = (hgb_o > 0.0) ? ESA_WK_UKG / hgb_o : 0.0;

[CAPTURE]
Hemoglobin Hematocrit RBC_count Reticulocyte_pct Reticulocyte_abs
EPO_endogenous EPO_total_equiv EPOR_attenuation HIF_activity REP_pool
Serum_iron TSAT_pct TIBC_level Ferritin Storage_iron_mg Iron_gate
Hepcidin Erythroferrone IL6_level CRP_level
FGF23_level Phosphate LDL_C MAP_mmHg NTBI_level Thrombotic_hazard
FACIT_fatigue LVMI_g_m2 eGFR_ml_min ESA_conc PHI_conc
In_target_10_115 Hb_overshoot_13 Iron_sufficient Hypophosphatemia ERI_Ukg_g


##  ============================================================================
##  R-side scenario helpers (documentation for users; not parsed by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("ackd", project = ".")   # file: ackd_mrgsolve_model.R
##
##  ---------------------------------------------------------------------------
##  Dose-unit conventions
##  ---------------------------------------------------------------------------
##    ESA_SC   amt = 1.0  ~ epoetin alfa 150 U/kg SC (au)
##    PHI_GUT  amt = 1.0  ~ roxadustat 100 mg PO     (au)
##    FE_GUT   amt in mg  ~ oral elemental iron (e.g. 65 mg = ferrous sulfate 200 mg)
##    FE_IV    amt in mg  ~ IV elemental iron (e.g. 500 mg ferric carboxymaltose)
##    RBC      amt = 0.33 ~ one unit of packed red cells (raises Hb ~1 g/dL)
##
##  Agent switches applied with param():
##    epoetin alfa SC      : KA_ESA=0.35, F_ESA=0.30, KEL_ESA=1.80
##    darbepoetin alfa SC  : KA_ESA=0.25, F_ESA=0.45, KEL_ESA=0.65
##    MPG-epoetin beta SC  : KA_ESA=0.08, F_ESA=0.55, KEL_ESA=0.13
##    roxadustat PO        : KA_PHI=3.0,  F_PHI=0.85, KEL_PHI=0.55
##    daprodustat PO       : KA_PHI=6.0,  F_PHI=0.65, KEL_PHI=3.50
##    vadadustat PO        : KA_PHI=4.0,  F_PHI=0.80, KEL_PHI=0.70
##    iron isomaltoside (no FGF23 signal) : FCM_FLAG = 0
##
##  ---------------------------------------------------------------------------
##  15 prebuilt scenarios  (doses below are the ones checked against the
##  independent numerical replication in this directory's README validation
##  table — change them and the reported Hb trajectories will move)
##  ---------------------------------------------------------------------------
##  ACKD_simulate_scenarios <- function(end_d = 365) {
##
##    nd  <- list(EGFR0 = 20, DIALYSIS = 0, BLOODLOSS = 0.0005)   # non-dialysis CKD G4
##    hd  <- list(EGFR0 = 8,  DIALYSIS = 1, BLOODLOSS = 0.0005)   # maintenance HD
##    epo <- list(KA_ESA = 0.35, F_ESA = 0.30, KEL_ESA = 1.80)
##    dar <- list(KA_ESA = 0.25, F_ESA = 0.45, KEL_ESA = 0.65)
##    mpg <- list(KA_ESA = 0.08, F_ESA = 0.55, KEL_ESA = 0.13)
##    rox <- list(KA_PHI = 3.0,  F_PHI = 0.85, KEL_PHI = 0.55)
##    dap <- list(KA_PHI = 6.0,  F_PHI = 0.65, KEL_PHI = 3.50)
##    tiw <- 7 / 3                                                # three times weekly
##
##    run <- function(p, e) mod %>% param(p) %>%
##      mrgsim(events = e, end = end_d, delta = 1) %>% as_tibble()
##
##    list(
##      # 1. Untreated natural history — Hb drifts down with eGFR/REP loss
##      "1. Untreated natural history (CKD G4)" =
##        run(nd, ev(amt = 0, cmt = "ESA_SC")),
##
##      # 2. Epoetin alfa ~75 U/kg SC TIW — typical MAINTENANCE dose, lands in band
##      "2. Epoetin alfa 75 U/kg SC TIW (maintenance)" =
##        run(c(nd, epo, list(ESA_WK_UKG = 225)),
##            ev(amt = 0.5, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 3. Epoetin alfa 150 U/kg SC TIW — CORRECTION dose held too long: shows
##      #    why an open-loop ESA dose overshoots the 10-11.5 g/dL band
##      "3. Epoetin alfa 150 U/kg SC TIW (correction, overshoots)" =
##        run(c(nd, epo, list(ESA_WK_UKG = 450)),
##            ev(amt = 1.0, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 4. Darbepoetin alfa Q2W — matched weekly exposure, flatter profile
##      "4. Darbepoetin alfa Q2W" =
##        run(c(nd, dar, list(ESA_WK_UKG = 450)),
##            ev(amt = 4.0, cmt = "ESA_SC", ii = 14, addl = floor(end_d/14))),
##
##      # 5. Methoxy-PEG-epoetin beta Q4W — flattest profile of the three
##      "5. Methoxy-PEG-epoetin beta Q4W" =
##        run(c(nd, mpg, list(ESA_WK_UKG = 450)),
##            ev(amt = 7.0, cmt = "ESA_SC", ii = 28, addl = floor(end_d/28))),
##
##      # 6. Epoetin + proactive high-dose IV iron in HD (PIVOTAL strategy;
##      #    iron sucrose, so FCM_FLAG = 0 and there is no FGF23 signal)
##      "6. Epoetin + proactive IV iron (HD, PIVOTAL)" =
##        run(c(hd, epo, list(ESA_WK_UKG = 300, FCM_FLAG = 0)),
##            ev(amt = 1.0, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw)) +
##            ev(amt = 400, cmt = "FE_IV",  ii = 28,  addl = floor(end_d/28))),
##
##      # 7. Roxadustat 200 mg PO TIW (dialysis)
##      "7. Roxadustat TIW (dialysis)" =
##        run(c(hd, rox),
##            ev(amt = 2.0, cmt = "PHI_GUT", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 8. Daprodustat PO daily (non-dialysis, ASCEND-ND-like)
##      "8. Daprodustat daily (non-dialysis)" =
##        run(c(nd, dap),
##            ev(amt = 4.0, cmt = "PHI_GUT", ii = 1, addl = end_d - 1)),
##
##      # 9. Oral ferrous sulfate 65 mg elemental daily, no ESA
##      "9. Oral iron alone (hepcidin-capped)" =
##        run(nd, ev(amt = 65, cmt = "FE_GUT", ii = 1, addl = end_d - 1)),
##
##      # 10. Inflammatory hyporesponder at the SAME ESA dose as scenario 3
##      "10. Inflammatory hyporesponder, matched ESA dose" =
##        run(c(nd, epo, list(IL6_DRIVE = 4, ESA_WK_UKG = 450)),
##            ev(amt = 1.0, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 11. Same patient, ESA escalated 3-fold (the ERI/hazard trade-off)
##      "11. Inflammatory hyporesponder, ESA escalated 3x" =
##        run(c(nd, epo, list(IL6_DRIVE = 4, ESA_WK_UKG = 1350)),
##            ev(amt = 3.0, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 12. Same patient on roxadustat instead
##      "12. Inflammatory hyporesponder, roxadustat" =
##        run(c(nd, rox, list(IL6_DRIVE = 4)),
##            ev(amt = 1.5, cmt = "PHI_GUT", ii = tiw, addl = floor(end_d/tiw))),
##
##      # 13. Aggressive Hb normalisation (Normal-Hematocrit / CHOIR-like)
##      "13. Hb normalisation overshoot (safety)" =
##        run(c(nd, epo, list(ESA_WK_UKG = 2250)),
##            ev(amt = 5.0, cmt = "ESA_SC", ii = tiw, addl = floor(end_d/tiw)) +
##            ev(amt = 300, cmt = "FE_IV",  ii = 28,  addl = floor(end_d/28))),
##
##      # 14. High-dose ferric carboxymaltose -> FGF23 -> hypophosphatemia
##      "14. High-dose FCM -> FGF23 -> hypophosphatemia" =
##        run(c(nd, list(FCM_FLAG = 1)),
##            ev(amt = 750, cmt = "FE_IV", ii = 7, addl = 1)),
##
##      # 15. ESA interruption at day 120 -> Hb cycling / rebound anemia
##      "15. ESA interruption at day 120 (Hb cycling)" =
##        run(c(nd, epo, list(ESA_WK_UKG = 450)),
##            ev(amt = 1.0, cmt = "ESA_SC", ii = tiw, addl = floor(120/tiw)))
##    ) %>% bind_rows(.id = "scenario")
##  }
##
##  ---------------------------------------------------------------------------
##  What each scenario is meant to reproduce
##  ---------------------------------------------------------------------------
##   1     Hb drifts down as eGFR falls: the REP pool shrinks, EPO stays
##         "inappropriately normal" (~9 mIU/mL at Hb 9.4), hepcidin creeps up as
##         renal clearance is lost, TSAT sags.
##   2-5   Three ESA molecules on three schedules. A MAINTENANCE dose lands in
##         the KDIGO 10-11.5 g/dL band; the same molecule at a CORRECTION dose
##         held open-loop for a year overshoots past 13 g/dL — which is exactly
##         why real practice titrates. All of them unmask FUNCTIONAL iron
##         deficiency: ERFE rises, hepcidin falls ~35-45%, ferritin drains from
##         ~147 to ~90-105 ng/mL while TSAT stays flat. That emergent store-drain
##         at constant TSAT is the model's central iron-kinetic behaviour.
##   6     Proactive IV iron keeps the store term high, so the same ESA exposure
##         gets to target sooner; ferritin climbs to ~800 ng/mL (PIVOTAL's
##         proactive arm ran high too) and the thrombotic-hazard slope stays
##         below the Hb-normalisation arm.
##   7-8   HIF-PHIs raise Hb with EPO peaks of only ~3-5x baseline (vs ~10x for
##         ESA), drop hepcidin hardest of any arm (60 -> ~18-30 ng/mL), raise
##         TIBC, and lower LDL-C by ~8-14% — the qualitative fingerprint that
##         separates them from ESAs in the trials.
##   9     Oral iron alone loads STORES (ferritin 147 -> ~430) without fixing Hb,
##         because absorption is hepcidin-gated and hepcidin rises with the
##         stores it creates. The clinical futility of oral iron in advanced CKD.
##   10-12 The hyporesponsiveness triad. At a MATCHED ESA dose the inflamed
##         patient gains less Hb (EPOR-JAK2-STAT5 transduction is attenuated by
##         epor_at). Escalating the dose 3x does buy Hb, but the cumulative
##         thrombotic hazard roughly doubles — the ERI trade-off. The HIF-PHI arm
##         works through a partly different route (hepcidin suppression + HIF
##         transcription) and does not need the escalation.
##   13    Hb overshoot to ~15.7 g/dL: viscosity, MAP and ESA terms drive the
##         cumulative thrombotic hazard ~4x the maintenance arm. The model's
##         rendering of the Normal-Hematocrit / CHOIR / TREAT result.
##   14    FGF23 rises with processed FCM and phosphate falls to ~1.6 mg/dL
##         within 2 weeks, recovering over 6-8 weeks. Setting FCM_FLAG = 0
##         (iron isomaltoside / iron sucrose) abolishes the signal.
##   15    Stopping the ESA lets Hb fall with the RBC-lifespan time constant
##         (12.0 -> 11.0 g/dL over 8 weeks, back to baseline by ~9 months) while
##         hepcidin REBOUNDS above baseline as ERFE collapses. The pharmacology
##         behind Hb cycling.
##
##  ---------------------------------------------------------------------------
##  A closed-loop KDIGO titration controller (what real practice does)
##  ---------------------------------------------------------------------------
##  The scenarios above are open-loop. To titrate, step the simulation in
##  4-week blocks and carry the state forward with init():
##
##  ACKD_titrate <- function(dose0 = 0.5, target = c(10, 11.5), blocks = 13,
##                           block_d = 28, p = list()) {
##    m <- mod %>% param(p); st <- NULL; dose <- dose0; out <- list()
##    for (b in seq_len(blocks)) {
##      if (!is.null(st)) m <- m %>% init(st)
##      e <- if (dose > 0) ev(amt = dose, cmt = "ESA_SC", ii = 7/3,
##                            addl = floor(block_d/(7/3))) else ev(amt = 0, cmt = "ESA_SC")
##      r  <- m %>% mrgsim(events = e, end = block_d, delta = 1) %>% as_tibble()
##      hb <- tail(r$Hemoglobin, 1)
##      # KDIGO-style +-25% steps, hold above the ceiling
##      dose <- if (hb > target[2]) max(0, dose * 0.75) else
##              if (hb < target[1]) dose * 1.25 else dose
##      st <- as.list(tail(r, 1))[names(init(mod))]
##      out[[b]] <- r %>% mutate(block = b, dose_au = dose)
##    }
##    bind_rows(out)
##  }
##
##  ---------------------------------------------------------------------------
##  Sensitivity handles worth sweeping
##  ---------------------------------------------------------------------------
##   BLUNT          — how much of the renal hypoxic drive survives; the single
##                    biggest determinant of endogenous EPO in CKD.
##   IL6_DRIVE      — inflammation; drives hepcidin, erythroblast apoptosis and
##                    (via KIL6_EPOR) the ESA hyporesponsiveness itself.
##   HEPC_BASE      — the ferroportin operating point, i.e. how much of the
##                    recycled ~11 mg/day of iron actually reaches the marrow.
##   KM_TSAT        — steepness of the iron gate; controls how quickly an ESA
##                    response saturates into functional iron deficiency.
##   MOB_MAX        — mobilisable store capacity; too low and full stores cannot
##                    rescue the erythron (loaded ferritin with a starved marrow).
##   LS0 / URE      — RBC lifespan; sets the lag on every Hb response and the
##                    obligate iron turnover (~11 mg/day at baseline).
##   EMAX_EPO       — ceiling of the marrow's expansion capacity (~1.6x here).
##
##  ---------------------------------------------------------------------------
##  Known simplifications — read before drawing conclusions
##  ---------------------------------------------------------------------------
##   * BASELINE IS PINNED. [MAIN] back-calculates KIN_PROG so that EVERY virtual
##     patient starts at BASE_HB, including the inflamed one. That is convenient
##     but it means IL6_DRIVE does NOT lower the starting Hb; inflammation shows
##     up as a blunted Hb gain per unit ESA (KIL6_EPOR) and a tighter iron gate,
##     not as a worse presenting anemia. Compare hyporesponders at MATCHED DOSE
##     (scenario 10 vs 3), never by their proportional reserve.
##   * ESA and HIF-PHI exposures are in dose-proportional au, not mg/mL, and the
##     PK is first-order with no target-mediated (EPOR) disposition.
##   * A single lumped HIF activity stands in for HIF-1alpha and HIF-2alpha in
##     kidney, liver and gut; isoform- and tissue-specific programs are not
##     separated, so the model cannot speak to isoform-selective agents.
##   * Hepcidin, ERFE and IL-6 are single well-mixed pools — no hepatic/marrow
##     compartmentalisation, no diurnal rhythm.
##   * Oral-iron absorption uses FMAX_ABS = 0.28, a figure from iron-deficient
##     healthy volunteers; real CKD patients absorb less, so scenario 9 probably
##     OVERSTATES how much store loading oral iron achieves.
##   * The thrombotic hazard is a mechanistic index for RANKING arms, not a
##     calibrated absolute event rate. Do not read it as events/100 py.
##   * Transferrin saturation is bounded below 100% by an overflow term
##     (KOVER_DEP), not by explicit transferrin binding stoichiometry.
