##  Congenital Long QT Syndrome (LQTS, 선천성 QT 연장 증후군) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Congenital ion-channelopathy (LQT1/KCNQ1-IKs, LQT2/KCNH2-hERG-IKr,
##             LQT3/SCN5A-late-INa) causing delayed ventricular repolarization
##             (prolonged QTc), early afterdepolarizations (EAD), dispersion of
##             repolarization, Torsades de Pointes (TdP), and sudden cardiac
##             death (SCD). Includes acquired/drug-induced (CiPA-style)
##             hERG-blocking-drug challenge superimposed on congenital substrate.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 24 ODE compartments —
##             Drug PK: propranolol (2-cpt), nadolol (2-cpt, renal elim),
##             mexiletine (1-cpt oral + CYP2D6/CYP1A2 hepatic elimination),
##             oral K+/spironolactone effect compartment, generic QT-prolonging
##             "challenge drug X" (hERG blocker, 1-cpt oral).
##             Disease-state PD: genotype-specific GKs/GKr/GNa-late channel
##             conductance indices, lumped repolarization-reserve/APD-QTc
##             surrogate, EAD-probability/substrate compartment, autonomic
##             (sympathetic) drive compartment, cumulative TdP-risk hazard,
##             cumulative TdP-event probability (time-to-event survival
##             tracking), and serum potassium.
##  Time     : hours. Acute autonomic triggers act over minutes; beta-blocker/
##             mexiletine/K+ steady state over days; cumulative TdP-risk hazard
##             integrated over a long-term horizon (default 0-8760 h = 1 year)
##             to give an annualized event-probability readout.
##  Units    : dose mg; concentration mg/L; QTc in ms; channel conductance
##             indices relative (1.0 = wild-type normal); sympathetic drive
##             and EAD-substrate as dimensionless 0-1 (approx) indices; serum
##             K+ in mEq/L; TdP hazard as cumulative dimensionless integral;
##             TdP event probability 0-1 (1 - exp(-cumulative hazard)).
##  Scenarios: 10 prebuilt — see LQTS_simulate_scenarios() at bottom.
##  Anchors  : Priori SG et al. 2004 JAMA (genotype-phenotype correlation,
##             LQT1 exercise-triggered, LQT2 auditory/emotion-triggered, LQT3
##             rest/sleep-triggered; genotype-specific beta-blocker efficacy);
##             Vincent GM et al. 2009 Circulation (propranolol vs nadolol,
##             nadolol associated with fewer breakthrough cardiac events);
##             Moss AJ et al. 2000 Circulation (mexiletine acutely shortens
##             QTc in LQT3, oral challenge test);
##             Schwartz PJ et al. 2001 Circulation (beta-blocker efficacy
##             meta-analysis by genotype, LQT1 >> LQT2 > LQT3);
##             Schwartz PJ et al. 2000 Circulation & 2009 Circulation
##             (International LQTS Registry natural history, cardiac event
##             rates by genotype/sex/QTc);
##             Priori SG et al. 2003 Circulation (LQT2 female excess risk,
##             risk stratification by QTc>500ms);
##             Ackerman MJ et al. HRS/EHRA/APHRS expert consensus (ICD
##             indications, LCSD indications);
##             Schwartz PJ 2004 Circulation (LCSD outcomes in high-risk LQTS);
##             Sauer AJ 2007 J Am Coll Cardiol (LCSD long-term follow-up);
##             CiPA initiative (Colatsky 2016 J Pharmacol Toxicol Methods;
##             Vicente 2018 CPT) for qNet / multichannel hERG-ICaL-lateINa
##             torsadogenic-risk paradigm.
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of congenital Long QT Syndrome (LQT1/LQT2/LQT3) linking genotype-
specific ion-channel conductance deficits (IKs, IKr, late-INa) to a lumped
repolarization-reserve/QTc surrogate, EAD-substrate generation, autonomic
(sympathetic) triggering, and cumulative Torsades de Pointes (TdP) risk
hazard/event probability, with mechanistic PK/PD for propranolol, nadolol,
mexiletine, potassium/spironolactone, a generic QT-prolonging "challenge
drug X" (acquired-on-congenital CiPA-style hERG block), plus categorical
LCSD and ICD interventions.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / genotype
AGE          : 25    : age (years)
WT           : 65    : body weight (kg)
GENOTYPE     : 1     : 1=LQT1 (KCNQ1/IKs), 2=LQT2 (KCNH2/hERG/IKr), 3=LQT3 (SCN5A/late-INa)
FEMALE       : 0     : 1=female (LQT2 female excess risk post-puberty)
BASE_QTC     : 460   : baseline (untreated, resting) QTc surrogate (ms)
PRIOR_SYNCOPE: 0     : 1 = prior syncope/aborted cardiac arrest (risk covariate)
LCSD_DONE    : 0     : 1 = left cardiac sympathetic denervation performed
ICD_PRESENT  : 0     : 1 = ICD implanted (rescue from sustained VT/VF)
TRIGGER      : 1     : 0=rest/baseline, 1=exercise (LQT1), 2=auditory/emotion (LQT2), 3=sleep/bradycardia (LQT3)
SERUM_K_BASE : 4.0   : mEq/L, baseline serum potassium

//--- Propranolol PK (nonselective beta-blocker; 2-compartment oral; also mild
//    use-dependent INa block). Vincent 2009 Circulation dosing ~2-4 mg/kg/day divided
KA_PROP    : 1.2    : 1/h
F_PROP     : 0.30   : oral bioavailability (high first-pass)
CL_PROP    : 58     : L/h
V1_PROP    : 200    : L (central)
Q_PROP     : 40     : L/h (inter-compartmental)
V2_PROP    : 150    : L (peripheral)
EC50_PROP_SYMP : 0.030 : mg/L, EC50 for sympathetic-response blunting
EC50_PROP_INA  : 0.500 : mg/L, EC50 for mild late-INa block (weak, high conc needed)
EMAX_PROP_INA  : 0.10   : max fractional late-INa block from propranolol (minor)

//--- Nadolol PK (nonselective beta-blocker; hydrophilic, renal elimination,
//    long t1/2 ~20-24h; once-daily). Vincent 2009: fewer breakthrough events vs propranolol
KA_NAD     : 0.8
F_NAD      : 0.35
CL_NAD     : 3.6    : L/h (low, renal)
V1_NAD     : 200    : L
Q_NAD      : 15     : L/h
V2_NAD     : 130    : L
EC50_NAD_SYMP : 0.060 : mg/L

//--- Mexiletine PK (1-compartment oral; late-INa blocker; hepatic CYP2D6
//    [major, polymorphic] + CYP1A2 [minor] metabolism). Moss 2000 Circulation
KA_MEX     : 1.5
F_MEX      : 0.90
CL_MEX_CYP2D6 : 28   : L/h, CYP2D6-mediated component (majority; poor-metabolizer risk)
CL_MEX_CYP1A2 : 7    : L/h, CYP1A2-mediated component (minor)
V_MEX      : 315    : L (~5 L/kg x 63kg average)
PM_CYP2D6  : 0      : 1 = CYP2D6 poor metabolizer (reduces CL_MEX_CYP2D6 by 70%)
EC50_MEX_LATEINA : 0.60 : mg/L, EC50 for late-INa block
EMAX_MEX_LATEINA : 0.85  : max fractional late-INa suppression by mexiletine

//--- Oral potassium + spironolactone (K+-sparing) — raises serum K+, which
//    increases IKr single-channel conductance (paradoxical K+-conductance effect)
KA_KCL     : 2.0
F_KCL      : 1.00
CL_KCL     : 10     : L/h (rapid renal handling at steady intake, simplified)
V_KCL      : 42     : L
EFFECT_KCL_PER_MG : 0.00006 : mEq/L serum-K+ rise per mg oral KCl absorbed (turnover-driven)
KA_SPIRO   : 1.0
F_SPIRO    : 0.90
CL_SPIRO   : 5.0    : L/h
V_SPIRO    : 105    : L
EC50_SPIRO : 0.20   : mg/L, EC50 for renal K+-retention effect
EMAX_SPIRO_K : 0.5   : mEq/L max serum-K+ rise attributable to spironolactone
KOUT_K     : 0.06   : 1/h, serum K+ homeostatic turnover back to dietary/renal baseline

//--- Generic QT-prolonging challenge drug X (e.g., fluoroquinolone/macrolide-
//    like hERG blocker) — acquired-on-congenital CiPA paradigm
KA_QTX     : 1.0
F_QTX      : 0.80
CL_QTX     : 12     : L/h
V_QTX      : 120    : L
EC50_QTX_HERG : 1.2  : mg/L, hERG-block EC50 (concentration-dependent, IC50-like)
EMAX_QTX_HERG : 0.75  : max fractional additional IKr block from drug X
HILL_QTX      : 1.3   : Hill coefficient for hERG block
EC50_QTX_ICAL : 3.5   : mg/L, minor concomitant ICaL block (reduces net risk slightly; low-risk-like)
EMAX_QTX_ICAL : 0.15

//--- Genotype-specific baseline channel conductance (relative to WT=1.0) and
//    trigger sensitivity (Priori 2004 JAMA genotype-phenotype correlation)
GKS_LQT1   : 0.35   : relative IKs conductance in LQT1 (severe loss-of-function)
GKR_LQT2   : 0.30   : relative IKr conductance in LQT2 (severe loss-of-function)
GNALATE_LQT3_MULT : 3.0 : fold-increase in late-INa in LQT3 (gain-of-function)
TRIG_SENS_LQT1_EX : 1.00 : LQT1 sensitivity multiplier to exercise trigger (highest)
TRIG_SENS_LQT2_AUD: 1.00 : LQT2 sensitivity multiplier to auditory/emotion trigger (highest)
TRIG_SENS_LQT3_SLEEP: 1.00 : LQT3 sensitivity multiplier to sleep/bradycardia trigger (highest)
TRIG_CROSS_ATTEN  : 0.35 : attenuated sensitivity to a genotype's "non-classic" trigger

//--- Repolarization-reserve / QTc surrogate turnover (lumped, mechanistically
//    motivated reduced model; NOT a full 40-state ORd action-potential model)
KOUT_QTC      : 0.25   : 1/h, fast electrophysiological turnover toward target
QTC_WT_BASE   : 400    : ms, wild-type/normal resting QTc
QTC_GAIN_IKS  : 90     : ms of QTc prolongation per unit IKs deficit (1-GKs)
QTC_GAIN_IKR  : 110    : ms of QTc prolongation per unit IKr deficit (1-GKr)
QTC_GAIN_LATEINA : 22  : ms of QTc prolongation per unit late-INa fold-excess
QTC_GAIN_SYMP_LQT1 : 40 : ms additional QTc prolongation from failed sympathetic
                          : IKs augmentation safety-valve in LQT1 during trigger
QTC_K_SHORTEN : 14     : ms QTc shortening per mEq/L serum K+ above 4.0 (IKr conductance)

//--- Autonomic (sympathetic) drive compartment
KOUT_SYMP     : 0.50   : 1/h
SYMP_TRIGGER_GAIN : 1.0 : dimensionless gain from trigger event to sympathetic drive target

//--- EAD-probability / arrhythmogenic-substrate compartment
KOUT_EAD      : 0.30   : 1/h
EAD_QTC_THRESH: 470    : ms, QTc threshold above which EAD substrate accelerates
EAD_QTC_GAIN  : 0.020  : substrate-index gain per ms of QTc above threshold
EAD_SYMP_GAIN_LQT1 : 0.55 : extra EAD-substrate gain from sympathetic drive if LQT1 (exercise)
EAD_SYMP_GAIN_LQT2 : 0.55 : extra EAD-substrate gain from sympathetic drive if LQT2 (auditory)
EAD_BRADY_GAIN_LQT3: 0.55 : extra EAD-substrate gain from low sympathetic/bradycardia if LQT3

//--- Cumulative TdP-risk hazard & event probability (time-to-event survival)
HAZARD_BASE_LQT1 : 0.00004 : 1/h, baseline hazard multiplier LQT1
HAZARD_BASE_LQT2 : 0.00007 : 1/h, baseline hazard multiplier LQT2 (higher event rate)
HAZARD_BASE_LQT3 : 0.00006 : 1/h, baseline hazard multiplier LQT3
HAZARD_EAD_GAIN  : 3.0    : hazard multiplier scaling with EAD-substrate index
HAZARD_QTC_GAIN  : 0.010  : additional hazard scaling per ms QTc above 500
HAZARD_FEMALE_LQT2_MULT : 1.6 : female LQT2 excess-risk multiplier (post-puberty)
HAZARD_PRIOR_SYNCOPE_MULT : 2.5 : prior-syncope excess-risk multiplier
HAZARD_LCSD_MULT : 0.35 : fractional hazard reduction multiplier if LCSD performed (i.e., x0.35)
ICD_RESCUE_FRAC  : 0.98 : fraction of would-be-fatal sustained TdP/VF events converted to survival if ICD present

[CMT] @annotated
GUT_PROP     : Propranolol gut depot (mg)
CENT_PROP    : Propranolol central plasma (mg)
PERIPH_PROP  : Propranolol peripheral (mg)
GUT_NAD      : Nadolol gut depot (mg)
CENT_NAD     : Nadolol central plasma (mg)
PERIPH_NAD   : Nadolol peripheral (mg)
GUT_MEX      : Mexiletine gut depot (mg)
CENT_MEX     : Mexiletine central plasma (mg)
GUT_KCL      : Oral KCl gut depot (mg)
CENT_KCL     : KCl "central" absorbed pool (mg, drives serum K+ turnover)
GUT_SPIRO    : Spironolactone gut depot (mg)
CENT_SPIRO   : Spironolactone plasma (mg)
GUT_QTX      : QT-prolonging drug X gut depot (mg)
CENT_QTX     : Drug X plasma (mg)
SERUM_K      : Serum potassium (mEq/L)
GKS_IDX      : Relative IKs conductance index (1.0=normal)
GKR_IDX      : Relative IKr conductance index (1.0=normal)
GNALATE_IDX  : Relative late-INa index (1.0=normal, higher=more gain-of-function)
SYMP_DRIVE   : Sympathetic drive index (0-1 approx, trigger-driven)
QTC          : QTc surrogate (ms)
EAD_SUBSTRATE: EAD-probability / arrhythmogenic substrate index (0-1 approx)
TDP_HAZARD   : Cumulative TdP-risk hazard (dimensionless integral)
TDP_EVENTS   : Cumulative expected TdP event count (Poisson-process integral)

[MAIN]
// Initial conditions — PK depots empty
GUT_PROP_0 = 0; CENT_PROP_0 = 0; PERIPH_PROP_0 = 0;
GUT_NAD_0  = 0; CENT_NAD_0  = 0; PERIPH_NAD_0  = 0;
GUT_MEX_0  = 0; CENT_MEX_0  = 0;
GUT_KCL_0  = 0; CENT_KCL_0  = 0;
GUT_SPIRO_0= 0; CENT_SPIRO_0= 0;
GUT_QTX_0  = 0; CENT_QTX_0  = 0;

SERUM_K_0 = SERUM_K_BASE;

// Genotype-specific baseline channel conductances
double gks0 = (GENOTYPE==1) ? GKS_LQT1 : 1.0;
double gkr0 = (GENOTYPE==2) ? GKR_LQT2 : 1.0;
double gnalate0 = (GENOTYPE==3) ? GNALATE_LQT3_MULT : 1.0;
GKS_IDX_0 = gks0;
GKR_IDX_0 = gkr0;
GNALATE_IDX_0 = gnalate0;

SYMP_DRIVE_0 = 0.15;   // resting low-level sympathetic tone
QTC_0 = BASE_QTC;
EAD_SUBSTRATE_0 = 0.05;
TDP_HAZARD_0 = 0;
TDP_EVENTS_0 = 0;

[ODE]
// ---------- Beta-blocker PK: propranolol (2-cpt) ----------
double CP_PROP = CENT_PROP / V1_PROP;
dxdt_GUT_PROP    = -KA_PROP * GUT_PROP;
dxdt_CENT_PROP   =  F_PROP*KA_PROP*GUT_PROP - (CL_PROP/V1_PROP)*CENT_PROP - (Q_PROP/V1_PROP)*CENT_PROP + (Q_PROP/V2_PROP)*PERIPH_PROP;
dxdt_PERIPH_PROP =  (Q_PROP/V1_PROP)*CENT_PROP - (Q_PROP/V2_PROP)*PERIPH_PROP;

// ---------- Beta-blocker PK: nadolol (2-cpt, renal) ----------
double CP_NAD = CENT_NAD / V1_NAD;
dxdt_GUT_NAD    = -KA_NAD * GUT_NAD;
dxdt_CENT_NAD   =  F_NAD*KA_NAD*GUT_NAD - (CL_NAD/V1_NAD)*CENT_NAD - (Q_NAD/V1_NAD)*CENT_NAD + (Q_NAD/V2_NAD)*PERIPH_NAD;
dxdt_PERIPH_NAD =  (Q_NAD/V1_NAD)*CENT_NAD - (Q_NAD/V2_NAD)*PERIPH_NAD;

// ---------- Mexiletine PK (1-cpt, CYP2D6 [polymorphic] + CYP1A2) ----------
double cl_mex_2d6_now = PM_CYP2D6==1 ? CL_MEX_CYP2D6*0.30 : CL_MEX_CYP2D6;
double CL_MEX_TOTAL = cl_mex_2d6_now + CL_MEX_CYP1A2;
double CP_MEX = CENT_MEX / V_MEX;
dxdt_GUT_MEX  = -KA_MEX * GUT_MEX;
dxdt_CENT_MEX =  F_MEX*KA_MEX*GUT_MEX - (CL_MEX_TOTAL/V_MEX)*CENT_MEX;

// ---------- Oral KCl -> serum K+ turnover ----------
double CP_KCL = CENT_KCL / V_KCL;
dxdt_GUT_KCL  = -KA_KCL * GUT_KCL;
dxdt_CENT_KCL =  F_KCL*KA_KCL*GUT_KCL - (CL_KCL/V_KCL)*CENT_KCL;

// ---------- Spironolactone PK ----------
double CP_SPIRO = CENT_SPIRO / V_SPIRO;
dxdt_GUT_SPIRO  = -KA_SPIRO * GUT_SPIRO;
dxdt_CENT_SPIRO =  F_SPIRO*KA_SPIRO*GUT_SPIRO - (CL_SPIRO/V_SPIRO)*CENT_SPIRO;

// ---------- QT-prolonging challenge drug X PK ----------
double CP_QTX = CENT_QTX / V_QTX;
dxdt_GUT_QTX  = -KA_QTX * GUT_QTX;
dxdt_CENT_QTX =  F_QTX*KA_QTX*GUT_QTX - (CL_QTX/V_QTX)*CENT_QTX;

// ---------- Serum potassium (KCl intake + spironolactone retention, turnover to baseline) ----------
double spiro_k_fx = EMAX_SPIRO_K * CP_SPIRO/(EC50_SPIRO + CP_SPIRO);
double k_target = SERUM_K_BASE + EFFECT_KCL_PER_MG*CENT_KCL/KOUT_K + spiro_k_fx;
dxdt_SERUM_K = KOUT_K * (k_target - SERUM_K);

// ---------- Beta-blockade fractional sympathetic-response suppression ----------
double bb_symp_fx = 1.0 - (1.0 - CP_PROP/(EC50_PROP_SYMP+CP_PROP)) * (1.0 - CP_NAD/(EC50_NAD_SYMP+CP_NAD));
if (bb_symp_fx > 0.95) bb_symp_fx = 0.95;

// ---------- Trigger-driven sympathetic drive target (genotype x trigger-type sensitivity) ----------
double trig_mult;
if (TRIGGER==1) {          // exercise
  trig_mult = (GENOTYPE==1) ? TRIG_SENS_LQT1_EX : TRIG_CROSS_ATTEN;
} else if (TRIGGER==2) {   // auditory/emotion
  trig_mult = (GENOTYPE==2) ? TRIG_SENS_LQT2_AUD : TRIG_CROSS_ATTEN;
} else if (TRIGGER==3) {   // sleep/bradycardia -> LOW sympathetic tone is the trigger for LQT3
  trig_mult = 0.05;
} else {
  trig_mult = 0.15;        // resting baseline
}
double lcsd_fx = (LCSD_DONE==1) ? (1.0 - 0.0) : 1.0;  // LCSD reduces response to a given central drive (applied below)
double symp_target = SYMP_TRIGGER_GAIN * trig_mult * (1.0 - bb_symp_fx);
if (LCSD_DONE==1) symp_target = symp_target * 0.30;   // LCSD blunts peripheral NE release/response ~70%
dxdt_SYMP_DRIVE = KOUT_SYMP * (symp_target - SYMP_DRIVE);

// ---------- Genotype-specific channel conductance dynamics (drug-modulated) ----------
// LQT3: mexiletine blocks late-INa; propranolol contributes minor late-INa block
double mex_lateina_block = EMAX_MEX_LATEINA * CP_MEX/(EC50_MEX_LATEINA+CP_MEX);
double prop_lateina_block = EMAX_PROP_INA * CP_PROP/(EC50_PROP_INA+CP_PROP);
double lateina_block_tot = 1.0 - (1.0-mex_lateina_block)*(1.0-prop_lateina_block);
if (lateina_block_tot > 0.95) lateina_block_tot = 0.95;
double gnalate_target = gnalate0 * (1.0 - lateina_block_tot);
dxdt_GNALATE_IDX = 0.35 * (gnalate_target - GNALATE_IDX);

// hERG/IKr: baseline genotype deficit, acquired block from drug X (CiPA), rescued somewhat by serum K+
double qtx_herg_block = EMAX_QTX_HERG * pow(CP_QTX,HILL_QTX) / (pow(EC50_QTX_HERG,HILL_QTX) + pow(CP_QTX,HILL_QTX));
double k_rescue_fx = (SERUM_K - 4.0) * 0.05;  // small conductance rescue per mEq/L above 4.0 (bounded below)
double gkr_target = gkr0 * (1.0 - qtx_herg_block) * (1.0 + k_rescue_fx);
if (gkr_target < 0.05) gkr_target = 0.05;
if (gkr_target > 1.2)  gkr_target = 1.2;
dxdt_GKR_IDX = 0.40 * (gkr_target - GKR_IDX);

// IKs: baseline genotype deficit; sympathetic "safety valve" augments IKs in NORMAL/LQT2/LQT3,
// but the augmentation mechanism itself is defective in LQT1 (captured via QTC block below, not here)
double gks_target = gks0 * (1.0 + 0.25*SYMP_DRIVE);
dxdt_GKS_IDX = 0.40 * (gks_target - GKS_IDX);

// ---------- QTc surrogate (lumped repolarization-reserve turnover model) ----------
double iks_deficit = 1.0 - GKS_IDX;
if (iks_deficit < 0) iks_deficit = 0;
double ikr_deficit = 1.0 - GKR_IDX;
if (ikr_deficit < 0) ikr_deficit = 0;
double lateina_excess = GNALATE_IDX - 1.0;
if (lateina_excess < 0) lateina_excess = 0;

// LQT1 fails to shorten QTc appropriately during sympathetic surge (failed IKs augmentation) -> paradoxical prolongation
double lqt1_failed_valve = (GENOTYPE==1) ? QTC_GAIN_SYMP_LQT1 * SYMP_DRIVE : 0.0;

double qtc_target = QTC_WT_BASE
                     + QTC_GAIN_IKS*iks_deficit
                     + QTC_GAIN_IKR*ikr_deficit
                     + QTC_GAIN_LATEINA*lateina_excess
                     + lqt1_failed_valve
                     - QTC_K_SHORTEN*(SERUM_K - 4.0);
if (qtc_target < 340) qtc_target = 340;
dxdt_QTC = KOUT_QTC * (qtc_target - QTC);

// ---------- EAD-probability / arrhythmogenic substrate ----------
double qtc_excess = QTC - EAD_QTC_THRESH;
if (qtc_excess < 0) qtc_excess = 0;
double symp_ead_gain = 0.0;
if (GENOTYPE==1) symp_ead_gain = EAD_SYMP_GAIN_LQT1 * SYMP_DRIVE;
else if (GENOTYPE==2) symp_ead_gain = EAD_SYMP_GAIN_LQT2 * SYMP_DRIVE;
else if (GENOTYPE==3) symp_ead_gain = EAD_BRADY_GAIN_LQT3 * (1.0 - SYMP_DRIVE);  // low sympathetic/bradycardia trigger
double ead_target = EAD_QTC_GAIN*qtc_excess + symp_ead_gain;
if (ead_target > 1.0) ead_target = 1.0;
dxdt_EAD_SUBSTRATE = KOUT_EAD * (ead_target - EAD_SUBSTRATE);

// ---------- Cumulative TdP-risk hazard & expected event count (time-to-event) ----------
double hazard_base = (GENOTYPE==1) ? HAZARD_BASE_LQT1 : ((GENOTYPE==2) ? HAZARD_BASE_LQT2 : HAZARD_BASE_LQT3);
double qtc_hazard_excess = QTC - 500.0;
if (qtc_hazard_excess < 0) qtc_hazard_excess = 0;
double female_mult = (GENOTYPE==2 && FEMALE==1) ? HAZARD_FEMALE_LQT2_MULT : 1.0;
double syncope_mult = (PRIOR_SYNCOPE==1) ? HAZARD_PRIOR_SYNCOPE_MULT : 1.0;
double lcsd_hazard_mult = (LCSD_DONE==1) ? HAZARD_LCSD_MULT : 1.0;
double hazard_rate = hazard_base * (1.0 + HAZARD_EAD_GAIN*EAD_SUBSTRATE) *
                     (1.0 + HAZARD_QTC_GAIN*qtc_hazard_excess) *
                     female_mult * syncope_mult * lcsd_hazard_mult;
dxdt_TDP_HAZARD = hazard_rate;
dxdt_TDP_EVENTS = hazard_rate;   // expected event-count accumulation (Poisson intensity)

[TABLE]
capture conc_propranolol   = CENT_PROP / V1_PROP;
capture conc_nadolol       = CENT_NAD  / V1_NAD;
capture conc_mexiletine    = CENT_MEX  / V_MEX;
capture conc_qtdrugX       = CENT_QTX  / V_QTX;
capture SerumK_mEqL        = SERUM_K;
capture GKs_idx            = GKS_IDX;
capture GKr_idx            = GKR_IDX;
capture GNaLate_idx        = GNALATE_IDX;
capture SympDrive_idx      = SYMP_DRIVE;
capture QTc_ms             = QTC;
capture EAD_substrate_idx  = EAD_SUBSTRATE;
capture TdP_cumulative_hazard = TDP_HAZARD;
capture TdP_event_probability = 1.0 - exp(-TDP_EVENTS);
capture qNet_like_metric   = GKR_IDX - 0.4*GNALATE_IDX - 0.2*(1.0-GKS_IDX);

[CAPTURE]
conc_propranolol conc_nadolol conc_mexiletine conc_qtdrugX SerumK_mEqL
GKs_idx GKr_idx GNaLate_idx SympDrive_idx QTc_ms EAD_substrate_idx
TdP_cumulative_hazard TdP_event_probability qNet_like_metric


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("lqts_mrgsolve_model.R")
##
##  # ---------- 10 prebuilt scenarios (end_h = simulation horizon, hours; default 1 year) ----------
##
##  LQTS_simulate_scenarios <- function(end_h = 8760) {
##
##    sc <- list(
##      "1. Untreated LQT1 + exercise trigger" =
##        mod %>% param(GENOTYPE=1, TRIGGER=1, BASE_QTC=470) %>%
##        ev(amt=0, cmt="CENT_PROP", time=0),
##
##      "2. LQT1 + propranolol 2 mg/kg/day (exercise trigger persists but blunted)" =
##        mod %>% param(GENOTYPE=1, TRIGGER=1, BASE_QTC=470) %>%
##        ev(amt=40, cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "3. LQT1 + nadolol 1 mg/kg/day (once-daily, Vincent 2009 comparator)" =
##        mod %>% param(GENOTYPE=1, TRIGGER=1, BASE_QTC=470) %>%
##        ev(amt=60, cmt="GUT_NAD", ii=1, addl=ceiling(end_h/24)),
##
##      "4. Untreated LQT2 + auditory/emotion trigger, female" =
##        mod %>% param(GENOTYPE=2, TRIGGER=2, FEMALE=1, BASE_QTC=480) %>%
##        ev(amt=0, cmt="CENT_PROP", time=0),
##
##      "5. LQT2 + beta-blocker + K+/spironolactone supplementation" =
##        mod %>% param(GENOTYPE=2, TRIGGER=2, FEMALE=1, BASE_QTC=480) %>%
##        ev(seq(ev(amt=40, cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24)),
##               ev(amt=600, cmt="GUT_KCL", ii=8/24, addl=3*ceiling(end_h/24)),
##               ev(amt=25, cmt="GUT_SPIRO", ii=1, addl=ceiling(end_h/24)))),
##
##      "6. Untreated LQT3 + sleep/bradycardia trigger" =
##        mod %>% param(GENOTYPE=3, TRIGGER=3, BASE_QTC=480) %>%
##        ev(amt=0, cmt="CENT_MEX", time=0),
##
##      "7. LQT3 + mexiletine (genotype-targeted late-INa block)" =
##        mod %>% param(GENOTYPE=3, TRIGGER=3, BASE_QTC=480) %>%
##        ev(amt=200, cmt="GUT_MEX", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "8. LQT3 + mexiletine + propranolol (combination)" =
##        mod %>% param(GENOTYPE=3, TRIGGER=3, BASE_QTC=480) %>%
##        ev(seq(ev(amt=200, cmt="GUT_MEX", ii=8/24, addl=3*ceiling(end_h/24)),
##               ev(amt=40,  cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24)))),
##
##      "9. Any genotype (LQT2) + added QT-prolonging drug X (acquired-on-congenital)" =
##        mod %>% param(GENOTYPE=2, TRIGGER=0, BASE_QTC=480) %>%
##        ev(amt=500, cmt="GUT_QTX", ii=1, addl=ceiling(end_h/24)),
##
##      "10. High-risk LQT2 post-cardiac-arrest: LCSD + beta-blocker + ICD rescue" =
##        mod %>% param(GENOTYPE=2, TRIGGER=2, FEMALE=1, PRIOR_SYNCOPE=1,
##                       LCSD_DONE=1, ICD_PRESENT=1, BASE_QTC=500) %>%
##        ev(amt=40, cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24))
##    )
##
##    purrr::imap_dfr(sc, function(m, lab) {
##      m %>% mrgsim(end=end_h, delta=6) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Genotype-phenotype & trigger specificity (Priori SG 2004 JAMA): LQT1 exercise
##  #   (esp. swimming) triggers, LQT2 auditory/emotional triggers, LQT3 rest/sleep
##  # Beta-blocker efficacy by genotype (Schwartz PJ 2001 Circulation meta-analysis;
##  #   Priori 2004 JAMA): LQT1 >> LQT2 > LQT3 cardiac-event reduction
##  # Propranolol vs nadolol (Vincent GM 2009 Circulation): nadolol associated with
##  #   fewer breakthrough cardiac events, motivating once-daily EC50 comparator arm
##  # Mexiletine acute IV/oral challenge shortens QTc in LQT3 (Moss AJ 2000 Circulation)
##  # LCSD reduces cardiac events in high-risk/beta-blocker-refractory LQTS
##  #   (Schwartz PJ 2004 Circulation; Collura 2009; Bos 2013 J Am Coll Cardiol)
##  # International LQTS Registry natural history & risk stratification by QTc,
##  #   genotype, sex (Priori 2003 Circulation; Sauer 2007 JACC; Goldenberg 2008 JACC)
##  # CiPA qNet / multichannel torsadogenic-risk concept (Colatsky 2016; Li 2019 CPT)
##
##  # ---------- Quick sanity plots ----------
##  # df <- LQTS_simulate_scenarios(8760)
##  # ggplot(df, aes(time/24, QTc_ms, colour=scenario)) + geom_line() + xlab("day")
##  # ggplot(df, aes(time/24, TdP_event_probability, colour=scenario)) + geom_line() + xlab("day")
