##  Chemotherapy-Induced Neutropenia / Febrile Neutropenia (CIN/FN)
##  QSP / PK-PD model
##  ============================================================================
##  Condition : Chemotherapy-induced neutropenia and its clinical consequence,
##              FEBRILE NEUTROPENIA.  The dose-limiting toxicity of essentially
##              every cytotoxic regimen, the commonest oncological emergency,
##              and the reason a large fraction of patients never receive the
##              dose intensity their trial protocol specified.
##
##  Authors   : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine    : mrgsolve (>= 1.5)   —   load with mrgsolve::mread()
##
##  ----------------------------------------------------------------------------
##  THE ORGANISING IDEA
##  ----------------------------------------------------------------------------
##  The absolute neutrophil count is not a state you can dose against, because
##  by the time it moves the event that set it has already happened.  The ANC
##  measured on day 10 was decided by the kill in the proliferating compartment
##  on days 0-2, and everything in between is a DELAY LINE:
##
##      PROL -> TR1 -> TR2 -> TR3(storage) -> CIRC        (Friberg 2002)
##
##      the DELAY (mean transit time MTT)      sets WHEN the nadir arrives
##      the EXPOSURE (slope * Cp)              sets HOW DEEP it goes
##      the FEEDBACK exponent gamma            sets HOW FAST it comes back
##
##  These three are structurally separate parameters.  Nearly every clinical
##  rule about myelosuppression is a consequence of that separation rather than
##  of potency, and the model is arranged so that each rule can be derived
##  rather than asserted:
##
##    * G-CSF cannot raise a nadir that is already committed.  It shortens the
##      delay, slows the clearance of the cells that survive, and empties the
##      storage pool.  That is why its TIMING (24-72 h after chemotherapy, not
##      day 8) determines its effect and its DOSE barely does.
##    * Febrile-neutropenia risk is not a function of nadir depth but of the
##      INTEGRAL of depth over time below the 0.5 x 10^9/L threshold -- so two
##      patients with identical nadirs can carry very different risk.
##    * Everything that raises the measured ANC is not the same as everything
##      that restores host defence.  Corticosteroid demargination, storage-pool
##      release and prolonged circulating survival all raise the NUMBER without
##      adding marrow OUTPUT.  Neutrophil FUNCTION is therefore a separate
##      state, and the model's effective defence is COUNT x FUNCTION.
##    * The clinical decision is never "how low will it go".  It is G-CSF
##      (which preserves dose intensity) versus dose reduction (which does not),
##      so the model carries a tumour compartment purely to price that trade.
##
##  ----------------------------------------------------------------------------
##  SCOPE — 53 ODE compartments
##  ----------------------------------------------------------------------------
##  (a) 15 drug states
##      A_C/A_P1/A_P2      cytotoxic slot A, 3-compartment (taxane, topotecan)
##      B_C/B_P1           cytotoxic slot B, 2-compartment (anthracycline, gem)
##      C_C/C_P1           cytotoxic slot C, 2-compartment (alkylator, platinum)
##      D_C/D_P1           cytotoxic slot D, 2-compartment (etoposide)
##      G_DEP/G_C/G_P/G_E  G-CSF SC depot, central, peripheral, EFFECT site
##      T_C/T_P            trilaciclib
##      DEX                dexamethasone           ABX  levofloxacin
##  (b) 20 haematopoietic states
##      HSC                        quiescent stem pool = marrow reserve
##      PROL/TR1/TR2/TR3/CIRC/MARG neutrophil chain + storage + marginated
##      PROLP/TP1/TP2/TP3/PLT      megakaryocyte chain + platelets
##      PROLE/TE1/TE2/TE3/HB       erythroid chain + haemoglobin
##      TPO                        thrombopoietin (c-Mpl-mediated clearance)
##      FUNC                       neutrophil functional capacity
##      FIB                        irreversible marrow damage
##  (c) 6 host-defence and inflammation states
##      BAR   mucosal barrier integrity      BACT  translocated bacterial load
##      IL6   CRP   TDEV (temperature deviation from 36.8 C)
##  (d) 10 counters and outcome states
##      AUC_A/AUC_B/AUC_C/AUC_D  cytotoxic exposure
##      AUC_G/AUC_T              G-CSF and trilaciclib exposure
##      DSN_H                    hours spent with ANC < 0.5 (the real endpoint)
##      CUMHAZ                   cumulative febrile-neutropenia hazard
##      TUMS/TUMR                drug-sensitive and resistant tumour clones
##
##  ----------------------------------------------------------------------------
##  UNITS
##  ----------------------------------------------------------------------------
##  time            hours; t = 0 is the first chemotherapy administration
##  cytotoxics      umol (amounts), umol/L (concentrations)
##  G-CSF           ng (amounts), ng/mL (concentrations)
##  trilaciclib     mg, mg/L         dexamethasone mg      levofloxacin mg
##  cell counts     10^9/L "virtual concentration", the Friberg convention
##  haemoglobin     g/dL             bacteria  CFU-equivalent (internal scale)
##
##  ----------------------------------------------------------------------------
##  CALIBRATION — two fitted parameters, and a trade-off that decided the rest
##  ----------------------------------------------------------------------------
##  Structural parameters are FIXED at their published values and never fitted:
##    MTT = 89.3 h and gamma = 0.170                     Friberg 2002 (12488418)
##    circulating neutrophil t1/2 = 7.9 h                Dancey 1976 (956397)
##    marginated pool = circulating pool                 Athens 1961 (13684958)
##    docetaxel CL 21.6 L/h/m2, V1 7.4 L/m2              Bruno 1998 (9440742)
##    carboplatin CL(mL/min) = GFR + 25                  Calvert 1989 (2681557)
##    pegfilgrastim: renal clearance ~ 0, cleared by     Roskos 2006 (16809800)
##      receptor-mediated internalisation only           Layton 1989 (2475185)
##
##  FITTED, one parameter per reported number:
##    HFN_BASE  <- febrile neutropenia 1% on pegfilgrastim   Vogel 2005 (15718314)
##    HFN_K     <- febrile neutropenia 17% on placebo        Vogel 2005
##
##  ONLY TWO, and the reason is a trade-off the model cannot escape.  The overall
##  myelotoxic scale SENS_GLOBAL can be set EITHER so that the absolute durations
##  of severe neutropenia reported in the G-CSF trials come out right, OR so that
##  the model tells regimens apart -- not both.  The duration below the 0.5
##  threshold SATURATES in this topology: the recovery limb starts from a floor
##  set by PHI, which does not depend on exposure, and climbs at a rate set by
##  the feedback exponent, so once the proliferative pool is empty at all, extra
##  exposure buys almost no extra duration.  Raising the scale until CAE reaches
##  Crawford 1991's 6-day median puts EVERY combination regimen at a nadir of
##  0.065-0.11 and a DSN of 5.4-6.8 days, i.e. it stops telling AC apart from
##  TAC.  SENS_GLOBAL = 2.0 is therefore chosen for DISCRIMINATION, and the
##  resulting shortfall against the absolute durations is REPORTED rather than
##  tuned away.  Analysis A1 of cin_reference_impl.py lists six such misses:
##
##    CAE without G-CSF, median DSN        6.0 d observed   model -23%
##    CAE + filgrastim d4-17, median DSN   1.0 d observed   model +90%
##    AT + pegfilgrastim, cycle-1 DSN      1.8 d observed   model -100%
##    AT + daily filgrastim, cycle-1 DSN   1.6 d observed   model  -9%
##    intact marrow + filgrastim, ANC peak 4-6 fold         model -62%
##    AC q3w P(FN) vs its guideline band   0.10-0.20        model at the top
##
##  Read together they say something specific: the model exaggerates how much
##  the TIMING of a growth factor matters, and it ranks pegfilgrastim above
##  daily filgrastim where Green 2003 found the opposite.  What survives is
##  everything COMPARATIVE -- change one thing at a time within a fixed regimen
##  and the comparison does not depend on the absolute scale being right.
##
##  ----------------------------------------------------------------------------
##  WHAT THE MODEL IS NOT
##  ----------------------------------------------------------------------------
##  * The nadir DAY is a function of MTT alone, so the model cannot reproduce
##    an agent-specific nadir day (carboplatin's is reported near day 21).
##  * The FN hazard is calibrated to a randomised-trial FN rate; trial rates
##    understate real-world rates (Truong 2016, 26712901), so every absolute
##    P(FN) here is a trial-population number.
##  * The tumour layer is a deliberately thin log-kill.  Its only job is to put
##    a price on dose reduction and cycle delay.  It is not a survival model.
##
##  Disclaimer: research / education / hypothesis generation only.  Not for
##              clinical decisions, prescribing, or regulatory submission.
##  ============================================================================

[PROB]
QSP model of chemotherapy-induced neutropenia posed as a DELAY problem rather
than a potency problem: cytotoxic exposure kills cycling granulocytic
progenitors on days 0-2, a four-stage maturation chain of fixed mean transit
time then determines when the resulting deficit reaches the blood, a weak
power-law feedback determines how fast it recovers, and febrile neutropenia
follows from the INTEGRAL of the deficit against a mucosal barrier the same
drug has just breached.  G-CSF is resolved into five distinct actions, only two
of which touch marrow output; its own clearance is mediated by the neutrophils
it creates, which makes a single fixed dose self-titrating.  Trilaciclib acts
by removing progenitors from the drug-sensitive cycling fraction.  The platelet
and erythroid lineages share the stem pool but run on their own clocks, and a
tumour compartment prices the dose reduction that neutropenia provokes.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient ---------------------------------------------------------------
BSA        : 1.75  : m2, body surface area
WT         : 70    : kg, body weight
GFR        : 90    : mL/min, glomerular filtration rate (carboplatin dosing)
ANC0       : 5.0   : 10^9/L, baseline absolute neutrophil count
PLT0       : 250   : 10^9/L, baseline platelet count
HB0        : 13.5  : g/dL, baseline haemoglobin
RESERVE    : 1.0   : marrow reserve multiplier (< 1 after prior chemo/RT)
SENS       : 1.0   : individual myelotoxic sensitivity multiplier
MTTMULT    : 1.0   : individual multiplier on marrow transit time
GAMMULT    : 1.0   : individual multiplier on the feedback exponent

//--- Neutrophil system (Friberg 2002; FIXED, never fitted) ----------------
MTT_N      : 89.3  : h, mean marrow transit time PROL -> CIRC
GAMMA_N    : 0.170 : feedback exponent on (ANC0/CIRC)
TAU_CIRC   : 7.9   : h, circulating neutrophil half-life
KMARG      : 0.50  : 1/h, circulating <-> marginated exchange
MARG_RATIO : 1.0   : marginated pool / circulating pool at baseline
KREL_MAX   : 0.35  : 1/h, maximal G-CSF-driven release from the storage pool
PHI        : 0.00390625 : = 2^-8, stem-derived share of the mitotic influx
PHI_PE     : 1.0   : platelet/erythroid precursor influx share -- 1, i.e. NO
                   : self-renewal, because megakaryocytes undergo endomitosis
                   : and erythroblasts enucleate; a self-renewing pool with
                   : gain > 1 behind an 8-day feedback delay runs away

//--- Platelet and erythroid systems ---------------------------------------
MTT_P      : 200   : h, megakaryocyte transit time
GAMMA_P    : 1.000 : platelet feedback exponent (proportional; 1/gamma enters
                   : the steady state, and at 0.2 the rebound was unphysiological)
TPO_MAX    : 2.5   : ceiling on the thrombopoietin feedback
FBP_MAX    : 3.0   : ceiling on the megakaryopoietic drive
LIFE_P     : 240   : h, platelet lifespan
MTT_E      : 150   : h, erythroid transit time
GAMMA_E    : 0.600 : erythroid feedback exponent
LIFE_E     : 2880  : h, red-cell lifespan (120 d)

//--- Stem pool / marrow reserve -------------------------------------------
KSELF      : 0.0010  : 1/h, logistic HSC self-renewal (slow, weeks)
KHSC_KILL  : 5.40e-4 : 1/h per unit cycle-corrected stem exposure
KFIB       : 2.97e-5 : 1/h, share of the stem hit that never recovers

//--- Global and class-level potency scales (FITTED) ------------------------
SENS_GLOBAL : 1.0  : global myelotoxic potency scale (fitted to Crawford 1991)
SENS_TAXANE : 1.0  : additional taxane-class scale (fitted to Green 2003)

//--- Cytotoxic slot A (3-compartment): docetaxel / paclitaxel / topotecan --
A_CL   : 37.8  : L/h    A_V1 : 12.95 : L    A_V2 : 43.75 : L    A_V3 : 73.5 : L
A_Q2   : 78.75 : L/h    A_Q3 : 8.75  : L/h
A_SLOPE : 15.9 : L/umol, neutrophil kill slope
A_SLOPEP : 0.076 : ratio, platelet slope / neutrophil slope
A_SLOPEE : 0.35  : ratio, erythroid slope / neutrophil slope
A_FCYC  : 0.90  : cell-cycle DEPENDENCE of the kill (1 = fully protectable)
A_HSC   : 0.55  : relative stem-cell toxicity
A_MUC   : 0.85  : relative mucosal toxicity
A_CTHR  : 0.0   : umol/L, PD threshold (> 0 selects threshold PD, paclitaxel)

//--- Cytotoxic slot B (2-compartment): doxorubicin / gemcitabine ----------
B_CL : 87.5 : L/h   B_V1 : 21.0 : L   B_V2 : 1225 : L   B_Q2 : 66.5 : L/h
B_SLOPE : 23.0 : L/umol
B_SLOPEP : 0.372 : ratio      B_SLOPEE : 0.55 : ratio
B_FCYC : 0.60 : B_HSC : 0.75 : B_MUC : 1.00 : B_CTHR : 0.0 :

//--- Cytotoxic slot C (2-compartment): cyclophosphamide / carboplatin -----
C_CL : 5.6 : L/h    C_V1 : 32.0 : L   C_V2 : 18.0 : L   C_Q2 : 6.0 : L/h
C_SLOPE : 0.0436 : L/umol
C_SLOPEP : 0.796 : ratio      C_SLOPEE : 0.60 : ratio
C_FCYC : 0.40 : C_HSC : 1.00 : C_MUC : 0.55 : C_CTHR : 0.0 :

//--- Cytotoxic slot D (2-compartment): etoposide --------------------------
D_CL : 2.36 : L/h   D_V1 : 14.0 : L   D_V2 : 17.5 : L   D_Q2 : 3.85 : L/h
D_SLOPE : 0.133 : L/umol
D_SLOPEP : 0.646 : ratio      D_SLOPEE : 0.35 : ratio
D_FCYC : 0.92 : D_HSC : 0.40 : D_MUC : 0.60 : D_CTHR : 0.0 :

//--- G-CSF PK.  GTYPE selects the product ---------------------------------
GTYPE   : 2    : 1 = filgrastim, 2 = pegfilgrastim (sets the PK block below)
G_F     : 0.62 : SC bioavailability
G_KA    : 0.033 : 1/h, SC absorption (rate-limiting for pegfilgrastim)
G_V     : 3.2  : L, central volume
G_VP    : 1.4  : L, peripheral volume
G_Q     : 0.20 : L/h, intercompartmental clearance
G_CLLIN : 0.030 : L/h, NON-specific (renal) clearance; ~0 once PEGylated
G_VMAX  : 70000 : ng/h, maximal TARGET-MEDIATED clearance capacity
G_KM    : 25.0 : ng/mL, Michaelis constant of the target-mediated route
G_EC50  : 1.5  : ng/mL, effect-site concentration for half-maximal PD
G_KEO   : 0.0578 : 1/h, effect-compartment equilibration (t1/2 12 h)

//--- G-CSF PD: five separate actions --------------------------------------
EMAX_AMP    : 0.357 : fractional increase in proliferation rate   (FITTED)
EMAX_KTR    : 3.00  : fold increase in transit rate, MTT 89 -> 22 h
EMAX_SURV   : 0.250 : fractional REDUCTION in circulating clearance
EMAX_DEMARG : 0.000 : fractional reduction in margination -- ZERO for G-CSF
EMAX_REL    : 1.00  : scaling of the storage-pool release term
EMAX_FUN    : 0.35  : fractional gain in neutrophil oxidative burst

//--- Trilaciclib (240 mg/m2 IV 30 min before each chemotherapy dose) ------
T_CL : 32.0 : L/h   T_V1 : 28.0 : L   T_Q : 22.0 : L/h   T_V2 : 110 : L
T_IC50 : 0.115 : mg/L, G1 arrest of the cycling HSPC fraction
T_IMAX : 0.760 : maximal fraction of the cycling pool pulled out of cycle

//--- Dexamethasone and levofloxacin --------------------------------------
DEX_CL : 12.0 : L/h    DEX_V : 70.0 : L
DEX_FUNC   : 0.45 : maximal fractional loss of neutrophil function
DEX_DEMARG : 0.85 : maximal fractional reduction in margination
DEX_EC50   : 8.0  : ng/mL equivalent
ABX_CL : 8.0 : L/h     ABX_V : 110 : L
ABX_IMAX : 0.80 : fractional suppression of translocation and growth
ABX_EC50 : 1.2  : mg/L

//--- Neutrophil function --------------------------------------------------
KFUNC : 0.030 : 1/h, recovery of functional capacity

//--- Mucosal barrier ------------------------------------------------------
KHEAL_BAR : 0.0125 : 1/h, epithelial repair (turnover ~3.5 d)
KDAM_BAR  : 0.55   : 1/h per unit mucosal drug effect

//--- Translocation and infection -----------------------------------------
K_TRANS  : 0.020 : CFU-eq/h per unit barrier breach
KGROW_B  : 0.145 : 1/h, net bacterial growth in tissue
BMAX     : 1e4   : CFU-eq, carrying capacity
KKILL_B  : 0.62  : 1/h per (10^9/L of FUNCTIONAL neutrophils)
B50      : 25.0  : CFU-eq, saturation of neutrophil-mediated killing
KCONSUME : 0.020 : 1/h, neutrophil consumption at the site of infection

//--- Inflammation and fever ----------------------------------------------
KIL6_B   : 0.055  : pg/mL/h per CFU-eq
KIL6_OUT : 0.35   : 1/h
KCRP_IN  : 0.020  : mg/L/h per (pg/mL IL-6)
KCRP_OUT : 0.0139 : 1/h  (CRP t1/2 ~50 h)
KT_IN    : 0.0090 : degC/h per (pg/mL IL-6)
KT_OUT   : 0.30   : 1/h

//--- Febrile-neutropenia hazard (FITTED to Vogel 2005) -------------------
HFN_BASE : 1.0e-5 : 1/h, non-neutropenic baseline hazard
HFN_K    : 1.30e-3 : 1/h, hazard scale
HFN_P    : 1.55   : exponent on relative neutropenia depth
HFN_BAR  : 1.00   : weight on the mucosal breach

//--- Tumour (the weakest layer; a price list, not a survival model) ------
TDOUBLE  : 1440  : h, tumour volume doubling time (60 d)
LOGKILL  : 0.850 : natural-log kill per FULL-DOSE cycle
RES_KILL : 0.060 : resistant clone's share of that kill
RES_FRAC0 : 2e-4 : initial resistant fraction
TUM0     : 100   : arbitrary volume units
DOSEMULT : 1.0   : delivered / planned dose multiplier for the current cycle

[CMT] @annotated
A_C   : umol, cytotoxic slot A central
A_P1  : umol, cytotoxic slot A rapid peripheral
A_P2  : umol, cytotoxic slot A deep peripheral
B_C   : umol, cytotoxic slot B central
B_P1  : umol, cytotoxic slot B peripheral
C_C   : umol, cytotoxic slot C central
C_P1  : umol, cytotoxic slot C peripheral
D_C   : umol, cytotoxic slot D central
D_P1  : umol, cytotoxic slot D peripheral
G_DEP : ng, G-CSF subcutaneous depot
G_C   : ng, G-CSF central
G_P   : ng, G-CSF peripheral
G_E   : ng/mL, G-CSF EFFECT compartment
T_C   : mg, trilaciclib central
T_P   : mg, trilaciclib peripheral
DEX   : mg, dexamethasone
ABX   : mg, levofloxacin
HSC   : normalised, quiescent stem pool = marrow reserve
PROL  : 10^9/L, proliferative granulocytic pool (the compartment that is killed)
TR1   : 10^9/L, maturation transit 1
TR2   : 10^9/L, maturation transit 2
TR3   : 10^9/L, marrow STORAGE pool (band and segmented forms)
CIRC  : 10^9/L, CIRCULATING neutrophils -- the measured ANC
MARG  : 10^9/L, MARGINATED neutrophils -- not measured
PROLP : 10^9/L, proliferative megakaryocyte pool
TP1   : 10^9/L, megakaryocyte transit 1
TP2   : 10^9/L, megakaryocyte transit 2
TP3   : 10^9/L, megakaryocyte transit 3
PLT   : 10^9/L, circulating platelets
PROLE : g/dL-equivalent, proliferative erythroid pool
TE1   : g/dL-equivalent, erythroid transit 1
TE2   : g/dL-equivalent, erythroid transit 2
TE3   : g/dL-equivalent, erythroid transit 3
HB    : g/dL, haemoglobin
TPO   : normalised, thrombopoietin (cleared by its own receptor on platelets)
BAR   : fraction, mucosal barrier integrity (1 = intact)
BACT  : CFU-eq, translocated bacterial load
IL6   : pg/mL, interleukin-6
CRP   : mg/L, C-reactive protein
TDEV  : degC, core temperature deviation from 36.8
AUC_A : umol*h/L, slot A exposure
AUC_B : umol*h/L, slot B exposure
AUC_C : umol*h/L, slot C exposure
AUC_D : umol*h/L, slot D exposure
AUC_G : ng*h/mL, G-CSF exposure
AUC_T : mg*h/L, trilaciclib exposure
DSN_H : h, cumulative hours with ANC < 0.5 -- THE endpoint
CUMHAZ : -, cumulative febrile-neutropenia hazard
TUMS  : au, drug-sensitive tumour clone
TUMR  : au, drug-resistant tumour clone
FUNC  : fraction, neutrophil FUNCTIONAL capacity
FIB   : fraction, irreversible marrow damage

[MAIN]
// ---- derived rate constants ------------------------------------------------
double MTTn   = MTT_N * MTTMULT;
double gam    = GAMMA_N * GAMMULT;
double ktrN   = 4.0 / MTTn;
double kcircN = log(2.0) / TAU_CIRC;
double ktrP   = 4.0 / MTT_P;
double kcircP = 1.0 / LIFE_P;          // mean-lifespan convention
double ktrE   = 4.0 / MTT_E;
double kcircE = 1.0 / LIFE_E;

// baseline compartment amounts, from the steady state of the transit chain
double PROL0  = ANC0 * kcircN / ktrN;
double MARG0  = ANC0 * MARG_RATIO;
double PROLP0 = PLT0 * kcircP / ktrP;
double PROLE0 = HB0  * kcircE / ktrE;
double RPOOL0 = PROL0 + ANC0 + MARG0;

// initial conditions
HSC_0   = RESERVE;
PROL_0  = PROL0;  TR1_0 = PROL0;  TR2_0 = PROL0;  TR3_0 = PROL0;
CIRC_0  = ANC0;   MARG_0 = MARG0;
PROLP_0 = PROLP0; TP1_0 = PROLP0; TP2_0 = PROLP0; TP3_0 = PROLP0;
PLT_0   = PLT0;
PROLE_0 = PROLE0; TE1_0 = PROLE0; TE2_0 = PROLE0; TE3_0 = PROLE0;
HB_0    = HB0;
TPO_0   = 1.0;    BAR_0 = 1.0;    FUNC_0 = 1.0;
TUMS_0  = TUM0 * (1.0 - RES_FRAC0);
TUMR_0  = TUM0 * RES_FRAC0;

// G-CSF product switch.  Filgrastim keeps a renal route and therefore an
// ANC-independent half-life; pegfilgrastim does not, so its half-life is a
// function of the neutrophil pool it has just created.
double gF, gKA, gV, gVP, gQ, gCLLIN, gVMAX, gKM;
if (GTYPE < 1.5) {                      // filgrastim
  gF = 0.65; gKA = 0.240; gV = 6.0; gVP = 4.5; gQ = 1.00;
  gCLLIN = 2.50; gVMAX = 12000.0; gKM = 25.0;
} else {                                // pegfilgrastim (or a long-acting peer)
  gF = G_F; gKA = G_KA; gV = G_V; gVP = G_VP; gQ = G_Q;
  gCLLIN = G_CLLIN; gVMAX = G_VMAX; gKM = G_KM;
}

[ODE]
// ===========================================================================
// 1. CYTOTOXIC PHARMACOKINETICS  (linear, one-way: nothing feeds back into it)
// ===========================================================================
double CA = A_C / A_V1;
double CB = B_C / B_V1;
double CC = C_C / C_V1;
double CD = D_C / D_V1;

dxdt_A_C  = -(A_CL/A_V1 + A_Q2/A_V1 + A_Q3/A_V1)*A_C
            + (A_Q2/A_V2)*A_P1 + (A_Q3/A_V3)*A_P2;
dxdt_A_P1 = (A_Q2/A_V1)*A_C - (A_Q2/A_V2)*A_P1;
dxdt_A_P2 = (A_Q3/A_V1)*A_C - (A_Q3/A_V3)*A_P2;
dxdt_B_C  = -(B_CL/B_V1 + B_Q2/B_V1)*B_C + (B_Q2/B_V2)*B_P1;
dxdt_B_P1 = (B_Q2/B_V1)*B_C - (B_Q2/B_V2)*B_P1;
dxdt_C_C  = -(C_CL/C_V1 + C_Q2/C_V1)*C_C + (C_Q2/C_V2)*C_P1;
dxdt_C_P1 = (C_Q2/C_V1)*C_C - (C_Q2/C_V2)*C_P1;
dxdt_D_C  = -(D_CL/D_V1 + D_Q2/D_V1)*D_C + (D_Q2/D_V2)*D_P1;
dxdt_D_P1 = (D_Q2/D_V1)*D_C - (D_Q2/D_V2)*D_P1;

dxdt_AUC_A = CA;  dxdt_AUC_B = CB;  dxdt_AUC_C = CC;  dxdt_AUC_D = CD;

// ---- effective driving concentration (threshold PD for paclitaxel) --------
// Paclitaxel's neutropenia tracks TIME ABOVE ~0.05 umol/L far better than it
// tracks AUC, which is the whole reason weekly 80 mg/m2 is less myelosuppressive
// than q3w 175 mg/m2 at a similar dose intensity.  Setting *_CTHR > 0 selects
// that form for the slot.
double EA = (A_CTHR > 0.0) ? ((CA > A_CTHR) ? CA - A_CTHR : 0.0) : CA;
double EB = (B_CTHR > 0.0) ? ((CB > B_CTHR) ? CB - B_CTHR : 0.0) : CB;
double EC = (C_CTHR > 0.0) ? ((CC > C_CTHR) ? CC - C_CTHR : 0.0) : CC;
double ED = (D_CTHR > 0.0) ? ((CD > D_CTHR) ? CD - D_CTHR : 0.0) : CD;

double sA = A_SLOPE * SENS * SENS_GLOBAL * SENS_TAXANE;   // slot A is taxane
double sB = B_SLOPE * SENS * SENS_GLOBAL;
double sC = C_SLOPE * SENS * SENS_GLOBAL;
double sD = D_SLOPE * SENS * SENS_GLOBAL;

double eA = sA * EA, eB = sB * EB, eC = sC * EC, eD = sD * ED;

double EdrugN = eA + eB + eC + eD;
double EcycW  = eA*A_FCYC + eB*B_FCYC + eC*C_FCYC + eD*D_FCYC;
double EdrugP = sA*A_SLOPEP*EA + sB*B_SLOPEP*EB + sC*C_SLOPEP*EC + sD*D_SLOPEP*ED;
double EdrugE = sA*A_SLOPEE*EA + sB*B_SLOPEE*EB + sC*C_SLOPEE*EC + sD*D_SLOPEE*ED;
double Edmuc  = eA*A_MUC + eB*B_MUC + eC*C_MUC + eD*D_MUC;
double Edhsc  = eA*A_HSC + eB*B_HSC + eC*C_HSC + eD*D_HSC;

// ===========================================================================
// 2. TRILACICLIB — G1 arrest of the CYCLING fraction of the HSPC pool
// ===========================================================================
double Ct = T_C / T_V1;
dxdt_T_C = -(T_CL + T_Q)/T_V1 * T_C + (T_Q/T_V2) * T_P;
dxdt_T_P = (T_Q/T_V1) * T_C - (T_Q/T_V2) * T_P;
dxdt_AUC_T = Ct;
double arrest = (Ct > 0.0) ? T_IMAX * Ct / (T_IC50 + Ct) : 0.0;
double Fcyc   = 1.0 - arrest;      // fraction still in cycle

// Only the CELL-CYCLE-DEPENDENT share of the kill can be protected by G1
// arrest.  This is why trilaciclib does much more for an S/G2M-specific
// topoisomerase poison than for a cycle-nonspecific platinum agent.
double fmix = (EdrugN > 1e-12) ? (EcycW / EdrugN) : 0.0;
double prot = (1.0 - fmix) + fmix * Fcyc;
double EdN  = EdrugN * prot;
double EdP  = EdrugP * prot;
double EdE  = EdrugE * prot;
double EdH  = Edhsc  * prot;

// ===========================================================================
// 3. G-CSF — PK with TARGET-MEDIATED clearance, and five PD actions
// ===========================================================================
double Cg = G_C / (gV * 1000.0);              // ng/mL
double RPOOL = TR3 + CIRC + MARG;             // receptor-bearing pool
double RP0   = (ANC0*kcircN/ktrN) + ANC0 + ANC0*MARG_RATIO;
// THE key term: the drug is eliminated by the very cells it creates, so its
// half-life falls as the ANC recovers.  For pegfilgrastim this is the ONLY
// clearance route, which is why one fixed 6 mg dose self-titrates and why the
// concentration collapses exactly when it is no longer needed.
double elim_tm = gVMAX * Cg / (gKM + Cg) * (RPOOL / RP0);

dxdt_G_DEP = -gKA * G_DEP;
dxdt_G_C   = gF*gKA*G_DEP - (gCLLIN/gV)*G_C - elim_tm
             - (gQ/gV)*G_C + (gQ/gVP)*G_P;
dxdt_G_P   = (gQ/gV)*G_C - (gQ/gVP)*G_P;
dxdt_G_E   = G_KEO * (Cg - G_E);
dxdt_AUC_G = Cg;
double Ce = (G_E > 0.0) ? G_E : 0.0;
double Eg = (Ce > 0.0) ? Ce / (G_EC50 + Ce) : 0.0;

// ===========================================================================
// 4. DEXAMETHASONE AND LEVOFLOXACIN
// ===========================================================================
double Cdex = DEX / DEX_V * 1000.0;           // mg/L -> ng/mL
dxdt_DEX = -(DEX_CL/DEX_V) * DEX;
double Edex = (Cdex > 0.0) ? Cdex / (DEX_EC50 + Cdex) : 0.0;
double Cabx = ABX / ABX_V;                    // mg/L
dxdt_ABX = -(ABX_CL/ABX_V) * ABX;
double Eabx = (Cabx > 0.0) ? ABX_IMAX * Cabx / (ABX_EC50 + Cabx) : 0.0;

// ===========================================================================
// 5. STEM POOL AND MARROW RESERVE
// ===========================================================================
double hsc = (HSC > 1e-9) ? HSC : 1e-9;
dxdt_HSC = KSELF * hsc * (1.0 - hsc/RESERVE) - KHSC_KILL * EdH * hsc;
dxdt_FIB = KFIB * EdH * (1.0 - FIB);
double reserve = hsc - FIB;
if (reserve < 0.0) reserve = 0.0;

// ===========================================================================
// 6. NEUTROPHIL LINEAGE — the delay line
// ===========================================================================
// G-CSF's transit acceleration is applied to BOTH the proliferation and the
// transit terms, because in this topology they are the SAME rate constant.
// Applying it only to the outflow makes accelerating transit empty the
// proliferative pool, which would have more G-CSF deepening the nadir.
double ktrNe = ktrN * (1.0 + EMAX_KTR * Eg);
double circ  = (CIRC > 0.05) ? CIRC : 0.05;
double fbN   = pow(ANC0 / circ, gam);
double ampN  = 1.0 + EMAX_AMP * Eg;
double PROL0b = ANC0 * kcircN / ktrN;

// The stem-derived influx is a FLUX set by upstream biology, so it is scaled by
// the BASE transit rate, not the accelerated one -- otherwise G-CSF would
// multiply the marrow's INPUT rather than shortening the pipeline.  With the
// base rate, faster transit shrinks the standing pool and leaves the flux
// through it unchanged: it moves the DELAY without moving the LEVEL, which is
// the separation the whole model is built around.
// NOTE the absence of `reserve` on the SELF-RENEWAL term.  Multiplying the
// self-renewal gain by the marrow reserve couples a small stem-cell loss to a
// huge change in the steady-state count through the 1/gamma exponent -- a 12%
// reserve loss HALVED the baseline ANC, which is not what a previously-treated
// patient looks like.  Reserve belongs on the stem-derived INFLUX, where a 12%
// loss costs 12% of the marrow's input.  The clinical consequence is the right
// one: reduced reserve barely moves the baseline count and markedly slows
// RECOVERY, because during the nadir the influx term is all that is left.
double prol_in = ktrNe*(1.0-PHI)*PROL*fbN*ampN*(1.0-EdN)
               + ktrN*PHI*PROL0b*hsc*fbN*ampN*(1.0-FIB)*(1.0-EdN);

// NOTE: (1 - EdN) is deliberately NOT clamped at zero.  At the published
// Friberg slopes EdN exceeds 1 during the infusion, so the term goes negative
// and the proliferative pool is actively DEPLETED rather than merely stopped.
// Clamping it caps the achievable nadir far above what is observed.
dxdt_PROL = prol_in - ktrNe*PROL;
dxdt_TR1  = ktrNe*(PROL - TR1);
dxdt_TR2  = ktrNe*(TR1  - TR2);
double krel = KREL_MAX * EMAX_REL * Eg;
dxdt_TR3  = ktrNe*TR2 - (ktrNe + krel)*TR3;

// Margination falls with corticosteroid (demargination) and, in this model, NOT
// with G-CSF.  Circulating clearance is slowed by G-CSF (anti-apoptotic).
double kmi = KMARG * (1.0 - DEX_DEMARG*Edex) * (1.0 - EMAX_DEMARG*Eg);
double kmo = KMARG;
double kcircNe = kcircN * (1.0 - EMAX_SURV*Eg);
double consume = KCONSUME * BACT/(B50 + BACT) * CIRC;

dxdt_CIRC = (ktrNe + krel)*TR3 - kcircNe*CIRC - kmi*CIRC + kmo*MARG - consume;
dxdt_MARG = kmi*CIRC - kmo*MARG;

// ===========================================================================
// 7. PLATELET AND ERYTHROID LINEAGES — same insult, different clocks
// ===========================================================================
double plt_ = (PLT > 2.0) ? PLT : 2.0;
double fbP  = pow(PLT0/plt_, GAMMA_P) * TPO;
if (fbP > FBP_MAX) fbP = FBP_MAX;
double PROLP0b = PLT0 * kcircP / ktrP;
dxdt_PROLP = ktrP*(1.0-PHI_PE)*PROLP*fbP*(1.0-EdP)
           + ktrP*PHI_PE*PROLP0b*hsc*fbP*(1.0-FIB)*(1.0-EdP) - ktrP*PROLP;
dxdt_TP1 = ktrP*(PROLP - TP1);
dxdt_TP2 = ktrP*(TP1 - TP2);
dxdt_TP3 = ktrP*(TP2 - TP3);
dxdt_PLT = ktrP*TP3 - kcircP*PLT;
// Thrombopoietin is cleared through c-Mpl on platelets: the same
// target-mediated trick as G-CSF, one lineage over.  The TPO_MAX ceiling is
// applied to the PRODUCTION branch only -- applied to both it becomes a sign
// trap, because above the ceiling both factors are negative and TPO then grows
// faster the further past its limit it goes.
double tpo_drive = 1.0 - TPO * PLT / PLT0;
if (tpo_drive > 0.0) tpo_drive *= (1.0 - TPO/TPO_MAX > 0.0 ? 1.0 - TPO/TPO_MAX : 0.0);
dxdt_TPO = 0.010 * tpo_drive;

double hb_ = (HB > 3.0) ? HB : 3.0;
double fbE = pow(HB0/hb_, GAMMA_E);
double PROLE0b = HB0 * kcircE / ktrE;
dxdt_PROLE = ktrE*(1.0-PHI_PE)*PROLE*fbE*(1.0-EdE)
           + ktrE*PHI_PE*PROLE0b*hsc*fbE*(1.0-FIB)*(1.0-EdE) - ktrE*PROLE;
dxdt_TE1 = ktrE*(PROLE - TE1);
dxdt_TE2 = ktrE*(TE1 - TE2);
dxdt_TE3 = ktrE*(TE2 - TE3);
dxdt_HB  = ktrE*TE3 - kcircE*HB;

// ===========================================================================
// 8. MUCOSAL BARRIER, NEUTROPHIL FUNCTION, INFECTION, FEVER
// ===========================================================================
dxdt_BAR = KHEAL_BAR*(1.0 - BAR) - KDAM_BAR*Edmuc*BAR;

// FUNCTION is a state distinct from COUNT.  Corticosteroid lowers it while
// raising the count; G-CSF raises both; the cytotoxic itself lowers it.
double edn1 = (EdrugN < 1.0) ? EdrugN : 1.0;
double fun_target = (1.0 - DEX_FUNC*Edex) * (1.0 + EMAX_FUN*Eg) * (1.0 - 0.25*edn1);
dxdt_FUNC = KFUNC * (fun_target - FUNC);

double breach = (BAR < 1.0) ? 1.0 - BAR : 0.0;
double influx = K_TRANS * breach * (1.0 - Eabx);
double func_  = (FUNC > 0.0) ? FUNC : 0.0;
double ANCeff = (CIRC + MARG) * func_;        // the defence that actually acts
double killB  = KKILL_B * ANCeff * BACT / (1.0 + BACT/B50);
dxdt_BACT = influx + KGROW_B*(1.0 - Eabx)*BACT*(1.0 - BACT/BMAX) - killB;

dxdt_IL6  = KIL6_B*BACT - KIL6_OUT*IL6;
dxdt_CRP  = KCRP_IN*IL6 - KCRP_OUT*CRP;
dxdt_TDEV = KT_IN*IL6 - KT_OUT*TDEV;

// ===========================================================================
// 9. COUNTERS — duration and hazard, not depth
// ===========================================================================
dxdt_DSN_H = (CIRC < 0.5) ? 1.0 : 0.0;
double depth = (CIRC < 0.5) ? (1.0 - CIRC/0.5) : 0.0;
dxdt_CUMHAZ = HFN_BASE
            + HFN_K * pow(depth, HFN_P) * (1.0 + HFN_BAR*breach) * (1.0 - 0.55*Eabx);

// ===========================================================================
// 10. TUMOUR — regrowth here; the log-kill is an event-driven impulse
// ===========================================================================
double kg = log(2.0)/TDOUBLE;
dxdt_TUMS = kg*TUMS;
dxdt_TUMR = kg*TUMR;

[TABLE]
double ANC       = CIRC;
double DSN_D     = DSN_H/24.0;
double P_FN      = 1.0 - exp(-CUMHAZ);
double TEMP      = 36.8 + TDEV;
double TUMOUR    = TUMS + TUMR;
double RESERVE_N = HSC - FIB;
double ANC_EFF   = (CIRC + MARG) * FUNC;
double GRADE     = (CIRC >= 2.0) ? 0.0 :
                   ((CIRC >= 1.5) ? 1.0 :
                   ((CIRC >= 1.0) ? 2.0 :
                   ((CIRC >= 0.5) ? 3.0 : 4.0)));
double CGCSF     = G_C / (G_V * 1000.0);
double CDOCE     = A_C / A_V1;
double FEBRILE   = ((CIRC < 0.5) && (36.8 + TDEV >= 38.3)) ? 1.0 : 0.0;
double GATE_D1   = ((CIRC >= 1.5) && (PLT >= 100.0)) ? 1.0 : 0.0;

[CAPTURE] @annotated
ANC       : 10^9/L, absolute neutrophil count (the measured number)
ANC_EFF   : 10^9/L, effective defence = (circulating + marginated) x function
GRADE     : -, CTCAE neutropenia grade
DSN_D     : d, cumulative days with ANC < 0.5
P_FN      : -, cumulative probability of febrile neutropenia
FEBRILE   : -, 1 when the FN definition is met at this instant
GATE_D1   : -, 1 when the day-1 CBC gate would allow the next cycle
TEMP      : degC, core temperature
TUMOUR    : au, total tumour burden
RESERVE_N : -, marrow reserve net of irreversible damage
CGCSF     : ng/mL, G-CSF plasma concentration
CDOCE     : umol/L, slot A cytotoxic concentration

##  ============================================================================
##  USAGE
##  ============================================================================
##  library(mrgsolve); library(dplyr); library(ggplot2)
##  mod <- mread("cin_mrgsolve_model.R")
##
##  ## --------------------------------------------------------------------
##  ## Agent parameter sets.  Each agent occupies one PK slot; a regimen is a
##  ## list of agents plus a dosing schedule.  Doses are converted to umol.
##  ## --------------------------------------------------------------------
##  CIN_AGENTS <- list(
##    docetaxel = list(slot="A", mw=807.9, per_bsa=TRUE, tinf=1.0,
##                     CL=21.6, V1=7.4, V2=25, V3=42, Q2=45, Q3=5,
##                     slope=15.9, slopeP=0.076, slopeE=0.35,
##                     fcyc=0.90, hsc=0.55, muc=0.85, cthr=0, taxane=TRUE),
##    paclitaxel = list(slot="A", mw=853.9, per_bsa=TRUE, tinf=3.0,
##                     CL=14, V1=10, V2=30, V3=180, Q2=40, Q3=8,
##                     slope=4.09, slopeP=0.152, slopeE=0.30,
##                     fcyc=0.90, hsc=0.35, muc=0.55, cthr=0.05, taxane=TRUE),
##    doxorubicin = list(slot="B", mw=543.5, per_bsa=TRUE, tinf=0.25,
##                     CL=50, V1=12, V2=700, Q2=38,
##                     slope=23.0, slopeP=0.372, slopeE=0.55,
##                     fcyc=0.60, hsc=0.75, muc=1.00, cthr=0),
##    gemcitabine = list(slot="B", mw=263.2, per_bsa=TRUE, tinf=0.5,
##                     CL=92, V1=14, V2=6, Q2=8,
##                     slope=0.545, slopeP=1.79, slopeE=0.60,
##                     fcyc=0.95, hsc=0.30, muc=0.35, cthr=0),
##    cyclophosphamide = list(slot="C", mw=261.1, per_bsa=FALSE, tinf=0.5,
##                     CL=5.6, V1=32, V2=18, Q2=6,
##                     slope=0.0436, slopeP=0.796, slopeE=0.60,
##                     fcyc=0.40, hsc=1.00, muc=0.55, cthr=0),
##    carboplatin = list(slot="C", mw=371.3, per_bsa=FALSE, tinf=0.5,
##                     CL=NA, V1=16, V2=8, Q2=3,      # CL from Calvert: GFR+25
##                     slope=0.0999, slopeP=4.42, slopeE=0.70,
##                     fcyc=0.35, hsc=0.85, muc=0.40, cthr=0, auc_dosed=TRUE),
##    etoposide = list(slot="D", mw=588.6, per_bsa=TRUE, tinf=1.0,
##                     CL=1.35, V1=8, V2=10, Q2=2.2,
##                     slope=0.133, slopeP=0.646, slopeE=0.35,
##                     fcyc=0.92, hsc=0.40, muc=0.60, cthr=0),
##    topotecan = list(slot="A", mw=421.4, per_bsa=TRUE, tinf=0.5,
##                     CL=26, V1=17, V2=30, V3=60, Q2=18, Q3=3,
##                     slope=160.0, slopeP=0.875, slopeE=0.55,
##                     fcyc=0.95, hsc=0.55, muc=0.65, cthr=0)
##  )
##  ## Slot compartment numbers: A_C = 1, B_C = 4, C_C = 6, D_C = 8,
##  ## G_DEP = 10, T_C = 14, DEX = 16, ABX = 17.
##
##  CIN_slot_params <- function(a, bsa = 1.75, gfr = 90) {
##    s   <- a$slot
##    scl <- if (isTRUE(a$per_bsa)) bsa else 1
##    CL  <- if (isTRUE(a$auc_dosed)) (gfr + 25) * 60/1000 else a$CL * scl
##    p <- list()
##    p[[paste0(s,"_CL")]] <- CL
##    p[[paste0(s,"_V1")]] <- a$V1 * scl
##    p[[paste0(s,"_V2")]] <- a$V2 * scl
##    p[[paste0(s,"_Q2")]] <- a$Q2 * scl
##    if (s == "A") { p$A_V3 <- a$V3 * scl; p$A_Q3 <- a$Q3 * scl }
##    p[[paste0(s,"_SLOPE")]]  <- a$slope
##    p[[paste0(s,"_SLOPEP")]] <- a$slopeP
##    p[[paste0(s,"_SLOPEE")]] <- a$slopeE
##    p[[paste0(s,"_FCYC")]]   <- a$fcyc
##    p[[paste0(s,"_HSC")]]    <- a$hsc
##    p[[paste0(s,"_MUC")]]    <- a$muc
##    p[[paste0(s,"_CTHR")]]   <- a$cthr
##    p
##  }
##
##  ## --------------------------------------------------------------------
##  ## Regimens.  dose is mg/m2 unless auc = TRUE (carboplatin, Calvert).
##  ## --------------------------------------------------------------------
##  CIN_REGIMENS <- list(
##    docetaxel100 = list(cycle = 504, drugs = list(
##        list(agent="docetaxel", dose=100, days=0))),
##    AT   = list(cycle = 504, drugs = list(      # Green 2003 / Holmes 2002
##        list(agent="docetaxel", dose=75,  days=0),
##        list(agent="doxorubicin", dose=60, days=0))),
##    CAE  = list(cycle = 504, drugs = list(      # Crawford 1991
##        list(agent="cyclophosphamide", dose=1000, days=0),
##        list(agent="doxorubicin", dose=45, days=0),
##        list(agent="etoposide", dose=100, days=c(0,24,48)))),
##    TAC  = list(cycle = 504, drugs = list(
##        list(agent="docetaxel", dose=75, days=0),
##        list(agent="doxorubicin", dose=50, days=0),
##        list(agent="cyclophosphamide", dose=500, days=0))),
##    AC   = list(cycle = 504, drugs = list(
##        list(agent="doxorubicin", dose=60, days=0),
##        list(agent="cyclophosphamide", dose=600, days=0))),
##    ddAC = list(cycle = 336, drugs = list(      # dose-dense; G-CSF obligatory
##        list(agent="doxorubicin", dose=60, days=0),
##        list(agent="cyclophosphamide", dose=600, days=0))),
##    EP   = list(cycle = 504, drugs = list(      # SCLC; trilaciclib setting
##        list(agent="carboplatin", dose=5, days=0, auc=TRUE),
##        list(agent="etoposide", dose=100, days=c(0,24,48)))),
##    GCb  = list(cycle = 504, drugs = list(
##        list(agent="gemcitabine", dose=1000, days=c(0,168)),
##        list(agent="carboplatin", dose=5, days=0, auc=TRUE))),
##    topotecan  = list(cycle = 504, drugs = list(
##        list(agent="topotecan", dose=1.5, days=c(0,24,48,72,96)))),
##    pac175q3w  = list(cycle = 504, drugs = list(
##        list(agent="paclitaxel", dose=175, days=0))),
##    pac80wk    = list(cycle = 504, drugs = list(
##        list(agent="paclitaxel", dose=80, days=c(0,168,336))))
##  )
##  SLOT_CMT <- c(A = 1, B = 4, C = 6, D = 8)
##
##  CIN_build <- function(regimen, n_cycles = 1, bsa = 1.75, gfr = 90,
##                        wt = 70, gcsf = NA, gcsf_start = 24, gcsf_days = 1,
##                        trilaciclib = FALSE, dex = FALSE, abx = FALSE,
##                        dose_mult = 1) {
##    reg <- CIN_REGIMENS[[regimen]]
##    pars <- list(BSA = bsa, GFR = gfr, WT = wt)
##    ev <- NULL
##    add <- function(e) ev <<- if (is.null(ev)) e else rbind(ev, e)
##    for (d in reg$drugs) {
##      a <- CIN_AGENTS[[d$agent]]
##      pars <- modifyList(pars, CIN_slot_params(a, bsa, gfr))
##      dose_mg <- if (isTRUE(d$auc)) d$dose * (gfr + 25) else d$dose * bsa
##      amt <- dose_mg * 1000 / a$mw * dose_mult          # umol
##      for (ci in seq_len(n_cycles) - 1) for (dd in d$days)
##        add(data.frame(ID = 1, time = ci*reg$cycle + dd, cmt = SLOT_CMT[[a$slot]],
##                       amt = amt, rate = amt/a$tinf, evid = 1))
##    }
##    ## a taxane-free regimen must not carry the taxane class scale
##    if (!any(vapply(reg$drugs, function(d) isTRUE(CIN_AGENTS[[d$agent]]$taxane),
##                    logical(1)))) pars$SENS_TAXANE <- 1
##    if (!is.na(gcsf)) {
##      pars$GTYPE <- if (gcsf == "filgrastim") 1 else 2
##      amt <- if (gcsf == "filgrastim") 5 * wt * 1000 else 6e6      # ng
##      for (ci in seq_len(n_cycles) - 1) for (k in seq_len(gcsf_days) - 1)
##        add(data.frame(ID = 1, time = ci*reg$cycle + gcsf_start + 24*k,
##                       cmt = 10, amt = amt, rate = 0, evid = 1))
##    }
##    if (trilaciclib) for (d in reg$drugs) for (ci in seq_len(n_cycles) - 1)
##      for (dd in unique(d$days))
##        add(data.frame(ID = 1, time = ci*reg$cycle + dd - 0.5, cmt = 14,
##                       amt = 240*bsa, rate = 240*bsa/0.5, evid = 1))
##    if (dex) for (ci in seq_len(n_cycles) - 1) for (h in c(-12,0,12,24,36,48))
##      add(data.frame(ID = 1, time = ci*reg$cycle + h, cmt = 16, amt = 8,
##                     rate = 0, evid = 1))
##    if (abx) for (ci in seq_len(n_cycles) - 1) for (k in 0:10)
##      add(data.frame(ID = 1, time = ci*reg$cycle + 120 + 24*k, cmt = 17,
##                     amt = 500, rate = 0, evid = 1))
##    ev <- ev[ev$time >= 0, ]
##    list(param = pars, events = ev[order(ev$time), ],
##         end = (n_cycles - 1)*reg$cycle + reg$cycle)
##  }
##
##  CIN_run <- function(regimen, ..., delta = 2) {
##    b <- CIN_build(regimen, ...)
##    mod %>% param(b$param) %>% data_set(b$events) %>%
##      mrgsim(end = b$end, delta = delta, hmax = 0.25) %>% as.data.frame()
##  }
##
##  ## --------------------------------------------------------------------
##  ## 14 prebuilt scenarios.  These are the same runs the Python reference
##  ## implementation reports as analyses A2-A14.
##  ## --------------------------------------------------------------------
##  CIN_SCENARIOS <- list(
##    S01_natural          = list(regimen="docetaxel100"),
##    S02_peg_day2         = list(regimen="docetaxel100", gcsf="pegfilgrastim",
##                                gcsf_start=24),
##    S03_peg_same_day     = list(regimen="docetaxel100", gcsf="pegfilgrastim",
##                                gcsf_start=0.5),
##    S04_filgrastim_d2_11 = list(regimen="docetaxel100", gcsf="filgrastim",
##                                gcsf_start=24, gcsf_days=10),
##    S05_filgrastim_late  = list(regimen="docetaxel100", gcsf="filgrastim",
##                                gcsf_start=168, gcsf_days=7),
##    S06_dose_reduce_75   = list(regimen="docetaxel100", dose_mult=0.75),
##    S07_crawford_CAE     = list(regimen="CAE"),
##    S08_crawford_CAE_G   = list(regimen="CAE", gcsf="filgrastim",
##                                gcsf_start=72, gcsf_days=14),
##    S09_green_AT_peg     = list(regimen="AT", gcsf="pegfilgrastim"),
##    S10_EP_sclc          = list(regimen="EP"),
##    S11_EP_trilaciclib   = list(regimen="EP", trilaciclib=TRUE),
##    S12_GCb_platelets    = list(regimen="GCb"),
##    S13_pac_q3w_vs_wk    = list(regimen="pac175q3w"),
##    S14_pac_weekly       = list(regimen="pac80wk"),
##    S15_ddAC_6cycles     = list(regimen="ddAC", n_cycles=6,
##                                gcsf="pegfilgrastim"),
##    S16_dex_premed       = list(regimen="docetaxel100", dex=TRUE),
##    S17_levofloxacin     = list(regimen="CAE", abx=TRUE),
##    S18_low_reserve      = list(regimen="CAE")     # set RESERVE = 0.75
##  )
##
##  CIN_simulate_scenarios <- function() {
##    out <- lapply(names(CIN_SCENARIOS), function(nm) {
##      a <- CIN_SCENARIOS[[nm]]
##      df <- do.call(CIN_run, a)
##      df$scenario <- nm
##      df
##    })
##    do.call(rbind, out)
##  }
##
##  CIN_summary <- function(df) {
##    df %>% group_by(scenario) %>%
##      summarise(nadir_ANC   = min(ANC),
##                nadir_day   = time[which.min(ANC)]/24,
##                DSN_days    = max(DSN_D),
##                P_FN        = max(P_FN),
##                nadir_PLT   = min(PLT),
##                nadir_HB    = min(HB),
##                peak_TEMP   = max(TEMP),
##                peak_CRP    = max(CRP),
##                reserve_end = last(RESERVE_N),
##                .groups = "drop")
##  }
##
##  ## df <- CIN_simulate_scenarios(); CIN_summary(df)
##  ##
##  ## ggplot(df, aes(time/24, ANC, colour = scenario)) + geom_line() +
##  ##   geom_hline(yintercept = 0.5, linetype = 2) +
##  ##   labs(x = "days from chemotherapy", y = "ANC (10^9/L)") +
##  ##   scale_y_log10()
##  ##
##  ## The pegfilgrastim self-titration result is easiest to see as
##  ##   ggplot(subset(df, scenario == "S02_peg_day2")) +
##  ##     geom_line(aes(time/24, CGCSF)) +
##  ##     geom_line(aes(time/24, ANC*20), colour = "red")
##  ## -- the G-CSF concentration collapses exactly as the ANC recovers, because
##  ## the recovering neutrophils are the clearance mechanism.
##  ##
##  ## Disclaimer: research / education / hypothesis generation only.
##  ## ============================================================================
