# =============================================================================
#  Kidney Transplant Rejection & Immunosuppression — QSP model (mrgsolve)
#  ---------------------------------------------------------------------------
#  ktx_mrgsolve_model.R   ·   companion to ktx_qsp_model.dot / ktx_shiny_app.R
#
#  WHAT THIS MODEL IS ABOUT
#  ------------------------
#  A kidney transplant is the only condition in this library whose pathology is
#  produced by a NORMALLY FUNCTIONING immune system, and whose treatment target
#  is therefore not a pathway but a SET POINT.  The model is built around one
#  scalar, NET IMMUNOSUPPRESSION (NIS), and the two failure modes that sit on
#  either side of it:
#
#      too little NIS  ->  TCMR, de novo DSA, ABMR      ->  graft loss
#      too much  NIS  ->  BK nephropathy, CMV, PTLD     ->  graft loss
#
#  Everything else in the model exists to make that trade-off quantitative.
#
#  THREE FEEDBACK LOOPS DO THE WORK
#  --------------------------------
#  LOOP 1  alloimmune amplification
#          injury -> DAMP -> antigen presentation (AG) -> effector traffic ->
#          injury.  Sub-critical under adequate immunosuppression, supercritical
#          without it: this is what makes untreated rejection an ignition event
#          (Banff t reaches ~2.5 within 10-14 days) rather than a slow drift.
#
#  LOOP 2  nephron mass / hyperfiltration (Brenner)
#          nephron loss -> single-nephron hyperfiltration -> TGF-beta -> IFTA ->
#          nephron loss.  DRUG-INDEPENDENT.  It is why every graft declines at
#          roughly -1 mL/min/1.73 m2/year even when nothing immunological
#          ever happens.
#
#  LOOP 3  the clinical control loop
#          BK viraemia -> the clinician reduces immunosuppression -> the virus
#          clears -> alloimmunity rebounds.  This one is implemented as a REAL
#          closed-loop controller inside $ODE (see BKRED), not as a scripted
#          dose change, so the rebound is generated by the model rather than
#          assumed by the modeller.
#
#  THE TWO THRESHOLDS THAT GENERATE THE PHENOTYPES
#  -----------------------------------------------
#  (a) T-cell ignition.  Alloreactive blast proliferation is autocatalytic
#      through IL-2 (PROLT below).  Its rate constant must exceed the blast
#      loss rate (KDIFF + KDTACT) for a lesion to ignite.  Under tacrolimus the
#      calcineurin term keeps it unconditionally sub-critical - which is why a
#      CYP3A5 expresser at a trough of 4 ng/mL gets a bigger lesion but not a
#      florid one.  Under belatacept there is NO calcineurin term, so the
#      system is only CONDITIONALLY stable: a recipient with a large CD28-null
#      CD57+ memory pool (FCD28N high) tips over it and rejects, while the
#      same regimen in a memory-poor recipient does not.  That is the model's
#      mechanistic account of the BENEFIT paradox (more early acute rejection,
#      better long-term GFR).
#
#  (b) Germinal-centre ignition.  GC B-cell proliferation requires ongoing Tfh
#      help (BHELP), scales with the eplet-mismatch load (BEPI), and is
#      suppressed by mycophenolate.  Standard therapy sits below the threshold
#      (DSA stays < 300 MFI for 5 years); halving exposure through
#      non-adherence pushes it above, and because long-lived plasma cells then
#      accumulate irreversibly, the resulting DSA does not come back down when
#      adherence is restored.  This is the model's account of why late graft
#      loss is dominated by dnDSA + non-adherence.
#
#  WHY THERE ARE (ALMOST) NO DOSING EVENTS
#  ---------------------------------------
#  This is a 5-year disease-progression model, not a first-dose PK study, so
#  chronic oral drugs enter as continuous input rates and the model carries the
#  AVERAGE concentration.  Reported troughs are recovered with published
#  Cavg->C0 ratios (RTROUGH = 0.75 for tacrolimus, since AUC0-12/C0 ~ 16 h;
#  RTRCSA = 0.45; RTRMPA = 0.40; RTREVR = 0.50).  Episodic IV agents (ATG,
#  basiliximab, belatacept, rituximab, anti-IL-6, anti-CD38, IVIG, steroid
#  pulses, plasma exchange, imlifidase) enter through smooth rectangular
#  windows so their real peak-to-trough behaviour is preserved.  Every scenario
#  is therefore a pure parameter set: reproducible, and diff-able.
#
#  THERAPEUTIC DRUG MONITORING IS A CONTROLLER, NOT A DOSE TABLE
#  -------------------------------------------------------------
#  DOSEADJ is a state: an integral controller that moves the tacrolimus dose
#  towards the protocol trough target (9 ng/mL to month 3, 7 to month 12, 6
#  thereafter).  Two consequences fall out of that and are worth stating:
#    - a CYP3A5 expresser on fixed mg/kg dosing (TDM = 0) sits at C0 ~ 4 ng/mL,
#      while the same patient under TDM is dose-corrected back to target;
#    - a NON-ADHERENT patient is NOT dose-corrected, because the trough the
#      clinic measures is drawn after a dose the patient did take ("white-coat
#      adherence").  The controller therefore sees a normal trough while true
#      exposure is halved - modelled as C0MEAS = C0 / ADH.  This is the single
#      most important reason non-adherence is invisible until the DSA appears.
#
#  WHAT IS DELIBERATELY *NOT* CLAIMED
#  ----------------------------------
#  This is a deterministic single-patient model.  It does not produce incidence
#  rates; a scenario either crosses a lesion threshold or it does not.  Trial
#  percentages (BPAR ~10-12%, dnDSA ~15-25% at 5 y) are population statements
#  and are used here only as sanity anchors for the phenotypes, never as
#  fitted targets.  Parameters are literature-anchored where a number exists
#  (all PK, CYP3A5 1.9x, trough targets, MPA AUC window, BK 10^4 threshold,
#  eGFR levels and slopes) and hand-calibrated otherwise.  Not for clinical use.
#
#  Requires: mrgsolve, dplyr, tidyr, ggplot2
#  Run:      Rscript ktx_mrgsolve_model.R
# =============================================================================

library(mrgsolve)
suppressMessages({
  library(dplyr)
  library(tidyr)
})

code <- '
$PROB
# Kidney transplant rejection / immunosuppression QSP model
- 59 ODEs: 21 PK + 1 TDM controller, 19 alloimmune, 9 graft, 6 infection/safety,
  3 behavioural & outcome
- All dosing is parameter-driven; every scenario is a pure parameter set

$PARAM @annotated
WT : 75.0 : recipient weight (kg)
CYP3A5 : 0.0 : CYP3A5 genotype flag, 1 = expresser (CL x 1.9)
HLAMM : 3.0 : HLA A/B/DR antigen mismatch (0-6)
EPLET : 12.0 : HLA-DR/DQ eplet mismatch load
CPRA : 0.0 : calculated PRA (%), descriptive covariate
PREDSA : 0.0 : preformed donor-specific antibody at day 0 (MFI)
CIT : 14.0 : cold ischaemia time (h)
DCD : 0.0 : donation after circulatory death flag
KDPI : 40.0 : kidney donor profile index (%)
FCD28N : 0.45 : fraction of alloreactive memory T cells that are CD28-null (belatacept-resistant)
MISSSELF : 0.3 : missing-self NK activation potential (0-1)
BKSUSC : 0.0 : BK polyomavirus reactivation susceptibility flag
CMVDR : 0.0 : CMV D+/R- mismatch flag (no pre-existing CMV immunity)
CMVSUSC : 0.0 : CMV reactivation susceptibility flag
EBVDR : 0.0 : EBV D+/R- mismatch flag, PTLD risk covariate
TACON : 1.0 : tacrolimus on/off
TACMGKG : 0.1 : tacrolimus starting dose (mg/kg per dose, BID)
TDM : 1.0 : therapeutic drug monitoring controller on/off
TACTGT1 : 9.0 : tacrolimus trough target, months 0-3 (ng/mL)
TACTGT2 : 7.0 : tacrolimus trough target, months 3-12 (ng/mL)
TACTGT3 : 6.0 : tacrolimus trough target, after month 12 (ng/mL)
KTDM : 0.1 : TDM controller gain (1/day)
DOSEMAX : 5.0 : maximum dose-adjustment factor the controller may reach
IPVAMP : 0.0 : intra-patient variability amplitude on tacrolimus clearance (fraction)
PIPV : 30.0 : period of the modelled IPV oscillation (day)
CSAON : 0.0 : cyclosporine on/off
CSAMGKG : 7.5 : cyclosporine dose (mg/kg/day)
MMFON : 1.0 : mycophenolate on/off
MMFDOSE : 2000.0 : mycophenolate mofetil dose (mg/day)
PREDON : 1.0 : corticosteroid on/off
PREDSTOP : 100000 : day of corticosteroid withdrawal
EVRON : 0.0 : everolimus on/off
EVRDOSE : 3.0 : everolimus dose (mg/day)
ATGON : 0.0 : rabbit ATG induction on/off
ATGMGKG : 1.5 : rabbit ATG dose (mg/kg/day)
ATGDAYS : 5.0 : number of consecutive rabbit ATG days
BASON : 1.0 : basiliximab induction on/off
BELAON : 0.0 : belatacept on/off
RTXON : 0.0 : rituximab on/off
RTXDAY : 100000 : day of rituximab infusion
TCZON : 0.0 : anti-IL-6/IL-6R on/off
TCZSTART : 100000 : day of first anti-IL-6 infusion
TCZN : 6.0 : number of monthly anti-IL-6 infusions
FZBON : 0.0 : anti-CD38 (felzartamab) on/off
FZBSTART : 100000 : day of first anti-CD38 infusion
IVIGON : 0.0 : IVIG on/off
IVIGSTART : 100000 : day of IVIG infusion
PLEXON : 0.0 : plasma exchange on/off
PLEXSTART : 100000 : day of first plasma exchange session
PLEXN : 5.0 : number of alternate-day plasma exchange sessions
IDESON : 0.0 : imlifidase (IdeS) on/off
IDESDAY : 0.0 : day of imlifidase dose
ECUON : 0.0 : eculizumab (anti-C5) on/off
MPON : 0.0 : methylprednisolone pulse on/off
MPSTART : 100000 : day of first methylprednisolone pulse
MPDOSE : 500.0 : methylprednisolone pulse dose (mg/day)
MPDAYS : 3.0 : number of methylprednisolone pulse days
ATG2ON : 0.0 : second (rescue) ATG course on/off
ATG2START : 100000 : day of first rescue ATG dose
VGCON : 1.0 : valganciclovir prophylaxis on/off
VGCSTOP : 90.0 : day valganciclovir prophylaxis stops
BKSCREEN : 1.0 : BK screening with pre-emptive IS reduction on/off (closed-loop controller)
ADHSTART : 100000 : day non-adherence begins
ADHEND : 100000 : day adherence is restored
ADHFINAL : 1.0 : adherence during the non-adherent period (fraction of doses taken)
KADHR : 0.02 : rate of change of the adherence state (1/day)
FTAC : 0.25 : tacrolimus oral bioavailability
KA_TAC : 6.0 : tacrolimus gut transit rate constant (1/day)
CLTAC : 380.0 : tacrolimus apparent clearance (L/day)
V2TAC : 500.0 : tacrolimus central volume (L)
QTAC : 900.0 : tacrolimus intercompartmental clearance (L/day)
V3TAC : 800.0 : tacrolimus peripheral volume (L)
RTROUGH : 0.75 : tacrolimus C0/Cavg ratio (AUC0-12/C0 approx 16 h)
CLCSA : 1300.0 : cyclosporine apparent clearance (L/day)
V2CSA : 600.0 : cyclosporine central volume (L)
QCSA : 1400.0 : cyclosporine intercompartmental clearance (L/day)
V3CSA : 1500.0 : cyclosporine peripheral volume (L)
RTRCSA : 0.45 : cyclosporine C0/Cavg ratio
FMPA : 0.94 : mycophenolate mofetil to MPA conversion fraction
KA_MPA : 8.0 : MPA absorption rate constant (1/day)
CLMPA : 600.0 : MPA apparent clearance (L/day)
VMPA : 200.0 : MPA central volume (L)
QMPA : 250.0 : MPA intercompartmental clearance (L/day)
V3MPA : 300.0 : MPA peripheral volume (L)
KBIL : 0.6 : MPAG biliary excretion rate constant (1/day)
KREN : 1.0 : MPAG renal elimination rate constant (1/day)
FEHC : 0.55 : fraction of biliary MPAG deconjugated back to MPA (enterohepatic recycling)
RTRMPA : 0.4 : MPA C0/Cavg ratio
FPRED : 0.8 : prednisone to prednisolone conversion fraction
CLPRED : 150.0 : prednisolone clearance (L/day)
VPRED : 40.0 : prednisolone volume (L)
CLMP : 400.0 : methylprednisolone clearance (L/day)
VMP : 80.0 : methylprednisolone volume (L)
CLEVR : 250.0 : everolimus apparent clearance (L/day)
VEVR : 340.0 : everolimus volume (L)
RTREVR : 0.5 : everolimus C0/Cavg ratio
CLATG : 0.12 : rabbit ATG clearance (L/day)
VATG : 5.0 : rabbit ATG volume (L)
CLBAS : 0.5 : basiliximab clearance (L/day)
VBAS : 8.0 : basiliximab volume (L)
CLBELA : 0.88 : belatacept clearance (L/day)
VBELA : 8.25 : belatacept volume (L)
CLRTX : 0.25 : rituximab clearance (L/day)
VRTX : 3.5 : rituximab volume (L)
CLTCZ : 0.25 : anti-IL-6(R) clearance (L/day)
VTCZ : 5.0 : anti-IL-6(R) volume (L)
CLFZB : 0.3 : anti-CD38 clearance (L/day)
VFZB : 5.0 : anti-CD38 volume (L)
CLIVIG : 0.5 : IVIG clearance (L/day)
VIVIG : 15.0 : IVIG distribution volume (L)
CLGCV : 290.0 : ganciclovir clearance at eGFR 70 (L/day)
VGCV : 45.0 : ganciclovir volume (L)
FGCV : 0.6 : valganciclovir to ganciclovir bioavailability
VGCDOSE : 900.0 : valganciclovir dose (mg/day)
EMAXCNI : 0.93 : maximum calcineurin inhibition
IC50CNI : 5.5 : CNI trough giving half-maximal calcineurin inhibition (ng/mL)
HCNI : 1.6 : Hill coefficient for calcineurin inhibition
EMAXMPA : 0.65 : maximum IMPDH-mediated antiproliferative effect
IC50MPA : 2.5 : MPA concentration for half-maximal effect (mg/L)
EMAXST : 0.9 : maximum glucocorticoid effect
IC50ST : 70.0 : prednisolone-equivalent for half-maximal effect (ng/mL)
EMAXBELA : 0.95 : maximum CD80/86 costimulation blockade
IC50BELA : 2.0 : belatacept concentration for half-maximal blockade (ug/mL)
EMAXBAS : 0.95 : maximum CD25 blockade
IC50BAS : 0.2 : basiliximab concentration for half-maximal CD25 saturation (ug/mL)
EMAXMTOR : 0.85 : maximum mTOR inhibition
IC50MTOR : 4.0 : everolimus concentration for half-maximal mTOR inhibition (ng/mL)
KMAXATG : 2.5 : maximum ATG-mediated T-cell killing rate (1/day)
C50ATG : 8.0 : ATG concentration for half-maximal killing (ug/mL)
KMAXRTX : 0.35 : maximum rituximab-mediated CD20+ B-cell killing rate (1/day)
C50RTX : 1.0 : rituximab concentration for half-maximal killing (ug/mL)
KMAXCD38 : 0.25 : maximum anti-CD38 plasma-cell killing rate (1/day)
C50CD38 : 2.0 : anti-CD38 concentration for half-maximal killing (ug/mL)
EMAXIL6 : 0.9 : maximum IL-6 axis blockade
IC50IL6 : 1.0 : anti-IL-6(R) concentration for half-maximal blockade (ug/mL)
KIVIGN : 0.01 : IVIG-mediated DSA neutralisation rate constant (L/g/day)
KPLEX : 7.0 : plasma exchange IgG removal rate constant during a session (1/day)
KIDES : 15.0 : imlifidase IgG cleavage rate constant (1/day)
EMAXECU : 0.9 : maximum C5 blockade by eculizumab
KAGIN : 0.3 : antigen presentation generation rate (1/day)
KAGOUT : 0.3 : antigen presentation decay rate (1/day)
FPASS : 3.0 : passenger-leucocyte antigen surge multiplier at day 0
KPASS : 0.08 : passenger-leucocyte decay rate (1/day)
GDAMP : 4.0 : amplification of antigen presentation by DAMPs (LOOP 1 gain)
AG50 : 1.0 : antigen load giving half-maximal T-cell signal 1
KTNPROD : 0.02 : naive alloreactive T-cell production (rel/day)
KDTN : 0.02 : naive T-cell loss rate (1/day)
KACT : 0.9 : naive T-cell priming rate constant (1/day)
KACTM : 0.25 : memory T-cell recall rate constant (1/day)
KPROL : 3.0 : maximum IL-2-driven clonal expansion rate (1/day) - the ignition term
TACTMAX : 6.0 : maximum activated blast pool (clonal burst ceiling, rel)
TMEMMAX : 0.9 : maximum alloreactive memory pool (rel)
KDIFF : 0.5 : blast differentiation rate (1/day)
KDTACT : 0.25 : blast loss rate (1/day)
KIL2 : 0.25 : IL-2 concentration for half-maximal proliferative drive (rel)
KIL2P : 24.0 : IL-2 production rate constant (1/day)
KDIL2 : 24.0 : IL-2 elimination rate constant (1/day)
FEFF : 0.85 : fraction of differentiating blasts becoming effectors (rest become memory)
KMIG : 0.5 : effector T-cell migration into the graft (1/day)
KDTEFF : 0.15 : circulating effector loss rate (1/day)
KDTMEM : 0.006 : memory T-cell loss rate (1/day)
FMEMRES : 0.45 : fraction of ATG killing that memory T cells actually sustain
KHOMEO : 0.05 : homeostatic (memory-skewed) repopulation rate after depletion (1/day)
LYMPH0 : 2.2 : lymphocyte pool size defining full repletion (rel)
KTREGP : 0.01 : thymic/constitutive Treg production (rel/day)
KTREGI : 0.02 : peripheral Treg induction from activated blasts (1/day)
KDTREG : 0.05 : Treg loss rate (1/day)
KDINF : 0.35 : graft-infiltrating T-cell clearance rate (1/day)
KAPOP : 2.5 : high-dose glucocorticoid apoptosis of infiltrating lymphocytes (1/day, cubic in effect)
KIFN : 0.6 : interferon-gamma production rate constant (1/day)
KDIFN : 4.0 : interferon-gamma elimination rate (1/day)
KTUB : 0.85 : tubulitis lesion formation rate constant (1/day)
KTUBREP : 0.4 : tubulitis resolution / tubular repair rate (1/day)
KBKTUB : 0.4 : BK nephropathy contribution to the tubulointerstitial lesion (1/day)
KBPROD : 0.03 : alloreactive B-cell production (rel/day)
KDB : 0.03 : alloreactive B-cell loss rate (1/day)
KBACT : 0.1 : B-cell activation rate constant (1/day)
KPROLB : 1.1 : maximum germinal-centre proliferation rate (1/day) - the dnDSA ignition term
KDIFFB : 0.25 : germinal-centre B-cell differentiation rate (1/day)
KDBGC : 0.2 : germinal-centre B-cell loss rate (1/day)
FPB : 0.8 : fraction of differentiating GC B cells becoming plasmablasts
KDPB : 0.15 : plasmablast loss rate (1/day)
KLL : 0.006 : plasmablast to long-lived plasma cell conversion (1/day)
KDLLPC : 0.0015 : long-lived plasma cell loss rate (1/day) - deliberately very small
KIGG : 8.0 : DSA production per unit plasma cell (MFI/rel/day)
WPB : 10.0 : relative per-cell IgG output of plasmablasts
WLL : 1.0 : relative per-cell IgG output of long-lived plasma cells
KDDSA : 0.033 : DSA elimination rate (1/day, IgG t1/2 ~21 d)
KB50 : 5000.0 : DSA MFI giving half-maximal binding to the graft endothelium
BGCMAX : 4.0 : germinal-centre carrying capacity (rel)
TMEM0 : 0.7 : heterologous (virus-primed) cross-reactive memory pool at transplant (rel)
BEPIREF : 0.72 : reference eplet-derived epitope availability (value of BEPI at eplet MM 12)
KBH : 0.55 : Tfh help giving half-maximal germinal-centre proliferation (rel)
KC4D : 1.2 : C4d deposition rate constant (1/day)
KDC4D : 0.6 : C4d clearance rate (1/day)
KMAC : 0.6 : membrane attack complex formation per unit bound DSA
KNK : 0.3 : NK activation rate constant (1/day)
KDNK : 0.6 : NK deactivation rate (1/day)
KENDO : 0.35 : endothelial activation rate constant (1/day)
KDENDO : 0.6 : endothelial deactivation rate (1/day)
KMVI : 0.3 : microvascular inflammation formation rate constant (1/day)
KDMVI : 0.35 : microvascular inflammation resolution rate (1/day)
KTG : 0.01 : transplant glomerulopathy formation rate constant (1/day)
KTG50 : 0.45 : microvascular inflammation giving half-maximal cg formation
KDTG : 0.002 : transplant glomerulopathy regression rate (1/day) - near-irreversible
KDAMP : 0.6 : DAMP generation rate constant (1/day)
KDDAMP : 1.0 : DAMP clearance rate (1/day)
KREC : 0.06 : tubular recovery rate after ischaemia-reperfusion injury (1/day)
KNTCMR : 0.004 : maximum nephron loss rate from TCMR (1/day)
KTUB50 : 0.65 : tubulitis burden at half-maximal nephron destruction
KNMVI : 0.0015 : maximum nephron loss rate from microvascular inflammation (1/day)
KMVI50 : 0.35 : microvascular inflammation at half-maximal nephron destruction
KNTG : 0.0003 : nephron loss rate from transplant glomerulopathy (1/day)
KNIFTA : 6e-05 : nephron loss rate from interstitial fibrosis (1/day)
KNBK : 0.002 : nephron loss rate from BK nephropathy (1/day)
KNHYAL : 3e-05 : nephron loss rate from CNI arteriolopathy (1/day)
KFIB : 0.01 : fibrogenesis rate constant (1/day)
KDFIB : 0.004 : fibrosis resolution rate (1/day)
KHYPER : 0.25 : weight of hyperfiltration stress on TGF-beta (LOOP 2 gain)
HYPMAX : 1.5 : cap on the hyperfiltration stress term
TGFB0 : 0.018 : basal TGF-beta tone
KHYALIN : 0.0008 : CNI arteriolar hyalinosis formation rate (1/day)
KDHYAL : 0.0012 : CNI arteriolar hyalinosis regression rate (1/day)
GFRK : 87.0 : intercept of donor-derived maximum eGFR (mL/min/1.73 m2)
GFRSL : 0.5 : slope of maximum eGFR on KDPI (mL/min per KDPI point)
EXPNM : 0.68 : exponent linking nephron mass to eGFR (allows single-nephron hyperfiltration)
FVASO : 0.3 : maximum CNI-induced fall in eGFR from afferent vasoconstriction
KVASO : 9.0 : CNI exposure at half-maximal vasoconstriction (ng/mL)
FAKI : 0.55 : maximum eGFR reduction from acute tubular injury
GCR : 1200.0 : creatinine generation rate (mg/day, net of tubular secretion)
VCR : 42.0 : creatinine distribution volume (L)
KPROT : 0.05 : proteinuria generation rate constant (1/day)
KDPROT : 0.08 : proteinuria resolution rate (1/day)
PROTB : 0.16 : basal proteinuria drive
KCF : 2.8 : donor-derived cell-free DNA generation rate constant (1/day)
KDCF : 2.8 : donor-derived cell-free DNA elimination rate (1/day, t1/2 ~6 h)
CFB : 0.2 : basal donor-derived cell-free DNA drive (%)
RBK : 0.32 : maximum BK replication rate (1/day)
CBK : 0.34 : maximum BK immune clearance rate (1/day)
BKMAX : 10000000.0 : BK carrying capacity (copies/mL)
BKSEED : 50.0 : BK reactivation seeding rate (copies/mL/day)
KBKN : 0.05 : BK nephropathy formation rate constant (1/day)
KDBKN : 0.02 : BK nephropathy resolution rate (1/day)
RCMV : 0.35 : maximum CMV replication rate (1/day)
CCMV : 0.4 : maximum CMV immune clearance rate (1/day)
CMVMAX : 1000000.0 : CMV carrying capacity (IU/mL)
CMVSEED : 20.0 : CMV reactivation seeding rate (IU/mL/day)
EMAXGCV : 0.55 : maximum ganciclovir antiviral effect (1/day)
IC50GCV : 1.2 : ganciclovir concentration for half-maximal effect (mg/L)
KWBCP : 1.05 : leucocyte production rate (10^9/L/day)
KDWBC : 0.15 : leucocyte loss rate (1/day)
KGLU : 0.1 : fasting glucose turnover rate (1/day)
KDGLU : 0.1 : fasting glucose elimination rate (1/day)
WCNI : 0.42 : weight of calcineurin inhibition in net immunosuppression
WMPA : 0.3 : weight of IMPDH inhibition in net immunosuppression
WST : 0.14 : weight of glucocorticoid effect in net immunosuppression
WCOS : 0.3 : weight of costimulation blockade in net immunosuppression
WIL2 : 0.1 : weight of CD25 blockade in net immunosuppression
WDEPL : 0.35 : weight of lymphodepletion in net immunosuppression
WMTOR : 0.22 : weight of mTOR inhibition in net immunosuppression
H0 : 2.2e-05 : baseline graft-failure hazard (1/day)
B1 : 0.35 : iBox-style hazard coefficient, eGFR (per 10 mL/min below 60)
B2 : 0.55 : iBox-style hazard coefficient, log(1 + proteinuria)
B3 : 0.22 : iBox-style hazard coefficient, microvascular inflammation g+ptc
B4 : 0.35 : iBox-style hazard coefficient, transplant glomerulopathy cg
B5 : 0.15 : iBox-style hazard coefficient, chronicity ci+ct
B6 : 0.3 : iBox-style hazard coefficient, log10 DSA

$CMT @annotated
TAC_A1  : tacrolimus gut transit 1 (mg)
TAC_A2  : tacrolimus gut transit 2 (mg)
TAC_C   : tacrolimus central (mg)
TAC_P   : tacrolimus peripheral (mg)
CSA_C   : cyclosporine central (mg)
CSA_P   : cyclosporine peripheral (mg)
MMF_D   : mycophenolate gut depot, MPA-equivalents (mg)
MPA_C   : mycophenolic acid central (mg)
MPA_P   : mycophenolic acid peripheral (mg)
MPAG    : MPA glucuronide, MPA-equivalents (mg)
PRED_C  : prednisolone central (mg)
MP_C    : methylprednisolone central (mg)
EVR_C   : everolimus central (mg)
ATG_C   : rabbit ATG central (mg)
BAS_C   : basiliximab central (mg)
BELA_C  : belatacept central (mg)
RTX_C   : rituximab central (mg)
TCZ_C   : anti-IL-6(R) central (mg)
FZB_C   : anti-CD38 central (mg)
IVIG_C  : pooled IgG central (g)
GCV_C   : ganciclovir central (mg)
DOSEADJ : TDM dose-adjustment factor (-)
AG      : donor antigen presentation load (-)
TN      : naive alloreactive T cells (rel)
TACT    : activated alloreactive blasts (rel)
TEFF    : circulating effector T cells (rel)
TMEM    : alloreactive memory T cells (rel)
TREG    : regulatory T cells (rel)
TINF    : graft-infiltrating T cells (rel)
IL2     : interleukin-2 (rel)
IFNG    : interferon-gamma (rel)
BN      : naive/memory alloreactive B cells (rel)
BGC     : germinal-centre B cells (rel)
PB      : short-lived plasmablasts (rel)
LLPC    : long-lived bone-marrow plasma cells (rel)
DSA     : donor-specific IgG (MFI)
C4D     : peritubular capillary C4d (0-1)
NKACT   : activated intragraft NK cells (0-1)
ENDO    : endothelial activation (0-1)
MVI     : microvascular inflammation g+ptc (0-1)
TG      : transplant glomerulopathy cg (0-1)
TUB     : tubulitis + interstitial inflammation (0-1)
AKI     : acute tubular injury from IRI (0-1)
DAMP    : danger-signal pool (-)
IFTA    : interstitial fibrosis / tubular atrophy (0-1)
CNIHYAL : CNI arteriolar hyalinosis (0-1)
NM      : functioning nephron mass (fraction of implanted)
SCR     : serum creatinine (mg/L)
PROT    : proteinuria UPCR (g/g)
CFDNA   : donor-derived cell-free DNA (%)
BKV     : plasma BK viral load (copies/mL)
BKVAN   : BK nephropathy burden (0-1)
CMV     : plasma CMV viral load (IU/mL)
WBC     : leucocyte count (10^9/L)
GLU     : fasting glucose index (mmol/L)
NISAUC  : cumulative net immunosuppression (NIS-days)
ADH     : adherence, fraction of doses taken (0-1)
HAZ     : cumulative graft-failure hazard (-)
CUMREJ  : cumulative rejection burden (lesion-days)

$GLOBAL
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif
#define WINK 40.0

// smooth, differentiable rectangular window: 1 between start and start+dur
double win(double tt, double start, double dur) {
  double a = -WINK * (tt - start);
  double b =  WINK * (tt - start - dur);
  if(a >  50.0) a =  50.0;
  if(a < -50.0) a = -50.0;
  if(b >  50.0) b =  50.0;
  if(b < -50.0) b = -50.0;
  return 1.0 / (1.0 + exp(a)) / (1.0 + exp(b));
}

double pos(double x) { return x > 0.0 ? x : 0.0; }

$MAIN
DOSEADJ_0 = 1.0;
TN_0      = 1.0;
BN_0      = 1.0;
TREG_0    = 0.20;
TMEM_0    = TMEM0;           // heterologous, virus-primed cross-reactive memory
NM_0      = 1.0;
SCR_0     = 60.0;            // pre-transplant uraemic creatinine, mg/L (6 mg/dL)
WBC_0     = 7.0;
GLU_0     = 5.2;
ADH_0     = 1.0;
DSA_0     = PREDSA;          // preformed / residual DSA after desensitisation

// ischaemia-reperfusion burden handed over at reperfusion
double AKI0 = 0.25 + 0.020 * (CIT - 12.0) + 0.35 * DCD + 0.004 * (KDPI - 40.0);
AKI_0 = AKI0 > 0.02 ? AKI0 : 0.02;

$ODE
double tt = SOLVERTIME;

// ---------------------------------------------------------------- exposures
double TACAVG = TAC_C / V2TAC * 1000.0;            // ng/mL, average
double TACC0  = RTROUGH * TACAVG;                  // ng/mL, trough
double CSAAVG = CSA_C / V2CSA * 1000.0;
double CSAC0  = RTRCSA * CSAAVG;
double CMPA   = MPA_C / VMPA;                      // mg/L, average
double CPRED  = (PRED_C / VPRED + MP_C / VMP) * 1000.0;   // ng/mL prednisolone-eq
double CEVR   = EVR_C / VEVR * 1000.0;             // ng/mL
double CATG   = ATG_C / VATG;                      // ug/mL
double CBAS   = BAS_C / VBAS;
double CBELA  = BELA_C / VBELA;
double CRTX   = RTX_C / VRTX;
double CTCZ   = TCZ_C / VTCZ;
double CFZB   = FZB_C / VFZB;
double CIVIG  = IVIG_C / VIVIG;                    // g/L
double CGCV   = GCV_C / VGCV;                      // mg/L

// potency-normalised CNI exposure.  Two different equivalences on purpose:
// cyclosporine is relatively MORE vasoconstrictive than it is immunosuppressive,
// which is the mechanistic reason its GFR sits below tacrolimus at equal
// rejection control.
double TACEQ  = TACC0 + CSAC0 / 25.0;
double TACEQV = TACC0 + CSAC0 / 15.0;

// ------------------------------------------------------------- drug effects
double CNINH   = EMAXCNI * pow(TACEQ, HCNI) / (pow(IC50CNI, HCNI) + pow(TACEQ, HCNI) + 1e-12);
double MPAINH  = EMAXMPA * CMPA / (IC50MPA + CMPA);
double STINH   = EMAXST * CPRED / (IC50ST + CPRED);
double COSBLK  = EMAXBELA * CBELA / (IC50BELA + CBELA);
double COSBLKN = COSBLK;                            // naive T: fully blockable
double COSBLKM = COSBLK * (1.0 - FCD28N);           // CD28-null CD57+ Tem escape
double IL2RBLK = EMAXBAS * CBAS / (IC50BAS + CBAS);
double MTORINH = EMAXMTOR * CEVR / (IC50MTOR + CEVR);
double ATGKILL = KMAXATG * CATG / (C50ATG + CATG);
double RTXKILL = KMAXRTX * CRTX / (C50RTX + CRTX);
double CD38KIL = KMAXCD38 * CFZB / (C50CD38 + CFZB);
double IL6BLK  = EMAXIL6 * CTCZ / (IC50IL6 + CTCZ);
double ECUBLK  = EMAXECU * ECUON;
double GCVE    = EMAXGCV * CGCV / (IC50GCV + CGCV);

double LYMPH   = TN + TMEM + TEFF;
double ATGDEPL = pos(1.0 - LYMPH / LYMPH0);

// ------------------------------------- NET IMMUNOSUPPRESSION (the set point)
double NIS = WCNI * CNINH + WMPA * MPAINH + WST * STINH + WCOS * COSBLK
           + WIL2 * IL2RBLK + WDEPL * ATGDEPL + WMTOR * MTORINH;
if(NIS > 0.97) NIS = 0.97;

// ------------------------- LOOP 3: BK screening as a closed-loop controller
// plasma PCR crosses 10^4 copies/mL -> mycophenolate is cut ~60% and the
// tacrolimus target ~30%.  Nothing about this is scheduled.
double BKRED = BKSCREEN / (1.0 + exp(-(log10(BKV + 1.0) - 4.0) / 0.15));

// --------------------------------------------------------------- drug input
double TACTGT = (tt < 90.0 ? TACTGT1 : (tt < 365.0 ? TACTGT2 : TACTGT3)) * (1.0 - 0.30 * BKRED);
double TACIN  = TACON * TACMGKG * WT * 2.0 * ADH * DOSEADJ;
double CSAIN  = CSAON * CSAMGKG * WT * ADH * DOSEADJ;
double MMFIN  = MMFON * MMFDOSE * ADH * (1.0 - 0.60 * BKRED);
double PREDD  = (tt < 7.0 ? 20.0 : (tt < 30.0 ? 10.0 : 5.0)) * (tt < PREDSTOP ? 1.0 : 0.0);
double PREDIN = PREDON * PREDD * FPRED * ADH;
double MPIN   = MPON * MPDOSE * win(tt, MPSTART, MPDAYS);
double EVRIN  = EVRON * EVRDOSE * ADH;
double ATGIN  = ATGON  * ATGMGKG * WT * win(tt, 0.0, ATGDAYS)
              + ATG2ON * ATGMGKG * WT * win(tt, ATG2START, ATGDAYS);
double BASIN  = BASON * 20.0 * (win(tt, 0.0, 1.0) + win(tt, 4.0, 1.0));

double belasum = 0.0;
for(int k = 0; k < 70; k++) belasum += win(tt, 112.0 + 28.0 * k, 1.0);
double BELAIN = BELAON * WT * (10.0 * (win(tt, 0.0, 1.0) + win(tt, 4.0, 1.0) + win(tt, 14.0, 1.0)
              + win(tt, 28.0, 1.0) + win(tt, 56.0, 1.0) + win(tt, 84.0, 1.0)) + 5.0 * belasum);

double RTXIN = RTXON * 700.0 * win(tt, RTXDAY, 1.0);

double tczsum = 0.0;
for(int k = 0; k < (int)TCZN; k++) tczsum += win(tt, TCZSTART + 28.0 * k, 1.0);
double TCZIN = TCZON * 8.0 * WT * tczsum;

double fzbsum = 0.0;
for(int k = 0; k < 5; k++) fzbsum += win(tt, FZBSTART + 14.0 * k, 1.0);
for(int k = 0; k < 4; k++) fzbsum += win(tt, FZBSTART + 70.0 + 28.0 * k, 1.0);
double FZBIN = FZBON * 16.0 * WT * fzbsum;

double IVIGIN = IVIGON * 2000.0 * WT * win(tt, IVIGSTART, 1.0);
double GCVIN  = VGCON * VGCDOSE * FGCV * (tt < VGCSTOP ? 1.0 : 0.0);

double plexsum = 0.0;
for(int k = 0; k < (int)PLEXN; k++) plexsum += win(tt, PLEXSTART + 2.0 * k, 0.2);
double PLEXK = KPLEX * PLEXON * plexsum;
double IDESK = KIDES * IDESON * win(tt, IDESDAY, 1.0);

// ---------------------------------------------------------------------- PK
double CLT = CLTAC * (CYP3A5 > 0.5 ? 1.9 : 1.0) * (1.0 + IPVAMP * sin(2.0 * M_PI * tt / PIPV));

dxdt_TAC_A1 = TACIN - KA_TAC * TAC_A1;
dxdt_TAC_A2 = KA_TAC * TAC_A1 - KA_TAC * TAC_A2;
dxdt_TAC_C  = FTAC * KA_TAC * TAC_A2 - CLT / V2TAC * TAC_C
            - QTAC * (TAC_C / V2TAC - TAC_P / V3TAC);
dxdt_TAC_P  = QTAC * (TAC_C / V2TAC - TAC_P / V3TAC);
dxdt_CSA_C  = 0.30 * CSAIN - CLCSA / V2CSA * CSA_C - QCSA * (CSA_C / V2CSA - CSA_P / V3CSA);
dxdt_CSA_P  = QCSA * (CSA_C / V2CSA - CSA_P / V3CSA);

// mycophenolate with explicit enterohepatic recirculation (~30-40% of AUC)
dxdt_MMF_D = MMFIN + KBIL * FEHC * MPAG - KA_MPA * MMF_D;
dxdt_MPA_C = FMPA * KA_MPA * MMF_D - CLMPA / VMPA * MPA_C - QMPA * (MPA_C / VMPA - MPA_P / V3MPA);
dxdt_MPA_P = QMPA * (MPA_C / VMPA - MPA_P / V3MPA);
dxdt_MPAG  = CLMPA / VMPA * MPA_C - (KBIL + KREN) * MPAG;

dxdt_PRED_C = PREDIN - CLPRED / VPRED * PRED_C;
dxdt_MP_C   = MPIN   - CLMP / VMP * MP_C;
dxdt_EVR_C  = 0.20 * EVRIN - CLEVR / VEVR * EVR_C;
dxdt_ATG_C  = ATGIN  - CLATG / VATG * ATG_C;
dxdt_BAS_C  = BASIN  - CLBAS / VBAS * BAS_C;
dxdt_BELA_C = BELAIN - CLBELA / VBELA * BELA_C;
dxdt_RTX_C  = RTXIN  - CLRTX / VRTX * RTX_C;
dxdt_TCZ_C  = TCZIN  - CLTCZ / VTCZ * TCZ_C;
dxdt_FZB_C  = FZBIN  - CLFZB / VFZB * FZB_C;
dxdt_IVIG_C = IVIGIN / 1000.0 - CLIVIG / VIVIG * IVIG_C;

// ------------------------------------------------ graft haemodynamics / GFR
double NMs    = NM > 1e-3 ? NM : 1e-3;
double HYPER  = 1.0 / (NM > 0.15 ? NM : 0.15) - 1.0;
if(HYPER > HYPMAX) HYPER = HYPMAX;
if(HYPER < 0.0)    HYPER = 0.0;
double VASO   = FVASO * TACEQV / (TACEQV + KVASO);
double AKIF   = AKI / (AKI + 0.35);
double GFRMAX = GFRK - GFRSL * KDPI;
double EGFR   = GFRMAX * pow(NMs, EXPNM) * (1.0 - VASO) * (1.0 - FAKI * AKIF);

dxdt_GCV_C = GCVIN - CLGCV * (EGFR / 70.0) / VGCV * GCV_C;

// ------------------------------------ TDM: an integral controller, bounded
// C0MEAS is what the CLINIC sees.  In a non-adherent patient the sample is
// drawn after a dose that was actually taken, so the measured trough looks
// normal while true exposure is ADH-fold lower -> no dose correction happens.
double ADHm   = ADH > 0.25 ? ADH : 0.25;
double C0MEAS = TACC0 / ADHm;
double TDMERR = TACON > 0.5 ? (TACTGT - C0MEAS) / TACTGT
                            : (200.0 - CSAC0 / ADHm) / 200.0;
double TDMBRK = TDMERR > 0.0 ? (1.0 - DOSEADJ / DOSEMAX) : (DOSEADJ / DOSEMAX);
dxdt_DOSEADJ  = TDM * KTDM * DOSEADJ * TDMERR * pos(TDMBRK) / (1.0 + exp(-(tt - 3.0)));

// ----------------------------------------------------- LOOP 1: alloimmunity
double AGLOAD = 0.30 + 0.70 * HLAMM / 6.0;
double BEPI   = 0.30 + 0.70 * EPLET / 20.0;
dxdt_AG = KAGIN * AGLOAD * (1.0 + FPASS * exp(-KPASS * tt)) * (1.0 + GDAMP * DAMP)
        - KAGOUT * AG;
double S1 = AG / (AG50 + AG);

double ACT   = KACT  * TN   * S1 * (1.0 - COSBLKN) * (1.0 - 0.5 * STINH);
double ACTM  = KACTM * TMEM * S1 * (1.0 - COSBLKM) * (1.0 - 0.4 * STINH);
double IL2DR = IL2 / (KIL2 + IL2);
// autocatalytic (IL-2-driven) clonal expansion: the ignition term
double PROLT = KPROL * TACT * S1 * IL2DR * pos(1.0 - TACT / TACTMAX)
             * (1.0 - CNINH) * (1.0 - MPAINH) * (1.0 - IL2RBLK) * (1.0 - MTORINH);

dxdt_TN   = KTNPROD - ACT - KDTN * TN - ATGKILL * TN;
dxdt_TACT = ACT + ACTM + PROLT - KDIFF * TACT - KDTACT * TACT - ATGKILL * TACT;
dxdt_TEFF = KDIFF * TACT * FEFF - KMIG * TEFF - KDTEFF * TEFF - ATGKILL * TEFF;
dxdt_TMEM = KDIFF * TACT * (1.0 - FEFF) * pos(1.0 - TMEM / TMEMMAX)
          + KHOMEO * TMEM * pos(1.0 - LYMPH / LYMPH0)          // post-depletion skew
          - KDTMEM * TMEM - ATGKILL * FMEMRES * TMEM;
dxdt_TREG = KTREGP + KTREGI * TACT * (1.0 - 0.7 * CNINH) * (1.0 + 0.8 * MTORINH)
          - KDTREG * TREG - 0.6 * ATGKILL * TREG;
double SUP = TREG / (TREG + TEFF + 0.05);
dxdt_TINF = KMIG * TEFF * (1.0 + 2.0 * ENDO / (1.0 + ENDO))
          - KDINF * TINF * (1.0 + 2.0 * SUP) - ATGKILL * TINF
          - KAPOP * pow(STINH, 3.0) * TINF;   // apoptosis is a HIGH-dose steroid effect
dxdt_IL2  = KIL2P * TACT * (1.0 - CNINH) * (1.0 - 0.6 * STINH) - KDIL2 * IL2;
dxdt_IFNG = KIFN * (TINF + 0.3 * NKACT) * (1.0 - 0.6 * STINH) - KDIFN * IFNG;

// --------------------------------------------------- B cells -> DSA -> ABMR
double TFH   = TACT;
double BHELP = TFH * (1.0 - 0.6 * IL6BLK) * (1.0 - 0.85 * COSBLKN);
double BACT  = KBACT * BN * S1 * BEPI * (0.02 + BHELP);
dxdt_BN  = KBPROD - BACT - KDB * BN - RTXKILL * BN;
// GC proliferation is the second ignition term: needs help, scales with eplet
// load, and is what mycophenolate actually prevents
dxdt_BGC = BACT + KPROLB * BGC * pos(1.0 - BGC / BGCMAX) * BHELP / (KBH + BHELP)
         * sqrt(BEPI / BEPIREF) * (1.0 - MPAINH) * (1.0 - MTORINH) * (1.0 - 0.5 * IL6BLK)
         - KDIFFB * BGC - KDBGC * BGC - RTXKILL * BGC;
dxdt_PB   = KDIFFB * BGC * FPB - KDPB * PB - CD38KIL * PB - KLL * PB;
// long-lived plasma cells are CD20-NEGATIVE: rituximab has no term here.
dxdt_LLPC = KLL * PB - KDLLPC * LLPC - 0.6 * CD38KIL * LLPC;
dxdt_DSA  = KIGG * (PB * WPB + LLPC * WLL) - KDDSA * DSA
          - PLEXK * DSA - IDESK * DSA - KIVIGN * CIVIG * DSA;

double DSAB = DSA / (DSA + KB50);                  // saturable binding to the graft
double MAC  = KMAC * DSAB * (1.0 - ECUBLK);        // eculizumab blocks MAC, not C4d
dxdt_C4D   = KC4D * DSAB * (1.0 - C4D) - KDC4D * C4D;
dxdt_NKACT = KNK * (DSAB * 1.5 + MISSSELF * DSAB * 0.8 + 0.05 * MISSSELF) * (1.0 - NKACT)
           - KDNK * NKACT - 0.8 * CD38KIL * NKACT;
dxdt_ENDO  = KENDO * (MAC + 0.7 * NKACT + 0.25 * IFNG + 0.3 * DAMP) * (1.0 - ENDO)
           - KDENDO * ENDO;
dxdt_MVI   = KMVI * (NKACT + MAC + 0.4 * TINF) * (1.0 - MVI) - KDMVI * MVI * (1.0 + 0.5 * STINH);
dxdt_TG    = KTG * MVI * MVI / (MVI * MVI + KTG50 * KTG50) * (1.0 - 0.4 * MTORINH)
           * (1.0 - TG) - KDTG * TG;

// ------------------------------------------------------------ graft lesions
dxdt_TUB  = (KTUB * TINF * (1.0 - 0.7 * SUP) + KBKTUB * BKVAN) * (1.0 - TUB)
          - KTUBREP * TUB * (1.0 + 0.8 * STINH);
dxdt_AKI  = -KREC * AKI * (1.0 - 0.35 * MTORINH);          // mTORi impairs repair
dxdt_DAMP = KDAMP * (AKI + 0.5 * TUB + 0.4 * MVI) - KDDAMP * DAMP;

// LOOP 2: the drug-independent chronic loop
double TGFB = TGFB0 + 0.20 * TUB + 0.30 * MVI + 0.50 * AKI + 0.10 * CNIHYAL
            + KHYPER * HYPER + 0.20 * PROT;
dxdt_IFTA    = KFIB * TGFB * (1.0 - IFTA) - KDFIB * IFTA;
dxdt_CNIHYAL = KHYALIN * TACEQ / (TACEQ + 8.0) * (1.0 - CNIHYAL) - KDHYAL * CNIHYAL;

// nephron destruction: cubic kernels, so trace inflammation is survivable and
// a full-blown lesion is not
double LOSST = KNTCMR * pow(TUB, 3.0) / (pow(TUB, 3.0) + pow(KTUB50, 3.0));
double LOSSM = KNMVI  * pow(MVI, 3.0) / (pow(MVI, 3.0) + pow(KMVI50, 3.0));
dxdt_NM = -(LOSST + LOSSM + KNTG * TG + KNIFTA * IFTA + KNBK * BKVAN + KNHYAL * CNIHYAL) * NM;

dxdt_SCR   = (GCR - EGFR * 1.44 * SCR) / VCR;
dxdt_PROT  = KPROT * (PROTB + 0.6 * TG + 0.3 * MVI + 0.25 * IFTA + 0.4 * MTORINH)
           - KDPROT * PROT;
dxdt_CFDNA = KCF * (CFB + 0.8 * TUB + 2.2 * MVI + 1.2 * TG + 1.5 * AKI + 0.4 * BKVAN)
           - KDCF * CFDNA;

// ---------------------------------------- the other arm of the U: infection
dxdt_BKV   = BKV * (RBK * (0.25 + 0.75 * NIS) * (1.0 - BKV / BKMAX) - CBK * (1.0 - NIS))
           + BKSEED * BKSUSC;
dxdt_BKVAN = KBKN * pos(log10(BKV + 1.0) - 4.0) / 3.0 * (1.0 - BKVAN) - KDBKN * BKVAN;
double CMVIMM = 1.0 - CMVDR;
dxdt_CMV = CMV * (RCMV * (0.20 + 0.80 * NIS) * (1.0 - CMV / CMVMAX)
         - CCMV * (1.0 - NIS) * (1.0 + 2.0 * CMVIMM) - GCVE) + CMVSEED * CMVSUSC;

double GCVMY = CGCV / (CGCV + 2.0);
dxdt_WBC = KWBCP * (1.0 - 0.55 * MPAINH - 0.45 * GCVMY) - KDWBC * WBC - 0.25 * ATGKILL * WBC;
double TACF = TACEQ / (TACEQ + 10.0);
dxdt_GLU = KGLU * (5.2 + 2.2 * STINH + 1.2 * TACF) - KDGLU * GLU;
dxdt_NISAUC = NIS;

// ------------------------------------------------------------- behaviour
double ADHTGT = (tt >= ADHSTART && tt < ADHEND) ? ADHFINAL : 1.0;
dxdt_ADH = KADHR * (ADHTGT - ADH);

// ----------------------------------------------- outcome (iBox-style hazard)
double BG   = 3.0 * MVI * MVI / (MVI * MVI + 0.0900);
double BPTC = 3.0 * MVI * MVI / (MVI * MVI + 0.0625);
double BCG  = 3.0 * TG * TG / (TG * TG + 0.1225);
double BCI  = 3.0 * IFTA * IFTA / (IFTA * IFTA + 0.0900);
double HR = exp(B1 * (60.0 - EGFR) / 10.0 + B2 * log(1.0 + PROT) + B3 * (BG + BPTC)
          + B4 * BCG + B5 * 2.0 * BCI + B6 * log10(1.0 + DSA / 1000.0));
dxdt_HAZ = H0 * HR;
dxdt_CUMREJ = 1.0 / (1.0 + exp(-(TUB - 0.5) / 0.1)) + 1.0 / (1.0 + exp(-(MVI - 0.5) / 0.1));

$TABLE
// Reported quantities are recomputed here from the states (rather than carried
// out of $ODE) so that every output is exactly consistent with the state vector
// at the output time.
double TACAVGr = TAC_C / V2TAC * 1000.0;
double TACC0r  = RTROUGH * TACAVGr;
double CSAAVGr = CSA_C / V2CSA * 1000.0;
double CSAC0r  = RTRCSA * CSAAVGr;
double CMPAr   = MPA_C / VMPA;
double MPAAUC  = CMPAr * 12.0;                       // mg.h/L over a dosing interval
double MPAC0   = RTRMPA * CMPAr;
double CPREDr  = (PRED_C / VPRED + MP_C / VMP) * 1000.0;
double CEVRr   = EVR_C / VEVR * 1000.0;
double EVRC0   = RTREVR * CEVRr;
double CATGr   = ATG_C / VATG;
double CBELAr  = BELA_C / VBELA;
double CRTXr   = RTX_C / VRTX;
double CTCZr   = TCZ_C / VTCZ;
double CFZBr   = FZB_C / VFZB;

double TACEQr  = TACC0r + CSAC0r / 25.0;
double TACEQVr = TACC0r + CSAC0r / 15.0;
double CNINHr  = EMAXCNI * pow(TACEQr, HCNI) / (pow(IC50CNI, HCNI) + pow(TACEQr, HCNI) + 1e-12);
double MPAINHr = EMAXMPA * CMPAr / (IC50MPA + CMPAr);
double STINHr  = EMAXST * CPREDr / (IC50ST + CPREDr);
double COSBLKr = EMAXBELA * CBELAr / (IC50BELA + CBELAr);
double IL2RBr  = EMAXBAS * (BAS_C / VBAS) / (IC50BAS + BAS_C / VBAS);
double MTORr   = EMAXMTOR * CEVRr / (IC50MTOR + CEVRr);
double LYMPHr  = TN + TMEM + TEFF;
double ATGDr   = LYMPHr < LYMPH0 ? (1.0 - LYMPHr / LYMPH0) : 0.0;
double NISr    = WCNI * CNINHr + WMPA * MPAINHr + WST * STINHr + WCOS * COSBLKr
               + WIL2 * IL2RBr + WDEPL * ATGDr + WMTOR * MTORr;
if(NISr > 0.97) NISr = 0.97;

double NMr    = NM > 1e-3 ? NM : 1e-3;
double VASOr  = FVASO * TACEQVr / (TACEQVr + KVASO);
double AKIFr  = AKI / (AKI + 0.35);
double EGFRr  = (GFRK - GFRSL * KDPI) * pow(NMr, EXPNM) * (1.0 - VASOr) * (1.0 - FAKI * AKIFr);
double SCRDL  = SCR / 10.0;                          // mg/dL

// Banff-style semi-quantitative scores (0-3), squared-Hill mappings
double BANFF_T   = 3.0 * TUB * TUB / (TUB * TUB + 0.1225);
double BANFF_I   = 3.0 * TUB * TUB / (TUB * TUB + 0.1000);
double BANFF_G   = 3.0 * MVI * MVI / (MVI * MVI + 0.0900);
double BANFF_PTC = 3.0 * MVI * MVI / (MVI * MVI + 0.0625);
double BANFF_CG  = 3.0 * TG * TG / (TG * TG + 0.1225);
double BANFF_CI  = 3.0 * IFTA * IFTA / (IFTA * IFTA + 0.0900);
double BANFF_AH  = 3.0 * CNIHYAL * CNIHYAL / (CNIHYAL * CNIHYAL + 0.0900);
double BANFF_C4D = 3.0 * C4D;
double MVISUM    = BANFF_G + BANFF_PTC;              // g+ptc, the ABMR criterion

double BKLOG  = log10(BKV + 1.0);
double CMVLOG = log10(CMV + 1.0);
double GS     = exp(-HAZ);                           // death-censored graft survival
double AKI0t  = 0.25 + 0.020 * (CIT - 12.0) + 0.35 * DCD + 0.004 * (KDPI - 40.0);
double DGF    = AKI0t > 0.45 ? 1.0 : 0.0;

$CAPTURE @annotated
TACC0r   : tacrolimus trough C0 (ng/mL)
CSAC0r   : cyclosporine trough C0 (ng/mL)
CMPAr    : MPA average concentration (mg/L)
MPAAUC   : MPA AUC0-12 (mg*h/L)
MPAC0    : MPA trough (mg/L)
CPREDr   : prednisolone-equivalent (ng/mL)
EVRC0    : everolimus trough (ng/mL)
CATGr    : rabbit ATG (ug/mL)
CBELAr   : belatacept (ug/mL)
CRTXr    : rituximab (ug/mL)
CTCZr    : anti-IL-6(R) (ug/mL)
CFZBr    : anti-CD38 (ug/mL)
CNINHr   : calcineurin inhibition (0-1)
MPAINHr  : IMPDH inhibition (0-1)
STINHr   : glucocorticoid effect (0-1)
COSBLKr  : costimulation blockade (0-1)
MTORr    : mTOR inhibition (0-1)
ATGDr    : lymphodepletion (0-1)
NISr     : NET IMMUNOSUPPRESSION (0-1)
EGFRr    : eGFR (mL/min/1.73 m2)
SCRDL    : serum creatinine (mg/dL)
BANFF_T  : Banff t, tubulitis (0-3)
BANFF_I  : Banff i, interstitial inflammation (0-3)
BANFF_G  : Banff g, glomerulitis (0-3)
BANFF_PTC: Banff ptc, capillaritis (0-3)
BANFF_CG : Banff cg, transplant glomerulopathy (0-3)
BANFF_CI : Banff ci, interstitial fibrosis (0-3)
BANFF_AH : Banff ah, arteriolar hyalinosis (0-3)
BANFF_C4D: C4d score (0-3)
MVISUM   : microvascular inflammation g+ptc (0-6)
BKLOG    : plasma BK viral load (log10 copies/mL)
CMVLOG   : plasma CMV viral load (log10 IU/mL)
GS       : death-censored graft survival probability
DGF      : delayed graft function flag
'

mod <- mcode("ktx", code)

# =============================================================================
#  SCENARIOS
#  Each scenario is a pure parameter set - no dosing events, no scripted
#  interventions, so any two scenarios differ only by the numbers listed here.
# =============================================================================

TEND <- 1825   # 5 years

ABMR <- list(ADHSTART = 365, ADHFINAL = 0.45, ADHEND = 730)   # dnDSA, then re-engaged
TCMR <- list(ADHSTART = 25,  ADHFINAL = 0.10, ADHEND = 95, KADHR = 0.06)
HIGH <- list(HLAMM = 5, EPLET = 22, CPRA = 85, PREDSA = 1500)

scenarios <- list(

  "01 Standard risk (TAC/MPA/steroid + basiliximab)" = list(),

  "02 Living donor, low mismatch, CIT 2 h" = list(
    CIT = 2, KDPI = 20, HLAMM = 2, EPLET = 7),

  "03 High immunological risk + ATG induction" = c(HIGH, list(ATGON = 1, BASON = 0)),

  "04 High immunological risk + basiliximab only" = HIGH,

  "05 CYP3A5 expresser, fixed mg/kg dose (no TDM)" = list(CYP3A5 = 1, TDM = 0),

  "06 CYP3A5 expresser, genotype-guided TDM" = list(CYP3A5 = 1, TDM = 1),

  "07 Belatacept, CNI-free maintenance" = list(TACON = 0, BELAON = 1, TDM = 0),

  "08 Belatacept in a CD28-null-rich recipient" = list(
    TACON = 0, BELAON = 1, TDM = 0, FCD28N = 0.80),

  "09 Cyclosporine-based comparator" = list(TACON = 0, CSAON = 1),

  "10 Early steroid withdrawal (day 7)" = list(PREDSTOP = 7),

  "11 Everolimus + reduced-exposure CNI (MPA-free)" = list(
    EVRON = 1, MMFON = 0, TACTGT1 = 5, TACTGT2 = 4, TACTGT3 = 4),

  "12 Non-adherence from month 12 (45% of doses)" = list(ADHSTART = 365, ADHFINAL = 0.45),

  "13 Non-adherence from month 12 (60% of doses)" = list(ADHSTART = 365, ADHFINAL = 0.60),

  "14 High eplet load (DR/DQ eplet MM 24)" = list(EPLET = 24, HLAMM = 5),

  "15 High tacrolimus intra-patient variability" = list(IPVAMP = 0.60, PIPV = 21),

  "16 BK viraemia WITH screening + IS reduction" = list(BKSUSC = 1, BKSCREEN = 1),

  "17 BK viraemia WITHOUT screening" = list(BKSUSC = 1, BKSCREEN = 0),

  "18 Banff IIA TCMR (adherence gap) + MP pulse" = c(TCMR, list(MPON = 1, MPSTART = 95)),

  "19 Steroid-resistant TCMR -> ATG rescue" = c(TCMR, list(
    MPON = 1, MPSTART = 95, EMAXST = 0.45, ATG2ON = 1, ATG2START = 105)),

  "20 dnDSA ABMR - adherence restored only (control)" = ABMR,

  "21 dnDSA ABMR - PLEX + IVIG + rituximab" = c(ABMR, list(
    PLEXON = 1, PLEXSTART = 730, IVIGON = 1, IVIGSTART = 740, RTXON = 1, RTXDAY = 742)),

  "22 dnDSA ABMR - anti-IL-6 (tocilizumab/clazakizumab)" = c(ABMR, list(
    TCZON = 1, TCZSTART = 730, TCZN = 18)),

  "23 dnDSA ABMR - anti-CD38 (felzartamab)" = c(ABMR, list(FZBON = 1, FZBSTART = 730)),

  "24 DCD donor, CIT 24 h, KDPI 85 (DGF, low nephron dose)" = list(
    DCD = 1, CIT = 24, KDPI = 85),

  "25 CMV D+/R- with 200-day valganciclovir" = list(
    CMVDR = 1, CMVSUSC = 1, VGCSTOP = 200),

  "26 No maintenance immunosuppression (untreated control)" = list(
    TACON = 0, MMFON = 0, PREDON = 0, BASON = 0, TDM = 0)
)

run_scen <- function(nm, pars) {
  m <- if (length(pars)) param(mod, pars) else mod
  out <- m %>%
    mrgsim(end = TEND, delta = 1, hmax = 3, atol = 1e-8, rtol = 1e-5) %>%
    as_tibble()
  out$scenario <- nm
  out
}

message("Simulating ", length(scenarios), " scenarios ...")
sim <- bind_rows(lapply(names(scenarios), function(nm) run_scen(nm, scenarios[[nm]])))

# =============================================================================
#  SUMMARY TABLE
# =============================================================================
at <- function(d, x, tt) x[which.min(abs(tt - d))]

summary_tbl <- sim %>%
  group_by(scenario) %>%
  summarise(
    C0_m6      = round(at(180,  TACC0r,   time), 1),
    MPA_AUC    = round(at(180,  MPAAUC,   time), 0),
    NIS_m6     = round(at(180,  NISr,     time), 2),
    eGFR_m12   = round(at(365,  EGFRr,    time), 1),
    eGFR_y5    = round(at(1825, EGFRr,    time), 1),
    slope_y1_5 = round((at(1825, EGFRr, time) - at(365, EGFRr, time)) / 4, 2),
    peak_t     = round(max(BANFF_T), 2),
    peak_gptc  = round(max(MVISUM),  2),
    DSA_y5     = round(at(1825, DSA,      time), 0),
    cg_y5      = round(at(1825, BANFF_CG, time), 2),
    ci_y5      = round(at(1825, BANFF_CI, time), 2),
    UPCR_y5    = round(at(1825, PROT,     time), 2),
    BK_peak    = round(max(BKLOG), 2),
    graft_surv = round(at(1825, GS,       time), 3),
    .groups = "drop"
  ) %>%
  arrange(scenario)

cat("\n=========== 5-YEAR SCENARIO SUMMARY ===========\n")
print(as.data.frame(summary_tbl), row.names = FALSE)

# =============================================================================
#  VALIDATION AGAINST PUBLISHED ANCHORS
#  These are qualitative phenotype checks, not fitted targets - see the header.
# =============================================================================
chk <- function(label, value, lo, hi, unit = "") {
  ok <- !is.na(value) && value >= lo && value <= hi
  cat(sprintf("  [%s] %-56s %8.2f %-12s (target %g-%g)\n",
              if (ok) "PASS" else "FAIL", label, value, unit, lo, hi))
  ok
}
g <- function(scn, col, d) {
  s <- sim[sim$scenario == scn, ]
  at(d, s[[col]], s$time)
}
S01 <- "01 Standard risk (TAC/MPA/steroid + basiliximab)"
S07 <- "07 Belatacept, CNI-free maintenance"
S09 <- "09 Cyclosporine-based comparator"
S12 <- "12 Non-adherence from month 12 (45% of doses)"
S26 <- "26 No maintenance immunosuppression (untreated control)"

cat("\n=========== VALIDATION ===========\n")
res <- c(
  chk("Standard: tacrolimus trough at month 6",        g(S01, "TACC0r", 180),  5,   8,  "ng/mL"),
  chk("Standard: MPA AUC0-12 at month 6",              g(S01, "MPAAUC", 180),  30,  60, "mg*h/L"),
  chk("Standard: eGFR at 12 months",                   g(S01, "EGFRr", 365),   52,  62, "mL/min"),
  chk("Standard: eGFR slope y1-y5",
      (g(S01, "EGFRr", 1825) - g(S01, "EGFRr", 365)) / 4,                      -2.5, -0.3, "mL/min/y"),
  chk("Standard: no dnDSA at 5 years (< 1000 MFI)",    g(S01, "DSA", 1825),    0,   1000, "MFI"),
  chk("Standard: serum creatinine at 12 months",       g(S01, "SCRDL", 365),   1.0, 1.8, "mg/dL"),
  chk("Belatacept: eGFR at 12 months above tacrolimus",
      g(S07, "EGFRr", 365) - g(S01, "EGFRr", 365),                             4,   18, "mL/min"),
  chk("Cyclosporine: eGFR at 12 months below tacrolimus",
      g(S01, "EGFRr", 365) - g(S09, "EGFRr", 365),                             1,   10, "mL/min"),
  chk("Non-adherence: dnDSA above 1500 MFI by year 5", g(S12, "DSA", 1825),    1500, 40000, "MFI"),
  chk("Non-adherence: chronic ABMR (cg) at year 5",    g(S12, "BANFF_CG", 1825), 1.0, 3.0, "score"),
  chk("Untreated: Banff t reaches >= 2 within 30 d",
      max(sim$BANFF_T[sim$scenario == S26 & sim$time <= 30]),                  2.0, 3.0, "score"),
  chk("Untreated: graft function lost by year 5",      g(S26, "EGFRr", 1825),  0,   20, "mL/min")
)
cat(sprintf("\n  %d/%d checks passed\n", sum(res), length(res)))

# =============================================================================
#  OPTIONAL PLOTS
# =============================================================================
if (requireNamespace("ggplot2", quietly = TRUE)) {
  library(ggplot2)
  key <- c(S01, S07, S09, S12, S26,
           "17 BK viraemia WITHOUT screening",
           "24 DCD donor, CIT 24 h, KDPI 85 (DGF, low nephron dose)")
  p <- sim %>%
    filter(scenario %in% key) %>%
    select(time, scenario, eGFR = EGFRr, DSA, `Banff t` = BANFF_T,
           `g+ptc` = MVISUM, `BK log10` = BKLOG, `NIS` = NISr) %>%
    pivot_longer(-c(time, scenario)) %>%
    ggplot(aes(time / 365.25, value, colour = scenario)) +
    geom_line(linewidth = 0.6) +
    facet_wrap(~name, scales = "free_y") +
    labs(x = "years after transplant", y = NULL,
         title = "Kidney transplant QSP model - key scenarios") +
    theme_bw(base_size = 9) +
    theme(legend.position = "bottom", legend.text = element_text(size = 6)) +
    guides(colour = guide_legend(ncol = 2))
  ggsave("ktx_scenarios.png", p, width = 11, height = 7, dpi = 150)
  message("wrote ktx_scenarios.png")
}

invisible(sim)
