##  SIADH (Syndrome of Inappropriate Antidiuretic Hormone Secretion) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : SIADH — non-osmotic/autonomous AVP release driving renal V2-
##             receptor/aquaporin-2 hyperfunction, euvolemic dilutional
##             hyponatremia, cerebral adaptation, and correction-rate-dependent
##             osmotic demyelination syndrome (ODS) risk.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 19 ODE compartments — oral/IV drug PK for tolvaptan, conivaptan,
##             demeclocycline, oral urea, and a hypertonic-saline infusion
##             driver + renal V2R/AQP2 functional-expression network + water/
##             sodium balance (TBW, free-water clearance, serum Na, serum &
##             urine osmolality, urine Na) + cerebral-adaptation and 24h/48h
##             sodium-correction-rate trackers feeding a neuro-symptom score
##             and an osmotic-demyelination-syndrome (ODS) risk accumulator.
##  Time     : days (study horizon 0-14 d acute-inpatient default; chronic
##             outpatient scenarios can run to 90 d).
##  Units    : oral/IV drug "exposure" compartments in arbitrary dose-
##             proportional units (au) — this library's standard surrogate for
##             a fully mechanistic plasma PK model when the disease-relevant
##             PD (V2R/AQP2 occupancy) is what matters; physiological states in
##             clinically familiar units (mEq/L, mOsm/kg, L) — see [CMT] below.
##  Scenarios: 7 prebuilt — see SIADH_simulate_scenarios() at bottom, including
##             a deliberately unsafe "overly rapid correction" teaching case.
##  Anchors  : SALT-1/SALT-2 tolvaptan trials (Schrier 2006 NEJM 355:2099);
##             conivaptan (Ghali 2006 J Clin Endocrinol Metab; Verbalis 2008);
##             demeclocycline (Forrest 1978 NEJM 298:173; De Troyer 1977);
##             hyponatremia correction-rate guidelines (Verbalis 2013 Am J Med
##             126:S1; Spasovski 2014 Eur J Endocrinol 170:G1); osmotic
##             demyelination syndrome (Sterns 1986 NEJM 314:1535; Sterns 2010);
##             Bartter & Schwartz 1967 Am J Med 42:790 (original description);
##             Robertson 2001 Am J Med 119:S36 (SIADH subtype classification).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of SIADH linking non-osmotic/autonomous AVP drive, renal V2-receptor
and aquaporin-2 functional expression, water/sodium balance (free-water
clearance, total body water, serum sodium, serum/urine osmolality), cerebral
osmotic adaptation, and correction-rate-dependent osmotic-demyelination risk to
a composite neuro-symptom score, with mechanistic PK/PD for tolvaptan,
conivaptan, demeclocycline, oral urea, and hypertonic saline.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease severity & etiology
SEV          : 0.6   : SIADH severity (0=none, 1=severe non-osmotic AVP drive)
ECTOPIC      : 0     : 1 = ectopic/malignancy-associated AVP source (SCLC etc.; higher, less feedback-suppressible severity ceiling)
CHRONIC      : 1     : 1 = chronic (>=48h, cerebral adaptation established) vs 0 = acute (<48h, not yet adapted)
FLUID_RESTRICT: 0    : 1 = fluid restriction <1 L/day (first-line therapy)
LOOP_SALT    : 0     : 1 = loop diuretic + oral salt tablets adjunct
SGLT2I       : 0     : 1 = SGLT2 inhibitor adjunct (emerging, osmotic diuresis)
BASE_NA      : 122   : mEq/L, starting serum sodium

//--- Tolvaptan 15-60mg PO QD (vaptan, selective V2 antagonist)
KA_TOLVA     : 1.8   : 1/day, oral absorption
KOUT_TOLVA   : 0.85  : 1/day, elimination
EC50_TOLVA   : 1.1   : au, exposure for half-maximal V2 blockade
EMAX_TOLVA   : 0.85  : max fractional V2-receptor blockade

//--- Conivaptan IV 20mg load + 20-40mg/day infusion (dual V1a/V2 antagonist, inpatient)
KOUT_CONIV   : 2.2   : 1/day, faster IV turnover
EC50_CONIV   : 1.0
EMAX_CONIV   : 0.80  : max fractional V2-receptor blockade

//--- Demeclocycline 600-1200mg/day PO (induces partial nephrogenic DI, post-receptor)
KA_DEMEC     : 1.2
KOUT_DEMEC   : 0.55  : slower onset (days) than vaptans
EC50_DEMEC   : 1.2
EMAX_DEMEC   : 0.70  : max fractional post-receptor AQP2 blockade

//--- Oral urea (osmotic diuresis / solute-load therapy)
KA_UREA      : 2.0
KOUT_UREA    : 1.6
EC50_UREA    : 1.0
EMAX_UREA    : 0.35  : max fractional free-water-clearance increase

//--- Hypertonic saline 3% (acute severe/symptomatic correction, direct osmotic Na input)
KOUT_HSAL    : 1.4   : 1/day, infusion-effect turnover
GAIN_HSAL_NA : 3.2   : mEq/L per unit HSAL cleared -> direct Na rise

//--- Renal V2R / AQP2 functional expression
AQP2_BASE    : 25    : a.u., normal unstimulated AQP2 apical expression
K_AQP_SEV    : 3.2   : fractional AQP2 upregulation per unit severity
AQP2_MAX     : 100
KOUT_AQP2    : 0.55
DDAVP_CLAMP  : 0     : 1 = controlled co-administration preventing AQP2 collapse (overcorrection-prevention clamp)
AQP2_CLAMP_FLOOR: 55 : a.u., minimum AQP2 maintained when DDAVP_CLAMP=1

//--- Free-water clearance & total body water
FWCL_MAX     : 1.6   : L/day-equivalent, max free-water excretion capacity
WATER_INTAKE_BASE: 2.2 : L/day-equivalent baseline free-water intake
KOUT_TBW     : 0.35
TBW_NORMAL   : 42    : L, normal total body water (70kg adult surrogate)

//--- Serum sodium / osmolality
NA_NORMAL    : 140   : mEq/L
KOUT_NA      : 0.30
OSM_OFFSET   : 10    : mOsm/kg, glucose/BUN contribution
KOUT_OSM     : 0.9   : fast equilibration to Na-driven osmolality

//--- Urine osmolality / urine sodium
UOSM_MIN     : 50
UOSM_MAX     : 900
KOUT_UOSM    : 0.8
UNA_BASE     : 25    : mEq/L
K_UNA_TBW    : 4.0
UNA_LOOP_SALT_ADD: 20
KOUT_UNA     : 0.6

//--- Cerebral adaptation
BRAINOSM_NORMAL: 100 : a.u., normal brain organic-osmolyte content
K_BRAINOSM_ADAPT: 0.9 : fractional osmolyte depletion per mEq/L chronic deficit
KOUT_BRAINOSM: 0.12   : slow (days) adaptation/repletion kinetics

//--- Correction-rate trackers
TAU24        : 1     : day, ~24h lag time-constant
TAU48        : 2     : day, ~48h lag time-constant
LIMIT_24H    : 8      : mEq/L, guideline max correction per 24h (6 if high-risk)

//--- Neuro-symptom & ODS risk
W_NA_DEFICIT : 0.55
W_ACUTE_RATE : 0.9
W_ADAPT      : 3.5
KOUT_NEURO   : 0.5
K_ODS        : 14     : ODS-risk accrual rate constant
KOUT_ODSRISK : 0      : cumulative risk, no intrinsic decay (soft-saturating instead)

[CMT] @annotated
TOLVA_GUT  : Tolvaptan oral absorption depot (au)
TOLVA_CENT : Tolvaptan effective exposure (au)
CONIV_CENT : Conivaptan IV effective exposure (au)
DEMEC_GUT  : Demeclocycline oral absorption depot (au)
DEMEC_CENT : Demeclocycline effective exposure (au)
UREA_GUT   : Oral urea effective exposure (au)
HSAL_INF   : Hypertonic-saline 3% infusion drive (au)
AQP2       : Functional renal AQP2 apical expression/activity (a.u., 0-100)
FWCL       : Electrolyte-free water clearance (L/day-equivalent)
TBW        : Total body water (L-equivalent)
NA_SERUM   : Serum sodium (mEq/L)
OSM_SERUM  : Serum osmolality (mOsm/kg)
OSM_URINE  : Urine osmolality (mOsm/kg)
UNA        : Urine sodium (mEq/L)
BRAIN_OSM  : Brain organic-osmolyte adaptation index (a.u., 0-100, lower=more chronically adapted/depleted)
NA_LAG24   : ~24h-delayed serum sodium tracker (mEq/L)
NA_LAG48   : ~48h-delayed serum sodium tracker (mEq/L)
NEURO_SYMPTOM: Composite neuro-symptom severity score (0-10)
ODS_RISK   : Cumulative osmotic-demyelination-syndrome risk score (0-100)

[MAIN]
TOLVA_GUT_0 = 0; TOLVA_CENT_0 = 0; CONIV_CENT_0 = 0;
DEMEC_GUT_0 = 0; DEMEC_CENT_0 = 0; UREA_GUT_0 = 0; HSAL_INF_0 = 0;

double sev_eff0 = SEV * (ECTOPIC>0 ? 1.3 : 1.0);
if (sev_eff0 > 1.3) sev_eff0 = 1.3;

AQP2_0      = AQP2_BASE * (1 + K_AQP_SEV*sev_eff0);
if (AQP2_0 > AQP2_MAX) AQP2_0 = AQP2_MAX;
FWCL_0      = FWCL_MAX * (1 - AQP2_0/AQP2_MAX);
TBW_0       = TBW_NORMAL * (NA_NORMAL/BASE_NA);
NA_SERUM_0  = BASE_NA;
OSM_SERUM_0 = 2.0*BASE_NA + OSM_OFFSET;
OSM_URINE_0 = UOSM_MIN + (UOSM_MAX-UOSM_MIN)*(AQP2_0/AQP2_MAX);
UNA_0       = UNA_BASE + K_UNA_TBW*(TBW_0 - TBW_NORMAL);
// Chronic disease has already reached its adapted (osmolyte-depleted) steady state;
// acute disease has not yet adapted and starts near the normal osmolyte content.
double deficit0 = NA_NORMAL - BASE_NA;
if (deficit0 < 0) deficit0 = 0;
double brainosm_adapted = BRAINOSM_NORMAL - K_BRAINOSM_ADAPT*deficit0;
if (brainosm_adapted < 10) brainosm_adapted = 10;
BRAIN_OSM_0 = (CHRONIC>0) ? brainosm_adapted : BRAINOSM_NORMAL;
NA_LAG24_0  = BASE_NA;
NA_LAG48_0  = BASE_NA;
NEURO_SYMPTOM_0 = W_NA_DEFICIT*deficit0/10.0;
ODS_RISK_0  = 0;

[ODE]
// ---------- Drug PK / exposure kinetics ----------
dxdt_TOLVA_GUT  = -KA_TOLVA*TOLVA_GUT;
dxdt_TOLVA_CENT =  KA_TOLVA*TOLVA_GUT - KOUT_TOLVA*TOLVA_CENT;
dxdt_CONIV_CENT = -KOUT_CONIV*CONIV_CENT;
dxdt_DEMEC_GUT  = -KA_DEMEC*DEMEC_GUT;
dxdt_DEMEC_CENT =  KA_DEMEC*DEMEC_GUT - KOUT_DEMEC*DEMEC_CENT;
dxdt_UREA_GUT   = -KOUT_UREA*UREA_GUT;
dxdt_HSAL_INF   = -KOUT_HSAL*HSAL_INF;

// ---------- Drug effect (Emax) terms ----------
double Tolva_eff = EMAX_TOLVA * TOLVA_CENT/(EC50_TOLVA + TOLVA_CENT);
double Coniv_eff = EMAX_CONIV * CONIV_CENT/(EC50_CONIV + CONIV_CENT);
double Demec_eff = EMAX_DEMEC * DEMEC_CENT/(EC50_DEMEC + DEMEC_CENT);
double Urea_eff  = EMAX_UREA  * UREA_GUT  /(EC50_UREA  + UREA_GUT);

double V2_block = Tolva_eff + Coniv_eff;               // combinable receptor antagonism
if (V2_block > 0.95) V2_block = 0.95;

// ---------- Renal V2R / AQP2 functional expression ----------
double sev_eff = SEV * (ECTOPIC>0 ? 1.3 : 1.0);
if (sev_eff > 1.3) sev_eff = 1.3;
double AQP2_target = AQP2_BASE*(1 + K_AQP_SEV*sev_eff) * (1 - V2_block) * (1 - Demec_eff);
if (DDAVP_CLAMP>0 && AQP2_target < AQP2_CLAMP_FLOOR) AQP2_target = AQP2_CLAMP_FLOOR;
if (AQP2_target < 2) AQP2_target = 2;
if (AQP2_target > AQP2_MAX) AQP2_target = AQP2_MAX;
dxdt_AQP2 = KOUT_AQP2 * (AQP2_target - AQP2);

// ---------- Free-water clearance ----------
double FWCL_target = FWCL_MAX*(1 - AQP2/AQP2_MAX)
                     + FWCL_MAX*(0.5*Urea_eff + 0.30*LOOP_SALT + 0.20*SGLT2I);
if (FWCL_target < 0) FWCL_target = 0;
dxdt_FWCL = KOUT_TBW * (FWCL_target - FWCL);

// ---------- Total body water ----------
double water_intake_eff = WATER_INTAKE_BASE * (1 - 0.65*FLUID_RESTRICT);
dxdt_TBW = water_intake_eff - FWCL;

// ---------- Serum sodium (dilutional target + direct hypertonic-saline input) ----------
double NA_target = NA_NORMAL * (TBW_NORMAL/TBW);
double hsal_na_input = GAIN_HSAL_NA * KOUT_HSAL * HSAL_INF;
dxdt_NA_SERUM = KOUT_NA*(NA_target - NA_SERUM) + hsal_na_input;

// ---------- Serum & urine osmolality, urine sodium ----------
double OSM_target = 2.0*NA_SERUM + OSM_OFFSET;
dxdt_OSM_SERUM = KOUT_OSM * (OSM_target - OSM_SERUM);

double UOSM_target = UOSM_MIN + (UOSM_MAX-UOSM_MIN)*(AQP2/AQP2_MAX);
UOSM_target = UOSM_target * (1 - 0.30*LOOP_SALT - 0.25*Urea_eff - 0.15*SGLT2I);
if (UOSM_target < UOSM_MIN) UOSM_target = UOSM_MIN;
dxdt_OSM_URINE = KOUT_UOSM * (UOSM_target - OSM_URINE);

double UNA_target = UNA_BASE + K_UNA_TBW*(TBW - TBW_NORMAL) + UNA_LOOP_SALT_ADD*LOOP_SALT;
if (UNA_target < 0) UNA_target = 0;
dxdt_UNA = KOUT_UNA * (UNA_target - UNA);

// ---------- Cerebral adaptation ----------
double deficit_now = NA_NORMAL - NA_SERUM;
if (deficit_now < 0) deficit_now = 0;
double BRAINOSM_target = BRAINOSM_NORMAL - K_BRAINOSM_ADAPT*deficit_now;
if (BRAINOSM_target < 10) BRAINOSM_target = 10;
if (BRAINOSM_target > BRAINOSM_NORMAL) BRAINOSM_target = BRAINOSM_NORMAL;
dxdt_BRAIN_OSM = KOUT_BRAINOSM * (BRAINOSM_target - BRAIN_OSM);

// ---------- ~24h / ~48h delayed sodium trackers (correction-rate proxies) ----------
dxdt_NA_LAG24 = (NA_SERUM - NA_LAG24) / TAU24;
dxdt_NA_LAG48 = (NA_SERUM - NA_LAG48) / TAU48;

// ---------- Composite neuro-symptom score ----------
double na_deficit10 = (NA_NORMAL - NA_SERUM)/10.0;
if (na_deficit10 < 0) na_deficit10 = 0;
double acute_fall = -(NA_SERUM - NA_LAG24);           // positive if Na has been dropping
if (acute_fall < 0) acute_fall = 0;
double acute_component = (CHRONIC>0) ? 0.3*acute_fall : acute_fall;
double adapt_relief = (BRAINOSM_NORMAL - BRAIN_OSM)/BRAINOSM_NORMAL * W_ADAPT;
double NEURO_target = W_NA_DEFICIT*na_deficit10 + W_ACUTE_RATE*acute_component - adapt_relief;
if (NEURO_target < 0) NEURO_target = 0;
if (NEURO_target > 10) NEURO_target = 10;
dxdt_NEURO_SYMPTOM = KOUT_NEURO * (NEURO_target - NEURO_SYMPTOM);

// ---------- Osmotic-demyelination-syndrome (ODS) risk accumulation ----------
double correction_rate24 = NA_SERUM - NA_LAG24;       // positive = correcting upward
double excess_rate = correction_rate24 - LIMIT_24H;
if (excess_rate < 0) excess_rate = 0;
double vulnerability = (BRAINOSM_NORMAL - BRAIN_OSM)/BRAINOSM_NORMAL;  // 0 (not adapted) .. ~0.9 (deeply adapted/chronic)
double saturation = 1 - ODS_RISK/100.0;
if (saturation < 0) saturation = 0;
dxdt_ODS_RISK = K_ODS * excess_rate * (0.15 + vulnerability) * saturation;

[TABLE]
capture Tolvaptan_effect   = Tolva_eff;
capture Conivaptan_effect  = Coniv_eff;
capture Demeclocycline_effect = Demec_eff;
capture Urea_effect        = Urea_eff;
capture V2_receptor_block  = V2_block;
capture AQP2_expression    = AQP2;
capture Free_water_clearance = FWCL;
capture Total_body_water   = TBW;
capture Serum_Na           = NA_SERUM;
capture Serum_osmolality   = OSM_SERUM;
capture Urine_osmolality   = OSM_URINE;
capture Urine_Na           = UNA;
capture Brain_osmolyte_adaptation = BRAIN_OSM;
capture Na_correction_rate_24h = NA_SERUM - NA_LAG24;
capture Na_correction_rate_48h = NA_SERUM - NA_LAG48;
capture Neuro_symptom_score = NEURO_SYMPTOM;
capture ODS_risk_score     = ODS_RISK;

[CAPTURE]
Tolvaptan_effect Conivaptan_effect Demeclocycline_effect Urea_effect V2_receptor_block
AQP2_expression Free_water_clearance Total_body_water Serum_Na Serum_osmolality
Urine_osmolality Urine_Na Brain_osmolyte_adaptation
Na_correction_rate_24h Na_correction_rate_48h Neuro_symptom_score ODS_risk_score


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("siadh_mrgsolve_model.R")
##
##  # ---------- 7 prebuilt scenarios ----------
##
##  SIADH_simulate_scenarios <- function(end_d = 14) {
##
##    sc <- list(
##      "1. Untreated natural history (chronic, no restriction)" =
##        ev(amt=0, cmt="TOLVA_GUT", time=0),
##
##      "2. Fluid restriction alone (<1 L/day, first-line)" =
##        ev(amt=0, cmt="TOLVA_GUT", time=0),   # FLUID_RESTRICT=1 set via param()
##
##      "3. Tolvaptan 15mg PO QD (up-titrate to 60mg)" =
##        ev(amt=1.0, cmt="TOLVA_GUT", ii=1, addl=end_d-1),
##
##      "4. Conivaptan IV 20mg load + 20mg/day infusion (inpatient)" =
##        ev(amt=1.4, cmt="CONIV_CENT", ii=1, addl=end_d-1),
##
##      "5. Demeclocycline 900mg/day (chronic, malignancy-associated)" =
##        ev(amt=1.1, cmt="DEMEC_GUT", ii=1, addl=end_d-1),
##
##      "6. Hypertonic saline 3% (acute severe, guideline-limited rate)" =
##        ev(amt=0.9, cmt="HSAL_INF", ii=0.5, addl=2*3-1),   # 3-day bolus course
##
##      "7. Overly rapid correction (unmonitored, ODS teaching example)" =
##        ev(amt=3.0, cmt="HSAL_INF", ii=0.25, addl=4*3-1)   # 4x saline rate, no rate cap
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      restrict <- grepl("^2\\.", lab)
##      mod %>% param(FLUID_RESTRICT = as.numeric(restrict)) %>%
##        mrgsim(e, end=end_d, delta=0.25) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # SALT-1/SALT-2 (Schrier 2006 NEJM)          : tolvaptan +3-4 mEq/L Na at day 4
##  #   vs placebo, sustained to day 30; modeled via EC50_TOLVA/EMAX_TOLVA on
##  #   AQP2 target with slow KOUT_NA relaxation.
##  # Conivaptan (Ghali 2006; Verbalis 2008)       : similar/faster Na rise given
##  #   IV loading + continuous infusion (higher initial exposure than oral vaptan).
##  # Demeclocycline (Forrest 1978; De Troyer 1977): slower onset (3-5 days) than
##  #   vaptans, modeled via lower KOUT_DEMEC; effective in chronic SIADH,
##  #   historically used when vaptans contraindicated/unavailable (hepatotoxicity
##  #   risk with vaptans in cirrhosis is why demeclocycline persists as an option).
##  # Correction-rate guidelines (Verbalis 2013 Am J Med; Spasovski 2014 Eur J
##  #   Endocrinol)                               : <=8 mEq/L/24h (<=4-6 if
##  #   high-risk) and <=18 mEq/L/48h; LIMIT_24H triggers ODS_RISK accrual only
##  #   above threshold, scaled by cerebral-adaptation vulnerability.
##  # Osmotic demyelination syndrome (Sterns 1986; Sterns 2010)  : risk is
##  #   negligible in ACUTE hyponatremia (BRAIN_OSM near normal, low
##  #   vulnerability) even with fast correction, and highest in CHRONIC
##  #   hyponatremia corrected too fast (BRAIN_OSM depleted -> high vulnerability)
##  #   -- reproduced via the vulnerability term gating K_ODS.
##
##  # ---------- Quick sanity plots ----------
##  # df <- SIADH_simulate_scenarios(14)
##  # ggplot(df, aes(time, Serum_Na, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Na_correction_rate_24h, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, ODS_risk_score, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Neuro_symptom_score, colour=scenario)) + geom_line()
