##  Community-Acquired Pneumonia (CAP) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Community-acquired pneumonia, pneumococcal-archetype. Micro-
##             aspiration of colonising Streptococcus pneumoniae -> alveolar
##             replication -> PAMP release (LTA/peptidoglycan/CpG DNA/
##             pneumolysin) -> TLR2/4/9-NLRP3-NF-kB innate activation ->
##             feed-forward TNF/IL-1b/IL-6/IL-8 amplification -> neutrophil
##             recruitment, alveolar-capillary barrier failure, protein-rich
##             oedema and consolidation -> intrapulmonary shunt -> hypoxaemia;
##             with systemic spill-over (bacteraemia, vasoplegia, lactate, AKI)
##             and a resolution arm (efferocytosis, SPMs, alveolar fluid
##             clearance) that is rate-limiting for radiographic recovery.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  ---------------------------------------------------------------------------
##  THE THREE STRUCTURAL COMMITMENTS (why this model is not the usual cartoon)
##  ---------------------------------------------------------------------------
##  Most CAP models write "antibiotic kills bug -> patient improves". That
##  cannot simultaneously hold six facts that the CAP literature insists on:
##
##   (a) fT>MIC and fAUC/MIC are not inputs. They are the emergent time-integral
##       of a saturating concentration-effect curve. So they are NOT parameters
##       here: TAM and AUCF are ODE accumulators, and the class difference
##       between ceftriaxone (flat Emax, low Hill) and levofloxacin (steep
##       Hill) falls out of the two Hill coefficients rather than being
##       hard-coded as "time-dependent" vs "concentration-dependent".
##
##   (b) KILLING IS A PAMP SOURCE, NOT A PAMP SINK. beta-lactams kill by
##       PBP inhibition -> LytA-mediated autolysis -> a bolus of cell wall and
##       pneumolysin into the alveolus. Non-lytic killing (macrolide, and to a
##       lesser degree fluoroquinolone) liberates far less. This model makes
##       PAMP release proportional to (kill rate x a drug-specific lysis yield
##       YLYS), which is what generates the observed EARLY (6-24 h) post-first-
##       dose inflammatory surge and clinical deterioration, and is why adding
##       a macrolide helps in severe pneumococcal CAP even when the isolate is
##       macrolide-RESISTANT: its benefit travels the toxin/cytokine channel
##       (PLY suppression + IL-8/neutrophil damping), not the kill channel.
##       Setting MIC_AZI = 64 (ermB) leaves KILL_AZI ~ 0 while MAC_IMM persists.
##
##   (c) CORTICOSTEROID IS TWO-ARMED AND ITS SIGN IS CONDITIONAL. The GC effect
##       compartment feeds BOTH a beneficial NF-kB transrepression term (damps
##       the cytokine amplifier, the barrier, the shunt, the vasoplegia) AND an
##       adverse term that suppresses opsonophagocytic killing. Net benefit
##       therefore depends on whether antibiotic-driven kill has made host
##       killing redundant. With a susceptible organism and an adequate
##       beta-lactam, steroid is protective (CAPE-COD). With a resistant
##       organism, or with a viral pneumonia where there is no bacterial
##       target for the antibiotic, the same dose is harmful. Scenarios 6 vs 7
##       vs 9 are built to show precisely this sign flip on one parameter set.
##
##  ---------------------------------------------------------------------------
##  Scope    : 38 ODE compartments =
##             11 PK  (ceftriaxone 2-cmt IV; amoxicillin oral 1-cmt; azithro-
##                     mycin oral 2-cmt with deep lung accumulation; levo-
##                     floxacin oral/IV 1-cmt; hydrocortisone central + effect)
##            + 5 pathogen (alveolar extracellular, tolerant/intracellular
##                     persisters, bacteraemia, free PAMP pool, respiratory
##                     virus)
##            + 9 immune (alveolar macrophage, blood & lung neutrophils,
##                     TNF-a, IL-1b, IL-6, IL-8, IL-10, pro-resolving mediators)
##            + 3 biomarker (CRP, procalcitonin, lymphocyte count)
##            + 4 lung (barrier permeability, alveolar oedema/consolidation,
##                     surfactant function, organising/fibroproliferative index)
##            + 3 systemic (MAP deficit, lactate, renal injury)
##            + 3 accumulators (fT>MIC, free ELF AUC, cumulative mortality
##                     hazard -> 28-day mortality = 1 - exp(-CHZ))
##  Time     : HOURS (default horizon 336 h = 14 d). Hours, not days, because
##             the whole point of (a) and (b) above is sub-dosing-interval
##             resolution of exposure and of the post-dose PAMP surge.
##  Units    : drug mg and mg/L; bacteria CFU/mL of epithelial lining fluid;
##             cytokines pg/mL; CRP mg/L; PCT ng/mL; cells 10^9/L; MAP mmHg;
##             lactate mmol/L; oedema and shunt dimensionless fractions.
##  Scenarios: 9 prebuilt -- see CAP_simulate_scenarios() at the bottom.
##  ---------------------------------------------------------------------------
##  Calibration anchors (see cap_references.md for the full list)
##   * Untreated natural history reproduces the pre-antibiotic-era pneumococcal
##     "crisis" at ~day 7-9 in survivors (host-only clearance), with a high
##     cumulative hazard -- KPHAG_AM/KPHAG_N and KG tuned to that.
##   * Ceftriaxone 2 g q24h: Cmax ~150 mg/L total, trough ~10 mg/L, fu ~0.10,
##     ELF/plasma free ~0.4; against MIC 0.25 mg/L this yields fT>MIC ~100%.
##   * Levofloxacin 750 mg q24h: Cmax ~8-12 mg/L, AUC24 ~100 mg.h/L, fu 0.70,
##     ELF/plasma ~1.0-1.4 -> fAUC/MIC ~70 at MIC 1 (target >=30-40).
##   * Azithromycin 500 mg q24h: serum Cmax only ~0.4 mg/L but ELF 1-3 mg/L and
##     alveolar-macrophage concentrations two orders higher -- hence the
##     separate deep AZIT compartment.
##   * Halm 1998: median time to clinical stability ~3 d on effective therapy.
##   * CAPE-COD (Dequin 2023): hydrocortisone 200 mg/d in severe CAP, 28-d
##     mortality 6.2% vs 11.9% -- scenario 6 vs 3.
##   * Uranga 2016 / Dinh 2021: 5-day (and 3-day) courses non-inferior when the
##     patient is stable -- scenario 8, with BP (persisters) governing relapse.
##   * Schuetz 2018: PCT falls faster than CRP and safely shortens therapy --
##     PCT t1/2 24 h vs CRP t1/2 19 h but with different production drivers.
##  Disclaimer: research / education / hypothesis generation only. Not fitted to
##              patient-level data; not for clinical or regulatory use.
##  ============================================================================

[PROB]
QSP model of community-acquired pneumonia coupling pneumococcal burden,
lysis-mode-dependent PAMP liberation, innate immune amplification, alveolar
barrier failure and intrapulmonary shunt, systemic organ dysfunction, and the
PK/PD of ceftriaxone, amoxicillin, azithromycin, levofloxacin and
hydrocortisone, with fT>MIC / fAUC/MIC as emergent accumulators and a
two-armed (protective + immunosuppressive) corticosteroid effect.

[GLOBAL]
// only POSITIVE net growth sheds PAMP from living (un-lysed) organisms
double grow_pos(double g) { return (g > 0.0) ? g : 0.0; }

// renal-function-scaled clearances: computed once per record in [MAIN] but read
// every derivative evaluation in [ODE], so they must live at file scope --
// a `double` declared inside [MAIN] is local to _main_ and invisible to _ode_.
double CLcef, CLamx, CLlvx;

[PARAM] @annotated
//---------------------------------------------------------------- patient ----
AGE        :  68   : years (CURB-65 term and hazard covariate)
WT         :  70   : kg body weight
CRCL       :  90   : mL/min, baseline creatinine clearance (scales renal CL)
IMMSUP     :   0   : 0-1, pre-existing immunosuppression (scales phagocyte kill down)
SEV0       : 0.55  : 0-1, presenting severity (sets initial inoculum and barrier tone)
FIO2       : 0.21  : inspired oxygen fraction (0.21 room air; raise for O2 therapy)
HB         :  13   : g/dL haemoglobin (oxygen content)
VIRAL      :   0   : 1 = antecedent/concurrent influenza (viral co-infection arm)
VACC       :   0   : 1 = PCV20/PPSV23 vaccinated (pre-existing anti-capsular IgG)

//------------------------------------------------------------ pathogen --------
B0         : 5e6   : CFU/mL, initial alveolar (ELF) extracellular inoculum
BMAX       : 1e9   : CFU/mL, alveolar carrying capacity
KG         : 0.22  : 1/h, maximal net replication rate (t_double ~3.2 h)
KPERS      : 0.010 : 1/h, phenotypic switch into tolerant/intracellular state
KREV       : 0.020 : 1/h, reversion of persisters to replicating state
KTRANS     : 2.5e-6: 1/h per permeability unit, alveolus -> blood translocation
KCLBB      : 0.30  : 1/h, splenic/hepatic clearance of blood-borne bacteria
KVIR       : 0.10  : 1/h, virus decay (viral co-infection driver)
V0         : 1.0   : au, initial virus load when VIRAL = 1
EVIR_ADH   : 1.6   : fold increase in bacterial growth with active virus (NanA synergy)
EVIR_BAR   : 0.8   : additional barrier injury from virus

//----------------------------------------- PAMP liberation and lysis yields ---
YLIVE      : 2.0e-8: au per CFU per h, PAMP shed by LIVING replicating bacteria
YHOST      : 3.0e-8: au per CFU killed, PAMP yield of phagocytic (intracellular) killing
YLYS_BL    : 1.00  : lysis yield of beta-lactam killing (LytA autolysis: maximal)
YLYS_FQ    : 0.35  : lysis yield of fluoroquinolone killing (filamentation, less lysis)
YLYS_MAC   : 0.12  : lysis yield of macrolide killing (non-bacteriolytic)
KPAMP      : 0.09  : 1/h, alveolar PAMP clearance (t1/2 ~7.7 h)
KMPAMP     : 0.35  : au, PAMP concentration giving half-maximal PRR stimulation
PLYFRAC    : 0.45  : fraction of PAMP signal attributable to pneumolysin (macrolide-suppressible)

//---------------------------------------------------------- innate immunity ---
AM0        : 1.0   : rel., resting alveolar macrophage pool
KAM_IN     : 0.05  : 1/h, AM turnover in
KAM_OUT    : 0.05  : 1/h, AM turnover out
EAM        : 4.0   : maximal fold AM activation by PAMP
NB0        : 5.0   : 10^9/L, baseline circulating neutrophils
KNB_OUT    : 0.12  : 1/h, blood neutrophil disappearance
EGCSF      : 0.012 : per pg/mL, granulopoietic drive from IL-6 + IL-1b
KMIG       : 0.0060: 1/h per pg/mL IL-8, blood -> lung neutrophil migration
KNL_OUT    : 0.055 : 1/h, lung neutrophil apoptosis/efferocytosis
NLMAX      : 60    : rel., ceiling on lung neutrophil accumulation

//------------------------------------------------------- phagocytic killing ---
KPHAG_AM   : 0.085 : 1/h per AM unit, alveolar-macrophage killing capacity
KPHAG_N    : 0.011 : 1/h per lung-neutrophil unit, neutrophil killing capacity
KM_PHAG    : 2.0e7 : CFU/mL, saturation of phagocytic killing (capsule-limited)
FTOL_HOST  : 0.15  : relative host killing of tolerant/intracellular bacteria
OPS_VACC   : 1.45  : opsonic boost if vaccinated / pre-existing anti-capsular IgG
IMAX_IL10  : 0.55  : maximal IL-10 suppression of phagocytic killing
IC50_IL10  : 120   : pg/mL, IL-10 potency on phagocyte function

//---------------------------------------------------------- cytokine network --
KS_TNF     : 26    : pg/mL/h, TNF-a production scale
KD_TNF     : 0.55  : 1/h, TNF-a elimination (t1/2 ~1.3 h)
KS_IL1     : 20    : pg/mL/h, IL-1b production scale (inflammasome-gated)
KD_IL1     : 0.30  : 1/h
KS_IL6     : 60    : pg/mL/h, IL-6 production scale
KD_IL6     : 0.22  : 1/h (t1/2 ~3 h)
KS_IL8     : 34    : pg/mL/h, IL-8/CXCL8 production scale
KD_IL8     : 0.28  : 1/h
KS_IL10    : 5.5   : pg/mL/h, IL-10 (counter-regulatory, cytokine-driven)
KD_IL10    : 0.25  : 1/h
EAMP       : 2.6   : maximal feed-forward cytokine amplification
KAMP       : 900   : pg/mL, half-maximal amplification (sum of TNF+IL1+IL6)
FNEUT_CYT  : 0.35  : relative cytokine contribution of recruited neutrophils
KS_SPM     : 0.11  : au/h per efferocytosis unit, pro-resolving mediator synthesis
KD_SPM     : 0.05  : 1/h
ESPM       : 0.65  : maximal SPM damping of the cytokine amplifier
KSPM50     : 1.2   : au, SPM potency

//----------------------------------------------------------- biomarkers -------
KS_CRP     : 0.95  : mg/L/h, maximal hepatic CRP synthesis
KM_CRP_IL6 : 110   : pg/mL, IL-6 EC50 for CRP synthesis
KD_CRP     : 0.0365: 1/h, CRP elimination (t1/2 = 19 h)
CRP0       : 3     : mg/L, baseline CRP
KS_PCT     : 0.60  : ng/mL/h, maximal procalcitonin induction
KM_PCT     : 0.55  : au, bacterial-PAMP EC50 for PCT (bacteria-specific driver)
KD_PCT     : 0.0289: 1/h, PCT elimination (t1/2 = 24 h)
PCT0       : 0.05  : ng/mL, baseline PCT
IPCT_VIR   : 0.70  : maximal IFN-mediated suppression of PCT in viral disease
LYM0       : 1.8   : 10^9/L, baseline lymphocyte count
KLYM_OUT   : 0.05  : 1/h, lymphocyte redistribution/apoptosis rate scale
ELYM       : 0.0012: per pg/mL, cytokine- and steroid-driven lymphopenia

//-------------------------------------------------- alveolar barrier & gas ----
KS_PERM    : 0.0016: 1/h per pg/mL, barrier injury by TNF + IL-1b
KS_PERM_N  : 0.0032: 1/h per lung-neutrophil unit, NET/elastase barrier injury
KD_PERM    : 0.045 : 1/h, barrier repair
KFILT      : 0.020 : 1/h per permeability unit, alveolar flooding rate
KAFC       : 0.030 : 1/h, alveolar fluid clearance (ENaC/Na-K-ATPase, surfactant-dependent)
IAFC_IL8   : 0.45  : maximal IL-8 inhibition of alveolar fluid clearance
IC50_AFC   : 260   : pg/mL
KS_SURF    : 0.030 : 1/h, surfactant regeneration by AT2
KD_SURF    : 0.010 : 1/h per injury unit, surfactant inactivation
QS0        : 0.045 : baseline physiological shunt fraction
QSMAX      : 0.52  : maximal shunt fraction at full consolidation
E50_QS     : 0.34  : oedema fraction at half-maximal shunt
HQS        : 1.8   : Hill coefficient, oedema -> shunt
HPV_MAX    : 0.30  : maximal shunt reduction by hypoxic pulmonary vasoconstriction
IHPV_CYT   : 0.65  : maximal cytokine blunting of HPV
KPF        : 5.9   : shunt -> PaO2/FiO2 mapping constant (PF = 500*exp(-KPF*Qs))
KS_FIB     : 0.0045: 1/h, organising/fibroproliferative drive from sustained oedema
KD_FIB     : 0.0035: 1/h, fibroproliferative resolution

//------------------------------------------------------- systemic / organ -----
MAP0       : 88    : mmHg, baseline mean arterial pressure
KS_MAP     : 0.0022: mmHg/h per pg/mL, vasoplegia drive (cytokines)
KS_MAP_BB  : 0.9   : mmHg/h per log10 CFU/mL blood, bacteraemia drive
KD_MAP     : 0.075 : 1/h, haemodynamic recovery
VASOPRESS  : 0     : 0-1, noradrenaline/fluid support level
EVASO      : 26    : mmHg, maximal MAP restoration by vasopressor support
EMAP_GC    : 12    : mmHg, maximal MAP restoration by corticosteroid
LACT0      : 1.0   : mmol/L, baseline lactate
KS_LACT    : 0.030 : mmol/L/h per mmHg MAP deficit above threshold
MAPTH      : 18    : mmHg, MAP deficit above which anaerobic lactate rises
KS_LACT_C  : 0.00055: mmol/L/h per pg/mL, aerobic (cytokine-driven) lactate
KD_LACT    : 0.28  : 1/h, lactate clearance
KS_AKI     : 0.0075: 1/h per mmHg MAP deficit, renal injury accrual
KD_AKI     : 0.020 : 1/h, renal recovery

//------------------------------------------------- ceftriaxone (2-cmt IV) -----
CL_CEF     : 1.00  : L/h at CRCL 90 (biliary + renal)
V1_CEF     : 8.0   : L
Q_CEF      : 1.10  : L/h intercompartmental
V2_CEF     : 6.5   : L
FU_CEF     : 0.10  : unbound fraction in plasma
PEN_CEF    : 0.40  : free ELF / free plasma penetration ratio
FREN_CEF   : 0.55  : fraction of ceftriaxone CL that is renal (CRCL-scaled)
MIC_CEF    : 0.25  : mg/L, ceftriaxone MIC of the infecting isolate
EMAX_CEF   : 0.90  : 1/h maximal kill rate
FEC50_CEF  : 1.00  : EC50 as a multiple of MIC
H_CEF      : 1.5   : Hill coefficient (shallow -> time-dependent behaviour)

//------------------------------------------------- amoxicillin (oral 1-cmt) ---
KA_AMX     : 1.5   : 1/h absorption
F_AMX      : 0.80  : oral bioavailability
CL_AMX     : 20.0  : L/h at CRCL 90
V_AMX      : 25.0  : L
FU_AMX     : 0.82  : unbound fraction
PEN_AMX    : 0.30  : free ELF / free plasma ratio
MIC_AMX    : 0.03  : mg/L, penicillin/amoxicillin MIC (0.03 S; >=4 non-susceptible)
EMAX_AMX   : 0.85  : 1/h maximal kill rate
FEC50_AMX  : 1.00  : EC50 as multiple of MIC
H_AMX      : 1.5   : Hill coefficient

//---------------------------------- azithromycin (oral, deep lung 2-cmt) ------
KA_AZI     : 0.50  : 1/h absorption
F_AZI      : 0.37  : oral bioavailability
CL_AZI     : 38.0  : L/h
V1_AZI     : 450   : L central (very large Vd)
Q_AZI      : 42.0  : L/h into deep lung/phagocyte compartment
V2_AZI     : 2200  : L deep lung/phagocyte compartment
KP_AZI_ELF : 22    : ELF concentration per deep-compartment concentration
FU_AZI     : 0.50  : unbound fraction
MIC_AZI    : 0.12  : mg/L (set 64 for an ermB macrolide-RESISTANT isolate)
EMAX_AZI   : 0.16  : 1/h maximal kill rate (bacteriostatic-leaning)
FEC50_AZI  : 1.20  : EC50 as multiple of MIC
H_AZI      : 1.2   : Hill coefficient
IMAX_MAC   : 0.42  : maximal macrolide damping of the cytokine amplifier
IC50_MAC   : 1.1   : mg/L ELF, macrolide immunomodulation potency
IMAX_PLY   : 0.60  : maximal macrolide suppression of pneumolysin output
IMAX_MIGM  : 0.30  : maximal macrolide reduction of neutrophil migration

//------------------------------------------- levofloxacin (oral/IV 1-cmt) -----
KA_LVX     : 1.50  : 1/h absorption
F_LVX      : 0.99  : oral bioavailability
CL_LVX     : 8.0   : L/h at CRCL 90
V_LVX      : 90.0  : L
FU_LVX     : 0.70  : unbound fraction
PEN_LVX    : 1.20  : free ELF / free plasma ratio
FREN_LVX   : 0.85  : renal fraction of levofloxacin CL
MIC_LVX    : 1.00  : mg/L, levofloxacin MIC
EMAX_LVX   : 1.40  : 1/h maximal kill rate
FEC50_LVX  : 1.20  : EC50 as multiple of MIC
H_LVX      : 2.6   : Hill coefficient (steep -> concentration-dependent behaviour)
FTOL_FQ    : 0.25  : relative fluoroquinolone activity on non-replicating persisters
FTOL_BL    : 0.04  : relative beta-lactam activity on non-replicating persisters
FTOL_MAC   : 0.10  : relative macrolide activity on non-replicating persisters

//------------------------------------------------------- hydrocortisone -------
CL_HC      : 18.0  : L/h
V_HC       : 35.0  : L
KE0_HC     : 0.20  : 1/h, effect-compartment equilibration
IMAX_GC    : 0.72  : maximal NF-kB transrepression of the cytokine amplifier
IC50_GC    : 0.22  : mg/L (effect-site), glucocorticoid potency
IMAX_GCP   : 0.45  : MAXIMAL ADVERSE suppression of opsonophagocytic killing
IC50_GCP   : 0.30  : mg/L (effect-site), potency of the immunosuppressive arm
IMAX_GCN   : 0.35  : maximal annexin-A1 reduction of neutrophil migration
EGLU_GC    : 3.2   : mmol/L, steroid-induced glucose rise (safety readout only)

//------------------------------------------------------------ outcomes --------
TEMP0      : 36.7  : degC, baseline temperature
KTEMP      : 3.1   : degC, maximal pyrogenic rise
KMTEMP     : 480   : pg/mL, IL-6 + IL-1b giving half-maximal fever
RR0        : 15    : /min, baseline respiratory rate
KRR_QS     : 42    : /min per unit shunt fraction
KRR_CYT    : 0.004 : /min per pg/mL
HR0        : 74    : /min, baseline heart rate
KHR_T      : 9.0   : /min per degC above baseline
KHR_MAP    : 0.85  : /min per mmHg MAP deficit
HAZ0       : 2.2e-5: 1/h, baseline hazard scale
HAZ_SOFA   : 0.42  : hazard exponent weight on SOFA
HAZ_AGE    : 0.030 : per year above 50
HAZ_BB     : 0.16  : hazard weight per log10 CFU/mL bacteraemia
ANTIPYR    : 0     : 0-1, antipyretic use (masks the fever readout only)

[CMT] @annotated
CEFC : ceftriaxone central (mg)
CEFP : ceftriaxone peripheral (mg)
AMXD : amoxicillin gut depot (mg)
AMXC : amoxicillin central (mg)
AZID : azithromycin gut depot (mg)
AZIC : azithromycin central (mg)
AZIT : azithromycin deep lung/phagocyte compartment (mg)
LVXD : levofloxacin gut depot (mg)
LVXC : levofloxacin central (mg)
HCC  : hydrocortisone central (mg)
HCE  : hydrocortisone effect site (mg/L)
BE   : alveolar extracellular bacteria (CFU/mL ELF)
BP   : tolerant / intracellular persister bacteria (CFU/mL ELF)
BB   : bacteraemia (CFU/mL blood)
PAMP : free alveolar PAMP pool (au)
VIR  : respiratory virus load (au)
AM   : activated alveolar macrophages (rel.)
NB   : circulating neutrophils (10^9/L)
NL   : lung-recruited neutrophils (rel.)
TNF  : TNF-alpha (pg/mL)
IL1  : IL-1beta (pg/mL)
IL6  : IL-6 (pg/mL)
IL8  : IL-8 / CXCL8 (pg/mL)
IL10 : IL-10 (pg/mL)
SPM  : specialised pro-resolving mediators (au)
CRP  : C-reactive protein (mg/L)
PCT  : procalcitonin (ng/mL)
LYM  : lymphocyte count (10^9/L)
PERM : alveolar-capillary permeability index (1 = normal)
EDEM : alveolar oedema / consolidated fraction (0-1)
SURF : surfactant function (1 = normal)
FIBP : organising / fibroproliferative index
MAPD : mean arterial pressure deficit (mmHg)
LACT : arterial lactate (mmol/L)
AKID : renal injury index (0-1)
TAM  : cumulative time above MIC of the active beta-lactam (h)
AUCF : cumulative free ELF AUC of the active fluoroquinolone (mg.h/L)
CHZ  : cumulative mortality hazard

[MAIN]
// ---- renal-function scaling of clearances -------------------------------
double crf = CRCL / 90.0;
CLcef = CL_CEF * (FREN_CEF*crf + (1.0 - FREN_CEF));   // biliary escape route
CLamx = CL_AMX * crf;
CLlvx = CL_LVX * (FREN_LVX*crf + (1.0 - FREN_LVX));

// ---- initial conditions --------------------------------------------------
BE_0   = B0 * (0.4 + 1.2*SEV0);
BP_0   = 0.02 * BE_0;
AM_0   = AM0;
NB_0   = NB0;
NL_0   = 1.0;
CRP_0  = CRP0;
PCT_0  = PCT0;
LYM_0  = LYM0;
PERM_0 = 1.0;
EDEM_0 = 0.04 + 0.12*SEV0;
SURF_0 = 1.0;
VIR_0  = VIRAL * V0;
IL10_0 = 6.0;

[ODE]
//===========================================================================
// 0. Guard rails
//===========================================================================
double be   = (BE   > 1e-6) ? BE   : 0.0;
double bp   = (BP   > 1e-6) ? BP   : 0.0;
double bb   = (BB   > 1e-9) ? BB   : 0.0;
double edem = (EDEM < 0.0) ? 0.0 : ((EDEM > 0.98) ? 0.98 : EDEM);
double surf = (SURF < 0.05) ? 0.05 : ((SURF > 1.0) ? 1.0 : SURF);
double perm = (PERM < 1.0) ? 1.0 : PERM;
double pamp = (PAMP > 0.0) ? PAMP : 0.0;

//===========================================================================
// 1. Drug concentrations: plasma total, plasma free, and free ELF
//===========================================================================
double Ccef_p = CEFC / V1_CEF;
double Camx_p = AMXC / V_AMX;
double Cazi_p = AZIC / V1_AZI;
double Cazi_t = AZIT / V2_AZI;
double Clvx_p = LVXC / V_LVX;
double Chc_p  = HCC  / V_HC;

double Ccef_elf = Ccef_p * FU_CEF * PEN_CEF;                 // free, alveolar
double Camx_elf = Camx_p * FU_AMX * PEN_AMX;
double Cazi_elf = Cazi_t * KP_AZI_ELF * FU_AZI;              // deep-cmt driven
double Clvx_elf = Clvx_p * FU_LVX * PEN_LVX;

//===========================================================================
// 2. Antibacterial PD -- Emax on free ELF concentration, EC50 scaled to MIC.
//    fT>MIC and fAUC/MIC are NOT parameters: they are integrals of these
//    curves, accumulated in TAM and AUCF below.
//===========================================================================
double ec_cef = FEC50_CEF * MIC_CEF;
double ec_amx = FEC50_AMX * MIC_AMX;
double ec_azi = FEC50_AZI * MIC_AZI;
double ec_lvx = FEC50_LVX * MIC_LVX;

double kcef = EMAX_CEF * pow(Ccef_elf, H_CEF) / (pow(Ccef_elf, H_CEF) + pow(ec_cef, H_CEF) + 1e-30);
double kamx = EMAX_AMX * pow(Camx_elf, H_AMX) / (pow(Camx_elf, H_AMX) + pow(ec_amx, H_AMX) + 1e-30);
double kazi = EMAX_AZI * pow(Cazi_elf, H_AZI) / (pow(Cazi_elf, H_AZI) + pow(ec_azi, H_AZI) + 1e-30);
double klvx = EMAX_LVX * pow(Clvx_elf, H_LVX) / (pow(Clvx_elf, H_LVX) + pow(ec_lvx, H_LVX) + 1e-30);

double kbl  = kcef + kamx;                    // combined beta-lactam pressure
double kdrug = kbl + kazi + klvx;

// killing of the tolerant / non-replicating subpopulation is class-specific
double kdrug_p = FTOL_BL*kbl + FTOL_MAC*kazi + FTOL_FQ*klvx;

//===========================================================================
// 3. Corticosteroid: ONE effect site, TWO opposite-signed arms
//===========================================================================
double gc      = (HCE > 0.0) ? HCE : 0.0;
double GC_ANTI = 1.0 - IMAX_GC  * gc / (IC50_GC  + gc);   // protective: NF-kB transrepression
double GC_PHAG = 1.0 - IMAX_GCP * gc / (IC50_GCP + gc);   // ADVERSE: phagocyte suppression
double GC_MIG  = 1.0 - IMAX_GCN * gc / (IC50_GCP + gc);   // annexin-A1: less neutrophil influx

//===========================================================================
// 4. Macrolide immunomodulation -- travels the toxin/cytokine channel,
//    survives full macrolide RESISTANCE (MIC_AZI = 64 kills kazi, not this)
//===========================================================================
double MAC_ANTI = 1.0 - IMAX_MAC  * Cazi_elf / (IC50_MAC + Cazi_elf);
double MAC_PLY  = 1.0 - IMAX_PLY  * Cazi_elf / (IC50_MAC + Cazi_elf);
double MAC_MIG  = 1.0 - IMAX_MIGM * Cazi_elf / (IC50_MAC + Cazi_elf);

//===========================================================================
// 5. Pathogen dynamics
//===========================================================================
double virfac  = 1.0 + EVIR_ADH * VIR / (0.3 + VIR);
double grow    = KG * virfac * be * (1.0 - (be + bp)/BMAX);

double il10sup = 1.0 - IMAX_IL10 * IL10 / (IC50_IL10 + IL10);
double opson   = (VACC > 0.5 ? OPS_VACC : 1.0) * (1.0 - 0.65*IMMSUP);
double phagcap = (KPHAG_AM*AM + KPHAG_N*NL) * opson * il10sup * GC_PHAG;
double hostkill_e = phagcap * be / (be + KM_PHAG);
double hostkill_p = FTOL_HOST * phagcap * bp / (bp + KM_PHAG);

double drugkill_e = kdrug * be;
double drugkill_p = kdrug_p * bp;

dxdt_BE = grow - hostkill_e - drugkill_e - KPERS*be + KREV*bp - KTRANS*perm*be;
dxdt_BP = KPERS*be - KREV*bp - hostkill_p - drugkill_p;
dxdt_BB = KTRANS*perm*be*1e-3 - (KCLBB + 0.6*kdrug)*bb;
dxdt_VIR = -KVIR * VIR;

//===========================================================================
// 6. PAMP pool -- THE lysis-coupled term. beta-lactam kill is a PAMP SOURCE.
//===========================================================================
double lysis_release = (YLYS_BL*kbl + YLYS_FQ*klvx + YLYS_MAC*kazi) * be;
double pamp_in = (YLIVE*grow_pos(grow) + YHOST*hostkill_e + lysis_release)
                 * (1.0 - PLYFRAC*(1.0 - MAC_PLY));
dxdt_PAMP = pamp_in - KPAMP*pamp;

//===========================================================================
// 7. Innate immune activation
//===========================================================================
double STIM = pamp / (pamp + KMPAMP);

dxdt_AM = KAM_IN*(1.0 + EAM*STIM) - KAM_OUT*AM;

double migr = KMIG * IL8 * NB * MAC_MIG * GC_MIG * (1.0 - NL/NLMAX);
if (migr < 0.0) migr = 0.0;
dxdt_NB = KNB_OUT*NB0*(1.0 + EGCSF*(IL6 + IL1)) - KNB_OUT*NB - migr;
dxdt_NL = migr - KNL_OUT*NL;

double effero = KNL_OUT * NL;                      // apoptotic-neutrophil uptake

//===========================================================================
// 8. Cytokine network: feed-forward amplifier, damped by IL-10, SPMs,
//    corticosteroid transrepression and macrolide immunomodulation
//===========================================================================
double cytsum = TNF + IL1 + IL6;
double AMP = 1.0 + EAMP * cytsum/(KAMP + cytsum)
                 * (1.0 - ESPM*SPM/(KSPM50 + SPM));
if (AMP < 1.0) AMP = 1.0;

double src   = (STIM*AM + FNEUT_CYT*NL/10.0) * AMP * GC_ANTI * MAC_ANTI;
double srcv  = 0.55 * VIR/(0.3 + VIR) * AMP * GC_ANTI;   // viral contribution
double inflm = 1.0 - IMAX_IL10*IL10/(IC50_IL10 + IL10);

dxdt_TNF = KS_TNF *(src + srcv)*inflm - KD_TNF *TNF;
dxdt_IL1 = KS_IL1 *(src*STIM + 0.4*srcv)*inflm - KD_IL1 *IL1;   // inflammasome-gated
dxdt_IL6 = KS_IL6 *(src + srcv)*inflm - KD_IL6 *IL6;
dxdt_IL8 = KS_IL8 *(src + 0.3*srcv)*inflm - KD_IL8 *IL8;
dxdt_IL10 = KS_IL10*cytsum/(KAMP + cytsum)*GC_ANTI*0.6 + KD_IL10*6.0 - KD_IL10*IL10;
dxdt_SPM = KS_SPM*effero*(1.0 + 2.0*(1.0 - STIM)) - KD_SPM*SPM;

//===========================================================================
// 9. Acute-phase biomarkers. CRP tracks IL-6; PCT tracks BACTERIAL PAMP and
//    is suppressed by the antiviral interferon programme -> the two markers
//    separate in viral disease and PCT falls first after sterilisation.
//===========================================================================
dxdt_CRP = KS_CRP * IL6/(IL6 + KM_CRP_IL6) + KD_CRP*CRP0 - KD_CRP*CRP;
double pct_vir = 1.0 - IPCT_VIR * VIR/(0.3 + VIR);
dxdt_PCT = KS_PCT * pamp/(pamp + KM_PCT) * pct_vir + KD_PCT*PCT0 - KD_PCT*PCT;
dxdt_LYM = KLYM_OUT*LYM0 - KLYM_OUT*LYM - ELYM*(cytsum + 700.0*gc/(IC50_GC+gc))*LYM;

//===========================================================================
// 10. Alveolar barrier, oedema, surfactant, shunt
//===========================================================================
double injury = KS_PERM*(TNF + IL1) + KS_PERM_N*NL + EVIR_BAR*KS_PERM_N*VIR/(0.3+VIR);
dxdt_PERM = injury - KD_PERM*(perm - 1.0)*(1.0 + 0.8*SPM);

double afc = KAFC * surf * (1.0 - IAFC_IL8*IL8/(IC50_AFC + IL8));
dxdt_EDEM = KFILT*(perm - 1.0)*(1.0 - edem) - afc*edem;
dxdt_SURF = KS_SURF*(1.0 - surf) - KD_SURF*(NL/10.0 + (perm - 1.0))*surf;
dxdt_FIBP = KS_FIB*edem*edem*(1.0 + 0.5*FIBP) - KD_FIB*FIBP;

//===========================================================================
// 11. Systemic haemodynamics, lactate, kidney
//===========================================================================
double logbb = (bb > 1.0) ? log10(bb) : 0.0;
double mapdrive = KS_MAP*(TNF + IL1) + KS_MAP_BB*logbb;
double supp_extra = EVASO*VASOPRESS + EMAP_GC*gc/(IC50_GC + gc);   // mmHg-equivalents
dxdt_MAPD = mapdrive - KD_MAP*MAPD*(1.0 + supp_extra/10.0);

double mapexc = (MAPD > MAPTH) ? (MAPD - MAPTH) : 0.0;
dxdt_LACT = KS_LACT*mapexc + KS_LACT_C*cytsum + KD_LACT*LACT0 - KD_LACT*LACT;
dxdt_AKID = KS_AKI*mapexc*(1.0 - AKID) - KD_AKI*AKID;

//===========================================================================
// 12. PK
//===========================================================================
dxdt_CEFC = -CLcef/V1_CEF*CEFC - Q_CEF/V1_CEF*CEFC + Q_CEF/V2_CEF*CEFP;
dxdt_CEFP =  Q_CEF/V1_CEF*CEFC - Q_CEF/V2_CEF*CEFP;
dxdt_AMXD = -KA_AMX*AMXD;
dxdt_AMXC =  KA_AMX*AMXD*F_AMX - CLamx/V_AMX*AMXC;
dxdt_AZID = -KA_AZI*AZID;
dxdt_AZIC =  KA_AZI*AZID*F_AZI - CL_AZI/V1_AZI*AZIC - Q_AZI/V1_AZI*AZIC + Q_AZI/V2_AZI*AZIT;
dxdt_AZIT =  Q_AZI/V1_AZI*AZIC - Q_AZI/V2_AZI*AZIT;
dxdt_LVXD = -KA_LVX*LVXD;
dxdt_LVXC =  KA_LVX*LVXD*F_LVX - CLlvx/V_LVX*LVXC;
dxdt_HCC  = -CL_HC/V_HC*HCC;
dxdt_HCE  =  KE0_HC*(Chc_p - HCE);

//===========================================================================
// 13. Emergent PK/PD indices and cumulative hazard
//===========================================================================
// the "active" beta-lactam is whichever one is actually on board; if both,
// use the more demanding (higher) MIC so fT>MIC is never flattered.
double blconc = Ccef_elf + Camx_elf;
double blmic  = MIC_CEF;
if ((AMXC + AMXD) > 1e-9 && MIC_AMX > blmic) blmic = MIC_AMX;
if ((AMXC + AMXD) > 1e-9 && CEFC < 1e-9)     blmic = MIC_AMX;
double above = 1.0/(1.0 + exp(-8.0*(log((blconc + 1e-12)/blmic))));
dxdt_TAM  = above;
dxdt_AUCF = Clvx_elf;

// severity -> hazard
double qs_raw = QS0 + (QSMAX - QS0)*pow(edem,HQS)/(pow(edem,HQS)+pow(E50_QS,HQS));
double hpv    = HPV_MAX*(1.0 - IHPV_CYT*cytsum/(KAMP + cytsum));
double qs     = qs_raw*(1.0 - hpv);
double pf     = 500.0*exp(-KPF*qs);
double mapnow = MAP0 - MAPD;

double sofa_r = (pf < 100 ? 4 : (pf < 200 ? 3 : (pf < 300 ? 2 : (pf < 400 ? 1 : 0))));
double sofa_c = (VASOPRESS > 0.5 ? 3 : (mapnow < 70 ? 1 : 0));
double sofa_k = (AKID > 0.75 ? 4 : (AKID > 0.55 ? 3 : (AKID > 0.35 ? 2 : (AKID > 0.15 ? 1 : 0))));
double sofa_n = (LACT > 4.0 ? 2 : 0);
double sofa   = sofa_r + sofa_c + sofa_k + sofa_n;

double logbe = (be > 1.0) ? log10(be) : 0.0;
dxdt_CHZ = HAZ0 * exp(HAZ_SOFA*sofa + HAZ_AGE*(AGE > 50 ? AGE - 50 : 0)
                      + HAZ_BB*logbb + 0.10*logbe + 0.9*IMMSUP);

[TABLE]
double edm  = (EDEM < 0) ? 0 : ((EDEM > 0.98) ? 0.98 : EDEM);
double cyts = TNF + IL1 + IL6;

// ---- gas exchange ---------------------------------------------------------
double qsr  = QS0 + (QSMAX - QS0)*pow(edm,HQS)/(pow(edm,HQS)+pow(E50_QS,HQS));
double hpvf = HPV_MAX*(1.0 - IHPV_CYT*cyts/(KAMP + cyts));
double Qs   = qsr*(1.0 - hpvf);
double PF   = 500.0*exp(-KPF*Qs);
double PaO2 = PF*FIO2;
double SpO2 = 100.0/(23400.0/(pow(PaO2,3.0) + 150.0*PaO2) + 1.0);
if (SpO2 > 99.5) SpO2 = 99.5;

// ---- vitals ---------------------------------------------------------------
double Temp = TEMP0 + (1.0 - ANTIPYR)*KTEMP*(IL6 + IL1)/(KMTEMP + IL6 + IL1);
double MAPv = MAP0 - MAPD;
double RR   = RR0 + KRR_QS*Qs + KRR_CYT*cyts;
double HR   = HR0 + KHR_T*(Temp - TEMP0) + KHR_MAP*MAPD;

// ---- scores ---------------------------------------------------------------
double sr = (PF < 100 ? 4 : (PF < 200 ? 3 : (PF < 300 ? 2 : (PF < 400 ? 1 : 0))));
double sc = (VASOPRESS > 0.5 ? 3 : (MAPv < 70 ? 1 : 0));
double sk = (AKID > 0.75 ? 4 : (AKID > 0.55 ? 3 : (AKID > 0.35 ? 2 : (AKID > 0.15 ? 1 : 0))));
double sn = (LACT > 4.0 ? 2 : 0);
double SOFA = sr + sc + sk + sn;

double conf   = (LACT > 4.0 || MAPv < 65) ? 1 : 0;         // confusion surrogate
double curb   = conf + (AKID > 0.35 ? 1 : 0) + (RR >= 30 ? 1 : 0)
                + (MAPv < 65 ? 1 : 0) + (AGE >= 65 ? 1 : 0);

// ---- Halm criteria for clinical stability ---------------------------------
double stable = ((Temp <= 37.8) && (HR <= 100) && (RR <= 24) && (MAPv >= 70)
                 && (SpO2 >= 90)) ? 1 : 0;

// ---- exposure indices -----------------------------------------------------
double hrs   = (TIME > 0.0) ? TIME : 1.0;
double fTMIC = 100.0*TAM/hrs;                                   // % of elapsed time
double fAUCMIC = AUCF/MIC_LVX;                                  // running fAUC/MIC
double Mort  = 100.0*(1.0 - exp(-CHZ));                         // cumulative mortality %

// ---- concentrations (report) ----------------------------------------------
double Ccef  = CEFC/V1_CEF;
double Cazie = (AZIT/V2_AZI)*KP_AZI_ELF*FU_AZI;
double Clvxe = (LVXC/V_LVX)*FU_LVX*PEN_LVX;
double Ccefe = (CEFC/V1_CEF)*FU_CEF*PEN_CEF;
double Camxe = (AMXC/V_AMX)*FU_AMX*PEN_AMX;
double Chc   = HCC/V_HC;
double Gluc  = 5.4 + EGLU_GC*HCE/(IC50_GC + HCE);

double logBE = (BE > 1.0) ? log10(BE) : 0.0;
double logBP = (BP > 1.0) ? log10(BP) : 0.0;
double logBB = (BB > 1.0) ? log10(BB) : 0.0;

capture Bacteria_log10        = logBE;
capture Persisters_log10      = logBP;
capture Bacteraemia_log10     = logBB;
capture PAMP_pool             = PAMP;
capture Ceftriaxone_plasma    = Ccef;
capture Ceftriaxone_ELF_free  = Ccefe;
capture Amoxicillin_ELF_free  = Camxe;
capture Azithromycin_ELF      = Cazie;
capture Levofloxacin_ELF_free = Clvxe;
capture Hydrocortisone_plasma = Chc;
capture fT_above_MIC_pct      = fTMIC;
capture fAUC_over_MIC         = fAUCMIC;
capture Alveolar_macrophage   = AM;
capture Lung_neutrophils      = NL;
capture Blood_neutrophils     = NB;
capture TNF_alpha             = TNF;
capture IL1_beta              = IL1;
capture IL6_level             = IL6;
capture IL8_level             = IL8;
capture IL10_level            = IL10;
capture SPM_level             = SPM;
capture CRP_level             = CRP;
capture PCT_level             = PCT;
capture Lymphocytes           = LYM;
capture Permeability          = PERM;
capture Oedema_fraction       = edm;
capture Surfactant_function   = SURF;
capture Fibroproliferation    = FIBP;
capture Shunt_fraction        = Qs;
capture PaO2_FiO2             = PF;
capture SpO2_pct              = SpO2;
capture Temperature           = Temp;
capture Resp_rate             = RR;
capture Heart_rate            = HR;
capture MAP_mmHg              = MAPv;
capture Lactate               = LACT;
capture Renal_injury          = AKID;
capture SOFA_score            = SOFA;
capture CURB65                = curb;
capture Clinically_stable     = stable;
capture Glucose               = Gluc;
capture Mortality_pct         = Mort;

// NOTE: every reported quantity above is declared with `capture` inside
// [TABLE]; there is deliberately no separate [CAPTURE] block, because listing
// the same name in both places redeclares it and fails to compile.


##  ============================================================================
##  R-side scenario helpers (comments; parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("cap_mrgsolve_model.R")
##
##  ## Dosing shorthand (time in HOURS) -----------------------------------------
##  ##  ceftriaxone 2 g IV q24h  : ev(amt=2000, cmt="CEFC", ii=24, addl=n)
##  ##  amoxicillin 1 g PO q8h   : ev(amt=1000, cmt="AMXD", ii=8,  addl=n)
##  ##  azithromycin 500 mg PO qd: ev(amt=500,  cmt="AZID", ii=24, addl=n)
##  ##  levofloxacin 750 mg qd   : ev(amt=750,  cmt="LVXD", ii=24, addl=n)
##  ##  hydrocortisone 200 mg/d continuous infusion:
##  ##                             ev(amt=200, rate=200/24, cmt="HCC", ii=24, addl=n)
##
##  CAP_simulate_scenarios <- function(end_h = 336) {
##
##    d <- function(n) n - 1L                        # addl for n daily doses
##    abx_start <- 6                                 # h, door-to-antibiotic time
##
##    sc <- list(
##      "1. Untreated natural history (pre-antibiotic era)" = list(
##         ev = ev(amt = 0, cmt = "CEFC", time = 0),
##         p  = list(SEV0 = 0.55)),
##
##      "2. Amoxicillin 1 g PO q8h -- mild outpatient CAP (CURB-65 0-1)" = list(
##         ev = ev(amt = 1000, cmt = "AMXD", time = abx_start, ii = 8, addl = d(15)),
##         p  = list(SEV0 = 0.30, AGE = 52)),
##
##      "3. Ceftriaxone 2 g IV q24h -- ward CAP monotherapy" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = abx_start, ii = 24, addl = d(7)),
##         p  = list(SEV0 = 0.55)),
##
##      "4. Ceftriaxone + azithromycin -- guideline combination" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = abx_start, ii = 24, addl = d(7)) +
##              ev(amt = 500,  cmt = "AZID", time = abx_start, ii = 24, addl = d(5)),
##         p  = list(SEV0 = 0.55)),
##
##      "5. Levofloxacin 750 mg qd -- respiratory fluoroquinolone monotherapy" = list(
##         ev = ev(amt = 750, cmt = "LVXD", time = abx_start, ii = 24, addl = d(7)),
##         p  = list(SEV0 = 0.55)),
##
##      "6. SEVERE CAP: ceftriaxone + azithromycin + hydrocortisone (CAPE-COD)" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = abx_start, ii = 24, addl = d(7)) +
##              ev(amt = 500,  cmt = "AZID", time = abx_start, ii = 24, addl = d(5)) +
##              ev(amt = 200,  cmt = "HCC",  time = abx_start, rate = 200/24,
##                 ii = 24, addl = d(4)),
##         p  = list(SEV0 = 0.85, VASOPRESS = 1, FIO2 = 0.60, AGE = 70)),
##
##      "7. SEVERE CAP + steroid but PENICILLIN-NON-SUSCEPTIBLE isolate" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = abx_start, ii = 24, addl = d(7)) +
##              ev(amt = 500,  cmt = "AZID", time = abx_start, ii = 24, addl = d(5)) +
##              ev(amt = 200,  cmt = "HCC",  time = abx_start, rate = 200/24,
##                 ii = 24, addl = d(4)),
##         p  = list(SEV0 = 0.85, VASOPRESS = 1, FIO2 = 0.60, AGE = 70,
##                   MIC_CEF = 4.0, MIC_AZI = 64)),
##
##      "8. Short course: ceftriaxone 5 days then stop (Uranga/Dinh)" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = abx_start, ii = 24, addl = d(5)),
##         p  = list(SEV0 = 0.55)),
##
##      "9. Delayed antibiotic (door-to-needle 18 h) in severe CAP" = list(
##         ev = ev(amt = 2000, cmt = "CEFC", time = 18, ii = 24, addl = d(7)) +
##              ev(amt = 500,  cmt = "AZID", time = 18, ii = 24, addl = d(5)),
##         p  = list(SEV0 = 0.85, VASOPRESS = 1, FIO2 = 0.60, AGE = 70))
##    )
##
##    purrr::imap_dfr(sc, function(x, lab) {
##      m <- mod
##      if (length(x$p)) m <- do.call(param, c(list(m), x$p))
##      mrgsim(m, events = x$ev, end = end_h, delta = 0.25) |>
##        as_tibble() |> mutate(scenario = lab)
##    })
##  }
##
##  ## ---- What each scenario is meant to show -------------------------------
##  ## 1 vs 3 : host-only clearance takes ~7-9 d ("the crisis") with a large
##  ##          cumulative hazard; an effective beta-lactam collapses BE within
##  ##          ~24-36 h and Mortality_pct falls several-fold.
##  ## 3 vs 4 : adding azithromycin barely changes Bacteria_log10 but lowers the
##  ##          PAMP_pool spike, IL8/TNF peak and Shunt_fraction -> earlier
##  ##          Clinically_stable. Re-run scenario 4 with MIC_AZI = 64 and the
##  ##          benefit LARGELY PERSISTS: that is the macrolide paradox.
##  ## 3 vs 5 : same bacterial endpoint by two different PK/PD routes -- watch
##  ##          fT_above_MIC_pct (ceftriaxone, ~100%) against fAUC_over_MIC
##  ##          (levofloxacin, ~70 by 24 h). Neither index was a parameter.
##  ## 6 vs 3 : hydrocortisone in severe CAP cuts the cytokine amplifier, shunt,
##  ##          vasopressor need and Mortality_pct (CAPE-COD direction).
##  ## 6 vs 7 : IDENTICAL steroid regimen, only MIC changed. With no effective
##  ##          antibiotic the immunosuppressive arm dominates: BE rebounds and
##  ##          Mortality_pct rises ABOVE the no-steroid case. The sign of the
##  ##          steroid effect is conditional on bacterial clearance, not on the
##  ##          steroid dose.
##  ## 3 vs 8 : stopping at day 5 is safe when BE is already sterilised, but
##  ##          Persisters_log10 (BP) is what decides relapse -- raise KPERS or
##  ##          FTOL_BL and scenario 8 relapses while scenario 3 does not.
##  ## 6 vs 9 : a 12-hour delay to first dose lets BE and PAMP reach a higher
##  ##          peak, and the extra cumulative hazard accrued during the delay is
##  ##          never recovered afterwards (Kumar 2006 geometry).
##  ##
##  ## ---- Diagnostic plots ---------------------------------------------------
##  ## df <- CAP_simulate_scenarios(336)
##  ## ggplot(df, aes(time/24, Bacteria_log10, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/24, PAMP_pool,      colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/24, PaO2_FiO2,      colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/24, Mortality_pct,  colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/24, CRP_level,      colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/24, PCT_level,      colour = scenario)) + geom_line()
##  ##
##  ## ---- Sensitivity handles worth turning ----------------------------------
##  ## YLYS_BL   1.0 -> 0.2 : abolishes the post-first-dose PAMP surge; the early
##  ##                        deterioration and much of the macrolide benefit
##  ##                        disappear with it (the mechanism is falsifiable).
##  ## IMAX_GCP  0.45 -> 0  : removes the adverse steroid arm; scenario 7 then
##  ##                        stops being harmful, which is the whole claim.
##  ## KPERS     0.010 -> 0 : removes relapse-after-short-course entirely.
##  ## CRCL      90 -> 25   : renal impairment; watch levofloxacin accumulate and
##  ##                        ceftriaxone barely move (biliary escape route).
##  ## VIRAL     0 -> 1     : influenza co-infection; PCT_level stays low while
##  ##                        CRP_level rises -- and steroid turns harmful again
##  ##                        because there is no bacterial target to sterilise.
