##  Premenstrual Dysphoric Disorder (PMDD, 월경전 불쾌장애) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : PMDD — a cyclical affective disorder confined to the luteal phase
##             of the ovulatory menstrual cycle, remitting within days of menses
##             onset, affecting ~1.6-5.5% of reproductive-age women.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.5)
##
##  ---------------------------------------------------------------------------
##  WHAT THIS MODEL COMMITS TO, AND WHY
##  ---------------------------------------------------------------------------
##  The obvious model of PMDD — "the luteal phase floods the brain with
##  progesterone/allopregnanolone, so lower it" — is already falsified by the
##  clinic, and this model refuses it:
##
##    * luteal E2, P4 and allopregnanolone (ALLO) concentrations in PMDD are
##      indistinguishable from those of asymptomatic controls, so a level model
##      has no disease variable at all;
##    * yet ovarian suppression abolishes the symptoms and physiological
##      add-back reinstates them in PMDD while doing nothing in controls
##      (Schmidt 1998; Schmidt 2017), so the ovarian steroids ARE causal;
##    * lowering ALLO helps (dutasteride 2.5 mg) but only at the HIGH dose, the
##      low dose does nothing (Martinez 2016);
##    * blocking ALLO at its GABA-A site helps (sepranolone, Bixo 2017);
##    * and SSRIs, which RAISE brain ALLO by shifting 3alpha-HSD toward the
##      reductive direction (Griffin & Mellon 1999), help too — and within
##      1-2 days rather than the 2-4 weeks they need in major depression.
##
##  Two structural commitments reconcile all five:
##
##   (1) NON-MONOTONIC TRANSDUCTION.  The affective drive produced by
##       neurosteroid load L at GABA-A is unimodal,
##
##            NS_DRIVE = SENS * (L/KP) * exp(1 - L/KP)      [peaks at L = KP]
##
##       Low-to-moderate ALLO is anxiogenic/dysphoric through extrasynaptic
##       alpha4-beta-delta receptors; high load is sedative.  The DISEASE
##       PARAMETER is KP — where the peak sits relative to the physiological
##       luteal range — not the range itself.  Controls in this model have
##       identical hormones and differ only in KP and two gains.
##
##   (2) A SLOW, SYMMETRIC CHANGE DETECTOR sets the gain SENS.  GABA-A subunit
##       composition moves on a timescale of DAYS while ALLO turns over in
##       MINUTES: delta-subunit abundance follows the ALLO exposure HISTORY and
##       is TOLERANCE-like (GAMMA_D is negative), while alpha4 abundance follows
##       the RATE OF CHANGE of neurosteroid and total progestogen tone and is
##       SENSITISING (GAMMA_A4 positive).  The detector is symmetric: the onset
##       of exposure drives it as well as the withdrawal.
##
##  Five consequences follow that a level detector cannot produce.  Each one is
##  simulated below, and each one disappears or inverts in the FALSIFICATION
##  run (MONOTONE = 1, RATE_OFF = 1, GAMMA_D = GAMMA_A4 = 0):
##
##    [P1] the symptom peak LAGS the ALLO peak by ~5 days (cycle day ~28 versus
##         an ALLO peak on day ~22); falsified model: ~1 day.
##    [P2] dutasteride 2.5 mg cuts the luteal burden by 45% while 0.5 mg cuts
##         it by 10% — the top of the inverted U is locally FLAT, so a small
##         ALLO reduction buys nothing; falsified model: 65% vs 36%, i.e. an
##         ordinary graded dose-response.
##    [P3] a SEDATIVE-dose exogenous neurosteroid analogue helps (+46%) while a
##         SUB-sedative dose of the same agent makes things worse (-6%);
##         falsified model: both harmful, the large dose catastrophically so.
##    [P4] a 4-day hormone-free interval beats a 7-day one by 8.4 points
##         because the driver is the withdrawal RATE, not the trough LEVEL;
##         falsified model: the two regimens are equivalent.
##    [P5] E2/P4 add-back on ovarian suppression reinstates symptoms
##         TRANSIENTLY (+10.7 DRSP-11 points in the first 10 days) and they then
##         remit (+0.5 points by day 112) under continued, IDENTICAL hormone
##         input; falsified model: +18.3 -> +23.3, it never fades.
##
##  ---------------------------------------------------------------------------
##  Scope    : 60 ODE compartments — HPO cycle engine (6) + neurosteroidogenesis
##             (5) + GABA-A composition plasticity and change detectors (5) +
##             serotonergic system (3) + corticolimbic circuit (3) + HPA axis (3)
##             + somatic/peripheral (4) + 11 DRSP symptom domains + organ-system
##             safety (3: hot flushes, lumbar BMD, endometrium) + drug PK (15) +
##             pituitary GnRH-receptor downregulation (1).
##  Time     : DAYS.  The cycle engine is driven by cycle day
##             cd = fmod(TIME, TCYC) + 1, so TIME = 0 is menses day 1.
##  Units    : E2 pg/mL; P4 ng/mL; ALLO nM; drug concentrations ng/mL;
##             FSH/LH/follicle/corpus-luteum in normalised model units;
##             receptor states as multiples of baseline; each DRSP domain 1-6;
##             DRSP-11 = sum of the 11 domains (11 = no symptoms, 66 = maximum);
##             BMD as % change from baseline; hot flushes per day.
##  Endpoint : DRSP_11 (all domains) and DRSP_CORE (the 5 core affective
##             domains, on which the DSM-5 >=30% luteal-vs-follicular criterion
##             is evaluated).
##  Scenarios: 30 prebuilt — see PMDD_simulate_scenarios() at the bottom.
##  Twin     : pmdd_python_twin.py reimplements this identical system in the
##             Python standard library and asserts 38 numerical checks; every
##             number quoted in README.md comes from that file.
##  Anchors  : Schmidt 1998 NEJM 338:209 (add-back reinstates symptoms in PMDD
##             and not in controls); Schmidt 2017 Am J Psychiatry 174:980
##             (symptoms are triggered by CHANGE in ovarian steroids, not by
##             continuous stable levels); Martinez 2016 Neuropsychopharmacology
##             41:1093 (dutasteride 2.5 mg yes / 0.5 mg no); Bixo 2017
##             Psychoneuroendocrinology 80:46 (sepranolone); Yonkers 1997 JAMA
##             278:983 and Steiner 1995 NEJM 332:1529 (SSRIs); Yonkers 2005
##             Obstet Gynecol 106:492 (drospirenone/EE 24/4); Thys-Jacobs 1998
##             Am J Obstet Gynecol 179:444 (calcium); Comasco 2021 Am J
##             Psychiatry 178:256 (ulipristal); Smith 1998 Nature 392:926
##             (withdrawal-induced alpha4 upregulation).
##  Caveat   : an educational/illustrative QSP model, not a validated clinical
##             tool.  Two parameters are FITTED rather than taken from the
##             literature — KI_ISO (to the sepranolone effect size) and
##             W_SHT_AMY (to the sertraline effect size); everything else is set
##             from published PK or from the physiological ranges asserted in
##             the twin's check table.
##  ============================================================================

[PROB]
# Premenstrual Dysphoric Disorder (PMDD) — 60-compartment QSP model
# Inverted-U neurosteroid transduction + slow symmetric GABA-A change detector

[PARAM] @annotated
// ---------------- HPO cycle engine ----------------------------------------
TCYC        : 28.0  : Cycle length (d)
KFSH_IN     : 2.4   : FSH synthesis rate (1/d)
KFSH_OUT    : 0.55  : FSH elimination (1/d)
KINH        : 0.30  : Inhibin (follicle-proportional) feedback constant
KLH_IN      : 1.6   : Tonic LH synthesis (1/d)
KLH_OUT     : 0.9   : LH elimination (1/d)
SURGE_AMP   : 26.0  : LH surge amplitude
SURGE_DAY   : 13.6  : LH surge centre (cycle day)
SURGE_SD    : 0.55  : LH surge width (d)
KFG         : 0.42  : Autocatalytic follicular growth rate (1/d)
REC         : 0.030 : Zero-order follicular recruitment (1/d)
KFSH_M      : 1.20  : Half-saturation of the follicular FSH response
FSH_THR     : 0.90  : FSH recruitment threshold
FMAX        : 1.0   : Maximum follicle mass
KFL         : 0.06  : Follicular atresia (1/d)
KOV         : 20.0  : Ovulatory flux constant (1/d)
OVUL_DAY    : 14.0  : Ovulation day
OVUL_SD     : 0.45  : Ovulation window width (d)
KCL         : 0.50  : Corpus-luteum seeding from the ovulatory flux
KCL_G       : 1.00  : Corpus-luteum growth rate (1/d)
CL_MAX      : 3.10  : Corpus-luteum carrying capacity
KLUT0       : 0.05  : Baseline luteolysis (1/d)
KLUT1       : 1.25  : Programmed late-luteal luteolysis (1/d)
LUT_REG_DAY : 24.0  : Onset of programmed luteolysis (cycle day)
LUT_REG_SD  : 0.75  : Steepness of luteolysis onset (d)
KE2F        : 3520  : Follicular E2 production constant (pg/mL/d)
E2_HILL     : 3.0   : Nonlinearity of E2 production in follicle maturity
KE2L        : 60.0  : Luteal E2 production constant (pg/mL/d)
KE2_OUT     : 2.2   : E2 elimination (1/d)
E2_BASE     : 30.0  : Non-ovarian E2 floor (pg/mL)
KP4         : 7.6   : Luteal P4 production constant (ng/mL/d)
KP4_OUT     : 2.0   : P4 elimination (1/d)
P4_BASE     : 0.25  : Adrenal P4 floor (ng/mL)
KP4_FB      : 3.0   : Luteal P4 feedback on the GnRH axis (ng/mL)
// ---------------- neurosteroidogenesis ------------------------------------
K5AR        : 3.0   : 5-alpha-reductase (SRD5A1) flux constant (1/d)
KDHP        : 3.2   : 5-alpha-DHP turnover (1/d)
K3HSD       : 3.0   : 3-alpha-HSD reductive flux constant (1/d)
KALLOP      : 7.0   : Plasma ALLO clearance (1/d)
ADR_ALLO    : 8.26  : Adrenal/non-luteal ALLO input (nM/d)
KIN_B       : 7.2   : Plasma-to-brain ALLO transfer (1/d)
KOUT_B      : 8.0   : Brain ALLO clearance (1/d)
DENOVO      : 1.0   : De-novo brain neurosteroidogenesis (nM/d)
W_STRESS_NS : 0.55  : Stress recruitment of de-novo synthesis
IC50_5AR1   : 110.0 : Dutasteride IC50 at brain SRD5A1 (ng/mL)
EMAX_HSD    : 0.55  : Maximum SSRI-driven increase in 3-alpha-HSD flux
EC50_HSD    : 30.0  : SSRI EC50 for the 3-alpha-HSD shift (ng/mL)
KISO_OUT    : 5.0   : Brain isoallopregnanolone clearance (1/d)
KI_ISO      : 0.80  : Isoallopregnanolone Ki at the ALLO site (FITTED)
K_ZUR       : 0.83  : Exogenous neurosteroid analogue elimination (1/d)
// ---------------- GABA-A plasticity: the slow change detector -------------
TAU_M       : 1.0   : ALLO exposure-memory time constant (d)
TAU_MP      : 1.0   : Progestogen-tone memory time constant (d)
TAU_D       : 5.0   : Delta-subunit time constant (d)
TAU_A4      : 1.2   : Alpha4-subunit time constant (d)
HD          : 1.25  : Maximum delta upregulation
KD          : 3.0   : ALLO for half-maximal delta upregulation (nM)
HA          : 2.20  : Maximum alpha4 upregulation
KA          : 0.55  : Change signal for half-maximal alpha4 upregulation
KRISE       : 0.55  : Weight of a RISING signal relative to a falling one
W_PROG      : 0.85  : Weight of progestogen-tone change relative to ALLO
GAMMA_D     : -0.35 : Delta gain — NEGATIVE = tolerance (controls -0.05)
GAMMA_A4    : 1.50  : Alpha4 gain — POSITIVE = sensitisation (controls 0.25)
// ---------------- inverted-U transduction ---------------------------------
KP          : 5.0   : Neurosteroid load at the response PEAK (nM) — the disease parameter (controls 13)
MONOTONE    : 0     : 1 = replace the inverted U with a level detector
RATE_OFF    : 0     : 1 = disable every rate/withdrawal detector
MONO_GAIN   : 1.66  : Scale of the level detector (peak-matched to the base model)
NS_HILL     : 4.0   : Hill coefficient of the affective transduction
NS50        : 1.50  : NS_DRIVE giving half-maximal affective effect
BZEQ        : 0.12  : Alprazolam ng/mL to nM ALLO-equivalent load
W_BZ_AMY    : 1.30  : Direct benzodiazepine anxiolysis at the BZ site
PREG_EQ     : 0.35  : Pregnanolone/THDOC additive load (nM)
TAU_ME2     : 6.0   : E2 memory time constant (d)
// ---------------- serotonergic system -------------------------------------
KS_SYN      : 1.0   : 5-HT synthesis (1/d)
KS_OUT      : 1.0   : 5-HT clearance by reuptake (1/d)
OCC_MAX     : 0.85  : Maximum SERT occupancy
EC50_SERT   : 13.0  : Sertraline-equivalent EC50 at SERT (ng/mL)
POT_FLX     : 0.50  : Fluoxetine+norfluoxetine potency vs sertraline
POT_DMS     : 0.05  : Desmethylsertraline potency vs sertraline
WB          : 0.50  : 5-HT1A autoreceptor brake strength
TAU_DES     : 12.0  : Autoreceptor desensitisation time constant (d)
KD2         : 1.6   : Autoreceptor desensitisation gain
KBDNF       : 1.10  : BDNF/TrkB plasticity gain
TAU_BDNF    : 14.0  : BDNF/TrkB plasticity time constant (d)
K5HT_NS     : 0.28  : Luteal 5-HT suppression by the neurosteroid drive (1/d)
// ---------------- corticolimbic -------------------------------------------
TAU_AMY     : 0.5   : Amygdala reactivity time constant (d)
TAU_PFC     : 0.8   : Prefrontal control time constant (d)
TAU_REW     : 1.2   : Reward-system time constant (d)
W_NS_AMY    : 1.50  : Neurosteroid drive on amygdala reactivity
W_CORT_AMY  : 0.45  : Cortisol on amygdala reactivity
W_SHT_AMY   : 1.25  : 5-HT suppression of amygdala reactivity (FITTED)
W_PFC_AMY   : 0.70  : Top-down prefrontal suppression of the amygdala
W_PROG_AMY  : 0.30  : Progestin-related mood side effect
P_NS_PFC    : 0.34  : Neurosteroid impairment of prefrontal control
P_E2_PFC    : 0.10  : Estradiol support of prefrontal control
CBT         : 0     : CBT/mindfulness prefrontal training (0-0.25)
R_NS_REW    : 0.45  : Neurosteroid blunting of reward
R_BDNF      : 0.30  : BDNF restoration of reward
R_WE2       : 0.15  : E2-withdrawal blunting of reward
// ---------------- HPA axis ------------------------------------------------
TAU_CRH     : 0.2   : CRH time constant (d)
TAU_ACTH    : 0.1   : ACTH time constant (d)
TAU_CORT    : 0.3   : Cortisol time constant (d)
STRESS      : 0.30  : Background psychosocial stress load (0-1)
K_ALLO_BRAKE: 0.45  : ALLO restraint of the HPA axis (lost as SENS rises)
CORT0       : 1.0   : Reference cortisol
// ---------------- somatic -------------------------------------------------
TAU_ALDO    : 1.0   : Aldosterone time constant (d)
A_P4        : 0.55  : P4-driven RAAS activation
TAU_ECFV    : 1.5   : Fluid-volume time constant (d)
ECF_GAIN    : 0.030 : Maximum fractional ECF volume expansion
KI_MR_DRSP  : 9.0   : Drospirenone Ki at the mineralocorticoid receptor (ng/mL)
KI_MR_SPIRO : 1.0   : Spironolactone Ki at the mineralocorticoid receptor (au)
KI_MR_P4    : 22.0  : P4 Ki at the mineralocorticoid receptor (ng/mL)
TAU_BR      : 1.5   : Breast-tenderness time constant (d)
B_E2        : 0.55  : E2 contribution to mastalgia
B_P4        : 0.55  : Progestogen contribution to mastalgia
E2REF       : 120.0 : Reference E2 (pg/mL)
P4REF       : 11.0  : Reference luteal P4 (ng/mL)
TAU_PG      : 0.8   : Prostaglandin time constant (d)
KPG         : 1.0   : Perimenstrual prostaglandin amplitude
NSAID       : 0     : NSAID inhibition of prostaglandin synthesis (0-0.9)
UPA_PR_KI   : 8.0   : Ulipristal Ki at the progesterone receptor (ng/mL)
KI_PR       : 9.0   : Drospirenone Ki at the progesterone receptor (ng/mL)
// ---------------- symptom domains -----------------------------------------
TAU_S       : 0.6   : Symptom-domain time constant (d)
BASE_SYM    : 0.08  : Non-cyclic symptom floor
CA_SUPP     : 0     : Calcium 1200 mg/d fractional relief (0-0.25)
// ---------------- organ / safety ------------------------------------------
TAU_HF      : 2.0   : Hot-flush time constant (d)
HF_MAX      : 9.0   : Maximum hot flushes per day
E50_HF      : 38.0  : E2 for half-maximal thermoneutral-zone narrowing (pg/mL)
HF_SSRI     : 0.45  : Maximum SSRI reduction of hot flushes
KBMD_LOSS   : 0.040 : Hypoestrogenic bone loss (%/d)
E50_BMD     : 45.0  : E2 for half-maximal skeletal hypoestrogenism (pg/mL)
HYPO_REF    : 0.15  : Hypoestrogenism index of a normal ovulatory cycle
KBMD_REC    : 0.010 : Bone recovery rate on re-estrogenisation (1/d)
TAU_ENDO    : 4.0   : Endometrial-state time constant (d)
// ---------------- PK ------------------------------------------------------
KA_SERT     : 14.4  : Sertraline absorption (1/d)
V_SERT      : 1500  : Sertraline V/F (L)
K_SERT      : 0.64  : Sertraline elimination (1/d) — t1/2 26 h
K_DMS       : 0.25  : Desmethylsertraline elimination (1/d)
FM_DMS      : 0.35  : Fraction metabolised to desmethylsertraline
V_FLX       : 2500  : Fluoxetine V/F (L)
K_FLX       : 0.173 : Fluoxetine elimination (1/d) — t1/2 4 d
K_NFLX      : 0.077 : Norfluoxetine elimination (1/d) — t1/2 9 d
FM_NFLX     : 0.60  : Fraction metabolised to norfluoxetine
KA_DRSP     : 9.0   : Drospirenone absorption (1/d)
V_DRSP      : 250   : Drospirenone V/F (L)
K_DRSP      : 0.533 : Drospirenone elimination (1/d) — t1/2 31 h
EC50_SUPP   : 4.0   : Drospirenone/EE EC50 for gonadotropin suppression (ng/mL)
EE_E2EQ     : 72.0  : Estradiol-equivalent activity of EE 20 ug (pg/mL)
KA_LEUP     : 0.075 : Leuprolide depot release (1/d)
V_LEUP      : 25.0  : Leuprolide V (L)
K_LEUP      : 2.8   : Leuprolide elimination (1/d)
K_DS_ON     : 1.60  : GnRH-receptor downregulation rate (1/d)
K_DS_OFF    : 0.045 : GnRH-receptor recovery rate (1/d)
AGON_FLARE  : 2.6   : GnRH-agonist flare amplitude
EC50_LEUP   : 0.9   : Leuprolide EC50 at the pituitary (ng/mL)
KA_SEPRA    : 2.2   : Sepranolone SC absorption (1/d)
V_SEPRA     : 90.0  : Sepranolone V/F (L)
K_SEPRA     : 4.5   : Sepranolone elimination (1/d)
SEPRA_BRAIN : 0.55  : Sepranolone plasma-to-brain transfer (1/d)
KA_DUTA     : 6.0   : Dutasteride absorption (1/d)
V_DUTA      : 500   : Dutasteride V/F (L)
K_DUTA      : 0.0198: Dutasteride elimination (1/d) — t1/2 35 d
KA_ALPZ     : 12.0  : Alprazolam absorption (1/d)
V_ALPZ      : 70.0  : Alprazolam V/F (L)
K_ALPZ      : 1.386 : Alprazolam elimination (1/d) — t1/2 12 h
K_UPA       : 0.35  : Ulipristal elimination (1/d)
EC50_UPA_SUPP: 6.0  : Ulipristal EC50 for gonadotropin suppression (ng/mL)
// ---------------- exogenous hormone / surgery -----------------------------
ADDBACK_E2  : 0     : Zero-order estradiol add-back (pg/mL/d)
ADDBACK_P4  : 0     : Zero-order progesterone add-back (ng/mL/d)
ADDBACK_T0  : 0     : Time at which add-back starts (d)
OOPH        : 0     : 1 = bilateral oophorectomy
SPIRO       : 0     : Spironolactone exposure (au)

[INIT] @annotated
FSH    : 3.0  : Follicle-stimulating hormone (model units)
LH     : 1.8  : Luteinising hormone (model units)
FOLL   : 0.05 : Dominant-follicle mass (model units)
CL     : 0.0  : Corpus-luteum mass (model units)
E2     : 40.0 : Estradiol (pg/mL)
P4     : 0.3  : Progesterone (ng/mL)
DHP    : 0.0  : 5-alpha-dihydroprogesterone (nM)
ALLOP  : 0.0  : Plasma allopregnanolone (nM)
ALLOB  : 1.3  : Brain allopregnanolone (nM)
ISOB   : 0.0  : Brain isoallopregnanolone / sepranolone (nM)
ZUR    : 0.0  : Exogenous neurosteroid analogue (nM ALLO-equivalents)
MALLO  : 1.3  : Neurosteroid exposure memory (nM)
MPROG  : 0.03 : Progestogen-tone memory (normalised)
DELTA  : 1.4  : GABA-A delta-subunit abundance (x baseline)
ALPHA4 : 1.1  : GABA-A alpha4-subunit abundance (x baseline)
ME2    : 40.0 : Estradiol memory (pg/mL)
SHT    : 1.0  : Extracellular 5-HT (x baseline)
DES    : 0.0  : 5-HT1A autoreceptor desensitisation (0-1)
BDNF   : 0.0  : BDNF/TrkB plasticity state
AMY    : 1.0  : Amygdala reactivity (x baseline)
PFC    : 1.0  : Prefrontal top-down control (x baseline)
REW    : 1.0  : Reward-system responsiveness (x baseline)
CRH    : 1.0  : Hypothalamic CRH (x baseline)
ACTH   : 1.0  : Pituitary ACTH (x baseline)
CORT   : 1.0  : Cortisol (x baseline)
ALDO   : 1.0  : Aldosterone (x baseline)
ECFV   : 1.0  : Extracellular fluid volume (x baseline)
BREAST : 0.0  : Breast tenderness signal
PGE    : 0.0  : Endometrial prostaglandin signal
S_IRR  : 1.5  : DRSP irritability / anger (1-6)
S_DEP  : 1.5  : DRSP depressed mood / hopelessness (1-6)
S_ANX  : 1.5  : DRSP anxiety / tension (1-6)
S_LAB  : 1.5  : DRSP affective lability (1-6)
S_ANH  : 1.5  : DRSP anhedonia / loss of interest (1-6)
S_COG  : 1.5  : DRSP concentration difficulty (1-6)
S_FAT  : 1.5  : DRSP fatigue / lethargy (1-6)
S_APP  : 1.5  : DRSP appetite change / craving (1-6)
S_SLP  : 1.5  : DRSP insomnia / hypersomnia (1-6)
S_OVR  : 1.5  : DRSP feeling overwhelmed / out of control (1-6)
S_PHY  : 1.5  : DRSP physical symptoms (1-6)
HF     : 0.0  : Hot flushes per day
BMD    : 0.0  : Lumbar BMD change (%)
ENDO   : 0.0  : Endometrial progestin state (0-1)
SERT_D : 0.0  : Sertraline depot (mg)
SERT_C : 0.0  : Sertraline plasma (ng/mL)
DMS_C  : 0.0  : Desmethylsertraline plasma (ng/mL)
FLX_C  : 0.0  : Fluoxetine plasma (ng/mL)
NFLX_C : 0.0  : Norfluoxetine plasma (ng/mL)
DRSP_D : 0.0  : Drospirenone depot (mg)
DRSP_C : 0.0  : Drospirenone plasma (ng/mL)
LEUP_D : 0.0  : Leuprolide depot (mg)
LEUP_C : 0.0  : Leuprolide plasma (ng/mL)
SEPRA_D: 0.0  : Sepranolone SC depot (mg)
SEPRA_C: 0.0  : Sepranolone plasma (ng/mL)
DUTA_D : 0.0  : Dutasteride depot (mg)
DUTA_C : 0.0  : Dutasteride plasma (ng/mL)
ALPZ_D : 0.0  : Alprazolam depot (mg)
ALPZ_C : 0.0  : Alprazolam plasma (ng/mL)
UPA_C  : 0.0  : Ulipristal acetate plasma (ng/mL)
PITDS  : 0.0  : Pituitary GnRH-receptor downregulation (0-1)

[GLOBAL]
// ---- helpers -------------------------------------------------------------
#define GAUSSF(x, mu, sd) (exp(-0.5*((x)-(mu))*((x)-(mu))/((sd)*(sd))))
#define SIGM(x, x0, k)    (1.0/(1.0+exp(-((x)-(x0))/(k))))
#define CLAMP01(x)        ((x) < 0.0 ? 0.0 : ((x) > 1.0 ? 1.0 : (x)))
#define POSPART(x)        ((x) < 0.0 ? 0.0 : (x))

// ---- quantities shared between [ODE] and [TABLE] -------------------------
namespace {
  double cday, E2_TOT, a5ar, ssri_eq, occ, load, sens, ns_drive, eff;
  double chg, WE2, PROG, gnrh_eff, hypo, sleep_q, bz_occ;
}

[ODE]
cday = fmod(SOLVERTIME, TCYC) + 1.0;                 // cycle day, 1..29

// ═══════════════════════════════ drug PK ═════════════════════════════════
dxdt_SERT_D = -KA_SERT*SERT_D;
dxdt_SERT_C =  KA_SERT*SERT_D/V_SERT*1000.0 - K_SERT*SERT_C;
dxdt_DMS_C  =  FM_DMS*K_SERT*SERT_C - K_DMS*DMS_C;
dxdt_FLX_C  = -K_FLX*FLX_C;
dxdt_NFLX_C =  FM_NFLX*K_FLX*FLX_C - K_NFLX*NFLX_C;
dxdt_DRSP_D = -KA_DRSP*DRSP_D;
dxdt_DRSP_C =  KA_DRSP*DRSP_D/V_DRSP*1000.0 - K_DRSP*DRSP_C;
dxdt_LEUP_D = -KA_LEUP*LEUP_D;
dxdt_LEUP_C =  KA_LEUP*LEUP_D/V_LEUP*1000.0 - K_LEUP*LEUP_C;
dxdt_SEPRA_D= -KA_SEPRA*SEPRA_D;
dxdt_SEPRA_C=  KA_SEPRA*SEPRA_D/V_SEPRA*1000.0 - K_SEPRA*SEPRA_C;
dxdt_DUTA_D = -KA_DUTA*DUTA_D;
dxdt_DUTA_C =  KA_DUTA*DUTA_D/V_DUTA*1000.0 - K_DUTA*DUTA_C;
dxdt_ALPZ_D = -KA_ALPZ*ALPZ_D;
dxdt_ALPZ_C =  KA_ALPZ*ALPZ_D/V_ALPZ*1000.0 - K_ALPZ*ALPZ_C;
dxdt_UPA_C  = -K_UPA*UPA_C;
dxdt_ZUR    = -K_ZUR*ZUR;

// ═══════════════════════ gonadotropin suppression ════════════════════════
double supp_oc  = DRSP_C/(DRSP_C + EC50_SUPP);
double supp_upa = UPA_C/(UPA_C + EC50_UPA_SUPP);
double leup_norm= LEUP_C/(LEUP_C + EC50_LEUP);
dxdt_PITDS = K_DS_ON*leup_norm*(1.0 - PITDS) - K_DS_OFF*PITDS;
// GnRH agonist: flare while PITDS is still low, profound suppression later
gnrh_eff = (1.0 - PITDS)*(1.0 + AGON_FLARE*leup_norm*(1.0 - PITDS));
gnrh_eff *= (1.0 - supp_oc)*(1.0 - 0.55*supp_upa);
gnrh_eff /= (1.0 + POSPART(P4)/KP4_FB);              // luteal P4 feedback
if (gnrh_eff < 0.0) gnrh_eff = 0.0;

// ═══════════════════════════ HPO cycle engine ════════════════════════════
dxdt_FSH = KFSH_IN*gnrh_eff/(1.0 + FOLL/KINH) - KFSH_OUT*FSH;
double surge = SURGE_AMP*GAUSSF(cday, SURGE_DAY, SURGE_SD)
             * CLAMP01((FOLL - 0.25)/0.35)*gnrh_eff;
dxdt_LH = KLH_IN*gnrh_eff + surge - KLH_OUT*LH;

double gonad = (OOPH > 0.5) ? 0.0 : 1.0;
double ovul_flux = KOV*FOLL*GAUSSF(cday, OVUL_DAY, OVUL_SD)
                 * CLAMP01((LH - 2.5)/6.0)*gonad;
// A fresh follicular cohort is recruited each cycle (REC) and then grows
// autocatalytically; the FSH response saturates (KFSH_M) so that the very high
// early-follicular FSH cannot drive explosive growth.
double hfsh = POSPART(FSH - FSH_THR);
hfsh = hfsh/(KFSH_M + hfsh);
dxdt_FOLL = (REC + KFG*FOLL)*hfsh*(1.0 - FOLL/FMAX)*gonad
          - KFL*FOLL - ovul_flux;

double klut = KLUT0 + KLUT1*SIGM(cday, LUT_REG_DAY, LUT_REG_SD);
// CL growth is gated to the post-ovulatory window so that a numerically small
// CL remnant cannot regrow during the follicular phase.
double w_lut = SIGM(cday, 14.8, 0.5)*(1.0 - SIGM(cday, 24.5, 0.7));
double grow  = (CL > 0.02) ? KCL_G*CL*(1.0 - CL/CL_MAX)*w_lut : 0.0;
dxdt_CL = KCL*ovul_flux + grow - klut*CL;

double ab = (SOLVERTIME >= ADDBACK_T0) ? 1.0 : 0.0;
dxdt_E2 = KE2F*pow(FOLL, E2_HILL) + KE2L*CL - KE2_OUT*(E2 - E2_BASE)
        + ab*ADDBACK_E2;
dxdt_P4 = KP4*CL - KP4_OUT*(P4 - P4_BASE) + ab*ADDBACK_P4;

// Ethinylestradiol is not in the E2 state but it IS estrogenic: every
// estrogen-receptor-mediated readout below therefore sees E2_TOT.
E2_TOT = E2 + EE_E2EQ*(DRSP_C/(DRSP_C + 5.0));

// ══════════════════════ neurosteroidogenesis ═════════════════════════════
a5ar    = 1.0/(1.0 + DUTA_C/IC50_5AR1);
ssri_eq = SERT_C + POT_DMS*DMS_C + POT_FLX*(FLX_C + NFLX_C);
double f_hsd = 1.0 + EMAX_HSD*ssri_eq/(EC50_HSD + ssri_eq);

dxdt_DHP   = K5AR*a5ar*POSPART(P4) - KDHP*DHP;
dxdt_ALLOP = K3HSD*f_hsd*DHP + ADR_ALLO*a5ar - KALLOP*ALLOP;
dxdt_ALLOB = KIN_B*ALLOP + DENOVO*(1.0 + W_STRESS_NS*STRESS)*a5ar
           - KOUT_B*ALLOB;
dxdt_ISOB  = SEPRA_BRAIN*SEPRA_C - KISO_OUT*ISOB;

// ═════════ GABA-A composition: the slow, SYMMETRIC change detector ═══════
PROG = POSPART(P4)/P4REF + 1.4*DRSP_C/(DRSP_C + KI_PR);
double ALLO_EFF = ALLOB + ZUR;               // exogenous analogues are sensed too
dxdt_MALLO = (ALLO_EFF - MALLO)/TAU_M;
dxdt_MPROG = (PROG - MPROG)/TAU_MP;
if (RATE_OFF > 0.5) {
  chg = 0.0;
  WE2 = 0.0;
} else {
  double fall_a = POSPART((MALLO - ALLO_EFF)/(MALLO + 0.5));
  double rise_a = POSPART((ALLO_EFF - MALLO)/(MALLO + 0.5));
  double fall_p = POSPART((MPROG - PROG)/(MPROG + 0.25));
  double rise_p = POSPART((PROG - MPROG)/(MPROG + 0.25));
  chg = (fall_a + KRISE*rise_a) + W_PROG*(fall_p + KRISE*rise_p);
  WE2 = POSPART((ME2 - E2_TOT)/(ME2 + 20.0));
}
double delta_ss = 1.0 + HD*ALLOB/(KD + ALLOB);
double a4_ss    = 1.0 + HA*chg/(KA + chg);
dxdt_DELTA  = (delta_ss - DELTA)/TAU_D;
dxdt_ALPHA4 = (a4_ss - ALPHA4)/TAU_A4;
dxdt_ME2    = (E2_TOT - ME2)/TAU_ME2;

// ══════════════ inverted-U neurosteroid transduction ═════════════════════
sens = 1.0 + GAMMA_D*(DELTA - 1.0) + GAMMA_A4*(ALPHA4 - 1.0);
double bz = BZEQ*ALPZ_C/(1.0 + 0.60*(ALPHA4 - 1.0));
load = (ALLOB + PREG_EQ + bz + ZUR)/(1.0 + ISOB/KI_ISO);
if (MONOTONE > 0.5) {
  // Level detector.  MONO_GAIN is chosen so the falsified model reaches the
  // SAME peak drive as the base model on an untreated cycle, so that the
  // comparison cannot be rigged by a difference of scale.
  ns_drive = MONO_GAIN*load/KP;
} else {
  double r = load/KP;
  ns_drive = sens*r*exp(1.0 - r);
}
ns_drive *= (1.0 - CA_SUPP);
eff = pow(ns_drive, NS_HILL)/(pow(ns_drive, NS_HILL) + pow(NS50, NS_HILL));

// ═════════════════════════════ serotonin ═════════════════════════════════
occ = OCC_MAX*ssri_eq/(ssri_eq + EC50_SERT);
double brake = WB*POSPART(SHT - 1.0)*(1.0 - DES);
dxdt_SHT = KS_SYN/(1.0 + brake) - KS_OUT*(1.0 - occ)*SHT - K5HT_NS*eff*SHT;
double des_t = KD2*POSPART(SHT - 1.0);
if (des_t > 1.0) des_t = 1.0;
dxdt_DES  = (des_t - DES)/TAU_DES;
dxdt_BDNF = (KBDNF*POSPART(SHT - 1.0) - BDNF)/TAU_BDNF;

// ══════════════════════════════ HPA axis ═════════════════════════════════
double allo_brake = K_ALLO_BRAKE*(ALLOB/(ALLOB + 2.0))/sens;
dxdt_CRH  = ((STRESS + 0.7)*(1.0 - allo_brake)/(1.0 + 0.8*(CORT - 1.0)) - CRH)
          / TAU_CRH;
dxdt_ACTH = (CRH - ACTH)/TAU_ACTH;
dxdt_CORT = (ACTH - CORT)/TAU_CORT;

// ═══════════════════════════ corticolimbic ═══════════════════════════════
bz_occ = ALPZ_C/(ALPZ_C + 8.0)/(1.0 + 0.60*(ALPHA4 - 1.0));
double prog_ex = DRSP_C/(DRSP_C + KI_PR);
double amy_ss = 1.0 + W_NS_AMY*eff + W_CORT_AMY*(CORT/CORT0 - 1.0)
              - W_SHT_AMY*POSPART(SHT - 1.0) - W_PFC_AMY*(PFC - 1.0)
              - W_BZ_AMY*bz_occ + W_PROG_AMY*prog_ex;
double pfc_ss = 1.0 - P_NS_PFC*eff + P_E2_PFC*(E2_TOT/E2REF - 1.0) + CBT;
double rew_ss = 1.0 - R_NS_REW*eff + R_BDNF*BDNF - R_WE2*WE2;
if (amy_ss < 0.2) amy_ss = 0.2;
if (pfc_ss < 0.2) pfc_ss = 0.2;
if (rew_ss < 0.2) rew_ss = 0.2;
dxdt_AMY = (amy_ss - AMY)/TAU_AMY;
dxdt_PFC = (pfc_ss - PFC)/TAU_PFC;
dxdt_REW = (rew_ss - REW)/TAU_REW;

// ═════════════════════════════ somatic ═══════════════════════════════════
dxdt_ALDO = (1.0 + A_P4*POSPART(P4)/P4REF - ALDO)/TAU_ALDO;
double mr_block = 1.0/(1.0 + DRSP_C/KI_MR_DRSP + SPIRO/KI_MR_SPIRO
                       + POSPART(P4)/KI_MR_P4);
dxdt_ECFV = (1.0 + ECF_GAIN*ALDO*mr_block - ECFV)/TAU_ECFV;
double pr_block = 1.0/(1.0 + UPA_C/UPA_PR_KI);
double br_ss = B_E2*E2_TOT/E2REF
             + B_P4*(POSPART(P4)/P4REF + prog_ex)*pr_block;
dxdt_BREAST = (br_ss - BREAST)/TAU_BR;
// perimenstrual prostaglandin window (cycle day ~27 through day ~3)
double pgw = 0.0;
if (cday >= 26.5)     pgw = SIGM(cday, 27.0, 0.5);
else if (cday <= 3.5) pgw = 1.0 - SIGM(cday, 3.0, 0.6);
dxdt_PGE = (KPG*pgw*(1.0 - NSAID)*((OOPH > 0.5) ? 0.0 : 1.0) - PGE)/TAU_PG;

// ═══════════════════════ DRSP symptom domains ════════════════════════════
double ca    = 1.0 - ((CA_SUPP > 0.0) ? 0.25 : 0.0);
double bloat = POSPART((ECFV - 1.0)/0.030);
double cramp = POSPART(PGE);
sleep_q = 1.0 - CLAMP01(0.35*eff + 0.030*HF);
double d_amy  = POSPART(AMY - 1.0);
double d_pfc  = POSPART(1.0 - PFC);
double d_rew  = POSPART(1.0 - REW);
double sht_up = POSPART(SHT - 1.0);
double sht_dn = POSPART(1.0 - SHT);

double f_irr = 0.62*d_amy + 0.22*eff - 0.34*sht_up - 0.18*(PFC - 1.0);
double f_anx = 0.66*d_amy + 0.18*eff - 0.28*sht_up;
double f_lab = 0.55*d_amy + 0.30*d_pfc + 0.15*WE2 - 0.22*sht_up;
double f_dep = 0.42*eff + 0.38*d_rew + 0.18*WE2 - 0.30*BDNF - 0.15*sht_up;
double f_anh = 0.28*eff + 0.62*d_rew - 0.32*BDNF;
double f_cog = 0.52*d_pfc + 0.26*eff + 0.14*(1.0 - sleep_q);
double f_fat = 0.34*eff + 0.32*(1.0 - sleep_q) + 0.22*d_rew;
double f_app = (0.58*eff + 0.30*sht_dn - 0.20*sht_up)*ca;
double f_slp = (1.0 - sleep_q)*1.15;
double f_ovr = 0.58*eff + 0.30*d_pfc - 0.20*sht_up;
double f_phy = (0.34*bloat + 0.34*BREAST + 0.32*cramp)*ca;

dxdt_S_IRR = (1.0 + 5.0*CLAMP01(f_irr + BASE_SYM) - S_IRR)/TAU_S;
dxdt_S_ANX = (1.0 + 5.0*CLAMP01(f_anx + BASE_SYM) - S_ANX)/TAU_S;
dxdt_S_LAB = (1.0 + 5.0*CLAMP01(f_lab + BASE_SYM) - S_LAB)/TAU_S;
dxdt_S_DEP = (1.0 + 5.0*CLAMP01(f_dep + BASE_SYM) - S_DEP)/TAU_S;
dxdt_S_ANH = (1.0 + 5.0*CLAMP01(f_anh + BASE_SYM) - S_ANH)/TAU_S;
dxdt_S_COG = (1.0 + 5.0*CLAMP01(f_cog + BASE_SYM) - S_COG)/TAU_S;
dxdt_S_FAT = (1.0 + 5.0*CLAMP01(f_fat + BASE_SYM) - S_FAT)/TAU_S;
dxdt_S_APP = (1.0 + 5.0*CLAMP01(f_app + BASE_SYM) - S_APP)/TAU_S;
dxdt_S_SLP = (1.0 + 5.0*CLAMP01(f_slp + BASE_SYM) - S_SLP)/TAU_S;
dxdt_S_OVR = (1.0 + 5.0*CLAMP01(f_ovr + BASE_SYM) - S_OVR)/TAU_S;
dxdt_S_PHY = (1.0 + 5.0*CLAMP01(f_phy + BASE_SYM) - S_PHY)/TAU_S;

// ═══════════════════════════ organ / safety ══════════════════════════════
double hf_ss = HF_MAX/(1.0 + (E2_TOT/E50_HF)*(E2_TOT/E50_HF))*(1.0 - HF_SSRI*occ);
dxdt_HF = (hf_ss - HF)/TAU_HF;
hypo = 1.0/(1.0 + (E2_TOT/E50_BMD)*(E2_TOT/E50_BMD));
dxdt_BMD = -KBMD_LOSS*POSPART(hypo - HYPO_REF)
         + KBMD_REC*POSPART(-BMD)*POSPART(HYPO_REF - hypo)/HYPO_REF;
dxdt_ENDO = ((DRSP_C/(DRSP_C + 5.0)) - ENDO)/TAU_ENDO;

[TABLE]
capture cycle_day        = cday;
capture DRSP_11          = S_IRR + S_DEP + S_ANX + S_LAB + S_ANH + S_COG
                         + S_FAT + S_APP + S_SLP + S_OVR + S_PHY;
capture DRSP_CORE        = S_IRR + S_DEP + S_ANX + S_LAB + S_ANH;
capture E2_total         = E2_TOT;
capture NS_load          = load;
capture NS_drive         = ns_drive;
capture NS_sensitivity   = sens;
capture Affective_effect = eff;
capture GnRH_axis_drive  = gnrh_eff;
capture SERT_occupancy   = occ;
capture SRD5A1_activity  = a5ar;
capture Change_signal    = chg;
capture E2_withdrawal    = WE2;
capture Progestogen_tone = PROG;
capture Hypoestrogenism  = hypo;
capture Sleep_quality    = sleep_q;

[CAPTURE]
cycle_day DRSP_11 DRSP_CORE E2_total NS_load NS_drive NS_sensitivity
Affective_effect GnRH_axis_drive SERT_occupancy SRD5A1_activity
Change_signal E2_withdrawal Progestogen_tone Hypoestrogenism Sleep_quality


##  ============================================================================
##  R-side scenario helpers (read by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(ggplot2)
##  mod <- mread("pmdd_mrgsolve_model.R")
##  out <- PMDD_simulate_scenarios(mod)
##  PMDD_endpoint_table(out)
##  PMDD_plot_cycle(out, c("pmdd_untreated", "control", "sert50_luteal"))
##
##  TCYC <- 28; a cycle-day-windowed dosing helper keeps the luteal-only and
##  24/4 regimens honest.
##
##  PMDD_cyclic_times <- function(tend, every = 1, lo = 1, hi = 29, tcyc = 28) {
##    t <- seq(0, tend - every, by = every)
##    cd <- (t %% tcyc) + 1
##    t[cd >= lo & cd < hi]
##  }
##
##  PMDD_dose <- function(cmt, amt, times) {
##    if (!length(times)) return(NULL)
##    data.frame(ID = 1, time = times, cmt = cmt, amt = amt, evid = 1)
##  }
##
##  PMDD_SCENARIOS <- list(
##
##    ## ---- reference and control ------------------------------------------
##    pmdd_untreated = list(param = list(), dose = NULL, tend = 168),
##    control        = list(param = list(GAMMA_D = -0.05, GAMMA_A4 = 0.25,
##                                      KP = 13), dose = NULL, tend = 168),
##
##    ## ---- SSRIs ----------------------------------------------------------
##    sert50_luteal  = list(param = list(),
##                          dose = quote(PMDD_dose("SERT_D", 50,
##                                   PMDD_cyclic_times(168, 1, 15, 29))),
##                          tend = 168),
##    sert50_cont    = list(param = list(),
##                          dose = quote(PMDD_dose("SERT_D", 50, seq(0, 167))),
##                          tend = 168),
##    sert100_cont   = list(param = list(),
##                          dose = quote(PMDD_dose("SERT_D", 100, seq(0, 167))),
##                          tend = 168),
##    sert50_onset   = list(param = list(),
##                          dose = quote(PMDD_dose("SERT_D", 50,
##                                   PMDD_cyclic_times(168, 1, 22, 29))),
##                          tend = 168),
##    flx20_cont     = list(param = list(),
##                          dose = quote(PMDD_dose("FLX_C", 20*1000*0.9/2500,
##                                                 seq(0, 167))),
##                          tend = 168),
##
##    ## ---- ovulation suppression ------------------------------------------
##    drsp_24_4      = list(param = list(),
##                          dose = quote(PMDD_dose("DRSP_D", 3,
##                                   PMDD_cyclic_times(168, 1, 1, 25))),
##                          tend = 168),
##    drsp_21_7      = list(param = list(),
##                          dose = quote(PMDD_dose("DRSP_D", 3,
##                                   PMDD_cyclic_times(168, 1, 1, 22))),
##                          tend = 168),
##    drsp_cont      = list(param = list(),
##                          dose = quote(PMDD_dose("DRSP_D", 3, seq(0, 167))),
##                          tend = 168),
##
##    ## ---- GnRH agonist and the add-back experiment -----------------------
##    leuprolide     = list(param = list(),
##                          dose = quote(PMDD_dose("LEUP_D", 3.75,
##                                                 seq(0, 167, by = 28))),
##                          tend = 168),
##    addback        = list(param = list(ADDBACK_E2 = 210, ADDBACK_P4 = 20,
##                                       ADDBACK_T0 = 112),
##                          dose = quote(PMDD_dose("LEUP_D", 3.75,
##                                                 seq(0, 279, by = 28))),
##                          tend = 280),
##    addback_ctrl   = list(param = list(GAMMA_D = -0.05, GAMMA_A4 = 0.25,
##                                       KP = 13, ADDBACK_E2 = 210,
##                                       ADDBACK_P4 = 20, ADDBACK_T0 = 112),
##                          dose = quote(PMDD_dose("LEUP_D", 3.75,
##                                                 seq(0, 279, by = 28))),
##                          tend = 280),
##
##    ## ---- neurosteroid-directed ------------------------------------------
##    sepranolone    = list(param = list(),
##                          dose = quote(PMDD_dose("SEPRA_D", 10,
##                                   PMDD_cyclic_times(168, 2, 15, 29))),
##                          tend = 168),
##    duta_2p5       = list(param = list(),
##                          dose = quote(PMDD_dose("DUTA_D", 2.5, seq(0, 279))),
##                          tend = 280),
##    duta_0p5       = list(param = list(),
##                          dose = quote(PMDD_dose("DUTA_D", 0.5, seq(0, 279))),
##                          tend = 280),
##    allo_high      = list(param = list(),
##                          dose = quote(PMDD_dose("ZUR", 20,
##                                   PMDD_cyclic_times(168, 1, 22, 29))),
##                          tend = 168),
##    allo_low       = list(param = list(),
##                          dose = quote(PMDD_dose("ZUR", 3,
##                                   PMDD_cyclic_times(168, 1, 22, 29))),
##                          tend = 168),
##    alprazolam     = list(param = list(),
##                          dose = quote(PMDD_dose("ALPZ_D", 0.25,
##                                   PMDD_cyclic_times(168, 1/3, 15, 29))),
##                          tend = 168),
##    ulipristal     = list(param = list(),
##                          dose = quote(PMDD_dose("UPA_C", 5*1000*0.8/500,
##                                                 seq(0, 167))),
##                          tend = 168),
##
##    ## ---- adjuncts, combination, surgery ---------------------------------
##    calcium        = list(param = list(CA_SUPP = 0.18), dose = NULL, tend = 168),
##    spironolactone = list(param = list(SPIRO = 1.6),   dose = NULL, tend = 168),
##    cbt            = list(param = list(CBT = 0.18),    dose = NULL, tend = 168),
##    nsaid          = list(param = list(NSAID = 0.7),   dose = NULL, tend = 168),
##    sert_plus_drsp = list(param = list(),
##                          dose = quote(rbind(
##                            PMDD_dose("SERT_D", 50, PMDD_cyclic_times(168, 1, 15, 29)),
##                            PMDD_dose("DRSP_D", 3,  PMDD_cyclic_times(168, 1, 1, 25)))),
##                          tend = 168),
##    oophorectomy   = list(param = list(OOPH = 1, ADDBACK_E2 = 170),
##                          dose = NULL, tend = 168),
##
##    ## ---- FALSIFICATION runs: level detector, no plasticity --------------
##    fals_untreated = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = NULL, tend = 168),
##    fals_sert      = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = quote(PMDD_dose("SERT_D", 50,
##                                   PMDD_cyclic_times(168, 1, 15, 29))),
##                          tend = 168),
##    fals_duta_2p5  = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = quote(PMDD_dose("DUTA_D", 2.5, seq(0, 279))),
##                          tend = 280),
##    fals_duta_0p5  = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = quote(PMDD_dose("DUTA_D", 0.5, seq(0, 279))),
##                          tend = 280),
##    fals_allo_high = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = quote(PMDD_dose("ZUR", 20,
##                                   PMDD_cyclic_times(168, 1, 22, 29))),
##                          tend = 168),
##    fals_allo_low  = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0),
##                          dose = quote(PMDD_dose("ZUR", 3,
##                                   PMDD_cyclic_times(168, 1, 22, 29))),
##                          tend = 168),
##    fals_addback   = list(param = list(MONOTONE = 1, RATE_OFF = 1,
##                                       GAMMA_D = 0, GAMMA_A4 = 0,
##                                       ADDBACK_E2 = 210, ADDBACK_P4 = 20,
##                                       ADDBACK_T0 = 112),
##                          dose = quote(PMDD_dose("LEUP_D", 3.75,
##                                                 seq(0, 279, by = 28))),
##                          tend = 280)
##  )
##
##  PMDD_simulate_scenarios <- function(mod, delta = 0.25) {
##    out <- lapply(names(PMDD_SCENARIOS), function(nm) {
##      sc <- PMDD_SCENARIOS[[nm]]
##      dose <- if (is.null(sc$dose)) NULL else eval(sc$dose)
##      m <- mod
##      if (length(sc$param)) m <- param(m, sc$param)
##      sim <- if (is.null(dose)) {
##        mrgsim(m, end = sc$tend, delta = delta)
##      } else {
##        mrgsim(m, data = dose, end = sc$tend, delta = delta)
##      }
##      as.data.frame(sim) %>% dplyr::mutate(scenario = nm)
##    })
##    dplyr::bind_rows(out)
##  }
##
##  ## Trial-style endpoint: % reduction of the luteal DRSP-11 burden above the
##  ## floor of the scale (11 = no symptoms), evaluated on the 5th cycle.
##  PMDD_endpoint_table <- function(out, cyc = 5, tcyc = 28) {
##    lo <- (cyc - 1)*tcyc; hi <- cyc*tcyc
##    d <- out %>% dplyr::filter(time >= lo, time < hi) %>%
##      dplyr::mutate(cd = cycle_day)
##    fol <- d %>% dplyr::filter(cd >= 5,  cd < 11) %>%
##      dplyr::group_by(scenario) %>%
##      dplyr::summarise(fol = mean(DRSP_11), core_fol = mean(DRSP_CORE),
##                       .groups = "drop")
##    lut <- d %>% dplyr::filter(cd >= 21, cd < 29) %>%
##      dplyr::group_by(scenario) %>%
##      dplyr::summarise(lut = mean(DRSP_11), core_lut = mean(DRSP_CORE),
##                       peak = max(DRSP_11), .groups = "drop")
##    ref <- lut$lut[lut$scenario == "pmdd_untreated"]
##    dplyr::left_join(fol, lut, by = "scenario") %>%
##      dplyr::mutate(
##        core_increase_pct = 100*(core_lut - core_fol)/core_fol,
##        luteal_reduction_pct = 100*(1 - (lut - 11)/(ref - 11)))
##  }
##
##  PMDD_plot_cycle <- function(out, which, cyc = 5, tcyc = 28) {
##    lo <- (cyc - 1)*tcyc; hi <- cyc*tcyc
##    d <- out %>% dplyr::filter(scenario %in% which, time >= lo, time < hi)
##    ggplot2::ggplot(d, ggplot2::aes(cycle_day, DRSP_11, colour = scenario)) +
##      ggplot2::geom_line(linewidth = 0.9) +
##      ggplot2::geom_vline(xintercept = 22, linetype = 3) +
##      ggplot2::labs(x = "cycle day", y = "DRSP-11 (11-66)",
##                    title = "PMDD: symptom peak lags the allopregnanolone peak",
##                    subtitle = "dotted line = brain allopregnanolone peak (day 22)") +
##      ggplot2::theme_minimal()
##  }
##
##  ##  The five structural predictions, as a one-line check each:
##  ##    [P1] symptom peak on cycle day ~28, ALLO peak day ~22 (lag +5.5 d)
##  ##    [P2] duta_2p5 45.4% vs duta_0p5 10.2% luteal reduction
##  ##    [P3] allo_high +46.2% vs allo_low -5.5% (opposite signs, one drug)
##  ##    [P4] drsp_24_4 59.2% vs drsp_21_7 50.8% (8.4-point gap)
##  ##    [P5] add-back flare +10.7 DRSP-11 points in the first 10 days, +0.5 by
##  ##         day 112 of identical continued exposure
##  ##  Re-run the falsification scenarios and every one of them collapses; see
##  ##  pmdd_python_twin.py for the assertions and the exact numbers.
