## ============================================================================
##  Hypophosphatasia (HPP) — QSP / PK-PD Model
## ============================================================================
##  Disease  : Hypophosphatasia — loss-of-function variants in ALPL (1p36.12)
##             reduce tissue-nonspecific alkaline phosphatase (TNSALP), a
##             GPI-anchored ECTOenzyme on the matrix-vesicle membrane of
##             osteoblasts and hypertrophic chondrocytes. Its natural substrates
##             are inorganic PYROPHOSPHATE (PPi), pyridoxal-5'-phosphate (PLP)
##             and phosphoethanolamine (PEA). PPi is a potent competitive
##             inhibitor of hydroxyapatite crystal growth, so losing the enzyme
##             that clears PPi arrests mineralization: rickets / osteomalacia,
##             rachitic chest and respiratory failure (perinatal-infantile),
##             premature deciduous tooth loss (odonto-HPP), fractures and
##             pseudofractures (adult), craniosynostosis, and pyridoxine-
##             responsive seizures from failure to dephosphorylate PLP at the
##             blood-brain barrier.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.0)
##  Time     : DAYS.  Doses in mg (asfotase alfa, subcutaneous).
##
##  Scope    : 32 differential states + 4 quasi-steady-state species —
##             PK   (4): asfotase alfa SC depot -> plasma -> capacity-limited
##                       HYDROXYAPATITE-BOUND pool (the deca-aspartate motif) +
##                       anti-drug antibody titre feeding back on clearance.
##             PD  (28): osteoblast / osteoclast pools, bone-bound bisphosphonate
##                       (a non-hydrolysable PPi analogue), osteopontin,
##                       CNS pyridoxal cofactor, serum Ca / Pi / PTH / 1,25D,
##                       nephrocalcinosis, osteoid volume, mineralised matrix,
##                       growth-plate integrity + IRREVERSIBLE growth-plate
##                       damage, RSS, height-Z, thoracic mineralization,
##                       respiratory index, muscle function, pain, dental
##                       attachment, craniosynostosis, seizure burden, ectopic
##                       calcification, fracture burden, survival, cumulative
##                       hazard, cumulative PPi exposure.
##             QSS  (4): perivesicular PPi, plasma PPi, plasma PLP, plasma PEA —
##                       these equilibrate in minutes to hours and are solved in
##                       CLOSED FORM (the coupled PPi pair reduces to a single
##                       quadratic), which removes all stiffness.
##
##  ==========================================================================
##  THE STRUCTURAL POINTS THIS MODEL IS BUILT TO EXPOSE
##  ==========================================================================
##  T1  THRESHOLD, NOT GRADIENT.  Perivesicular PPi is cleared BY TNSALP, so
##      PPi ~ 1/E; mineral apposition ~ 1/(1 + PPi/Ki). Composing the two gives
##      a HYPERBOLA in local enzyme activity E. The entire severity spectrum
##      (perinatal lethal -> infantile -> childhood -> adult -> odonto ->
##      asymptomatic carrier) is ONE curve read at different E, and its steep
##      part lies below ~0.2 of normal activity. Computed: 11.7x more enzyme
##      (3% -> 35% of normal) buys only 3.4x mineral apposition.
##
##  T2  THE PD MARKERS ARE MEASURED IN THE WRONG COMPARTMENT.  Plasma PLP and
##      plasma PPi are hydrolysed by enzyme in PLASMA; mineralization is set by
##      enzyme bound to HYDROXYAPATITE. Computed: in the infantile phenotype the
##      measurable plasma PPi elevation (2.6x) understates the causal
##      perivesicular elevation (13.4x) 5.2-fold, and plasma PLP reaches 99% of
##      its maximal suppression at ~0.6 mg/kg/week — about a tenth of the label
##      dose and 6% of the dose that maximises mineralization capacity.
##
##  T3  TWO CLOCKS.  Osteomalacia reverses in weeks-months; growth-plate
##      architecture and craniosynostosis accrue IRREVERSIBLY while untreated.
##      Computed: starting therapy at day 365 instead of day 14 leaves the same
##      osteoid volume at 3 years but 4.9x the irreversible growth-plate damage
##      and a height Z-score 1.27 SD lower.
##
##  T4  AN ANTIRESORPTIVE IS A MECHANISTIC POISON HERE.  Bisphosphonates are
##      non-hydrolysable PPi analogues with a bone half-life of years; they
##      enter the very Ki term the disease is already saturating. Computed:
##      3 years of exposure in adult HPP lowers relative mineral apposition 31%
##      and raises fracture burden 8.2x DESPITE suppressing osteoclasts.
##
##  T5  FRACTIONATION IS NEARLY IRRELEVANT; TOTAL WEEKLY DOSE IS NOT.  The
##      HA-bound pool has a 3.5-day half-life and buffers the dosing interval.
##      Computed: 2 mg/kg 3x/week and 1 mg/kg 6x/week differ by 0.2% in
##      relative mineral apposition at one year.
##
##  Every number quoted above is produced by hpp_reference_model.py, a
##  stdlib-only Python implementation whose parameter block matches the [PARAM]
##  block below 1:1. See hpp_model_report.txt for the full computed output and
##  README.md section 8 for limitations.
##
##  Disclaimer: Research / education / hypothesis generation only. NOT validated
##              for clinical decision-making or regulatory use.
## ============================================================================

library(mrgsolve)

HPP_code <- '
[PROB]
QSP model of hypophosphatasia linking ALPL genotype (residual TNSALP activity)
to the perivesicular pyrophosphate economy, competitive inhibition of
hydroxyapatite growth, growth-plate and thoracic mineralization, systemic
mineral homeostasis, the vitamin-B6 / CNS axis, and clinical endpoints (RSS,
height Z-score, respiratory index, 6MWT-like muscle function, dental
attachment, survival) — with mechanistic PK/PD for bone-targeted asfotase alfa
(sTNSALP-Fc-D10), pyridoxine, teriparatide, and an explicit bisphosphonate
HARM arm.

[PLUGIN] Rcpp

[PARAM] @annotated
//=========================================================================
// SUBJECT / GENOTYPE
//   FRACENZ is the residual LOCAL TNSALP activity as a fraction of normal.
//   It is THE genotype variable: 0.01 perinatal, 0.03 infantile,
//   0.12 childhood, 0.35 adult/odonto, 0.50 heterozygous carrier.
//=========================================================================
WT       : 5.0     : kg, body weight (fixed per scenario; see limitations)
FRACENZ  : 0.03    : -, residual LOCAL TNSALP activity (1 = healthy)
FISO     : 0.15    : -, fraction of serum ALP from non-TNSALP isoforms
ALPN     : 300.0   : U/L, age-normal total serum ALP (paediatric)
AGE0     : 14.0    : d, age at simulation start
GPCLOSE  : 5840.0  : d, physis closure (~16 y)

//--- asfotase alfa PK -----------------------------------------------------
FBIO     : 0.458   : -, SC bioavailability (label)
KA       : 1.2     : 1/d, absorption rate (tmax ~1.5 d)
VCKG     : 0.08    : L/kg, central volume
CLKG     : 0.0243  : L/kg/d, clearance (terminal t1/2 2.28 d)
KON      : 0.80    : 1/d, plasma -> hydroxyapatite association
KOFF     : 0.15    : 1/d, hydroxyapatite dissociation
KDEGB    : 0.05    : 1/d, degradation of HA-bound enzyme (t1/2 ~14 d)
BMAXKG   : 12.0    : mg/kg, HA binding capacity at BMIN = 1
SPACT    : 700.0   : U/mg, specific activity (serum ALP conversion)
KBONE    : 8.0     : -, normalised LOCAL activity per unit HA occupancy
GAMADA   : 3.0     : -, ADA-driven clearance multiplier
KADAON   : 0.010   : 1/d, ADA induction rate
KADA     : 3.0     : mg/L, ADA induction EC50 on plasma drug
KADAOFF  : 0.004   : 1/d, ADA decay
ADAMAX   : 0.20    : -, subject ADA ceiling (1.0 = high-titre subject)

//--- pyrophosphate economy ------------------------------------------------
JPPI     : 509.4   : uM/d, perivesicular PPi production (ENPP1 + ANKH)
KCATP    : 180.0   : 1/d, low-concentration hydrolysis slope at ELOC = 1
KMPPI    : 50.0    : uM, Km(TNSALP, PPi)
KOUT     : 12.0    : 1/d, perivesicular <-> plasma exchange
FVOL     : 0.02    : -, perivesicular / plasma volume ratio
JPSYS    : 9.0     : uM/d, systemic (non-skeletal) PPi production
CLPPI    : 2.0     : 1/d, enzyme-independent plasma PPi clearance
KCATPP   : 1.0     : 1/d, plasma PPi hydrolysis slope at EPL = 1
PPI0     : 3.0     : uM, healthy perivesicular / plasma PPi
KIPPI    : 4.0     : uM, Ki of PPi for hydroxyapatite growth
KIBP     : 8.0     : uM-eq, Ki of bisphosphonate (non-hydrolysable)
KIOPN    : 40.0    : -, Ki-equivalent of phospho-osteopontin
KOPNON   : 0.6     : -, PPi -> osteopontin co-induction gain
TAUOPN   : 20.0    : d, osteopontin turnover

//--- vitamin B6 / CNS -----------------------------------------------------
JPLP     : 402.75  : nM/d, hepatic PLP appearance
KCATPL   : 12.0    : 1/d, plasma PLP hydrolysis slope at EPL = 1
CLPL     : 0.15    : 1/d, enzyme-independent PLP clearance
PLPMIN   : 12.0    : nM, protein-bound / inaccessible PLP floor
PLP0     : 45.0    : nM, healthy plasma PLP
KINBR    : 1.0     : 1/d, CNS pyridoxal influx capacity
KMBR     : 45.0    : nM, half-saturation of BBB PLP dephosphorylation
KOUTBR   : 0.5     : 1/d, CNS cofactor turnover
KPN      : 0.004   : 1/(mg/d), pyridoxine bypass gain
PNDOSE   : 0.0     : mg/d, pyridoxine dose
EC50S    : 0.25    : -, CNS cofactor at half-maximal seizure risk
HILLS    : 3.0     : -, Hill coefficient for seizure risk
TAUSEIZ  : 3.0     : d, seizure-burden time constant

//--- phosphoethanolamine --------------------------------------------------
JPEA     : 12.0    : uM/d, PEA appearance
KCATPEA  : 3.0     : 1/d, PEA hydrolysis slope at EPL = 1
CLPEA    : 0.5     : 1/d, enzyme-independent PEA clearance

//--- mineral / endocrine --------------------------------------------------
CA0      : 2.40    : mmol/L, healthy serum Ca
PI0      : 1.80    : mmol/L, healthy serum Pi (infant reference)
VCA      : 0.30    : L/kg, ECF volume for Ca
VPI      : 0.30    : L/kg, ECF volume for Pi
CAIN     : 1.40    : mmol/kg/d, absorbed Ca at reference intake
QDEP     : 0.75    : mmol/kg/d, skeletal Ca deposition at MAR = 1
QRES     : 0.55    : mmol/kg/d, osteoclastic Ca release at OC = 1
QURN     : 1.296   : mmol/kg/d, renal Ca excretion capacity (Vmax)
KURN     : 0.02    : mmol/L, Michaelis constant above threshold
CATHR    : 2.15    : mmol/L, renal Ca excretion threshold
PIIN     : 1.00    : mmol/kg/d, absorbed Pi
QPDEP    : 0.45    : mmol/kg/d, skeletal Pi deposition at MAR = 1
QPURN    : 0.55    : mmol/kg/d, renal Pi excretion at PIS = PI0
PTH0     : 3.5     : pmol/L, healthy PTH
SPTH     : 6.0     : 1/(mmol/L), steepness of Ca -> PTH suppression
TAUPTH   : 0.20    : d, PTH time constant
VITD0    : 100.0   : pmol/L, healthy 1,25(OH)2D
KPD      : 0.5     : -, PTH -> 1,25D gain
TAUD     : 3.0     : d, 1,25D time constant
KNEPH    : 0.0025  : 1/d, nephrocalcinosis accrual per unit excess CaU
CAUTHR   : 1.30    : mmol/kg/d, urinary Ca above which deposits accrue
KNEPHD   : 0.0002  : 1/d, nephrocalcinosis resolution

//--- mineralization front / bone ------------------------------------------
KMIN     : 1.0     : -, mineral apposition scale (MAR = 1 healthy)
NSSAT    : 1.5     : -, supersaturation exponent
OST0     : 0.02    : -, healthy osteoid volume fraction
KOSTF    : 0.02    : 1/d, osteoid production at OB = 1
KCONS    : 1.0     : 1/d, osteoid consumption per unit MAR
POWOST   : 0.7     : -, osteoid-surface feedback exponent
KBF      : 0.010   : 1/d, mineral accrual
KBR      : 0.010   : 1/d, mineral resorption at OC = 1
TAUOB    : 30.0    : d, osteoblast pool time constant
TAUOC    : 30.0    : d, osteoclast pool time constant
ETPTD    : 0.0     : -, teriparatide osteoblast expansion (0.8 = on)
EBPOC    : 0.0     : -, bisphosphonate osteoclast suppression
KBPIN    : 0.0     : uM-eq/d, bisphosphonate skeletal accrual
KBPOUT   : 0.00019 : 1/d, bisphosphonate bone half-life ~10 y

//--- growth plate ---------------------------------------------------------
KGPR     : 0.020   : 1/d, growth-plate repair
KGPD     : 0.060   : 1/d, growth-plate degradation
KGP50    : 0.15    : -, Mrel at half-maximal repair/damage partition
KIRR     : 0.0006  : 1/d, irreversible architectural loss (baseline)
KIRRINF  : 2.0     : -, infancy multiplier amplitude
TIRR     : 365.0   : d, infancy multiplier time constant
RSSMAX   : 8.0     : -, RSS at complete growth-plate failure
KRSSOST  : 8.0     : -, osteomalacia contribution to RSS
KRSSIRR  : 4.0     : -, irreversible (non-healing) contribution to RSS
TAURSS   : 45.0    : d, radiographic lag
KZ       : 0.00329 : 1/d, height-Z change per unit growth deficit (1.2/365)
KCATCH   : 0.25    : -, maximal catch-up growth allowance

//--- thorax / respiration / survival --------------------------------------
KRIBR    : 0.050   : 1/d, thoracic mineralization repair
KRIBD    : 0.100   : 1/d, thoracic mineralization loss
KRIB50   : 0.15    : -, Mrel at half-maximal thoracic partition
WRIB     : 0.70    : -, weight of rib mineralization in RESP
WMUSR    : 0.25    : -, weight of muscle function in RESP
HYPOPL   : 0.0     : -, fixed pulmonary hypoplasia decrement (perinatal)
TAURESP  : 7.0     : d, respiratory index time constant
VENTTHR  : 0.50    : -, RESP below which invasive ventilation is assumed
HAZ0     : 0.0000640 : 1/d, respiratory hazard scale
KHZ      : 6.0     : -, hazard steepness in (1 - RESP)
HAZS     : 0.00015 : 1/d, seizure-attributable hazard
HTAU     : 548.0   : d, age decay of the infantile hazard window

//--- muscle / pain / dental / cranium / ectopic / fracture -----------------
MUSMAX   : 1.00    : -, maximal muscle function index
WPAINM   : 0.030   : -, pain weight in muscle function
WPLB     : 0.20    : -, CNS-cofactor weight in muscle function
WOSTM    : 4.00    : -, osteoid weight in muscle function
TAUMUS   : 60.0    : d, muscle time constant
KPO      : 40.0    : -, osteoid -> pain gain
KPF      : 0.8     : -, fracture -> pain gain
KPCPPD   : 0.25    : -, PPi-crystal (CPPD) -> pain gain
KPM      : 4.0     : -, mineralization-deficit -> pain gain
TAUPAIN  : 30.0    : d, pain time constant
KDR      : 0.010   : 1/d, cementum / attachment repair
KDD      : 0.100   : 1/d, cementum / attachment loss
KD50     : 0.50    : -, Mrel at half-maximal dental partition
KCS      : 0.0040  : 1/d, craniosynostosis progression
TCS      : 730.0   : d, infant window for craniosynostosis
KECT     : 0.0020  : 1/d, ectopic calcification accrual
KECTD    : 0.0005  : 1/d, ectopic calcification resolution
KFXO     : 0.0004  : 1/d, fracture accrual per unit excess osteoid
KFXH     : 0.0060  : 1/d, fracture healing at Mrel = 1
LOAD     : 1.0     : -, mechanical loading multiplier

[INIT] @annotated
// Default initial conditions are the HEALTHY reference state. The genotype
// steady state is reached by burn-in (HPP_settle() below) and injected with
// init(), never hand-set here — so every baseline biomarker value is earned by
// the model. NOTE: initial conditions are declared here rather than assigned
// in a MAIN block, precisely so that init() is not overwritten at each
// re-initialisation.
//--- PK (4) ---------------------------------------------------------------
ASC    : 0     : mg, asfotase alfa subcutaneous depot
AC     : 0     : mg, asfotase alfa in plasma
EB     : 0     : mg, asfotase alfa BOUND TO HYDROXYAPATITE (effect compartment)
ADA    : 0     : -, anti-drug antibody titre
//--- cells & inhibitor pools (4) -----------------------------------------
OB     : 1.0   : -, osteoblast pool (1 = healthy)
OC     : 1.0   : -, osteoclast pool (1 = healthy)
BPB    : 0     : uM-eq, bisphosphonate bound in bone (non-hydrolysable)
OPN    : 1.0   : -, phospho-osteopontin inhibitor pool (1 = healthy)
//--- CNS vitamin B6 (1) --------------------------------------------------
PLBR   : 1.0   : -, CNS pyridoxal / PLP cofactor pool (1 = healthy)
//--- mineral homeostasis (5) ---------------------------------------------
CAS    : 2.40  : mmol/L, serum calcium
PIS    : 1.80  : mmol/L, serum phosphate
PTHS   : 3.5   : pmol/L, parathyroid hormone
VITD   : 100.0 : pmol/L, 1,25(OH)2D
NEPH   : 0     : -, nephrocalcinosis burden (0-1)
//--- bone matrix (2) -----------------------------------------------------
OST    : 0.02  : -, unmineralised osteoid volume fraction
BMIN   : 1.0   : -, mineralised matrix (1 = age-normal)
//--- growth plate & stature (4) ------------------------------------------
GP     : 0.69  : -, growth-plate integrity (raw; see GPREL)
GPD    : 0     : -, IRREVERSIBLE growth-plate architectural damage (0-1)
RSS    : 0     : -, radiographic rickets severity score (0-10)
HTZ    : 0     : -, change in height / length Z-score since t = 0
//--- thorax, respiration, survival (3) ------------------------------------
RIB    : 0.77  : -, thoracic mineralization (raw; see RIBREL)
RESP   : 1.0   : -, respiratory function index (0-1)
SURV   : 1.0   : -, survival probability
//--- symptoms & other organs (7) -----------------------------------------
MUS    : 1.0   : -, muscle function index (6MWT-like, fraction of predicted)
PAIN   : 0     : -, pain score (0-10)
DENT   : 0.167 : -, dental / cementum attachment (raw; see DENTREL)
CRAN   : 0     : -, craniosynostosis index (0-1)
SEIZ   : 0     : -, seizure burden index (0-1)
ECT    : 0     : -, ectopic calcification burden
FX     : 0     : -, fracture / pseudofracture burden
//--- bookkeeping (2) -----------------------------------------------------
CUMHAZ : 0     : -, cumulative mortality hazard
AUCPPI : 0     : uM.d, cumulative perivesicular PPi exposure

[ODE]
//=========================================================================
// ALGEBRAIC LAYER
// NOTE: the block between the two markers below is duplicated verbatim in
// [TABLE] so that captured outputs are computed at exactly the output time.
// If you edit one, edit BOTH — and keep them in step with the algebra()
// function of hpp_reference_model.py.
//--- BEGIN SHARED ALGEBRA ------------------------------------------------
double VCL  = VCKG * WT;
double BMNZ = BMIN > 0.15 ? BMIN : 0.15;
double BMAX = BMAXKG * WT * BMNZ;
double Cp   = AC / VCL;
double OCC  = EB / BMAX;

// LOCAL enzyme activity (normalised, 1 = healthy). The endogenous term scales
// with the osteoblast pool: this is the channel teriparatide acts through.
double ELOC  = FRACENZ * OB + KBONE * OCC;
// PLASMA activity, normalised, including the non-TNSALP isoform floor.
double ALPUL = ALPN * (FRACENZ * (1.0 - FISO) + FISO) + SPACT * Cp;
double EPL   = ALPUL / ALPN;

// --- quasi-steady state of the four fast species ------------------------
// The coupled perivesicular/plasma PPi pair reduces to one quadratic:
//   alpha*P^2 + [Vm*ELOC + alpha*Km - S]*P - S*Km = 0
double c1a   = FVOL * KOUT;
double c2a   = KCATPP * EPL + CLPPI;
double alph  = KOUT * c2a / (c1a + c2a);
double beta  = KOUT * JPSYS / (c1a + c2a);
double Vm    = KCATP * KMPPI;
double Ssum  = JPPI + beta;
double bq    = Vm * ELOC + alph * KMPPI - Ssum;
double disc  = bq * bq + 4.0 * alph * Ssum * KMPPI;
if (disc < 0.0) disc = 0.0;
double PPIL  = (-bq + sqrt(disc)) / (2.0 * alph);
double PPIP  = (c1a * PPIL + JPSYS) / (c1a + c2a);
double PLPP  = (JPLP + KCATPL * EPL * PLPMIN) / (KCATPL * EPL + CLPL);
double PEAP  = JPEA / (KCATPEA * EPL + CLPEA);

// --- inhibition and mineral apposition ---------------------------------
double OPNX  = OPN > 1.0 ? (OPN - 1.0) : 0.0;
double MINH  = 1.0 / (1.0 + PPIL / KIPPI + BPB / KIBP + OPNX * 40.0 / KIOPN);
double MINH0 = 1.0 / (1.0 + PPI0 / KIPPI);
double SSATN = pow((CAS * PIS) / (CA0 * PI0), NSSAT);
double MRELN = MINH / MINH0;
double MAR   = KMIN * OB * MRELN * SSATN;

// --- mineral homeostasis fluxes (mmol/kg/d) ----------------------------
double PTHR = PTHS / PTH0;
double DR   = VITD / VITD0;
double JIN  = CAIN * (0.5 + 0.5 * DR);
double JDEP = QDEP * MAR;
double JRES = QRES * OC * (0.6 + 0.4 * PTHR);
double xca  = CAS - CATHR; if (xca < 0.0) xca = 0.0;
double JURN = QURN * xca / (KURN + xca) / (0.7 + 0.3 * PTHR);
double PISZ = PIS > 0.05 ? PIS : 0.05;
double JPURN = QPURN * pow(PISZ / PI0, 3.0) * (0.75 + 0.25 * PTHR);

// --- tissue-integrity partition functions ------------------------------
double mrc = MRELN < 1.0 ? MRELN : 1.0;
double fGPrep = mrc / (mrc + KGP50);
double fGPdmg = KGP50 / (mrc + KGP50);
double fRBrep = mrc / (mrc + KRIB50);
double fRBdmg = KRIB50 / (mrc + KRIB50);
double fDNrep = mrc / (mrc + KD50);
double fDNdmg = KD50 / (mrc + KD50);

// healthy-reference steady states, so the 0-1 integrity states can be read
// relative to normal
double GP0   = KGPR * (1.0/(1.0+KGP50)) /
               (KGPR * (1.0/(1.0+KGP50)) + KGPD * (KGP50/(1.0+KGP50)));
double RIB0  = KRIBR * (1.0/(1.0+KRIB50)) /
               (KRIBR * (1.0/(1.0+KRIB50)) + KRIBD * (KRIB50/(1.0+KRIB50)));
double DEN0  = KDR * (1.0/(1.0+KD50)) /
               (KDR * (1.0/(1.0+KD50)) + KDD * (KD50/(1.0+KD50)));
double GPREL   = GP / GP0;
double RIBREL  = RIB / RIB0;
double DENTREL = DENT / DEN0;

double AGEN   = AGE0 + SOLVERTIME;
double PHYSIS = AGEN < GPCLOSE ? 1.0 : 0.0;
double zdef   = -HTZ / 2.0; if (zdef < 0.0) zdef = 0.0; if (zdef > 1.0) zdef = 1.0;
double hdrv   = MRELN - 1.0; if (hdrv < 0.0) hdrv = 0.0; if (hdrv > 1.0) hdrv = 1.0;
double GROWTHREL = GPREL * (1.0 - GPD) * (1.0 + KCATCH * zdef * hdrv);

// --- relaxation targets -------------------------------------------------
double gpdef = 1.0 - GPREL; if (gpdef < 0.0) gpdef = 0.0;
double ostx  = OST - OST0;  if (ostx  < 0.0) ostx  = 0.0;
double RSSTGT = RSSMAX * gpdef + KRSSOST * ostx + KRSSIRR * GPD;
if (RSSTGT > 10.0) RSSTGT = 10.0;
double ribdef = 1.0 - RIBREL; if (ribdef < 0.0) ribdef = 0.0;
double musdef = 1.0 - MUS;    if (musdef < 0.0) musdef = 0.0;
double RESPTGT = 1.0 - WRIB * ribdef - WMUSR * musdef - HYPOPL;
if (RESPTGT < 0.02) RESPTGT = 0.02;
double plbdef = 1.0 - PLBR; if (plbdef < 0.0) plbdef = 0.0;
double MUSTGT = MUSMAX - WPAINM * PAIN - WPLB * plbdef - WOSTM * ostx;
if (MUSTGT < 0.05) MUSTGT = 0.05;
double cppd = PPIL - 10.0; if (cppd < 0.0) cppd = 0.0;
double PAINTGT = KPO * ostx + KPF * FX + KPCPPD * cppd + KPM * (1.0 - mrc);
if (PAINTGT > 10.0) PAINTGT = 10.0;
double plbz = PLBR > 1e-6 ? PLBR : 1e-6;
double SEIZTGT = 1.0 / (1.0 + pow(plbz / EC50S, HILLS));
double HAZ = exp(-AGEN / HTAU) *
             (HAZ0 * (exp(KHZ * (1.0 - RESP)) - 1.0) + HAZS * SEIZ);
//--- END SHARED ALGEBRA --------------------------------------------------

//=========================================================================
// DIFFERENTIAL EQUATIONS
//=========================================================================
// --- asfotase alfa PK: depot -> plasma -> capacity-limited HA pool -------
double CLt  = CLKG * WT * (1.0 + GAMADA * ADA);
double free = 1.0 - EB / BMAX; if (free < 0.0) free = 0.0;
double bind = KON * AC * free;
dxdt_ASC = -KA * ASC;
dxdt_AC  = FBIO * KA * ASC - CLt / VCL * AC - bind + KOFF * EB;
dxdt_EB  = bind - (KOFF + KDEGB) * EB;
double adaroom = ADAMAX - ADA; if (adaroom < 0.0) adaroom = 0.0;
dxdt_ADA = KADAON * Cp / (KADA + Cp) * adaroom - KADAOFF * ADA;

// --- cell pools ----------------------------------------------------------
dxdt_OB = ((1.0 + ETPTD) - OB) / TAUOB;
dxdt_OC = ((1.0 - EBPOC) - OC) / TAUOC;

// --- inhibitor pools -----------------------------------------------------
dxdt_BPB = KBPIN - KBPOUT * BPB;
double opntgt = 1.0 + KOPNON * (PPIL / PPI0 - 1.0) / (1.0 + PPIL / PPI0 / 4.0);
dxdt_OPN = (opntgt - OPN) / TAUOPN;

// --- CNS vitamin B6 ------------------------------------------------------
// Influx depends on LOCAL (neuronal / BBB) TNSALP only: asfotase alfa is
// bone-targeted and does not cross the blood-brain barrier. This is why
// pyridoxine, not ERT, is the treatment for HPP seizures.
dxdt_PLBR = KINBR * FRACENZ * PLPP / (KMBR + PLPP) + KPN * PNDOSE
            - KOUTBR * PLBR;

// --- mineral homeostasis -------------------------------------------------
dxdt_CAS = (JIN - JDEP + JRES - JURN) / VCA;
dxdt_PIS = (PIIN - QPDEP * MAR - JPURN) / VPI;
double PTHTGT = PTH0 * 2.0 / (1.0 + exp(SPTH * (CAS - CA0)));
dxdt_PTHS = (PTHTGT - PTHS) / TAUPTH;
dxdt_VITD = (VITD0 * (1.0 + KPD * (PTHR - 1.0)) - VITD) / TAUD;
double cauex = JURN - CAUTHR; if (cauex < 0.0) cauex = 0.0;
dxdt_NEPH = KNEPH * cauex * (1.0 - NEPH) - KNEPHD * NEPH;

// --- bone matrix ---------------------------------------------------------
dxdt_OST  = KOSTF * OB - KCONS * MAR * OST;
dxdt_BMIN = KBF * MAR * pow(OST / OST0, POWOST) - KBR * OC * BMIN;

// --- growth plate & stature ---------------------------------------------
dxdt_GP = KGPR * fGPrep * (1.0 - GP) - KGPD * fGPdmg * GP;
double kirr = KIRR * (1.0 + KIRRINF * exp(-AGEN / TIRR));
dxdt_GPD = kirr * gpdef * PHYSIS * (1.0 - GPD);
dxdt_RSS = (RSSTGT - RSS) / TAURSS;
double dz = (GROWTHREL - 1.0) * KZ * PHYSIS;
dxdt_HTZ = (HTZ <= -6.0 && dz < 0.0) ? 0.0 : dz;

// --- thorax / respiration / survival ------------------------------------
dxdt_RIB  = KRIBR * fRBrep * (1.0 - RIB) - KRIBD * fRBdmg * RIB;
dxdt_RESP = (RESPTGT - RESP) / TAURESP;
dxdt_SURV = -HAZ * SURV;
dxdt_CUMHAZ = HAZ;

// --- symptoms / other organs --------------------------------------------
dxdt_MUS  = (MUSTGT - MUS) / TAUMUS;
dxdt_PAIN = (PAINTGT - PAIN) / TAUPAIN;
dxdt_DENT = KDR * fDNrep * (1.0 - DENT) - KDD * fDNdmg * DENT;
dxdt_CRAN = KCS * exp(-AGEN / TCS) * (1.0 - 0.3 * mrc) * (1.0 - CRAN);
dxdt_SEIZ = (SEIZTGT - SEIZ) / TAUSEIZ;
double ssx = SSATN - 1.0;        if (ssx < 0.0) ssx = 0.0;
double ppd = 1.0 - PPIL / PPI0;  if (ppd < 0.0) ppd = 0.0;
dxdt_ECT = KECT * ssx * ppd - KECTD * ECT;
double ostr = OST / OST0 - 1.0; if (ostr < 0.0) ostr = 0.0;
dxdt_FX = KFXO * ostr * LOAD * (1.0 + 2.0 * BPB / KIBP) - KFXH * mrc * FX;
dxdt_AUCPPI = PPIL;

[TABLE]
//--- BEGIN SHARED ALGEBRA (duplicate of the [ODE] block; keep in sync) ---
double VCL  = VCKG * WT;
double BMNZ = BMIN > 0.15 ? BMIN : 0.15;
double BMAX = BMAXKG * WT * BMNZ;
double Cp   = AC / VCL;
double OCC  = EB / BMAX;
double ELOC  = FRACENZ * OB + KBONE * OCC;
double ALPUL = ALPN * (FRACENZ * (1.0 - FISO) + FISO) + SPACT * Cp;
double EPL   = ALPUL / ALPN;
double c1a   = FVOL * KOUT;
double c2a   = KCATPP * EPL + CLPPI;
double alph  = KOUT * c2a / (c1a + c2a);
double beta  = KOUT * JPSYS / (c1a + c2a);
double Vm    = KCATP * KMPPI;
double Ssum  = JPPI + beta;
double bq    = Vm * ELOC + alph * KMPPI - Ssum;
double disc  = bq * bq + 4.0 * alph * Ssum * KMPPI;
if (disc < 0.0) disc = 0.0;
double PPIL  = (-bq + sqrt(disc)) / (2.0 * alph);
double PPIP  = (c1a * PPIL + JPSYS) / (c1a + c2a);
double PLPP  = (JPLP + KCATPL * EPL * PLPMIN) / (KCATPL * EPL + CLPL);
double PEAP  = JPEA / (KCATPEA * EPL + CLPEA);
double OPNX  = OPN > 1.0 ? (OPN - 1.0) : 0.0;
double MINH  = 1.0 / (1.0 + PPIL / KIPPI + BPB / KIBP + OPNX * 40.0 / KIOPN);
double MINH0 = 1.0 / (1.0 + PPI0 / KIPPI);
double SSATN = pow((CAS * PIS) / (CA0 * PI0), NSSAT);
double MRELN = MINH / MINH0;
double MAR   = KMIN * OB * MRELN * SSATN;
double PTHR = PTHS / PTH0;
double xca  = CAS - CATHR; if (xca < 0.0) xca = 0.0;
double JURN = QURN * xca / (KURN + xca) / (0.7 + 0.3 * PTHR);
double GP0   = KGPR * (1.0/(1.0+KGP50)) /
               (KGPR * (1.0/(1.0+KGP50)) + KGPD * (KGP50/(1.0+KGP50)));
double RIB0  = KRIBR * (1.0/(1.0+KRIB50)) /
               (KRIBR * (1.0/(1.0+KRIB50)) + KRIBD * (KRIB50/(1.0+KRIB50)));
double DEN0  = KDR * (1.0/(1.0+KD50)) /
               (KDR * (1.0/(1.0+KD50)) + KDD * (KD50/(1.0+KD50)));
double GPREL   = GP / GP0;
double RIBREL  = RIB / RIB0;
double DENTREL = DENT / DEN0;
double AGEN    = AGE0 + TIME;
//--- END SHARED ALGEBRA --------------------------------------------------

double PPILX  = 100.0 * PPIL / PPI0;      // % of healthy perivesicular PPi
double PPIPX  = 100.0 * PPIP / PPI0;      // % of healthy plasma PPi
double PLPX   = 100.0 * PLPP / PLP0;      // % of healthy plasma PLP
double VENT   = RESP < VENTTHR ? 1.0 : 0.0;
double SIXMWT = 100.0 * MUS;              // 6MWT-like, % predicted
double AGEY   = AGEN / 365.0;
double ALPZ   = ALPUL / ALPN;             // serum ALP, x age-normal
double OSTPCT = 100.0 * OST;              // osteoid volume, %

[CAPTURE] @annotated
ELOC   : -, LOCAL TNSALP activity (1 = healthy) — the causal variable
EPL    : -, PLASMA TNSALP activity (1 = healthy) — the measured variable
ALPUL  : U/L, serum alkaline phosphatase activity
ALPZ   : -, serum ALP as multiple of age-normal
OCC    : -, hydroxyapatite occupancy by asfotase alfa
Cp     : mg/L, plasma asfotase alfa
PPIL   : uM, PERIVESICULAR PPi (causal, unmeasurable)
PPIP   : uM, plasma PPi (measurable)
PPILX  : %, perivesicular PPi as % of healthy
PPIPX  : %, plasma PPi as % of healthy
PLPP   : nM, plasma pyridoxal-5-phosphate
PLPX   : %, plasma PLP as % of healthy
PEAP   : uM, plasma phosphoethanolamine
MRELN  : -, relative mineral apposition capacity (1 = healthy)
MAR    : -, mineral apposition rate (1 = healthy)
MINH   : -, absolute inhibition factor
SSATN  : -, Ca x Pi supersaturation (1 = healthy)
GPREL  : -, growth-plate integrity relative to healthy
RIBREL : -, thoracic mineralization relative to healthy
DENTREL: -, dental attachment relative to healthy
OSTPCT : %, osteoid volume fraction (normal <2, osteomalacia >10)
JURN   : mmol/kg/d, urinary calcium excretion
VENT   : -, 1 = invasive ventilation assumed
SIXMWT : %, 6MWT-like muscle function, % predicted
AGEY   : y, current age
'

## ---------------------------------------------------------------------------
## Build
## ---------------------------------------------------------------------------
HPP_mod <- mcode("HPP_QSP", HPP_code)

## ---------------------------------------------------------------------------
## Genotype presets — residual LOCAL TNSALP activity as a fraction of normal.
##
## These are the ONLY disease-severity inputs. The clinical phenotype is an
## OUTPUT: the same equations produce perinatal lethality at 0.01 and an
## asymptomatic carrier at 0.50 (see T1 in the header).
## ---------------------------------------------------------------------------
HPP_genotype <- function(which = c("perinatal", "infantile", "childhood",
                                   "adult", "carrier")) {
  which <- match.arg(which)
  switch(
    which,
    perinatal = list(FRACENZ = 0.010, WT = 3.2,  AGE0 = 1,     HYPOPL = 0.15),
    infantile = list(FRACENZ = 0.030, WT = 5.0,  AGE0 = 14,    HYPOPL = 0.0),
    childhood = list(FRACENZ = 0.120, WT = 18.0, AGE0 = 1825,  HYPOPL = 0.0),
    adult     = list(FRACENZ = 0.350, WT = 70.0, AGE0 = 14600, HYPOPL = 0.0),
    carrier   = list(FRACENZ = 0.500, WT = 70.0, AGE0 = 14600, HYPOPL = 0.0)
  )
}

## ---------------------------------------------------------------------------
## HPP_settle() — the genotype burn-in
##
##   Integrates the UNTREATED genotype to its quasi-steady state with the
##   irreversible / cumulative processes switched off, then zeroes those states.
##   Scenarios start from this state, so an untreated and a treated arm share
##   one continuous trajectory and no "diseased baseline" is ever hand-set.
##
##   Mirrors settle() in hpp_reference_model.py.
## ---------------------------------------------------------------------------
HPP_settle <- function(pars, days = 4000) {
  burn <- modifyList(
    as.list(pars),
    list(KIRR = 0, KCS = 0, HAZ0 = 0, HAZS = 0, GPCLOSE = 1e9,
         KBPIN = 0, ETPTD = 0, EBPOC = 0, PNDOSE = 0, KNEPH = 0)
  )
  out <- as.data.frame(mrgsim(param(HPP_mod, burn), end = days, delta = days))
  last <- out[nrow(out), ]
  cmts <- names(as.list(mrgsolve::init(HPP_mod)))
  y0 <- as.list(setNames(as.numeric(last[cmts]), cmts))
  ## reset cumulative / therapy-dependent states
  for (nm in c("GPD", "HTZ", "CUMHAZ", "AUCPPI", "CRAN", "ECT", "FX", "BPB",
               "NEPH", "ADA", "ASC", "AC", "EB")) y0[[nm]] <- 0
  y0[["SURV"]] <- 1
  y0
}

## ---------------------------------------------------------------------------
## Dosing helpers
## ---------------------------------------------------------------------------
## Asfotase alfa is given SC. Label: 2 mg/kg three times weekly OR 1 mg/kg six
## times weekly; may be increased to 3 mg/kg three times weekly for insufficient
## response in perinatal/infantile disease.
HPP_dosing <- function(mgkg, wt, start = 14, stop = 3650, per_week = 3) {
  if (mgkg <= 0 || per_week <= 0) return(NULL)
  interval <- 7 / per_week
  n <- length(seq(start, stop - 1e-9, by = interval))
  if (n < 1) return(NULL)
  ev(time = start, amt = mgkg * wt, cmt = "ASC", ii = interval, addl = n - 1)
}

## ---------------------------------------------------------------------------
## HPP_run() — one scenario
## ---------------------------------------------------------------------------
HPP_run <- function(sev = "infantile", days = 365, dose = 0, per_week = 3,
                    dstart = 14, dstop = NULL, pn = 0, ada_max = 0.20,
                    tptd = 0, bp = 0, cain_mult = 1, extra = list(),
                    delta = 1) {
  pars <- HPP_genotype(sev)
  pars$PNDOSE <- pn
  pars$ADAMAX <- ada_max
  pars$ETPTD  <- tptd
  pars$CAIN   <- 1.40 * cain_mult
  if (bp > 0) { pars$KBPIN <- bp; pars$EBPOC <- 0.6 }
  pars <- modifyList(pars, extra)

  y0 <- HPP_settle(pars)
  if (is.null(dstop)) dstop <- days
  dos <- HPP_dosing(dose, pars$WT, start = dstart, stop = min(dstop, days),
                    per_week = per_week)

  m <- param(HPP_mod, pars)
  m <- mrgsolve::init(m, y0)
  out <- if (is.null(dos)) mrgsim(m, end = days, delta = delta)
         else mrgsim(m, events = dos, end = days, delta = delta)
  as.data.frame(out)
}

## ---------------------------------------------------------------------------
## The 17 scenarios
##
##  S1  perinatal, untreated .............. natural history, lethal form
##  S2  infantile, untreated .............. natural history
##  S3  childhood, untreated .............. natural history
##  S4  adult / odonto, untreated ......... natural history
##  S5  infantile + asfotase alfa 2 mg/kg 3x/wk .......... LABEL DOSE
##  S6  infantile + asfotase alfa 1 mg/kg 6x/wk .......... same weekly dose
##  S7  infantile + asfotase alfa 3 mg/kg 3x/wk .......... escalation
##  S8  infantile + asfotase alfa 0.5 mg/kg 3x/wk ........ under-dose
##  S9  infantile + asfotase alfa from day 14 (3-year horizon)
##  S10 infantile + asfotase alfa from day 365 ............ THE COST OF DELAY
##  S11 infantile + asfotase alfa, high-titre ADA subject
##  S12 perinatal + pyridoxine alone ..................... seizures only
##  S13 perinatal + asfotase alfa + pyridoxine ........... both axes
##  S14 adult + bisphosphonate ........................... MECHANISTIC HARM
##  S15 adult + teriparatide ............................. endogenous-enzyme route
##  S16 infantile + calcium / vitamin-D restriction ...... the hypercalcaemia lever
##  S17 childhood + asfotase alfa 1 year, then withdrawal
## ---------------------------------------------------------------------------
HPP_scenarios <- function() list(
  S1  = list(label = "S1  perinatal untreated",
             args = list(sev = "perinatal", days = 365)),
  S2  = list(label = "S2  infantile untreated",
             args = list(sev = "infantile", days = 365)),
  S3  = list(label = "S3  childhood untreated",
             args = list(sev = "childhood", days = 1095)),
  S4  = list(label = "S4  adult/odonto untreated",
             args = list(sev = "adult", days = 1095)),
  S5  = list(label = "S5  infantile AA 2 mg/kg TIW",
             args = list(sev = "infantile", days = 365, dose = 2, per_week = 3)),
  S6  = list(label = "S6  infantile AA 1 mg/kg 6x/wk",
             args = list(sev = "infantile", days = 365, dose = 1, per_week = 6)),
  S7  = list(label = "S7  infantile AA 3 mg/kg TIW",
             args = list(sev = "infantile", days = 365, dose = 3, per_week = 3)),
  S8  = list(label = "S8  infantile AA 0.5 mg/kg TIW",
             args = list(sev = "infantile", days = 365, dose = 0.5, per_week = 3)),
  S9  = list(label = "S9  infantile AA start d14",
             args = list(sev = "infantile", days = 1095, dose = 2, per_week = 3,
                         dstart = 14)),
  S10 = list(label = "S10 infantile AA start d365",
             args = list(sev = "infantile", days = 1095, dose = 2, per_week = 3,
                         dstart = 365)),
  S11 = list(label = "S11 infantile AA + high ADA",
             args = list(sev = "infantile", days = 365, dose = 2, per_week = 3,
                         ada_max = 1.0)),
  S12 = list(label = "S12 perinatal pyridoxine only",
             args = list(sev = "perinatal", days = 365, pn = 100)),
  S13 = list(label = "S13 perinatal AA + pyridoxine",
             args = list(sev = "perinatal", days = 365, dose = 2, per_week = 3,
                         pn = 100)),
  S14 = list(label = "S14 adult + bisphosphonate",
             args = list(sev = "adult", days = 1095, bp = 0.014)),
  S15 = list(label = "S15 adult + teriparatide",
             args = list(sev = "adult", days = 1095, tptd = 0.8)),
  S16 = list(label = "S16 infantile Ca/vitD restriction",
             args = list(sev = "infantile", days = 365, cain_mult = 0.6)),
  S17 = list(label = "S17 childhood AA 1 y then stop",
             args = list(sev = "childhood", days = 1095, dose = 2, per_week = 3,
                         dstop = 365))
)

## ---------------------------------------------------------------------------
## HPP_report() — reproduce the scenario table of hpp_model_report.txt
## ---------------------------------------------------------------------------
HPP_report <- function() {
  scn <- HPP_scenarios()
  rows <- lapply(names(scn), function(k) {
    s <- scn[[k]]
    out <- do.call(HPP_run, s$args)
    e <- out[nrow(out), ]
    data.frame(scenario = s$label, PPIL = e$PPIL, MRELN = e$MRELN,
               osteoid = e$OST, RSS = e$RSS, dHTZ = e$HTZ, RESP = e$RESP,
               SURV = e$SURV, MUS = e$MUS, SEIZ = e$SEIZ, PAIN = e$PAIN,
               PLP = e$PLPP, CaU = e$JURN, NEPH = e$NEPH,
               stringsAsFactors = FALSE)
  })
  res <- do.call(rbind, rows)
  print(res, digits = 3, row.names = FALSE)
  invisible(res)
}

## ---------------------------------------------------------------------------
## HPP_dose_ranging() — T2: which readout saturates first?
##
##   Sweeps total WEEKLY dose (given as mg/kg three times weekly) and reports
##   plasma PLP, plasma PPi, perivesicular PPi, HA occupancy, relative mineral
##   apposition and RSS at 26 weeks. The point of the sweep is that plasma PLP
##   is maximally suppressed at a dose that leaves the mineralization capacity
##   far from its ceiling.
## ---------------------------------------------------------------------------
HPP_dose_ranging <- function(weekly = c(0, 0.375, 0.75, 1.5, 3, 6, 9, 12, 18, 30),
                             sev = "infantile", days = 182) {
  rows <- lapply(weekly, function(w) {
    out <- HPP_run(sev = sev, days = days, dose = w / 3, per_week = 3, delta = 7)
    e <- out[nrow(out), ]
    data.frame(mgkg_week = w, ALP_UL = e$ALPUL, occupancy = e$OCC, ELOC = e$ELOC,
               PLP_nM = e$PLPP, PPi_plasma = e$PPIP, PPi_local = e$PPIL,
               Mrel = e$MRELN, RSS = e$RSS, osteoid = e$OST)
  })
  res <- do.call(rbind, rows)
  print(res, digits = 3, row.names = FALSE)
  invisible(res)
}

## ---------------------------------------------------------------------------
## HPP_threshold_curve() — T1: the hyperbola, and its closed form
##
##   Mrel(E) = (1 + PPi0/Ki) / (1 + (Jppi + kout*PPi_pl) / (Ki*(kcat*E + kout)))
##
##   is the PPi << Km limit; the model itself solves the exact quadratic. Both
##   are returned so the linearisation error is visible (it reaches ~44% in the
##   mid-range, which is why every reported number uses the exact solution).
## ---------------------------------------------------------------------------
HPP_threshold_curve <- function(E = c(0.01, 0.02, 0.05, 0.10, 0.20, 0.35,
                                      0.50, 0.75, 1.00)) {
  p <- as.list(param(HPP_mod))
  rows <- lapply(E, function(e) {
    pars <- modifyList(HPP_genotype("infantile"), list(FRACENZ = e))
    y0 <- HPP_settle(pars)
    m <- mrgsolve::init(param(HPP_mod, pars), y0)
    out <- as.data.frame(mrgsim(m, end = 1, delta = 1))
    ex <- out[nrow(out), ]
    lin_ppi <- (p$JPPI + p$KOUT * ex$PPIP) / (p$KCATP * e + p$KOUT)
    lin_mrel <- (1 + p$PPI0 / p$KIPPI) / (1 + lin_ppi / p$KIPPI)
    data.frame(fracEnz = e, PPi_local_exact = ex$PPIL,
               PPi_local_linear = lin_ppi, Mrel_exact = ex$MRELN,
               Mrel_linear = lin_mrel, osteoid = ex$OST, PLP_nM = ex$PLPP)
  })
  res <- do.call(rbind, rows)
  print(res, digits = 3, row.names = FALSE)
  invisible(res)
}

## ---------------------------------------------------------------------------
## CALIBRATION NOTES — what each block is anchored to
## ---------------------------------------------------------------------------
##  PK (asfotase alfa)
##    F = 0.458, tmax 24-48 h, terminal t1/2 = 2.28 d are the label values.
##    V, KON/KOFF/KDEGB and BMAXKG are NOT published; they are chosen so that
##    (i) 2 mg/kg TIW gives serum ALP in the low thousands of U/L, matching the
##    supraphysiologic activity reported on therapy, and (ii) HA occupancy at
##    the label dose is ~0.19, i.e. inside the linear range so that dose still
##    matters — consistent with the murine bone-targeted dose-response study
##    (PMID 21458605). These four parameters are the model's main PK
##    identifiability gap; treat occupancy as a relative, not absolute, scale.
##
##  PPi / mineralization
##    Healthy plasma PPi ~3 uM and Ki(PPi) for hydroxyapatite growth in the
##    low-micromolar range come from the classical calcification literature
##    (PMIDs 13893487, 6326671); the TNSALP/ENPP1/ANK antagonism that sets the
##    perivesicular balance is from PMIDs 12082181 and 15039209. JPPI is then
##    fixed by requiring PPi_loc = 3 uM at ELOC = 1 — not fitted to outcomes.
##    The resulting osteoid volume fractions (2% healthy -> 9-11% infantile)
##    fall in the histomorphometric osteomalacia range without being fitted.
##
##  Vitamin B6
##    Plasma PLP normal ~30-110 nM and markedly raised in HPP; the requirement
##    for TNSALP to dephosphorylate PLP before it can cross the blood-brain
##    barrier — hence pyridoxine-responsive seizures — is from the Alpl-null
##    mouse (PMIDs 7550313, 9056646) and the clinical reports (PMID 17395561).
##
##  Survival
##    HAZ0 / KHZ / HAZS are calibrated so that untreated perinatal HPP has
##    ~12% and untreated infantile HPP ~51% one-year survival, against ~89% on
##    label-dose asfotase alfa (reported: ~95% treated vs ~27-42% historical
##    control, PMID 26529632). The model is deliberately conservative on the
##    treated arm rather than tuned to match it exactly.
##
##  NOT calibrated / phenomenological
##    Craniosynostosis (KCS, TCS) is a rate law, not a mechanism: HPP
##    craniosynostosis is common and is NOT reliably prevented by ERT, and the
##    model reproduces that only by construction. The calcium homeostat runs
##    near its excretory capacity, which makes serum Ca the most
##    parameter-sensitive output in the model.
## ---------------------------------------------------------------------------

## ---------------------------------------------------------------------------
## Example session
## ---------------------------------------------------------------------------
if (FALSE) {
  ## natural history vs label dose
  nh <- HPP_run("infantile", days = 365)
  tx <- HPP_run("infantile", days = 365, dose = 2, per_week = 3)
  plot(nh$time, nh$RSS, type = "l", ylim = c(0, 8), xlab = "day", ylab = "RSS")
  lines(tx$time, tx$RSS, col = "red")

  ## T1: the severity spectrum is one hyperbola
  HPP_threshold_curve()

  ## T2: which readout saturates first?
  HPP_dose_ranging()

  ## all 17 scenarios
  HPP_report()
}
