##  Postural Orthostatic Tachycardia Syndrome (POTS, 체위성 기립성 빈맥 증후군) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : POTS — excessive orthostatic tachycardia without significant
##             orthostatic hypotension; neuropathic / hyperadrenergic /
##             hypovolemic / autoimmune-post-viral (incl. post-COVID) subtypes.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 23 ODE compartments — drug PK (midodrine + active metabolite
##             desglymidodrine, propranolol, fludrocortisone, ivabradine,
##             pyridostigmine, droxidopa) + orthostatic-hemodynamic/autonomic
##             disease network (plasma volume, total peripheral resistance,
##             standing norepinephrine, baroreflex sensitivity, deconditioning,
##             supine/standing heart rate, cerebral blood-flow index) +
##             clinical/PRO endpoints (COMPASS-31 composite, quality of life).
##  Time     : hours (acute hemodynamic response is minutes-hours; chronic
##             deconditioning/exercise-training and volume adaptation act over
##             days-weeks). Default simulation horizon 0 - 2016 h (12 weeks).
##  Units    : dose in mg; concentration in mg/L; heart rate in bpm; plasma
##             volume/TPR/baroreflex-sensitivity/deconditioning as relative
##             indices (1.0 = normal); NE in pg/mL; COMPASS-31/QoL 0-100.
##  Scenarios: 10 prebuilt — see POTS_simulate_scenarios() at bottom.
##  Anchors  : Sheldon 2015 Heart Rhythm (POTS consensus statement, diagnostic
##             criteria DeltaHR>=30 bpm adult/>=40 adolescent within 10 min
##             standing/tilt, without orthostatic hypotension);
##             Raj 2009 Circulation (propranolol RCT, low-dose 20 mg superior
##             to high-dose 80 mg for standing HR reduction);
##             Sutton/Grubb (midodrine open-label & crossover series);
##             Fu 2010/2011 Circulation & Heart Rhythm (exercise training
##             reverses cardiac atrophy/deconditioning, "The Levine protocol");
##             Raj 2005 Circulation (reduced blood/plasma volume in POTS,
##             RAAS paradox);
##             Kanjwal 2011 Cardiol J (pyridostigmine open-label);
##             Ruzieh 2017 / Moon 2018 (ivabradine case series, HR reduction
##             without hypotension);
##             Kaufmann/Gibbons droxidopa neurogenic-orthostatic-intolerance
##             program (norepinephrine-precursor rationale, extrapolated to
##             severe neuropathic POTS);
##             Fedorowski 2022 Nat Rev Cardiol & Vernino 2021 Auton Neurosci
##             (POTS subtypes, autoimmune/post-viral & post-COVID mechanisms).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of postural orthostatic tachycardia syndrome (POTS) linking
orthostatic venous pooling, baroreflex-arc control, and four overlapping
pathophysiological subtypes (neuropathic, hyperadrenergic, hypovolemic,
autoimmune/post-viral) to excessive standing tachycardia, cerebral
hypoperfusion symptoms, and PRO endpoints, with mechanistic PK/PD for
midodrine, beta-blockade, fludrocortisone, ivabradine, pyridostigmine, and
droxidopa plus non-pharmacologic volume/exercise therapy.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / subtype
AGE          : 28    : age (years; POTS typically 15-50, F:M ~5:1)
WT           : 65    : body weight (kg)
SUBTYPE      : 0     : 0=mixed/idiopathic, 1=neuropathic, 2=hyperadrenergic, 3=hypovolemic, 4=autoimmune/post-viral
BASE_HRSUP   : 72    : baseline supine heart rate (bpm)
BASE_PV      : 1.00  : baseline relative plasma volume index (1.0=normal)
BASE_COMPASS : 45    : baseline COMPASS-31 autonomic symptom score (0-100)
BASE_QOL     : 55    : baseline quality-of-life score (0-100, higher=better)
SALT_LOAD    : 0     : 1 = high salt (10-12 g/d) + fluid (2-3 L/d) loading
COMPRESSION  : 0     : 1 = abdominal/lower-limb compression garments worn
EXERCISE     : 0     : 1 = recumbent/semi-recumbent exercise-training program active

//--- Midodrine PK (oral prodrug F~0.93; parent t1/2~0.4h; active metabolite
//    desglymidodrine (DMD) t1/2~3-4h carries the alpha1-agonist activity)
KA_MID     : 4.0    : 1/h
F_MID      : 0.93
CL_MID     : 165    : L/h (parent, rapid clearance/conversion)
V_MID      : 100     : L
FM_DMD     : 0.90    : fraction of absorbed midodrine converted to desglymidodrine
CL_DMD     : 40      : L/h
V_DMD      : 200     : L

//--- Propranolol PK (nonselective beta-blocker; oral F~0.25 high first-pass;
//    t1/2~4h)  Raj 2009 Circulation used 20 mg TID (low-dose superior)
KA_PROP    : 1.5
F_PROP     : 0.25
CL_PROP    : 60      : L/h
V_PROP     : 280      : L

//--- Fludrocortisone PK (oral F~1.0; short plasma t1/2 but sustained genomic
//    mineralocorticoid-receptor renal Na-retention effect modeled via slow PD turnover)
KA_FLUDRO  : 2.0
F_FLUDRO   : 1.00
CL_FLUDRO  : 42      : L/h
V_FLUDRO   : 30       : L

//--- Ivabradine PK (If-channel blocker; oral F~0.40 first-pass; t1/2~2h)
KA_IVA     : 2.0
F_IVA      : 0.40
CL_IVA     : 35      : L/h
V_IVA      : 100      : L

//--- Pyridostigmine PK (AChE inhibitor at autonomic ganglia; oral F~0.12 poor
//    bioavailability; t1/2~1.5h)
KA_PYR     : 1.5
F_PYR      : 0.12
CL_PYR     : 14      : L/h
V_PYR      : 30       : L

//--- Droxidopa PK (norepinephrine precursor; oral F~0.10 effective; t1/2~2.5h)
KA_DROX    : 1.0
F_DROX     : 0.10
CL_DROX    : 56      : L/h
V_DROX     : 200      : L

//--- Plasma volume (PV) turnover: expanded by fludrocortisone MR activation &
//    salt/fluid loading; chronically reduced in hypovolemic subtype (RAAS paradox)
KOUT_PV       : 0.010  : 1/h (slow, days-scale genomic/renal adaptation)
PV_DEFICIT_HYPOVOL : 0.15  : fractional PV deficit if SUBTYPE==3
EC50_FLUDRO   : 0.006  : mg/L, desglymidodrine-equivalent EC50 surrogate for MR activation
EMAX_FLUDRO_PV: 0.18   : max fractional PV expansion from fludrocortisone
EMAX_SALT_PV  : 0.10   : max fractional PV expansion from salt/fluid loading alone

//--- Total peripheral resistance (TPR) turnover: raised by midodrine alpha1
//    agonism & by hyperadrenergic subtype tone; lowered by venous pooling/MCAS/hEDS
KOUT_TPR      : 0.35   : 1/h (fast vasomotor turnover)
TPR_BASE      : 1.00
EC50_DMD      : 0.010  : mg/L, desglymidodrine EC50 for alpha1 vasoconstriction
EMAX_DMD_TPR  : 0.45   : max fractional TPR increase from midodrine
TPR_DEFICIT_NEURO : 0.20 : fractional TPR deficit (impaired venoconstriction) if SUBTYPE==1
COMPRESSION_TPR    : 0.10 : fractional effective-TPR gain from compression garments

//--- Standing plasma norepinephrine (NE_ST) turnover
KOUT_NE       : 0.40   : 1/h
NE_BASE       : 350    : pg/mL, typical non-hyperadrenergic POTS standing NE
NE_HYPERAD_MULT : 1.9  : multiplier on NE synthesis if SUBTYPE==2 (>600 pg/mL threshold)
NE_AUTOIMM_MULT : 1.3  : multiplier if SUBTYPE==4 (agonist autoantibody potentiation)
EC50_DROX     : 0.15   : mg/L, droxidopa EC50 for peripheral NE synthesis boost
EMAX_DROX_NE  : 250    : pg/mL, max NE increase from droxidopa

//--- Baroreflex sensitivity (BRS, relative units, 1.0=normal) turnover
KOUT_BRS      : 0.006  : 1/h (slow, chronic)
BRS_DEFICIT_NEURO : 0.35 : fractional BRS deficit if SUBTYPE==1
DECON_BRS_LOSS: 0.30    : max fractional BRS loss attributable to deconditioning
EC50_PYR_BRS  : 0.08    : mg/L, pyridostigmine EC50 for ganglionic augmentation
EMAX_PYR_BRS  : 0.20    : max fractional BRS restoration from pyridostigmine

//--- Deconditioning index (0=fit, 1=fully deconditioned) turnover
KOUT_DECON    : 0.004   : 1/h (very slow, weeks-scale)
DECON_DRIVE_SYMPTOM : 0.55 : target deconditioning driven by symptom burden (activity avoidance)
EXERCISE_RECOVERY   : 0.85 : fractional reduction of deconditioning target if EXERCISE=1

//--- Supine heart rate turnover
KOUT_HRSUP    : 0.25   : 1/h
EMAX_BB_HRSUP : 0.10   : max fractional HRsupine reduction from beta-blockade (mild)
EC50_PROP     : 0.030  : mg/L, propranolol EC50 for beta1 blockade
EMAX_IVA_HRSUP: 0.08    : max fractional HRsupine reduction from ivabradine
EC50_IVA      : 0.020   : mg/L

//--- Standing heart rate turnover (10-min active-stand / tilt response)
KOUT_HRST     : 0.60   : 1/h (fast, within the 10-min stand-test window)
GAIN_NE_HR    : 0.055  : bpm increase in target HR per pg/mL standing NE above 150, scaled by BRS/TPR/PV deficits
GAIN_POOL_HR  : 55     : bpm, max additional tachycardia drive from uncorrected venous pooling/PV deficit
EMAX_BB_HRST  : 0.35    : max fractional HRstanding reduction from beta-blockade
EMAX_IVA_HRST : 0.30    : max fractional HRstanding reduction from ivabradine (selective, BP-sparing)
EMAX_PYR_HRST : 0.15    : max fractional HRstanding reduction from pyridostigmine

//--- Cerebral blood-flow index (CBF, relative, 1.0=normal) turnover
KOUT_CBF      : 0.50   : 1/h
CBF_TPR_WT    : 0.4     : weight of TPR deficit on CBF drop
CBF_PV_WT     : 0.4     : weight of PV deficit on CBF drop
CBF_HR_WT     : 0.2     : weight of excessive tachycardia (inefficient filling) on CBF drop

//--- COMPASS-31 composite symptom score turnover
KOUT_COMPASS  : 0.015  : 1/h (days-scale symptom adaptation)
SCALE_COMPASS_DHR : 0.55 : COMPASS points per bpm of DeltaHR above 30
SCALE_COMPASS_CBF : 30   : COMPASS points per unit CBF deficit
SCALE_COMPASS_DECON: 15   : COMPASS points per unit deconditioning

//--- Quality-of-life score turnover
KOUT_QOL      : 0.010  : 1/h
QOL_MAX       : 95
SCALE_QOL_COMPASS : 0.55 : QoL points lost per COMPASS point

[CMT] @annotated
GUT_MID    : Midodrine gut depot (mg)
CEN_MID    : Midodrine parent plasma (mg)
CEN_DMD    : Desglymidodrine active metabolite plasma (mg)
GUT_PROP   : Propranolol gut depot (mg)
CEN_PROP   : Propranolol plasma (mg)
GUT_FLUDRO : Fludrocortisone gut depot (mg)
CEN_FLUDRO : Fludrocortisone plasma (mg)
GUT_IVA    : Ivabradine gut depot (mg)
CEN_IVA    : Ivabradine plasma (mg)
GUT_PYR    : Pyridostigmine gut depot (mg)
CEN_PYR    : Pyridostigmine plasma (mg)
GUT_DROX   : Droxidopa gut depot (mg)
CEN_DROX   : Droxidopa plasma (mg)
PV         : Relative plasma volume index (1.0=normal)
TPR        : Relative total peripheral resistance index (1.0=normal)
NE_ST      : Standing plasma norepinephrine (pg/mL)
BRS        : Relative baroreflex sensitivity index (1.0=normal)
DECON      : Deconditioning index (0-1)
HRSUP      : Supine heart rate (bpm)
HRST       : Standing heart rate at 10 min (bpm)
CBF        : Relative cerebral blood-flow index (1.0=normal)
COMPASS    : COMPASS-31 autonomic-symptom composite score (0-100)
QOL        : Quality-of-life score (0-100, higher=better)

[MAIN]
// Initial conditions
GUT_MID_0 = 0; CEN_MID_0 = 0; CEN_DMD_0 = 0;
GUT_PROP_0 = 0; CEN_PROP_0 = 0;
GUT_FLUDRO_0 = 0; CEN_FLUDRO_0 = 0;
GUT_IVA_0 = 0; CEN_IVA_0 = 0;
GUT_PYR_0 = 0; CEN_PYR_0 = 0;
GUT_DROX_0 = 0; CEN_DROX_0 = 0;

double pv0 = BASE_PV * (1.0 - (SUBTYPE==3 ? PV_DEFICIT_HYPOVOL : 0.0));
PV_0 = pv0;

double tpr0 = TPR_BASE * (1.0 - (SUBTYPE==1 ? TPR_DEFICIT_NEURO : 0.0));
TPR_0 = tpr0;

double ne0 = NE_BASE * (SUBTYPE==2 ? NE_HYPERAD_MULT : (SUBTYPE==4 ? NE_AUTOIMM_MULT : 1.0));
NE_ST_0 = ne0;

double brs0 = 1.0 - (SUBTYPE==1 ? BRS_DEFICIT_NEURO : 0.0);
BRS_0 = brs0;

DECON_0  = 0.35;
HRSUP_0  = BASE_HRSUP;

double pool_deficit0 = (1.0 - pv0) + (1.0 - tpr0);
double hrst0 = BASE_HRSUP + GAIN_POOL_HR * pool_deficit0 / brs0 + GAIN_NE_HR * (ne0 - 150.0) / brs0;
HRST_0 = hrst0;

CBF_0    = 1.0 - CBF_TPR_WT*(1.0-tpr0) - CBF_PV_WT*(1.0-pv0);
COMPASS_0 = BASE_COMPASS;
QOL_0     = BASE_QOL;

[ODE]
// ---------- PK ----------
double CMID  = CEN_MID  / V_MID;
double CDMD  = CEN_DMD  / V_DMD;
double CPROP = CEN_PROP / V_PROP;
double CFLU  = CEN_FLUDRO / V_FLUDRO;
double CIVA  = CEN_IVA  / V_IVA;
double CPYR  = CEN_PYR  / V_PYR;
double CDROX = CEN_DROX / V_DROX;

dxdt_GUT_MID = -KA_MID * GUT_MID;
dxdt_CEN_MID =  F_MID * KA_MID * GUT_MID - (CL_MID/V_MID) * CEN_MID;
dxdt_CEN_DMD =  FM_DMD * (CL_MID/V_MID) * CEN_MID - (CL_DMD/V_DMD) * CEN_DMD;

dxdt_GUT_PROP = -KA_PROP * GUT_PROP;
dxdt_CEN_PROP =  F_PROP * KA_PROP * GUT_PROP - (CL_PROP/V_PROP) * CEN_PROP;

dxdt_GUT_FLUDRO = -KA_FLUDRO * GUT_FLUDRO;
dxdt_CEN_FLUDRO =  F_FLUDRO * KA_FLUDRO * GUT_FLUDRO - (CL_FLUDRO/V_FLUDRO) * CEN_FLUDRO;

dxdt_GUT_IVA = -KA_IVA * GUT_IVA;
dxdt_CEN_IVA =  F_IVA * KA_IVA * GUT_IVA - (CL_IVA/V_IVA) * CEN_IVA;

dxdt_GUT_PYR = -KA_PYR * GUT_PYR;
dxdt_CEN_PYR =  F_PYR * KA_PYR * GUT_PYR - (CL_PYR/V_PYR) * CEN_PYR;

dxdt_GUT_DROX = -KA_DROX * GUT_DROX;
dxdt_CEN_DROX =  F_DROX * KA_DROX * GUT_DROX - (CL_DROX/V_DROX) * CEN_DROX;

// ---------- Plasma volume (fludrocortisone MR activation + salt loading; hypovolemic deficit) ----------
double fludro_fx = EMAX_FLUDRO_PV * CFLU / (EC50_FLUDRO + CFLU);
double salt_fx   = (SALT_LOAD > 0) ? EMAX_SALT_PV : 0.0;
double pv_deficit_chronic = (SUBTYPE==3) ? PV_DEFICIT_HYPOVOL : 0.0;
double PV_target = BASE_PV * (1.0 - pv_deficit_chronic) * (1.0 + fludro_fx + salt_fx);
dxdt_PV = KOUT_PV * (PV_target - PV);

// ---------- Total peripheral resistance (midodrine alpha1 agonism; neuropathic deficit; compression) ----------
double mid_fx = EMAX_DMD_TPR * CDMD / (EC50_DMD + CDMD);
double compress_fx = (COMPRESSION > 0) ? COMPRESSION_TPR : 0.0;
double tpr_deficit_chronic = (SUBTYPE==1) ? TPR_DEFICIT_NEURO : 0.0;
double TPR_target = TPR_BASE * (1.0 - tpr_deficit_chronic) * (1.0 + mid_fx + compress_fx);
dxdt_TPR = KOUT_TPR * (TPR_target - TPR);

// ---------- Standing norepinephrine (subtype synthesis rate + droxidopa precursor boost) ----------
double subtype_ne_mult = (SUBTYPE==2) ? NE_HYPERAD_MULT : ((SUBTYPE==4) ? NE_AUTOIMM_MULT : 1.0);
double drox_fx = EMAX_DROX_NE * CDROX / (EC50_DROX + CDROX);
double NE_target = NE_BASE * subtype_ne_mult + drox_fx;
dxdt_NE_ST = KOUT_NE * (NE_target - NE_ST);

// ---------- Baroreflex sensitivity (neuropathic deficit; deconditioning; pyridostigmine augmentation) ----------
double pyr_fx = EMAX_PYR_BRS * CPYR / (EC50_PYR_BRS + CPYR);
double brs_deficit_chronic = (SUBTYPE==1) ? BRS_DEFICIT_NEURO : 0.0;
double BRS_target = (1.0 - brs_deficit_chronic) * (1.0 - DECON_BRS_LOSS*DECON) * (1.0 + pyr_fx);
dxdt_BRS = KOUT_BRS * (BRS_target - BRS);

// ---------- Deconditioning (symptom-driven activity avoidance vs. exercise-training reversal) ----------
double decon_drive = DECON_DRIVE_SYMPTOM * (COMPASS/100.0);
double DECON_target = (EXERCISE > 0) ? decon_drive * (1.0 - EXERCISE_RECOVERY) : decon_drive;
dxdt_DECON = KOUT_DECON * (DECON_target - DECON);

// ---------- Supine heart rate (mild beta-blocker/ivabradine effect at rest) ----------
double bb_fx_sup  = EMAX_BB_HRSUP  * CPROP/(EC50_PROP + CPROP);
double iva_fx_sup = EMAX_IVA_HRSUP * CIVA /(EC50_IVA  + CIVA);
double HRSUP_target = BASE_HRSUP * (1.0 - bb_fx_sup - iva_fx_sup);
dxdt_HRSUP = KOUT_HRSUP * (HRSUP_target - HRSUP);

// ---------- Standing heart rate (10-min stand/tilt response) ----------
double pool_deficit = (1.0 - PV) + (1.0 - TPR);
if (pool_deficit < 0) pool_deficit = 0;
double ne_drive = NE_ST - 150.0;
if (ne_drive < 0) ne_drive = 0;
double raw_target = HRSUP + GAIN_POOL_HR * pool_deficit / BRS + GAIN_NE_HR * ne_drive / BRS;
double bb_fx_st  = EMAX_BB_HRST  * CPROP/(EC50_PROP + CPROP);
double iva_fx_st = EMAX_IVA_HRST * CIVA /(EC50_IVA  + CIVA);
double pyr_fx_st = EMAX_PYR_HRST * CPYR/(EC50_PYR_BRS + CPYR);
double drug_fx_st = bb_fx_st + iva_fx_st + pyr_fx_st;
if (drug_fx_st > 0.75) drug_fx_st = 0.75;
double HRST_target = HRSUP + (raw_target - HRSUP) * (1.0 - drug_fx_st);
dxdt_HRST = KOUT_HRST * (HRST_target - HRST);

// ---------- Cerebral blood-flow index ----------
double excess_tachy = (HRST - HRSUP - 30.0);
if (excess_tachy < 0) excess_tachy = 0;
double CBF_target = 1.0 - CBF_TPR_WT*(1.0-TPR) - CBF_PV_WT*(1.0-PV) - CBF_HR_WT*(excess_tachy/60.0);
if (CBF_target < 0.3) CBF_target = 0.3;
dxdt_CBF = KOUT_CBF * (CBF_target - CBF);

// ---------- COMPASS-31 composite symptom score ----------
double dHR = HRST - HRSUP;
double dHR_excess = dHR - 30.0;
if (dHR_excess < 0) dHR_excess = 0;
double cbf_deficit = 1.0 - CBF;
if (cbf_deficit < 0) cbf_deficit = 0;
double COMPASS_target = SCALE_COMPASS_DHR*dHR_excess + SCALE_COMPASS_CBF*cbf_deficit + SCALE_COMPASS_DECON*DECON;
if (COMPASS_target > 100) COMPASS_target = 100;
if (COMPASS_target < 0) COMPASS_target = 0;
dxdt_COMPASS = KOUT_COMPASS * (COMPASS_target - COMPASS);

// ---------- Quality of life ----------
double QOL_target = QOL_MAX - SCALE_QOL_COMPASS * COMPASS;
if (QOL_target < 0) QOL_target = 0;
if (QOL_target > QOL_MAX) QOL_target = QOL_MAX;
dxdt_QOL = KOUT_QOL * (QOL_target - QOL);

[TABLE]
capture conc_midodrine       = CEN_MID  / V_MID;
capture conc_desglymidodrine = CEN_DMD  / V_DMD;
capture conc_propranolol     = CEN_PROP / V_PROP;
capture conc_fludrocortisone = CEN_FLUDRO / V_FLUDRO;
capture conc_ivabradine      = CEN_IVA  / V_IVA;
capture conc_pyridostigmine  = CEN_PYR  / V_PYR;
capture conc_droxidopa       = CEN_DROX / V_DROX;
capture PlasmaVolume_idx     = PV;
capture TPR_idx              = TPR;
capture StandingNE_pgmL      = NE_ST;
capture Baroreflex_idx       = BRS;
capture Deconditioning_idx   = DECON;
capture HR_supine_bpm        = HRSUP;
capture HR_standing_bpm      = HRST;
capture DeltaHR_bpm          = HRST - HRSUP;
capture CBF_idx              = CBF;
capture COMPASS31_score      = COMPASS;
capture QoL_score            = QOL;

[CAPTURE]
conc_midodrine conc_desglymidodrine conc_propranolol conc_fludrocortisone
conc_ivabradine conc_pyridostigmine conc_droxidopa
PlasmaVolume_idx TPR_idx StandingNE_pgmL Baroreflex_idx Deconditioning_idx
HR_supine_bpm HR_standing_bpm DeltaHR_bpm CBF_idx COMPASS31_score QoL_score


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("pots_mrgsolve_model.R")
##
##  # ---------- 10 prebuilt scenarios (end_h = simulation horizon, hours) ----------
##
##  POTS_simulate_scenarios <- function(end_h = 2016) {
##
##    sc <- list(
##      "1. Untreated natural history (mixed subtype)" =
##        ev(amt=0, cmt="CEN_MID", time=0),
##
##      "2. Salt/fluid loading + compression garments" =
##        ev(amt=0, cmt="CEN_MID", time=0),   # set SALT_LOAD=1, COMPRESSION=1 via idata/param
##
##      "3. Propranolol 20 mg PO TID (hyperadrenergic subtype)" =
##        ev(amt=20, cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "4. Midodrine 10 mg PO TID (neuropathic subtype)" =
##        ev(amt=10, cmt="GUT_MID", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "5. Fludrocortisone 0.1 mg PO QD + salt (hypovolemic subtype)" =
##        ev(amt=0.1, cmt="GUT_FLUDRO", ii=1, addl=ceiling(end_h/24)),  # + SALT_LOAD=1
##
##      "6. Ivabradine 5 mg PO BID (refractory tachycardia, BP-sparing)" =
##        ev(amt=5, cmt="GUT_IVA", ii=12/24, addl=2*ceiling(end_h/24)),
##
##      "7. Pyridostigmine 60 mg PO TID (mild-moderate augmentation)" =
##        ev(amt=60, cmt="GUT_PYR", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "8. Droxidopa 100 mg PO TID (severe neuropathic subtype)" =
##        ev(amt=100, cmt="GUT_DROX", ii=8/24, addl=3*ceiling(end_h/24)),
##
##      "9. Combination: propranolol 10 mg TID + midodrine 5 mg TID + compression + exercise" =
##        seq(ev(amt=10, cmt="GUT_PROP", ii=8/24, addl=3*ceiling(end_h/24)),
##            ev(amt=5,  cmt="GUT_MID",  ii=8/24, addl=3*ceiling(end_h/24))),  # + COMPRESSION=1, EXERCISE=1
##
##      "10. Recumbent/semi-recumbent exercise-training program alone" =
##        ev(amt=0, cmt="CEN_MID", time=0)  # EXERCISE=1 only
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      mod %>% mrgsim(e, end=end_h, delta=1) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # DeltaHR diagnostic threshold (Sheldon 2015 HRS consensus): >=30 bpm adult /
##  #   >=40 bpm adolescent within 10 min of standing/tilt, no orthostatic hypotension
##  # Propranolol 20 mg (Raj 2009 Circulation)    : standing HR reduction superior to 80 mg;
##  #   low-dose selectively blunts excess reflex tachycardia without excess fatigue
##  # Midodrine (Sutton/Grubb open-label series)  : standing HR/symptom improvement via
##  #   alpha1 venous/arteriolar constriction, most benefit in neuropathic subtype
##  # Fludrocortisone + salt (small RCTs, mixed)  : modest ~expansion of plasma volume,
##  #   best evidence in hypovolemic-subtype/low-renin patients
##  # Ivabradine (Ruzieh 2017, Moon 2018 case series): HR reduction without BP effect,
##  #   attractive when hypotension limits beta-blocker/midodrine titration
##  # Pyridostigmine (Kanjwal 2011 Cardiol J)     : ganglionic augmentation reduces
##  #   standing HR, GI cramping/diarrhea dose-limiting
##  # Exercise training (Fu 2010/2011 Circulation/Heart Rhythm, "Levine protocol"):
##  #   reverses cardiac atrophy/deconditioning over 3 months, reduces standing HR and
##  #   improves QoL comparably to pharmacotherapy in many patients
##  # Blood/plasma volume deficit (Raj 2005 Circulation): ~10-15% lower than controls
##  #   in a subset, with paradoxically low-normal renin/aldosterone for the deficit
##
##  # ---------- Quick sanity plots ----------
##  # df <- POTS_simulate_scenarios(2016)
##  # ggplot(df, aes(time/24, DeltaHR_bpm, colour=scenario)) + geom_line() + xlab("day")
##  # ggplot(df, aes(time/24, COMPASS31_score, colour=scenario)) + geom_line() + xlab("day")
