##  Endometrial Carcinoma (EC) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Endometrial carcinoma — the most common gynaecologic malignancy
##             in high-income countries and one of the few whose incidence is
##             RISING, tracking the obesity epidemic. Two intertwined engines:
##             (i) an ENDOCRINE engine — adipose aromatase converts adrenal/
##             ovarian androstenedione to estrone, hyperinsulinaemia lowers SHBG
##             and raises the free estradiol fraction, and in the absence of
##             luteal progesterone the endometrium sees UNOPPOSED oestrogen ->
##             ERa-driven proliferation -> hyperplasia -> EIN -> endometrioid
##             carcinoma; and (ii) a GENOMIC engine — PTEN/PIK3CA/PIK3R1 lesions
##             (PI3K pathway altered in >90% of endometrioid tumours), ARID1A,
##             CTNNB1, KRAS, and — the axis this model is built around —
##             DNA-repair status: POLE exonuclease-domain mutation, mismatch-
##             repair deficiency (Lynch or sporadic MLH1 hypermethylation), or
##             neither, with TP53 abnormality marking the copy-number-high
##             serous-like class.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  ---------------------------------------------------------------------------
##  THE ORGANISING CLAIM OF THIS MODEL
##  ---------------------------------------------------------------------------
##  Endometrial cancer is the solid tumour in which the MOLECULAR CLASS, not the
##  histology and not the stage, reorders the entire therapeutic decision tree.
##  The TCGA four classes (POLEmut / MMRd / NSMP / p53abn) are treated here NOT
##  as four discrete diseases but as FOUR POINTS ON ONE CONTINUOUS AXIS —
##  tumour mutational burden — separated by nearly two orders of magnitude:
##
##      p53abn  ~2.3 mut/Mb        NSMP ~2.9 mut/Mb
##      MMRd    ~18-40 mut/Mb      POLEmut  >100 mut/Mb
##
##  Everything immunological in this model hangs off a single saturating Hill
##  function of that axis:
##
##      IMMUNOGENICITY = TMB^h / (TMB50^h + TMB^h),   TMB50 = 13, h = 1.4
##
##  This one equation is not fitted to the immunotherapy trials — it is
##  parameterised from the mutation-rate literature and then CHECKED against
##  them. It reproduces, without further tuning, the central empirical fact of
##  modern EC therapeutics: the same anti-PD-1 antibody has hazard ratio ~0.28
##  in dMMR (RUBY) and ~0.76 in pMMR, because dMMR sits high on the shoulder of
##  the curve (I = 0.79, after the frameshift uplift) and pMMR sits on the
##  floor (I = 0.11).
##
##  Three consequences follow, and they are the reason to build the model this
##  way rather than as four separate disease models:
##
##  1. TMB50 = 13 mut/Mb sits almost exactly where the clinical dMMR/pMMR
##     dichotomy is drawn. The biomarker "works" precisely BECAUSE the
##     threshold was placed on the steepest part of a continuous curve — which
##     also means patients near the boundary (MSI-low, MMR-heterogeneous,
##     subclonal MLH1 methylation) are the ones a binary test must get wrong.
##     EMC_tmb_sweep() at the bottom of this file moves TMB continuously with
##     everything else fixed and shows the dichotomy is a convenience, not a
##     biological edge.
##  2. Because the curve SATURATES, POLEmut (TMB 140, I = 0.965) is barely more
##     immunogenic than a hypothetical TMB-60 tumour. POLEmut's spectacular
##     prognosis is therefore NOT a dose-response argument for more therapy —
##     it is the quantitative case for DE-ESCALATION (the RAINBO POLE-BLUE
##     hypothesis). In the adjuvant/micrometastatic setting the model puts
##     POLEmut at essentially the same 3-year tumour burden with and without
##     chemotherapy (4.8 vs 4.6 mm); the chemotherapy only makes the fall
##     faster, not deeper.
##  3. The floor of the curve is where the pharmacology has to be different in
##     kind, not in dose. pMMR tumours cannot be rescued by more checkpoint
##     blockade; they are rescued by CHANGING THE TME — lenvatinib's
##     anti-angiogenic MDSC-depleting vascular-normalising effect is modelled
##     as a multiplier on T-cell infiltration rather than as tumour kill.
##     Lenvatinib has NO tumour-kill term anywhere in this model. Zeroing
##     LEN_MDSC and LEN_NORM cuts the pembrolizumab+lenvatinib response in an
##     NSMP tumour from -60% to -26% and the survival surrogate from 0.64 to
##     0.43 — so roughly two thirds of the combination benefit is immunological
##     reprogramming and one third is plain perfusion starvation. That split is
##     the model's falsifiable claim about the KEYNOTE-775 mechanism.
##
##  Scope    : 35 ODE compartments —
##             PK (13): carboplatin, paclitaxel (2-cmt), anti-PD-1 mAb (2-cmt,
##                      dostarlimab/pembrolizumab), lenvatinib (oral, 2-cmt),
##                      progestin (megestrol PO or levonorgestrel IUS local),
##                      everolimus (oral), letrozole (oral)
##             Endocrine (3): free estradiol, ERa transcriptional activity,
##                      PR-B receptor expression (with chronic-progestin
##                      down-regulation = acquired hormonal resistance)
##             Oncogenic signalling (1): PI3K/AKT/mTOR activity
##             Tumour (2): chemo/hormone-sensitive and resistant clones
##             Immunity (5): neoantigen load, CD8 effector, exhausted T cells,
##                      Treg, MDSC
##             Vasculature (2): VEGF-A, microvessel density
##             Biomarkers (2): CA-125, ctDNA VAF
##             Myelosuppression (5): Friberg proliferating + 3 transit +
##                      circulating neutrophils
##             Toxicity/outcome (2): systolic blood pressure, cumulative hazard
##  Time     : days. Default horizon 730 d (advanced/recurrent disease) or
##             180-360 d for the fertility-sparing hormonal scenarios.
##  Units    : plasma PK in mg/L with literature-derived CL/V where available;
##             tumour burden as RECIST sum of target-lesion diameters (mm);
##             immune compartments in normalised density units (baseline = 1);
##             CA-125 U/mL; neutrophils 10^9/L; SBP mmHg.
##  Scenarios: 8 prebuilt — see EMC_simulate_scenarios() at the bottom.
##  Anchors  : Kandoth 2013 Nature 497:67 (TCGA integrated genomic
##             characterisation, the four classes); Talhouk 2015 Br J Cancer
##             113:299 / 2017 Cancer 123:802 (ProMisE surrogate classifier);
##             Leon-Castillo 2020 J Clin Oncol 38:3388 (PORTEC-3 molecular
##             subgroup analysis); Mirza 2023 N Engl J Med 388:2145 (RUBY,
##             dostarlimab + chemo, dMMR HR 0.28); Eskander 2023 N Engl J Med
##             388:2159 (NRG-GY018, pembrolizumab + chemo, dMMR HR 0.30 /
##             pMMR HR 0.54); Makker 2022 N Engl J Med 386:437 (KEYNOTE-775,
##             lenvatinib + pembrolizumab in pMMR, PFS HR 0.60, OS HR 0.68);
##             Oaknin 2020 JAMA Oncol 6:1766 (GARNET, dostarlimab monotherapy,
##             dMMR ORR 45.5% vs pMMR 15.4%); Miller 2020 J Clin Oncol 38:3841
##             (GOG-0209, carboplatin-paclitaxel as the reference doublet);
##             Slomovitz 2015 J Clin Oncol 33:930 (everolimus + letrozole,
##             ORR 32%); Westin 2021 Am J Obstet Gynecol 224:191.e1 (feMMe /
##             LNG-IUS fertility-sparing); Fader 2018 J Clin Oncol 36:2044
##             (trastuzumab in HER2+ uterine serous).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================

[PROB]
QSP model of endometrial carcinoma linking the unopposed-oestrogen endocrine
axis (adipose aromatase, SHBG, ERa/PR-B balance) and the PI3K/PTEN oncogenic
axis to the TCGA molecular class, and from molecular class through a single
continuous tumour-mutational-burden -> neoantigen -> T-cell-priming Hill
function to checkpoint-inhibitor efficacy. Includes mechanistic PK/PD for
carboplatin, paclitaxel, anti-PD-1 (dostarlimab/pembrolizumab), lenvatinib,
progestin (megestrol / levonorgestrel IUS), everolimus and letrozole, plus
Friberg myelosuppression, lenvatinib hypertension, and RECIST/PFS endpoints.

[PLUGIN] Rcpp

[PARAM] @annotated
//--------------------------------------------------------------------------
// PATIENT / TUMOUR PHENOTYPE
//--------------------------------------------------------------------------
MOLCLASS   : 2     : TCGA class 1=POLEmut 2=MMRd/MSI-H 3=NSMP/CN-low 4=p53abn/CN-high
TMB_OVR    : 0     : mut/Mb override; >0 overrides the class-default TMB (continuous-axis scenarios)
BMI        : 34    : kg/m2, body mass index (drives adipose aromatase capacity)
POSTMENO   : 1     : 1 = postmenopausal (ovarian E2 negligible), 0 = premenopausal
ERPR_POS   : 1     : 1 = ER+/PR+ by IHC (hormonal-therapy candidate), 0 = ER-/PR-
HER2_AMP   : 0     : 1 = ERBB2 amplified (serous subset, trastuzumab candidate)
HER2_TX    : 0     : 1 = trastuzumab on board (only active when HER2_AMP = 1)
HER2_DRIVE : 0.45  : added PI3K/RAS pathway drive contributed by HER2 amplification
HER2_BLOCK : 0.85  : fractional HER2 signal blockade achieved by trastuzumab
K_HER2KILL : 0.022 : 1/day, trastuzumab ADCC-mediated tumour kill (HER2-amplified only)
TUM0       : 60    : mm, baseline RECIST sum of target-lesion diameters
RESFRAC0   : 0.02  : baseline fraction of tumour that is intrinsically chemo-resistant
GRADE      : 2     : FIGO grade 1-3 (proliferative index scaling)
B2M_LOSS   : 0     : 1 = beta-2-microglobulin loss (antigen-presentation escape)

//--------------------------------------------------------------------------
// TMB AXIS — class-default mutational burdens (mut/Mb, TCGA/literature)
//--------------------------------------------------------------------------
TMB_POLE   : 140   : mut/Mb, POLE exonuclease-domain ultramutated
TMB_MMRD   : 25    : mut/Mb, MMR-deficient hypermutated (range 18-40)
TMB_NSMP   : 2.9   : mut/Mb, no-specific-molecular-profile / copy-number-low
TMB_P53    : 2.3   : mut/Mb, p53-abnormal / copy-number-high
TMB50      : 13    : mut/Mb, TMB producing half-maximal immunogenicity (Hill C50)
HILL_TMB   : 1.4   : Hill coefficient of the TMB -> immunogenicity relationship
FS_WEIGHT  : 0.35  : extra per-mutation immunogenicity of MSI frameshift indels

//--------------------------------------------------------------------------
// CARBOPLATIN PK (AUC 5-6 Calvert; CL ~ GFR + 25 mL/min)
//--------------------------------------------------------------------------
CL_CARB    : 144   : L/day, carboplatin clearance (~6 L/h)
V_CARB     : 16    : L, carboplatin volume of distribution
EMAX_CARB  : 0.24  : 1/day, maximal carboplatin-induced tumour kill rate
EC50_CARB  : 6.0   : mg/L, carboplatin concentration for half-maximal kill

//--------------------------------------------------------------------------
// PACLITAXEL PK (175 mg/m2 3-h infusion, 2-compartment)
//--------------------------------------------------------------------------
CL_PTX     : 520   : L/day, paclitaxel clearance
V1_PTX     : 10.5  : L, paclitaxel central volume
V2_PTX     : 300   : L, paclitaxel peripheral volume
Q_PTX      : 960   : L/day, paclitaxel intercompartmental clearance
EMAX_PTX   : 0.21  : 1/day, maximal paclitaxel-induced tumour kill rate
EC50_PTX   : 0.05  : mg/L, paclitaxel concentration for half-maximal kill
SYN_CP     : 0.25  : fractional supra-additive synergy of the carbo-taxol doublet
CHS_POLE   : 0.85  : relative chemosensitivity, POLEmut class
CHS_MMRD   : 0.90  : relative chemosensitivity, MMRd class (relatively platinum-refractory)
CHS_NSMP   : 1.00  : relative chemosensitivity, NSMP class (reference)
CHS_P53    : 1.55  : relative chemosensitivity, p53abn (G1 checkpoint loss -> mitotic catastrophe)

//--------------------------------------------------------------------------
// ANTI-PD-1 mAb PK (dostarlimab 500 mg q3w x4 -> 1000 mg q6w; pembrolizumab 200 mg q3w)
//--------------------------------------------------------------------------
CL_IO      : 0.21  : L/day, anti-PD-1 IgG4 linear clearance
V1_IO      : 3.6   : L, anti-PD-1 central volume
V2_IO      : 4.1   : L, anti-PD-1 peripheral volume
Q_IO       : 0.79  : L/day, anti-PD-1 intercompartmental clearance
IC50_IO    : 0.35  : mg/L, concentration giving 50% PD-1 receptor occupancy
EMAX_IO    : 0.97  : maximal achievable PD-1 pathway blockade

//--------------------------------------------------------------------------
// LENVATINIB PK/PD (20 mg PO daily; multikinase VEGFR1-3/FGFR1-4/PDGFRa/RET/KIT)
//--------------------------------------------------------------------------
KA_LEN     : 12    : 1/day, lenvatinib absorption rate constant
CLF_LEN    : 158   : L/day, lenvatinib apparent clearance (CL/F ~6.6 L/h)
VF_LEN     : 51    : L, lenvatinib apparent volume
IC50_VEGFR : 0.055 : mg/L, lenvatinib concentration for 50% VEGFR-2 inhibition
IC50_FGFR  : 0.11  : mg/L, lenvatinib concentration for 50% FGFR inhibition
LEN_MDSC   : 0.45  : max fractional MDSC suppression by lenvatinib
LEN_NORM   : 0.55  : max vascular-normalisation boost to T-cell infiltration
K_SBP_LEN  : 26    : mmHg, maximal lenvatinib-induced systolic BP rise

//--------------------------------------------------------------------------
// PROGESTIN (megestrol acetate 160-320 mg PO, or levonorgestrel IUS local)
//--------------------------------------------------------------------------
KA_PRG     : 10    : 1/day, oral progestin absorption rate constant
CLF_PRG    : 130   : L/day, apparent progestin clearance
VF_PRG     : 260   : L, apparent progestin volume
LOCAL_IUS  : 0     : 1 = levonorgestrel IUS (high local endometrial exposure, low systemic)
IUS_FACTOR : 3000  : local endometrial:plasma concentration ratio for the LNG-IUS route
EC50_PRG   : 0.35  : mg/L (route-adjusted), progestin concentration for half-maximal PR agonism
EMAX_PRG   : 0.85  : maximal PR-mediated suppression of ERa transcriptional output
K_PRGKILL  : 0.055 : 1/day, maximal direct progestin-induced tumour regression rate
K_PRDOWN   : 0.011 : 1/day, chronic-progestin PR-B down-regulation rate (acquired resistance)
K_PRUP     : 0.006 : 1/day, PR-B recovery rate off progestin
TAM_PULSE  : 0     : 1 = tamoxifen alternation (re-induces PR-B expression, GOG-153)
K_TAM_PR   : 0.014 : 1/day, tamoxifen-driven PR-B re-induction rate

//--------------------------------------------------------------------------
// LETROZOLE / EVEROLIMUS
//--------------------------------------------------------------------------
KA_LTZ     : 8     : 1/day, letrozole absorption rate constant
CLF_LTZ    : 53    : L/day, letrozole apparent clearance
VF_LTZ     : 130   : L, letrozole apparent volume
IC50_LTZ   : 0.020 : mg/L, letrozole concentration for 50% aromatase inhibition
EMAX_LTZ   : 0.98  : maximal aromatase inhibition (letrozole is near-complete)
KA_EVE     : 12    : 1/day, everolimus absorption rate constant
CLF_EVE    : 588   : L/day, everolimus apparent clearance
VF_EVE     : 480   : L, everolimus apparent volume
IC50_EVE   : 0.008 : mg/L, everolimus concentration for 50% mTORC1 inhibition
EMAX_EVE   : 0.88  : maximal mTORC1 inhibition

//--------------------------------------------------------------------------
// ENDOCRINE AXIS
//--------------------------------------------------------------------------
KSYN_E2    : 42    : pmol/L/day, baseline systemic estradiol appearance rate
KEL_E2     : 1.4   : 1/day, estradiol elimination rate
AROM_SLOPE : 0.060 : fractional aromatase capacity gain per BMI unit above 22
PREMENO_E2 : 3.2   : multiplier on E2 appearance if premenopausal
EC50_ER    : 55    : pmol/L, free estradiol for half-maximal ERa activation
KOUT_ER    : 0.9   : 1/day, ERa transcriptional-activity turnover
W_LIGIND   : 0.45  : weight of mTOR/ERK-driven ligand-independent ERa activation
PR0        : 1.0   : baseline PR-B expression (fraction, ER+/PR+ tumour)

//--------------------------------------------------------------------------
// PI3K/AKT/mTOR AXIS
//--------------------------------------------------------------------------
PI3K_BASE  : 0.30  : basal PI3K/AKT/mTOR pathway activity (no driver lesion)
PTEN_HIT   : 0.45  : added pathway activity from PTEN/PIK3CA/PIK3R1 lesions
KOUT_PI3K  : 1.2   : 1/day, PI3K pathway signal turnover
W_ER_PI3K  : 0.20  : ERa contribution to PI3K pathway drive (IGF-1 autocrine loop)

//--------------------------------------------------------------------------
// TUMOUR GROWTH
//--------------------------------------------------------------------------
KG_TUM     : 0.0109 : 1/day, intrinsic tumour growth rate constant
TUM_MAX    : 400    : mm, carrying capacity of the RECIST sum
W_ER_GROW  : 0.55   : ERa contribution to proliferative drive
W_PI3K_GROW: 1.15   : PI3K/AKT/mTOR contribution to proliferative drive
GRADE_SLOPE: 0.18   : proliferative-drive gain per FIGO grade above 1
AGG_POLE   : 0.85   : intrinsic proliferative aggressiveness, POLEmut class
AGG_MMRD   : 0.95   : intrinsic proliferative aggressiveness, MMRd class
AGG_NSMP   : 1.00   : intrinsic proliferative aggressiveness, NSMP class (reference)
AGG_P53    : 1.35   : intrinsic proliferative aggressiveness, p53abn (p53 checkpoint loss + CCNE1)
K_RESEMERGE: 0.0022 : 1/day, rate of chemo-resistant subclone emergence under drug pressure
KG_RES_REL : 0.92   : growth-rate of the resistant clone relative to the sensitive clone
PERF_FLOOR : 0.35   : minimum perfusion-limited growth support at MVD -> 0

//--------------------------------------------------------------------------
// IMMUNITY
//--------------------------------------------------------------------------
KIN_NEO    : 0.45  : 1/day, neoantigen release rate scalar (per unit immunogenicity)
KOUT_NEO   : 0.35  : 1/day, neoantigen clearance / tolerisation rate
KPRIME     : 0.55  : 1/day, maximal CD8 priming rate from presented neoantigen
NEO50      : 0.50  : neoantigen units for half-maximal priming
KDEATH_T   : 0.10  : 1/day, baseline CD8 effector loss rate
K_EXH      : 0.22  : 1/day, PD-1-driven exhaustion rate (blocked by anti-PD-1)
K_REINVIG  : 0.09  : 1/day, reinvigoration of exhausted cells under PD-1 blockade
KOUT_TEXH  : 0.12  : 1/day, terminal loss of exhausted T cells
KIN_TREG   : 0.10  : 1/day, Treg influx (TGF-b / VEGF driven)
KOUT_TREG  : 0.09  : 1/day, Treg turnover
KIN_MDSC   : 0.13  : 1/day, MDSC influx (VEGF / hypoxia driven)
KOUT_MDSC  : 0.11  : 1/day, MDSC turnover
SUP_TREG   : 0.55  : Treg suppressive weight on CD8 effector function
SUP_MDSC   : 0.40  : MDSC suppressive weight on CD8 effector function
KKILL_IMM  : 0.062 : 1/day, maximal immune-mediated tumour kill rate
KM_TEFF    : 1.10  : CD8 effector density for half-maximal immune kill
EXCL_P53   : 0.45  : immune-exclusion penalty in the p53abn/CN-high class
EXCL_BASE  : 0.12  : baseline immune-exclusion (stromal/TGF-b) in other classes
OBES_TCELL : 0.010 : fractional CD8 functional loss per BMI unit above 30
ICD_CHEMO  : 0.30  : immunogenic-cell-death boost to neoantigen release from platinum

//--------------------------------------------------------------------------
// ANGIOGENESIS
//--------------------------------------------------------------------------
KIN_VEGF   : 0.55  : 1/day, VEGF-A production scalar (hypoxia + mTOR driven)
KOUT_VEGF  : 0.50  : 1/day, VEGF-A clearance
KIN_MVD    : 0.09  : 1/day, microvessel formation rate
KOUT_MVD   : 0.08  : 1/day, microvessel regression rate
W_FGF_ESC  : 0.30  : FGF-driven escape angiogenesis fraction (lenvatinib also blocks this)

//--------------------------------------------------------------------------
// BIOMARKERS
//--------------------------------------------------------------------------
CA125_BASE : 12    : U/mL, baseline serum CA-125
K_CA125    : 1.30  : U/mL per mm of tumour burden
SEROUS_CA  : 2.2   : CA-125 shedding multiplier in the p53abn/serous class
KOUT_CA125 : 0.14  : 1/day, CA-125 elimination (t1/2 ~5 days)
K_CTDNA    : 0.022 : %VAF per mm of tumour burden
KOUT_CTDNA : 4.0   : 1/day, ctDNA clearance (t1/2 ~ hours)

//--------------------------------------------------------------------------
// FRIBERG MYELOSUPPRESSION
//--------------------------------------------------------------------------
CIRC0      : 4.5   : 10^9/L, baseline absolute neutrophil count
MTT_NEUT   : 125   : hours, mean transit time through the maturation chain
GAMMA_FB   : 0.16  : rebound/feedback exponent
SLOPE_CARB : 0.055 : L/mg, carboplatin myelosuppression slope
SLOPE_PTX  : 3.6   : L/mg, paclitaxel myelosuppression slope

//--------------------------------------------------------------------------
// TOXICITY / OUTCOME
//--------------------------------------------------------------------------
SBP0       : 128   : mmHg, baseline systolic blood pressure
KOUT_SBP   : 0.35  : 1/day, blood-pressure equilibration rate
H0_HAZ     : 0.0016 : 1/day, hazard at the reference tumour burden
HAZ_REF    : 60     : mm, reference tumour burden the hazard is normalised to
GAMMA_HAZ  : 1.35   : exponent linking relative tumour burden to hazard

[CMT] @annotated
CARB_C  : Carboplatin central amount (mg)
PTX_C   : Paclitaxel central amount (mg)
PTX_P   : Paclitaxel peripheral amount (mg)
IO_C    : Anti-PD-1 mAb central amount (mg)
IO_P    : Anti-PD-1 mAb peripheral amount (mg)
LEN_G   : Lenvatinib gut depot (mg)
LEN_C   : Lenvatinib central amount (mg)
PRG_G   : Progestin depot (mg; oral gut or IUS reservoir)
PRG_C   : Progestin central amount (mg)
LTZ_G   : Letrozole gut depot (mg)
LTZ_C   : Letrozole central amount (mg)
EVE_G   : Everolimus gut depot (mg)
EVE_C   : Everolimus central amount (mg)
E2      : Free estradiol (pmol/L)
ER_ACT  : ERa transcriptional activity (0-1)
PR_EXP  : PR-B receptor expression (fraction of baseline)
PI3K_A  : PI3K/AKT/mTOR pathway activity (0-1)
TUM_S   : Sensitive tumour burden (mm of RECIST sum)
TUM_R   : Resistant tumour burden (mm of RECIST sum)
NEO     : Presentable neoantigen load (normalised)
TEFF    : Intratumoral CD8 effector density (normalised)
TEXH    : Exhausted CD8 T-cell density (normalised)
TREG    : Regulatory T-cell density (normalised)
MDSC    : Myeloid-derived suppressor cell density (normalised)
VEGF    : VEGF-A level (normalised)
MVD     : Microvessel density / perfusion (normalised, baseline 1)
CA125   : Serum CA-125 (U/mL)
CTDNA   : Circulating tumour DNA (%VAF)
PROL    : Friberg proliferating neutrophil precursors (10^9/L)
TR1     : Friberg transit compartment 1 (10^9/L)
TR2     : Friberg transit compartment 2 (10^9/L)
TR3     : Friberg transit compartment 3 (10^9/L)
CIRC    : Circulating absolute neutrophil count (10^9/L)
SBP     : Systolic blood pressure (mmHg)
HAZ     : Cumulative progression/death hazard (dimensionless)

[GLOBAL]
#define CP_CARB  (CARB_C / V_CARB)
#define CP_PTX   (PTX_C  / V1_PTX)
#define CP_IO    (IO_C   / V1_IO)
#define CP_LEN   (LEN_C  / VF_LEN)
#define CP_LTZ   (LTZ_C  / VF_LTZ)
#define CP_EVE   (EVE_C  / VF_EVE)

// Values fixed once per subject in [MAIN] and read inside [ODE]
double TMBv;        // effective tumour mutational burden (mut/Mb)
double IMMUNv;      // TMB -> immunogenicity Hill output (0-1)
double AROMv;       // adipose aromatase capacity multiplier
double PTENv;       // PI3K driver-lesion contribution
double EXCLv;       // immune-exclusion penalty (class-dependent)
double HER2v;       // residual HER2-driven pathway contribution after trastuzumab
double PRODRIVE;    // proliferative-drive grade multiplier
double AGGRv;       // class-specific intrinsic proliferative aggressiveness
double CHEMOSv;     // class-specific relative chemosensitivity
double CA_MULT;     // CA-125 shedding multiplier
double APCv;        // antigen-presentation competence (B2M loss)
double KTR_FB;      // Friberg transit rate constant (1/day)
double TUMBASE;     // baseline total tumour burden (mm)

[MAIN]
//---------------------------------------------------------------------------
// 1. THE TMB AXIS — the single continuous variable this model is organised on
//---------------------------------------------------------------------------
if (TMB_OVR > 0) {
  TMBv = TMB_OVR;                       // continuous-axis / TMB-guided scenarios
} else if (MOLCLASS < 1.5) {
  TMBv = TMB_POLE;                      // POLEmut  — ultramutated
} else if (MOLCLASS < 2.5) {
  TMBv = TMB_MMRD;                      // MMRd     — hypermutated
} else if (MOLCLASS < 3.5) {
  TMBv = TMB_NSMP;                      // NSMP     — copy-number-low
} else {
  TMBv = TMB_P53;                       // p53abn   — copy-number-high
}

// MSI frameshift indels are more immunogenic PER MUTATION than POLE-driven
// SNVs (indel neoantigens are wholly non-self across their reading frame),
// so the MMRd class gets an effective-TMB uplift rather than a separate curve.
double tmb_eff = TMBv * (1.0 + FS_WEIGHT * ((MOLCLASS > 1.5 && MOLCLASS < 2.5) ? 1.0 : 0.0));

// THE central equation: a saturating Hill function of mutational burden.
// TMB50 = 13 mut/Mb lands almost exactly on the clinical dMMR/pMMR boundary —
// the binary biomarker works because the cut sits on the steepest part of a
// continuum, which is also why borderline tumours must be misclassified.
IMMUNv = pow(tmb_eff, HILL_TMB) / (pow(TMB50, HILL_TMB) + pow(tmb_eff, HILL_TMB));

// Antigen-presentation competence: B2M loss uncouples TMB from visibility.
APCv = B2M_LOSS > 0.5 ? 0.15 : 1.0;

//---------------------------------------------------------------------------
// 2. Host endocrine / phenotype modifiers
//---------------------------------------------------------------------------
AROMv    = 1.0 + AROM_SLOPE * fmax(BMI - 22.0, 0.0);   // adipose aromatase capacity
PTENv    = (MOLCLASS > 2.5 && MOLCLASS < 3.5) ? PTEN_HIT
         : (MOLCLASS < 2.5 ? 0.85 * PTEN_HIT : 0.40 * PTEN_HIT);
EXCLv    = (MOLCLASS > 3.5) ? EXCL_P53 : EXCL_BASE;

// HER2: amplification adds pathway drive; trastuzumab removes most of it.
// Fader 2018 showed the benefit is confined to the HER2-amplified serous
// subset, so the term is gated on HER2_AMP and vanishes without it.
HER2v    = (HER2_AMP > 0.5)
         ? HER2_DRIVE * (1.0 - HER2_BLOCK * (HER2_TX > 0.5 ? 1.0 : 0.0))
         : 0.0;

PRODRIVE = 1.0 + GRADE_SLOPE * fmax(GRADE - 1.0, 0.0);

// Intrinsic aggressiveness is NOT the same variable as immunogenicity. p53abn
// is the most aggressive class (p53 checkpoint loss, CCNE1 amplification)
// AND the least immunogenic; POLEmut is the least aggressive AND the most
// immunogenic. Conflating the two would make the model unable to say which
// of the two effects drives the prognostic gap.
AGGRv    = (MOLCLASS < 1.5) ? AGG_POLE
         : (MOLCLASS < 2.5) ? AGG_MMRD
         : (MOLCLASS < 3.5) ? AGG_NSMP : AGG_P53;

// Chemosensitivity is a THIRD independent class axis, and it runs the opposite
// way from immunogenicity: losing the p53 G1 checkpoint lets damaged cells
// enter S and M phase, so the class that responds worst to checkpoint blockade
// responds BEST to platinum/taxane. This is the mechanistic content of the
// PORTEC-3 molecular analysis, in which the adjuvant chemoradiotherapy benefit
// was concentrated in p53abn while POLEmut did well regardless of treatment.
CHEMOSv  = (MOLCLASS < 1.5) ? CHS_POLE
         : (MOLCLASS < 2.5) ? CHS_MMRD
         : (MOLCLASS < 3.5) ? CHS_NSMP : CHS_P53;
CA_MULT  = (MOLCLASS > 3.5) ? SEROUS_CA : 1.0;
KTR_FB   = 4.0 / (MTT_NEUT / 24.0);                    // hours -> 1/day
TUMBASE  = TUM0;

//---------------------------------------------------------------------------
// 3. Initial conditions
//---------------------------------------------------------------------------
double e2_ss = (KSYN_E2 * AROMv * (POSTMENO > 0.5 ? 1.0 : PREMENO_E2)) / KEL_E2;
E2_0     = e2_ss;
ER_ACT_0 = ERPR_POS > 0.5 ? e2_ss / (EC50_ER + e2_ss) : 0.05;
PR_EXP_0 = ERPR_POS > 0.5 ? PR0 : 0.05;
PI3K_A_0 = fmin(1.0, PI3K_BASE + PTENv + HER2v);

TUM_S_0  = TUM0 * (1.0 - RESFRAC0);
TUM_R_0  = TUM0 * RESFRAC0;

// Pre-treatment immune steady state — the untreated tumour has already
// reached an equilibrium between neoantigen-driven priming and suppression.
NEO_0    = (KIN_NEO * IMMUNv * APCv) / KOUT_NEO;
TREG_0   = 1.0;
MDSC_0   = 1.0;
// Initialise the T-cell compartments at the UNTREATED steady state rather
// than at an arbitrary "hot vs cold" guess. The tumour is clinically
// detectable precisely because priming and suppression have already reached
// an equilibrium the tumour wins; treatment has to move that equilibrium.
// A consequence worth stating: the exhausted-cell pool at diagnosis scales
// with prior antigen exposure, so a high-TMB tumour arrives with a LARGER
// reservoir of reinvigoratable cells — which is a second, independent reason
// checkpoint blockade works better there, on top of ongoing priming.
double prime_ss = KPRIME * NEO_0 / (NEO50 + NEO_0);
double obes_ss  = fmin(0.45, OBES_TCELL * fmax(BMI - 30.0, 0.0));
double supp_ss  = SUP_TREG * 1.0 + SUP_MDSC * 1.0;
TEFF_0   = prime_ss * (1.0 - obes_ss) / (K_EXH + KDEATH_T + 0.06 * supp_ss);
TEXH_0   = K_EXH * TEFF_0 / KOUT_TEXH;
VEGF_0   = 1.0;
MVD_0    = 1.0;

CA125_0  = CA125_BASE + K_CA125 * CA_MULT * TUM0;
CTDNA_0  = K_CTDNA * TUM0;

PROL_0   = CIRC0;
TR1_0    = CIRC0;
TR2_0    = CIRC0;
TR3_0    = CIRC0;
CIRC_0   = CIRC0;
SBP_0    = SBP0;
HAZ_0    = 0.0;

[ODE]
//===========================================================================
// A. PHARMACOKINETICS
//===========================================================================
dxdt_CARB_C = -(CL_CARB / V_CARB) * CARB_C;

dxdt_PTX_C  = -(CL_PTX / V1_PTX) * PTX_C
              - (Q_PTX / V1_PTX) * PTX_C + (Q_PTX / V2_PTX) * PTX_P;
dxdt_PTX_P  =  (Q_PTX / V1_PTX) * PTX_C - (Q_PTX / V2_PTX) * PTX_P;

dxdt_IO_C   = -(CL_IO / V1_IO) * IO_C
              - (Q_IO / V1_IO) * IO_C + (Q_IO / V2_IO) * IO_P;
dxdt_IO_P   =  (Q_IO / V1_IO) * IO_C - (Q_IO / V2_IO) * IO_P;

dxdt_LEN_G  = -KA_LEN * LEN_G;
dxdt_LEN_C  =  KA_LEN * LEN_G - (CLF_LEN / VF_LEN) * LEN_C;

dxdt_PRG_G  = -KA_PRG * PRG_G;
dxdt_PRG_C  =  KA_PRG * PRG_G - (CLF_PRG / VF_PRG) * PRG_C;

dxdt_LTZ_G  = -KA_LTZ * LTZ_G;
dxdt_LTZ_C  =  KA_LTZ * LTZ_G - (CLF_LTZ / VF_LTZ) * LTZ_C;

dxdt_EVE_G  = -KA_EVE * EVE_G;
dxdt_EVE_C  =  KA_EVE * EVE_G - (CLF_EVE / VF_EVE) * EVE_C;

//===========================================================================
// B. DRUG EFFECT SITES
//===========================================================================
// Progestin: the levonorgestrel IUS delivers a high LOCAL endometrial
// concentration from a low systemic one — the entire rationale for the
// fertility-sparing route. Modelled as a route-dependent effect-site
// multiplier rather than a separate compartment.
double prg_eff_conc = (PRG_C / VF_PRG) * (LOCAL_IUS > 0.5 ? IUS_FACTOR : 1.0);
double PRG_occ  = prg_eff_conc / (EC50_PRG + prg_eff_conc);      // PR occupancy
double PRG_act  = EMAX_PRG * PRG_occ * PR_EXP;                   // requires PR-B to be present

double LTZ_inh  = EMAX_LTZ * CP_LTZ / (IC50_LTZ + CP_LTZ);       // aromatase blockade
double EVE_inh  = EMAX_EVE * CP_EVE / (IC50_EVE + CP_EVE);       // mTORC1 blockade
double PD1_blk  = EMAX_IO  * CP_IO  / (IC50_IO  + CP_IO);        // PD-1 pathway blockade
double VEGFR_i  = CP_LEN / (IC50_VEGFR + CP_LEN);                // VEGFR-2 inhibition
double FGFR_i   = CP_LEN / (IC50_FGFR  + CP_LEN);                // FGFR inhibition

//===========================================================================
// C. ENDOCRINE AXIS — unopposed oestrogen and its opposition
//===========================================================================
double e2_in = KSYN_E2 * AROMv * (POSTMENO > 0.5 ? 1.0 : PREMENO_E2) * (1.0 - LTZ_inh);
dxdt_E2 = e2_in - KEL_E2 * E2;

// ERa activity has TWO inputs: ligand (E2) and ligand-INDEPENDENT activation
// by mTOR/ERK phosphorylation of ERa Ser167/118. The second term is why
// everolimus restores letrozole sensitivity (Slomovitz 2015) and why an
// aromatase inhibitor alone underperforms in a PI3K-driven tumour.
double er_ligand = E2 / (EC50_ER + E2);
double er_target = ERPR_POS > 0.5
                 ? fmin(1.0, er_ligand + W_LIGIND * PI3K_A * (1.0 - EVE_inh)) * (1.0 - PRG_act)
                 : 0.05;
dxdt_ER_ACT = KOUT_ER * (er_target - ER_ACT);

// PR-B expression: down-regulated by sustained progestin occupancy (the
// mechanism of acquired hormonal resistance in fertility-sparing therapy),
// re-induced by tamoxifen alternation (GOG-153) and by ERa signalling itself
// (PGR is an oestrogen target gene), recovering slowly off drug.
double pr_max = ERPR_POS > 0.5 ? PR0 : 0.05;
dxdt_PR_EXP = -K_PRDOWN * PRG_occ * PR_EXP
              + K_PRUP  * (pr_max - PR_EXP)
              + K_TAM_PR * TAM_PULSE * (pr_max - PR_EXP)
              + 0.004 * ER_ACT * (pr_max - PR_EXP);

//===========================================================================
// D. PI3K/AKT/mTOR
//===========================================================================
double pi3k_target = fmin(1.0, (PI3K_BASE + PTENv + HER2v + W_ER_PI3K * ER_ACT)
                               * (1.0 - EVE_inh));
dxdt_PI3K_A = KOUT_PI3K * (pi3k_target - PI3K_A);

//===========================================================================
// E. ANGIOGENESIS AND PERFUSION
//===========================================================================
double TUM_TOT = TUM_S + TUM_R;
double hypoxia = TUM_TOT / (TUM_TOT + 80.0 * MVD);   // burden per unit perfusion
dxdt_VEGF = KIN_VEGF * (hypoxia + 0.45 * PI3K_A) - KOUT_VEGF * VEGF;

// Lenvatinib blocks BOTH the VEGF axis and the FGF escape route — the FGFR
// arm is why it outperforms a pure anti-VEGF agent in this setting.
double angio_drive = VEGF * (1.0 - VEGFR_i) + W_FGF_ESC * (1.0 - FGFR_i);
dxdt_MVD = KIN_MVD * angio_drive - KOUT_MVD * MVD;

double perfusion = fmax(PERF_FLOOR, fmin(1.6, MVD));

// Vascular normalisation: partial VEGFR inhibition IMPROVES T-cell delivery
// even as it reduces vessel density. Peaks at intermediate inhibition.
double vasc_norm = 1.0 + LEN_NORM * 4.0 * VEGFR_i * (1.0 - VEGFR_i);

//===========================================================================
// F. IMMUNOSUPPRESSIVE COMPARTMENTS
//===========================================================================
dxdt_TREG = KIN_TREG * (0.55 + 0.55 * VEGF) - KOUT_TREG * TREG;
dxdt_MDSC = KIN_MDSC * (0.45 + 0.70 * VEGF) * (1.0 - LEN_MDSC * VEGFR_i)
            - KOUT_MDSC * MDSC;

//===========================================================================
// G. NEOANTIGEN -> PRIMING -> EFFECTOR -> KILL
//===========================================================================
// Platinum adds immunogenic cell death on top of the constitutive,
// TMB-determined neoantigen supply.
double chemo_kill_rate = EMAX_CARB * CP_CARB / (EC50_CARB + CP_CARB)
                       + EMAX_PTX  * CP_PTX  / (EC50_PTX  + CP_PTX);
double doublet = CHEMOSv * chemo_kill_rate * (1.0 + SYN_CP
                 * (CP_CARB / (EC50_CARB + CP_CARB)) * (CP_PTX / (EC50_PTX + CP_PTX)));

double icd = ICD_CHEMO * (CP_CARB / (EC50_CARB + CP_CARB));
dxdt_NEO = KIN_NEO * IMMUNv * APCv * (1.0 + icd) * (TUM_TOT / fmax(TUMBASE, 1.0))
           - KOUT_NEO * NEO;

double priming = KPRIME * NEO / (NEO50 + NEO);

// Suppression: Treg + MDSC + the obesity penalty on T-cell metabolic fitness.
double obes_pen = fmin(0.45, OBES_TCELL * fmax(BMI - 30.0, 0.0));
double suppression = SUP_TREG * TREG + SUP_MDSC * MDSC;

dxdt_TEFF = priming * vasc_norm * (1.0 - obes_pen)
            - K_EXH * (1.0 - PD1_blk) * TEFF
            + K_REINVIG * PD1_blk * TEXH
            - KDEATH_T * TEFF
            - 0.06 * suppression * TEFF;

dxdt_TEXH = K_EXH * (1.0 - PD1_blk) * TEFF
            - K_REINVIG * PD1_blk * TEXH
            - KOUT_TEXH * TEXH;

// Immune kill: saturating in effector density, gated by immune exclusion.
// This is where the whole TMB axis cashes out into tumour shrinkage.
double immune_kill = KKILL_IMM * (TEFF / (KM_TEFF + TEFF)) * (1.0 - EXCLv);

//===========================================================================
// H. TUMOUR DYNAMICS
//===========================================================================
double growth_drive = PRODRIVE * AGGRv
                    * (1.0 + W_ER_GROW * ER_ACT + W_PI3K_GROW * PI3K_A)
                    * perfusion;
double space = fmax(0.0, 1.0 - TUM_TOT / TUM_MAX);

// Direct progestin cytostatic/differentiating effect — requires PR-B, which
// is exactly what chronic progestin exposure erodes.
double prg_kill = K_PRGKILL * PRG_act;

// Trastuzumab acts twice: it removes HER2 pathway drive (via HER2v, above)
// AND recruits NK-cell ADCC. Both terms are gated on HER2 amplification, so
// the drug does nothing at all in a HER2-normal tumour — which is the whole
// finding of Fader 2018.
double her2_kill = (HER2_AMP > 0.5 && HER2_TX > 0.5) ? K_HER2KILL : 0.0;

dxdt_TUM_S = KG_TUM * growth_drive * space * TUM_S
             - doublet * TUM_S
             - immune_kill * TUM_S
             - prg_kill * TUM_S
             - her2_kill * TUM_S
             - K_RESEMERGE * doublet * TUM_S;

dxdt_TUM_R = KG_RES_REL * KG_TUM * growth_drive * space * TUM_R
             + K_RESEMERGE * doublet * TUM_S
             - immune_kill * TUM_R          // immunity still sees the resistant clone
             - 0.25 * prg_kill * TUM_R
             - her2_kill * TUM_R;

//===========================================================================
// I. BIOMARKERS
//===========================================================================
dxdt_CA125 = KOUT_CA125 * (CA125_BASE + K_CA125 * CA_MULT * TUM_TOT - CA125);
dxdt_CTDNA = KOUT_CTDNA * (K_CTDNA * TUM_TOT - CTDNA);

//===========================================================================
// J. FRIBERG MYELOSUPPRESSION (carboplatin + paclitaxel)
//===========================================================================
double edrug = fmin(0.95, SLOPE_CARB * CP_CARB + SLOPE_PTX * CP_PTX);
double fb    = pow(CIRC0 / fmax(CIRC, 0.05), GAMMA_FB);
dxdt_PROL = KTR_FB * PROL * (1.0 - edrug) * fb - KTR_FB * PROL;
dxdt_TR1  = KTR_FB * (PROL - TR1);
dxdt_TR2  = KTR_FB * (TR1  - TR2);
dxdt_TR3  = KTR_FB * (TR2  - TR3);
dxdt_CIRC = KTR_FB * (TR3  - CIRC);

//===========================================================================
// K. LENVATINIB HYPERTENSION (the dose-limiting toxicity in KEYNOTE-775)
//===========================================================================
dxdt_SBP = KOUT_SBP * (SBP0 + K_SBP_LEN * VEGFR_i - SBP);

//===========================================================================
// L. HAZARD ACCUMULATOR -> PFS/OS surrogate
//===========================================================================
// Normalised to a FIXED reference burden, not to this subject's baseline:
// otherwise an adjuvant run started at 8 mm and a metastatic run started at
// 100 mm would report the same hazard at the same relative change, which is
// exactly backwards.
dxdt_HAZ = H0_HAZ * pow(fmax(TUM_TOT, 1.0) / HAZ_REF, GAMMA_HAZ);

[TABLE]
double TUMTOT_o = TUM_S + TUM_R;

capture Molecular_class      = MOLCLASS;
capture TMB_mutMb            = TMBv;
capture Immunogenicity       = IMMUNv;
capture Carboplatin_conc     = CP_CARB;
capture Paclitaxel_conc      = CP_PTX;
capture AntiPD1_conc         = CP_IO;
capture PD1_blockade         = EMAX_IO * CP_IO / (IC50_IO + CP_IO);
capture Lenvatinib_conc      = CP_LEN;
capture VEGFR2_inhibition    = CP_LEN / (IC50_VEGFR + CP_LEN);
capture Letrozole_conc       = CP_LTZ;
capture Everolimus_conc      = CP_EVE;
capture Estradiol_free       = E2;
capture ERa_activity         = ER_ACT;
capture PRB_expression       = PR_EXP;
capture PI3K_activity        = PI3K_A;
capture HER2_residual_drive  = HER2v;
capture Chemosensitivity     = CHEMOSv;
capture Aggressiveness       = AGGRv;
capture Tumor_total_mm       = TUMTOT_o;
capture Tumor_sensitive_mm   = TUM_S;
capture Tumor_resistant_mm   = TUM_R;
capture Pct_change_baseline  = 100.0 * (TUMTOT_o - TUMBASE) / fmax(TUMBASE, 1.0);
capture Neoantigen_load      = NEO;
capture CD8_effector         = TEFF;
capture CD8_exhausted        = TEXH;
capture Treg_density         = TREG;
capture MDSC_density         = MDSC;
capture VEGFA_level          = VEGF;
capture Microvessel_density  = MVD;
capture CA125_UmL            = CA125;
capture ctDNA_VAF            = CTDNA;
capture ANC_10e9L            = CIRC;
capture SBP_mmHg             = SBP;
capture Survival_fraction    = exp(-HAZ);

[CAPTURE]
Molecular_class TMB_mutMb Immunogenicity
Carboplatin_conc Paclitaxel_conc AntiPD1_conc PD1_blockade
Lenvatinib_conc VEGFR2_inhibition Letrozole_conc Everolimus_conc
Estradiol_free ERa_activity PRB_expression PI3K_activity HER2_residual_drive
Chemosensitivity Aggressiveness
Tumor_total_mm Tumor_sensitive_mm Tumor_resistant_mm Pct_change_baseline
Neoantigen_load CD8_effector CD8_exhausted Treg_density MDSC_density
VEGFA_level Microvessel_density CA125_UmL ctDNA_VAF
ANC_10e9L SBP_mmHg Survival_fraction


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2); library(purrr)
##  mod <- mread_cache("emc_mrgsolve_model.R")
##
##  ## Class codes: 1 = POLEmut, 2 = MMRd/MSI-H, 3 = NSMP, 4 = p53abn
##
##  # ---------- Dosing building blocks ----------
##  CHEMO <- function(cycles = 6) {
##    ev(amt = 625, cmt = "CARB_C", ii = 21, addl = cycles - 1) +     # carbo AUC5
##    ev(amt = 300, cmt = "PTX_C",  ii = 21, addl = cycles - 1)       # paclitaxel 175 mg/m2
##  }
##  DOSTARLIMAB <- function(end_d = 730) {
##    ev(amt = 500,  cmt = "IO_C", ii = 21, addl = 3) +                          # 500 mg q3w x4
##    ev(amt = 1000, cmt = "IO_C", time = 84, ii = 42,
##       addl = max(floor((end_d - 84) / 42), 0))                                # then 1000 mg q6w
##  }
##  PEMBRO <- function(end_d = 730)
##    ev(amt = 200, cmt = "IO_C", ii = 21, addl = max(floor(end_d / 21) - 1, 0))
##  LENVA  <- function(end_d = 730, dose = 20)
##    ev(amt = dose, cmt = "LEN_G", ii = 1, addl = end_d - 1)
##  MEGACE <- function(end_d = 360, dose = 160)
##    ev(amt = dose, cmt = "PRG_G", ii = 1, addl = end_d - 1)
##  LNGIUS <- function(end_d = 360)                       # 52 mg IUS ~ 20 ug/day released
##    ev(amt = 0.020, cmt = "PRG_G", ii = 1, addl = end_d - 1)
##  LETRO  <- function(end_d = 730)
##    ev(amt = 2.5, cmt = "LTZ_G", ii = 1, addl = end_d - 1)
##  EVERO  <- function(end_d = 730)
##    ev(amt = 10,  cmt = "EVE_G", ii = 1, addl = end_d - 1)
##
##  # ---------- 8 prebuilt scenarios ----------
##  EMC_simulate_scenarios <- function(end_d = 730, molclass = 2) {
##
##    sc <- list(
##      "1. Untreated natural history" =
##        list(ev = ev(amt = 0, cmt = "CARB_C"), p = list()),
##
##      "2. Carboplatin-paclitaxel x6 (GOG-0209 reference doublet)" =
##        list(ev = CHEMO(6), p = list()),
##
##      "3. Dostarlimab + chemo, dMMR/MSI-H (RUBY)" =
##        list(ev = CHEMO(6) + DOSTARLIMAB(end_d), p = list(MOLCLASS = 2)),
##
##      "4. Dostarlimab + chemo, pMMR/NSMP (RUBY pMMR subgroup)" =
##        list(ev = CHEMO(6) + DOSTARLIMAB(end_d), p = list(MOLCLASS = 3)),
##
##      "5. Pembrolizumab + lenvatinib, pMMR (KEYNOTE-775)" =
##        list(ev = PEMBRO(end_d) + LENVA(end_d), p = list(MOLCLASS = 3)),
##
##      "6. Fertility-sparing LNG-IUS, grade 1 ER+/PR+ (feMMe)" =
##        list(ev = LNGIUS(min(end_d, 360)),
##             p = list(MOLCLASS = 3, GRADE = 1, TUM0 = 12, POSTMENO = 0,
##                      LOCAL_IUS = 1, ERPR_POS = 1)),
##
##      "7. Letrozole + everolimus (Slomovitz 2015, ORR 32%)" =
##        list(ev = LETRO(end_d) + EVERO(end_d), p = list(MOLCLASS = 3, ERPR_POS = 1)),
##
##      "8. Megestrol continuous vs tamoxifen-alternating (PR down-regulation)" =
##        list(ev = MEGACE(min(end_d, 360)), p = list(MOLCLASS = 3, TAM_PULSE = 1))
##    )
##
##    purrr::imap_dfr(sc, function(s, lab) {
##      p <- s$p; if (is.null(p$MOLCLASS)) p$MOLCLASS <- molclass
##      m <- do.call(param, c(list(mod), p))
##      mrgsim(m, s$ev, end = end_d, delta = 1) |>
##        as_tibble() |> mutate(scenario = lab)
##    })
##  }
##
##  # ---------- The continuous-TMB sweep (the model's central claim) ----------
##  # Holds the DRUG fixed and moves only the mutational burden. The dMMR/pMMR
##  # dichotomy appears as a steep but perfectly smooth stretch of one curve.
##  EMC_tmb_sweep <- function(tmb_grid = c(1, 2, 3, 5, 8, 13, 20, 30, 50, 100, 200),
##                            end_d = 365) {
##    purrr::map_dfr(tmb_grid, function(tt) {
##      mod |> param(TMB_OVR = tt, MOLCLASS = 3) |>
##        mrgsim(DOSTARLIMAB(end_d) + CHEMO(6), end = end_d, delta = 5) |>
##        as_tibble() |> mutate(TMB = tt)
##    })
##  }
##  # df <- EMC_tmb_sweep()
##  # df |> group_by(TMB) |> slice_min(Tumor_total_mm) |>
##  #   ggplot(aes(TMB, Pct_change_baseline)) + geom_line() + scale_x_log10() +
##  #   geom_vline(xintercept = 13, linetype = 2)   # <- where the dichotomy is drawn
##
##  # ---------- Calibration anchors ----------
##  # TCGA (Kandoth 2013 Nature 497:67): four classes with mutation rates spanning
##  #   ~2.3 to >100 mut/Mb; class prevalence POLE 7-12%, MSI 25-30%, CN-low
##  #   30-40%, CN-high 15-25%. Encoded as TMB_POLE/TMB_MMRD/TMB_NSMP/TMB_P53 and
##  #   as class-dependent PTEN/immune-exclusion parameters -- NOT as separate
##  #   efficacy parameters per class. Every therapeutic difference between the
##  #   classes in this model is downstream of the TMB number and the exclusion
##  #   penalty; nothing is tuned per-arm.
##  # RUBY (Mirza 2023 NEJM 388:2145): dostarlimab + carbo/taxol, dMMR/MSI-H
##  #   24-month PFS 61.4% vs 15.7% (HR 0.28); overall population HR 0.64.
##  #   Reproduced by IMMUNv(TMB 25 x 1.35 frameshift uplift) = 0.79 driving a
##  #   large TEFF rise once PD1_blk removes the exhaustion sink.
##  # NRG-GY018 (Eskander 2023 NEJM 388:2159): pembrolizumab + chemo, dMMR
##  #   HR 0.30, pMMR HR 0.54 -- the pMMR benefit is smaller but real, which the
##  #   model gets from the non-zero floor of the Hill curve (IMMUNv ~ 0.11 at
##  #   TMB 2.9) plus platinum immunogenic cell death (ICD_CHEMO) raising NEO
##  #   during chemotherapy. This is the mechanistic reason IO+chemo beats IO
##  #   alone in pMMR while adding little in dMMR.
##  # GARNET (Oaknin 2020 JAMA Oncol 6:1766): dostarlimab MONOtherapy ORR 45.5%
##  #   dMMR vs 15.4% pMMR -- without the chemotherapy ICD term the pMMR arm of
##  #   this model collapses to near-zero benefit, matching the monotherapy data.
##  # KEYNOTE-775 (Makker 2022 NEJM 386:437): lenvatinib + pembrolizumab in
##  #   PREVIOUSLY TREATED, predominantly pMMR disease: mPFS 6.6 vs 3.8 months
##  #   (HR 0.60), mOS 17.4 vs 12.0 months (HR 0.68), ORR ~30%. In this model the
##  #   benefit comes almost entirely from LEN_MDSC (MDSC depletion) and
##  #   LEN_NORM (vascular normalisation boosting T-cell delivery), NOT from
##  #   direct anti-tumour kill -- lenvatinib has no tumour-kill term at all.
##  #   Setting LEN_MDSC = LEN_NORM = 0 abolishes the combination benefit, which
##  #   is the model's testable claim about the mechanism.
##  # PORTEC-3 molecular analysis (Leon-Castillo 2020 JCO 38:3388): adjuvant
##  #   chemoradiotherapy benefit concentrated in p53abn; POLEmut excellent
##  #   outcome regardless of adjuvant therapy. Encoded NOT as an efficacy
##  #   parameter but as CHS_P53 = 1.55: losing the p53 G1 checkpoint lets
##  #   damaged cells enter S/M phase, so the class that responds WORST to
##  #   checkpoint blockade responds BEST to platinum/taxane. Model correlate
##  #   (TUM0 = 8 mm adjuvant setting, 3-year horizon):
##  #     POLEmut  observation 4.8 mm / S 0.93   vs chemo 4.6 mm / S 0.96
##  #     p53abn   observation TTP 18 d           vs chemo TTP 146 d, best -62%
##  #   i.e. POLEmut arms are nearly superimposable (the de-escalation
##  #   rationale, RAINBO POLE-BLUE) while p53abn gains a large delay.
##  #   KNOWN MISMATCH, stated rather than hidden: the model OVER-predicts
##  #   adjuvant chemotherapy benefit in MMRd (observation TTP 238 d vs chemo
##  #   TTP not reached), whereas PORTEC-3 found no significant chemotherapy
##  #   benefit in that subgroup. The cause is structural -- debulking hands
##  #   the residual tumour to an immune compartment that is competent in MMRd,
##  #   so chemotherapy and immunity compound. Reproducing the trial would
##  #   require chemotherapy-induced lymphodepletion, which this model does not
##  #   have.
##  # Slomovitz 2015 JCO 33:930: everolimus + letrozole ORR 32% in recurrent EC,
##  #   substantially better than either agent alone -- the model produces this
##  #   through W_LIGIND: letrozole alone lowers E2 but leaves the mTOR-driven
##  #   ligand-independent ERa term intact, and everolimus removes it.
##  # feMMe / fertility-sparing literature (Westin 2021 AJOG 224:191.e1; Gunderson
##  #   2012 Gynecol Oncol 125:477): LNG-IUS pathological CR ~76-90% in atypical
##  #   hyperplasia and ~57-70% in grade 1 EC, with relapse after progestin
##  #   withdrawal. Model correlate: IUS_FACTOR gives high local exposure at low
##  #   systemic concentration, and K_PRDOWN produces the plateau/escape seen
##  #   around 6-12 months of continuous progestin.
##  # GOG-119 / GOG-153 (Fiorica 2004 Gynecol Oncol 92:10; Whitney 2004 Gynecol
##  #   Oncol 92:4): alternating megestrol/tamoxifen ORR ~27% -- tamoxifen
##  #   re-induces PR expression, encoded as K_TAM_PR. Compare scenario 8 with
##  #   TAM_PULSE = 0 vs 1 to see the PR_EXP trajectory diverge.
##  # Friberg 2002 JCO 20:4713: semi-mechanistic myelosuppression model
##  #   (MTT ~125 h, feedback exponent ~0.16) -- used unchanged.
##  # Lenvatinib hypertension: ~65% all-grade in KEYNOTE-775, the dose-limiting
##  #   toxicity driving the 20 -> 14 -> 10 mg reduction ladder; K_SBP_LEN is
##  #   tied to the SAME VEGFR occupancy term that produces efficacy, so the
##  #   model cannot separate benefit from hypertension without separating
##  #   VEGFR-2 from the other kinases.
##
##  # ---------- Quick sanity plots ----------
##  # df <- EMC_simulate_scenarios(730)
##  # ggplot(df, aes(time, Tumor_total_mm, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, CD8_effector,   colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Survival_fraction, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, ANC_10e9L,      colour = scenario)) + geom_line()
