#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
cgd_analysis.py — runs the CGD QSP model and writes cgd_reference_output.txt
and cgd_calibration.json.  Every number quoted in README.md and in the header
of the mrgsolve file comes from here.

    python3 cgd_analysis.py
"""
import json
import math
import os
import sys
import io

import numpy as np
from scipy.optimize import brentq
from scipy.stats import norm

import cgd_kernel as KER
import cgd_python_reference as M

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = io.StringIO()


def w(*a):
    line = " ".join(str(x) for x in a)
    print(line)
    OUT.write(line + "\n")


def hdr(t):
    w("")
    w("=" * 78)
    w(t)
    w("=" * 78)


# Fixed literature case-fatality rates.  These are NOT fitted, which is what
# lets mortality be a prediction rather than a target.
CFR_B = 0.010     # per serious bacterial infection
CFR_F = 0.20      # per episode of invasive aspergillosis in CGD


# ============================================================================
def main():
    w("CHRONIC GRANULOMATOUS DISEASE — QSP MODEL REFERENCE OUTPUT")
    w("Generated by cgd_analysis.py.  All values computed, none transcribed.")

    # ------------------------------------------------------------------
    hdr("SECTION A — THE PHAGOSOME KERNEL, AND WHAT IT GETS RIGHT UNPROMPTED")
    cal = KER.calibrate(verbose=False)
    w("")
    w("Calibrated on NORMAL neutrophils only (five numbers, five targets):")
    for k in ("AH0", "alk_gain", "kK_comp", "kox", "kprot"):
        w(f"    {k:10s} = {cal[k]:.6g}")
    ref = KER.ORGANISMS["Staphylococcus aureus"]
    s1 = KER.summarise(KER.run_phagosome(1.0, ref, 3600.0, cal), KER.FIXED)
    s0 = KER.summarise(KER.run_phagosome(0.0, ref, 3600.0, cal), KER.FIXED)
    w("")
    w("Hit by construction (the five targets):")
    w(f"    HOCl share of phagosomal H2O2   {s1['frac_H2O2_to_HOCl']:.3f}   target 0.70")
    w(f"    peak phagosomal pH              {s1['pH_peak']:.2f}    target 7.80  (Segal 1981)")
    w(f"    peak phagosomal K+              {s1['K_peak']:.3f} M  target 0.500 (Reeves 2002)")
    w(f"    S. aureus killed in 60 min      {1 - s1['B_end']:.3f}   target 0.95")
    w(f"    the same at phi = 0             {1 - s0['B_end']:.3f}   target 0.40")
    w("")
    w("NOT fitted — these fall out of the rate constants:")
    w(f"    HOCl molecules delivered per ingested bacterium   "
      f"{s1['HOCl_molecules_per_bact']:.3e}")
    w("        Winterbourn 2006 estimated ~1e8 by a completely different route.")
    w(f"    superoxide converted to H2O2                     {s1['frac_O2m_to_H2O2']:.3f}")
    w(f"    peak phagosomal [O2.-]                           {s1['S_peak']:.3e} M")
    w(f"    peak phagosomal [H2O2]                           {s1['H_peak']:.3e} M")
    w(f"    MPO trapped as Compound III                      {s1['CIII_frac']:.3f}")
    w(f"    phagosomal Cl- nadir                             {s1['Cl_min']:.4f} M "
      f"(Chapman 2002 measured a fall from ~0.10 M)")
    w("")
    w("HONEST MISS: the peak superoxide concentration is "
      f"{25e-6 / s1['S_peak']:.0f}x BELOW the ~25 uM")
    w("that Winterbourn's own model reports, because in this kernel MPO — not")
    w("spontaneous dismutation — is the dominant superoxide sink, so O2.- never")
    w("accumulates.  The two models agree on the integrated quantity that matters")
    w("(HOCl delivered) and disagree on the instantaneous one.  Nothing downstream")
    w("in this model reads the O2.- concentration; everything reads the HOCl flux.")

    w("")
    w("An independent cross-check of R_ox that the kernel was not given:")
    whole_cell = 5e-9 / 1e6 / 60.0            # 5 nmol O2-/1e6 PMN/min -> mol/cell/s
    per_phag = whole_cell / (10 * KER.FIXED["V_phag"])
    w(f"    whole-cell PMA-stimulated output 5 nmol/1e6 cells/min, spread over 10")
    w(f"    phagosomes of 1.2 fL, is {per_phag:.2e} M/s; the kernel uses "
      f"{KER.FIXED['R_ox']:.2e} M/s — agreement to a factor of "
      f"{per_phag / KER.FIXED['R_ox']:.1f} between two unrelated measurements.")

    # ------------------------------------------------------------------
    hdr("SECTION B — THE CATALASE DOGMA, DONE AS ARITHMETIC")
    w("")
    w("The textbook says CGD patients are infected by CATALASE-POSITIVE organisms,")
    w("because catalase-negative organisms donate the H2O2 that the CGD phagosome")
    w("cannot make.  That is two claims, about two different properties, and the")
    w("model separates them.")
    w("")
    w("CLAIM 1 — catalase protects the organism by destroying phagosomal H2O2.")
    w("Pseudo-first-order competition for H2O2 inside the phagosome (/s):")
    w("")
    w(f"    {'organism':30s} {'k_MPO':>10s} {'k_catalase':>11s} {'catalase share':>15s}")
    for nm in ("Staphylococcus aureus", "Aspergillus fumigatus", "Escherichia coli",
               "Streptococcus pneumoniae"):
        cc = KER.h2o2_competition(KER.ORGANISMS[nm])
        w(f"    {nm:30s} {cc['k_mpo']:10.3g} {cc['k_cat']:11.3g} "
          f"{cc['frac_to_catalase']:14.1%}")
    cc = KER.h2o2_competition(KER.ORGANISMS["Staphylococcus aureus"])
    w("")
    w(f"    An organism would need {cc['catalase_M_needed_to_halve']:.2e} M of intracellular")
    w(f"    catalase haem — {cc['catalase_M_needed_to_halve'] / 5.0e-5:.0f}x what S. aureus carries — merely to take")
    w(f"    HALF the phagosomal H2O2 away from MPO.  Catalase loses this race.")
    w("")
    w("And the deeper problem with Claim 1: it is a claim about the NORMAL")
    w("phagosome.  In CGD there is no H2O2 for catalase to destroy.  Deleting")
    w("catalase from S. aureus in the model:")
    for phi, lab in ((1.0, "normal"), (0.0, "phi = 0 (CGD)")):
        kk = KER.kill_fraction(phi, KER.ORGANISMS["Staphylococcus aureus"], 60.0, cal)
        k0 = KER.kill_fraction(phi, KER.ORGANISMS["Staphylococcus aureus"], 60.0, cal,
                               arms=dict(catalase=False))
        w(f"    {lab:14s}  killed with catalase {kk:.4f} -> without catalase {k0:.4f} "
          f"(delta {k0 - kk:+.4f})")
    w("    Messina 2002 made exactly this mutant and found it fully virulent in")
    w("    CGD mice.  The model says so too, and says why: nothing was removed.")
    w("")
    w("CLAIM 2 — the organism's own H2O2 arms the CGD phagosome.  THIS one is")
    w("quantitatively enormous, and it is a DIFFERENT column of the table:")
    w("")
    w(f"    {'organism':30s} {'catalase':>9s} {'self-arming index':>18s} {'CGD pathogen?':>14s}")
    for nm, o in KER.ORGANISMS.items():
        sai = KER.self_arming_index(o)
        w(f"    {nm:30s} {'pos' if o['catalase'] > 0 else 'NEG':>9s} "
          f"{sai:18.2f} {'YES' if o['cgd'] else 'no':>14s}")
    w("")
    w("    A self-arming index of 1.0 means the organism hands the phagosome as")
    w("    much H2O2 as a HEALTHY NADPH oxidase would.  Every peroxigenic organism")
    w("    in the table clears that bar, and not one of them causes CGD disease.")
    w("")
    w("    BUT THE TABLE CANNOT ADJUDICATE BETWEEN THE TWO CLAIMS, AND SAYING SO")
    w("    IS THE POINT.  Score both rules as classifiers of CGD pathogenicity:")
    cat_tp = sum(1 for o in KER.ORGANISMS.values() if o["catalase"] > 0 and o["cgd"])
    cat_fp = sum(1 for o in KER.ORGANISMS.values() if o["catalase"] > 0 and not o["cgd"])
    cat_fn = sum(1 for o in KER.ORGANISMS.values() if o["catalase"] == 0 and o["cgd"])
    cat_tn = sum(1 for o in KER.ORGANISMS.values() if o["catalase"] == 0 and not o["cgd"])
    sa_tp = sum(1 for o in KER.ORGANISMS.values() if KER.self_arming_index(o) < 0.5 and o["cgd"])
    sa_fp = sum(1 for o in KER.ORGANISMS.values() if KER.self_arming_index(o) < 0.5 and not o["cgd"])
    sa_fn = sum(1 for o in KER.ORGANISMS.values() if KER.self_arming_index(o) >= 0.5 and o["cgd"])
    sa_tn = sum(1 for o in KER.ORGANISMS.values() if KER.self_arming_index(o) >= 0.5 and not o["cgd"])
    n_org = len(KER.ORGANISMS)
    w(f"        'catalase-positive -> CGD pathogen':  TP {cat_tp} FP {cat_fp} "
      f"FN {cat_fn} TN {cat_tn}   accuracy {(cat_tp + cat_tn) / n_org:.1%}")
    w(f"        'cannot self-arm   -> CGD pathogen':  TP {sa_tp} FP {sa_fp} "
      f"FN {sa_fn} TN {sa_tn}   accuracy {(sa_tp + sa_tn) / n_org:.1%}")
    w("")
    w("    IDENTICAL.  In this organism set catalase status and peroxigenicity are")
    w("    almost perfectly confounded, so the epidemiology cannot separate the")
    w("    hypotheses, and the decades of textbooks that cite the organism list as")
    w("    evidence for the catalase mechanism were citing evidence that does not")
    w("    discriminate.  Note also that BOTH rules mis-classify the same three")
    w("    organisms — E. coli, Candida albicans, Haemophilus influenzae are")
    w("    catalase-positive, cannot self-arm, and are still not CGD pathogens —")
    w("    which is where the third axis, how oxidant-dependent the killing of")
    w("    that organism is at all, has to do the work.")
    w("")
    w("    WHAT DOES DISCRIMINATE is the arithmetic, and it goes against catalase")
    w("    on both counts: catalase captures under 5% of phagosomal H2O2 even in a")
    w("    normal phagosome, and in the CGD phagosome it captures 5% of nothing.")
    w("    Deleting it changes the modelled kill by 0.0025 and 0.0000 respectively,")
    w("    which is what Messina 2002 found in mice.")
    w("")
    w("    CATALASE-NEGATIVITY IS A MARKER.  PEROXIGENICITY IS THE MECHANISM.")
    w("    The discriminating experiment the confounding hides: a catalase-NEGATIVE")
    w("    but non-peroxigenic organism should behave as a CGD pathogen, and a")
    w("    catalase-POSITIVE peroxigenic organism should be spared.  The dogma")
    w("    predicts the opposite for both.")

    # ------------------------------------------------------------------
    hdr("SECTION C — K(phi): THE SHAPE OF THE DOSE-RESPONSE TO OXIDASE ACTIVITY")
    phis, Ks = KER.K_curve(n=41, cal=cal)
    hp = KER.fit_hill(phis, Ks)
    w("")
    w("Hill fit to K(phi) = log10 kill of one ingested S. aureus in 60 min:")
    for k, v in hp.items():
        w(f"    {k:6s} = {v:.5g}")
    w("")
    w(f"    phi50 = {hp['phi50']:.3f} with a Hill coefficient of {hp['hill']:.2f}.")
    w("")
    Kraw = {round(p_, 4): KER.K_log(p_, ref, 60.0, cal)
            for p_ in (0.0, 0.2, 0.4, 0.6, 0.8, 1.0)}
    n_pow = math.log((Kraw[0.5 if 0.5 in Kraw else 0.6] - Kraw[0.0]) /
                     (Kraw[1.0] - Kraw[0.0])) / math.log(0.6)
    w("")
    w("    The Hill form fits only moderately (r2 %.3f) and it fits BADLY at the"
      % hp["r2"])
    w("    ends, because the true curve has no upper plateau.  Read the raw curve")
    w("    instead, in 0.2 steps of phi, and the shape is unmistakable:")
    for a_, b_ in ((0.0, 0.2), (0.2, 0.4), (0.4, 0.6), (0.6, 0.8), (0.8, 1.0)):
        w(f"        phi {a_:.1f} -> {b_:.1f}:  K gains {Kraw[b_] - Kraw[a_]:.3f} log")
    w("")
    w(f"    Each successive fifth of oxidase activity is worth MORE than the one")
    w(f"    before it, all the way to phi = 1.  A power law K = K0 + A*phi^n fits")
    w(f"    with n = {n_pow:.2f}, i.e. convex and still accelerating at full")
    w("    activity.  There is NO THRESHOLD inside the phagosome, and the first")
    w("    20% of oxidase activity is the LEAST valuable 20% there is.")
    w("    This matters clinically because it is the opposite of the intuition")
    w("    behind gene therapy and mixed chimerism, where 10-20% correction is")
    w("    known to be enough.  If the phagosome has no threshold, the clinical")
    w("    threshold has to be somewhere else.  It is: see Sections D and F.")
    w("")
    w("Where the phagosome DOES have a threshold is its pH:")
    for p_ in (0.3, 0.5, 0.55, 0.6, 0.7, 0.9, 1.0):
        ss = KER.summarise(KER.run_phagosome(p_, ref, 1800.0, cal), KER.FIXED)
        w(f"    phi = {p_:4.2f}  peak pH {ss['pH_peak']:.3f}  peak K+ {ss['K_peak']:.3f} M")
    w("")
    w("    Alkalinisation is a race between the oxidase's proton consumption and")
    w("    the V-ATPase, and below ~57% of normal flux the V-ATPase simply wins.")
    w("    So a hypomorphic patient with 30% residual oxidase has a phagosome that")
    w("    is, in pH and therefore in alkaline-protease terms, indistinguishable")
    w("    from a null patient's — even though the DHR assay separates them")
    w("    cleanly.  The location of that threshold is set by pH_rest and by the")
    w("    V-ATPase rate, neither of which is well measured; the EXISTENCE of the")
    w("    threshold is structural.")

    # ------------------------------------------------------------------
    hdr("SECTION D — THE DHR MEAN IS NOT A SUFFICIENT STATISTIC")
    w("")
    w("Two patients, one number.  A female X-CGD carrier with a fraction f of")
    w("fully competent neutrophils and the rest at zero, and a hypomorphic male")
    w("with EVERY neutrophil at a uniform residual activity r = f.  The DHR-123")
    w("assay reports the same mean channel fluorescence for both.")
    w("")
    w(f"    {'DHR mean':>9s} {'mosaic surv':>12s} {'uniform surv':>13s} {'ratio':>8s}  which is better")
    for m in (0.05, 0.10, 0.15, 0.20, 0.30, 0.40, 0.50, 0.70, 0.90):
        mos = KER.population_survival(m, 0.0, hp)
        uni = KER.survival_fraction(m, hp)
        better = "MOSAIC" if mos < uni else ("uniform" if uni < mos else "-")
        w(f"    {m:9.2f} {mos:12.4f} {uni:13.4f} {mos / uni:8.3f}  {better}")
    def _gap(m):
        return KER.population_survival(m, 0.0, hp) - KER.survival_fraction(m, hp)
    grid = np.linspace(0.02, 0.98, 97)
    xover = float("nan")
    for lo_, hi_ in zip(grid[:-1], grid[1:]):
        if _gap(lo_) * _gap(hi_) < 0:
            xover = brentq(_gap, lo_, hi_)
            break
    w("")
    w(f"    THE ORDERING CHANGES SIGN AT A DHR MEAN OF {xover:.3f}.")
    w("    Below it, concentrating the oxidase into a few fully competent cells")
    w("    beats spreading it thinly over all of them; above it, the reverse.")
    w("    The crossover is the inflection of K(phi) and nothing else.")
    w("")
    w("    The crossover matters because of WHERE the clinic operates.  X-linked")
    w("    carriers, mixed chimerism after reduced-intensity conditioning, and")
    w("    gene-therapy marking all sit in the 5-25% band, which is below the")
    w("    crossover, so mosaicism is the favourable arrangement there.  A")
    w("    hypomorphic patient reported as '20% of normal' on DHR is NOT the same")
    w("    patient as a carrier reported as '20% of normal', and the flow report")
    w("    that produced both numbers cannot say which one it is looking at unless")
    w("    the HISTOGRAM — bimodal versus uniformly shifted — is read as well.")
    w("    Above the crossover the ordering reverses, so this is not a general")
    w("    claim that mosaicism is better; it is a claim that the sufficient")
    w("    statistic is the distribution and not its mean.")
    w("")
    w("At the level of the whole focus the same comparison is much sharper,")
    w("because the sheltered compartment Bi only exists in cells that cannot kill:")
    w("")
    w(f"    {'patient':28s} {'DHR':>5s} {'log10 N_crit':>13s}")
    for nm in ("healthy", "X-CGD null (gp91phox-)", "X-CGD carrier 5%",
               "X-CGD hypomorph 5%", "X-CGD carrier 20%", "X-CGD hypomorph 20%",
               "X-CGD carrier 50%"):
        f, r = M.GENOTYPES[nm]
        nc = M.critical_inoculum(M.make_ctx(f, r, hp))
        w(f"    {nm:28s} {M.dhr_index(f, r):5.2f} {nc:13.3f}")
    f5c, _ = M.GENOTYPES["X-CGD carrier 20%"]
    nc_c = M.critical_inoculum(M.make_ctx(0.20, 0.0, hp))
    nc_u = M.critical_inoculum(M.make_ctx(0.0, 0.20, hp))
    w("")
    w(f"    At a DHR mean of 0.20 the mosaic patient tolerates "
      f"{10 ** (nc_c - nc_u):.2f}x the inoculum")
    w("    of the uniform patient.  One number on the flow report, two diseases.")

    # ------------------------------------------------------------------
    hdr("SECTION E — EXPOSURE CALIBRATION, AND THREE PREDICTED TRIALS")
    nc_cgd = M.critical_inoculum(M.make_ctx(0.0, 0.0, hp))
    nc_hlt = M.critical_inoculum(M.make_ctx(1.0, 1.0, hp))

    def resid(muN):
        lam = M.WHOLE_TARGETS["rate_bact_cgd_null"] / norm.sf((nc_cgd - muN) / M.SDN)
        return lam * norm.sf((nc_hlt - muN) / M.SDN) - M.WHOLE_TARGETS["rate_bact_healthy"]
    muN_b = brentq(resid, -2.0, nc_hlt - 0.1)
    lam_b = M.WHOLE_TARGETS["rate_bact_cgd_null"] / norm.sf((nc_cgd - muN_b) / M.SDN)

    ncf_cgd = M.critical_inoculum_f(M.make_fctx(0.0, 0.0, hp))
    ncf_hlt = M.critical_inoculum_f(M.make_fctx(1.0, 1.0, hp))

    def residf(muN):
        lam = M.WHOLE_TARGETS["rate_fung_cgd_null"] / norm.sf((ncf_cgd - muN) / M.SDN)
        return lam * norm.sf((ncf_hlt - muN) / M.SDN) - M.WHOLE_TARGETS["rate_fung_healthy"]
    muN_f = brentq(residf, -2.0, ncf_hlt - 0.1)
    lam_f = M.WHOLE_TARGETS["rate_fung_cgd_null"] / norm.sf((ncf_cgd - muN_f) / M.SDN)

    w("")
    w("Two bacterial targets fix two bacterial exposure parameters; two fungal")
    w("targets fix two fungal ones.  That is the entire whole-body calibration.")
    w(f"    log10 N_crit bacterial, untreated X-CGD null   {nc_cgd:.3f}")
    w(f"    log10 N_crit bacterial, healthy control        {nc_hlt:.3f}")
    w(f"    log10 N_crit fungal,    untreated X-CGD null   {ncf_cgd:.3f}")
    w(f"    log10 N_crit fungal,    healthy control        {ncf_hlt:.3f}")
    w(f"    lambda_b = {lam_b:.3f} exposures/patient-year, mean inoculum "
      f"10^{muN_b:.3f} CFU")
    w(f"    lambda_f = {lam_f:.3f} exposures/patient-year, mean inoculum "
      f"10^{muN_f:.3f} conidia")
    M.CALW.update(dict(lambda_b=lam_b, muN_b=muN_b, lambda_f=lam_f, muN_f=muN_f,
                       k_h_bact=2.0e-5, k_h_fung=1.0e-4, amp_IL1=4.0, k_gran=0.135))

    # steady-state drug effects computed from the PK, not assumed
    r_tmp = M.simulate(genotype="healthy", days=30, hp=hp, regimen=dict(tmpsmx=1))
    TMPss = M.get(r_tmp, "TMP_c")[-1] / M.P["TMP_Vc"] * M.P["TMP_fu"]
    E_TMP = M.P["TMP_Emax"] * TMPss / (M.P["TMP_EC50"] + TMPss)
    r_itz = M.simulate(genotype="healthy", days=30, hp=hp, regimen=dict(itra=1))
    ITZss = (M.get(r_itz, "ITZ_c")[-1] / M.P["ITZ_Vc"]
             + 0.6 * M.get(r_itz, "OHITZ")[-1] / M.P["OHITZ_V"])
    E_ITZ = M.P["ITZ_Emax"] * ITZss / (M.P["ITZ_EC50"] + ITZss)
    r_ifn = M.simulate(genotype="healthy", days=30, hp=hp, regimen=dict(ifng=1), n_out=721)
    IFNav = float(np.mean(M.get(r_ifn, "IFN_c")[-168:]) / M.P["IFN_V"])
    E_IFN = 1.0 + M.P["IFN_Emax_nonox"] * IFNav / (M.P["IFN_EC50"] + IFNav)
    w("")
    w("Drug effects taken from the simulated steady-state PK, not assumed:")
    w(f"    free trimethoprim   {TMPss:.3f} mg/L  -> bacterial kill {E_TMP:.3f}/d")
    w(f"    itraconazole+OH-ITZ {ITZss:.3f} mg/L  -> hyphal kill    {E_ITZ:.3f}/d")
    w(f"    interferon gamma-1b {IFNav:.3f} ng/mL -> non-oxidative arm x{E_IFN:.3f}")

    def rate_b(f, r, drug=0.0, nonox=1.0):
        return M.infection_rate(M.critical_inoculum(
            M.make_ctx(f, r, hp, drug_kill_b=drug, nonox_boost=nonox)), lam_b, muN_b)

    def rate_f(f, r, drug=0.0, nonox=1.0):
        return M.infection_rate(M.critical_inoculum_f(
            M.make_fctx(f, r, hp, drug_kill_f=drug, nonox_boost=nonox)), lam_f, muN_f)

    w("")
    w("PREDICTED TRIALS.  None of the following was fitted.")
    w("")
    b0 = rate_b(0.0, 0.0)
    b1 = rate_b(0.0, 0.0, drug=E_TMP)
    w("  1. Co-trimoxazole prophylaxis (Margolis 1990)")
    w(f"       model  {b0:.3f} -> {b1:.3f} bacterial infections/patient-year "
      f"({1 - b1 / b0:.0%} reduction)")
    w(f"       trial  1.90 -> 0.83                                    (56% reduction)")
    w(f"       ERROR on the treated arm: {b1 - 0.83:+.3f}/patient-year")
    f0 = rate_f(0.0, 0.0)
    f1 = rate_f(0.0, 0.0, drug=E_ITZ)
    w("")
    w("  2. Itraconazole prophylaxis (Gallin 2003)")
    w(f"       model  {f0:.3f} -> {f1:.3f} fungal infections/patient-year "
      f"({1 - f1 / f0:.0%} reduction)")
    w(f"       trial  7 events on placebo vs 1 on itraconazole        (86% reduction)")
    i0 = b0 + f0
    i1 = rate_b(0.0, 0.0, nonox=E_IFN) + rate_f(0.0, 0.0, nonox=E_IFN)
    w("")
    w("  3. Interferon gamma-1b (International CGD Cooperative Study 1991)")
    w(f"       model  {i0:.3f} -> {i1:.3f} serious infections/patient-year "
      f"({1 - i1 / i0:.0%} reduction)")
    w(f"       trial  30/65 vs 14/63 patients with a serious infection (67% reduction)")
    w("       and the model was NOT allowed to let interferon touch phi, because")
    w("       the trial found no reproducible rise in superoxide production.")
    w("")
    bt = rate_b(0.0, 0.0, drug=E_TMP, nonox=E_IFN)
    ft = rate_f(0.0, 0.0, drug=E_ITZ, nonox=E_IFN)
    w("  4. Modern triple prophylaxis (co-trimoxazole + itraconazole + interferon)")
    w(f"       model  {bt:.3f} bacterial + {ft:.3f} fungal = {bt + ft:.3f} serious "
      f"infections/patient-year")
    w(f"       registry era (Marciano 2015, van den Berg 2009): 0.2-0.4/patient-year")
    w("")
    w(f"  Predicted mortality, untreated X-CGD null, using FIXED case-fatality")
    w(f"  rates ({CFR_B:.1%} bacterial, {CFR_F:.0%} invasive aspergillosis):")
    w(f"       {b0 * CFR_B + f0 * CFR_F:.4f}/patient-year   "
      f"(pre-prophylaxis literature ~0.05)")
    w(f"  On triple prophylaxis: {bt * CFR_B + ft * CFR_F:.4f}/patient-year "
      f"(modern series 0.01-0.02)")

    # ------------------------------------------------------------------
    hdr("SECTION F — HOW MUCH CORRECTED MYELOPOIESIS IS ENOUGH?")
    w("")
    w("The clinical question that transplant and gene therapy both turn on.  The")
    w("model answers it WITHOUT having been told the answer: f is swept, and the")
    w("infection rate is read off.")
    w("")
    w(f"    {'corrected %':>12s} {'DHR mean':>9s} {'log10 Ncrit':>12s} {'bact/yr':>9s} "
      f"{'fung/yr':>9s} {'deaths/yr':>10s}")
    rows = []
    for f in (0.0, 0.02, 0.05, 0.08, 0.10, 0.12, 0.15, 0.20, 0.25, 0.30,
              0.40, 0.50, 0.70, 0.90, 1.00):
        nc = M.critical_inoculum(M.make_ctx(f, 0.0, hp))
        rb = M.infection_rate(nc, lam_b, muN_b)
        rf = M.infection_rate(M.critical_inoculum_f(M.make_fctx(f, 0.0, hp)), lam_f, muN_f)
        d = rb * CFR_B + rf * CFR_F
        rows.append((f, nc, rb, rf, d))
        w(f"    {f * 100:11.0f}% {f:9.2f} {nc:12.3f} {rb:9.3f} {rf:9.3f} {d:10.4f}")
    d0 = rows[0][4]
    thr = {}
    for frac in (0.50, 0.90, 0.95):
        try:
            thr[frac] = brentq(
                lambda f: (M.infection_rate(M.critical_inoculum(M.make_ctx(f, 0.0, hp)),
                                            lam_b, muN_b) * CFR_B
                           + M.infection_rate(M.critical_inoculum_f(M.make_fctx(f, 0.0, hp)),
                                              lam_f, muN_f) * CFR_F) - (1 - frac) * d0,
                0.001, 0.999, xtol=1e-3)
        except ValueError:
            thr[frac] = float("nan")
    w("")
    for frac, v in thr.items():
        w(f"    {frac:.0%} of the untreated mortality is removed by "
          f"{v * 100:.1f}% corrected myelopoiesis")
    w("")
    w("    Published thresholds: >20% donor myeloid chimerism is associated with")
    w("    resolution of CGD manifestations and <10% with recurrence (Guengoer 2014,")
    w("    Marciano 2018); lentiviral gene therapy achieved 16-46% DHR-positive")
    w("    neutrophils at 12 months with clinical resolution in 6/9 (Kohn 2020).")
    w("    The model was given none of these and lands in the same decade.")
    w("")
    w("    CAVEAT ON THE LOCATION.  The mortality column is dominated by the")
    w("    fungal term, because invasive aspergillosis carries a 20x higher")
    w("    case-fatality than a bacterial infection.  So the position of the")
    w("    threshold is mostly the position of the FUNGAL critical inoculum, and")
    w("    the fungal arm is the less well constrained of the two.  The bacterial")
    w("    column, which is better constrained, shows the same convexity but a")
    w("    gentler one: 20% correction halves it, 50% quarters it again.")
    w("")
    w("    NOTE WHERE THE THRESHOLD COMES FROM.  It is NOT in K(phi), which has no")
    w("    threshold at all (Section C).  It is manufactured downstream, by the")
    w("    sheltered compartment: correcting a cell does not merely add a killer,")
    w("    it removes a sanctuary, and the sanctuary term is what is convex.")

    # ------------------------------------------------------------------
    hdr("SECTION G — DOES THE BENEFIT OF EACH DRUG DEPEND ON RESIDUAL ROS?")
    w("")
    w("Kuhns 2010 showed that survival in CGD tracks residual superoxide")
    w("production continuously, and that genotype predicts outcome only through")
    w("it.  If that is right, a drug's usefulness should also depend on where the")
    w("patient sits on that axis — but not every drug the same way.")
    w("")
    w(f"    {'residual':>9s} {'no proph':>9s} {'+TMP-SMX':>9s} {'+itra':>8s} {'+IFN-g':>8s} "
      f"{'IFN rel.benefit':>16s}")
    for r in (0.00, 0.02, 0.05, 0.10, 0.20, 0.30, 0.50):
        n0 = rate_b(0.0, r) * CFR_B + rate_f(0.0, r) * CFR_F
        nt = rate_b(0.0, r, drug=E_TMP) * CFR_B + rate_f(0.0, r) * CFR_F
        ni = rate_b(0.0, r) * CFR_B + rate_f(0.0, r, drug=E_ITZ) * CFR_F
        ng = rate_b(0.0, r, nonox=E_IFN) * CFR_B + rate_f(0.0, r, nonox=E_IFN) * CFR_F
        w(f"    {r:9.2f} {n0:9.4f} {nt:9.4f} {ni:8.4f} {ng:8.4f} "
          f"{1 - ng / n0 if n0 > 0 else float('nan'):15.1%}")
    w("")
    w("    The interferon column is close to FLAT in relative terms, exactly as it")
    w("    must be if interferon acts on the oxidase-independent arm — which is")
    w("    what the 1991 trial's failure to find restored superoxide forces.  This")
    w("    is a falsifiable prediction and the trial was never powered to test it.")

    # ------------------------------------------------------------------
    hdr("SECTION H — GRANULOMA WITHOUT AN ORGANISM")
    w("")
    w("The claim: CGD's inflammatory disease is not caused by the infections and")
    w("does not answer to antimicrobials.  The test: run patients who are never")
    w("inoculated with anything at all, for a year.")
    w("")
    scen = [
        ("healthy control",             dict(genotype="healthy")),
        ("X-CGD null, no therapy",      dict(genotype="X-CGD null (gp91phox-)")),
        ("X-CGD, co-trimox+itra",       dict(genotype="X-CGD null (gp91phox-)",
                                             regimen=dict(tmpsmx=1, itra=1))),
        ("X-CGD, prednisolone 1 mg/kg", dict(genotype="X-CGD null (gp91phox-)",
                                             regimen=dict(pred=1, pred_dose=1.0))),
        ("X-CGD, anakinra 2 mg/kg",     dict(genotype="X-CGD null (gp91phox-)",
                                             regimen=dict(anakinra=1))),
        ("X-CGD, HSCT 95% chimerism",   dict(genotype="X-CGD null (gp91phox-)",
                                             chim_target=0.95)),
        ("X-CGD, gene therapy 20%",     dict(genotype="X-CGD null (gp91phox-)",
                                             vcn_target=0.20)),
    ]
    w("")
    w(f"    {'arm':30s} {'IL-1b':>7s} {'IL-10':>6s} {'apoptotic':>10s} "
      f"{'granuloma':>10s} {'colitis':>8s} {'CRP':>6s}")
    for nm, kw in scen:
        r = M.simulate(days=365, hp=hp, **kw)
        gg = lambda n: M.get(r, n)[-1]
        w(f"    {nm:30s} {gg('IL1B'):7.2f} {gg('IL10'):6.2f} {gg('APOP'):10.1f} "
          f"{gg('GRAN'):10.3f} {gg('COL'):8.2f} {gg('CRP'):6.2f}")
    w("")
    w("    Antimicrobial prophylaxis does not touch the granuloma, because there")
    w("    was never an organism in it.  Anakinra and transplant both abolish it,")
    w("    by opposite routes — one blocks the receptor, the other restores the")
    w("    oxidase that would have restrained the inflammasome and permitted")
    w("    efferocytosis in the first place.  Prednisolone lands in between and")
    w("    buys its effect with an infection penalty the other two do not pay.")
    w("")
    w("    The mechanism is a LOOP, not a level: the CGD neutrophil dies without")
    w("    externalising the oxidised phosphatidylserine that marks it for")
    w("    clearance, so the corpse persists, and the corpse is simultaneously an")
    w("    IL-1beta stimulus AND the missing source of the IL-10 that would have")
    w("    switched the lesion off.  Note the IL-10 column: it does not fall in")
    w("    CGD, it RISES, because there are so many more corpses; what fails is")
    w("    IL-10 per corpse, and the model shows that failing quantity is not")
    w("    enough on its own.")

    w("")
    w("    A DHR-MEAN CHECK.  The mosaic and uniform patients of Section D, whose")
    w("    infection risks differ, have IDENTICAL inflammatory phenotypes:")
    for nm in ("X-CGD carrier 20%", "X-CGD hypomorph 20%"):
        r = M.simulate(genotype=nm, days=365, hp=hp)
        w(f"        {nm:22s} IL-1b {M.get(r, 'IL1B')[-1]:6.2f}  "
          f"granuloma {M.get(r, 'GRAN')[-1]:6.3f}  colitis {M.get(r, 'COL')[-1]:5.2f}")
    w("        The DHR mean IS a sufficient statistic for the inflammatory")
    w("        phenotype and is NOT one for the infectious phenotype, because")
    w("        efferocytosis and inflammasome restraint average over the")
    w("        population while killing happens one phagosome at a time.")

    # ------------------------------------------------------------------
    hdr("SECTION I — PRICING THE THREE CONTESTED MECHANISMS")
    w("")
    w("Three arms of this model rest on findings that were disputed or did not")
    w("replicate.  Rather than argue, switch each one off and report the cost.")
    w("")
    base = KER.kill_fraction(0.0, ref, 60.0, cal)
    base1 = KER.kill_fraction(1.0, ref, 60.0, cal)
    for lab, arms in (("Segal 1981 phagosomal alkalinisation", dict(segal_pH=False)),
                      ("Reeves 2002 K+/protease killing", dict(protease=False))):
        k0 = KER.kill_fraction(0.0, ref, 60.0, cal, arms=arms)
        k1 = KER.kill_fraction(1.0, ref, 60.0, cal, arms=arms)
        w(f"    without {lab}:")
        w(f"        normal PMN kill 60 min  {base1:.3f} -> {k1:.3f}")
        w(f"        phi = 0 PMN kill 60 min {base:.3f} -> {k0:.3f}")
    r_on = M.simulate(genotype="X-CGD null (gp91phox-)", days=365, hp=hp,
                      arm_ido_needs_nox=True)
    r_off = M.simulate(genotype="X-CGD null (gp91phox-)", days=365, hp=hp,
                       arm_ido_needs_nox=False)
    w("    Romani 2008 'NADPH oxidase is required for IDO' (did not replicate,")
    w("    De Ravin 2010) — carried as a switchable arm, default OFF:")
    w(f"        kynurenine with the arm ON  {M.get(r_on, 'KYN')[-1]:.2f} uM, "
      f"tryptophan {M.get(r_on, 'TRP')[-1]:.2f} uM")
    w(f"        kynurenine with the arm OFF {M.get(r_off, 'KYN')[-1]:.2f} uM, "
      f"tryptophan {M.get(r_off, 'TRP')[-1]:.2f} uM")
    w("        Nothing else in the model reads either variable, which is the")
    w("        honest statement of how much work the hypothesis is doing here:")
    w("        none.  It is instrumented so that it CAN be tested, not asserted.")

    # ------------------------------------------------------------------
    hdr("SECTION J — SIXTEEN CLINICAL SCENARIOS")
    scenarios = [
        ("1  healthy control",                 dict(genotype="healthy"), 365),
        ("2  X-CGD null, no prophylaxis",      dict(genotype="X-CGD null (gp91phox-)"), 365),
        ("3  X-CGD null + co-trimoxazole",     dict(genotype="X-CGD null (gp91phox-)",
                                                    regimen=dict(tmpsmx=1)), 365),
        ("4  X-CGD null + cotrim + itra",      dict(genotype="X-CGD null (gp91phox-)",
                                                    regimen=dict(tmpsmx=1, itra=1)), 365),
        ("5  X-CGD null + triple prophylaxis", dict(genotype="X-CGD null (gp91phox-)",
                                                    regimen=dict(tmpsmx=1, itra=1, ifng=1)), 365),
        ("6  p47phox AR + triple",             dict(genotype="p47phox-deficient (AR)",
                                                    regimen=dict(tmpsmx=1, itra=1, ifng=1)), 365),
        ("7  X-CGD hypomorph 20%",             dict(genotype="X-CGD hypomorph 20%"), 365),
        ("8  X-CGD carrier 20% (same DHR)",    dict(genotype="X-CGD carrier 20%"), 365),
        ("9  staph inoculum 1e4, no rx",       dict(genotype="X-CGD null (gp91phox-)",
                                                    seed_bact=1e4), 90),
        ("10 staph inoculum 1e4 + co-trimox",  dict(genotype="X-CGD null (gp91phox-)",
                                                    seed_bact=1e4, regimen=dict(tmpsmx=1)), 90),
        ("10b established abscess 1e6 + same", dict(genotype="X-CGD null (gp91phox-)",
                                                    seed_bact=1e6, regimen=dict(tmpsmx=1)), 90),
        ("11 invasive aspergillosis, no rx",   dict(genotype="X-CGD null (gp91phox-)",
                                                    seed_conid=1e4), 90),
        ("12 same + voriconazole + IFN-g",     dict(genotype="X-CGD null (gp91phox-)",
                                                    seed_conid=1e4,
                                                    regimen=dict(vori=1, ifng=1)), 90),
        ("13 granulomatous colitis + steroid", dict(genotype="X-CGD null (gp91phox-)",
                                                    regimen=dict(pred=1, pred_dose=1.0)), 365),
        ("14 granulomatous colitis + anakinra",dict(genotype="X-CGD null (gp91phox-)",
                                                    regimen=dict(anakinra=1)), 365),
        ("15 HSCT, 95% donor chimerism",       dict(genotype="X-CGD null (gp91phox-)",
                                                    chim_target=0.95, extra_hazard=0.03), 365),
        ("16 lentiviral gene therapy, 20%",    dict(genotype="X-CGD null (gp91phox-)",
                                                    vcn_target=0.20), 365),
    ]
    w("")
    w("")
    w("The survival column here is the ODE hazard from THE SEEDED LESION ONLY.")
    w("Population mortality — the number that should be compared with a registry")
    w("— comes from the exposure model of Section E and is not this column.")
    w("")
    w(f"    {'scenario':38s} {'ANC':>6s} {'CRP':>6s} {'IL-1b':>7s} {'gran':>7s} "
      f"{'colitis':>7s} {'log10 B':>8s} {'log10 H':>8s} {'ALT':>6s} {'surv':>7s}")
    scen_rows = {}
    for lab, kw, dd in scenarios:
        r = M.simulate(days=dd, hp=hp, **kw)
        gg = lambda n: M.get(r, n)[-1]
        lb = math.log10(max(gg("BACT") + gg("BACT_i"), 1.0))
        lh = math.log10(max(gg("HYPH"), 1.0))
        w(f"    {lab:38s} {gg('ANC'):6.0f} {gg('CRP'):6.2f} {gg('IL1B'):7.2f} "
          f"{gg('GRAN'):7.3f} {gg('COL'):7.2f} {lb:8.2f} {lh:8.2f} {gg('ALT'):6.1f} "
          f"{gg('SURV'):7.4f}")
        scen_rows[lab] = dict(ANC=gg("ANC"), CRP=gg("CRP"), IL1B=gg("IL1B"),
                              GRAN=gg("GRAN"), COL=gg("COL"), logB=lb, logH=lh,
                              ALT=gg("ALT"), SURV=gg("SURV"), days=dd)

    # ------------------------------------------------------------------
    hdr("SECTION K — VIRTUAL POPULATION")
    rng = np.random.default_rng(20260806)
    n = 300
    # Half X-linked nulls, a quarter hypomorphs, a quarter autosomal recessive.
    out = []
    for i in range(n):
        u = rng.random()
        if u < 0.50:
            f, r = 0.0, float(np.clip(rng.lognormal(math.log(0.004), 1.0), 0.0, 0.05))
        elif u < 0.75:
            f, r = 0.0, float(np.clip(rng.lognormal(math.log(0.12), 0.7), 0.0, 0.6))
        else:
            f, r = 0.0, float(np.clip(rng.lognormal(math.log(0.05), 0.9), 0.0, 0.4))
        rb = M.infection_rate(M.critical_inoculum(M.make_ctx(f, r, hp, drug_kill_b=E_TMP)),
                              lam_b, muN_b)
        rf = M.infection_rate(M.critical_inoculum_f(M.make_fctx(f, r, hp, drug_kill_f=E_ITZ)),
                              lam_f, muN_f)
        out.append((M.dhr_index(f, r), rb, rf, rb * CFR_B + rf * CFR_F))
    out = np.array(out)
    q = np.quantile(out[:, 0], [0, 0.25, 0.50, 0.75, 1.0])
    w("")
    w("300 virtual patients on co-trimoxazole + itraconazole, stratified by")
    w("residual oxidase activity into quartiles, in the manner of Kuhns 2010:")
    w("")
    w(f"    {'quartile':>9s} {'residual ROS range':>22s} {'bact/yr':>9s} {'fung/yr':>9s} "
      f"{'deaths/yr':>10s} {'rel. risk':>10s}")
    ref_d = None
    for k in range(4):
        m = (out[:, 0] >= q[k]) & (out[:, 0] <= q[k + 1])
        d = out[m, 3].mean()
        if ref_d is None:
            ref_d = d
        w(f"    Q{k + 1:<8d} {q[k]:9.4f} - {q[k + 1]:<9.4f} {out[m, 1].mean():9.3f} "
          f"{out[m, 2].mean():9.3f} {d:10.4f} {d / ref_d:10.2f}")
    w("")
    w(f"    Mortality falls {ref_d / out[out[:, 0] >= q[3], 3].mean():.1f}-fold from the")
    w("    lowest to the highest residual-ROS quartile.  Kuhns 2010 reported a")
    w("    comparable, continuous gradient and showed that genotype adds nothing")
    w("    once residual ROS is known.  In this model the second half of that is")
    w("    true BY CONSTRUCTION — phi is the ONLY thing a genotype can change — so")
    w("    the only testable part is the MAGNITUDE of the gradient, and the model")
    w("    UNDER-PREDICTS it: Kuhns' highest and lowest quartiles differ by roughly")
    w("    fivefold in survival and this model gives twofold.  The most likely")
    w("    reason is that the virtual population's residual-ROS distribution is")
    w("    compressed into the very low end, where K(phi) is flattest (Section C),")
    w("    so three of the four quartiles are effectively the same patient.")
    w("")
    w(f"    Predicted survival to age 30 (constant hazard):")
    for k in range(4):
        m = (out[:, 0] >= q[k]) & (out[:, 0] <= q[k + 1])
        d = out[m, 3].mean()
        w(f"        Q{k + 1}: {math.exp(-d * 30) * 100:.1f}%")

    # ------------------------------------------------------------------
    hdr("SECTION L — WHAT THIS MODEL GETS WRONG, AND WHAT IT NEVER TESTED")
    w("""
 1. PEAK SUPEROXIDE is 17x below Winterbourn's own estimate (Section A).  The
    two models disagree about whether MPO or spontaneous dismutation is the
    dominant superoxide sink.  Nothing downstream reads [O2.-], so the error is
    contained, but it is a real disagreement and not a rounding difference.

 2. THE ALKALINISATION THRESHOLD at phi ~ 0.57 (Section C) depends on two
    numbers that are barely measured: the resting phagosomal pH and the
    V-ATPase rate constant.  Its EXISTENCE is structural; its LOCATION is not,
    and no clinical claim in this file rests on the location.

 3. SEGAL vs JANKOWSKI/GRINSTEIN on whether the CGD phagosome really fails to
    alkalinise is unresolved in the literature and is unresolved here.  The
    model follows Segal and prices the alternative (Section I) rather than
    pretending the question is closed.

 4. THE ITRACONAZOLE PREDICTION UNDERSHOOTS BADLY: 53% against the trial's 86%.
    Of the four predicted trials this is the poor one, and the direction is
    informative — the model has itraconazole acting only on hyphal extension,
    whereas azoles also block germination, which is the step the model gives
    entirely to the (uncorrectable) conidial survival term.  Adding a
    germination-block arm would very likely fix it and was not added, because
    it would then be a fitted arm rather than a predicted one.

 5. THE CO-TRIMOXAZOLE PREDICTION IS GOOD (61% vs 56%) BUT FLATTERS ITSELF: the
    untreated arm of that comparison is one of the two numbers the exposure
    model was calibrated on, so only the treated arm is a prediction.

 6. THE KUHNS GRADIENT IS UNDER-PREDICTED TWOFOLD (Section K).  Either the
    real residual-ROS distribution reaches higher than the one drawn here, or
    K(phi) is too flat at low phi, or residual ROS carries prognostic
    information this model does not represent at all.  The model cannot
    distinguish those three, and does not pretend to.

 7. omega, the oxidant-dependence of each organism, is ASSUMED.  It is the
    softest input in the whole model and it drives the entire organism
    spectrum.  The self-arming index of Section B does not depend on it; the
    Winkelstein ordering does.

 8. NOT TESTED AT ALL: age.  Every patient in this file is a 30 kg child with
    fixed pharmacokinetics.  CGD presents from infancy to the sixth decade and
    the drugs, the marrow and the exposure all change across that range.

 9. NOT TESTED: the autosomal-recessive genotypes as distinct entities.  p47phox
    deficiency is milder than X-linked CGD in every registry, and in this model
    that is represented ONLY by giving it a higher phi_res.  If any part of the
    AR/XL difference is not residual ROS, this model cannot see it.

10. NO R TOOLCHAIN was available in this environment, so cgd_mrgsolve_model.R
    and cgd_shiny_app.R mirror the equations executed here but have not
    themselves been run.  Parameters are injected into them mechanically by
    sync_r_params.py from cgd_calibration.json, so they cannot drift, but the
    R syntax has not been exercised by an interpreter.
""".rstrip())

    # ------------------------------------------------------------------
    calibration = dict(
        kernel=cal,
        kernel_fixed={k: v for k, v in KER.FIXED.items()},
        kernel_targets=KER.TARGETS,
        Kphi_hill=hp,
        whole_body=dict(lambda_b=lam_b, muN_b=muN_b, lambda_f=lam_f, muN_f=muN_f,
                        sdN=M.SDN, CFR_B=CFR_B, CFR_F=CFR_F,
                        amp_IL1=4.0, k_gran=0.135, k_COL=M.P["k_COL"]),
        derived=dict(logNcrit_cgd_null=nc_cgd, logNcrit_healthy=nc_hlt,
                     E_TMP=E_TMP, E_ITZ=E_ITZ, E_IFN=E_IFN,
                     TMP_ss_free_mgL=TMPss, ITZ_ss_mgL=ITZss, IFN_avg_ngmL=IFNav,
                     dhr_crossover=float(xover),
                     correction_for_90pct_benefit=thr.get(0.90)),
        scenarios=scen_rows,
    )
    with open(os.path.join(HERE, "cgd_calibration.json"), "w") as fh:
        json.dump(calibration, fh, indent=2, sort_keys=True, default=float)
    with open(os.path.join(HERE, "cgd_reference_output.txt"), "w") as fh:
        fh.write(OUT.getvalue())
    w("")
    w("Wrote cgd_calibration.json and cgd_reference_output.txt")


if __name__ == "__main__":
    main()
