#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
=======================================================================
 ami_reference_check.py
 Acute Myocardial Infarction (STEMI) — QSP reference implementation
=======================================================================

This file is the *numerical source of truth* for the acute myocardial
infarction (AMI / STEMI) QSP model in this directory.  It re-implements
the equations of ``ami_mrgsolve_model.R`` in numpy + scipy so that every
number quoted in ``README.md`` can be regenerated by anyone with a
Python install (R and mrgsolve are not needed to check the arithmetic).

    python3 ami_reference_check.py             # run every experiment
    python3 ami_reference_check.py 2 8         # run experiments 2 and 8

---------------------------------------------------------------------
THE CLAIM THIS MODEL IS BUILT TO MAKE
---------------------------------------------------------------------
An infarct is not "the artery closed, therefore the muscle died".
It is TWO RACES and ONE BIFURCATION:

  Race 1 (minutes to hours).  A wavefront of necrosis crawls from
      endocardium to epicardium.  Its speed is set by how far residual
      collateral flow falls short of BASAL metabolic demand -- not of
      resting demand.  Tissue that can pay its basal bill stops
      contracting and survives indefinitely; tissue that cannot, dies.
      The clock it races is time-to-reperfusion.
  Race 2 (the first minutes of reflow).  Ischemia leaves two things
      behind: acid, which holds the mitochondrial permeability
      transition pore SHUT, and succinate, which becomes an oxidant
      burst the instant oxygen returns.  Restoring flow washes out the
      acid and ignites the succinate at the same moment.  Reperfusion
      is simultaneously the treatment and a second injury.
  The bifurcation (weeks to months).  Laplace wall stress -> dilation
      -> more wall stress is a POSITIVE loop.  Concentric hypertrophy
      is the negative loop opposing it.  Whether a given infarct
      settles into a stable ventricle or runs away into heart failure
      is a bifurcation, not a dose.

Nothing in the parameter list is called ``golden_hour``,
``critical_infarct_size``, ``no_reflow_switch``, ``reperfusion_injury_
fraction``, ``therapeutic_window`` or ``severity``.  Each of those
appears below only as a computed result.

---------------------------------------------------------------------
STATE VECTOR
---------------------------------------------------------------------
The area at risk (AAR, as a fraction of the LV) is divided into NL = 5
transmural layers, i = 0 (subendocardial) ... 4 (subepicardial).  Each
layer carries 8 states.  The transmural gradient of COLLATERAL FLOW is
the only asymmetry between the layers; everything else about the
wavefront is emergent.

  layer block (8 x 5 = 40)
    E      energy charge (1 = normal ATP/PCr status)
    G      glycogen available to anaerobic glycolysis
    H      tissue acid load (H+/lactate)
    C      cytosolic + mitochondrial Ca2+ load
    P      mPTP open fraction
    NI     necrotic fraction from energy failure  (ischemic)
    NR     necrotic fraction from mPTP opening    (reperfusion)
    SUC    ischemic succinate pool

  global (29)
    ROS MVO THR PLN PLG FIB PAI DAMP NEU M1 M2 IL1 IL6 CRP TGF MYOF
    COL MMP EDVS MASS THIN STUN NE ANG ALD BNP VOL TNI CKMB

  pharmacokinetic (13)
    TNK1 TNK2 TICd TICc METd METc RAMd RAMc EPL EMP COLC CAN CSA

EDVS deserves a note: it is the STRUCTURAL (unstressed) chamber size,
not the observed end-diastolic volume.  Observed EDV is EDVS displaced
along the diastolic pressure-volume relation by the actual filling
pressure.  That is what lets one variable carry both the day-1 dilation
(impaired emptying raises filling pressure) and the six-month dilation
(EDVS itself grows) without conflating the two.

Author: QSP disease-model library (see repository README).
"""

import sys
import math
import numpy as np
from scipy.integrate import solve_ivp

# =====================================================================
# 0.  helpers
# =====================================================================

NL = 5                       # transmural layers


def relu(x):
    return x if x > 0.0 else 0.0


def clip01(x):
    return 0.0 if x < 0.0 else (1.0 if x > 1.0 else x)


def sstep(t, t0, width=0.03):
    """Smooth 0->1 step.  A tanh rather than an if(), so the stiff solver
    never has to integrate across a true discontinuity.  Width is in
    hours; 0.03 h ~ 2 min, far faster than any biology modelled here."""
    if t0 is None:
        return 0.0
    z = (t - t0) / width
    if z > 20.0:
        return 1.0
    if z < -20.0:
        return 0.0
    return 0.5 * (1.0 + math.tanh(z))


def window(t, t0, dur, width=0.03):
    if t0 is None:
        return 0.0
    return sstep(t, t0, width) * (1.0 - sstep(t, t0 + dur, width))


def hill(x, k, n):
    if x <= 0.0:
        return 0.0
    xn = x ** n
    return xn / (k ** n + xn)


# =====================================================================
# 1.  parameters
# =====================================================================
# Every entry is a rate, an affinity, a stoichiometry or an anatomical
# weight.  None of them encodes an outcome.

P = dict(

    # ---- anatomy of the ischemic bed --------------------------------
    AAR      = 0.35,       # area at risk as a fraction of LV (prox. LAD)
    # transmural weights (equal fifths) and the collateral flow gradient.
    # GC is the ONE transmural asymmetry in the whole model; Reimer and
    # Jennings measured exactly this gradient with microspheres in 1977.
    W  = (0.20, 0.20, 0.20, 0.20, 0.20),
    GC = (0.05, 0.35, 0.75, 1.35, 2.50),
    # transmural gradient of susceptibility to microvascular plugging
    GM = (1.60, 1.30, 1.00, 0.70, 0.40),
    COLL     = 0.10,       # mean collateral flow, fraction of normal

    # ---- energetics -------------------------------------------------
    # The survival criterion is BASAL demand -- a real measurable
    # quantity (~20% of resting MVO2 in the arrested heart), not a
    # fitted threshold.  Tissue that can pay it goes akinetic and lives.
    KE       = 30.0,       # 1/h fall of energy charge per unit deficit
    KREC     = 0.35,       # recovery of energy charge per unit surplus
    EFLOOR   = 0.02,       # soft floor keeping energy charge non-negative
    DEM      = 1.00,       # demand scale at baseline rate-pressure product
    DEM_BAS  = 0.20,       # basal (non-contractile) fraction of demand
    F_ANAERO = 0.18,       # maximum anaerobic contribution to supply
    HI50     = 0.50,       # product inhibition of glycolysis by H+
    KDIAST   = 1.00,       # collateral perfusion happens in DIASTOLE, so
                           # slowing the heart lengthens diastole and raises
                           # collateral flow.  This -- not the basal bill -- is
                           # how rate control reaches the wavefront.
    KGLY     = 5.00,       # 1/h glycogen consumption
    KGLYREP  = 0.25,       # 1/h glycogen repletion (needs flow)

    # ---- acidosis ---------------------------------------------------
    KH       = 8.00,       # 1/h H+ generation per unit anaerobic flux
    KHW      = 4.00,       # 1/h H+ washout -- REQUIRES FLOW (pH paradox)

    # ---- ischemic succinate and the oxidant burst -------------------
    KSUC     = 2.50,       # 1/h succinate accumulation per anaerobic flux
    KSUCO    = 6.00,       # 1/h succinate oxidation once oxygen returns
    KROS     = 4.00,       # 1/h ROS per unit succinate burned (RET at CI)
    KROS_N   = 0.60,       # 1/h ROS from neutrophil NADPH oxidase
    KROSD    = 3.00,       # 1/h scavenging

    # ---- calcium ----------------------------------------------------
    KCA      = 1.20,       # 1/h Ca2+ gain from failing SERCA / NCX
    NCA      = 1.50,
    KCA_RP   = 2.50,       # 1/h reflow Ca2+ surge (NHE -> Na -> rev. NCX),
                           #      proportional to flow x accumulated acid
    KCAO     = 3.00,       # 1/h Ca2+ extrusion, requires energy

    # ---- mitochondrial permeability transition pore -----------------
    KP_ON    = 8.00,       # 1/h opening rate
    CA50     = 0.55, NP_CA = 3.0,
    R50      = 0.50, NP_R  = 2.0,
    HP50     = 0.30,       # acid gate: low pH KEEPS THE PORE SHUT
    KP_OFF   = 2.00,       # 1/h resealing, requires energy

    # ---- necrosis ---------------------------------------------------
    KNI      = 0.50,       # 1/h ischemic necrosis rate constant
    NNI      = 4.00,       # power law on energy deficit (no threshold)
    KOSM     = 0.60,       # osmotic / contracture acceleration by acid
    KNR      = 2.50,       # 1/h mPTP-mediated necrosis rate constant

    # ---- microvascular obstruction (no-reflow) ----------------------
    KMVO_E   = 1.20,       # endothelial swelling from energy failure
    KMVO_N   = 0.020,      # neutrophil plugging
    KMVO_P   = 0.40,       # distal atherothrombotic embolisation
    KMVO_R   = 0.012,      # 1/h resolution (weeks)

    # ---- epicardial thrombus ----------------------------------------
    KREG     = 0.30,       # 1/h platelet-driven thrombus (re)growth
    KLYS0    = 0.02,       # 1/h endogenous lysis
    KLYS_PL  = 3.50,       # 1/h plasmin-driven lysis
    KPL50    = 0.35, NPL = 1.5,
    KPCI     = 60.0,       # 1/h mechanical thrombus removal at PCI
    PCI_FAIL = 0.05,       # residual burden after a successful PCI

    # ---- fibrinolytic pharmacology (tenecteplase) -------------------
    TNK_V1 = 4.2, TNK_CL = 6.3, TNK_Q = 1.5, TNK_V2 = 6.6,    # L, L/h
    KPG      = 8.00,       # 1/h plasminogen -> plasmin per unit TNK
    KPLD     = 10.0,       # 1/h plasmin inhibition by alpha2-antiplasmin
    KI_PAI   = 1.20,
    KPGD     = 1.50,       # 1/h systemic plasminogen consumption
    KPGS     = 0.06,       # 1/h plasminogen resynthesis
    KFIBD    = 0.50,       # 1/h fibrinogenolysis per unit plasmin
    KFIBS    = 0.02,       # 1/h fibrinogen resynthesis
    KPAID    = 0.35,
    KPAI_I   = 0.60,       # IL-6 driven PAI-1 induction

    # ---- antiplatelet / anticoagulant -------------------------------
    TIC_KA = 1.20, TIC_F = 0.36, TIC_V = 88.0, TIC_CL = 13.5,
    TIC_EC50 = 0.15, TIC_EMAX = 0.95,
    ASA_EFF  = 0.45,
    HEP_EFF  = 0.50,
    KPLT_PLN = 1.80,       # plasmin ACTIVATES platelets -- which is why a
                           # lytic partly undoes itself (Fitzgerald 1988)

    # ---- beta blockade ----------------------------------------------
    MET_KA = 1.10, MET_F = 0.40, MET_V = 250.0, MET_CL = 60.0,
    MET_EC50 = 0.030, MET_EMAX = 1.00,
    BB_HR    = 0.28,
    BB_NE    = 0.55,

    # ---- RAAS / SGLT2 / anti-inflammatory / mPTP --------------------
    RAM_KA = 1.50, RAM_F = 0.28, RAM_V = 90.0, RAM_CL = 8.0,
    RAM_KD = 0.010, ACEI_EMAX = 0.72,
    EPL_KEL = 0.14, EPL_KD = 30.0, MRA_EMAX = 0.68,
    EMP_KEL = 0.055, EMP_KD = 6.0, SGLT_EMAX = 1.00,
    COLC_KEL = 0.035, COLC_KD = 0.20, COLC_EMAX = 0.45,
    CAN_KEL = 0.0012, CAN_KD = 40.0, CAN_EMAX = 0.85,
    CSA_KEL = 0.058, CSA_KD = 120.0, CSA_EMAX = 0.70,
    ARNI     = 0.0,        # 0/1 sacubitril-valsartan in place of ACEi

    # ---- inflammation and healing -----------------------------------
    KD1 = 1.00, KD2 = 0.35,
    KN1 = 0.25, KN2 = 0.075,
    KM1 = 0.050, KM1D = 0.020,
    KSW = 0.055, KM2D = 0.014, KSW50 = 1.20,
    KI1 = 0.10, KI1D = 0.09,
    KI6 = 0.16, KI6D = 0.12,
    KC1 = 0.09, KC2 = 0.035,
    KT1 = 0.045, KT2 = 0.020,
    KMY = 0.030, KMYD = 0.012,
    KCO = 0.090, KCOD = 0.012, COLMAX = 8.0,
    KMM = 0.050, KMMD = 0.055,
    KSC = 1.10,            # collagen giving half-maximal scar strength
    SCARSET = 0.85,        # scar strength at which the infarct stops
                           # stretching altogether.  A fully cross-linked scar
                           # cannot expand, so this gate must reach exactly
                           # zero -- if it only asymptotes, infarct expansion
                           # becomes a constant dilation drive that never
                           # switches off, and then every infarct diverges
                           # eventually regardless of its size.

    # ---- LV mechanics -----------------------------------------------
    EDV0 = 110.0, ESV0 = 42.0, MASS0 = 150.0,
    V0E = 12.0,            # ESPVR volume intercept, mL
    PED0 = 8.0, NPED = 1.30,
    KPES = 0.50,           # incomplete emptying -> filling pressure
    PESSAT = 1.50,         # and that coupling SATURATES.  Unbounded, it is a
                           # second positive loop with no brake and every
                           # infarct diverges regardless of size.
    KSTIF_COL = 0.50,      # fibrosis stiffening
    SBP0 = 120.0, HR0 = 72.0,
    EDVMAX  = 450.0,       # mL.  NOT biology: a numerical ceiling.  The model
                           # contains no death and no saturating mechanism, so
                           # a divergent trajectory would otherwise run to
                           # infinity.  A run that reaches this ceiling should
                           # be read as "diverged", never as a volume estimate.
    BNPMAX  = 20.0,        # cap on the wall-stress ratio feeding the NP target
    KDIL    = 2.5e-4,      # 1/h eccentric dilation per unit overstress
    KDIL_A  = 0.60,        # angiotensin II amplification
    KDIL_L  = 0.40,        # aldosterone amplification
    KEXP    = 8.0e-4,      # 1/h early infarct expansion while unscarred
    KREVR   = 1.0e-4,      # 1/h reverse remodelling below set point
    KHYP    = 3.0e-4,      # 1/h CONCENTRIC hypertrophy per unit systolic
                           # overstress (Grossman 1975: pressure overload)
    KHYP_E  = 8.0e-4,      # 1/h ECCENTRIC hypertrophy per unit DIASTOLIC
                           # overstress (Grossman 1975: volume overload).  This
                           # is the brake on the dilation loop, and the reason
                           # a normal ventricle can dilate in pregnancy or
                           # athletic training without running away.
    MASSMAX = 300.0,       # g.  Hypertrophy has a ceiling (~2x normal); a
                           # heart does not triple its mass.  Once the brake
                           # saturates, wall stress keeps rising, end-systolic
                           # volume rises with it, and ejection fraction FALLS
                           # -- which is what a decompensating ventricle does.
    KATR    = 1.2e-4,
    KTH     = 3.0e-3,      # 1/h infarct thinning
    THINMAX = 0.55,        # a healed infarct thins to ~45% of the original
                           # wall, not to nothing.  Without this bound the
                           # infarct-zone thickness reaches its floor, the
                           # Laplace stress there becomes arbitrarily large,
                           # and infarct expansion runs away.
    KTHR    = 4.0e-4,
    KST_ON  = 0.55,        # stunning induction by oxidant + Ca load
    KST_OFF = 0.012,       # 1/h stunning recovery (tau ~ 3.5 d)
    EMASS_N = 1.00,        # exponent: wall mass -> end-systolic elastance
    EDIL_N  = 2.00,        # exponent: chamber size -> end-systolic elastance.
                           # From Laplace: generated pressure ~ sigma*h/r ~
                           # sigma*MASS/V, so elastance dP/dV ~ sigma*MASS/V^2.
                           # Without this term elastance is size-independent,
                           # end-systolic volume stays small however far the
                           # ventricle dilates, and ejection fraction RISES
                           # during remodelling -- the opposite of what happens.
    NE_DESENS = 0.18,      # chronic NE -> beta-receptor downregulation

    # ---- neurohormonal ----------------------------------------------
    KNE = 0.15, GNE = 6.0,
    KANG = 0.30, GANG = 4.0, GANG_NE = 0.60,
    # Neurohormonal activation after infarction is NOT driven by low cardiac
    # output alone: heart-rate compensation can hold output near normal while
    # renin and norepinephrine are plainly elevated.  Infarct size is an
    # independent drive (regional hypoperfusion, pain, sympathetic afferents).
    GNE_IS = 6.0, GANG_IS = 4.0,
    KALD = 0.20, GALD = 1.10,
    KBNP = 0.08, NBNP = 2.20,
    KVOL = 0.05, GVOL_A = 0.25, GVOL_N = 0.15, GVOL_S = 0.10,

    # ---- biomarkers -------------------------------------------------
    KTN = 900.0, KTND = 0.035,     # cTnI  (t1/2 ~20 h)
    KCK = 700.0, KCKD = 0.058,     # CK-MB (t1/2 ~12 h)
    WASH_FLOOR = 0.15,             # release into blood needs perfusion

    # ---- host -------------------------------------------------------
    AGE = 62.0,
    PRECOND = 0.0,                 # 0/1 pre-infarction angina
    PRECOND_EFF = 0.35,            # its effect on mPTP opening rate
)

# ---- intervention schedule.  Times are hours from symptom onset. -----
# These are the only decisions in the model.  None = not given.
D0 = dict(
    T_OCC   = 0.0,
    T_PCI   = None,
    T_LYT   = None, TNK_DOSE = 40.0,
    T_ASA   = None, T_TIC = None, T_HEP = None,
    TIC_LOAD = 180.0, TIC_MAINT = 90.0, TIC_TAU = 12.0,
    T_MET_IV = None, MET_IV_DOSE = 15.0,
    T_MET_PO = None, MET_PO = 100.0,
    T_RAM   = None, RAM_PO = 10.0,
    T_EPL   = None, EPL_PO = 50.0,
    T_EMP   = None, EMP_PO = 10.0,
    T_COLC  = None, COLC_PO = 0.5,
    T_CAN   = None, CAN_DOSE = 150.0,
    T_CSA   = None, CSA_DOSE = 175.0,
)

# ---- state layout ----------------------------------------------------
_LAYER = ['E', 'G', 'H', 'C', 'P', 'NI', 'NR', 'SUC']
_GLOBAL = ['ROS', 'MVO', 'THR', 'PLN', 'PLG', 'FIB', 'PAI', 'DAMP', 'NEU',
           'M1', 'M2', 'IL1', 'IL6', 'CRP', 'TGF', 'MYOF', 'COL', 'MMP',
           'EDVS', 'MASS', 'THIN', 'STUN', 'NE', 'ANG', 'ALD', 'BNP',
           'VOL', 'TNI', 'CKMB',
           'TNK1', 'TNK2', 'TICd', 'TICc', 'METd', 'METc', 'RAMd', 'RAMc',
           'EPL', 'EMP', 'COLC', 'CAN', 'CSA']
IDX = {nm: k * NL for k, nm in enumerate(_LAYER)}
IDX.update({nm: len(_LAYER) * NL + k for k, nm in enumerate(_GLOBAL)})
NST = len(_LAYER) * NL + len(_GLOBAL)


# =====================================================================
# 2.  baseline -- the healthy LV must be an EXACT fixed point
# =====================================================================

def geometry(V, MASS):
    """Thin-walled sphere.  V in mL, MASS in g; returns r and h in cm."""
    r = (3.0 * V / (4.0 * math.pi)) ** (1.0 / 3.0)
    sa = 4.0 * math.pi * r * r
    return r, MASS / (1.05 * sa)


def baseline_setpoints(p):
    EDV, ESV, MASS = p['EDV0'], p['ESV0'], p['MASS0']
    r_ed, h_ed = geometry(EDV, MASS)
    r_es, h_es = geometry(ESV, MASS)
    Pes = 0.90 * p['SBP0']
    return dict(
        WS_SET=p['PED0'] * r_ed / (2.0 * h_ed),
        WS_SET_ES=Pes * r_es / (2.0 * h_es),
        EMAX0=Pes / (ESV - p['V0E']),
        CO0=(EDV - ESV) * p['HR0'] / 1000.0,
    )


def initial_state(p):
    y = np.zeros(NST)
    for i in range(NL):
        y[IDX['E'] + i] = 1.0
        y[IDX['G'] + i] = 1.0
    for nm in ('PLG', 'FIB', 'PAI', 'NE', 'ANG', 'ALD', 'BNP', 'VOL'):
        y[IDX[nm]] = 1.0
    # The culprit lesion is already thrombosed at t = 0: plaque rupture is
    # the initial condition, not something the model has to grow.  Whether
    # that thrombus actually obstructs flow is governed separately by the
    # occlusion switch T_OCC, so a healthy run is unaffected.
    y[IDX['THR']] = 1.0
    y[IDX['EDVS']] = p['EDV0']
    y[IDX['MASS']] = p['MASS0']
    return y


# =====================================================================
# 3.  pharmacodynamics, perfusion and mechanics
#     Factored out of the RHS so the reporting code uses THE SAME
#     equations -- there is no second copy that can drift.
# =====================================================================

def drug_pd(t, y, p, d):
    c_tic = max(y[IDX['TICc']], 0.0) / p['TIC_V']
    c_met = max(y[IDX['METc']], 0.0) / p['MET_V']
    c_ram = max(y[IDX['RAMc']], 0.0) / p['RAM_V']
    ipi = p['TIC_EMAX'] * c_tic / (p['TIC_EC50'] + c_tic)
    asa = p['ASA_EFF'] * sstep(t, d['T_ASA'], 0.2)
    hep = p['HEP_EFF'] * sstep(t, d['T_HEP'], 0.2)
    return dict(
        c_tic=c_tic, c_met=c_met, c_ram=c_ram, ipi=ipi, asa=asa, hep=hep,
        plt_inh=1.0 - (1.0 - asa) * (1.0 - 0.85 * ipi),
        bb=p['MET_EMAX'] * c_met / (p['MET_EC50'] + c_met),
        acei=p['ACEI_EMAX'] * c_ram / (p['RAM_KD'] + c_ram),
        mra=p['MRA_EMAX'] * max(y[IDX['EPL']], 0.0) / (p['EPL_KD'] + max(y[IDX['EPL']], 0.0)),
        sglt=p['SGLT_EMAX'] * max(y[IDX['EMP']], 0.0) / (p['EMP_KD'] + max(y[IDX['EMP']], 0.0)),
        colc=p['COLC_EMAX'] * max(y[IDX['COLC']], 0.0) / (p['COLC_KD'] + max(y[IDX['COLC']], 0.0)),
        can=p['CAN_EMAX'] * max(y[IDX['CAN']], 0.0) / (p['CAN_KD'] + max(y[IDX['CAN']], 0.0)),
        csa=p['CSA_EMAX'] * max(y[IDX['CSA']], 0.0) / (p['CSA_KD'] + max(y[IDX['CSA']], 0.0)),
    )


def perfusion(t, y, p, d, rpp, hr):
    """Layer-by-layer flow, substrate supply and affordable contraction.

    The most consequential line here is CF: a layer spends what it can
    afford on contraction and no more.  A layer whose supply still
    covers basal metabolism therefore goes AKINETIC BUT STAYS ALIVE
    (hibernating myocardium) instead of dying -- which is why a
    subepicardial rim survives a permanently occluded artery.
    """
    THR = clip01(y[IDX['THR']])
    MVO = clip01(y[IDX['MVO']])
    occ = sstep(t, d['T_OCC'], 0.02)
    pat = 1.0 - occ * THR                       # epicardial patency 0..1
    # BASAL metabolism is rate-INDEPENDENT: it is by definition the
    # non-contractile cost of ion homeostasis and does not scale with the
    # rate-pressure product.  Letting it scale was an error -- it made a
    # tachycardic patient's subepicardium unable to pay a bill that had risen
    # under it, which wiped out the surviving rim Reimer and Jennings measured.
    # Only CONTRACTILE demand scales with RPP, which is where rpp appears below.
    basal = p['DEM_BAS'] * p['DEM']
    # Collateral flow is DIASTOLIC, so it rises when the heart slows.
    diast = (p['HR0'] / max(hr, 1.0)) ** p['KDIAST']
    out = []
    for i in range(NL):
        q_ante = relu(pat * (1.0 - p['GM'][i] * MVO))
        q_coll = (1.0 - pat) * p['COLL'] * p['GC'][i] * diast
        q = q_ante + q_coll
        qc = min(q, 1.0)
        G = max(y[IDX['G'] + i], 0.0)
        H = max(y[IDX['H'] + i], 0.0)
        E = clip01(y[IDX['E'] + i])
        # anaerobic glycolysis, limited by glycogen AND by its own acid
        anaer = p['F_ANAERO'] * relu(1.0 - qc) * G / (1.0 + H / p['HI50'])
        supply = q + anaer
        afford = clip01((supply / max(p['DEM'] * rpp, 1e-6) - p['DEM_BAS'])
                        / (1.0 - p['DEM_BAS']))
        out.append(dict(q=q, qc=qc, q_ante=q_ante, anaer=anaer, supply=supply,
                        deficit=relu(basal - supply),
                        surplus=relu(supply - basal),
                        CF=afford * E))
    return pat, out


def mechanics(t, y, p, d, sp, pdv):
    """Closed-loop LV mechanics.

    Causal order (it matters):
      NE and drugs        -> HR, SBP -> rate-pressure product -> demand
      demand and flow     -> affordable contraction, layer by layer
      contractile mass    -> Emax    -> ESV
      ESV + volume status -> filling pressure
      filling pressure    -> observed EDV along the diastolic PV curve
      EDV + wall mass     -> Laplace wall stress
    Wall stress then drives dEDVS/dt (the positive loop) and dMASS/dt
    (the negative loop).  That pair is the whole remodelling
    bifurcation; nothing else is needed to make it bistable.
    """
    NI = [clip01(y[IDX['NI'] + i]) for i in range(NL)]
    NR = [clip01(y[IDX['NR'] + i]) for i in range(NL)]
    VIA = [max(1.0 - NI[i] - NR[i], 0.0) for i in range(NL)]
    W = p['W']
    STUN = clip01(y[IDX['STUN']])

    is_lv = p['AAR'] * sum(W[i] * (NI[i] + NR[i]) for i in range(NL))
    ni_lv = p['AAR'] * sum(W[i] * NI[i] for i in range(NL))
    nr_lv = p['AAR'] * sum(W[i] * NR[i] for i in range(NL))

    EDVS = max(y[IDX['EDVS']], 25.0)
    MASS = max(y[IDX['MASS']], 40.0)
    COL = max(y[IDX['COL']], 0.0)
    THIN = clip01(y[IDX['THIN']])
    VOL = max(y[IDX['VOL']], 0.3)
    NE = max(y[IDX['NE']], 0.0)
    ANG = max(y[IDX['ANG']], 0.0)
    ALD = max(y[IDX['ALD']], 0.0)
    BNP = max(y[IDX['BNP']], 0.0)
    # Scar strength is MATURITY, not amount.  A small infarct lays down less
    # collagen in absolute terms but its scar is just as cross-linked, so both
    # the half-maximal constant and the saturating cap have to be scaled by how
    # much of the at-risk bed actually needs a scar.  Without this the
    # normalised scar of a small infarct never matures, infarct expansion never
    # switches off, and every infarct diverges however small it is.
    inj = max(is_lv / max(p['AAR'], 1e-6), 0.02)
    col_n = COL / (COL + p['KSC'] * inj)

    ne_eff = 1.0 + (NE - 1.0) * (1.0 - p['BB_NE'] * pdv['bb'])
    ald_eff = ALD * (1.0 - pdv['mra'])          # MRA blocks the RECEPTOR
    np_eff = BNP * (1.0 + 0.80 * p['ARNI'])

    HR = p['HR0'] * (1.0 + 0.30 * (ne_eff - 1.0)) * (1.0 - p['BB_HR'] * pdv['bb'])
    HR = min(max(HR, 45.0), 160.0)
    SBP = p['SBP0'] * (1.0 + 0.12 * (ANG - 1.0) + 0.08 * (ne_eff - 1.0)
                       - 0.10 * pdv['acei'] - 0.06 * p['ARNI'])
    SBP = min(max(SBP, 70.0), 200.0)
    Pes = 0.90 * SBP
    rpp = (HR / p['HR0']) * (SBP / p['SBP0'])

    pat, lay = perfusion(t, y, p, d, rpp, HR)

    # contractile capacity: the remote zone, plus whatever the at-risk
    # layers can still afford, minus post-reperfusion stunning
    contractile = (1.0 - p['AAR']) + p['AAR'] * sum(
        W[i] * VIA[i] * lay[i]['CF'] * (1.0 - STUN) for i in range(NL))
    emax = (sp['EMAX0'] * max(contractile, 0.02)
            * (MASS / p['MASS0']) ** p['EMASS_N']
            * (1.0 - p['NE_DESENS'] * min(relu(NE - 1.0) / 2.0, 1.0)))
    # The ESPVR volume intercept is NOT fixed: it shifts rightward as the
    # chamber remodels.  Without this, end-systolic volume stays small however
    # far the ventricle dilates, ejection fraction rises instead of falling,
    # end-systolic wall stress never rises, and the concentric-hypertrophy
    # brake never engages -- so every infarct diverges.  One term, and it is
    # what makes the bifurcation have a stable branch at all.
    v0 = p['V0E'] * (EDVS / p['EDV0'])
    emax = emax / (EDVS / p['EDV0']) ** p['EDIL_N']
    ESV = v0 + Pes / max(emax, 0.15)

    # Filling pressure is set by regulated volume status, plus a SATURATING
    # contribution from incomplete emptying.  Diastolic stiffening does not
    # raise the filling pressure -- it reduces the volume reached at that
    # pressure, which is where it belongs (restrictive physiology).
    x = relu(ESV / p['ESV0'] - 1.0)
    Ped = p['PED0'] * VOL * (1.0 + p['KPES'] * x / (1.0 + x / p['PESSAT']))
    EDV = EDVS * ((Ped / p['PED0']) / (1.0 + p['KSTIF_COL'] * col_n)) ** (1.0 / p['NPED'])
    ESV = min(ESV, EDV - 5.0)
    SV = max(EDV - ESV, 5.0)
    CO = SV * HR / 1000.0

    r_ed, h_ed = geometry(EDV, MASS)
    r_es, h_es = geometry(max(ESV, 15.0), MASS)
    h_inf = max(h_ed * (1.0 - THIN), 0.15)

    return dict(
        lay=lay, pat=pat, rpp=rpp, VIA=VIA, W=W,
        is_lv=is_lv, ni_lv=ni_lv, nr_lv=nr_lv, col_n=col_n,
        contractile=contractile, ne_eff=ne_eff, ang_eff=ANG,
        ald_eff=ald_eff, np_eff=np_eff,
        HR=HR, SBP=SBP, Pes=Pes, emax=emax, ESV=ESV, Ped=Ped,
        EDV=EDV, EDVS=EDVS, MASS=MASS, SV=SV, CO=CO, THIN=THIN,
        r_ed=r_ed, h_ed=h_ed, h_inf=h_inf,
        ws_ed=Ped * r_ed / (2.0 * h_ed),
        ws_es=Pes * r_es / (2.0 * h_es),
        ws_inf=Ped * r_ed / (2.0 * h_inf),
    )


# =====================================================================
# 4.  the right-hand side
# =====================================================================

def rhs(t, y, p, d, sp):
    dy = np.zeros(NST)
    W = p['W']

    # -- 4a. drug input rates (mg/h) ---------------------------------
    r_tnk = (d['TNK_DOSE'] / (5.0 / 60.0) * window(t, d['T_LYT'], 5.0 / 60.0)
             if d['T_LYT'] is not None else 0.0)
    if d['T_TIC'] is not None:
        r_tic = (d['TIC_LOAD'] / (5.0 / 60.0) * window(t, d['T_TIC'], 5.0 / 60.0)
                 + d['TIC_MAINT'] / d['TIC_TAU'] * sstep(t, d['T_TIC'] + d['TIC_TAU'], 0.2))
    else:
        r_tic = 0.0
    r_met_iv = (d['MET_IV_DOSE'] / (10.0 / 60.0) * window(t, d['T_MET_IV'], 10.0 / 60.0)
                if d['T_MET_IV'] is not None else 0.0)
    r_met_po = d['MET_PO'] / 24.0 * sstep(t, d['T_MET_PO'], 0.2)
    r_ram = d['RAM_PO'] / 24.0 * sstep(t, d['T_RAM'], 0.2)
    r_epl = d['EPL_PO'] / 24.0 * sstep(t, d['T_EPL'], 0.2)
    r_emp = d['EMP_PO'] / 24.0 * sstep(t, d['T_EMP'], 0.2)
    r_colc = d['COLC_PO'] / 24.0 * sstep(t, d['T_COLC'], 0.2)
    r_can = (d['CAN_DOSE'] / 6.0 * window(t, d['T_CAN'], 6.0, 0.2)
             if d['T_CAN'] is not None else 0.0)
    r_csa = (d['CSA_DOSE'] / (10.0 / 60.0) * window(t, d['T_CSA'], 10.0 / 60.0)
             if d['T_CSA'] is not None else 0.0)

    # -- 4b. pharmacokinetics ----------------------------------------
    c_tnk = max(y[IDX['TNK1']], 0.0) / p['TNK_V1']
    c_tnk2 = max(y[IDX['TNK2']], 0.0) / p['TNK_V2']
    dy[IDX['TNK1']] = r_tnk - p['TNK_CL'] * c_tnk - p['TNK_Q'] * c_tnk + p['TNK_Q'] * c_tnk2
    dy[IDX['TNK2']] = p['TNK_Q'] * c_tnk - p['TNK_Q'] * c_tnk2

    pdv = drug_pd(t, y, p, d)
    dy[IDX['TICd']] = r_tic * p['TIC_F'] - p['TIC_KA'] * max(y[IDX['TICd']], 0.0)
    dy[IDX['TICc']] = p['TIC_KA'] * max(y[IDX['TICd']], 0.0) - p['TIC_CL'] * pdv['c_tic']
    dy[IDX['METd']] = r_met_po * p['MET_F'] - p['MET_KA'] * max(y[IDX['METd']], 0.0)
    dy[IDX['METc']] = (r_met_iv + p['MET_KA'] * max(y[IDX['METd']], 0.0)
                       - p['MET_CL'] * pdv['c_met'])
    dy[IDX['RAMd']] = r_ram * p['RAM_F'] - p['RAM_KA'] * max(y[IDX['RAMd']], 0.0)
    dy[IDX['RAMc']] = p['RAM_KA'] * max(y[IDX['RAMd']], 0.0) - p['RAM_CL'] * pdv['c_ram']
    dy[IDX['EPL']] = r_epl - p['EPL_KEL'] * max(y[IDX['EPL']], 0.0)
    dy[IDX['EMP']] = r_emp - p['EMP_KEL'] * max(y[IDX['EMP']], 0.0)
    dy[IDX['COLC']] = r_colc - p['COLC_KEL'] * max(y[IDX['COLC']], 0.0)
    dy[IDX['CAN']] = r_can - p['CAN_KEL'] * max(y[IDX['CAN']], 0.0)
    dy[IDX['CSA']] = r_csa - p['CSA_KEL'] * max(y[IDX['CSA']], 0.0)

    # -- 4c. mechanics (which also gives us flow per layer) ----------
    m = mechanics(t, y, p, d, sp, pdv)
    lay = m['lay']

    ROS = max(y[IDX['ROS']], 0.0)
    MVO = clip01(y[IDX['MVO']])
    THR = clip01(y[IDX['THR']])
    PLN = max(y[IDX['PLN']], 0.0)
    PLG = clip01(y[IDX['PLG']])
    FIB = max(y[IDX['FIB']], 0.0)
    PAI = max(y[IDX['PAI']], 0.0)
    DAMP = max(y[IDX['DAMP']], 0.0)
    NEU = max(y[IDX['NEU']], 0.0)
    M1 = max(y[IDX['M1']], 0.0)
    M2 = max(y[IDX['M2']], 0.0)
    IL1 = max(y[IDX['IL1']], 0.0)
    IL6 = max(y[IDX['IL6']], 0.0)
    CRP = max(y[IDX['CRP']], 0.0)
    TGF = max(y[IDX['TGF']], 0.0)
    MYOF = clip01(y[IDX['MYOF']])
    COL = max(y[IDX['COL']], 0.0)
    MMP = max(y[IDX['MMP']], 0.0)
    STUN = clip01(y[IDX['STUN']])

    # -- 4d. epicardial thrombus, lysis, fibrinolytic system ---------
    lysis = p['KLYS0'] + p['KLYS_PL'] * hill(PLN, p['KPL50'], p['NPL'])
    plt_drive = (1.0 - pdv['plt_inh']) * (1.0 + p['KPLT_PLN'] * PLN) * (1.0 - pdv['hep'])
    pci = p['KPCI'] * sstep(t, d['T_PCI'], 0.05)
    dy[IDX['THR']] = (p['KREG'] * plt_drive * (1.0 - THR) - lysis * THR
                      - pci * relu(THR - p['PCI_FAIL']))

    tnk_n = c_tnk / 5.0
    dy[IDX['PLN']] = p['KPG'] * tnk_n * PLG / (1.0 + PAI / p['KI_PAI']) - p['KPLD'] * PLN
    dy[IDX['PLG']] = -p['KPGD'] * tnk_n * PLG + p['KPGS'] * (1.0 - PLG)
    dy[IDX['FIB']] = -p['KFIBD'] * PLN + p['KFIBS'] * (1.0 - FIB)
    dy[IDX['PAI']] = p['KPAID'] * (1.0 + p['KPAI_I'] * IL6 - PAI)

    # -- 4e. per-layer ischemia / reperfusion  ==  THE WAVEFRONT -----
    dNI_tot = dNR_tot = reox_flux = mvo_endo = qavg = 0.0
    for i in range(NL):
        L = lay[i]
        E = clip01(y[IDX['E'] + i])
        G = max(y[IDX['G'] + i], 0.0)
        H = max(y[IDX['H'] + i], 0.0)
        C = max(y[IDX['C'] + i], 0.0)
        PO = clip01(y[IDX['P'] + i])
        SU = max(y[IDX['SUC'] + i], 0.0)
        VIA = m['VIA'][i]

        # Energy charge falls only when supply cannot cover BASAL demand.
        # The E/(E+EFLOOR) factor is not biology, it is a soft floor: it
        # keeps the fall near-linear while there is ATP left and stops the
        # state going negative once there is not.
        dy[IDX['E'] + i] = p['KE'] * (-L['deficit'] * E / (E + p['EFLOOR'])
                                      + p['KREC'] * L['surplus'] * (1.0 - E))
        dy[IDX['G'] + i] = -p['KGLY'] * L['anaer'] + p['KGLYREP'] * L['qc'] * (1.0 - G)

        # acid: made anaerobically, removed ONLY by flow.  This is the
        # whole of the pH paradox -- the tissue's own protection against
        # the pore is washed away by the treatment.
        dy[IDX['H'] + i] = p['KH'] * L['anaer'] - p['KHW'] * L['qc'] * H

        # succinate: accumulates while anaerobic, burned the instant
        # oxygen returns.  Its oxidation IS the oxidant burst, which is
        # why the burst is a reperfusion event and is exactly zero in a
        # heart that was never ischemic.
        suc_ox = p['KSUCO'] * L['qc'] * SU
        dy[IDX['SUC'] + i] = p['KSUC'] * L['anaer'] - suc_ox

        # calcium: gained as energy fails, plus a surge at reflow that is
        # proportional to accumulated acid (NHE -> Na+ -> reverse NCX)
        dy[IDX['C'] + i] = (p['KCA'] * relu(1.0 - E) ** p['NCA']
                            + p['KCA_RP'] * L['qc'] * H
                            - p['KCAO'] * E * C)

        # mPTP: needs calcium AND oxidant AND the acid gate to have opened
        ph_gate = 1.0 / (1.0 + H / p['HP50'])
        kon = p['KP_ON'] * (1.0 - pdv['csa']) * (1.0 - p['PRECOND'] * p['PRECOND_EFF'])
        dy[IDX['P'] + i] = (kon * hill(C, p['CA50'], p['NP_CA'])
                            * hill(ROS, p['R50'], p['NP_R']) * ph_gate * (1.0 - PO)
                            - p['KP_OFF'] * PO * E)

        # necrosis: two mechanisms, tracked separately, so the split
        # between them is a RESULT and not an assumption
        dy[IDX['NI'] + i] = (p['KNI'] * relu(1.0 - E) ** p['NNI']
                             * (1.0 + p['KOSM'] * H) * VIA)
        dy[IDX['NR'] + i] = p['KNR'] * PO * VIA
        dNI_tot += W[i] * dy[IDX['NI'] + i]
        dNR_tot += W[i] * dy[IDX['NR'] + i]

        reox_flux += W[i] * VIA * suc_ox
        mvo_endo += W[i] * p['GM'][i] * relu(1.0 - E) ** 3 * min(L['q_ante'], 1.0)
        qavg += W[i] * L['qc']

    dy[IDX['ROS']] = p['KROS'] * reox_flux + p['KROS_N'] * NEU - p['KROSD'] * ROS

    # -- 4f. microvascular obstruction, and its positive feedback ----
    # lysing or crushing a clot sends some of it downstream, so distal
    # embolisation is proportional to the RATE of proximal clot removal
    embol = p['KMVO_P'] * (1.0 - pdv['plt_inh']) * relu(-dy[IDX['THR']])
    dy[IDX['MVO']] = ((p['KMVO_E'] * mvo_endo + p['KMVO_N'] * NEU + embol) * (1.0 - MVO)
                      - p['KMVO_R'] * MVO)

    # -- 4g. inflammation and healing --------------------------------
    il1_act = IL1 * (1.0 - pdv['can'])
    inv = 1.0 / (NEU + 0.05)
    switch = inv / (p['KSW50'] + inv)          # M1->M2 follows PMN clearance

    dy[IDX['DAMP']] = p['KD1'] * (dNI_tot + dNR_tot) - p['KD2'] * DAMP
    dy[IDX['NEU']] = p['KN1'] * DAMP * qavg - p['KN2'] * NEU
    dy[IDX['M1']] = (p['KM1'] * (0.6 * DAMP + 0.4 * NEU)
                     - p['KSW'] * M1 * switch - p['KM1D'] * M1)
    dy[IDX['M2']] = p['KSW'] * M1 * switch - p['KM2D'] * M2
    dy[IDX['IL1']] = p['KI1'] * (M1 + 0.5 * NEU) * (1.0 - pdv['colc']) - p['KI1D'] * IL1
    dy[IDX['IL6']] = (p['KI6'] * (0.7 * il1_act + 0.3 * relu(m['ne_eff'] - 1.0))
                      - p['KI6D'] * IL6)
    dy[IDX['CRP']] = p['KC1'] * IL6 - p['KC2'] * CRP
    dy[IDX['TGF']] = p['KT1'] * M2 - p['KT2'] * TGF
    dy[IDX['MYOF']] = (p['KMY'] * TGF * (1.0 + 0.4 * relu(m['ald_eff'] - 1.0)) * (1.0 - MYOF)
                       - p['KMYD'] * MYOF * (1.0 + 2.0 * m['col_n']))
    inj = max(m['is_lv'] / max(p['AAR'], 1e-6), 0.02)
    dy[IDX['COL']] = (p['KCO'] * MYOF * relu(1.0 - COL / (p['COLMAX'] * inj))
                      - p['KCOD'] * MMP * COL)
    dy[IDX['MMP']] = (p['KMM'] * (0.5 * NEU + 0.3 * M1 + 0.2 * il1_act)
                      - p['KMMD'] * MMP)

    # -- 4h. mechanics  ==  THE BIFURCATION --------------------------
    scar = m['col_n']
    over_ed = relu(m['ws_ed'] / sp['WS_SET'] - 1.0)
    over_es = relu(m['ws_es'] / sp['WS_SET_ES'] - 1.0)
    over_inf = relu(m['ws_inf'] / sp['WS_SET'] - 1.0)
    under_ed = relu(1.0 - m['ws_ed'] / sp['WS_SET'])
    amp = ((1.0 + p['KDIL_A'] * relu(m['ang_eff'] - 1.0)
            + p['KDIL_L'] * relu(m['ald_eff'] - 1.0))
           * (1.0 - 0.15 * pdv['sglt'])
           * (1.0 - 0.10 * min(relu(m['np_eff'] - 1.0) / 3.0, 1.0)))

    room = relu(1.0 - m['EDVS'] / p['EDVMAX'])      # numerical ceiling only
    unhealed = relu(1.0 - scar / p['SCARSET'])
    dy[IDX['EDVS']] = ((p['KDIL'] * m['EDVS'] * over_ed * amp
                        + p['KEXP'] * m['EDVS'] * over_inf * unhealed
                        * m['is_lv'] / max(p['AAR'], 1e-6)) * room
                       - p['KREVR'] * m['EDVS'] * under_ed)
    # SCAR CANNOT HYPERTROPHY.  Only surviving myocardium can add mass in
    # response to wall stress, so the compensatory brake is scaled by the
    # living fraction (1 - infarct fraction).  That single factor is what
    # makes the remodelling bifurcation exist: below some infarct size the
    # surviving wall can still add mass fast enough to hold wall stress at its
    # set point, and above it, it cannot.  No critical infarct size is written
    # anywhere -- it is where these two rates cross.
    alive = relu(1.0 - m['is_lv'])
    headroom = relu(1.0 - m['MASS'] / p['MASSMAX'])
    dy[IDX['MASS']] = (m['MASS'] * alive * headroom
                       * (p['KHYP'] * over_es + p['KHYP_E'] * over_ed)
                       - p['KATR'] * m['MASS'] * relu(1.0 - m['ws_es'] / sp['WS_SET_ES']))
    dy[IDX['THIN']] = (p['KTH'] * over_inf * unhealed * (1.0 + 0.5 * MMP)
                       * relu(p['THINMAX'] - m['THIN'])
                       - p['KTHR'] * m['THIN'] * scar)
    ca_avg = sum(W[i] * max(y[IDX['C'] + i], 0.0) for i in range(NL))
    dy[IDX['STUN']] = (p['KST_ON'] * (ROS + 0.5 * ca_avg) * (1.0 - STUN)
                       - p['KST_OFF'] * STUN)

    # -- 4i. neurohormonal -------------------------------------------
    co_n = m['CO'] / sp['CO0']
    dy[IDX['NE']] = p['KNE'] * (1.0 + p['GNE'] * relu(1.0 - co_n)
                                + p['GNE_IS'] * m['is_lv']
                                - max(y[IDX['NE']], 0.0))
    ang_tgt = ((1.0 + p['GANG'] * relu(1.0 - co_n) + p['GANG_IS'] * m['is_lv']
                + p['GANG_NE'] * relu(m['ne_eff'] - 1.0)) * (1.0 - pdv['acei']))
    dy[IDX['ANG']] = p['KANG'] * (ang_tgt - max(y[IDX['ANG']], 0.0))
    dy[IDX['ALD']] = p['KALD'] * (1.0 + p['GALD'] * relu(y[IDX['ANG']] - 1.0)
                                  - max(y[IDX['ALD']], 0.0))
    ws_ratio = min(m['ws_ed'] / sp['WS_SET'], p['BNPMAX'])
    dy[IDX['BNP']] = p['KBNP'] * (ws_ratio ** p['NBNP'] - max(y[IDX['BNP']], 0.0))
    # the natriuretic-peptide effect on plasma volume saturates; it is a
    # counter-regulator, not an unlimited diuretic
    vol_tgt = max(1.0 + p['GVOL_A'] * relu(m['ald_eff'] - 1.0)
                  - p['GVOL_N'] * min(relu(m['np_eff'] - 1.0), 1.5)
                  - p['GVOL_S'] * pdv['sglt'], 0.6)
    dy[IDX['VOL']] = p['KVOL'] * (vol_tgt - max(y[IDX['VOL']], 0.3))

    # -- 4j. biomarkers.  Release needs perfusion -- which is why a
    #        reperfused infarct gives a tall EARLY troponin peak and an
    #        occluded one a late blunted peak at a LARGER true size.
    wash = p['WASH_FLOOR'] + (1.0 - p['WASH_FLOOR']) * qavg
    ndot = (dNI_tot + dNR_tot) * p['AAR']
    dy[IDX['TNI']] = p['KTN'] * ndot * wash - p['KTND'] * max(y[IDX['TNI']], 0.0)
    dy[IDX['CKMB']] = p['KCK'] * ndot * wash - p['KCKD'] * max(y[IDX['CKMB']], 0.0)

    return dy


# =====================================================================
# 5.  driver
# =====================================================================

def derived(t, y, p, d, sp):
    """Reported quantities, computed through mechanics() -- the same code
    the ODE right-hand side uses, so a report can never disagree with the
    simulation that produced it."""
    pdv = drug_pd(t, y, p, d)
    m = mechanics(t, y, p, d, sp, pdv)
    N = [clip01(y[IDX['NI'] + i]) + clip01(y[IDX['NR'] + i]) for i in range(NL)]
    return dict(
        t=t,
        IS=100.0 * m['is_lv'], IS_ISCH=100.0 * m['ni_lv'], IS_REP=100.0 * m['nr_lv'],
        RPFRAC=100.0 * m['nr_lv'] / m['is_lv'] if m['is_lv'] > 1e-9 else 0.0,
        SALV=100.0 * (p['AAR'] - m['is_lv']) / p['AAR'],
        LAYERS=[100.0 * v for v in N],
        MVO=100.0 * clip01(y[IDX['MVO']]) * p['AAR'],
        EDV=m['EDV'], EDVS=m['EDVS'], ESV=m['ESV'], MASS=m['MASS'],
        EF=100.0 * m['SV'] / m['EDV'], CO=m['CO'], HR=m['HR'], SBP=m['SBP'],
        WS=m['ws_ed'], WS_INF=m['ws_inf'], PED=m['Ped'],
        H_ED=m['h_ed'], H_INF=m['h_inf'], CONTR=m['contractile'],
        THIN=100.0 * clip01(y[IDX['THIN']]), SCAR=m['col_n'],
        TNI=max(y[IDX['TNI']], 0.0), CKMB=max(y[IDX['CKMB']], 0.0),
        BNP=y[IDX['BNP']], CRP=y[IDX['CRP']], FIB=y[IDX['FIB']],
        PAT=100.0 * m['pat'], STUN=100.0 * clip01(y[IDX['STUN']]),
        CEIL=m['EDVS'] > 0.98 * p['EDVMAX'],
    )


def _grid(tend):
    """Output grid.  A STEMI trajectory needs minute resolution in the
    first hours and daily resolution at six months, so a uniform grid is
    the wrong shape -- it is either too coarse to see the mPTP transient
    or absurdly large.  Resolution is piecewise instead."""
    pieces = []
    for a, b, step in ((0.0, 6.0, 0.01), (6.0, 48.0, 0.10),
                       (48.0, 24.0 * 30, 1.0), (24.0 * 30, 24.0 * 400, 6.0)):
        if tend <= a:
            break
        pieces.append(np.arange(a, min(b, tend) + step * 0.5, step))
    g = np.unique(np.concatenate(pieces + [np.array([0.0, tend])]))
    return g[g <= tend + 1e-9]


def _breakpoints(d, tend):
    """Every time at which an input turns on or off.  The integrator is
    restarted at each one so no smooth ramp is ever stepped over -- this
    is what lets a single call span a two-minute mPTP transient and a
    365-day remodelling trajectory without a tiny max_step everywhere."""
    bp = {0.0, float(tend)}
    for k in ('T_OCC', 'T_PCI', 'T_LYT', 'T_ASA', 'T_TIC', 'T_HEP',
              'T_MET_IV', 'T_MET_PO', 'T_RAM', 'T_EPL', 'T_EMP',
              'T_COLC', 'T_CAN', 'T_CSA'):
        v = d.get(k)
        if v is not None and 0.0 <= v <= tend:
            bp.add(float(v))
    if d.get('T_TIC') is not None and d['T_TIC'] + d['TIC_TAU'] <= tend:
        bp.add(float(d['T_TIC'] + d['TIC_TAU']))
    for extra in (0.5, 2.0, 12.0, 48.0, 24.0 * 7, 24.0 * 30):
        if extra < tend:
            bp.add(float(extra))
    return sorted(bp)


def _ceiling_event(t, y, p, d, sp):
    """Terminal event: chamber growth has reached the ceiling.

    Integration STOPS here, for two reasons.  First, nothing past this point
    is meaningful -- the model has no death and no other saturating mechanism,
    so a divergent run just grinds along the ceiling.  Second, it grinds very
    slowly: pinned against the ceiling the system is stiff, and those runs
    dominated the total runtime while contributing no information.
    """
    return y[IDX['EDVS']] - 0.995 * p['EDVMAX']


_ceiling_event.terminal = True
_ceiling_event.direction = 1


def run(tend=24.0, over=None, dose=None):
    """Piecewise-staged integration: the horizon is split at every input
    event; each segment gets a finely stepped first half hour and then a
    step size proportional to its own length."""
    p = dict(P)
    if over:
        p.update(over)
    d = dict(D0)
    if dose:
        d.update(dose)
    sp = baseline_setpoints(p)
    y = initial_state(p)
    tgrid = _grid(float(tend))

    bps = _breakpoints(d, tend)
    ts, ys = [], []
    stopped = False
    for a, b in zip(bps[:-1], bps[1:]):
        if stopped:
            break
        if b <= a:
            continue
        subs = ([(a, a + 0.5, 0.02), (a + 0.5, b, max(0.20, min(4.0, (b - a) / 40.0)))]
                if b - a > 0.5 else [(a, b, 0.02)])
        for (aa, bb, ms) in subs:
            if bb <= aa:
                continue
            te = tgrid[(tgrid > aa) & (tgrid <= bb)]
            te_run = np.unique(np.append(te, bb))     # always reach bb
            sol = solve_ivp(rhs, (aa, bb), y, args=(p, d, sp), method='LSODA',
                            t_eval=te_run, rtol=1e-6, atol=1e-9, max_step=ms,
                            events=_ceiling_event)
            if not sol.success:
                raise RuntimeError(f"segment [{aa:.3f},{bb:.3f}]: {sol.message}")
            if len(te) and sol.y.shape[1]:
                keep = np.isin(sol.t, te)
                ts.append(sol.t[keep])
                ys.append(sol.y[:, keep])
            if sol.y.shape[1]:
                y = sol.y[:, -1].copy()
            if sol.status == 1:                 # ceiling reached: stop here
                if sol.t_events[0].size and (not ts or ts[-1][-1] < sol.t_events[0][0]):
                    ts.append(np.array([float(sol.t_events[0][0])]))
                    ys.append(np.asarray(sol.y_events[0][0]).reshape(-1, 1))
                    y = np.asarray(sol.y_events[0][0]).copy()
                stopped = True
                break

    y0 = initial_state(p).reshape(-1, 1)
    sol = type('Sol', (), {})()
    sol.t = np.concatenate([np.array([0.0])] + ts) if ts else np.array([0.0])
    sol.y = np.concatenate([y0] + ys, axis=1) if ys else y0
    return p, d, sp, sol


def at(sol, p, d, sp, hours):
    k = int(np.argmin(np.abs(sol.t - hours)))
    return derived(sol.t[k], sol.y[:, k], p, d, sp)


def summary(tend=24.0, **kw):
    p, d, sp, sol = run(tend=tend, **kw)
    out = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
    out.update(
        TNI_PEAK=float(np.max(sol.y[IDX['TNI']])),
        TNI_AUC=float(np.trapezoid(sol.y[IDX['TNI']], sol.t)),
        TNI_TPEAK=float(sol.t[int(np.argmax(sol.y[IDX['TNI']]))]),
        CK_PEAK=float(np.max(sol.y[IDX['CKMB']])),
        CK_TPEAK=float(sol.t[int(np.argmax(sol.y[IDX['CKMB']]))]),
        MVO_MAX=float(np.max(sol.y[IDX['MVO']]) * 100 * p['AAR']),
        CRP_PEAK=float(np.max(sol.y[IDX['CRP']])),
        FIB_MIN=float(np.min(sol.y[IDX['FIB']])),
        PLN_AUC=float(np.trapezoid(sol.y[IDX['PLN']], sol.t)),
        sol=sol, p=p, d=d, sp=sp,
    )
    return out


def time_to_patency(sol, thresh=0.70):
    pat = 1.0 - np.clip(sol.y[IDX['THR']], 0, 1)
    idx = np.where(pat >= thresh)[0]
    return float(sol.t[idx[0]]) if len(idx) else float('nan')


def ceiling_day(p, sol):
    """Day on which chamber growth reached EDVMAX, or None.

    Past that point the trajectory is NOT a volume prediction: the model has no
    death and no other saturating mechanism, so a divergent run simply runs into
    the ceiling.  What such a run reports is a VERDICT (this ventricle does not
    stabilise), never a number of millilitres."""
    hit = np.where(sol.y[IDX['EDVS']] >= 0.98 * p['EDVMAX'])[0]
    return float(sol.t[hit[0]] / 24.0) if len(hit) else None


def verdict_of(p, sol, growth):
    if ceiling_day(p, sol) is not None:
        return 'DIVERGED'
    return 'divergent' if growth > 12.0 else ('creeping' if growth > 4.0 else 'stable')


def time_to_fraction(p, d, sp, sol, frac):
    """Time at which the infarct reaches `frac` of its own final size."""
    isv = np.array([derived(sol.t[k], sol.y[:, k], p, d, sp)['IS']
                    for k in range(0, len(sol.t), 5)])
    tt = sol.t[::5]
    if isv[-1] <= 1e-9:
        return float('nan')
    j = np.where(isv >= frac * isv[-1])[0]
    return float(tt[j[0]]) if len(j) else float('nan')


# =====================================================================
# 6.  standard regimens
# =====================================================================

def rx_pci(t_pci, t_drug=None):
    t_drug = max((t_pci - 0.5) if t_drug is None else t_drug, 0.05)
    return dict(T_PCI=t_pci, T_ASA=t_drug, T_TIC=t_drug, T_HEP=t_drug)


def rx_lysis(t_lyt):
    t0 = max(t_lyt - 0.1, 0.05)
    return dict(T_LYT=t_lyt, T_ASA=t0, T_TIC=t0, T_HEP=t0)


def rx_gdmt(t0=24.0, ace=True, bb=True, mra=True, sglt=True):
    r = {}
    if ace:
        r['T_RAM'] = t0
    if bb:
        r['T_MET_PO'] = t0
    if mra:
        r['T_EPL'] = t0 + 24.0
    if sglt:
        r['T_EMP'] = t0
    return r


# =====================================================================
# 7.  experiments
# =====================================================================

def hdr(n, title):
    print()
    print("=" * 78)
    print(f" EXPERIMENT {n} -- {title}")
    print("=" * 78)


def exp0():
    hdr(0, "Sanity: an uninjured LV must be an exact fixed point")
    p, d, sp, sol = run(tend=24.0 * 365, dose=dict(T_OCC=None))
    a = derived(sol.t[0], sol.y[:, 0], p, d, sp)
    b = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
    print(f"  set points: WS_ed {sp['WS_SET']:.4f}, WS_es {sp['WS_SET_ES']:.4f}, "
          f"Emax0 {sp['EMAX0']:.4f} mmHg/mL, CO0 {sp['CO0']:.4f} L/min")
    print(f"  {'':>10} {'t = 0':>12} {'t = 365 d':>12}")
    for k in ('EDV', 'ESV', 'EF', 'MASS', 'IS', 'BNP', 'WS', 'CONTR', 'CO'):
        print(f"  {k:>10} {a[k]:12.5f} {b[k]:12.5f}")
    drift = abs(b['EDV'] - a['EDV']) / a['EDV'] * 100
    print(f"  -> 1-year EDV drift with no infarct: {drift:.5f} %  "
          f"({'OK' if drift < 0.5 else 'FAIL'})")


def exp1():
    hdr(1, "The wavefront: permanent occlusion, necrosis layer by layer")
    print("""
Nothing tells the model that necrosis should begin subendocardially.
The only transmural asymmetry in the parameter list is the collateral
flow gradient GC.  The wavefront is what that gradient does over time
once each layer's supply is compared with its BASAL metabolic bill.
""")
    p, d, sp, sol = run(tend=48.0, dose=dict(T_OCC=0.0))
    fin = derived(sol.t[-1], sol.y[:, -1], p, d, sp)['IS']
    print("  collateral flow by layer (fraction of normal): "
          + ", ".join(f"{p['COLL']*g:.3f}" for g in p['GC']))
    print(f"  basal metabolic requirement: {p['DEM_BAS']:.3f}\n")
    print(f"{'t (h)':>7} " + " ".join(f"{'L'+str(i+1)+' %':>7}" for i in range(NL))
          + f" {'IS %LV':>8} {'% of AAR':>9} {'% of final':>11}")
    for th in (0.5, 0.75, 1, 1.5, 2, 3, 4, 6, 9, 12, 24, 48):
        o = at(sol, p, d, sp, th)
        print(f"{th:7.2f} " + " ".join(f"{v:7.1f}" for v in o['LAYERS'])
              + f" {o['IS']:8.2f} {100-o['SALV']:9.1f} {100*o['IS']/fin:11.1f}")
    print()
    for frac in (0.25, 0.50, 0.75, 0.90, 0.95):
        print(f"  time to {int(frac*100):>3d}% of the final infarct: "
              f"{time_to_fraction(p, d, sp, sol, frac)*60:7.1f} min")
    print(f"\n  final infarct size (48 h, artery never opened) = {fin:.2f} %LV "
          f"= {100*fin/(100*p['AAR']):.1f}% of the area at risk")
    print("  -> a subepicardial rim survives on collateral flow alone, because it")
    print("     can still pay its basal bill.  That rim is the Reimer-Jennings")
    print("     result, and it appears nowhere in the parameter list.")


def exp2():
    hdr(2, "Time to reperfusion: the salvage curve, and the golden hour")
    print("""
Same model, same parameters; only T_PCI moves.  There is no parameter
called 'golden hour' and no time-dependent efficacy term.  Salvage falls
off because the wavefront has already gone past.
""")
    print(f"{'reperf (min)':>13} {'IS %LV':>8} {'salvage %':>10} {'ischemic':>9} "
          f"{'reperf':>8} {'RI frac %':>10} {'MVO %LV':>8} {'EF d2 %':>8}")
    rows = []
    for tmin in (15, 30, 45, 60, 75, 90, 120, 150, 180, 240, 300, 360, 480, 720):
        o = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_pci(tmin / 60.0)))
        rows.append((tmin, o))
        print(f"{tmin:13d} {o['IS']:8.2f} {o['SALV']:10.1f} {o['IS_ISCH']:9.2f} "
              f"{o['IS_REP']:8.2f} {o['RPFRAC']:10.1f} {o['MVO']:8.2f} {o['EF']:8.1f}")
    o = summary(tend=48.0, dose=dict(T_OCC=0.0))
    print(f"{'never':>13} {o['IS']:8.2f} {o['SALV']:10.1f} {o['IS_ISCH']:9.2f} "
          f"{o['IS_REP']:8.2f} {o['RPFRAC']:10.1f} {o['MVO']:8.2f} {o['EF']:8.1f}")
    print("\n  marginal value of time -- muscle saved per 30 min of delay avoided:")
    for a, b in zip(rows[:-1], rows[1:]):
        dt = b[0] - a[0]
        dI = b[1]['IS'] - a[1]['IS']
        print(f"    {a[0]:4d} -> {b[0]:4d} min : {dI:6.2f} %LV over {dt:3d} min "
              f"= {dI/dt*30:6.3f} %LV per 30 min")
    print("\n  -> the marginal value of time is far higher in the first hour than")
    print("     after four.  'Time is muscle' is a hyperbola, not a line, and the")
    print("     model was never told so.")


def exp3():
    hdr(3, "The clock speed is the collateral: same delay, different infarct")
    print("""
The clinical variable is time-to-reperfusion.  The model says time only
matters relative to how fast the wavefront moves, and that speed is set
by how far collateral flow falls short of basal demand.
""")
    print(f"{'COLL':>6} " + " ".join(f"{str(m)+' min':>9}" for m in (30, 60, 90, 180, 360))
          + f" {'never':>9} {'t50 (min)':>11}")
    for coll in (0.02, 0.05, 0.10, 0.15, 0.20, 0.30):
        vals = [summary(tend=48.0, over=dict(COLL=coll),
                        dose=dict(T_OCC=0.0, **rx_pci(m / 60.0)))['IS']
                for m in (30, 60, 90, 180, 360)]
        p, d, sp, sol = run(tend=48.0, over=dict(COLL=coll), dose=dict(T_OCC=0.0))
        nev = derived(sol.t[-1], sol.y[:, -1], p, d, sp)['IS']
        t50 = time_to_fraction(p, d, sp, sol, 0.5) * 60
        print(f"{coll:6.2f} " + " ".join(f"{v:9.2f}" for v in vals)
              + f" {nev:9.2f} {t50:11.1f}")
    print("\n  -> the 'golden hour' is a property of the patient's collateral bed,")
    print("     not of the clock.  A well-collateralised heart can lose less muscle")
    print("     after six hours than a poorly collateralised one loses after one.")


def exp4():
    hdr(4, "Reperfusion is also an injury: the pH paradox, minute by minute")
    print("""
Reperfusion necrosis comes from mPTP opening, and the pore is gated by
tissue acid: gate = 1/(1+H/HP50).  Acid keeps the pore SHUT, and acid is
removed only by flow.  Restoring flow therefore strips the protection at
the very instant it ignites the succinate pool.
""")
    for tmin in (45, 90, 180):
        p, d, sp, sol = run(tend=8.0, dose=dict(T_OCC=0.0, **rx_pci(tmin / 60.0)))
        t0 = tmin / 60.0
        print(f"\n  reperfusion at {tmin} min -- subendocardial layer (L1)")
        print(f"    {'t-Trep (min)':>13} {'H+':>7} {'succ':>7} {'ROS':>7} {'Ca':>7} "
              f"{'gate':>6} {'mPTP':>7} {'E':>6} {'NR % of layer':>14}")
        for dtm in (-5, 0, 1, 2, 3, 5, 10, 20, 40, 80, 160):
            tt = t0 + dtm / 60.0
            if tt < 0 or tt > 8.0:
                continue
            k = int(np.argmin(np.abs(sol.t - tt)))
            H = sol.y[IDX['H']][k]
            print(f"    {dtm:13d} {H:7.3f} {sol.y[IDX['SUC']][k]:7.3f} "
                  f"{sol.y[IDX['ROS']][k]:7.3f} {sol.y[IDX['C']][k]:7.3f} "
                  f"{1/(1+H/p['HP50']):6.3f} {sol.y[IDX['P']][k]:7.4f} "
                  f"{sol.y[IDX['E']][k]:6.3f} {100*sol.y[IDX['NR']][k]:14.2f}")
    print("""
  -> the pore opens in the first few minutes of reflow and is essentially
     finished inside half an hour.  That is why cardioprotection has to be
     on board before the balloon, and why the window for this mechanism is
     minutes rather than hours.  No window parameter exists in the model.
""")


def exp5():
    hdr(5, "mPTP inhibition: a window in minutes, and a prize that moves")
    print("""
Cyclosporine multiplies the pore opening rate by (1 - csa).  It is one IV
dose; the only thing that changes between rows is WHEN.
""")
    tpci = 1.5
    base = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_pci(tpci)))
    print(f"  reference: PCI at {tpci*60:.0f} min, no CsA -> IS {base['IS']:.2f} %LV "
          f"(of which {base['IS_REP']:.2f} %LV is reperfusion necrosis)")
    print(f"\n{'CsA given':>15} {'IS %LV':>8} {'delta':>8} {'% redn':>8} "
          f"{'reperf comp':>12} {'MVO %LV':>8}")
    for off in (-30, -10, -2, 0, 2, 5, 10, 20, 30, 60, 120):
        tcsa = tpci + off / 60.0
        if tcsa <= 0:
            continue
        o = summary(tend=48.0, dose=dict(T_OCC=0.0, T_CSA=tcsa, **rx_pci(tpci)))
        print(f"{'Trep%+d min' % off:>15} {o['IS']:8.2f} {o['IS']-base['IS']:8.2f} "
              f"{100*(base['IS']-o['IS'])/base['IS']:8.1f} {o['IS_REP']:12.2f} "
              f"{o['MVO']:8.2f}")
    print("\n  and the size of the prize depends on how long the ischemia lasted:")
    print(f"\n{'ischemia (min)':>15} {'IS no CsA':>10} {'IS + CsA':>9} {'% redn':>8} "
          f"{'RI frac % without':>18}")
    for tmin in (20, 30, 45, 60, 90, 120, 180, 240, 360):
        a = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_pci(tmin / 60.0)))
        b = summary(tend=48.0, dose=dict(T_OCC=0.0, T_CSA=tmin / 60.0,
                                        **rx_pci(tmin / 60.0)))
        red = 100 * (a['IS'] - b['IS']) / a['IS'] if a['IS'] > 1e-6 else 0.0
        print(f"{tmin:15d} {a['IS']:10.2f} {b['IS']:9.2f} {red:8.1f} {a['RPFRAC']:18.1f}")
    print("""
  -> the benefit is NON-MONOTONE in ischemic duration: nothing to save
     before the wavefront arrives, nothing left to save once it has passed.
     A pragmatic trial enrolling a wide range of ischemic times therefore
     dilutes its own effect size.  This model does not prove cyclosporine
     works -- CIRCUS and CYCLE were both neutral -- but it does show that
     the effect it predicts is exactly the kind a pragmatic trial loses.
""")


def exp6():
    hdr(6, "Fibrinolysis versus primary PCI: where the crossover falls, and why")
    print("""
Two different mechanisms of reperfusion sharing one clock.
  - Tenecteplase is available immediately, but patency has to be EARNED by
    plasmin, and plasmin also activates platelets, so the artery can reocclude.
  - PCI restores patency in one step, but it arrives later.
Nothing tells the model which is better, or when.
""")
    tfmc = 0.75
    print(f"  first medical contact at {tfmc*60:.0f} min from symptom onset.\n")
    o_lyt = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_lysis(tfmc)))
    p, d, sp, sol = run(tend=8.0, dose=dict(T_OCC=0.0, **rx_lysis(tfmc)))
    pat = 1.0 - np.clip(sol.y[IDX['THR']], 0, 1)
    t50 = time_to_patency(sol, 0.50)
    print(f"  lytic (the artery DOES open): bolus at {tfmc*60:.0f} min, 50% patency "
          f"at {t50*60:.0f} min, peak patency {100*pat.max():.0f}%,")
    print(f"         IS {o_lyt['IS']:.2f} %LV, fibrinogen nadir "
          f"{o_lyt['FIB_MIN']:.2f}, plasmin AUC {o_lyt['PLN_AUC']:.4f}")

    # ---- part A: one deterministic patient ---------------------------------
    print("\n  PART A -- one deterministic patient, artery opens in both arms")
    print(f"{'PCI delay (min)':>16} {'PCI at (min)':>13} {'IS PCI':>8} "
          f"{'IS lytic':>9} {'PCI - lytic':>12} {'winner':>8}")
    prev, loA, hiA = None, None, None
    pci_is = {}
    for dl in (0, 15, 30, 45, 60, 75, 90, 105, 120, 150, 180):
        tp = tfmc + dl / 60.0
        o = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_pci(tp, t_drug=tfmc)))
        pci_is[dl] = o['IS']
        diff = o['IS'] - o_lyt['IS']
        if prev is not None and prev[1] < 0 <= diff:
            loA, hiA = prev[0], dl
        prev = (dl, diff)
        print(f"{dl:16d} {tp*60:13.0f} {o['IS']:8.2f} {o_lyt['IS']:9.2f} "
              f"{diff:12.2f} {'PCI' if diff < 0 else 'lytic':>8}")
    print(f"\n  -> crossover at a PCI-related delay of only {loA}-{hiA} min, FAR")
    print("     shorter than the 60-120 min in the guidelines.  The model is not")
    print("     wrong here; the comparison is.  A single deterministic trajectory")
    print("     cannot represent the fact that in roughly 40% of lytic patients the")
    print("     artery does not open at all.  Note also WHY partial patency is")
    print("     nearly as good as full patency here: once antegrade flow exceeds")
    print("     basal demand (0.20) the wavefront stops, so even TIMI-2 flow")
    print("     arrests it.  That is physiology, not a modelling shortcut.")

    # ---- part B: the mixture ----------------------------------------------
    # These two weights are NOT model parameters.  They are the angiographic
    # patency RATES observed in trials (about 60% TIMI-3 at 90 min for a
    # fibrinolytic with full adjunctive therapy; about 95% for primary PCI).
    # Feeding them in as subpopulation weights is the only honest way to
    # compare a stochastic-success therapy with a near-deterministic one.
    P_LYT, P_PCI = 0.60, 0.95
    is_fail = summary(tend=48.0, dose=dict(T_OCC=0.0))['IS']   # artery never opens
    exp_lyt = P_LYT * o_lyt['IS'] + (1.0 - P_LYT) * is_fail
    print("\n  PART B -- the same comparison as a two-subpopulation mixture")
    print(f"    lysis succeeds ({100*P_LYT:.0f}%): IS {o_lyt['IS']:.2f} %LV; "
          f"fails ({100*(1-P_LYT):.0f}%): IS {is_fail:.2f} %LV"
          f"  ->  expected {exp_lyt:.2f} %LV")
    print(f"    PCI succeeds ({100*P_PCI:.0f}%): as tabulated; fails "
          f"({100*(1-P_PCI):.0f}%): IS {is_fail:.2f} %LV")
    print(f"\n{'PCI delay (min)':>16} {'E[IS] PCI':>11} {'E[IS] lytic':>12} "
          f"{'difference':>11} {'winner':>8}")
    prev, loB, hiB = None, None, None
    for dl in sorted(pci_is):
        e_pci = P_PCI * pci_is[dl] + (1.0 - P_PCI) * is_fail
        diff = e_pci - exp_lyt
        if prev is not None and prev[1] < 0 <= diff:
            loB, hiB = prev[0], dl
        prev = (dl, diff)
        print(f"{dl:16d} {e_pci:11.2f} {exp_lyt:12.2f} {diff:11.2f} "
              f"{'PCI' if diff < 0 else 'lytic':>8}")
    if loB is not None:
        print(f"\n  -> crossover at a PCI-related delay between {loB} and {hiB} min.")
    else:
        print("\n  -> no crossover inside the range tested.")
    print("     That is the guideline window (Nallamothu & Bates 2003: 60 min;")
    print("     Pinto 2006: 40-180 min depending on the patient).  The point is")
    print("     WHERE it came from: not from flow physiology, but from the two")
    print("     patency RATES.  The crossover is a statement about how OFTEN each")
    print("     therapy works, not about how well it works when it does.")

    # ---- part C: reocclusion ---------------------------------------------
    print("\n  PART C -- reocclusion after lysis: what the P2Y12 inhibitor is for")
    print(f"{'regimen':>32} {'patency 90 min %':>17} {'patency 24 h %':>15} {'IS %LV':>8}")
    for lbl, ds in (("lytic alone", dict(T_LYT=tfmc)),
                    ("lytic + aspirin", dict(T_LYT=tfmc, T_ASA=tfmc)),
                    ("lytic + ASA + heparin", dict(T_LYT=tfmc, T_ASA=tfmc, T_HEP=tfmc)),
                    ("lytic + ASA + hep + ticagrelor", rx_lysis(tfmc))):
        o = summary(tend=48.0, dose=dict(T_OCC=0.0, **ds))
        s = o['sol']
        k90 = int(np.argmin(np.abs(s.t - (tfmc + 1.5))))
        k24 = int(np.argmin(np.abs(s.t - 24.0)))
        print(f"{lbl:>32} {100*(1-s.y[IDX['THR']][k90]):17.1f} "
              f"{100*(1-s.y[IDX['THR']][k24]):15.1f} {o['IS']:8.2f}")
    print("\n  -> plasmin activates platelets, so a lytic partly undoes itself.")
    print("     The entire antiplatelet benefit here comes from one term, KPLT_PLN.")


def exp7():
    hdr(7, "Microvascular obstruction is not infarct size")
    print("""
MVO has its own equation -- endothelial energy failure graded
transmurally, neutrophil plugging, distal embolisation, slow resolution
-- and it feeds BACK on flow, so no-reflow perpetuates the ischemia that
caused it.  Nothing forces it to track infarct size.
""")
    print(f"{'scenario':>34} {'IS %LV':>8} {'MVO %LV':>9} {'MVO/IS':>7} "
          f"{'EDV d180':>9} {'EF d180':>8}")
    scen = (("PCI 90 min, rich collateral", dict(COLL=0.20), rx_pci(1.5)),
            ("PCI 90 min, poor collateral", dict(COLL=0.03), rx_pci(1.5)),
            ("PCI 90 min, heavy embolisation", dict(KMVO_P=1.6), rx_pci(1.5)),
            ("PCI 90 min, minimal embolisation", dict(KMVO_P=0.05), rx_pci(1.5)),
            ("PCI 240 min", {}, rx_pci(4.0)),
            ("prehospital lysis 45 min", {}, rx_lysis(0.75)))
    for lbl, ov, ds in scen:
        a = summary(tend=48.0, over=ov, dose=dict(T_OCC=0.0, **ds))
        p, d, sp, sol = run(tend=24.0 * 180, over=ov,
                            dose=dict(T_OCC=0.0, **ds, **rx_gdmt(24.0)))
        c = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        div = ' *DIVERGED' if ceiling_day(p, sol) is not None else ''
        print(f"{lbl:>34} {a['IS']:8.2f} {a['MVO_MAX']:9.2f} "
              f"{a['MVO_MAX']/max(a['IS'],1e-6):7.2f} {c['EDV']:9.1f} {c['EF']:8.1f}"
              f"{div}")
    print("  (* a starred row hit the growth ceiling: its d180 columns are a"
          " verdict, not millilitres)")
    print("\n  matched-infarct comparison -- the point of the experiment:")
    res = {}
    for tag, ov in (('minimal', dict(KMVO_P=0.05)), ('heavy', dict(KMVO_P=1.6))):
        a = summary(tend=48.0, over=ov, dose=dict(T_OCC=0.0, **rx_pci(1.5)))
        p, d, sp, sol = run(tend=24.0 * 180, over=ov,
                            dose=dict(T_OCC=0.0, **rx_pci(1.5), **rx_gdmt(24.0)))
        res[tag] = (a, derived(sol.t[-1], sol.y[:, -1], p, d, sp))
        print(f"    {tag+' embolisation':>22}: IS {a['IS']:5.2f} %LV, "
              f"MVO {a['MVO_MAX']:5.2f} %LV -> d180 EDV {res[tag][1]['EDV']:6.1f} mL, "
              f"EF {res[tag][1]['EF']:5.1f}%")
    dIS = abs(res['heavy'][0]['IS'] - res['minimal'][0]['IS'])
    dED = res['heavy'][1]['EDV'] - res['minimal'][1]['EDV']
    print(f"  -> infarct sizes differ by {dIS:.2f} %LV, six-month EDV by {dED:.1f} mL.")
    print("     MVO carries prognostic information that infarct size does not,")
    print("     which is what de Waha's 2017 pooled CMR analysis reported.")


def exp8():
    hdr(8, "The remodelling bifurcation: a critical infarct size, computed")
    print("""
Laplace: wall stress = P*r/(2h).  Dilation raises r, which raises stress,
which drives dilation -- a POSITIVE loop.  Concentric and eccentric
hypertrophy raise wall mass, which lowers stress -- the NEGATIVE loop.
Crucially, SCAR CANNOT HYPERTROPHY, so the brake is scaled by the
surviving fraction of the ventricle.  Whether a ventricle converges or
diverges is therefore a race between two rates.

READ THE VOLUMES ONLY ON THE STABLE BRANCH.  A run marked DIVERGED has
run into the model's growth ceiling; past that point it is reporting a
verdict (this ventricle does not stabilise), not millilitres.  No GDMT
anywhere in this table.
""")
    print(f"{'reperf (min)':>13} {'IS %LV':>8} {'EDV d30':>9} {'EDV d90':>9} "
          f"{'EDV d180':>9} {'growth % (30-180 d)':>20} {'EF d180':>8} "
          f"{'BNP d180':>9} {'ceiling day':>12}  {'verdict':<10}")
    for tmin in (20, 40, 60, 90, 120, 180, 240, 360, None):
        ds = dict(T_OCC=0.0)
        lbl = 'never' if tmin is None else str(tmin)
        if tmin is not None:
            ds.update(rx_pci(tmin / 60.0))
        p, d, sp, sol = run(tend=24.0 * 365, dose=ds)
        mk = {dd: at(sol, p, d, sp, 24.0 * dd) for dd in (30, 90, 180)}
        g = 100 * (mk[180]['EDV'] - mk[30]['EDV']) / mk[30]['EDV']
        cd = ceiling_day(p, sol)
        print(f"{lbl:>13} {mk[180]['IS']:8.2f} {mk[30]['EDV']:9.1f} "
              f"{mk[90]['EDV']:9.1f} {mk[180]['EDV']:9.1f} {g:20.1f} "
              f"{mk[180]['EF']:8.1f} {mk[180]['BNP']:9.2f} "
              f"{('day %.0f' % cd) if cd else '-':>12}  "
              f"{verdict_of(p, sol, g):<10}")
    print("\n  sweeping the area at risk (PCI fixed at 6 h) to locate the")
    print("  separatrix -- a number that appears nowhere in the parameter list:")
    print(f"{'AAR':>6} {'IS %LV':>8} {'EDV d30':>9} {'EDV d180':>9} "
          f"{'growth %':>9} {'EF d180':>8} {'BNP':>7}  {'verdict':<10}")
    for aar in (0.05, 0.08, 0.10, 0.12, 0.15, 0.20, 0.25, 0.30, 0.35, 0.45):
        p, d, sp, sol = run(tend=24.0 * 365, over=dict(AAR=aar),
                            dose=dict(T_OCC=0.0, **rx_pci(6.0)))
        m30 = at(sol, p, d, sp, 24.0 * 30)
        m180 = at(sol, p, d, sp, 24.0 * 180)
        g = 100 * (m180['EDV'] - m30['EDV']) / m30['EDV']
        print(f"{aar:6.2f} {m180['IS']:8.2f} {m30['EDV']:9.1f} {m180['EDV']:9.1f} "
              f"{g:9.1f} {m180['EF']:8.1f} {m180['BNP']:7.2f}  "
              f"{verdict_of(p, sol, g):<10}")
    print("""
  -> the separatrix is where two rate constants cross, and it moves with the
     surviving fraction of the ventricle.  The model's untreated separatrix
     sits at a SMALLER infarct than the 18-20 %LV usually quoted -- but the
     quoted figure comes from cohorts on guideline therapy.  Experiment 9
     tests exactly that.
""")


def exp9():
    hdr(9, "Neurohormonal blockade moves the separatrix, not the infarct")
    print("""
Guideline therapy starts at 24 h -- long after the wavefront has
finished.  It therefore cannot change infarct size, and below it does
not.  What it changes is whether the mechanical loop diverges, by
lowering the angiotensin/aldosterone amplification of the dilation term.
""")
    tpci = 3.0
    regs = (("no GDMT", dict(ace=False, bb=False, mra=False, sglt=False)),
            ("ACEi alone", dict(ace=True, bb=False, mra=False, sglt=False)),
            ("beta-blocker alone", dict(ace=False, bb=True, mra=False, sglt=False)),
            ("ACEi + BB", dict(ace=True, bb=True, mra=False, sglt=False)),
            ("ACEi + BB + MRA", dict(ace=True, bb=True, mra=True, sglt=False)),
            ("ACEi + BB + MRA + SGLT2i", dict(ace=True, bb=True, mra=True, sglt=True)))
    print(f"{'regimen':>26} {'IS %LV':>8} {'EDV d30':>9} {'EDV d180':>9} "
          f"{'growth %':>9} {'EF d180':>8} {'BNP':>7} {'ANG':>6} {'scar':>6}  "
          f"{'verdict':<10}")
    for lbl, kw in regs:
        p, d, sp, sol = run(tend=24.0 * 365,
                            dose=dict(T_OCC=0.0, **rx_pci(tpci), **rx_gdmt(24.0, **kw)))
        m30 = at(sol, p, d, sp, 24.0 * 30)
        m180 = at(sol, p, d, sp, 24.0 * 180)
        g = 100 * (m180['EDV'] - m30['EDV']) / m30['EDV']
        k180 = int(np.argmin(np.abs(sol.t - 24.0 * 180)))
        print(f"{lbl:>26} {m180['IS']:8.2f} {m30['EDV']:9.1f} {m180['EDV']:9.1f} "
              f"{g:9.1f} {m180['EF']:8.1f} {m180['BNP']:7.2f} "
              f"{sol.y[IDX['ANG']][k180]:6.2f} {m180['SCAR']:6.3f}  "
              f"{verdict_of(p, sol, g):<10}")
    print("\n  where does the separatrix move to?  (AAR swept, PCI at 6 h)")
    print(f"{'AAR':>6} {'IS %LV':>8} {'no GDMT: growth %':>18} {'verdict':>10}"
          f" | {'full GDMT: growth %':>20} {'verdict':>10}")
    for aar in (0.08, 0.12, 0.15, 0.20, 0.25, 0.30, 0.35, 0.45):
        row = []
        for kw in (dict(ace=False, bb=False, mra=False, sglt=False),
                   dict(ace=True, bb=True, mra=True, sglt=True)):
            p, d, sp, sol = run(tend=24.0 * 365, over=dict(AAR=aar),
                                dose=dict(T_OCC=0.0, **rx_pci(6.0), **rx_gdmt(24.0, **kw)))
            m30 = at(sol, p, d, sp, 24.0 * 30)
            m180 = at(sol, p, d, sp, 24.0 * 180)
            g = 100 * (m180['EDV'] - m30['EDV']) / m30['EDV']
            row.append((g, m180['IS'], verdict_of(p, sol, g)))
        print(f"{aar:6.2f} {row[0][1]:8.2f} {row[0][0]:18.1f} {row[0][2]:>10}"
              f" | {row[1][0]:20.1f} {row[1][2]:>10}")
    print("""
  -> guideline therapy leaves infarct size untouched (it starts after the
     wavefront is over) and moves the separatrix instead.  That is the whole
     mechanism of SAVE, AIRE and EPHESUS in one table, and the model was given
     no anti-remodelling term -- only receptor blockade upstream of the
     dilation amplifier.
""")


def exp10():
    hdr(10, "IV beta-blockade before reperfusion: rate control is part of the clock")
    print("""
Metoprolol has no anti-necrotic term anywhere in this model.  Coronary
perfusion happens mostly in DIASTOLE, so slowing the heart lengthens
diastole and raises COLLATERAL flow -- and collateral flow is exactly what
the wavefront is racing.  The timing prediction is therefore forced: it
can only help while the wavefront is still moving.

Note what this implies, and note that the model was not tuned to avoid it.
Rate control cannot change the BASAL metabolic bill (basal metabolism is
rate-independent by definition), so it cannot rescue tissue whose supply is
already below basal -- it can only raise supply.  The predicted effect on
infarct size is therefore SMALL.
""")
    tpci = 2.0
    base = summary(tend=48.0, dose=dict(T_OCC=0.0, **rx_pci(tpci)))
    print(f"  reference (PCI at {tpci*60:.0f} min, no IV metoprolol): "
          f"IS {base['IS']:.2f} %LV")
    print(f"\n{'IV metoprolol at':>18} {'IS %LV':>8} {'% redn':>8} {'HR at Trep':>11} "
          f"{'MVO %LV':>8}")
    for tm in (0.25, 0.5, 0.75, 1.0, 1.5, 1.95, 2.5, 4.0, 6.0):
        o = summary(tend=48.0, dose=dict(T_OCC=0.0, T_MET_IV=tm, **rx_pci(tpci)))
        hr = at(o['sol'], o['p'], o['d'], o['sp'], tpci)['HR']
        tag = "  (after reperfusion)" if tm > tpci else ""
        print(f"{'%.0f min' % (tm*60):>18} {o['IS']:8.2f} "
              f"{100*(base['IS']-o['IS'])/base['IS']:8.1f} {hr:11.1f} "
              f"{o['MVO']:8.2f}{tag}")
    print("""
  -> the DIRECTION and the TIMING are right: a reduction when given early,
     decaying to nothing once the artery is open.  That is the
     METOCARD-CNIC / EARLY-BAMI split, and it falls out of coronary
     haemodynamics rather than out of a cardioprotection parameter.
  -> the MAGNITUDE is not.  METOCARD-CNIC reported roughly a 20% reduction
     in infarct size; this model gives 2%.  The only channel by which rate
     control reaches the wavefront here is diastolic collateral flow, and
     the model has none of the neutrophil-platelet mechanism Ibanez's group
     later described.  KDIAST could have been raised until the number
     matched, which is precisely why it was not.
""")


def exp11():
    hdr(11, "Anti-inflammatory therapy: the same drug helps and harms")
    print("""
IL-1beta does two opposite things here, with no extra machinery: it
drives MMP, which thins the infarct, and it drives the
M1 -> M2 -> TGF-beta -> myofibroblast -> collagen cascade that BUILDS
the scar.  Blocking it must therefore have an optimum in dose and time.
""")
    tpci = 3.0
    print(f"{'anti-IL-1beta start':>21} {'IS %LV':>8} {'scar d14':>9} "
          f"{'thinning % d30':>15} {'EDV d180':>9} {'EF d180':>8} {'CRP peak':>9}")
    for tcan in (None, 0.1, 6.0, 24.0, 72.0, 24.0 * 7, 24.0 * 30):
        ds = dict(T_OCC=0.0, **rx_pci(tpci), **rx_gdmt(24.0))
        if tcan is not None:
            ds['T_CAN'] = tcan
        p, d, sp, sol = run(tend=24.0 * 180, dose=ds)
        o = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        lbl = ('none' if tcan is None
               else (f"{tcan:.1f} h" if tcan < 48 else f"day {tcan/24:.0f}"))
        print(f"{lbl:>21} {o['IS']:8.2f} {at(sol,p,d,sp,24*14)['SCAR']:9.3f} "
              f"{at(sol,p,d,sp,24*30)['THIN']:15.1f} {o['EDV']:9.1f} {o['EF']:8.1f} "
              f"{np.max(sol.y[IDX['CRP']]):9.2f}")
    print("\n  dose-response at a fixed start time of 6 h:")
    print(f"{'CAN_EMAX':>10} {'scar d14':>9} {'thinning % d30':>15} {'EDV d180':>9} "
          f"{'EF d180':>8} {'CRP peak':>9}")
    for em in (0.0, 0.25, 0.50, 0.70, 0.85, 0.95, 0.995):
        p, d, sp, sol = run(tend=24.0 * 180, over=dict(CAN_EMAX=em),
                            dose=dict(T_OCC=0.0, T_CAN=6.0, **rx_pci(tpci),
                                      **rx_gdmt(24.0)))
        o = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        print(f"{em:10.3f} {at(sol,p,d,sp,24*14)['SCAR']:9.3f} "
              f"{at(sol,p,d,sp,24*30)['THIN']:15.1f} {o['EDV']:9.1f} {o['EF']:8.1f} "
              f"{np.max(sol.y[IDX['CRP']]):9.2f}")
    print("\n  colchicine (NLRP3 -> IL-1beta; weaker, later, oral) for comparison:")
    for tc in (None, 24.0, 24.0 * 3):
        ds = dict(T_OCC=0.0, **rx_pci(tpci), **rx_gdmt(24.0))
        if tc is not None:
            ds['T_COLC'] = tc
        p, d, sp, sol = run(tend=24.0 * 180, dose=ds)
        o = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        lbl = 'none' if tc is None else f"day {tc/24:.0f}"
        print(f"    colchicine from {lbl:>7}: CRP peak {np.max(sol.y[IDX['CRP']]):6.2f}, "
              f"scar d14 {at(sol,p,d,sp,24*14)['SCAR']:.3f}, "
              f"EDV d180 {o['EDV']:6.1f} mL, EF {o['EF']:5.1f}%")


def exp12():
    hdr(12, "Biomarkers: troponin is a rate integral, and washout is real")
    print("""
Release into the blood is multiplied by perfusion.  Nobody told the
model about the 'washout peak'.
""")
    print(f"{'scenario':>26} {'TnI peak':>9} {'t peak h':>9} {'TnI AUC':>9} "
          f"{'CK peak':>8} {'CK tpk':>7} {'true IS':>8} {'AUC / IS':>9}")
    for lbl, ds in (("PCI 60 min", rx_pci(1.0)), ("PCI 120 min", rx_pci(2.0)),
                    ("PCI 240 min", rx_pci(4.0)), ("lytic 45 min", rx_lysis(0.75)),
                    ("no reperfusion", {})):
        o = summary(tend=120.0, dose=dict(T_OCC=0.0, **ds))
        print(f"{lbl:>26} {o['TNI_PEAK']:9.1f} {o['TNI_TPEAK']:9.2f} {o['TNI_AUC']:9.0f} "
              f"{o['CK_PEAK']:8.1f} {o['CK_TPEAK']:7.2f} {o['IS']:8.2f} "
              f"{o['TNI_AUC']/max(o['IS'],1e-6):9.0f}")
    print("""
  -> the reperfused artery gives an early, tall peak; the occluded artery a
     late, blunted one at a LARGER true infarct.  Peak troponin therefore
     ranks these patients in the wrong order, while AUC per unit infarct
     stays far flatter.  This is why enzymatic infarct sizing needs the
     area under the curve and not the peak.
""")


def exp13():
    hdr(13, "The bleeding side of the trade-off, and the elderly patient")
    print("""
Plasmin cannot tell coronary fibrin from intracranial fibrin.  The model
tracks systemic plasmin exposure and fibrinogen depletion.  The
haemorrhage index below is a REPORTING FORMULA built from plasmin AUC and
age -- it is not a fitted risk model and must not be read as one.
""")
    tfmc = 0.75
    print(f"{'age':>5} {'TNK mg':>8} {'plasmin AUC':>13} {'fibrinogen nadir':>17} "
          f"{'ICH index':>10} {'IS %LV':>8}")
    for age in (50, 62, 75, 85):
        for dose in (40.0, 20.0):
            o = summary(tend=48.0, over=dict(AGE=age),
                        dose=dict(T_OCC=0.0, TNK_DOSE=dose, **rx_lysis(tfmc)))
            ich = 0.9 * o['PLN_AUC'] * (1.0 + 0.055 * (age - 50))
            print(f"{age:5d} {dose:8.1f} {o['PLN_AUC']:13.4f} {o['FIB_MIN']:17.3f} "
                  f"{ich:10.3f} {o['IS']:8.2f}")
    print("""
  -> halving the lytic dose roughly halves the haemorrhage index but also
     costs patency and therefore muscle.  That trade is the STREAM
     half-dose-in-the-elderly amendment, reached here from one PK/PD chain.
""")


def exp14():
    hdr(14, "Cutting single edges: which loop is load-bearing?")
    print("""
Structural sensitivity.  Each row zeroes or clamps exactly ONE mechanism
and reruns the same scenario: PCI at 90 min, GDMT from 24 h.
""")
    tpci = 1.5

    def one(lbl, ov):
        a = summary(tend=48.0, over=ov, dose=dict(T_OCC=0.0, **rx_pci(tpci)))
        p, d, sp, sol = run(tend=24.0 * 180, over=ov,
                            dose=dict(T_OCC=0.0, **rx_pci(tpci), **rx_gdmt(24.0)))
        c = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        div = ' *DIV' if ceiling_day(p, sol) is not None else ''
        print(f"{lbl:>44} {a['IS']:8.2f} {a['IS_REP']:9.2f} {a['MVO_MAX']:8.2f} "
              f"{c['EDV']:9.1f} {c['EF']:8.1f}{div}")

    print(f"{'perturbation':>44} {'IS %LV':>8} {'reperf':>9} {'MVO':>8} "
          f"{'EDV d180':>9} {'EF d180':>8}")
    one("(intact model)", {})
    one("no mPTP (KP_ON = 0)", dict(KP_ON=0.0))
    one("no reflow Ca surge (KCA_RP = 0)", dict(KCA_RP=0.0))
    one("acid gate removed (HP50 = 1e6)", dict(HP50=1e6))
    one("no acid at all (KH = 0)", dict(KH=0.0))
    one("instant acid washout (KHW x 20)", dict(KHW=80.0))
    one("no succinate (KSUC = 0)", dict(KSUC=0.0))
    one("no oxidant burst (KROS = 0)", dict(KROS=0.0))
    one("flat collateral gradient (GC all 1.0)", dict(GC=(1.0,) * NL))
    one("no collateral flow (COLL = 0)", dict(COLL=0.0))
    one("no MVO feedback (GM all 0)", dict(GM=(0.0,) * NL))
    one("no anaerobic reserve (F_ANAERO = 0)", dict(F_ANAERO=0.0))
    one("no glycolytic product inhibition (HI50 1e6)", dict(HI50=1e6))
    one("no dilation loop (KDIL = 0)", dict(KDIL=0.0))
    one("no hypertrophy brake (KHYP = 0)", dict(KHYP=0.0))
    one("no infarct expansion (KEXP = 0)", dict(KEXP=0.0))
    one("preconditioned host (PRECOND = 1)", dict(PRECOND=1.0))
    print("""
  -> the load-bearing structures are the COLLATERAL GRADIENT (delete it and
     the wavefront stops being transmural), the BASAL-DEMAND survival
     criterion, and the DILATION loop (delete it and every infarct is
     benign at six months).  Removing the acid gate shifts necrosis from
     the reperfusion column into the ischemic column without changing the
     total very much -- an internal consistency check, since the pore then
     simply opens earlier.
""")


def exp15():
    hdr(15, "Seven reference scenarios, end to end")
    print("""
The scenarios shipped in the mrgsolve model file, integrated to 180
days.  These are the numbers the R model must reproduce.
""")
    scen = (
        ("S1 late presenter, artery never opened, no GDMT", {}, dict(T_OCC=0.0)),
        ("S2 primary PCI 90 min + DAPT, no GDMT", {}, dict(T_OCC=0.0, **rx_pci(1.5))),
        ("S3 primary PCI 90 min + full GDMT", {},
         dict(T_OCC=0.0, **rx_pci(1.5), **rx_gdmt(24.0))),
        ("S4 prehospital lysis 45 min + PCI 4 h + GDMT", {},
         dict(T_OCC=0.0, T_PCI=4.0, **rx_lysis(0.75), **rx_gdmt(24.0))),
        ("S5 PCI 90 min + GDMT + IV metoprolol + CsA + colchicine", {},
         dict(T_OCC=0.0, T_MET_IV=0.6, T_CSA=1.45, T_COLC=24.0,
              **rx_pci(1.5), **rx_gdmt(24.0))),
        ("S6 large AAR 0.45, PCI 4 h, full GDMT", dict(AAR=0.45),
         dict(T_OCC=0.0, **rx_pci(4.0), **rx_gdmt(24.0))),
        ("S7 small AAR 0.18, PCI 3 h, full GDMT", dict(AAR=0.18),
         dict(T_OCC=0.0, **rx_pci(3.0), **rx_gdmt(24.0))),
    )
    print(f"{'scenario':>56} {'IS':>6} {'MVO':>6} {'TnI pk':>7} {'EF d1':>7} "
          f"{'EF d180':>8} {'EDV d180':>9} {'BNP':>6} {'scar':>6}")
    print("  (*DIV = hit the growth ceiling; its late columns are a verdict, "
          "not millilitres)")
    for lbl, ov, ds in scen:
        a = summary(tend=48.0, over=ov, dose=ds)
        p, d, sp, sol = run(tend=24.0 * 180, over=ov, dose=ds)
        c = derived(sol.t[-1], sol.y[:, -1], p, d, sp)
        div = ' *DIV' if ceiling_day(p, sol) is not None else ''
        print(f"{lbl:>56} {a['IS']:6.2f} {a['MVO_MAX']:6.2f} {a['TNI_PEAK']:7.1f} "
              f"{at(sol,p,d,sp,24.0)['EF']:7.1f} {c['EF']:8.1f} {c['EDV']:9.1f} "
              f"{c['BNP']:6.2f} {c['SCAR']:6.3f}{div}")


EXPS = {0: exp0, 1: exp1, 2: exp2, 3: exp3, 4: exp4, 5: exp5, 6: exp6, 7: exp7,
        8: exp8, 9: exp9, 10: exp10, 11: exp11, 12: exp12, 13: exp13,
        14: exp14, 15: exp15}


def main():
    args = sys.argv[1:]
    keys = sorted(EXPS) if not args else [int(a) for a in args]
    print("=" * 78)
    print(" ACUTE MYOCARDIAL INFARCTION (STEMI) -- QSP reference output")
    print(f" {NST} ODEs | {NL} transmural layers | scipy LSODA")
    print("=" * 78)
    for k in keys:
        EXPS[k]()
    print()
    print("=" * 78)
    print(" end of reference output")
    print("=" * 78)


if __name__ == '__main__':
    main()
