##  Traumatic Spinal Cord Injury (SCI) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Traumatic spinal cord injury — an IRREVERSIBLE primary mechanical
##             insult (contusion / persistent compression / axonal shear)
##             followed by a TIME-WINDOWED secondary injury cascade:
##             compression + cord swelling raise intraspinal pressure (ISP) and
##             lower spinal cord perfusion pressure (SCPP = MAP - ISP) ->
##             ischemia -> ATP failure, SUR1-TRPM4/AQP4-mediated cytotoxic edema
##             (a compression-edema-ischemia VICIOUS CYCLE) -> glutamatergic
##             excitotoxicity -> Ca2+ overload / calpain -> lipid peroxidation
##             and peroxynitrite -> neutrophil then M1/M2 macrophage
##             neuroinflammation -> caspase-mediated neuron and oligodendrocyte
##             death -> demyelination, cystic cavitation and a CSPG/Nogo-A glial
##             scar that closes the plasticity window. What survives is a small
##             fraction of descending tracts; what is recovered on top of it is
##             rehabilitation- and plasticity-dependent circuit reorganization.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 43 ODE compartments — PK for methylprednisolone (2-cmt), riluzole
##             (depot+central), minocycline, glibenclamide, intrathecal
##             anti-Nogo-A antibody, baclofen and pregabalin, plus cumulative
##             steroid exposure; hemodynamics (neurogenic shock, MAP);
##             the secondary cascade (ischemia, edema, glutamate, Ca2+, ROS,
##             neutrophils, cytokines, M1/M2, caspase activity, debris);
##             tissue state (neurons, oligodendrocytes, remyelination ceiling,
##             spared descending axons, GFAP, CSPG, lesion index); recovery
##             (critical period, plasticity, atrophy, ISNCSCI motor score);
##             and the LATE complications that reflex reorganization creates
##             (spasticity, neuropathic pain, neurogenic bladder, autonomic
##             dysreflexia), plus respiratory function and sublesional BMD.
##  Time     : DAYS (1 h = 1/24 d).  Default horizon 365 d; the acute cascade
##             lives in the first 72 h, the plasticity window in the first
##             ~3 months, and BMD/atrophy over the whole year.
##  Units    : drug compartments in dose-proportional au (mg/kg-equivalent for
##             methylprednisolone, mg-equivalent for oral/IV agents — this
##             library's standard surrogate for a full mechanistic plasma PK
##             when the disease-relevant PD is what matters); MAP in mmHg;
##             ISNCSCI total motor score 0-100; modified Ashworth 0-4; pain
##             NRS 0-10; vital capacity in % predicted; BMD as a fraction of
##             baseline; lesion index 0-1 (multiply by CAV_ML for a mL-scale
##             read-out); cascade species in normalized au.
##  Scenarios: 18 prebuilt — see SCI_simulate_scenarios() at the bottom,
##             including the two window experiments the model exists to make
##             quantitative (methylprednisolone start time; time to surgical
##             decompression) and the early-vs-late rehabilitation contrast.
##
##  THREE THINGS THIS MODEL IS BUILT TO SHOW
##  ----------------------------------------------------------------------------
##  (1) TIMING DOMINATES DOSE. Efficacy of every neuroprotectant is the integral
##      of its effect against a cascade flux that has largely run to completion
##      within ~72 h. Toxicity, by contrast, is a function of DOSE ALONE. The
##      modelled complication index of methylprednisolone is IDENTICAL whether
##      the drug is given at 1 h or at 24 h, while its benefit falls ~4-fold —
##      which is the shape of the NASCIS II post-hoc "<8 h" story, and why a
##      48-h infusion (NASCIS III) buys ~1.4x the complication index for no
##      further benefit.
##  (2) THE SURROGATE AND THE ENDPOINT ARE NOT THE SAME VARIABLE. MOTOR is a
##      steep saturating Hill function of effective descending drive CONN
##      (TH50 = 0.22, HILL = 2.2). DOUBLING spared drive is worth ~+4 ISNCSCI
##      motor points in a severe AIS A patient (below the ~5-point measurement
##      noise) and ~+29 points in the mid-range. A neuroprotectant can cut
##      lesion volume by the same ~9% in every grade and be simultaneously
##      mechanistically real and clinically undetectable — which is an argument
##      about WHO you enroll, not about whether the drug works.
##  (3) THERE ARE TWO CLOCKS, AND RECOVERY CREATES ITS OWN PATHOLOGY. The
##      neuroprotection clock runs in hours; the plasticity clock runs in weeks
##      and is shut by the CSPG scar (CRIT decays with rate K_CRIT*(1+
##      K_CRIT_SCAR*CSPG)). The SAME rehabilitation dose given from day 120
##      instead of day 14 yields a fraction of the plasticity. Meanwhile the
##      return of sublesional reflex excitability — a marker of "recovery" —
##      is exactly what generates spasticity, detrusor overactivity and
##      autonomic dysreflexia: the same bladder distension that is harmless in
##      the flaccid first week is a hypertensive emergency at 6 months.
##
##  Anchors  : Bracken 1990 N Engl J Med 322:1405 (NASCIS II, the <8 h post-hoc
##             window) and Bracken 1997 JAMA 277:1597 (NASCIS III, 48-h arm
##             toxicity); Fehlings 2012 PLoS One 7:e32037 (STASCIS: early <24 h
##             decompression, ~2.8x odds of >=2-grade AIS improvement) and
##             Badhiwala 2021 Lancet Neurol 20:117 (pooled individual-patient
##             analysis of decompression timing); Fehlings 2023/RISCIS riluzole
##             programme and Grossman 2014 J Neurotrauma 31:239 (NACTN riluzole
##             pharmacokinetics/safety); Casha 2012 Brain 135:1224 (minocycline
##             phase 2); Simard 2007-2012 (SUR1-TRPM4 / glibenclamide in CNS
##             edema); Squair 2017 Neurology 89:1660 and Hawryluk 2015
##             J Neurotrauma 32:1958 (spinal cord perfusion pressure, MAP
##             targets); NISCI anti-Nogo-A programme (Kucher 2018 Neurorehabil
##             Neural Repair 32:578); Angeli 2018 N Engl J Med 379:1244 and
##             Wagner 2018 Nature 563:65 (epidural stimulation); Fawcett 2007
##             Spinal Cord 45:190 and EMSCI natural-history trajectories
##             (spontaneous recovery by AIS grade — the comparator every arm
##             must beat); Kirshblum 2011 J Spinal Cord Med 34:535 (ISNCSCI).
##             Every quantitative statement above is reproduced by
##             sci_reference_model.py, a dependency-free implementation of this
##             same 43-state system (see sci_reference_output.txt).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of traumatic spinal cord injury linking the primary mechanical insult,
cord perfusion (MAP - ISP), the compression-edema-ischemia vicious cycle,
excitotoxicity, oxidative stress, neutrophil/M1/M2 neuroinflammation, caspase-
mediated neuron and oligodendrocyte death, demyelination, glial scar formation,
axonal sparing, rehabilitation-driven plasticity within a closing critical
period, and the ISNCSCI motor score — with PK/PD for methylprednisolone,
riluzole, minocycline, glibenclamide, intrathecal anti-Nogo-A antibody,
baclofen and pregabalin, and with the late reflex-reorganization complications
(spasticity, neuropathic pain, neurogenic bladder, autonomic dysreflexia),
respiratory function and sublesional bone loss.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / injury descriptors
LEVEL_IDX    : 5     : Neurological level index (C1-C8=1-8, T1-T12=9-20, L1-L5=21-25)
AIS_INIT     : 1     : Initial AIS grade (1=A, 2=B, 3=C, 4=D)
DISRUPT      : -1    : Override for mechanically disrupted tract fraction (<0 = derive from AIS)
COMP0        : 0.60  : Residual mechanical cord compression before surgery (0-1)
SUBLESIONAL_LMN: 1   : 1 = suprasacral lesion (reflex arc intact), <1 = conus/cauda

//--- Interventions (timing switches; all times in DAYS)
TDECOMP      : 1.0   : d, time of surgical decompression (999 = never)
DECOMP_EFF   : 0.95  : Fraction of compression relieved by surgery
VASO         : 0     : 1 = MAP >= 85-90 mmHg haemodynamic protocol active
VASO_GAIN    : 20    : mmHg of MAP support achieved by vasopressors
TVASO_END    : 7.0   : d, duration of the MAP protocol
REHAB        : 0     : 0-1 activity-based rehabilitation intensity
TREHAB_START : 14    : d, rehabilitation start
TREHAB_END   : 180   : d, rehabilitation end
FES          : 0     : 0-1 functional electrical stimulation / FES cycling
ESTIM        : 0     : 1 = epidural electrical stimulation active
TESTIM_START : 120   : d, epidural stimulation start
CHASE        : 0     : 0-1 chondroitinase ABC effect (preclinical)
ROCKI        : 0     : 0-1 Rho-ROCK inhibitor effect
ANTIMUSC     : 0     : 0-1 antimuscarinic / onabotulinumtoxinA bladder effect

//--- Methylprednisolone PK/PD (NASCIS II: 30 mg/kg bolus + 5.4 mg/kg/h x 23 h)
KOUT_MP      : 6.0   : 1/day, elimination (t1/2 ~ 2.8 h)
KTR_MP       : 4.0   : 1/day, central<->peripheral transfer
EC50_MP      : 8.0   : au, central amount for half-maximal effect
EMAX_MP_LP   : 0.60  : Max fractional inhibition of lipid peroxidation (non-genomic)
EMAX_MP_CYT  : 0.50  : Max fractional cytokine-production suppression (genomic, NF-kB)
EMAX_MP_NEU  : 0.45  : Max fractional neutrophil-recruitment suppression
MP_AUC50     : 40    : au*day, cumulative exposure for half-maximal complication index

//--- Riluzole PK/PD (RISCIS: 100 mg q12h x 24 h then 50 mg q12h to day 14)
KA_RIL       : 8.0   : 1/day, enteral absorption
KOUT_RIL     : 1.4   : 1/day, CYP1A2-dominated elimination (t1/2 ~ 12 h)
EC50_RIL     : 45    : au
EMAX_RIL_REL : 0.55  : Max fractional presynaptic glutamate-release inhibition
K_RIL_UPTAKE : 0.60  : Fractional gain in astrocytic glutamate clearance

//--- Minocycline PK/PD (Casha 2012 phase 2 regimen)
KOUT_MINO    : 1.05  : 1/day (t1/2 ~ 16 h)
EC50_MINO    : 400   : au
EMAX_MINO_M1 : 0.40  : Max fractional M1 activation blockade
EMAX_MINO_CASP: 0.25 : Max fractional caspase-pathway inhibition
K_MINO_SWITCH: 0.50  : Additional M1->M2 switch promoted by minocycline

//--- Glibenclamide PK/PD (SUR1-TRPM4 channel blockade, investigational)
KOUT_GLY     : 2.5   : 1/day
EC50_GLY     : 0.5   : au
EMAX_GLY     : 0.55  : Max fractional SUR1-TRPM4-dependent edema blockade

//--- Anti-Nogo-A antibody, intrathecal (NISCI programme)
KOUT_NOGO    : 0.15  : 1/day, CSF/tissue residence (t1/2 ~ 4.6 d)
EC50_NOGO    : 0.60  : au
EMAX_NOGO    : 0.80  : Max fractional Nogo-A neutralization

//--- Symptomatic pharmacology
KOUT_BAC     : 4.0   : 1/day, baclofen (t1/2 ~ 4 h)
EC50_BAC     : 25    : au
EMAX_BAC     : 0.65  : Max fractional spasticity reduction
K_BAC_WEAK   : 0.12  : Functional-weakness penalty scalar (shared mechanism)
KOUT_PGB     : 2.7   : 1/day, pregabalin (t1/2 ~ 6 h)
EC50_PGB     : 150   : au
EMAX_PGB     : 0.45  : Max fractional neuropathic-pain reduction

//--- Hemodynamics: MAP -> SCPP -> ischemic burden
MAP_BASE     : 90    : mmHg, pre-injury mean arterial pressure
SHOCK_MAG    : 25    : mmHg MAP drop from neurogenic shock (lesion >= T6)
K_SHOCK      : 0.20  : 1/day, resolution of neurogenic shock
KOUT_MAP     : 12    : 1/day, MAP equilibration
ISP_BASE     : 7     : mmHg, baseline intraspinal pressure
K_ISP_EDEMA  : 18    : mmHg per unit cord edema
K_ISP_COMP   : 20    : mmHg per unit residual compression
SCPP50       : 65    : mmHg, perfusion pressure at half-maximal ischemia
SCPP_SLOPE   : 8     : mmHg, steepness of the perfusion-ischemia relation
K_ISCH_COMP  : 0.40  : Direct (non-perfusion) ischemic effect of compression
KOUT_ISCH    : 6.0   : 1/day, ischemia equilibration

//--- Acute injury driver (primary necrosis / DAMP release)
KOUT_INJ     : 2.0   : 1/day (t1/2 ~ 8.3 h)

//--- Cord edema (SUR1-TRPM4 / AQP4 / BSCB)
K_ED_ISCH    : 0.60  : per unit ischemia
K_ED_INJ     : 0.85  : per unit primary insult
K_ED_INFL    : 0.10  : per unit normalized cytokine burden
KOUT_EDEMA   : 0.35  : 1/day, edema resolution

//--- Excitotoxicity
K_GLU_INJ    : 110   : glutamate release per unit primary insult
K_GLU_ISCH   : 45    : glutamate release per unit ischemia (EAAT reversal)
KOUT_GLU     : 24    : 1/day, glutamate clearance (t1/2 ~ 42 min)
K_CA_GLU     : 1.00  : Ca2+ influx per unit extracellular glutamate
KOUT_CA      : 8.0   : 1/day, Ca2+ buffering/extrusion

//--- Oxidative stress
K_ROS_CA     : 0.90  : ROS per unit Ca2+ overload (mitochondrial)
K_ROS_ISCH   : 1.30  : ROS per unit ischemia
K_ROS_NEUT   : 0.80  : ROS per unit neutrophil burden (NADPH oxidase / MPO)
K_ROS_IRON   : 1.20  : ROS per unit primary insult (heme iron, Fenton)
KOUT_ROS     : 6.0   : 1/day, antioxidant clearance (SOD/catalase/GSH/Nrf2)

//--- Neuroinflammation
CYTO_REF     : 50    : au, reference cytokine scale
K_CYTO_DAMP  : 350   : cytokine production per unit DAMP release
K_CYTO_M1    : 8.0   : cytokine production per unit M1 burden
K_CYTO_NEUT  : 6.0   : cytokine production per unit neutrophil burden
KOUT_CYTO    : 2.5   : 1/day, cytokine clearance
K_CYTO_M2    : 0.35  : M2-mediated cytokine resolution
K_NEUT_IN    : 1.30  : neutrophil recruitment per unit normalized cytokine
KOUT_NEUT    : 1.20  : 1/day, neutrophil clearance
K_M1_DAMP    : 0.85  : M1 activation per unit DAMP release
K_M1_CYTO    : 0.20  : M1 activation per unit normalized cytokine
K_M1_DEBRIS  : 0.40  : M1 activation per unit myelin/cell debris
KOUT_M1      : 0.15  : 1/day, M1 turnover
K_SWITCH     : 0.060 : 1/day, M1->M2 phenotype switch
K_M2_SUPPRESS: 0.35  : M2-mediated resolution of the M1 phenotype
K_M2_BASE    : 0.45  : M2 recruitment per unit debris (phagocytic demand)
KOUT_M2      : 0.10  : 1/day, M2 turnover

//--- Cell death
K_AP_ROS     : 0.72  : caspase drive per unit oxidative burden
K_AP_CA      : 0.95  : caspase drive per unit Ca2+ overload (calpain/mPTP)
K_AP_CYTO    : 0.24  : caspase drive per unit normalized cytokine (TNF-R/Fas)
K_AP_ISCH    : 0.40  : caspase drive per unit ischemia
KOUT_APOP    : 0.50  : 1/day, caspase-activity turnover
APOP_THR     : 0.050 : Sub-threshold caspase activity is physiological turnover
ISCH_THR     : 0.040 : Sub-threshold perfusion deficit is tolerated
K_DEATH_N    : 0.030 : neuron loss per unit supra-threshold caspase activity
K_NEC_ISCH   : 0.120 : neuron necrosis per unit (supra-threshold ischemia)^2
K_DEATH_O    : 0.050 : oligodendrocyte loss per unit supra-threshold caspase
K_OX_O       : 0.030 : oligodendrocyte loss per unit oxidative burden
K_REMYEL     : 0.022 : 1/day, remyelination toward the surviving OPC ceiling
K_CAP_LOSS   : 0.45  : permanent loss of remyelination ceiling per unit oligo death
K_DEB_GEN    : 14    : debris generated per unit cell-death flux
K_DEB_NEC    : 0.20  : debris from necrosis per unit (supra-threshold ischemia)^2
K_DEB_CLEAR  : 0.60  : M2-mediated debris clearance rate
KOUT_DEB     : 0.020 : 1/day, background debris clearance
DEB50        : 0.45  : debris level that halves remyelination
OLIG_MAX     : 0.92  : baseline oligodendrocyte / myelin integrity
K_AX_APOP    : 0.017 : axonal loss per unit supra-threshold caspase activity
K_AX_ISCH    : 0.070 : axonal loss per unit (supra-threshold ischemia)^2

//--- Conduction: the acute exam is worse than the anatomy
MYEL_FLOOR   : 0.35  : conduction efficiency of a fully demyelinated spared axon
K_ABLOCK     : 0.08  : 1/day, resolution of spinal shock / acute conduction block
K_CB_ABLOCK  : 0.45  : depth of the initial reversible conduction block
K_CB_EDEMA   : 0.35  : reversible conduction block per unit edema
K_CB_ISCH    : 0.25  : reversible conduction block per unit ischemia
CB_FLOOR     : 0.25  : floor on the conduction factor

//--- Astrogliosis & glial scar
K_GFAP_CYTO  : 2.00  : astrocyte reactivity per unit normalized cytokine
K_GFAP_INJ   : 1.50  : astrocyte reactivity per unit primary insult
KOUT_GFAP    : 0.012 : 1/day (chronic gliosis persists, t1/2 ~ 58 d)
K_CSPG_GFAP  : 0.012 : CSPG deposition per unit reactive astrogliosis
KOUT_CSPG    : 0.015 : 1/day, CSPG turnover
CSPG50       : 0.55  : CSPG level that halves the plasticity drive

//--- Lesion cavity (the imaging surrogate)
K_CAV_APOP   : 0.035 : cavitation per unit supra-threshold caspase activity
K_CAV_NEUT   : 0.012 : cavitation per unit neutrophil burden
K_CAV_ISCH   : 0.030 : cavitation per unit (supra-threshold ischemia)^2
KOUT_CAV     : 0.0004: 1/day (a post-traumatic cavity is essentially permanent)
CAV_MAX      : 1.0   : lesion index saturates at full cross-sectional cavitation
CAV_ML       : 1.8   : mL of cavity per unit lesion index (reporting scale only)

//--- Plasticity & the critical period
K_CRIT       : 0.015 : 1/day, intrinsic closure of the plasticity window
K_CRIT_SCAR  : 0.90  : scar-accelerated window closure (per unit CSPG)
K_PL_REHAB   : 0.055 : plasticity drive per unit rehabilitation intensity
K_PL_SPONT   : 0.010 : spontaneous plasticity drive
K_PL_NOGO    : 1.10  : plasticity gain per unit Nogo-A neutralization
K_PL_ROCK    : 0.60  : plasticity gain per unit ROCK inhibition
KOUT_PLAST   : 0.0008: 1/day, slow loss of unused plasticity gains
PLAST_MAX    : 1.0   : saturation of the plasticity pool
G_PLAST      : 1.00  : gain of plasticity on effective descending drive
G_ESTIM      : 0.35  : gain of epidural stimulation on residual drive

//--- Muscle & the motor-score mapping
K_ATRO       : 0.020 : 1/day, disuse atrophy accumulation
K_ATRO_REC   : 0.030 : 1/day, atrophy reversal with loading
ATRO_MAX     : 0.60  : maximum atrophy fraction
ATRO_FLOOR   : 0.10  : atrophy that loading cannot reverse without voluntary drive
K_ATRO_MOT   : 0.25  : motor-score penalty per unit atrophy
TH50         : 0.22  : effective descending drive at half-maximal motor score
HILL         : 2.2   : Hill coefficient of the drive->motor mapping
KOUT_MOTOR   : 0.040 : 1/day, motor-score equilibration (months)

//--- Reflex reorganization -> spasticity / pain / bladder / dysreflexia
K_REFLEX     : 0.050 : 1/day, sublesional reflex-arc reorganization
ASH_MAX      : 2.8   : maximum mean modified Ashworth score
KOUT_SPAST   : 0.15  : 1/day, spasticity equilibration
K_NP_SENS    : 0.28  : pain drive per unit inflammatory sensitization
K_NP_ECTOPIC : 1.30  : pain drive from ectopic firing (peaks at partial sparing)
K_NP_REFLEX  : 0.45  : pain drive per unit reflex reorganization
NP_MAX       : 9.0   : maximum pain NRS
KOUT_NP      : 0.08  : 1/day, pain equilibration
BL_MAX       : 1.0   : maximum detrusor-overactivity index
KOUT_BL      : 0.06  : 1/day, bladder equilibration
KOUT_ADT     : 24    : 1/day, decay of a noxious autonomic-dysreflexia trigger
K_AD_SBP     : 60    : mmHg SBP surge at full trigger, mature reflex, lesion >= T6

//--- Respiratory & bone
KOUT_RESP    : 0.50  : 1/day, vital-capacity equilibration
K_RESP_EDEMA : 30    : %VC lost per unit cord edema (cervical lesions)
KOUT_BMD     : 0.0022: 1/day, sublesional bone loss toward the floor
BMD_FLOOR    : 0.60  : fraction of baseline BMD at the chronic floor

[CMT] @annotated
MP_CENT    : Methylprednisolone central compartment (au)
MP_PERIPH  : Methylprednisolone peripheral compartment (au)
RIL_DEPOT  : Riluzole enteral absorption depot (au)
RIL_CENT   : Riluzole plasma compartment (au)
MINO_CENT  : Minocycline plasma compartment (au)
GLY_CENT   : Glibenclamide plasma compartment (au)
NOGO_ITH   : Anti-Nogo-A antibody, intrathecal/CSF compartment (au)
BAC_CENT   : Baclofen compartment (au)
PGB_CENT   : Pregabalin plasma compartment (au)
MP_AUC     : Cumulative methylprednisolone exposure (au*day)
SHOCK      : Neurogenic-shock state (1 = full sympathectomy effect)
MAP        : Mean arterial pressure (mmHg)
INJ        : Primary insult / DAMP-release driver (au)
ABLOCK     : Spinal shock / reversible acute conduction block (0-1)
ISCHEMIA   : Ischemic burden, deficit vs intact perfusion (0-1)
EDEMA      : Cord edema / swelling (0-1)
GLU        : Extracellular glutamate above baseline (au)
CAI        : Intracellular Ca2+ overload (au)
ROS        : Net oxidative burden / lipid peroxidation (au)
NEUT       : Neutrophil infiltration (au)
CYTO       : Pro-inflammatory cytokine burden IL-1b/TNF-a/IL-6 (au)
M1         : M1 pro-inflammatory macrophage/microglia burden (au)
M2         : M2 pro-repair macrophage/microglia burden (au)
APOP       : Caspase-3 activity / apoptotic signalling (au)
DEBRIS     : Myelin and cell debris awaiting phagocytosis (au)
NEURON     : Surviving perilesional gray-matter neurons (fraction)
OLIG       : Oligodendrocyte / myelin integrity (fraction)
OLIG_CAP   : Remyelination ceiling — surviving OPC capacity (fraction)
AXON       : Spared descending axons, CST+reticulospinal (fraction)
GFAP       : Reactive astrogliosis (au)
CSPG       : Glial-scar CSPG deposition (au)
CAVITY     : Cystic lesion index, 0-1 (x CAV_ML for mL)
CRIT       : Heightened-plasticity critical period (1 = fully open)
PLAST      : Plasticity / collateral-sprouting pool (0-1)
ATRO       : Sublesional muscle atrophy (fraction)
MOTOR      : ISNCSCI total motor score (0-100)
REFLEX     : Sublesional reflex-arc reorganization (0-1)
SPAST      : Spasticity, mean modified Ashworth (0-4)
NPAIN      : Neuropathic pain, NRS (0-10)
BLADDER    : Neurogenic detrusor overactivity index (0-1)
AD_TRIG    : Noxious autonomic-dysreflexia trigger (decaying pulse)
RESP       : Vital capacity (% predicted)
BMD        : Sublesional bone mineral density (fraction of baseline)

[GLOBAL]
// smooth 0->1 switch: keeps the intervention timing differentiable
#define SWTCH(t, t0) (1.0/(1.0 + exp(-((t)-(t0))/0.02)))

[MAIN]
MP_CENT_0 = 0; MP_PERIPH_0 = 0; RIL_DEPOT_0 = 0; RIL_CENT_0 = 0;
MINO_CENT_0 = 0; GLY_CENT_0 = 0; NOGO_ITH_0 = 0; BAC_CENT_0 = 0;
PGB_CENT_0 = 0; MP_AUC_0 = 0; AD_TRIG_0 = 0;

// ---- level-dependent constants ----
double above_t6    = (LEVEL_IDX <= 14.0) ? 1.0 : 0.0;   // T6 == index 14
double is_cervical = (LEVEL_IDX <=  8.0) ? 1.0 : 0.0;

// ISNCSCI points preserved rostral to the lesion (of 100 total)
double above_score;
if (LEVEL_IDX <= 4.0)      above_score = 0.0;
else if (LEVEL_IDX <= 8.0) above_score = (LEVEL_IDX - 4.0)*10.0;  // C5->10 .. C8->40
else                       above_score = 50.0;                    // upper limbs intact

// respiratory penalty (percentage points of vital capacity)
double resp_pen;
if (LEVEL_IDX <= 4.0)       resp_pen = 70.0;
else if (LEVEL_IDX <= 8.0)  resp_pen = 45.0;
else if (LEVEL_IDX <= 14.0) resp_pen = 20.0;
else                        resp_pen = 5.0;

// ---- initial severity ----
double disrupt = DISRUPT;
if (disrupt < 0) {
  int g = (int)(AIS_INIT + 0.5);
  if      (g <= 1) disrupt = 0.94;   // AIS A
  else if (g == 2) disrupt = 0.86;   // AIS B
  else if (g == 3) disrupt = 0.70;   // AIS C
  else             disrupt = 0.45;   // AIS D
}

// ischemia is a DEFICIT relative to intact perfusion, so an uninjured cord is 0
double isch_base = 1.0/(1.0 + exp((MAP_BASE - ISP_BASE - SCPP50)/SCPP_SLOPE));

SHOCK_0    = above_t6;
MAP_0      = MAP_BASE - SHOCK_MAG*above_t6;
INJ_0      = disrupt;
ABLOCK_0   = 1.0;
ISCHEMIA_0 = 0; EDEMA_0 = 0; GLU_0 = 0; CAI_0 = 0; ROS_0 = 0;
NEUT_0 = 0; CYTO_0 = 0; M1_0 = 0; M2_0 = 0; APOP_0 = 0; DEBRIS_0 = 0;
NEURON_0   = 1.0 - 0.5*disrupt;
OLIG_0     = OLIG_MAX;
OLIG_CAP_0 = OLIG_MAX;
AXON_0     = 1.0 - disrupt;
GFAP_0 = 0; CSPG_0 = 0; CAVITY_0 = 0;
CRIT_0     = 1.0;
PLAST_0    = 0; ATRO_0 = 0;
REFLEX_0 = 0; SPAST_0 = 0; NPAIN_0 = 0; BLADDER_0 = 0;
BMD_0      = 1.0;

// initial functional state: the acute exam sees the anatomy THROUGH the
// reversible conduction block, which is why patients improve from it
double myel0 = MYEL_FLOOR + (1.0 - MYEL_FLOOR)*OLIG_0;
double cb0   = 1.0 - K_CB_ABLOCK*ABLOCK_0;
if (cb0 < CB_FLOOR) cb0 = CB_FLOOR;
double conn0 = AXON_0*myel0*cb0;
if (conn0 > 0.999) conn0 = 0.999;
double hill0 = pow(conn0, HILL)/(pow(TH50, HILL) + pow(conn0, HILL));
MOTOR_0 = above_score + (100.0 - above_score)*hill0;
RESP_0  = 100.0 - resp_pen*(1.0 - 0.6*hill0);

[ODE]
double t = SOLVERTIME;

// ---------- intervention switches ----------
double comp     = COMP0*(1.0 - DECOMP_EFF*SWTCH(t, TDECOMP));
double vaso_on  = VASO*(1.0 - SWTCH(t, TVASO_END));
double rehab_on = REHAB*SWTCH(t, TREHAB_START)*(1.0 - SWTCH(t, TREHAB_END));
double estim_on = ESTIM*SWTCH(t, TESTIM_START);
double fes_on   = FES*SWTCH(t, TREHAB_START);

// ---------- drug effect (Emax) terms ----------
double mp_lp     = EMAX_MP_LP  * MP_CENT/(EC50_MP + MP_CENT);
double mp_cyt    = EMAX_MP_CYT * MP_CENT/(EC50_MP + MP_CENT);
double mp_neu    = EMAX_MP_NEU * MP_CENT/(EC50_MP + MP_CENT);
double ril_rel   = EMAX_RIL_REL * RIL_CENT/(EC50_RIL + RIL_CENT);
double ril_up    = K_RIL_UPTAKE * RIL_CENT/(EC50_RIL + RIL_CENT);
double mino_m1   = EMAX_MINO_M1   * MINO_CENT/(EC50_MINO + MINO_CENT);
double mino_casp = EMAX_MINO_CASP * MINO_CENT/(EC50_MINO + MINO_CENT);
double gly_blk   = EMAX_GLY  * GLY_CENT/(EC50_GLY + GLY_CENT);
double nogo_blk  = EMAX_NOGO * NOGO_ITH/(EC50_NOGO + NOGO_ITH);
double bac_eff   = EMAX_BAC  * BAC_CENT/(EC50_BAC + BAC_CENT);
double pgb_eff   = EMAX_PGB  * PGB_CENT/(EC50_PGB + PGB_CENT);

// ---------- drug PK ----------
dxdt_MP_CENT   = -KOUT_MP*MP_CENT - KTR_MP*MP_CENT + KTR_MP*MP_PERIPH;
dxdt_MP_PERIPH =  KTR_MP*MP_CENT - KTR_MP*MP_PERIPH;
dxdt_RIL_DEPOT = -KA_RIL*RIL_DEPOT;
dxdt_RIL_CENT  =  KA_RIL*RIL_DEPOT - KOUT_RIL*RIL_CENT;
dxdt_MINO_CENT = -KOUT_MINO*MINO_CENT;
dxdt_GLY_CENT  = -KOUT_GLY*GLY_CENT;
dxdt_NOGO_ITH  = -KOUT_NOGO*NOGO_ITH;
dxdt_BAC_CENT  = -KOUT_BAC*BAC_CENT;
dxdt_PGB_CENT  = -KOUT_PGB*PGB_CENT;
dxdt_MP_AUC    =  MP_CENT;                 // toxicity depends on DOSE, not timing

// ---------- hemodynamics: MAP -> SCPP -> ischemia ----------
dxdt_SHOCK = -K_SHOCK*SHOCK;
double map_target = MAP_BASE - SHOCK_MAG*SHOCK + VASO_GAIN*vaso_on;
dxdt_MAP = KOUT_MAP*(map_target - MAP);

double isp  = ISP_BASE + K_ISP_EDEMA*EDEMA + K_ISP_COMP*comp;
double scpp = MAP - isp;
double zi   = (scpp - SCPP50)/SCPP_SLOPE;
if (zi >  30) zi =  30;
if (zi < -30) zi = -30;
double isch_base0 = 1.0/(1.0 + exp((MAP_BASE - ISP_BASE - SCPP50)/SCPP_SLOPE));
double isch_target = 1.0/(1.0 + exp(zi)) - isch_base0;
if (isch_target < 0) isch_target = 0;
if (isch_target > 1) isch_target = 1;
isch_target += K_ISCH_COMP*comp;
if (isch_target > 1) isch_target = 1;
dxdt_ISCHEMIA = KOUT_ISCH*(isch_target - ISCHEMIA);

// ---------- acute drivers ----------
dxdt_INJ    = -KOUT_INJ*INJ;
dxdt_ABLOCK = -K_ABLOCK*ABLOCK;

// ---------- edema: the compression-edema-ischemia vicious cycle ----------
double ed_drive = (K_ED_ISCH*ISCHEMIA + K_ED_INJ*INJ
                   + K_ED_INFL*(CYTO/CYTO_REF))*(1.0 - gly_blk);
dxdt_EDEMA = ed_drive*(1.0 - EDEMA) - KOUT_EDEMA*EDEMA;

// ---------- excitotoxicity ----------
double glu_prod = (K_GLU_INJ*INJ + K_GLU_ISCH*ISCHEMIA)*(1.0 - ril_rel);
dxdt_GLU = glu_prod - KOUT_GLU*GLU*(1.0 + ril_up);
dxdt_CAI = K_CA_GLU*GLU - KOUT_CA*CAI;

// ---------- oxidative stress (the methylprednisolone target) ----------
double ros_prod = K_ROS_CA*CAI + K_ROS_ISCH*ISCHEMIA
                  + K_ROS_NEUT*NEUT + K_ROS_IRON*INJ;
dxdt_ROS = ros_prod*(1.0 - mp_lp) - KOUT_ROS*ROS;

// ---------- neuroinflammation ----------
double cyto_prod = (K_CYTO_DAMP*INJ + K_CYTO_M1*M1 + K_CYTO_NEUT*NEUT)*(1.0 - mp_cyt);
dxdt_CYTO = cyto_prod - KOUT_CYTO*CYTO - K_CYTO_M2*M2*CYTO;
dxdt_NEUT = K_NEUT_IN*(CYTO/CYTO_REF)*(1.0 - mp_neu) - KOUT_NEUT*NEUT;

double m1_drive = (K_M1_DAMP*INJ + K_M1_CYTO*(CYTO/CYTO_REF)
                   + K_M1_DEBRIS*DEBRIS)*(1.0 - mino_m1);
double m1_switch = K_SWITCH*M1*(1.0 + K_MINO_SWITCH*mino_m1);
dxdt_M1 = m1_drive - KOUT_M1*M1 - m1_switch - K_M2_SUPPRESS*M2*M1;
dxdt_M2 = m1_switch + K_M2_BASE*DEBRIS - KOUT_M2*M2;

// ---------- cell death ----------
double ap_drive = (K_AP_ROS*ROS + K_AP_CA*CAI + K_AP_CYTO*(CYTO/CYTO_REF)
                   + K_AP_ISCH*ISCHEMIA)*(1.0 - mino_casp);
dxdt_APOP = ap_drive - KOUT_APOP*APOP;

// only SUPRA-threshold death signalling destroys tissue: sub-threshold caspase
// activity and perfusion deficit are physiological, and without this the model
// would drain axons for ever at its (tiny) chronic steady state
double ap_eff   = APOP - APOP_THR;      if (ap_eff  < 0) ap_eff  = 0;
double isch_eff = ISCHEMIA - ISCH_THR;  if (isch_eff < 0) isch_eff = 0;

double olig_loss  = K_DEATH_O*ap_eff + K_OX_O*ROS;
double death_flux = olig_loss*OLIG
                    + (K_DEATH_N*ap_eff + K_NEC_ISCH*isch_eff*isch_eff)*NEURON;
dxdt_DEBRIS = K_DEB_GEN*death_flux + K_DEB_NEC*isch_eff*isch_eff
              - K_DEB_CLEAR*M2*DEBRIS - KOUT_DEB*DEBRIS;

dxdt_NEURON = -(K_DEATH_N*ap_eff + K_NEC_ISCH*isch_eff*isch_eff)*NEURON;
dxdt_OLIG   = -olig_loss*OLIG
              + K_REMYEL*(1.0/(1.0 + DEBRIS/DEB50))*(OLIG_CAP > OLIG ? OLIG_CAP - OLIG : 0.0);
// remyelination can never exceed the surviving oligodendrocyte-lineage capacity:
// a ceiling that only ever falls
dxdt_OLIG_CAP = -K_CAP_LOSS*olig_loss*OLIG;
dxdt_AXON     = -(K_AX_APOP*ap_eff + K_AX_ISCH*isch_eff*isch_eff)*AXON;

// ---------- astrogliosis, glial scar, lesion cavity ----------
dxdt_GFAP = K_GFAP_CYTO*(CYTO/CYTO_REF) + K_GFAP_INJ*INJ - KOUT_GFAP*GFAP;
dxdt_CSPG = K_CSPG_GFAP*GFAP*(1.0 - CHASE) - KOUT_CSPG*CSPG;

double cav_drive = K_CAV_APOP*ap_eff + K_CAV_NEUT*NEUT
                   + K_CAV_ISCH*isch_eff*isch_eff;
dxdt_CAVITY = cav_drive*(1.0 - CAVITY/CAV_MAX) - KOUT_CAV*CAVITY;

// ---------- plasticity within a closing window ----------
dxdt_CRIT = -K_CRIT*CRIT*(1.0 + K_CRIT_SCAR*CSPG);
double pl_drive = (K_PL_REHAB*rehab_on + K_PL_SPONT)*CRIT
                  /(1.0 + CSPG/CSPG50)
                  *(1.0 + K_PL_NOGO*nogo_blk + K_PL_ROCK*ROCKI);
dxdt_PLAST = pl_drive*(1.0 - PLAST/PLAST_MAX) - KOUT_PLAST*PLAST;

// ---------- effective descending drive -> ISNCSCI motor score ----------
double myel = MYEL_FLOOR + (1.0 - MYEL_FLOOR)*OLIG;
double cb   = 1.0 - K_CB_ABLOCK*ABLOCK - K_CB_EDEMA*EDEMA - K_CB_ISCH*ISCHEMIA;
if (cb < CB_FLOOR) cb = CB_FLOOR;
double conn = AXON*myel*cb*(1.0 + G_PLAST*PLAST + G_ESTIM*estim_on);
if (conn > 0.999) conn = 0.999;
double hill = pow(conn, HILL)/(pow(TH50, HILL) + pow(conn, HILL));

double load = rehab_on + fes_on + hill;
dxdt_ATRO = K_ATRO*(load < 1.0 ? 1.0 - load : 0.0)*(ATRO_MAX - ATRO)
            - K_ATRO_REC*(rehab_on + fes_on)
              *((ATRO > ATRO_FLOOR*(1.0 - hill)) ? ATRO - ATRO_FLOOR*(1.0 - hill) : 0.0);

double above_sc;
if (LEVEL_IDX <= 4.0)      above_sc = 0.0;
else if (LEVEL_IDX <= 8.0) above_sc = (LEVEL_IDX - 4.0)*10.0;
else                       above_sc = 50.0;
double motor_target = above_sc + (100.0 - above_sc)*hill*(1.0 - K_ATRO_MOT*ATRO)
                      - K_BAC_WEAK*bac_eff*(100.0 - above_sc);
if (motor_target < 0.5*above_sc) motor_target = 0.5*above_sc;
dxdt_MOTOR = KOUT_MOTOR*(motor_target - MOTOR);

// ---------- reflex reorganization: recovery creates NEW pathology ----------
double reflex_target = SUBLESIONAL_LMN*(1.0 - 0.85*hill);
if (reflex_target < 0) reflex_target = 0;
dxdt_REFLEX = K_REFLEX*(reflex_target - REFLEX);

double spast_target = ASH_MAX*REFLEX*(1.0 - bac_eff);
dxdt_SPAST = KOUT_SPAST*(spast_target - SPAST);

// ectopic firing from PARTIALLY spared axons peaks at intermediate sparing,
// which is why neuropathic pain is not simply worst in the most complete injury
double np_drive = K_NP_SENS*(CYTO/CYTO_REF + 0.6*M1)
                  + K_NP_ECTOPIC*4.0*conn*(1.0 - conn)
                  + K_NP_REFLEX*REFLEX;
double np_target = NP_MAX*(np_drive/(1.0 + np_drive))*(1.0 - pgb_eff);
dxdt_NPAIN = KOUT_NP*(np_target - NPAIN);

double bl_target = BL_MAX*REFLEX*SUBLESIONAL_LMN*(1.0 - ANTIMUSC);
dxdt_BLADDER = KOUT_BL*(bl_target - BLADDER);
dxdt_AD_TRIG = -KOUT_ADT*AD_TRIG;

// ---------- respiratory function & sublesional bone ----------
double resp_pen2, is_cerv;
if (LEVEL_IDX <= 4.0)       { resp_pen2 = 70.0; is_cerv = 1.0; }
else if (LEVEL_IDX <= 8.0)  { resp_pen2 = 45.0; is_cerv = 1.0; }
else if (LEVEL_IDX <= 14.0) { resp_pen2 = 20.0; is_cerv = 0.0; }
else                        { resp_pen2 =  5.0; is_cerv = 0.0; }
double resp_target = 100.0 - resp_pen2*(1.0 - 0.6*hill) - K_RESP_EDEMA*EDEMA*is_cerv;
dxdt_RESP = KOUT_RESP*(resp_target - RESP);

double wb = hill + 0.5*rehab_on + 0.4*fes_on;
if (wb > 1.0) wb = 1.0;
dxdt_BMD = -KOUT_BMD*(1.0 - wb)*(BMD - BMD_FLOOR);

[TABLE]
double above_out;
if (LEVEL_IDX <= 4.0)      above_out = 0.0;
else if (LEVEL_IDX <= 8.0) above_out = (LEVEL_IDX - 4.0)*10.0;
else                       above_out = 50.0;

double myel_o = MYEL_FLOOR + (1.0 - MYEL_FLOOR)*OLIG;
double cb_o   = 1.0 - K_CB_ABLOCK*ABLOCK - K_CB_EDEMA*EDEMA - K_CB_ISCH*ISCHEMIA;
if (cb_o < CB_FLOOR) cb_o = CB_FLOOR;
double estim_o = ESTIM*SWTCH(SOLVERTIME, TESTIM_START);
double conn_o  = AXON*myel_o*cb_o*(1.0 + G_PLAST*PLAST + G_ESTIM*estim_o);
if (conn_o > 0.999) conn_o = 0.999;

capture Descending_drive   = conn_o;
capture Conduction_factor  = cb_o;
capture Myelin_efficiency  = myel_o;
capture SCPP               = MAP - (ISP_BASE + K_ISP_EDEMA*EDEMA
                                    + K_ISP_COMP*COMP0*(1.0 - DECOMP_EFF*SWTCH(SOLVERTIME, TDECOMP)));
capture ISP                = ISP_BASE + K_ISP_EDEMA*EDEMA
                             + K_ISP_COMP*COMP0*(1.0 - DECOMP_EFF*SWTCH(SOLVERTIME, TDECOMP));
capture Ischemic_burden    = ISCHEMIA;
capture Cascade_flux       = 0.40*ISCHEMIA + 0.95*CAI + 0.72*ROS + 0.24*(CYTO/CYTO_REF);
capture Lesion_volume_mL   = CAV_ML*CAVITY;
capture Axon_sparing       = AXON;
capture ISNCSCI_motor      = MOTOR;
capture Motor_above_lesion = above_out;
capture AIS_grade_index    = (MOTOR - above_out)/(100.0 - above_out + 1e-9);
capture Ashworth           = SPAST;
capture Pain_NRS           = NPAIN;
capture Bladder_index      = BLADDER;
capture AD_peak_SBP        = 1.15*MAP + K_AD_SBP*AD_TRIG*((LEVEL_IDX <= 14.0) ? 1.0 : 0.0)
                             *REFLEX*(1.0 + 0.5*BLADDER);
capture Vital_capacity     = RESP;
capture BMD_fraction       = BMD;
capture MP_complication_index = MP_AUC/(MP_AUC50 + MP_AUC);
capture Plasticity_pool    = PLAST;
capture Critical_period    = CRIT;
capture Scar_CSPG          = CSPG;

[CAPTURE]
Descending_drive Conduction_factor Myelin_efficiency SCPP ISP Ischemic_burden
Cascade_flux Lesion_volume_mL Axon_sparing ISNCSCI_motor Motor_above_lesion
AIS_grade_index Ashworth Pain_NRS Bladder_index AD_peak_SBP Vital_capacity
BMD_fraction MP_complication_index Plasticity_pool Critical_period Scar_CSPG


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2); library(purrr)
##  mod <- mread_cache("sci_mrgsolve_model.R")
##
##  ## ---------- regimen builders (all times in DAYS) ----------
##
##  ev_mp <- function(start_h = 3, hours = 23) {
##    ## NASCIS: 30 mg/kg IV bolus then 5.4 mg/kg/h for 23 h (or 47 h in NASCIS III)
##    t0 <- start_h/24
##    ev(amt = 30, cmt = "MP_CENT", time = t0) +
##      ev(amt = 5.4*hours, rate = 5.4*24, cmt = "MP_CENT", time = t0)
##  }
##
##  ev_riluzole <- function(start_h = 12, days = 14) {
##    t0 <- start_h/24
##    ev(amt = 100, cmt = "RIL_DEPOT", time = t0, ii = 0.5, addl = 1) +
##      ev(amt = 50, cmt = "RIL_DEPOT", time = t0 + 1,
##         ii = 0.5, addl = max(floor((days - 1)/0.5) - 1, 0))
##  }
##
##  ev_minocycline <- function(start_h = 12, days = 7) {
##    t0 <- start_h/24
##    ev(amt = 800, cmt = "MINO_CENT", time = t0, ii = 0.5, addl = 3) +
##      ev(amt = 400, cmt = "MINO_CENT", time = t0 + 2,
##         ii = 0.5, addl = max(floor((days - 2)/0.5) - 1, 0))
##  }
##
##  ev_glibenclamide <- function(start_h = 6, days = 3)
##    ev(amt = 1, cmt = "GLY_CENT", time = start_h/24, ii = 0.25,
##       addl = floor(days/0.25))
##
##  ev_antinogo <- function(start_d = 14, n = 6, interval = 7)
##    ev(amt = 1, cmt = "NOGO_ITH", time = start_d, ii = interval, addl = n - 1)
##
##  ev_baclofen <- function(start_d = 30, end_d = 365)
##    ev(amt = 20, cmt = "BAC_CENT", time = start_d, ii = 1/3,
##       addl = floor((end_d - start_d)*3))
##
##  ev_pregabalin <- function(start_d = 30, end_d = 365)
##    ev(amt = 150, cmt = "PGB_CENT", time = start_d, ii = 0.5,
##       addl = floor((end_d - start_d)*2))
##
##  ## ---------- 18 prebuilt scenarios ----------
##  ## Default subject: C5 AIS A (LEVEL_IDX = 5, AIS_INIT = 1), COMP0 = 0.6.
##  ## "std care" = decompression at 24 h + rehabilitation intensity 0.5 from d14.
##
##  SCI_simulate_scenarios <- function(end_d = 365) {
##
##    std <- list(TDECOMP = 1.0, REHAB = 0.5)
##
##    sc <- list(
##      "1. Natural history (no decompression, no rehab)" =
##        list(par = list(TDECOMP = 999, REHAB = 0),      ev = NULL),
##      "2. Standard care (decompression 24 h + rehab)" =
##        list(par = std,                                  ev = NULL),
##      "3. Early decompression < 12 h" =
##        list(par = list(TDECOMP = 0.5, REHAB = 0.5),     ev = NULL),
##      "4. Late decompression 72 h" =
##        list(par = list(TDECOMP = 3.0, REHAB = 0.5),     ev = NULL),
##      "5. Methylprednisolone within 3 h (NASCIS II)" =
##        list(par = std,                                  ev = ev_mp(3)),
##      "6. Methylprednisolone at 9 h (outside the window)" =
##        list(par = std,                                  ev = ev_mp(9)),
##      "7. Methylprednisolone 48-h infusion (NASCIS III)" =
##        list(par = std,                                  ev = ev_mp(3, hours = 47)),
##      "8. Riluzole 14 d (RISCIS)" =
##        list(par = std,                                  ev = ev_riluzole()),
##      "9. Minocycline 7 d" =
##        list(par = std,                                  ev = ev_minocycline()),
##      "10. Glibenclamide 3 d (SUR1-TRPM4)" =
##        list(par = std,                                  ev = ev_glibenclamide()),
##      "11. MAP >= 85 mmHg x 7 d" =
##        list(par = c(std, list(VASO = 1)),               ev = NULL),
##      "12. Bundle: decompression 8 h + MAP protocol + riluzole" =
##        list(par = list(TDECOMP = 8/24, VASO = 1, REHAB = 0.5),
##             ev = ev_riluzole(start_h = 8)),
##      "13. Anti-Nogo-A + intensive rehab from d14" =
##        list(par = list(TDECOMP = 1, REHAB = 1.0),       ev = ev_antinogo()),
##      "14. Intensive rehab EARLY (d14-180)" =
##        list(par = list(TDECOMP = 1, REHAB = 1.0, TREHAB_START = 14,
##                        TREHAB_END = 180),               ev = NULL),
##      "15. Intensive rehab LATE (d120-286, same dose)" =
##        list(par = list(TDECOMP = 1, REHAB = 1.0, TREHAB_START = 120,
##                        TREHAB_END = 286),               ev = NULL),
##      "16. Symptomatic: baclofen + pregabalin from d30" =
##        list(par = std,        ev = ev_baclofen() + ev_pregabalin()),
##      "17. Incomplete AIS C, standard care" =
##        list(par = c(std, list(AIS_INIT = 3)),           ev = NULL),
##      "18. AIS C + epidural stimulation from d120" =
##        list(par = c(std, list(AIS_INIT = 3, ESTIM = 1)), ev = NULL)
##    )
##
##    purrr::imap_dfr(sc, function(s, lab) {
##      m <- mod %>% param(s$par)
##      e <- if (is.null(s$ev)) ev(amt = 0, cmt = "MP_CENT", time = 0) else s$ev
##      m %>% mrgsim(events = e, end = end_d, delta = 0.25, hmax = 0.01) %>%
##        as_tibble() %>% mutate(scenario = lab)
##    })
##  }
##
##  ## ---------- experiment 1: the methylprednisolone window ----------
##  ## Benefit falls ~4-fold from 1 h to 24 h; MP_complication_index does not move.
##  SCI_mp_window <- function(hours = c(1, 3, 6, 9, 12, 24), ais = 1) {
##    ref <- mod %>% param(REHAB = 0.5, AIS_INIT = ais) %>%
##      mrgsim(end = 365, delta = 1, hmax = 0.01) %>% as_tibble()
##    m_ref <- tail(ref$ISNCSCI_motor, 1)
##    purrr::map_dfr(hours, function(h) {
##      out <- mod %>% param(REHAB = 0.5, AIS_INIT = ais) %>%
##        mrgsim(events = ev_mp(h), end = 365, delta = 1, hmax = 0.01) %>% as_tibble()
##      tibble(start_h = h,
##             motor = tail(out$ISNCSCI_motor, 1),
##             d_motor = tail(out$ISNCSCI_motor, 1) - m_ref,
##             lesion_mL = tail(out$Lesion_volume_mL, 1),
##             complication_index = tail(out$MP_complication_index, 1))
##    })
##  }
##
##  ## ---------- experiment 2: time to decompression ----------
##  SCI_decompression_sweep <- function(hours = c(4, 8, 12, 24, 48, 72), ais = 1)
##    purrr::map_dfr(hours, function(h) {
##      out <- mod %>% param(REHAB = 0.5, AIS_INIT = ais, TDECOMP = h/24) %>%
##        mrgsim(end = 365, delta = 0.25, hmax = 0.01) %>% as_tibble()
##      tibble(t_decomp_h = h,
##             peak_ischemia = max(out$Ischemic_burden),
##             peak_edema = max(out$EDEMA),
##             axon = tail(out$Axon_sparing, 1),
##             lesion_mL = tail(out$Lesion_volume_mL, 1),
##             motor = tail(out$ISNCSCI_motor, 1))
##    })
##
##  ## ---------- experiment 3: autonomic dysreflexia challenge ----------
##  ## The same bladder distension is harmless at day 7 and a hypertensive
##  ## emergency at day 180, because REFLEX has matured in between.
##  SCI_ad_challenge <- function(days = c(7, 30, 90, 180), level = 12)
##    purrr::map_dfr(days, function(d) {
##      out <- mod %>% param(LEVEL_IDX = level, REHAB = 0.5) %>%
##        mrgsim(events = ev(amt = 1, cmt = "AD_TRIG", time = d),
##               end = d + 1, delta = 0.005, hmax = 0.005) %>% as_tibble()
##      tibble(trigger_day = d, peak_SBP = max(out$AD_peak_SBP),
##             reflex = tail(out$REFLEX, 1))
##    })
##
##  ## ---------- quick sanity plots ----------
##  ## df <- SCI_simulate_scenarios(365)
##  ## ggplot(df, aes(time, ISNCSCI_motor, colour = scenario)) + geom_line()
##  ## ggplot(filter(df, time <= 14), aes(time, Ischemic_burden, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time, Lesion_volume_mL, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time, Ashworth, colour = scenario)) + geom_line()
##
##  ## ---------- CALIBRATION NOTES ----------
##  ## Natural history by AIS grade is the primary calibration target, because it
##  ## is the comparator every trial arm has to beat (Fawcett 2007 Spinal Cord
##  ## 45:190; EMSCI cohort trajectories). With default parameters and standard
##  ## care (decompression at 24 h, rehabilitation 0.5 from day 14) the model
##  ## reproduces, for a C5 lesion, initial -> 1-year ISNCSCI total motor:
##  ##     AIS A  11.2 -> 12.1    (+0.9;  little conversion, gains are root-level)
##  ##     AIS B  17.3 -> 22.1    (+4.8)
##  ##     AIS C  38.9 -> 51.3    (+12.4, largest absolute gain in the mid-range)
##  ##     AIS D  67.8 -> 79.7    (+11.9)
##  ## with intensive rehabilitation (REHAB = 1.0) adding a further ~0.4-4.4
##  ## points (A +1.3, B +7.0, C +16.8, D +15.0 from baseline),
##  ## the acute nadir at day 2-3 driven by edema/ischemia conduction block, and
##  ## ~90% of the change complete by 3-6 months (KOUT_MOTOR = 0.04/d).
##  ##
##  ## Methylprednisolone (Bracken 1990 NASCIS II; Bracken 1997 NASCIS III;
##  ## Cochrane 2012): a small benefit that shrinks with delay and a toxicity
##  ## that does not. Modelled: EMAX_MP_LP = 0.60 acting on ROS PRODUCTION (the
##  ## non-genomic high-dose lipid-peroxidation mechanism) plus EMAX_MP_CYT/NEU
##  ## on the genomic arm; because ROS production is a decaying pulse, the
##  ## efficacy integral collapses with start time while MP_AUC — and therefore
##  ## MP_complication_index — is identical. The 48-h regimen doubles exposure
##  ## for no further modelled benefit, which is the NASCIS III harm signal and
##  ## the reason MPSS was downgraded in the AANS/CNS guidelines.
##  ##
##  ## Early decompression (Fehlings 2012 STASCIS; Badhiwala 2021 Lancet Neurol):
##  ## modelled as relief of COMP0, which removes both the direct compressive
##  ## ischemia (K_ISCH_COMP) and the ISP contribution (K_ISP_COMP), breaking the
##  ## compression-edema-ischemia cycle. The model reproduces a graded, not
##  ## cliff-edged, benefit across 4-72 h — the shape Badhiwala's pooled analysis
##  ## reports — and shows that leaving the cord compressed indefinitely is
##  ## categorically different from being late (peak ischemia never resolves).
##  ##
##  ## Riluzole (RISCIS programme; Grossman 2014 J Neurotrauma 31:239): 55%
##  ## presynaptic release inhibition + enhanced astrocytic uptake gives a ~9%
##  ## reduction in lesion index and, at C5, +0.2 (AIS A) to +1.8 (AIS C) motor
##  ## points — deliberately calibrated to the small, grade-dependent effect
##  ## sizes the trial programme actually reports rather than to preclinical
##  ## enthusiasm.
##  ##
##  ## Minocycline (Casha 2012 Brain 135:1224): M1 blockade plus caspase
##  ## inhibition; largest effect on the lesion index among the drug arms here,
##  ## reflecting that its target (the macrophage phase) lasts days rather than
##  ## minutes — a wider window with a smaller instantaneous flux.
##  ##
##  ## Hemodynamic management (Hawryluk 2015 J Neurotrauma 32:1958; Squair 2017
##  ## Neurology 89:1660): VASO_GAIN = 20 mmHg for 7 days is the single most
##  ## effective modelled intervention (~55% lesion-index reduction, +2 motor
##  ## points at C5 AIS A), because it acts on the SCPP term that gates the
##  ## entire cascade for as long as the cord is swollen. This is a testable
##  ## model prediction and the reason SCPP is captured as an output.
##  ##
##  ## Plasticity-directed therapy (NISCI anti-Nogo-A, Kucher 2018; activity-
##  ## based rehabilitation; Angeli 2018 / Wagner 2018 epidural stimulation):
##  ## these act on PLAST and on the G_ESTIM amplification of residual drive,
##  ## NOT on AXON — so they change function without changing the imaging
##  ## surrogate at all, the mirror image of the neuroprotection problem.
##  ##
##  ## Spasticity, pain, bladder and dysreflexia are driven by REFLEX, which
##  ## matures with K_REFLEX = 0.05/d toward (1 - 0.85*hill): the LESS descending
##  ## drive survives, the MORE reflex pathology develops. Baclofen reduces
##  ## Ashworth through the same GABA-B mechanism that produces weakness
##  ## (K_BAC_WEAK), so the modelled motor score falls when spasticity is
##  ## suppressed — the trade-off is structural, not incidental.
##  ##
##  ## What is deliberately NOT modelled: GM-1 ganglioside (Sygen), naloxone and
##  ## tirilazad (negative trials, no mechanism worth carrying); cell
##  ## transplantation and chondroitinase beyond a parameter stub (CHASE);
##  ## syringomyelia and late neurological decline; pressure injuries, VTE and
##  ## the full cardiometabolic sequelae, which appear on the mechanistic map
##  ## but have no ODE here.
