## ============================================================================
##  Frontotemporal Dementia (FTD / FTLD) — QSP / PK-PD Model
## ============================================================================
##  Disease  : Frontotemporal lobar degeneration — the leading cause of dementia
##             under age 60 alongside early-onset Alzheimer's. Three Mendelian
##             genes account for most familial disease and converge on TWO
##             distinct proteinopathies:
##               GRN     (progranulin haploinsufficiency) -> FTLD-TDP type A
##               C9orf72 (GGGGCC repeat expansion)        -> FTLD-TDP type B +ALS
##               MAPT    (tau mutations)                  -> FTLD-tau, NO TDP-43
##             All three funnel into lysosomal / proteostatic failure, microglial
##             activation with COMPLEMENT-MEDIATED synapse elimination, and
##             degeneration of one specific large-scale network: salience network
##             / von Economo neurons -> bvFTD; anterior temporal -> svPPA;
##             left inferior frontal -> nfvPPA.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.5)
##  Time     : DAYS.
##
##  Scope    : 49 ODE compartments —
##             PK  (15): latozinemab 2-cmt with quasi-equilibrium TMDD on
##                       sortilin + CSF compartment; AAV-GRN vector -> transduced
##                       transgene pool; C9orf72 ASO (IT, CSF->tissue depot);
##                       MAPT ASO (IT, CSF->tissue depot); SSRI, trazodone and
##                       donepezil (oral).
##             PD  (34): THREE-compartment progranulin system (PLASMA / CSF /
##                       LYSOSOMAL), lysosomal function, lipofuscin, TDP-43
##                       (nuclear vs aggregate) with STMN2 / UNC13A cryptic
##                       splicing, C9 repeat RNA + poly-GP + poly-GR, MAPT mRNA
##                       -> soluble -> phospho -> aggregated tau, microglia ->
##                       C1q -> C3 -> synaptic pruning, astrocytes, synaptic
##                       density, two regional neuron pools, two regional
##                       volumes, CSF & plasma NfL, plasma GFAP, CSF BMP,
##                       serotonergic / cholinergic / dopaminergic tone,
##                       CDR plus NACC-FTLD SB, NPI, cumulative mortality hazard.
##
##  ==========================================================================
##  THE STRUCTURAL POINT THIS MODEL IS BUILT TO EXPOSE
##  ==========================================================================
##  Anti-sortilin therapy (latozinemab / AL001) reliably NORMALIZES plasma and
##  roughly DOUBLES CSF progranulin in GRN carriers — textbook target engagement
##  — and yet the phase 3 clinical endpoint did not move. In this model that
##  outcome is a PREDICTION of the structure, not a fudge.
##
##  Sortilin is BOTH (a) the dominant clearance route that sets extracellular
##  PGRN concentration and (b) one of the delivery routes filling the LYSOSOMAL
##  PGRN pool where progranulin actually does its job. Blocking it raises the
##  ligand and removes a delivery route AT THE SAME TIME. At steady state:
##
##      f     = sortilin share of CSF PGRN CLEARANCE
##      p     = sortilin share of LYSOSOMAL PGRN DELIVERY   (P_LYS_SORT)
##      theta = fractional sortilin occupancy by drug
##
##      CSF PGRN fold-rise       = 1 / (1 - f*theta)
##      LYSOSOMAL delivery ratio = (1 - p*theta) / (1 - f*theta)
##
##  Consequences, all dose-independent in sign:
##    * the sign of benefit depends ONLY on sign(f - p) — a property of the
##      BIOLOGY, not of the drug or the dose;
##    * if p = f the lysosomal pool is UNCHANGED at every occupancy: full
##      biomarker normalisation with mathematically zero delivery benefit;
##    * if p > f the drug LOWERS lysosomal PGRN while RAISING the biomarker;
##    * the ceiling as theta -> 1 is (1-p)/(1-f). You cannot dose past it,
##      because raising occupancy raises the ligand and removes delivery
##      capacity in lockstep;
##    * plasma PGRN rises for ANY value of p — so the registrational biomarker
##      is STRUCTURALLY INCAPABLE of measuring the parameter that decides
##      whether the drug works.
##
##  AAV-GRN gene therapy is NOT subject to this: it raises PRODUCTION, so
##  lysosomal delivery scales with transgene output and the receptor penalty
##  never appears. The model therefore predicts a qualitative separation
##  between two therapies with overlapping plasma-PGRN signatures — and in the
##  verified run the antibody reaches 49% of wild-type lysosomal PGRN from a
##  95%-of-control plasma level, while gene therapy reaches 80% from a LOWER
##  80% plasma level. A plasma-PGRN biomarker ranks them BACKWARDS.
##
##  P_LYS_SORT is NOT measured in humans. It is the single most consequential
##  number in this file and it is an assumption, exposed as a top-level
##  parameter precisely so it can be swept (see FTD_sweep_p()).
##  ==========================================================================
##
##  Numerically verified in ftd_reference_model.py (independent dependency-free
##  RK4 implementation of the same 49 states) — see ftd_model_report.txt for the
##  computed output, including the residual between the closed form above and
##  the integrated solution. Verified headline values:
##    * predicted onset ages MAPT 50.5 / C9orf72 54.3 / sporadic 59.2 y
##      (observed cohort means 50 / 57 / 58) and GRN 55.8 vs 61 observed — a
##      structural miss the report explains rather than hides;
##    * CSF/plasma antibody ratio 0.21%; peripheral occupancy 1.000, CNS 0.658;
##    * plasma PGRN 35% -> 95% of control, CSF 35% -> 73%, LYSOSOMAL 35% -> 49%;
##    * predicted 96-week CDR+NACC-FTLD SB slowing 0.65% — a predicted phase 3
##      miss coexisting with unambiguous target engagement;
##    * the benefit sign flips exactly at p = f_CSF = 0.780, at ANY dose;
##    * trazodone dNPI -5.8; donepezil dNPI +3.2 with dCDR EXACTLY 0.000;
##    * C9 ASO lowers CSF poly-GP 50% and moves CDR by -0.035;
##    * MAPT ASO lowers soluble tau 46% but AGGREGATED tau only 17%.
##
##  Calibration anchors (full citations in ftd_references.md):
##    * Plasma PGRN ~200 ng/mL in controls, ~1/3 of control in GRN carriers
##      (diagnostic cut-off commonly quoted near 110 ng/mL); CSF PGRN ~3 ng/mL
##      in controls, ~50% reduced in carriers. NOTE the asymmetry — plasma falls
##      to ~33% but CSF only to ~50%; the model reproduces both with DIFFERENT
##      compartment clearance structures rather than one gene-dose scalar.
##    * Latozinemab 60 mg/kg IV q4w: plasma PGRN restored to control range, CSF
##      PGRN ~2x, CSF C1QA and C3 reduced (INFRONT-1/2). INFRONT-3 did not meet
##      its primary CDR plus NACC-FTLD SB endpoint.
##    * Plasma NfL ~10 pg/mL in controls, ~50-80 pg/mL symptomatic; CSF NfL
##      ~700 vs 3000-5000; strongest single prognostic marker in FTD.
##    * CDR plus NACC-FTLD SB (0-24) progresses ~1.5-2.5 points/year when
##      symptomatic; brain atrophy 2-3 %/y vs ~0.5 %/y in controls.
##    * Genetic onset ages (GENFI / ALLFTD): MAPT ~50, C9orf72 ~57, GRN ~61 y.
##    * C9orf72 ASO (WVE-004, FOCUS-C9): CSF poly-GP lowered up to ~50%; NO
##      clinical benefit; programme discontinued. Modelled as such.
##    * MAPT ASO (BIIB080 class): CSF tau lowered ~30-50%.
##    * Trazodone (Lebert 2004 crossover RCT): NPI improved ~6-10 points.
##    * Memantine (Boxer 2013) negative; donepezil documented to WORSEN
##      behavioural disinhibition in bvFTD (Mendez 2007).
##    * The cholinergic system is largely PRESERVED in FTD, encoded here as
##      ACH_INTEGRITY = 0.95 so the AChEI null result emerges from STRUCTURE:
##      donepezil raises cholinergic tone and the cognitive endpoint does not
##      depend on it, so dCDR is exactly zero while behaviour gets worse.
##
##  KNOWN STRUCTURAL LIMITATION (stated, not hidden): the model has no
##  compensated latent phase — damage accumulates monotonically from t=0. That
##  single defect causes both the ~5-year GRN onset error and a presymptomatic
##  NfL lead time of ~15 y where ~1-2 y is reported. Fixing it requires a
##  different structure (a compensated regime that collapses at a threshold),
##  not a different parameter. See section J of ftd_model_report.txt.
##
##  Disclaimer: Research / education / hypothesis generation only. Not validated
##              for clinical decision-making or regulatory use.
## ============================================================================

library(mrgsolve)
library(dplyr)

FTD_code <- '
[PROB]
QSP model of frontotemporal dementia linking GRN / C9orf72 / MAPT genetic
drivers to a three-compartment progranulin system (plasma / CSF / lysosomal),
lysosomal-proteostatic failure, TDP-43 nuclear depletion with STMN2 & UNC13A
cryptic splicing, C9orf72 repeat RNA and dipeptide-repeat toxicity, tau
hyperphosphorylation and aggregation, microglial C1q-C3-mediated synaptic
pruning, regional neuronal loss and atrophy, fluid biomarkers (NfL, GFAP,
PGRN, poly-GP, BMP), neurotransmitter tone, and the CDR plus NACC-FTLD SB /
NPI clinical endpoints — with mechanistic PK/PD for latozinemab (anti-sortilin,
quasi-equilibrium TMDD), AAV-GRN gene therapy, C9orf72 and MAPT antisense
oligonucleotides, SSRI, trazodone, and an explicit donepezil null/harm arm.

[PLUGIN] Rcpp

[PARAM] @annotated
//=========================================================================
// GENOTYPE / PATIENT SETUP
//   Set exactly one genotype flag to 1 (all 0 = sporadic FTLD).
//   AGE0 is the age at t=0 and every trajectory starts CLINICALLY SILENT:
//   onset age is an OUTPUT of the model, not an input (see the age gate).
//=========================================================================
GENO_GRN     : 0     : 1 = heterozygous GRN loss-of-function carrier
GENO_C9      : 0     : 1 = C9orf72 GGGGCC repeat expansion carrier
GENO_MAPT    : 0     : 1 = MAPT mutation carrier
SPORADIC     : 1     : 1 = sporadic FTLD (no Mendelian gene)
ALS_FLAG     : 0     : 1 = FTD-ALS phenotype (C9-enriched; shortest survival)
PHENO_TEMP   : 0     : 1 = temporal-predominant (svPPA) label
TEMP_SHIFT   : 0     : 0-1, shift of regional burden toward temporal lobe
AGE0         : 30    : years, age at simulation start (clinically silent)
TMEM106B_PROT: 0     : 1 = protective TMEM106B haplotype (delays GRN onset)
BWT          : 70    : kg, body weight
PRESYMPT     : 0     : label only (retained for scenario bookkeeping)

//--- GRN allele dose & transcript stability -------------------------------
// Allele dose alone predicts 50% of control PGRN; observed plasma is ~1/3.
// KSYN_NMD carries the extra deficit (nonsense-mediated decay of the mutant
// transcript + lost autocrine recapture). FITTED, not measured.
GDOSE_HET    : 0.50  : fractional GRN transcription in heterozygotes
KSYN_NMD     : 0.70  : additional multiplier on synthesis in GRN carriers

//=========================================================================
// LATOZINEMAB (AL001) — anti-sortilin IgG1, 60 mg/kg IV q4w
//   2-compartment PK in nM with QUASI-EQUILIBRIUM TMDD. IgG binding to
//   sortilin is fast relative to every other timescale here and the drug sits
//   2-3 orders of magnitude above the receptor, so occupancy is taken at rapid
//   equilibrium rather than integrated as an explicit on/off pair. Receptor-
//   mediated elimination and drug-induced receptor downregulation are retained.
//   MW 145 kDa; dose entered in mg and F_CLATO converts mg -> nM.
//=========================================================================
MW_LATO      : 145000 : g/mol, latozinemab molecular weight
V1_LATO      : 3.0   : L, central volume
V2_LATO      : 3.6   : L, peripheral volume
CL_LATO      : 0.20  : L/day, linear (non-target) clearance
Q_LATO       : 0.45  : L/day, intercompartmental clearance
KD_SORT_PL   : 1.0   : nM, peripheral sortilin dissociation constant
KINT_SORT    : 0.25  : 1/day, receptor-mediated drug elimination
R0_SORT      : 30    : nM, baseline accessible sortilin
KDEG_SORT    : 0.35  : 1/day, sortilin receptor turnover
KDOWN_SORT   : 0.20  : 1/day, drug-induced sortilin downregulation
KIN_CSF      : 0.0020: 1/day, plasma->CSF transfer (gives ~0.2% exposure ratio)
KOUT_CSF     : 1.0   : 1/day, CSF bulk-flow elimination of antibody
KD_SORT_CNS  : 3.0   : nM, apparent in-situ CNS sortilin affinity

//=========================================================================
// AAV-GRN GENE THERAPY (PR006 / AVB-101 class) — single ICV/intraparenchymal
//=========================================================================
KDEC_VG      : 0.30  : 1/day, free vector-genome clearance
KTR_AAV      : 0.35  : 1/day, transduction rate (vector -> expressing cells)
KLOSS_TRANSD : 0.0004: 1/day, loss of transduced-cell expression (near-stable)
NAB_FRAC     : 0.0   : 0-1, pre-existing neutralising-antibody blockade
AAV_BOOST    : 1.10  : GRN-equivalent transcription per unit transduced pool

//=========================================================================
// C9orf72 ASO (WVE-004 / BIIB078 class) — intrathecal
//   EC50 in arbitrary depot units, fitted to reproduce the ~50% CSF poly-GP
//   lowering reported in FOCUS-C9 at the modelled dose/interval.
//=========================================================================
KOUT_ASO9_CSF: 2.5   : 1/day, CSF disappearance (rapid)
KTIS_ASO9    : 1.6   : 1/day, CSF -> CNS tissue uptake
KOUT_ASO9_TIS: 0.011 : 1/day, tissue depot elimination (t1/2 ~63 d)
EMAX_ASO9    : 0.60  : max fractional knockdown of C9 repeat RNA
EC50_ASO9    : 3.0   : au, tissue-depot potency
ASO9_ROSTRAL : 0.55  : 0-1, cortical (rostral) fraction of achieved exposure

//=========================================================================
// MAPT ASO (BIIB080 class) — intrathecal
//=========================================================================
KOUT_ASOT_CSF: 2.5   : 1/day, CSF disappearance
KTIS_ASOT    : 1.6   : 1/day, CSF -> tissue uptake
KOUT_ASOT_TIS: 0.010 : 1/day, tissue depot elimination (t1/2 ~69 d)
EMAX_ASOT    : 0.55  : max fractional MAPT mRNA knockdown
EC50_ASOT    : 3.5   : au, potency

//=========================================================================
// SYMPTOMATIC DRUGS
//=========================================================================
KA_SSRI      : 6.0   : 1/day, SSRI absorption
V_SSRI       : 900   : L, SSRI apparent volume (citalopram Vd/F)
KE_SSRI      : 0.46  : 1/day, SSRI elimination (t1/2 ~36 h)
EMAX_SERT    : 0.55  : max fractional SERT blockade
EC50_SERT    : 0.030 : mg/L, SERT-blockade potency
KA_TRZ       : 8.0   : 1/day, trazodone absorption
V_TRZ        : 90    : L, trazodone apparent volume
KE_TRZ       : 2.20  : 1/day, trazodone elimination (t1/2 ~7.5 h)
EMAX_TRZ     : 0.65  : max fractional reduction of behavioural drive
EC50_TRZ     : 0.60  : mg/L, trazodone potency
KA_DNP       : 4.0   : 1/day, donepezil absorption
V_DNP        : 830   : L, donepezil apparent volume
KE_DNP       : 0.238 : 1/day, donepezil elimination (t1/2 ~70 h)
EMAX_ACHE    : 0.60  : max fractional AChE inhibition
EC50_ACHE    : 0.020 : mg/L, AChE-inhibition potency
K_AGIT_DNP   : 0.55  : behavioural-drive INCREASE per unit AChE inhibition (harm)

//=========================================================================
// PROGRANULIN SYSTEM — the pivotal block
//=========================================================================
KSYN_PGRN_PL : 1400  : ng/mL/day equivalent, systemic PGRN production (WT)
KCL_SORT_PL  : 4.41  : 1/day, SORTILIN-mediated plasma PGRN clearance
KCL_OTH_PL   : 2.59  : 1/day, non-sortilin plasma PGRN clearance
                     : (=> f_plasma = 4.41/7.00 = 0.630, fitted to the 2.70x
                     :  plasma rise that normalises carriers to control range)
KSYN_PGRN_CSF: 6.00  : ng/mL/day equivalent, CNS PGRN production (WT)
KCL_SORT_CSF : 1.56  : 1/day, sortilin-mediated CSF PGRN clearance
KCL_OTH_CSF  : 0.44  : 1/day, non-sortilin CSF PGRN clearance
                     : (=> f_CSF = 0.780; with theta_CNS 0.658 gives 2.08x)
// ---- THE decisive unmeasured parameter -----------------------------------
P_LYS_SORT   : 0.50  : sortilin SHARE of lysosomal PGRN delivery (0-1).
                     : p < f_CSF -> anti-sortilin helps
                     : p = f_CSF -> exactly zero benefit at ANY dose
                     : p > f_CSF -> biomarker up, lysosomal PGRN DOWN
K_UPTAKE_LYS : 0.90  : 1/day, total lysosomal PGRN uptake capacity
KDEG_LYS_PGRN: 0.90  : 1/day, lysosomal PGRN/granulin turnover
PGRN_LYS_WT  : 1.00  : normalised WT lysosomal PGRN set-point
// Hypothesis switch: where does progranulin act?
W_ACT_LYS    : 0.80  : weight of the LYSOSOMAL pool in PGRN action
W_ACT_EXTRA  : 0.20  : weight of the EXTRACELLULAR (CSF) pool in PGRN action
                     : Swap to 0.20 / 0.80 for the rival "PGRN acts
                     : extracellularly" hypothesis (scenario 13).

//=========================================================================
// AGE GATE — why a lifelong carrier stays well for decades
//   Age-related decline of autophagic/lysosomal capacity and microglial
//   priming, (age/AGE_REF)^AGE_POW. Without this, onset is merely "t=0 plus a
//   fixed accrual time"; with it, onset AGE is a model OUTPUT. The exponent is
//   fitted to onset data, so the genotype ORDERING and the TMEM106B direction
//   are the predictions here, not the absolute ages.
//=========================================================================
AGE_REF      : 62.0  : years, reference age for the vulnerability gate
AGE_POW      : 5.0   : steepness of the age gate
AGE_FLOOR    : 0.02  : minimum gate value (young adulthood)
TMEM_ONSET_SHIFT: 0.88 : gate multiplier under the protective TMEM106B haplotype

//=========================================================================
// LYSOSOME / PROTEOSTASIS
//=========================================================================
KT_LYSO      : 0.030 : 1/day, lysosomal-function turnover toward target
HILL_LYSO    : 2.0   : Hill coefficient, PGRN action -> lysosomal function
K50_LYSO     : 0.28  : PGRN-action level giving half-maximal lysosomal function
C9_LYSO_PEN  : 0.09  : penalty from C9orf72 protein haploinsufficiency
TMEM_PEN     : 0.05  : additional penalty, non-protective TMEM106B haplotype
KGEN_LIPO    : 0.0008: 1/day, lipofuscin generation per unit lysosomal deficit
KCLR_LIPO    : 0.0006: 1/day, lipofuscin clearance
K_LIPO_DAM   : 0.10  : lysosomal-function loss per unit lipofuscin

//=========================================================================
// TDP-43 AXIS
//=========================================================================
KIN_TDP      : 0.0020: 1/day, restoration of nuclear TDP-43
KMIS_TDP     : 0.0030: 1/day, mislocalisation per unit proteostatic stress
W_STRESS_LYS : 0.30  : weight of lysosomal deficit in TDP-43 stress
W_STRESS_GA  : 0.18  : weight of poly-GA in TDP-43 stress
W_STRESS_OX  : 0.35  : constant oxidative/proteostatic stress (age-gated)
KAGG_TDP     : 2.60e-4 : 1/day, aggregation from cytoplasmic TDP-43
KSEED_TDP    : 0.85  : self-templating (prion-like) amplification
AGG_MAX_TDP  : 1.0   : carrying capacity of the TDP-43 aggregate pool
KCLR_TDP     : 3.50e-4 : 1/day, autophagic clearance of aggregate at LYSO=1
KCRYP_STMN2  : 0.040 : 1/day, STMN2 cryptic-exon generation
HILL_CRYP    : 1.6   : Hill coefficient, nuclear TDP-43 loss -> cryptic splicing
KDEG_STMN2   : 0.040 : 1/day, truncated-STMN2 turnover
KCRYP_UNC13A : 0.040 : 1/day, UNC13A cryptic-exon generation
KDEG_UNC13A  : 0.040 : 1/day, UNC13A product turnover

//=========================================================================
// C9orf72 REPEAT TOXICITY
//=========================================================================
KSYN_C9RNA   : 0.30  : 1/day, repeat-RNA transcription (carriers)
KDEG_C9RNA   : 0.30  : 1/day, repeat-RNA turnover
KRAN_GP      : 0.28  : 1/day, RAN translation to poly-GP
KDEG_GP      : 0.28  : 1/day, poly-GP turnover
KRAN_GR      : 0.18  : 1/day, RAN translation to poly-GR (toxic species)
KDEG_GR      : 0.20  : 1/day, poly-GR turnover
KRAN_GA_REL  : 1.20  : poly-GA relative to poly-GP (tracked algebraically)

//=========================================================================
// TAU AXIS
//=========================================================================
KSYN_TAUM    : 0.28  : 1/day, MAPT transcription
KDEG_TAUM    : 0.28  : 1/day, MAPT mRNA turnover
KTRL_TAU     : 0.30  : 1/day, translation to soluble tau
KDEG_TAUS    : 0.28  : 1/day, soluble-tau turnover
KPHOS_TAU    : 0.030 : 1/day, baseline tau phosphorylation
MUT_TAU_BOOST: 5.00  : extra phosphorylation/aggregation propensity, MAPT mutant
KDEPHOS_TAU  : 0.075 : 1/day, PP2A-mediated dephosphorylation
KOLIG_TAU    : 5.00e-4 : 1/day, oligomer/filament formation
KSEED_TAU    : 0.90  : self-templating tau amplification
AGG_MAX_TAU  : 1.0   : carrying capacity of the tau aggregate pool
KCLR_TAU     : 6.00e-4 : 1/day, autophagic clearance of tau aggregate at LYSO=1

//=========================================================================
// NEUROINFLAMMATION & COMPLEMENT
//=========================================================================
KACT_MG      : 0.030 : 1/day, microglial activation rate (age-gated)
KRES_MG      : 0.030 : 1/day, microglial resolution rate
W_MG_TDP     : 1.00  : microglial drive from TDP-43 aggregate
W_MG_TAU     : 0.90  : microglial drive from tau aggregate
W_MG_PGRN    : 0.60  : microglial drive from PGRN insufficiency (lost brake)
W_MG_GR      : 0.16  : microglial drive from poly-GR
KSYN_C1Q     : 0.10  : 1/day, C1q induction by activated microglia
KDEG_C1Q     : 0.10  : 1/day, C1q turnover
KSYN_C3      : 0.09  : 1/day, C3 induction downstream of C1q
KDEG_C3      : 0.09  : 1/day, C3 turnover
I_C1Q        : 0.0   : 0-1, exogenous anti-C1q inhibition (experimental arm)
KACT_AST     : 0.020 : 1/day, astrocyte activation
KRES_AST     : 0.020 : 1/day, astrocyte resolution

//=========================================================================
// SYNAPSE, NEURONS, VOLUME
//=========================================================================
KREP_SYN     : 1.12e-4 : 1/day, synaptic repair/homeostasis (declines with age)
KPRUNE_C3    : 3.00e-4 : 1/day, C3/CR3-mediated synapse elimination
KTOX_TAU_SYN : 1.50e-4 : 1/day, direct tau-oligomer synaptotoxicity
KTOX_UNC13A  : 3.00e-4 : 1/day, UNC13A-cryptic synaptic failure
KDEATH_SN    : 7.80e-5 : 1/day, salience-network neuron loss per unit toxicity
KDEATH_TEMP  : 5.60e-5 : 1/day, anterior-temporal neuron loss per unit toxicity
W_TOX_TDP    : 1.00  : neuronal toxicity weight, TDP-43 aggregate
W_TOX_TAU    : 1.00  : neuronal toxicity weight, tau aggregate
W_TOX_GR     : 0.16  : neuronal toxicity weight, poly-GR
W_TOX_CYT    : 0.70  : neuronal toxicity weight, cytokines/microglia
W_TOX_SYN    : 0.90  : neuronal toxicity weight, synaptic loss
W_TOX_STMN2  : 0.55  : neuronal toxicity weight, axonal (STMN2) failure
KATR_F       : 1.71e-4 : 1/day, frontal atrophy rate per unit damage
KATR_T       : 1.50e-4 : 1/day, temporal atrophy rate per unit damage
KATR_AGE     : 1.37e-5 : 1/day, age-related atrophy (~0.5%/y)

//=========================================================================
// BIOMARKERS
//=========================================================================
KPROD_NFL    : 930   : pg/mL/day per unit axonal degeneration
NFL_CSF_BASE : 700   : pg/mL, control CSF NfL
KOUT_NFL_CSF : 0.11  : 1/day, CSF NfL clearance
KTR_NFL      : 0.011 : 1/day, CSF -> plasma NfL transfer
KOUT_NFL_PL  : 0.60  : 1/day, plasma NfL clearance
NFL_PL_BASE  : 10.0  : pg/mL, control plasma NfL
KPROD_GFAP   : 130   : pg/mL/day per unit astrocyte activation
KOUT_GFAP    : 0.85  : 1/day, plasma GFAP clearance
GFAP_BASE    : 95    : pg/mL, control plasma GFAP
KPROD_BMP    : 48    : au/day per unit lysosomal deficit
KOUT_BMP     : 0.50  : 1/day, CSF BMP clearance
BMP_BASE     : 12.0  : au, control CSF BMP

//=========================================================================
// NEUROTRANSMITTERS
//=========================================================================
KIN_5HT      : 0.55  : 1/day, serotonergic tone production
KOUT_5HT     : 0.55  : 1/day, serotonergic tone loss (SERT-dependent)
W_5HT_LOSS   : 0.85  : fractional 5-HT production loss per unit neuronal loss
ACH_INTEGRITY: 0.95  : cholinergic system integrity (PRESERVED in FTD)
KIN_ACH      : 0.60  : 1/day, cholinergic tone production
KOUT_ACH     : 0.60  : 1/day, cholinergic tone loss (AChE-dependent)
KIN_DA       : 0.50  : 1/day, dopaminergic tone production
KOUT_DA      : 0.50  : 1/day, dopaminergic tone loss
W_DA_LOSS    : 0.55  : dopaminergic loss per unit tau/nigrostriatal burden

//=========================================================================
// CLINICAL ENDPOINTS
//=========================================================================
CDR_MAX      : 24    : CDR plus NACC-FTLD sum-of-boxes maximum
KCDR         : 0.0149: 1/day, CDR progression per unit functional damage
A_CDR_SYN    : 1.00  : CDR damage weight, synaptic loss
A_CDR_SN     : 1.20  : CDR damage weight, salience-network neuron loss
A_CDR_TEMP   : 0.60  : CDR damage weight, temporal neuron loss
A_CDR_VOL    : 0.80  : CDR damage weight, frontal volume loss
CDR_THRESH   : 0.45  : COGNITIVE RESERVE — accumulated damage below which no
                     : clinical deficit appears. This is what produces the long
                     : silent prodrome followed by relatively abrupt decline.
NPI_MAX      : 144   : NPI total maximum
KT_NPI       : 0.045 : 1/day, NPI equilibration toward its behavioural set-point
EMAX_NPI     : 0.42  : max fraction of NPI_MAX reachable
K50_NPI      : 0.62  : behavioural drive at half-maximal NPI
B_NPI_5HT    : 0.75  : behavioural drive from PRESYNAPTIC serotonergic deficit
                     : (SSRI-reversible; the postsynaptic/5-HT2A component sits
                     :  in B_NPI_SN and is NOT SSRI-reversible, which is why
                     :  SSRIs help behaviour partially and never fully)
B_NPI_SN     : 1.00  : behavioural drive from salience-network loss
B_NPI_DA     : 0.35  : behavioural drive from dopaminergic deficit
H0_HAZ       : 4.8e-5: 1/day, baseline mortality hazard
BH_CDR       : 0.115 : log-hazard per CDR+NACC-FTLD SB point
BH_NFL       : 0.42  : log-hazard per log-unit plasma NfL above control
BH_ALS       : 1.35  : log-hazard increment for FTD-ALS phenotype

[CMT] @annotated
//--- PK (15) --------------------------------------------------------------
CLATO     : nM, latozinemab central concentration
CPLATO    : nM, latozinemab peripheral concentration
SORTTOT   : nM, total accessible sortilin (falls with drug-induced downregulation)
BMPCSF    : au, CSF BMP — the LYSOSOMAL readout plasma PGRN cannot provide
CSFLATO   : nM, latozinemab CSF concentration
AAVVG     : au, free AAV vector genomes
TRANSD    : au, transduced-cell transgene-expressing pool
ASO9CSF   : au, C9orf72 ASO in CSF
ASO9TIS   : au, C9orf72 ASO CNS tissue depot
ASOTCSF   : au, MAPT ASO in CSF
ASOTTIS   : au, MAPT ASO CNS tissue depot
SSRIG     : mg, SSRI gut depot
SSRIC     : mg/L, SSRI plasma concentration
TRZC      : mg/L, trazodone plasma concentration
DNPC      : mg/L, donepezil plasma concentration
//--- Progranulin system (3) ----------------------------------------------
PGRNPL    : ng/mL, PLASMA progranulin
PGRNCSF   : ng/mL, CSF progranulin
PGRNLYS   : fraction of WT, LYSOSOMAL progranulin/granulin pool
//--- Lysosome (2) ---------------------------------------------------------
LYSO      : 0-1, lysosomal function index
LIPO      : au, lipofuscin/ceroid burden
//--- TDP-43 (4) -----------------------------------------------------------
TDPN      : 0-1, functional NUCLEAR TDP-43 fraction
TDPAGG    : au, cytoplasmic TDP-43 aggregate burden
STMN2T    : au, truncated STMN2 (cryptic exon) burden
UNC13AT   : au, UNC13A cryptic-exon burden
//--- C9orf72 (3) ----------------------------------------------------------
C9RNA     : au, GGGGCC repeat RNA / nuclear foci
POLYGP    : au, poly-GP dipeptide repeat (CSF-measurable)
POLYGR    : au, poly-GR dipeptide repeat (toxic species)
//--- Tau (4) --------------------------------------------------------------
TAUM      : au, MAPT mRNA
TAUS      : au, soluble tau
TAUP      : au, hyperphosphorylated / oligomeric tau
TAUAGG    : au, aggregated tau (filaments)
//--- Neuroinflammation (4) -----------------------------------------------
MG        : 0-1, disease-associated microglial activation
C1Q       : au, complement C1q
C3        : au, complement C3/C3b
AST       : 0-1, reactive astrocyte activation
//--- Structure (5) --------------------------------------------------------
SYN       : 0-1, synaptic density
NEURSN    : 0-1, salience-network (von Economo) neuron pool
NEURTMP   : 0-1, anterior-temporal neuron pool
VOLF      : %, frontal grey volume (% of baseline)
VOLT      : %, temporal grey volume (% of baseline)
//--- Fluid biomarkers (3) ------------------------------------------------
NFLCSF    : pg/mL, CSF neurofilament light
NFLPL     : pg/mL, plasma neurofilament light
GFAPPL    : pg/mL, plasma GFAP
//--- Neurotransmitters (3) -----------------------------------------------
HT5       : 0-1, serotonergic tone
ACH       : 0-1, cholinergic tone
DA        : 0-1, dopaminergic tone
//--- Clinical (3) ---------------------------------------------------------
CDR       : 0-24, CDR plus NACC-FTLD sum of boxes
NPI       : 0-144, Neuropsychiatric Inventory total
CUMHAZ    : -, cumulative mortality hazard

[MAIN]
//-------------------------------------------------------------------------
// Genotype-dependent GRN transcription: allele dose x transcript stability
//-------------------------------------------------------------------------
double GRNDOSE = GENO_GRN > 0.5 ? GDOSE_HET * KSYN_NMD : 1.0;

// Latozinemab: dose entered in mg -> nM in the central volume
F_CLATO = (1.0e6 / MW_LATO) / V1_LATO;

//-------------------------------------------------------------------------
// Initial conditions — a CLINICALLY SILENT carrier at age AGE0.
// Trial baselines are obtained by burn-in (see FTD_burnin() below), never by
// hand-setting a "symptomatic baseline", so treated and untreated arms share
// one continuous trajectory and baseline biomarkers are earned by the model.
//-------------------------------------------------------------------------
SORTTOT_0 = R0_SORT;
PGRNPL_0  = KSYN_PGRN_PL  * GRNDOSE / (KCL_SORT_PL  + KCL_OTH_PL);
PGRNCSF_0 = KSYN_PGRN_CSF * GRNDOSE / (KCL_SORT_CSF + KCL_OTH_CSF);

double PGRNCSF_WT = KSYN_PGRN_CSF / (KCL_SORT_CSF + KCL_OTH_CSF);
PGRNLYS_0 = (K_UPTAKE_LYS / KDEG_LYS_PGRN) * (PGRNCSF_0 / PGRNCSF_WT);

double ACT0 = W_ACT_LYS * PGRNLYS_0 + W_ACT_EXTRA * (PGRNCSF_0 / PGRNCSF_WT);
double PEN0 = (GENO_C9 > 0.5 ? C9_LYSO_PEN : 0.0)
            + (TMEM106B_PROT > 0.5 ? 0.0 : TMEM_PEN);
double LT0  = pow(ACT0, HILL_LYSO) / (pow(ACT0, HILL_LYSO) + pow(K50_LYSO, HILL_LYSO));
LYSO_0    = LT0 * (1.0 - PEN0);
LIPO_0    = 0.0;

TDPN_0    = 1.0;
TDPAGG_0  = 0.0;
STMN2T_0  = 0.0;
UNC13AT_0 = 0.0;

C9RNA_0   = GENO_C9 > 0.5 ? KSYN_C9RNA / KDEG_C9RNA : 0.0;
POLYGP_0  = KRAN_GP * C9RNA_0 / KDEG_GP;
POLYGR_0  = KRAN_GR * C9RNA_0 / KDEG_GR;

TAUM_0    = KSYN_TAUM / KDEG_TAUM;
TAUS_0    = KTRL_TAU * TAUM_0 / (KDEG_TAUS + KPHOS_TAU);
TAUP_0    = 0.0;
TAUAGG_0  = 0.0;

MG_0      = 0.0;
C1Q_0     = 0.0;
C3_0      = 0.0;
AST_0     = 0.0;

SYN_0     = 1.0;
NEURSN_0  = 1.0;
NEURTMP_0 = 1.0;
VOLF_0    = 100.0;
VOLT_0    = 100.0;

NFLCSF_0  = NFL_CSF_BASE;
NFLPL_0   = NFL_PL_BASE;
GFAPPL_0  = GFAP_BASE;
BMPCSF_0  = BMP_BASE + KPROD_BMP * (1.0 - LYSO_0) / KOUT_BMP;

HT5_0     = 1.0;
ACH_0     = ACH_INTEGRITY;
DA_0      = 1.0;

CDR_0     = 0.0;
NPI_0     = 0.0;
CUMHAZ_0  = 0.0;

[ODE]
//=========================================================================
// LATOZINEMAB PK with QUASI-EQUILIBRIUM TMDD on sortilin
//=========================================================================
double THETA_PL  = CLATO / (CLATO + KD_SORT_PL);
double THETA_CNS = CSFLATO / (CSFLATO + KD_SORT_CNS);
double RME       = KINT_SORT * THETA_PL * SORTTOT;   // receptor-mediated loss

dxdt_CLATO   = -(CL_LATO / V1_LATO) * CLATO
               - (Q_LATO / V1_LATO) * CLATO + (Q_LATO / V1_LATO) * CPLATO
               - KIN_CSF * CLATO - RME;
dxdt_CPLATO  =  (Q_LATO / V2_LATO) * CLATO - (Q_LATO / V2_LATO) * CPLATO;
dxdt_SORTTOT =  R0_SORT * KDEG_SORT - KDEG_SORT * SORTTOT
               - KDOWN_SORT * THETA_PL * SORTTOT;
dxdt_CSFLATO =  KIN_CSF * CLATO - KOUT_CSF * CSFLATO;

//=========================================================================
// AAV-GRN GENE THERAPY
//=========================================================================
dxdt_AAVVG  = -KDEC_VG * AAVVG - KTR_AAV * AAVVG * (1.0 - NAB_FRAC);
dxdt_TRANSD =  KTR_AAV * AAVVG * (1.0 - NAB_FRAC) - KLOSS_TRANSD * TRANSD;

//=========================================================================
// ANTISENSE OLIGONUCLEOTIDES
//=========================================================================
dxdt_ASO9CSF = -KOUT_ASO9_CSF * ASO9CSF - KTIS_ASO9 * ASO9CSF;
dxdt_ASO9TIS =  KTIS_ASO9 * ASO9CSF * ASO9_ROSTRAL - KOUT_ASO9_TIS * ASO9TIS;
dxdt_ASOTCSF = -KOUT_ASOT_CSF * ASOTCSF - KTIS_ASOT * ASOTCSF;
dxdt_ASOTTIS =  KTIS_ASOT * ASOTCSF * ASO9_ROSTRAL - KOUT_ASOT_TIS * ASOTTIS;

double KD9 = EMAX_ASO9 * ASO9TIS / (EC50_ASO9 + ASO9TIS);   // C9 RNA knockdown
double KDT = EMAX_ASOT * ASOTTIS / (EC50_ASOT + ASOTTIS);   // MAPT knockdown

//=========================================================================
// SYMPTOMATIC DRUG PK/PD
//=========================================================================
dxdt_SSRIG = -KA_SSRI * SSRIG;
dxdt_SSRIC =  KA_SSRI * SSRIG / V_SSRI - KE_SSRI * SSRIC;
dxdt_TRZC  = -KE_TRZ * TRZC;
dxdt_DNPC  = -KE_DNP * DNPC;

double SERTBLK = EMAX_SERT * SSRIC / (EC50_SERT + SSRIC);
double TRZBLK  = EMAX_TRZ  * TRZC  / (EC50_TRZ  + TRZC);
double ACHEBLK = EMAX_ACHE * DNPC  / (EC50_ACHE + DNPC);

//=========================================================================
// PROGRANULIN — the three-compartment system
//   PLASMA and CSF clearance each lose their SORTILIN component in proportion
//   to local occupancy; lysosomal DELIVERY loses its sortilin component in
//   proportion to the SAME CNS occupancy. That coupling is the whole point.
//=========================================================================
double GRND = (GENO_GRN > 0.5 ? GDOSE_HET * KSYN_NMD : 1.0)
              + AAV_BOOST * TRANSD;

dxdt_PGRNPL  = KSYN_PGRN_PL * GRND
               - KCL_SORT_PL * (1.0 - THETA_PL) * PGRNPL
               - KCL_OTH_PL * PGRNPL;

dxdt_PGRNCSF = KSYN_PGRN_CSF * GRND
               - KCL_SORT_CSF * (1.0 - THETA_CNS) * PGRNCSF
               - KCL_OTH_CSF * PGRNCSF;

double PCSFWT = KSYN_PGRN_CSF / (KCL_SORT_CSF + KCL_OTH_CSF);
double PCSFN  = PGRNCSF / PCSFWT;              // CSF PGRN, WT-normalised

// Lysosomal uptake: the sortilin share p is BLOCKED by the same drug that
// raised the ligand. The prosaposin/LRP1 share is untouched.
double UPTAKE = K_UPTAKE_LYS
                * (P_LYS_SORT * (1.0 - THETA_CNS) + (1.0 - P_LYS_SORT))
                * PCSFN;
dxdt_PGRNLYS = UPTAKE - KDEG_LYS_PGRN * PGRNLYS;

double PGRNACT = W_ACT_LYS * PGRNLYS + W_ACT_EXTRA * PCSFN;

//=========================================================================
// AGE GATE
//=========================================================================
double AGEYR  = AGE0 + SOLVERTIME / 365.0;
double AGEFAC = pow((AGEYR > 1.0 ? AGEYR : 1.0) / AGE_REF, AGE_POW) + AGE_FLOOR;
if (TMEM106B_PROT > 0.5) AGEFAC = AGEFAC * TMEM_ONSET_SHIFT;

//=========================================================================
// LYSOSOMAL FUNCTION & LIPOFUSCIN
//=========================================================================
double PEN = (GENO_C9 > 0.5 ? C9_LYSO_PEN : 0.0)
           + (TMEM106B_PROT > 0.5 ? 0.0 : TMEM_PEN);
double PA  = PGRNACT > 1e-9 ? PGRNACT : 1e-9;
double LYSOTGT = pow(PA, HILL_LYSO) / (pow(PA, HILL_LYSO) + pow(K50_LYSO, HILL_LYSO));
LYSOTGT = LYSOTGT * (1.0 - PEN) - K_LIPO_DAM * LIPO;
if (LYSOTGT < 0.0) LYSOTGT = 0.0;

dxdt_LYSO = KT_LYSO * (LYSOTGT - LYSO);
dxdt_LIPO = KGEN_LIPO * (1.0 - LYSO) - KCLR_LIPO * LIPO;

//=========================================================================
// TDP-43: nuclear depletion -> aggregation -> cryptic splicing
//   MAPT-mutation FTLD has NO TDP-43 pathology — enforced structurally.
//=========================================================================
double AGGC_T = TDPAGG < 0.0 ? 0.0 : (TDPAGG > AGG_MAX_TDP ? AGG_MAX_TDP : TDPAGG);
double POLYGA = KRAN_GA_REL * POLYGP;
double TDPDRIVE = (W_STRESS_LYS * (1.0 - LYSO)
                 + W_STRESS_GA * POLYGA
                 + W_STRESS_OX)
                 * AGEFAC * (1.0 + KSEED_TDP * AGGC_T);
double TDP_ALLOWED = (GENO_MAPT > 0.5) ? 0.0 : 1.0;   // pure tauopathy guard

dxdt_TDPN = KIN_TDP * (1.0 - TDPN)
            - KMIS_TDP * TDPN * TDPDRIVE * TDP_ALLOWED;

double CYTO_TDP = 1.0 - TDPN;
dxdt_TDPAGG = KAGG_TDP * CYTO_TDP * (1.0 + KSEED_TDP * AGGC_T)
              * (1.0 - AGGC_T / AGG_MAX_TDP) * TDP_ALLOWED
              - KCLR_TDP * LYSO * TDPAGG;

double CRYPD = CYTO_TDP > 0.0 ? pow(CYTO_TDP, HILL_CRYP) : 0.0;
dxdt_STMN2T  = KCRYP_STMN2 * CRYPD - KDEG_STMN2 * STMN2T;
dxdt_UNC13AT = KCRYP_UNC13A * CRYPD - KDEG_UNC13A * UNC13AT;

//=========================================================================
// C9orf72 REPEAT TOXICITY (ASO-sensitive at the RNA step)
//=========================================================================
double C9ON = GENO_C9 > 0.5 ? 1.0 : 0.0;
dxdt_C9RNA  = KSYN_C9RNA * C9ON * (1.0 - KD9) - KDEG_C9RNA * C9RNA;
dxdt_POLYGP = KRAN_GP * C9RNA - KDEG_GP * POLYGP;
dxdt_POLYGR = KRAN_GR * C9RNA - KDEG_GR * POLYGR;

//=========================================================================
// TAU CASCADE (MAPT-ASO-sensitive at the mRNA step)
//=========================================================================
double TAUBOOST = 1.0 + (GENO_MAPT > 0.5 ? MUT_TAU_BOOST : 0.0);
double AGGC_U = TAUAGG < 0.0 ? 0.0 : (TAUAGG > AGG_MAX_TAU ? AGG_MAX_TAU : TAUAGG);
dxdt_TAUM = KSYN_TAUM * (1.0 - KDT) - KDEG_TAUM * TAUM;
dxdt_TAUS = KTRL_TAU * TAUM - KDEG_TAUS * TAUS - KPHOS_TAU * TAUBOOST * TAUS;
dxdt_TAUP = KPHOS_TAU * TAUBOOST * TAUS - KDEPHOS_TAU * TAUP - KOLIG_TAU * TAUP;
dxdt_TAUAGG = KOLIG_TAU * AGEFAC * TAUP * (1.0 + KSEED_TAU * AGGC_U)
              * (1.0 - AGGC_U / AGG_MAX_TAU)
              - KCLR_TAU * LYSO * TAUAGG;

//=========================================================================
// NEUROINFLAMMATION: microglia -> C1q -> C3 -> synaptic pruning
//=========================================================================
double PLYS_CAP = PGRNLYS < 1.0 ? PGRNLYS : 1.0;
double MGDRIVE = W_MG_TDP * TDPAGG
               + W_MG_TAU * TAUAGG
               + W_MG_PGRN * (1.0 - PLYS_CAP)
               + W_MG_GR * POLYGR;
dxdt_MG  = KACT_MG * AGEFAC * MGDRIVE * (1.0 - MG) - KRES_MG * MG;
dxdt_C1Q = KSYN_C1Q * MG * (1.0 - I_C1Q) - KDEG_C1Q * C1Q;
dxdt_C3  = KSYN_C3 * C1Q - KDEG_C3 * C3;
dxdt_AST = KACT_AST * (TDPAGG + TAUAGG + MG) * (1.0 - AST) - KRES_AST * AST;

//=========================================================================
// SYNAPSE & NEURONS
//=========================================================================
dxdt_SYN = KREP_SYN / AGEFAC * (1.0 - SYN)
           - KPRUNE_C3 * C3 * SYN
           - KTOX_TAU_SYN * TAUP * SYN
           - KTOX_UNC13A * UNC13AT * SYN;

double TOX = W_TOX_TDP * TDPAGG
           + W_TOX_TAU * TAUAGG
           + W_TOX_GR  * POLYGR
           + W_TOX_CYT * MG
           + W_TOX_SYN * (1.0 - SYN)
           + W_TOX_STMN2 * STMN2T;

double WSN = 1.0 - TEMP_SHIFT;
double WTP = 0.55 + TEMP_SHIFT;
dxdt_NEURSN  = -KDEATH_SN   * TOX * WSN * NEURSN;
dxdt_NEURTMP = -KDEATH_TEMP * TOX * WTP * NEURTMP;

double DAMF = 0.60 * (1.0 - NEURSN) + 0.40 * (1.0 - SYN);
double DAMT = 0.60 * (1.0 - NEURTMP) + 0.40 * (1.0 - SYN);
dxdt_VOLF = -KATR_F * DAMF * VOLF - KATR_AGE * VOLF;
dxdt_VOLT = -KATR_T * DAMT * VOLT - KATR_AGE * VOLT;

//=========================================================================
// FLUID BIOMARKERS
//=========================================================================
double AXDEG = 0.55 * (1.0 - NEURSN) + 0.30 * (1.0 - NEURTMP)
             + 0.45 * STMN2T + 0.25 * (1.0 - SYN);
dxdt_NFLCSF = KPROD_NFL * AXDEG + KOUT_NFL_CSF * NFL_CSF_BASE
              - KOUT_NFL_CSF * NFLCSF;
dxdt_NFLPL  = KTR_NFL * NFLCSF + KOUT_NFL_PL * NFL_PL_BASE
              - KTR_NFL * NFL_CSF_BASE - KOUT_NFL_PL * NFLPL;
dxdt_GFAPPL = KPROD_GFAP * AST + KOUT_GFAP * GFAP_BASE - KOUT_GFAP * GFAPPL;
// CSF BMP tracks LYSOSOMAL function, i.e. the pool plasma PGRN cannot see.
dxdt_BMPCSF = KPROD_BMP * (1.0 - LYSO) + KOUT_BMP * BMP_BASE - KOUT_BMP * BMPCSF;

//=========================================================================
// NEUROTRANSMITTERS
//   Serotonergic: production falls with neuronal loss; SSRI blocks reuptake.
//   Cholinergic:  production is NEARLY INTACT, so AChE inhibition raises a
//                 tone that was never rate-limiting -> no cognitive gain,
//                 only the behavioural harm term downstream.
//=========================================================================
dxdt_HT5 = KIN_5HT * (1.0 - W_5HT_LOSS * (1.0 - NEURSN))
           - KOUT_5HT * (1.0 - SERTBLK) * HT5;
dxdt_ACH = KIN_ACH * ACH_INTEGRITY - KOUT_ACH * (1.0 - ACHEBLK) * ACH;
double TAUAGG_CAP = TAUAGG < 1.0 ? TAUAGG : 1.0;
dxdt_DA  = KIN_DA * (1.0 - W_DA_LOSS * TAUAGG_CAP) - KOUT_DA * DA;

//=========================================================================
// CLINICAL ENDPOINTS
//=========================================================================
double CDRDAM = A_CDR_SYN  * (1.0 - SYN)
              + A_CDR_SN   * (1.0 - NEURSN)
              + A_CDR_TEMP * (1.0 - NEURTMP)
              + A_CDR_VOL  * (1.0 - VOLF / 100.0);
double CDRDRIVE = CDRDAM - CDR_THRESH;      // cognitive reserve
if (CDRDRIVE < 0.0) CDRDRIVE = 0.0;
dxdt_CDR = KCDR * CDRDRIVE * (1.0 - CDR / CDR_MAX);

double DEF5HT = 1.0 - HT5; if (DEF5HT < 0.0) DEF5HT = 0.0;
double DEFDA  = 1.0 - DA;  if (DEFDA  < 0.0) DEFDA  = 0.0;
double NPIDRIVE = B_NPI_5HT * DEF5HT
                + B_NPI_SN  * (1.0 - NEURSN)
                + B_NPI_DA  * DEFDA;
NPIDRIVE = NPIDRIVE * (1.0 - TRZBLK) * (1.0 + K_AGIT_DNP * ACHEBLK);
double NPITGT = NPI_MAX * EMAX_NPI * NPIDRIVE / (K50_NPI + NPIDRIVE);
dxdt_NPI = KT_NPI * (NPITGT - NPI);

double NFLR = NFLPL / NFL_PL_BASE; if (NFLR < 1e-6) NFLR = 1e-6;
double HAZARG = BH_CDR * CDR + BH_NFL * log(NFLR) + BH_ALS * ALS_FLAG;
if (HAZARG > 50.0) HAZARG = 50.0;
dxdt_CUMHAZ = H0_HAZ * exp(HAZARG);

[TABLE]
double PGRNPL_PCT  = 100.0 * PGRNPL  / (KSYN_PGRN_PL  / (KCL_SORT_PL  + KCL_OTH_PL));
double PGRNCSF_PCT = 100.0 * PGRNCSF / (KSYN_PGRN_CSF / (KCL_SORT_CSF + KCL_OTH_CSF));
double PGRNLYS_PCT = 100.0 * PGRNLYS / PGRN_LYS_WT;
double SORT_OCC_PL  = CLATO / (CLATO + KD_SORT_PL);
double SORT_OCC_CNS = CSFLATO / (CSFLATO + KD_SORT_CNS);
double SURVIVAL = exp(-CUMHAZ);
double FRS_LOGIT = 4.2 - 0.62 * CDR;   // FTD Rating Scale logit (higher=better)
double VOL_WB = 0.55 * VOLF + 0.45 * VOLT;
double SYMPTOMATIC = (CDR >= 3.0) ? 1.0 : 0.0;
double AGE_NOW = AGE0 + TIME / 365.0;

[CAPTURE] @annotated
PGRNPL_PCT   : %, plasma PGRN as % of control
PGRNCSF_PCT  : %, CSF PGRN as % of control
PGRNLYS_PCT  : %, LYSOSOMAL PGRN as % of WT (the pool that matters)
SORT_OCC_PL  : -, peripheral sortilin occupancy
SORT_OCC_CNS : -, CNS sortilin occupancy
SURVIVAL     : -, model survival probability
FRS_LOGIT    : -, FTD Rating Scale logit (higher = better)
VOL_WB       : %, whole-brain grey volume (% baseline)
SYMPTOMATIC  : -, 1 once CDR+NACC-FTLD SB >= 3
AGE_NOW      : y, current age
'

## ---------------------------------------------------------------------------
## Build
## ---------------------------------------------------------------------------
FTD_mod <- mcode("FTD_QSP", FTD_code)

## ---------------------------------------------------------------------------
## Genotype helper
## ---------------------------------------------------------------------------
FTD_genotype <- function(which = c("sporadic", "GRN", "C9", "MAPT")) {
  which <- match.arg(which)
  switch(
    which,
    sporadic = list(GENO_GRN = 0, GENO_C9 = 0, GENO_MAPT = 0, SPORADIC = 1,
                    AGE0 = 30),
    GRN      = list(GENO_GRN = 1, GENO_C9 = 0, GENO_MAPT = 0, SPORADIC = 0,
                    AGE0 = 30),
    C9       = list(GENO_GRN = 0, GENO_C9 = 1, GENO_MAPT = 0, SPORADIC = 0,
                    AGE0 = 30, ALS_FLAG = 1),
    MAPT     = list(GENO_GRN = 0, GENO_C9 = 0, GENO_MAPT = 1, SPORADIC = 0,
                    AGE0 = 30)
  )
}

## ---------------------------------------------------------------------------
## FTD_burnin() — the disease clock
##
##   Runs the natural history from a clinically silent carrier until the CDR
##   plus NACC-FTLD SB reaches `cdr_target`, and returns that state together
##   with the elapsed time. Trial scenarios START HERE rather than from
##   hand-set "symptomatic baseline" initial conditions, so a treated and an
##   untreated arm share one continuous trajectory and every baseline
##   biomarker value is EARNED by the model instead of assumed.
## ---------------------------------------------------------------------------
FTD_burnin <- function(pars, cdr_target = 5.5, max_years = 80, delta = 1) {
  out <- FTD_mod |>
    param(pars) |>
    mrgsim(end = max_years * 365, delta = delta) |>
    as_tibble()
  hit <- which(out$CDR >= cdr_target)
  if (!length(hit)) {
    stop("burn-in never reached CDR = ", cdr_target,
         " (max CDR ", round(max(out$CDR), 2), ")")
  }
  i <- hit[1]
  states <- mrgsolve::cmt(FTD_mod)
  list(
    time = out$time[i],
    onset_age = pars$AGE0 + out$time[i] / 365,
    init = as.list(out[i, states]),
    trajectory = out[seq_len(i), ]
  )
}

## Run a scenario forward from a burn-in state.
FTD_from_onset <- function(pars, bi, events = NULL, weeks = 96, delta = 7) {
  m <- FTD_mod |> param(pars) |> init(bi$init)
  tend <- weeks * 7
  if (is.null(events)) {
    mrgsim(m, end = tend, delta = delta) |> as_tibble()
  } else {
    mrgsim_e(m, events, end = tend, delta = delta) |> as_tibble()
  }
}

## ---------------------------------------------------------------------------
## Dosing event builders
## ---------------------------------------------------------------------------
# Latozinemab 60 mg/kg IV q4w. Dose in mg; F_CLATO converts to nM.
ev_latozinemab <- function(mgkg = 60, bwt = 70, n = 24, start = 0) {
  ev(time = start, amt = mgkg * bwt, cmt = "CLATO", ii = 28, addl = n - 1)
}
# AAV-GRN: single administration into the vector compartment
ev_aav_grn <- function(dose = 1.0, start = 0) {
  ev(time = start, amt = dose, cmt = "AAVVG")
}
# C9orf72 ASO intrathecal q12w
ev_aso_c9 <- function(dose = 100, n = 8, start = 0) {
  ev(time = start, amt = dose, cmt = "ASO9CSF", ii = 84, addl = n - 1)
}
# MAPT ASO intrathecal q12w
ev_aso_mapt <- function(dose = 100, n = 8, start = 0) {
  ev(time = start, amt = dose, cmt = "ASOTCSF", ii = 84, addl = n - 1)
}
# SSRI (citalopram 30 mg) PO daily
ev_ssri <- function(dose = 30, n = 672, start = 0) {
  ev(time = start, amt = dose, cmt = "SSRIG", ii = 1, addl = n - 1)
}
# Trazodone 150 mg PO daily (dosed into the plasma compartment, scaled by V
# so that amt/V is the concentration increment)
ev_trazodone <- function(dose = 150, n = 672, start = 0, V = 90) {
  ev(time = start, amt = dose / V, cmt = "TRZC", ii = 1, addl = n - 1)
}
# Donepezil 10 mg PO daily — the NULL / HARM arm
ev_donepezil <- function(dose = 10, n = 672, start = 0, V = 830) {
  ev(time = start, amt = dose / V, cmt = "DNPC", ii = 1, addl = n - 1)
}

## ---------------------------------------------------------------------------
## 13 PREBUILT SCENARIOS
##   1-5   natural history by genotype / phenotype (onset age is an OUTPUT)
##   6-10  disease-modifying therapy from the model's own onset state
##   11-12 symptomatic pharmacology, including the null/harm arm
##   13    the rival hypothesis: same drug, opposite prediction
## ---------------------------------------------------------------------------
FTD_simulate_scenarios <- function(nat_years = 45, weeks = 96) {

  G <- list(GRN = FTD_genotype("GRN"), C9 = FTD_genotype("C9"),
            MAPT = FTD_genotype("MAPT"), SPO = FTD_genotype("sporadic"))
  svppa <- c(G$SPO, list(PHENO_TEMP = 1, TEMP_SHIFT = 0.40))

  nat <- function(label, pars) {
    FTD_mod |> param(pars) |>
      mrgsim(end = nat_years * 365, delta = 30) |>
      as_tibble() |> mutate(scenario = label)
  }
  tx <- function(label, pars, events = NULL) {
    bi <- FTD_burnin(pars)
    FTD_from_onset(pars, bi, events, weeks = weeks) |>
      mutate(scenario = label, onset_age = bi$onset_age)
  }

  bind_rows(
    ## --- natural history -------------------------------------------------
    nat("01 GRN natural history (onset age predicted)",   G$GRN),
    nat("02 C9orf72 FTD-ALS natural history",             G$C9),
    nat("03 MAPT FTLD-tau natural history",               G$MAPT),
    nat("04 Sporadic bvFTD natural history",              G$SPO),
    nat("05 Sporadic svPPA (temporal-predominant)",       svppa),

    ## --- disease-modifying ------------------------------------------------
    tx("06 GRN untreated reference (from onset)",         G$GRN),
    tx("07 GRN + latozinemab 60 mg/kg q4w",               G$GRN,
       ev_latozinemab(60, 70, n = ceiling(weeks * 7 / 28))),
    tx("08 GRN + AAV-GRN gene therapy (single dose)",     G$GRN,
       ev_aav_grn(1.0)),
    tx("09 C9orf72 + repeat-targeting ASO q12w",          G$C9,
       ev_aso_c9(100, n = 8)),
    tx("10 MAPT + MAPT-lowering ASO q12w",                G$MAPT,
       ev_aso_mapt(100, n = 8)),

    ## --- symptomatic ------------------------------------------------------
    tx("11 GRN + SSRI + trazodone",                       G$GRN,
       c(ev_ssri(30, n = weeks * 7), ev_trazodone(150, n = weeks * 7))),
    tx("12 GRN + donepezil (NULL / HARM arm)",            G$GRN,
       ev_donepezil(10, n = weeks * 7)),

    ## --- rival hypothesis -------------------------------------------------
    tx("13 Latozinemab, extracellular-PGRN hypothesis",
       c(G$GRN, list(W_ACT_LYS = 0.20, W_ACT_EXTRA = 0.80)),
       ev_latozinemab(60, 70, n = ceiling(weeks * 7 / 28)))
  )
}

## ---------------------------------------------------------------------------
## Sensitivity sweep on the pivotal unmeasured parameter P_LYS_SORT
##   Reproduces the sign flip at p = f_CSF = 0.780 and the (1-p)/(1-f) ceiling,
##   and shows that plasma PGRN is INVARIANT across the whole sweep.
## ---------------------------------------------------------------------------
FTD_sweep_p <- function(p_grid = seq(0, 0.95, by = 0.05), weeks = 96) {
  G <- FTD_genotype("GRN")
  lapply(p_grid, function(pv) {
    pars <- c(G, list(P_LYS_SORT = pv))
    bi <- FTD_burnin(pars)
    n <- ceiling(weeks * 7 / 28)
    treated <- FTD_from_onset(pars, bi, ev_latozinemab(60, 70, n = n),
                              weeks = weeks)
    control <- FTD_from_onset(pars, bi, NULL, weeks = weeks)
    tibble(
      P_LYS_SORT   = pv,
      PGRNPL_PCT   = tail(treated$PGRNPL_PCT, 1),
      PGRNLYS_PCT  = tail(treated$PGRNLYS_PCT, 1),
      lyso_ratio   = tail(treated$PGRNLYS, 1) / tail(control$PGRNLYS, 1),
      ceiling      = (1 - pv) / (1 - 0.78),
      dCDR         = tail(treated$CDR, 1) - tail(control$CDR, 1),
      dBMP         = tail(treated$BMPCSF, 1) - tail(control$BMPCSF, 1)
    )
  }) |> bind_rows()
}

## ---------------------------------------------------------------------------
## Quick usage
## ---------------------------------------------------------------------------
if (FALSE) {
  ## Predicted onset ages (compare GENFI/ALLFTD: MAPT ~50, C9 ~57, GRN ~61)
  for (g in c("MAPT", "C9", "GRN", "sporadic")) {
    bi <- FTD_burnin(FTD_genotype(g))
    cat(sprintf("%-9s predicted onset age %.1f y\n", g, bi$onset_age))
  }

  res <- FTD_simulate_scenarios()

  ## The biomarker / target dissociation
  res |>
    filter(scenario %in% c("06 GRN untreated reference (from onset)",
                           "07 GRN + latozinemab 60 mg/kg q4w",
                           "08 GRN + AAV-GRN gene therapy (single dose)"),
           time == max(time)) |>
    select(scenario, PGRNPL_PCT, PGRNCSF_PCT, PGRNLYS_PCT, CDR, NFLPL, BMPCSF)

  ## The sign flip, and the invariance of the plasma biomarker
  FTD_sweep_p()
}
