# =============================================================================
#  aad_mrgsolve_model.R
#  Acute Type B Aortic Dissection (AAD) — 53-ODE QSP model for mrgsolve
#  급성 B형 대동맥 박리 — mrgsolve 정량적 시스템 약리학 모델
# =============================================================================
#
#  WHAT THIS MODEL IS ORGANISED AROUND
#  -----------------------------------
#  One product and one divider.
#
#  THE PRODUCT.  What tears an aorta is not blood pressure, it is
#
#      ASI = (sigma_FL_sys / sigma_ref) * (dPdt_max / dPdt_ref)
#
#  a STRESS term and an IMPULSE term generated by different organs.  sigma comes
#  from Laplace applied to the FALSE lumen outer wall, which is outer media plus
#  adventitia only (h_FL = 0.40 * h_aorta), so at identical pressure the false
#  lumen carries about 2.5x the true lumen's circumferential stress.  dPdt_max
#  comes from the left ventricle and is set by contractility and heart rate,
#  which the arterial baroreflex RAISES when pressure falls.  A pure vasodilator
#  therefore lowers the first factor and pushes the second one back up.
#
#  THE DIVIDER.  The false lumen is a compliant chamber joined to the true lumen
#  by an entry-tear conductance G_EN and a distal re-entry conductance G_RE.
#  Its mean pressure is a resistive divider and its pulse pressure is RC
#  low-pass filtered with tau_FL ~ 1/(G_EN+G_RE).  Set G_RE to zero and the
#  false lumen becomes a blind sac: no outflow means no pressure drop, and the
#  filtered-out pulse means false-lumen DIASTOLIC pressure rises to the systemic
#  MEAN.  The stagnant distal sac clots while the entry tear stays open — which
#  is what "partial thrombosis" is, and it is the worst configuration in the
#  model without any equation saying so.
#
#  VERIFICATION STATUS
#  -------------------
#  Every equation below was independently re-implemented in Python/scipy
#  (aad_reference_model.py, LSODA) and all 22 scenarios were integrated.  That
#  exercise found and fixed nine defects, each recorded in a NOTE comment at the
#  equation responsible:
#    (1) an unbounded stress -> IL-6 -> MMP-9 -> wall-thinning loop that reached
#        MMP-9 44x normal and a 0.16 mm aortic wall by year 3;
#    (2) complete baroreflex resetting, which walked the untreated arm's own MAP
#        to 160 mmHg and beyond with no equilibrium;
#    (3) a dynamic-obstruction criterion satisfied at t = 0 in every patient,
#        which put the reference case in renal failure before any drug;
#    (4) no stress-driven collagen, i.e. no negative feedback anywhere in the
#        remodelling block, so no stable chronic state existed;
#    (5) flap stress that ignored exposure, making a fully thrombosed
#        depressurised false lumen the highest flap stress in the model;
#    (6) flap stress that ignored tear size, so a 9 mm2 entry tear did worse
#        than a 42 mm2 one - the opposite of every cohort;
#    (7) a softplus tail in the malperfusion hazard which leaked 1.05e-5/h from
#        perfectly perfused organs and became the leading cause of death in
#        every 5-year arm;
#    (8) a cord-ischaemia term written as a lifetime integral, which reported
#        certain paraplegia in all arms;
#    (9) 10/10 pain sustained for five years in chronic dissection, and with it
#        a phantom sympathetic cause of chronic hypertension.
#
#  UNITS
#  -----
#  time h · amounts mg · volumes L · pressure mmHg · diameter mm · stress kPa
#  dP/dt mmHg/s · flow L/min · resistance mmHg*min/L
#
#  USAGE
#  -----
#    library(mrgsolve); library(dplyr)
#    mod <- mread("aad_mrgsolve_model", "aortic-dissection")
#    # S04: guideline order, esmolol to HR 60 then nicardipine to SBP 110
#    mod %>% param(BB_AGENT = 1, BB_MAX = 900, VD_AGENT = 1, VD_MAX = 15) %>%
#            mrgsim(end = 72, delta = 0.1) %>% plot(SBP + HR + DPDT + ASI ~ time)
#
# =============================================================================

$PROB
# Acute type B aortic dissection — stress x impulse QSP model (53 ODEs)

$PARAM @annotated
WT      :  75.0 : Body weight (kg)

// ---- esmolol: RBC esterase, t1/2 9 min ------------------------------------
V_ESM   : 255.0 : Esmolol volume (L)
CL_ESM  : 1283. : Esmolol clearance (L/h)
IC50_ESM:  0.55 : Esmolol beta1 IC50 (mg/L)
// ---- labetalol: t1/2 5.4 h, IV alpha:beta = 1:7 ---------------------------
V_LAB   : 420.0 : Labetalol central volume (L)
V_LAB2  : 130.0 : Labetalol peripheral volume (L)
CL_LAB  :  70.0 : Labetalol clearance (L/h)
Q_LAB   :  45.0 : Labetalol intercompartmental clearance (L/h)
IC50_LABB: 0.13 : Labetalol beta1 IC50 (mg/L)
IC50_LABA: 0.91 : Labetalol alpha1 IC50 (mg/L)
// ---- metoprolol oral (chronic arm) ---------------------------------------
KA_MET  :   1.2 : Metoprolol absorption rate (1/h)
F_MET   :  0.40 : Metoprolol bioavailability
V_MET   : 300.0 : Metoprolol volume (L)
CL_MET  :  63.0 : Metoprolol clearance (L/h)
IC50_MET: 0.035 : Metoprolol beta1 IC50 (mg/L)
// ---- nicardipine IV ------------------------------------------------------
V_NIC   :  45.0 : Nicardipine central volume (L)
V_NIC2  : 200.0 : Nicardipine peripheral volume (L)
CL_NIC  :  40.0 : Nicardipine clearance (L/h)
Q_NIC   :  95.0 : Nicardipine intercompartmental clearance (L/h)
IC50_NIC: 0.055 : Nicardipine arteriolar IC50 (mg/L)
// ---- clevidipine IV: blood esterases, t1/2 1.7 min -----------------------
V_CLV   :  12.0 : Clevidipine volume (L)
CL_CLV  : 290.0 : Clevidipine clearance (L/h)
IC50_CLV: 0.030 : Clevidipine arteriolar IC50 (mg/L)
// ---- nitroprusside and its cyanide ---------------------------------------
V_SNP   :  15.0 : Nitroprusside volume (L)
CL_SNP  : 291.0 : Nitroprusside clearance (L/h)
IC50_SNP: 0.020 : Nitroprusside IC50 (mg/L)
FCN     : 0.436 : mg cyanide liberated per mg nitroprusside (5 CN- per SNP)
V_CN    :  30.0 : Cyanide volume (L)
CL_CN   :  31.0 : Cyanide clearance, rhodanese (L/h)
V_SCN   :  35.0 : Thiocyanate volume (L)
CL_SCN  :  0.34 : Thiocyanate renal clearance at normal Q_ren (L/h)
CN_TOX  :   1.0 : Cyanide toxic threshold (mg/L)
// ---- fentanyl ------------------------------------------------------------
V_FEN   : 280.0 : Fentanyl volume (L)
CL_FEN  :  45.0 : Fentanyl clearance (L/h)
KE0_FEN :   9.0 : Fentanyl effect-site equilibration (1/h)
IC50_FEN:0.0012 : Fentanyl analgesic IC50 (mg/L)
// ---- losartan / EXP-3174 -------------------------------------------------
KA_LOS  :   1.0 : Losartan absorption rate (1/h)
F_LOS   :  0.33 : Losartan bioavailability
V_LOS   :  34.0 : Losartan volume (L)
CL_LOS  :  50.0 : Losartan clearance (L/h)
FM_LOS  :  0.14 : Fraction of losartan converted to EXP-3174
V_E3174 :  12.0 : EXP-3174 volume (L)
CL_E3174:   2.0 : EXP-3174 clearance (L/h)
IC50_LOS: 0.075 : Losartan AT1 IC50 (mg/L)
IC50_E3174:0.010: EXP-3174 AT1 IC50 (mg/L)

// ---- baroreflex and sympathetic outflow ----------------------------------
TAU_SNA :  0.15 : Sympathetic outflow time constant (h)
TAU_BARO:  48.0 : Baroreflex resetting time constant (h)
BARO_REF: 106.0 : Baroreflex reference operating point (mmHg)
FRESET  :  0.45 : Fraction of a pressure change the reflex resets to
KBARO   :  1.25 : Baroreflex gain (blunted, 65 y hypertensive)
KPAIN   :  0.55 : Sympathoexcitation at 10/10 pain
KANG    :  0.35 : AT1-mediated sympathoexcitation
SNA0    :   1.0 : Reference sympathetic outflow

// ---- cardiac and vascular ------------------------------------------------
TAU_HR  :  0.05 : Heart rate time constant (h)
TAU_CTR :  0.05 : Contractility time constant (h)
TAU_SVR :  0.08 : Resistance time constant (h)
TAU_MAP :  0.01 : Arterial pressure time constant (h)
HR0     :  62.0 : Reference heart rate (bpm)
CTR0    :   1.0 : Reference contractility
SVR0    :  17.5 : Reference systemic vascular resistance (mmHg*min/L)
SV0     :  76.0 : Reference stroke volume (mL)
EMAX_BB_HR : 0.46 : Maximal beta1-blockade effect on heart rate
EMAX_BB_CTR: 0.42 : Maximal beta1-blockade effect on contractility
EMAX_DHP   : 0.68 : Maximal dihydropyridine effect on resistance
EMAX_ALPHA : 0.30 : Maximal alpha1-blockade effect on resistance
EMAX_NO    : 0.62 : Maximal NO-donor effect on resistance
EMAX_AT1   : 0.16 : Maximal AT1-blockade effect on resistance
EXP_HR_SNA : 0.85 : Heart rate exponent on sympathetic outflow
EXP_CTR_SNA: 0.60 : Contractility exponent on sympathetic outflow
EXP_SVR_SNA: 0.70 : Resistance exponent on sympathetic outflow
CART0   :  1.72 : Reference arterial compliance (mL/mmHg)
STIFF   :  0.55 : Elastin-loss stiffening coefficient
DPDT0   : 1180. : Reference dP/dt max (mmHg/s)
DBP0    :  80.0 : Reference diastolic pressure (mmHg)
EXP_DPDT_HR : 0.25 : dP/dt exponent on heart rate
EXP_DPDT_DBP: 0.35 : dP/dt exponent on diastolic pressure

// ---- volume and RAAS -----------------------------------------------------
BV0     :   5.0 : Reference blood volume (L)
TAU_BV  :  48.0 : Blood volume time constant (h)
TAU_PRA :   0.5 : Renin time constant (h)
TAU_ANG :  0.05 : Angiotensin II time constant (h)
TAU_ALDO:   2.0 : Aldosterone time constant (h)
KRENIN  :   2.2 : Renin gain per unit renal flow deficit
EMAX_BB_RENIN: 0.40 : Beta1-blockade of juxtaglomerular renin release
KAT1FB  :  1.10 : Loss of Ang II short-loop feedback under AT1 blockade
KALDO_BV:  0.09 : Aldosterone effect on blood volume

// ---- two-lumen mechanics -------------------------------------------------
KCOMM   : 260.0 : Lumen communication rate per unit conductance (1/h)
KDEP    :0.02083: Depressurisation rate of a sealed sac (1/h, tau 48 h)
PVEN    :   9.0 : Pressure a sealed sac decays to (mmHg)
DPAO    :   4.0 : True-lumen pressure drop along the aorta (mmHg)
AEN0    :  42.0 : Entry tear area at presentation (mm2)
AEN_REF :  42.0 : Fixed normaliser for entry conductance (mm2)
AEN_MAX : 320.0 : Whole-circumference tear limit (mm2)
GRE0    :  1.00 : Reference distal re-entry conductance
TAUFL0  :  0.30 : False-lumen charging time at unit conductance (s)
HAO0    :  1.90 : Descending thoracic aortic wall thickness (mm)
FOUT    :  0.40 : Fraction of wall thickness outside the dissection plane
DTL0    :  20.0 : True-lumen diameter at presentation (mm)
DFL0    :  17.0 : False-lumen diameter at presentation (mm)
TAU_DTL :   1.0 : True-lumen compression time constant (h)
KCOLLAPSE: 0.32 : Maximal true-lumen compression
SIGREF  : 118.0 : Reference aortic wall stress (kPa)
SEAL_THR50: 0.70: Thrombus fraction at which the entry tear starts to seal
SEAL_THRW : 0.05: Width of the sealing transition
SEAL_POW  :  3.0: Steepness of the sealing law
KFLOW_THR :  0.60: Fraction of false-lumen flow a full thrombus displaces

// ---- thrombosis ----------------------------------------------------------
KTHR    :0.0015 : False-lumen body thrombosis rate (1/h)
KLYS    :0.0060 : Flow-dependent lysis rate (1/h)
KTHRD   :0.0090 : Distal stagnant-zone thrombosis rate (1/h)
KLYSD   :0.0025 : Distal lysis rate (1/h)
FLOW50  :  0.30 : Stasis half-point, false-lumen body
FLOW50D :  0.09 : Stasis half-point, distal zone
KQ      :  0.95 : Through-flow scale
KTOFRO  :  0.55 : To-and-fro flow scale

// ---- growth and remodelling ---------------------------------------------
KGROW   :3.55e-4: False-lumen growth at reference stress (mm/h)
EXP_GROW:   1.9 : Laplace growth exponent
KMMP_GROW: 0.30 : MMP-9 amplification of growth
THR_SUPPORT:0.85: Mechanical support of the wall by thrombus
KREGRESS:6.0e-5 : Shrinkage rate of an organising depressurised sac (mm/h)
DFL_CAP :  58.0 : Numerical ceiling on false-lumen diameter (mm)
KREM_H  :0.004167: Wall-thickness remodelling rate (1/h, tau 240 h)
HFL_COL :  0.45 : Collagen effect on wall-thickness set-point
KH_MMP  :  0.10 : MMP-9 thinning coefficient
KTHR_H  :  1.00 : Mural-thrombus thinning coefficient
KELN    :8.0e-6 : Elastin degradation rate (1/h)
KCOL    :2.0e-3 : Collagen synthesis rate (1/h)
KCOL_STRESS:3.2e-3: Stress-driven collagen synthesis rate (1/h)
KDEGC   :1.0e-3 : Collagen degradation rate (1/h)
COLMAX  :   1.8 : Maximal adventitial collagen
KTEAR   :6.0e-3 : Tear propagation rate (1/h)
KHEAL_TEAR:3.0e-5: Tear healing rate (1/h)
EXP_TEAR_DPDT:1.2: dP/dt exponent in the flap stress-impulse
TEAR_TH :  0.45 : Flap stress-impulse threshold for propagation

// ---- inflammation --------------------------------------------------------
TAU_INJ :  30.0 : Acute injury signal decay (h)
KIL6    :   2.4 : Injury drive on IL-6
KIL6_STRESS: 0.8: Saturating stress drive on IL-6
KOUT_IL6:  0.35 : IL-6 turnover (1/h)
KMMP_IL6:  0.55 : IL-6 drive on MMP-9
KMMP_AT1:  0.60 : AT1 drive on MMP-9
KOUT_MMP:  0.20 : MMP-9 turnover (1/h)
GEN_MMP :   1.0 : Genetic MMP-9 multiplier (2.2 for a Marfan-like wall)
KTGF_INJ:  1.20 : Injury drive on TGF-beta
KTGF_MMP:  0.40 : MMP-9 drive on TGF-beta
KOUT_TGF:  0.09 : TGF-beta turnover (1/h)
TAU_PAIN:  0.10 : Pain time constant (h)
SIG_PAIN: 175.0 : Wall stress at half-maximal pain (kPa)
KPAIN_INJ:  7.5 : Injury contribution to pain (0-10)
EMAX_OP :  0.90 : Maximal opioid analgesia

// ---- organ perfusion ----------------------------------------------------
OBST_REN:   0.0 : Static renal branch obstruction (0-1)
OBST_MES:   0.0 : Static mesenteric branch obstruction (0-1)
OBST_SPI:   0.0 : Static segmental branch obstruction (0-1)
INV_REN :   0.0 : Renal branch arises from the dissected segment (0/1)
INV_MES :   0.0 : Mesenteric branch arises from the dissected segment (0/1)
INV_SPI :   1.0 : Segmental branches arise from the dissected segment (0/1)
KOBST_DYN: 0.75 : Maximal dynamic obstruction from true-lumen collapse
TAU_QREN:   1.0 : Renal perfusion lag (h)
CREAT_PROD:1.05 : Creatinine production (mg/dL*L/h scale)
CL_CREAT0:  1.0 : Creatinine clearance at normal renal flow
V_CREAT :  42.0 : Creatinine distribution volume (L)
KLACT_MES:  2.6 : Lactate production from mesenteric deficit
KLACT_CN :  2.2 : Lactate production from cyanide
KOUT_LACT: 0.55 : Lactate turnover (1/h)
LACT0   :   1.0 : Baseline lactate (mmol/L)
SCP_CSF :  10.0 : Cerebrospinal fluid pressure (mmHg)
KSCI    :   1.0 : Cord injury accumulation rate
SCI_THRESH:0.45 : Spinal perfusion index below which injury accrues
SCPP50  :  42.0 : Spinal perfusion pressure at half-maximal flow (mmHg)
SCI_PARA:  12.0 : Cord injury burden at which paraplegia is likely
TAU_SCI :  72.0 : Cord injury repair time (h)
KCOL_SPI:  0.85 : Collateral substitution for lost segmental supply
KCOLL   :  0.02 : Collateral recruitment rate (1/h)
KCOLL_D :6.94e-4: Collateral regression rate (1/h)
KDD_FLOW:   1.6 : D-dimer production from false-lumen flow
KDD_THR :   2.4 : D-dimer production from thrombus turnover
KOUT_DD :  0.10 : D-dimer turnover (1/h)
DDIM0   :  0.25 : Baseline D-dimer (ug/mL)

// ---- hazard --------------------------------------------------------------
SWALL0  : 760.0 : Ultimate aortic wall strength, fresh (kPa)
EXP_ELN_S: 0.30 : Elastin exponent in wall strength
H0_RUPT :1.10e-4: Rupture hazard at sigma = wall strength (1/h)
W_RUPT  : 0.155 : Exponential width of the rupture hazard
KH_MALPERF:1.3e-3: Malperfusion hazard coefficient
KH_OTHER:2.3e-6 : Non-aortic mortality (1/h, 2%/y at 65 y)
KH_EXT  :4.0e-3 : Extension hazard coefficient

// ---- target window and closed-loop titration ----------------------------
SBP_LO  : 100.0 : Lower systolic target (mmHg)
SBP_HI  : 120.0 : Upper systolic target (mmHg)
HR_TGT  :  60.0 : Heart rate target (bpm)
KI_VD   :  0.16 : Vasodilator controller gain (1/(mmHg*h))
KI_BB   :  0.11 : Beta-blocker controller gain on heart rate (1/(bpm*h))
KI_BB_SBP: 0.09 : Beta-blocker controller gain on pressure (1/(mmHg*h))
VD_MAX  :   0.0 : Maximum vasodilator infusion rate (mg/h)
BB_MAX  :   0.0 : Maximum beta-blocker infusion rate (mg/h)
SBP_SET : 110.0 : Systolic set-point for titration (mmHg)
HR_SET  :  60.0 : Heart rate set-point for titration (bpm)
BB_ON_SBP:  0.0 : Titrate the beta-blocker on pressure instead of heart rate
VD_AGENT:   0.0 : 0 none, 1 nicardipine, 2 clevidipine, 3 nitroprusside
BB_AGENT:   0.0 : 0 none, 1 esmolol, 2 labetalol

// ---- fixed-rate and oral dosing -----------------------------------------
R_ESM   :   0.0 : Fixed esmolol infusion (mg/h)
R_LAB   :   0.0 : Fixed labetalol infusion (mg/h)
R_NIC   :   0.0 : Fixed nicardipine infusion (mg/h)
R_CLV   :   0.0 : Fixed clevidipine infusion (mg/h)
R_SNP   :   0.0 : Fixed nitroprusside infusion (mg/h)
R_FEN   :   0.0 : Fixed fentanyl infusion (mg/h)
D_MET   :   0.0 : Metoprolol dose per TAU_PO (mg)
D_LOS   :   0.0 : Losartan dose per TAU_PO (mg)
TAU_PO  :  12.0 : Oral dosing interval (h)
ADHERE  :   1.0 : Adherence to chronic oral therapy (0-1)

// ---- interventions -------------------------------------------------------
TEVAR_T :  -1.0 : Time of entry-tear coverage (h, negative = never)
TEVAR_SEAL:0.985: Fraction of entry conductance a stent-graft removes
TEVAR_COVER:0.30: Fraction of segmental arteries covered

$CMT @annotated
A_ESM   : Esmolol, central (mg)
A_LABC  : Labetalol, central (mg)
A_LABP  : Labetalol, peripheral (mg)
A_METD  : Metoprolol, gut depot (mg)
A_METC  : Metoprolol, central (mg)
A_NICC  : Nicardipine, central (mg)
A_NICP  : Nicardipine, peripheral (mg)
A_CLV   : Clevidipine, central (mg)
A_SNP   : Nitroprusside, central (mg)
A_CN    : Cyanide (mg)
A_SCN   : Thiocyanate (mg)
A_FENC  : Fentanyl, central (mg)
A_FENE  : Fentanyl, effect site (mg)
A_LOSD  : Losartan, gut depot (mg)
A_LOSC  : Losartan, central (mg)
A_E3174 : EXP-3174 (mg)
SNA     : Sympathetic outflow (relative)
BAROSET : Baroreflex operating point (mmHg)
HR      : Heart rate (bpm)
CTR     : Left ventricular contractility (relative)
SVR     : Systemic vascular resistance (mmHg*min/L)
PMAP    : Mean arterial pressure (mmHg)
PRA     : Plasma renin activity (relative)
ANGII   : Angiotensin II (relative)
ALDO    : Aldosterone (relative)
BV      : Blood volume (L)
PFL     : False-lumen mean pressure (mmHg)
DFL     : False-lumen diameter (mm)
DTL     : True-lumen diameter (mm)
THRFL   : False-lumen body thrombus fraction (0-1)
THRD    : Distal re-entry thrombus fraction (0-1)
AEN     : Entry tear area (mm2)
HFL     : False-lumen outer wall thickness (mm)
ELN     : Medial elastin integrity (0-1)
COL     : Adventitial collagen (0-2)
INJ     : Acute dissection injury signal (0-1)
IL6     : Interleukin-6 (relative)
MMP9    : MMP-9 (relative)
TGFB    : TGF-beta signalling (relative)
PAIN    : Pain intensity (0-10)
QREN    : Renal perfusion, lagged (relative)
CREAT   : Serum creatinine (mg/dL)
LACT    : Arterial lactate (mmol/L)
SCI     : Spinal cord injury burden (index)
DDIM    : D-dimer (ug/mL)
CUMH    : Cumulative aortic hazard
SURV    : Survival probability
DAM     : Cumulative stress-impulse damage
TIT     : Time inside the blood-pressure and heart-rate target (h)
AUCASI  : AUC of the aortic stress-impulse index (h)
U_VD    : Vasodilator controller integrator
U_BB    : Beta-blocker controller integrator
COLLAT  : Paraspinal collateral network (0-1)

$MAIN
// ---- initial conditions --------------------------------------------------
SNA_0     = 1.0;
BAROSET_0 = 106.0;      // a hypertensive operating point, not a normal one
HR_0      = HR0;
CTR_0     = CTR0;
SVR_0     = SVR0;
PMAP_0    = 106.0;
PRA_0     = 1.0;
ANGII_0   = 1.0;
ALDO_0    = 1.0;
BV_0      = BV0;
PFL_0     = 104.0;
DFL_0     = DFL0;
DTL_0     = DTL0;
THRFL_0   = 0.0;
THRD_0    = 0.0;
AEN_0     = AEN0;
HFL_0     = HAO0 * FOUT;                 // 0.76 mm: the dissected outer wall
ELN_0     = 0.82;                        // 65-y hypertensive descending aorta
COL_0     = 0.10;
INJ_0     = 1.0;                         // the dissection happens at t = 0
IL6_0     = 1.0;
MMP9_0    = 1.0;
TGFB_0    = 1.0;
PAIN_0    = 0.0;
QREN_0    = 1.0;
CREAT_0   = 1.05;
LACT_0    = 1.0;
SCI_0     = 0.0;
DDIM_0    = DDIM0;
SURV_0    = 1.0;
U_VD_0    = -2.5;                        // controllers start nearly off
U_BB_0    = -2.5;
COLLAT_0  = 0.55;                        // a collateral network pre-exists

$GLOBAL
#define MMHG_TO_KPA 0.133322
#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// Numerically safe logistic.
double sigf(double x) {
  if (x >  40.0) return 1.0;
  if (x < -40.0) return 0.0;
  return 1.0 / (1.0 + exp(-x));
}

// Smooth max(x,0).  The sharpness matters: see NOTE 7 at the hazard block.
double sp(double x, double k) {
  double z = k * x;
  if (z >  40.0) return x;
  if (z < -40.0) return 0.0;
  return log1p(exp(z)) / k;
}

// Additive competitive occupancy of one receptor by up to three ligands.
double occ3(double c1, double i1, double c2, double i2, double c3, double i3) {
  double e = c1 / i1 + c2 / i2 + c3 / i3;
  return e / (1.0 + e);
}

$ODE
// =========================================================================
//  0.  CONCENTRATIONS AND RECEPTOR OCCUPANCIES
// =========================================================================
double C_ESM  = A_ESM  / V_ESM;
double C_LAB  = A_LABC / V_LAB;
double C_MET  = A_METC / V_MET;
double C_NIC  = A_NICC / V_NIC;
double C_CLV  = A_CLV  / V_CLV;
double C_SNP  = A_SNP  / V_SNP;
double C_CN   = A_CN   / V_CN;
double C_FEN  = A_FENE / V_FEN;
double C_LOS  = A_LOSC / V_LOS;
double C_E31  = A_E3174 / V_E3174;

double OCC_B   = occ3(C_ESM, IC50_ESM, C_LAB, IC50_LABB, C_MET, IC50_MET);
double OCC_A   = occ3(C_LAB, IC50_LABA, 0.0, 1.0, 0.0, 1.0);
double OCC_DHP = occ3(C_NIC, IC50_NIC, C_CLV, IC50_CLV, 0.0, 1.0);
double OCC_NO  = occ3(C_SNP, IC50_SNP, 0.0, 1.0, 0.0, 1.0);
double OCC_OP  = occ3(C_FEN, IC50_FEN, 0.0, 1.0, 0.0, 1.0);
double BLK_AT1 = occ3(C_LOS, IC50_LOS, C_E31, IC50_E3174, 0.0, 1.0);

// =========================================================================
//  1.  SYSTEMIC HAEMODYNAMICS
// =========================================================================
double PRELOAD = (BV / BV0) * (1.0 - 0.25 * OCC_NO) * (1.0 - 0.05 * OCC_DHP);
if (PRELOAD < 0.05) PRELOAD = 0.05;
double SV = SV0 * CTR * pow(PRELOAD, 0.60) * pow(SVR / SVR0, -0.20);
double CO = HR * SV / 1000.0;                                     // L/min

// Vasodilators do not only drop resistance, they raise conduit-artery
// compliance.  Without this term reflex stroke-volume rise blows the pulse
// pressure up and the systolic pressure never falls.
double CART = (CART0 / (1.0 + STIFF * (1.0 - ELN)))
              * (1.0 + 0.25 * OCC_DHP + 0.30 * OCC_NO + 0.10 * OCC_A);
double PP   = SV / CART;
double SBPv = PMAP + 2.0 / 3.0 * PP;
double DBPv = PMAP - 1.0 / 3.0 * PP;

// THE IMPULSE.  Contractility enters with exponent 1, heart rate and afterload
// weakly.  Note what is NOT here: mean pressure.
double DPDTv = DPDT0 * CTR * pow(HR / HR0, EXP_DPDT_HR)
               * pow((DBPv > 15.0 ? DBPv : 15.0) / DBP0, EXP_DPDT_DBP);

// =========================================================================
//  2.  THE DIVIDER
// =========================================================================
double seal      = (TEVAR_T >= 0.0 && SOLVERTIME >= TEVAR_T) ? TEVAR_SEAL : 0.0;
// NOTE 5/6.  Thrombus seals the ENTRY TEAR only when the false lumen is
// essentially completely clotted.  A 40%-thrombosed false lumen still has a
// wide-open entry tear and is still pressurised - that single asymmetry is the
// whole difference between "partial" and "complete" thrombosis.
double seal_thr  = pow(1.0 - sigf((THRFL - SEAL_THR50) / SEAL_THRW), SEAL_POW);
double G_EN      = (AEN / AEN_REF) * seal_thr * (1.0 - seal);
if (G_EN < 0.0) G_EN = 0.0;
double one_thrd  = (1.0 - THRD > 0.0) ? (1.0 - THRD) : 0.0;
double G_RE      = GRE0 * one_thrd * one_thrd;
double GTOT      = G_EN + G_RE;

double tau_fl = (GTOT > 1e-9) ? (TAUFL0 / GTOT) : 1e6;            // seconds
double omega  = 2.0 * M_PI * HR / 60.0;                           // rad/s
double PP_FL  = PP / sqrt(1.0 + omega * omega * tau_fl * tau_fl);
double PFL_SYS = PFL + 2.0 / 3.0 * PP_FL;
double PFL_DIA = PFL - 1.0 / 3.0 * PP_FL;

// Through-flow needs both tears; to-and-fro flow needs only the entry tear and
// is driven by the pressure-AMPLITUDE difference across it, so the harder the
// sac damps the pulse the harder blood is pushed in and out of it.
double gser  = (GTOT > 1e-9) ? (G_EN * G_RE / GTOT) : 0.0;
double dpp   = (PP - PP_FL > 0.0) ? (PP - PP_FL) : 0.0;
double FLOW  = KQ * gser + KTOFRO * G_EN * dpp / 46.0;
double fthr  = 1.0 - KFLOW_THR * THRFL;
FLOW *= (fthr > 0.0 ? fthr : 0.0);

// =========================================================================
//  3.  LAPLACE MECHANICS - AND THE PRODUCT
// =========================================================================
double r_fl   = DFL / 2.0;
double h_eff  = (HFL > 0.05) ? HFL : 0.05;
double SIG_FL     = PFL     * MMHG_TO_KPA * r_fl / h_eff;
double SIG_FL_SYS = PFL_SYS * MMHG_TO_KPA * r_fl / h_eff;
double SIG_TL     = SBPv * MMHG_TO_KPA * (DTL / 2.0) / (HAO0 * (1.0 - FOUT));

// NOTE 5.  The flap only carries stress where it is still a FREE flap: clot
// buttresses it and a stent-graft pins it.  NOTE 6: and its mobility scales
// with how much intima has actually detached, or a 9 mm2 tear feeding a damped
// sac becomes the highest flap stress in the model.
double mobility = pow(AEN / AEN_REF, 0.5);
if (mobility > 1.5) mobility = 1.5;
double exposed  = ((1.0 - THRFL > 0.0) ? (1.0 - THRFL) : 0.0) * (1.0 - seal) * mobility;
double SIG_FLAP = fabs(SBPv - PFL_SYS) * MMHG_TO_KPA * r_fl / 0.25 * exposed;

double ASIv      = (SIG_FL_SYS / SIGREF) * (DPDTv / DPDT0);
double ASI_FLAPv = (SIG_FLAP / SIGREF) * pow(DPDTv / DPDT0, EXP_TEAR_DPDT);

// wall strength and the rupture hazard
double SWALL = SWALL0 * pow((ELN > 0.02 ? ELN : 0.02), EXP_ELN_S) * (0.60 + 0.40 * COL);
double SRv   = SIG_FL_SYS / SWALL;
double earg  = (SRv - 1.0) / W_RUPT;
if (earg > 30.0) earg = 30.0;
double H_RUPT = H0_RUPT * exp(earg);
if (H_RUPT > 0.60) H_RUPT = 0.60;

// wall-thickness set-point: collagen thickens, MMP-9 thins, and mural thrombus
// thins hardest of all (the wall beneath an intraluminal thrombus is hypoxic
// and bathed in neutrophil elastase and plasmin).
double HFL_TGT = (HAO0 * FOUT * (1.0 + HFL_COL * COL))
                 / (1.0 + KH_MMP * sp(MMP9 - 1.0, 8.0) + KTHR_H * THRFL);

// =========================================================================
//  4.  BRANCH PERFUSION
// =========================================================================
// NOTE 3.  Dynamic obstruction needs TWO things at once - a diastolic pressure
// gradient AND false-lumen dominance.  Requiring only the first puts every
// patient in renal failure at t = 0, because a patent false lumen always
// carries mean pressure above true-lumen diastolic pressure.
double flr  = DFL / ((DFL + DTL > 1e-6) ? (DFL + DTL) : 1e-6);
double dom  = (flr - 0.40) / 0.30;
if (dom < 0.0) dom = 0.0;
if (dom > 1.0) dom = 1.0;
double COLLAPSEv = sigf((PFL_DIA - DBPv - 5.0) / 4.0) * dom;
double dyn = KOBST_DYN * COLLAPSEv;

double pat_ren = (1.0 - OBST_REN) * (1.0 - dyn * INV_REN);
double pat_mes = (1.0 - OBST_MES) * (1.0 - dyn * INV_MES);
double pat_spi = (1.0 - OBST_SPI) * (1.0 - 0.55 * COLLAPSEv * INV_SPI);
if (pat_ren < 0.02) pat_ren = 0.02;
if (pat_mes < 0.02) pat_mes = 0.02;
if (pat_spi < 0.02) pat_spi = 0.02;
double cover = (TEVAR_T >= 0.0 && SOLVERTIME >= TEVAR_T) ? TEVAR_COVER : 0.0;
double spi_loss = 1.0 - 0.20 * THRFL - cover;
pat_spi *= (spi_loss > 0.05 ? spi_loss : 0.05);

double PP_REN    = PMAP * pat_ren;
double QREN_INST = 0.04 + 1.02 * sigf((PP_REN - 58.0) / 8.5);
if (QREN_INST > 1.06) QREN_INST = 1.06;
double QMES = 0.04 + 1.02 * sigf((PMAP * pat_mes - 52.0) / 8.0);
if (QMES > 1.06) QMES = 1.06;
double SCPP = PMAP - SCP_CSF;
// NOTE 8.  Collaterals SUBSTITUTE for lost segmental supply; they are also
// recruitable, which is why paraplegia is an acute-window risk rather than a
// permanent state, and why staged coverage works.
double scpp_eff = SCPP * (pat_spi + KCOL_SPI * COLLAT * (1.0 - pat_spi));
double QSPI = 0.04 + 1.02 * sigf((scpp_eff - SCPP50) / 7.0);
if (QSPI > 1.06) QSPI = 1.06;

// =========================================================================
//  5.  INFUSION RATES (fixed plus closed-loop titration)
// =========================================================================
// A nurse titrating to a systolic target is an integral controller.  Writing it
// this way lets the arms be compared AT THE SAME ACHIEVED PRESSURE, which is
// the only fair way to ask what a vasodilator costs.
double u_vd = VD_MAX * sigf(U_VD);
double u_bb = BB_MAX * sigf(U_BB);
double r_esm = R_ESM + ((BB_AGENT > 0.5 && BB_AGENT < 1.5) ? u_bb : 0.0);
double r_lab = R_LAB + ((BB_AGENT > 1.5) ? u_bb : 0.0);
double r_nic = R_NIC + ((VD_AGENT > 0.5 && VD_AGENT < 1.5) ? u_vd : 0.0);
double r_clv = R_CLV + ((VD_AGENT > 1.5 && VD_AGENT < 2.5) ? u_vd : 0.0);
double r_snp = R_SNP + ((VD_AGENT > 2.5) ? u_vd : 0.0);

// =========================================================================
//  6.  THE 53 DIFFERENTIAL EQUATIONS
// =========================================================================
// ---- drug pharmacokinetics ----------------------------------------------
dxdt_A_ESM  = r_esm - CL_ESM / V_ESM * A_ESM;
dxdt_A_LABC = r_lab - CL_LAB / V_LAB * A_LABC
              - Q_LAB / V_LAB * A_LABC + Q_LAB / V_LAB2 * A_LABP;
dxdt_A_LABP = Q_LAB / V_LAB * A_LABC - Q_LAB / V_LAB2 * A_LABP;
// oral maintenance drugs are given as an equivalent continuous rate: the
// peak-trough ripple is irrelevant to a five-year growth curve
dxdt_A_METD = D_MET * ADHERE / TAU_PO - KA_MET * A_METD;
dxdt_A_METC = F_MET * KA_MET * A_METD - CL_MET / V_MET * A_METC;
dxdt_A_NICC = r_nic - CL_NIC / V_NIC * A_NICC
              - Q_NIC / V_NIC * A_NICC + Q_NIC / V_NIC2 * A_NICP;
dxdt_A_NICP = Q_NIC / V_NIC * A_NICC - Q_NIC / V_NIC2 * A_NICP;
dxdt_A_CLV  = r_clv - CL_CLV / V_CLV * A_CLV;
dxdt_A_SNP  = r_snp - CL_SNP / V_SNP * A_SNP;
// every molecule of nitroprusside that is cleared liberates five cyanide ions
dxdt_A_CN   = FCN * CL_SNP / V_SNP * A_SNP - CL_CN / V_CN * A_CN;
// rhodanese makes thiocyanate, which the kidney has to excrete - and the
// kidney is exactly what a dissection threatens
dxdt_A_SCN  = CL_CN / V_CN * A_CN * 2.23
              - CL_SCN * ((QREN > 0.05) ? QREN : 0.05) / V_SCN * A_SCN;
dxdt_A_FENC = R_FEN - CL_FEN / V_FEN * A_FENC;
dxdt_A_FENE = KE0_FEN * (A_FENC - A_FENE);
dxdt_A_LOSD = D_LOS * ADHERE / TAU_PO - KA_LOS * A_LOSD;
dxdt_A_LOSC = F_LOS * KA_LOS * A_LOSD - CL_LOS / V_LOS * A_LOSC;
dxdt_A_E3174= FM_LOS * CL_LOS / V_LOS * A_LOSC - CL_E3174 / V_E3174 * A_E3174;

// ---- baroreflex and sympathetic outflow ---------------------------------
double baro   = 1.0 + KBARO * (BAROSET - PMAP) / BAROSET;
double ang_ex = sp(ANGII - 1.0, 8.0);
double sna_t  = SNA0 * sp(baro, 6.0)
                * (1.0 + KPAIN * PAIN / 10.0)
                * (1.0 + KANG * ang_ex * (1.0 - BLK_AT1));
dxdt_SNA = (sna_t - SNA) / TAU_SNA;
// NOTE 2.  Resetting is PARTIAL.  Let the operating point track mean pressure
// completely and the reflex forgets the pressure it is meant to defend: the
// untreated arm then walks its own MAP past 160 mmHg with no equilibrium.
double baro_tgt = (1.0 - FRESET) * BARO_REF + FRESET * PMAP;
dxdt_BAROSET = (baro_tgt - BAROSET) / TAU_BARO;

// ---- heart, vessels, pressure -------------------------------------------
double sna_r = (SNA / SNA0 > 0.02) ? (SNA / SNA0) : 0.02;
double hr_t  = HR0 * pow(sna_r, EXP_HR_SNA) * (1.0 - EMAX_BB_HR * OCC_B);
dxdt_HR = ((hr_t > 32.0 ? hr_t : 32.0) - HR) / TAU_HR;
double ctr_t = CTR0 * pow(sna_r, EXP_CTR_SNA) * (1.0 - EMAX_BB_CTR * OCC_B);
dxdt_CTR = ((ctr_t > 0.25 ? ctr_t : 0.25) - CTR) / TAU_CTR;
double svr_t = SVR0 * pow(sna_r, EXP_SVR_SNA)
               * (1.0 - EMAX_DHP * OCC_DHP)
               * (1.0 - EMAX_ALPHA * OCC_A)
               * (1.0 - EMAX_NO * OCC_NO)
               * (1.0 + 0.30 * ang_ex * (1.0 - BLK_AT1))
               * (1.0 - EMAX_AT1 * BLK_AT1);
dxdt_SVR = ((svr_t > 3.0 ? svr_t : 3.0) - SVR) / TAU_SVR;
dxdt_PMAP = (CO * SVR + 5.0 - PMAP) / TAU_MAP;

// ---- RAAS and volume ----------------------------------------------------
double qren_s = (QREN > 0.05) ? QREN : 0.05;
double pra_t  = (1.0 + KRENIN * (1.0 / qren_s - 1.0))
                * (1.0 - EMAX_BB_RENIN * OCC_B)
                * (1.0 + KAT1FB * BLK_AT1);
dxdt_PRA   = ((pra_t > 0.05 ? pra_t : 0.05) - PRA) / TAU_PRA;
dxdt_ANGII = (PRA - ANGII) / TAU_ANG;
double aldo_t = 1.0 + 0.9 * (ANGII * (1.0 - BLK_AT1) - 1.0);
dxdt_ALDO = ((aldo_t > 0.1 ? aldo_t : 0.1) - ALDO) / TAU_ALDO;
dxdt_BV = (BV0 * (1.0 + KALDO_BV * (ALDO - 1.0)) - BV) / TAU_BV;

// ---- the two-lumen divider ---------------------------------------------
double pdist = PMAP - DPAO;
dxdt_PFL = KCOMM * (G_EN * (PMAP - PFL) + G_RE * (pdist - PFL))
           - KDEP * (PFL - PVEN);
dxdt_DTL = (DTL0 * (1.0 - KCOLLAPSE * COLLAPSEv) - DTL) / TAU_DTL;

// The mechanotransduced signal, saturating.  NOTE 1: left linear in wall
// stress it closes an unbounded stress -> IL-6 -> MMP-9 -> thinning -> stress
// loop, and the five-year run reaches MMP-9 44x normal on a 0.16 mm wall.
double xs = sp(SIG_FL_SYS / SIGREF - 1.0, 8.0);
double xs_sat = xs / (1.0 + xs);

// False-lumen expansion.  Stress enters with the Laplace exponent 1.9, so a
// thrombus that thins the wall by factor f multiplies growth by f^1.9 while
// supporting it by only (1 - 0.85*THR).  Exponent against linear term puts the
// growth maximum at an INTERMEDIATE thrombus fraction, closed form
//   THR* = (n*A - s) / ((1+n)*s*A) = 0.426
// for n = EXP_GROW, s = THR_SUPPORT, A = KTHR_H.  Nothing in this file says
// partial thrombosis is dangerous; this line makes it so.
double capf  = 1.0 - sigf((DFL - DFL_CAP) / 1.5);
double grow  = KGROW * pow(SIG_FL / SIGREF, EXP_GROW)
               * (1.0 + KMMP_GROW * sp(MMP9 - 1.0, 8.0))
               * (1.0 - THR_SUPPORT * THRFL) * capf;
double regress = KREGRESS * THRFL * sigf((25.0 - PFL) / 6.0);
dxdt_DFL = grow - regress;

double stasis   = 1.0 / (1.0 + pow(FLOW / FLOW50, 2.0));
double stasis_d = 1.0 / (1.0 + pow(FLOW / FLOW50D, 2.0));
double flow_c   = (FLOW < 3.0) ? FLOW : 3.0;
dxdt_THRFL = KTHR * stasis * (1.0 - THRFL) - KLYS * THRFL * flow_c;
dxdt_THRD  = KTHRD * stasis_d * (1.0 - THRD) - KLYSD * THRD * flow_c;

// Entry tear propagation: the place the product earns its keep.  A regimen is
// aorta-protective if and only if it drives ASI_flap below TEAR_TH - which a
// beta-blocker does by lowering BOTH factors, and which a vasodilator can fail
// to do even while lowering the pressure, because it raises the second one.
double tear_head = 1.0 - AEN / AEN_MAX;
if (tear_head < 0.0) tear_head = 0.0;
dxdt_AEN = KTEAR * AEN * sp(ASI_FLAPv - TEAR_TH, 40.0) * tear_head
           / (1.0 + 3.0 * COL)
           - KHEAL_TEAR * COL * sp(AEN - 0.6 * AEN0, 8.0);

dxdt_HFL = KREM_H * (HFL_TGT - HFL);
dxdt_ELN = -KELN * sp(MMP9 - 1.0, 8.0) * ELN;
// NOTE 4.  Stress-driven adventitial collagen is the ONLY negative feedback
// the aorta has: a thicker outer wall lowers sigma = P*r/h.  Without it the
// model has no stable chronic state at all.
double col_head = 1.0 - COL / COLMAX;
if (col_head < 0.0) col_head = 0.0;
dxdt_COL = (KCOL * (0.10 + sp(TGFB - 1.0, 8.0)) + KCOL_STRESS * xs) * col_head
           - KDEGC * COL * MMP9;

// ---- injury, inflammation, pain ----------------------------------------
dxdt_INJ = -INJ / TAU_INJ;
dxdt_IL6 = KIL6 * INJ + KIL6_STRESS * xs_sat - KOUT_IL6 * (IL6 - 1.0);
// MMP-9 and TGF-beta are set-point relaxations, so a healthy input of 1.0
// returns exactly 1.0.  The first version had production terms that did not
// balance their own baselines, and the model diverged.
double mmp_t = GEN_MMP * (1.0 + KMMP_IL6 * sp(IL6 - 1.0, 8.0))
               * (1.0 + KMMP_AT1 * sp(ANGII * (1.0 - BLK_AT1) - 1.0, 8.0));
dxdt_MMP9 = KOUT_MMP * (mmp_t - MMP9);
double tgf_t = (1.0 + KTGF_INJ * INJ + KTGF_MMP * sp(MMP9 - 1.0, 8.0))
               * (0.40 + 0.60 * (1.0 - BLK_AT1));
dxdt_TGFB = KOUT_TGF * (tgf_t - TGFB);

// NOTE 9.  Pain from wall stress is gated by flap friability: the tearing pain
// of onset is the injury signal, what persists is stress on a FRESH flap.  A
// chronic remodelled dissection is painless, and letting it hurt gave the model
// a phantom sympathetic cause of chronic hypertension.
double friab  = 1.0 / (1.0 + 4.0 * COL);
double pain_t = KPAIN_INJ * INJ
                + 10.0 * sigf((SIG_FL_SYS / SIG_PAIN - 1.0) / 0.16)
                * (0.15 + 0.85 * friab);
if (pain_t > 10.0) pain_t = 10.0;
pain_t *= (1.0 - EMAX_OP * OCC_OP);
dxdt_PAIN = (pain_t - PAIN) / TAU_PAIN;

// ---- organ perfusion and laboratory endpoints --------------------------
dxdt_QREN  = (QREN_INST - QREN) / TAU_QREN;
dxdt_CREAT = (CREAT_PROD - CL_CREAT0 * ((QREN > 0.03) ? QREN : 0.03) * CREAT)
             / V_CREAT * 24.0;
dxdt_LACT  = KLACT_MES * sp(0.85 - QMES, 8.0)
             + KLACT_CN * sp(C_CN - 0.35, 8.0)
             - KOUT_LACT * (LACT - LACT0);
dxdt_SCI   = KSCI * sp(SCI_THRESH - QSPI, 8.0) - SCI / TAU_SCI;
dxdt_COLLAT= KCOLL * sp(0.75 - QSPI, 8.0) * (1.0 - COLLAT) - KCOLL_D * COLLAT;
dxdt_DDIM  = KDD_FLOW * FLOW * (1.0 - THRFL)
             + KDD_THR * sp(dxdt_THRFL * 100.0, 8.0) * 0.1
             - KOUT_DD * (DDIM - DDIM0);

// ---- outcome integrals --------------------------------------------------
// NOTE 7.  The sharpness arguments here are not cosmetic.  With the default
// smoothing the softplus tail returns ~0.004 for an argument of -0.43, so a
// perfectly perfused organ contributed 1.05e-5/h of hazard - four times the
// whole non-aortic mortality - and over 43 800 h that numerical leak, not any
// modelled mechanism, became the leading cause of death in every chronic arm.
double h_mal = KH_MALPERF * (sp(0.55 - QMES, 40.0) + sp(0.45 - QREN, 40.0));
// Death in the acute phase is mostly not free-wall rupture, it is extension -
// retrograde into the arch or distally into a new branch - so the hazard
// carries a term proportional to how hard the flap is being driven, gated by
// flap friability (acute flap friable, chronic flap fibrotic).
double h_ext = KH_EXT * sp(ASI_FLAPv - TEAR_TH, 40.0)
               * (0.25 + 0.75 * INJ) / (1.0 + 4.0 * COL);
double h_tot = H_RUPT + h_mal + h_ext + KH_OTHER;
dxdt_CUMH = H_RUPT + h_ext;
dxdt_SURV = -h_tot * SURV;
dxdt_DAM  = ASIv;
dxdt_TIT  = sigf((SBPv - SBP_LO) / 2.0) * sigf((SBP_HI - SBPv) / 2.0)
            * sigf((HR_TGT + 5.0 - HR) / 2.0);
dxdt_AUCASI = ASIv;

// ---- closed-loop titration ---------------------------------------------
dxdt_U_VD = (VD_MAX > 0.0) ? KI_VD * (SBPv - SBP_SET) : 0.0;
if (BB_MAX > 0.0) {
  dxdt_U_BB = (BB_ON_SBP > 0.5) ? KI_BB_SBP * (SBPv - SBP_SET)
                                : KI_BB * (HR - HR_SET);
} else {
  dxdt_U_BB = 0.0;
}

$TABLE
double C_ESMo = A_ESM / V_ESM;
double C_NICo = A_NICC / V_NIC;
double C_SNPo = A_SNP / V_SNP;
double C_LABo = A_LABC / V_LAB;
double C_CLVo = A_CLV / V_CLV;
double C_CNo  = A_CN / V_CN;
double C_SCNo = A_SCN / V_SCN;
double C_METo = A_METC / V_MET;
double C_E31o = A_E3174 / V_E3174;
double C_FENo = A_FENE / V_FEN;

double OCC_Bo   = occ3(C_ESMo, IC50_ESM, C_LABo, IC50_LABB, C_METo, IC50_MET);
double OCC_Ao   = occ3(C_LABo, IC50_LABA, 0.0, 1.0, 0.0, 1.0);
double OCC_DHPo = occ3(C_NICo, IC50_NIC, C_CLVo, IC50_CLV, 0.0, 1.0);
double OCC_NOo  = occ3(C_SNPo, IC50_SNP, 0.0, 1.0, 0.0, 1.0);
double BLK_AT1o = occ3(A_LOSC / V_LOS, IC50_LOS, C_E31o, IC50_E3174, 0.0, 1.0);

double PRELOADo = (BV / BV0) * (1.0 - 0.25 * OCC_NOo) * (1.0 - 0.05 * OCC_DHPo);
if (PRELOADo < 0.05) PRELOADo = 0.05;
double SVo   = SV0 * CTR * pow(PRELOADo, 0.60) * pow(SVR / SVR0, -0.20);
double COo   = HR * SVo / 1000.0;
double CARTo = (CART0 / (1.0 + STIFF * (1.0 - ELN)))
               * (1.0 + 0.25 * OCC_DHPo + 0.30 * OCC_NOo + 0.10 * OCC_Ao);
double PPo   = SVo / CARTo;

capture SBP  = PMAP + 2.0 / 3.0 * PPo;
capture DBP  = PMAP - 1.0 / 3.0 * PPo;
capture MAP  = PMAP;
capture PULSE_PRESSURE = PPo;
capture CARDIAC_OUTPUT = COo;
capture STROKE_VOLUME  = SVo;
capture DPDT = DPDT0 * CTR * pow(HR / HR0, EXP_DPDT_HR)
               * pow(((PMAP - PPo / 3.0) > 15.0 ? (PMAP - PPo / 3.0) : 15.0) / DBP0,
                     EXP_DPDT_DBP);

double sealo     = (TEVAR_T >= 0.0 && SOLVERTIME >= TEVAR_T) ? TEVAR_SEAL : 0.0;
double seal_thro = pow(1.0 - sigf((THRFL - SEAL_THR50) / SEAL_THRW), SEAL_POW);
capture G_ENTRY  = (AEN / AEN_REF) * seal_thro * (1.0 - sealo);
double one_thrdo = (1.0 - THRD > 0.0) ? (1.0 - THRD) : 0.0;
capture G_REENTRY = GRE0 * one_thrdo * one_thrdo;
double GTOTo = G_ENTRY + G_REENTRY;
capture TAU_FL = (GTOTo > 1e-9) ? (TAUFL0 / GTOTo) : 1e6;
double omegao  = 2.0 * M_PI * HR / 60.0;
capture PP_FALSE = PPo / sqrt(1.0 + omegao * omegao * TAU_FL * TAU_FL);
capture PFL_SYSTOLIC  = PFL + 2.0 / 3.0 * PP_FALSE;
capture PFL_DIASTOLIC = PFL - 1.0 / 3.0 * PP_FALSE;
double gsero = (GTOTo > 1e-9) ? (G_ENTRY * G_REENTRY / GTOTo) : 0.0;
double dppo  = (PPo - PP_FALSE > 0.0) ? (PPo - PP_FALSE) : 0.0;
double fthro = 1.0 - KFLOW_THR * THRFL;
capture FLOW_FALSE = (KQ * gsero + KTOFRO * G_ENTRY * dppo / 46.0)
                     * (fthro > 0.0 ? fthro : 0.0);

double h_effo = (HFL > 0.05) ? HFL : 0.05;
capture SIGMA_FL     = PFL * MMHG_TO_KPA * (DFL / 2.0) / h_effo;
capture SIGMA_FL_SYS = PFL_SYSTOLIC * MMHG_TO_KPA * (DFL / 2.0) / h_effo;
capture SIGMA_TL     = SBP * MMHG_TO_KPA * (DTL / 2.0) / (HAO0 * (1.0 - FOUT));
double mobo = pow(AEN / AEN_REF, 0.5);
if (mobo > 1.5) mobo = 1.5;
double expo = ((1.0 - THRFL > 0.0) ? (1.0 - THRFL) : 0.0) * (1.0 - sealo) * mobo;
capture SIGMA_FLAP = fabs(SBP - PFL_SYSTOLIC) * MMHG_TO_KPA * (DFL / 2.0) / 0.25 * expo;

// THE INDEX, and the flap index that carries the propagation threshold
capture ASI      = (SIGMA_FL_SYS / SIGREF) * (DPDT / DPDT0);
capture ASI_FLAP = (SIGMA_FLAP / SIGREF) * pow(DPDT / DPDT0, EXP_TEAR_DPDT);
capture ABOVE_TEAR_THRESHOLD = (ASI_FLAP > TEAR_TH) ? 1.0 : 0.0;

capture WALL_STRENGTH = SWALL0 * pow((ELN > 0.02 ? ELN : 0.02), EXP_ELN_S)
                        * (0.60 + 0.40 * COL);
capture STRESS_RATIO  = SIGMA_FL_SYS / WALL_STRENGTH;
capture D_AORTA       = sqrt(DTL * DTL + DFL * DFL);
capture FL_FRACTION   = DFL / ((DFL + DTL > 1e-6) ? (DFL + DTL) : 1e-6);

double flro = FL_FRACTION;
double domo = (flro - 0.40) / 0.30;
if (domo < 0.0) domo = 0.0;
if (domo > 1.0) domo = 1.0;
capture TL_COLLAPSE = sigf((PFL_DIASTOLIC - DBP - 5.0) / 4.0) * domo;
double dyno = KOBST_DYN * TL_COLLAPSE;
double pat_reno = (1.0 - OBST_REN) * (1.0 - dyno * INV_REN);
if (pat_reno < 0.02) pat_reno = 0.02;
capture RENAL_PERFUSION_PRESSURE = PMAP * pat_reno;
double pat_meso = (1.0 - OBST_MES) * (1.0 - dyno * INV_MES);
if (pat_meso < 0.02) pat_meso = 0.02;
capture Q_MESENTERIC = (0.04 + 1.02 * sigf((PMAP * pat_meso - 52.0) / 8.0) > 1.06)
                       ? 1.06 : (0.04 + 1.02 * sigf((PMAP * pat_meso - 52.0) / 8.0));
double pat_spio = (1.0 - OBST_SPI) * (1.0 - 0.55 * TL_COLLAPSE * INV_SPI);
if (pat_spio < 0.02) pat_spio = 0.02;
double covero = (TEVAR_T >= 0.0 && SOLVERTIME >= TEVAR_T) ? TEVAR_COVER : 0.0;
double lsso = 1.0 - 0.20 * THRFL - covero;
pat_spio *= (lsso > 0.05 ? lsso : 0.05);
double scppo = (PMAP - SCP_CSF) * (pat_spio + KCOL_SPI * COLLAT * (1.0 - pat_spio));
capture Q_SPINAL = (0.04 + 1.02 * sigf((scppo - SCPP50) / 7.0) > 1.06)
                   ? 1.06 : (0.04 + 1.02 * sigf((scppo - SCPP50) / 7.0));
capture PARAPLEGIA_PROB = sigf((SCI - SCI_PARA) / 3.0);

capture CYANIDE   = C_CNo;
capture THIOCYANATE = C_SCNo;
capture CYANIDE_TOXIC = (C_CNo > CN_TOX) ? 1.0 : 0.0;
capture EGFR = 175.0 * pow((CREAT > 0.2 ? CREAT : 0.2), -1.154) * pow(65.0, -0.203);
capture IN_TARGET = sigf((SBP - SBP_LO) / 2.0) * sigf((SBP_HI - SBP) / 2.0)
                    * sigf((HR_TGT + 5.0 - HR) / 2.0);
capture OCC_BETA1 = OCC_Bo;
capture OCC_CCB   = OCC_DHPo;
capture OCC_NOD   = OCC_NOo;
capture OCC_AT1   = BLK_AT1o;
capture RATE_VD   = VD_MAX * sigf(U_VD);
capture RATE_BB   = BB_MAX * sigf(U_BB);
capture MORTALITY = 100.0 * (1.0 - SURV);

# =============================================================================
#  CALIBRATION NOTES — what each anchor is, and what it was fitted to
# =============================================================================
#
#  PHARMACOKINETICS.  Esmolol CL 285 mL/kg/min and t1/2 9 min give the 0.70 mg/L
#  plateau at 200 ug/kg/min that the model uses for a 56% beta1 occupancy.
#  Labetalol t1/2 5.4 h with an IV alpha:beta potency ratio of 1:7.  Nicardipine
#  two-compartment with an effective distributive half-life of ~45 min, IC50
#  55 ng/mL.  Clevidipine t1/2 1.7 min (blood esterases) — the drug exists so
#  the vasodilator arm can be switched off in one minute.  Nitroprusside t1/2
#  2 min with stoichiometric cyanide release at 5 CN- per molecule = 0.436 mg
#  CN- per mg SNP, cyanide t1/2 40 min, thiocyanate t1/2 3 days and renally
#  cleared, which is why the model makes renal malperfusion a cyanide risk
#  factor and not just a blood-pressure problem.
#
#  HAEMODYNAMICS.  Reference 65-year-old, 75 kg, treated-but-imperfect
#  hypertension: baroreflex operating point 106 mmHg, HR 62, SVR 17.5, SV 76 mL,
#  arterial compliance 1.72 mL/mmHg, dP/dt max 1180 mmHg/s.  Untreated, the
#  acute arm settles at 154/102 mmHg with HR 71 — IRAD's mean presenting
#  systolic pressure in type B dissection is about 160.
#
#  WALL GEOMETRY.  Descending thoracic wall 1.9 mm; the dissection plane runs in
#  the outer third of the media, so the false-lumen outer wall is 0.40 of that
#  = 0.76 mm, against 1.14 mm for the true lumen.  With r = 8.5 mm and P = 95
#  mmHg that is sigma_FL = 142 kPa, inside the 100-200 kPa range reported for
#  human aortic circumferential stress, and 2.5x the true lumen at the same
#  pressure.  Wall strength 760 kPa fresh.
#
#  GROWTH.  KGROW is set so that a chronically patent false lumen grows the
#  total aortic diameter 3.96 mm/y — reported medically-managed chronic type B
#  growth is 3-4 mm/y with a patent false lumen and under 1 mm/y when it is
#  thrombosed (the model gives -0.2 mm/y, i.e. slow shrinkage of a sealed sac).
#
#  RUPTURE HAZARD.  H0_RUPT and W_RUPT are anchored so that sigma/S = 0.40 (a
#  26 mm dissected aorta at controlled pressure) gives 2%/y and sigma/S = 0.67
#  (a 58 mm one) gives about 11%/y.  KH_OTHER is 2%/y non-aortic mortality.
#
#  WHAT THE MODEL REPRODUCES WITHOUT BEING FITTED TO IT
#  ---------------------------------------------------
#  * Partial false-lumen thrombosis carries the worst prognosis.  Implied hazard
#    ratio versus a patent false lumen 2.36; the adjusted hazard ratio Tsai and
#    colleagues reported from IRAD is 2.69.  The model was given two anatomical
#    numbers, not a hazard ratio.
#  * Vasodilator monotherapy is harmful.  At its labelled ceiling nicardipine
#    lowers systolic pressure 33 mmHg and changes dP/dt max by +0.3%; the entry
#    tear grows 12-13% in 72 h against 1% for an esmolol-first regimen at the
#    same pressure, and 72-h mortality (4.7-5.1%) exceeds giving nothing at all
#    (2.3%).  Every guideline says beta-blockade first; this model says why.
#  * Refractory hypertension in aortic dissection is renal, not pharmacological.
#    The same regimen at the same target reaches SBP 141 with a renal artery off
#    the false lumen and SBP 113 without, with the vasodilator already at its
#    ceiling and renin at 2.5x normal.
#  * Analgesia is an antihypertensive: fentanyl alone takes systolic pressure
#    from 154 to 143 mmHg and dP/dt down 7%.
#
#  WHAT THE MODEL PREDICTS THAT IS NOT ESTABLISHED — TREAT WITH SUSPICION
#  ---------------------------------------------------------------------
#  * Losartan added to a beta-blocked patient does nothing for aortic growth
#    (time to 55 mm 2.00 y without, 1.95 y with).  The mechanism offered is that
#    beta-blockade has already suppressed renin, and what AT1 blockade does
#    reach the wall removes TGF-beta-driven adventitial collagen — the only
#    negative feedback in the model — as fast as it removes Ang II-driven MMP-9.
#    This agrees with the randomised trials that failed to show losartan
#    superior to a beta-blocker, but the cancellation could equally be an
#    artefact of the TGF-beta/collagen coupling.  It is the model's most exposed
#    prediction.
#  * Sustained spinal perfusion-pressure augmentation after coverage halves the
#    cord-ischaemia burden and does not improve five-year survival, because the
#    pressure that perfuses the cord also loads the aorta.  The model's reading
#    is that augmentation belongs to the coverage window and not to the
#    discharge prescription — but the model has no within-window resolution of
#    the cord's tolerance and should not be used to set a duration.
#  * The tear-propagation threshold TEAR_TH = 0.45 is a model construct.  Its
#    existence (a regimen either is or is not above it) is doing a lot of work
#    in the acute-mortality comparison, and no human measurement anchors it.
#
# =============================================================================
#  SCENARIO LIBRARY — the 22 arms reported in aad_reference_output.txt
# =============================================================================
#
#  library(mrgsolve); library(dplyr)
#  mod <- mread("aad_mrgsolve_model", "aortic-dissection")
#  run <- function(end = 72, ...) mod %>% param(...) %>%
#           mrgsim(end = end, delta = ifelse(end > 800, 24, 0.1))
#
#  # --- acute phase, 72 h, all titrated to systolic 110 -------------------
#  S01 <- run()                                                  # untreated
#  S02 <- run(VD_AGENT = 1, VD_MAX = 15)                         # nicardipine only
#  S03 <- run(BB_AGENT = 1, BB_MAX = 1350, BB_ON_SBP = 1)        # esmolol only
#  S04 <- run(BB_AGENT = 1, BB_MAX = 900, VD_AGENT = 1, VD_MAX = 15)   # guideline
#  S05 <- run(VD_AGENT = 3, VD_MAX = 13.5)                       # nitroprusside only
#  S06 <- run(VD_AGENT = 3, VD_MAX = 13.5, BB_AGENT = 1, BB_MAX = 900) # Wheat
#  S07 <- run(BB_AGENT = 2, BB_MAX = 120, BB_ON_SBP = 1)         # labetalol
#  S08 <- run(VD_AGENT = 2, VD_MAX = 21, BB_AGENT = 1, BB_MAX = 900)   # clevidipine
#  S09 <- run(R_FEN = 0.075)                                     # analgesia only
#  S10 <- run(R_FEN = 0.075, BB_AGENT = 1, BB_MAX = 900,
#             VD_AGENT = 1, VD_MAX = 15)                         # full protocol
#  S21 <- run(VD_AGENT = 1, VD_MAX = 30)                         # above-label match
#
#  # --- malperfusion, the renin trap, cyanide ----------------------------
#  S11 <- run(VD_AGENT = 1, VD_MAX = 32, BB_AGENT = 1, BB_MAX = 900,
#             SBP_SET = 95, OBST_REN = 0.45, INV_REN = 1, INV_MES = 1)
#  S12 <- run(VD_AGENT = 1, VD_MAX = 32, BB_AGENT = 1, BB_MAX = 900,
#             OBST_REN = 0.45, INV_REN = 1, INV_MES = 1)
#  S13 <- run(VD_AGENT = 3, VD_MAX = 45, BB_AGENT = 1, BB_MAX = 900,
#             OBST_REN = 0.45, INV_REN = 1, SBP_SET = 100)
#
#  # --- false-lumen anatomy, 5 years -------------------------------------
#  S14 <- run(43800, GRE0 = 2.40, D_MET = 100, D_LOS = 50)       # patent
#  S15 <- run(43800, GRE0 = 0.05, D_MET = 100, D_LOS = 50)       # partial (blind sac)
#  S16 <- run(43800, GRE0 = 0.05, AEN0 = 9, D_MET = 100, D_LOS = 50)  # complete
#  S17 <- run(43800, GRE0 = 0.05, TEVAR_T = 336, D_MET = 100, D_LOS = 50)  # TEVAR
#  S22 <- run(43800, GRE0 = 0.05, TEVAR_T = 336, D_MET = 50, D_LOS = 25,
#             SBP_SET = 135)                                     # + MAP augmentation
#
#  # --- chronic therapy, genetics, adherence -----------------------------
#  S18 <- run(43800, GEN_MMP = 2.2, GRE0 = 0.05, D_MET = 100, D_LOS = 50)
#  S19 <- run(43800, GEN_MMP = 2.2, GRE0 = 0.05, D_MET = 100, D_LOS = 0)
#  S20 <- run(43800, GRE0 = 0.05, D_MET = 100, D_LOS = 50, ADHERE = 0.25)
#
#  # --- the comparison the model exists to make --------------------------
#  # At matched systolic pressure, read DPDT, ASI, ASI_FLAP and MORTALITY:
#  #   S21 (nicardipine, SBP 118): 1468 mmHg/s, 1.65, 0.83, 5.06%
#  #   S04 (esmolol first, SBP 113): 1017 mmHg/s, 1.16, 0.30, 0.59%
#  #   S01 (nothing at all,  SBP 154): 1463 mmHg/s, 2.26, 0.67, 2.34%
# =============================================================================
