##  Hypereosinophilic Syndrome (HES) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : HES — persistent blood/tissue eosinophilia with eosinophil-
##             mediated organ damage. Model tracks the two principal molecular
##             axes — myeloid/neoplastic constitutively-active tyrosine-kinase
##             fusion signaling (FIP1L1-PDGFRA, PDGFRB-rearranged, JAK2-
##             rearranged) and lymphocytic-variant clonal-T-cell IL-5-driven
##             eosinophilopoiesis — through marrow eosinophil production,
##             circulating/tissue eosinophil burden, degranulation-mediated
##             organ damage (cardiac Loeffler endocarditis as the anchor
##             severity endpoint), and response to genotype-matched therapy
##             (imatinib, corticosteroids, anti-IL-5-axis biologics
##             [mepolizumab/benralizumab], hydroxyurea, ruxolitinib).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 21 ODE compartments — drug PK (imatinib 2 [gut+central],
##             prednisone/prednisolone 2, mepolizumab 2 [SC depot+central],
##             benralizumab 2 [SC depot+central], hydroxyurea 2, ruxolitinib
##             2 = 12) + disease/PD network (constitutive kinase-signaling
##             index, endogenous IL-5, marrow eosinophil-production drive,
##             circulating absolute eosinophil count [AEC], tissue eosinophil
##             burden, cardiac Loeffler damage index, cardiac troponin,
##             composite HES symptom/flare score, serum ECP biomarker = 9).
##  Time     : hours (PK); disease dynamics resolved over weeks-months
##             (marrow turnover days, cardiac fibrosis remodeling weeks).
##             Default horizon 0-4320 h (180 days).
##  Units    : dose mg; concentration mg/L; AEC cells/µL; kinase-signaling
##             index & IL-5 arbitrary units (AU, 1.0 = untreated FIP1L1-
##             PDGFRA+ baseline); cardiac damage index 0(none)-1(severe
##             restrictive); troponin ng/L; HES symptom score 0-10;
##             ECP µg/L.
##  Scenarios: 10 prebuilt — see HES_simulate_scenarios() at bottom.
##  Genotype : GENOTYPE 0=idiopathic/lymphocytic-variant (IL-5-driven, TKI-
##             insensitive), 1=FIP1L1-PDGFRA+ (imatinib-exquisitely-
##             sensitive), 2=PDGFRB-rearranged (imatinib-sensitive),
##             3=JAK2-rearranged (ruxolitinib-sensitive, imatinib-insensitive).
##  Anchors  : Klion AD 2022 Blood (HES diagnosis/classification review);
##             Gotlib J 2021 Am J Hematol (HES annual clinical update);
##             Cools J 2003 NEJM (FIP1L1-PDGFRA discovery, imatinib
##             sensitivity); Pardanani A 2003 Blood (imatinib response in
##             FIP1L1-PDGFRA+ HES); Klion AD 2004 Blood (imatinib dose-
##             response, 100 mg vs 400 mg); Cools J 2004 Cancer Cell (T674I
##             imatinib-resistance mutation); Roufosse F 2020 J Allergy Clin
##             Immunol (mepolizumab HES pivotal trial); Kuang FL 2022 NEJM
##             (mepolizumab HES relapse-prevention trial); Kuang FL 2019 J
##             Allergy Clin Immunol (benralizumab open-label HES trial);
##             Roufosse F 2009 Allergy (lymphocytic-variant HES review);
##             Ogbogu PU 2009 J Allergy Clin Immunol (HES multicenter organ-
##             damage/therapy cohort); Parrillo JE 1979 Ann Intern Med
##             (Loeffler endocarditis natural history); Weller PF & Bubley GJ
##             1994 Blood (HES eosinophil-mediated tissue-damage review);
##             Peters MJ 2004 Clin Pharmacokinet (imatinib population PK);
##             Meno-Tetang GM 2007 Int J Clin Pharmacol Ther (mepolizumab
##             PK); Kolbeck R 2010 J Allergy Clin Immunol (benralizumab
##             afucosylated ADCC mechanism).
##  Disclaimer: For research / education / hypothesis generation only. Not a
##              substitute for clinical judgment, hematology/immunology
##              practice guidelines, or regulatory decision-making.
##  ============================================================================
[PROB]
QSP model of hypereosinophilic syndrome (HES) linking molecular-genotype-
specific constitutive kinase signaling (FIP1L1-PDGFRA/PDGFRB/JAK2) or
clonal-T-cell IL-5 overproduction to marrow eosinophilopoiesis, circulating/
tissue eosinophil burden, degranulation-mediated cardiac (Loeffler
endocarditis) and composite organ damage, and genotype-matched pharmacologic
response (imatinib, corticosteroids, mepolizumab, benralizumab, hydroxyurea,
ruxolitinib).

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease classification
AGE          : 42    : age (years)
WT           : 75    : body weight (kg)
GENOTYPE     : 1     : 0=idiopathic/L-HES, 1=FIP1L1-PDGFRA+, 2=PDGFRB-rearranged, 3=JAK2-rearranged
T674I_MUT    : 0     : 1 = acquired PDGFRA T674I imatinib-resistance mutation
BASE_AEC     : 8000  : baseline untreated absolute eosinophil count (cells/uL)
BASE_CARDIAC : 0.05  : baseline cardiac (Loeffler) damage index (0-1)
CARDIAC_INVOLVED : 0 : 1 = established cardiac involvement at baseline (accelerates fibrosis)

//--- Imatinib PK (oral TKI; F~0.98, hepatic CYP3A4, t1/2 ~18h)
KA_IMA      : 0.60   : 1/h
F_IMA       : 0.98   : bioavailability (fraction)
CL_IMA      : 8.0    : L/h
V_IMA       : 220     : L

//--- Prednisone/prednisolone PK (oral; rapid absorption, hepatic activation
//    modeled as single active moiety, t1/2 ~3h but pharmacodynamic effect
//    persists via slow-turnover downstream compartments)
KA_PRED     : 1.1    : 1/h
F_PRED      : 0.90   : bioavailability (fraction)
CL_PRED     : 12     : L/h
V_PRED      : 45      : L

//--- Mepolizumab PK (SC; F~0.80, t1/2 ~20 days, target-mediated drug
//    disposition minor at approved dose)
KA_MEPO     : 0.012   : 1/h (slow SC absorption)
F_MEPO      : 0.80   : bioavailability (fraction)
CL_MEPO     : 0.0090  : L/h
V_MEPO      : 5.0      : L

//--- Benralizumab PK (SC; F~0.58, t1/2 ~15-18 days)
KA_BENRA    : 0.010   : 1/h
F_BENRA     : 0.58   : bioavailability (fraction)
CL_BENRA    : 0.0110  : L/h
V_BENRA     : 5.5      : L

//--- Hydroxyurea PK (oral; rapid absorption, t1/2 ~4h)
KA_HU       : 1.4    : 1/h
F_HU        : 0.85   : bioavailability (fraction)
CL_HU       : 8.5     : L/h
V_HU        : 35      : L

//--- Ruxolitinib PK (oral JAK1/2 inhibitor; F~0.95, t1/2 ~3h)
KA_RUX      : 1.8    : 1/h
F_RUX       : 0.95   : bioavailability (fraction)
CL_RUX      : 13     : L/h
V_RUX       : 72      : L

//--- Constitutive kinase-signaling index (FIP1L1-PDGFRA/PDGFRB/JAK2) turnover
KOUT_KIN      : 0.020  : 1/h
KIN_BASE_G1   : 1.00   : baseline kinase-signaling index, GENOTYPE 1 (FIP1L1-PDGFRA+)
KIN_BASE_G2   : 0.85   : baseline kinase-signaling index, GENOTYPE 2 (PDGFRB-rearranged)
KIN_BASE_G3   : 0.75   : baseline kinase-signaling index, GENOTYPE 3 (JAK2-rearranged)
KIN_BASE_G0   : 0.05   : baseline kinase-signaling index, GENOTYPE 0 (idiopathic/L-HES, kinase-independent)
EC50_IMA_KIN  : 0.08   : mg/L, imatinib EC50 for kinase inhibition (wild-type)
T674I_EC50_MULT: 15    : fold-increase in imatinib EC50 conferred by T674I mutation
EMAX_IMA_KIN  : 0.97   : max fractional kinase-signaling inhibition by imatinib (wild-type)
EC50_RUX_KIN  : 0.15   : mg/L, ruxolitinib EC50 for JAK2-signaling inhibition
EMAX_RUX_KIN  : 0.90   : max fractional kinase-signaling inhibition by ruxolitinib (GENOTYPE 3 only)
HU_KIN_SUPPRESS: 0.30  : max fractional nonselective cytoreductive suppression of marrow output from hydroxyurea

//--- Endogenous IL-5 (clonal-T-cell / Th2-driven) turnover — dominant driver
//    in GENOTYPE 0 (idiopathic/L-HES); minor contributor in myeloid genotypes
KOUT_IL5      : 0.035  : 1/h
IL5_BASE_G0   : 1.00   : baseline IL-5 index, GENOTYPE 0
IL5_BASE_MYELOID: 0.30 : baseline IL-5 index, GENOTYPE 1-3 (paracrine/reactive)
EC50_PRED_IL5 : 0.15   : mg/L, prednisolone EC50 for IL-5 transcriptional suppression
EMAX_PRED_IL5 : 0.75   : max fractional IL-5 suppression from corticosteroids
IFN_ALEMTUZ_IL5_SUPPRESS: 0.55 : fractional IL-5 suppression from immunomodulatory therapy (scenario switch, applied as fixed multiplier)

//--- Marrow eosinophil-production drive turnover (upstream of AEC, days-scale)
KOUT_MARROW   : 0.045  : 1/h
MARROW_GAIN_KIN: 1.05  : marrow-drive gain per unit kinase-signaling index
MARROW_GAIN_IL5: 0.95  : marrow-drive gain per unit IL-5 index
PRED_DIRECT_APOPTOSIS: 0.60 : max fractional direct eosinophil-survival suppression (apoptosis induction) from corticosteroids, acting on AEC directly
EC50_PRED_APOP: 0.10   : mg/L, prednisolone EC50 for eosinophil apoptosis induction

//--- Circulating absolute eosinophil count (AEC, cells/uL) turnover
KOUT_AEC      : 0.060  : 1/h (fast relative to marrow, reflects short peripheral half-life ~8-18h amplified by survival signals)
AEC_MARROW_GAIN: 1.0   : proportionality of steady-state AEC to marrow drive x baseline
BENRA_ADCC_EMAX: 0.98  : max fractional direct AEC depletion via benralizumab ADCC (near-complete, receptor-independent of IL-5 level)
EC50_BENRA_ADCC: 0.001 : mg/L, benralizumab EC50 for ADCC-mediated eosinophil depletion (very high potency)
MEPO_IL5_NEUT_EMAX: 0.90 : max fractional free-IL-5 neutralization by mepolizumab (acts via IL5 compartment, not directly on AEC)
EC50_MEPO_IL5 : 0.50   : mg/L, mepolizumab EC50 for IL-5 neutralization

//--- Tissue eosinophil burden turnover (chemotaxis/transmigration, days-scale)
KOUT_TISSUE   : 0.030  : 1/h
TISSUE_AEC_GAIN: 1.0   : proportionality of tissue burden to circulating AEC

//--- Cardiac (Loeffler) damage index turnover — slow fibrotic remodeling
//    (weeks), partially reversible with sustained eosinophil suppression
KOUT_CARDIAC  : 0.0015 : 1/h (slow accrual/regression, weeks-scale)
CARDIAC_TISSUE_GAIN: 0.045 : cardiac-damage accrual rate per unit tissue-eosinophil-burden x time
CARDIAC_REGRESS_FLOOR: 0.03 : minimum residual fibrotic damage index (scarring largely irreversible)
CARDIAC_ACCEL_INVOLVED: 1.8 : multiplier on accrual rate if CARDIAC_INVOLVED=1 at baseline (active endocarditis)

//--- Cardiac troponin biomarker (acute necrosis marker, fast turnover)
KOUT_TROP     : 0.15   : 1/h
TROP_BASE     : 5      : ng/L
TROP_GAIN_CARDIAC_RATE: 900 : ng/L per unit of *active* cardiac-damage accrual rate (necrosis signal)

//--- Serum ECP biomarker (degranulation marker, tracks tissue burden)
KOUT_ECP      : 0.08   : 1/h
ECP_BASE      : 8      : ug/L
ECP_GAIN_TISSUE: 45    : ug/L per unit tissue-eosinophil-burden

//--- Composite HES symptom/flare score (0-10) turnover
KOUT_SYMPTOM  : 0.045  : 1/h
SYMPTOM_GAIN_AEC : 3.2  : symptom points per unit (AEC/BASE_AEC) ratio
SYMPTOM_GAIN_CARDIAC: 4.5 : symptom points per unit cardiac-damage index
SYMPTOM_GAIN_TISSUE: 1.8 : symptom points per unit tissue-eosinophil-burden ratio

[CMT] @annotated
GUT_IMA    : Imatinib gut depot (mg)
CEN_IMA    : Imatinib central plasma (mg)
GUT_PRED   : Prednisone/prednisolone gut depot (mg)
CEN_PRED   : Prednisolone central plasma (mg)
DEPOT_MEPO : Mepolizumab SC depot (mg)
CEN_MEPO   : Mepolizumab central plasma (mg)
DEPOT_BENRA: Benralizumab SC depot (mg)
CEN_BENRA  : Benralizumab central plasma (mg)
GUT_HU     : Hydroxyurea gut depot (mg)
CEN_HU     : Hydroxyurea central plasma (mg)
GUT_RUX    : Ruxolitinib gut depot (mg)
CEN_RUX    : Ruxolitinib central plasma (mg)
KIN        : Constitutive kinase-signaling index (AU, genotype-normalized)
IL5        : Endogenous IL-5 index (AU)
MARROW     : Marrow eosinophil-production drive (relative to baseline)
AEC        : Circulating absolute eosinophil count (cells/uL)
TISSUE     : Tissue eosinophil burden (relative to baseline)
CARDIAC    : Cardiac (Loeffler) damage index (0-1)
TROP       : Cardiac troponin (ng/L)
ECP        : Serum ECP biomarker (ug/L)
SYMPTOM    : Composite HES symptom/flare score (0-10)

[MAIN]
GUT_IMA_0 = 0; CEN_IMA_0 = 0;
GUT_PRED_0 = 0; CEN_PRED_0 = 0;
DEPOT_MEPO_0 = 0; CEN_MEPO_0 = 0;
DEPOT_BENRA_0 = 0; CEN_BENRA_0 = 0;
GUT_HU_0 = 0; CEN_HU_0 = 0;
GUT_RUX_0 = 0; CEN_RUX_0 = 0;

double kin_base = (GENOTYPE == 1) ? KIN_BASE_G1 :
                   (GENOTYPE == 2) ? KIN_BASE_G2 :
                   (GENOTYPE == 3) ? KIN_BASE_G3 : KIN_BASE_G0;
double il5_base = (GENOTYPE == 0) ? IL5_BASE_G0 : IL5_BASE_MYELOID;

KIN_0    = kin_base;
IL5_0    = il5_base;
MARROW_0 = MARROW_GAIN_KIN * kin_base + MARROW_GAIN_IL5 * il5_base;
AEC_0    = BASE_AEC;
TISSUE_0 = 1.0;
CARDIAC_0 = BASE_CARDIAC;
TROP_0    = TROP_BASE;
ECP_0     = ECP_BASE;
SYMPTOM_0 = SYMPTOM_GAIN_AEC * 1.0 + SYMPTOM_GAIN_TISSUE * 1.0;

[ODE]
// ---------- PK ----------
double CIMA   = CEN_IMA   / V_IMA;
double CPRED  = CEN_PRED  / V_PRED;
double CMEPO  = CEN_MEPO  / V_MEPO;
double CBENRA = CEN_BENRA / V_BENRA;
double CHU    = CEN_HU    / V_HU;
double CRUX   = CEN_RUX   / V_RUX;

dxdt_GUT_IMA = -KA_IMA * GUT_IMA;
dxdt_CEN_IMA =  F_IMA * KA_IMA * GUT_IMA - (CL_IMA/V_IMA) * CEN_IMA;

dxdt_GUT_PRED = -KA_PRED * GUT_PRED;
dxdt_CEN_PRED =  F_PRED * KA_PRED * GUT_PRED - (CL_PRED/V_PRED) * CEN_PRED;

dxdt_DEPOT_MEPO = -KA_MEPO * DEPOT_MEPO;
dxdt_CEN_MEPO   =  F_MEPO * KA_MEPO * DEPOT_MEPO - (CL_MEPO/V_MEPO) * CEN_MEPO;

dxdt_DEPOT_BENRA = -KA_BENRA * DEPOT_BENRA;
dxdt_CEN_BENRA   =  F_BENRA * KA_BENRA * DEPOT_BENRA - (CL_BENRA/V_BENRA) * CEN_BENRA;

dxdt_GUT_HU = -KA_HU * GUT_HU;
dxdt_CEN_HU =  F_HU * KA_HU * GUT_HU - (CL_HU/V_HU) * CEN_HU;

dxdt_GUT_RUX = -KA_RUX * GUT_RUX;
dxdt_CEN_RUX =  F_RUX * KA_RUX * GUT_RUX - (CL_RUX/V_RUX) * CEN_RUX;

// ---------- Kinase-signaling index (imatinib for GENOTYPE 1/2; ruxolitinib for GENOTYPE 3) ----------
double ima_ec50 = EC50_IMA_KIN * (T674I_MUT == 1 ? T674I_EC50_MULT : 1.0);
double ima_inh  = (GENOTYPE == 1 || GENOTYPE == 2) ?
                   EMAX_IMA_KIN * CIMA / (ima_ec50 + CIMA) : 0.0;
double rux_inh  = (GENOTYPE == 3) ?
                   EMAX_RUX_KIN * CRUX / (EC50_RUX_KIN + CRUX) : 0.0;
double kin_ss   = kin_base * (1.0 - ima_inh) * (1.0 - rux_inh);
dxdt_KIN = KOUT_KIN * (kin_ss - KIN);

// ---------- Endogenous IL-5 index (corticosteroid-suppressible) ----------
double pred_il5_inh = EMAX_PRED_IL5 * CPRED / (EC50_PRED_IL5 + CPRED);
double il5_ss = il5_base * (1.0 - pred_il5_inh);
dxdt_IL5 = KOUT_IL5 * (il5_ss - IL5);

// free (mepolizumab-neutralizable) IL-5 signal reaching the marrow
double mepo_neut = MEPO_IL5_NEUT_EMAX * CMEPO / (EC50_MEPO_IL5 + CMEPO);
double IL5_free = IL5 * (1.0 - mepo_neut);

// ---------- Marrow eosinophil-production drive ----------
double hu_suppress = HU_KIN_SUPPRESS * CHU / (2.0 + CHU);
double marrow_ss = (MARROW_GAIN_KIN * KIN + MARROW_GAIN_IL5 * IL5_free) * (1.0 - hu_suppress);
dxdt_MARROW = KOUT_MARROW * (marrow_ss - MARROW);

// ---------- Circulating absolute eosinophil count ----------
double pred_apop = PRED_DIRECT_APOPTOSIS * CPRED / (EC50_PRED_APOP + CPRED);
double benra_adcc = BENRA_ADCC_EMAX * CBENRA / (EC50_BENRA_ADCC + CBENRA);
double aec_ss = BASE_AEC * AEC_MARROW_GAIN * MARROW * (1.0 - pred_apop) * (1.0 - benra_adcc);
if (aec_ss < 10) aec_ss = 10;
dxdt_AEC = KOUT_AEC * (aec_ss - AEC);

// ---------- Tissue eosinophil burden ----------
double tissue_ss = TISSUE_AEC_GAIN * (AEC / BASE_AEC);
dxdt_TISSUE = KOUT_TISSUE * (tissue_ss - TISSUE);

// ---------- Cardiac (Loeffler) damage index ----------
double cardiac_accel = (CARDIAC_INVOLVED == 1) ? CARDIAC_ACCEL_INVOLVED : 1.0;
double cardiac_drive = CARDIAC_TISSUE_GAIN * cardiac_accel * TISSUE;
double cardiac_ss = CARDIAC_REGRESS_FLOOR + (1.0 - CARDIAC_REGRESS_FLOOR) *
                     (cardiac_drive / (cardiac_drive + KOUT_CARDIAC));
dxdt_CARDIAC = KOUT_CARDIAC * (cardiac_ss - CARDIAC);

// ---------- Cardiac troponin (tracks *active* damage-accrual rate) ----------
double cardiac_rate = fabs(KOUT_CARDIAC * (cardiac_ss - CARDIAC));
double trop_ss = TROP_BASE + TROP_GAIN_CARDIAC_RATE * cardiac_rate;
dxdt_TROP = KOUT_TROP * (trop_ss - TROP);

// ---------- Serum ECP ----------
double ecp_ss = ECP_BASE + ECP_GAIN_TISSUE * TISSUE;
dxdt_ECP = KOUT_ECP * (ecp_ss - ECP);

// ---------- Composite HES symptom/flare score ----------
double symptom_ss = SYMPTOM_GAIN_AEC * (AEC / BASE_AEC) +
                     SYMPTOM_GAIN_CARDIAC * CARDIAC +
                     SYMPTOM_GAIN_TISSUE * TISSUE;
if (symptom_ss > 10) symptom_ss = 10;
dxdt_SYMPTOM = KOUT_SYMPTOM * (symptom_ss - SYMPTOM);

[TABLE]
capture Cp_imatinib     = CIMA;
capture Cp_prednisolone = CPRED;
capture Cp_mepolizumab  = CMEPO;
capture Cp_benralizumab = CBENRA;
capture Cp_hydroxyurea  = CHU;
capture Cp_ruxolitinib  = CRUX;
capture AEC_ratio       = AEC / BASE_AEC;
capture Flare_flag      = (SYMPTOM >= 4) ? 1 : 0;

[CAPTURE]


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("hes_mrgsolve_model.R")
##
##  # ---------- 10 prebuilt scenarios (end_h = simulation horizon, hours) ----------
##
##  HES_simulate_scenarios <- function(end_h = 4320) {
##
##    sc <- list(
##      "1. Untreated FIP1L1-PDGFRA+ M-HES (natural history)" =
##        list(param=list(GENOTYPE=1), ev=ev(amt=0, cmt="GUT_IMA", time=0)),
##
##      "2. FIP1L1-PDGFRA+ M-HES + Imatinib 100 mg PO QD" =
##        list(param=list(GENOTYPE=1),
##             ev=ev(amt=100, cmt="GUT_IMA", ii=24, addl=ceiling(end_h/24))),
##
##      "3. Imatinib-resistant (T674I) FIP1L1-PDGFRA+ -> switch to Hydroxyurea" =
##        list(param=list(GENOTYPE=1, T674I_MUT=1),
##             ev=seq(ev(amt=400, cmt="GUT_IMA", ii=24, addl=29),   # 30 d futile high-dose imatinib
##                     ev(amt=1000, cmt="GUT_HU", ii=24, time=30*24, addl=ceiling(end_h/24)))),
##
##      "4. Idiopathic HES + Prednisone taper (steroid-responsive)" =
##        list(param=list(GENOTYPE=0),
##             ev=ev(amt=60, cmt="GUT_PRED", ii=24, addl=ceiling(end_h/24))),  # fixed dose; taper via param sweep
##
##      "5. Idiopathic HES steroid-refractory + Mepolizumab 300 mg SC Q4W" =
##        list(param=list(GENOTYPE=0),
##             ev=ev(amt=300, cmt="DEPOT_MEPO", ii=24*28, addl=ceiling(end_h/(24*28)))),
##
##      "6. Lymphocytic-variant HES + Benralizumab 30 mg SC Q4W" =
##        list(param=list(GENOTYPE=0),
##             ev=ev(amt=30, cmt="DEPOT_BENRA", ii=24*28, addl=ceiling(end_h/(24*28)))),
##
##      "7. PDGFRB-rearranged HES + low-dose Imatinib 100 mg QD" =
##        list(param=list(GENOTYPE=2),
##             ev=ev(amt=100, cmt="GUT_IMA", ii=24, addl=ceiling(end_h/24))),
##
##      "8. Cardiac Loeffler endocarditis (established) + high-dose steroid pulse" =
##        list(param=list(GENOTYPE=0, CARDIAC_INVOLVED=1, BASE_CARDIAC=0.35),
##             ev=ev(amt=100, cmt="GUT_PRED", ii=24, addl=ceiling(end_h/24))),
##
##      "9. JAK2-rearranged HES + Ruxolitinib 20 mg BID" =
##        list(param=list(GENOTYPE=3),
##             ev=ev(amt=20, cmt="GUT_RUX", ii=12, addl=2*ceiling(end_h/24))),
##
##      "10. Steroid taper + Mepolizumab steroid-sparing combination" =
##        list(param=list(GENOTYPE=0),
##             ev=seq(ev(amt=40, cmt="GUT_PRED", ii=24, addl=13),   # 2-wk steroid bridge
##                     ev(amt=300, cmt="DEPOT_MEPO", ii=24*28, time=14*24, addl=ceiling(end_h/(24*28)))))
##    )
##
##    purrr::imap_dfr(sc, function(s, lab) {
##      m <- do.call(param, c(list(mod), s$param))
##      m %>% mrgsim(s$ev, end=end_h, delta=1) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Imatinib exquisite sensitivity in FIP1L1-PDGFRA+ HES (Cools 2003 NEJM;
##  #   Pardanani 2003 Blood): complete hematologic response within 1-4 weeks
##  #   at doses as low as 100 mg/day; molecular remission (transcript
##  #   undetectable) typically follows over months.
##  # T674I resistance mutation (Cools 2004 Cancer Cell): analogous to BCR-ABL
##  #   T315I, confers >10-15x rightward shift in imatinib EC50; clinically
##  #   managed by alternative TKI or cytoreductive/biologic therapy.
##  # Mepolizumab HES trials (Roufosse 2020 JACI; Kuang 2022 NEJM): reduces
##  #   flare frequency and enables steroid-sparing in steroid-dependent/
##  #   refractory idiopathic and lymphocytic-variant HES; does not directly
##  #   deplete eosinophils but blocks IL-5-driven survival/production.
##  # Benralizumab ADCC mechanism (Kolbeck 2010 JACI; Kuang 2019 JACI):
##  #   afucosylated Fc drives near-complete eosinophil depletion independent
##  #   of IL-5 pathway status, including in FIP1L1-PDGFRA-negative and
##  #   lymphocytic-variant disease.
##  # Loeffler endocarditis natural history (Parrillo 1979 Ann Intern Med):
##  #   progresses acute necrotic -> thrombotic -> fibrotic stage over weeks
##  #   to months if eosinophilia uncontrolled; fibrotic/restrictive stage is
##  #   largely irreversible even after hematologic remission is achieved.
##
##  # ---------- Quick sanity plots ----------
##  # df <- HES_simulate_scenarios(4320)
##  # ggplot(df, aes(time/24, AEC, color=scenario)) + geom_line() +
##  #   scale_y_log10() + labs(x="Day", y="AEC (cells/uL)")
##  # ggplot(df, aes(time/24, CARDIAC, color=scenario)) + geom_line() +
##  #   labs(x="Day", y="Cardiac (Loeffler) damage index")
