##  Dry Eye Disease (DED, 건성안) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Dry eye disease (evaporative MGD-driven and aqueous-deficient
##             Sjögren-associated phenotypes), tear-film instability and
##             ocular-surface inflammatory vicious cycle
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 22 ODE compartments — topical/local drug exposure (cyclosporine
##             0.05%/0.09%, lifitegrast 5%, loteprednol 0.25% + cumulative
##             exposure tracker, perfluorohexyloctane, varenicline nasal spray
##             [nasal depot + systemic/trigeminal-reflex compartment],
##             diquafosol 3%) + tear-film/ocular-surface disease network
##             (osmolarity, lipid-layer proxy, aqueous production, mucin/goblet
##             density, dendritic-cell activation, IL-17 tone, MMP-9, epithelial
##             barrier integrity, corneal nerve density, neuropathic pain) +
##             clinical-endpoint compartments (TBUT, corneal staining, Schirmer,
##             OSDI).
##  Time     : days (study horizon 0-180 d; default 84 d / 12 wk trial window)
##  Units    : local/topical drug amount in arbitrary surface-exposure units
##             (au, proportional to instilled mass, NOT systemic plasma conc —
##             topical ophthalmic PK is dominated by tear turnover on a minutes
##             scale, so a day-resolution surrogate "sustained local exposure"
##             compartment is used, consistent with how this library treats
##             other topical agents); disease/biomarker states in study-typical
##             units (see [CMT] below).
##  Scenarios: 9 prebuilt — see DED_simulate_scenarios() at bottom.
##  Anchors  : Restasis/cyclosporine 0.05% (Sall 2000 Ophthalmology 107:631;
##             ATP III Fam 2019); Cequa/cyclosporine 0.09% (Tauber 2018 Cornea);
##             Xiidra/lifitegrast (OPUS-2 Tauber 2015 Ophthalmology, OPUS-3
##             Holland 2017 J Cataract Refract Surg — CFS/OSDI at wk 6);
##             Miebo/perfluorohexyloctane (GOBI Sheppard 2023 JAMA Ophthalmol,
##             MOJAVE Sheppard 2024 Am J Ophthalmol — TSS/CFS at wk 8);
##             Tyrvaya/varenicline nasal spray (ONSET-1 Wirta 2022 Ophthalmology,
##             ONSET-2 Quiroz-Mercado 2022 — Schirmer/eye-dryness score);
##             Diquafosol 3% (Matsumoto 2012 Cornea; Koh 2013 Jpn J Ophthalmol —
##             TBUT/fluorescein staining, approved Japan/Korea);
##             TFOS DEWS II (Craig 2017 Ocul Surf 15:276 — core mechanism/
##             vicious-cycle framework); Baudouin 2016 Ocul Surf 14:1-16 (MMP-9/
##             hyperosmolarity inflammatory cascade review).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of dry eye disease linking tear-film hyperosmolarity, meibomian-gland
and lacrimal-gland dysfunction, innate/adaptive ocular-surface inflammation
(dendritic cell -> Th17/IL-17A -> MMP-9), epithelial barrier breakdown, and
corneal neurosensory dysfunction to clinical endpoints (OSDI, TBUT, corneal
staining, Schirmer), with mechanistic PK/PD for topical anti-inflammatory,
secretagogue, and barrier-restoring agents.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease-subtype severity
MGD_SEV      : 0.6   : evaporative MGD severity (0=none, 1=severe gland dropout)
ADDE_SEV     : 0.3   : aqueous-deficient (lacrimal) severity (0=none, 1=severe Sjögren)
AUTOIMMUNE   : 0     : 1 = Sjögren/autoimmune-associated DED (raises chronic immune tone)
REFRACTIVE_SURG : 0  : 1 = prior LASIK/PRK (acute corneal-nerve transection)
BASE_OSDI    : 45    : baseline OSDI (0-100, higher=worse)

//--- Cyclosporine A 0.05%/0.09% topical BID (Restasis/Cequa) surrogate local exposure
KOUT_CSA     : 0.9   : 1/day, local clearance (tear turnover + conjunctival absorption)
EC50_CSA     : 1.2   : au, exposure for half-maximal calcineurin/NFAT blockade
EMAX_CSA     : 0.75  : max fractional anti-inflammatory effect

//--- Lifitegrast 5% topical BID (Xiidra)
KOUT_LIF     : 1.3   : faster local washout than CsA
EC50_LIF     : 1.0
EMAX_LIF     : 0.65  : max fractional LFA-1/ICAM-1 adhesion blockade

//--- Loteprednol etabonate 0.25% topical QID short pulse (2-4 wk induction)
KOUT_LOT     : 2.0   : rapid local clearance (soft steroid ester)
EC50_LOT     : 0.8
EMAX_LOT     : 0.90  : max fractional GR-transrepression anti-inflammatory effect
K_IOP_RISK   : 0.004 : IOP-risk-score accrual rate per unit cumulative LOT exposure

//--- Perfluorohexyloctane (Miebo) topical QID — physical evaporation barrier, non-drug MoA
KOUT_PFHO    : 1.1
EC50_PFHO    : 1.0
EMAX_PFHO    : 0.55  : max fractional evaporation-rate reduction (monolayer film)

//--- Varenicline nasal spray BID (Tyrvaya) — nasal trigeminal parasympathetic reflex
KA_VARNAS    : 3.0   : 1/day, nasal mucosal absorption
KOUT_VARSYS  : 1.2   : trigeminal-reflex "effect compartment" turnover
EC50_VAR     : 0.6
EMAX_VAR     : 0.50  : max fractional reflex secretomotor stimulation

//--- Diquafosol 3% topical 6x/day (approved Japan/Korea) — P2Y2 secretagogue
KOUT_DQS     : 2.4   : very short local half-life, high dose frequency compensates
EC50_DQS     : 0.9
EMAX_DQS     : 0.45  : max fractional mucin+aqueous secretagogue effect

//--- Tear-film osmolarity
OSM_NORMAL   : 302   : mOsm/L, normal tear osmolarity
OSM_BASE_ADD : 22    : mOsm/L, baseline elevation scale from MGD/ADDE severity
KOUT_OSM     : 0.45
SCALE_OSM_INFLAM: 10  : mOsm/L, vicious-cycle feed-forward from inflammation

//--- Lipid layer / evaporation
LIPID_NORMAL : 100   : a.u., healthy meibum lipid-layer quality
KOUT_LIPID   : 0.20
SCALE_EVAP_LIPID: 1.0

//--- Aqueous production (Schirmer-correlated)
AQP_NORMAL   : 12    : mm/5min-equivalent secretory-drive units (healthy)
KOUT_AQP     : 0.12  : slow — reflects weeks-scale lacrimal-gland recovery
SCALE_AQP_INFLAM: 0.55 : fractional chronic-inflammation suppression of AQP

//--- Mucin / goblet-cell density
MUCIN_NORMAL : 100
KOUT_MUCIN   : 0.15
SCALE_MUCIN_INFLAM: 0.5

//--- Dendritic-cell activation (innate->adaptive bridge)
DCACT_BASE   : 20
KOUT_DCACT   : 0.35
SCALE_DCACT_OSM: 1.4

//--- IL-17A / Th17 effector tone
IL17_BASE    : 15
KOUT_IL17    : 0.18  : slow — reflects weeks-scale adaptive immune remodeling
SCALE_IL17_DC: 1.6
AUTOIMMUNE_IL17_MULT: 1.8

//--- MMP-9 biomarker
MMP9_BASE    : 20    : ng/mL-equivalent
KOUT_MMP9    : 0.55
SCALE_MMP9_IL17: 2.2
SCALE_MMP9_OSM : 0.9

//--- Epithelial barrier integrity
BARRIER_NORMAL: 100
KOUT_BARRIER : 0.30
SCALE_BARRIER_MMP9: 0.55
SCALE_BARRIER_OSM: 0.35

//--- Corneal sub-basal nerve density (very slow turnover, months-scale)
NERVE_NORMAL : 28    : fibers/mm^2-equivalent
KOUT_NERVE   : 0.012
SCALE_NERVE_CHRONIC: 6.0
REFRACTIVE_NERVE_DROP: 0.40

//--- Neuropathic pain score
PAIN_BASE    : 0.5
KOUT_PAIN    : 0.25
SCALE_PAIN_NERVE: 5.0
SCALE_PAIN_INFLAM: 0.04

//--- Clinical endpoint transduction
TBUT_MAX     : 12    : s, normal TBUT
KOUT_TBUT    : 0.40
SCHIRMER_SCALE: 1.0
KOUT_SCHIRMER: 0.20
CSTAIN_MAX   : 15    : NEI corneal staining scale
KOUT_CSTAIN  : 0.35
KOUT_OSDI    : 0.15
W_OSDI_TBUT  : 2.6
W_OSDI_CSTAIN: 2.0
W_OSDI_PAIN  : 5.0
W_OSDI_OSM   : 0.5

[CMT] @annotated
CSA_TF     : Cyclosporine local ocular-surface exposure (au)
LIF_TF     : Lifitegrast local ocular-surface exposure (au)
LOT_TF     : Loteprednol local ocular-surface exposure (au)
LOT_AUC    : Cumulative loteprednol exposure -> IOP-risk driver (au*day)
PFHO_TF    : Perfluorohexyloctane film exposure (au)
VAR_NAS    : Varenicline nasal mucosal depot (au)
VAR_SYS    : Varenicline trigeminal-reflex effect compartment (au)
DQS_TF     : Diquafosol local ocular-surface exposure (au)
OSM        : Tear-film osmolarity (mOsm/L)
LIPID      : Lipid-layer quality (a.u., 0-100, higher=better)
AQP        : Aqueous tear production drive (a.u., Schirmer-correlated)
MUCIN      : Goblet-cell/mucin density (a.u., 0-100)
DCACT      : Dendritic-cell activation tone (a.u.)
IL17       : IL-17A/Th17 effector tone (a.u.)
MMP9       : Tear-film MMP-9 (ng/mL-equivalent)
BARRIER    : Epithelial barrier integrity (a.u., 0-100, higher=better)
NERVE      : Corneal sub-basal nerve density (fibers/mm^2-equivalent)
PAIN       : Neuropathic ocular pain score (0-10)
TBUT       : Tear break-up time (s)
SCHIRMER   : Schirmer I test (mm/5min)
CSTAIN     : Corneal fluorescein staining score (NEI, 0-15)
OSDI       : OSDI symptom score (0-100)

[MAIN]
CSA_TF_0 = 0; LIF_TF_0 = 0; LOT_TF_0 = 0; LOT_AUC_0 = 0; PFHO_TF_0 = 0;
VAR_NAS_0 = 0; VAR_SYS_0 = 0; DQS_TF_0 = 0;

double sev = MGD_SEV + ADDE_SEV;
if (sev > 1.3) sev = 1.3;

OSM_0     = OSM_NORMAL + OSM_BASE_ADD * sev;
LIPID_0   = LIPID_NORMAL * (1 - 0.75*MGD_SEV);
AQP_0     = AQP_NORMAL * (1 - 0.80*ADDE_SEV);
MUCIN_0   = MUCIN_NORMAL * (1 - 0.45*sev);
DCACT_0   = DCACT_BASE * (1 + 1.2*sev);
IL17_0    = IL17_BASE * (1 + 1.2*sev) * (AUTOIMMUNE>0 ? AUTOIMMUNE_IL17_MULT : 1.0);
MMP9_0    = MMP9_BASE * (1 + 1.5*sev);
BARRIER_0 = BARRIER_NORMAL * (1 - 0.40*sev);
NERVE_0   = NERVE_NORMAL * (1 - REFRACTIVE_SURG*REFRACTIVE_NERVE_DROP) * (1 - 0.25*sev);
PAIN_0    = PAIN_BASE + 2.0*sev;
TBUT_0    = TBUT_MAX * (1 - 0.65*sev);
SCHIRMER_0= SCHIRMER_SCALE * AQP_0;
CSTAIN_0  = CSTAIN_MAX * 0.25 * sev * 2;
if (CSTAIN_0 > CSTAIN_MAX) CSTAIN_0 = CSTAIN_MAX;
OSDI_0    = BASE_OSDI;

[ODE]
// ---------- Local/topical drug exposure kinetics (dosed via bolus events) ----------
dxdt_CSA_TF  = -KOUT_CSA*CSA_TF;
dxdt_LIF_TF  = -KOUT_LIF*LIF_TF;
dxdt_LOT_TF  = -KOUT_LOT*LOT_TF;
dxdt_LOT_AUC = LOT_TF;
dxdt_PFHO_TF = -KOUT_PFHO*PFHO_TF;
dxdt_VAR_NAS = -KA_VARNAS*VAR_NAS;
dxdt_VAR_SYS = KA_VARNAS*VAR_NAS - KOUT_VARSYS*VAR_SYS;
dxdt_DQS_TF  = -KOUT_DQS*DQS_TF;

// ---------- Drug effect (Emax) terms ----------
double CsA_eff  = EMAX_CSA  * CSA_TF /(EC50_CSA  + CSA_TF);
double Lif_eff  = EMAX_LIF  * LIF_TF /(EC50_LIF  + LIF_TF);
double Lot_eff  = EMAX_LOT  * LOT_TF /(EC50_LOT  + LOT_TF);
double Pfho_eff = EMAX_PFHO * PFHO_TF/(EC50_PFHO + PFHO_TF);
double Var_eff  = EMAX_VAR  * VAR_SYS/(EC50_VAR  + VAR_SYS);
double Dqs_eff  = EMAX_DQS  * DQS_TF /(EC50_DQS  + DQS_TF);

double ANTIINFLAM_fx = CsA_eff + Lif_eff + Lot_eff;   // combinable, not hard-capped (additive weak overlap)
if (ANTIINFLAM_fx > 0.97) ANTIINFLAM_fx = 0.97;

// ---------- Lipid layer / evaporation ----------
double LIPID_target = LIPID_NORMAL * (1 - 0.75*MGD_SEV);
dxdt_LIPID = KOUT_LIPID * (LIPID_target - LIPID);
double EvapRate = SCALE_EVAP_LIPID * (1 - LIPID/LIPID_NORMAL) * (1 - Pfho_eff);
if (EvapRate < 0) EvapRate = 0;

// ---------- Dendritic-cell activation (hyperosmolar-driven, drug-suppressed) ----------
double DCACT_target = DCACT_BASE*(1+1.2*sev) + SCALE_DCACT_OSM*(OSM - OSM_NORMAL) * (1 - CsA_eff - 0.6*Lif_eff);
if (DCACT_target < 0) DCACT_target = 0;
dxdt_DCACT = KOUT_DCACT * (DCACT_target - DCACT);

// ---------- IL-17A / Th17 tone ----------
double autoimmune_mult = (AUTOIMMUNE>0 ? AUTOIMMUNE_IL17_MULT : 1.0);
double IL17_target = (IL17_BASE + SCALE_IL17_DC*DCACT) * autoimmune_mult * (1 - 0.65*CsA_eff - 0.30*Lot_eff);
if (IL17_target < 0) IL17_target = 0;
dxdt_IL17 = KOUT_IL17 * (IL17_target - IL17);

// ---------- MMP-9 biomarker ----------
double MMP9_target = MMP9_BASE + SCALE_MMP9_IL17*(IL17/IL17_BASE) + SCALE_MMP9_OSM*(OSM-OSM_NORMAL)/10.0;
MMP9_target = MMP9_target * (1 - 0.55*Lot_eff - 0.30*CsA_eff - 0.25*Lif_eff);
if (MMP9_target < 0) MMP9_target = 0;
dxdt_MMP9 = KOUT_MMP9 * (MMP9_target - MMP9);

// ---------- Aqueous production (chronic immune-mediated suppression, drug-reversible) ----------
double chronic_immune_norm = IL17/(IL17_BASE + 1e-6);
double AQP_target = AQP_NORMAL*(1 - 0.80*ADDE_SEV) * (1 - SCALE_AQP_INFLAM*(chronic_immune_norm-1)/3.0)
                     + AQP_NORMAL * (Var_eff*0.6 + Dqs_eff*0.4);
if (AQP_target < 0.2) AQP_target = 0.2;
dxdt_AQP = KOUT_AQP * (AQP_target - AQP);

// ---------- Mucin / goblet-cell density ----------
double MUCIN_target = MUCIN_NORMAL*(1 - 0.45*sev) * (1 - SCALE_MUCIN_INFLAM*(chronic_immune_norm-1)/3.0)
                       + MUCIN_NORMAL * (Dqs_eff*0.5 + Var_eff*0.2);
if (MUCIN_target < 0) MUCIN_target = 0;
if (MUCIN_target > MUCIN_NORMAL) MUCIN_target = MUCIN_NORMAL;
dxdt_MUCIN = KOUT_MUCIN * (MUCIN_target - MUCIN);

// ---------- Tear-film osmolarity (vicious-cycle feed-forward from inflammation) ----------
double OSM_target = OSM_NORMAL + OSM_BASE_ADD*sev
                     + EvapRate*8.0
                     + SCALE_OSM_INFLAM * (chronic_immune_norm - 1) / 3.0
                     - (MUCIN/MUCIN_NORMAL - 1)*6.0;
dxdt_OSM = KOUT_OSM * (OSM_target - OSM);

// ---------- Epithelial barrier integrity ----------
double BARRIER_target = BARRIER_NORMAL - SCALE_BARRIER_MMP9*(MMP9/MMP9_BASE - 1)*20
                         - SCALE_BARRIER_OSM*(OSM - OSM_NORMAL);
if (BARRIER_target < 0) BARRIER_target = 0;
if (BARRIER_target > BARRIER_NORMAL) BARRIER_target = BARRIER_NORMAL;
dxdt_BARRIER = KOUT_BARRIER * (BARRIER_target - BARRIER);

// ---------- Corneal nerve density (very slow chronic attrition / partial recovery) ----------
double NERVE_target = NERVE_NORMAL*(1 - REFRACTIVE_SURG*REFRACTIVE_NERVE_DROP)
                       - SCALE_NERVE_CHRONIC*(chronic_immune_norm - 1);
if (NERVE_target < 2) NERVE_target = 2;
dxdt_NERVE = KOUT_NERVE * (NERVE_target - NERVE);

// ---------- Neuropathic pain ----------
double PAIN_target = PAIN_BASE + SCALE_PAIN_NERVE*(1 - NERVE/NERVE_NORMAL) + SCALE_PAIN_INFLAM*(OSM-OSM_NORMAL);
if (PAIN_target < 0) PAIN_target = 0;
if (PAIN_target > 10) PAIN_target = 10;
dxdt_PAIN = KOUT_PAIN * (PAIN_target - PAIN);

// ---------- Tear break-up time ----------
double TBUT_target = TBUT_MAX * (0.35*LIPID/LIPID_NORMAL + 0.35*MUCIN/MUCIN_NORMAL + 0.30*AQP/AQP_NORMAL);
if (TBUT_target > TBUT_MAX) TBUT_target = TBUT_MAX;
dxdt_TBUT = KOUT_TBUT * (TBUT_target - TBUT);

// ---------- Schirmer test ----------
double SCHIRMER_target = SCHIRMER_SCALE * AQP;
dxdt_SCHIRMER = KOUT_SCHIRMER * (SCHIRMER_target - SCHIRMER);

// ---------- Corneal staining ----------
double CSTAIN_target = CSTAIN_MAX * (1 - BARRIER/BARRIER_NORMAL);
if (CSTAIN_target < 0) CSTAIN_target = 0;
if (CSTAIN_target > CSTAIN_MAX) CSTAIN_target = CSTAIN_MAX;
dxdt_CSTAIN = KOUT_CSTAIN * (CSTAIN_target - CSTAIN);

// ---------- OSDI composite symptom score ----------
double OSDI_target = W_OSDI_TBUT*(TBUT_MAX - TBUT) + W_OSDI_CSTAIN*CSTAIN
                      + W_OSDI_PAIN*PAIN + W_OSDI_OSM*(OSM-OSM_NORMAL);
if (OSDI_target < 0) OSDI_target = 0;
if (OSDI_target > 100) OSDI_target = 100;
dxdt_OSDI = KOUT_OSDI * (OSDI_target - OSDI);

[TABLE]
capture IOP_risk_score   = K_IOP_RISK * LOT_AUC;
capture Evap_rate        = EvapRate;
capture CsA_effect       = CsA_eff;
capture Lifitegrast_effect = Lif_eff;
capture Loteprednol_effect = Lot_eff;
capture PFHO_effect      = Pfho_eff;
capture Varenicline_effect = Var_eff;
capture Diquafosol_effect = Dqs_eff;
capture Tear_osmolarity  = OSM;
capture Lipid_layer      = LIPID;
capture Aqueous_drive    = AQP;
capture Mucin_density    = MUCIN;
capture DC_activation    = DCACT;
capture IL17_tone        = IL17;
capture MMP9_biomarker   = MMP9;
capture Barrier_integrity= BARRIER;
capture Nerve_density    = NERVE;
capture Neuropathic_pain = PAIN;
capture TBUT_s           = TBUT;
capture Schirmer_mm      = SCHIRMER;
capture Corneal_staining = CSTAIN;
capture OSDI_score       = OSDI;

[CAPTURE]
IOP_risk_score Evap_rate CsA_effect Lifitegrast_effect Loteprednol_effect
PFHO_effect Varenicline_effect Diquafosol_effect
Tear_osmolarity Lipid_layer Aqueous_drive Mucin_density
DC_activation IL17_tone MMP9_biomarker Barrier_integrity
Nerve_density Neuropathic_pain TBUT_s Schirmer_mm Corneal_staining OSDI_score


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("ded_mrgsolve_model.R")
##
##  # ---------- 9 prebuilt scenarios ----------
##
##  DED_simulate_scenarios <- function(end_d = 84) {
##
##    sc <- list(
##      "1. Untreated natural history" =
##        ev(amt=0, cmt="CSA_TF", time=0),
##
##      "2. Cyclosporine 0.05% BID (Restasis)" =
##        ev(amt=1.0, cmt="CSA_TF", ii=0.5, addl=2*end_d),
##
##      "3. Cyclosporine 0.09% BID (Cequa, higher local exposure)" =
##        ev(amt=1.6, cmt="CSA_TF", ii=0.5, addl=2*end_d),
##
##      "4. Lifitegrast 5% BID (Xiidra)" =
##        ev(amt=1.2, cmt="LIF_TF", ii=0.5, addl=2*end_d),
##
##      "5. Loteprednol 0.25% QID x 2wk induction, then stop" =
##        ev(amt=1.0, cmt="LOT_TF", ii=0.25, addl=4*14-1),
##
##      "6. Perfluorohexyloctane QID (Miebo)" =
##        ev(amt=1.3, cmt="PFHO_TF", ii=0.25, addl=4*end_d),
##
##      "7. Varenicline nasal spray BID (Tyrvaya)" =
##        ev(amt=1.0, cmt="VAR_NAS", ii=0.5, addl=2*end_d),
##
##      "8. Diquafosol 3% 6x/day (Japan/Korea approved)" =
##        ev(amt=0.8, cmt="DQS_TF", ii=1/6, addl=6*end_d),
##
##      "9. Combination: Loteprednol 2wk induction + Cyclosporine 0.05% maintenance" =
##        seq(ev(amt=1.0, cmt="LOT_TF", ii=0.25, addl=4*14-1),
##            ev(amt=1.0, cmt="CSA_TF", ii=0.5, addl=2*end_d, time=0))
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      mod %>% mrgsim(e, end=end_d, delta=1) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Cyclosporine 0.05% BID (Sall 2000; ATP III) : Schirmer +>=10mm responder ~15%
##  #   vs ~5% vehicle at 6mo; CFS improvement by mo 3-6 (slow onset, modeled via
##  #   low KOUT_AQP/KOUT_NERVE).
##  # Cyclosporine 0.09% (Cequa, Tauber 2018)     : Schirmer responder ~17% at wk12,
##  #   higher aqueous concentration -> larger EC50_CSA occupancy vs 0.05%.
##  # Lifitegrast (OPUS-2/3)                      : CFS -0.9 to -1.1 vs vehicle at
##  #   wk6 (faster onset than CsA, modeled via higher KOUT_LIF / faster DC effect).
##  # Loteprednol 0.25% QID (short pulse)          : OSDI/CFS improvement within
##  #   2wk (fastest onset); IOP elevation risk tracked via LOT_AUC (do not use
##  #   >2-4wk continuously in practice).
##  # Perfluorohexyloctane (GOBI/MOJAVE)           : TSS -7 to -10 vs saline, CFS
##  #   -0.5 to -0.9 at wk8; acts purely via evaporation-barrier (Pfho_eff on
##  #   EvapRate), no direct anti-inflammatory arm.
##  # Varenicline nasal spray (ONSET-1/2)          : Schirmer +~4-5mm at wk4 vs
##  #   placebo spray; acts via trigeminal reflex (Var_eff on AQP/MUCIN), not
##  #   anti-inflammatory.
##  # Diquafosol 3% (Japan/Korea trials)           : TBUT +~1.5-2s, fluorescein
##  #   staining -1 to -2 at wk2-4; acts via P2Y2 mucin+aqueous secretagogue.
##  # TFOS DEWS II vicious-cycle framework          : hyperosmolarity <-> innate/
##  #   adaptive inflammation <-> epithelial damage feed-forward loop reproduced
##  #   via OSM_target's dependence on chronic_immune_norm and MUCIN.
##
##  # ---------- Quick sanity plots ----------
##  # df <- DED_simulate_scenarios(84)
##  # ggplot(df, aes(time, OSDI_score, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, TBUT_s, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Corneal_staining, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Schirmer_mm, colour=scenario)) + geom_line()
