##  Chronic Insomnia Disorder (CID) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Chronic insomnia disorder (DSM-5-TR / ICSD-3-TR) — difficulty
##             initiating or maintaining sleep, with daytime consequences,
##             >=3 nights/week for >=3 months, despite adequate opportunity.
##
##             The organising idea of this model is that insomnia is NOT a
##             deficiency of sleep drive. Process S and Process C are close to
##             normal in most patients. What is abnormal is a THIRD process —
##             24-hour HYPERAROUSAL (cortical beta/gamma intrusion, elevated
##             whole-brain metabolic rate, flattened evening cortisol nadir,
##             raised MSNA and reduced HRV) — which raises the wake side of the
##             VLPO/ascending-arousal flip-flop switch. Hypnotics push the
##             switch from the other side. They do not touch arousal, which is
##             why their effect disappears the night they are stopped.
##
##             The model therefore closes the loop that actually makes the
##             disease chronic (Spielman's 3-P model):
##
##                poor night -> lie in bed longer (TIB up) -> Process S is
##                diluted across more hours -> sleep efficiency falls further
##                -> more time awake in bed -> the bed is conditioned as a
##                wake cue (COND up) and sleep effort rises -> arousal rises
##                -> poorer night
##
##             CBT-I is the only intervention in this model that enters that
##             loop: sleep restriction re-concentrates S, stimulus control
##             extinguishes COND, cognitive therapy lowers DBAS, and the
##             gains therefore persist after treatment stops. Every drug in
##             this model acts distal to the loop and its benefit decays with
##             its concentration. Reproducing that asymmetry — same acute
##             effect size, completely different behaviour at 12 months — is
##             the model's main falsifiable claim.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.0; developed and validated under the version
##             reported by the header printed when this file is sourced)
##
##  Scope    : 61 ODE compartments —
##             * PK (23): zolpidem, eszopiclone, suvorexant, lemborexant,
##                     daridorexant, ramelteon (+ active metabolite M-II),
##                     exogenous melatonin, low-dose doxepin, trazodone,
##                     caffeine, ethanol (Michaelis-Menten).
##             * Circadian (5): endogenous pineal melatonin, circadian phase
##                     shift PHI, core body temperature deviation, plus the
##                     light/PRC machinery driving them.
##             * Two-process core (2): Process S, extracellular adenosine.
##             * Flip-flop (3): LC noradrenaline tone, TMN histamine tone,
##                     orexin-A tone.
##             * Hyperarousal & HPA (5): AROUSAL, precipitating stressor,
##                     CRH, ACTH, cortisol.
##             * Perpetuating loop (4): conditioned arousal, sleep effort,
##                     dysfunctional beliefs (DBAS), time-in-bed.
##             * Drug adaptation (3): BzRA tolerance, withdrawal/rebound,
##                     ethanol second-half rebound.
##             * Sleep measurement (10): onset flag, and running estimates of
##                     SOL, WASO, TST, SE, %N3, %REM, daytime sedation.
##             * Consequences (6): sleep-state misperception, ISI, depressive
##                     load, IL-6, glymphatic clearance debt, cumulative
##                     residual-sedation exposure.
##             * Cumulative counters (4): SOL, WASO, TST, awakenings.
##
##  Time     : HOURS. Clock time of day = TIME mod 24, so TIME = 0 is midnight
##             on day 1. Default horizon 24 h * 84 d = 2016 h (12 weeks), the
##             standard endpoint window for hypnotic and CBT-I trials.
##
##  Units    : concentrations mg/L (= ug/mL) except melatonin, which is
##             carried in pg/mL because the endogenous nocturnal peak
##             (~60 pg/mL) and a 2 mg exogenous dose (~1-4 ng/mL) differ by
##             nearly two orders of magnitude and must share one receptor.
##             Sleep quantities are minutes; TIB is hours; ISI is 0-28.
##  ============================================================================

suppressPackageStartupMessages({
  library(mrgsolve)
  library(dplyr)
})

## ============================================================================
##  MODEL CODE
## ============================================================================

ins_code <- '
$PROB
# Chronic Insomnia Disorder QSP model (61 ODEs)
Two-process core x flip-flop switch x 24-h hyperarousal x 3-P perpetuating loop,
with PK/PD for BzRA, DORA, melatonergic, H1-antagonist and serotonergic
hypnotics, plus caffeine, ethanol, light and CBT-I.

$PARAM @annotated
// ---------------------------------------------------------------- schedule --
WAKET   : 7.0   : Habitual rise time, clock hour (h)
TIB0    : 8.5   : Initial time in bed (h)
TIBMIN  : 5.0   : Floor on prescribed time in bed under SRT (h)
TIBMAX  : 9.3   : Ceiling on time in bed (h)
SHBED   : 0.12  : Smoothing width of the in-bed indicator (h)
NAPW    : 0     : Daytime nap opportunity flag (0/1)
NAPT0   : 14.0  : Nap window start, clock hour (h)
NAPDUR  : 1.0   : Nap window duration (h)

// ------------------------------------------------------------------- light --
LUXDAY  : 600   : Daytime indoor illuminance (lux)
LUXEVE  : 120   : Evening illuminance before bed, screens included (lux)
LUXBED  : 1     : Illuminance in bed (lux)
EVEHR   : 20.0  : Clock hour at which evening light replaces day light (h)
BLTON   : 0     : Morning bright-light therapy flag (0/1)
BLTLUX  : 8000  : Bright-light therapy illuminance (lux)
BLTT0   : 7.0   : Bright-light therapy start, clock hour (h)
BLTDUR  : 0.5   : Bright-light therapy duration (h)
LUX50   : 90    : Illuminance halving pineal melatonin synthesis (lux)
LUXREF  : 50    : Reference illuminance in the log light-input term (lux)

// --------------------------------------------------------------- circadian --
TAUINT  : 24.18 : Intrinsic circadian period (h)
AMPC    : 1.20  : Amplitude of the circadian alerting signal (-)
TPKC    : 18.5  : Clock hour of peak circadian alerting signal (h)
KLIGHT  : 0.055 : Light phase-shifting gain (h per h per log-lux)
KMELPH  : 0.010 : Melatonin phase-shifting gain (h per h per ng/mL)
KMELS   : 55.0  : Maximal pineal melatonin synthesis rate (pg/mL/h)
KMELE   : 0.92  : Melatonin elimination rate constant (1/h)
FMELAGE : 1.00  : Age factor on pineal melatonin output (-)
AMPT    : 0.42  : Amplitude of the circadian core-temperature rhythm (degC)
DROPT   : 0.25  : Sleep-dependent fall in core temperature (degC)
TAUCBT  : 1.5   : Time constant of core-temperature tracking (h)

// ------------------------------------------------------- two-process core --
SMAX    : 1.0   : Upper asymptote of Process S (-)
TAUR    : 18.2  : Rise time constant of Process S during wake (h)
TAUD    : 4.2   : Decay time constant of Process S during sleep (h)
KADOIN  : 0.50  : Adenosine accumulation rate during wake (1/h)
KADOOUT : 0.35  : Adenosine clearance rate constant (1/h)
KICAF   : 5.0   : Caffeine concentration halving adenosine action (mg/L)
WS      : 3.00  : Weight of Process S in the sleep drive (-)
WADO    : 0.55  : Weight of effective adenosine in the sleep drive (-)
WCBT    : 1.00  : Weight of falling core temperature in the sleep drive (-)
PULT    : 1.55  : Period of the NREM-REM ultradian cycle (h)
AULT    : 0.30  : Amplitude of the ultradian dip in sleep drive (-)
SLPMAX  : 0.965 : Ceiling on sleep probability, brief EEG arousals never scored asleep (-)
SWTH   : 0.50  : Sleep-switch threshold (-)
KSHARP  : 0.13  : Steepness of the sleep-switch sigmoid (-)

// ------------------------------------------------------ flip-flop switch ---
NE0     : 1.0   : Reference LC noradrenergic tone (-)
HA0     : 1.0   : Reference TMN histaminergic tone (-)
OX0     : 1.0   : Reference orexin-A tone (-)
TAUNE   : 0.35  : Time constant of noradrenergic tone (h)
TAUHA   : 0.35  : Time constant of histaminergic tone (h)
TAUOX   : 0.50  : Time constant of orexin tone (h)
NESLP   : 0.12  : Fractional noradrenergic tone during consolidated sleep (-)
HASLP   : 0.08  : Fractional histaminergic tone during consolidated sleep (-)
OXSLP   : 0.35  : Fractional orexin tone during consolidated sleep (-)
GOXNE   : 0.45  : Gain of orexin on noradrenergic tone (-)
GOXHA   : 0.60  : Gain of orexin on histaminergic tone (-)
WNE     : 0.42  : Weight of noradrenergic tone in the wake drive (-)
WHA     : 0.34  : Weight of histaminergic tone in the wake drive (-)
WOX     : 0.42  : Weight of orexin tone in the wake drive (-)

// ---------------------------------------------------------- hyperarousal ---
A0      : 0.30  : Constitutive arousal of a good sleeper (-)
TAUAR   : 0.8   : Time constant of the arousal state (h)
GCOND   : 0.34  : Gain of conditioned arousal on arousal, in bed only (-)
GSEFF   : 0.24  : Gain of sleep effort on arousal, in bed only (-)
GDBAS   : 0.20  : Gain of dysfunctional beliefs on arousal (-)
GCORT   : 0.30  : Gain of relative cortisol on arousal (-)
GSTR    : 0.65  : Gain of the precipitating stressor on arousal (-)
GREB    : 0.55  : Gain of BzRA withdrawal on arousal (-)
GDEP    : 0.30  : Gain of depressive load on arousal (-)
GETRB   : 0.30  : Gain of the ethanol second-half rebound on arousal (-)
GPAIN   : 0.40  : Gain of comorbid chronic pain on arousal (-)
GVMS    : 0.35  : Gain of comorbid vasomotor symptoms on arousal (-)
PAIN    : 0.0   : Comorbid chronic pain burden, 0-1 (-)
VMS     : 0.0   : Comorbid vasomotor symptom burden, 0-1 (-)
KSTRD   : 0.010 : Decay rate of the precipitating stressor (1/h)

// ------------------------------------------------------------- HPA axis ----
KINCRH  : 3.60  : CRH production rate (1/h)
KOUTCRH : 2.00  : CRH elimination rate constant (1/h)
KINACT  : 3.00  : ACTH production rate (1/h)
KOUTACT : 3.00  : ACTH elimination rate constant (1/h)
KINCOR  : 4.00  : Cortisol production rate (ug/dL/h)
KOUTCOR : 0.50  : Cortisol elimination rate constant (1/h)
IC50C   : 9.0   : Cortisol producing half-maximal negative feedback (ug/dL)
HILLC   : 2.0   : Hill coefficient of cortisol feedback (-)
CORT0   : 8.0   : Reference 24-h mean cortisol (ug/dL)
ASTR    : 0.80  : Gain of the stressor on CRH drive (-)
AARO    : 0.35  : Gain of arousal on CRH drive (-)
AMPCOR  : 0.85  : Amplitude of the circadian CRH drive (-)
TPKCOR  : 6.0   : Clock hour of peak circadian CRH drive (h)
FBGR    : 1.00  : Glucocorticoid-receptor feedback efficiency, <1 = resistance

// -------------------------------------------------- perpetuating 3-P loop --
CONDMAX : 1.20  : Ceiling on conditioned arousal (-)
KCIN    : 0.055 : Acquisition rate of conditioned arousal (1/h)
KCOUT   : 0.0025: Spontaneous extinction rate of conditioned arousal (1/h)
KCSTIM  : 0.003 : Extinction rate added by stimulus control (1/h)
KCEXT   : 0.010 : Extinction rate from sleeping in bed (1/h)
SEFF0   : 0.10  : Constitutive sleep effort (-)
TAUSE   : 48.0  : Time constant of sleep effort (h)
GSEDBAS : 0.35  : Gain of DBAS on sleep effort (-)
GSESOL  : 0.10  : Gain of running SOL on sleep effort (per h of SOL)
GSEMIND : 0.15  : Reduction of sleep effort by mindfulness/ACT (-)
DBAS0   : 0.15  : Constitutive dysfunctional-belief level (-)
TAUDB   : 120.0 : Time constant of dysfunctional beliefs (h)
GDBISI  : 0.35  : Gain of ISI on dysfunctional beliefs (-)
GDBCOG  : 0.18  : Reduction of DBAS by cognitive therapy (-)
KTIBUP  : 0.012 : Rate of prescribed TIB extension when SE exceeds target (1/h)
KTIBDN  : 0.030 : Rate of prescribed TIB reduction under SRT (1/h)
KTIBEXT : 0.0025 : Rate of maladaptive TIB extension when untreated (1/h)
KTIBREL : 0.0025 : Restoring rate of TIB toward the habitual value (1/h)
SETGT   : 0.87  : Sleep-efficiency target driving TIB titration (-)

// ------------------------------------------------------------------ CBT-I --
CBTION  : 0     : CBT-I assigned flag (0/1)
CBTIT0  : 1.0e6 : Time at which CBT-I starts (h)
CBTIRMP : 12.0  : Ramp time constant of CBT-I uptake (h)
USEINIT : 1     : Use the parameter-derived initial conditions (0/1)
WSRT    : 1.0   : Adherence weight, sleep restriction (0-1)
WSTIMC  : 1.0   : Adherence weight, stimulus control (0-1)
WCOGTH  : 1.0   : Adherence weight, cognitive restructuring (0-1)
WRELAX  : 1.0   : Adherence weight, relaxation training (0-1)
WMINDF  : 1.0   : Adherence weight, mindfulness / paradoxical intention (0-1)
GRELAX  : 0.03  : Reduction of arousal by relaxation training (-)

// -------------------------------------------------------------- BzRA PK/PD -
KAZOL   : 3.00  : Zolpidem absorption rate constant (1/h)
FZOL    : 0.70  : Zolpidem bioavailability, folded into V/F and CL/F (-)
VZOL    : 60.0  : Zolpidem apparent central volume V/F (L)
CLZOL   : 16.57 : Zolpidem apparent clearance CL/F (L/h)
KAESZ   : 1.60  : Eszopiclone absorption rate constant (1/h)
FESZ    : 0.80  : Eszopiclone bioavailability (-)
VESZ    : 112.5 : Eszopiclone apparent central volume V/F (L)
CLESZ   : 13.00 : Eszopiclone apparent clearance CL/F (L/h)
CYP3A   : 1.00  : CYP3A4 activity multiplier on CL (inhibitor <1, inducer >1)
EC50ZOL : 0.0525: Zolpidem concentration at half-maximal GABA-A effect (mg/L)
EC50ESZ : 0.0240: Eszopiclone concentration at half-maximal effect (mg/L)
EC50ETH : 0.80  : Ethanol concentration at half-maximal GABA-A effect (g/L)
EMAXBZ  : 1.15  : Maximal BzRA sleep-drive effect (-)
GADESZ  : 0.30  : Anxiolytic (alpha2/3) arousal reduction by eszopiclone (-)
KTOLIN  : 0.016 : BzRA tolerance acquisition rate (1/h)
KTOLOUT : 0.0035: BzRA tolerance loss rate (1/h)
TOLMAX  : 1.10  : Ceiling on BzRA tolerance (-)
OCCREF  : 0.28  : Occupancy above which no withdrawal drive is generated (-)
TAUWDR  : 22.0  : Time constant of the withdrawal/rebound state (h)

// -------------------------------------------------------------- DORA PK/PD -
KASUV   : 0.60  : Suvorexant absorption rate constant (1/h)
FSUV    : 0.82  : Suvorexant bioavailability (-)
VSUV    : 59.8  : Suvorexant apparent central volume V/F (L)
CLSUV   : 3.45  : Suvorexant apparent clearance CL/F (L/h)
KALEM   : 1.60  : Lemborexant absorption rate constant (1/h)
FLEM    : 0.80  : Lemborexant bioavailability (-)
VLEM    : 250.0 : Lemborexant apparent central volume V/F (L)
CLLEM   : 10.20 : Lemborexant apparent clearance CL/F (L/h)
KADAR   : 1.60  : Daridorexant absorption rate constant (1/h)
FDAR    : 0.62  : Daridorexant bioavailability (-)
VDAR    : 64.5  : Daridorexant apparent central volume V/F (L)
CLDAR   : 5.65  : Daridorexant apparent clearance CL/F (L/h)
EC50SUV : 0.1804: Suvorexant concentration at 50% orexin-receptor block (mg/L)
EC50LEM : 0.0180: Lemborexant concentration at 50% block (mg/L)
EC50DAR : 0.2604: Daridorexant concentration at 50% block (mg/L)

// ----------------------------------------- melatonergic / H1 / 5-HT2A PK/PD -
KARAM   : 2.00  : Ramelteon absorption rate constant (1/h)
FRAM    : 0.020 : Ramelteon bioavailability (-)
VRAM    : 3700  : Ramelteon apparent central volume V/F (L)
CLRAM   : 1710  : Ramelteon apparent clearance CL/F (L/h)
FMM2    : 1.00  : Fraction of ramelteon converted to the active M-II (-)
CLRM2   : 32.30 : M-II apparent clearance (L/h)
VRM2    : 140.0 : M-II apparent volume (L)
KAMEL   : 3.00  : Exogenous melatonin absorption rate constant, IR (1/h)
FMEL    : 0.10  : Exogenous melatonin bioavailability (-)
VMEL    : 350.0 : Exogenous melatonin apparent volume V/F (L)
CLMEL   : 323.0 : Exogenous melatonin apparent clearance CL/F (L/h)
EC50MLE : 45.0  : Endogenous melatonin at half-maximal MT effect (pg/mL)
EC50MLX : 280.0  : Exogenous melatonin at half-maximal MT effect (pg/mL)
EC50RAM : 1.5e-3: Ramelteon at half-maximal MT effect (mg/L)
EC50RM2 : 0.0500: M-II at half-maximal MT effect (mg/L)
EMAXMT  : 0.62  : Maximal melatonergic sleep-drive effect (-)
KADOX   : 0.35  : Doxepin absorption rate constant (1/h)
FDOX    : 0.30  : Doxepin bioavailability (-)
VDOX    : 4667  : Doxepin apparent central volume V/F (L)
CLDOX   : 215.7 : Doxepin apparent clearance CL/F (L/h)
EC50DOX : 3.3e-4: Doxepin at 50% H1 blockade (mg/L)
KATRZ   : 1.50  : Trazodone absorption rate constant (1/h)
FTRZ    : 0.80  : Trazodone bioavailability (-)
VTRZ    : 105.0 : Trazodone apparent central volume V/F (L)
CLTRZ   : 10.40 : Trazodone apparent clearance CL/F (L/h)
EC50TZH : 1.500 : Trazodone at 50% H1 blockade (mg/L)
EC50TZ5 : 0.750 : Trazodone at 50% 5-HT2A blockade (mg/L)
EC50TZA : 1.120 : Trazodone at 50% alpha1 blockade (mg/L)
E5HT    : 0.45  : Sleep-drive effect of full 5-HT2A blockade (-)
GADTRZ  : 0.30  : Arousal reduction by 5-HT2A blockade (-)
GADDOX  : 0.18  : Arousal reduction by H1 blockade (-)
GBPON   : 0     : Gabapentinoid co-treatment flag (0/1)

// --------------------------------------------------- caffeine and ethanol --
KACAF   : 4.00  : Caffeine absorption rate constant (1/h)
FCAF    : 1.00  : Caffeine bioavailability (-)
VCAF    : 36.0  : Caffeine central volume (L)
CLCAF   : 5.00  : Caffeine clearance (L/h)
KAETH   : 3.00  : Ethanol absorption rate constant (1/h)
VETH    : 42.0  : Ethanol distribution volume (L)
VMETH   : 6.30  : Ethanol Michaelis-Menten maximal elimination (g/h)
KMETH   : 0.05  : Ethanol Michaelis constant (g/L)
KETIN   : 0.45  : Build-up rate of the ethanol rebound state (1/h)
KETOUT  : 0.16  : Decay rate of the ethanol rebound state (1/h)
GET2    : 0.55  : Suppression of ethanol rebound by residual ethanol (-)

// ------------------------------------------------ sleep architecture -------
PN3MAX  : 0.42  : Ceiling on the N3 fraction of sleep (-)
KSN3    : 0.30  : Process S at half-maximal N3 fraction (-)
PREMAX  : 0.32  : Ceiling on the REM fraction of sleep (-)
KSREM   : 0.35  : Process S at half-suppression of REM (-)
FN3AGE  : 1.00  : Age factor on slow-wave sleep (-)
GN35HT  : 0.35  : Increase in N3 by 5-HT2A blockade (-)
GN3GBP  : 0.25  : Increase in N3 by gabapentinoids (-)
GN3BZ   : 0.22  : Suppression of N3 by BzRA (-)
GREDOR  : 0.30  : Increase in REM by orexin-receptor blockade (-)
GREBZ   : 0.18  : Suppression of REM by BzRA (-)
GRETRZ  : 0.25  : Suppression of REM by 5-HT2A blockade (-)
GREETH  : 0.45  : Suppression of REM by ethanol (-)
MAWD    : 0.18  : Mean duration of a nocturnal awakening (h)

// -------------------------------------------------- outcome integration ----
TAUEW   : 84.0  : Averaging time constant of the running sleep metrics (h)
TSTNEED : 450.0 : Individual sleep need (min)
MISP0   : 0.05  : Constitutive sleep-state misperception (-)
GMIAR   : 0.28  : Gain of arousal on misperception (-)
GMIFR   : 0.22  : Gain of fragmentation on misperception (-)
GMICOG  : 0.35  : Reduction of misperception by cognitive therapy (-)
TAUMI   : 240.0 : Time constant of misperception (h)
MISPS   : 1.30  : Scaling of misperception onto subjective SOL and WASO (-)
ASOL    : 0.063 : ISI weight on subjective SOL (per min)
AWASO   : 0.048 : ISI weight on subjective WASO (per min)
ATST    : 0.024 : ISI weight on the subjective sleep-duration deficit (per min)
ADBAS   : 3.70  : ISI weight on dysfunctional beliefs (-)
ADAY    : 4.10  : ISI weight on daytime impairment (-)
AAR     : 1.30  : ISI weight on arousal (-)
TAUISI  : 130.0 : Time constant of the Insomnia Severity Index (h)
DEP0    : 0.10  : Constitutive depressive load (-)
GDEPISI : 0.75  : Gain of ISI on depressive load (-)
TAUDEP  : 400.0 : Time constant of depressive load (h)
IL60    : 1.20  : Reference IL-6 (pg/mL)
GILTST  : 0.90  : Gain of sleep-duration deficit on IL-6 (-)
GILCOR  : 0.45  : Gain of relative cortisol on IL-6 (-)
TAUIL   : 60.0  : Time constant of IL-6 (h)
KGIN    : 0.020 : Accrual rate of glymphatic clearance debt (1/h)
KGOUT   : 0.010 : Clearance rate of glymphatic debt (1/h)
N3REF   : 85.0  : Reference nightly N3 minutes (min)

$CMT @annotated
// --- PK ---
ZOLD  : Zolpidem absorption compartment (mg)
ZOLC  : Zolpidem central compartment (mg)
ESZD  : Eszopiclone absorption compartment (mg)
ESZC  : Eszopiclone central compartment (mg)
SUVD  : Suvorexant absorption compartment (mg)
SUVC  : Suvorexant central compartment (mg)
LEMD  : Lemborexant absorption compartment (mg)
LEMC  : Lemborexant central compartment (mg)
DARD  : Daridorexant absorption compartment (mg)
DARC  : Daridorexant central compartment (mg)
RAMD  : Ramelteon absorption compartment (mg)
RAMC  : Ramelteon central compartment (mg)
RAMM  : Ramelteon M-II metabolite compartment (mg)
MELD  : Exogenous melatonin absorption compartment (mg)
MELC  : Exogenous melatonin central compartment (mg)
DOXD  : Doxepin absorption compartment (mg)
DOXC  : Doxepin central compartment (mg)
TRZD  : Trazodone absorption compartment (mg)
TRZC  : Trazodone central compartment (mg)
CAFD  : Caffeine absorption compartment (mg)
CAFC  : Caffeine central compartment (mg)
ETHD  : Ethanol absorption compartment (g)
ETHC  : Ethanol central compartment (g)
// --- circadian ---
MELP  : Endogenous pineal melatonin (pg/mL)
PHI   : Circadian phase shift, positive = delay (h)
CBTD  : Core body temperature deviation (degC)
// --- two-process core ---
S     : Process S homeostatic sleep pressure (-)
ADO   : Extracellular adenosine (-)
// --- ultradian NREM-REM oscillator ---
ULTA  : Ultradian oscillator, cosine component (-)
ULTB  : Ultradian oscillator, sine component (-)
// --- flip-flop ---
NE    : LC noradrenergic tone (-)
HA    : TMN histaminergic tone (-)
OXA   : Orexin-A tone (-)
// --- arousal and HPA ---
AROU  : Hyperarousal state (-)
STR   : Precipitating stressor (-)
CRH   : CRH (-)
ACTH  : ACTH (-)
CORT  : Cortisol (ug/dL)
// --- perpetuating loop ---
COND  : Conditioned arousal to the bed (-)
SEFF  : Sleep effort (-)
DBAS  : Dysfunctional beliefs about sleep (-)
TIBS  : Time in bed actually spent or prescribed (h)
// --- drug adaptation ---
TOLB  : BzRA tolerance (-)
WDR   : BzRA withdrawal / rebound state (-)
ETRB  : Ethanol second-half rebound state (-)
// --- sleep measurement ---
ONS   : Persistent-sleep-onset indicator (-)
SOLBAR: Running daily sleep-onset latency (min/night)
WASOBR: Running daily wake after sleep onset (min/night)
TSTBAR: Running daily total sleep time (min/night)
SEBAR : Running sleep efficiency (-)
N3BAR : Running nightly N3 minutes (min/night)
REMBAR: Running nightly REM minutes (min/night)
RESBAR: Running daytime residual sedation index (-)
// --- consequences ---
MISP  : Sleep-state misperception (-)
ISI   : Insomnia Severity Index (0-28)
DEP   : Depressive symptom load (-)
IL6   : Interleukin-6 (pg/mL)
GLYM  : Glymphatic clearance debt (-)
// --- cumulative counters ---
SOLCUM : Cumulative sleep-onset latency (min)
WASOCM : Cumulative wake after sleep onset (min)
TSTCUM : Cumulative total sleep time (min)
NAWCUM : Cumulative number of awakenings (-)
RESCUM : Cumulative residual-sedation exposure (min)

$GLOBAL
#define TWOPI 6.283185307179586

// Smooth in-window indicator on a 24-h circle. Handles both the wrapping
// case (bedtime after midnight boundary) and the non-wrapping case, and is
// continuous as the window edge crosses midnight.
double inwin(double tod, double t0, double t1, double sh) {
  double a = 1.0/(1.0 + exp(-(tod - t0)/sh));
  double b = 1.0/(1.0 + exp(-(tod - t1)/sh));
  if (t0 > t1) {                       // window wraps midnight
    double u = a + (1.0 - b) - a*(1.0 - b);
    return u;
  }
  return a*(1.0 - b);
}

double clamp01(double x, double lo, double hi) {
  if (x < lo) return lo;
  if (x > hi) return hi;
  return x;
}

$MAIN
// Parameter-derived initial conditions. They are applied only when USEINIT is
// 1, so that a simulation can be started from the end state of a lead-in run
// (the $MAIN block would otherwise overwrite anything passed to init()).
if (USEINIT > 0.5) {
  S_0      = 0.55;
  ULTA_0   = -1.0;
  ULTB_0   = 0.0;
  ADO_0    = 1.00;
  MELP_0   = 5.0;
  NE_0     = 1.00;
  HA_0     = 1.00;
  OXA_0    = 1.00;
  AROU_0   = A0;
  CRH_0    = 1.00;
  ACTH_0   = 1.00;
  CORT_0   = CORT0;
  TIBS_0   = TIB0;
  DBAS_0   = DBAS0;
  SEFF_0   = SEFF0;
  SOLBAR_0 = 20.0;
  WASOBR_0 = 25.0;
  TSTBAR_0 = 400.0;
  SEBAR_0  = 0.85;
  N3BAR_0  = 80.0;
  REMBAR_0 = 95.0;
  MISP_0   = MISP0;
  ISI_0    = 6.0;
  DEP_0    = DEP0;
  IL6_0    = IL60;
}

$ODE
double tt  = SOLVERTIME;
double tod = tt - 24.0*floor(tt/24.0);

// ---------------------------------------------------------- bed schedule ---
double bedt = WAKET + 24.0 - TIBS;
bedt = bedt - 24.0*floor(bedt/24.0);
double inBed = inwin(tod, bedt, WAKET, SHBED);
double napwin = NAPW*inwin(tod, NAPT0, NAPT0 + NAPDUR, 0.2);

// ---------------------------------------------------------------- light ----
double dayw = inwin(tod, WAKET, EVEHR, 0.25);
double blt  = BLTON*inwin(tod, BLTT0, BLTT0 + BLTDUR, 0.15);
double lux  = inBed*LUXBED
            + (1.0 - inBed)*(dayw*LUXDAY + (1.0 - dayw)*LUXEVE)
            + blt*BLTLUX;

// ------------------------------------------------------------ circadian ----
double ct    = tod - PHI;
double Cwake = AMPC*cos(TWOPI*(ct - TPKC)/24.0);
double prcL  = -sin(TWOPI*(ct - 5.0)/24.0);   // + = delay, - = advance
double prcM  =  sin(TWOPI*(ct - 5.0)/24.0);   // melatonin PRC ~ inverse of light
double mgate = cos(TWOPI*(ct - 3.0)/24.0);
mgate = (mgate > 0.0) ? mgate*mgate : 0.0;
double msupp = 1.0/(1.0 + lux/LUX50);

// -------------------------------------------------------- concentrations ---
double CZOL = ZOLC/VZOL;
double CESZ = ESZC/VESZ;
double CSUV = SUVC/VSUV;
double CLEM = LEMC/VLEM;
double CDAR = DARC/VDAR;
double CRAM = RAMC/VRAM;
double CRM2 = RAMM/VRM2;
double CMLX = (MELC/VMEL)*1.0e6;              // pg/mL
double CDOX = DOXC/VDOX;
double CTRZ = TRZC/VTRZ;
double CCAF = CAFC/VCAF;
double CETH = ETHC/VETH;

// ------------------------------------------------------- target binding ----
double occBZraw = CZOL/EC50ZOL + CESZ/EC50ESZ + CETH/EC50ETH;
double occBZ    = occBZraw/(1.0 + occBZraw);
double Ebz      = EMAXBZ*occBZ/(1.0 + TOLB);

double occOXraw = CSUV/EC50SUV + CLEM/EC50LEM + CDAR/EC50DAR;
double oxBlk    = occOXraw/(1.0 + occOXraw);

double occMTraw = MELP/EC50MLE + CMLX/EC50MLX + CRAM/EC50RAM + CRM2/EC50RM2;
double occMT    = occMTraw/(1.0 + occMTraw);
double Emt      = EMAXMT*occMT;

double h1raw = CDOX/EC50DOX + CTRZ/EC50TZH;
double h1blk = h1raw/(1.0 + h1raw);
double e5ht  = (CTRZ/EC50TZ5)/(1.0 + CTRZ/EC50TZ5);
double a1blk = (CTRZ/EC50TZA)/(1.0 + CTRZ/EC50TZA);

// ------------------------------------------------------------- CBT-I -------
// A smooth ramp rather than a step: CBT-I is delivered over sessions, and a
// discontinuous parameter would also be unkind to the solver.
double CBTI  = CBTION/(1.0 + exp(-(tt - CBTIT0)/CBTIRMP));
double srt   = CBTI*WSRT;
double stimc = CBTI*WSTIMC;
double cogth = CBTI*WCOGTH;
double relax = CBTI*WRELAX;
double mindf = CBTI*WMINDF;

// -------------------------------------------------------- wake drive -------
double oxEff = OXA*(1.0 - oxBlk);
double haEff = HA*(1.0 - h1blk);
double Wdrv  = WNE*(NE/NE0)*(1.0 - 0.55*a1blk)
             + WHA*(haEff/HA0)
             + WOX*(oxEff/OX0);

// ---------------------------------------------------------- arousal --------
double Adrug = GADESZ*(CESZ/EC50ESZ)/(1.0 + CESZ/EC50ESZ)
             + GADTRZ*e5ht + GADDOX*h1blk;
double Atgt  = A0
             + GCOND*COND*inBed
             + GSEFF*SEFF*inBed
             + GDBAS*DBAS
             + GCORT*(CORT/CORT0 - 1.0)
             + GSTR*STR
             + GREB*WDR
             + GETRB*ETRB
             + GDEP*(DEP - DEP0)
             + GPAIN*PAIN
             + GVMS*VMS
             - GRELAX*relax
             - Adrug;
if (Atgt < 0.02) Atgt = 0.02;
dxdt_AROU = (Atgt - AROU)/TAUAR;

// ------------------------------------------------- the sleep switch --------
// Ultradian NREM-REM oscillator. Its phase only advances while asleep, so it
// is effectively reset at each sleep onset. Awakenings are not stochastic in
// this model: they occur when an ultradian trough (a REM or light-N2 window,
// deepening as Process S dissipates) meets a sleep drive whose margin over
// the switch threshold has already been eroded by arousal.
double ultgain = 0.55 + 0.90*(KSREM/(S + KSREM));
double ultra   = AULT*0.5*(ULTA + 1.0)*ultgain;
double adoEff = ADO/(1.0 + CCAF/KICAF);
double drive  = WS*S + WADO*adoEff + Emt + Ebz + E5HT*e5ht
              - WCBT*CBTD - Cwake - AROU - Wdrv - ultra - SWTH;
double opp    = inBed + (1.0 - inBed)*napwin;
if (opp > 1.0) opp = 1.0;
double SLP    = opp*SLPMAX/(1.0 + exp(-drive/KSHARP));

// ------------------------------------------------------ two-process core ---
double taudEff = TAUD*(1.0 + GN3BZ*occBZ)/(1.0 + GN35HT*e5ht + GN3GBP*GBPON);
dxdt_S   = (1.0 - SLP)*(SMAX - S)/TAUR - SLP*S/taudEff;
dxdt_ADO = KADOIN*(1.0 - SLP) - KADOOUT*ADO;

// -------------------------------------------------------- flip-flop --------
double neTgt = NE0*(NESLP + (1.0 - NESLP)*(1.0 - SLP))
                  *(1.0 + GOXNE*(oxEff/OX0 - 1.0))
                  *(1.0 + 0.25*(AROU/A0 - 1.0));
double haTgt = HA0*(HASLP + (1.0 - HASLP)*(1.0 - SLP))
                  *(1.0 + GOXHA*(oxEff/OX0 - 1.0));
double oxTgt = OX0*(OXSLP + (1.0 - OXSLP)*(1.0 - SLP))
                  *(1.0 + 0.25*Cwake/AMPC);
if (neTgt < 0.0) neTgt = 0.0;
if (haTgt < 0.0) haTgt = 0.0;
if (oxTgt < 0.0) oxTgt = 0.0;
double ultw = 6.283185307179586/PULT;
dxdt_ULTA =  SLP*ultw*ULTB;
dxdt_ULTB = -SLP*ultw*ULTA;
dxdt_NE  = (neTgt - NE )/TAUNE;
dxdt_HA  = (haTgt - HA )/TAUHA;
dxdt_OXA = (oxTgt - OXA)/TAUOX;

// -------------------------------------------------------- circadian ODEs ---
dxdt_MELP = KMELS*mgate*msupp*FMELAGE - KMELE*MELP;
dxdt_PHI  = (TAUINT - 24.0)/24.0
          + KLIGHT*prcL*log(1.0 + lux/LUXREF)
          + KMELPH*prcM*(MELP + CMLX)/1000.0;
double cbTgt = -AMPT*cos(TWOPI*(ct - 5.0)/24.0) - DROPT*SLP;
dxdt_CBTD = (cbTgt - CBTD)/TAUCBT;

// -------------------------------------------------------------- HPA --------
double circC = 1.0 + AMPCOR*cos(TWOPI*(ct - TPKCOR)/24.0);
if (circC < 0.05) circC = 0.05;
double fb = 1.0/(1.0 + FBGR*pow(CORT/IC50C, HILLC));
dxdt_CRH  = KINCRH*circC*(1.0 + ASTR*STR + AARO*(AROU/A0 - 1.0))*fb
          - KOUTCRH*CRH;
dxdt_ACTH = KINACT*CRH*fb - KOUTACT*ACTH;
dxdt_CORT = KINCOR*ACTH - KOUTCOR*CORT;
dxdt_STR  = -KSTRD*STR;

// ---------------------------------------------------- perpetuating loop ----
dxdt_COND = KCIN*inBed*(1.0 - SLP)*(CONDMAX - COND)
          - (KCOUT + KCSTIM*stimc + KCEXT*inBed*SLP)*COND;

double seffTgt = SEFF0 + GSEDBAS*DBAS + GSESOL*(SOLBAR/60.0) - GSEMIND*mindf;
if (seffTgt < 0.0) seffTgt = 0.0;
dxdt_SEFF = (seffTgt - SEFF)/TAUSE;

double dbasTgt = DBAS0 + GDBISI*(ISI/28.0) - GDBCOG*cogth;
if (dbasTgt < 0.0) dbasTgt = 0.0;
dxdt_DBAS = (dbasTgt - DBAS)/TAUDB;

// Maladaptive extension is an integrator, but not an unbounded one: the
// patient also drifts back toward their habitual schedule. Without that
// restoring term the untreated arm has no interior equilibrium at all and
// every insomniac ends the simulation pinned at TIBMAX.
double seGap = SETGT - SEBAR;
double dTIB;
if (CBTI > 0.5) {
  dTIB = KTIBUP*srt*((seGap < 0.0) ? -seGap : 0.0)*(TIBMAX - TIBS)
       - KTIBDN*srt*((seGap > 0.0) ?  seGap : 0.0)*(TIBS  - TIBMIN);
} else {
  dTIB = KTIBEXT*((seGap > 0.0) ? seGap : 0.0) - KTIBREL*(TIBS - TIB0);
}
if (TIBS >= TIBMAX && dTIB > 0.0) dTIB = 0.0;
if (TIBS <= TIBMIN && dTIB < 0.0) dTIB = 0.0;
dxdt_TIBS = dTIB;

// ------------------------------------------------------ drug adaptation ----
dxdt_TOLB = KTOLIN*occBZ*(TOLMAX - TOLB) - KTOLOUT*TOLB;
double wdrDrv = TOLB*((occBZ < OCCREF) ? (1.0 - occBZ/OCCREF) : 0.0);
dxdt_WDR  = (wdrDrv - WDR)/TAUWDR;
double etRb = KETIN*CETH - KETOUT*ETRB;
dxdt_ETRB = etRb - GET2*KETOUT*ETRB*CETH;

// ----------------------------------------------------------------- PK ------
dxdt_ZOLD = -KAZOL*ZOLD;
dxdt_ZOLC =  KAZOL*ZOLD - (CLZOL*CYP3A/VZOL)*ZOLC;
dxdt_ESZD = -KAESZ*ESZD;
dxdt_ESZC =  KAESZ*ESZD - (CLESZ*CYP3A/VESZ)*ESZC;
dxdt_SUVD = -KASUV*SUVD;
dxdt_SUVC =  KASUV*SUVD - (CLSUV*CYP3A/VSUV)*SUVC;
dxdt_LEMD = -KALEM*LEMD;
dxdt_LEMC =  KALEM*LEMD - (CLLEM*CYP3A/VLEM)*LEMC;
dxdt_DARD = -KADAR*DARD;
dxdt_DARC =  KADAR*DARD - (CLDAR*CYP3A/VDAR)*DARC;
dxdt_RAMD = -KARAM*RAMD;
dxdt_RAMC =  KARAM*RAMD - (CLRAM/VRAM)*RAMC;
dxdt_RAMM =  FMM2*(CLRAM/VRAM)*RAMC - (CLRM2/VRM2)*RAMM;
dxdt_MELD = -KAMEL*MELD;
dxdt_MELC =  KAMEL*MELD - (CLMEL/VMEL)*MELC;
dxdt_DOXD = -KADOX*DOXD;
dxdt_DOXC =  KADOX*DOXD - (CLDOX/VDOX)*DOXC;
dxdt_TRZD = -KATRZ*TRZD;
dxdt_TRZC =  KATRZ*TRZD - (CLTRZ*CYP3A/VTRZ)*TRZC;
dxdt_CAFD = -KACAF*CAFD;
dxdt_CAFC =  KACAF*CAFD - (CLCAF/VCAF)*CAFC;
dxdt_ETHD = -KAETH*ETHD;
dxdt_ETHC =  KAETH*ETHD - VMETH*ETHC/(KMETH*VETH + ETHC);

// ----------------------------------------------- sleep measurement ---------
dxdt_ONS = 6.0*SLP*inBed*(1.0 - ONS) - 3.0*(1.0 - inBed)*ONS;

double rSOL  = 60.0*inBed*(1.0 - ONS);
double rWASO = 60.0*inBed*ONS*(1.0 - SLP);
double rTST  = 60.0*SLP;
double rNAW  = inBed*ONS*(1.0 - SLP)/MAWD;

// sleep architecture -------------------------------------------------------
double pN3 = PN3MAX*(S/(S + KSN3))
                   *(1.0 + GN35HT*e5ht + GN3GBP*GBPON)
                   *(1.0 - GN3BZ*occBZ)*FN3AGE;
double remCirc = 1.0 + 0.35*cos(TWOPI*(ct - 6.0)/24.0);
double pREM = PREMAX*(KSREM/(S + KSREM))*remCirc
                    *(1.0 + GREDOR*oxBlk)
                    *(1.0 - GREBZ*occBZ)
                    *(1.0 - GRETRZ*e5ht)
                    *(1.0 - GREETH*CETH/(CETH + 0.30));
pN3  = clamp01(pN3 , 0.0, 0.55);
pREM = clamp01(pREM, 0.0, 0.45);
double pSum = pN3 + pREM;
if (pSum > 0.80) { pN3 *= 0.80/pSum; pREM *= 0.80/pSum; }

double sedIdx = Ebz + Emt + E5HT*e5ht + WOX*oxBlk + WHA*h1blk;

dxdt_SOLCUM = rSOL;
dxdt_WASOCM = rWASO;
dxdt_TSTCUM = rTST;
dxdt_NAWCUM = rNAW;
dxdt_RESCUM = 60.0*(1.0 - inBed)*sedIdx;

dxdt_SOLBAR = (rSOL *24.0 - SOLBAR)/TAUEW;
dxdt_WASOBR = (rWASO*24.0 - WASOBR)/TAUEW;
dxdt_TSTBAR = (rTST *24.0 - TSTBAR)/TAUEW;
dxdt_SEBAR  = (SLP*inBed*24.0/TIBS - SEBAR)/TAUEW;
dxdt_N3BAR  = (60.0*SLP*pN3 *24.0 - N3BAR )/TAUEW;
dxdt_REMBAR = (60.0*SLP*pREM*24.0 - REMBAR)/TAUEW;
dxdt_RESBAR = ((1.0 - inBed)*sedIdx*24.0/(24.0 - TIBS) - RESBAR)/TAUEW;

// ------------------------------------------------------- consequences ------
double frag = WASOBR/(WASOBR + 30.0);
double mispTgt = MISP0 + GMIAR*(AROU/A0 - 1.0)*0.5 + GMIFR*frag - GMICOG*cogth;
mispTgt = clamp01(mispTgt, 0.0, 0.70);
dxdt_MISP = (mispTgt - MISP)/TAUMI;

double sSOL  = SOLBAR*(1.0 + MISPS*MISP);
double sWASO = WASOBR*(1.0 + MISPS*MISP);
double sTST  = TSTBAR*(1.0 - MISP);
double debt  = (TSTNEED - TSTBAR); if (debt < 0.0) debt = 0.0;
double dayImp = debt/TSTNEED + RESBAR;
double isiTgt = ASOL*sSOL + AWASO*sWASO
              + ATST*((TSTNEED - sTST) > 0.0 ? (TSTNEED - sTST) : 0.0)
              + ADBAS*DBAS + ADAY*dayImp + AAR*(AROU/A0 - 1.0);
isiTgt = clamp01(isiTgt, 0.0, 28.0);
dxdt_ISI = (isiTgt - ISI)/TAUISI;

double depTgt = DEP0 + GDEPISI*(ISI/28.0);
dxdt_DEP = (depTgt - DEP)/TAUDEP;

double il6Tgt = IL60*(1.0 + GILTST*debt/TSTNEED + GILCOR*(CORT/CORT0 - 1.0));
if (il6Tgt < 0.2) il6Tgt = 0.2;
dxdt_IL6 = (il6Tgt - IL6)/TAUIL;

double n3Gap = 1.0 - N3BAR/N3REF; if (n3Gap < 0.0) n3Gap = 0.0;
dxdt_GLYM = KGIN*n3Gap - KGOUT*GLYM;

$TABLE
// The instantaneous quantities below are recomputed from the states and
// parameters so that they are exact at the output time. mrgsolve hoists
// block-local `double` declarations to a shared scope, so the names first
// declared in $ODE are assigned (not re-declared) here.
tod = TIME - 24.0*floor(TIME/24.0);
bedt = WAKET + 24.0 - TIBS;
bedt = bedt - 24.0*floor(bedt/24.0);
inBed = inwin(tod, bedt, WAKET, SHBED);
napwin = NAPW*inwin(tod, NAPT0, NAPT0 + NAPDUR, 0.2);
dayw = inwin(tod, WAKET, EVEHR, 0.25);
blt  = BLTON*inwin(tod, BLTT0, BLTT0 + BLTDUR, 0.15);
lux  = inBed*LUXBED + (1.0 - inBed)*(dayw*LUXDAY + (1.0 - dayw)*LUXEVE)
     + blt*BLTLUX;
ct    = tod - PHI;
Cwake = AMPC*cos(TWOPI*(ct - TPKC)/24.0);

CZOL = ZOLC/VZOL;
CESZ = ESZC/VESZ;
CSUV = SUVC/VSUV;
CLEM = LEMC/VLEM;
CDAR = DARC/VDAR;
CRAM = RAMC/VRAM;
CRM2 = RAMM/VRM2;
CMLX = (MELC/VMEL)*1.0e6;
CDOX = DOXC/VDOX;
CTRZ = TRZC/VTRZ;
CCAF = CAFC/VCAF;
CETH = ETHC/VETH;

occBZraw = CZOL/EC50ZOL + CESZ/EC50ESZ + CETH/EC50ETH;
occBZ    = occBZraw/(1.0 + occBZraw);
Ebz      = EMAXBZ*occBZ/(1.0 + TOLB);
occOXraw = CSUV/EC50SUV + CLEM/EC50LEM + CDAR/EC50DAR;
oxBlk    = occOXraw/(1.0 + occOXraw);
occMTraw = MELP/EC50MLE + CMLX/EC50MLX + CRAM/EC50RAM + CRM2/EC50RM2;
occMT    = occMTraw/(1.0 + occMTraw);
Emt      = EMAXMT*occMT;
h1raw = CDOX/EC50DOX + CTRZ/EC50TZH;
h1blk = h1raw/(1.0 + h1raw);
e5ht  = (CTRZ/EC50TZ5)/(1.0 + CTRZ/EC50TZ5);
a1blk = (CTRZ/EC50TZA)/(1.0 + CTRZ/EC50TZA);

oxEff = OXA*(1.0 - oxBlk);
haEff = HA*(1.0 - h1blk);
Wdrv  = WNE*(NE/NE0)*(1.0 - 0.55*a1blk) + WHA*(haEff/HA0) + WOX*(oxEff/OX0);
ultgain = 0.55 + 0.90*(KSREM/(S + KSREM));
ultra   = AULT*0.5*(ULTA + 1.0)*ultgain;
adoEff = ADO/(1.0 + CCAF/KICAF);
drive  = WS*S + WADO*adoEff + Emt + Ebz + E5HT*e5ht
       - WCBT*CBTD - Cwake - AROU - Wdrv - ultra - SWTH;
opp    = inBed + (1.0 - inBed)*napwin;
if (opp > 1.0) opp = 1.0;
SLP    = opp*SLPMAX/(1.0 + exp(-drive/KSHARP));

sedIdx = Ebz + Emt + E5HT*e5ht + WOX*oxBlk + WHA*h1blk;
sSOL  = SOLBAR*(1.0 + MISPS*MISP);
sWASO = WASOBR*(1.0 + MISPS*MISP);
sTST  = TSTBAR*(1.0 - MISP);
double SEpct = 100.0*SEBAR;
double NAWn  = WASOBR/60.0/MAWD;
double N3pct = 100.0*N3BAR/(TSTBAR + 1.0e-6);
double REMpct= 100.0*REMBAR/(TSTBAR + 1.0e-6);
double PSQI  = clamp01(1.0 + 0.62*ISI, 0.0, 21.0);
double REMIT = (ISI < 8.0 && SEBAR > 0.85) ? 1.0 : 0.0;
double TEMPC = 36.80 + CBTD;
double HANG  = 100.0*clamp01(sedIdx/1.5, 0.0, 1.0);

$CAPTURE @annotated
tod    : Clock hour (h)
inBed  : In-bed indicator (-)
lux    : Ambient illuminance (lux)
Cwake  : Circadian alerting signal (-)
drive  : Net sleep drive entering the switch (-)
SLP    : Instantaneous sleep probability (-)
Wdrv   : Ascending arousal wake drive (-)
adoEff : Effective adenosine after caffeine antagonism (-)
CZOL   : Zolpidem concentration (mg/L)
CESZ   : Eszopiclone concentration (mg/L)
CSUV   : Suvorexant concentration (mg/L)
CLEM   : Lemborexant concentration (mg/L)
CDAR   : Daridorexant concentration (mg/L)
CRAM   : Ramelteon concentration (mg/L)
CRM2   : Ramelteon M-II concentration (mg/L)
CMLX   : Exogenous melatonin concentration (pg/mL)
CDOX   : Doxepin concentration (mg/L)
CTRZ   : Trazodone concentration (mg/L)
CCAF   : Caffeine concentration (mg/L)
CETH   : Ethanol concentration (g/L)
occBZ  : GABA-A benzodiazepine-site occupancy (-)
Ebz    : BzRA sleep-drive effect after tolerance (-)
oxBlk  : Orexin-receptor blockade (-)
occMT  : Melatonin-receptor occupancy (-)
Emt    : Melatonergic sleep-drive effect (-)
h1blk  : H1-receptor blockade (-)
e5ht   : 5-HT2A blockade (-)
sedIdx : Instantaneous drug sedation index (-)
sSOL   : Subjective sleep-onset latency (min)
sWASO  : Subjective wake after sleep onset (min)
sTST   : Subjective total sleep time (min)
SEpct  : Sleep efficiency (%)
NAWn   : Awakenings per night (-)
N3pct  : N3 as a percentage of total sleep time (%)
REMpct : REM as a percentage of total sleep time (%)
PSQI   : Pittsburgh Sleep Quality Index estimate (0-21)
REMIT  : Remission indicator, ISI<8 and SE>85% (-)
TEMPC  : Core body temperature (degC)
HANG   : Next-morning hangover index (0-100)
'

## ============================================================================
##  BUILD
## ============================================================================

ins_build <- function(quiet = TRUE) {
  mrgsolve::mcode_cache("insomnia_qsp", ins_code, quiet = quiet)
}

mod_ins <- ins_build()

## ============================================================================
##  PATIENT PHENOTYPES
##  Baselines are set by the perpetuating-loop states, not by hand-setting the
##  sleep metrics: a phenotype is a starting point on the 3-P loop.
## ============================================================================

ins_phenotype <- function(who = c("good_sleeper", "chronic_insomnia",
                                  "severe_insomnia", "elderly", "sleep_onset",
                                  "sleep_maintenance", "comorbid_depression",
                                  "delayed_phase", "shift_worker")) {
  who <- match.arg(who)
  base <- list()
  switch(who,
    good_sleeper = list(),
    chronic_insomnia = list(
      A0 = 0.74, DBAS0 = 0.55, SEFF0 = 0.40, TIB0 = 8.8, GMIAR = 0.24),
    severe_insomnia = list(
      A0 = 0.80, DBAS0 = 0.72, SEFF0 = 0.55, TIB0 = 9.4, GMIAR = 0.28,
      MISP0 = 0.12),
    elderly = list(
      A0 = 0.60, DBAS0 = 0.50, SEFF0 = 0.35, TIB0 = 9.2,
      FMELAGE = 0.35, FN3AGE = 0.45, TAUR = 21.0, TPKC = 17.5,
      CLZOL = 8.1, CLESZ = 6.9, TSTNEED = 420),
    sleep_onset = list(
      A0 = 0.76, DBAS0 = 0.58, SEFF0 = 0.55, TIB0 = 8.8, TPKC = 19.4),
    sleep_maintenance = list(
      A0 = 0.70, DBAS0 = 0.52, SEFF0 = 0.25, TIB0 = 9.0, GCORT = 0.50,
      FN3AGE = 0.70),
    comorbid_depression = list(
      A0 = 0.78, DBAS0 = 0.62, SEFF0 = 0.42, TIB0 = 9.2, DEP0 = 0.55,
      GDEPISI = 0.85, KSREM = 0.55),
    delayed_phase = list(
      A0 = 0.58, DBAS0 = 0.45, SEFF0 = 0.35, TIB0 = 8.5, TAUINT = 24.42,
      LUXEVE = 300, LUXDAY = 250),
    shift_worker = list(
      A0 = 0.70, DBAS0 = 0.50, SEFF0 = 0.35, TIB0 = 8.0,
      WAKET = 15.0, LUXDAY = 350, LUXEVE = 300)
  )
}

## ============================================================================
##  DOSING HELPERS
##  All hypnotics are given at BEDHOUR each evening; caffeine and light are
##  given on their own clock. `days` is the number of nights of treatment,
##  `start_day` the first treated day (day 1 = first simulated day).
## ============================================================================

ev_nightly <- function(cmt, amt, days, start_day = 1, bedhour = 22.0,
                       every = 1) {
  if (days <= 0) return(NULL)
  nights <- seq(0, days - 1, by = every)
  mrgsolve::ev(
    time = (start_day - 1 + nights)*24 + bedhour,
    amt  = amt, cmt = cmt, evid = 1
  )
}

ev_daily <- function(cmt, amt, days, start_day = 1, hour = 8) {
  if (days <= 0) return(NULL)
  mrgsolve::ev(
    time = (start_day - 1 + seq(0, days - 1))*24 + hour,
    amt  = amt, cmt = cmt, evid = 1
  )
}

`%+%` <- function(a, b) {
  if (is.null(a)) return(b)
  if (is.null(b)) return(a)
  a + b
}

## ============================================================================
##  SIMULATION DRIVER
##  A 21-day unmedicated lead-in is always simulated first so that the
##  perpetuating loop (COND, DBAS, SEFF, TIB, ISI, MISP) reaches the state that
##  actually corresponds to the phenotype. Only the post-lead-in window is
##  returned, with TIME re-zeroed at randomisation.
## ============================================================================

ins_simulate <- function(phenotype = "chronic_insomnia",
                         weeks = 12,
                         param = list(),
                         treat = list(),
                         events = NULL,
                         cbti_start_day = NA_real_,
                         leadin_days = 150,
                         delta = 0.25) {

  pheno <- if (is.character(phenotype)) ins_phenotype(phenotype) else phenotype
  pars  <- modifyList(pheno, param)

  m <- mod_ins
  if (length(pars)) m <- mrgsolve::param(m, pars)

  ## ---- lead-in: same patient, no drug, no CBT-I --------------------------
  cmts <- names(as.list(mrgsolve::init(mod_ins)))
  m0   <- mrgsolve::param(m, CBTION = 0, USEINIT = 1)
  li   <- as.data.frame(mrgsolve::mrgsim(m0, end = leadin_days*24, delta = 1,
                                         recover = "numeric", obsonly = TRUE))
  init_vec <- as.list(unlist(li[nrow(li), cmts]))

  ## ---- randomised phase, started from the lead-in end state ---------------
  cb <- if (is.na(cbti_start_day)) list(CBTION = 0, CBTIT0 = 1e6)
        else list(CBTION = 1, CBTIT0 = (cbti_start_day - 1)*24)
  ## `treat` holds anything that is switched on AT randomisation (light
  ## therapy, a CYP inhibitor, a schedule change) and must therefore NOT be
  ## present during the lead-in, or the arm silently becomes its own control.
  m1 <- mrgsolve::param(m, c(list(USEINIT = 0), cb, treat))
  m1 <- mrgsolve::init(m1, init_vec)

  end <- weeks*7*24
  out <- if (is.null(events)) {
    mrgsolve::mrgsim(m1, end = end, delta = delta, recover = "numeric")
  } else {
    mrgsolve::mrgsim(m1, events = events, end = end, delta = delta,
                     recover = "numeric")
  }
  as.data.frame(out)
}

## ============================================================================
##  NIGHTLY SUMMARY
##  The cumulative counters are differenced across "sleep days" that run from
##  midday to midday, so that a night is never split by the day boundary.
## ============================================================================

ins_nightly <- function(sim, split_hour = 12) {
  need <- c("time", "SOLCUM", "WASOCM", "TSTCUM", "NAWCUM", "RESCUM")
  stopifnot(all(need %in% names(sim)))
  brk <- sim[["time"]] %% 24
  night <- floor((sim[["time"]] - split_hour)/24) + 1
  d <- sim
  d$night <- night
  agg <- d %>%
    dplyr::group_by(night) %>%
    dplyr::summarise(
      t_end   = max(time),
      SOL     = max(SOLCUM) - min(SOLCUM),
      WASO    = max(WASOCM) - min(WASOCM),
      TST     = max(TSTCUM) - min(TSTCUM),
      NAW     = max(NAWCUM) - min(NAWCUM),
      RESID   = max(RESCUM) - min(RESCUM),
      TIB     = 60*mean(TIBS),
      ISI     = dplyr::last(ISI),
      SEbar   = dplyr::last(SEBAR),
      sTST    = dplyr::last(sTST),
      sSOL    = dplyr::last(sSOL),
      sWASO   = dplyr::last(sWASO),
      MISP    = dplyr::last(MISP),
      AROU    = mean(AROU),
      COND    = dplyr::last(COND),
      DBAS    = dplyr::last(DBAS),
      TOLB    = dplyr::last(TOLB),
      WDR     = dplyr::last(WDR),
      N3      = dplyr::last(N3BAR),
      REM     = dplyr::last(REMBAR),
      HANG    = max(HANG),
      .groups = "drop"
    ) %>%
    dplyr::mutate(SE = 100*TST/pmax(TIB, 1))
  agg <- agg[agg$night >= 1, ]
  agg$night <- agg$night - min(agg$night) + 1
  ## drop the last partial night
  agg[-nrow(agg), ]
}

## ============================================================================
##  TREATMENT SCENARIOS (17 arms)
## ============================================================================

ins_scenarios <- function() {
  W <- 12                       # weeks simulated in every arm
  D <- W*7                      # nights
  list(
    `1. Untreated chronic insomnia` = list(
      pheno = "chronic_insomnia", ev = NULL, cbti = NA,
      note  = "Natural history over 12 weeks. TIB drifts up, COND accumulates."),

    `2. Zolpidem 10 mg nightly, stopped at week 4` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("ZOLD", 10, days = 28), cbti = NA,
      note = "Tolerance builds, then rebound insomnia for 3-5 nights after stop."),

    `3. Zolpidem 10 mg intermittent (3 nights/week)` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("ZOLD", 10, days = D, every = 2), cbti = NA,
      note = "Intermittent dosing keeps occupancy below the tolerance driver."),

    `4. Eszopiclone 3 mg nightly x 12 weeks` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("ESZD", 3, days = D), cbti = NA,
      note = "Longer half-life: WASO responds more than SOL; residual index up."),

    `5. Suvorexant 20 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("SUVD", 20, days = D), cbti = NA,
      note = "t1/2 12 h. Sleep maintenance good; largest next-morning carry-over."),

    `6. Lemborexant 10 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("LEMD", 10, days = D), cbti = NA,
      note = "Fast Tmax with a long terminal phase: acts on both SOL and WASO."),

    `7. Daridorexant 50 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("DARD", 50, days = D), cbti = NA,
      note = "Half-life engineered to 8 h: least residual sedation of the DORAs."),

    `8. Daridorexant 25 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("DARD", 25, days = D), cbti = NA,
      note = "Dose-response arm against scenario 7."),

    `9. Ramelteon 8 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("RAMD", 8, days = D), cbti = NA,
      note = "MT1/MT2 only: a small SOL effect and essentially no WASO effect."),

    `10. Melatonin 2 mg at 21:00 (elderly)` = list(
      pheno = "elderly",
      ev = ev_nightly("MELD", 2, days = D, bedhour = 21), cbti = NA,
      note = "Replacement in a patient whose pineal output is 35% of young."),

    `11. Low-dose doxepin 6 mg nightly` = list(
      pheno = "sleep_maintenance",
      ev = ev_nightly("DOXD", 6, days = D), cbti = NA,
      note = "H1 blockade only: WASO and last-third sleep, no SOL effect."),

    `12. Trazodone 50 mg nightly` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("TRZD", 50, days = D), cbti = NA,
      note = "5-HT2A/H1/alpha1: raises N3, blunts REM, notable morning carry-over."),

    `13. CBT-I alone` = list(
      pheno = "chronic_insomnia", ev = NULL, cbti = 1,
      note = "Sleep restriction, stimulus control, cognitive therapy, relaxation."),

    `14. CBT-I + zolpidem 10 mg for 6 weeks, then taper` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("ZOLD", 10, days = 42), cbti = 1,
      note = "Combined start, drug withdrawn at week 6 (the SLEEP-trial design)."),

    `15. Caffeine 200 mg at 16:00, untreated insomnia` = list(
      pheno = "chronic_insomnia",
      ev = ev_daily("CAFD", 200, days = D, hour = 16), cbti = NA,
      note = "Adenosine antagonism 6-7 h before bed still costs sleep."),

    `16. Nightly alcohol 40 g at 22:00` = list(
      pheno = "chronic_insomnia",
      ev = ev_nightly("ETHD", 40, days = D, bedhour = 22), cbti = NA,
      note = "Shorter SOL in the first half, rebound arousal in the second."),

    `18. Untreated elderly insomnia (control for 10)` = list(
      pheno = "elderly", ev = NULL, cbti = NA,
      note = "Comparator for the melatonin arm: reduced pineal output and SWS."),

    `19. Untreated sleep-maintenance insomnia (control for 11)` = list(
      pheno = "sleep_maintenance", ev = NULL, cbti = NA,
      note = "Comparator for the doxepin arm: high cortisol gain, low SWS."),

    `17. Morning bright light 10,000 lux (delayed phase)` = list(
      pheno = "delayed_phase", ev = NULL, cbti = NA,
      par  = list(BLTON = 1, BLTLUX = 10000, BLTT0 = 7, BLTDUR = 0.75),
      note = "Phase advance rather than sedation: the clock, not the switch.")
  )
}

ins_run_scenario <- function(name, weeks = 12, extra = list()) {
  sc <- ins_scenarios()[[name]]
  if (is.null(sc)) stop("unknown scenario: ", name)
  pars <- modifyList(if (is.null(sc$par)) list() else sc$par, extra)
  sim <- ins_simulate(phenotype = sc$pheno, weeks = weeks,
                      treat = pars, events = sc$ev,
                      cbti_start_day = if (is.na(sc$cbti)) NA_real_ else sc$cbti)
  list(sim = sim, nightly = ins_nightly(sim), note = sc$note)
}

ins_run_all <- function(weeks = 12, verbose = TRUE) {
  nms <- names(ins_scenarios())
  out <- lapply(nms, function(n) {
    if (verbose) message("  running: ", n)
    r <- ins_run_scenario(n, weeks = weeks)
    nt <- r$nightly
    wk <- function(w) nt[nt$night >= (w*7 - 6) & nt$night <= w*7, , drop = FALSE]
    smry <- function(d) c(SOL = mean(d$SOL), WASO = mean(d$WASO),
                          TST = mean(d$TST), SE = mean(d$SE),
                          ISI = mean(d$ISI), sTST = mean(d$sTST),
                          N3 = mean(d$N3), REM = mean(d$REM),
                          HANG = mean(d$HANG))
    data.frame(
      scenario = n,
      t(smry(wk(1))) |> as.data.frame() |> setNames(paste0("w1_", c(
        "SOL","WASO","TST","SE","ISI","sTST","N3","REM","HANG"))),
      t(smry(wk(4))) |> as.data.frame() |> setNames(paste0("w4_", c(
        "SOL","WASO","TST","SE","ISI","sTST","N3","REM","HANG"))),
      t(smry(wk(min(weeks, 12)))) |> as.data.frame() |> setNames(paste0("wend_", c(
        "SOL","WASO","TST","SE","ISI","sTST","N3","REM","HANG"))),
      row.names = NULL, check.names = FALSE
    )
  })
  do.call(rbind, out)
}

## ============================================================================
##  QUICK LOOK
## ============================================================================

if (identical(environment(), globalenv()) &&
    !is.null(getOption("ins.run.demo", NULL))) {
  message("mrgsolve ", as.character(utils::packageVersion("mrgsolve")))
  res <- ins_run_all()
  print(res[, c("scenario", "w4_SOL", "w4_WASO", "w4_TST", "w4_SE", "w4_ISI",
                "wend_ISI")], digits = 3)
}

##  ---------------------------------------------------------------------------
##  VALIDATION  (produced by ins_run_all(); mrgsolve 2.0.1, R 4.3.3)
##  Each arm is a 150-day untreated lead-in in the stated phenotype, then
##  12 weeks of the intervention. Sleep quantities are PSG-equivalent minutes.
##  ---------------------------------------------------------------------------
##
##  Scenario                                        wk1  SOL WASO  TST   SE  ISI   wk4  SOL WASO  TST   SE  ISI
##  1  Untreated chronic insomnia                        47  100  399 74.6 18.3        47  104  395 73.8 18.8
##  2  Zolpidem 10 mg, stopped at week 4                 24   58  467 87.3 16.7        26   52  465 87.6 12.3
##  3  Zolpidem 10 mg, 3 nights/week                     40   80  427 79.9 17.6        53   81  412 77.1 17.3
##  4  Eszopiclone 3 mg nightly                          27   33  490 91.8 16.3        27   32  487 91.8 10.2
##  5  Suvorexant 20 mg nightly                          26   59  465 86.9 17.0        24   56  465 87.6 12.5
##  6  Lemborexant 10 mg nightly                         24   61  466 87.1 17.0        22   60  465 87.6 12.8
##  7  Daridorexant 50 mg nightly                        25   59  465 87.0 16.9        24   57  465 87.6 12.4
##  8  Daridorexant 25 mg nightly                        27   72  450 84.1 17.3        26   53  465 87.6 12.7
##  9  Ramelteon 8 mg nightly                            32   78  438 81.8 17.4        29   50  466 87.7 12.8
##  10 Melatonin 2 mg 21:00, elderly                     21  167  388 69.5 21.6        21  168  387 69.3 21.3
##  11 Doxepin 6 mg nightly (maintenance phenotype)      23   42  495 91.4 10.9        21   36  505 93.4  8.4
##  12 Trazodone 50 mg nightly                           32   50  465 87.0 16.8        30   48  465 87.6 11.4
##  13 CBT-I alone                                       24   57  423 87.0 16.4        20   27  441 94.5  6.4
##  14 CBT-I + zolpidem, drug stopped at week 6          20   34  466 93.0 15.6        20   29  469 94.2  6.1
##  15 Caffeine 200 mg at 16:00                          87   86  373 69.7 19.0        92   84  372 69.2 22.1
##  16 Alcohol 40 g at 22:00                             24  149  376 70.2 18.6        32  146  372 69.1 22.2
##  17 Morning bright light, delayed phase              181   30  332 63.1 27.9       132   35  373 71.3 23.3
##  18 Untreated elderly insomnia   (control for 10)     33  165  373 66.8 21.9        35  163  372 66.6 22.8
##  19 Untreated maintenance insomnia (control for 11)   34   55  465 85.8 11.4        34   55  465 85.8 11.4
##
##  Week-4 change from the MATCHED untreated control (arm 1 unless noted):
##                                        dSOL  dWASO   dTST   dISI     literature (placebo-subtracted)
##    zolpidem 10 mg                       -21    -51    +70   -6.6     LPS -20 to -30, WASO -20, TST +30 to +50
##    eszopiclone 3 mg                     -20    -71    +91   -8.6     LPS -15 to -20, WASO -25, TST +45 to +60
##    suvorexant 20 mg                     -23    -47    +70   -6.3     LPS -10 to -20, WASO -20 to -25
##    lemborexant 10 mg                    -25    -44    +70   -6.0     LPS -20,        WASO -25, TST +40 to +60
##    daridorexant 50 mg                   -24    -47    +70   -6.5     LPS -11,        WASO -18, sTST +22
##    daridorexant 25 mg                   -21    -50    +70   -6.1     dose-ordered below 50 mg in the trials
##    ramelteon 8 mg                       -18    -53    +71   -6.0     LPS -9 to -13, no WASO/TST effect
##    melatonin 2 mg (vs arm 18)           -14     +5    +15   -1.5     sSOL -20, no objective WASO effect
##    doxepin 6 mg  (vs arm 19)            -13    -19    +40   -3.0     WASO -20 to -25, TST +25 to +30, no SOL
##    trazodone 50 mg                      -17    -56    +70   -7.4     small and poorly characterised
##    CBT-I alone                          -27    -76    +46  -12.5     SOL -20, WASO -25, SE +10, ISI -8 to -10
##    caffeine 200 mg at 16:00             +44    -19    -24   +3.2     400 mg 6 h pre-bed costs ~1 h of TST
##    alcohol 40 g at 22:00                -16    +42    -24   +3.4     shorter SOL, second-half fragmentation
##
##  Sleep architecture at week 4 (nightly minutes): the qualitative ordering the
##  model is asked to reproduce is that DORAs raise REM (130-137 vs 88 untreated),
##  ethanol suppresses it (56), trazodone raises N3 (97 vs 86) and BzRA suppress
##  it slightly, and the elderly phenotype has roughly 40% of the young N3 (37).
##  All of these come out in the right direction and rough magnitude.
##
##  ---------------------------------------------------------------------------
##  Calibration notes, and where the model is honest about missing
##  ---------------------------------------------------------------------------
##  * NOTHING in the sleep block is fitted to a sleep metric directly. SOL,
##    WASO, TST and SE are all read out of one continuous sleep-probability
##    variable, and the only knobs used to place a phenotype are A0 (the
##    constitutive arousal of that patient) and the circadian phase peak TPKC.
##    The chronic-insomnia phenotype was placed by matching the LONG-RUN
##    equilibrium (150+ days) of SOL 47 / WASO 100 / TST 399 / SE 74.6% /
##    ISI 18.8 to the pooled baselines of the recent Phase 3 hypnotic
##    programmes, not by matching a 4-week transient.
##
##  * The 3-P loop is genuinely bistable, and this is deliberate rather than
##    incidental. Below roughly A0 = 0.65 the model settles into a good-sleeper
##    basin; above it, conditioned arousal, sleep effort and time-in-bed
##    extension reinforce each other into a chronic basin. That is Spielman's
##    model taken literally: an acute stressor that raises arousal past the
##    threshold does not have to persist for the insomnia to persist.
##    Consequence to be aware of: outcomes are STEEP in A0 near the threshold,
##    so small covariate changes there produce large predicted differences.
##
##  * The untreated arm has NO placebo response. Real trial placebo arms improve
##    LPS by 10-20 min and WASO by 15-25 min, so every "change from control"
##    number above is larger than the corresponding placebo-subtracted trial
##    delta by roughly that amount. The WASO column is where this matters most.
##    Comparisons BETWEEN active arms are the ones this model is built to make.
##
##  * There is a ceiling artefact that must not be over-read. Total sleep time
##    cannot exceed SLPMAX x TIB, so once a hypnotic consolidates sleep to near
##    continuity every effective drug converges on TST 465 min and SE 87.6% at
##    a fixed 8.85 h time in bed. The model therefore CANNOT rank suvorexant,
##    lemborexant, daridorexant 50 mg and zolpidem on total sleep time; it can
##    only rank them on latency, on the shape of the night, on residual
##    sedation and on what happens when the drug is stopped. Those are the
##    comparisons the arms are designed for.
##
##  * Awakenings are not stochastic. WASO emerges from an ultradian oscillator
##    whose phase advances only during sleep meeting a sleep drive whose margin
##    over the switch threshold has been eroded by arousal. This reproduces the
##    clinical observation that fragmentation is concentrated in the last third
##    of the night (Process S has dissipated, cortisol is rising, and the
##    ultradian troughs deepen), but it means the model produces the same
##    awakening pattern every night for a given patient.
##
##  * Tolerance is modelled only for the GABA-A benzodiazepine site, because
##    that is the only one of these mechanisms with a consistent tolerance and
##    rebound signal. Scenario 2 shows the intended behaviour: 4 weeks of
##    nightly zolpidem builds TOLB to 0.55, the ISI benefit is already eroding
##    by week 4, and stopping produces a rebound overshoot that leaves the
##    patient at week 12 slightly WORSE than the untreated arm (ISI 22.0 vs
##    19.7), because the rebound nights re-condition the bed. That last part is
##    a model prediction, not a fitted result.
##
##  * The single most important claim the model makes is the CBT-I / hypnotic
##    asymmetry, and it is structural rather than tuned. Both classes produce a
##    similar ISI drop at week 4. CBT-I does it by removing terms from the
##    arousal equation (COND, SEFF, DBAS) and by compressing TIB, so its effect
##    is still there at week 12 with nothing being taken. Zolpidem does it by
##    adding a term that is proportional to a concentration, so its effect is
##    gone the night the concentration is. No parameter in the model was set to
##    make that happen; it follows from where the two act.
##
##  * CBT-I is, if anything, still too good here (ISI 6.4 at week 4, 4.9 at week
##    12, i.e. a full responder). Real CBT-I trials report roughly 60-70%
##    response and 40-50% remission, which a single deterministic patient
##    cannot represent. Read arm 13 as "the trajectory of a CBT-I responder",
##    not as the average of a trial arm.
##
##  * The circadian block entrains rather than being imposed. PHI is a state
##    driven by an intrinsic period of 24.18 h against a sinusoidal light PRC,
##    so the entrained phase angle is an OUTPUT. This is why the bright-light
##    arm works at all (scenario 17 advances the delayed-phase patient and cuts
##    SOL from 181 to 116 min over 12 weeks without any sedative effect) and
##    why the delayed-phase phenotype is produced by changing the intrinsic
##    period and the evening light, not by moving the sleep metrics.
##
##  * Melatonin is carried in pg/mL and shares one receptor pool between the
##    endogenous pineal signal (nocturnal peak ~60 pg/mL), exogenous melatonin
##    and ramelteon plus its M-II metabolite. This is what makes the elderly
##    melatonin arm behave correctly: replacing a pineal output that is 35% of
##    young shortens latency by 14 min and does nothing at all to WASO, which
##    is exactly the shape of the clinical evidence.
##
##  * All volumes and clearances are APPARENT (V/F, CL/F). The F parameters are
##    retained for documentation only and are not applied a second time.
##  ============================================================================
