# =============================================================================
#  PROLACTINOMA QSP — Shiny dashboard
#
#  11 tabs built directly on the model spec in prl_mrgsolve_model.R, which is
#  read out of that file at start-up so the app and the model cannot drift
#  apart.
#
#  The organising ideas the dashboard is built to make visible:
#    * ONE D2 occupancy equation drives everything, so the same slider set
#      produces dopamine-agonist therapy, antipsychotic-induced
#      hyperprolactinaemia, the aripiprazole add-on paradox and stalk-effect
#      disconnection. Tab 2 shows the competition explicitly.
#    * The MEASUREMENT LAYER is separate from the biology. Tab 4 plots
#      bioactive, immunoreactive, reported and post-dilution prolactin on the
#      same axes, so the hook effect and macroprolactinaemia are visible as
#      gaps between curves rather than as footnotes.
#    * Efficacy runs off the PITUITARY BIOPHASE and valvular risk off PLASMA,
#      so tab 9 can show them diverging.
#    * Presenting values are GENERATED by a silent natural-history phase, not
#      typed in: every plot marks the day of presentation.
#
#  Run with:  shiny::runApp("prl_shiny_app.R")
# =============================================================================

library(shiny)
library(mrgsolve)
library(ggplot2)
library(dplyr)
library(tidyr)
library(DT)

MODEL_FILE <- "prl_mrgsolve_model.R"
stopifnot(file.exists(MODEL_FILE))
src  <- readLines(MODEL_FILE)
i0   <- grep("^prl_code <- '", src)[1]
i1   <- grep("^'$", src)
i1   <- i1[i1 > i0][1]
spec <- paste(src[(i0 + 1):(i1 - 1)], collapse = "\n")
mod  <- mcode("prl_shiny", spec)

PRESIM <- 730   # silent natural-history phase, as in the model file

theme_prl <- function() {
  theme_minimal(base_size = 12) +
    theme(panel.grid.minor = element_blank(),
          plot.title    = element_text(face = "bold", size = 13),
          plot.subtitle = element_text(colour = "grey35", size = 10),
          legend.position = "bottom", legend.title = element_blank(),
          strip.text = element_text(face = "bold"))
}
PAL <- c("#1565C0", "#C62828", "#2E7D32", "#E65100", "#6A1B9A",
         "#00838F", "#AD1457", "#37474F", "#827717", "#4527A0")

pres_line <- function()
  list(geom_vline(xintercept = PRESIM/365, linetype = "22", colour = "grey45"),
       annotate("text", x = PRESIM/365, y = Inf, label = " presentation",
                hjust = 0, vjust = 1.4, size = 3, colour = "grey35"))

# ---------------------------------------------------------------------------
#  Build parameter list and events from the UI state
# ---------------------------------------------------------------------------
build_par <- function(i) {
  p <- list(
    NS0     = i$ns0,
    NR0     = i$nr0,
    D2RS0   = i$d2rs,
    D2RR0   = 0.05,
    FDRIVE  = i$fdrive,
    FGEN    = i$fgen,
    SEX     = ifelse(i$sex == "male", 1, 0),
    STALKP  = i$stalkp,
    APABSET = i$apab,
    PRIMHYP = i$primhyp,
    FCLR    = i$fclr,
    MGMT0   = i$mgmt,
    FTREPL  = i$ftrepl,
    KI_5HT2B= i$ki5ht,
    ICDSUSC = i$icdsusc
  )
  if (i$preg) p$PREGON <- PRESIM + i$pregday
  if (i$surg) { p$SURGD <- PRESIM + i$surgday
                p$SURGRES <- i$surgres; p$SURGHYP <- i$surghyp }
  if (i$ap_drug == "aripiprazole") {
    p$EFF_AP <- 0.25; p$KI_AP <- 0.34; p$FU_AP <- 0.01
    p$CL_AP  <- 210;  p$V_AP  <- 1400
  } else if (i$ap_drug == "quetiapine (sparing)") {
    p$EFF_AP <- 0.00; p$KI_AP <- 45.0
  }
  p
}

build_ev <- function(i, end) {
  ee <- list()
  wk <- max(1, ceiling((end - PRESIM - i$startday)/7))
  if (i$da == "cabergoline" && i$cabdose > 0) {
    ii <- if (i$cabsplit) 3.5 else 7
    amt <- if (i$cabsplit) i$cabdose/2 else i$cabdose
    nd  <- max(1, ceiling((end - PRESIM - i$startday)/ii))
    stopd <- if (i$stopyr > 0) PRESIM + i$startday + i$stopyr*365 else Inf
    nd  <- min(nd, max(1, ceiling((stopd - PRESIM - i$startday)/ii)))
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = amt,
                             cmt = "CAB_G", ii = ii, addl = nd - 1)
  }
  if (i$da == "bromocriptine" && i$brcdose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = i$brcdose/3,
                             cmt = "BRC_G", ii = 1/3,
                             addl = 3*max(1, end - PRESIM - i$startday) - 1)
  if (i$da == "quinagolide" && i$quidose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM + i$startday, amt = i$quidose/1000,
                             cmt = "QUI_G", ii = 1,
                             addl = max(1, end - PRESIM - i$startday) - 1)
  if (i$ap_drug != "none" && i$apdose > 0)
    ee[[length(ee)+1]] <- ev(time = PRESIM, amt = i$apdose, cmt = "AP_G",
                             ii = 1, addl = max(1, end - PRESIM) - 1)
  if (i$tmz)
    for (k in 0:(i$tmzcyc - 1))
      ee[[length(ee)+1]] <- ev(time = PRESIM + i$tmzstart + 28*k,
                               amt = 180*1.8, cmt = "TMZ_C", ii = 1, addl = 4)
  if (!length(ee)) return(NULL)
  ds <- lapply(ee, as.data.frame)
  cn <- unique(unlist(lapply(ds, names)))
  ds <- lapply(ds, function(d) { for (k in setdiff(cn, names(d))) d[[k]] <- 0; d[cn] })
  as.ev(do.call(rbind, ds))
}

simulate <- function(i) {
  end <- PRESIM + i$horizon*365
  e   <- build_ev(i, end)
  m   <- param(mod, build_par(i))
  out <- if (is.null(e)) mrgsim(m, end = end, delta = 1, maxsteps = 500000, hmax = 0.5)
         else mrgsim(m, events = e, end = end, delta = 1, maxsteps = 500000, hmax = 0.5)
  d <- as.data.frame(out)
  d$year <- d$time/365
  d
}

atd  <- function(d, v, t) d[[v]][which.min(abs(d$time - t))]
prs  <- function(d, v) atd(d, v, PRESIM)

# ---------------------------------------------------------------------------
#  UI
# ---------------------------------------------------------------------------
ui <- fluidPage(
  titlePanel("프로락틴 분비 뇌하수체 종양 (Prolactinoma) — QSP 대시보드"),
  tags$p(style = "color:#555;margin-top:-8px",
         HTML("하나의 D2 점유 방정식이 도파민 작용제 치료 · 항정신병약 유발 고프로락틴혈증 ·
               아리피프라졸 역설 · 줄기 압박(stalk effect)을 모두 생성합니다.
               <b>측정층(measurement layer)</b>은 생물학과 분리되어 있어 hook effect와
               macroprolactin을 곡선 사이의 간격으로 볼 수 있습니다.")),
  sidebarLayout(
    sidebarPanel(
      width = 3,
      selectInput("preset", "프리셋 (preset patient)",
                  c("microadenoma (F)", "macroadenoma (F)", "giant, male",
                    "partial resistance", "true resistance (AIP-like)",
                    "stalk effect (NFPA)", "macroprolactinaemia",
                    "antipsychotic-induced", "healthy control")),
      hr(),
      h5("종양 (tumour)"),
      sliderInput("ns0", "D2R-sensitive 종양 부피 (mL)", 0.001, 25, 0.35, 0.01),
      sliderInput("nr0", "D2R-low 저항 클론 (mL)", 0, 2, 0, 0.01),
      sliderInput("d2rs", "D2 수용체 밀도 (정상 = 1)", 0.02, 1.0, 0.50, 0.01),
      sliderInput("fdrive", "내인성 전사 구동 (FDRIVE)", 0.5, 2.0, 1.0, 0.05),
      sliderInput("fgen", "증식 구동 (FGEN, AIP/SF3B1 > 1)", 0.7, 2.0, 1.0, 0.05),
      radioButtons("sex", "성별", c("female", "male"), inline = TRUE),
      hr(),
      h5("치료 (therapy)"),
      selectInput("da", "도파민 작용제",
                  c("none", "cabergoline", "bromocriptine", "quinagolide"),
                  selected = "cabergoline"),
      conditionalPanel("input.da == 'cabergoline'",
        sliderInput("cabdose", "카베르골린 (mg/주)", 0, 7, 1, 0.25),
        checkboxInput("cabsplit", "주 2회 분할 투여", FALSE)),
      conditionalPanel("input.da == 'bromocriptine'",
        sliderInput("brcdose", "브로모크립틴 (mg/일, 3분할)", 0, 30, 7.5, 0.5)),
      conditionalPanel("input.da == 'quinagolide'",
        sliderInput("quidose", "퀴나골라이드 (ug/일)", 0, 600, 300, 25)),
      sliderInput("startday", "치료 시작 지연 (일, 진단 후)", 0, 1825, 0, 30),
      sliderInput("stopyr", "치료 중단 시점 (년, 0 = 중단 없음)", 0, 15, 0, 0.5),
      hr(),
      h5("기타 개입 / 상황"),
      selectInput("ap_drug", "항정신병약",
                  c("none", "risperidone-like", "aripiprazole",
                    "quetiapine (sparing)")),
      conditionalPanel("input.ap_drug != 'none'",
        sliderInput("apdose", "항정신병약 용량 (mg/일)", 0, 30, 6, 0.5)),
      checkboxInput("preg", "임신 (pregnancy)", FALSE),
      conditionalPanel("input.preg",
        sliderInput("pregday", "임신 시작 (치료 시작 후 일)", 0, 1460, 400, 30)),
      checkboxInput("surg", "경비강 수술 (TSS)", FALSE),
      conditionalPanel("input.surg",
        sliderInput("surgday", "수술 시점 (일)", 0, 1460, 30, 10),
        sliderInput("surgres", "잔존 분율", 0, 1, 0.25, 0.05),
        sliderInput("surghyp", "수술성 뇌하수체 기능저하", 0, 0.6, 0.12, 0.02)),
      checkboxInput("tmz", "테모졸로마이드", FALSE),
      conditionalPanel("input.tmz",
        sliderInput("tmzstart", "TMZ 시작 (일)", 0, 730, 30, 10),
        sliderInput("tmzcyc", "주기 수", 1, 12, 6, 1),
        sliderInput("mgmt", "MGMT 활성 (낮으면 반응)", 0.01, 1, 0.20, 0.01)),
      hr(),
      h5("모델 축 / 감수성"),
      sliderInput("stalkp", "뇌하수체 줄기 개방성", 0.001, 1, 1, 0.005),
      sliderInput("apab", "항프로락틴 자가항체 (macroprolactin)", 0, 5, 0, 0.1),
      sliderInput("primhyp", "원발성 갑상선 기능저하 중증도", 0, 1, 0, 0.05),
      sliderInput("fclr", "프로락틴 제거율 배수 (CKD < 1)", 0.2, 1.2, 1, 0.05),
      sliderInput("ftrepl", "성호르몬 보충 (정상 대비)", 0, 1, 0, 0.05),
      sliderInput("ki5ht", "5-HT2B Ki (nM) — 선택성 축", 1, 1200, 12, 1),
      sliderInput("icdsusc", "충동조절장애 감수성", 0.3, 2, 1, 0.1),
      sliderInput("horizon", "시뮬레이션 기간 (년, 진단 후)", 1, 20, 5, 1)
    ),
    mainPanel(
      width = 9,
      tabsetPanel(
        id = "tabs",
        tabPanel("① 환자 프로파일",
                 h4("진단 시점에 생성된 표현형 (generated, not typed in)"),
                 tags$p(style = "color:#666",
                        "모든 제시 값은 무증상 자연경과 2년(PRESIM)을 시뮬레이션한 뒤
                         읽은 값입니다. 프로락틴·성선축·골밀도·시야는 입력이 아니라 결과입니다."),
                 DTOutput("tbl_profile"),
                 hr(), plotOutput("p_profile", height = "420px")),
        tabPanel("② D2 점유 방정식",
                 h4("하나의 경쟁적 점유식이 모든 방향을 만든다"),
                 verbatimTextOutput("txt_occ"),
                 plotOutput("p_occ", height = "300px"),
                 hr(), plotOutput("p_branch", height = "300px")),
        tabPanel("③ 약물 PK",
                 h4("혈장 vs 뇌하수체 biophase — 주 1회 투여가 되는 이유"),
                 plotOutput("p_pk", height = "330px"),
                 hr(), verbatimTextOutput("txt_pk")),
        tabPanel("④ 프로락틴 & 측정층",
                 h4("생물학적 프로락틴과 보고되는 프로락틴은 같은 수가 아니다"),
                 plotOutput("p_prl", height = "340px"),
                 hr(), h5("이 환자의 2점 샌드위치 면역측정 곡선"),
                 plotOutput("p_hook", height = "300px")),
        tabPanel("⑤ 종양",
                 h4("세포 부피(빠르고 가역적) vs 세포 수(느리고 저장됨)"),
                 plotOutput("p_tum", height = "340px"),
                 hr(), plotOutput("p_clone", height = "260px")),
        tabPanel("⑥ 질량 효과 · 시야",
                 h4("기하학 문제 — 가역 전도차단과 비가역 축삭 손실"),
                 plotOutput("p_vf", height = "330px"),
                 hr(), plotOutput("p_hypo", height = "280px")),
        tabPanel("⑦ 성선축 · 생식",
                 h4("KNDy → GnRH 박동 → LH/FSH → 성호르몬"),
                 plotOutput("p_hpg", height = "340px"),
                 hr(), plotOutput("p_repro", height = "280px")),
        tabPanel("⑧ 뼈 · 대사",
                 h4("회복되는 부분과 저장되는 부분"),
                 plotOutput("p_bone", height = "330px"),
                 hr(), plotOutput("p_met", height = "260px")),
        tabPanel("⑨ 안전성 (선택성)",
                 h4("이상반응은 같은 농도에서 읽은 다른 수용체다"),
                 plotOutput("p_safe", height = "330px"),
                 hr(), h5("5-HT2B/D2 선택성 스윕: 효능은 평평, 판막 위험은 붕괴"),
                 plotOutput("p_sweep", height = "300px")),
        tabPanel("⑩ 시나리오 비교",
                 h4("사전 정의된 비교 (모두 실시간 시뮬레이션)"),
                 selectInput("cmp", "비교 항목", width = "420px",
                   c("cabergoline vs bromocriptine vs quinagolide",
                     "cabergoline 용량 0.25 / 0.5 / 1 / 2 / 3.5 mg/주",
                     "부분 저항 vs 진성 저항 (± 증량)",
                     "치료 지연 0 / 1 / 2 / 4년",
                     "중단 후 잔존 부피별 재발")),
                 plotOutput("p_cmp", height = "420px"),
                 hr(), DTOutput("tbl_cmp")),
        tabPanel("⑪ 중단 · 임신",
                 h4("약을 끊으면 무엇이 먼저 돌아오는가"),
                 plotOutput("p_wd", height = "340px"),
                 hr(), verbatimTextOutput("txt_wd"))
      )
    )
  )
)

# ---------------------------------------------------------------------------
#  Server
# ---------------------------------------------------------------------------
server <- function(input, output, session) {

  observeEvent(input$preset, {
    p <- switch(input$preset,
      "microadenoma (F)"          = list(ns0=0.35, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "macroadenoma (F)"          = list(ns0=3.20, d2rs=0.35, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "giant, male"               = list(ns0=18.0, d2rs=0.25, sex="male", fgen=1.0,
                                         fdrive=1.3, stalkp=1, apab=0, ap_drug="none"),
      "partial resistance"        = list(ns0=3.20, d2rs=0.15, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "true resistance (AIP-like)"= list(ns0=3.20, d2rs=0.04, sex="male", fgen=1.3,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"),
      "stalk effect (NFPA)"       = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=0.05, apab=0, ap_drug="none"),
      "macroprolactinaemia"       = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=2.2, ap_drug="none"),
      "antipsychotic-induced"     = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0,
                                         ap_drug="risperidone-like"),
      "healthy control"           = list(ns0=0.001, d2rs=0.50, sex="female", fgen=1.0,
                                         fdrive=1.0, stalkp=1, apab=0, ap_drug="none"))
    updateSliderInput(session, "ns0", value = p$ns0)
    updateSliderInput(session, "d2rs", value = p$d2rs)
    updateSliderInput(session, "fgen", value = p$fgen)
    updateSliderInput(session, "fdrive", value = p$fdrive)
    updateSliderInput(session, "stalkp", value = p$stalkp)
    updateSliderInput(session, "apab", value = p$apab)
    updateRadioButtons(session, "sex", selected = p$sex)
    updateSelectInput(session, "ap_drug", selected = p$ap_drug)
  })

  sim <- reactive({ simulate(reactiveValuesToList(input)) })

  # ---- tab 1 --------------------------------------------------------------
  output$tbl_profile <- renderDT({
    d <- sim()
    tt <- c(PRESIM, PRESIM + 365, max(d$time))
    lab <- c("진단 시점", "1년 후", sprintf("%.0f년 후", (max(d$time)-PRESIM)/365))
    vars <- c(PRLB="생물학적 프로락틴 (ng/mL)", PRLMEAS_="보고된 프로락틴 (ng/mL)",
              PEGREC="PEG 회수율 (%)", TVOL_="종양 부피 (mL)",
              CELLN="종양 세포량 (mL)", VCELL="평균 세포 부피",
              COMPR_="시신경교차 압박 (cm)", VFMD="시야 MD (dB)",
              OVF="배란 능력", TST="테스토스테론 (ng/dL)", E2G="에스트라디올 (pg/mL)",
              TSCORE="요추 T-score", PFRACT="척추 골절 확률 (%)",
              BW="체중 (kg)", IR="HOMA-IR", CORT="코르티솔 예비능",
              SIGDRIVE="D2 신호 구동", PTR="중등도 이상 TR 확률 (%)",
              PICD="충동조절장애 확률 (%)")
    m <- sapply(tt, function(t) sapply(names(vars), function(v) atd(d, v, t)))
    df <- data.frame(metric = unname(vars), round(m, 3), check.names = FALSE)
    names(df) <- c("지표", lab)
    datatable(df, rownames = FALSE, options = list(pageLength = 20, dom = "t"))
  })

  output$p_profile <- renderPlot({
    d <- sim()
    dd <- d %>% select(year, PRLB, PRLMEAS_, TVOL_, VFMD, TSCORE, OVF) %>%
      pivot_longer(-year)
    lv <- c(PRLB="생물학적 PRL", PRLMEAS_="보고된 PRL", TVOL_="종양 부피 mL",
            VFMD="시야 MD dB", TSCORE="요추 T-score", OVF="배란 능력")
    dd$name <- factor(lv[dd$name], levels = lv)
    ggplot(dd, aes(year, value)) +
      geom_line(colour = PAL[1], linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y", ncol = 3) + pres_line() +
      labs(x = "년 (0 = 종양 seeding)", y = NULL,
           title = "생성된 표현형의 전체 경과",
           subtitle = "점선 = 환자가 내원하고 치료가 시작되는 시점") +
      theme_prl()
  })

  # ---- tab 2 --------------------------------------------------------------
  output$txt_occ <- renderText({
    d <- sim(); r <- d[which.min(abs(d$time - max(d$time))), ]
    p <- build_par(reactiveValuesToList(input))
    paste0(
      "SIGDRIVE = SUM_i e_i (C_i/K_i) / (1 + SUM_j C_j/K_j)   x   D2R density\n\n",
      sprintf("  건강한 도파민 단독 상태의 SIGDRIVE          : %.4f\n", 0.0909),
      sprintf("  현재 SIGDRIVE (모든 리간드 경쟁 후)         : %.4f  (%.2fx)\n",
              r$SIGDRIVE, r$SIGDRIVE/0.0909),
      sprintf("  종양 클론의 활성 수용체 신호 SIGS           : %.4f\n", r$SIGS),
      sprintf("  잔여 전사 활성 (branch 2, 낮을수록 억제)    : %.4f\n", r$RTRS),
      sprintf("  잔여 분비과립 방출 활성 (branch 1)          : %.4f\n", r$REXS),
      "\n  같은 식이 만들어내는 네 가지 방향:\n",
      "    작용제        -> SIGDRIVE 상승 -> 프로락틴 하강\n",
      "    D2 차단제     -> e=0 리간드가 도파민을 밀어냄 -> 프로락틴 상승\n",
      "    아리피프라졸  -> e=0.25, 친화도 높음 -> 단독시 생리적 톤을 초과\n",
      "    줄기 압박     -> 전달(DAP) 항이 끊김 -> 정상 세포만 탈억제(상한 존재)\n")
  })

  output$p_occ <- renderPlot({
    d <- sim()
    dd <- d %>% select(year, SIGDRIVE, SIGS, DAP) %>% pivot_longer(-year)
    lv <- c(SIGDRIVE="SIGDRIVE (전체 D2 구동)", SIGS="SIGS (종양 활성 수용체)",
            DAP="문맥 도파민 (nM)")
    dd$name <- factor(lv[dd$name], levels = lv)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "점유와 전달",
           subtitle = "문맥 도파민은 단기 루프로 상승한다 — 전달자는 정상, 수용체가 문제") +
      theme_prl()
  })

  output$p_branch <- renderPlot({
    d <- sim(); r0 <- d[which.min(abs(d$time - PRESIM)), ]
    dd <- d %>% filter(time >= PRESIM) %>%
      transmute(day = time - PRESIM,
                `branch 1 분비(exocytosis)` = REXS/r0$REXS,
                `branch 2 전사(transcription)` = RTRS/r0$RTRS,
                `branch 3 세포 부피` = VCELL/r0$VCELL,
                `branch 4 세포 수` = CELLN/r0$CELLN,
                `프로락틴` = PRLB/r0$PRLB) %>%
      pivot_longer(-day)
    ggplot(dd, aes(day + 1, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_x_log10() + scale_colour_manual(values = PAL) +
      labs(x = "치료 후 일수 + 1 (log)", y = "진단 시점 대비 비율",
           title = "하나의 수용체, 네 개의 시계",
           subtitle = "분비와 전사는 며칠 안에 정착하고, 세포 부피는 2개월, 세포 수는 수년") +
      theme_prl()
  })

  # ---- tab 3 --------------------------------------------------------------
  output$p_pk <- renderPlot({
    d <- sim() %>% filter(time >= PRESIM)
    dd <- d %>% transmute(day = time - PRESIM,
                          `혈장 카베르골린 (nM)` = CABNM,
                          `뇌하수체 biophase (nM)` = CAB_E,
                          `혈장 브로모크립틴 (nM)` = BRC_C/10700*1e6/654.6,
                          `혈장 퀴나골라이드 (nM)` = QUI_C/1200*1e6/395.6) %>%
      pivot_longer(-day) %>% filter(value > 1e-9)
    if (!nrow(dd)) return(NULL)
    ggplot(dd, aes(day, value, colour = name)) + geom_line(linewidth = 0.8) +
      scale_colour_manual(values = PAL) +
      labs(x = "치료 후 일수", y = "농도 (nM)",
           title = "왜 주 1회로 충분한가",
           subtitle = "biophase는 혈장의 약 60배 농도이고 반감기가 ~4일이라 거의 정주에 가깝다") +
      theme_prl()
  })

  output$txt_pk <- renderText({
    d <- sim() %>% filter(time > max(time) - 28)
    sprintf(paste0("  최근 4주 혈장 카베르골린   평균 %.4f nM (= %.1f pg/mL)\n",
                   "  최근 4주 biophase          평균 %.3f nM (D2 Ki 0.70 nM의 %.1f배)\n",
                   "  biophase 최고/최저 비      %.2f\n",
                   "  5-HT2B 점유(혈장 구동)     평균 %.4f\n",
                   "  D3 점유(혈장 구동)         평균 %.4f\n"),
            mean(d$CABNM), mean(d$CABNM)*451.6, mean(d$CAB_E),
            mean(d$CAB_E)/0.7,
            ifelse(min(d$CAB_E) > 0, max(d$CAB_E)/min(d$CAB_E), NA),
            mean(d$OCC5HT), mean(d$OCCD3))
  })

  # ---- tab 4 --------------------------------------------------------------
  output$p_prl <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year,
                          `생물학적 (monomer)` = PRLB,
                          `면역반응 analyte` = PRLIMM,
                          `보고된 값 (assay)` = PRLMEAS_,
                          `1:100 희석 후` = PRLDIL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_y_log10() + scale_colour_manual(values = PAL) + pres_line() +
      geom_hline(yintercept = 25, linetype = "33", colour = "grey50") +
      labs(x = "년", y = "프로락틴 (ng/mL, log)",
           title = "네 개의 서로 다른 프로락틴",
           subtitle = "곡선 사이의 간격이 hook effect(보고값이 낮아짐)와 macroprolactin(높아짐)") +
      theme_prl()
  })

  output$p_hook <- renderPlot({
    a <- 10^seq(1, 5, length.out = 300)
    dd <- data.frame(analyte = a,
                     `보고된 값` = a/(1 + (a/4000)^4),
                     `참값 (기준선)` = a) %>% pivot_longer(-analyte)
    cur <- prs(sim(), "PRLIMM")
    ggplot(dd, aes(analyte, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_x_log10() + scale_y_log10() + scale_colour_manual(values = PAL[c(2,8)]) +
      geom_vline(xintercept = cur, linetype = "22", colour = PAL[3]) +
      annotate("text", x = cur, y = 20, label = " 이 환자", hjust = 0,
               colour = PAL[3], size = 3.5) +
      labs(x = "실제 면역반응 analyte (ng/mL, log)", y = "보고되는 값 (ng/mL, log)",
           title = "2점 샌드위치 측정의 hook",
           subtitle = "약 3000 ng/mL에서 정점, 그 이상에서는 항원 과잉으로 신호가 붕괴") +
      theme_prl()
  })

  # ---- tab 5 --------------------------------------------------------------
  output$p_tum <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `종양 부피 (MRI, mL)` = TVOL_,
                          `세포량 (mL)` = CELLN,
                          `평균 세포 부피 (상대)` = VCELL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "부피 먼저, 세포 수는 나중에",
           subtitle = "세포 부피는 몇 주 안에 되돌아오지만 사라진 세포 수는 되돌아오지 않는다") +
      theme_prl()
  })

  output$p_clone <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `민감 클론 (mL)` = NS, `저항 클론 (mL)` = NR,
                          `저항 분율 (%)` = 100*NR/(NS+NR+1e-12)) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL[c(3,2,4)]) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "클론 선택 (Darwinian escape)",
           subtitle = "일정한 선택압 아래에서 D2R 낮은 클론의 분율이 서서히 증가") +
      theme_prl()
  })

  # ---- tab 6 --------------------------------------------------------------
  output$p_vf <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `시야 MD (dB)` = VFMD,
                          `가역 전도차단 (dB)` = -VFR,
                          `비가역 축삭 손실 (dB)` = -AXL,
                          `유효 압박력` = CEFF_) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "시야: 되돌아오는 부분과 빚으로 남는 부분",
           subtitle = "축삭 손실은 압박 역치를 넘긴 시간에 비례해 누적되며 회복되지 않는다") +
      theme_prl()
  })

  output$p_hypo <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `뇌하수체 기능저하` = HYPOP,
                          `코르티솔 예비능` = CORT, `FT4` = FT4, `IGF-1` = IGF1) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "년", y = "정상 대비", title = "압박성 뇌하수체 기능저하",
           subtitle = "회복 속도는 발생 속도보다 느리게 설정되어 있다 (수술성 손실은 영구)") +
      theme_prl()
  })

  # ---- tab 7 --------------------------------------------------------------
  output$p_hpg <- renderPlot({
    d <- sim(); male <- input$sex == "male"
    dd <- d %>% transmute(year, `KNDy/kisspeptin` = KISS, `GnRH 박동` = GNRH,
                          `LH` = LH, `FSH` = FSH,
                          `성호르몬 (정상 대비)` = if (male) TST/550 else E2G/60) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "년", y = "정상 대비",
           title = "프로락틴이 불임을 만드는 경로",
           subtitle = "프로락틴 → STAT5 → Kiss1 억제 → GnRH 박동 감소 → LH/FSH → 성호르몬") +
      theme_prl()
  })

  output$p_repro <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `배란 능력` = OVF, `정자 생산 지표` = SPZ,
                          `무배란/무월경 확률 (%)` = AMENP/100,
                          `유즙분비 지표 (%)` = GALA/100) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "년", y = "0-1", title = "생식 관련 임상 종점") + theme_prl()
  })

  # ---- tab 8 --------------------------------------------------------------
  output$p_bone <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `요추 BMD (g/cm2)` = BMD,
                          `비가역 소실 (g/cm2)` = BLOSSI,
                          `T-score` = TSCORE,
                          `척추 골절 확률 (%)` = PFRACT) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "뼈: 프로락틴이 정상화된 뒤에도 남는 병태",
           subtitle = "손실의 일부는 ratchet으로 저장되어 어떤 시점에도 회복되지 않는다") +
      theme_prl()
  })

  output$p_met <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `체중 (kg)` = BW, `HOMA-IR` = IR,
                          `골흡수 (OCF)` = OCF, `골형성 (OBF)` = OBF) %>%
      pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() + guides(colour = "none") +
      labs(x = "년", y = NULL, title = "대사 및 골대사 회전") + theme_prl()
  })

  # ---- tab 9 --------------------------------------------------------------
  output$p_safe <- renderPlot({
    d <- sim()
    dd <- d %>% transmute(year, `5-HT2B 점유 (혈장)` = OCC5HT,
                          `판막 섬유화 부담` = VALV/100,
                          `중등도 이상 TR 확률 (%)` = PTR/100,
                          `충동조절장애 확률 (%)` = PICD/100,
                          `구역 지표 (내성 반영)` = NAUS/100) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      scale_colour_manual(values = PAL) + pres_line() +
      labs(x = "년", y = "0-1 척도",
           title = "효능은 biophase, 판막은 혈장 — 둘은 비례하지 않는다",
           subtitle = "충동조절장애는 D3 점유에서 나오므로 ergot 골격을 피해도 줄지 않는다") +
      theme_prl()
  })

  output$p_sweep <- renderPlot({
    i <- reactiveValuesToList(input); i$horizon <- 5
    kis <- c(1.2, 3.6, 12, 36, 120, 1200)
    res <- do.call(rbind, lapply(kis, function(k) {
      j <- i; j$ki5ht <- k; d <- simulate(j)
      data.frame(ki = k, PRL = d$PRLB[nrow(d)], valve = d$VALV[nrow(d)],
                 PTR = d$PTR[nrow(d)])
    }))
    res2 <- res %>% transmute(ki, `프로락틴 (ng/mL)` = PRL,
                              `판막 부담` = valve,
                              `TR 확률 (%)` = PTR) %>% pivot_longer(-ki)
    ggplot(res2, aes(ki, value, colour = name)) +
      geom_line(linewidth = 0.9) + geom_point() +
      facet_wrap(~name, scales = "free_y") + scale_x_log10() +
      scale_colour_manual(values = PAL) + guides(colour = "none") +
      labs(x = "5-HT2B Ki (nM, log — 오른쪽이 더 선택적)", y = NULL,
           title = "선택성 4자리수 스윕",
           subtitle = "프로락틴 제어는 변하지 않고 판막 위험만 붕괴한다") +
      theme_prl()
  })

  # ---- tab 10 -------------------------------------------------------------
  cmp_runs <- reactive({
    i <- reactiveValuesToList(input)
    mk <- function(lab, mod_fn) { j <- mod_fn(i); d <- simulate(j); d$arm <- lab; d }
    switch(input$cmp,
      "cabergoline vs bromocriptine vs quinagolide" = rbind(
        mk("cabergoline 1 mg/wk", function(j){j$da<-"cabergoline";j$cabdose<-1;j}),
        mk("bromocriptine 7.5 mg/d", function(j){j$da<-"bromocriptine";j$brcdose<-7.5;j}),
        mk("quinagolide 300 ug/d", function(j){j$da<-"quinagolide";j$quidose<-300;j}),
        mk("무치료", function(j){j$da<-"none";j})),
      "cabergoline 용량 0.25 / 0.5 / 1 / 2 / 3.5 mg/주" = do.call(rbind,
        lapply(c(0.25,0.5,1,2,3.5), function(x)
          mk(sprintf("%.2f mg/wk", x),
             function(j){j$da<-"cabergoline";j$cabdose<-x;j}))),
      "부분 저항 vs 진성 저항 (± 증량)" = rbind(
        mk("부분 저항 0.5 mg/wk", function(j){j$d2rs<-0.15;j$cabdose<-0.5;j$da<-"cabergoline";j}),
        mk("부분 저항 3.5 mg/wk", function(j){j$d2rs<-0.15;j$cabdose<-3.5;j$da<-"cabergoline";j}),
        mk("진성 저항 0.5 mg/wk", function(j){j$d2rs<-0.04;j$cabdose<-0.5;j$da<-"cabergoline";j}),
        mk("진성 저항 3.5 mg/wk", function(j){j$d2rs<-0.04;j$cabdose<-3.5;j$da<-"cabergoline";j})),
      "치료 지연 0 / 1 / 2 / 4년" = do.call(rbind,
        lapply(c(0, 365, 730, 1460), function(x)
          mk(sprintf("%.0f년 지연", x/365),
             function(j){j$startday<-x;j$da<-"cabergoline";j$cabdose<-1;j}))),
      "중단 후 잔존 부피별 재발" = do.call(rbind,
        lapply(c(0.05, 0.2, 0.6, 1.6), function(x)
          mk(sprintf("초기 %.2f mL", x),
             function(j){j$ns0<-x;j$d2rs<-0.5;j$da<-"cabergoline";j$cabdose<-1;
                         j$stopyr<-3;j$horizon<-max(j$horizon,12);j})))
    )
  })

  output$p_cmp <- renderPlot({
    d <- cmp_runs()
    dd <- d %>% transmute(year, arm, `프로락틴 (ng/mL)` = PRLB,
                          `종양 부피 (mL)` = TVOL_,
                          `시야 MD (dB)` = VFMD, `T-score` = TSCORE) %>%
      pivot_longer(-c(year, arm))
    ggplot(dd, aes(year, value, colour = arm)) + geom_line(linewidth = 0.85) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() +
      labs(x = "년", y = NULL, title = input$cmp) + theme_prl()
  })

  output$tbl_cmp <- renderDT({
    d <- cmp_runs()
    s <- d %>% group_by(arm) %>%
      summarise(`진단시 PRL` = round(PRLB[which.min(abs(time - PRESIM))], 1),
                `최종 PRL` = round(last(PRLB), 1),
                `최종 부피 mL` = round(last(TVOL_), 3),
                `축소 %` = round(100*(1 - last(TVOL_)/TVOL_[which.min(abs(time-PRESIM))]), 0),
                `최종 MD dB` = round(last(VFMD), 1),
                `최종 T-score` = round(last(TSCORE), 2),
                `TR 확률 %` = round(last(PTR), 2), .groups = "drop")
    datatable(s, rownames = FALSE, options = list(dom = "t"))
  })

  # ---- tab 11 -------------------------------------------------------------
  output$p_wd <- renderPlot({
    i <- reactiveValuesToList(input)
    i$da <- "cabergoline"; i$cabdose <- max(i$cabdose, 1); i$stopyr <- 3
    i$horizon <- max(i$horizon, 12)
    d <- simulate(i)
    dd <- d %>% transmute(year, `프로락틴 (ng/mL)` = PRLB,
                          `종양 부피 (mL)` = TVOL_, `세포량 (mL)` = CELLN,
                          `평균 세포 부피` = VCELL) %>% pivot_longer(-year)
    ggplot(dd, aes(year, value, colour = name)) + geom_line(linewidth = 0.9) +
      facet_wrap(~name, scales = "free_y") + scale_colour_manual(values = PAL) +
      pres_line() +
      geom_vline(xintercept = (PRESIM + 3*365)/365, linetype = "22",
                 colour = PAL[2]) +
      guides(colour = "none") +
      labs(x = "년", y = NULL,
           title = "3년 치료 후 중단 (빨간 점선 = 중단 시점)",
           subtitle = "부피는 몇 주 안에 재팽창하지만 그것은 재성장이 아니라 세포 재팽윤이다") +
      theme_prl()
  })

  output$txt_wd <- renderText({
    i <- reactiveValuesToList(input)
    i$da <- "cabergoline"; i$cabdose <- max(i$cabdose, 1); i$stopyr <- 3
    i$horizon <- max(i$horizon, 12)
    d <- simulate(i); tstop <- PRESIM + 3*365
    aft <- d$time > tstop + 30
    irec <- which(d$PRLB[aft] > 25)[1]
    paste0(
      sprintf("  중단 시점 세포량            %.4f mL\n", atd(d,"CELLN",tstop)),
      sprintf("  중단 시점 프로락틴          %.1f ng/mL\n", atd(d,"PRLB",tstop)),
      sprintf("  중단 30일 후 부피 변화      %+.1f%% (세포 수 변화 %+.1f%%)\n",
              100*(atd(d,"TVOL_",tstop+30)/atd(d,"TVOL_",tstop) - 1),
              100*(atd(d,"CELLN",tstop+30)/atd(d,"CELLN",tstop) - 1)),
      sprintf("  생화학적 재발까지          %s\n",
              ifelse(is.na(irec), "관찰 기간 내 없음",
                     sprintf("%.1f년", (d$time[aft][irec] - tstop)/365))),
      "\n  이 모델은 완치를 만들지 못한다. 잔존 세포가 있으면 언제나 재발하며,\n",
      "  잔존이 작을수록 재발이 늦어질 뿐이다. 이는 기계론적 지도가 세운\n",
      "  가설(내인성 도파민이 작은 잔존을 붙잡는다)을 오히려 반박하는 결과이며,\n",
      "  단기 루프가 프로락틴으로 구동되기 때문에 잔존이 작을 때 내인성 톤이\n",
      "  가장 약해지기 때문이다. 모델 파일의 진단 D10을 참조하라.\n")
  })
}

shinyApp(ui, server)
