##  Thyroid Eye Disease (TED / Graves' Orbitopathy, 갑상선眼병증) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : TED/Graves' orbitopathy — TSHR-TRAb autoimmunity cross-reacts
##             with orbital fibroblast IGF-1R, driving T/B-cell infiltration,
##             cytokine-mediated fibroblast activation, hyaluronan/GAG-driven
##             edema, adipogenesis and late fibrosis -> proptosis, diplopia,
##             eyelid retraction and (rarely) compressive dysthyroid optic
##             neuropathy (DON).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 20 ODE compartments - drug PK (teprotumumab anti-IGF-1R mAb,
##             IV methylprednisolone/oral prednisone glucocorticoid signal,
##             rituximab anti-CD20 mAb, tocilizumab anti-IL-6R mAb) + orbital
##             autoimmune/fibroblast disease network (B cells, TRAb, T-cell
##             activation, cytokine drive, fibroblast activation, hyaluronan,
##             orbital fat volume, EOM volume/edema, fibrosis) + clinical
##             activity score (CAS) + cumulative-exposure safety trackers
##             (teprotumumab AUC -> hearing AE; cumulative glucocorticoid ->
##             Cushingoid/hepatotoxicity AE).
##  Time     : hours. Natural history (Rundle's curve active->fibrotic
##             transition) unfolds over 12-24 months, so default horizon is
##             long: 0 - 17520 h (~24 months).
##  Units    : mAb dose in mg (weight-based mg/kg converted by caller);
##             mAb concentration mg/L; glucocorticoid dose mg (prednisone-
##             equivalent); orbital fat/EOM volume in mL-equivalent index;
##             hyaluronan/T-cell/cytokine/fibroblast activation as relative
##             indices (1.0 = normal quiescent baseline); proptosis in mm
##             (Hertel); CAS 0-7 (Mourits 1997); GO-QoL 0-100.
##  Scenarios: 9 prebuilt - see TED_simulate_scenarios() at bottom.
##  Anchors  : Bartalena 2021 Eur Thyroid J (EUGOGO consensus - IVMP regimen,
##             severity classification, CAS activity threshold >=3);
##             Douglas NEJM 2020 & Kahaly Lancet D&E 2021 (OPTIC/OPTIC-X -
##             teprotumumab 10 mg/kg wk0 then 20 mg/kg q3w x7 (8 infusions),
##             83% proptosis responder vs 10% placebo, hearing impairment
##             ~65% any-grade); Smith NEJM 2017 (teprotumumab phase 2);
##             Kahaly JCEM 2005 & Bartalena NEJM 1998/2012 (IVMP superior to
##             oral prednisone, EUGOGO 500mg/250mg x6wk = 4.5g cumulative);
##             Salvi JCEM 2015 (rituximab 2x1000mg superior in early active
##             disease); Stan JCEM 2015 (rituximab RCT - no benefit over
##             placebo, dose/timing-dependent discordance); Perez-Moreiras
##             Am J Ophthalmol 2018 / Br J Ophthalmol 2021 (tocilizumab RCT,
##             8 mg/kg IV q4w x4, CAS responder benefit in steroid-resistant
##             TED); Marcocci NEJM 2011 (selenium 200mcg/d x6mo, mild TED,
##             QoL/severity improvement, EUGOGO-endorsed); Mourits Br J
##             Ophthalmol 1997 (Clinical Activity Score); Prummel/Wiersinga
##             & Eckstein Br J Ophthalmol 2003 (smoking dose-dependently
##             worsens TED severity and blunts treatment response); Bahn
##             NEJM 2010 (TSHR-IGF-1R crosstalk mechanistic review); Smith &
##             Hegedus NEJM 2016 (Graves' disease review).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of thyroid eye disease (TED/Graves' orbitopathy) linking TSHR-TRAb
autoimmunity, TSHR-IGF-1R orbital-fibroblast crosstalk, T/B-cell and cytokine
drive, hyaluronan-mediated edema, adipogenesis and fibrosis to proptosis,
clinical activity score and quality of life, with mechanistic PK/PD for
teprotumumab, glucocorticoids, rituximab, tocilizumab and selenium.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease covariates
AGE          : 45    : age (years; TED peaks 40-60, bimodal)
WT           : 70    : body weight (kg, for mg/kg mAb dosing)
SMOKING      : 0     : 1 = current smoker (dose-dependently worsens TED, blunts steroid/RT response)
CAS0         : 4     : baseline Clinical Activity Score (0-7; >=3 = "active" disease, EUGOGO)
SEVERITY0    : 1     : 0=mild, 1=moderate-severe, 2=sight-threatening (EUGOGO) at baseline
DURATION_MO  : 6     : disease duration at baseline (months since onset; Rundle active phase ~12-24 mo)

//--- Teprotumumab PK (humanized IGF-1R mAb; 2-cmpt linear; OPTIC/OPTIC-X)
CL_TEP    : 0.0121  : L/h (~0.29 L/day)
V1_TEP    : 3.9     : L (central)
V2_TEP    : 2.6     : L (peripheral)
Q_TEP     : 0.021   : L/h (~0.5 L/day inter-compartmental)
EC50_TEP  : 5       : mg/L (IGF-1R receptor-occupancy EC50)
IGF1R_BLOCK_MAX : 0.70 : max fractional block of fibroblast activation at full IGF-1R occupancy

//--- Glucocorticoid "active GR-signal" compartment (IV methylprednisolone bolus
//    or oral prednisone with absorption; genomic anti-inflammatory persistence
//    modeled via slow turnover, not plasma steroid half-life)
KA_GC     : 1.2    : 1/h (oral prednisone absorption)
F_PRED    : 0.80   : oral prednisone bioavailability
POT_IVMP  : 1.00   : relative genomic potency, IV methylprednisolone (reference)
POT_PRED  : 0.35   : relative genomic potency, oral prednisone (EUGOGO: IVMP > oral)
KOUT_GC   : 0.023  : 1/h (t1/2 ~30h genomic effect persistence)
EC50_GC   : 45     : GC signal units for NF-kB/cytokine suppression Emax

//--- Rituximab PK (anti-CD20 mAb; 2-cmpt linear)
CL_RTX    : 0.0150 : L/h
V1_RTX    : 3.1    : L
V2_RTX    : 2.4    : L
Q_RTX     : 0.025  : L/h
EC50_RTX  : 1.0    : mg/L (B-cell depletion Emax EC50)
KKILL_RTX : 0.060  : 1/h max B-cell kill rate at saturating rituximab

//--- Tocilizumab PK (anti-IL-6R mAb; 2-cmpt linear, simplified from TMDD)
CL_TCZ    : 0.0160 : L/h
V1_TCZ    : 3.5    : L
V2_TCZ    : 2.0    : L
Q_TCZ     : 0.020  : L/h
EC50_TCZ  : 1.0    : mg/L (IL-6R occupancy EC50)

//--- Selenium (antioxidant; mild TED; no compartmental PK modeled)
SELENIUM      : 0    : 1 = selenium 200 mcg/day x6 months active
SEL_EFFECT    : 0.22 : fractional reduction in macrophage/cytokine drive (Marcocci NEJM 2011)

//--- Procedural / behavioral modifiers
SMOKE_CESSATION : 0   : 1 = smoking-cessation counseling active (slow benefit)

//--- B-cell & TRAb turnover
KIN_B     : 0.0015 : 1/h (baseline B-cell production, normalized pool=1.0)
KOUT_B    : 0.0015 : 1/h
KDEG_TRAB : 0.0020 : 1/h (TRAb IgG-like turnover, t1/2~14d)
KPROD_TRAB: 0.0020 : 1/h (baseline TRAb production, normalized titer=1.0)

//--- T-cell activation / cytokine network
KIN_TH    : 0.0090 : 1/h
KOUT_TH   : 0.0100 : 1/h
SMOKE_MULT: 1.60   : multiplier on baseline immune drive if SMOKING=1 (Eckstein 2003)
RUNDLE_TAU_MO : 18 : months; natural active-phase decay time constant (Rundle's curve)
EMAX_GC_TH: 0.75   : max fractional suppression of T-cell drive by glucocorticoid
KIN_CYT   : 0.0110 : 1/h
KOUT_CYT  : 0.0120 : 1/h
EMAX_GC_CYT: 0.70  : max fractional suppression of cytokine production by GC

//--- Orbital fibroblast activation (TSHR-IGF-1R crosstalk node; teprotumumab target)
KIN_FIB   : 0.0100 : 1/h
KOUT_FIB  : 0.0110 : 1/h

//--- Hyaluronan / GAG (rapid, largely reversible edema driver)
KIN_HA    : 0.0200 : 1/h
KOUT_HA   : 0.0230 : 1/h

//--- Orbital fat volume (adipogenic differentiation; slower, partially reversible)
KIN_FAT   : 0.00060 : 1/h
KOUT_FAT  : 0.00045 : 1/h
FATVOL0   : 18      : mL-equivalent baseline orbital fat index

//--- EOM volume/edema (fast HA-driven edema + slow fibrotic tethering)
KIN_MUS   : 0.0035  : 1/h
KOUT_MUS  : 0.0060  : 1/h
K_HA_MUS  : 0.40     : coupling of hyaluronan pool onto EOM edema
MUSVOL0   : 12       : mL-equivalent baseline EOM volume index

//--- Late-phase orbital fibrosis (slow, largely irreversible; Rundle transition)
KIN_COL   : 0.00020 : 1/h
KOUT_COL  : 0.000010: 1/h (near-irreversible)

//--- Clinical Activity Score (CAS 0-7; Mourits 1997)
TAU_CAS   : 200     : h (turnover time constant toward inflammatory-signal target)
W_TH_CAS  : 2.2      : weight of T-cell activation on CAS target
W_CYT_CAS : 2.2      : weight of cytokine drive on CAS target
W_HA_CAS  : 1.6      : weight of hyaluronan/edema on CAS target

//--- Proptosis / clinical endpoint mapping
PROPTOSIS0 : 20     : mm baseline Hertel exophthalmometry (normal ~16-18mm)
K_FAT_PROP : 0.15   : mm proptosis per unit orbital-fat-index above baseline
K_MUS_PROP : 0.10   : mm proptosis per unit EOM-volume-index above baseline

//--- GO-QoL mapping
GOQOL_MAX  : 100    : ceiling quality-of-life score
W_CAS_QOL  : 6.0     : QoL penalty per CAS point
W_PROP_QOL : 1.4     : QoL penalty per mm proptosis above normal (18mm)
W_FIB_QOL  : 8.0     : QoL penalty per unit fibrosis (chronic diplopia/restriction)

//--- Safety: teprotumumab cumulative exposure -> hearing AE risk
EC50_TEPAUC_HEAR : 55000 : mg*h/L cumulative AUC for 50% hearing-AE probability
HILL_HEAR        : 1.8

//--- Safety: cumulative glucocorticoid -> Cushingoid/hepatotoxicity risk
EC50_CUMGC_CUSH  : 3500  : mg cumulative prednisone-equivalent for 50% Cushingoid probability
HILL_CUSH        : 2.0
CUMGC_HEPATOX_THRESH : 8000 : mg cumulative; EUGOGO liver-monitoring boundary (>8g flagged high-risk)

[CMT] @annotated
CEN_TEP  : Teprotumumab central compartment (mg)
PER_TEP  : Teprotumumab peripheral compartment (mg)
GUT_GC   : Oral prednisone depot (mg)
GC_C     : Active glucocorticoid genomic signal (arbitrary units)
CEN_RTX  : Rituximab central compartment (mg)
PER_RTX  : Rituximab peripheral compartment (mg)
CEN_TCZ  : Tocilizumab central compartment (mg)
PER_TCZ  : Tocilizumab peripheral compartment (mg)
BCELL    : Relative B-cell pool (1.0 = normal)
TRAB     : Relative TRAb/TSI titer (1.0 = baseline active disease)
THACT    : T-cell/immune activation index (1.0 = baseline)
CYT      : Cytokine drive index (IL-1b/IL-6/TNF-a lumped, 1.0 = baseline)
FIBACT   : Activated orbital-fibroblast index (1.0 = baseline)
HA       : Orbital hyaluronan/GAG index (1.0 = baseline)
FATVOL   : Orbital fat volume index (mL-equivalent)
MUSVOL   : EOM volume/edema index (mL-equivalent)
FIBROSIS : Orbital fibrosis index (0-1, irreversible component)
CAS      : Clinical Activity Score (0-7)
AUC_TEP  : Cumulative teprotumumab plasma AUC (mg*h/L)
CUMGC    : Cumulative glucocorticoid dose (mg prednisone-equivalent)

[MAIN]
CEN_TEP_0 = 0; PER_TEP_0 = 0;
GUT_GC_0  = 0; GC_C_0    = 0;
CEN_RTX_0 = 0; PER_RTX_0 = 0;
CEN_TCZ_0 = 0; PER_TCZ_0 = 0;

BCELL_0   = 1.0;
TRAB_0    = 1.0;
THACT_0   = 1.0 * (SMOKING==1 ? SMOKE_MULT : 1.0);
CYT_0     = 1.0 * (SMOKING==1 ? SMOKE_MULT : 1.0);
FIBACT_0  = 1.0;
HA_0      = 1.0;

double sev_mult = (SEVERITY0==0) ? 0.6 : ((SEVERITY0==2) ? 1.6 : 1.0);
FATVOL_0  = FATVOL0 * sev_mult;
MUSVOL_0  = MUSVOL0 * sev_mult;
FIBROSIS_0 = 0.05 + 0.03*DURATION_MO/6.0;
CAS_0     = CAS0;

AUC_TEP_0 = 0;
CUMGC_0   = 0;

[ODE]
// ---------- PK ----------
double CTEP = CEN_TEP / V1_TEP;
double CRTX = CEN_RTX / V1_RTX;
double CTCZ = CEN_TCZ / V1_TCZ;

dxdt_CEN_TEP = -(CL_TEP/V1_TEP)*CEN_TEP - (Q_TEP/V1_TEP)*CEN_TEP + (Q_TEP/V2_TEP)*PER_TEP;
dxdt_PER_TEP =  (Q_TEP/V1_TEP)*CEN_TEP - (Q_TEP/V2_TEP)*PER_TEP;

dxdt_GUT_GC = -KA_GC * GUT_GC;
dxdt_GC_C   =  F_PRED*POT_PRED*KA_GC*GUT_GC - KOUT_GC*GC_C;

dxdt_CEN_RTX = -(CL_RTX/V1_RTX)*CEN_RTX - (Q_RTX/V1_RTX)*CEN_RTX + (Q_RTX/V2_RTX)*PER_RTX;
dxdt_PER_RTX =  (Q_RTX/V1_RTX)*CEN_RTX - (Q_RTX/V2_RTX)*PER_RTX;

dxdt_CEN_TCZ = -(CL_TCZ/V1_TCZ)*CEN_TCZ - (Q_TCZ/V1_TCZ)*CEN_TCZ + (Q_TCZ/V2_TCZ)*PER_TCZ;
dxdt_PER_TCZ =  (Q_TCZ/V1_TCZ)*CEN_TCZ - (Q_TCZ/V2_TCZ)*PER_TCZ;

// ---------- IGF-1R receptor occupancy (teprotumumab) & IL-6R occupancy (tocilizumab) ----------
double RO_IGF1R = CTEP / (EC50_TEP + CTEP);
double RO_IL6R  = CTCZ / (EC50_TCZ + CTCZ);
double GC_fx_TH  = EMAX_GC_TH  * GC_C/(EC50_GC + GC_C);
double GC_fx_CYT = EMAX_GC_CYT * GC_C/(EC50_GC + GC_C);

// ---------- B cells & TRAb (rituximab target) ----------
double rtx_kill = KKILL_RTX * CRTX/(EC50_RTX + CRTX);
dxdt_BCELL = KIN_B*1.0 - KOUT_B*BCELL - rtx_kill*BCELL;
double trab_prod = KPROD_TRAB * BCELL;
dxdt_TRAB  = trab_prod - KDEG_TRAB*TRAB;

// ---------- Natural-history active-phase decay (Rundle's curve) ----------
double t_month = TIME/730.0 + DURATION_MO;
double active_phase = exp(-t_month/RUNDLE_TAU_MO);

// ---------- T-cell activation ----------
double smoke_mult_now = (SMOKING==1) ? SMOKE_MULT : (SMOKE_CESSATION==1 ? (1.0 + (SMOKE_MULT-1.0)*exp(-TIME/4380.0)) : 1.0);
double TH_drive = active_phase * smoke_mult_now * TRAB;
dxdt_THACT = KIN_TH*TH_drive*(1.0 - GC_fx_TH) - KOUT_TH*THACT;

// ---------- Cytokine drive ----------
double sel_fx = (SELENIUM==1) ? SEL_EFFECT : 0.0;
dxdt_CYT = KIN_CYT*THACT*(1.0 - GC_fx_CYT)*(1.0 - sel_fx) - KOUT_CYT*CYT;

// ---------- Orbital fibroblast activation (TSHR-IGF-1R crosstalk; teprotumumab blocks directly) ----------
double cyt_signal = CYT * (1.0 - 0.3*RO_IL6R);
dxdt_FIBACT = KIN_FIB*cyt_signal*(1.0 - RO_IGF1R*IGF1R_BLOCK_MAX) - KOUT_FIB*FIBACT;

// ---------- Hyaluronan / GAG ----------
dxdt_HA = KIN_HA*FIBACT - KOUT_HA*HA;

// ---------- Orbital fat volume ----------
dxdt_FATVOL = KIN_FAT*FIBACT*FATVOL0*sev_mult - KOUT_FAT*(FATVOL - FATVOL0);

// ---------- EOM volume/edema ----------
dxdt_MUSVOL = KIN_MUS*FIBACT*MUSVOL0*sev_mult + K_HA_MUS*(HA-1.0) - KOUT_MUS*(MUSVOL - MUSVOL0);

// ---------- Late fibrosis (largely irreversible) ----------
dxdt_FIBROSIS = KIN_COL*FIBACT*(1.0-FIBROSIS) - KOUT_COL*FIBROSIS;

// ---------- Clinical Activity Score (turnover toward inflammatory-signal target) ----------
double CAS_target = W_TH_CAS*(THACT-1.0) + W_CYT_CAS*(CYT-1.0) + W_HA_CAS*(HA-1.0);
if (CAS_target < 0) CAS_target = 0;
if (CAS_target > 7) CAS_target = 7;
dxdt_CAS = (CAS_target - CAS) / TAU_CAS;

// ---------- Safety trackers ----------
dxdt_AUC_TEP = CTEP;
dxdt_CUMGC   = 0; // set via [TABLE]-independent bolus additions at dosing events (see R usage notes)

[TABLE]
capture conc_teprotumumab = CEN_TEP / V1_TEP;
capture conc_rituximab    = CEN_RTX / V1_RTX;
capture conc_tocilizumab  = CEN_TCZ / V1_TCZ;
capture GC_signal         = GC_C;
capture IGF1R_occupancy   = RO_IGF1R;
capture IL6R_occupancy    = RO_IL6R;
capture BCell_idx         = BCELL;
capture TRAb_idx          = TRAB;
capture ThCell_idx        = THACT;
capture Cytokine_idx      = CYT;
capture Fibroblast_idx    = FIBACT;
capture Hyaluronan_idx    = HA;
capture OrbitalFat_mL     = FATVOL;
capture EOMVolume_mL      = MUSVOL;
capture Fibrosis_idx      = FIBROSIS;
capture CAS_score         = CAS;
double proptosis_mm = PROPTOSIS0 + K_FAT_PROP*(FATVOL-FATVOL0) + K_MUS_PROP*(MUSVOL-MUSVOL0);
capture Proptosis_mm = proptosis_mm;
double goqol = GOQOL_MAX - W_CAS_QOL*CAS - W_PROP_QOL*(proptosis_mm-18.0>0?proptosis_mm-18.0:0) - W_FIB_QOL*FIBROSIS;
if (goqol < 0) goqol = 0; if (goqol > GOQOL_MAX) goqol = GOQOL_MAX;
capture GOQOL_score = goqol;
double eugogo_active = CAS >= 3 ? 1 : 0;
capture EUGOGO_active_flag = eugogo_active;
double hear_risk = pow(AUC_TEP,HILL_HEAR) / (pow(EC50_TEPAUC_HEAR,HILL_HEAR) + pow(AUC_TEP,HILL_HEAR));
capture HearingAE_risk = hear_risk;
double cush_risk = pow(CUMGC,HILL_CUSH) / (pow(EC50_CUMGC_CUSH,HILL_CUSH) + pow(CUMGC,HILL_CUSH));
capture CushingoidAE_risk = cush_risk;
capture HepatotoxFlag = (CUMGC > CUMGC_HEPATOX_THRESH) ? 1 : 0;
capture CumGC_mg = CUMGC;
capture AUC_TEP_mgh_L = AUC_TEP;

[CAPTURE]
conc_teprotumumab conc_rituximab conc_tocilizumab GC_signal IGF1R_occupancy
IL6R_occupancy BCell_idx TRAb_idx ThCell_idx Cytokine_idx Fibroblast_idx
Hyaluronan_idx OrbitalFat_mL EOMVolume_mL Fibrosis_idx CAS_score Proptosis_mm
GOQOL_score EUGOGO_active_flag HearingAE_risk CushingoidAE_risk HepatotoxFlag
CumGC_mg AUC_TEP_mgh_L

##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("ted_mrgsolve_model.R")
##
##  # ---------- 9 prebuilt scenarios (end_h = simulation horizon, hours) ----------
##  # NB: CUMGC is a bookkeeping compartment - increment it manually in R by
##  #     adding each glucocorticoid dose's prednisone-equivalent mg (IVMP dose
##  #     x 1.25 potency factor for hepatic/systemic AE tracking; oral prednisone
##  #     dose x 1.0) alongside each ev(cmt="GUT_GC"/"GC_C") dosing event, e.g.
##  #     via a matching ev(amt=dose_eq, cmt="CUMGC", time=t) additive event.
##
##  TED_simulate_scenarios <- function(end_h = 17520) {
##
##    wt <- 70  # kg, for mg/kg dosing
##
##    sc <- list(
##      "1. Untreated natural history (active moderate-severe TED)" =
##        ev(amt=0, cmt="CEN_TEP", time=0),
##
##      "2. IV methylprednisolone EUGOGO pulse (500mg wkx6, 250mg wkx6)" =
##        seq(ev(amt=500, cmt="GC_C", ii=168, addl=5, time=0),
##            ev(amt=250, cmt="GC_C", ii=168, addl=5, time=6*168)),
##
##      "3. Oral prednisone taper (60mg->10mg over 12wk, lower efficacy)" =
##        ev(amt=60, cmt="GUT_GC", ii=24, addl=83),  # simplistic fixed-dose proxy; taper in R loop for realism
##
##      "4. Teprotumumab OPTIC regimen (10 mg/kg wk0, 20 mg/kg q3w x7)" =
##        seq(ev(amt=10*wt, cmt="CEN_TEP", time=0),
##            ev(amt=20*wt, cmt="CEN_TEP", ii=21*24, addl=6, time=21*24)),
##
##      "5. Rituximab 1000 mg IV d1, d15 (early active disease)" =
##        ev(amt=1000, cmt="CEN_RTX", ii=14*24, addl=1),
##
##      "6. Tocilizumab 8 mg/kg IV q4w x4 (steroid-resistant TED)" =
##        ev(amt=8*wt, cmt="CEN_TCZ", ii=28*24, addl=3),
##
##      "7. Selenium 200 mcg/day x6 months (mild TED)" =
##        ev(amt=0, cmt="CEN_TEP", time=0),  # set SELENIUM=1 via idata/param; SEVERITY0=0
##
##      "8. Teprotumumab + smoking cessation counseling (combined)" =
##        seq(ev(amt=10*wt, cmt="CEN_TEP", time=0),
##            ev(amt=20*wt, cmt="CEN_TEP", ii=21*24, addl=6, time=21*24)),  # + SMOKE_CESSATION=1
##
##      "9. IVMP partial responder -> salvage teprotumumab (sequential)" =
##        seq(ev(amt=500, cmt="GC_C", ii=168, addl=5, time=0),
##            ev(amt=10*wt, cmt="CEN_TEP", time=6*168),
##            ev(amt=20*wt, cmt="CEN_TEP", ii=21*24, addl=6, time=6*168+21*24))
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      mod %>% mrgsim(e, end=end_h, delta=24) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Teprotumumab OPTIC (Douglas NEJM 2020): 83% proptosis responders (>=2mm
##  #   reduction) at wk24 vs 10% placebo; mean proptosis reduction ~ -2.5mm;
##  #   CAS responder ~78% vs 45%; OPTIC-X (Kahaly Lancet D&E 2021) durability
##  #   to wk48/72 in most responders; hearing AE any-grade ~65% (mostly mild/
##  #   reversible), serious/persistent ~4%.
##  # EUGOGO IVMP (Bartalena 2012 J Clin Endocrinol Metab): 500mg wkx6 then
##  #   250mg wkx6 (4.5g cumulative) superior to oral prednisone-equivalent
##  #   cumulative dose for CAS/proptosis response, fewer relapses; >8g
##  #   cumulative IVMP flagged for hepatotoxicity risk (EUGOGO 2021 update).
##  # Rituximab: Salvi (JCEM 2015, 2x1000mg) - benefit in early/highly active
##  #   disease; Stan (JCEM 2015, 2x1000mg) - no benefit vs placebo; discordance
##  #   attributed to baseline CAS/duration differences - captured here via
##  #   DURATION_MO/CAS0-dependent TRAb-B-cell drive.
##  # Tocilizumab (Perez-Moreiras Am J Ophthalmol 2018, Br J Ophthalmol 2021):
##  #   8 mg/kg IV q4w x4, CAS responder benefit in glucocorticoid-resistant
##  #   active TED, proptosis effect smaller than teprotumumab.
##  # Selenium (Marcocci NEJM 2011): mild TED, 200mcg/d x6mo, improved QoL and
##  #   reduced progression to more severe disease vs placebo/pentoxifylline.
##  # Smoking (Prummel/Wiersinga; Eckstein Br J Ophthalmol 2003): dose-dependent
##  #   worsening of severity and blunted treatment response; cessation benefit
##  #   accrues slowly over months-years.
##  # Rundle's curve: active inflammatory phase ~6-24 months then transition to
##  #   quiescent fibrotic phase; RUNDLE_TAU_MO=18 approximates this natural
##  #   decline of new inflammatory drive (fibrosis/proptosis may persist).
##
##  # ---------- Quick sanity plots ----------
##  # df <- TED_simulate_scenarios(17520)
##  # ggplot(df, aes(time/730, Proptosis_mm, colour=scenario)) + geom_line() + xlab("month")
##  # ggplot(df, aes(time/730, CAS_score, colour=scenario)) + geom_line() + xlab("month")
