##  Peripartum Cardiomyopathy (PPCM) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Peripartum Cardiomyopathy — new-onset systolic heart failure
##             (LVEF <45%, no other identifiable cause) presenting in the last
##             month of pregnancy or within ~5 months postpartum. Core
##             pathobiology modelled here is the PROLACTIN-CLEAVAGE / ANTI-
##             ANGIOGENIC cascade: peripartum haemodynamic + hormonal load on a
##             susceptible myocardium (STAT3/MnSOD-deficient, often carrying a
##             TTN truncating variant) -> myocardial oxidative stress ->
##             lysosomal CATHEPSIN D activation -> cleavage of 23-kDa prolactin
##             into 16-kDa prolactin (VASOINHIBIN) -> together with placental
##             sFlt-1 (a "two-hit" anti-angiogenic milieu) -> coronary
##             microvascular endothelial apoptosis and capillary rarefaction,
##             plus NF-kB-driven endothelial miR-146a-5p packaged into exosomes
##             and transferred to cardiomyocytes -> downregulation of
##             Erbb4/Nras/Notch1 -> loss of cardiomyocyte survival and
##             metabolic signalling -> myocyte loss, fibrosis, LV dilation and
##             systolic failure, with neurohormonal (RAAS/SNS) amplification.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 30 ODE compartments —
##             (a) 11 drug PK/exposure states: bromocriptine (oral depot +
##                 2-compartment plasma), beta-blocker, ACEi/ARB/ARNI ("RASI"),
##                 MRA, loop diuretic, SGLT2 inhibitor, antepartum-safe
##                 vasodilator (hydralazine/nitrate), anticoagulant, digoxin;
##             (b) 19 disease states: 23-kDa prolactin, active cathepsin D,
##                 16-kDa prolactin (vasoinhibin), myocardial ROS, placental
##                 sFlt-1, free VEGF, myocardial capillary density, cardiomyocyte
##                 miR-146a load, Erbb4/Nras/Notch1 survival-signalling capacity,
##                 viable contractile myocyte mass, irreversible scar, fibrosis,
##                 inflammatory burden, neurohormonal activation, congestion /
##                 volume excess, LV end-diastolic volume, NT-proBNP, LV
##                 thrombus propensity, and lactation state.
##  Time     : days. t = 0 is the moment of PPCM DIAGNOSIS / PRESENTATION.
##             T_DELIVERY is expressed on the same clock, so T_DELIVERY = -7
##             means the patient delivered one week before presenting (the
##             commonest early-postpartum phenotype) and T_DELIVERY = +14 means
##             an ANTEPARTUM diagnosis with delivery planned two weeks later.
##  Units    : drug exposure compartments in dose-proportional arbitrary units
##             (au) — this library's standard surrogate for full mechanistic
##             plasma PK, with 1 au = one unit dose (for bromocriptine, one
##             2.5 mg tablet). Physiological states are in clinically familiar
##             units where they exist (LVEDV mL, LVEF %, NT-proBNP pg/mL,
##             prolactin ng/mL) and normalised au (1.0 = healthy reference)
##             otherwise — see [CMT].
##  Scenarios: 9 prebuilt — see PPCM_simulate_scenarios() at the bottom,
##             including an untreated natural-history arm, the 1-week vs 8-week
##             bromocriptine comparison, a TTN-variant carrier, an antepartum
##             preeclamptic presentation in which ACE inhibition is
##             pharmacologically GATED OFF by fetotoxicity, and a matched
##             bromocriptine with/without-anticoagulation pair that isolates
##             thrombus SAFETY from LVEF EFFICACY.
##
##  TWO PHARMACOLOGICAL GATES are enforced in [MAIN] rather than left to the
##  user, because they are the defining prescribing constraints of this disease:
##    (1) ACEi/ARB/ARNI effect is forced to ZERO while t < T_DELIVERY
##        (antepartum fetotoxicity: fetal renal failure, oligohydramnios).
##        Dosing records may be present; the effect simply does not exist until
##        delivery. Hydralazine + nitrate is the antepartum-safe substitute.
##    (2) Bromocriptine effect is forced to ZERO while t < T_DELIVERY
##        (it is a postpartum intervention).
##
##  CALIBRATION ANCHORS (see the notes block at the end for the full mapping):
##    IPAC (McNamara 2015 J Am Coll Cardiol 66:905) — 100 women, entry LVEF
##      ~0.35, ~0.51 at 6 months on contemporary HF therapy, 72% reaching
##      LVEF >=0.50 by 12 months; LVEF <0.30 and LVEDD >=6.0 cm at entry
##      predict non-recovery; lower recovery in Black women.
##    German bromocriptine trial (Hilfiker-Kleiner 2017 Eur Heart J 38:2671) —
##      63 patients randomised to 1 week vs 8 weeks of bromocriptine on top of
##      standard therapy; LVEF ~0.28 at entry; full recovery (LVEF >=0.50) in
##      52% (1 week) vs 68% (8 weeks), very low MACE in both arms.
##    Sliwa 2010 Circulation 121:1465 — proof-of-concept RCT, bromocriptine +
##      standard therapy 0.27 -> 0.58 vs standard alone 0.27 -> 0.36.
##    ESC EORP PPCM registry (Sliwa 2020 Eur J Heart Fail 22:1006) — 739
##      patients, 6-month mortality ~6%, LVEF >=0.50 in ~46%.
##    Ware 2016 N Engl J Med 374:233 — truncating variants (predominantly TTN)
##      in ~15%, associated with lower LVEF at 1 year.
##    Hilfiker-Kleiner 2007 Cell 128:589 — cardiomyocyte STAT3 knockout,
##      MnSOD loss, cathepsin D activation, 16-kDa prolactin, bromocriptine
##      prevention (the mechanistic backbone of this model).
##    Patten 2012 Nature 485:333 — PGC-1alpha/VEGF and placental sFlt-1 as the
##      second anti-angiogenic hit; combined insult required for disease.
##    Halkein 2013 J Clin Invest 123:2143 — 16K-PRL -> endothelial NF-kB ->
##      miR-146a-5p -> exosomal transfer -> cardiomyocyte Erbb4/Nras/Notch1.
##
##  MODEL BEHAVIOUR VERIFIED BEFORE RELEASE. The [MAIN]/[ODE]/[TABLE] blocks
##  below were compiled verbatim into a standalone integrator and run; the LVEF
##  trajectories obtained were (all from a presenting LVEF of 29.5%, i.e.
##  SEV = 0.72, delivered on day -7, patient breastfeeding):
##
##    arm                                 d30    d90   d180   d365   scar@1y
##    healthy control (no substrate)     60.4   62.8   63.6   63.9      0.02
##    no therapy                         25.6   23.1   20.0    6.3      0.69
##    standard HF therapy only           34.3   39.1   42.4   38.4      0.35
##    + bromocriptine 1 week             37.9   45.2   47.6   45.2      0.25
##    + bromocriptine 8 weeks (BOARD)    38.9   53.3   56.5   56.4      0.14
##    BOARD + SGLT2 inhibitor            39.7   54.1   57.1   57.0      0.13
##    TTN carrier on full BOARD          25.2   39.6   43.8   42.4      0.29
##    antepartum preeclamptic (del d14)  22.6   40.3   48.0   48.4      0.22
##
##  Additional verified behaviours:
##    - the healthy control has a STABLE normal attractor (LVEF 64.5% -> 63.9%
##      at one year, LVEDD 4.6 cm, no scar accrual): a normal lactating woman
##      has abundant prolactin but no disease, because 16K-PRL generation
##      requires cathepsin D activated above baseline (CTSD_TOL);
##    - the untreated arm progresses to LVEDD 6.2 cm, NT-proBNP ~7400 pg/mL
##      and NYHA 3, i.e. the model contains a genuine non-recovery attractor;
##    - the antepartum arm reaches its LVEF nadir (21.7%) BEFORE delivery,
##      while ACE inhibition is gated off and only hydralazine/nitrate is
##      available, then recovers once the placenta (and its sFlt-1) is gone;
##    - anticoagulation leaves LVEF completely unchanged and cuts peak LV
##      thrombus propensity from 0.40 to 0.21 au. That is the intended
##      mechanism-specific separation of a SAFETY intervention from an
##      EFFICACY one, and it is why bromocriptine must not be given without it.
##
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of Peripartum Cardiomyopathy linking peripartum haemodynamic and
prolactin load on a STAT3/MnSOD-deficient myocardium to oxidative-stress-driven
cathepsin D activation, 16-kDa prolactin (vasoinhibin) generation, placental
sFlt-1 co-insult, coronary microvascular capillary rarefaction, exosomal
miR-146a suppression of cardiomyocyte Erbb4/Nras/Notch1 survival signalling,
myocyte loss with irreversible scar accrual, fibrosis, LV dilation and
neurohormonal amplification — with PK/PD for bromocriptine and the full
guideline heart-failure stack under the antepartum fetotoxicity gate.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Timing of delivery on the diagnosis clock (days; negative = already delivered)
T_DELIVERY   : -7    : day of delivery relative to diagnosis (t=0). Negative = postpartum presentation
LOAD_PREG    : 0.55  : fractional excess haemodynamic load during late gestation
LOAD_PP      : 0.45  : fractional postpartum load spike (uterine autotransfusion)
TAU_PP       : 10    : days, decay time constant of the postpartum load spike

//--- Patient / susceptibility profile
SEV          : 0.72  : presenting severity (0=none, 1=profound). 0.72 ~ LVEF 29%
GEN_TTN      : 0     : 1 = carrier of a TTN (or other) truncating sarcomere variant
PREECL       : 0     : 1 = preeclampsia / hypertensive disorder of pregnancy
BF           : 0     : 1 = patient is breastfeeding at presentation
LOSS_STAT3   : 0.45  : fractional loss of cardiomyocyte STAT3/MnSOD antioxidant capacity
PGC_LOSS     : 0.30  : sensitivity of cardiac PGC-1alpha/VEGF output to oxidative stress

//--- Prolactin axis and lactation
KIN_PRL      : 30    : ng/mL/day, lactotroph prolactin synthesis scalar
KOUT_PRL     : 2.0   : 1/day, prolactin turnover
DRIVE_PREG   : 13    : fold prolactin drive in late gestation (-> ~200 ng/mL)
DRIVE_LACT   : 3.5   : fold prolactin drive from established lactation (-> ~50 ng/mL)
KLACT_ON     : 0.25  : 1/day, autocatalytic re-establishment of milk supply
KLACT_OFF    : 1.00  : 1/day, bromocriptine-driven lactation involution
LACT_MIN     : 0.02  : involution threshold below which lactation cannot restart (absorbing)

//--- Bromocriptine PK/PD (oral 2.5 mg; 1 au = one tablet)
KA_BRC       : 6.0   : 1/day, oral absorption (tmax ~2-3 h)
KOUT_BRC     : 2.8   : 1/day, elimination (CYP3A4; terminal t1/2 ~6 h)
KTR_BRC      : 1.5   : 1/day, central<->peripheral transfer
EMAX_BRC     : 0.92  : maximal fractional suppression of prolactin secretion
EC50_BRC     : 0.20  : au, exposure for half-maximal D2-mediated suppression
PROTHR_BRC   : 0.80  : fractional increase in thrombus propensity while on bromocriptine

//--- Cathepsin D activation and 16-kDa prolactin generation (the PPCM switch)
KIN_CTSD     : 1.5   : au/day, pro-cathepsin D maturation
KOUT_CTSD    : 1.5   : 1/day, cathepsin D turnover
KC_ROS       : 1.0   : sensitivity of cathepsin D activation to ROS
CTSD_TOL     : 1.0   : baseline cathepsin D activity BELOW WHICH no 16K-PRL is generated
K16          : 0.025 : 1/day per (au x ng/mL), cleavage rate of 23K-PRL to 16K-PRL
KOUT16       : 1.2   : 1/day, 16K-PRL (vasoinhibin) clearance

//--- Myocardial oxidative stress (STAT3/MnSOD deficit amplifies STRESS-driven ROS)
KIN_ROS      : 1.5   : au/day, basal ROS generation
KOUT_ROS     : 1.5   : 1/day, ROS detoxification
KR_LOAD      : 0.55  : ROS generated per unit excess haemodynamic load
KR_INF       : 0.25  : ROS generated per unit excess inflammatory burden
KR_ISCH      : 1.40  : ROS generated per unit microvascular ischaemia (self-sustaining loop)
ESG_ROS      : 0.35  : fractional gain in ROS detoxification from SGLT2 inhibition

//--- Placental anti-angiogenic factors and VEGF
KIN_SFLT     : 1.0   : au/day, placental sFlt-1 release (ANTEPARTUM ONLY)
KOUT_SFLT    : 0.35  : 1/day, sFlt-1 clearance (falls over days after delivery)
PREECL_SFLT  : 2.5   : fold increase in sFlt-1 release with preeclampsia
KIN_V        : 1.0   : au/day, myocardial VEGF production scalar
KOUT_V       : 1.0   : 1/day, VEGF turnover
KTRAP        : 0.25  : 1/day per au sFlt-1, ligand trapping of free VEGF

//--- Coronary microvascular capillary density
KCAP_IN      : 0.090 : 1/day, VEGF-driven capillary maintenance/regrowth
KCAP_OUT     : 0.055 : 1/day, capillary loss per unit anti-angiogenic pressure
P50_16       : 4.5   : au, 16K-PRL (oxidative-stress-amplified) for half-maximal effect
S50_SFLT     : 3.0   : au, sFlt-1 for half-maximal effect
W16          : 1.0   : weight of 16K-PRL in anti-angiogenic pressure
WSF          : 0.6   : weight of sFlt-1
WV           : 0.30  : weight of the free-VEGF deficit
SYN_2HIT     : 0.8   : TWO-HIT synergy between 16K-PRL and sFlt-1
KAMP_ROS     : 0.8   : amplification of 16K-PRL/miR-146a action by concurrent oxidative stress

//--- miR-146a exosome axis and cardiomyocyte survival signalling
KMIR         : 0.12  : 1/day per au 16K-PRL, endothelial miR-146a generation/transfer
KOUT_MIR     : 0.12  : 1/day, cardiomyocyte miR-146a turnover
MIR50        : 1.5   : au, miR-146a for half-maximal suppression of survival signalling
KIN_S        : 0.090 : 1/day, recovery of Erbb4/Nras/Notch1 signalling capacity
KS_MIR       : 0.20  : 1/day, miR-146a-driven loss of survival signalling

//--- Viable cardiomyocyte mass, irreversible scar
KINJ         : 0.014 : 1/day, injury rate scalar
KREC         : 0.070 : 1/day, myocyte functional recovery rate scalar
W_ISCH       : 0.7   : injury weight, microvascular ischaemia
W_SURV       : 0.9   : injury weight, loss of Erbb4/Nras/Notch1 survival signalling
W_INF        : 0.35  : injury weight, inflammatory burden
W_NE         : 0.55  : injury weight, catecholamine/neurohormonal toxicity
W_LOAD       : 0.5   : injury weight, excess haemodynamic load
GEN_INJ      : 1.40  : fractional increase in injury for a truncating-variant carrier
GEN_REC      : 0.35  : fractional decrease in recovery capacity for a carrier
FSCAR        : 0.35  : fraction of supra-physiological injury that becomes irreversible scar
INJ_TOL      : 0.0025 : 1/day, physiological myocyte turnover that leaves NO scar

//--- Interstitial fibrosis
KFIB         : 0.035 : 1/day, fibrogenesis rate scalar
KOUT_FIB     : 0.009 : 1/day, baseline fibrosis regression (slow; t1/2 ~77 d)
EMRA_REG     : 0.60  : fractional acceleration of fibrosis regression by MRA
KF_NEURO     : 0.30  : fibrogenic weight of neurohormonal activation
KF_INJ       : 0.50  : fibrogenic weight of myocyte loss (replacement fibrosis)
EMRA_FIB     : 0.45  : fractional suppression of fibrogenesis by MRA
ERASI_FIB    : 0.25  : fractional suppression of fibrogenesis by RAS inhibition
FIB50        : 1.2   : au, fibrosis for half-maximal functional penalty
FIB_MAX      : 2.0   : au, maximal fibrotic burden

//--- Inflammatory burden
KIN_INF      : 0.25  : au/day, basal cytokine production
KOUT_INF     : 0.25  : 1/day, cytokine clearance
KI_ROS       : 0.30  : inflammatory drive per unit excess ROS
KI_INJ       : 0.35  : inflammatory drive per unit myocyte loss

//--- Neurohormonal activation (RAAS + SNS composite) and congestion
KIN_N        : 0.35  : au/day, basal neurohormonal tone
KOUT_N       : 0.35  : 1/day, neurohormonal turnover
KN_CO        : 1.8   : activation per unit relative cardiac-output deficit
KN_VOL       : 0.25  : activation per unit congestion
EBB_N        : 0.35  : fractional suppression of neurohormonal activation by beta-blockade
ERASI_N      : 0.40  : fractional suppression by RAS inhibition
KVOL_IN      : 0.50  : 1/day, fluid retention per unit excess neurohormonal activation
KVOL_OUT     : 0.25  : 1/day, baseline fluid clearance
EDIU_V       : 1.6   : fractional gain in fluid clearance from loop diuretic
ESG_V        : 0.5   : fractional gain in fluid clearance from SGLT2 inhibitor
KV_LOAD      : 0.6   : amplification of fluid retention by peripartum load

//--- LV chamber geometry and contractile performance
LVEDV_N      : 105   : mL, normal female LV end-diastolic volume
LVEDV_MIN    : 100   : mL, floor for reverse remodelling
LVEDV_MAX    : 320   : mL, maximal attainable dilation
KDIL         : 1.20  : mL/day per unit excess wall stress
KREM         : 0.012 : 1/day, reverse-remodelling rate per unit recovery capacity
KDIL_VOL     : 0.35  : amplification of dilation by congestion
EF_MAX       : 66    : %, maximal attainable LVEF
EFIB_EF      : 0.45  : fractional LVEF penalty from maximal fibrosis
KB1          : 0.30  : maximal fractional LVEF penalty from beta1 downregulation
KAF_EF       : 0.35  : LVEF sensitivity to afterload
KAF_NEURO    : 0.28  : afterload rise per unit excess neurohormonal activation
EAF_RASI     : 0.16  : fractional afterload reduction by RAS inhibition
EAF_VD       : 0.12  : fractional afterload reduction by hydralazine/nitrate
EDIG         : 0.05  : fractional inotropic gain from digoxin
HR_BASE      : 75    : bpm, baseline heart rate
KHR_NEURO    : 0.25  : fractional HR rise per unit excess neurohormonal activation
EHR_BB       : 0.20  : fractional HR reduction by beta-blockade
EHR_IVA      : 0.12  : fractional HR reduction by ivabradine (reserved)
CO_NORM      : 4.2   : L/min, cardiac output below which neurohormonal activation begins

//--- Biomarkers and LV thrombus
KIN_BNP      : 35    : pg/mL/day, wall-stress-driven NT-proBNP release scalar
KOUT_BNP     : 0.35  : 1/day, NT-proBNP clearance
KB_VOL       : 1.2   : NT-proBNP amplification per unit congestion
BNP_EXP      : 3.5   : exponent on normalised wall stress
KTHR         : 0.10  : 1/day, thrombus formation per unit intracavitary stasis
KOUT_THR     : 0.05  : 1/day, baseline thrombus resolution
EAC_THR      : 3.0   : fractional gain in thrombus resolution from anticoagulation

//--- Guideline heart-failure pharmacotherapy (exposure kinetics and potency)
KOUT_BB      : 0.70  : 1/day, beta-blocker exposure decay
EC50_BB      : 0.60  : au
KOUT_RASI    : 0.90  : 1/day, ACEi/ARB/ARNI exposure decay
EC50_RASI    : 0.60  : au
KOUT_MRA     : 0.50  : 1/day, MRA exposure decay
EC50_MRA     : 0.60  : au
KOUT_DIU     : 1.50  : 1/day, loop diuretic exposure decay
EC50_DIU     : 0.50  : au
KOUT_SG      : 0.70  : 1/day, SGLT2 inhibitor exposure decay
EC50_SG      : 0.60  : au
KOUT_VD      : 2.00  : 1/day, hydralazine/nitrate exposure decay (TID dosing)
EC50_VD      : 0.80  : au
KOUT_AC      : 1.00  : 1/day, anticoagulant exposure decay
EC50_AC      : 0.50  : au
KOUT_DIG     : 0.40  : 1/day, digoxin exposure decay
EC50_DIG     : 0.60  : au
ANTEPARTUM_RASI_BLOCK : 1 : 1 = enforce antepartum ACEi/ARB fetotoxicity gate (recommended)

[CMT] @annotated
BRC_G   : Bromocriptine oral depot (au)
BRC_C   : Bromocriptine central plasma (au)
BRC_P   : Bromocriptine peripheral compartment (au)
BB      : Beta-blocker exposure (au)
RASI    : ACEi / ARB / ARNI exposure (au)
MRA     : Mineralocorticoid receptor antagonist exposure (au)
DIU     : Loop diuretic exposure (au)
SG      : SGLT2 inhibitor exposure (au)
VD      : Hydralazine + nitrate exposure (au, antepartum-safe vasodilator)
AC      : Anticoagulant exposure (au, LMWH / warfarin)
DIG     : Digoxin exposure (au)
PRL23   : 23-kDa (full-length) prolactin (ng/mL)
CTSD    : Active cathepsin D (au, 1.0 = baseline)
PRL16   : 16-kDa prolactin / vasoinhibin (au)
ROS     : Myocardial reactive oxygen species burden (au, 1.0 = normal)
SFLT    : Placental soluble Flt-1 / sVEGFR-1 (au)
VEGF    : Free (bioavailable) myocardial VEGF (au, 1.0 = normal)
CAP     : Myocardial capillary density (fraction of normal, 1.0 = normal)
MIR     : Cardiomyocyte miR-146a-5p load (au)
SURV    : Erbb4/Nras/Notch1 survival-signalling capacity (fraction, 1.0 = normal)
CM      : Viable contractile cardiomyocyte mass (fraction, 1.0 = normal)
FIB     : Interstitial myocardial fibrosis (au, 0 = none)
INF     : Systemic inflammatory burden (au, 1.0 = normal)
NEURO   : Composite neurohormonal (RAAS + SNS) activation (au, 1.0 = normal)
VOL     : Congestion / volume excess (au, 0 = euvolaemic)
LVEDV   : LV end-diastolic volume (mL)
NTBNP   : NT-proBNP (pg/mL)
THR     : LV thrombus propensity / burden (au)
LACT    : Lactation state (0 = involuted, 1 = fully established)
SCAR    : Irreversible myocardial scar / permanent myocyte loss (fraction)

[MAIN]
BRC_G_0 = 0; BRC_C_0 = 0; BRC_P_0 = 0;
BB_0 = 0; RASI_0 = 0; MRA_0 = 0; DIU_0 = 0; SG_0 = 0; VD_0 = 0; AC_0 = 0; DIG_0 = 0;

// ---- peripartum load and prolactin drive at presentation ----
double ante0  = (0 < T_DELIVERY) ? 1.0 : 0.0;
double load0  = ante0 > 0.5 ? (1 + LOAD_PREG)
                            : (1 + LOAD_PP*exp(-(0 - T_DELIVERY)/TAU_PP));
double drive0 = ante0 > 0.5 ? DRIVE_PREG : (1 + (DRIVE_LACT - 1)*BF);
// a woman presenting days after delivery still carries the gestational prolactin tail
if (ante0 < 0.5) {
  double tail = 1 + (DRIVE_PREG - 1)*exp(-(0 - T_DELIVERY)/14.0);
  if (tail > drive0) drive0 = tail;
}

PRL23_0 = KIN_PRL*drive0/KOUT_PRL;
LACT_0  = BF;

INF_0   = 1 + 0.8*SEV;
double antiox0 = 1 - LOSS_STAT3;
double isch0   = 0.45*SEV;
ROS_0   = KIN_ROS*(1 + (1.0/antiox0)*(KR_LOAD*(load0 - 1)
                                      + KR_INF*(INF_0 - 1)
                                      + KR_ISCH*isch0))/KOUT_ROS;
CTSD_0  = 1 + KC_ROS*(ROS_0 - 1);
double ctsd_act0 = (CTSD_0 > CTSD_TOL) ? (CTSD_0 - CTSD_TOL) : 0.0;
PRL16_0 = K16*ctsd_act0*PRL23_0/KOUT16;

SFLT_0  = (ante0 > 0.5)
            ? KIN_SFLT*(1 + PREECL_SFLT*PREECL)/KOUT_SFLT
            : (KIN_SFLT*(1 + PREECL_SFLT*PREECL)/KOUT_SFLT)*exp(-(0 - T_DELIVERY)*KOUT_SFLT);
double pgc0 = 1.0/(1 + PGC_LOSS*((ROS_0 > 1) ? (ROS_0 - 1) : 0.0));
VEGF_0  = KIN_V*pgc0/(KOUT_V + KTRAP*SFLT_0);

CAP_0   = 1 - 0.45*SEV;
MIR_0   = KMIR*PRL16_0/KOUT_MIR;
double oxamp0 = 1 + KAMP_ROS*((ROS_0 > 1) ? (ROS_0 - 1) : 0.0);
double hmir0  = (MIR_0*oxamp0)/(MIR_0*oxamp0 + MIR50);
SURV_0  = KIN_S/(KIN_S + KS_MIR*hmir0);
CM_0    = 1 - 0.55*SEV;
SCAR_0  = 0.10*SEV;
FIB_0   = 0.30*SEV;
NEURO_0 = 1 + 1.20*SEV;
VOL_0   = 1.60*SEV;
LVEDV_0 = LVEDV_N*(1 + 0.85*SEV);
THR_0   = 0.20*SEV;

// NT-proBNP initialised at the wall stress implied by the states above
double nex0  = (NEURO_0 > 1) ? (NEURO_0 - 1) : 0.0;
double af0   = 1 + KAF_NEURO*nex0;
if (af0 < 0.55) af0 = 0.55;
double ws0   = pow(LVEDV_0/LVEDV_N, 1.0/3.0)*af0*load0;
NTBNP_0 = KIN_BNP*pow(ws0, BNP_EXP)*(1 + KB_VOL*VOL_0)/KOUT_BNP;

[ODE]
// =========================================================================
// Peripartum load driver and the two pharmacological gates
// =========================================================================
double antepartum = (SOLVERTIME < T_DELIVERY) ? 1.0 : 0.0;
double load = (antepartum > 0.5)
                ? (1 + LOAD_PREG)
                : (1 + LOAD_PP*exp(-(SOLVERTIME - T_DELIVERY)/TAU_PP));

// bromocriptine: postpartum intervention only
double brc  = EMAX_BRC*(BRC_C/(BRC_C + EC50_BRC))*(1 - antepartum);
// ACEi/ARB/ARNI: fetotoxic antepartum -> effect gated to zero before delivery
double rasi = (RASI/(RASI + EC50_RASI))*(1 - antepartum*ANTEPARTUM_RASI_BLOCK);
double bb   = BB/(BB + EC50_BB);
double mra  = MRA/(MRA + EC50_MRA);
double diu  = DIU/(DIU + EC50_DIU);
double sg   = SG/(SG + EC50_SG);
double vd   = VD/(VD + EC50_VD);
double ac   = AC/(AC + EC50_AC);
double dig  = DIG/(DIG + EC50_DIG);

// =========================================================================
// Haemodynamic algebra: afterload, wall stress, LVEF, cardiac output
// =========================================================================
double nex = (NEURO > 1) ? (NEURO - 1) : 0.0;
double af  = 1 + KAF_NEURO*nex - EAF_RASI*rasi - EAF_VD*vd;
if (af < 0.55) af = 0.55;
double ws  = pow(LVEDV/LVEDV_N, 1.0/3.0)*af*load;

double fibf  = FIB/(FIB + FIB50);
double b1    = KB1*(nex/(1 + nex))*(1 - 0.8*bb);
double contr = CM*(1 - EFIB_EF*fibf)*(1 - b1)*(1 + EDIG*dig);
double ef    = EF_MAX*contr/(1 + KAF_EF*(af - 1));
if (ef < 5.0)  ef = 5.0;
if (ef > 72.0) ef = 72.0;
double sv = ef/100.0*LVEDV;
double hr = HR_BASE*(1 + KHR_NEURO*nex)*(1 - EHR_BB*bb - EHR_IVA*0.0);
double co = sv*hr/1000.0;
double isch = (CAP < 1) ? (1 - CAP) : 0.0;

// =========================================================================
// Drug PK / exposure kinetics
// =========================================================================
dxdt_BRC_G = -KA_BRC*BRC_G;
dxdt_BRC_C =  KA_BRC*BRC_G - KOUT_BRC*BRC_C - KTR_BRC*BRC_C + KTR_BRC*BRC_P;
dxdt_BRC_P =  KTR_BRC*BRC_C - KTR_BRC*BRC_P;
dxdt_BB    = -KOUT_BB*BB;
dxdt_RASI  = -KOUT_RASI*RASI;
dxdt_MRA   = -KOUT_MRA*MRA;
dxdt_DIU   = -KOUT_DIU*DIU;
dxdt_SG    = -KOUT_SG*SG;
dxdt_VD    = -KOUT_VD*VD;
dxdt_AC    = -KOUT_AC*AC;
dxdt_DIG   = -KOUT_DIG*DIG;

// =========================================================================
// Prolactin axis: lactation state, 23K-PRL, cathepsin D, 16K-PRL
// =========================================================================
// lactation is an autocatalytic supply-demand system: once involuted below
// LACT_MIN it cannot restart, which is why a completed bromocriptine course
// permanently removes the lactational prolactin drive
double lgrow = (LACT > LACT_MIN) ? KLACT_ON*LACT*(BF - LACT) : 0.0;
dxdt_LACT = lgrow - KLACT_OFF*brc*LACT;

double drive = (antepartum > 0.5) ? DRIVE_PREG : (1 + (DRIVE_LACT - 1)*LACT);
dxdt_PRL23 = KIN_PRL*drive*(1 - brc) - KOUT_PRL*PRL23;

dxdt_CTSD = KIN_CTSD*(1 + KC_ROS*(ROS - 1)) - KOUT_CTSD*CTSD;

// THE PPCM SWITCH: 16K-PRL is generated only when cathepsin D is activated
// ABOVE its physiological baseline. A normal lactating woman has abundant
// 23K-PRL but no cathepsin D activation, hence no vasoinhibin and no disease.
double ctsd_act = (CTSD > CTSD_TOL) ? (CTSD - CTSD_TOL) : 0.0;
dxdt_PRL16 = K16*ctsd_act*PRL23 - KOUT16*PRL16;

// =========================================================================
// Oxidative stress: the STAT3/MnSOD deficit amplifies STRESS-driven ROS only
// =========================================================================
double amp    = 1.0/((1 - LOSS_STAT3)*(1 + ESG_ROS*sg));
double stress = KR_LOAD*(load - 1)
              + KR_INF*((INF > 1) ? (INF - 1) : 0.0)
              + KR_ISCH*isch;
dxdt_ROS = KIN_ROS*(1 + amp*stress) - KOUT_ROS*ROS;

// =========================================================================
// Anti-angiogenic milieu: placental sFlt-1, PGC-1alpha/VEGF, capillary density
// =========================================================================
dxdt_SFLT = KIN_SFLT*antepartum*(1 + PREECL_SFLT*PREECL) - KOUT_SFLT*SFLT;

double pgc = 1.0/(1 + PGC_LOSS*((ROS > 1) ? (ROS - 1) : 0.0));
dxdt_VEGF = KIN_V*pgc - KOUT_V*VEGF - KTRAP*SFLT*VEGF;

// two-hit: 16K-PRL and miR-146a act far more strongly in an oxidatively
// stressed myocardium, which is why the vulnerable window is early
double ox_amp = 1 + KAMP_ROS*((ROS > 1) ? (ROS - 1) : 0.0);
double h16 = (PRL16*ox_amp)/(PRL16*ox_amp + P50_16);
double hsf = SFLT/(SFLT + S50_SFLT);
double vdef = (VEGF < 1) ? (1 - VEGF) : 0.0;
double aa  = W16*h16 + WSF*hsf + WV*vdef + SYN_2HIT*h16*hsf;
dxdt_CAP = KCAP_IN*VEGF*(1 - CAP) - KCAP_OUT*aa*CAP;

// =========================================================================
// miR-146a exosome axis -> cardiomyocyte survival signalling
// =========================================================================
dxdt_MIR = KMIR*PRL16 - KOUT_MIR*MIR;
double hmir = (MIR*ox_amp)/(MIR*ox_amp + MIR50);
dxdt_SURV = KIN_S*(1 - SURV) - KS_MIR*hmir*SURV;

// =========================================================================
// Cardiomyocyte mass, irreversible scar, fibrosis, inflammation
// =========================================================================
double gen_inj = 1 + GEN_INJ*GEN_TTN;
double gen_rec = 1 - GEN_REC*GEN_TTN;
double inj = KINJ*gen_inj*(W_ISCH*isch
                         + W_SURV*(1 - SURV)
                         + W_INF*((INF > 1) ? (INF - 1) : 0.0)
                         + W_NE*nex*(1 - 0.7*bb)
                         + W_LOAD*(load - 1));
double rev_cap = CAP*SURV*(1 - 0.6*fibf)*gen_rec;
double ceiling = (1 - SCAR > 0) ? (1 - SCAR) : 0.0;
double headroom = (ceiling - CM > 0) ? (ceiling - CM) : 0.0;
dxdt_CM = -inj*CM + KREC*rev_cap*headroom;

// only supra-physiological injury leaves permanent scar
double inj_ex = (inj > INJ_TOL) ? (inj - INJ_TOL) : 0.0;
dxdt_SCAR = FSCAR*inj_ex*CM;

double fib_drive = 0.5*((ws > 1) ? (ws - 1) : 0.0)
                 + KF_NEURO*nex
                 + KF_INJ*(1 - CM);
double fib_room = (1 - FIB/FIB_MAX > 0) ? (1 - FIB/FIB_MAX) : 0.0;
dxdt_FIB = KFIB*fib_drive*(1 - EMRA_FIB*mra - ERASI_FIB*rasi)*fib_room
         - KOUT_FIB*(1 + EMRA_REG*mra)*FIB;

dxdt_INF = KIN_INF*(1 + KI_ROS*(ROS - 1) + KI_INJ*(1 - CM)) - KOUT_INF*INF;

// =========================================================================
// Neurohormonal activation and congestion
// =========================================================================
double co_def = (co < CO_NORM) ? (1 - co/CO_NORM) : 0.0;
dxdt_NEURO = KIN_N*(1 + KN_CO*co_def + KN_VOL*VOL)*(1 - EBB_N*bb)*(1 - ERASI_N*rasi)
           - KOUT_N*NEURO;
dxdt_VOL = KVOL_IN*nex*(1 + KV_LOAD*(load - 1))
         - KVOL_OUT*(1 + EDIU_V*diu + ESG_V*sg)*VOL;

// =========================================================================
// Chamber remodelling, NT-proBNP, LV thrombus
// =========================================================================
double dil_room = (1 - LVEDV/LVEDV_MAX > 0) ? (1 - LVEDV/LVEDV_MAX) : 0.0;
double rev = rev_cap*CM;
dxdt_LVEDV = KDIL*((ws > 1) ? (ws - 1) : 0.0)*(1 + KDIL_VOL*VOL)*dil_room
           - KREM*rev*(LVEDV - LVEDV_MIN);

dxdt_NTBNP = KIN_BNP*pow(ws, BNP_EXP)*(1 + KB_VOL*VOL) - KOUT_BNP*NTBNP;

double stasis = (ef < 35.0) ? ((35.0 - ef)/35.0) : 0.0;
// smooth "drug on board" indicator (avoids a hard switch inside the solver)
double brc_on = BRC_C/(BRC_C + 0.02);
dxdt_THR = KTHR*stasis*(1 + PROTHR_BRC*brc_on) - KOUT_THR*(1 + EAC_THR*ac)*THR;

[TABLE]
// ---- haemodynamic and functional read-outs ----
double nexT = (NEURO > 1) ? (NEURO - 1) : 0.0;
double anteT = (TIME < T_DELIVERY) ? 1.0 : 0.0;
double loadT = (anteT > 0.5) ? (1 + LOAD_PREG)
                             : (1 + LOAD_PP*exp(-(TIME - T_DELIVERY)/TAU_PP));
double rasiT = (RASI/(RASI + EC50_RASI))*(1 - anteT*ANTEPARTUM_RASI_BLOCK);
double bbT   = BB/(BB + EC50_BB);
double vdT   = VD/(VD + EC50_VD);
double digT  = DIG/(DIG + EC50_DIG);

double afT = 1 + KAF_NEURO*nexT - EAF_RASI*rasiT - EAF_VD*vdT;
if (afT < 0.55) afT = 0.55;
double wsT   = pow(LVEDV/LVEDV_N, 1.0/3.0)*afT*loadT;
double fibfT = FIB/(FIB + FIB50);
double b1T   = KB1*(nexT/(1 + nexT))*(1 - 0.8*bbT);

capture Contractility   = CM*(1 - EFIB_EF*fibfT)*(1 - b1T)*(1 + EDIG*digT);
capture LVEF            = EF_MAX*Contractility/(1 + KAF_EF*(afT - 1));
if (LVEF < 5.0)  LVEF = 5.0;
if (LVEF > 72.0) LVEF = 72.0;
capture Stroke_volume   = LVEF/100.0*LVEDV;
capture Heart_rate      = HR_BASE*(1 + KHR_NEURO*nexT)*(1 - EHR_BB*bbT);
capture Cardiac_output  = Stroke_volume*Heart_rate/1000.0;
capture LVESV           = LVEDV - Stroke_volume;
// prolate-ellipsoid geometry with long axis = 2 x minor axis:
//   V = (pi/6)*d^2*(2d) = (pi/3)*d^3  ->  d = (3V/pi)^(1/3)
// gives ~4.7 cm at LVEDV 105 mL and ~5.6 cm at LVEDV 180 mL
capture LVEDD_cm        = pow(3.0*LVEDV/3.14159265, 1.0/3.0);
capture Wall_stress     = wsT;
capture Afterload_index = afT;
capture Load_index      = loadT;

// ---- clinical endpoint surrogates ----
// NYHA class: monotone in congestion and output deficit (1-4, continuous)
double co_defT = (Cardiac_output < CO_NORM) ? (1 - Cardiac_output/CO_NORM) : 0.0;
capture NYHA = 1 + 3.0*((0.6*co_defT + 0.4*(VOL/(VOL + 1.0))));
if (NYHA > 4.0) NYHA = 4.0;
capture SixMWT_m        = 550.0 - 320.0*(NYHA - 1)/3.0;
capture Recovered_flag  = (LVEF >= 50.0) ? 1.0 : 0.0;
// MACE hazard surrogate (death / LVAD / transplant), per year, illustrative
capture MACE_hazard_yr  = 0.02 + 0.55*((LVEF < 30.0) ? (30.0 - LVEF)/30.0 : 0.0)
                               + 0.25*(THR/(THR + 1.0));

// ---- mechanistic read-outs ----
capture Bromocriptine_effect = EMAX_BRC*(BRC_C/(BRC_C + EC50_BRC))*(1 - anteT);
capture RASI_effect          = rasiT;
capture Antepartum_flag     = anteT;
capture Prolactin_23kDa     = PRL23;
capture Prolactin_16kDa     = PRL16;
capture Cathepsin_D         = CTSD;
capture Myocardial_ROS      = ROS;
capture sFlt1_level         = SFLT;
capture Free_VEGF           = VEGF;
capture Capillary_density   = CAP;
capture miR146a_load        = MIR;
capture Survival_signalling = SURV;
capture Viable_myocyte_mass = CM;
capture Irreversible_scar   = SCAR;
capture Fibrosis            = FIB;
capture Inflammation        = INF;
capture Neurohormonal       = NEURO;
capture Congestion          = VOL;
capture NTproBNP            = NTBNP;
capture LV_thrombus         = THR;
capture Lactation           = LACT;


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(purrr); library(ggplot2)
##  mod <- mread_cache("ppcm_mrgsolve_model.R")
##
##  # ---------- dosing builders ----------
##
##  # Bromocriptine, 1 au = one 2.5 mg tablet.
##  #   "1wk" = 2.5 mg BID x 7 days               (ESC minimum course)
##  #   "8wk" = 2.5 mg BID x 2 wk -> 2.5 mg OD x 6 wk  (German trial long arm)
##  ppcm_brc <- function(regimen = c("none","1wk","8wk"), t0 = 0) {
##    regimen <- match.arg(regimen)
##    if (regimen == "none") return(NULL)
##    if (regimen == "1wk")
##      return(ev(amt = 1, cmt = "BRC_G", time = t0, ii = 0.5, addl = 13))
##    # 8-week regimen: BID for 14 d, then OD for 42 d
##    ev(amt = 1, cmt = "BRC_G", time = t0,      ii = 0.5, addl = 27) +
##    ev(amt = 1, cmt = "BRC_G", time = t0 + 14, ii = 1.0, addl = 41)
##  }
##
##  # Guideline HF stack. `rasi` records are still given for an antepartum
##  # patient -- the model's fetotoxicity gate is what zeroes their EFFECT.
##  ppcm_hf <- function(end = 365, t0 = 0, bb = TRUE, rasi = TRUE, mra = TRUE,
##                      diu = TRUE, sg = FALSE, vaso = FALSE, ac = FALSE,
##                      dig = FALSE) {
##    n <- floor(end - t0)
##    e <- NULL
##    add <- function(e, on, cmt, ii = 1, addl = n - 1) {
##      if (!on) return(e)
##      d <- ev(amt = 1, cmt = cmt, time = t0, ii = ii, addl = addl)
##      if (is.null(e)) d else e + d
##    }
##    e <- add(e, bb,   "BB");   e <- add(e, rasi, "RASI")
##    e <- add(e, mra,  "MRA");  e <- add(e, diu,  "DIU")
##    e <- add(e, sg,   "SG");   e <- add(e, ac,   "AC")
##    e <- add(e, dig,  "DIG")
##    # hydralazine + nitrate is dosed TID
##    e <- add(e, vaso, "VD", ii = 1/3, addl = 3*n - 1)
##    e
##  }
##
##  # ---------- 9 prebuilt scenarios ----------
##
##  PPCM_simulate_scenarios <- function(end_d = 365) {
##
##    sc <- list(
##      # Every postpartum arm assumes the patient intends to breastfeed
##      # (BF = 1). Bromocriptine is what ends lactation -- that is modelled,
##      # not assumed, via the LACT compartment.
##      "1. No therapy (natural history)" = list(
##        par = list(BF = 1, T_DELIVERY = -7),
##        ev  = NULL),
##
##      "2. Standard HF therapy only (BB + ACEi + MRA + diuretic)" = list(
##        par = list(BF = 1, T_DELIVERY = -7),
##        ev  = ppcm_hf(end_d)),
##
##      "3. Standard + bromocriptine 1 week + LMWH" = list(
##        par = list(BF = 1, T_DELIVERY = -7),
##        ev  = ppcm_hf(end_d, ac = TRUE) + ppcm_brc("1wk")),
##
##      "4. BOARD: standard + bromocriptine 8 weeks + LMWH" = list(
##        par = list(BF = 1, T_DELIVERY = -7),
##        ev  = ppcm_hf(end_d, ac = TRUE) + ppcm_brc("8wk")),
##
##      "5. BOARD + SGLT2 inhibitor (contemporary quadruple therapy)" = list(
##        par = list(BF = 1, T_DELIVERY = -7),
##        ev  = ppcm_hf(end_d, ac = TRUE, sg = TRUE) + ppcm_brc("8wk")),
##
##      "6. TTN truncating-variant carrier on full BOARD" = list(
##        par = list(BF = 1, T_DELIVERY = -7, GEN_TTN = 1),
##        ev  = ppcm_hf(end_d, ac = TRUE) + ppcm_brc("8wk")),
##
##      # Antepartum diagnosis: ACEi/ARB effect is GATED OFF until delivery on
##      # day 14; hydralazine + nitrate carries the afterload reduction, and
##      # bromocriptine cannot start until after delivery.
##      "7. Antepartum preeclamptic PPCM (ACEi gated off until delivery)" = list(
##        par = list(BF = 1, T_DELIVERY = 14, PREECL = 1),
##        ev  = ppcm_hf(end_d, mra = FALSE, vaso = TRUE, ac = TRUE) +
##              ppcm_brc("8wk", t0 = 14)),
##
##      "8. Severe (LVEF ~23%) BOARD WITHOUT anticoagulation" = list(
##        par = list(BF = 1, T_DELIVERY = -7, SEV = 0.90),
##        ev  = ppcm_hf(end_d, ac = FALSE) + ppcm_brc("8wk")),
##
##      "9. Severe (LVEF ~23%) BOARD WITH anticoagulation" = list(
##        par = list(BF = 1, T_DELIVERY = -7, SEV = 0.90),
##        ev  = ppcm_hf(end_d, ac = TRUE) + ppcm_brc("8wk"))
##    )
##
##    purrr::imap_dfr(sc, function(s, lab) {
##      m <- mod
##      if (length(s$par)) m <- do.call(param, c(list(m), s$par))
##      e <- if (is.null(s$ev)) ev(amt = 0, cmt = "BB", time = 0) else s$ev
##      mrgsim(m, e, end = end_d, delta = 0.5) %>%
##        as_tibble() %>% mutate(scenario = lab)
##    })
##  }
##
##  # A healthy postpartum control, useful as a reference trace and as a
##  # regression test that the model has a stable NORMAL attractor:
##  PPCM_healthy_control <- function(end_d = 730) {
##    mod %>% param(SEV = 0.02, LOSS_STAT3 = 0, PGC_LOSS = 0, BF = 1,
##                  T_DELIVERY = -7) %>%
##      mrgsim(ev(amt = 0, cmt = "BB", time = 0), end = end_d, delta = 1) %>%
##      as_tibble()
##  }
##
##  # ---------- Calibration notes: how each anchor maps onto the model ----------
##  #
##  # Hilfiker-Kleiner 2007 Cell 128:589 (cardiomyocyte STAT3 knockout ->
##  #   MnSOD loss -> cathepsin D activation -> 16K-PRL -> PPCM in mice,
##  #   prevented by bromocriptine) is the model's backbone. LOSS_STAT3
##  #   reduces the myocardium's capacity to detoxify STRESS-driven ROS (the
##  #   `amp` term), which activates cathepsin D (CTSD), which cleaves 23K-PRL
##  #   into PRL16. CTSD_TOL encodes the essential clinical fact that a normal
##  #   lactating woman has abundant prolactin but NO disease: below baseline
##  #   cathepsin D activity, no vasoinhibin is generated at all. Breastfeeding
##  #   alone is therefore not pathogenic in this model, which matches the
##  #   absence of convincing evidence that breastfeeding harms PPCM outcome.
##  #
##  # Patten 2012 Nature 485:333 (PGC-1alpha knockout mice develop PPCM;
##  #   disease requires BOTH a cardiac VEGF/PGC-1alpha deficit AND placental
##  #   sFlt-1; bromocriptine or VEGF rescues) is the SYN_2HIT term plus the
##  #   PGC_LOSS -> VEGF -> CAP path. sFlt-1 is produced ONLY while
##  #   antepartum, so scenario 7 (antepartum preeclamptic) carries a much
##  #   larger early anti-angiogenic hit that resolves after delivery -- the
##  #   model's explanation for why such patients present severely yet can
##  #   still recover well once the placenta is delivered.
##  #
##  # Halkein 2013 J Clin Invest 123:2143 (16K-PRL -> endothelial NF-kB ->
##  #   miR-146a-5p -> exosomal transfer to cardiomyocytes -> Erbb4/Nras/
##  #   Notch1 knockdown; serum miR-146a is elevated in PPCM specifically and
##  #   falls with bromocriptine) is the MIR -> SURV path. SURV gates BOTH
##  #   injury (W_SURV) and recovery (rev_cap), which is why suppressing the
##  #   prolactin substrate early has a disproportionate effect.
##  #
##  # IPAC (McNamara 2015 JACC 66:905): entry LVEF ~0.35 -> ~0.51 at 6 months
##  #   on contemporary therapy. The model's standard-therapy arm rises from
##  #   29.5% to 42.4% at 6 months from a lower entry point, and LVEDD/LVEDV at
##  #   entry limits recovery through the wall-stress and dilation terms --
##  #   reproducing IPAC's finding that LVEF <0.30 with LVEDD >=6.0 cm
##  #   predicts non-recovery.
##  #
##  # German bromocriptine trial (Hilfiker-Kleiner 2017 Eur Heart J 38:2671):
##  #   1 week vs 8 weeks, full recovery 52% vs 68%. In the model the two
##  #   regimens differ ONLY in how much of the high-oxidative-stress
##  #   vulnerable window they cover: ROS (and hence ox_amp and cathepsin D)
##  #   is highest in the first weeks, so continued prolactin suppression
##  #   through weeks 2-8 prevents damage that would otherwise be locked in as
##  #   irreversible SCAR. The model gives 47.6% vs 56.5% mean LVEF at 6 months.
##  #   NOTE THE OVERSHOOT: the trial's MEAN LVEF difference between the two
##  #   arms was small (0.49 vs 0.51) even though the RECOVERY-RATE difference
##  #   was 16 points. This model exaggerates the duration effect on mean
##  #   LVEF; it should be read as a mechanistic hypothesis about WHY duration
##  #   matters (window coverage plus scar lock-in), not as a quantitative
##  #   prediction of the mean-LVEF gap.
##  #
##  # Sliwa 2010 Circulation 121:1465 (bromocriptine 0.27 -> 0.58 vs standard
##  #   0.27 -> 0.36) brackets the model's bromocriptine effect size from
##  #   above; IPAC brackets the standard-therapy arm from above. The model
##  #   deliberately sits between the small proof-of-concept RCT and the
##  #   larger observational cohorts.
##  #
##  # Ware 2016 NEJM 374:233 (truncating variants, mostly TTN, in ~15%;
##  #   lower LVEF at 1 year) is GEN_TTN acting through GEN_INJ (more injury
##  #   per unit insult, since a titin-haploinsufficient sarcomere has less
##  #   reserve) and GEN_REC (less recovery capacity). Scenario 6 recovers to
##  #   43.8% rather than 56.5% on identical therapy.
##  #
##  # Bromocriptine thrombotic risk / mandatory anticoagulation (ESC position
##  #   statement, Bauersachs 2019 Eur J Heart Fail 21:827): PROTHR_BRC raises
##  #   thrombus propensity while the drug is on board, and anticoagulation
##  #   acts ONLY on THR. Scenarios 8 and 9 therefore have IDENTICAL LVEF
##  #   trajectories and differ only in peak thrombus burden (0.40 vs 0.21 au)
##  #   -- the model's way of showing that anticoagulation here buys safety,
##  #   not efficacy.
##  #
##  # ESC EORP registry (Sliwa 2020 Eur J Heart Fail 22:1006): ~46% reach
##  #   LVEF >=0.50 and 6-month mortality is ~6% globally. The untreated arm
##  #   (scenario 1) is the model's representation of the late-presenting,
##  #   under-treated end of that distribution: it deteriorates progressively
##  #   and accrues a large irreversible SCAR fraction.
##  #
##  # NOT modelled as efficacious, deliberately: levosimendan (Biteker 2011
##  #   negative RCT), pentoxifylline and IVIG (small, unreplicated). They
##  #   appear in the mechanistic map for completeness but have no PD effect
##  #   here.
##
##  # ---------- Quick sanity plots ----------
##  # df <- PPCM_simulate_scenarios(365)
##  # ggplot(df, aes(time, LVEF, colour = scenario)) + geom_line() +
##  #   geom_hline(yintercept = 50, linetype = 2) + labs(y = "LVEF (%)")
##  # ggplot(df, aes(time, Prolactin_16kDa, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Capillary_density, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Irreversible_scar, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, LV_thrombus, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, NTproBNP, colour = scenario)) + geom_line() +
##  #   scale_y_log10()
