##  Phenylketonuria (페닐케톤뇨증, PKU) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : PKU — autosomal-recessive PAH-gene loss-of-function causing
##             hepatic phenylalanine hydroxylase deficiency, hyperphenyl-
##             alaninemia, LAT1/BBB large-neutral-amino-acid transport
##             competition, cerebral monoamine (dopamine/serotonin) synthesis
##             deficit and neurotoxicity (classic / moderate / mild PKU and
##             mild hyperphenylalaninemia, MHP, across the residual-activity
##             spectrum; BH4-responsive vs non-responsive genotypes).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 18 ODE compartments — drug PK (sapropterin/BH4 2-cmpt oral,
##             pegvaliase SC 2-cmpt + anti-drug-antibody titer + immune-
##             tolerization state) + amino-acid mass-balance network (plasma
##             Phe/Tyr/Trp via Michaelis-Menten hepatic PAH + pegvaliase
##             alternative clearance + linear minor-pathway/renal clearance;
##             brain Phe/Tyr/Trp via saturable, competitively-inhibited LAT1
##             transport) + downstream PD (dopamine- and serotonin-synthesis
##             indices, myelin/white-matter integrity, cumulative IQ deficit
##             weighted by a critical-developmental-period function of age,
##             executive-function index, growth Z-score).
##  Time     : hours (drug PK, diurnal Phe fluctuation and BBB transport
##             equilibrate over hours; ADA/tolerization over weeks; myelin/
##             growth over months; cumulative IQ deficit over years via a
##             critical-period-weighted, largely irreversible accrual term).
##             Default simulation horizon 0 - 70,080 h (8 years) for natural-
##             history/childhood scenarios; shorter horizons for PK-focused runs.
##  Units    : dose in mg; plasma/brain Phe-Tyr-Trp in umol/L; drug plasma
##             concentration in mg/L; ADA/tolerization/dopamine-serotonin/
##             myelin as relative indices; IQ deficit in points below genetic
##             potential; executive-function index and growth Z-score as
##             illustrative composite scores.
##  Scenarios: 10 prebuilt — see PKU_simulate_scenarios() at bottom.
##  Anchors  : Levy 2007 Lancet (sapropterin PKU-001 phase 3, PMID 17693179);
##             Trefz 2009 J Pediatr (sapropterin PKU-003 pediatric, PMID
##             19261295); Thomas 2018 Mol Genet Metab (pegvaliase PRISM-1/2
##             phase 3 induction/titration, PMID 29653686); Longo 2018
##             Orphanet J Rare Dis (pegvaliase PAL-003 long-term extension,
##             PMID 29973227); Gupta 2018 EBioMedicine (pegvaliase pooled
##             immunogenicity/ADA kinetics, PMID 30366815); Vockley 2014 Genet
##             Med (ACMG PKU management guideline, target Phe 120-360 umol/L
##             lifelong, PMID 24385074); Rouse 2000 J Pediatr / Koch 2000 Mol
##             Genet Metab (Maternal PKU Collaborative Study, congenital heart
##             disease & microcephaly risk vs periconceptional Phe control,
##             PMID 10636975 / 11001815); Waisbren 2007 Mol Genet Metab
##             (meta-analysis, early/continuous treatment preserves IQ, PMID
##             17591452); Diamond 1997 Monogr Soc Res Child Dev (prefrontal
##             dopamine-dependent executive-function deficits even in early-
##             and well-treated PKU, PMID 9421921); Pietz 1999 J Clin Invest
##             (in vivo MRS brain Phe vs plasma Phe, transporter saturation,
##             PMID 10207169).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of phenylketonuria (PKU) linking dietary phenylalanine intake,
saturable hepatic PAH/BH4 enzymatic clearance, saturable BBB LAT1 amino-acid
transport competition, cerebral monoamine synthesis and myelination, and
critical-period-weighted cumulative neurocognitive injury, with mechanistic
PK/PD for sapropterin dihydrochloride (BH4 cofactor) and pegvaliase (PEG-PAL
enzyme substitution, including anti-drug-antibody immunogenicity and
tolerization) plus dietary/medical-formula management.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / genotype
AGE0         : 0.02  : baseline age at simulation start (years; 0.02 ~ 1 week, NBS diagnosis)
WT           : 8     : body weight (kg; default infant, override per scenario)
GENOTYPE     : 0     : 0=classic, 1=moderate, 2=mild, 3=MHP (mild hyperphenylalaninemia)
BH4_RESPONSIVE : 0   : 0=non-responder (null allele), 1=BH4-responsive (misfolding-type missense)
MATERNAL     : 0     : 1 = maternal-PKU pregnancy context (fetal-risk reporting active)
PRECONCEPT_CONTROL : 0 : 1 = optimized pre-conception/pregnancy Phe control

//--- Diet / medical-formula prescription
DIET_PHE_MGKGD : 50   : dietary natural-protein phenylalanine intake (mg/kg/day)
TYR_DIET_MGKGD : 30   : dietary + medical-formula tyrosine intake (mg/kg/day; 30=unsupplemented, ~70=formula-supplemented)
TRP_DIET_MGKGD : 15   : dietary tryptophan intake (mg/kg/day, largely diet-independent)

//--- Genotype-dependent residual hepatic PAH activity (fraction of normal Vmax)
RESID_CLASSIC  : 0.01 : classic PKU residual PAH activity fraction
RESID_MODERATE : 0.03 : moderate PKU residual PAH activity fraction
RESID_MILD     : 0.08 : mild PKU residual PAH activity fraction
RESID_MHP      : 0.35 : MHP residual PAH activity fraction

//--- Amino-acid molecular weights (g/mol) & apparent volumes of distribution
MW_PHE   : 165.19 : g/mol, phenylalanine
MW_TYR   : 181.19 : g/mol, tyrosine
MW_TRP   : 204.23 : g/mol, tryptophan
VD_PHE_LKG : 0.6   : L/kg
VD_TYR_LKG : 0.6   : L/kg
VD_TRP_LKG : 0.6   : L/kg

//--- Hepatic PAH Michaelis-Menten kinetics (calibrated: normal adult diet
//    ~50 mg/kg/d Phe intake -> steady-state plasma Phe ~55 umol/L)
VMAX_PAH_NORMAL_LKG : 70  : umol/h/kg, full-activity (residual=1.0) hepatic Vmax per kg body weight (~4900 umol/h in a 70-kg reference adult)
KM_PAH          : 250   : umol/L
CL_MINOR_LKG    : 0.008 : L/h/kg, linear minor-pathway/renal/protein-incorporation Phe clearance

//--- Sapropterin (Kuvan, BH4) oral PK — illustrative surrogate (Levy 2007;
//    Trefz 2009): Tmax ~3-4h fasted (food roughly doubles AUC), t1/2 ~6h
KA_BH4    : 0.6    : 1/h
F_BH4     : 1.0     : oral bioavailability (apparent, illustrative)
CL_BH4    : 3       : L/h
V_BH4     : 25      : L
EMAX_BH4  : 4.0     : max fold-increase in effective PAH Vmax from BH4 cofactor/chaperone effect (responders only)
EC50_BH4  : 1.0     : mg/L

//--- Pegvaliase (Palynziq, PEG-PAL) SC PK — illustrative surrogate (Thomas
//    2018 PRISM-1; Longo 2019 PRISM-2): slow SC absorption, long maintenance t1/2
KA_PEG     : 0.02   : 1/h
F_PEG      : 0.9     : SC bioavailability (apparent, illustrative)
CL_PEG     : 0.0738 : L/h
V_PEG      : 5       : L
KM_PEG     : 400     : umol/L, Phe-ammonia-lyase apparent Km
KCAT_PEG   : 480     : umol/h per (mg/L) active PEG-PAL, catalytic-capacity constant (calibrated to PRISM-2 20 mg/d maintenance response)

//--- Anti-drug antibody (ADA) formation & immune tolerization (Gupta 2018;
//    Longo 2019: transient efficacy loss during induction/titration,
//    tolerization typically by ~3-6 months of maintenance dosing)
KIN_ADA   : 0.02   : 1/h scaling constant
KOUT_ADA  : 0.004  : 1/h
KM_ADA    : 5       : mg/L (CEN_PEG driving ADA production)
ADA50     : 2       : ADA titer index at half-maximal neutralization
KOUT_TOL  : 0.00035 : 1/h (~120-day tolerization time constant)

//--- Blood-brain-barrier LAT1 transport (saturable; Phe competitively
//    inhibits Tyr/Trp uptake) — illustrative surrogate indices (Pietz 1999)
VMAX_BBB_PHE : 600   : umol/L (brain), transporter-limited ceiling
KM_BBB_PHE   : 150   : umol/L
VMAX_BBB_TYR : 150   : umol/L (brain), transporter-limited ceiling
KM_BBB_TYR   : 100   : umol/L
VMAX_BBB_TRP : 120   : umol/L (brain), transporter-limited ceiling
KM_BBB_TRP   : 100   : umol/L
KI_PHE_COMPET: 100   : umol/L, potency of plasma Phe as competitive LAT1 inhibitor
KOUT_BBB     : 0.35  : 1/h, brain-plasma quasi-equilibration rate

//--- Peripheral Tyr/Trp elimination (fast amino-acid pool turnover)
CL_TYR_LKG : 0.33   : L/h/kg
CL_TRP_LKG : 0.056  : L/h/kg

//--- Downstream monoamine-synthesis indices (relative, 1.0 = normal capacity)
BRAIN_TYR_REF : 42   : umol/L, reference normal-physiology brain Tyr (for DA index normalization)
BRAIN_TRP_REF : 33   : umol/L, reference normal-physiology brain Trp (for 5-HT index normalization)
KOUT_DA   : 0.05    : 1/h
KOUT_SER  : 0.05    : 1/h

//--- Myelin/white-matter integrity (relative, 1.0 = normal)
KOUT_MYELIN     : 0.002  : 1/h
MYELIN_MAX_LOSS : 0.5    : maximum fractional myelin-integrity loss
KM_MYELIN       : 500    : umol/L (brain Phe)

//--- Cumulative IQ deficit (critical-period-weighted, largely irreversible)
IQ_CAP          : 40     : points, maximum plausible cumulative deficit
IQ_SAFE_BRAIN_PHE : 250  : umol/L (brain), threshold below which little/no injury accrues
IQ_LOSS_RATE    : 1.7e-7 : 1/(h*umol/L), calibrated accrual-rate constant
CRIT_TAU        : 6      : years, critical-developmental-period time constant

//--- Executive-function index (largely reversible, tracks current control)
EXECFX_MAX_DEFICIT : 30  : points (0-100 scale)
KM_EXECFX           : 400 : umol/L (brain Phe)
KOUT_EXECFX          : 0.01 : 1/h

//--- Growth Z-score (Tyr/protein-balance sensitive)
TYR_NORMAL_REF   : 60    : umol/L
GROWTHZ_MAX_DEFICIT : 1.0 : maximum growth Z-score deficit (SD units)
KOUT_GROWTHZ      : 0.0005 : 1/h

//--- Initial conditions (override via param() to chain multi-stage scenarios,
//    e.g. carrying childhood end-state into an adolescent off-diet continuation)
INIT_PHE        : 55   : umol/L, initial plasma Phe
INIT_TYR        : 55   : umol/L, initial plasma Tyr
INIT_TRP        : 55   : umol/L, initial plasma Trp
INIT_BRAIN_PHE  : 150  : umol/L-equivalent, initial brain Phe
INIT_BRAIN_TYR  : 42   : umol/L-equivalent, initial brain Tyr
INIT_BRAIN_TRP  : 33   : umol/L-equivalent, initial brain Trp
INIT_DA         : 1.0  : initial dopamine-synthesis index
INIT_SER        : 1.0  : initial serotonin-synthesis index
INIT_MYELIN     : 1.0  : initial myelin-integrity index
INIT_IQDEF      : 0    : points, initial cumulative IQ deficit
INIT_EXECFX     : 0    : initial executive-function deficit index
INIT_GROWTHZ    : 0    : initial growth Z-score deficit

[CMT] @annotated
GUT_BH4    : Sapropterin gut depot (mg)
CEN_BH4    : Sapropterin plasma (mg)
SC_PEG     : Pegvaliase SC depot (mg)
CEN_PEG    : Pegvaliase plasma (mg)
ADA        : Anti-PEG-PAL antibody titer index
TOL        : Immune tolerization fraction (0-1)
PLASMA_PHE : Plasma phenylalanine (umol/L)
PLASMA_TYR : Plasma tyrosine (umol/L)
PLASMA_TRP : Plasma tryptophan (umol/L)
BRAIN_PHE  : Brain (CNS) phenylalanine, illustrative index (umol/L-equivalent)
BRAIN_TYR  : Brain tyrosine, illustrative index (umol/L-equivalent)
BRAIN_TRP  : Brain tryptophan, illustrative index (umol/L-equivalent)
DA_IDX     : Dopamine-synthesis capacity index (1.0=normal)
SER_IDX    : Serotonin-synthesis capacity index (1.0=normal)
MYELIN_IDX : White-matter/myelin integrity index (1.0=normal)
IQ_DEFICIT : Cumulative IQ deficit (points below genetic potential)
EXECFX_IDX : Executive-function deficit index (0-100)
GROWTHZ    : Growth Z-score deficit (SD units below expected)

[MAIN]
GUT_BH4_0 = 0; CEN_BH4_0 = 0; SC_PEG_0 = 0; CEN_PEG_0 = 0;
ADA_0 = 0; TOL_0 = 0;

// initial conditions read from INIT_* parameters (override via param() to chain
// multi-stage scenarios, e.g. childhood-controlled -> adolescent off-diet, while
// carrying prior state forward instead of resetting to normal-physiology defaults)
PLASMA_PHE_0 = INIT_PHE;
PLASMA_TYR_0 = INIT_TYR;
PLASMA_TRP_0 = INIT_TRP;
BRAIN_PHE_0  = INIT_BRAIN_PHE;
BRAIN_TYR_0  = INIT_BRAIN_TYR;
BRAIN_TRP_0  = INIT_BRAIN_TRP;
DA_IDX_0     = INIT_DA;
SER_IDX_0    = INIT_SER;
MYELIN_IDX_0 = INIT_MYELIN;
IQ_DEFICIT_0 = INIT_IQDEF;
EXECFX_IDX_0 = INIT_EXECFX;
GROWTHZ_0    = INIT_GROWTHZ;

[ODE]
// ---------- Drug PK ----------
double CBH4 = CEN_BH4 / V_BH4;
double CPEG = CEN_PEG / V_PEG;

dxdt_GUT_BH4 = -KA_BH4 * GUT_BH4;
dxdt_CEN_BH4 =  F_BH4 * KA_BH4 * GUT_BH4 - (CL_BH4/V_BH4) * CEN_BH4;

double ada_neutral_frac = (ADA/(ADA+ADA50)) * (1.0 - TOL);
double ada_extra_cl = 0.05 * ADA;  // ADA-accelerated PEG-PAL clearance
dxdt_SC_PEG  = -KA_PEG * SC_PEG;
dxdt_CEN_PEG =  F_PEG * KA_PEG * SC_PEG - (CL_PEG/V_PEG + ada_extra_cl) * CEN_PEG;

double ada_drive = KIN_ADA * CPEG/(KM_ADA + CPEG);
dxdt_ADA = ada_drive - KOUT_ADA * ADA;
dxdt_TOL = KOUT_TOL * (1.0 - TOL);

// ---------- Genotype residual PAH activity & BH4 chaperone/cofactor effect ----------
double resid_frac = (GENOTYPE==0) ? RESID_CLASSIC :
                    (GENOTYPE==1) ? RESID_MODERATE :
                    (GENOTYPE==2) ? RESID_MILD : RESID_MHP;
double bh4_fx = (BH4_RESPONSIVE > 0) ? (EMAX_BH4 * CBH4/(EC50_BH4 + CBH4)) : 0.0;
double vmax_pah_eff = VMAX_PAH_NORMAL_LKG * WT * resid_frac * (1.0 + bh4_fx);

// ---------- Dietary amino-acid inputs (mg/kg/d -> umol/h) ----------
double phe_input  = DIET_PHE_MGKGD * WT / 24.0 / MW_PHE * 1000.0;
double tyr_input  = TYR_DIET_MGKGD * WT / 24.0 / MW_TYR * 1000.0;
double trp_input  = TRP_DIET_MGKGD * WT / 24.0 / MW_TRP * 1000.0;

// ---------- Plasma phenylalanine mass balance ----------
double pah_flux   = vmax_pah_eff * PLASMA_PHE/(KM_PAH + PLASMA_PHE);
double peg_active = CPEG * (1.0 - ada_neutral_frac);
if (peg_active < 0) peg_active = 0;
double vmax_peg_eff = KCAT_PEG * peg_active;
double peg_flux   = vmax_peg_eff * PLASMA_PHE/(KM_PEG + PLASMA_PHE);
double minor_flux = CL_MINOR_LKG * WT * PLASMA_PHE;
double vd_phe = VD_PHE_LKG * WT;
dxdt_PLASMA_PHE = (phe_input - pah_flux - peg_flux - minor_flux) / vd_phe;

// ---------- Plasma tyrosine mass balance (PAH-derived Tyr + diet - elimination) ----------
double vd_tyr = VD_TYR_LKG * WT;
dxdt_PLASMA_TYR = (tyr_input + pah_flux - CL_TYR_LKG*WT*PLASMA_TYR) / vd_tyr;

// ---------- Plasma tryptophan mass balance ----------
double vd_trp = VD_TRP_LKG * WT;
dxdt_PLASMA_TRP = (trp_input - CL_TRP_LKG*WT*PLASMA_TRP) / vd_trp;

// ---------- Brain (BBB LAT1) transport: Phe saturable uptake; Tyr/Trp competitively inhibited ----------
double brain_phe_target = VMAX_BBB_PHE * PLASMA_PHE/(KM_BBB_PHE + PLASMA_PHE);
dxdt_BRAIN_PHE = KOUT_BBB * (brain_phe_target - BRAIN_PHE);

double phe_compet = 1.0 + PLASMA_PHE/KI_PHE_COMPET;
double brain_tyr_target = VMAX_BBB_TYR * PLASMA_TYR/(KM_BBB_TYR*phe_compet + PLASMA_TYR);
dxdt_BRAIN_TYR = KOUT_BBB * (brain_tyr_target - BRAIN_TYR);

double brain_trp_target = VMAX_BBB_TRP * PLASMA_TRP/(KM_BBB_TRP*phe_compet + PLASMA_TRP);
dxdt_BRAIN_TRP = KOUT_BBB * (brain_trp_target - BRAIN_TRP);

// ---------- Monoamine synthesis capacity indices ----------
double da_target = BRAIN_TYR / BRAIN_TYR_REF;
if (da_target > 1.2) da_target = 1.2;
dxdt_DA_IDX = KOUT_DA * (da_target - DA_IDX);

double ser_target = BRAIN_TRP / BRAIN_TRP_REF;
if (ser_target > 1.2) ser_target = 1.2;
dxdt_SER_IDX = KOUT_SER * (ser_target - SER_IDX);

// ---------- Myelin / white-matter integrity ----------
double myelin_target = 1.0 - MYELIN_MAX_LOSS * BRAIN_PHE/(BRAIN_PHE + KM_MYELIN);
dxdt_MYELIN_IDX = KOUT_MYELIN * (myelin_target - MYELIN_IDX);

// ---------- Cumulative IQ deficit (critical-period-weighted, near-irreversible) ----------
double current_age = AGE0 + SOLVERTIME/8760.0;
double phe_excess_iq = BRAIN_PHE - IQ_SAFE_BRAIN_PHE;
if (phe_excess_iq < 0) phe_excess_iq = 0;
double crit_wt = exp(-current_age/CRIT_TAU);
double iq_drive = IQ_LOSS_RATE * phe_excess_iq * crit_wt;
dxdt_IQ_DEFICIT = iq_drive * (1.0 - IQ_DEFICIT/IQ_CAP);

// ---------- Executive-function deficit (largely reversible, tracks current control) ----------
double execfx_target = EXECFX_MAX_DEFICIT * BRAIN_PHE/(KM_EXECFX + BRAIN_PHE);
dxdt_EXECFX_IDX = KOUT_EXECFX * (execfx_target - EXECFX_IDX);

// ---------- Growth Z-score deficit (Tyr/protein-balance sensitive) ----------
double tyr_deficit_frac = (TYR_NORMAL_REF - PLASMA_TYR) / TYR_NORMAL_REF;
if (tyr_deficit_frac < 0) tyr_deficit_frac = 0;
double growthz_target = GROWTHZ_MAX_DEFICIT * tyr_deficit_frac;
dxdt_GROWTHZ = KOUT_GROWTHZ * (growthz_target - GROWTHZ);

[TABLE]
capture conc_sapropterin   = CEN_BH4 / V_BH4;
capture conc_pegvaliase    = CEN_PEG / V_PEG;
capture ADA_titer          = ADA;
capture Tolerization_frac  = TOL;
capture Plasma_Phe_umolL   = PLASMA_PHE;
capture Plasma_Tyr_umolL   = PLASMA_TYR;
capture Plasma_Trp_umolL   = PLASMA_TRP;
capture Brain_Phe_idx      = BRAIN_PHE;
capture Brain_Tyr_idx      = BRAIN_TYR;
capture Brain_Trp_idx      = BRAIN_TRP;
capture Dopamine_idx       = DA_IDX;
capture Serotonin_idx      = SER_IDX;
capture Myelin_idx         = MYELIN_IDX;
capture IQ_deficit_pts     = IQ_DEFICIT;
capture ExecFunction_deficit = EXECFX_IDX;
capture GrowthZ_deficit    = GROWTHZ;
capture Age_years          = AGE0 + TIME/8760.0;
capture ACMG_band_flag     = (PLASMA_PHE >= 120 && PLASMA_PHE <= 360) ? 1 : 0;
capture Maternal_CHD_risk_flag = (MATERNAL > 0 && PLASMA_PHE > 900) ? 1 : 0;
capture Maternal_Microcephaly_risk_flag = (MATERNAL > 0 && PLASMA_PHE > 600) ? 1 : 0;

[CAPTURE]
conc_sapropterin conc_pegvaliase ADA_titer Tolerization_frac
Plasma_Phe_umolL Plasma_Tyr_umolL Plasma_Trp_umolL
Brain_Phe_idx Brain_Tyr_idx Brain_Trp_idx
Dopamine_idx Serotonin_idx Myelin_idx
IQ_deficit_pts ExecFunction_deficit GrowthZ_deficit Age_years
ACMG_band_flag Maternal_CHD_risk_flag Maternal_Microcephaly_risk_flag


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("pku_mrgsolve_model.R")
##
##  # ---------- 9 single-stage scenarios + 1 two-stage scenario (validated by ----------
##  # ---------- actually running this model with mrgsolve 1.x / R 4.3)         ----------
##  # NOTE: time unit is HOURS throughout -> daily dosing is ii=24 (NOT ii=1).
##  # Validated 8-year (scenarios 1-4,7) / 1-year (5-6) / 40-week (8-9) steady-state
##  # Plasma_Phe_umolL outputs are annotated inline below.
##
##  PKU_simulate_scenarios <- function() {
##
##    sc <- list(
##      "1. Untreated classic PKU (natural history)" =                     # -> Phe ~1502 umol/L
##        list(m = mod %>% param(GENOTYPE=0, WT=8, DIET_PHE_MGKGD=50, TYR_DIET_MGKGD=30), end_h=8760*8),
##
##      "2. Diet-only, well-controlled classic PKU (NBS + lifelong diet)" = # -> Phe ~329 (within ACMG band)
##        list(m = mod %>% param(GENOTYPE=0, WT=8, DIET_PHE_MGKGD=12, TYR_DIET_MGKGD=70), end_h=8760*8),
##
##      "3. Diet + sapropterin, BH4-responsive moderate PKU (liberalized)" = # -> Phe ~304 (vs 603 w/o BH4)
##        list(m = mod %>% param(GENOTYPE=1, BH4_RESPONSIVE=1, WT=15, DIET_PHE_MGKGD=25, TYR_DIET_MGKGD=50) %>%
##               ev(amt=150, cmt="GUT_BH4", ii=24, addl=8*366), end_h=8760*8),   # ~10 mg/kg/d, Levy 2007/Trefz 2009
##
##      "4. Sapropterin trial, classic PKU non-responder (null genotype)" = # -> Phe ~329 (identical to diet-only #2: zero drug benefit, as expected)
##        list(m = mod %>% param(GENOTYPE=0, BH4_RESPONSIVE=0, WT=15, DIET_PHE_MGKGD=12, TYR_DIET_MGKGD=70) %>%
##               ev(amt=300, cmt="GUT_BH4", ii=24, addl=8*366), end_h=8760*8),
##
##      "5. Pegvaliase induction->maintenance, severe classic PKU (liberalized)" = # -> Phe ~503 by 1y
##        list(m = mod %>% param(GENOTYPE=0, WT=70, DIET_PHE_MGKGD=45, TYR_DIET_MGKGD=70) %>%
##               ev(amt=20, cmt="SC_PEG", ii=24, addl=366), end_h=8760),         # PRISM-1/2 20 mg/d maintenance
##
##      "6. Pegvaliase with heightened immunogenicity (ADA rise -> tolerization)" = # -> Phe ~736 (efficacy attenuated by ADA)
##        list(m = mod %>% param(GENOTYPE=0, WT=70, DIET_PHE_MGKGD=45, TYR_DIET_MGKGD=70, KIN_ADA=0.05) %>%
##               ev(amt=20, cmt="SC_PEG", ii=24, addl=366), end_h=8760),
##
##      "7. Untreated mild hyperphenylalaninemia (MHP, benign)" =           # -> Phe ~203 (within ACMG band, no Rx needed)
##        list(m = mod %>% param(GENOTYPE=3, WT=8, DIET_PHE_MGKGD=50, TYR_DIET_MGKGD=30), end_h=8760*8),
##
##      "8. Maternal PKU pregnancy - poor pre-conception control" =         # -> Phe ~1345 (>900: high CHD-risk flag)
##        list(m = mod %>% param(GENOTYPE=0, MATERNAL=1, WT=60, DIET_PHE_MGKGD=45, TYR_DIET_MGKGD=40, AGE0=25),
##             end_h=24*280),
##
##      "9. Maternal PKU pregnancy - optimized pre-conception control" =    # -> Phe ~270 (within ACMG band: low fetal risk)
##        list(m = mod %>% param(GENOTYPE=0, MATERNAL=1, WT=60, DIET_PHE_MGKGD=10, TYR_DIET_MGKGD=70, AGE0=25),
##             end_h=24*280)
##    )
##
##    out <- purrr::imap_dfr(sc, function(s, lab) {
##      s$m %>% mrgsim(end=s$end_h, delta=24) %>% as_tibble() %>% mutate(scenario=lab)
##    })
##
##    # ---- 10. Adolescent diet discontinuation after good childhood control ('off-diet') ----
##    # Two-stage chain: simulate 0-12y well-controlled, then carry the end-state forward
##    # via INIT_* parameters (NOT init(), which [MAIN]'s literal X_0 = ... would clobber)
##    # into a second run with diet liberalized from age 12y onward.
##    stage1 <- mod %>% param(GENOTYPE=0, WT=8, DIET_PHE_MGKGD=12, TYR_DIET_MGKGD=70, AGE0=0.02) %>%
##      mrgsim(end=8760*12, delta=24) %>% as_tibble()
##    e <- tail(stage1, 1)                                                  # -> Phe ~329, IQ deficit ~1.2 at age 12y
##    stage2 <- mod %>% param(GENOTYPE=0, WT=45, DIET_PHE_MGKGD=50, TYR_DIET_MGKGD=30, AGE0=12,
##        INIT_PHE=e$Plasma_Phe_umolL, INIT_TYR=e$Plasma_Tyr_umolL, INIT_TRP=e$Plasma_Trp_umolL,
##        INIT_BRAIN_PHE=e$Brain_Phe_idx, INIT_BRAIN_TYR=e$Brain_Tyr_idx, INIT_BRAIN_TRP=e$Brain_Trp_idx,
##        INIT_DA=e$Dopamine_idx, INIT_SER=e$Serotonin_idx, INIT_MYELIN=e$Myelin_idx,
##        INIT_IQDEF=e$IQ_deficit_pts, INIT_EXECFX=e$ExecFunction_deficit, INIT_GROWTHZ=e$GrowthZ_deficit) %>%
##      mrgsim(end=8760*6, delta=24) %>% as_tibble()                        # -> Phe reverts to ~1502 by age 18y;
##                                                                          #    IQ deficit rises only slightly (~1.2->1.4,
##                                                                          #    critical period mostly over) but executive-
##                                                                          #    function deficit rises sharply (~0->17),
##                                                                          #    matching the largely-reversible, current-
##                                                                          #    control-tracking design of EXECFX_IDX.
##    out10 <- bind_rows(mutate(stage1, scenario="10a. Childhood controlled (0-12y)"),
##                        mutate(stage2, scenario="10b. Off-diet adolescent/adult (12-18y)"))
##
##    bind_rows(out, out10)
##  }
##
##  # ---------- Calibration anchors (all PMIDs verified against pubmed.ncbi.nlm.nih.gov) ----------
##  # ACMG/NIH lifelong target range 120-360 umol/L (Vockley 2014 Genet Med, PMID 24385074)
##  # Sapropterin responder definition >=30% plasma-Phe reduction on 8.5-20 mg/kg/d
##  #   (Levy 2007 Lancet PKU-001, PMID 17693179; Trefz 2009 J Pediatr PKU-003, PMID 19261295)
##  # Pegvaliase PRISM-1/2 induction/titration/maintenance, mean Phe reduction with
##  #   liberalized diet at 20 mg/d maintenance (Thomas 2018 Mol Genet Metab, PMID 29653686)
##  # Pegvaliase long-term immunogenicity/tolerization pattern (Longo 2018 Orphanet J
##  #   Rare Dis PAL-003 extension, PMID 29973227; Gupta 2018 EBioMedicine ADA/PEG-
##  #   antibody kinetics, PMID 30366815)
##  # Maternal PKU Collaborative Study: congenital heart disease/microcephaly risk vs
##  #   periconceptional/gestational Phe control (Rouse 2000 J Pediatr, PMID 10636975;
##  #   Koch 2000 Mol Genet Metab, PMID 11001815; Lenke & Levy 1980 NEJM, PMID 7421947)
##  # Waisbren 2007 meta-analysis: early-and-continuously-treated PKU IQ approaches
##  #   population mean; each 100 umol/L Phe increase predicts 1.3-3.1 point IQ
##  #   decrease during the critical period (PMID 17591452)
##  # Diamond 1997 Monogr Soc Res Child Dev: prefrontal-cortex dopamine-dependent
##  #   executive deficits detectable even in early- and well-treated PKU due to the
##  #   PFC's heightened sensitivity to small tyrosine-availability changes (PMID 9421921)
##  # Pietz 1999 J Clin Invest: in vivo 1H-MRS shows brain Phe rises with, but is
##  #   partly buffered relative to, plasma Phe via saturable LAT1 transport (PMID 10207169)
##
##  # ---------- Quick sanity plots ----------
##  # df <- PKU_simulate_scenarios()
##  # ggplot(df, aes(time/8760, Plasma_Phe_umolL, colour=scenario)) + geom_line() + xlab("age (years)")
##  # ggplot(df, aes(time/8760, IQ_deficit_pts, colour=scenario)) + geom_line() + xlab("age (years)")
