##  ============================================================================
##  Gastrointestinal Stromal Tumor (GIST) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : GIST — the most common mesenchymal neoplasm of the GI tract,
##             arising from interstitial cells of Cajal (ICC) / their precursors
##             under an ETV1 lineage program, driven in ~85% of cases by a
##             mutually exclusive activating mutation of KIT (exon 11 ~65-70%,
##             exon 9 ~8-10%) or PDGFRA (exon 18 D842V ~5-6%), with a distinct
##             SDH-deficient / quadruple-wild-type minority that is
##             KIT-independent and pseudohypoxia (succinate-HIF1a-VEGF) driven.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  WHY THIS DISEASE NEEDS A *POLYCLONAL* QSP MODEL
##  -----------------------------------------------
##  GIST is the textbook case in which a single-compartment "tumor size vs
##  drug concentration" model cannot reproduce the clinic. Three facts force a
##  clonal structure:
##    (1) Imatinib almost always works, and almost always stops working at
##        ~20-24 months — not because the drug stops reaching the target, but
##        because the drug SELECTS a pre-existing / newly acquired secondary
##        kinase-domain mutant.
##    (2) The secondary mutants are POLYCLONAL: different metastases in the
##        same patient carry different secondary mutations, and the two major
##        families respond to OPPOSITE drugs — ATP-binding-pocket mutants
##        (exon 13 V654A, exon 14 T670I) are suppressed by sunitinib but poorly
##        by regorafenib, whereas activation-loop mutants (exon 17 D816/D820/
##        N822K, Y823D) are the reverse.
##    (3) Consequently, the winner of a head-to-head second-line trial depends
##        on the ctDNA-measured clonal composition of the enrolled population —
##        which is exactly what INTRIGUE (ripretinib vs sunitinib, 2nd line)
##        found: NEGATIVE overall, but with opposite subgroup directions.
##  This model therefore carries SIX tumor sub-populations and a
##  DRUG x CLONE effective-IC50 matrix, and lets the trial results emerge
##  rather than be asserted.
##
##  Scope    : 34 ODE compartments —
##             * oral PK for five TKIs (imatinib 1L, sunitinib 2L,
##               regorafenib 3L, ripretinib 4L, avapritinib for PDGFRA D842V),
##               with imatinib alpha-1-acid-glycoprotein (AAG) protein binding
##               and time-dependent clearance modeled explicitly;
##             * six tumor sub-populations (primary-driver sensitive clone;
##               quiescent drug-tolerant persister pool; exon 13/14 ATP-pocket
##               resistant clone; exon 17/18 activation-loop resistant clone;
##               primary-refractory clone [PDGFRA D842V or SDH-deficient
##               biology depending on genotype]; KIT-independent bypass clone);
##             * signal transduction readouts (pKIT, AKT/mTOR, ERK, ETV1, BIM);
##             * tumor vascular support (VEGFR-dependent, the mechanism by
##               which sunitinib/regorafenib work on KIT-refractory disease);
##             * imaging & molecular biomarkers (FDG-PET SUVmax, CT attenuation
##               for Choi criteria, and SEPARATE sensitive- and resistant-clone
##               plasma ctDNA so that molecular progression can be shown to
##               precede radiologic progression);
##             * organ-system toxicity (periorbital edema, neutropenia,
##               hypothyroidism, hypertension, hand-foot skin reaction).
##  Time     : days. Default horizon 1460 d (4 y) to span adjuvant therapy,
##             first-line response, secondary resistance and 2nd-4th line.
##  Units    : drug amounts mg; concentrations converted to nM internally;
##             tumor burden mL (cm3) of viable tumor; biomarkers in clinical
##             units (ng/mL, HU, SUV, %VAF, x10^9/L, mIU/L, mmHg).
##  Scenarios: 13 prebuilt scenario families (19 arms) — see GIST_scenarios()
##             at the bottom of this file.
##  Anchors  : B2222 (Demetri 2002 NEJM 347:472); EORTC 62005 / S0033 and the
##             MetaGIST pooled analysis (JCO 2010 28:1247, exon 9 800 mg PFS
##             benefit); Heinrich 2003 JCO 21:4342 & 2008 JCO 26:5352
##             (genotype-response); Antonescu 2005 Clin Cancer Res 11:4182 and
##             Wardelmann 2006 Clin Cancer Res 12:1743 (polyclonal secondary
##             mutations); Demetri 2009 J Clin Oncol 27:3141 (imatinib Cmin
##             1100 ng/mL threshold);
##             Widmer 2006 Br J Clin Pharmacol 62:97 (AAG binding);
##             Demetri 2006 Lancet 368:1329 (sunitinib GRID-precursor);
##             Demetri 2013 Lancet 381:295 (GRID, regorafenib);
##             Blay 2020 Lancet Oncol 21:923 (INVICTUS, ripretinib 4L);
##             Bauer 2022 J Clin Oncol 40:3918 (INTRIGUE, ripretinib vs
##             sunitinib 2L — negative overall) and Bauer 2024 Nat Med
##             30:498 (INTRIGUE ctDNA exon 11+13/14 vs 11+17/18 subgroups);
##             Heinrich 2020/2021 (NAVIGATOR, avapritinib in PDGFRA D842V);
##             Blay 2007 JCO 25:1107 (BFR14 interruption -> rapid regrowth);
##             Joensuu 2012 JAMA 307:1265 (SSGXVIII, 3 y adjuvant imatinib);
##             Choi 2007 JCO 25:1753 (CT density response criteria);
##             Van den Abbeele 2008 (FDG-PET early metabolic response).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================

[PROB]
Polyclonal QSP model of gastrointestinal stromal tumor (GIST) linking oral PK
of five tyrosine kinase inhibitors to a drug x clone effective-IC50 matrix
over six tumor sub-populations (primary-driver sensitive, quiescent
drug-tolerant persister, exon 13/14 ATP-pocket resistant, exon 17/18
activation-loop resistant, primary-refractory PDGFRA-D842V/SDH-deficient, and
KIT-independent bypass), through KIT-PI3K/AKT-MAPK/ERK-ETV1-BIM signaling and
VEGFR-dependent vascular support, to imaging (RECIST size, Choi CT density,
FDG-PET SUVmax), molecular (clone-resolved plasma ctDNA VAF) and toxicity
endpoints.

[PLUGIN] Rcpp

[PARAM] @annotated
//--------------------------------------------------------------------------
// Patient / genotype configuration
//--------------------------------------------------------------------------
GENO       : 1     : Genotype: 1=KIT ex11, 2=KIT ex9, 3=PDGFRA D842V, 4=SDH-deficient/WT, 5=KIT ex11 + BIM deletion polymorphism
TB0        : 500   : mL, baseline viable tumor burden at simulation start (metastatic default)
TMAX_BURDEN: 4000  : mL, carrying capacity of the anatomic compartment
ADJUVANT   : 0     : 1 = post-R0-resection micrometastatic setting (overrides TB0 to TB0_ADJ)
TB0_ADJ    : 0.03  : mL, occult micrometastatic burden after complete resection

//--------------------------------------------------------------------------
// Imatinib PK (oral; 400 mg/d standard, 800 mg/d for KIT exon 9)
//--------------------------------------------------------------------------
KA_IMA     : 10.0  : 1/day, first-order absorption (tmax 2-4 h)
CL_IMA     : 183   : L/day, apparent oral clearance at first dose (~7.6 L/h; drifts up to ~10.3 L/h at steady state via FCLDRIFT)
V1_IMA     : 200   : L, apparent central volume
V2_IMA     : 153   : L, apparent peripheral volume (total Vd/F ~353 L)
Q_IMA      : 600   : L/day, intercompartmental clearance (rapid distribution)
MW_IMA     : 493.6 : g/mol, imatinib molecular weight
FT_IMA     : 0.050 : effective target-site availability fraction (unbound + tissue partition + CGP74588 contribution)
CLFAC_IMA  : 1.0   : multiplier on imatinib CL (CYP3A4 phenotype / DDI / adherence; >1 = faster clearance)
FCLDRIFT   : 0.35  : fractional increase in apparent CL at steady state (time-dependent clearance)
KDRIFT     : 0.008 : 1/day, rate constant of the clearance drift
AAG_REF    : 1.0   : reference alpha-1-acid glycoprotein level (relative units)
KIN_AAG    : 0.20  : 1/day, AAG synthesis rate constant
KOUT_AAG   : 0.20  : 1/day, AAG elimination rate constant
GAAG       : 0.55  : acute-phase AAG induction per unit relative tumor burden

//--------------------------------------------------------------------------
// Sunitinib PK (oral; 50 mg 4/2 schedule or 37.5 mg continuous)
//--------------------------------------------------------------------------
KA_SUN     : 3.0   : 1/day, absorption (tmax 6-12 h)
CL_SUN     : 816   : L/day, apparent oral clearance (~34 L/h)
V1_SUN     : 2230  : L, apparent volume of distribution
MW_SUN     : 398.5 : g/mol
FT_SUN     : 0.100 : effective target-site availability (includes equipotent SU12662 metabolite)

//--------------------------------------------------------------------------
// Regorafenib PK (oral; 160 mg 3 weeks on / 1 week off)
//--------------------------------------------------------------------------
KA_REG     : 1.5   : 1/day, absorption
CL_REG     : 84    : L/day, apparent oral clearance (~3.5 L/h)
V1_REG     : 100   : L, apparent volume
MW_REG     : 482.8 : g/mol
FT_REG     : 0.010 : effective target-site availability (very high protein binding; includes M-2/M-5 metabolites)

//--------------------------------------------------------------------------
// Ripretinib PK (oral; 150 mg once daily, switch-control inhibitor)
//--------------------------------------------------------------------------
KA_RIP     : 2.0   : 1/day, absorption
CL_RIP     : 600   : L/day, apparent oral clearance (~25 L/h)
V1_RIP     : 800   : L, apparent volume
MW_RIP     : 510.0 : g/mol
FT_RIP     : 0.020 : effective target-site availability (includes active DP-5439 metabolite)

//--------------------------------------------------------------------------
// Avapritinib PK (oral; 300 mg once daily, type I inhibitor)
//--------------------------------------------------------------------------
KA_AVA     : 2.0   : 1/day, absorption
CL_AVA     : 480   : L/day, apparent oral clearance (~20 L/h)
V1_AVA     : 1200  : L, apparent volume
MW_AVA     : 498.6 : g/mol
FT_AVA     : 0.020 : effective target-site availability

//--------------------------------------------------------------------------
// DRUG x CLONE EFFECTIVE IC50 MATRIX  (nM of effective target-site conc.)
// Columns: S = primary-driver sensitive clone (KIT exon 11 reference)
//          A = exon 13 V654A / exon 14 T670I  (ATP-binding-pocket family)
//          L = exon 17 D816/D820/N822K, Y823D (activation-loop family)
//          D = primary-refractory clone (PDGFRA D842V, or SDH-deficient)
// These are CALIBRATED EFFECTIVE potencies (see calibration notes at the
// bottom), not raw biochemical Kd values.
//--------------------------------------------------------------------------
IC_IMA_S   : 35      : nM, imatinib vs KIT exon 11
IC_IMA_A   : 900     : nM, imatinib vs exon 13/14 ATP-pocket mutants
IC_IMA_L   : 2500    : nM, imatinib vs exon 17/18 activation-loop mutants
IC_IMA_D   : 20000   : nM, imatinib vs PDGFRA D842V (clinically inactive)
IC_SUN_S   : 6       : nM, sunitinib vs primary clone
IC_SUN_A   : 10      : nM, sunitinib vs ATP-pocket mutants (POTENT)
IC_SUN_L   : 250     : nM, sunitinib vs activation-loop mutants (WEAK)
IC_SUN_D   : 800     : nM, sunitinib vs primary-refractory clone
IC_REG_S   : 16      : nM, regorafenib vs primary clone
IC_REG_A   : 130     : nM, regorafenib vs ATP-pocket mutants (modest)
IC_REG_L   : 45      : nM, regorafenib vs activation-loop mutants (ACTIVE)
IC_REG_D   : 1000    : nM, regorafenib vs primary-refractory clone
IC_RIP_S   : 4       : nM, ripretinib vs primary clone
IC_RIP_A   : 25      : nM, ripretinib vs ATP-pocket mutants (moderate — weaker than sunitinib)
IC_RIP_L   : 5       : nM, ripretinib vs activation-loop mutants (good)
IC_RIP_D   : 60      : nM, ripretinib vs primary-refractory clone
IC_AVA_S   : 3       : nM, avapritinib vs primary clone
IC_AVA_A   : 200     : nM, avapritinib vs V654A (a known avapritinib-escape mutation)
IC_AVA_L   : 2       : nM, avapritinib vs activation-loop mutants (POTENT)
IC_AVA_D   : 1.5     : nM, avapritinib vs PDGFRA D842V (POTENT; set high internally for SDH-deficient)
IC_AVA_D_SDH : 30000 : nM, avapritinib vs SDH-deficient clone (inactive)
GF_EX9     : 5.0     : imatinib IC50 fold-increase for KIT exon 9 vs exon 11
GF_EX9_SUN : 0.7     : sunitinib IC50 fold for KIT exon 9 (sunitinib is MORE potent on exon 9)

//--------------------------------------------------------------------------
// Tumor growth, death and clonal dynamics
//--------------------------------------------------------------------------
KG         : 0.011   : 1/day, maximal intrinsic proliferation rate of viable clones
KD0        : 0.002   : 1/day, baseline (drug-independent) tumor cell loss
EMAX_AP    : 0.022   : 1/day, maximal drug-induced apoptotic death rate
IC_AP      : 0.60    : pathway-inhibition fraction giving half-maximal apoptosis
HAP        : 3.0     : Hill coefficient for the cytostatic-to-cytocidal transition
BIMFAC_WT  : 1.0     : BIM apoptotic competence, wild-type
BIMFAC_DEL : 0.55    : BIM apoptotic competence, intron-2 2903-bp deletion carrier
WVASC      : 0.45    : fraction of proliferative drive requiring vascular support (KIT-driven clones)
WVASC_SDH  : 0.85    : same, for SDH-deficient/pseudohypoxic clone (highly VEGF-dependent)
MU_A       : 8.0e-4  : mutant-supply coefficient, exon 13/14 (resistant clone volume generated per unit sensitive-clone proliferative flux; lumps mutation rate x number of resistance codons x outgrowth probability)
MU_L       : 6.5e-4  : mutant-supply coefficient, exon 17/18
MU_IND     : 4.0e-5  : mutant-supply coefficient, KIT-independent escape
FRAC_A0    : 3.0e-4  : pre-existing exon 13/14 subclone fraction at baseline
FRAC_L0    : 2.4e-4  : pre-existing exon 17/18 subclone fraction at baseline
FRAC_IND0  : 1.0e-5  : pre-existing KIT-independent subclone fraction at baseline
FITCOST    : 0.92    : relative fitness of secondary-mutant clones vs sensitive clone

//--------------------------------------------------------------------------
// Quiescent drug-tolerant persister pool (autophagy-dependent)
//--------------------------------------------------------------------------
KQIN       : 0.009   : 1/day, maximal rate of drug-induced entry into quiescence
KQOUT      : 0.020   : 1/day, maximal rate of re-entry into cycle when signaling recovers
KDQ        : 0.0015  : 1/day, slow attrition of the quiescent pool

//--------------------------------------------------------------------------
// Tumor vascular support (VEGFR2 / PDGFRB / TIE2 dependent)
//--------------------------------------------------------------------------
KANG       : 0.06    : 1/day, turnover of the vascular support index
ICA_SUN    : 5       : nM, sunitinib effective IC50 for anti-angiogenic effect
ICA_REG    : 12      : nM, regorafenib effective IC50 for anti-angiogenic effect
ICA_RIP    : 40      : nM, ripretinib effective IC50 for anti-angiogenic effect (weak)
ANG_FLOOR  : 0.20    : residual vascular support under maximal VEGFR blockade

//--------------------------------------------------------------------------
// Signal transduction readouts
//--------------------------------------------------------------------------
KPKIT      : 24      : 1/day, phospho-KIT turnover (hours)
KAKT       : 12      : 1/day, AKT/mTOR pathway turnover
KERK       : 12      : 1/day, ERK pathway turnover
KETV1      : 0.8     : 1/day, ETV1 protein turnover (ERK-stabilized)
KBIM       : 1.2     : 1/day, BIM protein turnover
BIM_MAX    : 3.0     : maximal fold BIM induction on full pathway shutdown

//--------------------------------------------------------------------------
// Imaging biomarkers
//--------------------------------------------------------------------------
SUV_BASE   : 9.0     : baseline FDG-PET SUVmax
SUV_MIN    : 1.8     : SUVmax floor at full KIT shutdown (background liver)
KSUV       : 1.5     : 1/day, SUV equilibration (metabolic response within 24-48 h)
HU_BASE    : 70      : Hounsfield units, baseline contrast-enhanced tumor attenuation
HU_MIN     : 22      : HU floor of fully myxoid/cystic responding tumor
KHU        : 0.055   : 1/day, CT density equilibration (weeks)
KHU50      : 0.010   : 1/day, kill rate giving half-maximal myxoid-degeneration drive
KMYX_IN    : 0.045   : 1/day, rate of accumulating myxoid/cystic degeneration
KMYX_OUT   : 0.004   : 1/day, slow reversal of myxoid degeneration (density recovers on progression)

//--------------------------------------------------------------------------
// Circulating tumor DNA
//--------------------------------------------------------------------------
SHED_P     : 0.35    : ctDNA shed per unit proliferative flux (arb/mL/day)
SHED_D     : 3.2     : ctDNA shed per unit death flux (apoptotic release dominates)
KEL_CTD    : 12      : 1/day, plasma cfDNA elimination (t1/2 ~ 1.4 h)
CFDNA_WT   : 12      : background wild-type cfDNA level (sets the VAF denominator)
LOD_VAF    : 0.10    : % VAF, assay limit of detection

//--------------------------------------------------------------------------
// Toxicity / organ-system effects
//--------------------------------------------------------------------------
KED        : 0.08    : 1/day, edema equilibration
EMAX_ED    : 2.6     : maximal periorbital/peripheral edema score (0-4 CTCAE-like)
EC50_ED    : 120     : nM, imatinib effective conc for half-maximal edema
KIN_ANC    : 0.60    : x10^9/L/day, neutrophil production
KOUT_ANC   : 0.15    : 1/day, neutrophil elimination (ANC baseline = KIN/KOUT = 4.0)
MS_IMA     : 0.30    : maximal fractional myelosuppression, imatinib
MS_SUN     : 0.42    : maximal fractional myelosuppression, sunitinib
MS_REG     : 0.18    : maximal fractional myelosuppression, regorafenib
MS_RIP     : 0.12    : maximal fractional myelosuppression, ripretinib
EC50_MS    : 1.0     : relative-exposure scaling for myelosuppression Emax terms
KIN_TSH    : 0.55    : mIU/L/day, TSH production
KOUT_TSH   : 0.33    : 1/day, TSH elimination (baseline = 1.67 mIU/L)
ETSH_MAX   : 2.4     : maximal fold TSH rise (sunitinib-induced hypothyroidism)
EC50_TSH   : 9       : nM, sunitinib effective conc for half-maximal TSH rise
KSBP       : 0.12    : 1/day, blood-pressure equilibration
SBP0       : 126     : mmHg, baseline systolic blood pressure
DSBP_MAX   : 24      : mmHg, maximal VEGFR-blockade-induced systolic rise
KHFS       : 0.10    : 1/day, hand-foot skin reaction equilibration
HFS_MAX    : 2.8     : maximal HFSR score (0-3 CTCAE-like)
EC50_HFS_R : 25      : nM, regorafenib effective conc for half-maximal HFSR
EC50_HFS_S : 12      : nM, sunitinib effective conc for half-maximal HFSR

[CMT] @annotated
IMA_DEPOT : mg, imatinib gut depot
IMA_CENT  : mg, imatinib central compartment
IMA_PER   : mg, imatinib peripheral compartment
SUN_DEPOT : mg, sunitinib gut depot
SUN_CENT  : mg, sunitinib central compartment
REG_DEPOT : mg, regorafenib gut depot
REG_CENT  : mg, regorafenib central compartment
RIP_DEPOT : mg, ripretinib gut depot
RIP_CENT  : mg, ripretinib central compartment
AVA_DEPOT : mg, avapritinib gut depot
AVA_CENT  : mg, avapritinib central compartment
AAG       : rel, alpha-1-acid glycoprotein (imatinib binding protein)
TS        : mL, primary-driver sensitive tumor clone
TQ        : mL, quiescent drug-tolerant persister pool
TA        : mL, exon 13/14 ATP-pocket resistant clone
TL        : mL, exon 17/18 activation-loop resistant clone
TD        : mL, primary-refractory clone (PDGFRA D842V or SDH-deficient)
TI        : mL, KIT-independent bypass clone
PKIT      : frac, aggregate phospho-KIT signaling activity (1 = untreated)
AKTP      : frac, PI3K/AKT/mTOR pathway activity
ERKP      : frac, RAS/RAF/MEK/ERK pathway activity
ETV1      : frac, ETV1 lineage transcription factor level
BIM       : frac, BIM (BCL2L11) pro-apoptotic protein level
ANG       : frac, tumor vascular support index
CTDS      : arb, plasma ctDNA from sensitive/primary clone
CTDR      : arb, plasma ctDNA from resistant clones
SUV       : SUV, FDG-PET SUVmax
HU        : HU, tumor CT attenuation (Choi criteria)
MYX       : frac, cumulative myxoid/cystic degeneration
EDEMA     : score, periorbital/peripheral edema (0-4)
ANC       : 10^9/L, absolute neutrophil count
TSH       : mIU/L, thyroid stimulating hormone
SBP       : mmHg, systolic blood pressure
HFS       : score, hand-foot skin reaction (0-3)

[GLOBAL]
// Genotype-resolved quantities, assigned in [MAIN], visible in [ODE]/[TABLE]
double gIC_IMA_S, gIC_IMA_A, gIC_IMA_L;
double gIC_SUN_S, gIC_SUN_A, gIC_SUN_L;
double gIC_AVA_D;
double gBIMF, gWV_D, gTB0;
double gCL_IMA_T;

[MAIN]
//--------------------------------------------------------------------------
// Genotype resolution
//   GENO 1 = KIT exon 11 (reference)
//   GENO 2 = KIT exon 9   -> 4-fold imatinib IC50 rise (dose 800 mg matters),
//                            sunitinib slightly MORE potent
//   GENO 3 = PDGFRA D842V -> tumor is essentially all "primary-refractory"
//                            clone; avapritinib is the only active agent
//   GENO 4 = SDH-deficient/quadruple-WT -> KIT-independent, strongly
//                            VEGF-dependent; TKI benefit is anti-angiogenic
//   GENO 5 = KIT exon 11 + BIM intron-2 deletion polymorphism (apoptosis-
//                            impaired; cytostatic rather than cytocidal)
//--------------------------------------------------------------------------
double f9  = (GENO == 2) ? GF_EX9 : 1.0;
gIC_IMA_S  = IC_IMA_S * f9;
gIC_IMA_A  = IC_IMA_A * f9;
gIC_IMA_L  = IC_IMA_L * f9;
gIC_SUN_S  = IC_SUN_S * ((GENO == 2) ? GF_EX9_SUN : 1.0);
gIC_SUN_A  = IC_SUN_A * ((GENO == 2) ? GF_EX9_SUN : 1.0);
gIC_SUN_L  = IC_SUN_L * ((GENO == 2) ? GF_EX9_SUN : 1.0);
gIC_AVA_D  = (GENO == 4) ? IC_AVA_D_SDH : IC_AVA_D;
gBIMF      = (GENO == 5) ? BIMFAC_DEL : BIMFAC_WT;
gWV_D      = (GENO == 4) ? WVASC_SDH  : WVASC;

// Time-dependent apparent imatinib clearance (rises ~35% toward steady state)
gCL_IMA_T  = CL_IMA * CLFAC_IMA * (1.0 + FCLDRIFT*(1.0 - exp(-KDRIFT*TIME)));

//--------------------------------------------------------------------------
// Initial conditions — baseline clonal composition
//--------------------------------------------------------------------------
gTB0 = (ADJUVANT > 0) ? TB0_ADJ : TB0;

double refractory_dominant = (GENO == 3 || GENO == 4) ? 1.0 : 0.0;
double fD0 = refractory_dominant ? 0.985 : 1.0e-4;
double fA0 = refractory_dominant ? FRAC_A0*0.05 : FRAC_A0;
double fL0 = refractory_dominant ? FRAC_L0*0.05 : FRAC_L0;
double fI0 = FRAC_IND0;
double fS0 = 1.0 - fD0 - fA0 - fL0 - fI0;
if (fS0 < 0) fS0 = 0;

TS_0 = gTB0 * fS0;
TA_0 = gTB0 * fA0;
TL_0 = gTB0 * fL0;
TD_0 = gTB0 * fD0;
TI_0 = gTB0 * fI0;
TQ_0 = 0.0;

AAG_0   = AAG_REF * (1.0 + GAAG*gTB0/500.0);
PKIT_0  = 1.0;
AKTP_0  = 1.0;
ERKP_0  = 1.0;
ETV1_0  = 1.0;
BIM_0   = 1.0;
ANG_0   = 1.0;
CTDS_0  = SHED_P*KG*TS_0/KEL_CTD;
CTDR_0  = SHED_P*KG*(TA_0+TL_0+TD_0+TI_0)/KEL_CTD;
SUV_0   = SUV_BASE;
HU_0    = HU_BASE;
MYX_0   = 0.0;
EDEMA_0 = 0.0;
ANC_0   = KIN_ANC/KOUT_ANC;
TSH_0   = KIN_TSH/KOUT_TSH;
SBP_0   = SBP0;
HFS_0   = 0.0;

[ODE]
//==========================================================================
// 1. DRUG PHARMACOKINETICS
//==========================================================================
dxdt_IMA_DEPOT = -KA_IMA*IMA_DEPOT;
dxdt_IMA_CENT  =  KA_IMA*IMA_DEPOT - (gCL_IMA_T/V1_IMA)*IMA_CENT
                  - (Q_IMA/V1_IMA)*IMA_CENT + (Q_IMA/V2_IMA)*IMA_PER;
dxdt_IMA_PER   =  (Q_IMA/V1_IMA)*IMA_CENT - (Q_IMA/V2_IMA)*IMA_PER;

dxdt_SUN_DEPOT = -KA_SUN*SUN_DEPOT;
dxdt_SUN_CENT  =  KA_SUN*SUN_DEPOT - (CL_SUN/V1_SUN)*SUN_CENT;

dxdt_REG_DEPOT = -KA_REG*REG_DEPOT;
dxdt_REG_CENT  =  KA_REG*REG_DEPOT - (CL_REG/V1_REG)*REG_CENT;

dxdt_RIP_DEPOT = -KA_RIP*RIP_DEPOT;
dxdt_RIP_CENT  =  KA_RIP*RIP_DEPOT - (CL_RIP/V1_RIP)*RIP_CENT;

dxdt_AVA_DEPOT = -KA_AVA*AVA_DEPOT;
dxdt_AVA_CENT  =  KA_AVA*AVA_DEPOT - (CL_AVA/V1_AVA)*AVA_CENT;

//--------------------------------------------------------------------------
// Total tumor burden (needed for the AAG acute-phase term)
//--------------------------------------------------------------------------
double Ttot = TS + TQ + TA + TL + TD + TI;
if (Ttot < 1e-9) Ttot = 1e-9;

// Alpha-1-acid glycoprotein: acute-phase protein induced by tumor burden.
// High AAG sequesters imatinib -> LOWER free drug at the SAME total plasma
// concentration (Widmer 2006). This is why total-drug TDM can mislead.
dxdt_AAG = KIN_AAG*AAG_REF*(1.0 + GAAG*Ttot/500.0) - KOUT_AAG*AAG;

//--------------------------------------------------------------------------
// Effective target-site concentrations (nM)
//--------------------------------------------------------------------------
double aag_now  = (AAG > 0.05) ? AAG : 0.05;
double ft_ima   = FT_IMA * (AAG_REF/aag_now);

double Eima = ft_ima * 1.0e6 * IMA_CENT / (V1_IMA * MW_IMA);
double Esun = FT_SUN * 1.0e6 * SUN_CENT / (V1_SUN * MW_SUN);
double Ereg = FT_REG * 1.0e6 * REG_CENT / (V1_REG * MW_REG);
double Erip = FT_RIP * 1.0e6 * RIP_CENT / (V1_RIP * MW_RIP);
double Eava = FT_AVA * 1.0e6 * AVA_CENT / (V1_AVA * MW_AVA);

//==========================================================================
// 2. DRUG x CLONE PATHWAY SUPPRESSION
//    Residual KIT/PDGFRA signaling in clone j under all drugs simultaneously
//    (Bliss-independent combination of competitive inhibition terms).
//==========================================================================
double res_S = 1.0/((1.0+Eima/gIC_IMA_S)*(1.0+Esun/gIC_SUN_S)
                   *(1.0+Ereg/IC_REG_S)*(1.0+Erip/IC_RIP_S)*(1.0+Eava/IC_AVA_S));
double res_A = 1.0/((1.0+Eima/gIC_IMA_A)*(1.0+Esun/gIC_SUN_A)
                   *(1.0+Ereg/IC_REG_A)*(1.0+Erip/IC_RIP_A)*(1.0+Eava/IC_AVA_A));
double res_L = 1.0/((1.0+Eima/gIC_IMA_L)*(1.0+Esun/gIC_SUN_L)
                   *(1.0+Ereg/IC_REG_L)*(1.0+Erip/IC_RIP_L)*(1.0+Eava/IC_AVA_L));
double res_D = 1.0/((1.0+Eima/IC_IMA_D)*(1.0+Esun/IC_SUN_D)
                   *(1.0+Ereg/IC_REG_D)*(1.0+Erip/IC_RIP_D)*(1.0+Eava/gIC_AVA_D));
double res_I = 1.0;   // KIT-independent bypass clone: no KIT-directed effect

double inh_S = 1.0 - res_S;
double inh_A = 1.0 - res_A;
double inh_L = 1.0 - res_L;
double inh_D = 1.0 - res_D;

//==========================================================================
// 3. TUMOR VASCULAR SUPPORT (VEGFR2/PDGFRB/TIE2)
//    The mechanism by which sunitinib and regorafenib retain activity in
//    KIT-refractory disease, and the main mechanism in SDH-deficient GIST.
//==========================================================================
double ang_ss = ANG_FLOOR + (1.0 - ANG_FLOOR)
                /(1.0 + Esun/ICA_SUN + Ereg/ICA_REG + Erip/ICA_RIP);
dxdt_ANG = KANG*(ang_ss - ANG);

double vasc_kit = (1.0 - WVASC) + WVASC*ANG;   // vascular modifier, KIT-driven clones
double vasc_ref = (1.0 - gWV_D) + gWV_D*ANG;   // vascular modifier, refractory clone

//==========================================================================
// 4. CLONAL POPULATION DYNAMICS
//    Growth  ~ KG * residual signaling * vascular support * logistic space
//    Death   ~ baseline + apoptotic drive that is a SIGMOID of inhibition,
//              i.e. partial inhibition is cytostatic, deep inhibition is
//              cytocidal (and is blunted by the BIM deletion polymorphism).
//==========================================================================
double space = 1.0 - Ttot/TMAX_BURDEN;
if (space < 0) space = 0;

double ap_S = EMAX_AP*gBIMF*pow(inh_S,HAP)/(pow(IC_AP,HAP)+pow(inh_S,HAP));
double ap_A = EMAX_AP*gBIMF*pow(inh_A,HAP)/(pow(IC_AP,HAP)+pow(inh_A,HAP));
double ap_L = EMAX_AP*gBIMF*pow(inh_L,HAP)/(pow(IC_AP,HAP)+pow(inh_L,HAP));
double ap_D = EMAX_AP*gBIMF*pow(inh_D,HAP)/(pow(IC_AP,HAP)+pow(inh_D,HAP));

double prol_S = KG          * res_S * vasc_kit * space * TS;
double prol_A = KG*FITCOST  * res_A * vasc_kit * space * TA;
double prol_L = KG*FITCOST  * res_L * vasc_kit * space * TL;
double prol_D = KG*FITCOST  * res_D * vasc_ref * space * TD;
double prol_I = KG*FITCOST  * res_I * vasc_kit * space * TI;

// Mutant supply is proportional to the DIVISION FLUX of the sensitive clone:
// a large, actively cycling sensitive clone manufactures its own resistance.
// This is what couples imatinib DOSE (which controls res_S) to PFS.
double sup_A = MU_A   * prol_S;
double sup_L = MU_L   * prol_S;
double sup_I = MU_IND * prol_S;

// Drug-induced quiescence (autophagy-dependent persister pool). Cells leave
// the cycling compartment when signaling is shut down and return when it
// recovers -> the source of rapid rebound after treatment interruption.
double q_in  = KQIN  * inh_S * TS;
double q_out = KQOUT * res_S * TQ;

dxdt_TS = prol_S - (KD0 + ap_S)*TS - sup_A - sup_L - sup_I - q_in + q_out;
dxdt_TQ = q_in - q_out - KDQ*TQ;
dxdt_TA = prol_A - (KD0 + ap_A)*TA + sup_A;
dxdt_TL = prol_L - (KD0 + ap_L)*TL + sup_L;
dxdt_TD = prol_D - (KD0 + ap_D)*TD;
dxdt_TI = prol_I - KD0*TI + sup_I;

//==========================================================================
// 5. SIGNAL TRANSDUCTION READOUTS (burden-weighted across clones)
//==========================================================================
double res_bar = (res_S*(TS+TQ) + res_A*TA + res_L*TL + res_D*TD + res_I*TI)/Ttot;

dxdt_PKIT = KPKIT*(res_bar - PKIT);
dxdt_AKTP = KAKT *(PKIT    - AKTP);
dxdt_ERKP = KERK *(PKIT    - ERKP);
dxdt_ETV1 = KETV1*(ERKP    - ETV1);           // ERK stabilizes ETV1 protein
dxdt_BIM  = KBIM *(1.0 + (BIM_MAX-1.0)*(1.0-ERKP)*gBIMF - BIM);

//==========================================================================
// 6. IMAGING BIOMARKERS
//    FDG-PET SUV tracks GLUT1/hexokinase, i.e. pKIT, within 24-48 h.
//    CT attenuation (Choi) tracks accumulated myxoid/cystic degeneration and
//    therefore falls WEEKS BEFORE any RECIST size change.
//==========================================================================
double suv_ss = SUV_MIN + (SUV_BASE - SUV_MIN)*PKIT;
dxdt_SUV = KSUV*(suv_ss - SUV);

double kill_flux = ap_S*TS + ap_A*TA + ap_L*TL + ap_D*TD;
double kill_rate_rel = kill_flux/Ttot;
// Myxoid/cystic degeneration is CUMULATIVE and only slowly reversible: this is
// why Choi density stays low for as long as therapy works, and climbs back
// when a resistant nodule starts to re-enhance.
dxdt_MYX = KMYX_IN*( kill_rate_rel/(KHU50 + kill_rate_rel) )*(1.0 - MYX)
           - KMYX_OUT*MYX;
double hu_ss = HU_BASE - (HU_BASE - HU_MIN)*MYX;
dxdt_HU = KHU*(hu_ss - HU);

//==========================================================================
// 7. CIRCULATING TUMOR DNA — clone-resolved
//    Resistant-clone ctDNA rises while total burden is still falling:
//    molecular progression precedes radiologic progression.
//==========================================================================
double death_S = (KD0 + ap_S)*TS + KDQ*TQ;
double death_R = (KD0 + ap_A)*TA + (KD0 + ap_L)*TL + (KD0 + ap_D)*TD + KD0*TI;
dxdt_CTDS = SHED_P*prol_S + SHED_D*death_S - KEL_CTD*CTDS;
dxdt_CTDR = SHED_P*(prol_A + prol_L + prol_D + prol_I)
            + SHED_D*death_R - KEL_CTD*CTDR;

//==========================================================================
// 8. ORGAN-SYSTEM TOXICITY
//==========================================================================
// Periorbital / peripheral edema — PDGFR-beta inhibition, imatinib-dominant
dxdt_EDEMA = KED*( EMAX_ED*Eima/(EC50_ED + Eima) - EDEMA );

// Myelosuppression — KIT/FLT3 on hematopoietic progenitors
double myelo = MS_IMA*(Eima/gIC_IMA_S)/(EC50_MS + Eima/gIC_IMA_S)
             + MS_SUN*(Esun/IC_SUN_S)/(EC50_MS + Esun/IC_SUN_S)
             + MS_REG*(Ereg/IC_REG_S)/(EC50_MS + Ereg/IC_REG_S)
             + MS_RIP*(Erip/IC_RIP_S)/(EC50_MS + Erip/IC_RIP_S);
if (myelo > 0.85) myelo = 0.85;
dxdt_ANC = KIN_ANC*(1.0 - myelo) - KOUT_ANC*ANC;

// Hypothyroidism — essentially sunitinib-specific
dxdt_TSH = KIN_TSH*(1.0 + ETSH_MAX*Esun/(EC50_TSH + Esun)) - KOUT_TSH*TSH;

// Hypertension — VEGFR blockade; tracks the anti-angiogenic effect itself
double aai = 1.0 - (ang_ss - ANG_FLOOR)/(1.0 - ANG_FLOOR);
dxdt_SBP = KSBP*(SBP0 + DSBP_MAX*aai - SBP);

// Hand-foot skin reaction — regorafenib > sunitinib
double hfs_ss = HFS_MAX*( 0.75*Ereg/(EC50_HFS_R + Ereg)
                        + 0.35*Esun/(EC50_HFS_S + Esun) );
if (hfs_ss > HFS_MAX) hfs_ss = HFS_MAX;
dxdt_HFS = KHFS*(hfs_ss - HFS);

[TABLE]
//--------------------------------------------------------------------------
// Burden, composition and response criteria
//--------------------------------------------------------------------------
double TT   = TS + TQ + TA + TL + TD + TI;
if (TT < 1e-9) TT = 1e-9;
double TRES = TA + TL + TD + TI;

capture Tumor_burden_mL   = TT;
capture Clone_sensitive   = TS;
capture Clone_quiescent   = TQ;
capture Clone_exon13_14   = TA;
capture Clone_exon17_18   = TL;
capture Clone_refractory  = TD;
capture Clone_KIT_indep   = TI;
capture Resistant_frac    = TRES/TT;

// RECIST is a DIAMETER criterion: volume^(1/3)
capture RECIST_pct_change = 100.0*(pow(TT/gTB0, 1.0/3.0) - 1.0);
capture CT_density_HU     = HU;
capture Choi_density_pct  = 100.0*(HU/HU_BASE - 1.0);
capture SUVmax            = SUV;
capture SUV_pct_change    = 100.0*(SUV/SUV_BASE - 1.0);

// Choi partial response = density fall >=15% OR size fall >=10%
capture Choi_PR = ( (100.0*(HU/HU_BASE - 1.0) <= -15.0) ||
                    (100.0*(pow(TT/gTB0,1.0/3.0)-1.0) <= -10.0) ) ? 1.0 : 0.0;
// RECIST PR = >=30% diameter fall; RECIST PD = >=20% diameter rise from nadir
capture RECIST_PR = (100.0*(pow(TT/gTB0,1.0/3.0)-1.0) <= -30.0) ? 1.0 : 0.0;

//--------------------------------------------------------------------------
// Drug exposures
//--------------------------------------------------------------------------
capture Imatinib_ng_mL    = 1000.0*IMA_CENT/V1_IMA;
capture Imatinib_Cmin_ok  = (1000.0*IMA_CENT/V1_IMA >= 1100.0) ? 1.0 : 0.0;
capture Sunitinib_ng_mL   = 1000.0*SUN_CENT/V1_SUN;
capture Regorafenib_ng_mL = 1000.0*REG_CENT/V1_REG;
capture Ripretinib_ng_mL  = 1000.0*RIP_CENT/V1_RIP;
capture Avapritinib_ng_mL = 1000.0*AVA_CENT/V1_AVA;
capture AAG_level         = AAG;

//--------------------------------------------------------------------------
// Pathway and biomarkers
//--------------------------------------------------------------------------
capture pKIT_activity     = PKIT;
capture AKT_activity      = AKTP;
capture ERK_activity      = ERKP;
capture ETV1_level        = ETV1;
capture BIM_level         = BIM;
capture Vascular_support  = ANG;

double vaf_tot = 100.0*(CTDS + CTDR)/(CTDS + CTDR + CFDNA_WT);
double vaf_res = 100.0*(CTDR)/(CTDS + CTDR + CFDNA_WT);
capture ctDNA_VAF_total     = vaf_tot;
capture ctDNA_VAF_resistant = vaf_res;
capture ctDNA_res_detected  = (vaf_res >= LOD_VAF) ? 1.0 : 0.0;

//--------------------------------------------------------------------------
// Toxicity
//--------------------------------------------------------------------------
capture Edema_score       = EDEMA;
capture Neutrophils       = ANC;
capture Neutropenia_G34   = (ANC < 1.0) ? 1.0 : 0.0;
capture TSH_level         = TSH;
capture Hypothyroid       = (TSH > 5.0) ? 1.0 : 0.0;
capture Systolic_BP       = SBP;
capture Hypertension_G3   = (SBP >= 160.0) ? 1.0 : 0.0;
capture HFSR_score        = HFS;

[CAPTURE]
Tumor_burden_mL Clone_sensitive Clone_quiescent Clone_exon13_14 Clone_exon17_18
Clone_refractory Clone_KIT_indep Resistant_frac
RECIST_pct_change CT_density_HU Choi_density_pct SUVmax SUV_pct_change
Choi_PR RECIST_PR
Imatinib_ng_mL Imatinib_Cmin_ok Sunitinib_ng_mL Regorafenib_ng_mL
Ripretinib_ng_mL Avapritinib_ng_mL AAG_level
pKIT_activity AKT_activity ERK_activity ETV1_level BIM_level Vascular_support
ctDNA_VAF_total ctDNA_VAF_resistant ctDNA_res_detected
Edema_score Neutrophils Neutropenia_G34 TSH_level Hypothyroid
Systolic_BP Hypertension_G3 HFSR_score


##  ============================================================================
##  R-side scenario helpers (documentation; parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(purrr); library(ggplot2)
##  mod <- mread_cache("gist_mrgsolve_model.R")
##
##  # ---------- Dosing building blocks ----------
##  # All doses are oral once-daily unless noted. `addl` covers the horizon.
##  d_ima  <- function(mg = 400, start = 0, days = 1460)
##      ev(amt = mg, cmt = "IMA_DEPOT", time = start, ii = 1, addl = days - 1)
##  d_sun  <- function(mg = 50, start = 0, cycles = 12)   # 4 weeks on / 2 off
##      purrr::map_dfr(seq_len(cycles) - 1, function(k)
##        as.data.frame(ev(amt = mg, cmt = "SUN_DEPOT",
##                         time = start + k*42, ii = 1, addl = 27)))
##  d_reg  <- function(mg = 160, start = 0, cycles = 16)  # 3 weeks on / 1 off
##      purrr::map_dfr(seq_len(cycles) - 1, function(k)
##        as.data.frame(ev(amt = mg, cmt = "REG_DEPOT",
##                         time = start + k*28, ii = 1, addl = 20)))
##  d_rip  <- function(mg = 150, start = 0, days = 365)
##      ev(amt = mg, cmt = "RIP_DEPOT", time = start, ii = 1, addl = days - 1)
##  d_ava  <- function(mg = 300, start = 0, days = 730)
##      ev(amt = mg, cmt = "AVA_DEPOT", time = start, ii = 1, addl = days - 1)
##
##  # ---------- 11 prebuilt scenarios ----------
##  GIST_scenarios <- function(end_d = 1460) {
##
##    list(
##      # 1. Untreated metastatic natural history (KIT exon 11)
##      "1. Natural history, untreated" =
##        list(par = list(GENO = 1), ev = ev(amt = 0, cmt = "IMA_DEPOT")),
##
##      # 2. First-line imatinib 400 mg — the canonical response-then-resistance
##      #    curve. Expect deep Choi/SUV response by weeks, RECIST nadir by
##      #    ~6-9 months, resistant-clone ctDNA rising from ~month 10-14, and
##      #    radiologic progression at ~20-24 months (B2222 / EORTC 62005).
##      "2. Imatinib 400 mg, KIT exon 11" =
##        list(par = list(GENO = 1), ev = d_ima(400, 0, end_d)),
##
##      # 3-4. KIT exon 9: 400 vs 800 mg (MetaGIST PFS benefit at 800 mg)
##      "3. Imatinib 400 mg, KIT exon 9" =
##        list(par = list(GENO = 2), ev = d_ima(400, 0, end_d)),
##      "4. Imatinib 800 mg, KIT exon 9" =
##        list(par = list(GENO = 2), ev = d_ima(800, 0, end_d)),
##
##      # 5. Sub-therapeutic trough (fast CYP3A4 metabolizer / poor adherence):
##      #    Cmin below the 1100 ng/mL threshold shortens PFS *mechanistically*,
##      #    because a less-suppressed sensitive clone supplies more mutants.
##      "5. Imatinib 400 mg, high clearance (Cmin < 1100)" =
##        list(par = list(GENO = 1, CLFAC_IMA = 1.9), ev = d_ima(400, 0, end_d)),
##      "6. Same patient, TDM-guided escalation to 600 mg" =
##        list(par = list(GENO = 1, CLFAC_IMA = 1.9), ev = d_ima(600, 0, end_d)),
##
##      # 7. Treatment interruption at 1 year (BFR14): rapid regrowth from the
##      #    quiescent persister pool, and NOT rescued to the original curve.
##      "7. Imatinib stopped at day 365 (BFR14)" =
##        list(par = list(GENO = 1), ev = d_ima(400, 0, 365)),
##
##      # 8. Standard sequential therapy: imatinib -> sunitinib -> regorafenib
##      #    -> ripretinib. Each line re-shapes the clonal composition.
##      "8. Sequential IMA -> SUN -> REG -> RIP" =
##        list(par = list(GENO = 1),
##             ev = rbind(as.data.frame(d_ima(400, 0, 700)),
##                        d_sun(50, 700, 6),
##                        d_reg(160, 950, 6),
##                        as.data.frame(d_rip(150, 1120, 340)))),
##
##      # 9. INTRIGUE re-creation. Run the SAME post-imatinib patient on
##      #    sunitinib vs ripretinib, once with an exon 13/14-dominant clonal
##      #    background and once with an exon 17/18-dominant one, by setting
##      #    FRAC_A0 / FRAC_L0. Overall (mixed) the two arms are near-identical
##      #    — the trial's negative primary endpoint — while the subgroups
##      #    separate in opposite directions (Bauer 2024 Nat Med ctDNA analysis).
##      "9a. 2L sunitinib, exon 13/14-dominant" =
##        list(par = list(GENO = 1, FRAC_A0 = 4e-3, FRAC_L0 = 1e-4),
##             ev = rbind(as.data.frame(d_ima(400, 0, 640)), d_sun(50, 640, 12))),
##      "9b. 2L ripretinib, exon 13/14-dominant" =
##        list(par = list(GENO = 1, FRAC_A0 = 4e-3, FRAC_L0 = 1e-4),
##             ev = rbind(as.data.frame(d_ima(400, 0, 640)),
##                        as.data.frame(d_rip(150, 640, 640)))),
##      "9c. 2L sunitinib, exon 17/18-dominant" =
##        list(par = list(GENO = 1, FRAC_A0 = 1e-4, FRAC_L0 = 4e-3),
##             ev = rbind(as.data.frame(d_ima(400, 0, 640)), d_sun(50, 640, 12))),
##      "9d. 2L ripretinib, exon 17/18-dominant" =
##        list(par = list(GENO = 1, FRAC_A0 = 1e-4, FRAC_L0 = 4e-3),
##             ev = rbind(as.data.frame(d_ima(400, 0, 640)),
##                        as.data.frame(d_rip(150, 640, 640)))),
##
##      # 10. PDGFRA D842V: imatinib does nothing; avapritinib is dramatic.
##      "10a. PDGFRA D842V on imatinib 400 mg" =
##        list(par = list(GENO = 3), ev = d_ima(400, 0, end_d)),
##      "10b. PDGFRA D842V on avapritinib 300 mg" =
##        list(par = list(GENO = 3), ev = d_ava(300, 0, end_d)),
##
##      # 11. SDH-deficient GIST: KIT-directed therapy is inert, but sunitinib
##      #     still slows growth through the anti-angiogenic arm.
##      "11a. SDH-deficient on imatinib" =
##        list(par = list(GENO = 4), ev = d_ima(400, 0, end_d)),
##      "11b. SDH-deficient on sunitinib" =
##        list(par = list(GENO = 4), ev = d_sun(37.5, 0, 24)),
##
##      # 12. Adjuvant imatinib x 3 y after R0 resection of a high-risk tumor
##      #     (SSGXVIII): recurrence is DELAYED, and the recurrence hazard
##      #     re-emerges after stopping — the model reproduces the
##      #     "shift, not cure" shape of the adjuvant curves.
##      "12a. High-risk resected, no adjuvant" =
##        list(par = list(GENO = 1, ADJUVANT = 1), ev = ev(amt = 0, cmt = "IMA_DEPOT")),
##      "12b. High-risk resected, adjuvant imatinib 3 y" =
##        list(par = list(GENO = 1, ADJUVANT = 1), ev = d_ima(400, 0, 1095)),
##
##      # 13. BIM deletion polymorphism carrier (~12% of East Asians):
##      #     same exposure, same pathway inhibition, blunted apoptosis.
##      "13. KIT exon 11 + BIM intron-2 deletion" =
##        list(par = list(GENO = 5), ev = d_ima(400, 0, end_d))
##    )
##  }
##
##  GIST_run <- function(end_d = 1460, delta = 1) {
##    purrr::imap_dfr(GIST_scenarios(end_d), function(s, lab) {
##      m <- mod
##      if (length(s$par)) m <- do.call(param, c(list(m), s$par))
##      mrgsim(m, data = s$ev, end = end_d, delta = delta) |>
##        as_tibble() |> mutate(scenario = lab)
##    })
##  }
##
##  # ---------- Derived trial-style summaries ----------
##  # Time to radiologic progression = first time the summed diameter rises
##  # >=20% RELATIVE to its running nadir (RECIST 1.1). See the 'known artifact'
##  # note in the calibration section before comparing arms of unequal depth.
##  pfs_days <- function(df) {
##    df |> group_by(scenario) |> arrange(time) |>
##      mutate(diam = 100 + RECIST_pct_change) |>
##      filter(diam / cummin(diam) >= 1.20) |>   # RECIST 1.1: +20% RELATIVE to nadir
##      summarise(PFS_days = first(time), .groups = "drop")
##  }
##  # Lead time of molecular over radiologic progression
##  lead_time <- function(df) {
##    mol <- df |> group_by(scenario) |> filter(ctDNA_res_detected > 0) |>
##      summarise(mol_d = first(time), .groups = "drop")
##    left_join(pfs_days(df), mol, by = "scenario") |>
##      mutate(lead_days = PFS_days - mol_d)
##  }
##
##  # ---------- Quick sanity plots ----------
##  # df <- GIST_run()
##  # ggplot(df, aes(time, RECIST_pct_change, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Tumor_burden_mL, colour = scenario)) +
##  #   geom_line() + scale_y_log10()
##  # ggplot(df, aes(time, ctDNA_VAF_resistant, colour = scenario)) + geom_line()
##
##  ============================================================================
##  CALIBRATION NOTES — what each number is anchored to, and what was CHECKED
##  ============================================================================
##
##  Everything below marked [VERIFIED] was produced by numerically integrating
##  these exact equations and comparing the output to the cited trial. Numbers
##  quoted are simulation output, not aspiration. One target was NOT met and is
##  flagged as such rather than tuned away.
##
##  --- PK -------------------------------------------------------------------
##  Imatinib CL/F 183 L/d at the first dose, drifting to ~247 L/d (10.3 L/h) at
##  steady state via FCLDRIFT/KDRIFT, with total Vd/F 353 L (V1 200 + V2 153,
##  Q 600 L/d for rapid distribution). [VERIFIED] this gives a day-180 trough of
##  1,231 ng/mL at 400 mg/d, against the reported steady-state Cmin of
##  ~1,110 ng/mL and the ~1,100 ng/mL efficacy threshold of Demetri 2009
##  (J Clin Oncol 27:3141, PMID 19451435). The clearance drift reproduces the
##  ~30% fall in imatinib exposure between first dose and one year of
##  continuous therapy (Eechoute 2012 Clin Cancer Res 18:5780, PMID 22850565).
##  Sunitinib CL/F 816 L/d gives total (parent + SU12662) Cavg ~60 ng/mL at
##  50 mg/d, the target steady-state range. Regorafenib, ripretinib and
##  avapritinib volumes/clearances reproduce their reported Cmax ranges.
##
##  --- Protein binding and the effective-concentration convention ------------
##  FT_* are CALIBRATED EFFECTIVE target-site availability fractions, folding
##  together unbound fraction, tissue partitioning and active-metabolite
##  contribution. They are NOT measured fu values, and the IC50 matrix is
##  calibrated jointly with them: only the RATIO (effective concentration /
##  effective IC50) is identifiable from clinical response data, so neither
##  number should be quoted on its own.
##  The AAG term is the one binding effect modeled explicitly, because it is
##  clinically consequential and directionally counter-intuitive: a large tumor
##  burden raises alpha-1-acid glycoprotein, lowering FREE imatinib at unchanged
##  TOTAL plasma concentration (Widmer 2006 Br J Clin Pharmacol 62:97,
##  PMID 16842382). It also produces an emergent positive feedback the model was
##  not built to contain: as the tumor responds, AAG falls, free drug rises, and
##  suppression deepens — which partly offsets the clearance drift above.
##
##  --- IC50 matrix -----------------------------------------------------------
##  Set so that at label doses the effective pathway inhibition is: imatinib on
##  KIT exon 11 ~0.75 (deep, cytocidal); imatinib on exon 9 markedly less at
##  400 mg and substantially recovered at 800 mg (GF_EX9 = 5); sunitinib strong
##  on exon 13/14 and near-inert on exon 17/18; regorafenib the reverse;
##  ripretinib intermediate-to-good on BOTH families, which is the switch-control
##  design claim (Smith 2019 Cancer Cell 35:738, PMID 31085175); avapritinib
##  dominant on PDGFRA D842V but penalized on V654A, consistent with VOYAGER
##  failing to generalize beyond D842V (Kang 2021 JCO 39:3128, PMID 34343033).
##  The asymmetry itself is from Heinrich 2008 (JCO 26:5352, PMID 18955451) and
##  Serrano 2019 (Br J Cancer 120:612, PMID 30792533).
##
##  --- Growth and resistance timing ------------------------------------------
##  KG 0.011/d (untreated volume doubling ~63 d), pre-existing resistant subclone
##  fractions ~3e-4, and mutant-supply coefficients ~8e-4 per unit sensitive-clone
##  proliferative flux. [VERIFIED] first-line imatinib 400 mg in KIT exon 11
##  gives a best RECIST response of -56% with radiologic progression at 23.9
##  months, against the ~20-24 month median time to progression of B2222
##  (PMID 12181401) and EORTC 62005 (PMID 15451219).
##  MU_* are LUMPED phenomenological coefficients, not per-division point-mutation
##  probabilities: they absorb the mutation rate, the number of codons that can
##  confer resistance, and the probability that any given new mutant clone
##  actually establishes. Because mutant supply scales with the DIVISION FLUX of
##  the sensitive clone, deeper suppression delays resistance mechanistically
##  rather than by fiat. That is the model's main testable claim, and it is what
##  makes dose and trough matter for PFS rather than only for response depth.
##
##  --- What the model reproduces [VERIFIED] ----------------------------------
##  * Imaging ordering. FDG-PET SUV -63% by day 7; Choi density partial response
##    (-15% HU) at day 25; RECIST partial response (-30% diameter) at day 101 —
##    a 76-day lead of density over size. This is precisely the discordance that
##    motivated the Choi criteria (PMID 17470865) and it emerges from three
##    different time constants, not from three fitted curves.
##  * Molecular before radiologic. Resistant-clone ctDNA crosses the 0.1% VAF
##    limit of detection at day 531 while radiologic progression is at day 727 —
##    a ~6.5 month lead time (cf. PMID 30097488).
##  * Exon 9 dose effect. 400 mg gives a -22.9% best response, 800 mg -54.4%,
##    with time-to-return-to-baseline 28.7 vs 31.1 months (MetaGIST, PMID
##    20124181). The response-depth effect is large; the progression-delay
##    component is present but smaller than the published PFS separation.
##  * Exposure-response. At a 2.2-fold clearance multiplier (day-180 trough
##    373 ng/mL) time-to-baseline is 31.3 months vs 33.8 months at normal
##    clearance; escalating that patient to 600 and 800 mg recovers troughs of
##    560 and 746 ng/mL and 32.5 and 33.5 months, monotonically.
##  * Interruption. Stopping at day 365 from a -51% response: -38% at day 485,
##    -27% at day 545, above baseline by day 730, and never returning to the
##    continuous-therapy curve (BFR14, PMID 17369574). The rebound comes out of
##    the quiescent persister pool, which is also why pathologic complete
##    responses are rare despite dramatic radiologic ones.
##  * Adjuvant therapy. Recurrence to 10 mL at 1.8 y with observation vs 4.7 y
##    with 3 years of adjuvant imatinib — the "delay, not cure" shape of
##    SSGXVIII (PMID 22453568), with the hazard re-emerging after stopping.
##  * Genotype-directed therapy. PDGFRA D842V progresses at 2.9 months on
##    imatinib and responds -86.7% on avapritinib (NAVIGATOR, PMID 32615108).
##    SDH-deficient disease is inert to imatinib (PD at 2.9 months) but is
##    slowed by sunitinib (PD at 6.8 months) purely through the anti-angiogenic
##    arm, since res_D is unchanged — the mechanism, not just the outcome.
##  * BIM polymorphism. Same exposure and same pathway inhibition, best response
##    -47.4% vs -56.0% for BIM wild-type (PMID 22426421): cytostasis without
##    cytocidal effect.
##  * INTRIGUE ctDNA subgroups. In an exon-13/14-only background sunitinib is
##    ahead of ripretinib; in an exon-17/18-only background ripretinib is ahead
##    by a far larger margin. The DIRECTION of both subgroups matches the
##    published ctDNA analysis (PMID 38182785), and it is emergent from the
##    IC50 matrix rather than asserted.
##
##  --- What the model does NOT reproduce -------------------------------------
##  The INTRIGUE PRIMARY endpoint. In a mixed second-line population the model
##  puts ripretinib clearly ahead of sunitinib, whereas the trial was negative
##  (Bauer 2022 JCO 40:3918, PMID 35947817). The reason is structural and worth
##  stating plainly: with sunitinib near-inert against activation-loop mutants,
##  ANY population containing an appreciable exon-17/18 clone favours ripretinib,
##  because sunitinib's failure mode there is catastrophic while ripretinib's
##  disadvantage on exon 13/14 is merely moderate. For the arms to tie, one of
##  the following must be true and is not encoded here: ATP-pocket-only
##  resistance is considerably more prevalent than the ~1:1 split assumed;
##  sunitinib's anti-angiogenic contribution is larger than WVASC = 0.45 allows;
##  or ripretinib's real-world exposure at 150 mg/d is lower relative to its
##  IC50s than FT_RIP implies. Each is a falsifiable, quantitative hypothesis,
##  and separating them is a better use of this model than tuning until the
##  curves overlap.
##
##  --- Known artifact --------------------------------------------------------
##  Nadir-referenced RECIST progression behaves counter-intuitively when arms
##  differ in RESPONSE DEPTH: a shallower responder has a higher nadir, so the
##  ">=20% above nadir" rule fires LATER even though that patient is doing worse.
##  This is a property of the criterion, not of the biology, and it shows up in
##  the exon-9 400 mg and BIM-deletion arms. When comparing arms with different
##  response depths, prefer time-to-return-to-baseline-burden (see ttb() below)
##  or read response depth and progression as two separate endpoints.
##
##  --- Toxicity --------------------------------------------------------------
##  Edema Emax 2.6 at imatinib exposures (its most common adverse event);
##  sunitinib TSH rise reproducing the ~30-40% incidence of hypothyroidism on
##  50 mg 4/2 (Desai 2006 Ann Intern Med 145:660, PMID 17088579); VEGFR-driven
##  systolic rise up to ~24 mmHg; HFSR weighted to regorafenib, its
##  dose-limiting toxicity in GRID (PMID 23177515). [VERIFIED] steady state:
##  imatinib day 365 edema 1.44, ANC 3.03; sunitinib day 180 TSH 4.08,
##  SBP 141 mmHg; regorafenib day 180 HFSR 1.09, SBP 142 mmHg.
##
##  --- Reproducing these checks ----------------------------------------------
##  ttb <- function(df) {                     # time to return to baseline burden
##    i <- which(df$time > 10 & df$Tumor_burden_mL >= df$Tumor_burden_mL[1])
##    if (length(i)) df$time[i[1]] else NA_real_
##  }
##  pd  <- function(df) {                     # RECIST 1.1 PD: +20% over nadir
##    d <- 100 + df$RECIST_pct_change; i <- which(d/cummin(d) >= 1.20)
##    if (length(i)) df$time[i[1]] else NA_real_
##  }
##
##  ============================================================================
