##  Bronchopulmonary Dysplasia (BPD) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Bronchopulmonary dysplasia — the chronic lung disease of
##             prematurity, defined (Jensen/NICHD 2019) by the MODE of
##             respiratory support still required at 36 weeks postmenstrual age
##             (PMA): grade 1 = nasal cannula <=2 L/min, grade 2 = >2 L/min or
##             non-invasive positive pressure, grade 3 = invasive mechanical
##             ventilation.
##
##  THE ORGANISING IDEA OF THIS MODEL
##  ---------------------------------
##  Almost every BPD model in the literature is written as a damage model:
##  oxygen and pressure injure the lung, injury accumulates, the lung ends up
##  scarred. That framing is wrong in a way that matters for drug development,
##  because it predicts that a more potent anti-injury drug given at any time
##  should help — and forty years of trials say otherwise.
##
##  This model poses BPD instead as a SCHEDULING problem.
##
##  Alveolarisation is a developmental PROGRAMME that runs on the PMA clock,
##  not on the postnatal clock. Let S_dev(PMA) be the septation drive. Its
##  integral over a lifetime is FINITE and it peaks at ~32 weeks PMA — i.e.
##  precisely while a 24-week infant is lying on a ventilator. Injury does not
##  primarily destroy alveoli; it closes a multiplicative GROWTH GATE
##
##      G(t) = [VEGF^wv * cGMP^wn * IGF1^wi * RA^wr * EPC^we] / (1 + a*TGFb)
##
##  and the surface actually built is
##
##      ALV(36 wk) = integral of  k * S_dev(PMA(t)) * G(t) * (1 - ALV/ALVmax) dt
##
##  Three consequences fall straight out of that structure, and they are the
##  reason this file exists:
##
##   (1) TIMING BEATS POTENCY. Because S_dev is decaying while the infant is
##       in the NICU, a therapy that opens G by 40% on day 1 buys more surface
##       than one that opens it by 100% on day 21. There is a computable
##       crossover day. This is PREMILOC vs DART, expressed as arithmetic
##       rather than as a difference of opinion about steroids.
##
##   (2) THERAPIES SPLIT INTO THREE CLASSES BY WHICH TERM THEY TOUCH, and the
##       class — not the potency — sets the ceiling:
##         (a) EXPOSURE reducers shrink the injury input   (caffeine via
##             ventilator days, LISA/nCPAP, volume-targeted ventilation,
##             permissive hypercapnia, PDA closure, SpO2 band);
##         (b) TRANSDUCTION suppressors shrink injury -> G  (hydrocortisone,
##             dexamethasone, intratracheal budesonide, azithromycin in
##             Ureaplasma-positive infants, IL-1Ra);
##         (c) PROGRAMME supporters raise G directly       (vitamin A/retinoate,
##             rhIGF-1/BP3, MSC, the small direct A2A arm of caffeine).
##       Anything that touches NONE of the three can move a number for hours
##       and change nothing at 36 weeks. Furosemide is the model's designated
##       example and it is included on purpose.
##
##   (3) THE LOST WINDOW IS THE READOUT, NOT THE SUPPORT LEVEL. The model
##       carries an explicit counter LOSTW = integral of k*S_dev*(1-G)*
##       (1-ALV/ALVmax) dt — the surface that was never built. Two infants can
##       share a 36-week FiO2 and carry completely different LOSTW, and it is
##       LOSTW, not FiO2, that predicts the adult FEV1 plateau.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.0)
##  Time     : DAYS of postnatal life. t = 0 is birth. PMA(t) = GA + t/7 weeks.
##
##  Scope    : 37 ODE compartments —
##             (a) 11 PK/exposure states with REAL neonatal pharmacokinetics
##                 in mg and mg/L (not arbitrary units): caffeine depot +
##                 central (PMA-maturing clearance, t1/2 90 h -> 6 h),
##                 dexamethasone, hydrocortisone, intratracheal budesonide
##                 (lung + systemic), hepatic retinol store + plasma retinol,
##                 azithromycin, sildenafil, and a cumulative dexamethasone-
##                 equivalent dose ledger;
##             (b) 5 inflammation states: NF-kB activity, IL-1beta, airway
##                 neutrophil/elastase burden, TGF-beta1, ROS;
##             (c) 5 growth-gate states: VEGF, NO bioavailability, IGF-1,
##                 retinoate signalling, endothelial progenitor pool;
##             (d) 5 structural states: alveolar surface, microvascular
##                 density, septal thickening, airway smooth muscle, lung water;
##             (e) 3 support/exposure states: support intensity, fraction of
##                 day on invasive MV, Ureaplasma burden;
##             (f) 2 pulmonary-vascular states: vascular remodelling, RV
##                 hypertrophy;
##             (g) 6 accumulators that ARE the clinically reported endpoints:
##                 body weight, LOSTW (lost developmental window), NDI cost,
##                 ventilator days, supplemental-oxygen days, mortality hazard.
##
##  Units    : PK in mg (amounts) and mg/L (concentrations) — caffeine doses
##             are entered as CAFFEINE CITRATE mg/kg and halved internally to
##             caffeine base. Steroid exposure is expressed throughout as
##             DEXAMETHASONE-EQUIVALENT mg/L so that hydrocortisone,
##             dexamethasone and budesonide share one receptor-occupancy
##             equation. Structural states are normalised so that 1.0 = the
##             value of a HEALTHY infant at 36 weeks PMA; ALV can exceed 1.0
##             after term because alveolarisation continues. Weight in kg.
##
##  Scenarios: 15 prebuilt — see BPD_simulate_scenarios() at the bottom.
##
##  ==========================  IMPORTANT CAVEAT  ==============================
##  This is a MECHANISTIC TEACHING/RESEARCH model, calibrated to reproduce the
##  DIRECTION and rough MAGNITUDE of the landmark trials named in
##  bpd_references.md (CAP, PREMILOC, DART, Tyson vitamin A, Yeh budesonide,
##  NeOProM/SUPPORT, SAIL, the LISA meta-analyses). It has NOT been fitted to
##  individual patient data and MUST NOT be used for clinical decisions,
##  dosing, or regulatory submission. Where the model and the literature
##  disagree, bpd_references.md and the directory README say so explicitly
##  rather than hiding it.
##  ============================================================================

library(mrgsolve)
suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
})

bpd_code <- '
$PROB
# BPD QSP model — alveolarisation as a scheduling problem
# ALV(36wk) = int k*S_dev(PMA)*G(t)*(1-ALV/ALVmax) dt ; LOSTW = the shortfall

$GLOBAL
// Closed-form integral of the septation-drive window S_dev from PMA 20 to p.
// S_dev is a two-sided Gaussian in PMA with different widths either side of
// the peak, so its integral is a difference of error functions — no numerical
// quadrature is needed anywhere in the model, and the "uninjured ideal"
// trajectory is therefore exact rather than approximate.
#define BPD_SQRT2      1.41421356237309505
#define BPD_SQRT_PI_2  1.25331413731550025

double bpd_gauss_int(double a, double b, double m, double w) {
  return w * BPD_SQRT_PI_2 * (erf((b - m) / (w * BPD_SQRT2))
                            - erf((a - m) / (w * BPD_SQRT2)));
}

double bpd_phi(double pma, double pk, double wl, double wr) {
  if (pma <= 20.0) return 0.0;
  if (pma <= pk)   return bpd_gauss_int(20.0, pma, pk, wl);
  return bpd_gauss_int(20.0, pk, pk, wl) + bpd_gauss_int(pk, pma, pk, wr);
}

$PARAM @annotated
// ---------------------------------------------------------------- PATIENT ---
GA      :  25.0  : Gestational age at birth (weeks)
BW      :   0.70 : Birth weight (kg); set 0 to use the GA-based default
IUGR    :   0    : IUGR / SGA flag (0/1) — lowers IGF-1 and raises sFlt-1
CHORIO  :   0    : Histologic chorioamnionitis / fetal inflammatory response (0/1)
ANTESTER:   1    : Complete antenatal corticosteroid course (0/1)
MALE    :   1    : Male sex (0/1)
GENRISK :   0    : Genetic risk index (0-1) — NF-kB set-point shift
UREA0   :   0    : Ureaplasma airway colonisation at birth (0/1)

// ------------------------------------------------- DEVELOPMENTAL PROGRAMME ---
PMAPK   :  32.0  : PMA at peak septation drive (weeks)
SDW_L   :   6.0  : Rising-limb width of S_dev (weeks)
SDW_R   :  14.0  : Falling-limb width of S_dev (weeks)
ALVMAX  :   4.0  : Asymptotic alveolar surface (1.0 = healthy 36-wk PMA lung)
CAPMAX  :   4.0  : Asymptotic microvascular density
A20     :   0.02 : Alveolar surface at PMA 20 wk (canalicular, near zero)
KALV    :   0.2826: Programme rate constant per unit of integrated S_dev
                   (chosen so an UNINJURED fetus reaches ALV=1.0 at 36 wk PMA;
                   the normalising integral is computed in closed form by
                   bpd_phi(), so this is exact and needs no fitted PHI36)
KDEGALV :   0.0015: Elastolytic surface loss per unit elastase burden per day
KCAPREL :   1.00 : Microvascular programme rate relative to the alveolar one

// ----------------------------------------------- RESPIRATORY SUPPORT MODE ---
LISA    :   0    : LISA/MIST surfactant without intubation (0/1)
VTV     :   0    : Volume-targeted ventilation (0/1)
PHC     :   0    : Permissive hypercapnia strategy (0/1)
SPO2HI  :   1    : SpO2 target band: 1 = 91-95%, 0 = 85-89%
SURF    :   1    : Exogenous surfactant given (0/1)
NUTR    :   0    : Aggressive early protein/energy strategy (0/1)
TRACH_T : 999    : Day of tracheostomy (999 = never)

// --------------------------------------------------- INJURY COEFFICIENTS ---
KVILI   :   0.583: Volutrauma/atelectrauma gain on invasive MV
KNIV    :   0.15 : Relative injury gain of non-invasive support
NVILI   :   1.60 : Power on support intensity in the VILI term
EFF_VTV :   0.35 : Fractional VILI reduction by volume-targeted ventilation
EFF_PHC :   0.15 : Fractional VILI reduction by permissive hypercapnia
KOX     :   1.10 : Hyperoxic injury gain
NOX     :   1.20 : Power on the normalised excess-FiO2 term
KHYPOX  :   0.90 : Hypoxaemia burden gain (HPV / ET-1 arm)
KURE    :   0.55 : Injury gain per unit Ureaplasma burden
KSEP    :   1.20 : Injury gain per unit sepsis intensity
KPDAI   :   0.45 : Injury gain per unit PDA overcirculation
KANTE   :   2.24 : Peak antenatal inflammatory injury (chorioamnionitis)
TAU_ANTE:   7.0  : Decay time constant of the antenatal hit (days)
KROSI   :   0.35 : Contribution of ROS state back into the injury drive

// ---------------------------------------------------- SUPPORT REGULATION ---
KFIO2   :   0.10 : Steepness of the diffusion/reserve arm of the FiO2 map
DTHR    :   1.60 : Demand index tolerated on room air (the RESERVE zone)
KSH     :   0.564: Gain of the shunt arm of the FiO2 map (no reserve)
LW_BASE :   0.08 : Healthy baseline lung water (subtracted from the shunt term)
SEPT_BASE:  0.05 : Healthy baseline septal thickness (saturated units)
FIO2_THR:   0.23 : FiO2 above which the infant counts as needing oxygen
KSUP    :   0.966: Steepness of the support-intensity requirement
BANDF   :   0.86 : FiO2 multiplier when the low SpO2 band is used
BANDHX  :   0.35 : Hypoxaemia burden attributable to the low SpO2 band
THRMV   :   0.62 : Invasive-MV drive threshold
SMV     :   0.12 : Steepness of the MV decision sigmoid
TAU_MV  :   2.50 : Clinician response lag for mode change (days)
TAU_SUP :   0.60 : Clinician response lag for support intensity (days)
THRNIV  :   0.35 : Support intensity above which non-invasive PPV is needed
AP0     :   0.85 : Apnoea burden at birth (drives intubation independently)
TAU_AP  :  14.1  : Spontaneous maturation time constant of apnoea (days)
WAP     :   0.876: Weight of apnoea in the invasive-MV drive
PALV    :   1.00 : Power on ALV in the oxygenation-capacity term
PCAP    :   0.50 : Power on CAP in the oxygenation-capacity term
KSEPTO  :   0.60 : Septal-thickening penalty on oxygenation capacity
KLWO    :   1.28 : Lung-water penalty on oxygenation capacity
KASMO   :   0.35 : Airway-smooth-muscle penalty on oxygenation capacity

// ------------------------------------------------------ INFLAMMATION PKPD ---
KINJ50  :   0.90 : Injury drive at half-maximal NF-kB activation
NFMAX   :   1.00 : Maximal NF-kB activity (the cascade SATURATES)
KOUT_NF :   1.20 : NF-kB relaxation rate towards its target (/day)
NF0     :   0.10 : Basal NF-kB activity
KIN_IL1 :   1.00 : IL-1beta production from NF-kB
FNLRP3  :   0.45 : ROS amplification of IL-1beta via NLRP3
KOUT_IL1:   1.50 : IL-1beta relaxation rate (/day)
KIN_NE  :   0.70 : Neutrophil/elastase influx gain
KOUT_NE :   0.80 : Neutrophil/elastase resolution (/day)
KIN_TG  :   0.85 : TGF-beta1 activation gain
WTG_MECH:   0.60 : Fraction of TGF-beta activation that is MECHANICAL
KOUT_TG :   0.45 : TGF-beta1 decay (/day)
KIN_RO  :   1.00 : ROS production gain
KOUT_RO :   2.00 : ROS clearance (/day)
AOX0    :   1.60 : Mature antioxidant capacity (Nrf2/SOD/GSH)
AOXPMA  :  31.0  : PMA at half-maximal antioxidant maturation (weeks)
AOXSL   :   2.50 : Steepness of antioxidant maturation (weeks)

// ------------------------------------------------------- GROWTH GATE PKPD ---
TAU_V   :   1.50 : VEGF turnover time constant (days)
AV_IL1  :   0.657: IL-1beta suppression of VEGF
AV_ROS  :   0.50 : ROS suppression of VEGF
AV_SFLT :   0.60 : sFlt-1 trapping of VEGF
TAU_NO  :   0.50 : NO bioavailability turnover (days)
AN_ROS  :   0.70 : ROS/peroxynitrite uncoupling of eNOS
AN_ADMA :   0.45 : ADMA-mediated eNOS uncoupling
TAU_I   :   2.50 : IGF-1 turnover (days)
AI_INFL :   0.55 : Inflammatory suppression of IGF-1
AI_DEX  :   0.70 : Glucocorticoid suppression of IGF-1
IGFB0   :   0.55 : IGF-1 axis activity at PMA 24 wk (fraction of term)
IGFBSL  :   0.055: IGF-1 maturation slope per week of PMA
TAU_R   :   2.00 : Retinoate signalling turnover (days)
KM_RA   :   0.45 : Plasma retinol (micromol/L) at half-maximal RAR signalling
TAU_E   :   3.00 : EPC/ECFC pool turnover (days)
AE_ROS  :   0.70 : ROS depletion of the progenitor pool
WV      :   0.30 : Gate weight — VEGF
WN      :   0.20 : Gate weight — cGMP/NO
WI      :   0.25 : Gate weight — IGF-1
WR      :   0.15 : Gate weight — retinoate
WE      :   0.10 : Gate weight — progenitor pool
AG_TGF  :   1.15 : TGF-beta1 arrest of secondary crest formation
AG_IL1  :   0.25 : Direct IL-1beta block of septation (beyond its VEGF effect)
AG_GR   :   0.45 : Emax of the GLUCOCORTICOID ANTIPROLIFERATIVE effect on G

// ------------------------------------------- STRUCTURE / AIRWAY / WATER ---
KSEPT   :   0.10 : Septal thickening gain from TGF-beta1 (/day)
KOUT_SEPT:  0.18 : Septal thickening resolution (/day)
KASM    :   0.30 : Airway smooth muscle gain (/day)
KOUT_ASM:   0.08 : Airway smooth muscle resolution (/day)
IL1B_BAS:   0.10 : Basal IL-1beta; ASM is driven by IL-1beta ABOVE this, so
                   a healthy lung sits at ASM = 0 and adds no shunt
KLW     :   0.45 : Lung-water accumulation gain (/day)
KOUT_LW :   1.281: Lung-water clearance (/day)
FLUID   :   0.00 : Excess fluid intake index (0 = restricted, 1 = liberal)
LW0_SURF:   0.30 : Lung water at birth WITH exogenous surfactant
LW0_NOSURF: 0.55 : Lung water at birth WITHOUT exogenous surfactant

// ------------------------------------------------------ PULMONARY VASCULAR ---
PXS     :   1.20 : Power on cross-sectional area in the PVR relation
KHPV    :   0.80 : HPV contribution to PVR
KVR     :   0.60 : Remodelling contribution to PVR
KVRIN   :   0.18 : Vascular remodelling gain (/day)
KVROUT  :   0.06 : Vascular remodelling regression (/day)
KET1    :   0.35 : ET-1 contribution to remodelling and tone
KRV     :   0.04 : RV hypertrophy gain per unit excess PVR (/day)
KRVOUT  :   0.04 : RV hypertrophy regression (/day)
ERA     :   0    : Endothelin receptor antagonist on board (0/1)
ERA_EMAX:   0.45 : Fractional ET-1 blockade by an ERA
INO_PPM :   0.00 : Inhaled nitric oxide (ppm)
INO_EC50:   8.00 : iNO ppm at half-maximal cGMP effect
INO_EMAX:   0.80 : Maximal iNO effect on the cGMP term

// ---------------------------------------------------------- GROWTH / BODY ---
GRMAX   :   0.0155: Maximal fractional weight gain (/day) = 15.5 g/kg/d
WLOSS   :   0.020: Peak early fractional weight loss (/day)
TAU_WL  :   4.0  : Time constant of early weight loss (days)
AW_DEX  :   0.40 : Glucocorticoid suppression of weight gain
AW_INFL :   0.30 : Inflammatory suppression of weight gain
NUTR_EFF:   0.25 : Fractional rescue of the protein-energy deficit by NUTR

// ----------------------------------------------------- CAFFEINE PK / PD ---
CAF_LD  :  20.0  : Caffeine CITRATE loading dose (mg/kg)
CAF_MD  :   5.0  : Caffeine CITRATE maintenance dose (mg/kg/day)
CAF_T0  : 999    : Day caffeine is started (999 = never)
CAF_T1  :  60.0  : Day caffeine is stopped
CAF_KA  :   8.0  : Caffeine absorption rate constant (/day)
CAF_VD  :   0.85 : Caffeine volume of distribution (L/kg)
CAF_CLI :   4.60 : Caffeine clearance asymptote (L/day/kg)
CAF_PMA50: 60.0  : PMA at half-maximal caffeine clearance (weeks)
CAF_HILL:   4.0  : Hill coefficient of caffeine clearance maturation
CAF_EC50:   9.0  : Caffeine concentration for half-maximal apnoea effect (mg/L)
CAF_EMAX:   0.60 : Maximal fractional apnoea reduction by caffeine
CAF_EALV:   0.10 : Maximal DIRECT A2A effect of caffeine on the growth gate
CAF_ECA :  15.0  : Caffeine concentration for half-maximal direct A2A effect
CAF_DRIVE:  1    : Enable the central-drive (exposure) arm of caffeine (0/1)

// ------------------------------------------------ CORTICOSTEROID PK / PD ---
DEX_RATE:   0.00 : Dexamethasone dose rate (mg/kg/day) during the window
DEX_T0  : 999    : Day dexamethasone starts
DEX_T1  : 999    : Day dexamethasone stops
DEX_DART:   0    : Use the DART tapering schedule instead of DEX_RATE (0/1)
DEX_VD  :   1.00 : Dexamethasone volume of distribution (L/kg)
DEX_CL  :   3.60 : Dexamethasone clearance (L/day/kg) — t1/2 ~4.6 h
HC_RATE :   0.00 : Hydrocortisone dose rate (mg/kg/day) during the window
HC_T0   : 999    : Day hydrocortisone starts
HC_T1   : 999    : Day hydrocortisone stops
HC_PREM :   0    : Use the PREMILOC schedule instead of HC_RATE (0/1)
HC_VD   :   0.50 : Hydrocortisone volume of distribution (L/kg)
HC_CL   :   3.40 : Hydrocortisone clearance (L/day/kg) — t1/2 ~2.4 h
HC_POT  :   0.040: Hydrocortisone potency relative to dexamethasone (1/25)
BUD_DOSE:   0.00 : Intratracheal budesonide per dose (mg/kg)
BUD_T0  : 999    : Day intratracheal budesonide starts
BUD_N   :   4    : Number of budesonide doses (q8h)
BUD_KLS :   1.80 : Budesonide lung-to-systemic transfer (/day)
BUD_CL  :  30.0  : Budesonide systemic clearance (L/day/kg) — high first-pass
BUD_VD  :   3.00 : Budesonide systemic volume of distribution (L/kg)
BUD_POT :   2.00 : Budesonide GR potency relative to dexamethasone
BUD_VL  :   0.03 : Effective lung distribution volume (L/kg)
GR_EC50 :   0.004: Dexamethasone-equivalent conc. for half-maximal GR occupancy (mg/L)
GR_EMAXR:   0.85 : Emax of GR transrepression of NF-kB
GR_ECOMP:   0.55 : Emax of the GR effect on lung compliance / extubation

// -------------------------------------------------------- VITAMIN A PK/PD ---
VITA_IU : 5000   : Vitamin A dose (IU retinyl palmitate, IM)
VITA_T0 : 999    : Day vitamin A starts
VITA_N  :  12    : Number of doses (3 per week)
VITA_IVL:   2.333: Interval between vitamin A doses (days)
RET_KR  :   0.18 : Hepatic store to plasma release (/day)
RET_CL  :   1.20 : Plasma retinol clearance (L/day/kg)
RET_VD  :   0.60 : Plasma retinol volume of distribution (L/kg)
RET_S0  :   3.00 : Hepatic retinol store at birth (micromol) — preterm deficient
RET_DIET:   1.50 : Baseline enteral/parenteral retinol input (micromol/day)
                   (~1400 IU/day; gives plasma retinol ~0.5 micromol/L, i.e.
                   the deficient range typical of the preterm infant)

// ---------------------------------------------- AZITHROMYCIN / UREAPLASMA ---
AZI_RATE:   0.00 : Azithromycin dose (mg/kg/day)
AZI_T0  : 999    : Day azithromycin starts
AZI_T1  : 999    : Day azithromycin stops
AZI_CL  :   6.40 : Azithromycin clearance (L/day/kg)
AZI_VD  :  24.0  : Azithromycin volume of distribution (L/kg)
AZI_EC50:   0.05 : Azithromycin conc. for half-maximal Ureaplasma kill (mg/L)
AZI_KILL:   1.80 : Maximal Ureaplasma kill rate (/day)
AZI_AI  :   0.20 : Fractional non-antimicrobial anti-inflammatory effect
URE_GROW:   0.25 : Ureaplasma net growth rate (/day)
URE_MAX :   1.00 : Ureaplasma carrying capacity

// --------------------------------------------------------- SILDENAFIL PK ---
SIL_RATE:   0.00 : Sildenafil dose (mg/kg/day, divided q8h)
SIL_T0  : 999    : Day sildenafil starts
SIL_T1  : 999    : Day sildenafil stops
SIL_F   :   0.35 : Sildenafil oral bioavailability
SIL_CL  :   2.00 : Sildenafil clearance (L/day/kg) — immature CYP3A4
SIL_VD  :   1.20 : Sildenafil volume of distribution (L/kg)
SIL_EC50:   0.06 : Sildenafil conc. for half-maximal PDE5 inhibition (mg/L)
SIL_EMAX:   0.75 : Maximal fractional PDE5 inhibition

// ---------------------------------------------------------- OTHER THERAPY ---
FURO    :   0    : Loop diuretic on board (0/1)
FURO_T0 : 999    : Day the diuretic starts
FURO_EMAX: 0.55  : Fractional increase in lung-water clearance
MSC     :   0    : Intratracheal MSC therapy (0/1)
MSC_T0  : 999    : Day of MSC administration
MSC_EMAX:   0.30 : Fractional VEGF rescue by MSC
MSC_TAU :  14.0  : Duration of the MSC paracrine effect (days)
RHIGF   :   0    : rhIGF-1/rhIGFBP-3 infusion (0/1)
RHIGF_T1:  28.0  : Day rhIGF-1 stops
RHIGF_E :   0.35 : Fractional IGF-1 axis rescue
IL1RA   :   0    : IL-1 receptor antagonist / idealised gate-opener (0/1)
IL1RA_E :   0.60 : Fractional IL-1beta neutralisation
IL1RA_T0:   0.0  : Day the IL-1Ra / gate-opener starts
IL1RA_T1: 999    : Day the IL-1Ra / gate-opener stops
BRONCHO :   0    : Bronchodilator on board (0/1)
BRONCHO_E: 0.30  : Fractional airway-smooth-muscle effect (symptomatic only)

// ------------------------------------------------------- DISCRETE EVENTS ---
PDA_T0  :   1.0  : Day a haemodynamically significant PDA opens
PDA_T1  :   0.0  : Day the PDA closes (0 = never opened / already closed)
PDA_MAG :   0.60 : Magnitude of pulmonary overcirculation while the PDA is open
SEP_T0  : 999    : Day of a late-onset sepsis episode
SEP_DUR :   5.0  : Duration of the sepsis episode (days)
SEP_MAG :   0.80 : Intensity of the sepsis episode

// ------------------------------------------------- MORTALITY / NDI WEIGHTS ---
H0      :   0.0004: Baseline daily mortality hazard
H_HYPOX :   0.0035: Hazard per unit hypoxaemia burden per day
H_PVR   :   0.0015: Hazard per unit PVR above 1.5 per day
H_SEP   :   0.0090: Hazard per unit sepsis intensity per day
H_G3    :   0.0008: Hazard per day of invasive ventilation
W_DEX   :   0.55 : NDI cost per mg/kg of dexamethasone-equivalent
W_EARLY :   1.00 : Extra NDI weight for exposure in the first postnatal week
W_HYPOX :   0.012: NDI cost per unit-day of hypoxaemia burden
W_HYPOCAP: 0.004 : NDI cost per unit-day of hypocapnia
HYPOCAP :   0    : Hypocapnia exposure flag (0/1) — pressure-limited, no VTV
W_NDI   :   0.45 : Weight of NDI in the net-utility calculation

$CMT @annotated
// -- PK ---------------------------------------------------------------------
CAFG    : Caffeine in the absorption depot (mg)
CAFC    : Caffeine in the central compartment (mg)
DEXC    : Dexamethasone in the central compartment (mg)
HCC     : Hydrocortisone in the central compartment (mg)
BUDL    : Budesonide in the lung compartment (mg)
BUDC    : Budesonide in the systemic compartment (mg)
RETS    : Hepatic retinol store (micromol)
RETP    : Plasma retinol (micromol)
AZIC    : Azithromycin in the central compartment (mg)
SILC    : Sildenafil in the central compartment (mg)
DEXEQ   : Cumulative dexamethasone-equivalent dose ledger (mg/kg)
// -- inflammation -----------------------------------------------------------
NFKB    : NF-kB transcriptional activity (au, 0.1 = basal)
IL1B    : IL-1beta activity (au)
NEUT    : Airway neutrophil / elastase burden (au)
TGFB    : Active TGF-beta1 (au)
ROS     : Oxidant burden (au)
// -- growth gate ------------------------------------------------------------
VEGF    : VEGF-A signalling (1.0 = healthy)
NOB     : NO bioavailability (1.0 = healthy)
IGF1    : IGF-1 axis activity (1.0 = term-equivalent)
RASIG   : Retinoate/RAR signalling (1.0 = replete)
EPC     : Endothelial progenitor pool (1.0 = healthy)
// -- structure --------------------------------------------------------------
ALV     : Alveolar gas-exchange surface (1.0 = healthy 36-wk PMA lung)
CAPD    : Pulmonary microvascular density (1.0 = healthy 36-wk PMA lung)
SEPT    : Septal thickening / interstitial fibrosis (0 = none)
ASM     : Airway smooth muscle mass (0 = none)
LW      : Extravascular lung water (0 = none)
// -- support ----------------------------------------------------------------
SUP     : Respiratory support intensity index (0-1)
MVF     : Fraction of the day on invasive mechanical ventilation (0-1)
UREA    : Ureaplasma airway burden (0-1)
// -- pulmonary vascular -----------------------------------------------------
VREM    : Pulmonary vascular remodelling (0 = none)
RVHY    : RV hypertrophy index (0 = none)
// -- accumulators / endpoints ----------------------------------------------
WT      : Body weight (kg)
LOSTW   : Lost developmental window (alveolar surface never built)
NDIC    : Neurodevelopmental cost accumulator (au)
VDAYS   : Cumulative days of invasive ventilation
O2DAYS  : Cumulative days of supplemental oxygen
HAZ     : Cumulative mortality hazard

$MAIN
// ---- initial conditions --------------------------------------------------
// The alveolar surface an infant is BORN with follows the uninjured
// trajectory of the same programme equation, evaluated at PMA = GA:
//     ALV(p) = ALVMAX - (ALVMAX - A20) * exp(-r * PHI(p)),
//     r = KALV / PHI(36),  PHI computed in closed form by bpd_phi()
// so no separate birth-surface table is needed and the gestational gradient
// of BPD emerges from the geometry rather than from a fitted coefficient.
double phi_ga  = bpd_phi(GA,   PMAPK, SDW_L, SDW_R);
double phi_36  = bpd_phi(36.0, PMAPK, SDW_L, SDW_R);
double r_prog  = KALV / phi_36;
double ALV_birth = ALVMAX - (ALVMAX - A20) * exp(-r_prog * phi_ga);

double bw = (BW > 0.01) ? BW : (0.0 + exp(0.2718 * GA - 6.35));  // GA-based default
if (IUGR > 0.5) bw = bw * 0.72;

ALV_0   = ALV_birth;
CAPD_0  = ALV_birth;                 // capillary bed tracks surface at birth
SEPT_0  = 0.0;
ASM_0   = 0.0;
// Antenatal steroids reduce surfactant deficiency and therefore the initial
// atelectasis/oedema load. Written as a PENALTY for an incomplete course so
// that ANTESTER = 1 (the reference) leaves the baseline untouched.
LW_0    = ((SURF > 0.5) ? LW0_SURF : LW0_NOSURF) * (1.0 + 0.25 * (1.0 - ANTESTER));
NFKB_0  = NF0 * (1.0 + 2.5 * CHORIO) * (1.0 + 0.8 * GENRISK);
IL1B_0  = NFKB_0 * KIN_IL1 / KOUT_IL1;
NEUT_0  = (KIN_NE * (IL1B_0 + 0.5 * NFKB_0)) / KOUT_NE;
TGFB_0  = 0.05 + 0.25 * CHORIO;
ROS_0   = 0.10;
VEGF_0  = 1.0 / (1.0 + AV_IL1 * IL1B_0 + AV_SFLT * 0.35 * IUGR);
NOB_0   = 1.0 / (1.0 + AN_ROS * ROS_0);
IGF1_0  = (IGFB0 + IGFBSL * (GA - 24.0)) * (IUGR > 0.5 ? 0.65 : 1.0);
RASIG_0 = (RET_S0 * 0.12) / (KM_RA + RET_S0 * 0.12);
EPC_0   = 1.0 / (1.0 + AE_ROS * ROS_0);
SUP_0   = (LISA > 0.5) ? 0.25 : 0.55;
MVF_0   = (LISA > 0.5) ? 0.05 : 0.90;
UREA_0  = (UREA0 > 0.5) ? 0.35 : 0.0;
VREM_0  = 0.0;
RVHY_0  = 0.0;
WT_0    = bw;
RETS_0  = RET_S0;
RETP_0  = 0.35 * RET_VD * bw;        // plasma retinol ~0.35 micromol/L, deficient
LOSTW_0 = 0.0; NDIC_0 = 0.0; VDAYS_0 = 0.0; O2DAYS_0 = 0.0; HAZ_0 = 0.0;
DEXEQ_0 = 0.0;

$ODE
// ==========================================================================
// 0. CLOCKS
// ==========================================================================
double PMA = GA + SOLVERTIME / 7.0;
double wS  = (PMA < PMAPK) ? SDW_L : SDW_R;
double zS  = (PMA - PMAPK) / wS;
double SDEV = exp(-0.5 * zS * zS);                    // septation drive
double r_prog2 = KALV / bpd_phi(36.0, PMAPK, SDW_L, SDW_R);
double phi_now_ode = bpd_phi(PMA, PMAPK, SDW_L, SDW_R);
double wt = (WT > 0.35) ? WT : 0.35;

// ==========================================================================
// 1. DOSING WINDOWS -> INFUSION-LIKE INPUT RATES (mg/day, not bolus events)
//    Continuous rates are used deliberately: the interesting timescale here
//    is DAYS of gate suppression, not the q8h ripple.
// ==========================================================================
// --- caffeine: citrate mg/kg -> BASE mg (factor 0.5) ----------------------
double caf_on   = ((SOLVERTIME >= CAF_T0) && (SOLVERTIME <= CAF_T1)) ? 1.0 : 0.0;
double caf_load = ((SOLVERTIME >= CAF_T0) && (SOLVERTIME < CAF_T0 + 0.25))
                    ? (0.5 * CAF_LD * wt / 0.25) : 0.0;
double caf_in   = caf_on * (0.5 * CAF_MD * wt) + caf_load;

// --- dexamethasone: flat rate, or the DART taper -------------------------
double dex_rate = 0.0;
if (DEX_DART > 0.5) {
  double d = SOLVERTIME - DEX_T0;
  if      (d >= 0.0 && d < 3.0)  dex_rate = 0.15;
  else if (d >= 3.0 && d < 6.0)  dex_rate = 0.10;
  else if (d >= 6.0 && d < 8.0)  dex_rate = 0.05;
  else if (d >= 8.0 && d < 10.0) dex_rate = 0.02;
} else if (SOLVERTIME >= DEX_T0 && SOLVERTIME <= DEX_T1) {
  dex_rate = DEX_RATE;
}
double dex_in = dex_rate * wt;

// --- hydrocortisone: flat rate, or the PREMILOC schedule ----------------
double hc_rate = 0.0;
if (HC_PREM > 0.5) {
  double d = SOLVERTIME - HC_T0;
  if      (d >= 0.0 && d < 7.0)  hc_rate = 1.0;    // 0.5 mg/kg BID
  else if (d >= 7.0 && d < 10.0) hc_rate = 0.5;    // 0.5 mg/kg daily
} else if (SOLVERTIME >= HC_T0 && SOLVERTIME <= HC_T1) {
  hc_rate = HC_RATE;
}
double hc_in = hc_rate * wt;

// --- intratracheal budesonide: BUD_N doses q8h ---------------------------
double bud_in = 0.0;
if (BUD_DOSE > 0.0) {
  double dwin = BUD_N / 3.0;                       // q8h -> N/3 days
  if (SOLVERTIME >= BUD_T0 && SOLVERTIME < BUD_T0 + dwin)
    bud_in = BUD_DOSE * BUD_N * wt / dwin;
}

// --- vitamin A: VITA_N IM doses at VITA_IVL intervals ---------------------
double vita_in = 0.0;
if (VITA_T0 < 900.0) {
  double dwin = VITA_N * VITA_IVL;
  if (SOLVERTIME >= VITA_T0 && SOLVERTIME < VITA_T0 + dwin) {
    // 1 IU retinol = 0.3 microgram = 0.001047 micromol
    vita_in = VITA_IU * 0.001047 / VITA_IVL;
  }
}

double azi_in = ((SOLVERTIME >= AZI_T0) && (SOLVERTIME <= AZI_T1)) ? AZI_RATE * wt : 0.0;
double sil_in = ((SOLVERTIME >= SIL_T0) && (SOLVERTIME <= SIL_T1))
                  ? SIL_F * SIL_RATE * wt : 0.0;

// ==========================================================================
// 2. PK -> CONCENTRATIONS -> RECEPTOR OCCUPANCIES
// ==========================================================================
// caffeine clearance matures with PMA (t1/2 ~90 h at PMA 26 -> ~6 h at PMA 60)
double pmh    = pow(PMA, CAF_HILL);
double caf_cl = CAF_CLI * pmh / (pow(CAF_PMA50, CAF_HILL) + pmh) * wt;
double Ccaf   = CAFC / (CAF_VD * wt);
double Cdex   = DEXC / (DEX_VD * wt);
double Chc    = HCC  / (HC_VD  * wt);
double Cbudl  = BUDL / (BUD_VL * wt);
double Cbudc  = BUDC / (BUD_VD * wt);
double Cret   = RETP / (RET_VD * wt);
double Cazi   = AZIC / (AZI_VD * wt);
double Csil   = SILC / (SIL_VD * wt);

// ONE receptor, THREE ligands: everything is dexamethasone-equivalent mg/L.
// The systemic occupancy drives NDI cost; the lung occupancy drives the local
// anti-inflammatory and antiproliferative effects. Intratracheal budesonide
// separates the two, which is exactly why it is interesting.
double DXE_sys  = Cdex + HC_POT * Chc + BUD_POT * Cbudc;
double DXE_lung = Cdex + HC_POT * Chc + BUD_POT * Cbudl;
double GRocc_s  = DXE_sys  / (GR_EC50 + DXE_sys);
double GRocc_l  = DXE_lung / (GR_EC50 + DXE_lung);

double E_transrep = GR_EMAXR * GRocc_l;              // NF-kB suppression
double E_comp     = GR_ECOMP * GRocc_l;              // compliance / extubation
double E_antiprol = AG_GR    * GRocc_l;              // THE HIDDEN COST
double E_caf_ap   = CAF_EMAX * Ccaf / (CAF_EC50 + Ccaf);
double E_caf_alv  = CAF_EALV * Ccaf / (CAF_ECA  + Ccaf);
double E_sil      = SIL_EMAX * Csil / (SIL_EC50 + Csil);
double E_ino      = INO_EMAX * INO_PPM / (INO_EC50 + INO_PPM);
double E_azi      = AZI_KILL * Cazi / (AZI_EC50 + Cazi);
double E_furo     = ((FURO > 0.5) && (SOLVERTIME >= FURO_T0)) ? FURO_EMAX : 0.0;
double E_msc      = ((MSC  > 0.5) && (SOLVERTIME >= MSC_T0))
                      ? MSC_EMAX * exp(-(SOLVERTIME - MSC_T0) / MSC_TAU) : 0.0;
double E_rhigf    = ((RHIGF > 0.5) && (SOLVERTIME <= RHIGF_T1)) ? RHIGF_E : 0.0;
double E_il1ra    = ((IL1RA > 0.5) && (SOLVERTIME >= IL1RA_T0)
                     && (SOLVERTIME <= IL1RA_T1)) ? IL1RA_E : 0.0;
double E_era      = (ERA   > 0.5) ? ERA_EMAX : 0.0;
double E_bd       = (BRONCHO > 0.5) ? BRONCHO_E : 0.0;

// ==========================================================================
// 3. GAS EXCHANGE -> REQUIRED FiO2 -> CLINICIAN ESCALATION LOOP
//    This is the vicious cycle, written as a feedback loop rather than
//    asserted in prose: worse lung -> more support -> more injury.
// ==========================================================================
// Oxygen requirement is built from TWO physiologically distinct terms:
//
//  (a) a DIFFUSION/RESERVE term from the surface and capillary deficit,
//      measured against the GESTATION-MATCHED IDEAL (a healthy 25-weeker
//      breathes room air, so the deficit relative to its own developmental
//      trajectory is what costs oxygen). The lung has large reserve: demand
//      up to DTHR is tolerated on room air, and only beyond DTHR does FiO2
//      climb. That reserve is why the 36-week FiO2 is a POOR readout of the
//      developmental deficit, and why this model carries LOSTW separately.
//
//  (b) a SHUNT term from atelectasis, oedema, septal fibrosis and airway
//      narrowing, measured ABOVE the healthy baseline (LW_BASE, SEPT_BASE),
//      because a normal lung carries some water and normal septa and still
//      needs no oxygen. Shunt has NO reserve: it raises FiO2 immediately,
//      which is exactly what makes a diuretic look like it is working.
double aid_e = ALVMAX - (ALVMAX - A20) * exp(-r_prog2 * phi_now_ode);
double rel_a = (ALV  / aid_e > 1e-4) ? ALV  / aid_e : 1e-4;
double rel_c = (CAPD / aid_e > 1e-4) ? CAPD / aid_e : 1e-4;

double Dmd_s = 1.0 / (pow(rel_a, PALV) * pow(rel_c, PCAP));
Dmd_s = Dmd_s / (1.0 + 0.35 * E_comp);               // steroid compliance gain
double Rex = (Dmd_s - DTHR > 0.0) ? Dmd_s - DTHR : 0.0;

double sept_sat = SEPT / (1.0 + SEPT);
double lw_ex = (LW - LW_BASE > 0.0) ? LW - LW_BASE : 0.0;
double sp_ex = (sept_sat - SEPT_BASE > 0.0) ? sept_sat - SEPT_BASE : 0.0;
double sh_arg = KSH * (KLWO / 1.28 * lw_ex + 0.5 * sp_ex
                       + KASMO * ASM * (1.0 - E_bd));
sh_arg = sh_arg / (1.0 + 0.35 * E_comp);
double Sh = sh_arg / (1.0 + sh_arg);
double Dmd = Dmd_s * (1.0 + KSEPTO * sp_ex + KLWO * lw_ex);

double band = (SPO2HI > 0.5) ? 1.0 : BANDF;
double FiO2 = 0.21 + 0.79 * (1.0 - (1.0 - Sh) * exp(-KFIO2 * Rex));
FiO2 = 0.21 + (FiO2 - 0.21) * band;
if (FiO2 > 1.0)  FiO2 = 1.0;
if (FiO2 < 0.21) FiO2 = 0.21;

double sup_tgt = 1.0 - exp(-KSUP * (Rex + 2.0 * Sh));

// apnoea of prematurity: matures spontaneously, suppressed by caffeine
double apnoea = AP0 * exp(-SOLVERTIME / TAU_AP) * (1.0 - CAF_DRIVE * E_caf_ap);
double mvdrive = sup_tgt + WAP * apnoea - 0.25 * LISA - 0.30 * E_comp;
if (SOLVERTIME >= TRACH_T) mvdrive = 1.0;
double mvf_tgt = 1.0 / (1.0 + exp(-(mvdrive - THRMV) / SMV));

// ==========================================================================
// 4. INJURY DRIVE
// ==========================================================================
double vili = KVILI * MVF * pow(SUP, NVILI)
                * (1.0 - EFF_VTV * VTV) * (1.0 - EFF_PHC * PHC)
              + KNIV * (1.0 - MVF) * pow(SUP, NVILI);

// Male sex is associated with later lung and antioxidant maturation; written
// as a BONUS for female sex so MALE = 1 (the reference) is the baseline.
double aoxpma_e = AOXPMA - 0.8 * (1.0 - MALE);
double aoxm  = AOX0 / (1.0 + exp(-(PMA - aoxpma_e) / AOXSL));
double fexc  = (FiO2 - 0.21) / 0.79;
double oxtox = KOX * pow(fexc, NOX) / (1.0 + aoxm);

// hypoxaemia burden: the low SpO2 band and unresolved apnoea both contribute
double hb = ((SPO2HI > 0.5) ? 0.0 : BANDHX) + 0.55 * apnoea;
double hypox = KHYPOX * hb;

double pda = ((SOLVERTIME >= PDA_T0) &&
              ((PDA_T1 <= 0.0) || (SOLVERTIME <= PDA_T1))) ? PDA_MAG : 0.0;
double sepsis = ((SOLVERTIME >= SEP_T0) && (SOLVERTIME <= SEP_T0 + SEP_DUR))
                  ? SEP_MAG : 0.0;
double ante = KANTE * CHORIO * exp(-SOLVERTIME / TAU_ANTE);

double INJ = vili + oxtox
             + KURE * UREA * (1.0 - ((E_azi > 0.0) ? AZI_AI : 0.0))
             + KSEP * sepsis + KPDAI * pda
             + ante + KROSI * ROS;

// ==========================================================================
// 5. INFLAMMATION
// ==========================================================================
double sflt = 0.35 * IUGR + 0.15 * CHORIO;

// Every cascade node is a SATURATING target-approach, so no amount of injury
// can make the mediators unbounded. Biologically this is receptor and
// transcription-factor saturation; numerically it is what makes the escalation
// loop settle into a PHENOTYPE instead of diverging. A linear cascade here
// produces an infant who is on 100% oxygen by day 3 and dies, which is not
// the disease being modelled.
double nf_tgt = (NF0 + (NFMAX - NF0) * INJ / (KINJ50 + INJ))
                / (1.0 + 2.0 * E_transrep);
dxdt_NFKB = (nf_tgt - NFKB) * KOUT_NF;

double il1_tgt = KIN_IL1 * NFKB * (1.0 + FNLRP3 * ROS / (1.0 + ROS))
                 / (1.0 + 0.9 * E_transrep + 2.0 * E_il1ra);
dxdt_IL1B = (il1_tgt - IL1B) * KOUT_IL1;

double ne_tgt = KIN_NE * (IL1B + 0.5 * NFKB) / (1.0 + 0.8 * E_transrep);
dxdt_NEUT = (ne_tgt - NEUT) * KOUT_NE;

double tg_tgt = KIN_TG * (WTG_MECH * vili + (1.0 - WTG_MECH) * NFKB);
dxdt_TGFB = (tg_tgt - TGFB) * KOUT_TG;

double ro_tgt = KIN_RO * (oxtox + 0.30 * NEUT) / (1.0 + aoxm);
dxdt_ROS  = (ro_tgt - ROS) * KOUT_RO;

// ==========================================================================
// 6. THE GROWTH GATE  G
// ==========================================================================
double vegf_t = (1.0 + MSC_EMAX * 0.0 + E_msc)
                / (1.0 + AV_IL1 * IL1B + AV_ROS * ROS + AV_SFLT * sflt);
double no_t   = (0.35 + 0.65 * VEGF) / (1.0 + AN_ROS * ROS + AN_ADMA * hb);
double igf_b  = IGFB0 + IGFBSL * (PMA - 24.0);
if (igf_b > 1.15) igf_b = 1.15;
double igf_t  = igf_b * (1.0 - AI_INFL * NFKB / (1.0 + NFKB))
                      * (1.0 - AI_DEX  * GRocc_s)
                      * (1.0 + (NUTR > 0.5 ? NUTR_EFF : 0.0))
                      * (1.0 + E_rhigf)
                      * (IUGR > 0.5 ? 0.80 : 1.0);
double ra_t   = Cret / (KM_RA + Cret);
double epc_t  = (1.0 + 0.5 * E_msc) / (1.0 + AE_ROS * ROS);

dxdt_VEGF  = (vegf_t - VEGF) / TAU_V;
dxdt_NOB   = (no_t   - NOB)  / TAU_NO;
dxdt_IGF1  = (igf_t  - IGF1) / TAU_I;
dxdt_RASIG = (ra_t   - RASIG)/ TAU_R;
dxdt_EPC   = (epc_t  - EPC)  / TAU_E;

// cGMP tone: NO bioavailability, amplified by PDE5 inhibition and iNO
double cgmp = NOB * (1.0 + E_sil) + E_ino;
if (cgmp > 2.5) cgmp = 2.5;

double v_e = (VEGF  > 1e-4) ? VEGF  : 1e-4;
double n_e = (cgmp  > 1e-4) ? cgmp  : 1e-4;
double i_e = (IGF1  > 1e-4) ? IGF1  : 1e-4;
double r_e = (RASIG > 1e-4) ? RASIG : 1e-4;
double e_e = (EPC   > 1e-4) ? EPC   : 1e-4;

double Gcore = exp(WV*log(v_e) + WN*log(n_e) + WI*log(i_e)
                 + WR*log(r_e) + WE*log(e_e));
double G = Gcore / (1.0 + AG_TGF * TGFB)
                 / (1.0 + AG_IL1 * IL1B)
                 * (1.0 - E_antiprol)
                 * (1.0 + E_caf_alv);
if (G < 0.0) G = 0.0;
if (G > 1.6) G = 1.6;

// ==========================================================================
// 7. STRUCTURE — the programme equation and its shadow, the LOST WINDOW
// ==========================================================================
double head_alv = r_prog2 * SDEV * (ALVMAX - ALV) / 7.0;   // per DAY
double head_cap = KCAPREL * r_prog2 * SDEV * (CAPMAX - CAPD) / 7.0;
double Gv = exp(0.45*log(v_e) + 0.30*log(n_e) + 0.15*log(i_e) + 0.10*log(e_e))
            / (1.0 + 0.5 * AG_TGF * TGFB) * (1.0 - E_antiprol);
if (Gv > 1.6) Gv = 1.6;

dxdt_ALV  = head_alv * G  - KDEGALV * NEUT * ALV;
dxdt_CAPD = head_cap * Gv - KDEGALV * 0.6 * NEUT * CAPD;

// THE COUNTER: surface that the programme was scheduled to build and did not.
dxdt_LOSTW = head_alv * (1.0 - G);

dxdt_SEPT = KSEPT * TGFB - KOUT_SEPT * SEPT;
// ASM is EXCESS smooth muscle: driven by IL-1beta above its basal level, so
// a healthy lung sits at ASM = 0 and contributes nothing to the shunt term.
dxdt_ASM  = KASM * (((IL1B - IL1B_BAS > 0.0) ? IL1B - IL1B_BAS : 0.0)
                    + 0.3 * MVF) - KOUT_ASM * ASM;
dxdt_LW   = KLW * (pda + 0.5 * NEUT / (1.0 + NEUT) + 0.4 * FLUID)
            - KOUT_LW * LW * (1.0 + E_furo);

// ==========================================================================
// 8. SUPPORT DYNAMICS (the loop closes here)
// ==========================================================================
dxdt_SUP = (sup_tgt - SUP) / TAU_SUP;
dxdt_MVF = (mvf_tgt - MVF) / TAU_MV;

// ==========================================================================
// 9. UREAPLASMA
// ==========================================================================
dxdt_UREA = URE_GROW * UREA * (1.0 - UREA / URE_MAX) - E_azi * UREA;

// ==========================================================================
// 10. PULMONARY VASCULAR / RV
// ==========================================================================
double XS = pow((CAPD > 0.02 ? CAPD : 0.02), 1.0);
double et1 = (0.25 + 0.6 * ROS + 0.5 * hb) * (1.0 - E_era);
double hpv = hb / (1.0 + 1.2 * (cgmp - 1.0 > 0.0 ? cgmp - 1.0 : 0.0));
double PVRn = (1.0 / pow(XS, PXS)) * (1.0 + KHPV * hpv) * (1.0 + KVR * VREM);

dxdt_VREM = KVRIN * (hb + KET1 * et1 + 0.2 * pda) - KVROUT * VREM;
dxdt_RVHY = KRV * ((PVRn - 1.0 > 0.0) ? PVRn - 1.0 : 0.0) - KRVOUT * RVHY;

// ==========================================================================
// 11. PK ODEs
// ==========================================================================
dxdt_CAFG = caf_in - CAF_KA * CAFG;
dxdt_CAFC = CAF_KA * CAFG - caf_cl * Ccaf;
dxdt_DEXC = dex_in - DEX_CL * wt * Cdex;
dxdt_HCC  = hc_in  - HC_CL  * wt * Chc;
dxdt_BUDL = bud_in - BUD_KLS * BUDL;
dxdt_BUDC = BUD_KLS * BUDL - BUD_CL * wt * Cbudc;
dxdt_RETS = vita_in + RET_DIET - RET_KR * RETS;
dxdt_RETP = RET_KR * RETS - RET_CL * wt * Cret;
dxdt_AZIC = azi_in - AZI_CL * wt * Cazi;
dxdt_SILC = sil_in - SIL_CL * wt * Csil;
dxdt_DEXEQ = dex_rate + HC_POT * hc_rate
             + (bud_in > 0.0 ? BUD_POT * 0.05 * bud_in / wt : 0.0);

// ==========================================================================
// 12. BODY WEIGHT
// ==========================================================================
double gr = GRMAX * (1.0 - AW_DEX * GRocc_s)
                  * (1.0 - AW_INFL * NFKB / (1.0 + NFKB))
                  * (1.0 + (NUTR > 0.5 ? NUTR_EFF : 0.0));
double wl = WLOSS * exp(-SOLVERTIME / TAU_WL);
dxdt_WT = WT * (gr - wl);

// ==========================================================================
// 13. ENDPOINT ACCUMULATORS
// ==========================================================================
double early_w = 1.0 + W_EARLY * exp(-SOLVERTIME / 7.0);
dxdt_NDIC  = W_DEX * (dex_rate + HC_POT * hc_rate) * early_w
             + W_HYPOX * hb
             + W_HYPOCAP * HYPOCAP * MVF * (1.0 - VTV);
dxdt_VDAYS  = MVF;
dxdt_O2DAYS = (FiO2 > FIO2_THR) ? 1.0 : 0.0;
dxdt_HAZ    = H0 + H_HYPOX * hb + H_PVR * ((PVRn > 1.5) ? PVRn - 1.5 : 0.0)
              + H_SEP * sepsis + H_G3 * MVF;

$TABLE
double PMAout = GA + TIME / 7.0;
double wt_o   = (WT > 0.35) ? WT : 0.35;

double Ccaf_o = CAFC / (CAF_VD * wt_o);
double Cdex_o = DEXC / (DEX_VD * wt_o);
double Chc_o  = HCC  / (HC_VD  * wt_o);
double Cret_o = RETP / (RET_VD * wt_o);
double Csil_o = SILC / (SIL_VD * wt_o);
double Cazi_o = AZIC / (AZI_VD * wt_o);
double Cbud_o = BUDL / (BUD_VL * wt_o);

double DXEs_o = Cdex_o + HC_POT * Chc_o + BUD_POT * (BUDC / (BUD_VD * wt_o));
double DXEl_o = Cdex_o + HC_POT * Chc_o + BUD_POT * Cbud_o;
double GRo_s  = DXEs_o / (GR_EC50 + DXEs_o);
double GRo_l  = DXEl_o / (GR_EC50 + DXEl_o);

double wSo = (PMAout < PMAPK) ? SDW_L : SDW_R;
double zSo = (PMAout - PMAPK) / wSo;
double SDEVo = exp(-0.5 * zSo * zSo);

double alv_o = (ALV  > 0.02) ? ALV  : 0.02;
double cap_o = (CAPD > 0.02) ? CAPD : 0.02;
double Ecmp  = GR_ECOMP * GRo_l;
double Ebd_o = (BRONCHO > 0.5) ? BRONCHO_E : 0.0;
double phi_now = bpd_phi(PMAout, PMAPK, SDW_L, SDW_R);
double r_prog_o = KALV / bpd_phi(36.0, PMAPK, SDW_L, SDW_R);
double ALV_ideal = ALVMAX - (ALVMAX - A20) * exp(-r_prog_o * phi_now);

double rel_ao = (alv_o / ALV_ideal > 1e-4) ? alv_o / ALV_ideal : 1e-4;
double rel_co = (cap_o / ALV_ideal > 1e-4) ? cap_o / ALV_ideal : 1e-4;
double Dmd_so = 1.0 / (pow(rel_ao, PALV) * pow(rel_co, PCAP));
Dmd_so = Dmd_so / (1.0 + 0.35 * Ecmp);
double Rexo = (Dmd_so - DTHR > 0.0) ? Dmd_so - DTHR : 0.0;

double sept_sato = SEPT / (1.0 + SEPT);
double lw_exo = (LW - LW_BASE > 0.0) ? LW - LW_BASE : 0.0;
double sp_exo = (sept_sato - SEPT_BASE > 0.0) ? sept_sato - SEPT_BASE : 0.0;
double sh_argo = KSH * (KLWO / 1.28 * lw_exo + 0.5 * sp_exo
                        + KASMO * ASM * (1.0 - Ebd_o));
sh_argo = sh_argo / (1.0 + 0.35 * Ecmp);
double Sho = sh_argo / (1.0 + sh_argo);
double Dmdo = Dmd_so * (1.0 + KSEPTO * sp_exo + KLWO * lw_exo);

double bando = (SPO2HI > 0.5) ? 1.0 : BANDF;
double FIO2 = 0.21 + 0.79 * (1.0 - (1.0 - Sho) * exp(-KFIO2 * Rexo));
FIO2 = 0.21 + (FIO2 - 0.21) * bando;
if (FIO2 > 1.0)  FIO2 = 1.0;
if (FIO2 < 0.21) FIO2 = 0.21;

double apn_o = AP0 * exp(-TIME / TAU_AP)
               * (1.0 - CAF_DRIVE * (CAF_EMAX * Ccaf_o / (CAF_EC50 + Ccaf_o)));
double hbo = ((SPO2HI > 0.5) ? 0.0 : BANDHX) + 0.55 * apn_o;

double XSo = cap_o;
double cgmpo = NOB * (1.0 + SIL_EMAX * Csil_o / (SIL_EC50 + Csil_o))
               + INO_EMAX * INO_PPM / (INO_EC50 + INO_PPM);
double hpvo = hbo / (1.0 + 1.2 * ((cgmpo - 1.0 > 0.0) ? cgmpo - 1.0 : 0.0));
double PVR = (1.0 / pow(XSo, PXS)) * (1.0 + KHPV * hpvo) * (1.0 + KVR * VREM);

// ---- Jensen/NICHD 2019 grade, evaluated on the support the model needs ----
double GRADE = 0.0;
if      (MVF >= 0.50)                      GRADE = 3.0;
else if (SUP >= THRNIV)                    GRADE = 2.0;
else if (FIO2 > FIO2_THR)                  GRADE = 1.0;
double PSURV = exp(-HAZ);
double NETU  = PSURV * ((GRADE < 0.5) ? 1.0 : 0.0) - W_NDI * NDIC;

// ---- the "surface debt": ALV_ideal was computed above from the same
//      closed-form window integral, so this is the exact shortfall ---------
double ALV_PCT = 100.0 * ALV / ALV_ideal;

$CAPTURE @annotated
PMAout  : Postmenstrual age (weeks)
FIO2    : Model-required FiO2 to hold the SpO2 target band
GRADE   : BPD grade by mode of support (0 none, 1, 2, 3)
SDEVo   : Septation drive S_dev(PMA)
ALV_ideal: Alveolar surface of an uninjured fetus at the same PMA
ALV_PCT : Alveolar surface as % of the gestation-matched ideal
PVR     : Pulmonary vascular resistance (1.0 = healthy)
Ccaf_o  : Caffeine concentration (mg/L)
Cdex_o  : Dexamethasone concentration (mg/L)
Chc_o   : Hydrocortisone concentration (mg/L)
Cret_o  : Plasma retinol (micromol/L)
Csil_o  : Sildenafil concentration (mg/L)
Cazi_o  : Azithromycin concentration (mg/L)
Cbud_o  : Budesonide lung concentration (mg/L)
GRo_s   : Systemic GR occupancy (drives NDI cost and growth failure)
GRo_l   : Lung GR occupancy (drives anti-inflammatory and antiproliferative effects)
Dmdo    : Oxygenation demand index (1.0 = healthy)
hbo     : Hypoxaemia burden
PSURV   : Modelled probability of survival to the current time
NETU    : Net utility = survival without BPD minus W_NDI x NDI cost
'

mod <- mcode("bpd_qsp", bpd_code, soloc = tempdir())

## ============================================================================
##  SCENARIO LIBRARY
## ============================================================================
##  Every scenario is a named list of parameter overrides applied to the same
##  25-week reference infant, so differences between arms are attributable to
##  the intervention and nothing else. The reference infant is deliberately
##  bleak (chorioamnionitis-exposed, intubated in the delivery room, PDA open
##  for two weeks, no adjunctive therapy) because that is the population in
##  which the landmark trials were run.

BPD_reference <- list(
  GA = 25, BW = 0.70, CHORIO = 1, ANTESTER = 1, MALE = 1,
  LISA = 0, VTV = 0, PHC = 0, SPO2HI = 1, SURF = 1,
  PDA_T0 = 1, PDA_T1 = 14, HYPOCAP = 1
)

.ov <- function(...) modifyList(BPD_reference, list(...))

BPD_scenarios <- list(

  ## ---- 0. natural history: no adjunctive therapy at all -------------------
  "S00 reference (no adjunct)" = .ov(),

  ## ---- 1. EXPOSURE-class interventions ------------------------------------
  "S01 caffeine (CAP dosing)" =
    .ov(CAF_T0 = 1, CAF_LD = 20, CAF_MD = 5),

  "S02 caffeine, drive arm OFF (biology arm only)" =
    .ov(CAF_T0 = 1, CAF_LD = 20, CAF_MD = 5, CAF_DRIVE = 0),

  "S03 LISA / nCPAP (no intubation)" =
    .ov(LISA = 1),

  "S04 volume-targeted ventilation + permissive hypercapnia" =
    .ov(VTV = 1, PHC = 1, HYPOCAP = 0),

  "S05 early PDA closure (day 3)" =
    .ov(PDA_T1 = 3),

  ## ---- 2. TRANSDUCTION-class interventions --------------------------------
  "S06 PREMILOC early low-dose hydrocortisone (d1-10)" =
    .ov(HC_PREM = 1, HC_T0 = 1),

  "S07 DART late low-dose dexamethasone (d14-23)" =
    .ov(DEX_DART = 1, DEX_T0 = 14),

  "S08 early HIGH-dose dexamethasone (0.5 mg/kg/d, d1-7)" =
    .ov(DEX_RATE = 0.5, DEX_T0 = 1, DEX_T1 = 7),

  "S09 intratracheal budesonide + surfactant" =
    .ov(BUD_DOSE = 0.25, BUD_T0 = 1, BUD_N = 4),

  "S10 azithromycin, Ureaplasma POSITIVE" =
    .ov(UREA0 = 1, AZI_RATE = 10, AZI_T0 = 1, AZI_T1 = 7),

  "S11 azithromycin, Ureaplasma NEGATIVE" =
    .ov(UREA0 = 0, AZI_RATE = 10, AZI_T0 = 1, AZI_T1 = 7),

  ## ---- 3. PROGRAMME-class interventions -----------------------------------
  "S12 vitamin A (Tyson regimen)" =
    .ov(VITA_T0 = 1, VITA_IU = 5000, VITA_N = 12),

  ## ---- 4. things that move a number but not the endpoint ------------------
  "S13 furosemide only" =
    .ov(FURO = 1, FURO_T0 = 10),

  "S14 sildenafil for BPD-PH (from day 28)" =
    .ov(SIL_RATE = 3, SIL_T0 = 28, SIL_T1 = 90),

  ## ---- 5. bundles and the timing experiment -------------------------------
  "S15 EARLY bundle (all of it, from day 1)" =
    .ov(LISA = 1, VTV = 1, PHC = 1, HYPOCAP = 0,
        CAF_T0 = 1, HC_PREM = 1, HC_T0 = 1,
        VITA_T0 = 1, NUTR = 1, PDA_T1 = 4,
        UREA0 = 1, AZI_RATE = 10, AZI_T0 = 1, AZI_T1 = 7),

  "S16 LATE bundle (the same drugs, from day 21)" =
    .ov(CAF_T0 = 21, DEX_DART = 1, DEX_T0 = 21,
        VITA_T0 = 21, NUTR = 1, FURO = 1, FURO_T0 = 21),

  ## ---- 6. the SpO2 target band --------------------------------------------
  "S17 low SpO2 target band (85-89%)" =
    .ov(SPO2HI = 0, CAF_T0 = 1),

  "S18 high SpO2 target band (91-95%)" =
    .ov(SPO2HI = 1, CAF_T0 = 1)
)

## ============================================================================
##  RUNNERS
## ============================================================================

#' Simulate one scenario out to a chosen PMA
#'
#' @param pars named list of parameter overrides
#' @param end_pma  PMA (weeks) at which to stop; 36 is the definitional stop,
#'                 but the model is informative out to 50-60 weeks because the
#'                 septation window is still open there.
BPD_run <- function(pars = BPD_reference, end_pma = 40, dt = 0.25) {
  ga  <- if (!is.null(pars$GA)) pars$GA else 25
  end <- (end_pma - ga) * 7
  mod %>%
    param(pars) %>%
    mrgsim(end = end, delta = dt, atol = 1e-8, rtol = 1e-6, hmax = 0.25) %>%
    as_tibble()
}

#' Endpoint summary at exactly 36 weeks PMA (the definitional clock stop)
BPD_endpoints <- function(sim, ga) {
  t36 <- (36 - ga) * 7
  r <- sim[which.min(abs(sim$time - t36)), ]
  tibble::tibble(
    PMA36_day   = round(t36, 1),
    ALV36       = round(r$ALV, 4),
    ALV_pct_ideal = round(r$ALV_PCT, 1),
    CAP36       = round(r$CAPD, 4),
    LOSTW       = round(r$LOSTW, 4),
    FiO2_36     = round(r$FIO2, 3),
    grade       = r$GRADE,
    MV_frac_36  = round(r$MVF, 3),
    vent_days   = round(r$VDAYS, 1),
    O2_days     = round(r$O2DAYS, 1),
    PVR36       = round(r$PVR, 3),
    RVH36       = round(r$RVHY, 3),
    weight36    = round(r$WT, 3),
    DEXEQ_mgkg  = round(r$DEXEQ, 3),
    NDI_cost    = round(r$NDIC, 4),
    P_survive   = round(r$PSURV, 4),
    net_utility = round(r$NETU, 4)
  )
}

#' Run every prebuilt scenario and return one endpoint table
BPD_simulate_scenarios <- function(scenarios = BPD_scenarios, end_pma = 40) {
  out <- lapply(names(scenarios), function(nm) {
    p  <- scenarios[[nm]]
    s  <- BPD_run(p, end_pma = end_pma)
    e  <- BPD_endpoints(s, ga = if (!is.null(p$GA)) p$GA else 25)
    dplyr::bind_cols(tibble::tibble(scenario = nm), e)
  })
  dplyr::bind_rows(out)
}

## ============================================================================
##  A1. THE GESTATIONAL GRADIENT COMES FROM THE WINDOW, NOT FROM A COEFFICIENT
## ============================================================================
#' How much of the alveolarisation programme is still ahead at birth?
#'
#' Returns, for each GA, the fraction of the total S_dev integral that has NOT
#' yet been spent at the moment of birth. This is the quantity that has to be
#' completed EX UTERO, on a ventilator, in oxygen — and it is why the GA
#' gradient of BPD is as steep as it is.
BPD_window_remaining <- function(ga = c(22, 24, 26, 28, 30, 32, 34, 37),
                                 pmapk = 32, wl = 4, wr = 14) {
  sdev <- function(p) {
    w <- ifelse(p < pmapk, wl, wr)
    exp(-0.5 * ((p - pmapk) / w)^2)
  }
  tot <- integrate(sdev, 20, 120)$value
  tibble::tibble(
    GA = ga,
    frac_spent_in_utero = round(sapply(ga, function(g)
      integrate(sdev, 20, g)$value) / tot, 3),
    frac_remaining_ex_utero = round(1 - sapply(ga, function(g)
      integrate(sdev, 20, g)$value) / tot, 3),
    frac_of_window_between_birth_and_36wk = round(sapply(ga, function(g)
      integrate(sdev, g, 36)$value) / tot, 3)
  )
}

## ============================================================================
##  A2. TIMING vs POTENCY — the crossover day
## ============================================================================
#' Compare an EARLY WEAK gate-opener against a LATE STRONG one
#'
#' Both arms are given the same idealised "gate opener" implemented as a
#' fractional reduction of IL-1beta (a transduction-class drug). The early arm
#' is weak (eff_early), the late arm is strong (eff_late). The function returns
#' the 36-week alveolar surface for each start day so the crossover can be read
#' off directly.
BPD_timing_vs_potency <- function(eff_early = 0.40, eff_late = 1.00,
                                  start_days = c(1, 3, 5, 7, 10, 14, 21, 28),
                                  base = BPD_reference) {
  run1 <- function(eff, t0) {
    p <- modifyList(base, list(IL1RA = 1, IL1RA_E = eff, IL1RA_T0 = t0,
                               IL1RA_T1 = 999))
    s <- BPD_run(p, end_pma = 36.01)
    tail(s$ALV, 1)
  }
  base_alv <- tail(BPD_run(base, end_pma = 36.01)$ALV, 1)
  out <- lapply(start_days, function(t0) {
    data.frame(
      start_day  = t0,
      ALV36_weak   = round(run1(eff_early, t0), 4),
      ALV36_strong = round(run1(eff_late,  t0), 4)
    )
  })
  out <- dplyr::bind_rows(out)
  out$ALV36_untreated <- round(base_alv, 4)
  # the claim: early-weak beats late-strong up to the crossover day
  early_weak <- out$ALV36_weak[out$start_day == min(start_days)]
  out$early_weak_still_wins <- out$ALV36_strong < early_weak
  out
}

## ============================================================================
##  A3. WHERE DOES CAFFEINE'S BENEFIT ACTUALLY COME FROM?
## ============================================================================
#' Decompose caffeine into its exposure arm and its biology arm
#'
#' S01 has both arms; S02 has only the direct A2A alveolarisation arm. The
#' difference between them is the share of caffeine's 36-week benefit that is
#' attributable to getting the infant off the ventilator sooner rather than to
#' any direct effect on the lung.
BPD_caffeine_decomposition <- function() {
  arms <- list(
    "no caffeine"        = BPD_scenarios[["S00 reference (no adjunct)"]],
    "caffeine, full"     = BPD_scenarios[["S01 caffeine (CAP dosing)"]],
    "caffeine, A2A only" = BPD_scenarios[["S02 caffeine, drive arm OFF (biology arm only)"]]
  )
  tab <- BPD_simulate_scenarios(arms, end_pma = 40)
  base <- tab$ALV36[1]
  tab$delta_ALV <- round(tab$ALV36 - base, 4)
  tab$share_of_full_benefit <- round(tab$delta_ALV /
                                       (tab$ALV36[2] - base), 3)
  tab[, c("scenario", "ALV36", "delta_ALV", "share_of_full_benefit",
          "vent_days", "grade", "LOSTW")]
}

## ============================================================================
##  A4. THE VIRTUAL POPULATION — turning one infant into an incidence
## ============================================================================
#' Deterministic grid population (no RNG, fully reproducible)
#'
#' Two covariates dominate between-infant variance in this model: the severity
#' of the antenatal hit and the individual sensitivity of the lung to
#' mechanical injury. A weighted 7x7 grid over those two reproduces a BPD
#' incidence that can be compared with the CAP-trial control arm.
BPD_virtual_population <- function(pars = BPD_reference, end_pma = 36.01,
                                   gas = c(25, 26, 27, 28, 29),
                                   gaw = c(0.12, 0.20, 0.26, 0.24, 0.18)) {
  q  <- c(-1.5, 0, 1.5)
  wq <- exp(-0.5 * q^2); wq <- wq / sum(wq)
  gw <- gaw / sum(gaw)
  chors <- list(c(0, 0.65), c(1, 0.35))
  base_ante <- if (!is.null(pars$KANTE)) pars$KANTE else 2.24
  base_vili <- if (!is.null(pars$KVILI)) pars$KVILI else 0.583

  rows <- list()
  for (gi in seq_along(gas)) for (ch in chors)
    for (i in seq_along(q)) for (j in seq_along(q)) {
      p <- pars
      p$GA <- gas[gi]; p$BW <- 0; p$CHORIO <- ch[1]
      p$KANTE <- base_ante * exp(0.40 * q[i])
      p$KVILI <- base_vili * exp(0.35 * q[j])
      r <- tail(BPD_run(p, end_pma = end_pma), 1)
      rows[[length(rows) + 1]] <- data.frame(
        w = gw[gi] * ch[2] * wq[i] * wq[j],
        grade = r$GRADE, alv = r$ALV, lostw = r$LOSTW, psurv = r$PSURV)
    }
  res <- do.call(rbind, rows)
  tibble::tibble(
    n_virtual_infants = nrow(res),
    BPD_any_pct     = round(100 * sum(res$w * (res$grade >= 1)), 1),
    BPD_grade23_pct = round(100 * sum(res$w * (res$grade >= 2)), 1),
    BPD_grade3_pct  = round(100 * sum(res$w * (res$grade >= 3)), 1),
    death_pct       = round(100 * sum(res$w * (1 - res$psurv)), 1),
    mean_ALV36      = round(sum(res$w * res$alv), 4),
    mean_LOSTW      = round(sum(res$w * res$lostw), 4),
    surv_no_BPD_pct = round(100 * sum(res$w * res$psurv * (res$grade < 1)), 1)
  )
}

## NOTE on the "any BPD" column: under the reference care pattern it SATURATES
## at 100% in this model (see bpd_reference_impl.py, experiment A3). Compare
## treatment effects on BPD_grade23_pct, not on BPD_any_pct.


## ============================================================================
##  A5. THE SpO2 TARGET IS A TRADE-OFF, NOT AN OPTIMUM
## ============================================================================
#' Sweep the oxygen-saturation target band
#'
#' Reproduces the shape of the NeOProM/SUPPORT/BOOST-II result: the low band
#' reduces hyperoxic lung and retinal injury but costs survival, so the two
#' curves cross and the "best" band depends entirely on the weight put on
#' mortality relative to lung and eye.
BPD_spo2_sweep <- function(bands = seq(0, 1, by = 0.25)) {
  out <- lapply(bands, function(b) {
    p <- modifyList(BPD_reference, list(CAF_T0 = 1))
    p$BANDF  <- 1.0 - 0.14 * (1 - b)   # 0 = 85-89%, 1 = 91-95%
    p$SPO2HI <- 1
    p$KHYPOX <- 0.90 * (1 + 0.9 * (1 - b))
    s <- BPD_run(p, end_pma = 36.01); r <- tail(s, 1)
    data.frame(band_index = b, FiO2_36 = round(r$FIO2, 3),
               ALV36 = round(r$ALV, 4), grade = r$GRADE,
               P_survive = round(r$PSURV, 4),
               surv_no_BPD = round(r$PSURV * (r$GRADE < 1), 4),
               PVR36 = round(r$PVR, 3))
  })
  dplyr::bind_rows(out)
}

## ============================================================================
##  A6. PK SANITY CHECKS — the model must reproduce published neonatal PK
## ============================================================================
#' Caffeine half-life across PMA, and the concentration achieved by CAP dosing
BPD_caffeine_pk_check <- function() {
  pma  <- c(26, 28, 32, 36, 44, 52, 60)
  clkg <- 4.60 * pma^4 / (60^4 + pma^4)          # L/day/kg
  tibble::tibble(
    PMA_weeks   = pma,
    CL_L_h_kg   = round(clkg / 24, 4),
    t_half_h    = round(log(2) * 0.85 / clkg * 24, 1),
    Css_5mgkg_citrate  = round(0.5 * 5  / clkg, 1),
    Css_10mgkg_citrate = round(0.5 * 10 / clkg, 1)
  )
}

## ============================================================================
##  EXAMPLE SESSION
## ============================================================================
if (interactive()) {
  ## 1. every scenario, one table
  tab <- BPD_simulate_scenarios()
  print(as.data.frame(tab), row.names = FALSE)

  ## 2. how much programme is left at birth?
  print(BPD_window_remaining())

  ## 3. where does caffeine's benefit come from?
  print(BPD_caffeine_decomposition())

  ## 4. the SpO2 trade-off
  print(BPD_spo2_sweep())

  ## 5. PK sanity
  print(BPD_caffeine_pk_check())

  ## 6. a picture of the central claim
  s0 <- BPD_run(BPD_scenarios[["S00 reference (no adjunct)"]], end_pma = 44)
  s1 <- BPD_run(BPD_scenarios[["S15 EARLY bundle (all of it, from day 1)"]], end_pma = 44)
  op <- par(mfrow = c(2, 2), mar = c(4, 4, 2, 1))
  plot(s0$PMAout, s0$SDEVo, type = "l", lwd = 2, xlab = "PMA (weeks)",
       ylab = "S_dev", main = "The window is closing while you treat")
  abline(v = 36, lty = 3)
  plot(s0$PMAout, s0$ALV, type = "l", lwd = 2, ylim = c(0, 1.6),
       xlab = "PMA (weeks)", ylab = "Alveolar surface",
       main = "Surface built vs ideal")
  lines(s1$PMAout, s1$ALV, lwd = 2, col = "steelblue")
  lines(s0$PMAout, s0$ALV_ideal, lty = 2)
  abline(v = 36, lty = 3)
  legend("topleft", c("reference", "early bundle", "uninjured ideal"),
         lwd = c(2, 2, 1), lty = c(1, 1, 2), col = c(1, "steelblue", 1), bty = "n")
  plot(s0$PMAout, s0$LOSTW, type = "l", lwd = 2, xlab = "PMA (weeks)",
       ylab = "LOSTW", main = "The lost-window counter")
  lines(s1$PMAout, s1$LOSTW, lwd = 2, col = "steelblue")
  plot(s0$PMAout, s0$FIO2, type = "l", lwd = 2, ylim = c(0.2, 1),
       xlab = "PMA (weeks)", ylab = "FiO2", main = "What the chart records")
  lines(s1$PMAout, s1$FIO2, lwd = 2, col = "steelblue")
  abline(v = 36, lty = 3)
  par(op)
}
