##  Acute Respiratory Distress Syndrome (ARDS) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : ARDS (Berlin definition) — an acute, diffuse, inflammatory lung
##             injury in which a direct (pneumonia, aspiration, contusion) or
##             indirect (extrapulmonary sepsis, pancreatitis, trauma, TRALI)
##             insult breaks BOTH sides of the alveolar-capillary barrier. The
##             resulting protein-rich oedema floods and de-recruits alveoli, so
##             the aerated lung shrinks to a "baby lung" of 20-35% of the
##             parenchyma. Shunt through that flooded lung produces refractory
##             hypoxaemia; capillary microthrombosis produces dead space.
##
##             The distinguishing feature of ARDS as a QSP problem is that the
##             TREATMENT IS ALSO THE INJURY: every breath the ventilator gives
##             is delivered into whatever aerated lung is left, so the same
##             tidal volume that is harmless in a normal lung is a strain of
##             1.5-2.0 in a baby lung. This model therefore closes the loop
##
##                inflammation -> barrier failure -> oedema -> loss of aerated
##                lung -> higher strain / driving pressure / mechanical power
##                for the SAME ventilator setting -> VILI -> biotrauma ->
##                more inflammation
##
##             which is why interventions that change nothing about the biology
##             (tidal volume, prone position, ECMO) are the ones with the
##             largest mortality effects, while most anti-inflammatory drugs
##             tested in ARDS have failed.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5; developed and validated under 2.0.1)
##
##  Scope    : 38 ODE compartments —
##             * PK  : dexamethasone, methylprednisolone (both feeding one
##                     glucocorticoid-receptor genomic effect state),
##                     cisatracurium + its neuromuscular-block effect site,
##                     inhaled vasodilator (iNO / epoprostenol) effect site,
##                     tocilizumab, furosemide.
##             * Injury: insult burden, DAMPs, NF-kB, TNF-a, IL-1b, IL-6,
##                     IL-8, IL-10, alveolar neutrophils, NETs/elastase,
##                     oxidant burden, M1 and M2 macrophage programmes.
##             * Barrier: epithelial integrity, AT2 progenitor pool,
##                     surfactant pool, endothelial integrity, angiopoietin-2,
##                     PAI-1, alveolar fibrin/microthrombi.
##             * Physiology: extravascular lung water, cumulative fluid
##                     balance, cumulative VILI burden.
##             * Late phase: TGF-b1, collagen.
##             * Systemic: non-pulmonary SOFA, cumulative mortality hazard,
##                     ICU-acquired weakness, glucose, ventilator-free time.
##
##  Time     : HOURS (default horizon 672 h = 28 days, the standard endpoint
##             window for ventilator-free days and 28-day mortality).
##  Units    : cytokines pg/mL · Ang-2 and PAI-1 ng/mL · EVLW mL/kg PBW ·
##             fluid balance L · pressures cmH2O · PaO2/FiO2 mmHg ·
##             PaCO2 mmHg · compliance mL/cmH2O · mechanical power J/min ·
##             PVR dyn·s·cm^-5 · glucose mg/dL · drugs in mg (amounts) with
##             stated volumes, except tocilizumab which is dosed in mg into a
##             4 L central volume.
##             Barrier integrities (EPI, ENDO, SURF, AT2P) and the macrophage,
##             neutrophil, NET, ROS, DAMP and VILI pools are dimensionless
##             0-1(+) indices — the library's convention when the clinical
##             readout, not the assay, is the object of interest.
##
##  SELF-CALIBRATING BASELINE
##  -------------------------
##  A patient does not arrive at ICU admission in a healthy steady state, and
##  the clinician does not know their alveolar barrier integrity — they know
##  the PaO2/FiO2 ratio. [MAIN] therefore INVERTS the physiology: given the
##  presenting PaO2/FiO2 (PF0), the ventilator settings at enrolment, the
##  direct/indirect injury pattern (DIRECT) and the inflammatory subphenotype
##  (HYPER), it solves backwards for the shunt, the aerated fraction, the
##  split of non-aerated lung between flooding and atelectasis, and finally —
##  by a short fixed-point iteration on the lung-water balance — for the
##  epithelial and endothelial integrities and the surfactant pool that
##  actually produce that PaO2/FiO2. Cytokine production constants are then
##  back-calculated so that the prescribed presenting cytokine profile is the
##  one the model's own NF-kB state supports.
##
##  Consequence: change PF0 from 250 to 90 and every downstream state — EVLW,
##  compliance, driving pressure, mechanical power, hazard — moves the way it
##  moves in a real patient, without touching a single initial condition by
##  hand. Nothing in the untreated arm drifts for bookkeeping reasons; it
##  drifts because the insult resolves (or does not) and because the
##  ventilator keeps delivering energy into a shrunken lung.
##
##  Scenarios: 14 prebuilt — see ARDS_simulate_scenarios() at the bottom.
##
##  Anchors  :
##    * ARDSNet ARMA (NEJM 2000;342:1301) — 6 vs 12 mL/kg PBW: mortality
##      39.8% -> 31.0%. The single largest therapeutic effect in ARDS and the
##      calibration target for the VILI block (scenarios 1-2).
##    * Amato 2015 NEJM 372:747 — driving pressure is the ventilator variable
##      most strongly associated with survival (mediation analysis of 3562
##      patients); implemented as an explicit hazard term, not as a proxy.
##    * Gattinoni 2016 Intensive Care Med 42:1567 — mechanical power; the
##      ~12 J/min region as the inflection for VILI.
##    * PROSEVA (Guerin 2013 NEJM 368:2159) — >=16 h/day prone in PF<150:
##      28-day mortality 32.8% -> 16.0% (scenario 4).
##    * ACURASYS (Papazian 2010 NEJM 363:1107) vs ROSE (NHLBI PETAL 2019 NEJM
##      380:1997) — 48 h cisatracurium: benefit under deep sedation, neutral
##      under light sedation; the model reproduces the divergence through the
##      P-SILI/effort term (scenario 5 vs 5b).
##    * FACTT (Wiedemann 2006 NEJM 354:2564) — conservative fluid strategy:
##      +2.5 ventilator-free days, no change in mortality (scenario 7).
##    * DEXA-ARDS (Villar 2020 Lancet Respir Med 8:267) — dexamethasone 20 mg
##      d1-5 then 10 mg d6-10: +4.8 ventilator-free days, mortality
##      36% -> 21% (scenario 6); RECOVERY (NEJM 2021;384:693) for COVID-ARDS.
##    * ARDSNet LaSRS (Steinberg 2006 NEJM 354:1671) — methylprednisolone
##      started after day 14 increases mortality; reproduced in scenario 13
##      through the secondary-infection and weakness terms.
##    * EOLIA (Combes 2018 NEJM 378:1965) + CESAR — VV-ECMO with
##      ultraprotective settings (scenario 9).
##    * Calfee 2014 Lancet Respir Med 2:611 / Famous 2017 AJRCCM 195:331 —
##      hyper- vs hypo-inflammatory latent classes and their heterogeneous
##      treatment effects (scenarios 11-12).
##    * Taylor 2004 JAMA 291:1603 (iNO: oxygenation up, mortality unchanged)
##      and Matthay 2019 Lancet Respir Med 7:154 (MSC) for the "physiology
##      improves, outcome does not" pattern the hazard block must reproduce
##      (scenario 8).
##  ============================================================================
[PROB]
QSP model of the acute respiratory distress syndrome. Couples (1) a
DAMP/NF-kB-driven cytokine and neutrophil injury cascade, (2) failure and
repair of the alveolar epithelial and pulmonary endothelial barriers with an
explicit surfactant and AT2-progenitor pool, (3) a Starling lung-water balance
with alveolar fluid clearance, (4) a respiratory-mechanics layer in which the
aerated "baby lung" sets compliance, driving pressure, strain and mechanical
power for whatever the ventilator is set to, (5) a VILI feedback that returns
mechanical energy to the inflammatory cascade as biotrauma, and (6) shunt /
dead-space gas exchange with right-ventricular consequences — to the
pharmacology of corticosteroids, neuromuscular blockade, inhaled pulmonary
vasodilators, IL-6 receptor blockade, JAK inhibition and diuretics, and to the
non-pharmacological interventions (low tidal volume, PEEP, prone position,
conservative fluids, VV-ECMO) that actually carry the mortality signal.

[PLUGIN] Rcpp

[SET] end = 672, delta = 1

[GLOBAL]
// ---------------------------------------------------------------------------
// Back-calculated constants shared between [MAIN], [ODE] and [TABLE]. They are
// solved in [MAIN] from the presenting phenotype so that the initial condition
// is the one that actually reproduces the presenting PaO2/FiO2.
// ---------------------------------------------------------------------------
double KIN_TNF;     // TNF-a production per unit NF-kB (holds TNF0)
double KIN_IL1;     // IL-1b production per unit NF-kB
double KIN_IL6;     // IL-6 production per unit NF-kB
double KIN_IL8;     // IL-8 production per unit NF-kB
double KIN_IL10;    // IL-10 production
double KIN_ANG2;    // Ang-2 release scaling
double KIN_PAI;     // PAI-1 production scaling
double NFKB0;       // NF-kB activity supporting the presenting cytokine profile
double AER_INIT;    // aerated fraction reproducing PF0
double SHUNT_INIT;  // shunt fraction reproducing PF0
double EVLW_INIT;   // lung water reproducing the flooding share of PF0
double SURF_INIT;   // surfactant pool reproducing the atelectatic share
double EPI_INIT;    // epithelial integrity consistent with that lung water
double ENDO_INIT;   // endothelial integrity consistent with that lung water
double SEV0;        // 0-1 composite presenting severity (drives the biology)

// ---------------------------------------------------------------------------
// ARDS_PHYSIO() — the algebraic respiratory-physiology layer.
//
// Expanded verbatim inside [ODE] and inside [TABLE] so that the mechanics the
// solver integrates against and the mechanics that are reported are, by
// construction, the same code. Parameters and compartments are in scope at
// both expansion sites.
//
// Order of derivation:
//   lung water + surfactant + PEEP -> aerated fraction -> compliance ->
//   driving pressure / plateau -> spontaneous effort (P-SILI) -> effective
//   tidal volume -> strain, mechanical power -> shunt and dead space ->
//   PaO2/FiO2, PaCO2, pH -> PVR and cardiac output -> alveolar fluid
//   clearance and transvascular filtration.
// ---------------------------------------------------------------------------
#define ARDS_PHYSIO()                                                          \
  double pronef  = (PRONE_H > 0.0) ? (PRONE_H / 24.0) : 0.0;                   \
  double vt_kg   = (ECMO > 0.5) ? VT_ECMO : VT_KG;                             \
  double rr_set  = (ECMO > 0.5) ? RR_ECMO : RR;                                \
  double vt_set  = vt_kg * PBW;                                                \
  double edema   = fmax(0.0, EVLW - EVLW_DRY);                                 \
  double ned     = (edema / (edema + K_ED)) * (1.0 - PRONE_ED * pronef);       \
  double natel_p = (1.0 - SURF) * ATEL_MAX;                                    \
  double peep_rel= RECRUIT * PEEP / (PEEP + P50_PEEP);                         \
  double natel   = natel_p * (1.0 - peep_rel) * (1.0 - PRONE_AT * pronef);     \
  double aer     = fmax(0.05, fmin(1.0, (1.0 - ned) * (1.0 - natel)));         \
  double crs     = fmax(8.0, CRS0 * aer / (1.0 + KFIB_CRS * COLL));            \
  double eelv    = aer * FRC0 * (1.0 + 0.030 * (PEEP - 5.0));                  \
  double dp_set  = vt_set / fmax(3.0, crs);                                    \
  double vdvt0   = fmin(0.85, VD0 + KVD_T * FIBA / (FIBA + 1.0)                \
                              + KVD_A * (1.0 - aer));                          \
  double va0     = fmax(0.30, rr_set * (vt_set / 1000.0) * (1.0 - vdvt0));     \
  double vco2    = VCO2 * (1.0 - 0.15 * NMB) * (1.0 + 0.25 * fmin(1.0, PATH)); \
  double pco2_0  = 0.863 * vco2 / va0;                                         \
  double sh_pre  = (1.0 - aer) * (1.0 - HPV0 * (1.0 - KHPV_INF                 \
                     * (IL6 / (IL6 + 400.0))));                                \
  double pf_pre  = PF_MAX * exp(-KSH * fmin(0.80, sh_pre));                    \
  double drive   = DRIVE_GAIN * (fmax(0.0, (220.0 - pf_pre)) / 220.0           \
                     + fmax(0.0, pco2_0 - 45.0) / 25.0);                       \
  double effort  = fmax(0.0, drive * (1.0 - NMB) * (1.0 - SEDATION)            \
                     * (1.0 - 0.60 * ECMO));                                   \
  double vt_eff  = vt_set * (1.0 + EFF_GAIN * effort);                         \
  double dp      = vt_eff / fmax(3.0, crs);                                    \
  double pplat   = PEEP + dp;                                                  \
  double ppeak   = pplat + RAW_P;                                              \
  double strain  = vt_eff / fmax(120.0, eelv);                                 \
  double mpow    = 0.098 * rr_set * (vt_eff / 1000.0) * (ppeak - 0.5 * dp);    \
  double noeff   = EMAX_NO * VDIL / (VDIL + EC50_NO);                          \
  double shunt   = fmin(0.80, fmax(0.02, sh_pre * (1.0 - KNO_SH * noeff)));    \
  double vdvt    = fmin(0.85, VD0 + KVD_T * FIBA / (FIBA + 1.0)                \
                              + KVD_A * (1.0 - aer));                          \
  double va      = fmax(0.30, rr_set * (vt_eff / 1000.0) * (1.0 - vdvt));      \
  double paco2   = 0.863 * vco2 / va;                                          \
  double pf_vent = PF_MAX * exp(-KSH * shunt - KDIFF * edema / (edema + 20.0));\
  double pf      = pf_vent + ECMO * ECMO_PF * (1.0 - 0.5 * shunt);             \
  double phv     = 7.40 - 0.0085 * (paco2 - 40.0) - 0.010 * SOFA;              \
  double pvr     = PVR0 * (1.0 + KPVR_HYP * fmax(0.0, 150.0 - pf) / 150.0      \
                     + KPVR_CO2 * fmax(0.0, paco2 - 45.0) / 15.0               \
                     + KPVR_THR * FIBA / (FIBA + 1.0)                          \
                     + KPVR_P * fmax(0.0, pplat - 25.0) / 8.0)                 \
                   * (1.0 - KNO_PVR * noeff) * (1.0 - PRONE_RV * pronef);      \
  double rvload  = fmax(0.0, pvr / PVR0 - 1.6);                                \
  double co      = CO0 / (1.0 + KCO_RV * rvload);                              \
  double perm    = fmin(PERM_MAX,                                              \
                     1.0 + KPERM_E * (1.0 - ENDO) + KPERM_P * (1.0 - EPI));    \
  double pcap    = PCAP0 + KPC_FL * FLUID + 1.2 * rvload;                      \
  double gc_eff  = GRE;                                                        \
  double afc     = AFC0 * EPI * (1.0 + KGC_AFC * gc_eff)                       \
                     * (1.0 + KB2_AFC * BETA2) * (1.0 - 0.35 * fmin(1.0, ROS));\
  double filt    = KF0 * perm * (pcap / PCAP0)                                 \
                     * fmax(0.0, 1.0 - EVLW / EVLW_MAX);                       \
  double il6sig  = IL6 / (1.0 + TCZ / KD_TCZ) * (1.0 - 0.40 * BARI);           \
  double pf_use  = fmin(500.0, pf);

[PARAM] @annotated
//--------------------------------------------------------------------------
// Presenting patient / phenotype descriptors  (the "virtual patient")
//--------------------------------------------------------------------------
PF0        : 130  : mmHg, PaO2/FiO2 at enrolment (Berlin: <=100 severe, <=200 moderate)
PBW        : 60   : kg, predicted body weight (sets every mL/kg dose of ventilation)
DIRECT     : 0.5  : 0-1, direct (pulmonary, epithelial-first) vs indirect (endothelial-first) insult
HYPER      : 0    : 1 = hyperinflammatory latent class (Calfee); 0 = hypoinflammatory
INSULT0    : 1.0  : au, presenting insult / pathogen burden
KCLR_P     : 0.020: 1/h, insult clearance (source control + antimicrobials)
RECRUIT    : 0.60 : 0-1, lung recruitability (high in indirect / non-focal ARDS)
ANTIOX     : 1.0  : relative antioxidant reserve (0.6 = chronic alcohol / smoking)
AGE_RISK   : 1.0  : multiplier on the baseline mortality hazard (age, comorbidity)

//--------------------------------------------------------------------------
// Ventilator settings and non-pharmacological interventions
//--------------------------------------------------------------------------
VT_KG      : 6.0  : mL/kg PBW, set tidal volume (ARMA: 6 protective vs 12 conventional)
PEEP       : 12   : cmH2O, positive end-expiratory pressure
RR         : 25   : /min, set respiratory rate
FIO2       : 0.7  : fraction, inspired oxygen
SEDATION   : 0.5  : 0-1, sedation depth (1 = deep, suppresses spontaneous effort)
PRONE_H    : 0    : h/day, hours proned per day (PROSEVA protocol = 16)
ECMO       : 0    : 1 = VV-ECMO with ultraprotective settings
VT_ECMO    : 3.0  : mL/kg PBW, tidal volume once on ECMO
RR_ECMO    : 10   : /min, respiratory rate once on ECMO
ECMO_PF    : 110  : mmHg, arterial oxygenation added by the extracorporeal circuit
FLUID_IN   : 125  : mL/h, net fluid intake (liberal ~125, conservative ~60)
BETA2      : 0    : 1 = inhaled beta2-agonist (BALTI-2; AFC effect without outcome benefit)
BARI       : 0    : 1 = baricitinib 4 mg/day (JAK1/2 inhibition, COVID-ARDS)
MOBILISE   : 0.3  : 0-1, early mobilisation intensity (ABCDEF bundle)

//--------------------------------------------------------------------------
// Mechanics
//--------------------------------------------------------------------------
CRS0       : 85   : mL/cmH2O, compliance of the fully aerated lung
FRC0       : 2200 : mL, end-expiratory lung volume of the fully aerated lung at PEEP 5
K_ED       : 9.0  : mL/kg, lung water producing half-maximal flooding of alveoli
EVLW_DRY   : 7.0  : mL/kg PBW, normal extravascular lung water
ATEL_MAX   : 0.75 : fraction, maximal atelectatic share at zero surfactant function
P50_PEEP   : 7.0  : cmH2O, PEEP producing half-maximal recruitment
PRONE_ED   : 0.28 : fraction, redistribution of flooding by prone position
PRONE_AT   : 0.50 : fraction, dorsal de-atelectasis by prone position
PRONE_RV   : 0.15 : fraction, RV afterload relief in prone position
PRONE_HOM  : 0.55 : fraction, homogenisation of regional stress/strain in prone position
KFIB_CRS   : 0.030: per unit collagen, stiffening of the lung by fibroproliferation
RAW_P      : 7.0  : cmH2O, resistive pressure drop (Ppeak - Pplat)
DRIVE_GAIN : 1.0  : gain of the respiratory drive from hypoxaemia and hypercapnia
EFF_GAIN   : 0.55 : fractional increase in delivered tidal volume per unit effort (P-SILI)
VCO2       : 200  : mL/min, CO2 production

//--------------------------------------------------------------------------
// Gas exchange
//--------------------------------------------------------------------------
PF_MAX     : 500  : mmHg, PaO2/FiO2 of the shunt-free lung
KSH        : 2.70 : per unit shunt, exponential decay of PaO2/FiO2 (Riley-calibrated)
KDIFF      : 0.35 : maximal fractional oxygenation penalty from barrier thickening
HPV0       : 0.45 : fraction of perfusion diverted from non-aerated lung by intact HPV
KHPV_INF   : 0.65 : fractional blunting of HPV at saturating inflammation
VD0        : 0.30 : baseline dead-space fraction
KVD_T      : 0.16 : dead space added by capillary microthrombosis
KVD_A      : 0.25 : dead space added by loss of aerated lung

//--------------------------------------------------------------------------
// Lung water / Starling balance
//--------------------------------------------------------------------------
KF0        : 0.330: mL/kg/h, filtration of the intact barrier at normal Pcap
KPERM_E    : 4.0  : permeability gain per unit endothelial integrity lost
KPERM_P    : 2.0  : permeability gain per unit epithelial integrity lost
PERM_MAX   : 8.0  : ceiling on the permeability multiplier (fully denuded barrier)
EVLW_MAX   : 35.0 : mL/kg PBW, alveolar flooding capacity of the lung
PCAP0      : 10.0 : mmHg, reference pulmonary capillary pressure
KPC_FL     : 0.5  : mmHg per L of cumulative positive fluid balance
AFC0       : 0.120: 1/h, alveolar fluid clearance of the intact epithelium (12%/h)
KLYM       : 0.070: 1/h, lymphatic clearance of interstitial oedema
KGC_AFC    : 0.55 : fractional increase in AFC at full glucocorticoid effect
KB2_AFC    : 0.25 : fractional increase in AFC with a beta2-agonist

//--------------------------------------------------------------------------
// Inflammatory cascade
//--------------------------------------------------------------------------
KD_PATH    : 0.55 : DAMP release per unit insult per h
KD_VILI    : 0.75 : DAMP release per unit VILI burden per h
KD_EPI     : 0.60 : DAMP release per unit epithelial integrity lost per h
KD_NET     : 0.25 : DAMP release from NETs per h
KDC        : 0.150: 1/h, DAMP clearance
KNF        : 0.300: NF-kB activation per unit DAMP per h
KNFO       : 0.300: 1/h, NF-kB deactivation
KBIO       : 0.80 : biotrauma gain — VILI burden entering NF-kB directly
IMAX_GC    : 0.70 : maximal fractional NF-kB suppression by glucocorticoid
KOUT_TNF   : 0.350: 1/h, TNF-a elimination
KOUT_IL1   : 0.200: 1/h, IL-1b elimination
KOUT_IL6   : 0.150: 1/h, IL-6 elimination
KOUT_IL8   : 0.200: 1/h, IL-8 elimination
KOUT_IL10  : 0.250: 1/h, IL-10 elimination
KNLRP      : 1.20 : inflammasome amplification of IL-1b at saturating DAMP
KREC_N     : 0.075: 1/h, alveolar neutrophil recruitment at saturating IL-8
K8_50      : 120  : pg/mL, IL-8 producing half-maximal neutrophil recruitment
KGC_REC    : 0.55 : fractional suppression of neutrophil recruitment by glucocorticoid
KEFF_N     : 0.045: 1/h per unit M2, efferocytic clearance of alveolar neutrophils
KDN        : 0.015: 1/h, spontaneous neutrophil disappearance
KNET       : 0.055: 1/h, NETosis per unit alveolar neutrophil
KNETC      : 0.100: 1/h, NET/elastase clearance
KROS       : 0.090: 1/h, oxidant generation per unit neutrophil
KHYPEROX   : 0.60 : oxidant generation from FiO2 above 0.6
KROSC      : 0.220: 1/h, oxidant scavenging per unit antioxidant reserve
KM1        : 0.030: 1/h, M1 macrophage programming per unit DAMP+insult
KSWITCH    : 0.022: 1/h, M1 -> M2 phenotype switch at low DAMP
KM2B       : 0.020: 1/h, IL-10-driven M2 programming
KMOUT      : 0.015: 1/h, macrophage pool turnover

//--------------------------------------------------------------------------
// Barrier injury and repair
//--------------------------------------------------------------------------
KI_NET     : 0.055: 1/h, epithelial injury per unit NET burden
KI_ROS     : 0.045: 1/h, epithelial injury per unit oxidant burden
KI_VILI    : 0.045: 1/h, epithelial injury per unit VILI burden
KI_PATH    : 0.030: 1/h, direct epithelial injury by the insult
KREP_E     : 0.150: 1/h, epithelial repair per unit AT2 progenitor pool
KP2        : 0.030: 1/h, AT2 progenitor self-renewal
KL2        : 0.022: 1/h, AT2 progenitor loss per unit injury
KTGF_AT2   : 0.60 : fractional block of AT2 renewal at saturating TGF-b (basaloid arrest)
KS_SURF    : 0.045: 1/h, surfactant resynthesis per unit AT2 pool
KSI_PROT   : 0.070: 1/h, surfactant inactivation by alveolar protein
KSI_ROS    : 0.030: 1/h, surfactant inactivation by oxidants
KEREP      : 0.090: 1/h, endothelial repair
KE_TNF     : 0.060: 1/h, endothelial injury at saturating TNF-a
KE_NET     : 0.050: 1/h, endothelial injury per unit NET burden
KE_VILI    : 0.035: 1/h, endothelial injury per unit VILI burden
KE_ANG2    : 0.045: 1/h, endothelial injury at saturating Ang-2
KOUT_ANG2  : 0.080: 1/h, Ang-2 clearance
KOUT_PAI   : 0.030: 1/h, PAI-1 clearance
KFIB_IN    : 0.030: 1/h, alveolar fibrin deposition per unit PAI-1-weighted thrombin drive
KFIB_OUT   : 0.012: 1/h, fibrinolysis of alveolar fibrin

//--------------------------------------------------------------------------
// VILI
//--------------------------------------------------------------------------
KV_STRAIN  : 0.020: VILI generation per (strain - threshold)^2 per h
STRAIN_TH  : 0.90 : threshold global strain above which volutrauma begins
KV_DP      : 0.006: VILI generation per (driving pressure - 14)^2/100 per h
KV_ATEL    : 0.020: VILI generation from cyclic opening and closing per h
KV_POWER   : 0.006: VILI generation per (mechanical power - 12)/10 per h
KVOUT      : 0.030: 1/h, resolution of the VILI burden

//--------------------------------------------------------------------------
// Fibroproliferation
//--------------------------------------------------------------------------
KTGF       : 0.045: 1/h, TGF-b1 activation by epithelial injury and inflammation
KOUT_TGF   : 0.050: 1/h, TGF-b1 turnover
KGC_TGF    : 0.45 : fractional suppression of TGF-b1 by glucocorticoid
KCOLL      : 0.012: 1/h, collagen deposition per unit TGF-b1
KOUT_COLL  : 0.004: 1/h, collagen turnover

//--------------------------------------------------------------------------
// Systemic organ failure, hazard and outcome
//--------------------------------------------------------------------------
KS_IN      : 0.090: 1/h, non-pulmonary organ dysfunction accrual
KS_OUT     : 0.030: 1/h, organ recovery
H0         : 0.000759: 1/h, baseline hazard of an intubated ARDS patient (ARMA-calibrated)
B_PF       : 0.90 : hazard weight on hypoxaemia below PaO2/FiO2 200
B_DP       : 0.40 : hazard weight per 5 cmH2O of driving pressure above 14
B_MP       : 0.28 : hazard weight per 10 J/min of mechanical power above 15
B_VD       : 0.45 : hazard weight per 0.1 of dead-space fraction above 0.5
B_SOFA     : 1.30 : hazard weight on non-pulmonary SOFA
B_VILI     : 0.44 : hazard weight on the cumulative VILI burden
B_FIB      : 0.30 : hazard weight on fibroproliferation
KW_IN      : 0.012: 1/h, ICU-acquired weakness accrual
KW_OUT     : 0.004: 1/h, weakness recovery with mobilisation
KGLU       : 45   : mg/dL, glucose rise at full glucocorticoid effect
KGLU_OUT   : 0.10 : 1/h, glucose homeostasis

//--------------------------------------------------------------------------
// Drug PK / PD
//--------------------------------------------------------------------------
V_DEX      : 60   : L, dexamethasone volume of distribution
CL_DEX     : 12.0 : L/h, dexamethasone clearance (t1/2 ~3.5 h)
POT_DEX    : 1.00 : relative glucocorticoid potency (reference)
V_MP       : 100  : L, methylprednisolone volume of distribution
CL_MP      : 25.0 : L/h, methylprednisolone clearance (t1/2 ~2.8 h)
POT_MP     : 0.19 : relative glucocorticoid potency vs dexamethasone (5.3:1)
KIN_GRE    : 0.075: 1/h, glucocorticoid genomic effect onset
KOUT_GRE   : 0.058: 1/h, glucocorticoid genomic effect offset (t1/2 ~12 h)
EC50_GC    : 0.020: mg/L dexamethasone-equivalent, half-maximal receptor occupancy
V_CIS      : 10.5 : L, cisatracurium volume of distribution
CL_CIS     : 20.0 : L/h, cisatracurium Hofmann + ester clearance (t1/2 ~22 min)
KEO_NMB    : 6.0  : 1/h, neuromuscular block equilibration
EC50_CIS   : 0.10 : mg/L, cisatracurium producing half-maximal block
NO_PPM     : 0    : ppm, inhaled nitric oxide / epoprostenol equivalent
KIN_NO     : 6.0  : 1/h, inhaled vasodilator effect-site equilibration
KOUT_NO    : 6.0  : 1/h, inhaled vasodilator washout (minutes)
EMAX_NO    : 0.85 : maximal inhaled-vasodilator effect
EC50_NO    : 8.0  : ppm-equivalent producing half-maximal effect
KNO_SH     : 0.30 : maximal fractional shunt reduction by inhaled vasodilator
KNO_PVR    : 0.28 : maximal fractional PVR reduction by inhaled vasodilator
V_TCZ      : 4.0  : L, tocilizumab central volume
KEL_TCZ    : 0.0024: 1/h, tocilizumab elimination (t1/2 ~12 days)
KD_TCZ     : 1.0  : mg/L, tocilizumab concentration halving IL-6 signalling
V_FUR      : 15.0 : L, furosemide volume of distribution
CL_FUR     : 8.0  : L/h, furosemide clearance
EMAX_FUR   : 260  : mL/h, maximal additional urine output
EC50_FUR   : 0.50 : mg/L, furosemide producing half-maximal diuresis
UO_BASE    : 70   : mL/h, baseline urine output
KUO_FL     : 0.16 : fractional rise in urine output per L of positive fluid balance

//--------------------------------------------------------------------------
// Right heart / haemodynamics
//--------------------------------------------------------------------------
PVR0       : 150  : dyn.s.cm-5, baseline pulmonary vascular resistance
KPVR_HYP   : 1.20 : PVR gain from hypoxaemia
KPVR_CO2   : 0.50 : PVR gain per 15 mmHg of hypercapnia
KPVR_THR   : 0.80 : PVR gain from capillary microthrombosis
KPVR_P     : 0.40 : PVR gain per 8 cmH2O of plateau pressure above 25
CO0        : 5.5  : L/min, cardiac output without RV loading
KCO_RV     : 0.45 : fractional fall in cardiac output per unit RV overload

//--------------------------------------------------------------------------
// Secondary infection (the price of immunosuppression)
//--------------------------------------------------------------------------
KSEC       : 0.0130: 1/h, secondary-infection seeding at full glucocorticoid effect
T_SEC      : 168  : h, time after which immunosuppression starts to seed infection

[INIT] @annotated
DEX   : 0    : mg, dexamethasone in the central compartment
MPRED : 0    : mg, methylprednisolone in the central compartment
GRE   : 0    : 0-1, glucocorticoid genomic effect
CIS   : 0    : mg, cisatracurium in the central compartment
NMB   : 0    : 0-1, depth of neuromuscular block
VDIL  : 0    : ppm-eq, inhaled vasodilator at the effect site
TCZ   : 0    : mg/L, tocilizumab concentration
FUR   : 0    : mg, furosemide in the central compartment
PATH  : 1    : au, insult / pathogen burden
DAMP  : 1    : au, DAMP pool
NFKB  : 1    : au, NF-kB activity
TNF   : 30   : pg/mL, TNF-alpha
IL1B  : 25   : pg/mL, IL-1beta
IL6   : 400  : pg/mL, IL-6
IL8   : 150  : pg/mL, IL-8
IL10  : 30   : pg/mL, IL-10
NEUTA : 0.5  : au, alveolar neutrophil burden
NETS  : 0.3  : au, NET / elastase burden
ROS   : 0.3  : au, oxidant burden
M1    : 0.5  : au, M1 macrophage programme
M2    : 0.1  : au, M2 macrophage programme
EPI   : 0.7  : 0-1, alveolar epithelial integrity
AT2P  : 0.85 : 0-1, AT2 progenitor pool
SURF  : 0.6  : 0-1, functional surfactant pool
ENDO  : 0.7  : 0-1, pulmonary endothelial integrity
ANG2  : 8    : ng/mL, angiopoietin-2
PAI1  : 40   : ng/mL, plasminogen activator inhibitor-1
FIBA  : 0.5  : au, alveolar fibrin / capillary microthrombus burden
EVLW  : 14   : mL/kg PBW, extravascular lung water
FLUID : 0    : L, cumulative fluid balance
VILI  : 0    : au, cumulative ventilator-induced lung injury burden
TGFB  : 1    : au, active TGF-beta1
COLL  : 0    : au, collagen / fibroproliferation
SOFA  : 4    : points, non-pulmonary SOFA score
HAZ   : 0    : cumulative mortality hazard
WEAK  : 0    : au, ICU-acquired weakness burden
GLU   : 130  : mg/dL, blood glucose
VFD   : 0    : days, accumulated time free of the ventilator

[MAIN]
if (NEWIND <= 1) {

  //------------------------------------------------------------------------
  // 1. Composite presenting severity from the Berlin PaO2/FiO2 class.
  //------------------------------------------------------------------------
  SEV0 = fmin(1.0, fmax(0.05, (300.0 - PF0) / 240.0));   // PF 300 -> 0, PF 60 -> 1

  //------------------------------------------------------------------------
  // 2. Presenting inflammatory profile by latent class, scaled by severity.
  //    This is solved BEFORE the gas-exchange inversion because inflammation
  //    is what blunts hypoxic pulmonary vasoconstriction, and HPV is what
  //    decides how much of the non-aerated lung actually shunts.
  //------------------------------------------------------------------------
  double sevf = 0.55 + 0.90 * SEV0;
  double tnf0 = (HYPER > 0.5 ?   55.0 : 14.0) * sevf;
  double il60 = (HYPER > 0.5 ? 1600.0 : 190.0) * sevf;
  double il80 = (HYPER > 0.5 ?  340.0 :  75.0) * sevf;
  double il1s = (HYPER > 0.5 ?   45.0 :  12.0) * sevf;
  double i100 = (HYPER > 0.5 ?   75.0 :  22.0) * sevf;
  double ang0 = (HYPER > 0.5 ?   16.0 :   7.0) * sevf;
  double pai0 = (HYPER > 0.5 ?  120.0 :  40.0) * sevf;

  //------------------------------------------------------------------------
  // 3. Invert gas exchange: what shunt, and therefore what aerated fraction,
  //    reproduces the presenting PaO2/FiO2 at the enrolment settings? The
  //    diffusion penalty depends on lung water, which depends on the aerated
  //    fraction, so the inversion is iterated to a fixed point.
  //------------------------------------------------------------------------
  double hpv_eff  = HPV0 * (1.0 - KHPV_INF * il60 / (il60 + 400.0));
  double lpf      = -log(fmin(0.98, PF0 / PF_MAX));
  double ned0 = 0.0;
  double natel0 = 0.0;
  double edema_i = 0.0;
  double prel = RECRUIT * PEEP / (PEEP + P50_PEEP);
  double flood_shr = 0.45 + 0.30 * DIRECT;               // consolidation share

  double natel_max = fmax(0.05, ATEL_MAX * (1.0 - prel));
  for (int itg = 0; itg < 10; ++itg) {
    double diffpen = KDIFF * edema_i / (edema_i + 20.0);
    SHUNT_INIT = fmin(0.80, fmax(0.03, (lpf - diffpen) / KSH));
    AER_INIT   = fmax(0.05, fmin(0.98,
                   1.0 - SHUNT_INIT / fmax(0.20, 1.0 - hpv_eff)));
    // Take the atelectatic share first, capped by what a surfactant pool of
    // zero can physically produce at this PEEP, and make up the remainder of
    // the non-aerated lung with flooding. Solving in this order guarantees the
    // inversion closes for every PaO2/FiO2 instead of silently hitting a floor
    // and returning a patient who is less hypoxaemic than the one requested.
    natel0  = fmin(0.95 * natel_max, (1.0 - AER_INIT) * (1.0 - flood_shr));
    ned0    = fmin(0.93, fmax(0.0, 1.0 - AER_INIT / fmax(0.05, 1.0 - natel0)));
    edema_i = K_ED * ned0 / fmax(0.02, 1.0 - ned0);
  }
  EVLW_INIT = fmin(0.95 * EVLW_MAX, EVLW_DRY + edema_i);
  SURF_INIT = fmax(0.05, fmin(1.0, 1.0 - natel0 / natel_max));

  //------------------------------------------------------------------------
  // 4. Fixed-point solve for the barrier integrities that hold that lung
  //    water: the permeability required is the one whose filtration exactly
  //    balances clearance at EVLW_INIT. The epithelial/endothelial split
  //    follows the direct/indirect injury pattern.
  //------------------------------------------------------------------------
  double edema0 = fmax(0.0, EVLW_INIT - EVLW_DRY);
  double head   = fmax(0.05, 1.0 - EVLW_INIT / EVLW_MAX);  // flooding-capacity term
  double epi_i  = 1.0 - 0.55 * SEV0;
  double endo_i = 1.0 - 0.50 * SEV0;
  for (int itb = 0; itb < 12; ++itb) {
    double clr      = (AFC0 * epi_i + KLYM) * edema0;              // mL/kg/h out
    double perm_req = fmax(1.0, clr / fmax(1e-6, KF0 * head));     // Pcap = PCAP0 at t0
    double lost     = fmax(0.0, perm_req - 1.0);                   // KPERM_E*(1-ENDO)+KPERM_P*(1-EPI)
    // split the required permeability loss between the two barriers
    double w_epi    = 0.30 + 0.45 * DIRECT;                        // direct insult -> epithelium
    double d_epi    = fmin(0.80, lost * w_epi / KPERM_P);
    double d_endo   = fmin(0.80, lost * (1.0 - w_epi) / KPERM_E);
    epi_i  = fmax(0.15, 1.0 - d_epi);
    endo_i = fmax(0.15, 1.0 - d_endo);
  }
  EPI_INIT  = epi_i;
  ENDO_INIT = endo_i;

  //------------------------------------------------------------------------
  // 5. Back-calculate the cytokine production constants so that the presenting
  //    profile of section 2 is stationary for the NF-kB activity that the
  //    presenting DAMP load supports — the profile then evolves only because
  //    the biology (insult clearance, VILI, drugs) makes it evolve.
  //------------------------------------------------------------------------
  double damp0 = KD_PATH * INSULT0 / KDC + KD_EPI * (1.0 - EPI_INIT) / KDC;
  NFKB0        = fmax(0.10, KNF * damp0 / KNFO);

  double m10   = KM1 * (0.6 * INSULT0 + 0.4 * damp0) / (KSWITCH * 0.5 + KMOUT);
  KIN_TNF  = tnf0 * KOUT_TNF  / fmax(0.05, NFKB0 * (1.0 + 0.5 * m10));
  KIN_IL1  = il1s * KOUT_IL1  / fmax(0.05, NFKB0 * (1.0 + KNLRP * damp0 / (damp0 + 5.0)));
  KIN_IL6  = il60 * KOUT_IL6  / fmax(0.05, NFKB0 * (1.0 + 0.4 * m10));
  KIN_IL8  = il80 * KOUT_IL8  / fmax(0.05, NFKB0 * (1.0 + 0.6 * m10));
  KIN_IL10 = i100 * KOUT_IL10 / fmax(0.05, 0.20 * NFKB0 + 0.10);
  KIN_ANG2 = ang0 * KOUT_ANG2 / fmax(0.05,
               tnf0 / (tnf0 + 20.0) + il1s / (il1s + 20.0));
  KIN_PAI  = pai0 * KOUT_PAI  / fmax(0.05,
               il1s / (il1s + 20.0) + tnf0 / (tnf0 + 20.0) + 0.3);

  //------------------------------------------------------------------------
  // 6. Apply the solved baseline.
  //------------------------------------------------------------------------
  PATH_0  = INSULT0;
  DAMP_0  = damp0;
  NFKB_0  = NFKB0;
  TNF_0   = tnf0;
  IL1B_0  = il1s;
  IL6_0   = il60;
  IL8_0   = il80;
  IL10_0  = i100;
  ANG2_0  = ang0;
  PAI1_0  = pai0;
  M1_0    = m10;
  M2_0    = 0.15 * m10;
  NEUTA_0 = KREC_N * (il80 / (il80 + K8_50)) / (KDN + KEFF_N * 0.15 * m10);
  NETS_0  = KNET * NEUTA_0 / KNETC;
  ROS_0   = KROS * NEUTA_0 / (KROSC * ANTIOX);
  EPI_0   = EPI_INIT;
  ENDO_0  = ENDO_INIT;
  SURF_0  = SURF_INIT;
  EVLW_0  = EVLW_INIT;
  AT2P_0  = fmax(0.25, 0.95 - 0.45 * SEV0);
  FIBA_0  = KFIB_IN * (pai0 / 60.0) * (0.5 + SEV0) / KFIB_OUT;
  TGFB_0  = KTGF * (1.0 - EPI_INIT) / KOUT_TGF;
  COLL_0  = 0.0;
  SOFA_0  = (HYPER > 0.5 ? 7.0 : 3.0) * (0.6 + 0.6 * SEV0);
  GLU_0   = 130.0;
  VILI_0  = 0.0;
  FLUID_0 = 0.0;
  HAZ_0   = 0.0;
  WEAK_0  = 0.0;
  VFD_0   = 0.0;
}

[ODE]
ARDS_PHYSIO();

//---------------------------------------------------------------------------
// PK / drug effect
//---------------------------------------------------------------------------
double c_dex = DEX / V_DEX;
double c_mp  = MPRED / V_MP;
double gc_eq = POT_DEX * c_dex + POT_MP * c_mp;          // dexamethasone-equivalent mg/L
double c_cis = CIS / V_CIS;
double c_fur = FUR / V_FUR;

dxdt_DEX   = -CL_DEX / V_DEX * DEX;
dxdt_MPRED = -CL_MP  / V_MP  * MPRED;
dxdt_GRE   =  KIN_GRE * gc_eq / (gc_eq + EC50_GC) - KOUT_GRE * GRE;
dxdt_CIS   = -CL_CIS / V_CIS * CIS;
dxdt_NMB   =  KEO_NMB * (c_cis / (c_cis + EC50_CIS) - NMB);
dxdt_VDIL  =  KIN_NO * NO_PPM - KOUT_NO * VDIL;
dxdt_TCZ   = -KEL_TCZ * TCZ;
dxdt_FUR   = -CL_FUR / V_FUR * FUR;

double gc_sup = 1.0 - IMAX_GC * GRE;                     // NF-kB transrepression

//---------------------------------------------------------------------------
// Insult, DAMPs and NF-kB — with VILI entering as biotrauma
//---------------------------------------------------------------------------
double secinf = (SOLVERTIME > T_SEC) ? KSEC * GRE : 0.0;
dxdt_PATH = -KCLR_P * PATH + secinf;

dxdt_DAMP = KD_PATH * PATH + KD_VILI * VILI / (VILI + 2.0)
            + KD_EPI * (1.0 - EPI) + KD_NET * NETS / (NETS + 1.0) - KDC * DAMP;

dxdt_NFKB = KNF * (DAMP + KBIO * VILI / (VILI + 1.0)) * gc_sup - KNFO * NFKB;

//---------------------------------------------------------------------------
// Cytokines
//---------------------------------------------------------------------------
double inflmm = 1.0 + KNLRP * DAMP / (DAMP + 5.0);

dxdt_TNF  = KIN_TNF  * NFKB * (1.0 + 0.5 * M1) * gc_sup - KOUT_TNF  * TNF;
dxdt_IL1B = KIN_IL1  * NFKB * inflmm            * gc_sup - KOUT_IL1  * IL1B;
dxdt_IL6  = KIN_IL6  * NFKB * (1.0 + 0.4 * M1) * gc_sup - KOUT_IL6  * IL6;
dxdt_IL8  = KIN_IL8  * NFKB * (1.0 + 0.6 * M1) * gc_sup - KOUT_IL8  * IL8;
dxdt_IL10 = KIN_IL10 * (0.20 * NFKB + 0.10 + 0.35 * M2) - KOUT_IL10 * IL10;

//---------------------------------------------------------------------------
// Neutrophils, NETs, oxidants, macrophage programmes
//---------------------------------------------------------------------------
double gcrec = 1.0 - KGC_REC * GRE;

dxdt_NEUTA = KREC_N * (IL8 / (IL8 + K8_50)) * gcrec
             - KEFF_N * M2 * NEUTA - KDN * NEUTA;
dxdt_NETS  = KNET * NEUTA * (1.0 + 0.5 * ROS) - KNETC * NETS;
dxdt_ROS   = KROS * (NEUTA + KHYPEROX * fmax(0.0, FIO2 - 0.6) / 0.4)
             - KROSC * ANTIOX * ROS;

double swtch = 1.0 / (1.0 + DAMP / 2.0);
dxdt_M1 = KM1 * (0.6 * PATH + 0.4 * DAMP) - KSWITCH * swtch * M1 - KMOUT * M1;
dxdt_M2 = KSWITCH * swtch * M1 + KM2B * (IL10 / (IL10 + 30.0)) - KMOUT * M2;

//---------------------------------------------------------------------------
// Barriers: epithelium, AT2 progenitors, surfactant, endothelium
//---------------------------------------------------------------------------
// Injury intensities saturate: a barrier can only be attacked so fast, and
// without saturation any positive feedback in the network runs away.
double einj = KI_NET  * NETS / (NETS + 0.8)
            + KI_ROS  * ROS  / (ROS  + 0.8)
            + KI_VILI * VILI / (VILI + 1.0)
            + KI_PATH * PATH / (PATH + 0.5);

dxdt_EPI  = KREP_E * AT2P * (1.0 - EPI) - einj * EPI;
dxdt_AT2P = KP2 * AT2P * (1.0 - AT2P) * (1.0 - KTGF_AT2 * TGFB / (TGFB + 2.0))
            - KL2 * (0.5 * ROS + 0.5 * NETS + PATH) * AT2P;

double alvprot = (1.0 - EPI) * edema / (edema + 8.0);
dxdt_SURF = KS_SURF * AT2P * (1.0 - SURF)
            - (KSI_PROT * alvprot + KSI_ROS * ROS) * SURF;

dxdt_ENDO = KEREP * (1.0 - ENDO)
            - (KE_TNF  * TNF / (TNF + 20.0)
               + KE_NET  * NETS / (NETS + 0.8)
               + KE_VILI * VILI / (VILI + 1.0)
               + KE_ANG2 * ANG2 / (ANG2 + 10.0)) * ENDO;

dxdt_ANG2 = KIN_ANG2 * (TNF / (TNF + 20.0) + IL1B / (IL1B + 20.0))
            - KOUT_ANG2 * ANG2;
dxdt_PAI1 = KIN_PAI * (IL1B / (IL1B + 20.0) + TNF / (TNF + 20.0)
                       + 0.3 * (1.0 - EPI)) * (1.0 - 0.30 * GRE)
            - KOUT_PAI * PAI1;
dxdt_FIBA = KFIB_IN * (PAI1 / 60.0) * (0.4 + 0.8 * (1.0 - ENDO))
            - KFIB_OUT * FIBA;

//---------------------------------------------------------------------------
// Lung water and fluid balance
//---------------------------------------------------------------------------
dxdt_EVLW = filt - (afc + KLYM) * edema;

// Urine output falls with organ failure but rises with volume expansion —
// without that pressure-natriuresis feedback a fixed intake integrates without
// bound and the capillary pressure term becomes meaningless.
// You cannot diurese fluid the patient does not have: the loop-diuretic
// response is gated by volume state, which is also how the FACTT protocol was
// actually run (furosemide held when the patient was not fluid-overloaded or
// was hypoperfused). Without this gate a fixed diuretic order integrates into
// an impossible negative balance.
double vol_avail = 1.0 / (1.0 + exp(-(FLUID - 1.0) / 0.6));
double uo = UO_BASE * (1.0 - 0.55 * fmin(1.0, SOFA / 10.0))
            * (1.0 + KUO_FL * fmax(0.0, FLUID))
            + EMAX_FUR * c_fur / (c_fur + EC50_FUR) * vol_avail;
dxdt_FLUID = (FLUID_IN - uo) / 1000.0;

//---------------------------------------------------------------------------
// VILI: the ventilator writing back into the biology
//---------------------------------------------------------------------------
// The three mechanical exposures are capped at the highest values a ventilated
// patient is physically taken to; beyond that the lung is already maximally
// injured and the quadratic terms would only produce numerical runaway.
double strain_c = fmin(3.0,  strain);
double dp_c     = fmin(40.0, dp);
double mpow_c   = fmin(60.0, mpow);
double v_str = KV_STRAIN * pow(fmax(0.0, strain_c - STRAIN_TH), 2.0);
double v_dp  = KV_DP     * pow(fmax(0.0, dp_c - 14.0), 2.0) / 100.0;
double v_at  = KV_ATEL   * natel * fmax(0.0, 1.0 - PEEP / 15.0);
double v_pw  = KV_POWER  * fmax(0.0, mpow_c - 12.0) / 10.0;
// Prone position does not only recruit: it makes the stress/strain field more
// homogeneous, which removes the regional stress raisers that turn a tolerable
// global strain into local overdistension.
double homog = 1.0 - PRONE_HOM * pronef;
dxdt_VILI = (v_str + v_dp + v_at + v_pw) * homog * (1.0 - 0.55 * ECMO)
            - KVOUT * VILI;

//---------------------------------------------------------------------------
// Fibroproliferation
//---------------------------------------------------------------------------
dxdt_TGFB = KTGF * ((1.0 - EPI) + 0.4 * IL1B / (IL1B + 30.0) + 0.3 * VILI)
            * (1.0 - KGC_TGF * GRE) - KOUT_TGF * TGFB;
dxdt_COLL = KCOLL * TGFB * (1.0 - KGC_TGF * GRE) - KOUT_COLL * COLL;

//---------------------------------------------------------------------------
// Systemic organ failure, hazard, weakness, glucose, ventilator-free time
//---------------------------------------------------------------------------
dxdt_SOFA = KS_IN * (0.40 * il6sig / (il6sig + 300.0)
                     + 0.30 * fmax(0.0, 150.0 - pf_use) / 150.0
                     + 0.30 * fmin(1.0, rvload)
                     + 0.25 * fmin(1.0, PATH)
                     + 0.20 * fmin(1.0, VILI))
            - KS_OUT * SOFA;

// Liberation from the ventilator: every criterion must be met, so the index is
// a product of logistic gates (oxygenation, mechanics, lung water, shock,
// strength). A patient who satisfies all of them is off the ventilator, and
// the ARDS-attributable hazard is then almost entirely spent — which is why
// the same index gates both the hazard and the ventilator-free-day counter.
// Readiness is judged on what the NATIVE lung can do: for a patient on VV-ECMO
// the arterial PaO2/FiO2 is largely the circuit's work, so decannulation and
// then extubation depend on the ventilator-only oxygenation.
double g_pf   = 1.0 / (1.0 + exp(-(pf_vent - 190.0) / 25.0));
// Readiness is judged at a weaning setting, not at the setting the patient is
// currently on: what matters is the driving pressure a 6 mL/kg breath WOULD
// generate against the compliance the lung now has.
double dp_wean = 6.0 * PBW / fmax(3.0, crs);
double g_dp   = 1.0 / (1.0 + exp(-(14.0 - dp_wean) / 1.5));
double g_evlw = 1.0 / (1.0 + exp(-(12.0 - EVLW) / 1.2));
double g_sofa = 1.0 / (1.0 + exp(-(5.0 - SOFA) / 0.8));
double g_weak = 1.0 / (1.0 + exp(-(2.5 - WEAK) / 0.5));
double wean   = g_pf * g_dp * g_evlw * g_sofa * g_weak;

double hz = H0 * AGE_RISK
            * (1.0 + B_PF   * fmax(0.0, 200.0 - pf_use) / 100.0
                   + B_DP   * fmax(0.0, dp - 14.0) / 5.0
                   + B_MP   * fmax(0.0, mpow - 15.0) / 10.0
                   + B_VD   * fmax(0.0, vdvt - 0.50) / 0.10
                   + B_SOFA * SOFA / 8.0
                   + B_VILI * VILI
                   + B_FIB  * COLL / 20.0);
dxdt_HAZ = hz * (1.0 - 0.85 * wean);

dxdt_WEAK = KW_IN * (0.5 * GRE + 0.5 * NMB + 0.4 * SEDATION + 0.3 * fmin(1.0, SOFA / 8.0))
            - KW_OUT * (1.0 + 2.0 * MOBILISE) * WEAK;

dxdt_GLU = KGLU * GRE * 0.10 - KGLU_OUT * (GLU - 130.0);

dxdt_VFD = wean / 24.0;

[TABLE]
ARDS_PHYSIO();

double surv   = exp(-HAZ);
double berlin = (pf_use > 300.0) ? 0.0 : ((pf_use > 200.0) ? 1.0
                : ((pf_use > 100.0) ? 2.0 : 3.0));       // 0 none 1 mild 2 mod 3 severe

// Murray lung injury score (hypoxaemia + PEEP + compliance + a radiographic
// surrogate taken from the non-aerated fraction)
double m_ox  = (pf_use >= 300.0) ? 0.0 : (pf_use >= 225.0 ? 1.0
               : (pf_use >= 175.0 ? 2.0 : (pf_use >= 100.0 ? 3.0 : 4.0)));
double m_pep = (PEEP <= 5.0) ? 0.0 : (PEEP <= 8.0 ? 1.0
               : (PEEP <= 11.0 ? 2.0 : (PEEP <= 14.0 ? 3.0 : 4.0)));
double m_crs = (crs >= 80.0) ? 0.0 : (crs >= 60.0 ? 1.0
               : (crs >= 40.0 ? 2.0 : (crs >= 20.0 ? 3.0 : 4.0)));
double m_cxr = fmin(4.0, 4.0 * (1.0 - aer));
double murray = (m_ox + m_pep + m_crs + m_cxr) / 4.0;

capture PaO2_FiO2       = pf_use;
capture PaO2_FiO2_vent  = pf_vent;
capture Berlin_class    = berlin;
capture Shunt_fraction  = shunt;
capture DeadSpace_VdVt  = vdvt;
capture PaCO2_mmHg      = paco2;
capture pH_arterial     = phv;
capture Aerated_frac    = aer;
capture Compliance_Crs  = crs;
capture DrivingP_cmH2O  = dp;
capture Plateau_cmH2O   = pplat;
capture MechPower_Jmin  = mpow;
capture Strain_global   = strain;
capture Effort_PSILI    = effort;
capture VT_delivered_ml = vt_eff;
capture EELV_ml         = eelv;
capture Murray_score    = murray;
capture EVLW_mlkg       = EVLW;
capture Permeability    = perm;
capture AFC_per_h       = afc;
capture Fluid_balance_L = FLUID;
capture Epi_integrity   = EPI;
capture Endo_integrity  = ENDO;
capture Surfactant      = SURF;
capture AT2_pool        = AT2P;
capture VILI_burden     = VILI;
capture IL6_pgml        = IL6;
capture IL6_signalling  = il6sig;
capture IL8_pgml        = IL8;
capture IL1b_pgml       = IL1B;
capture TNFa_pgml       = TNF;
capture IL10_pgml       = IL10;
capture Ang2_ngml       = ANG2;
capture PAI1_ngml       = PAI1;
capture Neutrophils_alv = NEUTA;
capture NETs_burden     = NETS;
capture ROS_burden      = ROS;
capture M1_programme    = M1;
capture M2_programme    = M2;
capture Fibrin_alveolar = FIBA;
capture TGFb_active     = TGFB;
capture Collagen        = COLL;
capture SOFA_nonpulm    = SOFA;
capture PVR_dyn         = pvr;
capture CardiacOutput   = co;
capture RV_overload     = rvload;
capture Glucose_mgdl    = GLU;
capture Weakness        = WEAK;
capture GC_effect       = GRE;
capture NMB_depth       = NMB;
capture TCZ_conc        = TCZ;
capture Survival_prob   = surv;
capture Mortality_prob  = 1.0 - surv;
capture VFD_raw         = VFD;
capture VFD_expected    = VFD * surv;
// Guideline / trial-relevant flags
capture LungProtective  = (dp <= 15.0 && pplat <= 30.0) ? 1.0 : 0.0;
capture Severe_ARDS     = (pf_use <= 100.0) ? 1.0 : 0.0;
capture AcuteCorPulm    = (rvload > 0.35) ? 1.0 : 0.0;
capture Hyperglycaemia  = (GLU > 180.0) ? 1.0 : 0.0;

[CAPTURE]
PaO2_FiO2 PaO2_FiO2_vent Berlin_class Shunt_fraction DeadSpace_VdVt PaCO2_mmHg
pH_arterial Aerated_frac Compliance_Crs DrivingP_cmH2O Plateau_cmH2O
MechPower_Jmin Strain_global Effort_PSILI VT_delivered_ml EELV_ml Murray_score
EVLW_mlkg Permeability AFC_per_h Fluid_balance_L
Epi_integrity Endo_integrity Surfactant AT2_pool VILI_burden
IL6_pgml IL6_signalling IL8_pgml IL1b_pgml TNFa_pgml IL10_pgml Ang2_ngml
PAI1_ngml Neutrophils_alv NETs_burden ROS_burden M1_programme M2_programme
Fibrin_alveolar TGFb_active Collagen SOFA_nonpulm PVR_dyn CardiacOutput
RV_overload Glucose_mgdl Weakness GC_effect NMB_depth TCZ_conc
Survival_prob Mortality_prob VFD_raw VFD_expected
LungProtective Severe_ARDS AcuteCorPulm Hyperglycaemia

##  ============================================================================
##  R-side scenario helpers (documentation for users; not parsed by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(ggplot2)
##  mod <- mread_cache("ards", project = ".")   # file: ards_mrgsolve_model.R
##
##  ---------------------------------------------------------------------------
##  Dose-unit conventions
##  ---------------------------------------------------------------------------
##    DEX    amt in mg   IV bolus dexamethasone   (DEXA-ARDS: 20 mg d1-5, 10 mg d6-10)
##    MPRED  amt in mg   IV methylprednisolone    (e.g. 1 mg/kg/day = 60 mg)
##    CIS    rate mg/h   cisatracurium infusion   (ACURASYS: 37.5 mg/h for 48 h)
##    TCZ    amt in mg   tocilizumab              (8 mg/kg = 480 mg into V_TCZ = 4 L)
##    FUR    amt in mg   furosemide               (FACTT: 20 mg q6h when perfused)
##    Inhaled vasodilator is a PARAMETER, not a dose: param(NO_PPM = 20).
##
##  Non-pharmacological interventions are parameters as well, because that is
##  what they are physically — a change of ventilator setting or body position:
##    LTVV                : VT_KG = 6,  PEEP = 12, RR = 28
##    Conventional 1990s  : VT_KG = 12, PEEP = 8,  RR = 16
##    Higher PEEP         : PEEP = 16
##    Prone (PROSEVA)     : PRONE_H = 16
##    Deep sedation       : SEDATION = 0.9   (light sedation, ROSE: 0.35)
##    Conservative fluids : FLUID_IN = 60  + furosemide dosing
##    VV-ECMO             : ECMO = 1  (forces VT_ECMO / RR_ECMO)
##
##  ---------------------------------------------------------------------------
##  14 prebuilt scenarios
##  ---------------------------------------------------------------------------
##  ARDS_simulate_scenarios <- function(end_h = 672) {
##
##    ## the reference patient: moderate-severe ARDS from pneumonia,
##    ## PaO2/FiO2 130, hypoinflammatory class, PBW 60 kg
##    base <- list(PF0 = 130, PBW = 60, DIRECT = 0.8, HYPER = 0, RECRUIT = 0.55)
##
##    ltvv <- list(VT_KG = 6,  PEEP = 12, RR = 28, SEDATION = 0.5)
##    conv <- list(VT_KG = 12, PEEP = 8,  RR = 16, SEDATION = 0.5)
##
##    run <- function(p, ev = NULL, ...) {
##      m <- mod %>% param(c(base, p, list(...)))
##      if (is.null(ev)) m %>% mrgsim(end = end_h, delta = 1)
##      else             m %>% mrgsim(events = ev, end = end_h, delta = 1)
##    }
##
##    ## dexamethasone 20 mg IV daily x5 then 10 mg daily x5 (DEXA-ARDS)
##    dexa <- c(ev(amt = 20, cmt = "DEX", ii = 24, addl = 4, time = 0),
##              ev(amt = 10, cmt = "DEX", ii = 24, addl = 4, time = 120))
##    ## cisatracurium 37.5 mg/h for 48 h (ACURASYS)
##    cisa <- ev(amt = 1800, rate = 37.5, cmt = "CIS", time = 0)
##    ## tocilizumab 8 mg/kg once (480 mg for 60 kg)
##    tocz <- ev(amt = 480, cmt = "TCZ", time = 0)
##    ## furosemide 20 mg q6h x 7 days (FACTT conservative arm)
##    furo <- ev(amt = 20, cmt = "FUR", ii = 6, addl = 27, time = 0)
##    ## methylprednisolone 2 mg/kg/day started on day 14 (LaSRS late arm)
##    late <- ev(amt = 120, cmt = "MPRED", ii = 24, addl = 13, time = 336)
##
##    list(
##      s01_conventional_Vt12   = run(conv),
##      s02_LTVV_Vt6            = run(ltvv),
##      s03_LTVV_highPEEP       = run(c(ltvv, list(PEEP = 16))),
##      s04_LTVV_prone          = run(c(ltvv, list(PRONE_H = 16))),
##      s05_prone_NMBA_deep     = run(c(ltvv, list(PRONE_H = 16, SEDATION = 0.9)), cisa),
##      s05b_NMBA_light_sed     = run(c(ltvv, list(SEDATION = 0.35)), cisa),
##      s06_dexamethasone       = run(ltvv, dexa),
##      s07_conservative_fluid  = run(c(ltvv, list(FLUID_IN = 60)), furo),
##      s08_inhaled_NO          = run(c(ltvv, list(NO_PPM = 20))),
##      s09_VV_ECMO             = run(c(ltvv, list(ECMO = 1)),
##                                    NULL),
##      s10_COVID_dexa_tocz     = run(c(ltvv, list(HYPER = 1, DIRECT = 1.0,
##                                                 RECRUIT = 0.70)),
##                                    c(dexa, tocz)),
##      s11_hyper_steroid       = run(c(ltvv, list(HYPER = 1)), dexa),
##      s12_hypo_steroid        = run(c(ltvv, list(HYPER = 0)), dexa),
##      s13_late_steroid_d14    = run(ltvv, late),
##      s14_full_bundle         = run(c(ltvv, list(PRONE_H = 16, SEDATION = 0.9,
##                                                 FLUID_IN = 60)),
##                                    c(dexa, cisa, furo))
##    )
##  }
##
##  ---------------------------------------------------------------------------
##  Reading the output
##  ---------------------------------------------------------------------------
##    Mortality_prob at t = 672 h  -> 28-day mortality
##    VFD_expected   at t = 672 h  -> ventilator-free days (survival-weighted,
##                                    i.e. the quantity trials actually report)
##    DrivingP_cmH2O, MechPower_Jmin, Strain_global -> the mechanical exposure
##    Aerated_frac, EVLW_mlkg, Compliance_Crs       -> the baby lung
##    IL6_signalling vs IL6_pgml -> note that tocilizumab RAISES measured IL-6
##                                  while lowering signalling; the model keeps
##                                  the two separate deliberately.
##
##  ---------------------------------------------------------------------------
##  Validation — what the model actually produces (mrgsolve 2.0.1, 672 h,
##  reference patient PF0 = 130 unless the row says "severe" = PF0 90)
##  ---------------------------------------------------------------------------
##    scenario                  28-d mortality   VFD    trial comparator
##    01 conventional Vt 12          38.3%      10.9    ARMA 39.8% / 10 d
##    02 LTVV Vt 6                   28.8%      13.6    ARMA 31.0% / 12 d
##    03 LTVV + PEEP 16              32.2%      12.4    ALVEOLI/ART: no benefit
##                                                      (harm when unrecruitable)
##    04 LTVV + prone 16 h           22.9%      16.2    PROSEVA direction
##    05 prone + NMBA, deep sed      23.2%      15.9    ACURASYS (small increment
##                                                      on top of prone)
##    05b NMBA, light sedation       28.4%      13.7    ROSE: neutral
##    06 dexamethasone               23.9%      16.0    DEXA-ARDS 21% / +4.8 VFD
##    07 conservative fluid          24.1%      16.5    FACTT: VFD +2.5, no
##                                                      mortality effect
##    08 inhaled NO 20 ppm           26.8%      14.4    PaO2/FiO2 +20% at 24 h,
##                                                      mortality ~unchanged
##    09 VV-ECMO                     22.1%      16.2    EOLIA direction
##    10 COVID-ARDS dexa + TCZ       38.1%       8.5    RECOVERY / REMAP-CAP
##    11 hyperinflammatory + steroid 41.2%       7.7    Calfee HTE: steroid ARR
##    11b hyperinflammatory alone    50.7%       5.2    9.5% in hyper ...
##    12 hypoinflammatory + steroid  23.9%      16.0    ... vs 4.9% in hypo
##    13 methylpred started day 14   29.3%      13.4    LaSRS: no benefit, more
##                                                      weakness (0.84 vs 0.38)
##    14 full bundle                 17.8%      19.4    —
##    severe supine / prone / ECMO   31.9 / 24.7 / 23.6% PROSEVA 32.8 -> 16.0%,
##                                                      EOLIA 46 -> 35%
##
##  Where the model is honest about missing the target: the mortality effects of
##  PRONE POSITION (model ARR 7.2% vs PROSEVA 16.8%) and of DEXAMETHASONE
##  (model ARR 4.9% vs DEXA-ARDS 15%) are roughly half the size reported in
##  those two trials. Both trials are single results with effect sizes at the
##  large end of the ARDS literature, and a mechanistic model that reproduced
##  them exactly would have to attribute more of the mortality signal to
##  regional stress homogenisation, and to NF-kB transrepression, than the
##  physiological evidence supports. The ordering, direction and the mechanism
##  of every intervention are reproduced; the two effect magnitudes are not
##  tuned to match, and should not be read as predictions of trial results.
##
##  ---------------------------------------------------------------------------
##  Calibration notes
##  ---------------------------------------------------------------------------
##  * The hazard block is calibrated so that scenario 1 (12 mL/kg) and
##    scenario 2 (6 mL/kg) bracket the ARMA result (39.8% vs 31.0% at 28 days)
##    for the reference patient, and so that adding prone position in a severe
##    patient (PF0 = 90) reproduces the PROSEVA effect size.
##  * The VILI block is deliberately driven by THREE partly redundant
##    mechanical exposures (strain, driving pressure, mechanical power) because
##    no single one of them explains the trial data on its own: ARMA separates
##    on tidal volume, Amato's mediation analysis on driving pressure, and the
##    observational power literature on J/min. A model with only one of the
##    three cannot reproduce all three findings.
##  * Corticosteroid benefit is NOT hard-coded: it emerges from NF-kB
##    transrepression, reduced neutrophil recruitment, increased alveolar fluid
##    clearance and reduced TGF-b. The late-steroid harm in scenario 13 emerges
##    from the secondary-infection seeding term and the weakness term acting on
##    a patient whose collagen is already deposited — no separate "late" rule.
##  * Inhaled NO (scenario 8) improves PaO2/FiO2 by ~20% at 24 h while moving
##    28-day mortality by only 2 percentage points, because it acts only on the
##    shunt term and the hazard is dominated by mechanics, dead space and organ
##    failure. This is the intended behaviour and is the model's main
##    falsifiable claim: an intervention that buys oxygenation without touching
##    the mechanical exposure should not buy survival.
##  * The fluid block contains two feedbacks without which it is meaningless —
##    pressure natriuresis (urine output rises with positive balance) and a
##    volume gate on the diuretic response. Without them a fixed intake or a
##    fixed furosemide order integrates for 28 days into a balance no patient
##    ever has, and the capillary-pressure term then dominates the lung water.
##  ============================================================================
