##  Cold Agglutinin Disease (CAD) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Cold Agglutinin Disease — clonal marrow B-cell/lymphoplasmacytic
##             population secreting monoclonal IgM cold agglutinin (anti-I/i) ->
##             cold-dependent RBC binding -> classical complement pathway
##             activation (C1q-C1r-C1s -> C4 -> C3) -> C3b RBC opsonization ->
##             predominantly EXTRAvascular hemolysis (hepatic Kupffer-cell
##             CR1/CRIg erythrophagocytosis) plus a variable INTRAvascular
##             component (C5b-9 membrane attack complex) -> anemia, reticulocy-
##             tosis, indirect hyperbilirubinemia, LDH elevation, haptoglobin
##             depletion. Notably STEROID-REFRACTORY (unlike warm AIHA).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 21 ODE compartments — IV drug PK for rituximab, bendamustine,
##             sutimlimab (anti-C1s), and SC pegcetacoplan (C3 inhibitor) +
##             clonal B-cell burden + monoclonal IgM titer + classical-pathway
##             activity (C1s, C4, C3, C3b-RBC opsonization) + terminal complement
##             (C5b-9/MAC) + hemolysis biomarkers (Hb, reticulocytes, indirect
##             bilirubin, LDH, haptoglobin) + a decaying acute cold-exposure
##             driver compartment for hemolytic-crisis challenge scenarios.
##  Time     : days (chronic outpatient horizon; default 180 d to capture
##             rituximab/bendamustine cycles and sutimlimab loading+maintenance).
##  Units    : IV/SC drug "exposure" compartments in arbitrary dose-proportional
##             units (au) — this library's standard surrogate for full
##             mechanistic plasma PK when the disease-relevant PD (B-cell
##             depletion, C1s/C3 blockade) is what matters; physiological states
##             in clinically familiar units (g/dL, mg/dL, U/L, %) — see [CMT].
##  Scenarios: 7 prebuilt — see CAD_simulate_scenarios() at bottom, including a
##             sutimlimab-discontinuation relapse case and an acute cold-
##             exposure hemolytic-crisis challenge on/off complement blockade.
##  Anchors  : Berentsen 2020 Blood 136:480 (232-patient multinational natural-
##             history/observational study); Jager 2020 Blood Rev 41:100648
##             (diagnostic criteria & consensus treatment recommendations);
##             Berentsen 2017 Blood 130:537 (Nordic bendamustine-rituximab
##             trial, 71% ORR); CARDINAL trial (Roth 2021 N Engl J Med
##             384:1323, sutimlimab, ~54% composite response, rapid Hb rise
##             within days); CADENZA trial (Roth 2022 Blood 140:980,
##             sutimlimab without recent transfusion history, ~73% response);
##             pegcetacoplan CAD/wAIHA phase 2 pilot (NCT03226678) and CASCADE
##             phase 3 (NCT05096403) (dual classical+alternative pathway C3
##             inhibition); Berentsen & Barcellini 2021 Blood 137:1295 (How I
##             treat cold agglutinin disease — corticosteroids not recommended,
##             i.e. steroid-refractory nature of CAD).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of Cold Agglutinin Disease linking clonal B-cell/lymphoplasmacytic
IgM cold-agglutinin production, cold-dependent RBC binding, classical
complement pathway activation (C1s-C4-C3), C3b-mediated extravascular
(Kupffer-cell) hemolysis, C5b-9 (MAC)-mediated intravascular hemolysis, and
downstream hemolysis biomarkers (Hb, reticulocytes, bilirubin, LDH,
haptoglobin), with mechanistic PK/PD for rituximab, bendamustine, sutimlimab
(anti-C1s), and pegcetacoplan (C3 inhibitor), plus an acute cold-exposure
challenge driver.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease severity
SEV          : 0.65  : Clonal disease severity (0=none, 1=high monoclonal IgM burden)
SECONDARY    : 0     : 1 = secondary CAD (infection-triggered; more self-limited clone)
AMB_COLD     : 0.5   : 0-1, ambient/habitual cold-exposure level (reduced by cold-avoidance behavior)
COLD_AVOIDANCE: 0    : 1 = behavioral cold avoidance counseling in effect
BASE_HB      : 9.0   : g/dL, presenting hemoglobin

//--- Rituximab IV 375mg/m2 weekly x4 (anti-CD20, depletes clonal B cells)
KOUT_RTX     : 0.12  : 1/day, slow mAb elimination
EC50_RTX     : 1.2   : au
EMAX_RTX     : 0.55  : max fractional weekly B-cell kill rate
KTR_RTX      : 0.35  : 1/day, central<->peripheral transfer

//--- Bendamustine IV 90mg/m2 d1-2 q28d (alkylator, cytotoxic to clonal lymphocytes)
KOUT_BEN     : 0.6   : 1/day
EC50_BEN     : 1.0   : au
EMAX_BEN     : 0.45  : max fractional clone apoptosis rate
KTR_BEN      : 0.5   : 1/day, central<->peripheral transfer

//--- Sutimlimab IV loading (d0,d7) + biweekly maintenance (anti-C1s, blocks classical pathway)
KOUT_SUT     : 0.10  : 1/day, slow mAb elimination (TMDD-flattened at high dose)
EC50_SUT     : 0.9   : au, exposure for half-maximal C1s blockade
EMAX_SUT     : 0.92  : max fractional classical-pathway (C1s) blockade
KTR_SUT      : 0.30  : 1/day, central<->peripheral transfer

//--- Pegcetacoplan SC (investigational in CAD; C3/C3b binder, dual-pathway blockade)
KA_PEG       : 0.9   : 1/day, SC absorption
KOUT_PEG     : 0.35  : 1/day
EC50_PEG     : 1.0   : au
EMAX_PEG     : 0.85  : max fractional C3-convertase blockade (blocks both classical & alternative amplification)

//--- Clonal B-cell / lymphoplasmacytic burden
CLONE_MAX    : 100   : a.u., carrying capacity
K_CLONE_GROW : 0.010 : 1/day, intrinsic clonal growth rate
K_KILL_RTX   : 1.1   : scales rituximab-driven clone kill
K_KILL_BEN   : 1.3   : scales bendamustine-driven clone kill
K_SYNERGY_RB : 0.55  : additional multiplicative synergy when both RTX & BEN active

//--- Monoclonal IgM cold-agglutinin production
K_PROD_IGM   : 1.0   : production rate scalar per unit clone
KOUT_IGM     : 0.20  : 1/day, IgM turnover (slow, large pentamer)

//--- Cold-dependent agglutination -> classical pathway trigger
K_AGG        : 1.15  : agglutination signal scalar (IgM x cold exposure)
COLD_PULSE_KOUT: 2.5 : 1/day, decay of an acute cold-exposure event pulse
KOUT_C1S     : 1.8   : 1/day, C1s activation-state turnover (fast enzyme kinetics)

//--- Classical complement pathway (C4, C3) turnover & consumption
C4_NORMAL    : 100   : a.u. (~ percent of normal serum C4)
KIN_C4       : 14    : a.u./day, hepatic C4 synthesis
KOUT_C4      : 0.14  : 1/day, baseline C4 clearance
K_CONSUME_C4 : 0.55  : fractional C4 consumption rate by active classical pathway
C3_NORMAL    : 100   : a.u. (~ percent of normal serum C3)
KIN_C3       : 13    : a.u./day, hepatic C3 synthesis
KOUT_C3      : 0.13  : 1/day, baseline C3 clearance
K_CONSUME_C3 : 0.60  : fractional C3 consumption rate by classical convertase flux

//--- C3b RBC-surface opsonization & terminal complement (MAC)
KON_C3B      : 1.6   : 1/day, C3b deposition-accumulation rate
KOUT_C3B     : 0.9   : 1/day, C3b-opsonized RBC clearance (Kupffer phagocytosis)
KON_MAC      : 0.55  : 1/day, C5b-9 MAC formation rate (requires C3b + terminal pathway)
KOUT_MAC     : 1.3   : 1/day, MAC turnover

//--- Hemolysis -> hemoglobin / reticulocyte / bilirubin / LDH / haptoglobin
HB_NORMAL    : 14.5  : g/dL
W_MAC_IV     : 0.85  : weight, intravascular hemolysis contribution (MAC-driven)
W_C3B_EV     : 0.45  : weight, extravascular hemolysis contribution (C3b/Kupffer-driven, dominant in CAD)
HEMOL_HALF   : 18    : a.u., hemolysis signal producing half-maximal Hb suppression
KOUT_HB      : 0.10  : 1/day, Hb equilibration (RBC lifespan-scale)
RETIC_BASE   : 1.2   : %, baseline reticulocyte percentage
K_EPO_RETIC  : 0.55  : reticulocyte compensatory gain per g/dL Hb deficit
KOUT_RETIC   : 0.35  : 1/day
BILI_BASE    : 0.6   : mg/dL
K_BILI_HEMOL : 0.09  : mg/dL per unit hemolysis signal
KOUT_BILI    : 0.5   : 1/day
LDH_BASE     : 190   : U/L
K_LDH_IV     : 9.0   : U/L per unit MAC (intravascular hemolysis is LDH-dominant)
K_LDH_EV     : 2.5   : U/L per unit C3b (extravascular contributes less LDH)
KOUT_LDH     : 0.55  : 1/day
HAPTO_BASE   : 90    : mg/dL
K_HAPTO_CONSUME: 0.075: fractional haptoglobin consumption per unit MAC (binds free Hb)
KOUT_HAPTO   : 0.6   : 1/day

[CMT] @annotated
RTX_CENT   : Rituximab central compartment (au)
RTX_PERIPH : Rituximab peripheral compartment (au)
BEN_CENT   : Bendamustine central compartment (au)
BEN_PERIPH : Bendamustine peripheral compartment (au)
SUT_CENT   : Sutimlimab central compartment (au)
SUT_PERIPH : Sutimlimab peripheral compartment (au)
PEG_DEPOT  : Pegcetacoplan SC absorption depot (au)
PEG_CENT   : Pegcetacoplan central compartment (au)
CLONE      : Clonal B-cell/lymphoplasmacytic burden (a.u., 0-100)
IGM        : Serum monoclonal IgM cold-agglutinin titer (a.u.)
COLD_PULSE : Acute cold-exposure event driver (a.u., decaying pulse)
C1S_ACT    : Active classical-pathway C1s enzymatic state (fraction 0-1)
C4         : Serum C4 level (a.u., ~percent of normal)
C3         : Serum C3 level (a.u., ~percent of normal)
C3B_RBC    : C3b opsonization intensity on RBC surface (a.u.)
MAC        : C5b-9 membrane attack complex level (a.u.)
HB         : Hemoglobin (g/dL)
RETIC      : Reticulocyte percentage (%)
BILI       : Indirect bilirubin (mg/dL)
LDH        : Lactate dehydrogenase (U/L)
HAPTO      : Haptoglobin (mg/dL)

[MAIN]
RTX_CENT_0 = 0; RTX_PERIPH_0 = 0; BEN_CENT_0 = 0; BEN_PERIPH_0 = 0;
SUT_CENT_0 = 0; SUT_PERIPH_0 = 0; PEG_DEPOT_0 = 0; PEG_CENT_0 = 0;
COLD_PULSE_0 = 0;

double sev_eff0 = SEV * (SECONDARY>0 ? 0.6 : 1.0);
CLONE_0   = CLONE_MAX * sev_eff0;
IGM_0     = K_PROD_IGM * CLONE_0 / KOUT_IGM;

double amb0 = AMB_COLD * (1 - 0.5*COLD_AVOIDANCE);
double agg0 = K_AGG * IGM_0/100.0 * amb0;
if (agg0 > 1) agg0 = 1;
C1S_ACT_0 = agg0;
C4_0      = C4_NORMAL * (1 - 0.35*agg0);
C3_0      = C3_NORMAL * (1 - 0.35*agg0);
double cpflux0 = C1S_ACT_0 * (C4_0/C4_NORMAL);
C3B_RBC_0 = KON_C3B*cpflux0 / KOUT_C3B;
MAC_0     = KON_MAC*C3B_RBC_0 / KOUT_MAC;

double hemol0 = W_MAC_IV*MAC_0 + W_C3B_EV*C3B_RBC_0;
HB_0      = BASE_HB;
RETIC_0   = RETIC_BASE + K_EPO_RETIC*(HB_NORMAL - BASE_HB);
BILI_0    = BILI_BASE + K_BILI_HEMOL*hemol0;
LDH_0     = LDH_BASE + K_LDH_IV*MAC_0 + K_LDH_EV*C3B_RBC_0;
HAPTO_0   = HAPTO_BASE / (1 + K_HAPTO_CONSUME*MAC_0);

[ODE]
// ---------- Drug PK / exposure kinetics ----------
dxdt_RTX_CENT   = -KOUT_RTX*RTX_CENT - KTR_RTX*RTX_CENT + KTR_RTX*RTX_PERIPH;
dxdt_RTX_PERIPH =  KTR_RTX*RTX_CENT - KTR_RTX*RTX_PERIPH;
dxdt_BEN_CENT   = -KOUT_BEN*BEN_CENT - KTR_BEN*BEN_CENT + KTR_BEN*BEN_PERIPH;
dxdt_BEN_PERIPH =  KTR_BEN*BEN_CENT - KTR_BEN*BEN_PERIPH;
dxdt_SUT_CENT   = -KOUT_SUT*SUT_CENT - KTR_SUT*SUT_CENT + KTR_SUT*SUT_PERIPH;
dxdt_SUT_PERIPH =  KTR_SUT*SUT_CENT - KTR_SUT*SUT_PERIPH;
dxdt_PEG_DEPOT  = -KA_PEG*PEG_DEPOT;
dxdt_PEG_CENT   =  KA_PEG*PEG_DEPOT - KOUT_PEG*PEG_CENT;
dxdt_COLD_PULSE = -COLD_PULSE_KOUT*COLD_PULSE;

// ---------- Drug effect (Emax) terms ----------
double Rtx_eff = EMAX_RTX * RTX_CENT/(EC50_RTX + RTX_CENT);
double Ben_eff = EMAX_BEN * BEN_CENT/(EC50_BEN + BEN_CENT);
double Sut_block = EMAX_SUT * SUT_CENT/(EC50_SUT + SUT_CENT);
if (Sut_block > 0.97) Sut_block = 0.97;
double Peg_block = EMAX_PEG * PEG_CENT/(EC50_PEG + PEG_CENT);
if (Peg_block > 0.95) Peg_block = 0.95;

// ---------- Clonal B-cell / lymphoplasmacytic burden ----------
double synergy = 1 + K_SYNERGY_RB * ((Rtx_eff>0 && Ben_eff>0) ? 1.0 : 0.0);
double kill_rate = (K_KILL_RTX*Rtx_eff + K_KILL_BEN*Ben_eff) * synergy;
dxdt_CLONE = K_CLONE_GROW*CLONE*(1 - CLONE/CLONE_MAX) - kill_rate*CLONE;
if (CLONE < 0.01 && kill_rate > 0) dxdt_CLONE = 0;   // floor: residual clone, not eradicated

// ---------- Monoclonal IgM production/turnover ----------
dxdt_IGM = K_PROD_IGM*CLONE - KOUT_IGM*IGM;

// ---------- Cold-dependent agglutination signal ----------
double cold_now = AMB_COLD*(1 - 0.5*COLD_AVOIDANCE) + COLD_PULSE;
double agg_signal = K_AGG * (IGM/100.0) * cold_now;
if (agg_signal > 1) agg_signal = 1;

// ---------- Classical complement pathway: C1s, C4, C3 ----------
double c1s_target = agg_signal * (1 - Sut_block);
dxdt_C1S_ACT = KOUT_C1S * (c1s_target - C1S_ACT);

double cp_flux = C1S_ACT * (C4/C4_NORMAL);            // classical convertase (C4b2a) activity proxy
dxdt_C4 = KIN_C4 - KOUT_C4*C4 - K_CONSUME_C4*cp_flux*C4;

double c3_consume_flux = cp_flux * (1 - Peg_block);
dxdt_C3 = KIN_C3 - KOUT_C3*C3 - K_CONSUME_C3*c3_consume_flux*(C3/C3_NORMAL)*C3;

// ---------- C3b RBC opsonization & terminal complement (MAC) ----------
dxdt_C3B_RBC = KON_C3B*c3_consume_flux*(C3/C3_NORMAL) - KOUT_C3B*C3B_RBC;

double mac_drive = C3B_RBC * (1 - Peg_block);          // dual-pathway blockade also limits C5 convertase formation
dxdt_MAC = KON_MAC*mac_drive - KOUT_MAC*MAC;

// ---------- Hemolysis signal & hemoglobin ----------
double hemol = W_MAC_IV*MAC + W_C3B_EV*C3B_RBC;
double hb_suppression = hemol / (HEMOL_HALF + hemol);
double comp_boost = 1 + 0.20*(RETIC/RETIC_BASE - 1);   // partial marrow compensation
if (comp_boost < 1) comp_boost = 1;
double HB_target = HB_NORMAL * (1 - hb_suppression) * comp_boost;
if (HB_target > HB_NORMAL) HB_target = HB_NORMAL;
if (HB_target < 3) HB_target = 3;
dxdt_HB = KOUT_HB * (HB_target - HB);

// ---------- Reticulocytes (compensatory erythropoiesis) ----------
double hb_deficit = HB_NORMAL - HB;
if (hb_deficit < 0) hb_deficit = 0;
double RETIC_target = RETIC_BASE + K_EPO_RETIC*hb_deficit;
dxdt_RETIC = KOUT_RETIC * (RETIC_target - RETIC);

// ---------- Indirect bilirubin ----------
double BILI_target = BILI_BASE + K_BILI_HEMOL*hemol;
dxdt_BILI = KOUT_BILI * (BILI_target - BILI);

// ---------- LDH ----------
double LDH_target = LDH_BASE + K_LDH_IV*MAC + K_LDH_EV*C3B_RBC;
dxdt_LDH = KOUT_LDH * (LDH_target - LDH);

// ---------- Haptoglobin (consumed by intravascular hemolysis) ----------
double HAPTO_target = HAPTO_BASE / (1 + K_HAPTO_CONSUME*MAC);
dxdt_HAPTO = KOUT_HAPTO * (HAPTO_target - HAPTO);

[TABLE]
capture Rituximab_effect    = Rtx_eff;
capture Bendamustine_effect = Ben_eff;
capture Sutimlimab_C1s_block = Sut_block;
capture Pegcetacoplan_C3_block = Peg_block;
capture Clonal_burden       = CLONE;
capture IgM_titer           = IGM;
capture Agglutination_signal = agg_signal;
capture Classical_pathway_flux = cp_flux;
capture C4_level            = C4;
capture C3_level            = C3;
capture C3b_opsonization    = C3B_RBC;
capture MAC_level           = MAC;
capture Hemolysis_signal    = hemol;
capture Hemoglobin          = HB;
capture Reticulocyte_pct    = RETIC;
capture Indirect_bilirubin  = BILI;
capture LDH_level           = LDH;
capture Haptoglobin_level   = HAPTO;

[CAPTURE]
Rituximab_effect Bendamustine_effect Sutimlimab_C1s_block Pegcetacoplan_C3_block
Clonal_burden IgM_titer Agglutination_signal Classical_pathway_flux
C4_level C3_level C3b_opsonization MAC_level Hemolysis_signal
Hemoglobin Reticulocyte_pct Indirect_bilirubin LDH_level Haptoglobin_level


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("cad_mrgsolve_model.R")
##
##  # ---------- 7 prebuilt scenarios ----------
##
##  CAD_simulate_scenarios <- function(end_d = 180) {
##
##    sc <- list(
##      "1. Untreated natural history (cold avoidance only)" =
##        ev(amt=0, cmt="RTX_CENT", time=0),          # COLD_AVOIDANCE=1 set via param()
##
##      "2. Rituximab 375mg/m2 IV weekly x4" =
##        ev(amt=1.0, cmt="RTX_CENT", ii=7, addl=3),
##
##      "3. Rituximab + Bendamustine (RB regimen, q28d x4 cycles)" =
##        seq(ev(amt=1.0, cmt="RTX_CENT", ii=7, addl=3),
##            ev(amt=1.0, cmt="BEN_CENT", ii=28, addl=3, time=0)),
##
##      "4. Sutimlimab loading (d0,d7) + biweekly maintenance (CARDINAL)" =
##        ev(amt=1.3, cmt="SUT_CENT", time=0, ii=7, addl=1) +
##        ev(amt=1.1, cmt="SUT_CENT", time=14, ii=14, addl=floor((end_d-14)/14)),
##
##      "5. Pegcetacoplan SC biweekly (investigational, dual-pathway)" =
##        ev(amt=1.2, cmt="PEG_DEPOT", ii=14, addl=floor(end_d/14)),
##
##      "6. Sutimlimab then discontinuation at day 90 (relapse teaching case)" =
##        ev(amt=1.3, cmt="SUT_CENT", time=0, ii=7, addl=1) +
##        ev(amt=1.1, cmt="SUT_CENT", time=14, ii=14, addl=floor((90-14)/14)),
##
##      "7. Acute cold-exposure hemolytic crisis (on sutimlimab background)" =
##        ev(amt=1.3, cmt="SUT_CENT", time=0, ii=7, addl=1) +
##        ev(amt=1.1, cmt="SUT_CENT", time=14, ii=14, addl=floor((end_d-14)/14)) +
##        ev(amt=3.0, cmt="COLD_PULSE", time=60)
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      avoid <- grepl("^1\\.", lab)
##      mod %>% param(COLD_AVOIDANCE = as.numeric(avoid)) %>%
##        mrgsim(e, end=end_d, delta=0.5) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Berentsen 2020 Blood 136:480 (232-patient study) / Jager 2020 Blood Rev
##  #   41:100648: rituximab monotherapy ~50-54% ORR, complete response rare,
##  #   relapse common (median ~15 months) -- modeled via moderate K_KILL_RTX
##  #   with clone regrowth after the drug washes out.
##  # Rituximab-bendamustine (Berentsen 2017 Blood 130:537): ~71% ORR (40% CR),
##  #   more durable than rituximab alone -- modeled via K_SYNERGY_RB
##  #   multiplicative term when both agents are simultaneously active.
##  # CARDINAL (Roth 2021 N Engl J Med 384:1323) / CADENZA (Roth 2022 Blood
##  #   140:980): sutimlimab produces Hb rise within days (fastest onset of all
##  #   agents), ~54-73% composite response, but classical-pathway blockade
##  #   does NOT reduce clonal burden or IgM titer -- modeled via Sut_block
##  #   acting purely on C1S_ACT, leaving CLONE/IGM dynamics untouched;
##  #   hemolysis recurs on discontinuation once SUT_CENT washes out
##  #   (scenario 6), consistent with reported post-sutimlimab relapse.
##  # Pegcetacoplan (phase 2 CAD/wAIHA pilot NCT03226678; CASCADE phase 3
##  #   NCT05096403): dual classical+alternative pathway C3 blockade --
##  #   modeled via Peg_block acting on both C3 consumption and
##  #   C5-convertase-dependent MAC formation (broader than sutimlimab's
##  #   upstream-only C1s blockade).
##  # Jager 2020 Blood Rev 41:100648: cold agglutinin titer / thermal amplitude
##  #   and cold exposure are the proximate triggers for acute hemolytic
##  #   crises -- modeled via the decaying COLD_PULSE driver superimposed on
##  #   ambient cold exposure.
##  # Berentsen & Barcellini 2021 Blood 137:1295 (How I treat CAD): CAD is
##  #   characteristically STEROID-REFRACTORY (unlike warm AIHA) and
##  #   corticosteroids are not recommended -- intentionally NOT modeled as a
##  #   treatment arm; corticosteroids are omitted from PK/PD scenarios.
##
##  # ---------- Quick sanity plots ----------
##  # df <- CAD_simulate_scenarios(180)
##  # ggplot(df, aes(time, Hemoglobin, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, MAC_level, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Clonal_burden, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, LDH_level, colour=scenario)) + geom_line()
