##  Malignant Pleural Mesothelioma (MPM, 악성 흉막 중피종) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Asbestos-driven malignant pleural mesothelioma (epithelioid /
##             sarcomatoid / biphasic), BAP1/CDKN2A/NF2-Hippo-YAP tumor-
##             suppressor loss, immune-evasive TME.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 25 ODE compartments — drug PK (cisplatin, pemetrexed,
##             bevacizumab, nivolumab, ipilimumab, anetumab ravtansine [ADC],
##             rucaparib) + two-clone tumor-burden model (epithelioid vs.
##             sarcomatoid growth/drug-sensitivity) + mesothelin biomarker,
##             pleural effusion, renal function, 3-compartment (Friberg-like)
##             myelosuppression, and a cumulative-hazard survival readout.
##  Time     : days (study horizon 0 - 730 d, default 168-252 d trial window)
##  Units    : dose in mg (drugs) or mg/m2-derived mg (chemo, using BSA=1.8 m2
##             fixed default); concentration in mg/L; tumor burden in relative
##             volume units (baseline = 100); biomarkers in study-specific
##             units.
##  Scenarios: 10 prebuilt — see MPM_simulate_scenarios() at bottom.
##  Anchors  : EMPHACIS (cisplatin+pemetrexed) Vogelzang 2003 JCO PMID 12860938;
##             MAPS (bevacizumab) Zalcman 2016 Lancet PMID 26719230;
##             CheckMate 743 (nivo+ipi 1L) Baas 2021 Lancet PMID 33485464;
##             CONFIRM (nivo 2L) Fennell 2021 Lancet Oncol PMID 34656227;
##             MAPS2 (nivo/nivo+ipi 2L) Scherpereel 2019 Lancet Oncol PMID 30660609;
##             STELLAR (TTFields+chemo) Ceresoli 2019 Lancet Oncol PMID 31628016;
##             MiST1 (rucaparib, BAP1-def) Fennell 2021 Lancet Respir Med PMID 33515503;
##             Anetumab ravtansine Ph1 Hassan 2020 (ADC) PMID 32213105;
##             MARS/MARS2 (surgery) Treasure 2011 PMID 21723781 / Lim 2024 PMID 38740044;
##             Pass 2012 NEJM (fibulin-3) PMID 23050525; Robinson 2005 Lung
##             Cancer (SMRP) PMID 15950789.
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of malignant pleural mesothelioma linking BAP1/CDKN2A/NF2-Hippo-YAP
tumor-suppressor loss and a two-clone (epithelioid/sarcomatoid) tumor-burden
network to platinum/antifolate chemotherapy, anti-VEGF, dual checkpoint
immunotherapy, mesothelin-ADC, and BAP1-synthetic-lethal PARP-inhibitor
pharmacodynamics, with mesothelin biomarker, effusion, myelosuppression,
renal, and survival-hazard readouts.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / tumor biology
AGE          : 68   : age (years, median MPM diagnosis 65-70)
BSA          : 1.8  : body surface area (m^2)
CRCL0        : 80   : baseline creatinine clearance (mL/min)
HIST_SARC_FRAC : 0.20 : fraction of tumor that is sarcomatoid at baseline (0=pure epithelioid,1=pure sarcomatoid)
BAP1_DEFICIENT : 0  : 1 = BAP1-deficient/BRCA1-deficient tumor (PARPi-sensitive)
MSLN_HIGH    : 1    : 1 = mesothelin-high tumor (ADC-responsive)
PDL1_HIGH    : 0    : 1 = PD-L1-high tumor (modest added IO sensitivity)
TUM0         : 100  : baseline relative tumor burden (a.u.)
EFF0         : 30   : baseline pleural effusion volume (relative units, 0-100)
ECOG0        : 1    : baseline ECOG performance status (0-4)

//--- Cisplatin PK (75 mg/m2 IV q3w; 2-cpt; renal CL) Reyno 1990/Urien 2005
CL_CIS      : 12.0   : L/h total plasma CL (free+bound overall surrogate)
Q_CIS       : 4.0    : L/h inter-cpt
V1_CIS      : 20     : L central
V2_CIS      : 30     : L peripheral (protein-bound depot)
FR_RENAL_CIS: 0.35   : fraction of CL that is renal (nephrotoxic driver)

//--- Pemetrexed PK (500 mg/m2 IV q3w; 2-cpt; renal CL) Latz 2006 Clin Pharmacokinet
CL_PEM      : 3.5    : L/h
Q_PEM       : 1.0    : L/h
V1_PEM      : 9      : L
V2_PEM      : 4      : L

//--- Bevacizumab PK (15 mg/kg IV q3w; 2-cpt mAb) MAPS/Lu 2008
WT          : 70     : kg (for mg/kg dosing)
CL_BEV      : 0.0080 : L/h (t1/2 ~20 d)
Q_BEV       : 0.0030 : L/h
V1_BEV      : 3.1    : L
V2_BEV      : 2.4    : L

//--- Nivolumab PK (3 mg/kg IV q2w or 360 mg flat q3w; 2-cpt mAb) CheckMate743 PopPK
CL_NIVO     : 0.0084 : L/h (t1/2 ~25 d)
Q_NIVO      : 0.0025
V1_NIVO     : 3.0
V2_NIVO     : 3.3
EC50_NIVO   : 0.0012 : mg/L, receptor-occupancy IC50 (surrogate)

//--- Ipilimumab PK (1 mg/kg IV q6w; 2-cpt mAb) CheckMate743
CL_IPI      : 0.0068 : L/h (t1/2 ~15 d)
Q_IPI       : 0.0022
V1_IPI      : 3.3
V2_IPI      : 2.9
EC50_IPI    : 0.0015

//--- Anetumab ravtansine PK (anti-MSLN ADC, 6.5 mg/kg IV q3w; 2-cpt) Hassan 2020 PMID 32213105
CL_ADC      : 0.0110 : L/h
Q_ADC       : 0.0035
V1_ADC      : 3.4
V2_ADC      : 2.6
EC50_ADC    : 0.60   : mg/L, tumor-kill IC50 (mesothelin-gated)

//--- Rucaparib PK (600 mg PO BID; 1-cpt+gut) Fennell 2021 MiST1 / Shapiro 2019
KA_RUCA     : 1.6    : 1/h
F_RUCA      : 0.36
CL_RUCA     : 15.0   : L/h
V_RUCA      : 262    : L
EC50_RUCA   : 1.8    : mg/L, PARP-trapping IC50 (BAP1-deficient only)

//--- Tumor growth / clone dynamics (relative units, Gompertzian-logistic)
KG_EPI      : 0.0090 : 1/day intrinsic growth, epithelioid clone
KG_SARC     : 0.0150 : 1/day intrinsic growth, sarcomatoid clone (faster, more aggressive)
TUM_CAP     : 4000   : carrying capacity (a.u.)
KDEATH_BASE : 0.0015 : 1/day background tumor-cell death (spontaneous)

//--- Chemo cytotoxic Emax/EC50 (per-clone sensitivity; sarcomatoid less sensitive)
EMAX_CIS_EPI : 0.050 : 1/day max kill, epithelioid
EC50_CIS    : 1.2    : mg/L (free-Pt surrogate)
EMAX_CIS_SARC_REL : 0.55 : relative sensitivity of sarcomatoid vs epithelioid
EMAX_PEM_EPI : 0.045
EC50_PEM    : 8.0    : mg/L
EMAX_PEM_SARC_REL : 0.50

//--- Anti-VEGF effect (bevacizumab: growth-inhibitory, not directly cytotoxic)
EMAX_BEV_GROWTH : 0.35 : max fractional growth-rate reduction
EC50_BEV    : 25      : mg/L
EMAX_BEV_EFF: 0.45     : max fractional effusion-formation reduction

//--- Immune checkpoint PD (nivolumab/ipilimumab; epithelioid more IO-responsive on average)
EMAX_IO_EPI : 0.038   : 1/day max IO-driven kill, epithelioid, single-agent nivo
EMAX_IO_SARC_REL : 0.70
IPI_SYNERGY : 1.55    : multiplicative boost when CTLA4 occupancy also high (combo)
PDL1_BOOST  : 1.25    : multiplier if PDL1_HIGH=1

//--- Mesothelin-ADC PD (mesothelin-gated, epithelioid-selective)
EMAX_ADC    : 0.060   : 1/day max kill (if MSLN_HIGH)
MSLN_GATE_LOW : 0.15  : residual effect fraction if MSLN_HIGH=0

//--- Rucaparib synthetic-lethal PD (BAP1-deficient only)
EMAX_RUCA   : 0.050   : 1/day max kill if BAP1_DEFICIENT=1
RUCA_GATE_LOW : 0.05

//--- TTFields PD (adds to chemo cytotoxicity, mitotic/septin disruption)
TTF_ACTIVE  : 0      : 1 = continuous 150 kHz TTFields device active (STELLAR-style)
EMAX_TTF    : 0.020   : 1/day incremental kill when active

//--- Surgery / pleurodesis (instantaneous events, not continuous PD; see [MAIN]/doses)
SURG_DEBULK_FRAC : 0.85 : fractional tumor-volume reduction at EPP/P-D event
TALC_EFF_FRAC : 0.55    : fractional effusion reduction at pleurodesis event

//--- Pleural effusion dynamics
KIN_EFF     : 0.60   : a.u./day formation scale (VEGF/tumor-driven)
KOUT_EFF    : 0.045  : 1/day drainage/resorption

//--- Mesothelin biomarker (SMRP surrogate), correlates with epithelioid burden
KIN_SMRP    : 0.50
KOUT_SMRP   : 0.12
SMRP_TUM_SCALE : 1.0

//--- Renal function (cisplatin nephrotoxicity)
KOUT_CRCL   : 0.02
CIS_NEPHRO_SLOPE : 0.55 : mL/min CrCl loss per cumulative AUC unit

//--- Myelosuppression (simplified 3-cpt Friberg: Prol -> Transit -> Circ)
ANC0        : 4.5    : baseline ANC (10^9/L)
MTT         : 5.0    : days mean transit time
SLOPE_MYELO : 0.0060 : drug-effect slope on proliferating pool (per mg/L-day cisplatin+pemetrexed surrogate)
GAMMA_ANC   : 0.17   : feedback exponent

//--- ECOG / QoL & survival hazard
KOUT_ECOG   : 0.05
SCALE_ECOG_TUM : 0.0009
SCALE_ECOG_EFF : 0.010
HAZ_BASE    : 0.0028 : 1/day background hazard
HAZ_TUM_SLOPE : 0.0000070 : hazard increment per unit tumor burden
HAZ_ECOG_SLOPE: 0.0060

[CMT] @annotated
CIS_C1      : Cisplatin central (mg)
CIS_C2      : Cisplatin peripheral (mg)
PEM_C1      : Pemetrexed central (mg)
PEM_C2      : Pemetrexed peripheral (mg)
BEV_C1      : Bevacizumab central (mg)
BEV_C2      : Bevacizumab peripheral (mg)
NIVO_C1     : Nivolumab central (mg)
NIVO_C2     : Nivolumab peripheral (mg)
IPI_C1      : Ipilimumab central (mg)
IPI_C2      : Ipilimumab peripheral (mg)
ADC_C1      : Anetumab ravtansine central (mg)
ADC_C2      : Anetumab ravtansine peripheral (mg)
GUT_RUCA    : Rucaparib gut depot (mg)
RUCA_C1     : Rucaparib central (mg)
TUM_EPI     : Epithelioid tumor burden (a.u.)
TUM_SARC    : Sarcomatoid tumor burden (a.u.)
EFF         : Pleural effusion volume (a.u., 0-100)
SMRP        : Serum mesothelin biomarker (a.u.)
CRCL        : Creatinine clearance (mL/min)
ANC_PROL    : Marrow proliferating neutrophil pool (10^9/L)
ANC_TRANS   : Marrow transit neutrophil pool (10^9/L)
ANC_CIRC    : Circulating ANC (10^9/L)
ECOG        : ECOG performance-status score (0-4, continuous surrogate)
HAZARD      : Cumulative mortality hazard (a.u.)

[MAIN]
CIS_C1_0=0; CIS_C2_0=0; PEM_C1_0=0; PEM_C2_0=0;
BEV_C1_0=0; BEV_C2_0=0; NIVO_C1_0=0; NIVO_C2_0=0;
IPI_C1_0=0; IPI_C2_0=0; ADC_C1_0=0; ADC_C2_0=0;
GUT_RUCA_0=0; RUCA_C1_0=0;

TUM_EPI_0  = TUM0 * (1 - HIST_SARC_FRAC);
TUM_SARC_0 = TUM0 * HIST_SARC_FRAC;
EFF_0      = EFF0;
SMRP_0     = KIN_SMRP/KOUT_SMRP * (TUM_EPI_0/100.0) * SMRP_TUM_SCALE;
CRCL_0     = CRCL0;
double anc_ss = ANC0;
ANC_PROL_0 = anc_ss; ANC_TRANS_0 = anc_ss; ANC_CIRC_0 = anc_ss;
ECOG_0     = ECOG0;
HAZARD_0   = 0;

[ODE]
// ---------- PK ----------
double CCIS = CIS_C1 / V1_CIS;
double CPEM = PEM_C1 / V1_PEM;
double CBEV = BEV_C1 / V1_BEV;
double CNIVO = NIVO_C1 / V1_NIVO;
double CIPI  = IPI_C1 / V1_IPI;
double CADC  = ADC_C1 / V1_ADC;
double CRUCA = RUCA_C1 / V_RUCA;

dxdt_CIS_C1 = -(CL_CIS/V1_CIS)*CIS_C1 - (Q_CIS/V1_CIS)*CIS_C1 + (Q_CIS/V2_CIS)*CIS_C2;
dxdt_CIS_C2 =  (Q_CIS/V1_CIS)*CIS_C1 - (Q_CIS/V2_CIS)*CIS_C2;

dxdt_PEM_C1 = -(CL_PEM/V1_PEM)*PEM_C1 - (Q_PEM/V1_PEM)*PEM_C1 + (Q_PEM/V2_PEM)*PEM_C2;
dxdt_PEM_C2 =  (Q_PEM/V1_PEM)*PEM_C1 - (Q_PEM/V2_PEM)*PEM_C2;

dxdt_BEV_C1 = -(CL_BEV/V1_BEV)*BEV_C1 - (Q_BEV/V1_BEV)*BEV_C1 + (Q_BEV/V2_BEV)*BEV_C2;
dxdt_BEV_C2 =  (Q_BEV/V1_BEV)*BEV_C1 - (Q_BEV/V2_BEV)*BEV_C2;

dxdt_NIVO_C1 = -(CL_NIVO/V1_NIVO)*NIVO_C1 - (Q_NIVO/V1_NIVO)*NIVO_C1 + (Q_NIVO/V2_NIVO)*NIVO_C2;
dxdt_NIVO_C2 =  (Q_NIVO/V1_NIVO)*NIVO_C1 - (Q_NIVO/V2_NIVO)*NIVO_C2;

dxdt_IPI_C1 = -(CL_IPI/V1_IPI)*IPI_C1 - (Q_IPI/V1_IPI)*IPI_C1 + (Q_IPI/V2_IPI)*IPI_C2;
dxdt_IPI_C2 =  (Q_IPI/V1_IPI)*IPI_C1 - (Q_IPI/V2_IPI)*IPI_C2;

dxdt_ADC_C1 = -(CL_ADC/V1_ADC)*ADC_C1 - (Q_ADC/V1_ADC)*ADC_C1 + (Q_ADC/V2_ADC)*ADC_C2;
dxdt_ADC_C2 =  (Q_ADC/V1_ADC)*ADC_C1 - (Q_ADC/V2_ADC)*ADC_C2;

dxdt_GUT_RUCA = -KA_RUCA*GUT_RUCA;
dxdt_RUCA_C1  =  F_RUCA*KA_RUCA*GUT_RUCA - (CL_RUCA/V_RUCA)*RUCA_C1;

// ---------- Drug-effect fractions (0-1, additive-independent Bliss combination) ----------
double CIS_kill_epi  = EMAX_CIS_EPI * CCIS/(EC50_CIS + CCIS);
double CIS_kill_sarc = CIS_kill_epi * EMAX_CIS_SARC_REL;
double PEM_kill_epi  = EMAX_PEM_EPI * CPEM/(EC50_PEM + CPEM);
double PEM_kill_sarc = PEM_kill_epi * EMAX_PEM_SARC_REL;

double BEV_growth_inhib = EMAX_BEV_GROWTH * CBEV/(EC50_BEV + CBEV);
double BEV_eff_inhib    = EMAX_BEV_EFF   * CBEV/(EC50_BEV + CBEV);

double NIVO_occ = CNIVO/(EC50_NIVO + CNIVO);
double IPI_occ  = CIPI /(EC50_IPI  + CIPI);
double io_synergy = 1.0 + (IPI_SYNERGY - 1.0) * (NIVO_occ>0.05 ? IPI_occ : 0.0);
double pdl1_mult = PDL1_HIGH>0 ? PDL1_BOOST : 1.0;
double IO_kill_epi  = EMAX_IO_EPI * NIVO_occ * io_synergy * pdl1_mult;
double IO_kill_sarc = IO_kill_epi * EMAX_IO_SARC_REL;

double msln_gate = MSLN_HIGH>0 ? 1.0 : MSLN_GATE_LOW;
double ADC_kill_epi = EMAX_ADC * msln_gate * CADC/(EC50_ADC + CADC);
double ADC_kill_sarc = ADC_kill_epi * 0.30;

double bap1_gate = BAP1_DEFICIENT>0 ? 1.0 : RUCA_GATE_LOW;
double RUCA_kill = EMAX_RUCA * bap1_gate * CRUCA/(EC50_RUCA + CRUCA);

double TTF_kill = TTF_ACTIVE>0 ? EMAX_TTF : 0.0;

double kill_epi  = CIS_kill_epi + PEM_kill_epi + IO_kill_epi + ADC_kill_epi + RUCA_kill + TTF_kill;
double kill_sarc = CIS_kill_sarc + PEM_kill_sarc + IO_kill_sarc + ADC_kill_sarc + RUCA_kill + TTF_kill;
if (kill_epi > 0.95) kill_epi = 0.95;
if (kill_sarc > 0.95) kill_sarc = 0.95;

// ---------- Tumor dynamics (logistic growth minus drug kill minus background death) ----------
double TUM_TOT = TUM_EPI + TUM_SARC + 1e-6;
double growth_brake = (1.0 - TUM_TOT/TUM_CAP);
if (growth_brake < 0) growth_brake = 0;
double g_epi  = KG_EPI  * (1.0 - BEV_growth_inhib) * growth_brake;
double g_sarc = KG_SARC * (1.0 - BEV_growth_inhib*0.5) * growth_brake;

dxdt_TUM_EPI  = g_epi*TUM_EPI  - (kill_epi + KDEATH_BASE)*TUM_EPI;
dxdt_TUM_SARC = g_sarc*TUM_SARC - (kill_sarc + KDEATH_BASE)*TUM_SARC;

// ---------- Pleural effusion ----------
double EFF_drive = KIN_EFF * (TUM_TOT/100.0) * (1.0 - BEV_eff_inhib);
dxdt_EFF = EFF_drive - KOUT_EFF*EFF;

// ---------- Mesothelin biomarker (tracks epithelioid burden with lag) ----------
double SMRP_target = (KIN_SMRP/KOUT_SMRP) * (TUM_EPI/100.0) * SMRP_TUM_SCALE;
dxdt_SMRP = KOUT_SMRP * (SMRP_target - SMRP);

// ---------- Renal function (cisplatin nephrotoxic) ----------
double cis_renal_load = FR_RENAL_CIS * CCIS;
dxdt_CRCL = -CIS_NEPHRO_SLOPE*cis_renal_load + KOUT_CRCL*(CRCL0 - CRCL)*0.05;

// ---------- Myelosuppression (3-cpt Friberg-like) ----------
double myelo_drive = SLOPE_MYELO * (CCIS + CPEM);
if (myelo_drive > 0.90) myelo_drive = 0.90;
double fb = pow(ANC0/(ANC_CIRC+1e-6), GAMMA_ANC);
double ktr = 4.0/MTT;
dxdt_ANC_PROL  = ktr*ANC_PROL*((1.0-myelo_drive)*fb - 1.0);
dxdt_ANC_TRANS = ktr*(ANC_PROL - ANC_TRANS);
dxdt_ANC_CIRC  = ktr*(ANC_TRANS - ANC_CIRC);

// ---------- ECOG / functional status ----------
double ECOG_target = ECOG0 + SCALE_ECOG_TUM*(TUM_TOT-TUM0) + SCALE_ECOG_EFF*(EFF-EFF0);
if (ECOG_target < 0) ECOG_target = 0;
if (ECOG_target > 4) ECOG_target = 4;
dxdt_ECOG = KOUT_ECOG*(ECOG_target - ECOG);

// ---------- Cumulative mortality hazard ----------
double haz_rate = HAZ_BASE + HAZ_TUM_SLOPE*TUM_TOT + HAZ_ECOG_SLOPE*ECOG;
dxdt_HAZARD = haz_rate;

[TABLE]
capture conc_cisplatin   = CIS_C1 / V1_CIS;
capture conc_pemetrexed  = PEM_C1 / V1_PEM;
capture conc_bevacizumab = BEV_C1 / V1_BEV;
capture conc_nivolumab   = NIVO_C1 / V1_NIVO;
capture conc_ipilimumab  = IPI_C1 / V1_IPI;
capture conc_anetumab    = ADC_C1 / V1_ADC;
capture conc_rucaparib   = RUCA_C1 / V_RUCA;
capture Tumor_epithelioid = TUM_EPI;
capture Tumor_sarcomatoid = TUM_SARC;
capture Tumor_total       = TUM_EPI + TUM_SARC;
capture Effusion_vol      = EFF;
capture SMRP_biomarker    = SMRP;
capture CrCl_mLmin        = CRCL;
capture ANC_circulating   = ANC_CIRC;
capture ECOG_score        = ECOG;
capture Cum_hazard        = HAZARD;
capture Survival_prob     = exp(-HAZARD);

[CAPTURE]
conc_cisplatin conc_pemetrexed conc_bevacizumab conc_nivolumab conc_ipilimumab
conc_anetumab conc_rucaparib Tumor_epithelioid Tumor_sarcomatoid Tumor_total
Effusion_vol SMRP_biomarker CrCl_mLmin ANC_circulating ECOG_score Cum_hazard
Survival_prob


##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("mpm_mrgsolve_model.R")
##
##  # ---------- 10 prebuilt scenarios ----------
##
##  MPM_simulate_scenarios <- function(end_d = 252) {
##
##    sc <- list(
##      "1. Untreated / best supportive care" =
##        ev(amt=0, cmt="CIS_C1", time=0),
##
##      "2. Cisplatin+Pemetrexed q3w x6 (EMPHACIS)" =
##        seq(ev(amt=135, cmt="CIS_C1", ii=21, addl=5),
##            ev(amt=900, cmt="PEM_C1", ii=21, addl=5)),
##
##      "3. Cisplatin+Pemetrexed+Bevacizumab q3w (MAPS)" =
##        seq(ev(amt=135, cmt="CIS_C1", ii=21, addl=5),
##            ev(amt=900, cmt="PEM_C1", ii=21, addl=5),
##            ev(amt=1050, cmt="BEV_C1", ii=21, addl=11)),
##
##      "4. Nivolumab+Ipilimumab 1L (CheckMate 743)" =
##        seq(ev(amt=240, cmt="NIVO_C1", ii=14, addl=25),
##            ev(amt=63,  cmt="IPI_C1",  ii=42, addl=8)),
##
##      "5. Nivolumab monotherapy 2L (CONFIRM)" =
##        ev(amt=240, cmt="NIVO_C1", ii=14, addl=25),
##
##      "6. Nivolumab+Ipilimumab 2L (MAPS2)" =
##        seq(ev(amt=180, cmt="NIVO_C1", ii=14, addl=25),
##            ev(amt=63,  cmt="IPI_C1",  ii=42, addl=8)),
##
##      "7. TTFields + Cisplatin/Pemetrexed (STELLAR)" =
##        # run with mod %>% param(TTF_ACTIVE=1) %>% mrgsim(...)
##        seq(ev(amt=135, cmt="CIS_C1", ii=21, addl=5),
##            ev(amt=900, cmt="PEM_C1", ii=21, addl=5)),
##
##      "8. Anetumab ravtansine (mesothelin-high)" =
##        ev(amt=455, cmt="ADC_C1", ii=21, addl=11),
##
##      "9. Rucaparib (BAP1-deficient, MiST1)" =
##        ev(amt=600, cmt="GUT_RUCA", ii=0.5, addl=2*end_d),  # 600 mg PO BID
##
##      "10. Surgery (P/D) + adjuvant chemo + talc pleurodesis" =
##        seq(ev(amt=0, cmt="TUM_EPI", time=1, method="replace"),  # apply SURG_DEBULK_FRAC via param()/idata in R
##            ev(amt=135, cmt="CIS_C1", ii=21, addl=5),
##            ev(amt=900, cmt="PEM_C1", ii=21, addl=5))
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      mod %>% mrgsim(e, end=end_d, delta=1) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Cisplatin+Pemetrexed (EMPHACIS)      : median OS 12.1 vs 9.3 mo (cisplatin alone)
##  # +Bevacizumab (MAPS)                  : median OS 18.8 vs 16.1 mo
##  # Nivolumab+Ipilimumab 1L (CheckMate743): median OS 18.1 vs 14.1 mo (chemo)
##  # Nivolumab 2L (CONFIRM)               : median OS 9.2 vs 6.6 mo (placebo); PFS HR 0.67
##  # Nivolumab+-Ipilimumab 2L (MAPS2)     : disease control ~44-50% at 12 wk
##  # TTFields+chemo (STELLAR)             : median OS 18.2 mo vs ~12 mo historical control
##  # Rucaparib BAP1-deficient (MiST1)     : disease control rate ~58% at 12 wk
##  # Anetumab ravtansine (ARCS-M Ph2)     : PFS similar to vinorelbine, MSLN-high subgroup benefit
##  # MARS/MARS2 (EPP / extended P-D)      : surgery arms did NOT improve OS vs chemo alone;
##  #                                         MARS2: 24.8 mo (chemo alone) vs 19.3 mo (surgery+chemo)
##
##  # ---------- Quick sanity plots ----------
##  # df <- MPM_simulate_scenarios(252)
##  # ggplot(df, aes(time, Tumor_total, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, Survival_prob, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, SMRP_biomarker, colour=scenario)) + geom_line()
##  # ggplot(df, aes(time, ANC_circulating, colour=scenario)) + geom_line()
