##  ============================================================================
##  Barrett's Esophagus (BE) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Barrett's esophagus — chronic acid + bile (duodenogastro-
##             esophageal) reflux injures the distal squamous epithelium ->
##             NF-kB / IL-6-STAT3 inflammation and bile-acid-driven CDX2 /
##             SOX9 / HNF4A reprogramming replace it with specialized
##             intestinal (columnar, goblet-cell) metaplasia -> within that
##             metaplastic field, a stepwise clonal evolution (CDKN2A/p16 loss
##             EARLY -> TP53 mutation as the LGD->HGD gatekeeper -> whole-
##             genome doubling / aneuploidy) drives non-dysplastic BE (NDBE)
##             -> low-grade dysplasia (LGD) -> high-grade dysplasia (HGD) ->
##             intramucosal -> invasive esophageal adenocarcinoma (EAC).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 32 ODE compartments —
##             (a) PK/PD: esomeprazole (enteric depot -> plasma -> covalent
##                 H+/K+-ATPase inhibition with pump resynthesis, CYP2C19
##                 phenotype scaling), vonoprazan (P-CAB), aspirin (plasma ->
##                 irreversible COX acetylation -> mucosal COX activity),
##                 UDCA, plus decaying pulse drivers for RFA ablation and
##                 EMR/ESD;
##             (b) reflux/injury axis: acid exposure time (AET, % pH<4),
##                 esophageal bile exposure, epithelial injury / oxidative DNA
##                 damage, mucosal inflammation, tissue PGE2, serum gastrin;
##             (c) metaplasia: CDX2 drive, Barrett segment length (Prague M),
##                 Ki-67 proliferative index, post-ablation neosquamous
##                 re-epithelialization, post-ablation stricture;
##             (d) clonal evolution: p16-null clone fraction, LGD fraction,
##                 TP53-mutant fraction OF THE DYSPLASTIC POOL, HGD fraction,
##                 aneuploidy index, invasive EAC burden;
##             (e) clinical endpoints: symptom score and two cumulative-
##                 incidence integrators (EAC alone; AspECT composite of
##                 HGD-or-EAC).
##  Time     : DAYS. Default horizon 3650 d (10 years) — the AspECT trial ran
##             a median 8.9 years, and BE natural history is a decade-scale
##             process, so short horizons are not informative.
##  Units    : Oral drug amounts in dose-proportional arbitrary units (au):
##             1.0 au = esomeprazole 20 mg = aspirin 300 mg = vonoprazan 20 mg
##             (this library's convention when the disease-relevant PD, not
##             plasma concentration, is the object of interest). Physiological
##             states in clinically familiar units: AET %, segment length cm,
##             gastrin pg/mL, Ki-67 %, clone fractions 0-1, cumulative
##             incidence 0-1.
##  Scenarios: 10 prebuilt — see BE_simulate_scenarios() at the bottom
##             (AspECT 2x2 factorial arms, SURF ablation-vs-surveillance in
##             confirmed LGD, vonoprazan, fundoplication, EMR+RFA for HGD,
##             CYP2C19 pharmacogenomics, weight loss in central obesity).
##
##  ---- THE MECHANISTIC TENSION THIS MODEL IS BUILT TO EXPRESS --------------
##  Acid suppression is not the same thing as reflux suppression. A PPI
##  removes the H+ arm of the insult (and inactivates pepsin above pH 4) but
##  does NOT stop the volume reflux that delivers bile acids to the
##  esophagus — and deoxycholate/unconjugated bile acids are MORE membrane-
##  permeant and more potent inducers of NF-kB -> CDX2 at neutral pH than in
##  acid. On top of that, profound acid suppression raises gastrin 2-4x, and
##  gastrin is trophic to Barrett epithelium through CCK2R. The model encodes
##  both terms (K_PH_BILE > 0, K_GAS_KI > 0), so high-dose PPI produces a
##  large drop in acid exposure and symptoms but only a PARTIAL reduction in
##  the mutational drive that governs progression — which is why AspECT's
##  high-dose-PPI hazard ratio was 0.73 rather than near zero, and why adding
##  aspirin (which acts on the PGE2/apoptosis arm the PPI cannot reach) was
##  additive (HR 0.59 for the combination). Any parameterization that makes
##  PPI monotherapy abolish progression has broken this tension.
##  --------------------------------------------------------------------------
##
##  Anchors  : AspECT (Jankowski 2018 Lancet 392:400) — 2557 patients, 2x2
##             factorial esomeprazole 40 mg BID vs 20 mg OD +/- aspirin 300 mg,
##             median 8.9 y, composite of all-cause mortality/EAC/HGD: high-
##             dose PPI HR 0.73, aspirin HR 0.93 (NS alone), high-dose PPI +
##             aspirin vs low-dose PPI alone HR 0.59.
##             SURF (Phoa 2014 JAMA 311:1209) — confirmed LGD, RFA vs
##             surveillance: progression to HGD/EAC 1.5% vs 26.5% at 3 y.
##             AIM Dysplasia (Shaheen 2009 NEJM 360:2277) — RFA: CE-D 90.5%,
##             CE-IM 77.4%, stricture 6%.
##             Hvid-Jensen 2011 NEJM 365:1375 — Danish nationwide cohort,
##             11,028 BE patients: EAC incidence 1.2 per 1000 person-years
##             (0.12%/yr) in NDBE.
##             Duits 2015 Gut 64:700 — expert-confirmed LGD progresses at
##             ~9%/yr; 73% of community LGD is downstaged on review.
##             Prague C&M criteria: Sharma 2006 Gastroenterology 131:1392.
##             Segment length: ~1.7x risk per additional 2 cm
##             (Anaparthy 2013 Clin Gastroenterol Hepatol 11:1430).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================

[PROB]
QSP model of Barrett's esophagus linking acid + bile reflux exposure,
epithelial injury and oxidative DNA damage, NF-kB/IL-6 inflammation, tissue
PGE2, bile-acid-driven CDX2 metaplastic reprogramming, Barrett segment length
(Prague M), and a stepwise CDKN2A -> TP53 -> aneuploidy clonal cascade
through LGD and HGD to invasive esophageal adenocarcinoma — with mechanistic
PK/PD for esomeprazole (covalent proton-pump inhibition + resynthesis +
CYP2C19 phenotype + hypergastrinemia), vonoprazan (P-CAB), aspirin
(irreversible COX acetylation), UDCA, and pulse drivers for radiofrequency
ablation and EMR/ESD, plus antireflux surgery and weight-loss interventions.

[PLUGIN] Rcpp

[GLOBAL]
#define HILLF(x, k, n) (pow((x) < 0 ? 0 : (x), (n)) / (pow((x) < 0 ? 0 : (x), (n)) + pow((k), (n))))
#define POSF(x) ((x) < 0 ? 0 : (x))

// (a) File-scope references computed in [MAIN] from PARAMETERS ONLY (the
//     untreated baseline state of this particular patient) and used in [ODE]
//     to normalize the drive terms so that MUT == 1 in the untreated baseline.
//     Every one of them is a pure function of the parameter vector, so
//     recomputing them at each record is harmless.
double ref_bile_eff;
double ref_injury;
double ref_inflam;
double ref_pge2;
double ref_cdx_drive;
double ref_ki67;
double ref_be_len;
double ref_cdx2_0;

// (b) Derived quantities that [ODE] computes and [TABLE] reports. These MUST
//     live at file scope: variables declared inside [ODE] are out of scope in
//     [TABLE], so declaring them here is what makes the capture block legal.
//     [TABLE] runs after the solve, so these hold the values from the last
//     ODE evaluation at (or immediately before) the output time.
double g_ppi_block;
double g_vpz_block;
double g_acid_block;
double g_cox_inhib;
double g_udca_block;
double g_bile_eff;
double g_abl_eff;
double g_emr_eff;
double g_seg_factor;
double g_MUT;
double g_haz_lgd;
double g_haz_hgd;
double g_haz_eac;

[PARAM] @annotated
//--- Patient / baseline reflux phenotype -------------------------------------
BASE_AET     : 12.0  : %, off-therapy acid exposure time (% of 24 h with pH<4; normal <4%)
BASE_BILE    : 35.0  : index 0-100, off-therapy esophageal bile-acid exposure (Bilitec-like)
BASE_BE_LEN  : 3.0   : cm, Prague M (maximal) extent of the Barrett segment at t=0
HH_SIZE      : 3.0   : cm, axial hiatal hernia size (3 cm = model reference)
OBESITY      : 0.50  : 0-1, visceral adiposity level (waist-hip-ratio surrogate)
SMOKE        : 1     : 1 = current smoker (oxidative + APOBEC mutational load)
SEX_M        : 1     : 1 = male
AGE0         : 58    : years, age at simulation start

//--- Baseline clonal architecture of the segment (prevalent, not incident) ---
INIT_FP16    : 0.45  : fraction of segment carrying CDKN2A/p16 loss (early, common)
INIT_FLGD    : 0.03  : fraction of segment with low-grade dysplasia
INIT_FP53    : 0.05  : fraction of segment carrying TP53 mutation / aberrant p53 IHC
INIT_FHGD    : 0.00  : fraction of segment with high-grade dysplasia
INIT_ANEUPL  : 0.05  : 0-1, aneuploidy / DNA-content abnormality index

//--- Esomeprazole PK (oral, enteric-coated; 1.0 au = 20 mg) ------------------
KA_PPI       : 6.0   : 1/day, enteric-coated absorption rate
KE_PPI       : 8.0   : 1/day, elimination (t1/2 ~2 h in a normal metabolizer)
CL2C19       : 1.0   : CYP2C19 phenotype clearance multiplier (UM 1.8, RM 1.4, NM 1.0, IM 0.55, PM 0.25)
KINH_PUMP    : 3.26  : 1/(au*day), covalent (irreversible) H+/K+-ATPase inactivation
KSYN_PUMP    : 0.333 : 1/day, de-novo pump resynthesis (t1/2 ~50 h)

//--- Vonoprazan PK/PD (potassium-competitive acid blocker; 1.0 au = 20 mg) ---
KA_VPZ       : 8.0   : 1/day, absorption
KE_VPZ       : 2.4   : 1/day, elimination (t1/2 ~7 h; minimal CYP2C19 dependence)
EMAX_VPZ     : 0.92  : max fractional acid-output blockade
EC50_VPZ     : 0.18  : au, plasma concentration for half-maximal blockade

//--- Aspirin PK/PD (1.0 au = 300 mg) ----------------------------------------
KA_ASA       : 15.0  : 1/day, absorption
KE_ASA       : 6.0   : 1/day, salicylate elimination (t1/2 ~2.8 h)
KACET_COX    : 22.0  : 1/(au*day), irreversible COX-1/COX-2 Ser acetylation
KREC_COX     : 0.50  : 1/day, mucosal COX activity recovery via cell turnover

//--- UDCA (bile-pool hydrophobicity modifier; 1.0 au = 300 mg BID) ----------
KE_UDCA      : 1.2   : 1/day, elimination
EMAX_UDCA    : 0.30  : max fractional reduction in effective bile toxicity
EC50_UDCA    : 0.5   : au

//--- Non-pharmacologic reflux interventions ---------------------------------
FUNDO        : 0     : 1 = antireflux surgery / magnetic sphincter augmentation performed
FUNDO_START  : 365   : day of antireflux surgery
EFF_FUNDO_A  : 0.80  : fractional reduction in acid exposure after surgery
EFF_FUNDO_B  : 0.70  : fractional reduction in bile exposure after surgery (drugs cannot do this)
BACLOFEN     : 0     : 1 = baclofen (GABA-B) on board, reduces TLESRs
EFF_BACLO    : 0.25  : fractional reduction in reflux events
ALGINATE     : 0     : 1 = alginate raft therapy
EFF_ALG      : 0.15  : fractional reduction in postprandial reflux
WL_START     : 1e6   : day weight-loss intervention starts (1e6 = never)
WL_MAG       : 0.50  : fractional reduction in visceral adiposity achieved
KOUT_ADI     : 0.02  : 1/day, adiposity turnover (t1/2 ~35 d)
K_OBES_REFL  : 0.0859  : mechanical amplification of reflux per unit adiposity

//--- Reference patient defining the absolute scale of the mutational drive ---
// MUT is normalized to a FIXED reference patient, NOT to each individual's own
// baseline. If it were normalized per-patient, every covariate (obesity,
// smoking, baseline AET/bile) would cancel out of the risk calculation.
REF_AET      : 12.0  : %, reference off-therapy acid exposure time
REF_BILE     : 35.0  : index, reference off-therapy bile exposure
REF_OBESITY  : 0.50  : reference visceral adiposity
REF_SMOKE    : 1.0   : reference smoking status

//--- Reflux -> injury -> inflammation axis ----------------------------------
KOUT_ACID    : 1.0   : 1/day, AET equilibration
KOUT_BILE    : 1.0   : 1/day, bile-exposure equilibration
K_PH_BILE    : 0.35    : max bile-toxicity amplification at neutral pH (unconjugated, membrane-permeant)
PH_BILE_HALF : 0.25    : acid blockade giving half-maximal bile-toxicity amplification
PH_BILE_N    : 2.0      : Hill coefficient (bile-acid ionization is sigmoid in luminal pH)
W_ACID_INJ   : 0.4593: injury weight of acid exposure (applied to AET^ACID_POW)
ACID_POW     : 1.9891   : CONVEX exponent on AET - long/deep acid exposures dominate damage
W_BILE_INJ   : 0.6027  : injury weight of effective bile exposure
W_SMOKE_INJ  : 8.0      : additive injury from current smoking
KOUT_INJ     : 0.10  : 1/day, injury / 8-OHdG turnover
KOUT_INF     : 0.08  : 1/day, mucosal inflammation turnover
INFLAM_BASE  : 4.0   : index, inflammation floor
K_INJ_INF    : 0.85  : inflammation per unit injury
K_ADI_INF    : 6.0     : adipose-derived IL-6/TNF contribution to inflammation
PGE2_BASE    : 8.0   : pg/mg, COX-1-derived constitutive PGE2
K_INF_PGE2   : 1.10  : COX-2-derived PGE2 per unit inflammation
KOUT_PGE2    : 0.60  : 1/day, PGE2 turnover

//--- Gastrin / CCK2R trophic feedback ---------------------------------------
GASTRIN_BASE : 35.0  : pg/mL, fasting serum gastrin off therapy
K_GASTRIN    : 2.50  : fold-rise coefficient for acid blockade (gives 3-4x on high-dose PPI)
KOUT_GASTRIN : 0.50  : 1/day, gastrin equilibration

//--- Metaplastic reprogramming / segment length -----------------------------
K_BILE_CDX2  : 0.030 : CDX2 drive per unit effective bile exposure
K_INF_CDX2   : 0.016 : CDX2 drive per unit inflammation
CDX2_HALF    : 1.00  : half-maximal composite drive for CDX2 induction
CDX2_N       : 2.0   : Hill coefficient for CDX2 induction
KOUT_CDX2    : 0.025 : 1/day, CDX2 program turnover (t1/2 ~28 d)
K_LEN        : 0.0004 : 1/day, segment remodeling toward its drive-set target (tau ~2500 d;
                     //         sets post-ablation regrowth at ~8-10 %/yr, per Cotton 2018)
BE_MAX       : 12.0  : cm, maximum attainable segment length
SEED_BURIED  : 0.15  : cm-equivalent residual/buried intestinal glands after ablation

//--- Proliferation / apoptosis balance --------------------------------------
// Proliferation has a COX-INDEPENDENT arm (K_INF_KI, IL-6/STAT3) that aspirin
// cannot touch and a small COX-DEPENDENT arm (K_PGE2_KI) that it can. That
// split is what keeps aspirin's effect as modest as AspECT actually measured.
KI67_BASE    : 10.6     : %, Ki-67 floor of quiescent metaplastic epithelium
K_INF_KI     : 0.07609  : Ki-67 per unit inflammation (IL-6/STAT3, COX-INDEPENDENT)
K_PGE2_KI    : 0.003663 : Ki-67 per unit PGE2 (EP2/EP4 -> cyclin D1; the aspirin target)
K_GAS_KI     : 4.00    : Ki-67 per unit fractional gastrin rise (CCK2R trophic effect)
K_ADI_KI     : 4.00    : Ki-67 contribution of PI3K/AKT (leptin, insulin/IGF-1)
K_ASA_KI     : 0.0      : direct antiproliferative effect of COX inhibition (0 = acts only via PGE2)
K_ASA_REG    : 0.09415  : acceleration of LGD regression per unit COX inhibition (apoptosis restoration)
KOUT_KI67    : 0.15  : 1/day, proliferative-index equilibration

//--- Clonal evolution cascade (per-day transition rates) --------------------
K_P16        : 3.0e-4: 1/day, CDKN2A/p16 loss acquisition (per unit mutational drive)
KREG_P16     : 1.0e-4: 1/day, p16-null clone loss
K_LGD        : 1.2e-4: 1/day, LGD emergence within the p16-null field
KREG_LGD     : 2.0e-3: 1/day, LGD regression / downstaging
K_P53        : 0.09341: 1/day, TP53 mutation acquisition within LGD
KREG_P53     : 2.0e-4: 1/day, TP53-mutant clone loss
K_HGD        : 5.503e-3: 1/day, LGD -> HGD transition (TP53-gated)
KREG_HGD     : 5.0e-4: 1/day, HGD regression
K_EAC        : 2.774e-4: 1/day, HGD -> invasive EAC transition
K_ANEU       : 1.2e-3: 1/day, aneuploidy accumulation in TP53-mutant clones
KOUT_ANEU    : 3.0e-4: 1/day, aneuploidy clearance
K_ANEU_EAC   : 1.50  : amplification of the EAC transition by aneuploidy
SEG_REF      : 3.0   : cm, reference segment length for the length-risk scaling
SEG_POW      : 1.00  : exponent of segment-length risk scaling (~1.7x per 2 cm)
EAC_SEED     : 1.0   : burden units generated per unit EAC transition rate
K_GROW_EAC   : 0.008 : 1/day, invasive tumor growth (doubling ~87 d)
EAC_MAX      : 100.0 : burden units, carrying capacity

//--- Endoscopic eradication therapy ----------------------------------------
KOUT_ABL     : 0.15  : 1/day, decay of one ablation session's effect (t1/2 ~4.6 d)
EMAX_ABL     : 0.95  : maximal fractional ablation effect
EC50_ABL     : 0.25  : au
K_ABL_LEN    : 0.55  : 1/day, metaplastic length ablated per unit effect
K_ABL_DYS    : 0.85  : 1/day, dysplastic clone fraction ablated per unit effect
K_NEO        : 0.35  : 1/day, neosquamous re-epithelialization
K_NEO_LOSS   : 0.010 : 1/day, loss of neosquamous cover under persistent reflux
K_STRICT     : 0.008  : 1/day, stricture formation per unit ablation effect (a 3-4 session
                     //         course lands in the reported 6-12% band)
KOUT_STRICT  : 0.010 : 1/day, stricture resolution / dilation
KOUT_EMR     : 0.35  : 1/day, decay of one EMR/ESD session's effect
EMAX_EMR     : 0.98  : maximal fractional resection effect on a visible lesion
EC50_EMR     : 0.25  : au
K_EMR_EAC    : 1.20  : 1/day, intramucosal tumor burden resected per unit effect

//--- Symptoms & safety readouts --------------------------------------------
SYMPT_MAX    : 10.0  : points, maximal heartburn/regurgitation score
SYMPT_HALF   : 12.0  : composite exposure giving half-maximal symptom score
W_ACID_SYM   : 1.00  : symptom weight of acid exposure
W_BILE_SYM   : 0.35  : symptom weight of bile exposure
KOUT_SYMPT   : 0.30  : 1/day, symptom equilibration
BLEED_BASE   : 0.35  : %/yr, background upper-GI bleeding rate
K_ASA_BLEED  : 2.20  : bleeding amplification per unit COX inhibition
K_PPI_PROTEC : 0.45  : fractional bleeding reduction from full acid blockade

[CMT] @annotated
PPI_DEPOT  : Esomeprazole enteric-coated absorption depot (au)
PPI_CENT   : Esomeprazole plasma compartment (au)
PUMP       : Active gastric H+/K+-ATPase pool (fraction of normal, 0-1)
GASTRIN    : Fasting serum gastrin (pg/mL)
ASA_DEPOT  : Aspirin absorption depot (au)
ASA_CENT   : Aspirin / salicylate plasma compartment (au)
COX        : Mucosal COX-1/COX-2 catalytic activity (fraction of normal, 0-1)
VPZ_DEPOT  : Vonoprazan absorption depot (au)
VPZ_CENT   : Vonoprazan plasma compartment (au)
UDCA_CENT  : Ursodeoxycholic acid exposure (au)
ABL_PULSE  : Radiofrequency-ablation session effect driver (au, decaying)
EMR_PULSE  : EMR/ESD session effect driver (au, decaying)
ACID        : Esophageal acid exposure time (AET, % of 24 h with pH<4)
BILE        : Esophageal bile-acid exposure (index 0-100)
INJURY      : Epithelial injury / oxidative DNA damage index (8-OHdG surrogate)
INFLAM      : Mucosal inflammatory signal (NF-kB/IL-6/IL-8 composite index)
PGE2        : Tissue prostaglandin E2 (pg/mg)
CDX2        : Intestinal metaplastic transcriptional drive (0-1)
BE_LEN      : Barrett segment length, Prague M (cm)
KI67        : Epithelial proliferative index (Ki-67 %)
FP16        : Segment fraction carrying CDKN2A/p16 loss (0-1)
FLGD        : Segment fraction with low-grade dysplasia (0-1)
FP53        : TP53-mutant fraction of the DYSPLASTIC clone pool (0-1; not of the whole segment - see README)
FHGD        : Segment fraction with high-grade dysplasia (0-1)
ANEUPL      : Aneuploidy / genomic instability index (0-1)
EAC         : Invasive esophageal adenocarcinoma burden (0-100)
ADIPO       : Visceral adiposity signal (0-1)
NEOSQ       : Neosquamous re-epithelialized fraction after ablation (0-1)
STRICT      : Post-ablation stricture / fibrosis burden (0-1)
SYMPT       : Heartburn / regurgitation symptom score (0-10)
CUM_EAC     : Cumulative incidence of progression to EAC (probability 0-1)
CUM_COMP    : Cumulative incidence of the AspECT composite, HGD or EAC (0-1)

[MAIN]
//---------------------------------------------------------------------------
// Drug compartments start empty; the pump and COX pools start intact.
//---------------------------------------------------------------------------
PPI_DEPOT_0 = 0; PPI_CENT_0 = 0; ASA_DEPOT_0 = 0; ASA_CENT_0 = 0;
VPZ_DEPOT_0 = 0; VPZ_CENT_0 = 0; UDCA_CENT_0 = 0;
ABL_PULSE_0 = 0; EMR_PULSE_0 = 0;
PUMP_0 = 1.0;
COX_0  = 1.0;

//---------------------------------------------------------------------------
// (i) This patient's own untreated baseline (used for the initial conditions
//     and for the segment-length set point, which IS in equilibrium with the
//     patient's own drive at presentation).
//---------------------------------------------------------------------------
double refl0   = 1.0 + K_OBES_REFL * OBESITY;              // mechanical reflux amplification
double acid0   = BASE_AET  * refl0;                        // no drug on board
double bile0   = BASE_BILE * refl0;
double inj0    = W_ACID_INJ*pow(acid0, ACID_POW) + W_BILE_INJ*bile0 + W_SMOKE_INJ*SMOKE;
double inf0    = INFLAM_BASE + K_INJ_INF*inj0 + K_ADI_INF*OBESITY;
double pge0    = PGE2_BASE + K_INF_PGE2*inf0;              // COX fully active
double ki0     = KI67_BASE + K_INF_KI*inf0 + K_PGE2_KI*pge0 + K_ADI_KI*OBESITY;
ref_bile_eff   = bile0;                                    // no acid blockade -> no pH penalty
ref_cdx_drive  = K_BILE_CDX2*bile0 + K_INF_CDX2*inf0;
ref_be_len     = BASE_BE_LEN;

//---------------------------------------------------------------------------
// (ii) The FIXED REFERENCE PATIENT that sets the absolute scale of MUT. This
//      is what makes the clonal rate constants readable as "per day at
//      reference drive" AND lets covariates move absolute risk: a lean
//      non-smoker gets MUT < 1, an obese smoker MUT > 1.
//---------------------------------------------------------------------------
double rrefl   = 1.0 + K_OBES_REFL * REF_OBESITY;
double racid   = REF_AET  * rrefl;
double rbile   = REF_BILE * rrefl;
ref_injury     = W_ACID_INJ*pow(racid, ACID_POW) + W_BILE_INJ*rbile + W_SMOKE_INJ*REF_SMOKE;
ref_inflam     = INFLAM_BASE + K_INJ_INF*ref_injury + K_ADI_INF*REF_OBESITY;
ref_pge2       = PGE2_BASE + K_INF_PGE2*ref_inflam;
ref_ki67       = KI67_BASE + K_INF_KI*ref_inflam + K_PGE2_KI*ref_pge2
                 + K_ADI_KI*REF_OBESITY;                   // gastrin at its baseline

//---------------------------------------------------------------------------
// Initial conditions of the physiological states = untreated steady state.
//---------------------------------------------------------------------------
ACID_0   = acid0;
BILE_0   = bile0;
INJURY_0 = inj0;
INFLAM_0 = inf0;
PGE2_0   = pge0;
ref_cdx2_0 = pow(ref_cdx_drive, CDX2_N) / (pow(ref_cdx_drive, CDX2_N) + pow(CDX2_HALF, CDX2_N));
CDX2_0   = ref_cdx2_0;
BE_LEN_0 = BASE_BE_LEN;
KI67_0   = ki0;
GASTRIN_0 = GASTRIN_BASE;
ADIPO_0  = OBESITY;

FP16_0   = INIT_FP16;
FLGD_0   = INIT_FLGD;
FP53_0   = INIT_FP53;
FHGD_0   = INIT_FHGD;
ANEUPL_0 = INIT_ANEUPL;
EAC_0    = 0;
NEOSQ_0  = 0;
STRICT_0 = 0;
CUM_EAC_0  = 0;
CUM_COMP_0 = 0;

double sym0 = W_ACID_SYM*acid0 + W_BILE_SYM*bile0;
SYMPT_0 = SYMPT_MAX * sym0 / (SYMPT_HALF + sym0);

[ODE]
//===========================================================================
// 1. Drug PK
//===========================================================================
dxdt_PPI_DEPOT = -KA_PPI*PPI_DEPOT;
dxdt_PPI_CENT  =  KA_PPI*PPI_DEPOT - KE_PPI*CL2C19*PPI_CENT;

dxdt_ASA_DEPOT = -KA_ASA*ASA_DEPOT;
dxdt_ASA_CENT  =  KA_ASA*ASA_DEPOT - KE_ASA*ASA_CENT;

dxdt_VPZ_DEPOT = -KA_VPZ*VPZ_DEPOT;
dxdt_VPZ_CENT  =  KA_VPZ*VPZ_DEPOT - KE_VPZ*VPZ_CENT;

dxdt_UDCA_CENT = -KE_UDCA*UDCA_CENT;

dxdt_ABL_PULSE = -KOUT_ABL*ABL_PULSE;
dxdt_EMR_PULSE = -KOUT_EMR*EMR_PULSE;

//===========================================================================
// 2. Acid-suppression pharmacodynamics
//    PPI: covalent pump inactivation offset by pump resynthesis.
//    Vonoprazan: reversible K+-competitive functional blockade (Emax).
//    The two combine on the RESIDUAL acid output, not additively.
//===========================================================================
dxdt_PUMP = KSYN_PUMP*(1.0 - PUMP) - KINH_PUMP*PPI_CENT*PUMP;

double ppi_block = 1.0 - PUMP;                                  // 0-1
double vpz_block = EMAX_VPZ * VPZ_CENT/(EC50_VPZ + VPZ_CENT);
double acid_block = 1.0 - (1.0 - ppi_block)*(1.0 - vpz_block);
if (acid_block > 0.98) acid_block = 0.98;
g_ppi_block = ppi_block; g_vpz_block = vpz_block; g_acid_block = acid_block;

//===========================================================================
// 3. Aspirin pharmacodynamics — irreversible acetylation vs cell turnover
//===========================================================================
dxdt_COX = KREC_COX*(1.0 - COX) - KACET_COX*ASA_CENT*COX;
double cox_inhib = 1.0 - COX;                                   // 0-1
g_cox_inhib = cox_inhib;

//===========================================================================
// 4. Non-pharmacologic barrier interventions & adiposity
//===========================================================================
double fundo_on = (FUNDO > 0 && SOLVERTIME >= FUNDO_START) ? 1.0 : 0.0;
double barrier_a = (1.0 - EFF_FUNDO_A*fundo_on)
                 * (1.0 - EFF_BACLO*BACLOFEN)
                 * (1.0 - EFF_ALG*ALGINATE);
double barrier_b = (1.0 - EFF_FUNDO_B*fundo_on)
                 * (1.0 - EFF_BACLO*BACLOFEN);

double adipo_target = OBESITY * (SOLVERTIME >= WL_START ? (1.0 - WL_MAG) : 1.0);
dxdt_ADIPO = KOUT_ADI*(adipo_target - ADIPO);
double refl_mech = 1.0 + K_OBES_REFL*ADIPO;

//===========================================================================
// 5. Reflux exposure: acid and bile are NOT the same target
//===========================================================================
double acid_target = BASE_AET * (1.0 - acid_block) * barrier_a * refl_mech
                     * (1.0 + 0.10*(HH_SIZE/3.0 - 1.0));
if (acid_target < 0) acid_target = 0;
dxdt_ACID = KOUT_ACID*(acid_target - ACID);

double udca_block  = EMAX_UDCA * UDCA_CENT/(EC50_UDCA + UDCA_CENT);
double bile_target = BASE_BILE * barrier_b * refl_mech;         // acid suppression does not reduce volume reflux
if (bile_target < 0) bile_target = 0;
dxdt_BILE = KOUT_BILE*(bile_target - BILE);

// Effective bile toxicity RISES with acid blockade: at neutral pH bile acids
// are unconjugated / non-ionized, more membrane-permeant, and stronger
// inducers of NF-kB -> CDX2. The amplification SATURATES (Hill in acid_block)
// because bile-acid ionization is sigmoid in luminal pH: once the patient is
// above pH 4 for much of the day the penalty is essentially fully incurred,
// so it barely grows further when the dose is doubled. UDCA lowers bile-pool
// hydrophobicity and so reduces the effective toxicity directly.
double bile_eff = BILE * (1.0 + K_PH_BILE*HILLF(acid_block, PH_BILE_HALF, PH_BILE_N))
                       * (1.0 - udca_block);
g_udca_block = udca_block; g_bile_eff = bile_eff;

//===========================================================================
// 6. Injury -> inflammation -> PGE2
//    Acid injury is CONVEX in AET (ACID_POW = 2): damage is done by long,
//    deep acid exposures, and pepsin is only proteolytic below pH 4. The
//    consequence is a saturating benefit curve — most of the achievable acid
//    benefit is realized by low-dose PPI, and doubling the dose adds little.
//===========================================================================
double inj_target = W_ACID_INJ*pow(ACID, ACID_POW) + W_BILE_INJ*bile_eff
                    + W_SMOKE_INJ*SMOKE;
dxdt_INJURY = KOUT_INJ*(inj_target - INJURY);

double inf_target = INFLAM_BASE + K_INJ_INF*INJURY + K_ADI_INF*ADIPO;
dxdt_INFLAM = KOUT_INF*(inf_target - INFLAM);

double pge2_target = (PGE2_BASE + K_INF_PGE2*INFLAM) * COX;
dxdt_PGE2 = KOUT_PGE2*(pge2_target - PGE2);

//===========================================================================
// 7. Gastrin — the price of acid suppression, and a trophic signal
//===========================================================================
double gastrin_target = GASTRIN_BASE * (1.0 + K_GASTRIN*pow(acid_block, 1.5));
dxdt_GASTRIN = KOUT_GASTRIN*(gastrin_target - GASTRIN);

//===========================================================================
// 8. Metaplastic reprogramming and segment length
//===========================================================================
double cdx_drive  = K_BILE_CDX2*bile_eff + K_INF_CDX2*INFLAM;
double cdx_target = HILLF(cdx_drive, CDX2_HALF, CDX2_N);
dxdt_CDX2 = KOUT_CDX2*(cdx_target - CDX2);

double abl_eff = EMAX_ABL * ABL_PULSE/(EC50_ABL + ABL_PULSE);
double emr_eff = EMAX_EMR * EMR_PULSE/(EC50_EMR + EMR_PULSE);
g_abl_eff = abl_eff; g_emr_eff = emr_eff;

// Target segment length scales with the metaplastic drive relative to this
// patient's own untreated baseline, capped by BE_MAX.
double len_target = ref_be_len * (CDX2 / (ref_cdx2_0 > 1e-6 ? ref_cdx2_0 : 1e-6));
if (len_target > BE_MAX) len_target = BE_MAX;
dxdt_BE_LEN = K_LEN*(len_target + SEED_BURIED - BE_LEN) - K_ABL_LEN*abl_eff*BE_LEN;
if (BE_LEN < 0.02 && dxdt_BE_LEN < 0) dxdt_BE_LEN = 0;

// Neosquamous cover after ablation; lost again under persistent reflux.
dxdt_NEOSQ = K_NEO*abl_eff*(1.0 - NEOSQ)
           - K_NEO_LOSS*NEOSQ*(INJURY/(ref_injury > 1e-6 ? ref_injury : 1e-6));
dxdt_STRICT = K_STRICT*abl_eff*(1.0 - STRICT) - KOUT_STRICT*STRICT;

//===========================================================================
// 9. Proliferation / apoptosis balance -> mutational drive
//===========================================================================
// K_INF_KI is the COX-INDEPENDENT (IL-6/STAT3) proliferative arm; K_PGE2_KI is
// the COX-DEPENDENT arm, and PGE2 itself is multiplied by COX activity, so
// aspirin reaches only the second term. K_GAS_KI is the price of acid control.
double ki_target = KI67_BASE
                 + K_INF_KI*INFLAM
                 + K_PGE2_KI*PGE2
                 + K_GAS_KI*(GASTRIN/GASTRIN_BASE - 1.0)
                 + K_ADI_KI*ADIPO;
ki_target = ki_target / (1.0 + K_ASA_KI*cox_inhib);             // optional direct effect
if (ki_target < 1.0) ki_target = 1.0;
dxdt_KI67 = KOUT_KI67*(ki_target - KI67);

double inj_rel = INJURY / (ref_injury > 1e-6 ? ref_injury : 1e-6);
double ki_rel  = KI67   / (ref_ki67   > 1e-6 ? ref_ki67   : 1e-6);
double MUT = inj_rel * ki_rel;                                  // == 1 at untreated baseline
if (MUT < 0) MUT = 0;
g_MUT = MUT;

//===========================================================================
// 10. Clonal evolution cascade
//===========================================================================
double seg_factor = pow((BE_LEN + 0.05)/SEG_REF, SEG_POW);
g_seg_factor = seg_factor;

double haz_p16 = K_P16*MUT*(1.0 - FP16);
dxdt_FP16 = haz_p16 - KREG_P16*FP16 - K_ABL_DYS*abl_eff*FP16;

double haz_lgd = K_LGD*MUT*FP16*(1.0 - FLGD);
double haz_hgd = K_HGD*MUT*FP53*FLGD*(1.0 - FHGD);
dxdt_FLGD = haz_lgd
          - KREG_LGD*FLGD*(1.0 + K_ASA_REG*cox_inhib)   // aspirin: apoptosis restoration
          - haz_hgd
          - K_ABL_DYS*abl_eff*FLGD;

dxdt_FP53 = K_P53*MUT*FLGD*(1.0 - FP53) - KREG_P53*FP53 - K_ABL_DYS*abl_eff*FP53;

double haz_eac = K_EAC*MUT*FHGD*seg_factor*(1.0 + K_ANEU_EAC*ANEUPL);
g_haz_lgd = haz_lgd; g_haz_hgd = haz_hgd; g_haz_eac = haz_eac;
dxdt_FHGD = haz_hgd
          - KREG_HGD*FHGD
          - haz_eac
          - K_ABL_DYS*abl_eff*FHGD;

dxdt_ANEUPL = K_ANEU*MUT*FP53*(1.0 - ANEUPL) - KOUT_ANEU*ANEUPL;

dxdt_EAC = EAC_SEED*haz_eac
         + K_GROW_EAC*EAC*(1.0 - EAC/EAC_MAX)
         - K_EMR_EAC*emr_eff*EAC;
if (EAC < 0) EAC = 0;

//===========================================================================
// 11. Clinical endpoint integrators (competing-risk-free cumulative incidence)
//===========================================================================
dxdt_CUM_EAC  = haz_eac * (1.0 - CUM_EAC);
dxdt_CUM_COMP = (haz_hgd + haz_eac) * (1.0 - CUM_COMP);

//===========================================================================
// 12. Symptoms
//===========================================================================
double sym_drive  = W_ACID_SYM*ACID + W_BILE_SYM*BILE;
double sym_target = SYMPT_MAX * sym_drive/(SYMPT_HALF + sym_drive)
                  + 2.0*STRICT;                                  // stricture dysphagia
if (sym_target > SYMPT_MAX) sym_target = SYMPT_MAX;
dxdt_SYMPT = KOUT_SYMPT*(sym_target - SYMPT);

[TABLE]
// All derived quantities below come from the file-scope g_* variables set in
// [ODE] (see [GLOBAL] note (b)); compartment amounts are directly in scope.
//--- Pharmacology readouts ---
capture PPI_conc          = PPI_CENT;
capture Pump_active_frac  = PUMP;
capture Acid_blockade     = g_acid_block;
capture pH4_holding_pct   = 100.0*g_acid_block;               // ~% of 24 h with pH>4
capture COX_activity      = COX;
capture COX_inhibition    = g_cox_inhib;
capture Vonoprazan_block  = g_vpz_block;
capture UDCA_block        = g_udca_block;
capture Ablation_effect   = g_abl_eff;
capture EMR_effect        = g_emr_eff;

//--- Reflux / injury axis ---
capture AET_pct           = ACID;
capture DeMeester_proxy   = 14.7 * ACID/4.0;                  // 4% AET ~ score 14.7
capture Bile_exposure     = BILE;
capture Bile_effective    = g_bile_eff;
capture Injury_index      = INJURY;
capture Inflammation      = INFLAM;
capture PGE2_tissue       = PGE2;
capture Gastrin_pg_mL     = GASTRIN;
capture Gastrin_fold      = GASTRIN/GASTRIN_BASE;

//--- Metaplasia / proliferation ---
capture CDX2_drive        = CDX2;
capture Prague_M_cm       = BE_LEN;
capture LSBE_flag         = (BE_LEN >= 3.0) ? 1.0 : 0.0;
capture Ki67_pct          = KI67;
capture Mutational_drive  = g_MUT;
capture Segment_risk_mult = g_seg_factor;
capture Neosquamous_frac  = NEOSQ;
capture Stricture_burden  = STRICT;

//--- Clonal / histologic state ---
capture p16_null_frac     = FP16;
capture LGD_frac          = FLGD;
capture TP53_mut_frac     = FP53;
capture HGD_frac          = FHGD;
capture Aneuploidy        = ANEUPL;
capture EAC_burden        = EAC;

//--- Annualized hazards (%/yr) and cumulative incidence (%) ---
capture Hazard_LGD_pct_yr  = 100.0*365.0*g_haz_lgd;
capture Hazard_HGD_pct_yr  = 100.0*365.0*g_haz_hgd;
capture Hazard_EAC_pct_yr  = 100.0*365.0*g_haz_eac;
capture Hazard_comp_pct_yr = 100.0*365.0*(g_haz_hgd + g_haz_eac);
capture CumInc_EAC_pct     = 100.0*CUM_EAC;
capture CumInc_comp_pct    = 100.0*CUM_COMP;

//--- Clinical endpoints & safety ---
capture Symptom_score      = SYMPT;
capture Bleed_risk_pct_yr  = BLEED_BASE*(1.0 + K_ASA_BLEED*g_cox_inhib)
                             *(1.0 - K_PPI_PROTEC*g_acid_block);
capture PPI_safety_index   = g_acid_block*(1.0 + 0.5*(GASTRIN/GASTRIN_BASE - 1.0));

// NOTE: there is deliberately no [CAPTURE] block. Every output above is
// declared with the `capture` keyword inside [TABLE], which both declares the
// variable and marks it for output; re-listing the same names in [CAPTURE]
// would be a duplicate declaration.


##  ============================================================================
##  R-side scenario helpers (documentation block — parsed by users, not mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  library(purrr)
##  mod <- mread_cache("be_mrgsolve_model.R")
##
##  ## ---------------------------------------------------------------------
##  ## Dosing vocabulary (1.0 au = esomeprazole 20 mg = aspirin 300 mg
##  ##                            = vonoprazan 20 mg = UDCA 300 mg)
##  ## ---------------------------------------------------------------------
##  ppi_low   <- function(d) ev(amt = 1.0, cmt = "PPI_DEPOT", ii = 1, addl = d - 1)
##  ppi_high  <- function(d) ev(amt = 2.0, cmt = "PPI_DEPOT", ii = 0.5, addl = 2*d - 1)
##  asa_300   <- function(d) ev(amt = 1.0, cmt = "ASA_DEPOT", ii = 1, addl = d - 1)
##  vpz_20    <- function(d) ev(amt = 1.0, cmt = "VPZ_DEPOT", ii = 1, addl = d - 1)
##  udca      <- function(d) ev(amt = 1.0, cmt = "UDCA_CENT", ii = 0.5, addl = 2*d - 1)
##  ## RFA: one session per event, q8 weeks, 3-4 sessions to reach CE-IM.
##  ## Ablate PROMPTLY after the confirmed-LGD diagnosis: SURF randomized at
##  ## baseline, and in a patient whose hazard is ~9 %/yr a one-year delay
##  ## costs most of the benefit (3.8% -> 19.8% 3-year progression in this
##  ## model). Scenario 8b keeps the delayed arm so the cost is visible.
##  rfa       <- function(start, n = 3, every = 56)
##                 ev(amt = 1.0, cmt = "ABL_PULSE", time = start, ii = every, addl = n - 1)
##  emr       <- function(start) ev(amt = 1.0, cmt = "EMR_PULSE", time = start)
##
##  ## ---------------------------------------------------------------------
##  ## 10 prebuilt scenarios (10-year horizon, matching AspECT/SURF designs)
##  ## ---------------------------------------------------------------------
##  BE_simulate_scenarios <- function(end_d = 3650) {
##
##    ## Patient archetypes -------------------------------------------------
##    ndbe  <- list(BASE_BE_LEN = 3, INIT_FP16 = 0.45, INIT_FLGD = 0.03,
##                  INIT_FP53 = 0.05, INIT_FHGD = 0.00)
##    lgd   <- list(BASE_BE_LEN = 5, INIT_FP16 = 0.80, INIT_FLGD = 0.50,
##                  INIT_FP53 = 0.50, INIT_FHGD = 0.00, INIT_ANEUPL = 0.25)
##    hgd   <- list(BASE_BE_LEN = 6, INIT_FP16 = 0.90, INIT_FLGD = 0.60,
##                  INIT_FP53 = 0.70, INIT_FHGD = 0.45, INIT_ANEUPL = 0.45)
##
##    sc <- list(
##      "1. NDBE natural history (no therapy)" =
##        list(par = ndbe, ev = ev(amt = 0, cmt = "PPI_DEPOT")),
##
##      "2. AspECT low-dose PPI (esomeprazole 20 mg OD)" =
##        list(par = ndbe, ev = ppi_low(end_d)),
##
##      "3. AspECT high-dose PPI (esomeprazole 40 mg BID)" =
##        list(par = ndbe, ev = ppi_high(end_d)),
##
##      "4. AspECT low-dose PPI + aspirin 300 mg" =
##        list(par = ndbe, ev = ppi_low(end_d) + asa_300(end_d)),
##
##      "5. AspECT high-dose PPI + aspirin 300 mg (best arm)" =
##        list(par = ndbe, ev = ppi_high(end_d) + asa_300(end_d)),
##
##      "6. Vonoprazan 20 mg OD (P-CAB)" =
##        list(par = ndbe, ev = vpz_20(end_d)),
##
##      "7. Confirmed LGD — surveillance on PPI (SURF control)" =
##        list(par = lgd, ev = ppi_high(end_d)),
##
##      "8. Confirmed LGD — prompt RFA x3 on PPI (SURF ablation arm)" =
##        list(par = lgd, ev = ppi_high(end_d) + rfa(30, n = 3)),
##
##      "8b. Confirmed LGD — RFA x3 DELAYED to year 1 (cost of waiting)" =
##        list(par = lgd, ev = ppi_high(end_d) + rfa(365, n = 3)),
##
##      "9. HGD — EMR of visible lesion + RFA x4 on PPI" =
##        list(par = hgd, ev = ppi_high(end_d) + emr(30) + rfa(65, n = 4)),
##
##      "10. Antireflux surgery at year 1 (no acid drug)" =
##        list(par = c(ndbe, list(FUNDO = 1, FUNDO_START = 365)),
##             ev = ev(amt = 0, cmt = "PPI_DEPOT"))
##    )
##
##    purrr::imap_dfr(sc, function(s, lab) {
##      mod %>% param(s$par) %>%
##        mrgsim(events = s$ev, end = end_d, delta = 5) %>%
##        as_tibble() %>% mutate(scenario = lab)
##    })
##  }
##
##  ## ---------------------------------------------------------------------
##  ## CYP2C19 pharmacogenomic sweep on esomeprazole 20 mg OD
##  ## ---------------------------------------------------------------------
##  BE_cyp2c19_sweep <- function(end_d = 3650) {
##    phen <- c(UM = 1.8, RM = 1.4, NM = 1.0, IM = 0.55, PM = 0.25)
##    purrr::imap_dfr(phen, function(cl, nm) {
##      mod %>% param(CL2C19 = cl) %>%
##        mrgsim(events = ppi_low(end_d), end = end_d, delta = 5) %>%
##        as_tibble() %>% mutate(phenotype = nm, CL2C19 = cl)
##    })
##  }
##
##  ## ---------------------------------------------------------------------
##  ## Weight-loss intervention in central obesity
##  ## ---------------------------------------------------------------------
##  BE_weightloss <- function(end_d = 3650) {
##    bind_rows(
##      mod %>% param(OBESITY = 0.85) %>%
##        mrgsim(events = ppi_low(end_d), end = end_d, delta = 5) %>%
##        as_tibble() %>% mutate(arm = "Obesity maintained"),
##      mod %>% param(OBESITY = 0.85, WL_START = 730, WL_MAG = 0.5) %>%
##        mrgsim(events = ppi_low(end_d), end = end_d, delta = 5) %>%
##        as_tibble() %>% mutate(arm = "50% visceral fat loss at year 2")
##    )
##  }
##
##  ## ---------------------------------------------------------------------
##  ## Calibration — how the parameters were actually determined
##  ## ---------------------------------------------------------------------
##  ## This model was calibrated numerically, in two stages, against SIX
##  ## independent published anchors. The timescale separation in the model
##  ## makes that cheap: the reflux/injury/inflammation/proliferation
##  ## subsystem equilibrates in weeks, the clonal cascade evolves over years.
##  ##
##  ## Stage 1 (the drug axis) — three free parameters, three anchors, each
##  ## anchor matched to the parameter that dominates it:
##  ##   ACID_POW    = 1.989  <- AspECT high-dose vs low-dose PPI ratio  0.73
##  ##   K_ASA_REG   = 0.0942 <- AspECT aspirin vs no aspirin           0.93
##  ##   K_OBES_REFL = 0.0859 <- central obesity vs lean EAC risk       ~2.0
##  ## Stage 2 (the clonal cascade) — three free rates, three anchors:
##  ##   K_P53 = 0.0934, K_HGD = 5.503e-3, K_EAC = 2.774e-4
##  ##   <- NDBE 0.12 %/yr (Hvid-Jensen), confirmed LGD 9 %/yr (Duits),
##  ##      HGD -> EAC 6 %/yr (Rastogi)
##  ## The two stages were alternated to a joint fixed point (4 rounds); all
##  ## six residuals converged to zero.
##  ##
##  ## Achieved vs target:
##  ##   high-dose PPI ratio   0.729  [AspECT 0.73]
##  ##   aspirin ratio         0.929  [AspECT 0.93]
##  ##   combination ratio     0.675  [AspECT 0.59]  <- PREDICTED, not fitted
##  ##   NDBE EAC incidence    0.120 %/yr  [Hvid-Jensen 0.12 %/yr]
##  ##   obese/lean EAC ratio  2.007  [~2.0]
##  ##   confirmed LGD         9.00 %/yr   [Duits ~9 %/yr]
##  ##   HGD -> EAC            6.00 %/yr   [Rastogi ~6 %/yr]
##  ##
##  ## The COMBINATION arm is the model's one honest miss: because the drug
##  ## effects enter MUT multiplicatively, the model can only predict
##  ## 0.729 x 0.929 = 0.677 for the combination, and it delivers 0.675. The
##  ## trial reported 0.59, i.e. slightly MORE than multiplicative. The model
##  ## therefore under-predicts the combination benefit, and that gap is a
##  ## substantive statement: either AspECT's combination estimate is at the
##  ## favourable end of its confidence interval, or there is a real
##  ## acid x COX interaction that this model does not contain.
##  ##
##  ## Fixed from mechanism rather than fitted:
##  ##   W_*_INJ split      acid 0.70 / bile 0.22 / smoking 0.08 of reference injury
##  ##   Ki-67 composition  IL-6/STAT3 0.35 (COX-INDEPENDENT) / PGE2 0.02
##  ##                      (the aspirin target) / adiposity 0.10 / floor 0.53
##  ##   K_GAS_KI = 4.0     a doubling of gastrin raises Ki-67 by 20%
##  ##                      (Haigh 2003, CCK2R trophic effect)
##  ##   K_PH_BILE = 0.35, PH_BILE_HALF = 0.25, PH_BILE_N = 2
##  ##   KINH_PUMP = 3.26 with KSYN_PUMP = 0.333 (pump resynthesis t1/2 ~50 h)
##  ##     reproduces the acid-control ladder: esomeprazole 20 mg OD -> 53%
##  ##     blockade (AET 12.5 -> 5.8%), 40 mg BID -> 82% (AET -> 2.2%).
##  ##   CL2C19 scales elimination only: PM (0.25) quadruples exposure and
##  ##     lifts 20 mg OD to high-dose-equivalent blockade, UM/*17 (1.8) drops
##  ##     it to ~41% (Furuta / Klotz / CPIC).
##  ##   KACET_COX = 22 with KREC_COX = 0.5/day gives ~87% steady-state mucosal
##  ##     COX inhibition on aspirin 300 mg OD.
##  ##   SEG_POW = 1.0 about SEG_REF = 3 cm gives ~1.7-2x risk per 2 cm
##  ##     (Anaparthy 2013).
##  ##   K_ABL_DYS = 0.85/day over a 3-session q8wk RFA course drives the
##  ##     dysplastic fractions down >99% (CE-D) while K_STRICT = 0.008 keeps
##  ##     the stricture burden in the reported 6-12% band (Shaheen 2009,
##  ##     Phoa 2014).
##  ##   K_LEN = 0.0004/day (tau ~2500 d) sets how fast an ablated segment
##  ##     regrows toward its drive-set target, i.e. the recurrence rate. The
##  ##     first draft used 0.002/day, which regrew the whole segment inside
##  ##     3 years -- far faster than the ~8-10 %/yr recurrence after CE-IM
##  ##     reported by Cotton 2018.
##  ##
##  ## THREE THINGS THAT ARE PREDICTIONS, NOT FITS
##  ##  1. The AspECT combination arm (above).
##  ##  2. Post-ablation recurrence. There is no recurrence parameter. After
##  ##     RFA the segment's target length is still set by the patient's own
##  ##     CDX2 drive, so SEED_BURIED regrows the segment whenever acid AND
##  ##     bile exposure remain uncontrolled. Durability comes out as a
##  ##     reflux-control result rather than an ablation-technique result.
##  ##  3. PPI vs no acid suppression at all. Not an AspECT comparison (every
##  ##     AspECT patient got a PPI); the model produces HR ~0.31, in the same
##  ##     direction and magnitude as the confounded observational estimate of
##  ##     ~0.4 (Kastelein 2013).
##  ##
##  ## THE FALSIFIABLE CORE: set K_PH_BILE = 0 and K_GAS_KI = 0 and high-dose
##  ## PPI monotherapy becomes far more effective than any arm of the real
##  ## trial. Those two parameters are each set from their own mechanistic
##  ## literature (Jenkins 2007 / Nehra 1999 for the pH-bile term; Haigh 2003
##  ## for the gastrin term), NOT tuned to hit AspECT — and together they land
##  ## the model on 0.729 against a measured 0.73. They are the first thing a
##  ## skeptical reader should attack.
##
##  ## ---------------------------------------------------------------------
##  ## Quick sanity plots
##  ## ---------------------------------------------------------------------
##  ## df <- BE_simulate_scenarios(3650)
##  ## ggplot(df, aes(time/365, CumInc_comp_pct, colour = scenario)) + geom_line() +
##  ##   labs(x = "Years", y = "Cumulative HGD/EAC incidence (%)")
##  ## ggplot(df, aes(time/365, AET_pct, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/365, Prague_M_cm, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/365, Mutational_drive, colour = scenario)) + geom_line()
##  ## ggplot(df, aes(time/365, Gastrin_fold, colour = scenario)) + geom_line()
