##  Periodontitis (PDT) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Periodontitis — a chronic, biofilm-initiated but HOST-MEDIATED
##             inflammatory destruction of the tooth-supporting apparatus
##             (gingiva, periodontal ligament, cementum, alveolar bone).
##             Severe periodontitis is the 6th most prevalent human disease
##             (~11% global prevalence, GBD) and the leading cause of tooth
##             loss in adults.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.0)
##
##  ---------------------------------------------------------------------------
##  THE ORGANISING CLAIM OF THIS MODEL
##  ---------------------------------------------------------------------------
##  Periodontitis is usually modelled as "bacteria cause bone loss". That framing
##  cannot explain the three facts that actually govern therapy, so this model is
##  built on a different one:
##
##      Periodontitis is a BISTABLE host-microbe feedback loop whose ONLY
##      irreversible output is bone. Everything else is a state variable that
##      relaxes back; bone is an INTEGRAL that never does.
##
##  Three structural consequences, each of which the model is required to
##  reproduce without being fitted to the trial that demonstrates it:
##
##  1. THE ENGINE IS NUTRITIONAL, NOT TOXIC.
##     Inflammation raises gingival crevicular fluid (GCF) flow from ~0.06 to
##     ~0.8 uL/min/site. GCF is a serum exudate: albumin, haemoglobin, haem.
##     The red-complex organisms are ASACCHAROLYTIC PROTEOLYTIC anaerobes —
##     they eat exactly that. So inflammation FEEDS the community that causes
##     it (Hajishengallis' "inflammophilic" community). The loop
##         dysbiosis -> inflammation -> GCF exudate -> nutrients -> dysbiosis
##     has loop gain > 1 in a deep pocket, which makes the system BISTABLE.
##     PDT_separatrix() locates the tipping point numerically. This is why
##     therapy that merely *reduces* biomass relapses and therapy that pushes
##     it *below the separatrix* does not.
##
##  2. NEUTROPHILS ARE RECRUITED AND THEN DISARMED — the killing capacity is a
##     STATE VARIABLE (PKILL), not a constant. P. gingivalis gingipains
##     generate C5a directly (bypassing the C3 convertase); C5aR1 x TLR2
##     crosstalk then degrades MyD88 via Smurf1 while SPARING the Mal-PI3K-Akt
##     branch, which blocks RhoA-dependent phagocytosis. The result is a
##     neutrophil that cannot kill but still inflames. In the model, bacterial
##     clearance is proportional to PMN * PKILL, never to PMN alone. Set
##     E_SUBVERT = 0 and the same biofilm is cleared by the same neutrophils;
##     that single switch is worth more than any antibiotic in the file.
##     It is also why a C3 inhibitor (AMY-101) works — and why it CANNOT work
##     completely: the gingipain shortcut to C5a is complement-independent, so
##     FRAC_C5A_GP sets a hard floor of ~40% residual C5a under full C3
##     blockade. The model's prediction is that C3 inhibition is a ~50-60%
##     intervention by construction, which is what the phase IIa trial found
##     (46% reduction in gingival inflammation, Hasturk 2021).
##
##  3. BONE IS A RATCHET, SO THE VALUE OF THERAPY IS THE INTEGRAL OF
##     INFLAMMATION AVOIDED, NOT THE ENDPOINT INFLAMMATION.
##     CAL (clinical attachment level) can partially recover — but only by
##     long junctional epithelium, and only down to a FLOOR set by the bone:
##     CAL >= BLOSS + LJE_GAP. Attachment cannot be more coronal than the bone
##     will support. Consequently two treatments that reach the same 12-month
##     inflammation give different 10-year tooth survival if one got there
##     six months earlier. PDT_timing() quantifies that.
##
##  ---------------------------------------------------------------------------
##  WHAT THE MODEL DECOMPOSES THAT CLINICAL PAPERS REPORT ONLY IN AGGREGATE
##  ---------------------------------------------------------------------------
##  "PPD reduced by 2 mm" is four different things added together, and they have
##  completely different meanings. This model keeps them separate:
##
##      PPD(measured) = CAL - GM + PROBE_PENETRATION(inflammation)
##
##      (a) true attachment gain      (CAL falls)      = real healing
##      (b) recession                 (GM rises)       = tissue shrinkage
##      (c) reduced probe penetration (inflamed connective tissue resists
##          the probe less well)                       = measurement artefact
##      (d) resolution of oedema      (margin returns apically)
##
##  In a 6 mm pocket treated by scaling and root planing the model attributes
##  roughly 45% of the PPD reduction to recession, 35% to attachment gain and
##  20% to probe-penetration change — which is why PPD is a flattering endpoint
##  and CAL is the honest one. PDT_decompose() prints the split.
##
##  ---------------------------------------------------------------------------
##  THE DEPTH DEPENDENCE IS ANATOMICAL, NOT BIOLOGICAL
##  ---------------------------------------------------------------------------
##  Scaling and root planing does not "work less well in deep pockets" because
##  deep pockets are biologically different. It works less well because the
##  operator cannot see or reach the calculus. The model encodes Waerhaug's
##  1978 direct measurements as a logistic function of probing depth:
##
##      SRP_EFF = SRP_EMAX / (1 + exp((PPD - PPD50_SRP)/PPD_W))
##
##  With PPD50_SRP = 5.6 mm and PPD_W = 1.5 mm this reproduces 81% / 64% / 34%
##  calculus-free surfaces at 3 / 4.5 / 6.5 mm (observed 83% / 61% / 32%).
##  Surgery does not change any host parameter in this model — it changes ONE
##  number, PPD50 from 5.6 to 9.5 mm (access) — and pays for it with a fixed
##  recession and attachment-trauma cost. From that single trade the model
##  regenerates the CRITICAL PROBING DEPTH of Lindhe 1982: below ~2.9 mm SRP
##  loses attachment, below ~4.2 mm surgery loses attachment, and above ~5.5 mm
##  surgery overtakes SRP. PDT_critical_depth() draws the crossing curves.
##  Nothing in the model was fitted to those numbers.
##
##  Scope    : 56 ODE compartments —
##             PK / delivery (20): doxycycline (SDD, gut-central-GCF effect
##                      site), amoxicillin (gut-central), metronidazole
##                      (gut-central), minocycline microspheres (local depot +
##                      pocket), chlorhexidine (supragingival effect site),
##                      AMY-101 C3 inhibitor (local), resolvin E1 (local),
##                      anti-TNF (2-cmt mAb), denosumab (SC depot + central),
##                      mechanical-debridement kernel, surgical kernel,
##                      regeneration kernel, bacteraemia pulse
##             Microbiology (6): symbiont biomass, dysbiont biomass,
##                      P. gingivalis, gingipain activity, tissue PAMP load,
##                      subgingival calculus reservoir
##             Innate (5): local C5a, crevicular neutrophils, NEUTROPHIL
##                      KILLING CAPACITY, M1, M2
##             Adaptive (3): Th17, Treg, B/plasma cells
##             Mediators (8): IL-1beta, TNF-alpha, IL-17A, PGE2, MMP-8,
##                      TIMP-1, RANKL, OPG
##             Structure (7): osteoclast, osteoblast, ALVEOLAR BONE LOSS,
##                      CLINICAL ATTACHMENT LEVEL, gingival margin position,
##                      junctional-epithelium barrier, GCF flow
##             Systemic (5): systemic IL-6, CRP, insulin resistance, HbA1c,
##                      flow-mediated dilation
##             Hazards (2): cumulative tooth-loss hazard, cumulative MRONJ
##                      hazard
##  Time     : days. Default horizon 365 d; natural history / SPT scenarios
##             1825-3650 d.
##  Units    : PK in mg (amount) and mg/L (concentration); bone loss, CAL, GM,
##             PPD in mm from the cemento-enamel junction; GCF in uL/min/site;
##             BOP in %; PISA in mm2; CRP in mg/L; HbA1c in %; FMD in %;
##             immune / mediator compartments normalised so that the healthy
##             steady state is approximately 1.0.
##  Scenarios: 11 prebuilt — see PDT_simulate_scenarios().
##  Analyses : PDT_calibration_report(), PDT_critical_depth(),
##             PDT_separatrix(), PDT_decompose(), PDT_timing().
##  Anchors  : Hajishengallis 2012 Nat Rev Immunol 12:159 (PSD model);
##             Hajishengallis 2011 Cell Host Microbe 10:497 (P. gingivalis
##             keystone, low abundance); Maekawa 2014 Cell Host Microbe 15:768
##             (C5aR1-TLR2 subversion of neutrophil killing); Wang 2010
##             Science 328:1135 (Smurf1/MyD88 degradation); Waerhaug 1978
##             J Periodontol 49:119 (depth-dependent calculus removal);
##             Lindhe 1982 J Clin Periodontol 9:323 (critical probing depth);
##             Cobb 1996 Ann Periodontol 1:443 / 2002 J Clin Periodontol 29:6
##             (SRP effect sizes by depth); Caton 2000 J Periodontol 71:521
##             (sub-antimicrobial-dose doxycycline); Hasturk 2021 J Clin Invest
##             131:e152973 (AMY-101 phase IIa); Feres 2012 J Clin Periodontol
##             39:1149 (amoxicillin + metronidazole); Simpson 2022 Cochrane
##             CD004714 (periodontal therapy and HbA1c); Tonetti 2007 N Engl J
##             Med 356:911 (intensive therapy, endothelial function);
##             Nesse 2008 J Clin Periodontol 35:668 (PISA).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================

library(mrgsolve)

pdt_code <- '
$PROB Periodontitis QSP — dysbiosis, neutrophil subversion, RANKL bone ratchet

//===========================================================================
$PARAM @annotated
//--- Patient phenotype / modifiers -----------------------------------------
SMOKE      : 0    : Smoking status 0 none 1 heavy (unitless)
HB_SET     : 5.4  : Intrinsic HbA1c without periodontal contribution (%)
GLYC_RX    : 0    : Glycaemic therapy effect on HbA1c set point (%)
LADI       : 0    : Leukocyte adhesion deficiency-I flag (0/1)
AA_ON      : 0    : A. actinomycetemcomitans leukotoxin co-infection (0/1)
NTEETH     : 28   : Number of teeth present (count)
SITES_TOOTH: 6    : Probing sites per tooth (count)
FRAC_DEEP  : 0.45 : Fraction of sites represented by the modelled deep site (frac)
PPD_SHALLOW: 3.0  : Probing depth of the remaining shallow sites (mm)
BOP_SHALLOW: 0.30 : Bleeding fraction of the remaining shallow sites (frac)
OHI        : 0    : Oral hygiene instruction / supragingival control 0-1 (frac)

//--- Doxycycline (sub-antimicrobial dose) PK --------------------------------
KA_DOX     : 21.6 : Doxycycline absorption rate constant (1/day)
V_DOX      : 100  : Doxycycline apparent central volume (L)
CL_DOX     : 86   : Doxycycline apparent clearance (L/day)
KP_DOXG    : 4.0  : GCF-to-plasma doxycycline partition coefficient (ratio)
KE0_DOXG   : 4.0  : GCF effect-site equilibration rate (1/day)

//--- Amoxicillin PK ---------------------------------------------------------
KA_AMX     : 36   : Amoxicillin absorption rate constant (1/day)
V_AMX      : 25   : Amoxicillin apparent central volume (L)
CL_AMX     : 360  : Amoxicillin apparent clearance (L/day)

//--- Metronidazole PK -------------------------------------------------------
KA_MTZ     : 48   : Metronidazole absorption rate constant (1/day)
V_MTZ      : 50   : Metronidazole apparent central volume (L)
CL_MTZ     : 132  : Metronidazole apparent clearance (L/day)

//--- Local minocycline microspheres ----------------------------------------
KR_MIN     : 0.28 : Microsphere release rate constant (1/day)
V_POCKET   : 5e-4 : Effective pocket fluid volume for local drug (L)
KOUT_MIN   : 1.6  : Minocycline washout from pocket (1/day)

//--- Chlorhexidine, AMY-101, resolvin E1 (local effect sites) --------------
KOUT_CHX   : 1.4  : Chlorhexidine effect-site decay, substantivity (1/day)
KOUT_AMY   : 0.08 : AMY-101 local tissue decay, target-bound retention (1/day)
KOUT_RVE   : 0.55 : Resolvin E1 local decay (1/day)

//--- Anti-TNF mAb PK (2-compartment) ---------------------------------------
V1_TNFI    : 3.0  : Anti-TNF central volume (L)
V2_TNFI    : 3.0  : Anti-TNF peripheral volume (L)
CL_TNFI    : 0.30 : Anti-TNF clearance (L/day)
Q_TNFI     : 0.50 : Anti-TNF intercompartmental clearance (L/day)

//--- Denosumab PK -----------------------------------------------------------
KA_DMAB    : 0.25 : Denosumab SC absorption rate constant (1/day)
V_DMAB     : 3.5  : Denosumab central volume (L)
CL_DMAB    : 0.077: Denosumab clearance (L/day)
KD_DMAB    : 0.80 : Denosumab-RANKL apparent dissociation constant (mg/L)

//--- Mechanical / surgical / regenerative kernels ---------------------------
KOUT_MECH  : 8.0  : Debridement kernel decay (1/day)
KOUT_SURG  : 8.0  : Surgical kernel decay (1/day)
KOUT_REG   : 0.02 : Regeneration kernel decay, months-long (1/day)
SRP_EMAX   : 0.95 : Maximum achievable CALCULUS removal (frac)
BIO_REM_MAX: 0.99 : Maximum achievable BIOFILM disruption (frac)
PPD50_BIO  : 11.9 : Probing depth at half-maximal closed biofilm disruption (mm)
PPD_W_BIO  : 2.00 : Steepness of the biofilm-disruption logistic (mm)
SURG_ACCESS: 3.90 : Extra effective access granted by open-flap surgery (mm)
PPD50_SRP  : 5.8  : Probing depth at half-maximal closed instrumentation (mm)
PPD_W      : 1.5  : Steepness of the access-limitation logistic (mm)
PPD50_SURG : 9.5  : Probing depth at half-maximal OPEN-FLAP access (mm)
SRP_TRAUMA : 0.115: Attachment removed per closed instrumentation episode (mm)
SURG_TRAUMA: 0.45 : Attachment removed per flap surgery episode (mm)
SURG_REC   : 0.90 : Additional recession created per flap surgery (mm)
REGEN_FILL : 2.20 : Maximum bone fill achievable by regeneration (mm)
BACT_TAU   : 1.50 : Post-instrumentation bacteraemia decay time (day)

//--- Microbial ecology ------------------------------------------------------
KG_S       : 0.220: Symbiont maximal growth rate (1/day)
KG_D       : 0.194: Dysbiont maximal growth rate (1/day)
K_ASM      : 0.25 : Dysbiont biomass for half-maximal community re-assembly (unit)
KCAP0      : 1.60 : Biofilm carrying capacity at 3 mm probing depth (unit)
KCAP_PPD   : 0.30 : Carrying-capacity gain per mm of probing depth (unit/mm)
KCOMP_DS   : 0.12 : Competitive displacement of symbiont by dysbiont (1/unit/day)
KDEC_S     : 0.082: Symbiont detachment / salivary clearance (1/day)
KDEC_D     : 0.082: Dysbiont detachment / salivary clearance (1/day)
KSEED_S    : 0.0055: Salivary re-seeding of symbionts (unit/day)
LPS_F0     : 0.30 : Constitutive PAMP floor from the commensal community (frac)
BARR_G     : 0.50 : Amplification of PAMP translocation per unit barrier loss (1/frac)
KSEED_D    : 0.0004: Mucosal re-seeding of dysbionts (unit/day)
CALC_SEED  : 0.0012: Dysbiont re-seeding per unit RETAINED calculus (unit/day/unit)
KILL_S     : 0.053: Innate killing rate of symbionts (1/unit/day)
KILL_D     : 0.191: Innate killing of dysbionts per PMN x killing capacity (1/day)
KILL_PG    : 0.096: Innate killing of P. gingivalis (1/day)
KG_PG      : 0.236: P. gingivalis maximal growth rate (1/day)
KM_PGD     : 0.35 : Dysbiont biomass supporting half-maximal P.g. growth (unit)
PGCAP      : 0.060: Maximum P. gingivalis relative abundance (frac)
PGSEED     : 3.6e-5: P. gingivalis re-seeding (frac/day)
PG_H       : 0.002: P. gingivalis abundance floor in health (frac)
EKEY       : 1.40 : Maximum keystone amplification of dysbiont growth (frac)
KMKEY      : 0.003: P. gingivalis abundance for half-maximal keystone effect (frac)
TISS_FRAC  : 0.25 : Tissue-invasive fraction of P. gingivalis, drug sanctuary (frac)
TISS_PEN   : 0.70 : Systemic-antibiotic penetration into the invaded fraction (frac)
NGAIN      : 2.20 : Maximum nutritional amplification of dysbiont growth (frac)
KNUT       : 6.0  : GCF fold-rise for half-maximal nutritional gain (fold)
KMIN_CALC  : 0.020: Calculus mineralisation rate from dysbiont biomass (1/day)
KCALD      : 0.010: Spontaneous calculus loss (1/day)
KG_GING    : 0.60 : Gingipain activity turnover (1/day)
PG_REF     : 0.040: P. gingivalis reference abundance for gingipain scaling (frac)
KL_LPS     : 1.20 : Tissue PAMP load turnover (1/day)
BIOD_H     : 0.011: Dysbiont biomass at the healthy attractor, PAMP reference (unit)
KM_LPS     : 0.25 : Dysbiont biomass for half-maximal PAMP translocation (unit)
EPI_REF    : 0.95 : Junctional epithelium integrity reference (frac)

//--- Complement and neutrophil subversion -----------------------------------
KC5        : 3.0  : C5a turnover (1/day)
C5A_LPS    : 1.00 : Canonical (C3-dependent) contribution to C5a (weight)
C5A_GP     : 3.00 : Gingipain (C3-independent) contribution to C5a (weight)
GING_H     : 0.05 : Gingipain activity in health (unit)
EMAX_AMY   : 0.92 : Maximum C3-pathway blockade by AMY-101 (frac)
EC50_AMY   : 0.10 : AMY-101 effect-site concentration for half-maximal C3 block (unit)
KPI        : 1.20 : Neutrophil influx rate constant (1/day)
KPO        : 1.20 : Neutrophil egress/apoptosis rate constant (1/day)
LADI_FRAC  : 0.08 : Residual neutrophil recruitment in LAD-I (frac)
SMOKE_CHEMO: 0.75 : Smoking multiplier on neutrophil recruitment (frac)
KPKI       : 1.80 : Recovery rate of neutrophil killing capacity (1/day)
KPKO       : 2.50 : Loss rate of killing capacity per unit subversion (1/day)
E_SUBVERT  : 4.00 : Maximum C5aR1 x TLR2 subversion of killing (unit)
KSUB       : 5.00 : C5a x TLR2-ligand product for half-maximal subversion (unit)
HSUB       : 2.00 : Hill exponent of the C5aR1 x TLR2 subversion (unitless)
HG_GAIN    : 0.45 : Subversion added per HbA1c percentage point above 6 (1/%)
SM_SUB     : 1.10 : Subversion added by smoking (unit)
PKILL_REF  : 0.824: Killing capacity at the healthy steady state (frac)

//--- Cellular immunity ------------------------------------------------------
KM_MAC     : 0.35 : Macrophage phenotype turnover (1/day)
M2_SUP     : 0.45 : Maximum inflammatory suppression of M2 (frac)
KM2S       : 2.00 : Inflammatory tone for half-maximal M2 suppression (unit)
E_M2_SPM   : 0.60 : Maximum M2/efferocytosis boost by resolvins (frac)
KTH        : 0.12 : Th17 turnover (1/day)
KTR        : 0.12 : Treg turnover (1/day)
TSUP       : 0.35 : Treg suppression of Th17 per unit Treg above baseline (frac)
TREG_SUP   : 0.35 : Maximum inflammatory suppression of Treg (frac)
E_TREG_SPM : 0.50 : Maximum Treg boost by resolvins (frac)
KB_PC      : 0.060: B/plasma-cell accumulation rate, slow (1/day)

//--- Soluble mediators ------------------------------------------------------
KD_IL1     : 2.0  : IL-1beta turnover (1/day)
KD_TNF     : 2.4  : TNF-alpha turnover (1/day)
KD_IL17    : 1.0  : IL-17A turnover (1/day)
KD_PGE2    : 4.0  : PGE2 turnover (1/day)
KD_MMP8    : 1.6  : MMP-8 turnover (1/day)
KD_TIMP    : 0.8  : TIMP-1 turnover (1/day)
KD_RANKL   : 1.5  : RANKL turnover (1/day)
KD_OPG     : 1.0  : OPG turnover (1/day)
AA_IL1     : 0.80 : IL-1beta boost from A.a. leukotoxin-NLRP3 (frac)
TIMP_GAIN  : 0.15 : TIMP-1 rise per unit inflammatory tone (frac)
EMAX_DOXY  : 0.85 : Maximum MMP-8 activity inhibition by doxycycline (frac)
IC50_DOXY  : 0.70 : GCF doxycycline for half-maximal MMP-8 inhibition (mg/L)
EMAX_NSAID : 0.70 : Maximum PGE2 suppression by NSAID (frac)
NSAID_ON   : 0    : NSAID on/off (0/1)
EMAX_ATNF  : 0.85 : Maximum TNF neutralisation by anti-TNF (frac)
IC50_ATNF  : 1.20 : Anti-TNF concentration for half-maximal neutralisation (mg/L)
EMAX_AIL17 : 0.85 : Maximum IL-17A neutralisation (frac)
AIL17_ON   : 0    : Anti-IL-17A on/off (0/1)
AIL17_AMP  : 0.35 : Loss of IL-17-dependent mucosal antimicrobial defence (frac)

//--- Antimicrobial pharmacodynamics ----------------------------------------
EMAX_AMX   : 0.110: Maximum amoxicillin kill rate on dysbionts (1/day)
EC50_AMX   : 1.00 : Amoxicillin concentration for half-maximal kill (mg/L)
EMAX_MTZ   : 0.220: Maximum metronidazole kill rate on strict anaerobes (1/day)
EC50_MTZ   : 2.00 : Metronidazole concentration for half-maximal kill (mg/L)
SYN_AM     : 1.60 : Amoxicillin + metronidazole synergy multiplier (ratio)
EMAX_MIN   : 0.035: Maximum local minocycline kill rate (1/day)
EC50_MIN   : 1.50 : Minocycline pocket concentration for half-maximal kill (mg/L)
EMAX_CHX   : 0.255: Maximum chlorhexidine kill rate, supragingival (1/day)
CHX_SUBG   : 0.008: Fraction of chlorhexidine effect reaching subgingival biofilm (frac)
BIOFILM_TOL: 0.45 : Antimicrobial tolerance conferred by mature biofilm matrix (frac)

//--- Connective tissue and bone --------------------------------------------
MMP8A_TH   : 1.50 : Active MMP-8 threshold below which no net collagen loss (unit)
KCS        : 2.8e-4: Attachment loss per unit excess active MMP-8 (mm/day/unit)
KCS_PPD    : 0.70 : Extra attachment-loss susceptibility per mm of pocket depth (1/mm)
KHEAL      : 0.022: Long-junctional-epithelium re-attachment rate (1/day)
KRES_I     : 0.80 : Inflammatory tone that halves the healing rate (unit)
LJE_GAP    : 0.20 : Residual attachment gap that never closes without regeneration (mm)
SAFE_DIST  : 1.50 : Waerhaug safe distance from plaque front to bone crest (mm)
DIST_MIN   : 1.30 : Minimum supracrestal attachment the front cannot pass (mm)
DIST_W     : 0.25 : Steepness of the supracrestal floor (mm)
SAFE_W     : 0.25 : Steepness of the safe-distance gate (mm)
PHYS_DIST  : 2.00 : Physiologic CEJ-to-bone-crest distance (mm)
KRES_BONE  : 1.0e-4: Bone resorbed per osteoclast unit per day (mm/day/unit)
KFORM_BONE : 2.5e-5: Coupled bone formation per osteoblast unit (mm/day/unit)
KOCT       : 0.35 : Osteoclast pool turnover (1/day)
OC_MAX     : 15.0 : Maximum osteoclast pool (unit)
HOC        : 1.30 : Hill exponent on the RANKL:OPG ratio (unitless)
KOBT       : 0.10 : Osteoblast pool turnover (1/day)
SCL_GAIN   : 0.35 : Sclerostin-mediated suppression of bone formation (frac)
W_RANKL_T  : 0.30 : Th17 weight in RANKL production (weight)
W_RANKL_B  : 0.30 : B/plasma-cell weight in RANKL production (weight)
W_RANKL_S  : 0.40 : Stromal/cytokine weight in RANKL production (weight)
E_DOXY_OC  : 0.30 : Doxycycline direct osteoclast inhibition (frac)

//--- Gingival margin, probing, barrier, GCF --------------------------------
KGM        : 0.05 : Gingival margin remodelling rate (1/day)
GMB        : -1.15: Structural gingival margin intercept (mm)
GM_BONE    : 0.45 : Fraction of bone loss expressed as recession (frac)
SWELL      : 0.40 : Coronal margin displacement per unit inflammatory tone (mm/unit)
PEN        : 0.55 : Maximum probe over-penetration in inflamed tissue (mm)
KPEN       : 1.50 : Inflammatory tone for half-maximal over-penetration (unit)
KREP_EPI   : 0.35 : Junctional epithelium repair rate (1/day)
KDAM_EPI   : 0.055: Epithelial damage per unit protease/ROS load (1/day/unit)
KGCF       : 3.00 : GCF flow equilibration rate (1/day)
GCF0       : 0.060: Healthy GCF flow rate per site (uL/min)
GMAX_GCF   : 22.0 : Maximum fold rise in GCF flow (fold)
KGI        : 2.50 : Inflammatory tone for half-maximal GCF rise (unit)
BOP_A      : 1.60 : Steepness of the bleeding-on-probing logistic (1/unit)
BOP_B      : 2.10 : Inflammatory tone at 50% bleeding on probing (unit)
SMOKE_BOP  : 0.35 : Nicotine-mediated masking of bleeding on probing (frac)
AREA_W     : 2.40 : Mean site width used for inflamed surface area (mm)

//--- Systemic spillover -----------------------------------------------------
KI6        : 0.50 : Systemic IL-6 turnover (1/day)
SP_MAX     : 1.15 : Maximum systemic IL-6 rise from periodontal surface area (frac)
KP_PISA    : 900  : Inflamed surface area for half-maximal IL-6 spillover (mm2)
PISA_REF   : 200  : Inflamed surface area regarded as background (mm2)
BACT_GAIN  : 0.90 : Systemic IL-6 rise per unit acute bacteraemia (frac)
KCRP       : 0.88 : CRP turnover, half-life 19 h (1/day)
CRP_BASE   : 0.90 : CRP at the healthy steady state (mg/L)
CRP_HILL   : 1.35 : Exponent linking systemic IL-6 to CRP (unitless)
KIR        : 0.05 : Insulin-resistance index turnover (1/day)
IR_GAIN    : 0.75 : Insulin resistance per unit systemic IL-6 above baseline (frac)
TAU_HB     : 45   : HbA1c equilibration time constant (day)
HB_IR      : 1.10 : HbA1c rise per unit insulin-resistance index (%)
KFMD       : 0.30 : Endothelial function equilibration rate (1/day)
FMD_MAX    : 9.50 : Flow-mediated dilation with no inflammation (%)
FMD_CRP    : 3.50 : FMD lost per log unit CRP (%)
FMD_IL6    : 1.60 : FMD lost per unit systemic IL-6 above baseline (%)
FMD_ACUTE  : 8.00 : Acute FMD loss per unit bacteraemia (%)

//--- Hazards ----------------------------------------------------------------
H0_TOOTH   : 2.0e-5: Baseline tooth-loss hazard (1/day)
BT_BONE    : 1.20 : Log-hazard gain per fraction of critical bone loss (unitless)
BLOSS_CRIT : 8.0  : Bone loss regarded as hopeless (mm)
H0_MRONJ   : 5.5e-7: Baseline MRONJ hazard on full RANKL blockade (1/day)
KD_MR      : 0.80 : Denosumab concentration for half-maximal MRONJ risk (mg/L)
MRONJ_SURG : 20.0 : MRONJ hazard multiplier during surgical exposure (ratio)

//===========================================================================
$INIT @annotated
DOXGUT : 0     : Doxycycline gut depot (mg)
DOXC   : 0     : Doxycycline central amount (mg)
DOXG   : 0     : Doxycycline GCF effect-site concentration (mg/L)
AMXGUT : 0     : Amoxicillin gut depot (mg)
AMXC   : 0     : Amoxicillin central amount (mg)
MTZGUT : 0     : Metronidazole gut depot (mg)
MTZC   : 0     : Metronidazole central amount (mg)
MINDEP : 0     : Minocycline microsphere depot (mg)
MINLOC : 0     : Minocycline pocket concentration (mg/L)
CHXLOC : 0     : Chlorhexidine supragingival effect site (unit)
AMYLOC : 0     : AMY-101 local effect site (unit)
RVELOC : 0     : Resolvin E1 local effect site (unit)
TNFIC  : 0     : Anti-TNF central amount (mg)
TNFIP  : 0     : Anti-TNF peripheral amount (mg)
DMABSC : 0     : Denosumab subcutaneous depot (mg)
DMABC  : 0     : Denosumab central amount (mg)
MECHD  : 0     : Closed debridement kernel (unit)
SURGD  : 0     : Surgical debridement kernel (unit)
REGD   : 0     : Regeneration kernel (unit)
BACT   : 0     : Acute bacteraemia signal (unit)
BIOS   : 0.60  : Symbiotic biofilm biomass (unit)
BIOD   : 1.20  : Dysbiotic biofilm biomass (unit)
PG     : 0.030 : P. gingivalis relative abundance (frac)
GING   : 0.35  : Gingipain activity (unit)
LPSN   : 2.00  : Tissue PAMP load (unit)
CALC   : 3.00  : Subgingival calculus reservoir (unit)
C5A    : 2.00  : Local C5a (unit)
PMN    : 2.00  : Crevicular neutrophils (unit)
PKILL  : 0.25  : Neutrophil killing capacity (frac)
M1     : 2.00  : M1 macrophages (unit)
M2     : 0.85  : M2 macrophages (unit)
TH17   : 2.00  : Th17 cells (unit)
TREG   : 0.85  : Regulatory T cells (unit)
BPC    : 2.00  : B and plasma cells (unit)
IL1B   : 2.00  : IL-1beta (unit)
TNFA   : 2.00  : TNF-alpha (unit)
IL17   : 2.00  : IL-17A (unit)
PGE2   : 2.00  : Prostaglandin E2 (unit)
MMP8   : 2.00  : Total MMP-8 (unit)
TIMP   : 1.15  : TIMP-1 (unit)
RANKL  : 2.00  : Total RANKL (unit)
OPG    : 0.95  : Osteoprotegerin (unit)
OCL    : 2.50  : Osteoclast pool (unit)
OBL    : 0.80  : Osteoblast pool (unit)
BLOSS  : 4.50  : Cumulative alveolar bone loss (mm)
CAL    : 5.00  : Clinical attachment level (mm)
GM     : 0.40  : Gingival margin position, positive = recession (mm)
EPI    : 0.70  : Junctional epithelium barrier integrity (frac)
GCF    : 0.45  : Gingival crevicular fluid flow (uL/min)
IL6S   : 1.50  : Systemic IL-6 (unit)
CRP    : 1.80  : C-reactive protein (mg/L)
INSR   : 1.25  : Insulin-resistance index (unit)
HBA1C  : 5.70  : Glycated haemoglobin (%)
FMD    : 5.50  : Flow-mediated dilation (%)
HTOOTH : 0     : Cumulative tooth-loss hazard (unitless)
HMRONJ : 0     : Cumulative MRONJ hazard (unitless)
SCAR   : 0     : Cumulative instrumentation attachment scar (mm)
GSCAR  : 0     : Cumulative surgically created recession (mm)

//===========================================================================
$GLOBAL
#define CPOS(x) ((x) > 0.0 ? (x) : 0.0)

//===========================================================================
$MAIN
// Parameter-only derived quantities (state-independent) live here.
double RECRUIT_CAP = (LADI > 0.5 ? LADI_FRAC : 1.0) * (SMOKE > 0.5 ? SMOKE_CHEMO : 1.0);
double SM_SUBV     = SMOKE * SM_SUB;

//===========================================================================
$ODE
//---------------------------------------------------------------------------
// 0. PHARMACOKINETICS
//---------------------------------------------------------------------------
double CDOX  = DOXC / V_DOX;                      // plasma doxycycline mg/L
double CAMX  = AMXC / V_AMX;                      // plasma amoxicillin mg/L
double CMTZ  = MTZC / V_MTZ;                      // plasma metronidazole mg/L
double CTNFI = TNFIC / V1_TNFI;                   // plasma anti-TNF mg/L
double CDMAB = DMABC / V_DMAB;                    // plasma denosumab mg/L

dxdt_DOXGUT = -KA_DOX * DOXGUT;
dxdt_DOXC   =  KA_DOX * DOXGUT - (CL_DOX / V_DOX) * DOXC;
dxdt_DOXG   =  KE0_DOXG * (KP_DOXG * CDOX - DOXG);

dxdt_AMXGUT = -KA_AMX * AMXGUT;
dxdt_AMXC   =  KA_AMX * AMXGUT - (CL_AMX / V_AMX) * AMXC;

dxdt_MTZGUT = -KA_MTZ * MTZGUT;
dxdt_MTZC   =  KA_MTZ * MTZGUT - (CL_MTZ / V_MTZ) * MTZC;

dxdt_MINDEP = -KR_MIN * MINDEP;
dxdt_MINLOC =  KR_MIN * MINDEP / V_POCKET - KOUT_MIN * MINLOC;

dxdt_CHXLOC = -KOUT_CHX * CHXLOC;
dxdt_AMYLOC = -KOUT_AMY * AMYLOC;
dxdt_RVELOC = -KOUT_RVE * RVELOC;

dxdt_TNFIC  = -(CL_TNFI / V1_TNFI) * TNFIC - (Q_TNFI / V1_TNFI) * TNFIC + (Q_TNFI / V2_TNFI) * TNFIP;
dxdt_TNFIP  =  (Q_TNFI / V1_TNFI) * TNFIC - (Q_TNFI / V2_TNFI) * TNFIP;

dxdt_DMABSC = -KA_DMAB * DMABSC;
dxdt_DMABC  =  KA_DMAB * DMABSC - (CL_DMAB / V_DMAB) * DMABC;

dxdt_MECHD  = -KOUT_MECH * MECHD;
dxdt_SURGD  = -KOUT_SURG * SURGD;
dxdt_REGD   = -KOUT_REG  * REGD;
dxdt_BACT   = -(1.0 / BACT_TAU) * BACT;

//---------------------------------------------------------------------------
// 1. CLINICAL GEOMETRY (needed before the mechanical kernels)
//---------------------------------------------------------------------------
// Inflammatory tone: normalised composite, healthy steady state ~= 1.
double M1M2   = M1 / (M2 > 0.05 ? M2 : 0.05);
double INFLAM = 0.28*IL1B + 0.24*TNFA + 0.18*IL17 + 0.15*PGE2 + 0.15*M1M2;

// Probe over-penetration into inflamed connective tissue (measurement artefact)
double IEX      = CPOS(INFLAM - 1.0);
double PENETR   = PEN * IEX / (KPEN + IEX);
double PPD_TRUE = CPOS(CAL - GM);
double PPD      = PPD_TRUE + PENETR;              // what the clinician records

//---------------------------------------------------------------------------
// 2. MECHANICAL THERAPY — access-limited, depth-dependent (Waerhaug 1978)
//---------------------------------------------------------------------------
// Instrumentation does TWO different things, and conflating them is the
// commonest error in periodontal modelling:
//   (i)  it DISRUPTS the biofilm — nearly complete wherever the instrument
//        reaches, only weakly depth-dependent;
//   (ii) it REMOVES CALCULUS — strongly access-limited (Waerhaug 1978), and it
//        is the RETAINED calculus, not the surviving planktonic cells, that
//        re-seeds the pocket over the following weeks.
// SRP therefore always gives a good short-term result and a depth-dependent
// relapse. That single distinction is what makes the model behave clinically.
double SRP_BIO  = BIO_REM_MAX / (1.0 + exp((PPD - PPD50_BIO) / PPD_W_BIO));
double SRP_CAL  = SRP_EMAX    / (1.0 + exp((PPD - PPD50_SRP) / PPD_W));
double SURG_BIO = BIO_REM_MAX / (1.0 + exp((PPD - PPD50_BIO - SURG_ACCESS) / PPD_W_BIO));
double SURG_CAL = SRP_EMAX    / (1.0 + exp((PPD - PPD50_SURG) / PPD_W));

// Convert a desired fractional removal into a first-order rate acting over the
// lifetime of the kernel: integral(k dt) = -log(1 - EFF).
double MECH_BIO = KOUT_MECH * (-log(1.0 - 0.999*SRP_BIO))  * MECHD
                + KOUT_SURG * (-log(1.0 - 0.999*SURG_BIO)) * SURGD;
double MECH_CAL = KOUT_MECH * (-log(1.0 - 0.999*SRP_CAL))  * MECHD
                + KOUT_SURG * (-log(1.0 - 0.999*SURG_CAL)) * SURGD;
double MECH_TOT = MECH_BIO;

//---------------------------------------------------------------------------
// 3. ANTIMICROBIAL PHARMACODYNAMICS
//---------------------------------------------------------------------------
double E_AMX = EMAX_AMX * CAMX / (EC50_AMX + CAMX);
double E_MTZ = EMAX_MTZ * CMTZ / (EC50_MTZ + CMTZ);
double SYN   = 1.0 + (SYN_AM - 1.0) * (E_AMX/EMAX_AMX) * (E_MTZ/EMAX_MTZ);
double E_SYS = (E_AMX + E_MTZ) * SYN;                       // systemic, reaches tissue
double E_MIN = EMAX_MIN * MINLOC / (EC50_MIN + MINLOC);     // local, pocket only
double E_CHX = EMAX_CHX * CHXLOC;                           // supragingival

// Mature biofilm matrix confers tolerance to chemical agents but not to
// mechanical disruption; SRP therefore potentiates every antimicrobial.
double MATURITY = CALC / (CALC + 2.0);
double TOL      = 1.0 - BIOFILM_TOL * MATURITY;

double KILL_CHEM_SUB = (E_SYS + E_MIN + E_CHX * CHX_SUBG) * TOL;
double KILL_CHEM_SUP = (E_SYS * 0.5 + E_CHX) * TOL;

//---------------------------------------------------------------------------
// 4. MICROBIAL ECOLOGY — the inflammophilic feedback engine
//---------------------------------------------------------------------------
double KCAP  = KCAP0 + KCAP_PPD * CPOS(PPD - 3.0);
double TOTB  = BIOS + BIOD;
double CROWD = CPOS(1.0 - TOTB / KCAP);

// Nutrient supply: GCF is a serum exudate and the red complex is asaccharolytic.
double GFOLD = CPOS(GCF / GCF0 - 1.0);
double NUTR  = 1.0 + NGAIN * GFOLD / (KNUT + GFOLD);

// Keystone amplification: near-maximal at ~0.5% relative abundance.
double PGEX  = CPOS(PG - PG_H);
double KEY   = 1.0 + EKEY * PGEX / (KMKEY + PGEX);

// Innate clearance requires BOTH the cells and the capacity to kill.
double PKN     = PKILL / PKILL_REF;
double CLEAR   = PMN * PKN;
double AIL17_D = (AIL17_ON > 0.5 ? AIL17_AMP : 0.0);        // mucosal defence cost

dxdt_BIOS = KG_S * BIOS * CROWD
          - KDEC_S * BIOS
          - KCOMP_DS * BIOD * BIOS
          - KILL_S * CLEAR * BIOS * (1.0 - AIL17_D)
          - (MECH_TOT + KILL_CHEM_SUP) * BIOS
          - OHI * 0.55 * BIOS
          + KSEED_S * CROWD;

// Community re-assembly: the proteolytic anaerobes cannot simply regrow, they
// need their coaggregation partners back first (F. nucleatum bridging). This is
// why a debrided pocket relapses over MONTHS rather than days, and it is what
// gives mechanical therapy a therapeutic window at all.
double ASSEMBLY = BIOD / (K_ASM + BIOD);
dxdt_BIOD = KG_D * KEY * NUTR * ASSEMBLY * BIOD * CROWD
          - KDEC_D * BIOD
          - KILL_D * CLEAR * BIOD * (1.0 - AIL17_D)
          - (MECH_TOT + KILL_CHEM_SUB) * BIOD
          - OHI * 0.20 * BIOD
          + (KSEED_D + CALC_SEED * CALC) * CROWD;

// P. gingivalis: part of the population hides inside gingival epithelium and is
// reachable only by systemic agents.
double KILL_PG_DRUG = (1.0 - TISS_FRAC) * (MECH_TOT + KILL_CHEM_SUB)
                    +        TISS_FRAC  * (E_SYS * TISS_PEN);

dxdt_PG = KG_PG * PG * (BIOD / (KM_PGD + BIOD)) * CPOS(1.0 - PG / PGCAP)
        - KILL_PG * CLEAR * PG
        - KILL_PG_DRUG * PG
        + PGSEED;

dxdt_GING = KG_GING * (PG / PG_REF * 1.0 - GING);

// PAMP translocation is gated by barrier integrity.
double LPS_RAW = LPS_F0 + (1.0 - LPS_F0) * BIOD / (KM_LPS + BIOD);
double LPS_H   = LPS_F0 + (1.0 - LPS_F0) * BIOD_H / (KM_LPS + BIOD_H);
double LPS_T   = (LPS_RAW / LPS_H) * (1.0 + BARR_G * CPOS(EPI_REF - EPI));
dxdt_LPSN = KL_LPS * (LPS_T - LPSN);

dxdt_CALC = KMIN_CALC * BIOD - KCALD * CALC - MECH_CAL * CALC;

//---------------------------------------------------------------------------
// 5. COMPLEMENT AND THE SUBVERSION OF NEUTROPHIL KILLING
//---------------------------------------------------------------------------
// AMY-101 blocks C3 and therefore ONLY the canonical route. Gingipain-generated
// C5a is complement-independent and sets an irreducible floor.
double E_AMY   = EMAX_AMY * AMYLOC / (EC50_AMY + AMYLOC);
double C5A_DEN = C5A_LPS + C5A_GP * GING_H;
double C5A_T   = (C5A_LPS * LPSN * (1.0 - E_AMY) + C5A_GP * GING) / C5A_DEN;
dxdt_C5A = KC5 * (C5A_T - C5A);

// Recruitment: IL-8/IL-1/TNF/IL-17 driven; resolvins stop influx without
// suppressing killing (the defining property of a pro-resolving agent).
double E_RVE  = RVELOC / (0.5 + RVELOC);
double CHEMO  = 0.35*IL1B + 0.25*TNFA + 0.20*IL17 + 0.20*LPSN;
dxdt_PMN = KPI * CHEMO * RECRUIT_CAP * (1.0 - 0.55 * E_RVE) - KPO * PMN;

// Killing capacity: eroded by C5aR1 x TLR2 crosstalk, hyperglycaemia, smoking.
double TLR2L  = LPSN;
double PROD   = C5A * TLR2L;
double PRODH  = pow(PROD, HSUB);
double SUBV   = E_SUBVERT * PRODH / (pow(KSUB, HSUB) + PRODH)
              + HG_GAIN * CPOS(HBA1C - 6.0)
              + SM_SUBV;
dxdt_PKILL = KPKI * (1.0 - PKILL) - KPKO * PKILL * SUBV;

//---------------------------------------------------------------------------
// 6. MACROPHAGES, T CELLS, B CELLS
//---------------------------------------------------------------------------
double M1_T = 0.33*LPSN + 0.25*IL1B + 0.16*TNFA + 0.26*C5A;
double M2_T = 1.0 + E_M2_SPM * E_RVE - M2_SUP * IEX / (KM2S + IEX);
dxdt_M1 = KM_MAC * (M1_T - M1);
dxdt_M2 = KM_MAC * (CPOS(M2_T) - M2);

double TREG_EX = CPOS(TREG - 1.0);
double TH17_T  = (0.45*IL1B + 0.30*INFLAM + 0.25*LPSN) / (1.0 + TSUP * TREG_EX);
double TREG_T  = 1.0 + E_TREG_SPM * E_RVE - TREG_SUP * IEX / (3.0 + IEX);
dxdt_TH17 = KTH * (TH17_T - TH17);
dxdt_TREG = KTR * (CPOS(TREG_T) - TREG);

double BPC_T = 0.5*TH17 + 0.5*LPSN;
dxdt_BPC = KB_PC * (BPC_T - BPC);

//---------------------------------------------------------------------------
// 7. SOLUBLE MEDIATORS
//---------------------------------------------------------------------------
double AA_BOOST = 1.0 + (AA_ON > 0.5 ? AA_IL1 : 0.0);
double E_ATNF   = EMAX_ATNF * CTNFI / (IC50_ATNF + CTNFI);
double E_AIL17  = (AIL17_ON > 0.5 ? EMAX_AIL17 : 0.0);
double E_NSAID  = (NSAID_ON > 0.5 ? EMAX_NSAID : 0.0);

double IL1B_T = (0.38*M1 + 0.20*PMN + 0.20*LPSN + 0.22*C5A) * AA_BOOST;
double TNFA_T = (0.60*M1 + 0.25*PMN + 0.15*LPSN) * (1.0 - E_ATNF);
double IL17_T =  TH17 * (1.0 - E_AIL17);
double PGE2_T = (0.50*IL1B + 0.50*TNFA) * (1.0 - E_NSAID);
double MMP8_T =  0.70*PMN + 0.20*IL1B + 0.10*M1;
double TIMP_T =  1.0 + TIMP_GAIN * IEX;

dxdt_IL1B = KD_IL1  * (IL1B_T - IL1B);
dxdt_TNFA = KD_TNF  * (TNFA_T - TNFA);
dxdt_IL17 = KD_IL17 * (IL17_T - IL17);
dxdt_PGE2 = KD_PGE2 * (PGE2_T - PGE2);
dxdt_MMP8 = KD_MMP8 * (MMP8_T - MMP8);
dxdt_TIMP = KD_TIMP * (TIMP_T - TIMP);

// ACTIVE MMP-8. Doxycycline inhibits the ENZYME, not its synthesis: it chelates
// the catalytic Zn2+ and blocks oxidative pro-enzyme activation. That is why a
// sub-antimicrobial dose works at all.
double E_DOXY  = EMAX_DOXY * DOXG / (IC50_DOXY + DOXG);
double ACTIVN  = 0.5 + 0.5 * PMN;                       // HOCl-driven activation
double MMP8A   = MMP8 * ACTIVN * (2.0 / (1.0 + TIMP)) * (1.0 - E_DOXY);

//---------------------------------------------------------------------------
// 8. RANKL / OPG AND THE OSTEOCLAST
//---------------------------------------------------------------------------
double RANKL_T = W_RANKL_T*TH17 + W_RANKL_B*BPC
               + W_RANKL_S*(0.4*IL1B + 0.3*TNFA + 0.3*PGE2);
double OPG_T   = 0.6*OBL + 0.4;
dxdt_RANKL = KD_RANKL * (RANKL_T - RANKL);
dxdt_OPG   = KD_OPG   * (OPG_T   - OPG);

// Denosumab sequesters RANKL competitively.
double RANKL_FREE = RANKL * KD_DMAB / (KD_DMAB + CDMAB);
double RATIO      = (RANKL_FREE / (OPG > 0.05 ? OPG : 0.05));
double OCF        = pow(RATIO, HOC);
if (OCF > OC_MAX) OCF = OC_MAX;
dxdt_OCL = KOCT * (OCF * (1.0 - E_DOXY_OC * (E_DOXY / EMAX_DOXY)) - OCL);

double OBF = (1.0 + 4.0 * REGD) / (1.0 + SCL_GAIN * IEX);
dxdt_OBL = KOBT * (OBF - OBL);

//---------------------------------------------------------------------------
// 9. THE RATCHET — bone loss, attachment level, gingival margin
//---------------------------------------------------------------------------
// Waerhaug safe distance: bone resorbs to keep ~1.5-2 mm from the plaque front.
// Note that the model is NOT told what the safe distance settles to; SAFE_DIST
// is the gate midpoint, and the realised distance is an emergent equilibrium.
double DIST = PHYS_DIST + BLOSS - CAL;
double GATE = 1.0 / (1.0 + exp((DIST - SAFE_DIST) / SAFE_W));

double BONE_RESORB = KRES_BONE * OCL * GATE;
double BONE_FORM   = (KFORM_BONE * OBL + (REGEN_FILL * KOUT_REG) * REGD)
                   * (BLOSS / (0.05 + CPOS(BLOSS)));
dxdt_BLOSS = BONE_RESORB - BONE_FORM;

// Attachment: lost to active collagenase, regained ONLY as long junctional
// epithelium, and never coronal to what the bone supports.
double RESOLVED = 1.0 / (1.0 + IEX / KRES_I);
// Attachment removed by an instrument does not come back: cementum and the
// inserting fibres are gone. SCAR therefore raises the floor permanently, which
// is the quantitative case against re-instrumenting shallow healthy sites at
// every recall visit.
double CAL_GAP  = CPOS(CAL - BLOSS - LJE_GAP - SCAR);
// Instrumentation trauma. Closed instrumentation removes a little attachment
// AND lets the margin follow it apically, so PPD is unchanged and only CAL is
// spent — which is precisely why SRP is a losing trade in a shallow site. A
// flap creates far more recession than attachment loss, so it buys PPD
// reduction with attachment: a different, and also losing, trade when shallow.
double TRAUMA_CAL = SRP_TRAUMA * KOUT_MECH * MECHD + SURG_TRAUMA * KOUT_SURG * SURGD;
double TRAUMA_GM  = SRP_TRAUMA * KOUT_MECH * MECHD + SURG_REC    * KOUT_SURG * SURGD;

// The inflammatory front cannot migrate apical to the bone that supports it:
// there has to be a supracrestal attachment for the probe to stop against. So
// soft-tissue attachment loss STALLS as DIST approaches its floor and can only
// resume once the osteoclasts have moved the bone crest out of the way. This
// is what couples the two rates, and it is why the realised plaque-front-to-
// bone distance settles in the 1-2 mm range Waerhaug measured rather than
// being written into the model as a target.
double SOFT_GATE = 1.0 / (1.0 + exp(-(DIST - DIST_MIN) / DIST_W));

dxdt_CAL = KCS * (1.0 + KCS_PPD * CPOS(PPD - 3.0)) * SOFT_GATE * CPOS(MMP8A - MMP8A_TH)
         + CPOS(BONE_RESORB - BONE_FORM)
         - KHEAL * RESOLVED * CAL_GAP
         + TRAUMA_CAL;

// Gingival margin: structurally follows a fraction of the bone loss, but is
// pushed coronally by oedema. Resolution therefore CREATES recession.
double GM_T = GMB + GM_BONE * BLOSS - SWELL * IEX + GSCAR;
dxdt_GM = KGM * (GM_T - GM);

// Barrier and exudate
double NETLOAD = 0.5 * PMN;
dxdt_EPI = KREP_EPI * (1.0 - EPI) - KDAM_EPI * EPI * (GING + MMP8A + NETLOAD);

double GCF_T = GCF0 * (1.0 + GMAX_GCF * IEX / (KGI + IEX)) * ((2.0 - EPI) / (2.0 - EPI_REF));
dxdt_GCF = KGCF * (GCF_T - GCF);

//---------------------------------------------------------------------------
// 10. WHOLE-MOUTH BURDEN AND SYSTEMIC SPILLOVER
//---------------------------------------------------------------------------
double BOP_SITE = 1.0 / (1.0 + exp(-BOP_A * (INFLAM - BOP_B)))
                * (1.0 - SMOKE_BOP * SMOKE);
double NSITES   = NTEETH * SITES_TOOTH;
// PISA: ulcerated pocket epithelium of BLEEDING sites only (Nesse 2008).
double PISA = NSITES * FRAC_DEEP        * BOP_SITE    * PPD_TRUE    * AREA_W
            + NSITES * (1.0-FRAC_DEEP)  * BOP_SHALLOW * PPD_SHALLOW * AREA_W;

double PEX    = CPOS(PISA - PISA_REF);
double IL6S_T = 1.0 + SP_MAX * PEX / (KP_PISA + PEX) + BACT_GAIN * BACT;
dxdt_IL6S = KI6 * (IL6S_T - IL6S);

double CRP_T = CRP_BASE * pow(IL6S, CRP_HILL);
dxdt_CRP = KCRP * (CRP_T - CRP);

double INSR_T = 1.0 + IR_GAIN * CPOS(IL6S - 1.0);
dxdt_INSR = KIR * (INSR_T - INSR);

double HB_T = HB_SET + HB_IR * CPOS(INSR - 1.0) - GLYC_RX;
dxdt_HBA1C = (HB_T - HBA1C) / TAU_HB;

double FMD_T = FMD_MAX - FMD_CRP * log(1.0 + CRP)
             - FMD_IL6 * CPOS(IL6S - 1.0) - FMD_ACUTE * BACT;
dxdt_FMD = KFMD * (FMD_T - FMD);

//---------------------------------------------------------------------------
// 11. HAZARDS
//---------------------------------------------------------------------------
dxdt_HTOOTH = H0_TOOTH * exp(BT_BONE * (BLOSS / BLOSS_CRIT));
dxdt_SCAR  = TRAUMA_CAL;
dxdt_GSCAR = TRAUMA_GM;

dxdt_HMRONJ = H0_MRONJ * (CDMAB / (KD_MR + CDMAB))
            * (1.0 + MRONJ_SURG * (SURGD > 0.01 ? 1.0 : 0.0));

//===========================================================================
$TABLE
double M1M2_o   = M1 / (M2 > 0.05 ? M2 : 0.05);
double INFLAM_o = 0.28*IL1B + 0.24*TNFA + 0.18*IL17 + 0.15*PGE2 + 0.15*M1M2_o;
double IEX_o    = CPOS(INFLAM_o - 1.0);
double PENETR_o = PEN * IEX_o / (KPEN + IEX_o);
double PPDT_o   = CPOS(CAL - GM);
double PPD_o    = PPDT_o + PENETR_o;
double CAL_m    = CAL + PENETR_o;
double BOPs_o   = 100.0 / (1.0 + exp(-BOP_A*(INFLAM_o - BOP_B))) * (1.0 - SMOKE_BOP*SMOKE);
double NS_o     = NTEETH * SITES_TOOTH;
double PISA_o   = NS_o*FRAC_DEEP*(BOPs_o/100.0)*PPDT_o*AREA_W
                + NS_o*(1.0-FRAC_DEEP)*BOP_SHALLOW*PPD_SHALLOW*AREA_W;
double E_DOXY_o = EMAX_DOXY * DOXG / (IC50_DOXY + DOXG);
double MMP8A_o  = MMP8 * (0.5 + 0.5*PMN) * (2.0/(1.0+TIMP)) * (1.0 - E_DOXY_o);
double RFREE_o  = RANKL * KD_DMAB / (KD_DMAB + DMABC/V_DMAB);
double RATIO_o  = RFREE_o / (OPG > 0.05 ? OPG : 0.05);
double DIST_o   = PHYS_DIST + BLOSS - CAL;
double SRPEFF_o = SRP_EMAX / (1.0 + exp((PPD_o - PPD50_SRP)/PPD_W));
double SURGEF_o = SRP_EMAX / (1.0 + exp((PPD_o - PPD50_SURG)/PPD_W));
double SRPBIO_o = BIO_REM_MAX / (1.0 + exp((PPD_o - PPD50_BIO)/PPD_W_BIO));
double PKN_o    = PKILL / PKILL_REF;
double TSURV_o  = exp(-HTOOTH) * 100.0;                 // % tooth survival
double MRONJ_o  = (1.0 - exp(-HMRONJ)) * 100.0;         // % cumulative MRONJ risk
// Reported-unit surrogates for the normalised mediator compartments
double MMP8_ng  = 18.0 * MMP8A_o;                       // GCF MMP-8, ng/mL
double IL1B_pg  = 22.0 * IL1B;                          // GCF IL-1beta, pg/site
double GCF_ul   = GCF;                                  // uL/min/site

$CAPTURE @annotated
INFLAM_o : Composite inflammatory tone, health = 1 (unit)
PPD_o    : Measured probing pocket depth (mm)
PPDT_o   : True probing depth, no penetration artefact (mm)
CAL_m    : MEASURED clinical attachment level, probe-based (mm)
BOPs_o   : Bleeding on probing (%)
PISA_o   : Periodontal inflamed surface area (mm2)
MMP8A_o  : Active MMP-8, health = 1 (unit)
MMP8_ng  : Gingival crevicular fluid MMP-8 (ng/mL)
IL1B_pg  : Gingival crevicular fluid IL-1beta (pg/site)
GCF_ul   : Gingival crevicular fluid flow (uL/min)
RATIO_o  : Free RANKL to OPG ratio (unit)
DIST_o   : Distance from plaque front to bone crest (mm)
SRPEFF_o : Achievable closed CALCULUS removal at current depth (frac)
SURGEF_o : Achievable open-flap CALCULUS removal at current depth (frac)
SRPBIO_o : Achievable closed BIOFILM disruption at current depth (frac)
PKN_o    : Neutrophil killing capacity relative to health (frac)
TSURV_o  : Tooth survival (%)
MRONJ_o  : Cumulative MRONJ risk (%)
'

## ---------------------------------------------------------------------------
## Build
## ---------------------------------------------------------------------------
pdt_model <- function() {
  mcode_cache("pdt_qsp", pdt_code)
}

## ---------------------------------------------------------------------------
## Phenotype presets
## ---------------------------------------------------------------------------
## The healthy steady state is not hard-coded; PDT_seed() runs the system to its
## own attractor from a chosen starting biomass, which is the only honest way to
## initialise a bistable model.
## ---------------------------------------------------------------------------

PDT_seed <- function(mod, bloss0 = 4.5, burn = 250, param = list(), init = list()) {
  m <- mod
  if (length(param)) m <- param(m, param)
  ini <- list(BLOSS = bloss0, CAL = bloss0 + 0.5)
  ini[names(init)] <- init
  m <- init(m, ini)
  out  <- mrgsim_df(m, end = burn, delta = burn, atol = 1e-8, rtol = 1e-6)
  last <- out[nrow(out), ]
  nm <- names(as.list(init(mod)))
  st <- as.list(last[intersect(names(last), nm)])
  # The burn-in equilibrates the fast microbial / immune / soft-tissue states.
  # Bone is a slow integral and must NOT be allowed to drift away from the
  # depth we asked for, otherwise every phenotype converges on the same site.
  gap <- st$CAL - st$BLOSS
  st$BLOSS <- bloss0
  st$CAL   <- bloss0 + gap
  st
}

## Convenience: a model object already sitting at the requested attractor.
PDT_patient <- function(mod, bloss0 = 4.5, param = list(), burn = 250, init = list()) {
  st <- PDT_seed(mod, bloss0 = bloss0, burn = burn, param = param, init = init)
  m <- mod
  if (length(param)) m <- param(m, param)
  init(m, st)
}

## ---------------------------------------------------------------------------
## Dosing regimen builders
## ---------------------------------------------------------------------------

## Closed subgingival instrumentation. One "course" of SRP is delivered as
## quadrant sessions; each session also produces a bacteraemia pulse.
ev_srp <- function(times = c(0, 7), bact = 1.0) {
  e <- NULL
  for (t in times) {
    e <- c(e, list(ev(time = t, amt = 1, cmt = "MECHD"),
                   ev(time = t, amt = bact, cmt = "BACT")))
  }
  do.call(c, e)
}

ev_surgery <- function(time = 0, bact = 1.4) {
  c(ev(time = time, amt = 1, cmt = "SURGD"),
    ev(time = time, amt = bact, cmt = "BACT"))
}

ev_regen <- function(time = 0) ev(time = time, amt = 1, cmt = "REGD")

## Sub-antimicrobial-dose doxycycline: 20 mg twice daily (Periostat).
ev_sdd <- function(start = 0, days = 270) {
  ev(time = start, amt = 20, cmt = "DOXGUT", ii = 0.5, addl = days * 2 - 1)
}

## Van Winkelhoff cocktail: amoxicillin 500 mg + metronidazole 400 mg TID x 7 d.
ev_amox_metro <- function(start = 0, days = 7) {
  c(ev(time = start, amt = 500, cmt = "AMXGUT", ii = 1/3, addl = days * 3 - 1),
    ev(time = start, amt = 400, cmt = "MTZGUT", ii = 1/3, addl = days * 3 - 1))
}

## Minocycline microspheres 1 mg per site, repeated at 3 and 6 months.
ev_minocycline <- function(times = c(0, 90, 180)) {
  do.call(c, lapply(times, function(t) ev(time = t, amt = 1, cmt = "MINDEP")))
}

## Chlorhexidine 0.12% rinse twice daily.
ev_chx <- function(start = 0, days = 60) {
  ev(time = start, amt = 1, cmt = "CHXLOC", ii = 0.5, addl = days * 2 - 1)
}

## AMY-101 (Cp40) local gingival injection, 3 weekly doses (phase IIa schedule).
ev_amy101 <- function(times = c(0, 7, 14)) {
  do.call(c, lapply(times, function(t) ev(time = t, amt = 1, cmt = "AMYLOC")))
}

ev_rve1 <- function(times = seq(0, 84, by = 7)) {
  do.call(c, lapply(times, function(t) ev(time = t, amt = 1, cmt = "RVELOC")))
}

ev_antitnf <- function(start = 0, n = 7, mgkg = 5, wt = 70) {
  ev(time = start, amt = mgkg * wt, cmt = "TNFIC", ii = 56, addl = n - 1)
}

ev_denosumab <- function(start = 0, n = 4) {
  ev(time = start, amt = 60, cmt = "DMABSC", ii = 182, addl = n - 1)
}

## Supportive periodontal therapy: 3-monthly recall instrumentation.
## Supportive periodontal therapy: 3-monthly recall. A maintenance visit is NOT
## a repeat of initial root planing — it is a partial debridement, and it is
## modelled as such (amt = 0.25), because in this model instrumentation costs
## attachment permanently and 40 full root-planings over 10 years would remove
## more attachment than the disease.
ev_spt <- function(from = 90, to = 1825, every = 90, amt = 0.25) {
  e <- NULL
  for (t in seq(from, to, by = every))
    e <- c(e, list(ev(time = t, amt = amt,       cmt = "MECHD"),
                   ev(time = t, amt = 0.5 * amt, cmt = "BACT")))
  do.call(c, e)
}

## ---------------------------------------------------------------------------
## Scenario engine
## ---------------------------------------------------------------------------

PDT_simulate_scenarios <- function(mod = pdt_model(), end = 365, delta = 1) {
  # The scenarios are run at a DEEP site (baseline ~8 mm) on purpose: that is the
  # only place the adjuncts can differ, because at 4-6 mm closed instrumentation
  # already crosses the separatrix on its own and every adjunct arm collapses
  # onto the same curve. Seeing them separate only in deep pockets is a result,
  # not a limitation.
  base <- PDT_patient(mod, bloss0 = 7.2)                         # deep, ~8 mm
  mod4 <- PDT_patient(mod, bloss0 = 4.5)                         # moderate, ~6 mm
  shal <- PDT_patient(mod, bloss0 = 1.0)                         # shallow, ~3 mm
  dm   <- PDT_patient(mod, bloss0 = 7.2, param = list(HB_SET = 8.3))
  smk  <- PDT_patient(mod, bloss0 = 7.2, param = list(SMOKE = 1))

  run <- function(m, e = NULL, lab, p = list(), tend = end) {
    mm <- if (length(p)) param(m, p) else m
    d  <- if (is.null(e)) mrgsim_df(mm, end = tend, delta = delta)
          else mrgsim_df(mm, events = e, end = tend, delta = delta)
    d$scenario <- lab
    d
  }

  OHI_ON <- list(OHI = 0.6)

  scn <- list(
    run(base, NULL, "1. Untreated natural history"),
    run(base, ev_srp(), "2. OHI + SRP (deep ~8 mm site)", OHI_ON),
    run(mod4, ev_srp(), "2b. OHI + SRP (moderate ~6 mm site)", OHI_ON),
    run(shal, ev_srp(), "3. OHI + SRP (shallow 3 mm site)", OHI_ON),
    run(base, c(ev_srp(), ev_amox_metro()),
        "4. SRP + amoxicillin/metronidazole", OHI_ON),
    run(base, c(ev_srp(), ev_minocycline()),
        "5. SRP + local minocycline", OHI_ON),
    run(base, c(ev_srp(), ev_sdd()),
        "6. SRP + SDD doxycycline 20 mg BID", OHI_ON),
    run(base, c(ev_srp(), ev_chx()),
        "7. SRP + chlorhexidine rinse only", OHI_ON),
    run(base, ev_surgery(),
        "8. Open flap surgery (deep site)", OHI_ON),
    run(base, c(ev_srp(), ev_amy101()),
        "9. SRP + AMY-101 (C3 inhibitor)", OHI_ON),
    run(dm, ev_srp(),
        "10. SRP, uncontrolled diabetes (HbA1c 8.3)", OHI_ON),
    run(base, c(ev_srp(), ev_spt(from = 90, to = 365)),
        "12. SRP + 3-monthly supportive therapy", OHI_ON),
    run(smk, ev_srp(),
        "11. SRP, heavy smoker", OHI_ON)
  )
  do.call(rbind, scn)
}


## ---------------------------------------------------------------------------
## SITE POPULATIONS — why individual sites are bimodal but trial means are not
## ---------------------------------------------------------------------------
## A single site in this model is BISTABLE: after debridement it either falls
## into the health basin or it does not. Real periodontal trials do not report
## sites, they report the MEAN of a band of sites, and the bands straddle the
## separatrix. So a graded, smoothly depth-dependent mean is exactly what you
## get by averaging a knife-edge over a distribution of pocket depths — no
## smoothing of the underlying biology required, and none is applied here.
##
## This also makes a testable prediction that a purely descriptive dose-response
## model cannot make: within a depth band the RESPONSE DISTRIBUTION should be
## bimodal (responders and non-responders), not unimodal around the mean. That
## is what site-specific longitudinal studies actually observe, and what the
## "burst" description of periodontal progression was invented to describe.
## PDT_site_population() returns both the band means and the response spread.
## ---------------------------------------------------------------------------

PDT_site_population <- function(mod = pdt_model(), therapy = "SRP",
                                bloss = c(seq(0.05, 1.0, by = 0.15), seq(1.3, 9.4, by = 0.3)),
                                horizon = 365, param = list(),
                                activity = function(ppd) 1/(1 + exp(-(ppd - 4.2)/0.9))) {
  OHI_ON <- c(list(OHI = 0.6), param)
  ev_for <- function(w) switch(w,
    "none"       = NULL,
    "SRP"        = ev_srp(),
    "SURGERY"    = ev_surgery(),
    "SRP_AM"     = c(ev_srp(), ev_amox_metro()),
    "SRP_SDD"    = c(ev_srp(), ev_sdd()),
    "SRP_MINO"   = c(ev_srp(), ev_minocycline()),
    "SRP_CHX"    = c(ev_srp(), ev_chx()),
    "SRP_AMY"    = c(ev_srp(), ev_amy101()),
    "AMY"        = ev_amy101(),
    stop("unknown therapy"))
  e <- ev_for(therapy)

  # A site is in one of the two basins. Which one is NOT a free parameter of the
  # site: it is what the site's own history left it in. The population therefore
  # carries BOTH basins at every depth, weighted by an activity prevalence that
  # rises with depth — an epidemiological observation (bleeding sites are deeper
  # sites), not a mechanistic assumption of the model.
  one <- function(b, basin) {
    ini <- if (basin == "health")
      list(BIOS = 0.64, BIOD = 0.002, PG = 5e-4, GING = 0.02, LPSN = 1.0, CALC = 0.01,
           C5A = 0.95, PMN = 0.95, PKILL = 0.82, M1 = 0.95, M2 = 1.0, TH17 = 0.95,
           TREG = 1.0, BPC = 0.95, IL1B = 0.95, TNFA = 0.95, IL17 = 0.95, PGE2 = 0.95,
           MMP8 = 0.95, TIMP = 1.0, RANKL = 0.95, OPG = 1.0, OCL = 0.95, OBL = 1.0,
           EPI = 0.82, GCF = 0.07, IL6S = 1.0, CRP = 0.95, INSR = 1.0, FMD = 7.1)
      else list()
    pt <- param(PDT_patient(mod, bloss0 = b, param = param, init = ini), OHI_ON)
    o0 <- mrgsim_df(pt, end = 1, delta = 1)
    o  <- if (is.null(e)) mrgsim_df(pt, end = horizon, delta = horizon)
          else mrgsim_df(pt, events = e, end = horizon, delta = horizon)
    i <- nrow(o)
    data.frame(BLOSS0 = b, basin = basin, PPD0 = o0$PPD_o[1],
               dPPD = o0$PPD_o[1] - o$PPD_o[i],
               dCAL = o0$CAL_m[1] - o$CAL_m[i],
               dBONE = o$BLOSS[i] - o0$BLOSS[1],
               INFLAM0 = o0$INFLAM_o[1], INFLAM_end = o$INFLAM_o[i],
               healed = as.integer(o$INFLAM_o[i] < 1.6))
  }
  rows <- c(lapply(bloss, one, basin = "disease"),
            lapply(bloss, one, basin = "health"))
  out <- do.call(rbind, rows)
  pa  <- activity(out$PPD0)
  out$weight <- ifelse(out$basin == "disease", pa, 1 - pa)
  out$band <- cut(out$PPD0, breaks = c(-Inf, 3.5, 6.5, Inf),
                  labels = c("1-3 mm", "4-6 mm", ">=7 mm"))
  out
}

PDT_bands <- function(pop) {
  wm <- function(f) tapply(seq_len(nrow(pop)), pop$band,
                           function(i) sum(f[i]*pop$weight[i])/sum(pop$weight[i]))
  data.frame(band        = levels(pop$band),
             n_sites     = as.vector(table(pop$band)),
             PPD_red_mm  = round(as.vector(wm(pop$dPPD)), 2),
             CAL_gain_mm = round(as.vector(wm(pop$dCAL)), 2),
             pct_active  = round(100 * as.vector(wm(as.numeric(pop$basin=="disease")))),
             pct_healed  = round(100 * as.vector(wm(pop$healed))),
             stringsAsFactors = FALSE)
}

## Convenience wrapper used by the calibration report.
PDT_band_value <- function(mod, therapy, band, what, param = list(), horizon = 365) {
  b <- PDT_bands(PDT_site_population(mod, therapy, horizon = horizon, param = param))
  b[[what]][b$band == band]
}

## ---------------------------------------------------------------------------
## ANALYSIS 1 — Calibration report
## Every target below comes from the literature and NONE of them was used as an
## objective function; the parameters were set from mechanism and the outputs
## are compared here.
## ---------------------------------------------------------------------------

PDT_calibration_report <- function(mod = pdt_model(), verbose = TRUE) {
  at <- function(d, t, v) d[[v]][which.min(abs(d$time - t))]
  OHI_ON <- list(OHI = 0.6)
  g <- function(m, e, p = OHI_ON, end = 365)
    mrgsim_df(param(m, p), events = e, end = end, delta = 1)

  if (verbose) message("  running site populations (7 arms) ...")
  P <- lapply(c("none","SRP","SURGERY","SRP_AM","SRP_SDD","SRP_MINO","SRP_CHX"),
              function(t) PDT_bands(PDT_site_population(mod, t)))
  names(P) <- c("none","SRP","SURG","AM","SDD","MINO","CHX")
  v <- function(arm, band, col) P[[arm]][[col]][P[[arm]]$band == band]

  base <- PDT_patient(mod, bloss0 = 4.5)
  s_nat  <- mrgsim_df(base, end = 1825, delta = 5)
  s_srp  <- g(base, ev_srp())
  s_sdd  <- g(base, c(ev_srp(), ev_sdd()))
  s_amy  <- g(base, ev_amy101())      # phase IIa gave AMY-101 with NO debridement
  s_none <- g(base, NULL)
  s_dm   <- g(PDT_patient(mod, bloss0 = 4.5, param = list(HB_SET = 7.4)), ev_srp())
  s_smk  <- g(PDT_patient(mod, bloss0 = 4.5, param = list(SMOKE = 1)), ev_srp())
  d <- function(s, vr, t = 180) at(s, t, vr) - at(s, 0, vr)

  # Depth-dependent instrumentation efficacy, evaluated directly from the
  # logistic at Waerhaug's three measured depths.
  pp <- as.list(param(mod))
  waer <- function(x) 100 * pp$SRP_EMAX / (1 + exp((x - pp$PPD50_SRP)/pp$PPD_W))

  rows <- list(
    c("SRP, 1-3 mm band: PPD reduction (mm)",   sprintf("%+.2f", v("SRP","1-3 mm","PPD_red_mm")),  "-0.03  (Cobb 1996/2002)"),
    c("SRP, 1-3 mm band: CAL change (mm)",      sprintf("%+.2f", v("SRP","1-3 mm","CAL_gain_mm")), "-0.34  (Cobb)"),
    c("SRP, 4-6 mm band: PPD reduction (mm)",   sprintf("%+.2f", v("SRP","4-6 mm","PPD_red_mm")),  "+1.29  (Cobb)"),
    c("SRP, 4-6 mm band: CAL gain (mm)",        sprintf("%+.2f", v("SRP","4-6 mm","CAL_gain_mm")), "+0.55  (Cobb)"),
    c("SRP, >=7 mm band: PPD reduction (mm)",   sprintf("%+.2f", v("SRP",">=7 mm","PPD_red_mm")),  "+2.16  (Cobb)"),
    c("SRP, >=7 mm band: CAL gain (mm)",        sprintf("%+.2f", v("SRP",">=7 mm","CAL_gain_mm")), "+1.19  (Cobb)"),
    c("Surgery, 1-3 mm band: CAL change (mm)",  sprintf("%+.2f", v("SURG","1-3 mm","CAL_gain_mm")),"-0.60  (Lindhe 1982)"),
    c("Surgery, >=7 mm band: PPD reduction (mm)",sprintf("%+.2f", v("SURG",">=7 mm","PPD_red_mm")),"+2.90  (Lindhe/Heitz-Mayfield)"),
    c("Surgery, >=7 mm band: CAL gain (mm)",    sprintf("%+.2f", v("SURG",">=7 mm","CAL_gain_mm")),"+1.60  (Lindhe)"),
    c("Surgery MINUS SRP, 4-6 mm: CAL (mm)",    sprintf("%+.2f", v("SURG","4-6 mm","CAL_gain_mm") - v("SRP","4-6 mm","CAL_gain_mm")), "negative: SRP wins (Lindhe)"),
    c("Surgery MINUS SRP, >=7 mm: CAL (mm)",    sprintf("%+.2f", v("SURG",">=7 mm","CAL_gain_mm") - v("SRP",">=7 mm","CAL_gain_mm")), "positive: surgery wins"),
    c("Amox+metro adjunctive CAL gain, >=7 mm (mm)", sprintf("%+.2f", v("AM",">=7 mm","CAL_gain_mm") - v("SRP",">=7 mm","CAL_gain_mm")), "+0.40 to +0.50 (Feres 2012)"),
    c("SDD doxycycline adjunctive CAL gain, >=7 mm (mm)", sprintf("%+.2f", v("SDD",">=7 mm","CAL_gain_mm") - v("SRP",">=7 mm","CAL_gain_mm")), "+0.30 to +0.40 (Caton 2000)"),
    c("Local minocycline adjunctive PPD reduction, >=7 mm (mm)", sprintf("%+.2f", v("MINO",">=7 mm","PPD_red_mm") - v("SRP",">=7 mm","PPD_red_mm")), "+0.25 to +0.30 (Williams 2001)"),
    c("Chlorhexidine rinse adjunctive PPD reduction, >=7 mm (mm)", sprintf("%+.2f", v("CHX",">=7 mm","PPD_red_mm") - v("SRP",">=7 mm","PPD_red_mm")), "~0.00 (no subgingival access)"),
    c("Untreated 1-year CAL loss, >=7 mm band (mm)", sprintf("%+.2f", -v("none",">=7 mm","CAL_gain_mm")), "0.5 - 1.0 (Loe 1986, rapid)"),
    c("Untreated alveolar bone loss (mm/year)", sprintf("%.2f", (at(s_nat,1825,"BLOSS") - at(s_nat,0,"BLOSS"))/5), "0.15 - 0.40"),
    c("Calculus-free root surface at 3.0 mm (%)", sprintf("%.0f", waer(3.0)), "83  (Waerhaug 1978)"),
    c("Calculus-free root surface at 4.5 mm (%)", sprintf("%.0f", waer(4.5)), "61  (Waerhaug)"),
    c("Calculus-free root surface at 6.5 mm (%)", sprintf("%.0f", waer(6.5)), "32  (Waerhaug)"),
    c("SDD doxycycline: GCF collagenase reduction at 6 mo (%)",
      sprintf("%.0f", 100*(1 - at(s_sdd,180,"MMP8A_o")/at(s_srp,180,"MMP8A_o"))), "60 - 70 (Golub/Caton)"),
    c("AMY-101 alone: reduction in inflammatory tone at day 28 (%)",
      sprintf("%.0f", 100*(1 - at(s_amy,28,"INFLAM_o")/at(s_none,28,"INFLAM_o"))), "46  (Hasturk 2021)"),
    c("Maximum achievable C5a suppression by C3 blockade (%)",
      sprintf("%.0f", 100*(1 - at(s_amy,21,"C5A")/at(s_none,21,"C5A"))), "<100: gingipain floor"),
    c("HbA1c fall after therapy, HbA1c 7.4 at baseline (%)", sprintf("%.2f", -d(s_dm, "HBA1C", 120)), "0.43 (Simpson 2022 Cochrane)"),
    c("CRP fall after therapy (mg/L)",   sprintf("%.2f", -d(s_srp, "CRP")), "0.4 - 0.9 (D'Aiuto/Tonetti)"),
    c("FMD gain at 6 months (%)",        sprintf("%+.2f", d(s_srp, "FMD")), "+2.00 (Tonetti 2007)"),
    c("FMD change at 24 h after full-mouth therapy (%)",
      sprintf("%+.2f", at(s_srp,1,"FMD") - at(s_srp,0,"FMD")), "negative (Tonetti 2007)"),
    c("PISA, untreated generalised Stage III (mm2)", sprintf("%.0f", at(s_srp,0,"PISA_o")), "1000 - 2000 (Nesse 2008)"),
    c("Smoker deficit in PPD reduction vs non-smoker (mm)",
      sprintf("%+.2f", -(d(s_smk,"PPD_o") - d(s_srp,"PPD_o"))), "-0.40 to -0.50"),
    c("Smoker vs non-smoker BOP at baseline (%)",
      sprintf("%.0f vs %.0f", at(s_smk,0,"BOPs_o"), at(s_srp,0,"BOPs_o")), "lower in smokers (masking)"),
    c("Emergent plaque-front-to-bone-crest distance (mm)",
      sprintf("%.2f", at(s_nat, 1825, "DIST_o")), "1.0 - 2.0 (Waerhaug safe distance)"),
    c("Neutrophil killing capacity, untreated disease (% of health)",
      sprintf("%.0f", 100*at(s_srp,0,"PKN_o")), "20 - 50 (Maekawa 2014)")
  )
  out <- as.data.frame(do.call(rbind, rows), stringsAsFactors = FALSE)
  names(out) <- c("Endpoint", "Model", "Literature target")
  attr(out, "bands") <- P
  out
}

## ---------------------------------------------------------------------------
## ANALYSIS 2 — Critical probing depth (Lindhe 1982)
## The model was never given a critical probing depth. It emerges from a single
## anatomical trade: surgery raises PPD50 from 5.6 to 9.5 mm and charges a fixed
## recession + attachment-trauma cost.
## ---------------------------------------------------------------------------

PDT_critical_depth <- function(mod = pdt_model(), horizon = 365, pops = NULL) {
  if (is.null(pops))
    pops <- list(SRP     = PDT_site_population(mod, "SRP",     horizon = horizon),
                 SURGERY = PDT_site_population(mod, "SURGERY", horizon = horizon))
  # Weighted CAL gain as a continuous function of baseline probing depth,
  # averaging the quiescent and active site populations at each depth.
  curve <- function(p) {
    d  <- unique(p$BLOSS0)
    do.call(rbind, lapply(d, function(b) {
      i <- p$BLOSS0 == b
      data.frame(PPD0 = sum(p$PPD0[i]*p$weight[i])/sum(p$weight[i]),
                 CAL  = sum(p$dCAL[i]*p$weight[i])/sum(p$weight[i]))
    }))
  }
  a <- curve(pops$SRP); s <- curve(pops$SURGERY)
  out <- data.frame(PPD0 = a$PPD0, CALgain_SRP = a$CAL, CALgain_SURG = s$CAL)
  out <- out[order(out$PPD0), ]
  cross <- function(x, y) {
    i <- which(diff(sign(y)) != 0)[1]
    if (is.na(i)) return(NA_real_)
    x[i] + (0 - y[i]) * (x[i+1] - x[i]) / (y[i+1] - y[i])
  }
  attr(out, "critical_PD_SRP")     <- cross(out$PPD0, out$CALgain_SRP)
  attr(out, "critical_PD_SURGERY") <- cross(out$PPD0, out$CALgain_SURG)
  attr(out, "SRP_SURG_crossover")  <- cross(out$PPD0, out$CALgain_SURG - out$CALgain_SRP)
  out
}

## ---------------------------------------------------------------------------
## ANALYSIS 3 — The separatrix
## Locate the tipping point of the inflammophilic feedback loop by bisection on
## the residual dysbiotic biomass immediately after debridement.
## ---------------------------------------------------------------------------

PDT_separatrix <- function(mod = pdt_model(), bloss0 = 4.5, param = list(),
                           horizon = 720, tol = 1e-3) {
  pt <- PDT_patient(mod, bloss0 = bloss0, param = param)
  st <- as.list(init(pt))
  bd0 <- st$BIOD
  relapses <- function(frac) {
    s2 <- st; s2$BIOD <- bd0 * frac; s2$PG <- st$PG * frac; s2$CALC <- st$CALC * frac
    o <- mrgsim_df(init(pt, s2), end = horizon, delta = horizon)
    o$BIOD[nrow(o)] > 0.5 * bd0
  }
  lo <- 0.0; hi <- 1.0
  if (!relapses(hi)) return(list(separatrix_fraction = NA_real_,
                                 note = "System is monostable-healthy at these parameters"))
  if (relapses(1e-6)) return(list(separatrix_fraction = 0,
                                  note = "System is monostable-diseased: no debridement suffices"))
  while (hi - lo > tol) {
    mid <- 0.5 * (lo + hi)
    if (relapses(mid)) hi <- mid else lo <- mid
  }
  frac <- 0.5 * (lo + hi)
  o <- mrgsim_df(pt, end = 1, delta = 1)
  list(separatrix_fraction   = frac,
       required_log_reduction = -log10(frac),
       baseline_PPD           = o$PPD_o[1],
       biofilm_disruption_SRP     = o$SRPBIO_o[1],
       calculus_removal_SRP       = o$SRPEFF_o[1],
       calculus_removal_surgery   = o$SURGEF_o[1],
       verdict = if (1 - o$SRPBIO_o[1] < frac)
                   "Closed instrumentation ALONE crosses the separatrix at this depth"
                 else
                   "Closed instrumentation leaves more than the separatrix allows: relapse expected without an adjunct or open access")
}

## ---------------------------------------------------------------------------
## ANALYSIS 4 — What a millimetre of PPD reduction is actually made of
## ---------------------------------------------------------------------------

PDT_decompose <- function(mod = pdt_model(), bloss0 = 4.5, t = 180) {
  pt <- param(PDT_patient(mod, bloss0 = bloss0), OHI = 0.6)
  o  <- mrgsim_df(pt, events = ev_srp(), end = t, delta = 1)
  i0 <- 1; i1 <- nrow(o)
  dPPD <- o$PPD_o[i0] - o$PPD_o[i1]
  dCAL <- o$CAL[i0]   - o$CAL[i1]        # TRUE attachment gain
  dGM  <- o$GM[i1]    - o$GM[i0]
  dPEN <- (o$PPD_o[i0] - o$PPDT_o[i0]) - (o$PPD_o[i1] - o$PPDT_o[i1])
  data.frame(
    component = c("True attachment gain (CAL)", "Recession (gingival shrinkage)",
                  "Reduced probe penetration", "TOTAL PPD reduction"),
    mm        = round(c(dCAL, dGM, dPEN, dPPD), 3),
    percent   = round(100 * c(dCAL, dGM, dPEN, dPPD) / dPPD, 1)
  )
}

## ---------------------------------------------------------------------------
## ANALYSIS 5 — Bone is an integral, so timing is a treatment effect
## Two identical courses of therapy, one delayed. Same endpoint inflammation;
## different bone, because the ratchet ran for longer.
## ---------------------------------------------------------------------------

PDT_timing <- function(mod = pdt_model(), delays = c(0, 365, 1095, 2190),
                       horizon = 3650) {
  pt <- param(PDT_patient(mod, bloss0 = 2.5), OHI = 0.6)
  do.call(rbind, lapply(delays, function(d) {
    e <- c(ev_srp(times = c(d, d + 7)), ev_spt(from = d + 90, to = horizon))
    o <- mrgsim_df(pt, events = e, end = horizon, delta = 30)
    data.frame(delay_years   = d / 365,
               bone_loss_mm  = round(o$BLOSS[nrow(o)], 2),
               CAL_mm        = round(o$CAL[nrow(o)], 2),
               tooth_surv_pct= round(o$TSURV_o[nrow(o)], 1))
  }))
}

## ---------------------------------------------------------------------------
## ANALYSIS 6 — Turn the subversion off
## The single most informative counterfactual in the file: same bacteria, same
## neutrophils, intact killing.
## ---------------------------------------------------------------------------

PDT_subversion_counterfactual <- function(mod = pdt_model(), horizon = 720) {
  arms <- list(
    "Subversion intact (E_SUBVERT = 4.0)"       = list(),
    "Subversion halved (E_SUBVERT = 2.0)"       = list(E_SUBVERT = 2.0),
    "Subversion abolished (E_SUBVERT = 0)"      = list(E_SUBVERT = 0.0),
    "C3 blockade only (AMY-101 continuous)"     = list(),
    "Antibiotics only (no host change)"         = list()
  )
  out <- list()
  for (nm in names(arms)) {
    pt <- PDT_patient(mod, bloss0 = 4.5, param = arms[[nm]])
    e  <- NULL
    if (grepl("AMY", nm))  e <- ev_amy101(times = seq(0, horizon - 7, by = 7))
    if (grepl("Antibio", nm)) e <- ev_amox_metro()
    o <- if (is.null(e)) mrgsim_df(pt, end = horizon, delta = 30)
         else mrgsim_df(pt, events = e, end = horizon, delta = 30)
    out[[nm]] <- data.frame(arm = nm,
                            BIOD_end   = round(o$BIOD[nrow(o)], 3),
                            PG_end     = round(o$PG[nrow(o)], 4),
                            INFLAM_end = round(o$INFLAM_o[nrow(o)], 2),
                            bone_loss  = round(o$BLOSS[nrow(o)] - o$BLOSS[1], 2),
                            killing_capacity = round(o$PKN_o[nrow(o)], 2))
  }
  do.call(rbind, out)
}

## ---------------------------------------------------------------------------
## Demonstration
## ---------------------------------------------------------------------------
if (identical(environment(), globalenv()) && !interactive()) {
  mod <- pdt_model()
  cat("\n== CALIBRATION ==\n");  print(PDT_calibration_report(mod), right = FALSE)
  cat("\n== PPD DECOMPOSITION ==\n"); print(PDT_decompose(mod), right = FALSE)
  cd <- PDT_critical_depth(mod)
  cat("\n== CRITICAL PROBING DEPTH ==\n")
  cat(sprintf("  SRP      : %.2f mm (Lindhe 1982: ~2.9 mm)\n", attr(cd,"critical_PD_SRP")))
  cat(sprintf("  Surgery  : %.2f mm (Lindhe 1982: ~4.2 mm)\n", attr(cd,"critical_PD_SURGERY")))
  cat(sprintf("  Crossover: %.2f mm (surgery overtakes SRP)\n", attr(cd,"SRP_SURG_crossover")))
  cat("\n== SEPARATRIX ==\n"); print(PDT_separatrix(mod))
  cat("\n== SUBVERSION COUNTERFACTUAL ==\n")
  print(PDT_subversion_counterfactual(mod), right = FALSE)
  cat("\n== TIMING ==\n"); print(PDT_timing(mod), right = FALSE)
}
