##  Diabetic Foot Ulcer (DFU) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Diabetic foot ulcer — the convergence of (i) diabetic peripheral
##             neuropathy with loss of protective sensation, (ii) peripheral
##             arterial disease / microvascular dysfunction, and (iii) repetitive
##             plantar pressure on an insensate, deformed foot.  The resulting
##             wound arrests in a protease-dominant, biofilm-colonised,
##             senescent-fibroblast state in which inflammation never resolves,
##             keratinocytes proliferate but do not migrate, and closure — when
##             it happens — is a remission, not a cure.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.5)
##
##  Scope    : 44 ODE compartments —
##               topical/systemic therapy PK (becaplermin gel, TLC-NOSF sucrose
##               octasulfate dressing, esmolol 14% gel, systemic antibiotic with
##               explicit wound- and bone-tissue compartments, cellular tissue
##               product, hyperbaric/topical oxygen, sharp debridement)
##             + slow systemic axes (HbA1c, neuropathy, perfusion)
##             + infection (planktonic bioburden, biofilm, osteomyelitis, exposed
##               bone nidus)
##             + wound inflammation (neutrophils, M1/M2 macrophages, IL-1beta, ROS)
##             + protease/anti-protease balance (MMP-9, TIMP-1)
##             + growth factors & angiogenesis (PDGF-BB, VEGF, SDF-1alpha, EPC,
##               granulation vascular density)
##             + repair tissue (fibroblasts, senescent fibroblasts, collagen,
##               granulation fill, keratinocyte migratory competence)
##             + wound geometry (AREA, DEPTH) and outcomes (scar maturation,
##               re-ulceration hazard, amputation hazard, ulcer-free days,
##               antibiotic-days, treatment-burden index).
##  Time     : days.  Default horizon 540 d (12-week closure window + 12 months
##             of post-closure remission follow-up); 1825 d for the slow axes.
##  Units    : AREA cm^2, DEPTH mm, wound pO2 mmHg, BACT log10 CFU/g, HbA1c %,
##             cytokine/protease/growth-factor states in normalised wound units
##             (1.0 = the level of a typical stalled chronic DFU at presentation),
##             topical/systemic drug states in dose-proportional units (au).
##
##  ---------------------------------------------------------------------------
##  SIX STRUCTURAL COMMITMENTS (what makes this model say something)
##  ---------------------------------------------------------------------------
##  1. CLOSURE IS A PERIMETER PROCESS, NOT AN AREA PROCESS.
##       dA/dt = -k(t) * P,  P = 2*sqrt(pi*A)   <=>   dr/dt = -k(t)
##     All biology enters through the linear edge-advance rate k (cm/day); the
##     geometry is exactly a shrinking radius.  Consequence: time-to-heal is
##     r0/k, so a 16-fold range of wound AREA is only a 4-fold range of healing
##     TIME, and the 4-week percent-area-reduction rule (Sheehan) has a
##     closed-form, size-free reading  t_heal = 28/(1 - sqrt(1 - PAR4)).
##
##  2. OFFLOADING IS DEVICE EFFICACY x ADHERENCE.
##     A removable cast walker is not a worse device than a total contact cast —
##     it is a slightly BETTER device (87% vs 85% peak-pressure reduction) that
##     is worn during only ~28% of daily activity (Armstrong 2003).  The model
##     encodes adherence separately, so the entire TCC-vs-walker healing gap is
##     recovered as an adherence effect and vanishes when adherence is set to 1.
##
##  3. TOPICAL GROWTH FACTOR IS A RACE AGAINST PROTEASE.
##     Becaplermin is cleared from the wound at (KOUT_BEC + KDEG_BEC_PROT*PROT)
##     where PROT = MMP-9/TIMP-1.  In a protease-dominant wound most of the
##     applied rhPDGF-BB is destroyed before it signals.
##
##  4. OXYGEN GATES EVERY ANABOLIC TERM.
##     One Hill gate OG = pO2^3/(pO2^3 + PO2_50^3) multiplies collagen synthesis
##     (prolyl hydroxylase is O2-dependent), angiogenesis, the M1->M2 switch, the
##     neutrophil oxidative burst and the epithelial edge.  Below the gate no
##     biologic can work.  Separately, methylglyoxal blocks HIF-1alpha
##     transactivation, so the hypoxic diabetic wound cannot even mount the
##     hypoxia response it is entitled to.
##
##  5. HbA1c IS A SLOW-AXIS DRUG.
##     Neuropathy relaxes with a ~4.6-year time constant.  Intensive glycaemic
##     control therefore does very little for the ulcer in front of you and a
##     great deal for the one three years from now — which is why HbA1c is a weak
##     predictor of index-ulcer healing and a strong predictor of incidence.
##
##  6. CLOSURE IS REMISSION, NOT CURE.
##     Healing resets AREA and leaves NEURO, plantar pressure and deformity
##     untouched, and leaves behind scar at ~80% of normal tensile strength.  The
##     post-closure re-ulceration hazard is driven by that unchanged substrate.
##
##  ---------------------------------------------------------------------------
##  CALIBRATION ANCHORS  (see dfu_references.md; model values from the
##  dependency-free reference implementation dfu_reference_implementation.py)
##  ---------------------------------------------------------------------------
##    Armstrong 2001 Diabetes Care 24:1019 — mean days to healing, A0 = 1.4 cm2
##        TCC        obs 33.5 d   model 36.3 d
##        RCW        obs 50.4 d   model 59.6 d
##        half-shoe  obs 61.0 d   model 64.4 d
##    Armstrong 2003 Diabetes Care 26:2595 — RCW worn during 28% of daily
##        activity; encoded directly as ADHERENCE = 0.28.
##    Sheehan 2003 Diabetes Care 26:1879 — PAR4 > 50% predicts 12-week closure.
##    Armstrong 2017 NEJM 376:2367 — ~40% recurrence at 1 year (model 41.8%);
##        ~60% at 3 years (model 79.4% — see LIMITATIONS).
##    Wieman 1998 Diabetes Care 21:822 — becaplermin 50% vs 35% closure at 20 wk
##        (model: 7% faster healing rate).
##    Edmonds 2018 Lancet Diabetes Endocrinol 6:186 (Explorer) — TLC-NOSF 48% vs
##        30% closure at 20 wk (model: 17% faster).
##    Lipsky 2012 Clin Infect Dis 54:e132 / IWGDF 2023 — infection & osteomyelitis
##        management; biofilm antibiotic tolerance 100-1000x planktonic MIC.
##
##  LIMITATIONS
##    * Deterministic single-patient trajectories.  "89.5% healed at 12 weeks"
##      style trial endpoints are represented as time-to-closure, not as a
##      population proportion.
##    * The post-closure re-ulceration hazard is constant in time-since-closure.
##      That reproduces the 1-year figure (41.8% vs ~40% observed) but
##      over-predicts 3-year recurrence (79.4% vs ~60%): in reality the hazard
##      declines as the highest-risk patients recur early and the scar matures.
##    * Drug amounts are dose-proportional surrogate units, not mg; the PK is
##      structurally correct (depot -> wound tissue -> bone) but not fitted to
##      measured tissue concentrations.
##    * BEXP (exposed bone) and AUCEDGE are bookkeeping states, not physiology.
##    * The Python reference implements the same 44 states; the declaration order
##      differs between the two files for readability. The equations do not.
##
##  Disclaimer: research / education / hypothesis generation only.  Not a
##              substitute for clinical judgment and not a regulatory artefact.
##  ============================================================================

[PROB]
QSP model of the diabetic foot ulcer: neuropathy + ischaemia + repetitive
plantar pressure drive ulceration; the wound then arrests in a protease-
dominant, biofilm-colonised, senescent state.  Closure is modelled as a
perimeter process (dA/dt = -k*P), offloading as device efficacy x adherence,
topical growth factor as a race against MMP-9, and every anabolic term is
gated by wound pO2.  Post-closure the model carries a re-ulceration hazard
driven by the unchanged neuropathic/biomechanical substrate.

[PLUGIN] Rcpp

[GLOBAL]
#define HILL(x, ec50, h)  (pow(fmax(x,0.0), h) / (pow(fmax(x,0.0), h) + pow(ec50, h)))
#define INHIB(x, ic50, h) (1.0 / (1.0 + pow(fmax(x,0.0)/(ic50), h)))
#define SWON(t, t0)       (1.0 / (1.0 + exp(-fmin(fmax(((t) - (t0)) / 0.5, -35.0), 35.0))))
#define SWONW(x, x0, w)   (1.0 / (1.0 + exp(-fmin(fmax(((x) - (x0)) / (w), -35.0), 35.0))))
#define WINDOW(t, a, b)   (SWON(t,a) * (1.0 - SWON(t,b)))

[PARAM] @annotated
//=========================== patient / systemic =============================
HBA1C0       :  9.0   : %, HbA1c at presentation
HBA1C_TGT    :  9.0   : %, HbA1c target achieved by glucose-lowering therapy
TAU_A1C      : 45     : day, time constant of the HbA1c response
HB_GDL       : 12.5   : g/dL, haemoglobin (O2-carrying capacity)
KP_NEURO     : 5.0e-4 : 1/(day*%A1C), glycaemic drive of neuropathy progression
KR_NEURO     : 3.5e-4 : 1/day, intrinsic neuropathy repair (tau ~ 7.8 y)

//=========================== perfusion / oxygen =============================
PERF0        : 0.85   : 0-1, effective wound perfusion at presentation
PERF_TGT     : 0.85   : 0-1, perfusion set-point without revascularisation
TAU_PERF     : 7      : day, perfusion response time constant
T_REVASC     : 1e6    : day, time of endovascular / bypass revascularisation
REVASC_GAIN  : 0.0    : 0-1, perfusion gained by revascularisation
K_RESTEN     : 1.5e-3 : 1/day, restenosis / graft-failure decay of that gain
TCPO2_MAX    : 62     : mmHg, wound pO2 at full perfusion and full vascularity
PO2_50       : 26     : mmHg, half-maximal pO2 for the anabolic gate
HILL_O2      : 3      : -, Hill coefficient of the oxygen gate
PO2_HIF      : 30     : mmHg, pO2 at which the hypoxia signal is half-maximal
OEDEMA_PEN   : 0      : mmHg, interstitial-oedema diffusion penalty

//=========================== mechanics / offloading =========================
DEFORMITY    : 0.45   : 0-1, claw toe / MT-head prominence / Charcot deformity
DEFORM_REF   : 0.45   : 0-1, reference deformity (normalises STRESS to 1.0)
DEV_EFF      : 0.0    : 0-1, peak-pressure reduction of the offloading device
ADHERENCE    : 1.0    : 0-1, fraction of daily activity the device is worn
T_OFF_ON     : 0      : day, offloading start
T_OFF_OFF    : 1e6    : day, offloading stop
FOOTWEAR     : 0      : 0/1, therapeutic footwear after closure
STEPS_REL    : 1.0    : -, daily step count relative to reference
S50_MECH     : 1.00   : -, mechanical stress giving half-maximal edge inhibition
H_MECH       : 2.0    : -, Hill coefficient of the mechanical gate
STRESS_TOL   : 0.55   : -, stress below which no re-injury occurs
K_REINJ      : 0.086  : cm/day, re-injury edge-retreat scalar
AREA_MAXPR   : 10     : cm2, extent of the high-pressure zone (bounds re-injury)

//=========================== epithelial edge / geometry =====================
EDGE_MAX     : 0.158  : cm/day, maximal linear epithelial edge advance
K_CONTR      : 0.010  : 1/day, myofibroblast wound-contraction scalar
C50_CONTR    : 0.60   : -, collagen level for half-maximal contraction
AREA0        : 2.00   : cm2, wound area at presentation
DEPTH0       : 3.0    : mm, wound depth at presentation
AREA_CLOSE   : 0.05   : cm2, area defining complete closure

//=========================== keratinocytes / granulation ====================
KIN_K        : 0.25   : 1/day, keratinocyte migratory-competence acquisition
KOUT_K       : 0.12   : 1/day, loss of migratory competence
IL1_50K      : 1.00   : -, IL-1beta for half-maximal inhibition of migration
PR50_K       : 1.60   : -, MMP9/TIMP1 for half-maximal inhibition of migration
KG_GRAN      : 0.22   : 1/day, granulation-tissue fill rate
KD_GRAN      : 0.030  : 1/day, protease-driven granulation loss
K_FILL       : 0.16   : mm/day, depth filling per unit granulation

//=========================== inflammation ===================================
KIN_NEUT     : 0.50   : 1/day, neutrophil recruitment scalar
KOUT_NEUT    : 0.50   : 1/day, neutrophil clearance
KIN_M1       : 0.40   : 1/day, M1 macrophage recruitment scalar
KOUT_M1      : 0.18   : 1/day, M1 clearance
K_SW         : 0.55   : 1/day, maximal M1 -> M2 conversion rate
IL1_SW       : 0.85   : -, IL-1beta blocking half the M1->M2 switch
KIN_M2       : 0.10   : 1/day, baseline M2 influx
KOUT_M2      : 0.16   : 1/day, M2 clearance
KIN_IL1      : 0.60   : 1/day, IL-1beta production scalar
KOUT_IL1     : 0.55   : 1/day, IL-1beta clearance
IL10_50      : 0.90   : -, M2 (IL-10) level halving IL-1beta production
KIN_ROS      : 0.45   : 1/day, wound ROS production scalar
KOUT_ROS     : 0.60   : 1/day, ROS clearance

//=========================== proteases ======================================
KIN_M9       : 0.55   : 1/day, MMP-9 production scalar
KOUT_M9      : 0.30   : 1/day, MMP-9 clearance
KIN_T1       : 0.22   : 1/day, TIMP-1 production scalar
KOUT_T1      : 0.30   : 1/day, TIMP-1 clearance

//=========================== growth factors / angiogenesis ==================
KIN_PDGF     : 0.14   : 1/day, endogenous PDGF-BB production scalar
KOUT_PDGF    : 0.45   : 1/day, endogenous PDGF-BB clearance
PDGF_50      : 1.10   : -, PDGF-BB for half-maximal fibroblast drive
KIN_VEGF     : 0.40   : 1/day, VEGF-A production scalar
KOUT_VEGF    : 0.40   : 1/day, VEGF-A clearance
KIN_SDF      : 0.35   : 1/day, SDF-1alpha production scalar
KOUT_SDF     : 0.30   : 1/day, SDF-1alpha clearance
K_DPP4       : 0.45   : 1/day, DPP-4 mediated SDF-1alpha inactivation
KM_EPC       : 0.30   : 1/day, EPC homing scalar
KOUT_EPC     : 0.35   : 1/day, EPC loss
KG_VASC      : 0.30   : 1/day, granulation vascular-density growth scalar
KR_VASC      : 0.10   : 1/day, vascular regression
MGO_BLOCK    : 0.085  : 1/%A1C, methylglyoxal block of HIF-1alpha transactivation

//=========================== fibroblasts / ECM ==============================
KP_FIB       : 0.34   : 1/day, fibroblast proliferation scalar
KD_FIB       : 0.10   : 1/day, fibroblast loss
FIB_MAX      : 2.0    : -, fibroblast carrying capacity
K_SEN        : 0.055  : 1/day, senescence conversion scalar (ROS + protease)
KCL_SEN      : 0.030  : 1/day, senescent-cell clearance
KS_COL       : 0.30   : 1/day, collagen synthesis scalar
KDEG_COL     : 0.14   : 1/day, protease-driven collagen degradation

//=========================== infection ======================================
BACT0        : 5.2    : log10 CFU/g, bioburden at presentation
BMAX         : 9.5    : log10 CFU/g, carrying capacity
KG_BACT      : 0.55   : 1/day, bacterial growth scalar
KILL_HOST    : 0.50   : 1/day, host innate killing scalar
EMAX_ABX     : 1.30   : 1/day, maximal antibiotic kill
EC50_ABX     : 0.45   : au, wound antibiotic for half-maximal kill
TOL_BIOF     : 0.92   : -, fraction of antibiotic effect lost in mature biofilm
KG_BIOF      : 1.45   : 1/day, biofilm regrowth (tolerance restored in 2-3 d)
KD_BIOF      : 0.05   : 1/day, spontaneous biofilm loss
K_DEBR_BIOF  : 13.8   : 1/day per au, debridement biofilm removal (~82%/session)
K_RIF        : 0.10   : 1/day, rifampicin anti-biofilm effect
PROBE_BONE   : 0      : 0/1, probe-to-bone positive (bone at risk)
K_ON_OST     : 0.045  : 1/day, bone seeding rate from wound bioburden
K_OFF_OST    : 0.25   : 1/day, maximal antibiotic clearance of bone infection
EC50_ABX_B   : 0.25   : au, bone antibiotic for half-maximal effect
NECRO        : 0.35   : 0-1, necrotic slough burden

//=========================== therapy PK =====================================
R_BEC        : 0      : au/day, becaplermin 0.01% gel application rate
T_BEC_END    : 140    : day, end of becaplermin course (max 20 weeks)
KA_BEC       : 1.20   : 1/day, gel -> wound tissue transfer
KOUT_BEC     : 0.15   : 1/day, protease-independent wound clearance
KDEG_BEC_PROT: 5.00   : 1/day per unit MMP9/TIMP1, PROTEOLYTIC destruction
E_BEC        : 1.80   : -, maximal PDGF-BB equivalent delivered
EC50_BEC     : 0.30   : au, wound becaplermin for half-maximal effect
H_BEC        : 2.0    : -, Hill coefficient
R_NOSF       : 0      : au/day, TLC-NOSF sucrose octasulfate dressing
T_NOSF_END   : 140    : day, end of dressing course
KOUT_NOSF    : 0.90   : 1/day, dressing washout
EMAX_NOSF    : 0.62   : -, maximal suppression of MMP-9 production
EC50_NOSF    : 0.50   : au
R_ESM        : 0      : au/day, esmolol 14% topical gel
T_ESM_END    : 84     : day, end of esmolol course
KA_ESM       : 1.50   : 1/day
KOUT_ESM     : 1.30   : 1/day
E_ESM        : 0.55   : -, maximal boost to keratinocyte migratory drive
EC50_ESM     : 0.40   : au
R_ABX        : 0      : au/day, systemic antibiotic input
T_ABX_END    : 14     : day, end of antibiotic course
KOUT_ABX     : 1.60   : 1/day, central elimination
KTR_ABX_W    : 0.90   : 1/day, central -> wound tissue
KOUT_ABX_W   : 1.10   : 1/day, wound-tissue elimination
F_BONE       : 0.35   : -, bone penetration fraction
KTR_ABX_B    : 0.25   : 1/day, central -> bone
KOUT_ABX_B   : 0.45   : 1/day, bone elimination
RIF_ON       : 0      : 0/1, rifampicin adjunct (bone penetration + anti-biofilm)
R_CTP        : 0      : au/day, cellular / tissue product application
T_CTP_END    : 56     : day, end of CTP course
KOUT_CTP     : 0.085  : 1/day, graft-derived trophic decay
E_CTP        : 0.85   : -, maximal keratinocyte boost from CTP
EC50_CTP     : 0.35   : au
R_OXY        : 0      : au/day, hyperbaric or topical oxygen
T_OXY_END    : 40     : day, end of oxygen course (40 sessions)
KOUT_OXY     : 8.0    : 1/day, washout of the oxygen pulse
E_OXY        : 22     : mmHg, maximal wound pO2 gain during a session
KOUT_DEBR    : 8.0    : 1/day, decay of the debridement action (sharp debridement
//                       is dosed as a bolus into cmt 11, not as a rate parameter)
NPWT         : 0      : 0/1, negative-pressure wound therapy
DPP4I        : 0      : 0/1, DPP-4 inhibitor (protects SDF-1alpha)

//=========================== outcomes =======================================
TAU_SCAR     : 60     : day, scar tensile maturation time constant
SCAR_MAX_TENS: 0.80   : -, scar plateau tensile strength (fraction of normal)
H0_REC       : 2.20e-3: 1/day, reference post-closure re-ulceration hazard
EDU          : 0      : 0/1, structured patient education / self-inspection
TEMPMON      : 0      : 0/1, home skin-temperature monitoring
SURVEIL      : 0      : 0/1, structured podiatric surveillance
A0_AMP       : 1.10e-3: 1/day, reference amputation hazard
W_TOX_ABX    : 1.0    : -, treatment-burden weight, antibiotic
W_TOX_HBOT   : 0.6    : -, treatment-burden weight, hyperbaric oxygen
W_TOX_BEC    : 0.8    : -, treatment-burden weight, becaplermin (boxed warning)
W_TOX_TCC    : 0.5    : -, treatment-burden weight, cast immobilisation

[CMT] @annotated
BEC_D   :  1 au   becaplermin gel skin depot
BEC_W   :  2 au   becaplermin (rhPDGF-BB) in wound tissue
NOSF    :  3 au   sucrose octasulfate (TLC-NOSF) on the wound
ESM_D   :  4 au   esmolol gel depot
ESM_W   :  5 au   esmolol in wound tissue
ABX_C   :  6 au   systemic antibiotic, central
ABX_W   :  7 au   antibiotic, wound tissue
ABX_B   :  8 au   antibiotic, bone
CTP     :  9 au   cellular/tissue-product trophic activity
OXY     : 10 au   hyperbaric / topical oxygen exposure
DEBR    : 11 au   sharp-debridement action (bolus-driven, fast decay)
HBA1C   : 12 %    HbA1c
NEURO   : 13 0-1  neuropathy severity (1 = complete loss of protective sensation)
PERF    : 14 0-1  effective wound perfusion
BACT    : 15 log  planktonic bioburden, log10 CFU/g
BIOF    : 16 0-1  biofilm biomass
OSTEO   : 17 0-1  osteomyelitis burden
BEXP    : 18 0-1  exposed / at-risk bone (the nidus; removed by resection)
NEUT    : 19 -    wound neutrophils
M1      : 20 -    M1 pro-inflammatory macrophages
M2      : 21 -    M2 reparative macrophages
IL1B    : 22 -    IL-1beta
ROS     : 23 -    wound reactive oxygen species
MMP9    : 24 -    MMP-9
TIMP1   : 25 -    TIMP-1
PDGF    : 26 -    endogenous PDGF-BB
VEGF    : 27 -    VEGF-A
SDF1    : 28 -    SDF-1alpha / CXCL12
EPC     : 29 -    endothelial progenitor / angiogenic drive
VASC    : 30 0-1  granulation-tissue vascular density
FIB     : 31 -    active dermal fibroblasts
SEN     : 32 -    senescent fibroblasts
COL     : 33 -    collagen / ECM in granulation tissue
GRAN    : 34 0-1  granulation fill fraction
KERA    : 35 0-1  keratinocyte migratory competence
AREA    : 36 cm2  WOUND AREA
DEPTH   : 37 mm   wound depth
SCAR    : 38 0-1  scar maturation after closure
HAZREC  : 39 -    cumulative re-ulceration hazard
HAZAMP  : 40 -    cumulative amputation hazard
UFD     : 41 day  ulcer-free days
ABXD    : 42 day  antibiotic-exposure days
TOXIDX  : 43 -    cumulative treatment-burden index
AUCEDGE : 44 cm   cumulative epithelial edge advance

[MAIN]
BEC_D_0  = 0;   BEC_W_0 = 0;   NOSF_0 = 0;   ESM_D_0 = 0;   ESM_W_0 = 0;
ABX_C_0  = 0;   ABX_W_0 = 0;   ABX_B_0 = 0;  CTP_0   = 0;   OXY_0   = 0;
DEBR_0   = 0;

HBA1C_0  = HBA1C0;
// neuropathy starts at the steady state implied by the presenting HbA1c
NEURO_0  = KP_NEURO * fmax(HBA1C0 - 6.5, 0.0)
           / (KP_NEURO * fmax(HBA1C0 - 6.5, 0.0) + KR_NEURO);
PERF_0   = PERF0;

BACT_0   = BACT0;
BIOF_0   = 0.72;                 // biofilm is present in >=60% of chronic wounds
OSTEO_0  = 0.55 * PROBE_BONE;
BEXP_0   = PROBE_BONE;

NEUT_0   = 0.75;  M1_0    = 0.90;  M2_0   = 0.30;  IL1B_0 = 1.05;  ROS_0 = 0.95;
MMP9_0   = 1.30;  TIMP1_0 = 0.55;
PDGF_0   = 0.30;  VEGF_0  = 0.35;  SDF1_0 = 0.25;  EPC_0  = 0.18;  VASC_0 = 0.28;
FIB_0    = 0.55;  SEN_0   = 0.45;  COL_0  = 0.40;  GRAN_0 = 0.35;  KERA_0 = 0.35;

AREA_0   = AREA0;
DEPTH_0  = DEPTH0;
SCAR_0   = 0;
HAZREC_0 = 0;  HAZAMP_0 = 0;  UFD_0 = 0;  ABXD_0 = 0;  TOXIDX_0 = 0;
AUCEDGE_0 = 0;

[ODE]
//===========================================================================
// 0. Shared algebra
//===========================================================================
double A     = fmax(AREA, 0.0);
double PERIM = 2.0 * sqrt(M_PI * fmax(A, 1e-9));
double healed = 1.0 - SWONW(A, AREA_CLOSE, 0.02);  // ~1 once AREA < AREA_CLOSE
double open_w = 1.0 - healed;

double hyperg = fmax(HBA1C - 6.0, 0.0);
double PROT   = MMP9 / (TIMP1 + 0.05);             // MMP-9 / TIMP-1 ratio
double PROTn  = PROT / (PROT + 1.5);

// --- offloading: efficacy x adherence -------------------------------------
double on_off  = WINDOW(SOLVERTIME, T_OFF_ON, T_OFF_OFF);
double offload = DEV_EFF * ADHERENCE * on_off;
double ppp_idx = (1.0 + 0.60 * (DEFORMITY - DEFORM_REF)) * STEPS_REL;
double STRESS  = ppp_idx * (1.0 - offload);
double MG      = INHIB(STRESS, S50_MECH, H_MECH);
double over    = fmax(STRESS - STRESS_TOL, 0.0);
// re-injury is a MARGIN process too: proportional to perimeter, bounded by the
// anatomical extent of the high-pressure zone
double REINJ = K_REINJ * over * over * PERIM
               * fmax(1.0 - A / AREA_MAXPR, 0.0) * open_w;

// --- perfusion, oxygen and the HIF competence defect ----------------------
double rev      = SWON(SOLVERTIME, T_REVASC);
double resten   = exp(-K_RESTEN * fmax(SOLVERTIME - T_REVASC, 0.0));
double perf_tgt = fmin(PERF_TGT + REVASC_GAIN * rev * resten, 1.0);

double hb_f = fmin(HB_GDL / 13.0, 1.0);
double WPO2 = fmax(TCPO2_MAX * PERF * (0.45 + 0.55 * VASC) * hb_f
                   - OEDEMA_PEN * (1.0 - 0.5 * NPWT)
                   + E_OXY * HILL(OXY, 0.5, 1.0), 1.0);
double OG   = HILL(WPO2, PO2_50, HILL_O2);         // THE anabolic oxygen gate

double hypoxia  = INHIB(WPO2, PO2_HIF, 2.0);
double hif_comp = fmax(1.0 - MGO_BLOCK * hyperg, 0.05);
double HIFdrive = hypoxia * hif_comp;              // hypoxia present, response absent

//===========================================================================
// 1. Therapy PK — every course is finite
//===========================================================================
double on_bec  = WINDOW(SOLVERTIME, 0.0, T_BEC_END);
double on_nosf = WINDOW(SOLVERTIME, 0.0, T_NOSF_END);
double on_esm  = WINDOW(SOLVERTIME, 0.0, T_ESM_END);
double on_abx  = WINDOW(SOLVERTIME, 0.0, T_ABX_END);
double on_ctp  = WINDOW(SOLVERTIME, 0.0, T_CTP_END);
double on_oxy  = WINDOW(SOLVERTIME, 0.0, T_OXY_END);

dxdt_BEC_D = R_BEC * on_bec * open_w - KA_BEC * BEC_D;
dxdt_BEC_W = KA_BEC * BEC_D - (KOUT_BEC + KDEG_BEC_PROT * PROT) * BEC_W;
dxdt_NOSF  = R_NOSF * on_nosf * open_w - KOUT_NOSF * NOSF;
dxdt_ESM_D = R_ESM * on_esm * open_w - KA_ESM * ESM_D;
dxdt_ESM_W = KA_ESM * ESM_D - KOUT_ESM * ESM_W;
dxdt_ABX_C = R_ABX * on_abx - (KOUT_ABX + KTR_ABX_W + KTR_ABX_B) * ABX_C;
dxdt_ABX_W = KTR_ABX_W * ABX_C - KOUT_ABX_W * ABX_W;
dxdt_ABX_B = KTR_ABX_B * F_BONE * ABX_C * (1.0 + 1.8 * RIF_ON) - KOUT_ABX_B * ABX_B;
dxdt_CTP   = R_CTP * on_ctp * open_w - KOUT_CTP * CTP;
dxdt_OXY   = R_OXY * on_oxy - KOUT_OXY * OXY;
dxdt_DEBR  = -KOUT_DEBR * DEBR;                    // driven by bolus doses

//===========================================================================
// 2. Slow systemic axes
//===========================================================================
dxdt_HBA1C = (HBA1C_TGT - HBA1C) / TAU_A1C;
dxdt_NEURO = KP_NEURO * fmax(HBA1C - 6.5, 0.0) * (1.0 - NEURO) - KR_NEURO * NEURO;
dxdt_PERF  = (perf_tgt - PERF) / TAU_PERF;

//===========================================================================
// 3. Infection: bioburden, biofilm, bone
//===========================================================================
double bf = fmin(fmax((BACT - 3.0) / 6.0, 0.0), 1.0);
double hostdef = (0.30 + 0.70 * OG)
                 * (1.0 - 0.35 * fmin(hyperg / 4.0, 1.0))
                 * (1.0 - 0.85 * BIOF);
double abx_kill = EMAX_ABX * HILL(ABX_W, EC50_ABX, 1.0) * (1.0 - TOL_BIOF * BIOF);

dxdt_BACT = KG_BACT * (BMAX - BACT) / BMAX * (0.55 + 0.45 * NECRO) * open_w
            - KILL_HOST * hostdef * bf
            - abx_kill
            - 0.55 * DEBR
            - 1.2 * healed * fmax(BACT - 3.0, 0.0) / 6.0;

dxdt_BIOF = KG_BIOF * bf * (1.0 - BIOF)
            - KD_BIOF * BIOF
            - K_DEBR_BIOF * DEBR * BIOF
            - K_RIF * RIF_ON * BIOF;

dxdt_BEXP  = -0.0015 * BEXP;                       // resection is an event on BEXP
dxdt_OSTEO = K_ON_OST * bf * BEXP * (1.0 - OSTEO)
             - K_OFF_OST * HILL(ABX_B, EC50_ABX_B, 1.0) * (1.0 - 0.70 * BIOF) * OSTEO
             - 0.002 * OSTEO;

//===========================================================================
// 4. Chronic inflammation and the failed M1 -> M2 switch
//===========================================================================
double damage = 0.45 * over + 0.30 * OSTEO;
dxdt_NEUT = KIN_NEUT * (0.15 + 1.20 * bf + damage) * open_w - KOUT_NEUT * NEUT;

double swch = INHIB(IL1B, IL1_SW, 3.0)
              * (0.40 + 0.60 * OG)
              * (1.0 - 0.30 * fmin(hyperg / 4.0, 1.0));
dxdt_M1 = KIN_M1 * (0.20 + 0.80 * bf + 0.60 * NEUT + 0.50 * SEN) * open_w
          - (KOUT_M1 + K_SW * swch) * M1;
dxdt_M2 = K_SW * swch * M1 + KIN_M2 * open_w
          + 0.30 * HILL(CTP, EC50_CTP, 1.0) - KOUT_M2 * M2;
dxdt_IL1B = KIN_IL1 * (0.30 * bf + 0.70 * M1 + 0.40 * ROS)
            * INHIB(M2, IL10_50, 1.0) * open_w - KOUT_IL1 * IL1B;
dxdt_ROS = KIN_ROS * (NEUT + 0.50 * M1 + 0.25 * fmin(hyperg / 3.0, 1.0)) * open_w
           - KOUT_ROS * ROS;

//===========================================================================
// 5. Protease / anti-protease balance
//===========================================================================
double enosf = EMAX_NOSF * HILL(NOSF, EC50_NOSF, 1.0);
dxdt_MMP9  = KIN_M9 * (0.60 * NEUT + 0.50 * M1 + 0.30 * SEN + 0.30 * IL1B)
             * (1.0 - enosf) * open_w - KOUT_M9 * MMP9;
dxdt_TIMP1 = KIN_T1 * (0.30 + 0.80 * M2) * open_w - KOUT_T1 * TIMP1;

//===========================================================================
// 6. Growth factors and angiogenesis
//===========================================================================
double PDGF_tot = PDGF + E_BEC * HILL(BEC_W, EC50_BEC, H_BEC);
dxdt_PDGF = KIN_PDGF * (0.40 + 0.60 * M2) * open_w
            + 0.35 * HILL(CTP, EC50_CTP, 1.0)
            - (KOUT_PDGF + 0.45 * PROT) * PDGF;
dxdt_VEGF = KIN_VEGF * (HIFdrive + 0.50 * M2) * open_w
            + 0.30 * HILL(CTP, EC50_CTP, 1.0) - KOUT_VEGF * VEGF;
dxdt_SDF1 = KIN_SDF * HIFdrive * open_w
            - (KOUT_SDF + K_DPP4 * (1.0 - 0.75 * DPP4I)) * SDF1;
double mobfail = 0.55 * fmin(hyperg / 4.0, 1.0);   // diabetic stem-cell mobilopathy
dxdt_EPC  = KM_EPC * SDF1 * (1.0 - mobfail) - KOUT_EPC * EPC;
dxdt_VASC = KG_VASC * VEGF * (0.35 + 0.65 * EPC) * OG * (1.0 - VASC)
            - KR_VASC * VASC * (1.0 + 0.50 * PROTn);

//===========================================================================
// 7. Fibroblasts, senescence, ECM, granulation
//===========================================================================
dxdt_FIB = KP_FIB * HILL(PDGF_tot, PDGF_50, 1.0) * OG
           * (1.0 - FIB / FIB_MAX) * open_w
           - K_SEN * (ROS + 0.40 * PROTn) * FIB - KD_FIB * FIB;
dxdt_SEN = K_SEN * (ROS + 0.40 * PROTn) * FIB - KCL_SEN * SEN - 1.6 * DEBR * SEN;
dxdt_COL = KS_COL * FIB * OG * open_w - KDEG_COL * PROTn * COL;
dxdt_GRAN = KG_GRAN * HILL(COL, 0.70, 1.0) * (0.30 + 0.70 * VASC) * OG
            * (1.0 + 0.35 * NPWT) * (1.0 - GRAN)
            - KD_GRAN * PROTn * GRAN - 0.25 * DEBR * GRAN;

//===========================================================================
// 8. Keratinocytes and the epithelial edge  (the perimeter law)
//===========================================================================
double kdrive = INHIB(IL1B, IL1_50K, 2.0)
                * INHIB(PROT, PR50_K, 1.0)
                * (0.60 + 0.40 * OG)
                * (1.0 + E_ESM * HILL(ESM_W, EC50_ESM, 1.0))
                * (1.0 + E_CTP * HILL(CTP, EC50_CTP, 1.0))
                * (1.0 - 0.10 * fmin(hyperg / 4.0, 1.0));
dxdt_KERA = KIN_K * kdrive * (1.0 - KERA) - KOUT_K * KERA
            + 0.40 * DEBR * (1.0 - KERA);          // de-epibolisation

double EDGE = EDGE_MAX * MG * OG * KERA * GRAN * (1.0 - 0.55 * bf)
              * (1.0 + 0.25 * HILL(PDGF_tot, PDGF_50, 1.0));
double CONTR = K_CONTR * HILL(COL, C50_CONTR, 1.0) * A;

dxdt_AREA  = (-EDGE * PERIM - CONTR + REINJ) * open_w;
dxdt_DEPTH = (-K_FILL * GRAN + 0.06 * OSTEO + 0.04 * bf * (1.0 - GRAN))
             * open_w * (DEPTH > 0.05 ? 1.0 : 0.0);

//===========================================================================
// 9. Outcomes — closure is remission, not cure
//===========================================================================
dxdt_SCAR = healed * (1.0 - SCAR) / TAU_SCAR - open_w * 0.10 * SCAR;

double stress_post = ppp_idx * (1.0 - 0.30 * FOOTWEAR);
double tens = SCAR_MAX_TENS * SCAR;
double haz  = H0_REC * (0.30 + 0.70 * NEURO)
              * pow(stress_post / 0.90, 1.5)
              * (1.0 - 0.55 * tens)
              * (1.0 - 0.10 * EDU) * (1.0 - 0.28 * TEMPMON) * (1.0 - 0.12 * SURVEIL);
dxdt_HAZREC = healed * haz;
dxdt_HAZAMP = A0_AMP * (2.0 * pow(OSTEO, 1.5)
                        + 1.2 * pow(1.0 - PERF, 2.0)
                        + 0.9 * fmax(bf - 0.6, 0.0) * 2.5) * open_w;
dxdt_UFD  = healed;
dxdt_ABXD = (R_ABX > 0 ? on_abx : 0.0);
dxdt_TOXIDX = (W_TOX_ABX  * on_abx  * (R_ABX > 0 ? 1.0 : 0.0)
             + W_TOX_HBOT * on_oxy  * (R_OXY > 0 ? 1.0 : 0.0)
             + W_TOX_BEC  * on_bec  * (R_BEC > 0 ? 1.0 : 0.0)
             + W_TOX_TCC  * DEV_EFF * on_off) / 100.0;
dxdt_AUCEDGE = EDGE;

[TABLE]
double A_now  = fmax(AREA, 0.0);
double PERIM_o = 2.0 * sqrt(M_PI * fmax(A_now, 1e-9));
double RADIUS = sqrt(fmax(A_now, 0.0) / M_PI);
double PROT_o = MMP9 / (TIMP1 + 0.05);
double hb_o   = fmin(HB_GDL / 13.0, 1.0);
double TCPO2  = fmax(TCPO2_MAX * PERF * (0.45 + 0.55 * VASC) * hb_o
                     - OEDEMA_PEN * (1.0 - 0.5 * NPWT)
                     + E_OXY * HILL(OXY, 0.5, 1.0), 1.0);
double OG_o   = HILL(TCPO2, PO2_50, HILL_O2);
double off_o  = DEV_EFF * ADHERENCE * WINDOW(SOLVERTIME, T_OFF_ON, T_OFF_OFF);
double ppp_o  = (1.0 + 0.60 * (DEFORMITY - DEFORM_REF)) * STEPS_REL;
double STRESS_o = ppp_o * (1.0 - off_o);
double PAR    = 100.0 * (1.0 - A_now / AREA0);            // percent area reduction
double CLOSED = (A_now <= AREA_CLOSE) ? 1.0 : 0.0;
double P_REC  = 100.0 * (1.0 - exp(-HAZREC));             // % re-ulcerated
double P_AMP  = 100.0 * (1.0 - exp(-HAZAMP));             // % amputation
double BIOF_TOL = 100.0 * (1.0 - TOL_BIOF * BIOF);        // % of antibiotic effect left
double PDGF_TOT_o = PDGF + E_BEC * HILL(BEC_W, EC50_BEC, H_BEC);
double WAGNERISH = (DEPTH > 4.0 ? 3.0 : (DEPTH > 2.0 ? 2.0 : (A_now > 0.05 ? 1.0 : 0.0)))
                   + (OSTEO > 0.3 ? 1.0 : 0.0);

[CAPTURE] @annotated
PERIM_o   : cm    wound perimeter (2*sqrt(pi*A)) — the closure lever arm
RADIUS    : cm    equivalent wound radius (falls linearly under the perimeter law)
TCPO2     : mmHg  wound tissue oxygen tension
OG_o      : -     anabolic oxygen gate (0-1)
STRESS_o  : -     effective mechanical stress after offloading x adherence
PROT_o    : -     MMP-9 / TIMP-1 ratio
PDGF_TOT_o: -     total PDGF-BB drive (endogenous + surviving becaplermin)
PAR       : %     percent area reduction from baseline (PAR4 at t = 28 d)
CLOSED    : 0/1   complete closure indicator
P_REC     : %     cumulative re-ulceration probability
P_AMP     : %     cumulative amputation probability
BIOF_TOL  : %     fraction of antibiotic effect surviving biofilm tolerance
WAGNERISH : -     Wagner-like composite grade (illustrative)

##  ============================================================================
##  R DRIVER
##  ============================================================================
##  library(mrgsolve); library(dplyr); library(ggplot2)
##  mod <- mread("dfu_mrgsolve_model.R")
##
##  ---------------------------------------------------------------------------
##  Dosing helpers.  Everything that happens repeatedly (daily gel, q8h
##  antibiotic, scheduled debridement, HBOT sessions) is a zero-order input via
##  the R_* rate parameters, EXCEPT sharp debridement, which is a genuine
##  discrete event and is dosed as a bolus into the DEBR compartment (cmt 11).
##  ---------------------------------------------------------------------------
##
##  debride <- function(period = 14, until = 140, amt = 1)
##    ev(time = seq(0, until, by = period), amt = amt, cmt = 11)
##
##  resect <- function(day = 7)          # surgical bone resection
##    ev(time = day, amt = 0, cmt = 1)   # see note below
##
##  NOTE ON RESECTION.  Surgical removal of the infected bone is a multiplicative
##  reset of two states (OSTEO and BEXP), which mrgsolve expresses most cleanly
##  as a $PREAMBLE-free two-step simulation: run to the resection day, scale the
##  two states, and continue.  The reference implementation does exactly this:
##
##    sim_resection <- function(mod, day = 7, frac = 0.85, end = 540) {
##      a <- mod %>% mrgsim(end = day, delta = 0.25)
##      last <- tail(as.data.frame(a), 1)
##      init2 <- c(OSTEO = last$OSTEO * (1 - frac),
##                 BEXP  = last$BEXP  * (1 - frac),
##                 BACT  = max(last$BACT - 1.5, 3))
##      b <- mod %>% init(init2) %>% mrgsim(start = day, end = end, delta = 0.25)
##      dplyr::bind_rows(as.data.frame(a), as.data.frame(b))
##    }
##
##  ---------------------------------------------------------------------------
##  DFU_simulate_scenarios() — 23 prebuilt scenarios
##  ---------------------------------------------------------------------------
##  DFU_scenarios <- list(
##
##    ## ---- offloading: the largest single effect, and it is behavioural -----
##    "S01 no offloading" =
##      list(par = list(DEV_EFF = 0.00, ADHERENCE = 1.00), ev = debride(14)),
##    "S02 standard care (RCW, 28% adherence)" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28), ev = debride(14)),
##    "S03 total contact cast (irremovable)" =
##      list(par = list(DEV_EFF = 0.85, ADHERENCE = 1.00), ev = debride(14)),
##    "S04 SAME removable walker at 100% wear" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 1.00), ev = debride(14)),
##    "S05 half-shoe" =
##      list(par = list(DEV_EFF = 0.40, ADHERENCE = 0.55), ev = debride(14)),
##
##    ## ---- debridement frequency --------------------------------------------
##    "S06 TCC + weekly debridement" =
##      list(par = list(DEV_EFF = 0.85, ADHERENCE = 1.00), ev = debride(7)),
##    "S07 TCC + debridement q4wk" =
##      list(par = list(DEV_EFF = 0.85, ADHERENCE = 1.00), ev = debride(28)),
##
##    ## ---- topical pharmacology ---------------------------------------------
##    "S08 + becaplermin gel" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_BEC = 1.0), ev = debride(14)),
##    "S09 + TLC-NOSF dressing" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_NOSF = 1.0), ev = debride(14)),
##    "S10 + becaplermin + TLC-NOSF" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_BEC = 1.0, R_NOSF = 1.0),
##           ev = debride(14)),
##    "S11 + esmolol 14% gel" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_ESM = 1.0), ev = debride(14)),
##
##    ## ---- perfusion gates everything ---------------------------------------
##    "S12 ischaemic wound + becaplermin" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, PERF0 = 0.32,
##                      PERF_TGT = 0.32, R_BEC = 1.0), ev = debride(14)),
##    "S13 revascularise d14, then becaplermin" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, PERF0 = 0.32,
##                      PERF_TGT = 0.32, T_REVASC = 14, REVASC_GAIN = 0.45,
##                      R_BEC = 1.0), ev = debride(14)),
##
##    ## ---- infection and biofilm --------------------------------------------
##    "S14 infected, 14-d antibiotic, no debridement" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, BACT0 = 7.4,
##                      R_ABX = 1.0, T_ABX_END = 14), ev = NULL),
##    "S15 infected, 14-d antibiotic + weekly debridement" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, BACT0 = 7.4,
##                      R_ABX = 1.0, T_ABX_END = 14), ev = debride(7)),
##    "S16 osteomyelitis, 6-week antibiotic only" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, BACT0 = 7.4,
##                      PROBE_BONE = 1, R_ABX = 1.0, T_ABX_END = 42), ev = debride(14)),
##    "S17 osteomyelitis, resection d7 + 3-week antibiotic" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, BACT0 = 7.4,
##                      PROBE_BONE = 1, R_ABX = 1.0, T_ABX_END = 21),
##           ev = debride(14), resect = 7),
##
##    ## ---- adjuncts ----------------------------------------------------------
##    "S18 + HBOT (40 sessions)" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_OXY = 1.0), ev = debride(14)),
##    "S19 + cellular tissue product" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, R_CTP = 1.0), ev = debride(14)),
##    "S20 + NPWT" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, NPWT = 1), ev = debride(14)),
##
##    ## ---- the slow axis and the aftercare -----------------------------------
##    "S21 intensive glycaemic control (A1c 9 -> 7)" =
##      list(par = list(DEV_EFF = 0.87, ADHERENCE = 0.28, HBA1C_TGT = 7.0),
##           ev = debride(14)),
##    "S22 optimal bundle" =
##      list(par = list(DEV_EFF = 0.85, ADHERENCE = 1.00, R_BEC = 1.0, R_NOSF = 1.0),
##           ev = debride(7)),
##    "S23 optimal bundle + remission care" =
##      list(par = list(DEV_EFF = 0.85, ADHERENCE = 1.00, R_BEC = 1.0, R_NOSF = 1.0,
##                      FOOTWEAR = 1, TEMPMON = 1, EDU = 1, SURVEIL = 1,
##                      HBA1C_TGT = 7.0),
##           ev = debride(7))
##  )
##
##  DFU_simulate_scenarios <- function(mod, end = 540, delta = 0.25) {
##    purrr::imap_dfr(DFU_scenarios, function(s, nm) {
##      m <- mod %>% param(s$par)
##      out <- if (is.null(s$ev)) mrgsim(m, end = end, delta = delta)
##             else               mrgsim(m, events = s$ev, end = end, delta = delta)
##      as.data.frame(out) %>% dplyr::mutate(scenario = nm)
##    })
##  }
##
##  ---------------------------------------------------------------------------
##  Endpoint extraction
##  ---------------------------------------------------------------------------
##  DFU_endpoints <- function(sim, area0 = 2.0, close = 0.05) {
##    sim %>% dplyr::group_by(scenario) %>% dplyr::summarise(
##      PAR4       = 100 * (1 - AREA[which.min(abs(time - 28))] / area0),
##      A_12wk     = AREA[which.min(abs(time - 84))],
##      t_close    = ifelse(any(AREA <= close), time[which.max(AREA <= close)], NA_real_),
##      closed_12w = any(AREA[time <= 84] <= close),
##      ## Sheehan's rule read through the perimeter law: given PAR4 alone,
##      ## t_heal = 28 / (1 - sqrt(1 - PAR4)) — independent of wound size.
##      t_pred_PAR4 = 28 / (1 - sqrt(pmax(1 - PAR4/100, 0))),
##      rec_12mo   = 100 * (1 - exp(-(P_REC[which.min(abs(time - (t_close + 365)))] -
##                                    P_REC[which.min(abs(time - t_close))]) / 100)),
##      amp_1yr    = P_AMP[which.min(abs(time - 365))],
##      abx_days   = max(ABXD),
##      burden     = max(TOXIDX),
##      .groups = "drop")
##  }
##
##  ---------------------------------------------------------------------------
##  Verification against the reference implementation
##  ---------------------------------------------------------------------------
##  Every number in README.md is produced by
##      python3 dfu_reference_implementation.py
##  which integrates this identical 44-state system with fixed-step RK4 and no
##  third-party packages.  Use it to check any mrgsolve result:
##      python3 dfu_reference_implementation.py --anchors
##  ============================================================================
