##  Idiopathic Intracranial Hypertension (IIH / pseudotumour cerebri)
##  QSP / PK-PD model
##  ============================================================================
##  Disease  : Idiopathic Intracranial Hypertension — raised CSF pressure
##             (> 25 cmH2O) without mass lesion, hydrocephalus, or venous
##             thrombosis, overwhelmingly in women of reproductive age with
##             central obesity and recent weight gain. Papilloedema threatens
##             permanent visual field loss; headache dominates quality of life.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.5)
##  Companion: iih_reference_check.py — a pure-Python reference implementation
##             of THIS system. Every number quoted in this header and in
##             README.md is printed by that script (iih_model_report.txt), so
##             the prose, the R model and the Python model can be checked
##             against each other.
##
##  ---------------------------------------------------------------------------
##  THE MODEL IN ONE EQUATION, AND WHY THAT EQUATION IS THE POINT
##  ---------------------------------------------------------------------------
##  Chronic CSF hydrodynamics obey the Davson relation
##
##        ICP  =  I_f * R_out  +  P_sss                                 (1)
##
##  with I_f the CSF formation rate (~0.35 mL/min), R_out the outflow
##  resistance, and P_sss the dural sinus pressure at the absorption site.
##  Equation (1) contains a BOUND: P_sss is additive, so as I_f -> 0 (a
##  perfect secretion-blocking drug) ICP -> P_sss and no further. Every drug
##  licensed or trialled for IIH — acetazolamide, topiramate, furosemide,
##  GLP-1 receptor agonists, 11beta-HSD1 inhibitors — acts on I_f. All of them
##  are therefore bounded by a term none of them touches.
##
##  What makes IIH more than plumbing is that P_sss is not a constant. The
##  transverse sinus is a collapsible tube inside the skull, so
##
##        P_sss = P_cv + G(ICP),      gamma = dG/dICP > 0               (2)
##
##  (1)+(2) is positive feedback. Closed-loop sensitivity to any input is the
##  open-loop sensitivity times 1/(1-gamma), and the bound becomes the
##  self-consistent VENOUS FLOOR
##
##        ICP_floor = P_cv + G(ICP_floor)                               (3)
##
##  Lalou 2020 (PMID 31832847) measured this coupling directly in PTCS: CSF
##  and sagittal sinus pressure track each other (R = 0.96 at baseline, 0.92
##  during infusion) and, during CSF drainage, keep tracking until the sinus
##  pressure bottoms out while CSF pressure continues to fall — gamma > 0
##  while the sinus is collapsible, gamma -> 0 once it is open. Equation (3)
##  is the quantitative content of that observation, and it is what separates
##  a drug from a stent: the drug scales I_f*R_out, the stent moves the floor
##  the drug is bounded by.
##
##  ---------------------------------------------------------------------------
##  SCOPE — 26 ODE compartments
##  ---------------------------------------------------------------------------
##    drug PK/PD (9)   acetazolamide (gut/central/CA-effect), topiramate
##                     (gut/central), exenatide (SC/central/effect),
##                     furosemide
##    hydrodynamics(4) ICP (Marmarou dynamics), P_sss (collapsible sinus),
##                     intra-abdominal pressure, central venous pressure
##    host (4)         body weight, androgen index, R_out, lymphatic reserve
##    devices (2)      venous stent effect (with restenosis), shunt patency
##    optic nerve (2)  papilloedema/axoplasmic stasis, surviving axon fraction
##    symptoms (3)     central sensitisation, HIT-6, pulsatile tinnitus
##    exposure (2)     serum bicarbonate, cumulative injurious TLPG integral
##
##  Time  : days (default horizon 365 d; acute scenarios run in minutes —
##          the ICP relaxation time constant is ~10 min, so lumbar puncture
##          and CSF infusion studies are inside the model, not bolted on).
##  Units : pressures mmHg internally, reported ALSO in cmH2O (= cmCSF, the
##          clinical unit: 1 mmHg = 1.35951 cmH2O); flows mL/min; weight kg;
##          OCT thickness um; perimetric mean deviation dB.
##
##  ---------------------------------------------------------------------------
##  CALIBRATION — one parameter per published anchor, in this order
##  ---------------------------------------------------------------------------
##   1 ROUT0      27.92 mmHg/(mL/min)  <- IIHTT baseline CSF pressure 357.2 mmH2O
##   2 EC50_ACZ   21.55 mg/L           <- IIHTT between-arm ICP difference -59.9
##                                        mmH2O  => eps_ACZ(2.5 g/day) = 0.283
##   3 KW_ACZ     17.29 kg/unit        <- IIHTT between-arm weight diff -4.05 kg
##   4 KEDON       0.914 um/(mmHg.d)   <- IIHTT OCT substudy: ACZ RNFL -175 um
##   5 ED50_FRISEN 289 um              <- IIHTT baseline Frisen grade 2.76
##   6 PMD_ED       2.91 dB            <- IIHTT ACZ-arm PMD gain +1.43 dB
##   7 KRG_ED      0.0206 um/um        <- IIHTT ACZ-arm RGCL -3.6 um
##   8 ED_CRIT     392 um              <- IIHTT mild cohort: no true axon loss
##   9 KAX         0.00227 /d          <- fulminant IIH: ~50% axon loss in 60 d
##  10 EC50_GLP    0.011 ug/L          <- exenatide RCT: ICP -5.7 cmH2O at 2.5 h
##
##  NOT calibrated, physiological constants: IF0 (0.35 mL/min), ELAST (0.11/mL,
##  Marmarou 1978), IOP (15 mmHg), KTRANS (abdominal-to-central transmission).
##  NOT calibrated, structural (varied in the sensitivity analysis): GMAX,
##  ICPCOL, WCOL (the collapse curve), KEDOFF (papilloedema resolution time
##  constant, 42 d, from the clinical course), and the entire slow
##  R_out/meningeal-lymphatic remodelling loop, which has NO human quantitative
##  anchor in IIH and is included because chronicity and relapse need one.
##
##  ---------------------------------------------------------------------------
##  WHAT THIS MODEL COMPUTES THAT IS WORTH KNOWING
##  ---------------------------------------------------------------------------
##  (1) THE VENOUS FLOOR IS A HARD BOUND. Pin a virtual patient to a measured
##      opening pressure of 37 cmH2O and vary only the COMPOSITION of that
##      pressure (how much is trans-stenotic gradient, how much resistive).
##      The maximum ICP fall achievable by a PERFECT secretion blocker ranges
##      from 24.8 cmH2O (no stenosis, floor 10.9) down to 7.8 cmH2O (severe
##      stenosis, floor 29.2) — a 3.2-fold range across patients with the same
##      measured pressure. In the stenosis-dominated compositions the floor
##      sits ABOVE the 25 cmH2O remission threshold. Those patients cannot be brought to remission by
##      any drug at any dose — and they are exactly the phenotype referred for
##      stenting at a mean acetazolamide dose of 950 mg/day with a CSF pressure
##      of 37 cmH2O (PMID 29871989). Drug failure there is structural.
##
##  (2) THE LOOP GAIN IS VISIBLE IN PUBLISHED DATA. Stenting lowers sagittal
##      sinus pressure by 8.1 mmHg (PMID 29922401) and CSF pressure by 16.8
##      cmH2O = 12.4 mmHg (PMID 29871989) — a ratio of 1.5. A passive,
##      non-collapsible sinus forces that ratio to be EXACTLY 1, because
##      lowering P_sss by x lowers ICP by x and nothing else changes. A ratio
##      above 1 is only possible with a collapsible sinus, and 1/(1-gamma) =
##      1.5 gives gamma ~ 0.35. Both known biases across that 3-month interval
##      (acetazolamide dose fell 950 -> 300 mg/day, weight ROSE 1.1 kg) push
##      the other way, so the gain is if anything under-estimated.
##
##  (3) ICP IS A STATE, VISION IS AN INTEGRAL — so a pressure endpoint
##      mis-prices interventions by their SHAPE IN TIME. Acetazolamide is a
##      step (full effect in days); weight loss is a ramp (~90-day time
##      constant). Forced to the SAME day-180 pressure, the step delivers
##      1.26x the visual gain of the ramp (1.23 vs 0.97 dB), because the eye
##      integrates an excursion the pressure endpoint has already forgotten.
##      A 6-month ICP endpoint therefore systematically over-values weight
##      loss (and the weight component of GLP-1 agonists) against drugs,
##      stents and shunts that act as steps.
##
##      This effect is REAL but SMALL, and that matters, because 1.26x is not
##      enough to explain the asymmetry it was invoked for. IIHTT reports that
##      weight loss mediated ~20% of the between-arm PRESSURE difference
##      (4.05 kg x 0.28 cmH2O/kg of 5.99 cmH2O) but only 4% of the VISION
##      benefit (0.03 dB of 0.71 dB in the trial's own mediation analysis).
##      This model gets the pressure share right (18.7%) and the vision share
##      WRONG (~16% against the reported 4%) — see the failures section.
##
##  (4) THE IIHTT PLACEBO ARM FALLS ~5x MORE THAN ANY WEIGHT MECHANISM ALLOWS.
##      Its 3.45 kg of weight loss buys at most 0.97 cmH2O at the IIH:WT slope
##      (0.28 cmH2O/kg); the observed fall was 5.24 cmH2O, an implied slope of
##      1.52 cmH2O/kg. Fitted to each arm's ABSOLUTE fall, the model shortfalls
##      are -49.7 mmH2O (acetazolamide) and -46.8 mmH2O (placebo) — nearly
##      EQUAL, which is the signature of an arm-independent, non-treatment
##      offset (enrolment required a raised opening pressure, and LP opening
##      pressure has large within-subject variance: regression to the mean).
##      The consequence is a warning about method: reading the trial at face
##      value requires eps_ACZ = 0.53, at or above the pharmacological ceiling
##      for carbonic anhydrase inhibition, whereas the randomisation-protected
##      between-arm reading requires 0.28. A QSP model fitted to absolute arm
##      trajectories — the common practice — silently picks the first and
##      inherits the artefact as drug potency.
##
##  (5) THE ICP ENDPOINT CANNOT SEPARATE POTENCY FROM LOOP GAIN. It constrains
##      only the product eps * I_f * R_out / (1 - gamma). Rows of the
##      identifiability table trade gamma against eps exactly; what breaks the
##      tie is not more pressure data but one venous manometry or one infusion
##      study with a simultaneous sinus trace. Worse, the classical CSF
##      infusion test measures R_out/(1-gamma), not R_out — in IIH it is
##      biased HIGH by the amplification factor, and any drug effect predicted
##      from it is biased with it.
##
##  (6) RNFL AND RGCL ARE NOT VALID SURROGATES, and the trial's own numbers
##      show it. RNFL = axons + swelling - atrophy, so falling RNFL is either
##      recovery or blindness. IIHTT's RGCL "thinned" MORE in the
##      acetazolamide arm (3.6 vs 2.1 um) — which reads as more damage but is
##      oedema contamination resolving faster in the better-treated arm. This
##      model reproduces both RGCL numbers with essentially ZERO true axon
##      loss, which is the correct reading of a mild-visual-loss cohort.
##
##  ---------------------------------------------------------------------------
##  WHAT THIS MODEL GETS WRONG, STATED RATHER THAN TUNED AWAY
##  ---------------------------------------------------------------------------
##  * It reproduces the IIHTT between-arm PRESSURE difference to 5% (-56.9 vs
##    -59.9 mmH2O) but OVER-predicts the between-arm PMD difference by ~1.8x
##    (1.31 vs 0.71 dB). The excess is the same size as the placebo-arm visual
##    improvement the model cannot generate (0.12 predicted vs 0.71 observed).
##    If the placebo arm's pressure fall is partly artefact, its 0.59 dB of
##    unexplained visual gain plausibly is too — perimetry has a documented
##    learning effect — but the model cannot prove that, and until it is
##    resolved the ocular chain here is too responsive to pressure.
##  * It over-predicts the visual value of weight loss. The model puts the
##    weight-mediated share of the IIHTT vision benefit at ~16%; the trial's
##    mediation analysis put it at 4% (0.03 of 0.71 dB). The step-vs-ramp
##    timing penalty accounts for only 1.26x of the needed ~5x. Either that 4%
##    is a decomposition of noise — IIHTT's TOTAL PMD effect was 0.71 dB with
##    a 95% CI of 0 to 1.43 and p = 0.050, and the model's ~16% sits well
##    inside that interval — or weight loss lowers pressure without protecting
##    the nerve proportionally, which would require the ocular chain to be
##    driven by something other than the pressure fed to it here. The model
##    cannot decide, and the discrepancy is left standing.
##  * The exenatide anchor is only just reachable: the observed -5.7 cmH2O at
##    2.5 hours forces the GLP-1R maximal secretory effect to ~0.5, essentially
##    equal to acetazolamide's ceiling, and forces the 10 ug bid dose to sit
##    near saturation (EC50 0.011 ug/L). That is a strong, falsifiable claim:
##    higher doses or weekly analogues should NOT deepen the acute ICP fall,
##    only the weight-mediated ramp. The trial's own time course is also
##    non-monotone (-5.7 at 2.5 h, -6.4 at 24 h, -5.6 at 12 weeks) in a way
##    this model structurally cannot produce while weight is falling.
##  * The model's baseline papilloedema (456 um RNFL) is higher than typical
##    reported IIH values (~250-350 um). Only RNFL CHANGE is compared with the
##    trial, and PMD/Frisen are normalised to baseline, so the pressure
##    conclusions do not depend on it — but the absolute OCT scale should not
##    be quoted.
##  * Headache is modelled with a large central-sensitisation term precisely
##    because it is famously poorly coupled to pressure; that term is
##    structurally motivated and quantitatively unanchored.
##
##  Disclaimer: research / education / hypothesis generation only. Not for
##  clinical decisions, prescribing, or regulatory submission. Per-patient
##  floors must not be quoted without that patient's own manometry.
##  ============================================================================

library(mrgsolve)

iih_code <- '
[PROB]
QSP model of idiopathic intracranial hypertension. Couples CSF secretion
(choroid plexus, carbonic anhydrase / Na-K-ATPase / NKCC1 / GLP-1R), CSF
outflow resistance (arachnoid granulations, meningeal lymphatics, glymphatic
reserve), and a COLLAPSIBLE dural venous sinus that makes sinus pressure a
rising function of ICP — a positive feedback loop with gain gamma whose
self-consistent solution is a venous FLOOR that bounds every
secretion-blocking drug. Downstream: translaminar pressure gradient ->
axoplasmic stasis -> papilloedema (reversible) and axon loss (irreversible)
-> Frisen grade, OCT RNFL/RGCL, perimetric mean deviation; plus headache with
central sensitisation and pulsatile tinnitus tracking the trans-stenotic
gradient. Therapies: acetazolamide, topiramate, exenatide/GLP-1 RA,
furosemide, 11beta-HSD1 inhibition, weight loss, bariatric surgery, venous
sinus stenting, CSF shunting, therapeutic LP and CSF infusion testing.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- unit conversion ---------------------------------------------------------
CMPMMHG      : 1.35951 : cmH2O per mmHg (clinical CSF pressure unit)

//--- CSF secretion (the I_f term) -------------------------------------------
IF0          : 0.35   : mL/min, CSF formation rate (healthy adult)
ELAST        : 0.11   : 1/mL, cerebral elastance (Marmarou 1978)

//--- CSF outflow (the R_out term) -------------------------------------------
ROUT0        : 27.92  : mmHg/(mL/min), outflow resistance (normal 6-10)
TAU_ROUT     : 180    : d, time constant of outflow-pathway remodelling
KROUT_LYMPH  : 0.45   : fractional R_out rise at zero lymphatic reserve
LYMPH0       : 1.0    : lymphatic/glymphatic reserve, 1 = intact
TAU_LYMPH    : 120    : d
KL_ICP       : 0.020  : reserve lost per mmHg above ICP_LYMPH
ICP_LYMPH    : 20     : mmHg, threshold for reserve loss

//--- collapsible sinus (the amplifier and the floor) -----------------------
GMAX         : 13.0   : mmHg, maximal trans-stenotic gradient (0 = no stenosis)
ICPCOL       : 18.0   : mmHg, midpoint of the sinus collapse curve
WCOL         : 13.0   : mmHg, width of the collapse curve
TAU_SSS      : 0.010  : d (~14 min), sinus pressure relaxation

//--- abdominal -> central venous chain (the P_cv term) --------------------
PCV0         : 8.0    : mmHg, post-stenotic outflow pressure at ref weight
KTRANS       : 0.32   : fraction of intra-abdominal pressure reaching P_cv
IAP0         : 14.0   : mmHg, intra-abdominal pressure at reference weight
KIAP_W       : 0.45   : mmHg IAP per kg body weight
WREF         : 107.7  : kg, IIHTT reference weight
TAU_IAP      : 20     : d
TAU_PCV      : 1.0    : d
NAPD         : 0      : mmHg, negative-abdominal-pressure device offset on IAP

//--- body weight -----------------------------------------------------------
W0           : 107.7  : kg, baseline weight
TAU_W        : 90     : d
D_DIET       : 0      : kg, weight set-point shift from dietary intervention
TAU_DIET     : 0      : d (0 = use TAU_W; VLCD is faster, ~40 d)
D_BARI       : 0      : kg, weight set-point shift from bariatric surgery
TAU_BARI     : 200    : d
T_BARI       : 1e9    : d, time of bariatric surgery
KW_ACZ       : 17.29  : kg per unit acetazolamide effect
KW_GLP       : 22.0   : kg per unit GLP-1R effect
KW_TPM       : 12.0   : kg per unit topiramate effect

//--- androgen / 11beta-HSD1 axis -------------------------------------------
AND0         : 1.0    : androgen index (1 = IIH reference)
TAU_AND      : 30     : d
KAND_W       : 0.35   : androgen index per 100 kg body weight
KAND_SECR    : 0.25   : fractional rise in I_f per unit androgen index
EHSD         : 0      : 11beta-HSD1 inhibitor effect (0-1), e.g. AZD4017

//--- acetazolamide PK/PD ---------------------------------------------------
KA_ACZ       : 36     : 1/d
V_ACZ        : 20     : L
CL_ACZ       : 100    : L/d (t1/2 ~3.3 h)
EMAX_ACZ     : 0.55   : max fractional suppression of I_f (CA-inhibition ceiling)
EC50_ACZ     : 21.55  : mg/L
HILL_ACZ     : 3.0    : steep: CSF flow falls only once CA is nearly fully inhibited
TAU_EACZ     : 0.20   : d, equilibration of carbonic anhydrase inhibition
HCO30        : 25     : mmol/L, baseline serum bicarbonate
KHCO3        : 9.0    : mmol/L fall in bicarbonate at full effect
TAU_HCO3     : 2.0    : d
AD_SENS      : 0.30   : adherence lost per unit normalised side-effect burden

//--- topiramate ------------------------------------------------------------
KA_TPM       : 12     : 1/d
V_TPM        : 60     : L
CL_TPM       : 36     : L/d (t1/2 ~21 h)
EMAX_TPM     : 0.15   : max fractional suppression of I_f
EC50_TPM     : 4.0    : mg/L

//--- exenatide / GLP-1 receptor agonist -----------------------------------
KA_GLP       : 24     : 1/d
V_GLP        : 20     : L
CL_GLP       : 139    : L/d (t1/2 ~2.4 h)
EMAX_GLP     : 0.50   : max fractional suppression of I_f
EC50_GLP     : 0.011  : ug/L
TAU_EGLP     : 0.04   : d (~1 h), fast enough for the 2.5-hour trial endpoint

//--- furosemide ------------------------------------------------------------
KA_FUR       : 18     : 1/d
V_FUR        : 15     : L
CL_FUR       : 90     : L/d
EMAX_FUR     : 0.20   : max fractional suppression of I_f (NKCC1)
EC50_FUR     : 1.5    : mg/L

//--- devices ---------------------------------------------------------------
KREST        : 0.00035 : 1/d, in-stent restenosis
SHUNT_ON     : 0      : 1 = CSF shunt in place
T_SHUNT      : 1e9    : d, time of shunt insertion
RSHUNT       : 12     : mmHg/(mL/min), valve + catheter resistance
PVALVE       : 8      : mmHg, valve opening pressure
KOCC         : 0.0011 : 1/d, shunt occlusion hazard

//--- CSF infusion / drainage (LP, infusion study) -------------------------
INF_RATE     : 0      : mL/min added to CSF space (negative = drainage)
T_INF_ON     : 1e9    : d
T_INF_OFF    : 1e9    : d

//--- optic nerve -----------------------------------------------------------
IOP          : 15     : mmHg, intraocular pressure
FSHEATH      : 1.0    : fraction of ICP reaching the retrolaminar space
TLPG0        : 2.0    : mmHg, translaminar gradient at which stasis begins
KEDON        : 0.914  : um/(mmHg.d), swelling gain
KEDOFF       : 0.0238 : 1/d, resolution of axoplasmic stasis (tau 42 d)
ED50_FRISEN  : 289    : um, swelling giving Frisen grade 2.5
FRISEN_MAX   : 5.0    : maximal Frisen grade
RNFL0        : 100    : um, normal peripapillary RNFL
RGCL0        : 35     : um, normal ganglion cell layer
KRG_ED       : 0.0206 : um apparent RGCL per um of swelling (contamination)
ED_CRIT      : 392    : um, swelling above which axons are lost
KAX          : 0.00227 : 1/d per unit normalised excess swelling
PMD_ED       : 2.91   : dB of field loss from reversible swelling
PMD_BASE_AX  : 0.62   : dB of irreversible baseline deficit
PMD_AX       : 18     : dB of field loss at total axon loss
TLPG_INJ     : 12     : mmHg, gradient above which exposure counts as injurious
ONSF         : 0      : 1 = optic nerve sheath fenestration (protects nerve only)
ONSF_EFF     : 0.55   : fractional reduction of the swelling drive after ONSF

//--- symptoms --------------------------------------------------------------
HIT6_BASE    : 58     : baseline HIT-6 (severe impact)
KHA_ICP      : 0.95   : HIT-6 points per cmH2O
TAU_HIT      : 20     : d
KHA_SENS     : 12     : HIT-6 points at full central sensitisation
KSENS_ON     : 0.0035 : 1/d growth of sensitisation while headache is severe
KSENS_OFF    : 0.0025 : 1/d decay
KHA_ACZ      : 6.0    : HIT-6 points from acetazolamide side effects
TINN_K       : 3.0    : mmHg gradient giving half-maximal tinnitus
TAU_TINN     : 3.0    : d

[CMT] @annotated
AGUT_ACZ : mg,   acetazolamide gut depot
ACEN_ACZ : mg,   acetazolamide central
EACZ     : -,    carbonic anhydrase inhibition effect (0-1)
AGUT_TPM : mg,   topiramate gut depot
ACEN_TPM : mg,   topiramate central
ASC_GLP  : ug,   exenatide subcutaneous depot
ACEN_GLP : ug,   exenatide central
EGLP     : -,    choroid plexus GLP-1R effect (0-1)
ACEN_FUR : mg,   furosemide central
ICP      : mmHg, intracranial pressure
PSSS     : mmHg, dural sinus pressure at the absorption site
IAP      : mmHg, intra-abdominal pressure
PCV      : mmHg, post-stenotic central venous pressure
W        : kg,   body weight
AND      : -,    androgen index
ROUT     : mmHg/(mL/min), CSF outflow resistance
LYMPH    : -,    meningeal lymphatic / glymphatic reserve
STENT    : -,    fraction of the trans-stenotic gradient abolished
SHUNTP   : -,    shunt patency
EDEMA    : um,   papilloedema (axoplasmic stasis) as RNFL swelling
AXON     : -,    surviving axon fraction
SENS     : -,    headache central sensitisation
HIT6     : -,    HIT-6 headache impact score
TINN     : -,    pulsatile tinnitus severity (0-10)
HCO3     : mmol/L, serum bicarbonate
AUCTL    : mmHg.d, cumulative injurious translaminar exposure

[MAIN]
// ---- untreated steady state as the initial condition ---------------------
// Solve ICP = I_f*R_out + P_cv + G(ICP) by damped fixed-point iteration, so
// that every simulation starts on the chronic fixed point of that
// patient rather than on an arbitrary guess that then drifts.
double iap_init = IAP0 + KIAP_W*(W0 - WREF);
double pcv_init = PCV0 + KTRANS*(iap_init - IAP0);
double and_init = AND0 + KAND_W*(W0 - WREF)/100.0;
double if_init  = IF0*(1.0 + KAND_SECR*(and_init - 1.0));
double icp_i    = pcv_init + 10.0;
for (int i = 0; i < 300; ++i) {
  double s   = 1.0/(1.0 + exp(-(icp_i - ICPCOL)/WCOL));
  double nxt = pcv_init + GMAX*s + if_init*ROUT0;
  icp_i += 0.5*(nxt - icp_i);
}
double s_i     = 1.0/(1.0 + exp(-(icp_i - ICPCOL)/WCOL));
double psss_i  = pcv_init + GMAX*s_i;
double tlpg_i  = FSHEATH*icp_i - IOP;
double drive_i = (tlpg_i > TLPG0) ? (tlpg_i - TLPG0) : 0.0;
double grad_i  = GMAX*s_i;

IAP_0    = iap_init;
PCV_0    = pcv_init;
AND_0    = and_init;
ICP_0    = icp_i;
PSSS_0   = psss_i;
W_0      = W0;
ROUT_0   = ROUT0;
LYMPH_0  = LYMPH0;
STENT_0  = 0.0;
SHUNTP_0 = 1.0;
EDEMA_0  = KEDON*drive_i/KEDOFF;
AXON_0   = 1.0;
HCO3_0   = HCO30;
HIT6_0   = HIT6_BASE;    // param is HIT6_BASE: "HIT6_0" is reserved by
                         // mrgsolve as the initial condition of HIT6
TINN_0   = 10.0*grad_i/(grad_i + TINN_K);
SENS_0   = 0.0;
AUCTL_0  = 0.0;

[ODE]
// ==========================================================================
// DRUG PK
// ==========================================================================
double c_acz = ACEN_ACZ/V_ACZ;          // mg/L
double c_tpm = ACEN_TPM/V_TPM;          // mg/L
double c_glp = ACEN_GLP/V_GLP;          // ug/L
double c_fur = ACEN_FUR/V_FUR;          // mg/L

dxdt_AGUT_ACZ = -KA_ACZ*AGUT_ACZ;
dxdt_ACEN_ACZ =  KA_ACZ*AGUT_ACZ - CL_ACZ*c_acz;
dxdt_AGUT_TPM = -KA_TPM*AGUT_TPM;
dxdt_ACEN_TPM =  KA_TPM*AGUT_TPM - CL_TPM*c_tpm;
dxdt_ASC_GLP  = -KA_GLP*ASC_GLP;
dxdt_ACEN_GLP =  KA_GLP*ASC_GLP - CL_GLP*c_glp;
dxdt_ACEN_FUR = -CL_FUR*c_fur;

// Tolerability feeds back on the achievable dose. Acetazolamide in IIH is
// limited by paraesthesia/fatigue, not by any lack of pharmacological
// ceiling: 48% of the IIHTT arm could not reach the 4 g/day target.
double sideff = (HCO30 - HCO3)/KHCO3;
if (sideff < 0.0) sideff = 0.0;
double adhere = 1.0 - AD_SENS*sideff;
if (adhere < 0.25) adhere = 0.25;

// ==========================================================================
// DRUG PD — every drug below acts on the SAME term, I_f
// ==========================================================================
double ca_p    = pow(c_acz, HILL_ACZ);
double e_acz_t = EMAX_ACZ*ca_p/(pow(EC50_ACZ, HILL_ACZ) + ca_p)*adhere;
dxdt_EACZ      = (e_acz_t - EACZ)/TAU_EACZ;
double e_glp_t = EMAX_GLP*c_glp/(EC50_GLP + c_glp);
dxdt_EGLP      = (e_glp_t - EGLP)/TAU_EGLP;
double e_tpm   = EMAX_TPM*c_tpm/(EC50_TPM + c_tpm);
double e_fur   = EMAX_FUR*c_fur/(EC50_FUR + c_fur);

double ifrac = (1.0 - EACZ)*(1.0 - EGLP)*(1.0 - e_tpm)*(1.0 - e_fur)
               *(1.0 + KAND_SECR*(AND - 1.0));
if (ifrac < 0.0) ifrac = 0.0;
double i_f = IF0*ifrac;                                  // mL/min

// ==========================================================================
// HYDRODYNAMICS — Davson relation with a collapsible sinus
// ==========================================================================
double i_out = (ICP > PSSS) ? (ICP - PSSS)/ROUT : 0.0;    // mL/min
double i_sh  = 0.0;
if (SHUNT_ON > 0.5 && SOLVERTIME >= T_SHUNT && ICP > PVALVE)
  i_sh = SHUNTP*(ICP - PVALVE)/RSHUNT;
double i_ext = 0.0;
if (SOLVERTIME >= T_INF_ON && SOLVERTIME < T_INF_OFF) i_ext = INF_RATE;

// Marmarou: dP/dt = E*P*(net volume flux). Relaxation time constant here is
// ~10 min, which is why lumbar puncture and infusion studies are inside the
// model and why ICP tracks its quasi-steady state on a chronic time scale.
double icp_pos = (ICP > 1.0) ? ICP : 1.0;
dxdt_ICP = ELAST*icp_pos*(i_f - i_out - i_sh + i_ext)*1440.0;

double s_col  = 1.0/(1.0 + exp(-(ICP - ICPCOL)/WCOL));
double grad   = GMAX*(1.0 - STENT)*s_col;                 // G(ICP)
dxdt_PSSS     = (PCV + grad - PSSS)/TAU_SSS;

double iap_t  = IAP0 + KIAP_W*(W - WREF) - NAPD;
dxdt_IAP      = (iap_t - IAP)/TAU_IAP;
double pcv_t  = PCV0 + KTRANS*(IAP - IAP0);
dxdt_PCV      = (pcv_t - PCV)/TAU_PCV;

// ==========================================================================
// HOST: weight, androgens, outflow remodelling
// ==========================================================================
double w_set = W0 + D_DIET - KW_ACZ*EACZ - KW_GLP*EGLP - KW_TPM*e_tpm;
double tau_w = (TAU_DIET > 0.0) ? TAU_DIET : TAU_W;
dxdt_W = (w_set - W)/tau_w;
if (SOLVERTIME >= T_BARI) dxdt_W += (W0 + D_BARI - W)/TAU_BARI;

double and_t = AND0 + KAND_W*(W - WREF)/100.0 - EHSD;
dxdt_AND = (and_t - AND)/TAU_AND;

double lymph_t = LYMPH0 - KL_ICP*((ICP > ICP_LYMPH) ? (ICP - ICP_LYMPH) : 0.0);
if (lymph_t < 0.0) lymph_t = 0.0;
dxdt_LYMPH = (lymph_t - LYMPH)/TAU_LYMPH;
double rout_t = ROUT0*(1.0 + KROUT_LYMPH*(1.0 - LYMPH));
dxdt_ROUT = (rout_t - ROUT)/TAU_ROUT;

// ==========================================================================
// DEVICES
// ==========================================================================
dxdt_STENT  = -KREST*STENT;
dxdt_SHUNTP = (SHUNT_ON > 0.5) ? -KOCC*SHUNTP : 0.0;

// ==========================================================================
// OPTIC NERVE — one reversible channel, one irreversible channel
// ==========================================================================
double tlpg  = FSHEATH*ICP - IOP;
double drive = (tlpg > TLPG0) ? (tlpg - TLPG0) : 0.0;
if (ONSF > 0.5) drive *= (1.0 - ONSF_EFF);   // protects the nerve, not the ICP
dxdt_EDEMA = KEDON*drive - KEDOFF*EDEMA;
double excess = (EDEMA > ED_CRIT) ? (EDEMA - ED_CRIT)/100.0 : 0.0;
dxdt_AXON  = -KAX*excess*AXON;
dxdt_AUCTL = (tlpg > TLPG_INJ) ? (tlpg - TLPG_INJ) : 0.0;

// ==========================================================================
// SYMPTOMS
// ==========================================================================
double hit_t = HIT6_BASE + KHA_ICP*(ICP*CMPMMHG - 24.0*CMPMMHG)
               + KHA_SENS*SENS + KHA_ACZ*sideff;
dxdt_HIT6 = (hit_t - HIT6)/TAU_HIT;
double severe = (HIT6 > 55.0) ? 1.0 : 0.0;
dxdt_SENS = KSENS_ON*severe*(1.0 - SENS) - KSENS_OFF*(1.0 - severe)*SENS;
double tinn_t = 10.0*grad/(grad + TINN_K);
dxdt_TINN = (tinn_t - TINN)/TAU_TINN;

double hco3_t = HCO30 - KHCO3*EACZ/EMAX_ACZ;
dxdt_HCO3 = (hco3_t - HCO3)/TAU_HCO3;

[TABLE]
// ---- pressures in the clinical unit --------------------------------------
capture ICP_cm   = ICP*CMPMMHG;
capture PSSS_cm  = PSSS*CMPMMHG;
double s_out     = 1.0/(1.0 + exp(-(ICP - ICPCOL)/WCOL));
capture GRAD     = GMAX*(1.0 - STENT)*s_out;
// loop gain gamma = dG/dICP, and the closed-loop amplification it implies
capture GAMMA    = GMAX*(1.0 - STENT)*s_out*(1.0 - s_out)/WCOL;
capture AMPLIF   = 1.0/(1.0 - GAMMA);

// ---- THE VENOUS FLOOR: ICP_floor = P_cv + G(ICP_floor) -------------------
// The bound on every secretion-blocking drug, recomputed at every time point
// because weight loss and stenting both move it.
double fl = PCV;
for (int i = 0; i < 300; ++i) {
  double sf  = 1.0/(1.0 + exp(-(fl - ICPCOL)/WCOL));
  double nxt = PCV + GMAX*(1.0 - STENT)*sf;
  fl += 0.5*(nxt - fl);
}
capture FLOOR_cm  = fl*CMPMMHG;
capture DRUG_ROOM = (ICP - fl)*CMPMMHG;   // max ICP fall any I_f drug can give
capture FLOOR_OK  = (fl*CMPMMHG <= 25.0) ? 1.0 : 0.0;  // remission reachable?

// ---- ocular ---------------------------------------------------------------
capture TLPG_out = FSHEATH*ICP - IOP;
capture FRISEN   = FRISEN_MAX*EDEMA/(EDEMA + ED50_FRISEN);
double axl       = 1.0 - AXON;
capture AXLOSS   = 100.0*axl;
capture RNFL     = RNFL0 + EDEMA - RNFL0*axl;   // NOTE: two opposite channels
capture RGCL     = RGCL0*AXON + KRG_ED*EDEMA;   // ditto — see header point (6)
double tlpg0_ref = FSHEATH*ICP_0 - IOP;
double drive0    = (tlpg0_ref > TLPG0) ? (tlpg0_ref - TLPG0) : 1e-6;
double edema_ref = KEDON*drive0/KEDOFF;
capture PMD      = -(PMD_ED*EDEMA/edema_ref + PMD_BASE_AX + PMD_AX*axl);

// ---- clinical status ------------------------------------------------------
capture REMISSION = (ICP*CMPMMHG <= 25.0) ? 1.0 : 0.0;
capture DIPLOPIA  = (ICP*CMPMMHG >= 40.0) ? 1.0 : 0.0;
capture CACZ      = ACEN_ACZ/V_ACZ;
capture EPS_TOT   = 1.0 - (1.0 - EACZ)*(1.0 - EGLP);
'

iih <- mcode("iih", iih_code)

## ============================================================================
## HELPERS
## ============================================================================
## Acetazolamide is given in 4 divided daily doses (the IIHTT schedule);
## exenatide subcutaneously twice daily; topiramate twice daily.
acz_ev <- function(mg_per_day, dur = 365, start = 0)
  ev(time = start, amt = mg_per_day/4, cmt = "AGUT_ACZ",
     ii = 0.25, addl = max(0, dur*4 - 1))
glp_ev <- function(ug = 10, dur = 365, start = 0)
  ev(time = start, amt = ug, cmt = "ASC_GLP",
     ii = 0.5, addl = max(0, dur*2 - 1))
tpm_ev <- function(mg_per_day, dur = 365, start = 0)
  ev(time = start, amt = mg_per_day/2, cmt = "AGUT_TPM",
     ii = 0.5, addl = max(0, dur*2 - 1))
## A venous stent is a step change in the state STENT (fraction of the
## trans-stenotic gradient abolished), not a dose of anything.
stent_ev <- function(eff = 0.90, at = 14)
  ev(time = at, amt = eff, cmt = "STENT")
## Therapeutic lumbar puncture: withdraw ~25 mL over 10 minutes.
lp_ev <- function(at = 0, mL = 25, minutes = 10)
  list(INF_RATE = -mL/minutes, T_INF_ON = at, T_INF_OFF = at + minutes/1440)

## Phenotypes. Each is pinned to its published baseline PRESSURE; what differs
## between them is the COMPOSITION of that pressure — how much is venous floor
## and how much is resistive. That composition is exactly what the trials never
## measured, and it decides whether a drug can work at all.
IIH_phenotype <- function(which = c("iihtt", "resistive", "stenotic",
                                    "fulminant", "normal")) {
  which <- match.arg(which)
  switch(which,
    ## IIHTT-like: mild visual loss, moderate stenosis. ICP 35.7 cmH2O.
    ## This is the calibration patient; every fitted parameter came from it.
    iihtt     = list(GMAX = 13.0, PCV0 =  8.0, ROUT0 = 27.92, W0 = 107.7,
                     WREF = 107.7, IAP0 = 14.0),
    ## Pure outflow-resistance disease, no collapsible segment: the phenotype
    ## in which drugs have the most room (floor 10.9 cmH2O). ICP 35.7 cmH2O.
    resistive = list(GMAX =  0.0, PCV0 =  8.0, ROUT0 = 52.20, W0 = 107.7,
                     WREF = 107.7, IAP0 = 14.0),
    ## Stenosis-dominated — the phenotype referred for stenting. ICP 37 cmH2O,
    ## floor 29.2 cmH2O, i.e. ABOVE remission. Note P_cv is 9.0 and not higher:
    ## a larger venous term would force R_out below the normal 6-10 range, so
    ## this is the most drug-favourable composition still compatible with a
    ## severe stenosis, and the bound holds even there.
    stenotic  = list(GMAX = 22.0, PCV0 =  9.0, ROUT0 =  9.90, W0 =  95.4,
                     WREF =  95.4, IAP0 = 12.0),
    ## Fulminant: high floor (45.5 cmH2O), days-to-weeks to blindness.
    fulminant = list(GMAX = 28.0, PCV0 = 12.0, ROUT0 = 13.40, W0 = 110.0,
                     WREF = 110.0, IAP0 = 16.0),
    ## Healthy control for reference. ICP ~12 cmH2O.
    normal    = list(GMAX =  0.0, PCV0 =  5.1, ROUT0 = 10.60, W0 =  70.0,
                     WREF =  70.0, IAP0 =  6.0)
  )
}

run_iih <- function(pheno = "iihtt", pars = list(), events = NULL,
                    end = 365, delta = 1, dose_dur = NULL) {
  p <- modifyList(IIH_phenotype(pheno), pars)
  m <- param(iih, p)
  if (is.null(events)) mrgsim(m, end = end, delta = delta)
  else mrgsim(m, events = events, end = end, delta = delta)
}

## ============================================================================
## FOURTEEN PREBUILT THERAPY SCENARIOS
## ============================================================================
IIH_simulate_scenarios <- function(end = 365) {
  S <- list()

  ## --- 1. natural history, untreated -------------------------------------
  S[["01_natural_history"]] <- run_iih("iihtt", end = end)

  ## --- 2. IIHTT placebo arm: low-sodium weight-reduction diet only --------
  ##     observed: ICP 357.2 -> 304.8 mmH2O, weight -3.45 kg, PMD +0.71 dB
  S[["02_IIHTT_placebo_diet"]] <-
    run_iih("iihtt", list(D_DIET = -4.0), end = end)

  ## --- 3. IIHTT acetazolamide arm: 2.5 g/day achieved + same diet ---------
  ##     observed: ICP 357.2 -> 244.9 mmH2O, weight -7.50 kg, PMD +1.43 dB
  S[["03_IIHTT_acetazolamide"]] <-
    run_iih("iihtt", list(D_DIET = -4.0), acz_ev(2500, end), end = end)

  ## --- 4. acetazolamide at the 4 g/day TARGET dose ------------------------
  ##     the dose 48% of IIHTT patients could not tolerate; shows how little
  ##     extra pressure the extra 1.5 g/day buys once the Hill curve saturates
  S[["04_acetazolamide_4g"]] <-
    run_iih("iihtt", list(D_DIET = -4.0), acz_ev(4000, end), end = end)

  ## --- 5. topiramate 200 mg/day (weak CA inhibition + weight loss) --------
  S[["05_topiramate"]] <-
    run_iih("iihtt", list(D_DIET = -4.0), tpm_ev(200, end), end = end)

  ## --- 6. very-low-calorie diet (Sinclair 2010: -15.7 kg, ICP -8.0 cmH2O) -
  S[["06_very_low_calorie_diet"]] <-
    run_iih("iihtt", list(D_DIET = -17.0, TAU_DIET = 40), end = end)

  ## --- 7. bariatric surgery (IIH:WT: -21.4 kg, ICP -6.0 cmH2O at 12 mo) --
  S[["07_bariatric_surgery"]] <-
    run_iih("iihtt", list(D_BARI = -30.0, T_BARI = 30, W0 = 119.5), end = end)

  ## --- 8. exenatide 10 ug bid (Mitchell 2023: -5.7 cmH2O by 2.5 hours) ---
  S[["08_exenatide"]] <-
    run_iih("iihtt", list(W0 = 104.0, IAP0 = 12.5, ROUT0 = 21.2),
            glp_ev(10, end), end = end)

  ## --- 9. venous sinus stenting (Patsalides 2019: 37 -> 20.2 cmH2O) -------
  ##     note the arm of the argument: in that series weight ROSE 1.1 kg and
  ##     the acetazolamide dose FELL from 950 to 300 mg/day, so the pressure
  ##     fall cannot be attributed to either.
  S[["09_venous_sinus_stenting"]] <-
    run_iih("stenotic", events = stent_ev(0.90, 14), end = end)

  ## --- 10. stent + acetazolamide: the two terms together ------------------
  S[["10_stent_plus_acetazolamide"]] <-
    run_iih("stenotic",
            events = c(stent_ev(0.90, 14), acz_ev(2000, end)), end = end)

  ## --- 11. THE BOUND: maximal drug therapy in the stenotic phenotype ------
  ##     4 g/day acetazolamide PLUS exenatide PLUS topiramate. Watch
  ##     DRUG_ROOM: the fall stops at the venous floor whatever is added.
  S[["11_maximal_drug_vs_floor"]] <-
    run_iih("stenotic",
            events = c(acz_ev(4000, end), glp_ev(10, end), tpm_ev(200, end)),
            end = end)

  ## --- 12. CSF shunt: bypasses BOTH terms of the equation -----------------
  S[["12_csf_shunt"]] <-
    run_iih("iihtt", list(SHUNT_ON = 1, T_SHUNT = 14), end = end)

  ## --- 13. fulminant IIH: drug vs urgent stent ---------------------------
  ##     the model has no stable fixed point below the floor here, so the
  ##     clinically-observed answer (mechanical decompression, not dose
  ##     escalation) is a structural consequence, not a tuned one
  S[["13a_fulminant_drug_only"]] <-
    run_iih("fulminant", events = acz_ev(4000, end), end = end)
  S[["13b_fulminant_urgent_stent"]] <-
    run_iih("fulminant", events = stent_ev(0.90, 3), end = end)

  ## --- 14. acetazolamide withdrawal at 6 months: relapse ------------------
  ##     nothing structural changed, so ICP returns to its own fixed point
  S[["14_acetazolamide_withdrawal"]] <-
    run_iih("iihtt", list(D_DIET = -4.0), acz_ev(4000, dur = 180), end = end)

  S
}

## ============================================================================
## THE DIAGNOSTIC STUDIES THAT WOULD IDENTIFY THE MODEL
## ============================================================================
## A CSF infusion test measures R_out/(1-gamma), NOT R_out. Run the same test
## in a patient with and without a collapsible sinus and compare the apparent
## resistance with the true one: the ratio IS the amplification factor. Adding
## a simultaneous sinus pressure trace (dPSSS/dICP) turns an unidentifiable
## model into an identified one — which is the practical recommendation this
## model makes.
IIH_infusion_study <- function(rate = 1.5, minutes = 60) {
  out <- list()
  for (ph in c("resistive", "iihtt", "stenotic")) {
    p <- IIH_phenotype(ph)
    p$INF_RATE <- rate
    p$T_INF_ON <- 10/1440
    p$T_INF_OFF <- (10 + minutes)/1440
    out[[ph]] <- mrgsim(param(iih, p), end = (minutes + 20)/1440,
                        delta = 0.25/1440)
  }
  out
}

## A therapeutic lumbar puncture, to show how quickly CSF re-forms: the ICP
## relaxation time constant is E*ICP/R_out ~ 10 minutes, which is why an LP is
## a diagnostic manoeuvre and not a treatment.
IIH_lumbar_puncture <- function(mL = 25, minutes = 10) {
  p <- c(IIH_phenotype("iihtt"), lp_ev(at = 0.02, mL = mL, minutes = minutes))
  mrgsim(param(iih, p), end = 0.5, delta = 0.5/1440)
}

## ============================================================================
## THE HEADLINE CALCULATION: the drug ceiling as a function of a quantity
## nobody measures. Hold the OBSERVED opening pressure at 37 cmH2O and vary
## only the trans-stenotic gradient.
## ============================================================================
IIH_drug_ceiling_table <- function(icp_cm = 37.0,
                                   gmax_grid = c(0, 5, 10, 15, 20, 25)) {
  ## R_out required to put the untreated fixed point at icp_cm, per GMAX
  rout_for <- function(gmax) {
    f <- function(rout) {
      p <- modifyList(IIH_phenotype("stenotic"),
                      list(GMAX = gmax, ROUT0 = rout))
      as.numeric(mrgsim(param(iih, p), end = 0, delta = 1)$ICP_cm[1]) - icp_cm
    }
    stats::uniroot(f, c(0.5, 400))$root
  }
  do.call(rbind, lapply(gmax_grid, function(g) {
    r <- rout_for(g)
    p <- modifyList(IIH_phenotype("stenotic"), list(GMAX = g, ROUT0 = r))
    s <- mrgsim(param(iih, p), end = 0, delta = 1)
    data.frame(gradient_mmHg = round(as.numeric(s$GRAD[1]), 1),
               R_out = round(r, 1),
               ICP_cm = round(as.numeric(s$ICP_cm[1]), 1),
               floor_cm = round(as.numeric(s$FLOOR_cm[1]), 1),
               max_drug_fall_cm = round(as.numeric(s$DRUG_ROOM[1]), 1),
               remission_reachable = as.numeric(s$FLOOR_OK[1]) > 0.5)
  }))
}

## ============================================================================
## USAGE
## ============================================================================
if (FALSE) {
  ## the bound, in one table
  print(IIH_drug_ceiling_table())

  ## all fourteen scenarios
  S <- IIH_simulate_scenarios()
  plot(S[["03_IIHTT_acetazolamide"]], ICP_cm + FRISEN + PMD + W ~ time)

  ## a drug cannot cross the floor; a stent moves it
  plot(S[["11_maximal_drug_vs_floor"]], ICP_cm + FLOOR_cm + DRUG_ROOM ~ time)
  plot(S[["09_venous_sinus_stenting"]], ICP_cm + FLOOR_cm + GRAD + TINN ~ time)

  ## the infusion test measures the loop, not the tissue
  inf <- IIH_infusion_study()
  lapply(inf, function(s) tail(as.data.frame(s)[, c("time", "ICP", "PSSS")], 3))

  ## RNFL is not a surrogate: watch RNFL and AXLOSS diverge
  plot(S[["13a_fulminant_drug_only"]], RNFL + AXLOSS + PMD ~ time)
}
