##  Ménière's Disease (메니에르병) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Ménière's disease — endolymphatic sac dysfunction and stria
##             vascularis ion-transport imbalance drive endolymphatic hydrops
##             (cochlear duct/saccule/utricle distension), episodic Reissner's
##             membrane rupture with K+ intoxication of perilymph, progressive
##             cochlear (OHC/IHC) and vestibular hair-cell injury -> episodic
##             vertigo attacks, fluctuating low-to-pan-frequency sensorineural
##             hearing loss, tinnitus, aural fullness, and (in advanced/burned-
##             out disease) Tumarkin otolithic drop attacks.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 18 ODE compartments - drug PK (oral betahistine + active
##             metabolite, oral diuretic [HCTZ/triamterene combination lumped
##             as a single thiazide-class signal], intratympanic dexamethasone,
##             intratympanic gentamicin) + inner-ear disease network (endolymph
##             volume/hydrops index, cochlear OHC + vestibular hair-cell
##             viability tracked separately, perilymph K+-intoxication index,
##             PTA hearing threshold, vertigo attack-rate/frequency, tinnitus
##             severity, DHI/QoL) + ECoG SP/AP ratio biomarker output.
##  Time     : hours. Natural history (relapsing-remitting attacks over years,
##             eventual "burn-out") unfolds over months-years, so default
##             horizon is long: 0 - 8760 h (~12 months); chronic natural-
##             history runs can extend to 26280 h (~36 months).
##  Units    : oral drug doses in mg; intratympanic doses in mg (per injection,
##             local middle-ear depot, not systemic mg/kg); plasma/perilymph
##             concentrations mg/L; hydrops/hair-cell/K+-intoxication indices
##             as relative units (1.0 = normal baseline, hair-cell viability
##             1.0 = fully intact, 0 = complete loss); PTA in dB HL (0=normal,
##             higher=worse); vertigo attack rate in spells/month; tinnitus
##             severity 0-10; DHI 0-100 (higher=worse handicap); ECoG SP/AP
##             ratio dimensionless (>0.40-0.45 suggestive of hydrops).
##  Scenarios: 8 prebuilt - see MED_simulate_scenarios() at bottom.
##  Anchors  : Committee on Hearing and Equilibrium, AAO-HNS. Otolaryngol Head
##             Neck Surg 1995;113(3):181-185 (diagnostic criteria & 4-tone PTA
##             staging I-IV); Basura GJ, et al. Otolaryngol Head Neck Surg
##             2020;162(4):415-434 (AAO-HNS Clinical Practice Guideline);
##             Nauta JJP. Eur Arch Otorhinolaryngol 2014;271(5):887-897
##             (betahistine meta-analysis); Adrion C, et al. BMJ 2016;352:h6816
##             (BEMED trial - high-dose betahistine 48mg TID x9mo, no
##             superiority over placebo on attack frequency); James AL, Burton
##             MJ. Cochrane Database Syst Rev 2001 (diuretics for Ménière's -
##             insufficient evidence, still widely used); Thirlwall AS, Kundu
##             S. Cochrane Database Syst Rev 2006 (diuretics update); Phillips
##             JS, Westerberg B. Cochrane Database Syst Rev 2011;(7):CD008514
##             (intratympanic steroids for Ménière's); Patel M, et al. Lancet
##             2016;388(10061):2753-2762 (low-dose vs high-dose intratympanic
##             gentamicin RCT - equivalent vertigo control, low-dose trend
##             toward less hearing loss); Postema RJ, et al. Acta Otolaryngol
##             2008;128(8):876-880 (gentamicin titration protocol); Boleas-
##             Aguirre MS, et al. Arch Otolaryngol Head Neck Surg
##             2008;134(4):289-295 (gentamicin titration outcomes); Sajjadi H,
##             Paparella MM. Lancet 2008;372(9636):406-414 (Ménière's disease
##             review); Semaan MT, Megerian CA. Curr Opin Otolaryngol Head Neck
##             Surg 2011;19(5):392-398 (pathophysiology update); Merchant SN,
##             Adams JC, Nadol JB Jr. Otol Neurotol 2005;26(1):74-81 (temporal
##             bone histopathology of hydrops); Minor LB. JAMA
##             1998;280(17):1568 (Tumarkin/vestibular drop attacks review
##             context); Rauch SD. N Engl J Med 2008;359(9):919-921 (clinical
##             review); AAO-HNS 1995 Functional Level Scale (FLS 1-6).
##  Disclaimer: For research / education / hypothesis generation only.
##              Not a substitute for clinical judgment or regulatory filings.
##  ============================================================================
[PROB]
QSP model of Ménière's disease linking endolymphatic sac dysfunction and
stria vascularis ion-transport imbalance to endolymphatic hydrops, episodic
Reissner's membrane rupture/perilymph K+ intoxication, cochlear and
vestibular hair-cell injury, and the resulting episodic vertigo, fluctuating
hearing loss, tinnitus and handicap, with mechanistic PK/PD for betahistine,
thiazide/K+-sparing diuretic, intratympanic dexamethasone and intratympanic
gentamicin (chemical labyrinthectomy).

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient / disease covariates
AGE          : 55    : age (years; MD typically presents 40-60)
WT           : 70    : body weight (kg)
STAGE0       : 2     : AAO-HNS stage at baseline (1-4, by 4-tone PTA average)
DURATION_YR  : 3     : disease duration at baseline (years since diagnosis)
BILATERAL    : 0     : 1 = bilateral disease at baseline

//--- Betahistine PK (rapid absorption, extensive first-pass to active
//    metabolite aminoethylpyridine; oral TID dosing)
KA_BETA      : 1.8    : 1/h (oral absorption)
CL_BETA      : 4.20   : L/h/kg equivalent lumped clearance (fast elimination, t1/2~3-4h parent)
V_BETA       : 2.5    : L/kg equivalent central volume (lumped)
F_BETA       : 0.90   : oral bioavailability (parent, pre-metabolite)
KA_MET       : 1.2    : 1/h (formation/appearance rate of active metabolite pool)
KE_MET       : 0.35   : 1/h (metabolite elimination, longer apparent persistence)
EC50_BETA_CBF: 8      : ng/mL metabolite conc for half-maximal cochlear blood-flow/vestibular-compensation effect
EMAX_BETA_COMP: 0.35  : max fractional increase in central vestibular compensation rate at saturating betahistine
EMAX_BETA_HYDR: 0.15  : max fractional reduction in endolymph production rate (modest; BEMED showed limited effect)

//--- Diuretic PK (lumped thiazide [HCTZ] + K+-sparing [triamterene] signal;
//    single "diuretic effect" compartment reflecting systemic+local fluid effect)
KA_DIUR      : 1.0    : 1/h (oral absorption, lumped)
CL_DIUR      : 0.25   : L/h/kg lumped clearance
V_DIUR       : 0.60   : L/kg lumped volume
F_DIUR       : 0.70   : oral bioavailability (lumped)
EC50_DIUR    : 0.08   : mg/L for half-maximal renal/inner-ear fluid effect
EMAX_DIUR_HYDR: 0.20  : max fractional reduction in endolymph volume at saturating diuretic exposure

//--- Intratympanic dexamethasone PK (local middle-ear depot -> round-window
//    membrane permeation -> perilymph; genomic anti-inflammatory persistence)
KMEDEX       : 0.060  : 1/h (middle-ear depot clearance/absorption across RWM)
KPERI_OUT_DEX: 0.040  : 1/h (perilymph dexamethasone elimination)
V_PERI_DEX   : 0.15   : L (perilymph + adjoining inner-ear fluid equivalent volume)
KOUT_GRDEX   : 0.020  : 1/h (genomic GR-signal turnover, t1/2~35h persistence)
EC50_DEX_GR  : 0.50   : mg/L perilymph concentration for half-maximal GR genomic signal
EMAX_DEX_ANTIINFLAM: 0.40 : max fractional reduction in autoimmune/inflammatory injury drive
EMAX_DEX_HYDR: 0.15   : max fractional improvement in fluid resorption (Na/K-ATPase upregulation)

//--- Intratympanic gentamicin PK (local depot -> RWM permeation -> perilymph
//    -> vestibular hair-cell uptake; selective ototoxicity)
KMEGENT      : 0.045  : 1/h (middle-ear depot clearance/absorption across RWM)
KPERI_OUT_GENT: 0.030 : 1/h (perilymph gentamicin elimination)
V_PERI_GENT  : 0.15   : L (perilymph equivalent volume)
KUP_VEST     : 0.0180 : 1/h (vestibular hair-cell uptake rate constant, high affinity)
KUP_COCH     : 0.0022 : 1/h (cochlear hair-cell uptake rate constant, lower affinity - basis of selectivity)
EC50_GENT_VESTKILL: 3.0 : mg/L perilymph for half-maximal vestibular hair-cell kill rate
KKILL_VEST_MAX: 0.0090 : 1/h max vestibular hair-cell death rate at saturating gentamicin
EC50_GENT_COCHTOX : 8.0 : mg/L perilymph for half-maximal cochlear ototoxic injury rate
KKILL_COCH_MAX: 0.0035 : 1/h max cochlear hair-cell injury rate at saturating gentamicin (lower than vestibular - therapeutic window)

//--- Endolymph / hydrops dynamics
KIN_HYDROPS  : 0.00090 : 1/h baseline endolymph-volume/hydrops production rate
KOUT_HYDROPS : 0.00070 : 1/h baseline hydrops resorption rate
HYDROPS0     : 1.0     : baseline hydrops index (1.0 = mild/compensated hydrops at typical diagnosis)
K_STAGE_HYDR : 0.35    : additional hydrops drive per AAO-HNS stage above 1

//--- Perilymph K+ intoxication (episodic Reissner's-membrane-rupture events)
KRUPTURE_BASE: 0.0030  : 1/h baseline stochastic-mean rupture/leak rate at HYDROPS=1
HILL_RUPT    : 3.0     : Hill coefficient - rupture probability rises steeply above hydrops threshold
HYDROPS_RUPT50: 1.8    : hydrops index for half-maximal rupture-rate escalation
KOUT_KINTOX  : 0.25    : 1/h fast clearance/re-equilibration of transient K+ intoxication signal
KIN_KINTOX_PER_RUPT: 3.5 : magnitude of K+-intoxication impulse per rupture event (arbitrary units)

//--- Cochlear (outer hair cell, OHC) viability
KOUT_OHC     : 0.000045: 1/h baseline slow OHC attrition from chronic hydrops/K+ stress
K_KINTOX_OHC : 0.00028 : 1/h*unit added OHC injury rate per unit K+-intoxication index
KREGEN_OHC   : 0.0000090: 1/h slow partial regenerative/compensatory recovery toward 1.0 (early/reversible phase)

//--- Vestibular hair-cell viability
KOUT_VEST    : 0.000035: 1/h baseline slow vestibular hair-cell attrition
K_KINTOX_VEST: 0.00022 : 1/h*unit added vestibular injury rate per unit K+-intoxication index
KREGEN_VEST  : 0.0000070: 1/h slow partial regenerative/compensatory recovery

//--- Vertigo attack generation
TAU_VERTFREQ : 400    : h turnover time constant for attack-frequency state toward target
W_HYDR_VERT  : 3.0     : weight of hydrops index on attack-frequency target
W_KINTOX_VERT: 1.6     : weight of K+-intoxication index on attack-frequency target (acute spikes)
W_VEST_VERT  : -2.0    : weight of vestibular hair-cell viability on attack-frequency target (loss of viable cells eventually reduces attacks - "burn-out")
VERTFREQ_MAX : 12      : ceiling spells/month (severe uncontrolled disease)

//--- Central vestibular compensation (reduces functional impact of attacks over time; also drives burn-out)
KIN_COMP     : 0.00060 : 1/h baseline compensation accrual
KOUT_COMP    : 0.00030 : 1/h compensation decay (attacks reset compensation partially)
K_ATTACK_DECOMP: 0.35  : decompensating effect of each unit of current vertigo-frequency target on compensation

//--- PTA hearing threshold mapping
PTA0         : 25     : dB HL baseline PTA (stage-dependent, set in $MAIN)
K_OHC_PTA    : 55      : dB HL swing per unit OHC-viability loss (1.0->0 viability spans ~55dB)

//--- Tinnitus severity mapping
TINN0        : 3      : baseline tinnitus severity (0-10)
K_OHC_TINN   : 6       : tinnitus severity points per unit OHC-viability loss

//--- DHI / QoL mapping
DHI_MAX      : 100    : ceiling Dizziness Handicap Inventory score
W_VERT_DHI   : 7.0     : DHI points per (spell/month) of current vertigo frequency
W_TUMARKIN_DHI: 15.0   : additional DHI points if Tumarkin drop-attack risk flag active
W_COMP_DHI   : -18.0   : DHI reduction per unit central vestibular compensation

//--- Tumarkin otolithic drop-attack risk (advanced/unpredictable vestibular loss)
TUMARKIN_VEST_THRESH: 0.55 : vestibular viability threshold below which drop-attack risk emerges
TUMARKIN_HYDR_THRESH: 1.6  : hydrops index threshold contributing to drop-attack risk

//--- ECoG SP/AP ratio biomarker
SPAP0        : 0.30   : baseline (normal) ECoG SP/AP ratio
K_HYDR_SPAP  : 0.10    : SP/AP ratio increase per unit hydrops index above baseline

[CMT] @annotated
GUT_BETA   : Betahistine oral gut depot (mg)
CEN_BETA   : Betahistine parent plasma compartment (mg)
MET_BETA   : Betahistine active metabolite (aminoethylpyridine) pool (mg-equivalent)
GUT_DIUR   : Diuretic oral gut depot (mg, lumped HCTZ/triamterene signal)
CEN_DIUR   : Diuretic plasma compartment (mg, lumped)
ME_DEX     : Intratympanic dexamethasone middle-ear depot (mg)
PERI_DEX   : Perilymph dexamethasone concentration compartment (mg)
GR_DEX     : Active glucocorticoid genomic signal, inner ear (arbitrary units)
ME_GENT    : Intratympanic gentamicin middle-ear depot (mg)
PERI_GENT  : Perilymph gentamicin concentration compartment (mg)
HYDROPS    : Endolymphatic hydrops index (1.0 = baseline mild hydrops)
KINTOX     : Perilymph K+-intoxication index (transient, episodic)
OHC        : Cochlear outer hair-cell viability (1.0 = fully intact)
VEST       : Vestibular hair-cell viability (1.0 = fully intact)
VERTFREQ   : Vertigo attack-frequency state (spells/month, turnover-smoothed)
COMP       : Central vestibular compensation index (0 = none, higher = better adapted)
DHI        : Dizziness Handicap Inventory (0-100)

[MAIN]
GUT_BETA_0 = 0; CEN_BETA_0 = 0; MET_BETA_0 = 0;
GUT_DIUR_0 = 0; CEN_DIUR_0 = 0;
ME_DEX_0   = 0; PERI_DEX_0 = 0; GR_DEX_0 = 0;
ME_GENT_0  = 0; PERI_GENT_0 = 0;

double stage_mult = 1.0 + K_STAGE_HYDR*(STAGE0 - 1.0);
HYDROPS_0 = HYDROPS0 * stage_mult;
KINTOX_0  = 0;
OHC_0     = 1.0 - 0.12*(STAGE0 - 1.0) - 0.03*DURATION_YR;
if (OHC_0 < 0.05) OHC_0 = 0.05;
VEST_0    = 1.0 - 0.08*(STAGE0 - 1.0) - 0.02*DURATION_YR;
if (VEST_0 < 0.05) VEST_0 = 0.05;
VERTFREQ_0 = 2.0 + 1.2*(STAGE0 - 1.0);
COMP_0     = 0.10 + 0.05*DURATION_YR;
if (COMP_0 > 1.0) COMP_0 = 1.0;
DHI_0      = 20 + 8*(STAGE0 - 1.0);

double PTA0_stage = 20 + 20*(STAGE0 - 1.0);   // AAO-HNS 4-tone PTA staging anchor (approx midpoints)

[ODE]
// ---------- Betahistine PK ----------
double CBETA = CEN_BETA / V_BETA;
dxdt_GUT_BETA = -KA_BETA*GUT_BETA;
dxdt_CEN_BETA =  F_BETA*KA_BETA*GUT_BETA - (CL_BETA/V_BETA)*CEN_BETA - KA_MET*CEN_BETA;
dxdt_MET_BETA =  KA_MET*CEN_BETA - KE_MET*MET_BETA;
double CMET = MET_BETA;  // arbitrary metabolite-pool "concentration" surrogate (ng/mL-equivalent)

// ---------- Diuretic PK (lumped) ----------
double CDIUR = CEN_DIUR / V_DIUR;
dxdt_GUT_DIUR = -KA_DIUR*GUT_DIUR;
dxdt_CEN_DIUR =  F_DIUR*KA_DIUR*GUT_DIUR - (CL_DIUR/V_DIUR)*CEN_DIUR;

// ---------- Intratympanic dexamethasone PK ----------
dxdt_ME_DEX   = -KMEDEX*ME_DEX;
dxdt_PERI_DEX =  KMEDEX*ME_DEX/V_PERI_DEX - KPERI_OUT_DEX*PERI_DEX;
double GR_target = EC50_DEX_GR>0 ? PERI_DEX/(EC50_DEX_GR + PERI_DEX) : 0;
dxdt_GR_DEX   = KOUT_GRDEX*(GR_target - GR_DEX);

// ---------- Intratympanic gentamicin PK ----------
dxdt_ME_GENT   = -KMEGENT*ME_GENT;
dxdt_PERI_GENT =  KMEGENT*ME_GENT/V_PERI_GENT - KPERI_OUT_GENT*PERI_GENT;

// ---------- Drug effect fractions ----------
double beta_comp_fx = EMAX_BETA_COMP * CMET/(EC50_BETA_CBF + CMET);
double beta_hydr_fx = EMAX_BETA_HYDR * CMET/(EC50_BETA_CBF + CMET);
double diur_hydr_fx = EMAX_DIUR_HYDR * CDIUR/(EC50_DIUR + CDIUR);
double dex_antiinflam_fx = EMAX_DEX_ANTIINFLAM * GR_DEX;
double dex_hydr_fx  = EMAX_DEX_HYDR * GR_DEX;

// ---------- Endolymphatic hydrops ----------
// Production scaled by baseline stage severity (stage_mult, fixed at t=0 in $MAIN);
// resorption is first-order, and drugs act by suppressing production (betahistine,
// diuretic) or improving resorption (intratympanic dexamethasone, folded into the
// combined production-suppression term below for simplicity).
double hydr_in = KIN_HYDROPS * stage_mult * (1.0 - beta_hydr_fx) * (1.0 - diur_hydr_fx) * (1.0 - dex_hydr_fx);
dxdt_HYDROPS = hydr_in - KOUT_HYDROPS*HYDROPS;

// ---------- Episodic Reissner's-membrane rupture -> K+ intoxication ----------
double hydr_pow   = pow(HYDROPS, HILL_RUPT);
double hydr50_pow = pow(HYDROPS_RUPT50, HILL_RUPT);
double rupture_rate = KRUPTURE_BASE * hydr_pow/(hydr50_pow + hydr_pow) * (1.0 - 0.5*dex_antiinflam_fx);
dxdt_KINTOX = KIN_KINTOX_PER_RUPT*rupture_rate - KOUT_KINTOX*KINTOX;

// ---------- Cochlear (OHC) viability ----------
dxdt_OHC = -( KOUT_OHC + K_KINTOX_OHC*KINTOX*(1.0 - dex_antiinflam_fx) )*OHC
           - KKILL_COCH_MAX*(PERI_GENT/(EC50_GENT_COCHTOX+PERI_GENT))*OHC
           + KREGEN_OHC*(1.0 - OHC);

// ---------- Vestibular hair-cell viability ----------
dxdt_VEST = -( KOUT_VEST + K_KINTOX_VEST*KINTOX*(1.0 - dex_antiinflam_fx) )*VEST
            - KKILL_VEST_MAX*(PERI_GENT/(EC50_GENT_VESTKILL+PERI_GENT))*VEST
            + KREGEN_VEST*(1.0 - VEST);

// ---------- Vertigo attack-frequency state (turnover toward mechanistic target) ----------
double vert_target = W_HYDR_VERT*(HYDROPS-1.0) + W_KINTOX_VERT*KINTOX + W_VEST_VERT*(1.0-VEST) - 10.0*COMP;
if (vert_target < 0) vert_target = 0;
if (vert_target > VERTFREQ_MAX) vert_target = VERTFREQ_MAX;
dxdt_VERTFREQ = (vert_target - VERTFREQ) / TAU_VERTFREQ;

// ---------- Central vestibular compensation ----------
dxdt_COMP = KIN_COMP*(1.0 + beta_comp_fx) - KOUT_COMP*COMP - K_ATTACK_DECOMP*0.001*VERTFREQ*COMP;

// ---------- Dizziness Handicap Inventory (turnover toward target) ----------
double tumarkin_flag = (VEST < TUMARKIN_VEST_THRESH && HYDROPS > TUMARKIN_HYDR_THRESH) ? 1.0 : 0.0;
double dhi_target = 20 + W_VERT_DHI*VERTFREQ + W_TUMARKIN_DHI*tumarkin_flag + W_COMP_DHI*COMP;
if (dhi_target < 0) dhi_target = 0;
if (dhi_target > DHI_MAX) dhi_target = DHI_MAX;
dxdt_DHI = (dhi_target - DHI) / 300.0;

[TABLE]
capture conc_betahistine_parent = CBETA;
capture conc_betahistine_metabolite = CMET;
capture conc_diuretic      = CDIUR;
capture peri_dexamethasone = PERI_DEX;
capture GR_signal_dex      = GR_DEX;
capture peri_gentamicin    = PERI_GENT;
capture Hydrops_idx        = HYDROPS;
capture Kintox_idx         = KINTOX;
capture OHC_viability      = OHC;
capture Vestibular_viability = VEST;
capture VertigoFreq_permo  = VERTFREQ;
capture Compensation_idx   = COMP;
double pta_db = PTA0_stage + K_OHC_PTA*(1.0-OHC);
if (pta_db < 0) pta_db = 0;
capture PTA_dB = pta_db;
double tinnitus = TINN0 + K_OHC_TINN*(1.0-OHC);
if (tinnitus > 10) tinnitus = 10;
capture Tinnitus_severity = tinnitus;
capture DHI_score = DHI;
double spap = SPAP0 + K_HYDR_SPAP*(HYDROPS - 1.0);
if (spap < 0.1) spap = 0.1;
capture ECoG_SPAP_ratio = spap;
double tumark = (VEST < TUMARKIN_VEST_THRESH && HYDROPS > TUMARKIN_HYDR_THRESH) ? 1 : 0;
capture Tumarkin_risk_flag = tumark;
double aaohns_stage = 1;
if (pta_db > 25) aaohns_stage = 2;
if (pta_db > 40) aaohns_stage = 3;
if (pta_db > 70) aaohns_stage = 4;
capture AAOHNS_stage_current = aaohns_stage;
double qol = 100 - 0.8*DHI - 3.0*tinnitus;
if (qol < 0) qol = 0; if (qol > 100) qol = 100;
capture QoL_score = qol;

[CAPTURE]
conc_betahistine_parent conc_betahistine_metabolite conc_diuretic peri_dexamethasone
GR_signal_dex peri_gentamicin Hydrops_idx Kintox_idx OHC_viability Vestibular_viability
VertigoFreq_permo Compensation_idx PTA_dB Tinnitus_severity DHI_score ECoG_SPAP_ratio
Tumarkin_risk_flag AAOHNS_stage_current QoL_score

##  ============================================================================
##  R-side scenario helpers (parsed by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("med_mrgsolve_model.R")
##
##  # ---------- 8 prebuilt scenarios (end_h = simulation horizon, hours) ----------
##
##  MED_simulate_scenarios <- function(end_h = 8760) {
##
##    sc <- list(
##      "1. Untreated natural history (moderate MD, stage II)" =
##        ev(amt=0, cmt="GUT_BETA", time=0),
##
##      "2. Betahistine standard-dose (16mg TID)" =
##        ev(amt=16, cmt="GUT_BETA", ii=8, addl=999),
##
##      "3. Betahistine high-dose (48mg TID, BEMED regimen)" =
##        ev(amt=48, cmt="GUT_BETA", ii=8, addl=999),
##
##      "4. Diuretic (HCTZ 25mg + triamterene 50mg, once daily)" =
##        ev(amt=25, cmt="GUT_DIUR", ii=24, addl=999),
##
##      "5. Intratympanic dexamethasone series (4mg/mL, weekly x4)" =
##        ev(amt=4, cmt="ME_DEX", ii=168, addl=3),
##
##      "6. Low-dose intratympanic gentamicin titration (26.7mg/mL, monthly, symptom-guided)" =
##        ev(amt=10, cmt="ME_GENT", ii=720, addl=2),
##
##      "7. High-dose intratympanic gentamicin fixed protocol (destructive, 2x/week x2wk)" =
##        ev(amt=26.7, cmt="ME_GENT", ii=84, addl=3),
##
##      "8. Combination: betahistine high-dose + diuretic" =
##        seq(ev(amt=48, cmt="GUT_BETA", ii=8, addl=999),
##            ev(amt=25, cmt="GUT_DIUR", ii=24, addl=999))
##    )
##
##    purrr::imap_dfr(sc, function(e, lab) {
##      mod %>% mrgsim(e, end=end_h, delta=6) %>%
##        as_tibble() %>% mutate(scenario=lab)
##    })
##  }
##
##  # ---------- Calibration anchors ----------
##  # Betahistine (Nauta 2014 Eur Arch Otorhinolaryngol meta-analysis): modest
##  #   overall reduction in vertigo frequency/severity across pooled small
##  #   RCTs, substantial heterogeneity; BEMED trial (Adrion 2016 BMJ,
##  #   PMID 27075667) - high-dose betahistine (48mg TID x9mo) showed NO
##  #   significant superiority over placebo on definitive vertigo-day rate in
##  #   a well-powered double-blind RCT - captured here via a deliberately
##  #   small EMAX_BETA_COMP/EMAX_BETA_HYDR effect size (mechanistic plausibility
##  #   via cochlear blood flow / vestibular compensation, but limited RCT-
##  #   confirmed magnitude on hard endpoints).
##  # Diuretics (James AL, Burton MJ. Cochrane Database Syst Rev 2001; Thirlwall
##  #   AS, Kundu S. Cochrane Database Syst Rev 2006) - long-standing clinical
##  #   use but limited/low-quality RCT evidence; modeled with a modest
##  #   EMAX_DIUR_HYDR effect reflecting plausible-but-unproven fluid benefit.
##  # Intratympanic steroids (Phillips JS, Westerberg B. Cochrane Database Syst
##  #   Rev 2011;(7):CD008514) - some evidence for short/medium-term vertigo
##  #   control, generally favorable safety profile vs gentamicin (no hearing-
##  #   loss risk) - modeled via dex_antiinflam_fx reducing rupture rate and
##  #   K+-intoxication-driven hair-cell injury.
##  # Intratympanic gentamicin (Patel M, et al. Lancet 2016;388(10061):2753-2762,
##  #   PMID 27544377 - low-dose titration vs single high fixed dose: equivalent
##  #   vertigo control at 18mo, low-dose trend toward less hearing loss; Postema
##  #   RJ, et al. Acta Otolaryngol 2008;128(8):876-880 and Boleas-Aguirre MS, et
##  #   al. Arch Otolaryngol Head Neck Surg 2008;134(4):289-295 - titration
##  #   protocol outcomes) - captured via KUP_VEST >> KUP_COCH selectivity and
##  #   two dosing-intensity scenarios (titration vs fixed high-dose) producing
##  #   similar vestibular ablation but divergent OHC/PTA trajectories.
##  # AAO-HNS 1995 diagnostic/staging criteria (Committee on Hearing and
##  #   Equilibrium. Otolaryngol Head Neck Surg 1995;113(3):181-185) - 4-tone
##  #   PTA average staging I-IV anchors the PTA_dB -> AAOHNS_stage_current
##  #   mapping; Basura GJ, et al. Otolaryngol Head Neck Surg
##  #   2020;162(4):415-434 (AAO-HNS Clinical Practice Guideline) informs the
##  #   overall treatment-ladder structure (dietary/behavioral -> betahistine/
##  #   diuretic -> intratympanic steroid -> intratympanic gentamicin/surgery).
##
##  # ---------- Quick sanity plots ----------
##  # df <- MED_simulate_scenarios(8760)
##  # ggplot(df, aes(time/730, VertigoFreq_permo, colour=scenario)) + geom_line() + xlab("month")
##  # ggplot(df, aes(time/730, PTA_dB, colour=scenario)) + geom_line() + xlab("month")
##  # ggplot(df, aes(time/730, DHI_score, colour=scenario)) + geom_line() + xlab("month")
