## ============================================================================
##  Urea Cycle Disorders (UCD) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Inherited block of hepatic ureagenesis. The index defect modelled
##             here is ORNITHINE TRANSCARBAMYLASE (OTC) DEFICIENCY — X-linked,
##             the commonest UCD — but the same structure covers CPS1, NAGS,
##             ASS1, ASL and ARG1 deficiency through the activity parameters
##             (OTCACT, CPS1A, NAGSA, DISTALA, ARG1A).
##
##             Physiology in one paragraph. Waste nitrogen from dietary protein
##             and from endogenous proteolysis reaches the periportal hepatocyte
##             as ammonia. The only route by which the body can dispose of that
##             nitrogen in bulk is the urea cycle: NAG-activated CPS1 makes
##             carbamoyl phosphate, OTC condenses it with ornithine to
##             citrulline, and the cytosolic arm (ASS1 -> ASL -> ARG1) adds a
##             second nitrogen from aspartate and releases urea. Block any step
##             and nitrogen backs up. The body's response is not to accumulate
##             ammonia linearly but to BUFFER it as glutamine (glutamine
##             synthetase, mostly skeletal muscle, ~300 umol/kg/h of flux). That
##             buffer is why plasma glutamine rises BEFORE ammonia does, and why
##             glutamine is the early-warning biomarker. It is also why the
##             disease is a cliff rather than a slope: while the buffer holds,
##             the patient looks well; when the nitrogen load exceeds residual
##             ureagenic capacity for long enough, ammonia rises steeply.
##
##             The lethal organ is the brain, and the mechanism is osmotic.
##             Astrocytes are the only CNS cells with glutamine synthetase, so
##             blood-borne ammonia is trapped there as glutamine. Glutamine is
##             an osmolyte; the astrocyte defends its volume by extruding
##             myo-inositol. In CHRONIC hyperammonaemia myo-inositol is already
##             spent — which is exactly why a chronically-elevated patient
##             decompensates catastrophically on a trigger that a naive brain
##             would tolerate. This model reproduces that interaction explicitly
##             (MINSB compartment), because it is the single most important
##             non-obvious behaviour in UCD.
##
##  Pharmacology modelled
##             * Sodium phenylbutyrate (NaPBA) and glycerol phenylbutyrate (GPB,
##               Ravicti/HPN-100): prodrugs -> PBA -> (beta-oxidation) ->
##               PHENYLACETATE -> conjugated with GLUTAMINE by GLYATL1 ->
##               PHENYLACETYLGLUTAMINE, excreted by OAT1/3. Two nitrogens per
##               molecule. GPB's slow lipase-dependent release is modelled as a
##               separate hydrolysis step, which is what produces its lower
##               Cmax, flatter 24-h profile and better overnight ammonia control.
##             * Sodium benzoate (and IV Na-phenylacetate/Na-benzoate, Ammonul):
##               benzoyl-CoA + GLYCINE -> hippurate. One nitrogen per molecule.
##             * Carglumic acid (N-carbamylglutamate): stable NAG analogue that
##               allosterically activates CPS1 — curative in NAGS deficiency.
##             * L-citrulline: bypasses the OTC block, adding an OTC-INDEPENDENT
##               nitrogen sink through ASS1 (one aspartate nitrogen per
##               citrulline) and regenerating ornithine.
##             * L-arginine HCl: substrate replacement + allosteric NAGS
##               stimulation.
##             * Haemodialysis / CVVHDF: direct ammonia clearance, with the
##               post-dialysis REBOUND that comes from re-equilibration of the
##               deep tissue glutamine reservoir (GLNM compartment).
##             * AAV8-OTC gene transfer (DTX301) and OTC mRNA-LNP (ARCT-810):
##               transgene template -> transgene-derived OTC activity.
##             * Liver transplantation: step restoration of ureagenic capacity.
##
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>= 1.0; developed and run against 2.0.1)
##
##  Scope    : 35 ODE compartments (see $CMT).
##  Time     : HOURS. Default horizons: 72 h for crises, 8760 h (1 y) for
##             chronic scenarios.
##  Units    : amounts umol · concentrations umol/L · nitrogen fluxes umol N/h ·
##             brain glutamine and myo-inositol reported in mmol/L · brain water
##             excess in % · ICP mmHg · drug doses entered in umol (helper
##             functions convert from g / mg/kg / mL).
##
##  SELF-CALIBRATING BASELINE
##  -------------------------
##  Nothing is hard-coded as an initial condition. From the patient descriptors
##  (WT, OTCACT, PROT, CPS1A, NAGSA, ARGBASE, CITBASE, ...) [$MAIN] solves the
##  untreated steady state ANALYTICALLY and sets every compartment to it:
##
##    N load        RA_N  = FDISP * PROT * WT * 11430 / 24            umol N/h
##    ureagenesis   V     = A * C / (KMNH4 + C),  A = UCAP*WT*ACT*fNAG*fORN
##    other N loss  (CLNH4R + CLRGLN*RATIO) * C                       [linear]
##    =>  CLReff*C^2 + (A + CLReff*KMNH4 - RA_N)*C - RA_N*KMNH4 = 0
##
##  which is solved with the positive root. Glutamine, brain ammonia, brain
##  glutamine, myo-inositol, brain water, ornithine, orotate, glycine and BCAA
##  all follow in closed form from that root, and every production constant is
##  back-calculated so the untreated arm is EXACTLY stationary. Change the
##  patient and the model still starts in balance — so any drift you see in a
##  simulation is mechanism, not bookkeeping.
##
##  KEY CALIBRATION ANCHORS (see ucd_references.md for the full list)
##  -----------------------------------------------------------------
##   * Maximal ureagenesis capacity ~4-5x the habitual nitrogen load in healthy
##     adults; healthy operating point ~20% of Vmax at ammonia 30 umol/L.
##     -> UCAP = 2400 umol N/kg/h, KMNH4 = 120 umol/L reproduce both.
##   * Whole-body glutamine flux ~300 umol/kg/h (Darmaun 1986 Am J Physiol) and
##     the clinically observed plasma Gln:NH3 ratio of ~20-22 in normals and in
##     UCD -> KGS = 700 L/h, (KGLNASE + CLRGLN) = 32.3 L/h for a 70 kg adult.
##   * Renal glutamine-derived ammoniagenesis disposes ~30-50 mmol N/day
##     -> CLRGLN = 1.924 L/h.
##   * NaPBA 20 g/day == GPB 17.5 mL/day == ~107-109 mmol PBA/day; urinary PAGN
##     recovery ~60-75% of administered PBA (Monteleone 2013; Diaz 2013)
##     -> VMPAGN = 115 umol/kg/h, KMPAA = 300, KMGLNP = 400 give 70%.
##   * Diaz 2013 Hepatology 57:2171 (GPB vs NaPBA crossover): equivalent 24-h
##     ammonia AUC with LOWER Cmax and better overnight/early-morning control —
##     reproduced by scenarios 3 vs 4.
##   * PAA neurotoxicity threshold ~500 ug/mL and the PAA:PAGN ratio >2.5
##     (ug/mL basis) as the marker of saturated conjugation (Mokhtarani 2013).
##   * Msall 1984 NEJM 310:1500 / Bachmann 2003: duration of neonatal
##     hyperammonaemic coma is the dominant predictor of later IQ -> the NEURO
##     injury integrator is driven by ammonia x time x brain water.
##   * Haemodialysis ammonia clearance far exceeds any pharmacological route;
##     ammonia >360-500 umol/L is a dialysis indication (Haberle 2019 revised
##     European guideline) -> scenario 9.
##   * Brain glutamine rises from ~5 mM to ~15-20 mM with reciprocal
##     myo-inositol depletion on 1H-MRS (Connelly 1993; Gropman 2008).
##
##  IMPORTANT: this is an educational / exploratory QSP model. It is not
##  validated for clinical decision-making, dose selection or regulatory use.
## ============================================================================

suppressPackageStartupMessages({
  library(mrgsolve)
})

ucd_code <- '
$PROB
# Urea Cycle Disorders (OTC deficiency index) — QSP model
- 35 compartments; nitrogen-balance core with astrocytic osmolyte CNS module
- Scavenger, cycle-substrate, dialysis and gene-therapy pharmacology

$PARAM @annotated
// ---------------- patient ------------------------------------------------
WT      :  70    : Body weight (kg)
BSA     :  1.80  : Body surface area (m2, for scavenger dosing helpers)
AGEY    :  28    : Age (years, descriptive)
ALLOM   :   0.75 : Allometric exponent for clearances
VBR     :   1.35 : Brain volume (L)

// ---------------- genotype / residual enzyme activity --------------------
OTCACT  :   0.32 : Residual OTC activity (fraction of normal)
CPS1A   :   1.00 : CPS1 activity (fraction; <1 for CPS1 deficiency)
NAGSA   :   1.00 : NAGS activity (fraction; ~0 for NAGS deficiency)
DISTALA :   1.00 : Distal-arm (ASS1/ASL/ARG1) activity (fraction)
ACTX    :  -1    : Post-transplant total ureagenic activity (<0 = no transplant)
TTX     :  1e9   : Time of liver transplantation (h)

// ---------------- nitrogen load ------------------------------------------
PROT    :   0.50 : Natural protein intake (g/kg/day)
PROT2   :  -1    : Protein intake after TPROT (g/kg/day; <0 = unchanged)
TPROT   :  1e9   : Time of the first protein-intake change (h)
PROT3   :  -1    : Protein intake after TPROT3 (g/kg/day; <0 = unchanged)
TPROT3  :  1e9   : Time of the second protein-intake change (h)
FDISP   :   0.85 : Fraction of dietary N requiring urea-cycle disposal
FEEDTHR : 200    : Ammonia above which anorexia/vomiting suppress intake (umol/L)
FEEDSC  : 300    : Ammonia excess giving 50% suppression of intake (umol/L)
NPERG   : 11430  : umol nitrogen per gram of dietary protein
NCATKG  : 357    : Endogenous N release at full catabolic stress (umol N/kg/h)
NOBLKG  :  43    : Obligate endogenous N flux at zero protein intake (umol N/kg/h)
CATAMP  :   0    : Catabolic trigger amplitude (0-1)
CATT0   :  1e9   : Catabolic trigger start (h)
CATDUR  :  24    : Catabolic trigger duration (h)
KINCAT  :   0.35 : Catabolic state on-rate (1/h)
KOUTCAT :   0.09 : Catabolic state off-rate (1/h)
ANAB    :   0    : Anabolic rescue intensity (0-1; IV dextrose/lipid)

// ---------------- ureagenesis --------------------------------------------
UCAP    : 2400   : Maximal ureagenesis capacity (umol N/kg/h at 100% activity)
KMNH4   : 120    : Apparent Km of ureagenesis for plasma ammonia (umol/L)
KNAG    :   0.1111 : Km of CPS1 for NAG-equivalent activation (rel. units)
GARG    :   0.25 : Fractional NAGS gain per unit relative arginine excess
GNCG    :   0.020 : NAG-equivalent gain per umol/L of carglumic acid
VPAI    :   0    : Fractional NAGS inhibition by valproate (0-1)
TVPA    :  1e9   : Time valproate exposure begins (h)
KORN    :   6.67 : Km of the cycle for ornithine (umol/L)
KCITN   :   9.0  : OTC-independent N disposal per unit supplemental citrulline (L/h)

// ---------------- ammonia / glutamine handling ---------------------------
FECF    :   0.20 : ECF fraction of body weight (L/kg) — ammonia volume
FGLNC   :   0.25 : Exchangeable glutamine volume (L/kg)
FGLNM   :   0.40 : Deep tissue glutamine reservoir volume (L/kg)
VG0KG   : 184.6  : High-affinity glutamine synthetase capacity (umol/h/kg)
KG0     :   8    : Km of the high-affinity GS component for ammonia (umol/L)
KGSKG   :   3.843 : Low-affinity glutamine synthetase gain (L/h/kg)
KGSAT   : 1200   : Ammonia at which the low-affinity GS component half-saturates
KGLNKG  :   0.4336 : Glutaminase back-flux (L/h/kg)
CLRGKG  :   0.02749 : Renal glutamine-derived N excretion clearance (L/h/kg)
KEXMKG  :   0.30 : Plasma<->deep glutamine exchange clearance (L/h/kg)
CLNH4KG :   0.00714 : Direct renal plasma-ammonia clearance (L/h/kg)

// ---------------- blood-brain barrier and CNS ----------------------------
PSBBB   : 400    : BBB permeability-surface product for NH3 (L/h)
PKANH3  :   9.15 : pKa of the NH4+/NH3 couple
PHART   :   7.40 : Arterial pH at ammonia 30 umol/L
PHSLOPE :   0.03 : Rise in arterial pH per 100 umol/L of ammonia (hyperventilation)
PHMAX   :   7.60 : Ceiling on respiratory alkalosis
PHBR    :   7.05 : Intracellular brain pH (ion trapping)
VMGSB   : 892    : Astrocytic glutamine synthetase Vmax (umol/h)
KMGSB   : 500    : Astrocytic GS Km for brain ammonia (umol/L)
KOUTGB  :   0.05 : Brain glutamine efflux rate constant (1/h)
GLNBREF :   4.0  : Recycled (N-neutral) brain glutamine baseline (mmol/L)
GLNBTHR :   5.0  : Brain glutamine osmotic threshold (mmol/L)
KINMI   :   0.10 : Brain myo-inositol synthesis/uptake (mmol/L/h)
KOUTMI  :   0.02 : Brain myo-inositol turnover (1/h)
KEXTMI  :   0.02 : Myo-inositol extrusion per mmol/L of excess brain glutamine (1/h)
MIREF   :   5.0  : Normal brain myo-inositol (mmol/L)
FCOMP   :   0.60 : Maximal fraction of the glutamine osmotic load an osmolyte can offset
KBWIN   :   0.04138 : Brain-water gain per mmol/L of net osmolyte excess (%/mmol/L/h)
KBWOUT  :   0.15 : Brain-water equilibration rate (1/h)
ICP0    :  10    : Baseline intracranial pressure (mmHg)
KICP    :   0.90 : ICP exponential gain per % brain water

// ---------------- injury / outcome integrators ---------------------------
NH3THR  : 150    : Ammonia above which cumulative neuro-injury accrues (umol/L)
KINJ    :   0.10 : Neuro-injury accrual gain (1/h per 100 umol/L excess)
COMATHR : 200    : Ammonia defining coma-range exposure (umol/L)
IQMAX   : 100    : Ceiling of the modelled full-scale IQ
IQDROP  :  45    : Maximal modelled IQ decrement
IQ50    :  50    : Injury index producing half-maximal IQ decrement

// ---------------- phenylbutyrate axis PK ---------------------------------
KHYDG   :   0.30 : GPB pancreatic-lipase hydrolysis rate constant (1/h)
KAPBA   :   2.00 : PBA absorption rate constant (1/h)
FPBA    :   0.95 : PBA oral bioavailability
FVPBA   :   0.20 : PBA volume of distribution (L/kg)
CLPBA   :  12.1  : PBA clearance (L/h) — beta-oxidation dominated
FMPAA   :   0.85 : Fraction of PBA clearance forming phenylacetate
FVPAA   :   0.35 : PAA volume of distribution (L/kg)
CLPAA   :   3.11 : Non-conjugative PAA clearance (L/h)
VMPKG   : 115    : GLYATL1 Vmax for PAGN formation (umol/kg/h)
KMPAA   : 300    : GLYATL1 Km for phenylacetate (umol/L)
KMGLNP  : 400    : GLYATL1 Km for glutamine (umol/L)
FVPGN   :   0.25 : PAGN volume of distribution (L/kg)
CLPGN   :  12.0  : PAGN renal clearance (L/h)

// ---------------- benzoate axis PK ---------------------------------------
KABZ    :   2.50 : Benzoate absorption rate constant (1/h)
FBZ     :   0.95 : Benzoate oral bioavailability
FVBZ    :   0.20 : Benzoate volume of distribution (L/kg)
CLBZ    :   2.00 : Non-conjugative benzoate clearance (L/h)
VMHKG   :  90    : GLYAT Vmax for hippurate formation (umol/kg/h)
KMBZ    : 250    : GLYAT Km for benzoate (umol/L)
KMGLY   : 200    : GLYAT Km for glycine (umol/L)
FVHIP   :   0.25 : Hippurate volume of distribution (L/kg)
CLHIP   :  20.0  : Hippurate renal clearance (L/h)

// ---------------- cycle substrates and activators PK ---------------------
KACIT   :   1.50 : Citrulline absorption rate constant (1/h)
FCIT    :   0.85 : Citrulline oral bioavailability
FVCIT   :   0.30 : Citrulline volume of distribution (L/kg)
CLCIT   :   8.00 : Citrulline clearance (L/h)
CITBASE :  12    : Baseline plasma citrulline (umol/L; low in OTC/CPS1)
KAARG   :   1.20 : Arginine absorption rate constant (1/h)
FARG    :   0.70 : Arginine oral bioavailability
FVARG   :   0.30 : Arginine volume of distribution (L/kg)
CLARG   :  25.0  : Arginine clearance (L/h)
ARGBASE :  60    : Baseline plasma arginine (umol/L)
KANCG   :   0.80 : Carglumic acid absorption rate constant (1/h)
FNCG    :   0.30 : Carglumic acid oral bioavailability
FVNCG   :   2.30 : Carglumic acid volume of distribution (L/kg)
CLNCG   :  19.9  : Carglumic acid clearance (L/h)

// ---------------- ornithine, glycine, BCAA, orotate ----------------------
ORNBASE :  60    : Baseline hepatic ornithine pool concentration (umol/L)
FVORN   :   0.30 : Ornithine distribution volume (L/kg)
KOUTORN :   0.50 : Ornithine turnover (1/h)
KARGORN :   0.006 : Ornithine generation per umol/L of plasma arginine (1/h)
GLYBASE : 250    : Baseline plasma glycine (umol/L)
FVGLY   :   0.35 : Glycine distribution volume (L/kg)
CLGLY   :  60.0  : Glycine turnover clearance (L/h)
BCABASE : 380    : Baseline plasma branched-chain amino acids (umol/L)
FVBCA   :   0.35 : BCAA distribution volume (L/kg)
CLBCA   :   9.0  : BCAA turnover clearance (L/h)
KBPAA   :   0.9  : BCAA depletion per umol/L of plasma PAA (umol/h per umol/L)
KCPOVR  :   0.55 : Carbamoyl-phosphate overflow gain
KOROT   :   0.030 : Orotate formation per unit CP overflow
KOUTOR  :   0.35 : Orotate elimination rate constant (1/h)

// ---------------- extracorporeal and genetic therapy ---------------------
CLHD    :   0    : Extracorporeal ammonia clearance while running (L/h)
FHDGLN  :   0.70 : Glutamine clearance as a fraction of CLHD
HDT0    :  1e9   : Dialysis start (h)
HDDUR   :   6    : Dialysis duration (h)
KTRANS  :   0.0005 : Transgene template loss rate (1/h; AAV episome ~ 0)
KEXPR   :   0.0020 : OTC activity expressed per unit template per hour
KDEGOTC :   0.010 : Turnover of transgene-derived OTC activity (1/h)
OTCXMAX :   0.60 : Ceiling on transgene-derived OTC activity (fraction of normal)

$CMT @annotated
GPBG   : Glycerol phenylbutyrate in gut, as PBA-equivalents (umol)
PBAG   : Phenylbutyrate available for absorption (umol)
PBAC   : Phenylbutyrate, central (umol)
PAAC   : Phenylacetate, central (umol)
PGNC   : Phenylacetylglutamine, central (umol)
PGNU   : Phenylacetylglutamine excreted, cumulative (umol)
BZG    : Benzoate in gut (umol)
BZC    : Benzoate, central (umol)
HIPC   : Hippurate, central (umol)
HIPU   : Hippurate excreted, cumulative (umol)
CITG   : Citrulline in gut (umol)
CITC   : Citrulline, central (umol)
ARGG   : Arginine in gut (umol)
ARGC   : Arginine, central (umol)
NCGG   : Carglumic acid in gut (umol)
NCGC   : Carglumic acid, central (umol)
NH4C   : Ammonia, extracellular pool (umol)
NH4B   : Ammonia, brain (umol)
GLNC   : Glutamine, exchangeable pool (umol)
GLNM   : Glutamine, deep tissue reservoir (umol)
GLNB   : Brain glutamine derived de novo from blood ammonia (umol)
MINSB  : Brain myo-inositol (umol)
BRWAT  : Brain water excess (%)
ORNP   : Ornithine pool (umol)
GLYP   : Glycine pool (umol)
BCAAP  : Branched-chain amino-acid pool (umol)
OROTP  : Orotic acid pool (umol)
TRANSG : Transgene template, AAV episome or LNP-mRNA (arbitrary units)
OTCX   : Transgene-derived OTC activity (fraction of normal)
CATB   : Catabolic state (0-1)
NAUC   : Cumulative ammonia AUC above 100 umol/L (umol/L*h)
COMAH  : Cumulative hours with ammonia above COMATHR (h)
NEURO  : Cumulative neuro-injury index (dimensionless)
PAATOX : Cumulative phenylacetate exposure above 500 ug/mL (ug/mL*h)
UREAX  : Cumulative urea nitrogen produced (umol N)

$GLOBAL
#define CNH4  (NH4C/VECF)
#define CNH4B (NH4B/VBR)
#define CGLNC (GLNC/VGLNC)
#define CGLNM (GLNM/VGLNM)
#define CPAA  (PAAC/VPAA)
#define CPGN  (PGNC/VPGN)
#define CPBA  (PBAC/VPBA)
#define CBZ   (BZC/VBZ)
#define CHIP  (HIPC/VHIP)
#define CCIT  (CITC/VCIT)
#define CARG  (ARGC/VARG)
#define CNCG  (NCGC/VNCG)
#define CORN  (ORNP/VORN)
#define CGLY  (GLYP/VGLY)
#define CBCA  (BCAAP/VBCA)

// distribution volumes and back-calculated production constants,
// all assigned once per individual in $MAIN
double VECF, VGLNC, VGLNM, VPAA, VPGN, VPBA, VBZ, VHIP, VCIT, VARG, VNCG;
double VORN, VGLY, VBCA;
double KGS, VG0, KGLNASE, CLRGLN, KEXM, CLNH4R, VMPAGN, VMHIP;
double A_UC, FNAG0, FORN0, C0, GLN0C, RA_N0, VUREA0, CB0, GLNB0, MI0, OSM0;
double KINORN, KINCIT, KINARG, KINGLY, KINBCA, CPOVER0;
double NH3F0, ASCL, PSB, VMGS, NOBL, NCATA, GDENOM;

// Whole-body glutamine synthesis as a function of plasma ammonia. Two
// components, BOTH proportional to ammonia at low concentration so that no
// scenario can drive the free-nitrogen pool negative:
//   * a high-affinity, near-saturated term  -> the ~400 umol/L glutamine floor
//   * a low-affinity, ammonia-driven term   -> the rise of glutamine in UCD
double ucd_vgs(double C, double vg0, double kg0, double kgs, double ksat) {
  if(C < 0.0) C = 0.0;
  return vg0*C/(kg0 + C) + kgs*C/(1.0 + C/ksat);
}

// Anorexia, vomiting and obtundation: a hyperammonaemic patient stops eating.
// Without this negative feedback an untreated severe defect integrates its
// nitrogen load without bound; with it, ammonia plateaus in the range actually
// seen in decompensation. Protein aversion is also the classic history in
// late-onset disease, so the same term carries a real clinical sign.
double ucd_feed(double C, double thr, double sc) {
  double e = C - thr;
  if(e < 0.0) e = 0.0;
  return 1.0/(1.0 + (e/sc)*(e/sc));
}
double cPBA, cPAA, cPGN, cBZ, cHIP, cCIT, cARG, cNCG, cGLY, cBCA, kBPAA;

$MAIN
// ---------------------------------------------------------------- volumes
VECF  = FECF  * WT;
VGLNC = FGLNC * WT;
VGLNM = FGLNM * WT;
VPBA  = FVPBA * WT;
VPAA  = FVPAA * WT;
VPGN  = FVPGN * WT;
VBZ   = FVBZ  * WT;
VHIP  = FVHIP * WT;
VCIT  = FVCIT * WT;
VARG  = FVARG * WT;
VNCG  = FVNCG * WT;
VORN  = FVORN * WT;
VGLY  = FVGLY * WT;
VBCA  = FVBCA * WT;

// ------------------------------------------------- weight-scaled kinetics
ASCL    = pow(WT/70.0, ALLOM);         // allometric clearance scaling
KGS     = KGSKG   * WT;   // L/h
VG0     = VG0KG   * WT;   // umol/h
KGLNASE = KGLNKG  * WT;   // L/h
CLRGLN  = CLRGKG  * WT;   // L/h
KEXM    = KEXMKG  * WT;   // L/h
CLNH4R  = CLNH4KG * WT;   // L/h
VMPAGN  = VMPKG   * WT;   // umol/h
VMHIP   = VMHKG   * WT;   // umol/h
NOBL    = NOBLKG  * WT;   // umol N/h
NCATA   = NCATKG  * WT;   // umol N/h

// brain-size scaling of the astrocytic module
PSB  = PSBBB * (VBR/1.35);
VMGS = VMGSB * (VBR/1.35);

// allometrically scaled drug and amino-acid clearances
cPBA = CLPBA*ASCL; cPAA = CLPAA*ASCL; cPGN = CLPGN*ASCL;
cBZ  = CLBZ *ASCL; cHIP = CLHIP*ASCL; cCIT = CLCIT*ASCL;
cARG = CLARG*ASCL; cNCG = CLNCG*ASCL; cGLY = CLGLY*ASCL;
cBCA = CLBCA*ASCL; kBPAA = KBPAA*ASCL;

// At steady state plasma glutamine is  vgs(NH3)/(KGLNASE + CLRGLN):
// ~600 umol/L at an ammonia of 34, ~890 at 65, and several thousand in a
// neonatal crisis — the observed relationship, and the reason glutamine is
// the early-warning biomarker in this model.
GDENOM = KGLNASE + CLRGLN;

// ------------------------------------------------- baseline activation terms
FNAG0 = NAGSA / (KNAG + NAGSA);
FORN0 = ORNBASE / (KORN + ORNBASE);

double ACTB = OTCACT;
if(CPS1A  < ACTB) ACTB = CPS1A;      // the slowest step sets the flux
if(DISTALA< ACTB) ACTB = DISTALA;
A_UC = UCAP * WT * ACTB * FNAG0 * FORN0;

// ------------------------------------------------------- baseline N load
RA_N0 = FDISP * PROT * WT * NPERG / 24.0 + NOBL;

// ------------- untreated steady state, solved by bisection.
//   RA_N = A*C/(KM+C) + CLNH4R*C + CLRGLN*vgs(C)/(KGLNASE+CLRGLN)
// The right-hand side is strictly increasing in C, so 60 bisections on
// [1e-6, 1e6] umol/L give the root to machine-useful precision. Every other
// initial condition follows from it in closed form, which is what makes the
// untreated arm exactly stationary for ANY patient descriptor set.
double lo = 1e-6;
double hi = 1e6;
double mid = 0.0;
for(int i = 0; i < 60; i++) {
  mid = 0.5*(lo + hi);
  double ran = FDISP*PROT*WT*NPERG/24.0 * ucd_feed(mid, FEEDTHR, FEEDSC) + NOBL;
  double fv = A_UC*mid/(KMNH4 + mid) + CLNH4R*mid
              + CLRGLN*ucd_vgs(mid, VG0, KG0, KGS, KGSAT)/GDENOM - ran;
  if(fv > 0.0) hi = mid; else lo = mid;
}
C0 = mid;
if(C0 < 0.5) C0 = 0.5;
RA_N0 = FDISP*PROT*WT*NPERG/24.0 * ucd_feed(C0, FEEDTHR, FEEDSC) + NOBL;
GLN0C = ucd_vgs(C0, VG0, KG0, KGS, KGSAT)/GDENOM;

VUREA0 = A_UC * C0 / (KMNH4 + C0);

// ------------------------------------------------------- baseline brain
double ph0  = PHART + PHSLOPE*(C0 - 30.0)/100.0;
if(ph0 > PHMAX) ph0 = PHMAX;
NH3F0       = 1.0/(1.0 + pow(10.0, PKANH3 - ph0));
double fbr  = 1.0/(1.0 + pow(10.0, PKANH3 - PHBR));
// PSBBB*(NH3F0*C0 - fbr*CB) = VMGSB*CB/(KMGSB+CB)  ->  quadratic in CB
double aa = PSB*fbr;
double bb = PSB*fbr*KMGSB + VMGS - PSB*NH3F0*C0;
double cc = -PSB*NH3F0*C0*KMGSB;
CB0 = (-bb + sqrt(bb*bb - 4.0*aa*cc)) / (2.0*aa);
if(CB0 < 0.0) CB0 = 0.0;
double vgsb0 = VMGS * CB0/(KMGSB + CB0);
GLNB0 = vgsb0 / KOUTGB;                       // umol of de-novo brain glutamine

double glnb_mM0 = GLNBREF + GLNB0/VBR/1000.0;
double gexc0    = glnb_mM0 - GLNBTHR; if(gexc0 < 0.0) gexc0 = 0.0;
MI0  = KINMI / (KOUTMI + KEXTMI*gexc0);       // mmol/L
double comp0 = MIREF - MI0; if(comp0 < 0.0) comp0 = 0.0;
if(comp0 > FCOMP*gexc0) comp0 = FCOMP*gexc0;  // osmolyte loss can only ever
OSM0 = gexc0 - comp0;                         // offset part of the load
if(OSM0 < 0.0) OSM0 = 0.0;

// ------------------------------------------------- baseline orotate / pools
double actx0 = ACTB; if(actx0 > 1.0) actx0 = 1.0;
CPOVER0 = KCPOVR * CPS1A * FNAG0 * (C0/(KMNH4 + C0)) * (1.0 - actx0);
if(CPOVER0 < 0.0) CPOVER0 = 0.0;

KINORN = KOUTORN*ORNBASE*VORN - KARGORN*ARGBASE*VORN;
if(KINORN < 0.0) KINORN = 0.0;
KINCIT = cCIT * CITBASE;
KINARG = cARG * ARGBASE;
KINGLY = cGLY * GLYBASE;
KINBCA = cBCA * BCABASE;

// --------------------------------------------------- initial conditions
NH4C_0  = C0 * VECF;
GLNC_0  = GLN0C * VGLNC;
GLNM_0  = GLN0C * VGLNM;
NH4B_0  = CB0 * VBR;
GLNB_0  = GLNB0;
MINSB_0 = MI0 * VBR * 1000.0;
BRWAT_0 = KBWIN * OSM0 / KBWOUT;
ORNP_0  = ORNBASE * VORN;
GLYP_0  = GLYBASE * VGLY;
BCAAP_0 = BCABASE * VBCA;
CITC_0  = CITBASE * VCIT;
ARGC_0  = ARGBASE * VARG;
OROTP_0 = KOROT * CPOVER0 / KOUTOR;

$ODE
// ------------------------------------------------------- forcing functions
double sw_prot = (PROT2 < 0) ? 0.0 :
                 1.0/(1.0 + exp(-(SOLVERTIME - TPROT)/0.5));
double protnow = PROT + ((PROT2 < 0 ? PROT : PROT2) - PROT)*sw_prot;
if(PROT3 >= 0) {
  double sw3 = 1.0/(1.0 + exp(-(SOLVERTIME - TPROT3)/0.5));
  protnow = protnow + (PROT3 - protnow)*sw3;
}

double trig = 1.0/(1.0 + exp(-(SOLVERTIME - CATT0)/0.5))
            - 1.0/(1.0 + exp(-(SOLVERTIME - CATT0 - CATDUR)/0.5));

double hdon = 1.0/(1.0 + exp(-(SOLVERTIME - HDT0)/0.25))
            - 1.0/(1.0 + exp(-(SOLVERTIME - HDT0 - HDDUR)/0.25));
double clhd = CLHD * hdon;

double sw_tx = 1.0/(1.0 + exp(-(SOLVERTIME - TTX)/1.0));

// ------------------------------------------------------- catabolic state
dxdt_CATB = KINCAT*CATAMP*trig*(1.0 - CATB) - KOUTCAT*CATB;
double catnow = CATB * (1.0 - 0.70*ANAB);

// ------------------------------------------------------- nitrogen load
double feedsup = ucd_feed(CNH4, FEEDTHR, FEEDSC);
double ra_n = FDISP * protnow * WT * NPERG / 24.0 * feedsup
              + NOBL + NCATA * catnow;

// ------------------------------------------- effective ureagenic activity
double actbase = OTCACT;
if(CPS1A   < actbase) actbase = CPS1A;
if(DISTALA < actbase) actbase = DISTALA;
double otcx = OTCX; if(otcx > OTCXMAX) otcx = OTCXMAX;
double acteff = actbase + otcx;
if(ACTX >= 0) acteff = acteff + (ACTX - acteff)*sw_tx;
if(acteff > 1.0) acteff = 1.0;

// NAG-equivalent activation: endogenous NAGS (arginine-stimulated, valproate-
// inhibitable) plus any carglumic acid on board
double sw_vpa = 1.0/(1.0 + exp(-(SOLVERTIME - TVPA)/0.5));
double nagsx  = NAGSA*(1.0 - VPAI*sw_vpa);
double nagact = nagsx*(1.0 + GARG*(CARG/ARGBASE - 1.0)) + GNCG*CNCG;
if(nagact < 0.0) nagact = 0.0;
double fnag = nagact/(KNAG + nagact);
double forn = CORN/(KORN + CORN);

double vurea = UCAP*WT*acteff*fnag*forn * CNH4/(KMNH4 + CNH4);   // umol N/h

// supplemental citrulline: OTC-independent nitrogen sink through ASS1
double citex = CCIT - CITBASE; if(citex < 0.0) citex = 0.0;
double vcitn = KCITN * DISTALA * citex;                          // umol N/h

// ------------------------------------------------------- scavenger fluxes
double vpagn = VMPAGN * (CPAA/(KMPAA + CPAA)) * (CGLNC/(KMGLNP + CGLNC));
double vhip  = VMHIP  * (CBZ /(KMBZ  + CBZ )) * (CGLY /(KMGLY  + CGLY ));

// ------------------------------------------------------- BBB ammonia flux
double phart = PHART + PHSLOPE*(CNH4 - 30.0)/100.0;
if(phart > PHMAX) phart = PHMAX;
double fnh3  = 1.0/(1.0 + pow(10.0, PKANH3 - phart));
double fbrn  = 1.0/(1.0 + pow(10.0, PKANH3 - PHBR));
double jbbb  = PSB*(fnh3*CNH4 - fbrn*CNH4B);
double vgsb  = VMGS * CNH4B/(KMGSB + CNH4B);

// ======================================================================
//  PK — phenylbutyrate axis
// ======================================================================
dxdt_GPBG = -KHYDG*GPBG;
dxdt_PBAG =  KHYDG*GPBG - KAPBA*PBAG;
dxdt_PBAC =  FPBA*KAPBA*PBAG - cPBA*CPBA;
dxdt_PAAC =  FMPAA*cPBA*CPBA - cPAA*CPAA - vpagn;
dxdt_PGNC =  vpagn - cPGN*CPGN;
dxdt_PGNU =  cPGN*CPGN;

// ======================================================================
//  PK — benzoate axis
// ======================================================================
dxdt_BZG  = -KABZ*BZG;
dxdt_BZC  =  FBZ*KABZ*BZG - cBZ*CBZ - vhip;
dxdt_HIPC =  vhip - cHIP*CHIP;
dxdt_HIPU =  cHIP*CHIP;

// ======================================================================
//  PK — cycle substrates and the NAG analogue
// ======================================================================
dxdt_CITG = -KACIT*CITG;
dxdt_CITC =  FCIT*KACIT*CITG + KINCIT - cCIT*CCIT - vcitn;
dxdt_ARGG = -KAARG*ARGG;
dxdt_ARGC =  FARG*KAARG*ARGG + KINARG - cARG*CARG;
dxdt_NCGG = -KANCG*NCGG;
dxdt_NCGC =  FNCG*KANCG*NCGG - cNCG*CNCG;

// ======================================================================
//  Nitrogen balance — the core of the model
// ======================================================================
//  Glutamine carries TWO nitrogens, so glutamine synthesis debits 2 N from the
//  free pool and glutaminase credits 2 N back. Renal glutamine utilisation
//  excretes one N as urinary NH4+ and returns the other. PAGN formation
//  therefore removes a full 2 N from the body per molecule, and hippurate 1 N —
//  the stoichiometric reason phenylbutyrate is the more nitrogen-efficient
//  scavenger per mole.
//  Hippurate carries one nitrogen out of the body. That nitrogen leaves as
//  glycine, and the glycine pool is re-filled from the free amino-nitrogen
//  pool — so hippurate formation is debited directly against ammonia here
//  (the GLYP compartment tracks the transient pool depletion separately).
double vgs = ucd_vgs(CNH4, VG0, KG0, KGS, KGSAT);

dxdt_NH4C = ra_n
            - vurea
            - vcitn
            - vhip
            - 2.0*vgs
            + 2.0*KGLNASE*CGLNC
            + 1.0*CLRGLN*CGLNC
            - CLNH4R*CNH4
            - clhd*CNH4
            - jbbb
            + KOUTGB*GLNB;

dxdt_GLNC =  vgs
            - KGLNASE*CGLNC
            - CLRGLN*CGLNC
            - vpagn
            - KEXM*(CGLNC - CGLNM)
            - FHDGLN*clhd*CGLNC;

dxdt_GLNM =  KEXM*(CGLNC - CGLNM);

dxdt_UREAX = vurea;

// ======================================================================
//  CNS — astrocytic glutamine trap and osmolyte compensation
// ======================================================================
dxdt_NH4B = jbbb - vgsb;
dxdt_GLNB = vgsb - KOUTGB*GLNB;

double glnb_mM = GLNBREF + GLNB/VBR/1000.0;
double gexc    = glnb_mM - GLNBTHR; if(gexc < 0.0) gexc = 0.0;
double mi_mM   = MINSB/VBR/1000.0;

dxdt_MINSB = (KINMI - KOUTMI*mi_mM - KEXTMI*gexc*mi_mM) * VBR * 1000.0;

double micomp = MIREF - mi_mM; if(micomp < 0.0) micomp = 0.0;
if(micomp > FCOMP*gexc) micomp = FCOMP*gexc;   // partial compensation only
double osmnet = gexc - micomp; if(osmnet < 0.0) osmnet = 0.0;

dxdt_BRWAT = KBWIN*osmnet - KBWOUT*BRWAT;

// ======================================================================
//  Ancillary pools
// ======================================================================
dxdt_ORNP  = KINORN + KARGORN*CARG*VORN - KOUTORN*ORNP;
dxdt_GLYP  = KINGLY - cGLY*CGLY - vhip;
dxdt_BCAAP = KINBCA - cBCA*CBCA - kBPAA*CPAA;

double actc  = acteff; if(actc > 1.0) actc = 1.0;
double cpover = KCPOVR * CPS1A * fnag * (CNH4/(KMNH4 + CNH4)) * (1.0 - actc);
if(cpover < 0.0) cpover = 0.0;
dxdt_OROTP = KOROT*cpover - KOUTOR*OROTP;

// ======================================================================
//  Genetic therapy
// ======================================================================
dxdt_TRANSG = -KTRANS*TRANSG;
dxdt_OTCX   =  KEXPR*TRANSG - KDEGOTC*OTCX;

// ======================================================================
//  Injury / exposure integrators
// ======================================================================
double exc100 = CNH4 - 100.0; if(exc100 < 0.0) exc100 = 0.0;
dxdt_NAUC = exc100;

double sc = 1.0/(1.0 + exp(-(CNH4 - COMATHR)/10.0));
dxdt_COMAH = sc;

double excinj = CNH4 - NH3THR; if(excinj < 0.0) excinj = 0.0;
dxdt_NEURO = KINJ * (excinj/100.0) * (1.0 + 2.0*BRWAT);

double paaug = CPAA*136.15/1000.0;
double exctox = paaug - 500.0; if(exctox < 0.0) exctox = 0.0;
dxdt_PAATOX = exctox;

$TABLE
double NH3     = CNH4;
double GLNP    = CGLNC;
double GLNDEEP = CGLNM;
double NH3BR   = CNH4B;
double GLNBRAIN= GLNBREF + GLNB/VBR/1000.0;         // mmol/L, total
double MINSMM  = MINSB/VBR/1000.0;                  // mmol/L
double BW      = BRWAT;                             // %
double ICP     = ICP0 * exp(KICP*BRWAT);            // mmHg

// hepatic-encephalopathy stage 0-4 driven by oedema AND by ammonia itself
double hedrv = BRWAT/1.0 + (NH3 > 100.0 ? (NH3-100.0)/300.0 : 0.0);
double HESTAGE = 4.0*pow(hedrv,2.5)/(1.0 + pow(hedrv,2.5));

double PAAUG  = CPAA*136.15/1000.0;                 // ug/mL
double PGNUG  = CPGN*264.28/1000.0;                 // ug/mL
double PBAUG  = CPBA*164.20/1000.0;                 // ug/mL
double BZUG   = CBZ *122.12/1000.0;                 // ug/mL
double HIPUG  = CHIP*179.17/1000.0;                 // ug/mL
double PARATIO= (PGNUG > 0.01) ? PAAUG/PGNUG : 0.0;
double UPAGN  = CLPGN*CPGN*24.0/1000.0;             // mmol/day
double UHIPP  = CLHIP*CHIP*24.0/1000.0;             // mmol/day

double CITP = CCIT;
double ARGP = CARG;
double NCGP = CNCG;
double ORNC = CORN;
double GLYC = CGLY;
double BCAC = CBCA;
double OROTC= OROTP;

double IQEST = IQMAX - IQDROP*NEURO/(NEURO + IQ50);

// instantaneous nitrogen-disposal accounting (umol N/h)
double actbase2 = OTCACT;
if(CPS1A   < actbase2) actbase2 = CPS1A;
if(DISTALA < actbase2) actbase2 = DISTALA;
double otcx2 = OTCX; if(otcx2 > OTCXMAX) otcx2 = OTCXMAX;
double ACTEFF = actbase2 + otcx2;
double swtx2 = 1.0/(1.0 + exp(-(TIME - TTX)/1.0));
if(ACTX >= 0) ACTEFF = ACTEFF + (ACTX - ACTEFF)*swtx2;
if(ACTEFF > 1.0) ACTEFF = 1.0;

double swvpa2  = 1.0/(1.0 + exp(-(TIME - TVPA)/0.5));
double nagact2 = NAGSA*(1.0 - VPAI*swvpa2)*(1.0 + GARG*(CARG/ARGBASE - 1.0))
                 + GNCG*CNCG;
if(nagact2 < 0.0) nagact2 = 0.0;
double fnag2 = nagact2/(KNAG + nagact2);
double forn2 = CORN/(KORN + CORN);
double NUREA = UCAP*WT*ACTEFF*fnag2*forn2 * NH3/(KMNH4 + NH3);
double citex2 = CCIT - CITBASE; if(citex2 < 0.0) citex2 = 0.0;
double NCITR  = KCITN*DISTALA*citex2;
double NPAGN = 2.0*cPGN*CPGN;
double NHIPP = 1.0*cHIP*CHIP;
double NRENL = CLRGLN*CGLNC + CLNH4R*NH3;
double NBENZ = NHIPP;
double NTOTAL= NUREA + NCITR + NPAGN + NHIPP + NRENL;

// natural-protein tolerance: the intake (g/kg/day) at which this patient,
// on the CURRENT scavenger regimen, would sit at an ammonia of 60 umol/L
double gln60 = ucd_vgs(60.0, VG0, KG0, KGS, KGSAT)/GDENOM;
double ntol  = UCAP*WT*ACTEFF*fnag2*forn2*60.0/(KMNH4+60.0)
               + CLNH4R*60.0 + CLRGLN*gln60
               + NPAGN + NHIPP + NCITR - NOBL;
if(ntol < 0.0) ntol = 0.0;
double PROTTOL = ntol*24.0/(FDISP*WT*NPERG);

double CATNOW = CATB;

$CAPTURE @annotated
NH3      : Plasma ammonia (umol/L)
GLNP     : Plasma glutamine (umol/L)
GLNDEEP  : Deep tissue glutamine (umol/L)
NH3BR    : Brain ammonia (umol/L)
GLNBRAIN : Brain glutamine (mmol/L)
MINSMM   : Brain myo-inositol (mmol/L)
BW       : Brain water excess (%)
ICP      : Intracranial pressure (mmHg)
HESTAGE  : Encephalopathy stage (0-4)
PAAUG    : Plasma phenylacetate (ug/mL)
PGNUG    : Plasma phenylacetylglutamine (ug/mL)
PBAUG    : Plasma phenylbutyrate (ug/mL)
BZUG     : Plasma benzoate (ug/mL)
HIPUG    : Plasma hippurate (ug/mL)
PARATIO  : PAA:PAGN ratio (ug/mL basis)
UPAGN    : Urinary PAGN excretion rate (mmol/day)
UHIPP    : Urinary hippurate excretion rate (mmol/day)
CITP     : Plasma citrulline (umol/L)
ARGP     : Plasma arginine (umol/L)
NCGP     : Plasma carglumic acid (umol/L)
ORNC     : Ornithine pool (umol/L)
GLYC     : Plasma glycine (umol/L)
BCAC     : Plasma BCAA (umol/L)
OROTC    : Orotic acid pool (umol)
IQEST    : Modelled full-scale IQ
ACTEFF   : Effective ureagenic activity (fraction)
NUREA    : Nitrogen disposed as urea (umol N/h)
NCITR    : Nitrogen disposed via supplemental citrulline (umol N/h)
NPAGN    : Nitrogen disposed as PAGN (umol N/h)
NHIPP    : Nitrogen disposed as hippurate (umol N/h)
NRENL    : Nitrogen disposed renally (umol N/h)
NTOTAL   : Total nitrogen disposal (umol N/h)
PROTTOL  : Natural-protein tolerance at ammonia 60 (g/kg/day)
CATNOW   : Catabolic state (0-1)
'

## ---------------------------------------------------------------------------
##  Build
## ---------------------------------------------------------------------------
UCD_build <- function() {
  mrgsolve::mcode("ucd_qsp", ucd_code, quiet = TRUE)
}

## ---------------------------------------------------------------------------
##  Dose helpers — convert clinical units to umol
## ---------------------------------------------------------------------------
MW <- list(NaPBA = 186.2, PBA = 164.2, GPB = 530.6, PAA = 136.15,
           NaPAA = 158.13, PAGN = 264.28, NaBz = 144.11, BZ = 122.12,
           HIP = 179.17, CIT = 175.19, ARGHCL = 210.66, NCG = 190.15)

#' Sodium phenylbutyrate, g/day split over `n` doses -> umol PBA per dose
ucd_napba <- function(g_per_day, n = 3, ii = 8, days = 1, addl = NULL, start = 0) {
  amt <- g_per_day / MW$NaPBA * 1e6 / n
  if (is.null(addl)) addl <- ucd_addl(days, ii)
  mrgsolve::ev(time = start, amt = amt, cmt = "PBAG", ii = ii, addl = addl)
}

#' Glycerol phenylbutyrate, mL/day -> umol PBA-equivalents per dose (3 PBA/GPB)
ucd_gpb <- function(mL_per_day, n = 3, ii = 8, days = 1, addl = NULL, start = 0,
                    density = 1.1) {
  amt <- mL_per_day * density / MW$GPB * 1e6 * 3 / n
  if (is.null(addl)) addl <- ucd_addl(days, ii)
  mrgsolve::ev(time = start, amt = amt, cmt = "GPBG", ii = ii, addl = addl)
}

#' Sodium benzoate, mg/kg/day -> umol per dose
ucd_benzoate <- function(mgkg_per_day, wt = 70, n = 3, ii = 8, days = 1,
                         addl = NULL, start = 0) {
  amt <- mgkg_per_day * wt / MW$NaBz * 1e3 / n
  if (is.null(addl)) addl <- ucd_addl(days, ii)
  mrgsolve::ev(time = start, amt = amt, cmt = "BZG", ii = ii, addl = addl)
}

#' Ammonul-style IV load: 250 mg/kg each of Na-phenylacetate and Na-benzoate
#' over 90 min, then the same amount as a 24-h infusion.
ucd_ammonul <- function(wt = 70, load_mgkg = 250, maint_mgkg = 250,
                        start = 0, load_dur = 1.5, maint_dur = 24) {
  paa_load <- load_mgkg  * wt / MW$NaPAA * 1e3
  bz_load  <- load_mgkg  * wt / MW$NaBz  * 1e3
  paa_mnt  <- maint_mgkg * wt / MW$NaPAA * 1e3
  bz_mnt   <- maint_mgkg * wt / MW$NaBz  * 1e3
  c(
    mrgsolve::ev(time = start, amt = paa_load, cmt = "PAAC", rate = paa_load/load_dur),
    mrgsolve::ev(time = start, amt = bz_load,  cmt = "BZC",  rate = bz_load /load_dur),
    mrgsolve::ev(time = start + load_dur, amt = paa_mnt, cmt = "PAAC",
                 rate = paa_mnt/maint_dur),
    mrgsolve::ev(time = start + load_dur, amt = bz_mnt,  cmt = "BZC",
                 rate = bz_mnt /maint_dur)
  )
}

#' L-citrulline, mg/kg/day PO -> umol per dose
ucd_citrulline <- function(mgkg_per_day, wt = 70, n = 3, ii = 8, days = 1,
                           addl = NULL, start = 0) {
  amt <- mgkg_per_day * wt / MW$CIT * 1e3 / n
  if (is.null(addl)) addl <- ucd_addl(days, ii)
  mrgsolve::ev(time = start, amt = amt, cmt = "CITG", ii = ii, addl = addl)
}

#' L-arginine HCl IV load (mg/kg over `dur` hours)
ucd_arginine_iv <- function(mgkg, wt = 70, start = 0, dur = 1.5) {
  amt <- mgkg * wt / MW$ARGHCL * 1e3
  mrgsolve::ev(time = start, amt = amt, cmt = "ARGC", rate = amt/dur)
}

#' Carglumic acid, mg/kg/day PO -> umol per dose
ucd_carglumic <- function(mgkg_per_day, wt = 70, n = 2, ii = 12, days = 1,
                          addl = NULL, start = 0) {
  amt <- mgkg_per_day * wt / MW$NCG * 1e3 / n
  if (is.null(addl)) addl <- ucd_addl(days, ii)
  mrgsolve::ev(time = start, amt = amt, cmt = "NCGG", ii = ii, addl = addl)
}

#' AAV8-OTC gene transfer: a single durable template dose
ucd_aav <- function(units = 200, start = 0) {
  mrgsolve::ev(time = start, amt = units, cmt = "TRANSG")
}

#' OTC mRNA-LNP: repeat template dosing (template cleared fast — set KTRANS up)
ucd_mrna <- function(units = 900, ii = 336, addl = 5, start = 0) {
  mrgsolve::ev(time = start, amt = units, cmt = "TRANSG", ii = ii, addl = addl)
}

## ---------------------------------------------------------------------------
##  Number of `addl` doses needed to carry an every-`ii`-hours regimen for
##  `days` days (the first dose is the one in the ev(), hence the -1)
## ---------------------------------------------------------------------------
ucd_addl <- function(days, ii = 8) ceiling(days*24/ii) - 1

## ---------------------------------------------------------------------------
##  Fourteen prebuilt scenarios
## ---------------------------------------------------------------------------
#' @param mod   a model object from UCD_build()
#' @param which integer vector of scenario numbers (default all 14)
#' @return a data.frame with one row per output time and a `scenario` column
UCD_simulate_scenarios <- function(mod = UCD_build(), which = 1:14) {

  wt      <- 70
  chr_end <- 90*24     # chronic horizon: 90 days
  acu_end <- 96        # acute horizon: 96 hours

  ## a scavenger regimen carried for the whole chronic horizon
  A90  <- ucd_addl(90, 8)
  A30  <- ucd_addl(30, 12)

  run <- function(label, events = NULL, end = chr_end, delta = 1, pars = list()) {
    m <- mod
    if (length(pars)) m <- do.call(mrgsolve::param, c(list(m), pars))
    out <- mrgsolve::mrgsim(m, events = events, end = end, delta = delta,
                            hmax = 0.25, atol = 1e-8, rtol = 1e-6)
    d <- as.data.frame(out)
    d$scenario <- label
    d
  }

  ## regimen building blocks -------------------------------------------------
  GPB90  <- ucd_gpb(17.5, n = 3, ii = 8, addl = A90)
  PBA90  <- ucd_napba(20,  n = 3, ii = 8, addl = A90)
  CIT90  <- ucd_citrulline(170, wt, n = 3, ii = 8, addl = A90)
  BZ90   <- ucd_benzoate(250, wt, n = 3, ii = 8, addl = A90)

  S <- list(

    ## 1 — natural history: late-onset OTC male on diet alone
    function() run(
      "1. Diet alone (late-onset OTC, 0.60 g/kg/d)",
      NULL, end = chr_end),

    ## 2 — stricter protein restriction + L-citrulline
    function() run(
      "2. Protein 0.45 g/kg/d + citrulline 170 mg/kg/d",
      CIT90, end = chr_end, pars = list(PROT = 0.45)),

    ## 3 — sodium phenylbutyrate TID + citrulline
    function() run(
      "3. NaPBA 20 g/d TID + citrulline",
      c(PBA90, CIT90), end = chr_end),

    ## 4 — glycerol phenylbutyrate TID (matched PBA-equivalent dose)
    function() run(
      "4. GPB 17.5 mL/d TID + citrulline",
      c(GPB90, CIT90), end = chr_end),

    ## 5 — sodium benzoate monotherapy
    function() run(
      "5. Sodium benzoate 250 mg/kg/d TID",
      BZ90, end = chr_end),

    ## 6 — GPB + benzoate combination
    function() run(
      "6. GPB 17.5 mL/d + benzoate 250 mg/kg/d",
      c(GPB90, BZ90), end = chr_end),

    ## 7 — intercurrent illness, no treatment escalation
    function() run(
      "7. Severe catabolic crisis (sepsis), no escalation",
      GPB90, end = acu_end, delta = 0.25,
      pars = list(CATAMP = 4.0, CATT0 = 12, CATDUR = 96)),

    ## 8 — the same crisis, rescued medically
    function() run(
      "8. Crisis + Ammonul + arginine + anabolic rescue at 30 h",
      c(GPB90, ucd_ammonul(wt, start = 30), ucd_arginine_iv(400, wt, start = 30)),
      end = acu_end, delta = 0.25,
      pars = list(CATAMP = 4.0, CATT0 = 12, CATDUR = 96,
                  PROT2 = 0.0, TPROT = 30, ANAB = 0.8)),

    ## 9 — the neonatal counterfactual: the same baby as scenario 10, rescued
    ##     with maximal MEDICAL therapy but WITHOUT extracorporeal removal.
    ##     Scenarios 9 and 10 are the clearest statement the model can make
    ##     about why dialysis, not pharmacology, is the emergency treatment of
    ##     neonatal hyperammonaemia.
    function() run(
      "9. Neonatal OTC (1%): medical therapy only, no dialysis",
      c(ucd_gpb(2.2, n = 4, ii = 6, addl = ucd_addl(6, 6), start = 60),
        ucd_ammonul(3.4, start = 60),
        ucd_arginine_iv(400, 3.4, start = 60)),
      end = 168, delta = 0.25,
      pars = list(WT = 3.4, BSA = 0.22, VBR = 0.40, AGEY = 0,
                  OTCACT = 0.01, PROT = 0.05,
                  PROT2 = 1.80, TPROT = 12,
                  PROT3 = 0.20, TPROT3 = 60,
                  CATAMP = 1.5, CATT0 = 6, CATDUR = 150,
                  ANAB = 1.0)),

    ## 10 — neonatal-onset OTC: the classical presentation. A 3.4 kg boy with
    ##      1% residual activity is well at birth (placental clearance), feeds
    ##      are established at 12 h, he is obtunded by 48 h, and full rescue
    ##      (protein withdrawal + Ammonul + arginine + CVVHD) starts at 60 h.
    function() run(
      "10. Neonatal OTC (1%): the same rescue plus CVVHD at 62 h",
      c(ucd_gpb(2.2, n = 4, ii = 6, addl = ucd_addl(6, 6), start = 60),
        ucd_ammonul(3.4, start = 60),
        ucd_arginine_iv(400, 3.4, start = 60)),
      end = 168, delta = 0.25,
      pars = list(WT = 3.4, BSA = 0.22, VBR = 0.40, AGEY = 0,
                  OTCACT = 0.01, PROT = 0.05,
                  PROT2 = 1.80, TPROT = 12,     # feeds established
                  PROT3 = 0.20, TPROT3 = 60,    # protein withdrawn at rescue
                  CATAMP = 1.5, CATT0 = 6, CATDUR = 150,
                  CLHD = 3.0, HDT0 = 62, HDDUR = 24, ANAB = 1.0)),

    ## 11 — NAGS deficiency rescued by carglumic acid
    function() run(
      "11. NAGS deficiency + carglumic acid 150 mg/kg/d",
      ucd_carglumic(150, wt, n = 2, ii = 12, addl = A30),
      end = 30*24,
      pars = list(OTCACT = 1.0, NAGSA = 0.05, PROT = 0.80)),

    ## 12 — AAV8-OTC gene transfer with the scavenger continued
    function() run(
      "12. AAV8-OTC gene transfer (DTX301) on GPB",
      c(GPB90, ucd_aav(200, start = 24)), end = chr_end),

    ## 13 — organ impairment unmasks phenylacetate accumulation: slower renal
    ##      PAGN clearance AND a halved hepatic conjugation capacity, which is
    ##      the combination that pushes the PAA:PAGN ratio through 2.5 and PAA
    ##      towards the 500 ug/mL neurotoxicity threshold
    function() run(
      "13. GPB with renal + hepatic impairment (PAA accumulation)",
      ucd_gpb(20, n = 3, ii = 8, addl = A90), end = 21*24, delta = 0.25,
      pars = list(CLPGN = 1.8, CLPAA = 0.6, CLHIP = 4.0, VMPKG = 45)),

    ## 14 — a manifesting OTC heterozygote started on valproate. She is stable
    ##      at an ammonia of ~45 until valproate inhibits NAGS at 24 h; the
    ##      accompanying illness adds a modest catabolic load.
    function() run(
      "14. Valproate started in a manifesting OTC heterozygote",
      NULL, end = 240, delta = 0.25,
      pars = list(OTCACT = 0.65, PROT = 0.80,
                  VPAI = 0.80, TVPA = 24,
                  CATAMP = 0.40, CATT0 = 24, CATDUR = 168))
  )

  res <- do.call(rbind, lapply(S[which], function(f) f()))
  rownames(res) <- NULL
  res
}

## ---------------------------------------------------------------------------
##  Compact numeric summary of a scenario set
## ---------------------------------------------------------------------------
UCD_summarise <- function(sim) {
  sp <- split(sim, sim$scenario)
  out <- do.call(rbind, lapply(names(sp), function(nm) {
    d <- sp[[nm]]
    tail1 <- d[nrow(d), ]
    data.frame(
      scenario     = nm,
      hours        = max(d$time),
      NH3_start    = round(d$NH3[1], 1),
      NH3_end      = round(tail1$NH3, 1),
      NH3_peak     = round(max(d$NH3), 1),
      GLN_end      = round(tail1$GLNP, 0),
      BrainGln_pk  = round(max(d$GLNBRAIN), 1),
      mIns_end     = round(tail1$MINSMM, 2),
      BW_peak_pct  = round(max(d$BW), 2),
      ICP_peak     = round(max(d$ICP), 1),
      HE_peak      = round(max(d$HESTAGE), 2),
      coma_h       = round(tail1$COMAH, 1),
      PAA_peak_ug  = round(max(d$PAAUG), 1),
      PAAPGN_pk    = round(max(d$PARATIO), 2),
      PAAPGN_med   = round(stats::median(d$PARATIO), 2),
      UPAGN_mmold  = round(stats::median(d$UPAGN), 1),
      ProtTol_end  = round(tail1$PROTTOL, 2),
      IQ_end       = round(tail1$IQEST, 1),
      Nurea_pct    = round(100*stats::median(d$NUREA/pmax(d$NTOTAL,1)), 0),
      Npagn_pct    = round(100*stats::median(d$NPAGN/pmax(d$NTOTAL,1)), 0),
      Nhipp_pct    = round(100*stats::median(d$NHIPP/pmax(d$NTOTAL,1)), 0),
      stringsAsFactors = FALSE
    )
  }))
  rownames(out) <- NULL
  out
}

## ---------------------------------------------------------------------------
##  Quick-look plot (base graphics; no extra dependencies)
## ---------------------------------------------------------------------------
UCD_plot <- function(sim, yvar = "NH3", ylab = NULL, log = "") {
  sp <- split(sim, sim$scenario)
  cols <- grDevices::hcl.colors(length(sp), "Dark 3")
  ylim <- range(unlist(lapply(sp, function(d) d[[yvar]])), na.rm = TRUE)
  xlim <- range(sim$time)
  plot(NA, xlim = xlim/24, ylim = ylim, log = log,
       xlab = "Time (days)", ylab = ylab %||% yvar,
       main = paste("UCD QSP —", yvar))
  for (i in seq_along(sp)) {
    lines(sp[[i]]$time/24, sp[[i]][[yvar]], col = cols[i], lwd = 2)
  }
  legend("topright", legend = names(sp), col = cols, lwd = 2,
         cex = 0.6, bty = "n")
  invisible(NULL)
}
`%||%` <- function(a, b) if (is.null(a)) b else a

## ---------------------------------------------------------------------------
##  Example
## ---------------------------------------------------------------------------
if (identical(environment(), globalenv()) && !interactive() &&
    isTRUE(getOption("ucd.run.example", FALSE))) {
  mod <- UCD_build()
  sim <- UCD_simulate_scenarios(mod)
  print(UCD_summarise(sim))
}
