##  Paediatric Growth Hormone Deficiency (GHD) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Paediatric growth hormone deficiency — impaired hypothalamic
##             (GHRH/somatostatin/ghrelin) drive and/or reduced somatotroph
##             secretory mass -> low pulsatile GH -> reduced GHR/JAK2/STAT5b
##             signalling -> low hepatic IGF-1 AND low IGFBP-3/ALS carrier
##             capacity (a DOUBLE hit: less synthesis and faster clearance of
##             what is made) -> reduced growth-plate chondrocyte proliferation
##             and hypertrophic cell enlargement -> subnormal height velocity,
##             falling height SDS, increased fat mass, reduced lean mass and
##             BMD accrual. GH insensitivity (GHR/STAT5B/IGFALS/PAPPA2 defects,
##             i.e. Laron-type) is the mirror lesion and is representable with
##             the same structure by collapsing the transduction gains.
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (built & numerically validated under mrgsolve 2.0.1,
##             R 4.3.3)
##
##  ---------------------------------------------------------------------------
##  MODELLING IDEA (why this model is structured the way it is)
##  ---------------------------------------------------------------------------
##  Linear growth is treated NOT as a state to be prescribed but as the PRODUCT
##  of a chain of independently breakable gains:
##
##      HV  =  [hypothalamic drive]  x  [somatotroph mass]
##             x  [GH PK & free fraction]  x  [GHR-JAK2-STAT5b transduction]
##             x  [IGF-1 output x its BINDING state]
##             x  [growth-plate responsiveness]
##             x  [REMAINING proliferative reserve]
##
##  Two consequences fall out of the structure rather than being coded:
##
##   (1) CATCH-UP GROWTH IS A CONSUMABLE, NOT A SETPOINT. The resting-zone
##       reserve RZ multiplies the proliferation rate and is itself spent in
##       proportion to proliferation. An untreated GHD child grows slowly and
##       therefore SAVES reserve; starting rhGH spends it fast. That is why
##       year-1 HV (~10-11 cm/yr) exceeds year-3 HV (~7 cm/yr) on an UNCHANGED
##       mg/kg/wk dose, and why age at initiation is the dominant modifiable
##       predictor of near-adult height. No "year-1 decay function" is fitted.
##
##   (2) OESTROGEN ENTERS TWICE WITH OPPOSITE SIGN. E2 amplifies GH pulse
##       amplitude (the pubertal spurt, HV up) AND accelerates reserve
##       consumption and epiphyseal fusion (growing time down). The net effect
##       of an aromatase inhibitor or a GnRH analogue is therefore an emergent
##       trade-off between cm/yr and years-of-growth, not a coded height gain.
##
##  A third structural point: IGF-1 clearance depends on its own BINDING state
##  (KE_IGF is a weighted average of the fast free-pool rate and the slow
##  150-kDa ternary-complex rate). In untreated GHD, low IGFBP-3/ALS raises the
##  free fraction and thus SPEEDS clearance, deepening the IGF-1 deficit beyond
##  the drop in synthesis. In IGFALS deficiency the same term reproduces very
##  low total IGF-1 with a near-normal growth phenotype relative to the number.
##
##  ---------------------------------------------------------------------------
##  Scope    : 42 ODE compartments
##             - hypothalamic oscillator (GHRH, somatostatin, ghrelin)
##             - somatotroph functional mass + releasable granule pool
##             - GH 2-compartment PK with GHBP binding and saturable
##               receptor-mediated clearance; ADA neutralisation
##             - 5 drug/PK routes: daily somatropin SC; weekly long-acting GH
##               (carrier/prodrug -> released bioactive GH: lonapegsomatropin,
##               somatrogon, somapacitan); mecasermin (rhIGF-1) SC;
##               GnRH-analogue depot; aromatase inhibitor
##             - GHR density, pSTAT5b, SOCS2 feedback brake
##             - IGF-1, IGFBP-3, ALS, IGFBP-1, local growth-plate IGF-1,
##               ternary-complex-dependent clearance, free (bioactive) IGF-1
##             - growth plate: resting-zone reserve, proliferative zone,
##               hypertrophic zone, senescence/fusion program
##             - height, bone age, BMD Z
##             - puberty: GnRH pulse generator, testosterone, oestradiol
##             - body composition (fat/lean), insulin resistance, insulin,
##               glucose, FFA, LDL-C
##             - safety: ADA titre, free T4 (unmasked central hypothyroidism),
##               intracranial-pressure index (benign intracranial hypertension)
##  Time     : DAYS. Default horizon 4 years (1460 d) for growth endpoints;
##             short horizons (0.2-7 d) for PK profiling and provocation tests.
##  Units    : GH in ug/L (= ng/mL); IGF-1 in ng/mL; IGFBP-3 in mg/L; drug
##             depots in mg; height in cm; bone age in yr; mass in kg;
##             glucose mg/dL; insulin uU/mL; FFA mmol/L; LDL-C mg/dL.
##             Signalling species (pSTAT5b, SOCS2, ALS, IGFBP-1, local IGF-1,
##             GHBP, zone sizes) are normalised so that 1.0 = healthy
##             prepubertal reference.
##  Scenarios: 19 prebuilt — see GHD_simulate_scenarios() at the bottom, plus a
##             closed-loop annual IGF-1-SDS titration helper GHD_titrate().
##
##  ---------------------------------------------------------------------------
##  CALIBRATION — TARGETS AND WHAT THE MODEL ACTUALLY PRODUCES
##  ---------------------------------------------------------------------------
##  Every number in the right-hand column below was read off this file as
##  written, integrated under mrgsolve 2.0.1 / R 4.3.3, for the default patient
##  (5-year-old boy, severe congenital isolated GHD, PITMAX = 0.06, height SDS
##  -2.3, ~15.5 kg) over a 4-year horizon, dose re-titrated +10%/yr for growth.
##
##    Anchor                                       target         model
##    ----------------------------------------------------------------------
##    Healthy reference child (PITMAX = 1, age 5, ~19 kg)
##      endogenous GH secretion rate               ~300 ug/day    397 ug/day
##      24-h mean total GH                         2-3 ug/L       4.2 ug/L
##      24-h peak / trough GH                      15-25 / <0.2   10.9 / 1.9
##      IGF-1                                      ~90 ng/mL      97 ng/mL
##      IGFBP-3                                    2-4 mg/L       3.3 mg/L
##      height velocity, age 5 -> 6 -> 7 -> 8      6.0 5.7 5.6 5.3   6.6 6.0 5.5 5.0
##      height SDS drift over 4 yr                 ~0             +0.19
##      bone age / chronological age               ~1.0           0.95
##    Untreated severe GHD (PITMAX = 0.06, height SDS -2.3, 15.5 kg)
##      provoked peak GH (secretagogue bolus)      <5 ug/L        0.4 ug/L
##      provoked peak, PARTIAL GHD (PITMAX 0.35)   5-9 ug/L       2.2 ug/L
##      provoked peak, healthy child               >10 ug/L       10.1 ug/L
##      IGF-1 / IGF-1 SDS                          low / -2..-3   21 / -1.9
##      height velocity                            3-4 cm/yr      3.3 cm/yr
##      height SDS lost per year                   0.3-0.4        0.42
##    Daily somatropin, single 0.034 mg/kg SC dose
##      Cmax                                       15-40 ug/L     17.3 ug/L
##      Tmax                                       3-6 h          1.8 h
##      apparent terminal t1/2 (flip-flop)         2-4 h          4.4 h
##      24-h mean GH on treatment vs healthy       ~1.3x          5.0 vs 4.2
##    Daily somatropin, annualised height velocity (dose re-titrated +10%/yr)
##      0.025 mg/kg/day                            ~9.3 cm/yr     9.6
##      0.034 mg/kg/day                            10.3-10.8      10.5
##      0.050 mg/kg/day                            ~11.3          11.5
##      IGF-1 on 0.034 / 0.050 mg/kg/day           109 / 143 ng/mL (SDS +0.4 / +1.4)
##      delta-height-SDS, year 1 (0.034)           +0.8 to +1.1   +1.06
##      HV year 1 -> 2 -> 3 -> 4 (0.034)           10.5 8.5 7.5 -  10.5 9.5 8.7 8.0
##    Weekly long-acting GH, year-1 height velocity
##      lonapegsomatropin 0.24 mg/kg/wk            11.2 (heiGHt)  10.3
##      somatrogon 0.66 mg/kg/wk                   10.1           9.8
##      somapacitan 0.16 mg/kg/wk                  11.2 (REAL4)   10.2
##      released-GH Tmax within the interval       ~1-2 d         2.0-2.1 d
##      IGF-1 peak day / trough day                2-4 / 7        2.6-3.1 / 7
##      within-week IGF-1 SDS swing                1.5-2.5 SDS    2.3 (lonapeg)
##                                                                2.6 (somatrogon)
##                                                                1.7 (somapacitan)
##    Other arms (4-year horizon from age 5 unless stated)
##      GH insensitivity (Laron), untreated        3-4 cm/yr      3.5
##      Laron + mecasermin 100 ug/kg BID           8-9 cm/yr      7.6
##      IGFALS deficiency: IGF-1 SDS / HV          very low / mild  -2.5 / 4.3
##      unreplaced central hypothyroidism          blunted        2.4 cm/yr
##        with free T4 and bone age both low       low FT4        FT4 0.52, BA/CA 0.63
##      high-dose glucocorticoid (12 mg/m2/day)    blunted        4.0 cm/yr
##      60% adherence to the daily product         costs 1-2 cm/yr  10.5 -> 8.3
##      neutralising ADA                           attenuation    10.5 -> 8.2
##      late start (age 10, same dose)             worse outcome  final height SDS
##                                                                -1.80 vs +0.59
##      GH + GnRH analogue, 4 yr from age 12       +4-5 cm        +1.14 height SDS
##      GH + anastrozole, 4 yr from age 12         smaller gain   +0.84 height SDS
##        with the bone-mineral trade-off          BMD penalty    BMD Z -0.52 vs -0.06
##      IGF-1-SDS-titrated dosing (GHD_titrate)    converges to   dose 0.034 -> 0.045
##                                                 target band    IGF-1 SDS ~ +1.2
##
##  KNOWN LIMITATIONS (state these before using any output)
##   1. ULTRADIAN GH PULSES ARE NOT RESOLVED. The model carries a circadian
##      (nocturnal-surge) modulation only, so the simulated endogenous profile is
##      smoother than physiology: peaks are underestimated (~11 vs 15-25 ug/L),
##      troughs overestimated (~1.9 vs <0.2 ug/L) and the 24-h mean therefore
##      sits above the reported 2-3 ug/L. Any question whose answer depends on
##      pulse shape rather than 24-h exposure is out of scope.
##   2. The GH -> STAT5b step uses an APPARENT (system-level) EC50 of 60 ug/L,
##      above the molecular GHR Kd, so that the IGF-1 dose-response stays close
##      to proportional across the therapeutic range as clinical data require.
##      It is a lumped transduction gain, not a receptor-binding constant.
##   3. Height and IGF-1 SDS use smooth internal reference tables (see [GLOBAL]),
##      not a validated national growth chart or an assay-specific IGF-1
##      reference. SDS values are internally consistent, not transferable.
##   4. Provoked GH peaks are compressed (normal ~10 ug/L rather than 15-40), so
##      the model separates severe / partial / normal correctly but should not be
##      used to explore diagnostic cut-offs quantitatively.
##   5. Body composition, insulin resistance, lipids, BMD Z, the intracranial-
##      pressure index and the ADA titre are semi-mechanistic target-tracking
##      representations. Directions and time courses are calibrated; absolute
##      values are illustrative. The ICP term is a relative risk index, not a
##      pressure in mmHg.
##   6. Adherence is applied deterministically (every n-th dose taken), not as
##      a stochastic missed-dose process.
##   7. The initial growth-plate reserve (RZ_0 in [MAIN]) is the same
##      consumption law integrated over the child's life so far, but using a
##      LIFETIME-AVERAGE growth rate (KPH0/KPH1) rather than the trajectory the
##      model would have produced. Starting a run at age 8 therefore gives a
##      slightly lower reserve (~15-20%) than integrating the same child from
##      age 5 to 8. Compare arms at the same starting age.
##   8. The provoked-GH response saturates in the secretagogue bolus amount, so
##      the model discriminates severe / partial / normal secretion but cannot
##      be used to compare stimulation agents against each other.
##
##  Disclaimer: Research / education / hypothesis generation only. Parameters
##              are illustrative approximations from public literature and are
##              NOT fitted to individual patient data. The height and IGF-1
##              reference tables below are smooth approximations of published
##              growth/assay references for SDS bookkeeping inside the model —
##              they are NOT a substitute for a validated national growth chart
##              or an assay-specific IGF-1 reference. Not for clinical use.
##  ============================================================================

[PROB]
QSP model of paediatric growth hormone deficiency. Linear growth is computed as
the product of separable gains: hypothalamic GHRH/somatostatin/ghrelin drive,
somatotroph secretory mass, GH pharmacokinetics and free fraction (GHBP),
GHR-JAK2-STAT5b transduction under a SOCS2 brake, hepatic IGF-1 output and its
binding state (IGFBP-3/ALS ternary complex), growth-plate chondrocyte
proliferation/hypertrophy, and the REMAINING resting-zone proliferative
reserve. Catch-up growth and the year-on-year decline of height velocity on an
unchanged dose emerge from reserve consumption; the oestrogen trade-off between
cm/yr and years-of-growth emerges from E2 entering with opposite signs.
Includes daily somatropin, three weekly long-acting GH constructs, mecasermin,
a GnRH analogue and an aromatase inhibitor, plus body composition, insulin
resistance, bone, and safety (IGF-1 cap, ADA, free T4, intracranial pressure).

[GLOBAL]
// ---------------------------------------------------------------------------
// Reference tables for SDS bookkeeping (smooth approximations — see header
// disclaimer). Height: CDC/WHO-like 50th centile and SD, ages 2-18 y.
// IGF-1: immunoassay-typical age-referenced mean and SD (ng/mL).
// ---------------------------------------------------------------------------
#define NREF 17

namespace ghdref {

  const double AGEG[NREF] = {2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18};

  // Boys: median height (cm) and SD (cm)
  const double HTM_M[NREF] = {87.1, 96.1,103.3,110.0,116.0,121.7,127.3,132.6,
                             137.8,143.1,149.1,156.0,163.2,169.0,172.9,175.2,176.1};
  const double HTS_M[NREF] = { 3.7,  4.0,  4.3,  4.6,  4.9,  5.2,  5.5,  5.8,
                               6.1,  6.4,  6.8,  7.2,  7.3,  7.0,  6.8,  6.7, 6.7};
  // Girls: median height (cm) and SD (cm)
  const double HTM_F[NREF] = {86.0, 94.9,102.7,109.4,115.5,121.1,126.6,132.2,
                             138.3,144.8,151.2,156.4,159.8,161.7,162.6,163.1,163.3};
  const double HTS_F[NREF] = { 3.7,  4.0,  4.3,  4.6,  4.9,  5.3,  5.7,  6.1,
                               6.5,  6.7,  6.7,  6.5,  6.4,  6.4,  6.4,  6.4, 6.4};

  // Age-referenced serum total IGF-1 (ng/mL): mean and SD
  const double IGFM_M[NREF] = { 58,  68,  78,  90, 102, 116, 132, 150,
                               172, 200, 232, 268, 296, 312, 300, 282, 262};
  const double IGFS_M[NREF] = { 26,  29,  32,  36,  40,  45,  50,  56,
                                63,  72,  82,  92, 100, 104, 100,  96,  90};
  const double IGFM_F[NREF] = { 62,  74,  86, 100, 116, 134, 158, 184,
                               216, 250, 282, 300, 300, 288, 274, 262, 250};
  const double IGFS_F[NREF] = { 28,  31,  35,  39,  44,  50,  57,  64,
                                74,  84,  92,  98,  98,  95,  92,  90,  88};

  // linear interpolation with flat extrapolation
  inline double interp(double x, const double *xs, const double *ys) {
    if (x <= xs[0])       return ys[0];
    if (x >= xs[NREF-1])  return ys[NREF-1];
    int i = 0;
    while (i < NREF-2 && x > xs[i+1]) i++;
    double f = (x - xs[i]) / (xs[i+1] - xs[i]);
    return ys[i] + f*(ys[i+1] - ys[i]);
  }

  inline double ht_med(double a, double sex){ return sex > 0.5 ? interp(a,AGEG,HTM_M) : interp(a,AGEG,HTM_F); }
  inline double ht_sd (double a, double sex){ return sex > 0.5 ? interp(a,AGEG,HTS_M) : interp(a,AGEG,HTS_F); }
  inline double ig_med(double a, double sex){ return sex > 0.5 ? interp(a,AGEG,IGFM_M) : interp(a,AGEG,IGFM_F); }
  inline double ig_sd (double a, double sex){ return sex > 0.5 ? interp(a,AGEG,IGFS_M) : interp(a,AGEG,IGFS_F); }
}

[PARAM] @annotated
// ---------------------------------------------------------------------------
// PATIENT / AETIOLOGY COVARIATES
// ---------------------------------------------------------------------------
SEX      :  1    : Sex (1 = male, 0 = female)
AGE0     :  5    : Chronological age at time 0 (yr)
BA0      :  4.0  : Bone age at time 0 (yr)
MPHSDS   : -0.5  : Mid-parental (target) height SDS
PITMAX   :  0.06 : Somatotroph secretory capacity ceiling (1 = normal, 0.06 = severe congenital GHD)
GHRCAP   :  1.0  : GH-receptor expression capacity (1 = normal, <0.1 = Laron / GHR loss of function)
STAT5CAP :  1.0  : STAT5b transduction capacity (1 = normal, <0.2 = STAT5B defect)
ALSCAP   :  1.0  : IGFALS (acid-labile subunit) capacity (1 = normal, 0 = ALS deficiency)
PAPPA2A  :  1.0  : PAPP-A2 proteolytic activity (1 = normal; 0 = high total / low free IGF-1)
XRT_ON   :  0    : Ongoing progressive hypothalamic-pituitary injury flag (post-irradiation)
KDAM     :  0.0008 : Progressive somatotroph loss rate when XRT_ON = 1 (1/day)
HYPOGON  :  0    : Co-existing hypogonadotrophic hypogonadism (1 = no endogenous puberty)
NUTR     :  1.0  : Nutritional adequacy multiplier on hepatic IGF-1 synthesis
LIVER    :  1.0  : Hepatic functional capacity multiplier
SLEEPQ   :  1.0  : Slow-wave-sleep quality multiplier on GHRH drive
GCDOSE   :  0    : Glucocorticoid exposure (prednisolone-equivalent mg/m2/day)
IC50_GC  :  6.0  : Glucocorticoid dose halving growth-plate proliferation (mg/m2/day)
IMGEN    :  0    : Immunogenicity of the administered GH product (0 = none, 1 = high)
LT4      :  1.0  : Levothyroxine replacement adequacy (1 = fully replaced, 0 = unreplaced); substitutes for missing thyrotroph capacity rather than multiplying it
INITMODE :  1    : 1 = derive initial conditions from the covariates below; 0 = keep whatever init() supplies (needed to carry state across sequential runs, e.g. annual dose titration)

// ---------------------------------------------------------------------------
// HYPOTHALAMIC OSCILLATOR
// ---------------------------------------------------------------------------
KIN_GHRH  : 14.0 : GHRH tone production rate (1/day)
KOUT_GHRH : 14.0 : GHRH tone elimination rate (1/day)
AMPC      : 24.0 : Amplitude of the circadian (nocturnal-surge) drive
HILLC     :  8.0 : Sharpness of the nocturnal surge
PHASE     :  0.72: Phase of the nocturnal surge (fraction of a day)
KI_SST_G  :  1.6 : Somatostatin tone halving GHRH production
EMAX_GHRL :  1.1 : Maximal ghrelin amplification of GHRH drive
EC50_GHRL :  1.4 : Ghrelin tone for half-maximal amplification
GAIN_IGFG :  0.9 : IGF-1 long-loop inhibition gain on GHRH
KIN_SST   :  8.0 : Somatostatin tone production rate (1/day)
KOUT_SST  :  8.0 : Somatostatin tone elimination rate (1/day)
SL_IGF_S  :  0.8 : IGF-1 long-loop drive on somatostatin
SL_GH_S   :  0.5 : GH short-loop autofeedback drive on somatostatin
SL_FFA_S  :  0.3 : FFA drive on somatostatin
KIN_GHRL  :  9.0 : Ghrelin tone production rate (1/day)
KOUT_GHRL :  9.0 : Ghrelin tone elimination rate (1/day)
KI_INS_GL :  9.0 : Insulin (uU/mL) halving ghrelin production

// ---------------------------------------------------------------------------
// SOMATOTROPH
// ---------------------------------------------------------------------------
KGROW     : 0.02  : Somatotroph trophic growth rate (1/day)
KSYN_GH   : 611   : GH granule synthesis rate at full somatotroph mass and reference size (ug/day)
WTREF     : 20    : Reference body weight for secretion-capacity scaling (kg)
EMAX_CREB : 1.4   : Maximal GHRH/cAMP/CREB amplification of GH synthesis
EC50_CREB : 1.3   : GHRH tone for half-maximal synthesis amplification
VMAX_SEC  : 4700  : Maximal GH secretion rate at full mass and reference size (ug/day)
KM_GHRH   : 6.0   : GHRH tone for half-maximal secretion
KI_SST_S  : 1.1   : Somatostatin tone halving secretion
KM_POOL   : 60    : Granule pool for half-maximal secretion (ug)
KDEG_POOL : 0.35  : Intracellular GH degradation rate (1/day)

// ---------------------------------------------------------------------------
// GH DISPOSITION
// ---------------------------------------------------------------------------
VC70      : 10.5  : GH central volume (L/70 kg)
VP70      : 6.0   : GH peripheral volume (L/70 kg)
Q70       : 30    : GH intercompartmental clearance (L/day/70 kg)
CL70      : 340   : Linear clearance of FREE GH (L/day/70 kg)
CLRMAX    : 765   : Maximal receptor-mediated GH elimination (ug/day/70 kg)
KM_CLR    : 2.0   : Free GH for half-maximal receptor-mediated elimination (ug/L)
KSYN_BP   : 1.0   : GHBP production rate (1/day)
KOUT_BP   : 1.0   : GHBP elimination rate (1/day)
KD_BP     : 1.0   : GHBP level giving 50% GH bound (normalised)
KADA      : 0.50  : ADA titre halving free (active) GH

// ---------------------------------------------------------------------------
// DRUG PK — DAILY SOMATROPIN (SC)
// ---------------------------------------------------------------------------
KA_D      : 4.8   : Daily somatropin SC absorption rate (1/day; ~0.20 1/h, Tmax ~3-4 h)
FBIO_D    : 0.70  : Daily somatropin SC bioavailability

// ---------------------------------------------------------------------------
// DRUG PK — WEEKLY LONG-ACTING GH (carrier/prodrug -> bioactive GH)
//   set KA_W / KREL / CLP_K / POT_W per product (see scenario helpers):
//   lonapegsomatropin  KA_W 0.45 KREL 0.55  CLP_K 0.08  POT_W 1.00  (0.24 mg/kg/wk)
//   somatrogon         KA_W 0.60 KREL 0.58  CLP_K 0.10  POT_W 0.33  (0.66 mg/kg/wk)
//   somapacitan        KA_W 0.50 KREL 0.35  CLP_K 0.05  POT_W 1.45  (0.16 mg/kg/wk)
//   POT_W converts mg of construct into mg of bioactive GH equivalents: the CTP
//   fusion and the albumin-binder add mass without proportional activity, so
//   each product's label dose is a different number of mg for a similar
//   bioactive exposure. POT_W is fitted so that each label dose reproduces its
//   own phase-3 annualised height velocity.
// ---------------------------------------------------------------------------
KA_W      : 0.45  : Weekly LAGH SC absorption rate into the carrier pool (1/day; the depot, not the linker, is usually the rate-limiting step)
KREL      : 0.55  : Carrier -> bioactive GH release rate (1/day)
CLP_K     : 0.08  : Non-releasing carrier elimination rate (1/day)
POT_W     : 1.00  : Bioactive GH equivalents per mg of released construct
FBIO_W    : 0.72  : Weekly LAGH SC bioavailability

// ---------------------------------------------------------------------------
// DRUG PK — MECASERMIN (rhIGF-1, SC) and ADJUVANTS
// ---------------------------------------------------------------------------
KA_M      : 12.0  : Mecasermin SC absorption rate (1/day)
FBIO_M    : 0.85  : Mecasermin SC bioavailability
VD_IGF    : 21.0  : IGF-1 distribution volume (L/70 kg; ~0.3 L/kg, plasma + interstitial)
LEUPRATE  : 0     : GnRH-analogue depot delivery rate (mg/day; 11.25 mg/12 wk ~ 0.134)
VLEU      : 25    : GnRH-analogue distribution volume (L)
KEL_LEU   : 0.9   : GnRH-analogue elimination rate (1/day)
IC50_LEU  : 0.6   : GnRH-analogue concentration halving GnRH pulse drive (ug/L)
AIRATE    : 0     : Aromatase-inhibitor dose rate (mg/day; anastrozole 1 mg/day)
VAI       : 100   : Aromatase-inhibitor distribution volume (L)
KEL_AI    : 0.4   : Aromatase-inhibitor elimination rate (1/day)
IC50_AI   : 12    : Aromatase-inhibitor concentration halving aromatase activity (ug/L)

// ---------------------------------------------------------------------------
// GHR / JAK2 / STAT5b / SOCS2
// ---------------------------------------------------------------------------
KD_GHR    : 60.0  : APPARENT free GH for half-maximal GH->STAT5b transcriptional signal (ug/L) - a system-level EC50, deliberately above the molecular GHR Kd (0.3-1 nM, ~7-22 ug/L) so that the signal stays near-linear in GH exposure across the therapeutic range, as the clinical IGF-1 dose-response requires
KSYN_R    : 1.0   : GHR synthesis rate (1/day)
KDEG_R    : 1.0   : GHR degradation rate (1/day)
KDOWN     : 0.4   : Ligand-induced GHR down-regulation factor
KI_SOCS_R : 8.0   : SOCS2 level halving GHR synthesis
KON_S     : 120.0 : STAT5b transcriptional-signal formation rate (1/day)
KOFF_S    : 2.50  : STAT5b transcriptional-signal decay rate (1/day; t1/2 ~6.7 h)
KI_SOCS_S : 5.0   : SOCS2 level halving STAT5b signal formation
KSYN_SOC  : 1.6   : SOCS2 synthesis rate from pSTAT5b (1/day)
KOUT_SOC  : 1.6   : SOCS2 elimination rate (1/day)

// ---------------------------------------------------------------------------
// IGF SYSTEM
// ---------------------------------------------------------------------------
KSYN_IGF  : 380   : Maximal hepatic IGF-1 synthesis at the reference age (ng/mL/day)
KMATI     : 0.95  : Hepatic maturation (liver-mass) exponent on IGF-1 synthesis vs age
AGE_IREF  : 5.0   : Reference age at which KSYN_IGF is defined (yr)
KM_S      : 2.0   : STAT5b signal for half-maximal IGF-1 synthesis (kept well above the healthy operating point so the IGF-1 dose-response stays close to proportional)
HS        : 2.0   : Hill coefficient, pSTAT5b -> IGF-1 synthesis
BAS_IGF   : 0.10  : GH-independent fraction of hepatic IGF-1 synthesis
EMAX_E2I  : 0.55  : Maximal E2 amplification of hepatic IGF-1 synthesis
EC50_E2I  : 26    : E2 for half-maximal IGF-1 amplification (pg/mL)
KEF_IGF   : 42    : Elimination rate of FREE IGF-1 (1/day; t1/2 ~25 min)
KET_IGF   : 1.05  : Elimination rate of ternary-complexed IGF-1 (1/day; t1/2 ~16 h)
KB_TERN   : 39.0  : Binding strength of the IGFBP-3 x ALS carrier pool
KB_BIN    : 6     : Binding strength of the IGFBP-1 binary pool
KSYN_BP3  : 6.55  : IGFBP-3 synthesis rate (mg/L/day)
BAS_BP3   : 0.40  : GH-independent fraction of IGFBP-3 synthesis (IGFBP-3 SDS is less deviant than IGF-1 SDS in GHD)
KM3       : 0.9   : pSTAT5b for half-maximal IGFBP-3 synthesis
H3        : 1.6   : Hill coefficient, pSTAT5b -> IGFBP-3
KOUT_BP3  : 1.1   : IGFBP-3 elimination rate (1/day)
KPA       : 0.35  : PAPP-A2 contribution to IGFBP-3 proteolysis
KSYN_ALS  : 1.324 : ALS synthesis rate (1/day)
KOUT_ALS  : 1.0   : ALS elimination rate (1/day)
KMA       : 0.8   : STAT5b signal for half-maximal ALS synthesis
BAS_ALS   : 0.42  : GH-independent fraction of ALS synthesis
KSYN_BP1  : 2.0   : IGFBP-1 synthesis rate (1/day)
KOUT_BP1  : 2.0   : IGFBP-1 elimination rate (1/day)
KI_INS_B1 : 6.0   : Insulin halving IGFBP-1 synthesis (uU/mL)
KSYN_L    : 3.60  : Local growth-plate IGF-1 synthesis rate (1/day)
KOUT_L    : 1.20  : Local growth-plate IGF-1 elimination rate (1/day)
KML       : 2.00  : STAT5b signal for half-maximal local IGF-1 induction
FIGFREF   : 0.72  : Healthy reference free (bioactive) IGF-1 (ng/mL)

// ---------------------------------------------------------------------------
// GROWTH PLATE
// ---------------------------------------------------------------------------
KPROL0    : 0.62  : Intrinsic proliferative-zone recruitment rate (1/day)
KAGE      : 0.032 : Intrinsic age-related decline of proliferation rate (1/yr of bone age)
BA_REF    : 5.0   : Bone age at which KPROL0 is defined (yr)
EMAX_GHD  : 0.58  : Maximal DIRECT GH effect on the resting zone (dual-effector)
GHRREF    : 0.86  : Healthy reference GH-receptor density (normalises the direct growth-plate effect)
EC50_GHD  : 2.2   : Free GH for half-maximal direct resting-zone effect (ug/L)
EMAX_IGF  : 1.15  : Maximal endocrine free-IGF-1 effect on proliferative-zone cycling
EC50_IGF  : 2.60  : Normalised free IGF-1 for half-maximal proliferation (kept well above the healthy operating point so that supraphysiological rhIGF-1 can drive growth without a GH receptor)
EMAX_LOC  : 1.30  : Maximal local (paracrine, GH-dependent) IGF-1 effect on proliferation
EC50_LOC  : 1.00  : Local IGF-1 for half-maximal proliferative effect
FGF_TONE  : 0.35  : FGF18/FGFR3 brake tone on proliferation
PZMAX     : 6.0   : Maximal proliferative zone (normalised; keeps recruitment near-linear)
KDIFF     : 0.50  : Proliferative -> hypertrophic transition rate (1/day)
HYP0      : 1.0   : Baseline hypertrophic cell height (normalised)
EMH       : 0.45  : Maximal IGF-1 amplification of hypertrophic cell height
KREM      : 0.55  : Hypertrophic-zone removal (ossification) rate (1/day)
KHV       : 20.30 : Scale factor: (cell flux x cell height) -> cm/yr
KSEN      : 6.90e-5 : Reserve consumption rate coefficient (1/day)
NSEN      : 1.50  : Superlinearity of reserve consumption in the REALISED growth rate
HVREF_SEN : 6.0   : Age-normal height velocity at which reserve consumption is defined (cm/yr)
KPH0      : 0.50  : Lifetime-average (HV/HVREF_SEN)^NSEN before time 0, at a fully broken GH-growth chain
KPH1      : 4.50  : Additional lifetime-average (HV/HVREF_SEN)^NSEN contributed by an intact chain. KPH0 + KPH1 = 5.0 is far above the age-5 value of ~1 on purpose: infantile growth reaches 25 cm/yr, and at NSEN = 1.5 those first two years dominate the reserve a child has already spent by the time treatment starts
KSEN_E2   : 2.6   : Maximal E2 acceleration of reserve consumption
EC50_SE2  : 30    : E2 for half-maximal reserve-consumption acceleration (pg/mL)
KFUS      : 1.9e-3: Maximal E2-driven epiphyseal-fusion rate (1/day)
EC50_FUS  : 34    : E2 for half-maximal fusion rate (pg/mL)
KFUS0     : 6.0e-5: E2-independent background fusion rate (1/day)

// ---------------------------------------------------------------------------
// BONE AGE AND BONE MINERAL
// ---------------------------------------------------------------------------
KBA0      : 0.60  : GH-independent bone-age advance per chronological year
KBA_E2    : 0.45  : Maximal E2 acceleration of bone-age advance
EC50_BAE2 : 30    : E2 for half-maximal bone-age acceleration (pg/mL)
KBA_GH    : 0.40  : IGF-1-tone contribution to bone-age advance (KBA0 + KBA_GH = 1.0 at the healthy tone)
KBZ_TURN  : 0.004 : Rate at which BMD Z-score approaches its current target (1/day)
KBZ_TONE  : 3.00  : Sensitivity of the BMD target to the IGF-1 tone
IGFARMREF : 0.51  : Healthy reference IGF-1 tone (0-1) for BMD and body-composition targets
KBZ_E2    : 1.20  : Maximal E2 contribution to the BMD target (pubertal mineral accrual)
EC50_BE2  : 26    : E2 for half-maximal bone-mineral accrual (pg/mL)
KBZ_HV    : 0.35  : Transient BMD-for-age penalty during rapid linear growth (mineral accrual lags elongation)
HVREF     : 6.0   : Reference height velocity for the growth-dilution term (cm/yr)
KBZ_GC    : 1.50  : Maximal glucocorticoid penalty on the BMD target
KBZ_AI    : 0.90  : Maximal aromatase-inhibitor penalty on the BMD target (oestrogen-dependent accrual)

// ---------------------------------------------------------------------------
// PUBERTY
// ---------------------------------------------------------------------------
KG_IN     : 0.09  : GnRH pulse-generator activation rate (1/day)
KG_OUT    : 0.09  : GnRH pulse-generator decay rate (1/day)
BA50      : 11.6  : Bone age at half-maximal pubertal activation (yr)
TAUP      : 0.85  : Steepness of pubertal activation (yr)
KLEP      : 0.30  : Adiposity (leptin) permissive effect on pubertal activation
KT_SYN    : 620   : Testosterone synthesis rate at full drive (ng/dL/day)
KT_OUT    : 1.1   : Testosterone elimination rate (1/day)
KARO      : 70    : Aromatase conversion capacity (pg/mL/day)
KMT       : 320   : Testosterone for half-maximal aromatisation (ng/dL)
KOV       : 62    : Ovarian oestradiol synthesis rate at full drive (pg/mL/day)
KOUT_E2   : 1.6   : Oestradiol elimination rate (1/day)

// ---------------------------------------------------------------------------
// BODY COMPOSITION AND INTERMEDIARY METABOLISM
// ---------------------------------------------------------------------------
KFTURN    : 0.010 : Fat-mass turnover rate toward target (1/day)
FMBASE    : 2.90  : Fat-mass scale coefficient (kg at height 100 cm)
ELIP      : 0.85  : Maximal GH suppression of the fat-mass target
EC50_LIP  : 3.0   : Free GH for half-maximal lipolytic effect (ug/L)
KLTURN    : 0.012 : Lean-mass turnover rate toward target (1/day)
LBMBASE   : 12.6  : Lean-mass scale coefficient (kg at height 100 cm)
ELEAN     : 0.30  : Maximal IGF-1 amplification of the lean-mass target
HEXP      : 2.55  : Height exponent for body-mass scaling
KIR_IN    : 0.25  : Insulin-resistance index production rate (1/day)
KIR_OUT   : 0.25  : Insulin-resistance index elimination rate (1/day)
EMAX_IR   : 0.85  : Maximal GH-induced insulin resistance
KIR_FFA   : 0.35  : FFA contribution to insulin resistance
KIR_FM    : 0.55  : Adiposity contribution to insulin resistance
FMPREF    : 19.0  : Reference body-fat percentage
KI_IN     : 1.6   : Insulin secretion rate coefficient (1/day)
KI_OUT    : 1.6   : Insulin elimination rate (1/day)
INSREF    : 5.0   : Reference fasting insulin (uU/mL)
KG_PROD   : 90    : Hepatic glucose production coefficient (mg/dL/day)
KGH_GNG   : 0.30  : Maximal GH amplification of hepatic glucose production
KG_UP     : 1.06  : Glucose disposal rate coefficient (1/day)
KINS_UP   : 0.12  : Insulin sensitivity of glucose disposal (per uU/mL)
KFFA_IN   : 1.5   : FFA appearance rate coefficient (1/day)
EMAX_LIP2 : 1.10  : Maximal GH amplification of FFA appearance
KFFA_OUT  : 4.0   : FFA disposal rate (1/day)
FFAREF    : 0.42  : Reference FFA (mmol/L)
KL_IN     : 130   : LDL-C appearance rate (mg/dL/day)
KL_OUT    : 1.2   : LDL-C clearance rate (1/day)
ELDL      : 0.30  : Maximal GH amplification of LDL-C clearance

// ---------------------------------------------------------------------------
// SAFETY
// ---------------------------------------------------------------------------
KADA_IN   : 0.050 : ADA formation rate under maximal exogenous GH exposure (1/day)
KADA_OUT  : 0.020 : ADA decay rate (1/day)
EC50_EXO  : 500   : Exogenous GH input rate for half-maximal immunogenic drive (ug/day)
KT4_IN    : 1.1   : Free T4 production rate (1/day; set equal to KT4_OUT so that FT4 = FT4REF at negligible GH exposure and falls ~10-15% on rhGH)
KT4_OUT   : 1.1   : Free T4 elimination rate (1/day)
KD2       : 0.32  : Maximal GH-driven increase in T4 -> T3 conversion
THYRCAP   : 1.0   : Thyrotroph capacity (1 = normal; <1 = central hypothyroidism)
FT4REF    : 1.25  : Reference free T4 (ng/dL)
KICP_IN   : 0.25  : Intracranial-pressure index formation rate (1/day)
KICP_OUT  : 0.11  : Intracranial-pressure index resolution rate (1/day)
KICP_ADAPT: 2.5   : Adaptation (tachyphylaxis) strength of the ICP response

[CMT] @annotated
GHRH   : Hypothalamic GHRH tone (normalised)
SST    : Hypothalamic somatostatin tone (normalised)
GHREL  : Ghrelin / GHS-R1a drive (normalised; bolus dosing = provocation test)
PITM   : Somatotroph functional mass (fraction of normal)
GHPOOL : Releasable somatotroph GH granule pool (ug)
GHC    : GH central concentration (ug/L)
GHP    : GH peripheral concentration (ug/L)
GHBP   : GH-binding protein (normalised)
DEPD   : Daily somatropin SC depot (mg)
DEPW   : Weekly long-acting GH SC depot (mg)
PROD   : Circulating long-acting GH carrier / prodrug (mg)
DEPM   : Mecasermin (rhIGF-1) SC depot (mg)
LEUP   : GnRH-analogue concentration (ug/L)
AIC    : Aromatase-inhibitor concentration (ug/L)
GHRc   : Hepatic GH-receptor density (normalised)
PS5    : Phosphorylated STAT5b signal (normalised)
SOCS   : SOCS2 feedback brake (normalised)
IGF1   : Serum total IGF-1 (ng/mL)
BP3    : Serum IGFBP-3 (mg/L)
ALSC   : Acid-labile subunit (normalised)
BP1    : IGFBP-1 (normalised)
IGFL   : Local growth-plate IGF-1 (normalised)
RZ     : Resting-zone proliferative reserve (fraction remaining)
PZ     : Proliferative-zone size (normalised)
HZ     : Hypertrophic-zone height (normalised)
GPS    : Growth-plate fusion program (0 = open, 1 = fused)
HT     : Height (cm)
BA     : Bone age (yr)
BMDZ   : Bone mineral density Z-score
GT     : GnRH pulse-generator activity (normalised)
TST    : Testosterone (ng/dL)
E2     : Oestradiol (pg/mL)
FM     : Fat mass (kg)
LBM    : Lean body mass (kg)
IRES   : Insulin-resistance index (1 = normal)
INS    : Fasting insulin (uU/mL)
GLU    : Fasting glucose (mg/dL)
FFA    : Free fatty acids (mmol/L)
LDL    : LDL-cholesterol (mg/dL)
ADA    : Anti-drug-antibody titre (normalised)
FT4    : Free thyroxine (ng/dL)
ICPX   : Intracranial-pressure index (benign intracranial hypertension risk)

[MAIN]
// ---------------------------------------------------------------------------
// Bioavailability of the SC routes
// ---------------------------------------------------------------------------
F_DEPD = FBIO_D;
F_DEPW = FBIO_W;
F_DEPM = FBIO_M;

// ---------------------------------------------------------------------------
// Initial conditions. Signalling species start at their normalised reference;
// the endocrine/growth states start at values consistent with the aetiology
// parameters, then relax to their own steady state within the first days of
// simulation (run a 60-day lead-in before dosing for a clean baseline).
//
// Guarded by INITMODE: set INITMODE = 0 to keep an externally supplied init()
// vector, which is what makes sequential runs (annual dose titration, treatment
// interruption, transition to adult dosing) carry their state forward instead of
// silently resetting to the covariate-derived baseline.
// ---------------------------------------------------------------------------
if (INITMODE > 0.5) {

double ht0    = ghdref::ht_med(AGE0, SEX);
double htsd0  = ghdref::ht_sd (AGE0, SEX);
double igm0   = ghdref::ig_med(AGE0, SEX);

// How much of the GH -> growth chain is intact? Any lesion counts, not just the
// pituitary: GHR loss (Laron), STAT5b loss and ALS loss all produce a short
// child with an INTACT pituitary, so severity must be read off the whole chain.
double chain  = PITMAX*GHRCAP*STAT5CAP*(0.35 + 0.65*ALSCAP);
double sev    = 1.0 - chain;                        // 0 = normal, ~1 = severe
double htsds0 = MPHSDS - 2.6*sev*(1.0 - exp(-0.30*(AGE0 - 0.5)));

GHRH_0   = 1.0;
SST_0    = 1.0;
GHREL_0  = 1.0;
PITM_0   = PITMAX;
GHPOOL_0 = 260.0*PITMAX + 6.0;
GHC_0    = 0.25 + 2.6*PITMAX;
GHP_0    = GHC_0;
GHBP_0   = 1.0*GHRCAP;
GHRc_0   = GHRCAP;
PS5_0    = 0.15 + 0.85*chain;
SOCS_0   = PS5_0;
BP3_0    = 3.2*(0.30 + 0.70*chain);
ALSC_0   = ALSCAP*(0.30 + 0.70*chain);
BP1_0    = 1.0;
IGFL_0   = 0.20 + 0.80*chain;
IGF1_0   = igm0*(0.30 + 0.70*chain);
// Initial reserve is the SAME consumption law integrated over the child's life
// so far, at the proliferation rate their own aetiology has allowed. A severe
// GHD child has grown slowly and therefore arrives with reserve almost intact —
// this, not a fitted decay function, is where catch-up growth comes from.
double hist_sen = KPH0 + KPH1*chain;   // lifetime-average (HV/HVREF_SEN)^NSEN
RZ_0     = exp(-KSEN*365.0*AGE0*hist_sen);
PZ_0     = 0.45 + 0.55*chain;
HZ_0     = PZ_0;
GPS_0    = 0.0;
HT_0     = ht0 + htsds0*htsd0;
BA_0     = BA0;
BMDZ_0   = MPHSDS - 1.1*sev;
GT_0     = 0.02;
TST_0    = SEX > 0.5 ? 8.0 : 4.0;
E2_0     = 1.5;
LBM_0    = LBMBASE*pow(HT_0/100.0, HEXP)*(0.90 + 0.10*chain);
FM_0     = FMBASE *pow(HT_0/100.0, HEXP)*(1.00 + 0.45*sev);
IRES_0   = 1.0;
INS_0    = 5.0;
GLU_0    = 85.0;
FFA_0    = FFAREF;
LDL_0    = 108.0;
ADA_0    = 0.0;
FT4_0    = FT4REF*(THYRCAP + (1.0 - THYRCAP)*LT4 > 1.0 ? 1.0 : THYRCAP + (1.0 - THYRCAP)*LT4);
ICPX_0   = 0.0;

}   // end INITMODE guard

[ODE]
// ===========================================================================
// 0. Derived quantities used throughout
// ===========================================================================
double AGE  = AGE0 + SOLVERTIME/365.0;              // chronological age (yr)
double WT   = LBM + FM;                             // total body weight (kg)
double WTA  = pow(WT/70.0, 0.75);                   // allometric scalar
double WTL  = WT/70.0;                              // linear (volume) scalar

// GH free fraction: GHBP sequesters GH reversibly.
double FU   = 1.0/(1.0 + GHBP/KD_BP);
double GF   = GHC*FU;                               // free GH (the cleared species)
if (GF < 0) GF = 0;
// NEUTRALISING anti-drug antibodies block receptor binding without accelerating
// clearance. They must therefore act on the PD side: if they were written into
// the free fraction they would cancel exactly, because receptor-mediated
// clearance also acts on free GH, leaving steady-state active GH unchanged.
double GA   = GF/(1.0 + ADA/KADA);                  // ACTIVE (receptor-available) GH

// IGF-1 binding state: the 150-kDa ternary carrier pool sets the free fraction,
// and therefore the CLEARANCE, of total IGF-1 (the second hit in GHD).
double BINDCAP = BP3*ALSC;
double FU_IGF  = 1.0/(1.0 + KB_TERN*BINDCAP + KB_BIN*BP1);
double FIGF    = IGF1*FU_IGF*(0.55 + 0.45*PAPPA2A);  // free/bioactive IGF-1
double FIGFN   = FIGF/FIGFREF;                       // normalised to healthy reference

// Thyroid permissive factor on the growth plate and on bone age. What the
// growth plate sees is the T3-equivalent tissue signal, NOT free T4: GH raises
// type-2 deiodinase activity, so free T4 FALLS on rhGH while tissue T3 is
// preserved. The measured biomarker (FT4) and the growth-relevant signal
// therefore move in opposite directions — which is exactly why an FT4 fall
// after starting rhGH unmasks central hypothyroidism rather than causing it.
double THYR = (FT4/FT4REF)*(1.0 + KD2*GA/(EC50_LIP + GA));
if (THYR > 1.15) THYR = 1.15;
if (THYR < 0.20) THYR = 0.20;

// exogenous bioactive GH input (ug/day) — used for immunogenicity drive
double EXOIN = KA_D*DEPD*1000.0 + KREL*PROD*1000.0*POT_W;

// ===========================================================================
// 1-3. Hypothalamic oscillator
// ===========================================================================
double s    = sin(2.0*M_PI*(SOLVERTIME - PHASE));
double CIRC = 1.0 + AMPC*pow(s > 0 ? s : 0.0, HILLC);

dxdt_GHRH = KIN_GHRH*CIRC*SLEEPQ
            /(1.0 + SST/KI_SST_G)
            *(1.0 + EMAX_GHRL*GHREL/(EC50_GHRL + GHREL))
            /(1.0 + GAIN_IGFG*(FIGFN > 1.0 ? FIGFN - 1.0 : 0.0))
            - KOUT_GHRH*GHRH;

dxdt_SST = KIN_SST*(1.0
             + SL_IGF_S*(FIGFN > 1.0 ? FIGFN - 1.0 : 0.0)
             + SL_GH_S *(GA > 1.2 ? GA/1.2 - 1.0 : 0.0)
             + SL_FFA_S*(FFA > FFAREF ? FFA/FFAREF - 1.0 : 0.0))
           - KOUT_SST*SST;

dxdt_GHREL = KIN_GHRL/(1.0 + INS/KI_INS_GL) - KOUT_GHRL*GHREL;

// ===========================================================================
// 4-5. Somatotroph mass and releasable granule pool
// ===========================================================================
double pitcap = PITMAX > 1e-4 ? PITMAX : 1e-4;
dxdt_PITM = KGROW*PITM*(1.0 - PITM/pitcap) - KDAM*XRT_ON*PITM;

double SIZEC = pow(WT/WTREF, 0.75);        // secretion capacity scales with size
double SYNTH = KSYN_GH*SIZEC*PITM*(1.0 + EMAX_CREB*GHRH/(EC50_CREB + GHRH));
double SECR  = VMAX_SEC*SIZEC*PITM
               *(GHRH/(KM_GHRH + GHRH))
               /(1.0 + SST/KI_SST_S)
               *(GHPOOL/(KM_POOL + GHPOOL));
dxdt_GHPOOL = SYNTH - SECR - KDEG_POOL*GHPOOL;

// ===========================================================================
// 6-8. GH pharmacokinetics (2-compartment, saturable receptor-mediated CL)
// ===========================================================================
double VC   = VC70*WTL;
double VP   = VP70*WTL;
double Q    = Q70*WTA;
double CLGH = CL70*WTA + (CLRMAX*GHRc*WTA)/(KM_CLR + GF);

dxdt_GHC = (SECR + EXOIN)/VC
           - CLGH*GF/VC
           - (Q/VC)*(GHC - GHP);
dxdt_GHP = (Q/VP)*(GHC - GHP);

dxdt_GHBP = KSYN_BP*GHRc - KOUT_BP*GHBP;

// ===========================================================================
// 9-14. Drug kinetics
// ===========================================================================
dxdt_DEPD = -KA_D*DEPD;                              // daily somatropin depot
dxdt_DEPW = -KA_W*DEPW;                              // weekly LAGH depot
dxdt_PROD =  KA_W*DEPW - (KREL + CLP_K)*PROD;        // circulating carrier
dxdt_DEPM = -KA_M*DEPM;                              // mecasermin depot
dxdt_LEUP =  LEUPRATE*1000.0/VLEU - KEL_LEU*LEUP;    // GnRH analogue
dxdt_AIC  =  AIRATE *1000.0/VAI  - KEL_AI *AIC;      // aromatase inhibitor

// ===========================================================================
// 15-17. GHR / pSTAT5b / SOCS2
// ===========================================================================
double OCC = GA/(KD_GHR + GA);

dxdt_GHRc = KSYN_R*GHRCAP/(1.0 + SOCS/KI_SOCS_R)
            - KDEG_R*GHRc*(1.0 + KDOWN*OCC);

dxdt_PS5  = KON_S*OCC*GHRc*STAT5CAP/(1.0 + SOCS/KI_SOCS_S) - KOFF_S*PS5;

dxdt_SOCS = KSYN_SOC*PS5 - KOUT_SOC*SOCS;

// ===========================================================================
// 18-22. IGF system
// ===========================================================================
double ps5h    = pow(PS5 > 0 ? PS5 : 0.0, HS);
// hepatic maturation: circulating IGF-1 rises through childhood at roughly
// constant GH secretion because hepatic synthetic mass grows with the child
double MATIGF  = pow(AGE/AGE_IREF, KMATI);
double SYN_IGF = KSYN_IGF*NUTR*LIVER*MATIGF
                 *(BAS_IGF + (1.0 - BAS_IGF)*ps5h/(pow(KM_S,HS) + ps5h))
                 *(1.0 + EMAX_E2I*E2/(EC50_E2I + E2));

double KE_IGF  = KEF_IGF*FU_IGF + KET_IGF*(1.0 - FU_IGF);

dxdt_IGF1 = SYN_IGF
            + KA_M*DEPM*1000.0/(VD_IGF*WTL)          // mecasermin input
            - KE_IGF*IGF1;

double ps3 = pow(PS5 > 0 ? PS5 : 0.0, H3);
dxdt_BP3  = KSYN_BP3*(BAS_BP3 + (1.0 - BAS_BP3)*ps3/(pow(KM3,H3) + ps3))
            - KOUT_BP3*BP3*(1.0 + KPA*PAPPA2A);

dxdt_ALSC = KSYN_ALS*ALSCAP*(BAS_ALS + (1.0 - BAS_ALS)*PS5/(KMA + PS5)) - KOUT_ALS*ALSC;

dxdt_BP1  = KSYN_BP1/(1.0 + INS/KI_INS_B1) - KOUT_BP1*BP1;

dxdt_IGFL = KSYN_L*PS5/(KML + PS5) - KOUT_L*IGFL;

// ===========================================================================
// 23-27. Growth plate — the multiplicative engine
// ===========================================================================
// (a) the three drives on chondrocyte proliferation
// The direct (dual-effector) GH action on the resting zone still needs a GH
// RECEPTOR, so it is gated by receptor density. This is what separates GH
// DEFICIENCY (low GH, intact receptor) from GH INSENSITIVITY (high GH, no
// receptor): in Laron syndrome the high circulating GH buys nothing.
double DIR_GH = EMAX_GHD*(GHRc/GHRREF)*STAT5CAP*GA/(EC50_GHD + GA);  // direct, resting zone
double DR_IGF = EMAX_IGF*FIGFN/(EC50_IGF + FIGFN);           // endocrine IGF-1
double DR_LOC = EMAX_LOC*IGFL/(EC50_LOC + IGFL);             // paracrine IGF-1
double DRIVE  = DIR_GH + DR_IGF + DR_LOC;

// (b) brakes: FGFR3 tone, glucocorticoid, thyroid permissiveness, ageing
double BRAKE = 1.0/(1.0 + FGF_TONE);
double GCEFF = 1.0/(1.0 + GCDOSE/IC50_GC);
double AGEF  = exp(-KAGE*(BA - BA_REF));

// (c) proliferation rate. Split into the DRIVE per unit reserve and the
// remaining reserve itself, because senescence is spent by the per-cell cycling
// rate (KDRIVE), not by the product. Keeping these separate is what makes the
// initial-reserve formula in [MAIN] and this ODE the same law, so that starting
// a simulation at age 8 gives the same reserve as running from age 5 to 8.
double KDRIVE = DRIVE*BRAKE*GCEFF*THYR*AGEF;
double KPROL  = KPROL0*KDRIVE*RZ;

dxdt_PZ = KPROL*(1.0 - PZ/PZMAX) - KDIFF*PZ;

// (d) hypertrophic cell height, the hypertrophic zone, and height velocity
double IGFARM = (DR_IGF + DR_LOC)/(EMAX_IGF + EMAX_LOC);   // 0-1 IGF-1 tone
double HYPSZ  = HYP0*(1.0 + EMH*IGFARM)*THYR;
double FLUX   = KDIFF*PZ;                                    // cells entering hypertrophy
dxdt_HZ = FLUX*HYPSZ - KREM*HZ;

double OPEN = 1.0 - GPS;
if (OPEN < 0) OPEN = 0;
double HV = KHV*FLUX*HYPSZ*OPEN;                             // cm/yr
dxdt_HT = HV/365.0;

// (e) reserve consumption. Keyed to the REALISED growth rate, not to the drive:
// reserve is spent by cell divisions, and the number of divisions is what
// actually produced the centimetres. This is the term that makes catch-up growth
// self-limiting — a child pushed to 10 cm/yr spends reserve about twice as fast
// as a child growing 6 cm/yr — while leaving a child who is already growing at
// the age-normal rate almost unpenalised. Oestrogen accelerates it on top.
dxdt_RZ = -KSEN*RZ*pow(HV/HVREF_SEN, NSEN)*(1.0 + KSEN_E2*E2/(EC50_SE2 + E2));
if (RZ < 1e-4 && dxdt_RZ < 0) dxdt_RZ = 0.0;

// (f) oestrogen-driven epiphyseal fusion program
dxdt_GPS = (KFUS*E2/(EC50_FUS + E2) + KFUS0)*(1.0 - GPS);

// ===========================================================================
// 28-30. Bone age and bone mineral
// ===========================================================================
// bone age advances with maturation, is accelerated by oestrogen and (modestly,
// saturably) by the IGF-1 tone, is slowed by hypothyroidism, and stops at fusion
double tone = IGFARM/IGFARMREF;  if (tone > 1.8) tone = 1.8;
dxdt_BA = (KBA0
           + KBA_GH*tone
           + KBA_E2*E2/(EC50_BAE2 + E2))*THYR*(1.0 - 0.85*GPS)/365.0;

// BMD Z-score tracks a target set by the IGF-1 tone, oestrogen-driven mineral
// accrual, glucocorticoid/aromatase-inhibitor penalties, MINUS a transient
// penalty proportional to how fast the child is currently growing: newly formed
// bone is under-mineralised, so areal BMD-for-age dips while height velocity is
// supranormal and recovers as the velocity falls. This reproduces the observed
// early-BMD-dip-then-net-gain pattern without a second bone compartment.
double BZTGT = MPHSDS
               + KBZ_TONE*(IGFARM - IGFARMREF)
               + KBZ_E2*E2/(EC50_BE2 + E2)
               - KBZ_HV*(HV/HVREF - 1.0)
               - KBZ_GC*GCDOSE/(IC50_GC + GCDOSE)
               - KBZ_AI*AIC/(IC50_AI + AIC);
dxdt_BMDZ = KBZ_TURN*(BZTGT - BMDZ);

// ===========================================================================
// 31-33. Puberty and the oestrogen clock
// ===========================================================================
double FMPCT = 100.0*FM/(WT > 0.1 ? WT : 0.1);
double MAT   = 1.0/(1.0 + exp(-(BA - BA50)/TAUP));
double gonad = (HYPOGON > 0.5) ? 0.0 : 1.0;

dxdt_GT = KG_IN*MAT*gonad*(1.0 + KLEP*(FMPCT/FMPREF - 1.0))/(1.0 + LEUP/IC50_LEU)
          - KG_OUT*GT;

double AROMA = 1.0/(1.0 + AIC/IC50_AI);

dxdt_TST = KT_SYN*GT*SEX - KT_OUT*TST;
dxdt_E2  = KARO*AROMA*TST/(KMT + TST)
           + KOV*GT*(1.0 - SEX)*AROMA
           + 0.9                                        // small adrenal/extragonadal source
           - KOUT_E2*E2;

// ===========================================================================
// 34-40. Body composition and intermediary metabolism
// ===========================================================================
double LIPO   = ELIP*GA/(EC50_LIP + GA);
double FMTGT  = FMBASE *pow(HT/100.0, HEXP)/(1.0 + LIPO);
double LBMTGT = LBMBASE*pow(HT/100.0, HEXP)*(1.0 + ELEAN*DR_IGF);

dxdt_FM  = KFTURN*(FMTGT - FM);
dxdt_LBM = KLTURN*(LBMTGT - LBM);

dxdt_IRES = KIR_IN*(1.0
              + EMAX_IR*GA/(EC50_LIP + GA)
              + KIR_FFA*(FFA/FFAREF - 1.0)
              + KIR_FM *(FMPCT/FMPREF - 1.0))
            - KIR_OUT*IRES;

dxdt_INS = KI_IN*INSREF*(GLU/85.0)*IRES - KI_OUT*INS;
dxdt_GLU = KG_PROD*(1.0 + KGH_GNG*GA/(EC50_LIP + GA))*(0.5 + 0.5*IRES)
           - KG_UP*GLU*(1.0 + KINS_UP*INS/(IRES > 0.1 ? IRES : 0.1));

dxdt_FFA = KFFA_IN*(1.0 + EMAX_LIP2*GA/(EC50_LIP + GA))*(FM/(FMTGT > 0.1 ? FMTGT : 0.1))
           - KFFA_OUT*FFA;

dxdt_LDL = KL_IN - KL_OUT*LDL*(1.0 + ELDL*GA/(EC50_LIP + GA));

// ===========================================================================
// 41-43. Safety states
// ===========================================================================
dxdt_ADA = KADA_IN*IMGEN*EXOIN/(EC50_EXO + EXOIN) - KADA_OUT*ADA;

// replacement substitutes for what the thyrotroph cannot make
double THYSUP = THYRCAP + (1.0 - THYRCAP)*LT4;
if (THYSUP > 1.0) THYSUP = 1.0;
dxdt_FT4 = KT4_IN*FT4REF*THYSUP
           - KT4_OUT*FT4*(1.0 + KD2*GA/(EC50_LIP + GA));

// early, dose-related and self-limiting (adaptation term in the denominator)
dxdt_ICPX = KICP_IN*(GA/(EC50_LIP + GA))/(1.0 + KICP_ADAPT*ICPX) - KICP_OUT*ICPX;

[TABLE]
// ---------------------------------------------------------------------------
// Clinical read-outs
// ---------------------------------------------------------------------------
double AGEt   = AGE0 + TIME/365.0;
double htmed  = ghdref::ht_med(AGEt, SEX);
double htsd   = ghdref::ht_sd (AGEt, SEX);
double igmed  = ghdref::ig_med(AGEt, SEX);
double igsd   = ghdref::ig_sd (AGEt, SEX);

double fu_t   = 1.0/(1.0 + GHBP/KD_BP);
double gf_t   = GHC*fu_t/(1.0 + ADA/KADA);            // active (receptor-available) GH
double bcap   = BP3*ALSC;
double fuig   = 1.0/(1.0 + KB_TERN*bcap + KB_BIN*BP1);
double figf   = IGF1*fuig*(0.55 + 0.45*PAPPA2A);
double figfn  = figf/FIGFREF;
double thyr_t = (FT4/FT4REF)*(1.0 + KD2*gf_t/(EC50_LIP + gf_t));
if (thyr_t > 1.15) thyr_t = 1.15; if (thyr_t < 0.20) thyr_t = 0.20;

double dir_t  = EMAX_GHD*(GHRc/GHRREF)*STAT5CAP*gf_t/(EC50_GHD + gf_t);
double igf_t  = EMAX_IGF*figfn/(EC50_IGF + figfn);
double loc_t  = EMAX_LOC*IGFL/(EC50_LOC + IGFL);
double hyps_t = HYP0*(1.0 + EMH*(igf_t + loc_t)/(EMAX_IGF + EMAX_LOC))*thyr_t;
double flux_t = KDIFF*PZ;
double open_t = 1.0 - GPS;  if (open_t < 0) open_t = 0;
double sizec_t = pow((LBM + FM)/WTREF, 0.75);
double secr_t  = VMAX_SEC*sizec_t*PITM*(GHRH/(KM_GHRH + GHRH))
                 /(1.0 + SST/KI_SST_S)*(GHPOOL/(KM_POOL + GHPOOL));
double exoin_t = KA_D*DEPD*1000.0 + KREL*PROD*1000.0*POT_W;

capture GH_total     = GHC;                            // ug/L
capture GH_active    = gf_t;                           // ug/L, receptor-available
capture GH_carrier   = PROD;                           // mg (LAGH prodrug)
capture GH_secretion = secr_t;                         // endogenous, ug/day
capture GH_exo_input = exoin_t;                        // exogenous, ug/day
capture pSTAT5b      = PS5;
capture SOCS2        = SOCS;
capture GHR_density  = GHRc;
capture IGF1_total   = IGF1;                           // ng/mL
capture IGF1_free    = figf;                           // ng/mL
capture IGF1_SDS     = (IGF1 - igmed)/igsd;
capture IGFBP3       = BP3;                            // mg/L
capture IGFBP3_SDS   = (BP3 - 3.2)/0.85;
capture ALS_level    = ALSC;
capture Ternary_frac = 1.0 - fuig;
capture Height_cm    = HT;
capture Height_SDS   = (HT - htmed)/htsd;
capture HV_cm_yr     = KHV*flux_t*hyps_t*open_t;
capture Reserve_RZ   = RZ;
capture Fusion_prog  = GPS;
capture Prolif_zone  = PZ;
capture Hyper_zone   = HZ;
capture BoneAge_yr   = BA;
capture Age_yr       = AGEt;
capture BA_CA_ratio  = BA/(AGEt > 0.1 ? AGEt : 0.1);
capture PAH_SDS      = (HT - htmed)/htsd + 0.55*(1.0 - BA/(AGEt > 0.1 ? AGEt : 0.1))*(1.0 - GPS);
capture Target_SDS   = MPHSDS;
capture BMD_Z        = BMDZ;
capture Estradiol    = E2;
capture Testosterone = TST;
capture GnRH_drive   = GT;
capture Weight_kg    = LBM + FM;
capture Fat_mass_kg  = FM;
capture Fat_pct      = 100.0*FM/(LBM + FM);
capture Lean_mass_kg = LBM;
capture Insulin      = INS;
capture Glucose      = GLU;
capture HOMA_IR      = INS*GLU/405.0;
capture FFA_mM       = FFA;
capture LDL_C        = LDL;
capture FreeT4       = FT4;
capture Thyroid_tone = thyr_t;
capture IGF1_tone    = (igf_t + loc_t)/(EMAX_IGF + EMAX_LOC);
capture GH_drive_dir = dir_t;
capture ADA_titre    = ADA;
capture ICP_index    = ICPX;
capture Somatotroph  = PITM;

[CAPTURE]
GH_total GH_active GH_carrier GH_secretion GH_exo_input pSTAT5b SOCS2 GHR_density
IGF1_total IGF1_free IGF1_SDS IGFBP3 IGFBP3_SDS ALS_level Ternary_frac
Height_cm Height_SDS HV_cm_yr Reserve_RZ Fusion_prog Prolif_zone Hyper_zone
BoneAge_yr Age_yr BA_CA_ratio PAH_SDS Target_SDS BMD_Z
Estradiol Testosterone GnRH_drive
Weight_kg Fat_mass_kg Fat_pct Lean_mass_kg
Insulin Glucose HOMA_IR FFA_mM LDL_C FreeT4 Thyroid_tone IGF1_tone GH_drive_dir
ADA_titre ICP_index Somatotroph


##  ============================================================================
##  R-side scenario helpers (read by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(tidyr); library(ggplot2)
##  mod <- mread_cache("ghd_mrgsolve_model.R")
##
##  ## ---- product-specific long-acting GH parameter sets --------------------
##  LAGH <- list(
##    lonapegsomatropin = list(KA_W=0.45, KREL=0.55, CLP_K=0.08, POT_W=1.00,
##                             FBIO_W=0.72, mgkgwk=0.24),
##    somatrogon        = list(KA_W=0.60, KREL=0.58, CLP_K=0.10, POT_W=0.33,
##                             FBIO_W=0.72, mgkgwk=0.66),
##    somapacitan       = list(KA_W=0.50, KREL=0.35, CLP_K=0.05, POT_W=1.45,
##                             FBIO_W=0.72, mgkgwk=0.16)
##  )
##
##  ## ---- event-table helpers ------------------------------------------------
##  ##  `grow` re-titrates the absolute dose by +10%/yr so that mg/kg stays
##  ##  roughly constant as the child grows (real practice re-weighs at every
##  ##  visit). Set grow = 0 to see how much of the year-on-year fall in height
##  ##  velocity is simply dose dilution rather than reserve consumption.
##  daily_gh <- function(mgkgd, WT0, days, adherence = 1, grow = 0.10) {
##    d <- seq(0, days - 1, by = 1)
##    a <- mgkgd*WT0*(1 + grow)^floor(d/365)
##    keep <- if (adherence >= 1) rep(TRUE, length(d)) else
##              (seq_along(d) %% max(1, round(1/adherence))) == 0
##    ev(time = d[keep], amt = a[keep], cmt = "DEPD")
##  }
##  weekly_gh <- function(mgkgwk, WT0, days, grow = 0.10) {
##    d <- seq(0, days - 1, by = 7)
##    ev(time = d, amt = mgkgwk*WT0*(1 + grow)^floor(d/365), cmt = "DEPW")
##  }
##  mecasermin_bid <- function(ugkg, WT0, days, grow = 0.10) {
##    d <- seq(0, days - 0.5, by = 0.5)
##    ev(time = d, amt = ugkg*WT0*(1 + grow)^floor(d/365)/1000, cmt = "DEPM")
##  }
##  none <- ev(amt = 0, cmt = "DEPD")
##
##  ## ---- 19 prebuilt scenarios ---------------------------------------------
##  GHD_simulate_scenarios <- function(years = 4) {
##    D <- round(years*365); W0 <- 15.5
##    lon <- LAGH$lonapegsomatropin; som <- LAGH$somatrogon; spa <- LAGH$somapacitan
##    run <- function(m, e, lab)
##      mrgsim(m, e, end = D, delta = 1, hmax = 0.25) %>% as_tibble() %>%
##        filter(!duplicated(time, fromLast = TRUE)) %>% mutate(scenario = lab)
##
##    bind_rows(
##      run(mod, none, "01 Untreated severe GHD"),
##      run(param(mod, PITMAX = 1.0, BA0 = 5.0), none, "02 Healthy reference child"),
##      run(mod, daily_gh(0.025, W0, D), "03 Daily somatropin 0.025 mg/kg/d"),
##      run(mod, daily_gh(0.034, W0, D), "04 Daily somatropin 0.034 mg/kg/d"),
##      run(mod, daily_gh(0.050, W0, D), "05 Daily somatropin 0.050 mg/kg/d"),
##      run(param(mod, lon[1:5]), weekly_gh(lon$mgkgwk, W0, D),
##          "06 Weekly lonapegsomatropin 0.24 mg/kg/wk"),
##      run(param(mod, som[1:5]), weekly_gh(som$mgkgwk, W0, D),
##          "07 Weekly somatrogon 0.66 mg/kg/wk"),
##      run(param(mod, spa[1:5]), weekly_gh(spa$mgkgwk, W0, D),
##          "08 Weekly somapacitan 0.16 mg/kg/wk"),
##      run(param(mod, AGE0 = 10, BA0 = 8.4), daily_gh(0.034, 25, D),
##          "09 Late start at age 10 (same dose)"),
##      run(mod, daily_gh(0.034, W0, D, adherence = 0.6),
##          "10 Daily somatropin, 60% adherence"),
##      run(param(mod, PITMAX = 1.0, GHRCAP = 0.05), none,
##          "11 GH insensitivity (Laron), untreated"),
##      run(param(mod, PITMAX = 1.0, GHRCAP = 0.05), mecasermin_bid(100, W0, D),
##          "12 Laron + mecasermin 100 ug/kg BID"),
##      run(param(mod, IMGEN = 1), daily_gh(0.034, W0, D),
##          "13 Daily somatropin + neutralising ADA"),
##      run(param(mod, AGE0 = 12, BA0 = 12.4), daily_gh(0.034, 38, D),
##          "14 Pubertal start, GH alone"),
##      run(param(mod, AGE0 = 12, BA0 = 12.4, LEUPRATE = 0.134),
##          daily_gh(0.034, 38, D), "15 Pubertal GH + GnRH analogue"),
##      run(param(mod, AGE0 = 12, BA0 = 12.4, AIRATE = 1.0),
##          daily_gh(0.034, 38, D), "16 Pubertal GH + aromatase inhibitor"),
##      run(param(mod, THYRCAP = 0.45, LT4 = 0), daily_gh(0.034, W0, D),
##          "17 GH with unreplaced central hypothyroidism"),
##      run(param(mod, GCDOSE = 12), daily_gh(0.034, W0, D),
##          "18 GH on high-dose glucocorticoid"),
##      run(param(mod, ALSCAP = 0.05), none, "19 IGFALS (ALS) deficiency")
##    )
##  }
##
##  ## ---- IGF-1-SDS-titrated dosing (closed loop, annual review) ------------
##  ##  This is the clinical algorithm: review IGF-1 SDS once a year and move the
##  ##  dose toward a target band, never above +2 SDS.
##  GHD_titrate <- function(years = 4, target = 1.0, start = 0.034) {
##    D <- 365; W0 <- 15.5; dose <- start; m <- mod; out <- list()
##    cmts <- outvars(mod)$cmt
##    for (yr in seq_len(years)) {
##      s <- mrgsim(m, daily_gh(dose, W0, D, grow = 0), end = D, delta = 1,
##                  hmax = 0.25) %>% as_tibble() %>%
##             filter(!duplicated(time, fromLast = TRUE))
##      out[[yr]] <- mutate(s, year = yr, dose_mgkgd = dose)
##      last <- tail(s, 1)
##      dose <- min(max(dose*(1 + 0.35*(target - last$IGF1_SDS)), 0.015), 0.070)
##      m  <- init(m, as.list(last[, cmts]))          # carry the state forward
##      m  <- param(m, AGE0 = last$Age_yr, BA0 = last$BoneAge_yr, INITMODE = 0)
##      W0 <- last$Weight_kg
##    }
##    bind_rows(out)
##  }
##
##  ## ---- short-horizon uses -----------------------------------------------
##  ##  (a) GH provocation test — a bolus into the GHREL compartment stands in for
##  ##      any secretagogue (arginine, clonidine, glucagon, macimorelin):
##  ##        mrgsim(mod, ev(amt = 25, cmt = "GHREL"), end = 0.25, delta = 0.001)
##  ##      severe GHD ~0.4, partial GHD (PITMAX = 0.35) ~2.2, normal ~10 ug/L
##  ##  (b) single-dose PK, daily vs weekly:
##  ##        mrgsim(mod, ev(amt = 0.53, cmt = "DEPD"), end = 2,  delta = 0.005)
##  ##        mrgsim(param(mod, LAGH$lonapegsomatropin[1:5]),
##  ##               ev(amt = 3.72, cmt = "DEPW"), end = 21, delta = 0.02)
##  ##  (c) the sampling-day problem for weekly products — run three weekly doses
##  ##      and read IGF1_SDS on day 2 versus day 7 of the interval.
##  ##
##  ##  Use hmax = 0.25 on multi-year runs so the 24-h circadian term in the GHRH
##  ##  drive is not stepped over. Set AMPC = 0 to switch circadian modulation off
##  ##  for faster long-horizon screening.
##  ##
##  ## ---- quick look --------------------------------------------------------
##  ##  df <- GHD_simulate_scenarios(4)
##  ##  ggplot(df, aes(Age_yr, Height_SDS, colour = scenario)) + geom_line()
##  ##  ggplot(df, aes(Age_yr, HV_cm_yr,   colour = scenario)) + geom_line()
##  ##  ggplot(df, aes(Age_yr, IGF1_SDS,   colour = scenario)) + geom_line() +
##  ##    geom_hline(yintercept = 2, linetype = 2)   # the safety cap
##  ##  ggplot(df, aes(Age_yr, Reserve_RZ, colour = scenario)) + geom_line()
