## =====================================================================
##  Refractory Chronic Cough (RCC) — Shiny dashboard
##  rcc_shiny_app.R
## ---------------------------------------------------------------------
##  Interactive front end for rcc_mrgsolve_model.R.
##
##  The app is organised around the one question the model exists to
##  answer: WHICH LAYER OF THE COUGH REFLEX ARC IS A GIVEN THERAPY
##  ACTING ON, and what can that layer possibly deliver?
##
##    Tab 1  Patient        build a virtual patient, watch the disease be
##                          GENERATED by natural history rather than assigned
##    Tab 2  Cough diary    24-h and awake cough frequency, circadian profile
##    Tab 3  Reflex arc     peripheral gain / central gain / threshold —
##                          the three layers, plotted against each other
##    Tab 4  PK & target    plasma concentration, P2X3 occupancy, ATP
##                          competition
##    Tab 5  Endpoints      LCQ, VAS, CSD, urge, responder status
##    Tab 6  Therapeutic    THE HEADLINE: efficacy and dysgeusia as two
##           window         readouts of one occupancy curve, swept over
##                          four decades of selectivity
##    Tab 7  Scenarios      all 25 scenarios side by side
##    Tab 8  Trial view     placebo-adjusted effects against published
##                          results, with the misfits shown not hidden
##    Tab 9  Challenges     capsaicin C5 vs ATP threshold dissociation
##    Tab 10 Biomarkers     ATP, NGF, P2X3 density, wind-up, microglia
##
##  Run with:  shiny::runApp("rcc_shiny_app.R")
## =====================================================================

suppressPackageStartupMessages({
  library(shiny)
  library(ggplot2)
})

## The model file defines mod, the phenotypes, the event builders, run(),
## daily(), the scenario list and every diagnostic. Sourcing it compiles
## the model once at start-up.
source("rcc_mrgsolve_model.R")

THEME <- theme_minimal(base_size = 12) +
  theme(panel.grid.minor = element_blank(),
        strip.text = element_text(face = "bold"),
        legend.position = "bottom")

PAL <- c(placebo = "#90A4AE", active = "#1565C0", second = "#00897B",
         warn = "#E64A19", grey = "#B0BEC5")

## ---------------------------------------------------------------------
##  UI
## ---------------------------------------------------------------------
ui <- fluidPage(
  titlePanel("Refractory Chronic Cough — QSP model (cough hypersensitivity syndrome)"),
  tags$p(style = "color:#555;margin-top:-8px;",
         "Peripheral gain → central gain → cortical control. ",
         tags$b("Every drug acts on exactly one layer, and the layer decides which endpoint it can move.")),

  sidebarLayout(
    sidebarPanel(
      width = 3,
      h4("Patient"),
      selectInput("phen", "Phenotype",
                  choices = c("Refractory chronic cough" = "rcc",
                              "Healthy control" = "healthy",
                              "Post-infectious (resolves)" = "postviral",
                              "Male" = "male",
                              "Eosinophilic (NAEB / CVA)" = "eos",
                              "Acid reflux" = "acid",
                              "Non-acid reflux" = "nonacid",
                              "ACE-inhibitor cough" = "acei",
                              "IPF-associated cough" = "ipf",
                              "Upper airway cough syndrome" = "uacs",
                              "Registration-trial population" = "trial",
                              "High-baseline stratum (SOOTHE)" = "highbl"),
                  selected = "trial"),
      sliderInput("lgain", "Host loop gain (susceptibility)",
                  0.4, 1.3, 1.0, step = 0.05),
      sliderInput("estro", "Oestrogen status (1 = pre-, 0.3 = postmenopausal)",
                  0.2, 1.0, 0.3, step = 0.05),
      sliderInput("prerun", "Disease duration before enrolment (weeks)",
                  4, 260, 104, step = 4),

      hr(), h4("Therapy"),
      selectInput("drug", "Drug",
                  choices = c("None (placebo arm)" = "none",
                              "Gefapixant" = "gef",
                              "Camlipixant" = "cam",
                              "Eliapixant" = "eli",
                              "Sivopixant" = "siv",
                              "Gabapentin" = "gab",
                              "Pregabalin" = "pre",
                              "Morphine SR" = "mor",
                              "Nalbuphine ER" = "nal",
                              "Amitriptyline" = "ami",
                              "Inhaled corticosteroid" = "ics",
                              "Proton pump inhibitor" = "ppi",
                              "Dextromethorphan" = "dxm"),
                  selected = "gef"),
      uiOutput("dose_ui"),
      checkboxInput("slt", "Add speech & language therapy", FALSE),
      checkboxInput("cbt", "Add CBT for cough catastrophising", FALSE),
      sliderInput("weeks", "Trial duration (weeks)", 4, 52, 12, step = 2),

      hr(), h4("Mechanism knobs"),
      sliderInput("wp2x", "P2X3 share of tussive drive",
                  0.01, 0.35, 0.047, step = 0.005),
      sliderInput("sel", "P2X3 : P2X2/3 selectivity (gefapixant)",
                  1, 2000, 6, step = 1),
      sliderInput("kdrop", "Discontinuation hazard per unit dysgeusia",
                  0, 0.02, 0.0005, step = 0.0005),
      helpText("The first two are the therapeutic window. The third is",
               "what turns efficacy into effectiveness.")
    ),

    mainPanel(
      width = 9,
      tabsetPanel(
        id = "tabs",
        tabPanel("1 · Patient",       br(), plotOutput("p_nat", height = "380px"),
                                      br(), tableOutput("t_base")),
        tabPanel("2 · Cough diary",   br(), plotOutput("p_diary", height = "320px"),
                                      br(), plotOutput("p_circ", height = "260px")),
        tabPanel("3 · Reflex arc",    br(), plotOutput("p_arc", height = "380px"),
                                      br(), htmlOutput("txt_arc")),
        tabPanel("4 · PK & target",   br(), plotOutput("p_pk", height = "320px"),
                                      br(), plotOutput("p_occ", height = "280px")),
        tabPanel("5 · Endpoints",     br(), plotOutput("p_pro", height = "380px"),
                                      br(), tableOutput("t_pro")),
        tabPanel("6 · Therapeutic window", br(), plotOutput("p_win", height = "400px"),
                                      br(), tableOutput("t_win")),
        tabPanel("7 · Scenarios",     br(), plotOutput("p_scen", height = "460px")),
        tabPanel("8 · Trial view",    br(), tableOutput("t_val"),
                                      br(), htmlOutput("txt_val")),
        tabPanel("9 · Challenges",    br(), plotOutput("p_chal", height = "340px"),
                                      br(), htmlOutput("txt_chal")),
        tabPanel("10 · Biomarkers",   br(), plotOutput("p_bio", height = "420px"))
      )
    )
  )
)

## ---------------------------------------------------------------------
##  SERVER
## ---------------------------------------------------------------------
server <- function(input, output, session) {

  PHEN <- list(rcc = pat_rcc, healthy = pat_healthy, postviral = pat_postviral,
               male = pat_male, eos = pat_eos, acid = pat_acid,
               nonacid = pat_nonacid, acei = pat_acei, ipf = pat_ipf,
               uacs = pat_uacs, trial = pat_trial, highbl = pat_highbl)

  DOSES <- list(
    gef = list(label = "Gefapixant (mg BID)",       choices = c(15, 30, 45), sel = 45),
    cam = list(label = "Camlipixant (mg BID)",      choices = c(12.5, 25, 50, 100), sel = 50),
    eli = list(label = "Eliapixant (mg BID)",       choices = c(25, 75, 150), sel = 75),
    siv = list(label = "Sivopixant (mg QD)",        choices = c(50, 150, 300), sel = 150),
    gab = list(label = "Gabapentin (mg TID)",       choices = c(200, 400, 600), sel = 600),
    pre = list(label = "Pregabalin (mg BID)",       choices = c(75, 150, 300), sel = 150),
    mor = list(label = "Morphine SR (mg BID)",      choices = c(5, 10, 20), sel = 10),
    nal = list(label = "Nalbuphine ER (mg BID)",    choices = c(27, 54, 108, 162), sel = 108),
    ami = list(label = "Amitriptyline (mg nocte)",  choices = c(10, 25, 50), sel = 25),
    ics = list(label = "ICS (ug BID)",              choices = c(200, 400, 800), sel = 400),
    ppi = list(label = "PPI (mg OD)",               choices = c(20, 40, 80), sel = 40),
    dxm = list(label = "Dextromethorphan (mg QID)", choices = c(15, 30, 60), sel = 30))

  output$dose_ui <- renderUI({
    d <- DOSES[[input$drug]]
    if (is.null(d)) return(NULL)
    selectInput("dose", d$label, choices = d$choices, selected = d$sel)
  })

  patient <- reactive({
    p <- PHEN[[input$phen]]
    p$LGAIN <- input$lgain
    p$ESTRO <- input$estro
    p$WP2X  <- input$wp2x
    ## keep the four afferent weights summing to 1 as the P2X3 share moves
    spare <- 1 - input$wp2x
    p$WTRP <- spare * 0.44; p$WMEC <- spare * 0.375; p$WACI <- spare * 0.185
    p$GEF_SEL <- input$sel
    p$KDROP   <- input$kdrop
    p
  })

  extra_params <- reactive({
    l <- list()
    if (input$slt) l$ESLT <- 0.42
    if (input$cbt) l$ECBT <- 0.30
    l
  })

  event <- reactive({
    if (input$drug == "none" || is.null(input$dose)) return(NULL)
    dz <- as.numeric(input$dose); dur <- input$weeks * 7
    switch(input$drug,
           gef = ev_gefapixant(dz, dur),  cam = ev_camlipixant(dz, dur),
           eli = ev_eliapixant(dz, dur),  siv = ev_sivopixant(dz, dur),
           gab = ev_gabapentin(dz, dur),  pre = ev_pregabalin(dz, dur),
           mor = ev_morphine(dz, dur),    nal = ev_nalbuphine(dz, dur),
           ami = ev_amitrip(dz, dur),     ics = ev_ics(dz, dur),
           ppi = ev_ppi(dz, dur),         dxm = ev_dxm(dz, dur), NULL)
  })

  prerun_days <- reactive(round(input$prerun * 7))

  ## The pre-run is the expensive step, so it is cached on the patient and
  ## the disease duration only, and shared by the active and placebo arms.
  ic <- reactive({
    withProgress(message = "Generating the disease from natural history...",
                 value = 0.5, settle(patient(), prerun_days()))
  })

  sim_active <- reactive({
    run(patient(), extra_params(), event(),
        days = input$weeks * 7, ic = ic(), trial = TRUE)
  })
  sim_placebo <- reactive({
    run(patient(), extra_params(), NULL,
        days = input$weeks * 7, ic = ic(), trial = TRUE)
  })
  d_active  <- reactive(daily(sim_active()))
  d_placebo <- reactive(daily(sim_placebo()))

  arm_frame <- reactive({
    a <- d_active(); p <- d_placebo()
    a$arm <- if (input$drug == "none") "active (no drug)" else "active"
    p$arm <- "placebo"
    rbind(a, p)
  })

  ## ---- Tab 1: natural history -------------------------------------
  output$p_nat <- renderPlot({
    o <- run(patient(), list(), NULL, days = prerun_days(), trial = FALSE,
             prerun = 0, tgrid = seq(0, prerun_days(), 0.5))
    d <- daily(o)
    ggplot(d, aes(day / 7, cf24)) +
      geom_line(colour = PAL["active"], linewidth = 0.9) +
      labs(title = "The disease is generated, not assigned",
           subtitle = paste0("A healthy subject receives the insult at week 0. ",
                             "Whatever cough they have at enrolment is what the model gave them."),
           x = "weeks since the insult", y = "24-h cough frequency (coughs/h)") + THEME
  })

  output$t_base <- renderTable({
    b <- at_day(d_placebo(), 1)
    data.frame(
      Quantity = c("24-h cough frequency (coughs/h)", "Awake cough frequency (coughs/h)",
                   "Leicester Cough Questionnaire (3-21)", "Cough severity VAS (mm)",
                   "Cough Severity Diary (0-10)", "Urge to cough (0-10)",
                   "Peripheral gain", "Central gain", "Wind-up",
                   "P2X3 receptor density", "Ectopic discharge",
                   "Capsaicin C5 (uM)"),
      Value = c(round(b$cf24, 1), round(b$cfawk, 1), round(b$LCQ, 1),
                round(b$VAS), round(b$CSD, 1), round(b$URG, 1),
                round(b$LOOP, 2), round(b$CENG, 2), round(b$WIND, 2),
                round(b$P2X3E, 2), round(b$ECTO, 2), round(b$C5, 1)))
  }, digits = 2)

  ## ---- Tab 2: cough diary ------------------------------------------
  output$p_diary <- renderPlot({
    ggplot(arm_frame(), aes(day / 7, cf24, colour = arm)) +
      geom_line(linewidth = 0.9) +
      scale_colour_manual(values = c("placebo" = unname(PAL["placebo"]),
                                     "active" = unname(PAL["active"]),
                                     "active (no drug)" = unname(PAL["placebo"]))) +
      labs(title = "24-h cough frequency, active vs placebo arm",
           subtitle = paste("The placebo arm carries the enrolment flare, the trial-participation",
                            "effect on cortical suppression, and natural resolution."),
           x = "weeks on treatment", y = "coughs / hour", colour = NULL) + THEME
  })

  output$p_circ <- renderPlot({
    o <- run(patient(), extra_params(), event(), days = 3, ic = ic(),
             trial = TRUE, tgrid = seq(0, 3, 1 / 96))
    o <- o[o$time >= 1 & o$time < 3, ]
    o$clock <- ((o$time %% 1) * 24 + 7) %% 24
    ggplot(o, aes(time * 24 - 24, CFQ)) +
      geom_area(fill = "#BBDEFB", colour = PAL["active"]) +
      labs(title = "Circadian structure (two days), emergent not imposed",
           subtitle = paste("Cough nearly stops in sleep because the cortical urge pathway is offline;",
                            "the morning rise follows overnight mucus accumulation."),
           x = "hours from 07:00", y = "coughs / hour") + THEME
  })

  ## ---- Tab 3: the three layers -------------------------------------
  output$p_arc <- renderPlot({
    a <- arm_frame()
    long <- rbind(
      data.frame(day = a$day, arm = a$arm, layer = "1 · peripheral gain", value = a$AFIR),
      data.frame(day = a$day, arm = a$arm, layer = "2 · central gain",    value = a$CENG),
      data.frame(day = a$day, arm = a$arm, layer = "2 · wind-up",         value = a$WIND),
      data.frame(day = a$day, arm = a$arm, layer = "3 · cortical suppression", value = a$CORT))
    ggplot(long, aes(day / 7, value, colour = arm)) +
      geom_line(linewidth = 0.9) + facet_wrap(~layer, scales = "free_y") +
      scale_colour_manual(values = c("placebo" = unname(PAL["placebo"]),
                                     "active" = unname(PAL["active"]),
                                     "active (no drug)" = unname(PAL["placebo"]))) +
      labs(x = "weeks", y = NULL, colour = NULL,
           title = "The three layers of the reflex arc") + THEME
  })

  output$txt_arc <- renderUI(HTML(paste0(
    "<p><b>Read this panel as a diagnosis of the therapy, not of the patient.</b> ",
    "A P2X3 antagonist moves layer 1 and only what layer 1 feeds. ",
    "Gabapentin and morphine move layer 2. Speech therapy moves layer 3 and moves ",
    "nothing else &mdash; and note that the placebo arm moves layer 3 too, which is ",
    "why the placebo response in this disease is so large.</p>")))

  ## ---- Tab 4: PK and target engagement ------------------------------
  output$p_pk <- renderPlot({
    o <- sim_active()
    conc <- switch(input$drug, gef = o$Cgefo, cam = o$Ccamo, eli = o$Celio,
                   siv = o$Csivo, gab = o$Cgabo, mor = o$Cmoro, NULL)
    if (is.null(conc) || max(conc, na.rm = TRUE) <= 0) {
      return(ggplot() + annotate("text", 0, 0,
        label = "No plasma-concentration output for this arm") + theme_void())
    }
    w <- min(14, input$weeks * 7)
    k <- o$time <= w
    ggplot(data.frame(t = o$time[k], C = conc[k]), aes(t, C)) +
      geom_line(colour = PAL["active"], linewidth = 0.7) +
      labs(title = "Plasma concentration (first 2 weeks)",
           x = "days", y = "mg / L") + THEME
  })

  output$p_occ <- renderPlot({
    a <- d_active()
    long <- rbind(
      data.frame(day = a$day, curve = "P2X3 homotrimer (EFFICACY)",   value = a$OCC3),
      data.frame(day = a$day, curve = "P2X2/3 heterotrimer (TASTE)",  value = a$OCC23),
      data.frame(day = a$day, curve = "adherence remaining",          value = a$ADHR))
    ggplot(long, aes(day / 7, value, colour = curve)) +
      geom_line(linewidth = 0.9) + ylim(0, 1) +
      scale_colour_manual(values = c(unname(PAL["warn"]), unname(PAL["active"]),
                                     unname(PAL["grey"]))) +
      labs(title = "One drug, two receptors, one selectivity ratio",
           subtitle = "The gap between the two occupancy curves IS the therapeutic window.",
           x = "weeks", y = "occupancy / fraction", colour = NULL) + THEME
  })

  ## ---- Tab 5: endpoints ---------------------------------------------
  output$p_pro <- renderPlot({
    a <- arm_frame()
    long <- rbind(
      data.frame(day = a$day, arm = a$arm, pro = "LCQ (3-21, higher better)", value = a$LCQ),
      data.frame(day = a$day, arm = a$arm, pro = "Cough VAS (mm)",            value = a$VAS),
      data.frame(day = a$day, arm = a$arm, pro = "Cough Severity Diary (0-10)", value = a$CSD),
      data.frame(day = a$day, arm = a$arm, pro = "Urge to cough (0-10)",      value = a$URG))
    ggplot(long, aes(day / 7, value, colour = arm)) +
      geom_line(linewidth = 0.9) + facet_wrap(~pro, scales = "free_y") +
      scale_colour_manual(values = c("placebo" = unname(PAL["placebo"]),
                                     "active" = unname(PAL["active"]),
                                     "active (no drug)" = unname(PAL["placebo"]))) +
      labs(x = "weeks", y = NULL, colour = NULL,
           title = "Patient-reported outcomes (2-week recall, so they LAG the counts)") + THEME
  })

  output$t_pro <- renderTable({
    wk <- input$weeks * 7
    a <- d_active(); p <- d_placebo()
    a0 <- at_day(a, 1); a1 <- at_day(a, wk)
    p0 <- at_day(p, 1); p1 <- at_day(p, wk)
    rr <- (a1$cf24 / a0$cf24) / (p1$cf24 / p0$cf24)
    data.frame(
      Endpoint = c("24-h cough frequency, ratio vs placebo",
                   "24-h cough frequency, % vs placebo",
                   "LCQ change vs placebo (MCID 1.3)",
                   "Cough VAS change vs placebo (mm)",
                   "CSD change vs placebo (MCID 1.3)",
                   "Taste-related adverse events (%)",
                   "Still on treatment at end (%)",
                   "LCQ responder (>= 1.3)?"),
      Value = c(sprintf("%.3f", rr), sprintf("%+.1f%%", 100 * (rr - 1)),
                sprintf("%+.2f", (a1$LCQ - a0$LCQ) - (p1$LCQ - p0$LCQ)),
                sprintf("%+.1f", (a1$VAS - a0$VAS) - (p1$VAS - p0$VAS)),
                sprintf("%+.2f", (a1$CSD - a0$CSD) - (p1$CSD - p0$CSD)),
                sprintf("%.0f", a1$TASTEAE), sprintf("%.0f", 100 * a1$ADHR),
                ifelse((a1$LCQ - a0$LCQ) - (p1$LCQ - p0$LCQ) >= 1.3, "YES", "no")))
  })

  ## ---- Tab 6: the therapeutic window --------------------------------
  win <- reactive({
    withProgress(message = "Sweeping selectivity over four decades...", value = 0.5, {
      sels <- c(1, 3, 6, 10, 30, 70, 150, 400, 1500, 5000)
      icx <- ic(); wk <- input$weeks
      pl <- daily(run(patient(), extra_params(), NULL, days = wk * 7, ic = icx))
      plb <- at_day(pl, 1)$cf24; plw <- at_day(pl, wk * 7)$cf24
      do.call(rbind, lapply(sels, function(s) {
        d <- daily(run(patient(), modifyList(extra_params(), list(GEF_SEL = s)),
                       ev_gefapixant(45, wk * 7), days = wk * 7, ic = icx))
        a <- at_day(d, 1); b <- at_day(d, wk * 7)
        data.frame(selectivity = s,
                   efficacy = -100 * ((b$cf24 / a$cf24) / (plw / plb) - 1),
                   taste = b$TASTEAE, adherence = 100 * b$ADHR)
      }))
    })
  })

  output$p_win <- renderPlot({
    w <- win()
    ggplot(w, aes(selectivity)) +
      geom_line(aes(y = efficacy, colour = "cough reduction vs placebo (%)"), linewidth = 1.1) +
      geom_point(aes(y = efficacy, colour = "cough reduction vs placebo (%)"), size = 2) +
      geom_line(aes(y = taste, colour = "taste-related adverse events (%)"), linewidth = 1.1) +
      geom_point(aes(y = taste, colour = "taste-related adverse events (%)"), size = 2) +
      geom_vline(xintercept = c(6, 40, 70, 1500), linetype = 3, colour = "grey55") +
      annotate("text", x = 6, y = 78, label = "gefapixant", angle = 90,
               vjust = -0.4, size = 3.2, colour = "grey30") +
      annotate("text", x = 70, y = 78, label = "eliapixant", angle = 90,
               vjust = -0.4, size = 3.2, colour = "grey30") +
      annotate("text", x = 1500, y = 78, label = "camlipixant", angle = 90,
               vjust = -0.4, size = 3.2, colour = "grey30") +
      scale_x_log10() +
      scale_colour_manual(values = c(unname(PAL["active"]), unname(PAL["warn"]))) +
      labs(title = "THE THERAPEUTIC WINDOW — one drug, one dose, selectivity swept",
           subtitle = paste("Efficacy is nearly flat across four decades of selectivity while",
                            "dysgeusia collapses. The taste system has no receptor reserve,",
                            "\nwhich is why 6-fold selectivity is not remotely enough."),
           x = "P2X3 : P2X2/3 selectivity ratio (log scale)",
           y = "percent", colour = NULL) + THEME
  })

  output$t_win <- renderTable(win(), digits = 1)

  ## ---- Tab 7: scenarios ---------------------------------------------
  output$p_scen <- renderPlot({
    withProgress(message = "Running all 25 scenarios...", value = 0.4, {
      res <- run_all(days = input$weeks * 7, verbose = FALSE)
      g <- endpoints(res, input$weeks)
      g$id <- factor(g$id, levels = rev(g$id))
      ggplot(g, aes(pct_change, id, fill = pct_change < 0)) +
        geom_col() +
        geom_vline(xintercept = 0, colour = "grey40") +
        scale_fill_manual(values = c("TRUE" = unname(PAL["active"]),
                                     "FALSE" = unname(PAL["warn"])), guide = "none") +
        labs(title = paste0("Change in 24-h cough frequency at week ", input$weeks,
                            " (each arm vs its own baseline)"),
             subtitle = "S03 is the placebo arm. Everything above it is a real drug effect; S17 and S19 are the deliberate nulls.",
             x = "% change from baseline", y = NULL) + THEME
    })
  })

  ## ---- Tab 8: trial view ---------------------------------------------
  output$t_val <- renderTable({
    withProgress(message = "Reproducing published trials...", value = 0.4,
                 validate_trials())
  })

  output$txt_val <- renderUI(HTML(paste0(
    "<p><b>Read the misfits, not only the fits.</b> The model was anchored on ",
    "COUGH-1 at 12 weeks and reproduces it almost exactly (&minus;18.6% modelled ",
    "vs &minus;18.5% observed), together with gabapentin, morphine, pregabalin, ",
    "nalbuphine in IPF cough, and the two deliberate nulls (ICS without ",
    "eosinophils, PPI without acid). It is wrong in opposite directions on ",
    "COUGH-2 at 24 weeks (too strong) and SOOTHE at 4 weeks (too weak), because ",
    "its treatment effect builds too slowly and then keeps growing where the real ",
    "class plateaus by about a month. It also cannot reproduce the gefapixant ",
    "15 mg cliff &mdash; no occupancy-based model can. Those are missing ",
    "mechanisms, and they are listed in the model file rather than tuned away.</p>")))

  ## ---- Tab 9: challenge tests -----------------------------------------
  output$p_chal <- renderPlot({
    withProgress(message = "Running challenge tests...", value = 0.5, {
      ch <- check_challenges(week = min(4, input$weeks))
      long <- rbind(
        data.frame(arm = ch$arm, test = "capsaicin C5 (TRPV1 — bypasses P2X3)",
                   fold = ch$capsaicin_C5_fold),
        data.frame(arm = ch$arm, test = "inhaled ATP threshold (P2X3)",
                   fold = ch$ATP_threshold_fold))
      ggplot(long, aes(arm, fold, fill = test)) +
        geom_col(position = "dodge") +
        geom_hline(yintercept = 1, linetype = 2, colour = "grey40") +
        scale_fill_manual(values = c(unname(PAL["grey"]), unname(PAL["active"]))) +
        labs(title = "The diagnostic signature of the P2X3 class",
             subtitle = "Predicted, not assumed: it follows from where each agonist enters the afferent equation.",
             x = NULL, y = "fold change in cough threshold", fill = NULL) + THEME
    })
  })

  output$txt_chal <- renderUI(HTML(paste0(
    "<p>Capsaicin gates TRPV1 directly and never touches P2X3, so a P2X3 ",
    "antagonist barely shifts capsaicin C5 while it clearly shifts the inhaled-ATP ",
    "threshold. That is the observed behaviour of the class and it is the reason ",
    "capsaicin challenge is a poor pharmacodynamic biomarker for these drugs. ",
    "<b>Caveat:</b> the modelled ATP shift (about 1.1&ndash;1.2 fold) is much ",
    "smaller than the near-log-order shifts reported experimentally, so read the ",
    "direction and the dissociation, not the magnitude.</p>")))

  ## ---- Tab 10: biomarkers ----------------------------------------------
  output$p_bio <- renderPlot({
    a <- arm_frame()
    long <- rbind(
      data.frame(day = a$day, arm = a$arm, marker = "P2X3 receptor density", value = a$P2X3E),
      data.frame(day = a$day, arm = a$arm, marker = "nTS wind-up",           value = a$WIND),
      data.frame(day = a$day, arm = a$arm, marker = "Ectopic discharge",     value = a$ECTO),
      data.frame(day = a$day, arm = a$arm, marker = "Loop gain",             value = a$LOOP),
      data.frame(day = a$day, arm = a$arm, marker = "Capsaicin C5 (uM)",     value = a$C5),
      data.frame(day = a$day, arm = a$arm, marker = "Complication burden",   value = a$COMP))
    ggplot(long, aes(day / 7, value, colour = arm)) +
      geom_line(linewidth = 0.9) + facet_wrap(~marker, scales = "free_y") +
      scale_colour_manual(values = c("placebo" = unname(PAL["placebo"]),
                                     "active" = unname(PAL["active"]),
                                     "active (no drug)" = unname(PAL["placebo"]))) +
      labs(x = "weeks", y = NULL, colour = NULL,
           title = "Mechanistic biomarkers",
           subtitle = paste("P2X3 density turns over in about two weeks; wind-up in about three.",
                            "Symptomatic relief is fast, disease modification is not.")) + THEME
  })
}

shinyApp(ui, server)
