#!/usr/bin/env python3
"""Build supporting figures for the KBCS 2026 talk (pure Python: cairosvg +
Pillow + qrcode — no R/Graphviz/ImageMagick needed).

Per the 2026-07 revision, this deck deliberately minimizes generated/mockup
diagrams (they read as "AI-made") in favor of real deliverables: actual
Graphviz disease maps, a real Shiny dashboard screenshot, and (for the organ-
chip case study) a single cropped figure from the original poster showing
predicted-vs-observed fit quality. Those real images are committed directly
under assets/figs, assets/shiny, assets/poster — this script only regenerates
the montage and the QR code."""
import os, glob, io
from PIL import Image
import cairosvg, qrcode

NAVY = "#163A5F"
PANEL = "#F5F7FA"

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
A = os.path.abspath(os.path.join(HERE, "..", "assets"))
FIG = os.path.join(A, "figs")
os.makedirs(FIG, exist_ok=True)


def find_svg(disease):
    g = sorted(glob.glob(os.path.join(ROOT, disease, "*_qsp*.svg")))
    return g[0] if g else None


# ---------- 1) QSP library montage (real mechanistic maps) ----------
print("[1] montage")
MONTAGE = ["rheumatoid-arthritis", "systemic-lupus-erythematosus", "multiple-sclerosis",
 "type2-diabetes", "heart-failure-hfref", "pulmonary-arterial-hypertension", "copd",
 "breast-cancer", "multiple-myeloma", "chronic-myeloid-leukemia", "glioblastoma",
 "sickle-cell-disease", "iga-nephropathy", "chronic-kidney-disease", "parkinsons-disease",
 "alzheimers-disease", "epilepsy", "schizophrenia", "psoriasis", "atopic-dermatitis",
 "crohn-disease", "ulcerative-colitis", "hiv-aids", "cystic-fibrosis"]
cols, rows = 6, 4; cw, ch = 440, 300; pad = 10
sheet = Image.new("RGB", (cols * cw + pad * (cols + 1), rows * ch + pad * (rows + 1)), "white")
for i, dis in enumerate(MONTAGE):
    svg = find_svg(dis)
    if not svg:
        continue
    png = cairosvg.svg2png(url=svg, output_width=560)
    im = Image.open(io.BytesIO(png)).convert("RGB")
    im.thumbnail((cw - 12, ch - 12))
    r, c = divmod(i, cols)
    cell = Image.new("RGB", (cw, ch), PANEL)
    cell.paste(im, ((cw - im.width) // 2, (ch - im.height) // 2))
    sheet.paste(cell, (pad + c * (cw + pad), pad + r * (ch + pad)))
sheet.save(os.path.join(FIG, "montage.png"))
print("  montage.png", sheet.size)

# ---------- 2) real disease-map figures used in the deep-dive slides ----------
print("[2] deep-dive maps")
for dis, out in [("iga-nephropathy", "igan_map.png"), ("sickle-cell-disease", "scd_map.png"),
                  ("multiple-myeloma", "mm_map.png"), ("rheumatoid-arthritis", "ra_map.png"),
                  ("duchenne-muscular-dystrophy", "dmd_map.png"), ("alzheimers-disease", "ad_map.png")]:
    svg = find_svg(dis)
    if not svg:
        print("  ! missing svg for", dis); continue
    cairosvg.svg2png(url=svg, write_to=os.path.join(FIG, out), output_width=1600)
    print("  ", out)

# ---------- 3) repo QR ----------
print("[3] QR")
qr = qrcode.QRCode(border=1, box_size=10, error_correction=qrcode.constants.ERROR_CORRECT_M)
qr.add_data("https://github.com/pipetcpt/qsp"); qr.make(fit=True)
qr.make_image(fill_color=NAVY, back_color="white").convert("RGB").save(os.path.join(FIG, "repo_qr.png"))
print("  repo_qr.png")

print("NOTE: assets/shiny/merigolix_dashboard.webp and assets/poster/fig1_fit_only.png")
print("      are committed source images (real screenshot / cropped poster figure) —")
print("      not regenerated by this script.")
print("ALL ASSETS BUILT ->", A)
