##  Anorexia Nervosa (AN) — QSP / PK-PD Model
##  ============================================================================
##  Disease  : Anorexia Nervosa — the psychiatric illness with the highest
##             mortality (SMR ~5.9), in which cognitively driven caloric
##             restriction (fear of weight gain, body-image distortion,
##             habit-entrenched restriction, compulsive exercise) produces a
##             sustained NEGATIVE ENERGY BALANCE. The resulting starvation
##             state triggers a coordinated neuroendocrine adaptation —
##             hypoleptinemia, low-T3 (euthyroid-sick) syndrome, adaptive
##             thermogenesis, hypercortisolemia, hepatic GH resistance with
##             low IGF-1, and suppression of the GnRH pulse generator giving
##             functional hypothalamic amenorrhea — which uncouples bone
##             remodeling (P1NP down / CTX up -> BMD Z-score decline) and
##             drives cardiovascular adaptation (bradycardia, QTc risk).
##             Nutritional rehabilitation reverses these axes but carries its
##             own hazard: the REFEEDING SYNDROME (insulin-driven
##             intracellular shift of phosphate/potassium/magnesium onto an
##             occult total-body deficit, plus thiamine consumption).
##  Authors  : Generated by Claude Code Routine (QSP Disease Model Library)
##  Engine   : mrgsolve (>=1.5)
##
##  Scope    : 31 ODE compartments —
##             * Drug/intervention PK (9): olanzapine (gut + systemic),
##               fluoxetine + norfluoxetine, transdermal estradiol (patch
##               depot + systemic), teriparatide, skeletal bisphosphonate,
##               psychotherapy engagement.
##             * Behavior & energetics (6): ED-cognition drive, energy intake,
##               metabolic adaptation-to-intake state (which sets the
##               refeeding insulin surge), fat mass, fat-free mass, adaptive
##               thermogenesis.
##             * Neuroendocrine axes (7): leptin, ghrelin, free T3, cortisol,
##               GnRH pulse index, estradiol, IGF-1.
##             * Skeletal (3): P1NP, CTX, BMD Z-score.
##             * Cardiac (1): heart rate (QTc derived algebraically).
##             * Refeeding safety (5): total-body phosphate depletion index,
##               serum phosphate, potassium, magnesium, thiamine stores.
##  Time     : days. Default horizon 365 d (weight restoration takes months;
##             menses resumption and BMD recovery take 6-18 months).
##  Units    : kcal/day (intake/expenditure), kg (FM/FFM), kg/m^2 (BMI),
##             ng/mL (leptin, IGF-1), pg/mL (T3, estradiol, ghrelin),
##             ug/dL (cortisol), ug/L (P1NP), ng/mL (CTX), Z-score (BMD),
##             bpm (HR), ms (QTc), mg/dL (phosphate, magnesium),
##             mEq/L (potassium), 0-1 index (drive, thiamine, depletion).
##             Drug compartments are dose-proportional "exposure" units (au) —
##             this library's standard surrogate when the disease-relevant PD
##             is what matters rather than literal plasma concentration.
##  Scenarios: 10 prebuilt — see AN_simulate_scenarios() at the bottom.
##  Anchors  : Keys 1950 Minnesota Semi-Starvation Experiment (starvation
##             itself reproduces AN cognition and rigidity -> the
##             starvation-perpetuation term); Forbes 1987 / Hall 2011 Lancet
##             378:826 (FM/FFM partition dFFM/dFM = C/FM); Dulloo 2015
##             Obes Rev 16(S1):25 (adaptive thermogenesis); Grinspoon 1996
##             JCEM 81:3861 and Misra 2004 (hypoleptinemia, GH resistance,
##             low IGF-1); Kopp 1997 Mol Psychiatry 2:335 / Audi 2002 Horm Res
##             58:65 (leptin ~1.85 ng/mL threshold for menses resumption);
##             Misra & Klibanski 2014 Lancet Diabetes Endocrinol 2:581
##             (low-formation/high-resorption skeletal phenotype); Misra 2011
##             J Bone Miner Res 26:2430 (transdermal — not oral — estradiol
##             improves BMD); Fazeli 2014 JCEM 99:1322 (teriparatide in adult
##             AN); Golden 2013 / O'Connor 2016 / Garber 2021 J Adolesc Health
##             68:1 (higher-calorie refeeding is safe with phosphate
##             monitoring and shortens length of stay); Attia 1998 Am J
##             Psychiatry 155:548 and Walsh 2006 JAMA 295:2605 (fluoxetine
##             ineffective in the underweight state -> explicit nutritional
##             GATE); Attia 2019 Am J Psychiatry 176:449 (olanzapine: modest
##             BMI benefit, no psychopathology benefit); Lock 2010 Arch Gen
##             Psychiatry 67:1025 (FBT for adolescents); Arcelus 2011 Arch Gen
##             Psychiatry 68:724 (SMR 5.86).
##  Disclaimer: For research / education / hypothesis generation only. Not a
##             substitute for clinical judgment and NOT a refeeding protocol —
##             refeeding a severely malnourished patient is an inpatient
##             medical procedure with mandatory electrolyte monitoring.
##  ============================================================================
[PROB]
QSP model of Anorexia Nervosa linking eating-disorder cognition, energy intake
and a Forbes-partitioned two-compartment body composition to the starvation
neuroendocrine cascade (leptin, ghrelin, T3, cortisol, GnRH, estradiol,
IGF-1), skeletal remodeling (P1NP/CTX/BMD), cardiac adaptation (bradycardia,
QTc) and refeeding-syndrome safety (phosphate, potassium, magnesium,
thiamine), with PK/PD for olanzapine, fluoxetine (nutritionally gated),
transdermal estradiol, teriparatide, risedronate and psychotherapy.

[PLUGIN] Rcpp

[PARAM] @annotated
//--- Patient profile -------------------------------------------------------
HT           : 1.65  : m, height
BASE_BMI     : 14.0  : kg/m2, presenting BMI
MEDIAN_BMI   : 20.5  : kg/m2, median BMI for age/sex/height (%mBMI denominator)
FM_FRAC0     : 0.10  : fraction of presenting body weight that is fat mass
SEV          : 0.80  : 0-1, baseline eating-disorder cognition severity
PURGE        : 0     : 1 = binge/purge subtype (vomiting/laxative behavior)
ADOLESCENT   : 1     : 1 = adolescent (bone accrual physiology, FBT eligible)
INPATIENT    : 0     : 1 = inpatient (supervised meals, exercise curtailed)
ILLNESS_DUR  : 1.5   : years of illness (scales occult phosphate/bone deficit)

//--- Prescribed nutrition (meal plan) --------------------------------------
EI_START     : 1800  : kcal/day, starting prescribed intake (0 = no plan)
EI_ESCAL     : 60    : kcal/day per day, meal-plan escalation rate
EI_PLAN_MAX  : 3200  : kcal/day, ceiling of the prescribed plan
DISCHARGE_DAY: 0     : day of discharge (0 = none); plan drops afterwards
POST_DC_FAC  : 0.78  : fraction of the max plan still eaten after discharge
ADHERE_IN    : 0.94  : plan adherence when supervised (inpatient)
ADHERE_OUT   : 0.35  : max fractional plan refusal at full drive (outpatient)

//--- Olanzapine PO (2.5-10 mg qHS) -----------------------------------------
KA_OLZ       : 1.2   : 1/day, oral absorption
KOUT_OLZ     : 0.46  : 1/day, elimination (t1/2 ~33 h)
SMOKER       : 0     : 1 = smoker (CYP1A2 induction, ~1.5x clearance)
EC50_OLZ     : 0.9   : au, exposure for half-maximal effect
EMAX_OLZ_APP : 0.22  : max fractional increase in intake (H1/5-HT2C blockade)
EMAX_OLZ_COG : 0.12  : max fractional reduction in ED drive (modest)

//--- Fluoxetine PO (20-60 mg qd) -------------------------------------------
KOUT_FLX     : 0.35  : 1/day, fluoxetine elimination (t1/2 ~2-4 d)
KMET_FLX     : 0.22  : 1/day, conversion to norfluoxetine
KOUT_NOR     : 0.07  : 1/day, norfluoxetine elimination (t1/2 ~10 d)
EC50_SERT    : 1.0   : au, SERT-occupancy EC50 (fluoxetine + norfluoxetine)
EMAX_FLX     : 0.30  : max fractional ED-drive reduction when the gate is open
GATE_MBMI50  : 0.90  : %mBMI (fraction) at half-maximal SSRI efficacy gate
GATE_HILL    : 8     : steepness of the nutritional gate (near-switch)

//--- Transdermal 17-beta estradiol 100 ug patch (+ cyclic progesterone) ----
KA_E2P       : 0.7   : 1/day, patch release into systemic exposure
KOUT_E2X     : 0.9   : 1/day, exogenous estradiol exposure decay
E2_PATCH_GAIN: 55    : pg/mL per au of exogenous estradiol exposure
OCP_ORAL     : 0     : 1 = oral contraceptive instead (first-pass IGF-1 drop)
OCP_IGF_SUPP : 0.20  : fractional IGF-1 suppression from oral estrogen

//--- Teriparatide SC 20 ug qd (adults with fractures) ----------------------
KOUT_TPTD    : 6.0   : 1/day, short exposure (intermittent anabolic window)
EC50_TPTD    : 0.35  : au
EMAX_TPTD    : 0.55  : max fractional increase in bone formation (P1NP)

//--- Risedronate PO 35 mg weekly (adults; teratogenicity caution) ----------
KOUT_BIS     : 0.012 : 1/day, skeletal retention (long)
EC50_BIS     : 1.5   : au
EMAX_BIS     : 0.50  : max fractional suppression of resorption (CTX)

//--- Psychotherapy (FBT / CBT-E) -------------------------------------------
KOUT_TX      : 0.10  : 1/day, decay of engagement between weekly sessions
EC50_TX      : 1.8   : au, engagement for half-maximal effect
EMAX_TX      : 0.70  : max fractional reduction in ED cognition drive
FBT          : 1     : 1 = family-based treatment (vs individual CBT-E)
FBT_BONUS    : 1.25  : multiplier on therapy effect for adolescents in FBT

//--- Eating-disorder cognition ---------------------------------------------
KOUT_DRIVE   : 0.05  : 1/day, drive equilibration (slow: weeks-months)
K_STARVE_DRV : 0.55  : starvation-perpetuation gain (Minnesota effect)
DRIVE_FLOOR  : 0.05  : residual drive even in remission

//--- Energy intake behavior ------------------------------------------------
KOUT_EI      : 0.25  : 1/day, intake adjustment toward behavioral target
REL_DEF_MAX  : 0.20  : max fractional self-imposed deficit below requirement
RESTRICT_FLOOR:0.55  : %mBMI (fraction) below which restriction capacity fails
RESTRICT_FULL: 0.72  : %mBMI (fraction) above which restriction is unimpaired
GOAL_LO      : 0.98  : %mBMI (fraction) where the plan starts tapering to maintenance
GOAL_HI      : 1.04  : %mBMI (fraction) where the plan reaches pure maintenance
GI_SAT_MAX   : 0.18  : max fractional intake loss (gastroparesis/early satiety)
PURGE_LOSS   : 0.22  : fractional loss of absorbed intake from purging x drive

//--- Energy expenditure ----------------------------------------------------
RMR_FFM      : 22.0  : kcal/kg/day per kg fat-free mass
RMR_FM       : 3.2   : kcal/kg/day per kg fat mass
RMR_CONST    : 95    : kcal/day, constant term
PAL0         : 0.35  : baseline non-exercise activity as a fraction of REE
K_EXER       : 320   : kcal/day, maximal compulsive-exercise expenditure
K_SIH        : 0.50  : semi-starvation-induced hyperactivity gain (low leptin)
TEF_FRAC     : 0.10  : thermic effect of food (fraction of intake)
ADAPT_MAX    : 0.22  : maximum adaptive thermogenesis (fractional REE cut)
KOUT_ADAPT   : 0.08  : 1/day, adaptive thermogenesis kinetics
K_HYPERMET   : 0.35  : fractional REE rise per unit refeeding insulin-surge index

//--- Body composition (Forbes partition; asymmetric tissue energy cost) ----
FORBES_C     : 10.4  : kg, Forbes partition constant
RATIO_MIN    : 0.50  : lower bound on the Forbes dFFM/dFM mass ratio
RATIO_MAX    : 4.00  : upper bound on the Forbes dFFM/dFM mass ratio (very low FM)
RHO_FM_GAIN  : 10850 : kcal/kg, cost of depositing fat mass (9440 + synthesis)
RHO_FM_LOSS  : 9440  : kcal/kg, energy released per kg fat mobilized
RHO_FFM_GAIN : 5200  : kcal/kg, effective cost of lean accretion (synthesis work + refeeding hypermetabolism)
RHO_FFM_LOSS : 2400  : kcal/kg, effective energy yield of lean-tissue loss
K_CORT_PART  : 0.25  : extra lean share of weight LOSS per unit hypercortisolemia

//--- Starvation signal (drives every neuroendocrine axis) ------------------
STORE_REF    : 0.35  : %mBMI deficit (fraction) giving a maximal store signal
W_STORE      : 0.75  : weight of body-store depletion in the starvation index
W_FLOW       : 0.45  : weight of acute energy-flow deficit in the index
FLOW_MIN     : -0.30 : most negative (i.e. overfed) value of the flow term

//--- Leptin / ghrelin ------------------------------------------------------
K_LEP_FM     : 0.72  : ng/mL per kg fat mass
LEP_ACUTE    : 0.35  : extra fractional leptin fall during energy deficit
KOUT_LEP     : 2.5   : 1/day, leptin kinetics (fast)
LEP_NORM     : 11.0  : ng/mL, reference female leptin
GHRL_MAX     : 1450  : pg/mL, maximal fasting acyl-ghrelin in severe AN
GHRL_NORM    : 620   : pg/mL, reference ghrelin
KOUT_GHRL    : 1.5   : 1/day

//--- Thyroid (low-T3 syndrome) ---------------------------------------------
T3_NORM      : 3.1   : pg/mL, reference free T3
T3_SUPP      : 0.52  : max fractional T3 suppression by starvation
KOUT_T3      : 0.25  : 1/day

//--- HPA axis --------------------------------------------------------------
CORT_NORM    : 12.0  : ug/dL, reference morning cortisol
K_CORT_DEF   : 0.55  : fractional cortisol rise per unit starvation index
K_CORT_STRESS: 0.20  : fractional cortisol rise per unit ED drive
KOUT_CORT    : 0.6   : 1/day

//--- HPG axis --------------------------------------------------------------
LEP50_GNRH   : 1.85  : ng/mL, leptin threshold for GnRH pulse recovery
LEP_HILL     : 4     : Hill coefficient of the leptin gate
FM_FRAC_GATE : 0.13  : body-fat fraction at half-maximal reproductive gate
FAT_HILL     : 3     : Hill coefficient of the body-fat reproductive gate
K_CORT_GNRH  : 0.85  : cortisol brake on the GnRH pulse generator
KOUT_GNRH    : 0.030 : 1/day, pulse-generator recovery (slow; months)
E2_MAX       : 78    : pg/mL, estradiol at full GnRH pulsatility
KOUT_E2      : 0.9   : 1/day
E2_NORM      : 65    : pg/mL, reference estradiol

//--- GH resistance / IGF-1 -------------------------------------------------
IGF1_NORM    : 290   : ng/mL, reference IGF-1 (adolescent/young adult)
IGF_SUPP     : 0.65  : max fractional IGF-1 suppression by starvation
KOUT_IGF1    : 0.35  : 1/day (IGF-1 responds within days to refeeding)

//--- Bone remodeling -------------------------------------------------------
P1NP_NORM    : 55    : ug/L, reference bone-formation marker
CTX_NORM     : 0.42  : ng/mL, reference bone-resorption marker
K_P1NP_IGF   : 0.85  : exponent, IGF-1 dependence of osteoblast activity
K_P1NP_CORT  : 0.30  : fractional P1NP loss per unit relative hypercortisolemia
K_P1NP_LEP   : 0.22  : fractional P1NP loss from marrow adipogenic switch
K_CTX_E2     : 0.95  : fractional CTX rise per unit estradiol deficit
K_CTX_CORT   : 0.28  : fractional CTX rise per unit relative hypercortisolemia
KOUT_P1NP    : 0.20  : 1/day
KOUT_CTX     : 0.20  : 1/day
K_BMD_TURN   : 0.0016: Z-score/day scale of the remodeling balance
K_BMD_ACCRUE : 0.0006: Z-score/day adolescent accrual bonus once nourished
BMD_BASE     : -1.6  : BMD Z-score at presentation

//--- Cardiac ---------------------------------------------------------------
HR_NORM      : 72    : bpm
HR_BRADY_MAX : 46    : bpm, maximal bradycardic adaptation
KOUT_HR      : 0.30  : 1/day
QTC_BASE     : 400   : ms
K_QTC_K      : 26    : ms per mEq/L below 4.0 potassium
K_QTC_MG     : 12    : ms per mg/dL below 2.0 magnesium
K_QTC_BRADY  : 0.35  : ms per bpm below 60

//--- Refeeding: phosphate / potassium / magnesium / thiamine ---------------
K_DEPL_ON    : 0.020 : 1/day, accrual of occult total-body phosphate depletion
K_DEPL_OFF   : 0.045 : 1/day, repletion during positive energy balance
KOUT_EIA     : 0.15  : 1/day, tissue metabolic adaptation to current intake
K_SURGE      : 1000  : kcal/day per unit refeeding insulin-surge index
PHOS_NORM    : 3.9   : mg/dL, reference serum phosphate
KIN_PHOS     : 3.12  : mg/dL/day (= KOUT_PHOS x PHOS_NORM)
KOUT_PHOS    : 0.80  : 1/day
K_SHIFT_PHOS : 1.60  : mg/dL/day per unit (insulin surge x depletion index)
PHOS_SUP     : 0     : mg/dL/day, prophylactic/therapeutic phosphate repletion
K_NORM       : 4.1   : mEq/L, reference potassium
KIN_K        : 2.87  : mEq/L/day (= KOUT_K x K_NORM)
KOUT_K       : 0.70  : 1/day
K_SHIFT_K    : 0.55  : mEq/L/day per unit (insulin surge x depletion index)
K_PURGE_LOSS : 0.45  : mEq/L/day potassium loss at full purging activity
K_SUP        : 0     : mEq/L/day, potassium repletion
MG_NORM      : 2.05  : mg/dL, reference magnesium
KIN_MG       : 1.435 : mg/dL/day (= KOUT_MG x MG_NORM)
KOUT_MG      : 0.70  : 1/day
K_SHIFT_MG   : 0.28  : mg/dL/day per unit (insulin surge x depletion index)
MG_SUP       : 0     : mg/dL/day, magnesium repletion
THIA_DIET    : 0.00025: 1/day per kcal, dietary thiamine delivery
K_THIA_GLYC  : 0.00008: 1/day per kcal, thiamine consumed by glycolytic flux
KOUT_THIA    : 0.02  : 1/day, baseline thiamine turnover
THIA_SUP     : 0     : 1/day, thiamine repletion (give BEFORE glucose load)

[CMT] @annotated
OLZ_GUT   : Olanzapine oral depot (au)
OLZ_CENT  : Olanzapine systemic exposure (au)
FLX_CENT  : Fluoxetine systemic exposure (au)
FLX_NOR   : Norfluoxetine (active metabolite) exposure (au)
E2_PATCH  : Transdermal estradiol patch depot (au)
E2_EXO    : Exogenous estradiol systemic exposure (au)
TPTD      : Teriparatide exposure (au; intermittent anabolic pulses)
BIS       : Skeletal bisphosphonate exposure (au; long retention)
THERAPY   : Psychotherapy engagement (au; weekly sessions)
DRIVE     : Eating-disorder cognition drive (0-1; EDE-Q global proxy)
EI        : Actual energy intake (kcal/day)
EI_ADAPT  : Metabolic adaptation-to-intake state (kcal/day)
FM        : Fat mass (kg)
FFM       : Fat-free mass (kg)
ADAPT     : Adaptive thermogenesis (fractional REE suppression)
LEP       : Plasma leptin (ng/mL)
GHRL      : Plasma acyl-ghrelin (pg/mL)
T3        : Free triiodothyronine (pg/mL)
CORT      : Plasma cortisol (ug/dL)
GNRH      : GnRH pulse-generator index (0-1)
E2        : Plasma estradiol (pg/mL; endogenous + exogenous)
IGF1      : Plasma IGF-1 (ng/mL)
P1NP      : Bone-formation marker P1NP (ug/L)
CTX       : Bone-resorption marker CTX (ng/mL)
BMD       : Lumbar-spine BMD Z-score
HR        : Heart rate (bpm)
DEPL      : Total-body phosphate depletion index (0-1; occult)
PHOS      : Serum phosphate (mg/dL)
POT       : Serum potassium (mEq/L)
MG        : Serum magnesium (mg/dL)
THIA      : Thiamine stores (0-1 relative)

[MAIN]
OLZ_GUT_0 = 0; OLZ_CENT_0 = 0; FLX_CENT_0 = 0; FLX_NOR_0 = 0;
E2_PATCH_0 = 0; E2_EXO_0 = 0; TPTD_0 = 0; BIS_0 = 0; THERAPY_0 = 0;

double W0 = BASE_BMI * HT * HT;
FM_0      = W0 * FM_FRAC0;
FFM_0     = W0 - FM_0;
DRIVE_0   = SEV;

// Chronic (weight-stable) starvation signal from depleted body stores alone
double store_def0 = (1 - BASE_BMI/MEDIAN_BMI)/STORE_REF;
if (store_def0 < 0) store_def0 = 0;
if (store_def0 > 1) store_def0 = 1;
double fdef0 = W_STORE*store_def0;
if (fdef0 > 1) fdef0 = 1;

ADAPT_0 = ADAPT_MAX * fdef0;
LEP_0   = K_LEP_FM * FM_0 * (1 - LEP_ACUTE*fdef0);
GHRL_0  = GHRL_NORM + (GHRL_MAX - GHRL_NORM)*(1 - BASE_BMI/MEDIAN_BMI);
T3_0    = T3_NORM * (1 - T3_SUPP*fdef0);
CORT_0  = CORT_NORM * (1 + K_CORT_DEF*fdef0 + K_CORT_STRESS*DRIVE_0);

// Baseline energetics: the untreated patient sits close to energy balance
double ree_raw0 = RMR_FFM*FFM_0 + RMR_FM*FM_0 + RMR_CONST;
double REE0     = ree_raw0 * (1 - ADAPT_0);
double sih0     = 1 + K_SIH*(1 - LEP_0/LEP_NORM);
if (sih0 < 1) sih0 = 1;
double pm0      = BASE_BMI/MEDIAN_BMI;
double rcap0    = (pm0 - RESTRICT_FLOOR)/(RESTRICT_FULL - RESTRICT_FLOOR);
if (rcap0 < 0) rcap0 = 0;
if (rcap0 > 1) rcap0 = 1;
double EXER0    = K_EXER * DRIVE_0 * sih0 * (INPATIENT>0 ? 0.10 : 1.0) * rcap0;
double need0    = REE0*(1 + PAL0) + EXER0;
EI_0            = need0/(1 - TEF_FRAC) * (1 - REL_DEF_MAX*DRIVE_0*rcap0);
EI_ADAPT_0      = EI_0;

double fmfrac0  = FM_0/W0;
double lepgate0 = pow(LEP_0, LEP_HILL)/(pow(LEP50_GNRH, LEP_HILL) + pow(LEP_0, LEP_HILL));
double fatgate0 = pow(fmfrac0, FAT_HILL)/(pow(FM_FRAC_GATE, FAT_HILL) + pow(fmfrac0, FAT_HILL));
double cortbrk0 = 1.0/(1 + K_CORT_GNRH*(CORT_0/CORT_NORM - 1));
if (cortbrk0 > 1) cortbrk0 = 1;
GNRH_0 = lepgate0 * fatgate0 * cortbrk0;
E2_0   = E2_MAX * GNRH_0;

IGF1_0 = IGF1_NORM * (1 - IGF_SUPP*fdef0) * (1 - OCP_ORAL*OCP_IGF_SUPP);

double cort_rel0 = CORT_0/CORT_NORM - 1;   if (cort_rel0 < 0) cort_rel0 = 0;
double lep_def0  = 1 - LEP_0/LEP_NORM;     if (lep_def0  < 0) lep_def0  = 0;
double e2_def0   = 1 - E2_0/E2_NORM;       if (e2_def0   < 0) e2_def0   = 0;
P1NP_0 = P1NP_NORM * pow(IGF1_0/IGF1_NORM, K_P1NP_IGF)
         * (1 - K_P1NP_CORT*cort_rel0) * (1 - K_P1NP_LEP*lep_def0);
if (P1NP_0 < 3) P1NP_0 = 3;
CTX_0  = CTX_NORM * (1 + K_CTX_E2*e2_def0) * (1 + K_CTX_CORT*cort_rel0);
BMD_0  = BMD_BASE;

HR_0 = HR_NORM - HR_BRADY_MAX*(0.6*(1 - T3_0/T3_NORM) + 0.4*fdef0);
if (HR_0 < 32) HR_0 = 32;

// Occult total-body phosphate depletion scales with severity and chronicity
double depl0 = (1 - BASE_BMI/MEDIAN_BMI) * (1.6 + 0.35*ILLNESS_DUR);
if (depl0 > 0.95) depl0 = 0.95;
if (depl0 < 0.05) depl0 = 0.05;
DEPL_0 = depl0;
PHOS_0 = PHOS_NORM * (1 - 0.06*depl0);      // serum stays normal until refed
POT_0  = K_NORM - (PURGE>0 ? 0.55 : 0.0);
MG_0   = MG_NORM * (1 - 0.05*depl0);
THIA_0 = 1 - 0.45*depl0;

[ODE]
//=========================================================================
// 0. Prescribed meal plan (escalating; steps down after discharge)
//=========================================================================
double plan = EI_START + EI_ESCAL*SOLVERTIME;
if (plan > EI_PLAN_MAX) plan = EI_PLAN_MAX;
if (DISCHARGE_DAY > 0 && SOLVERTIME > DISCHARGE_DAY) plan = EI_PLAN_MAX*POST_DC_FAC;
double inpt = (DISCHARGE_DAY > 0 && SOLVERTIME > DISCHARGE_DAY) ? 0.0 : INPATIENT;

//=========================================================================
// 1. Drug / intervention PK
//=========================================================================
double cl_olz = KOUT_OLZ * (SMOKER > 0 ? 1.5 : 1.0);
dxdt_OLZ_GUT  = -KA_OLZ*OLZ_GUT;
dxdt_OLZ_CENT =  KA_OLZ*OLZ_GUT - cl_olz*OLZ_CENT;
dxdt_FLX_CENT = -(KOUT_FLX + KMET_FLX)*FLX_CENT;
dxdt_FLX_NOR  =  KMET_FLX*FLX_CENT - KOUT_NOR*FLX_NOR;
dxdt_E2_PATCH = -KA_E2P*E2_PATCH;
dxdt_E2_EXO   =  KA_E2P*E2_PATCH - KOUT_E2X*E2_EXO;
dxdt_TPTD     = -KOUT_TPTD*TPTD;
dxdt_BIS      = -KOUT_BIS*BIS;
dxdt_THERAPY  = -KOUT_TX*THERAPY;

double olz_app  = EMAX_OLZ_APP * OLZ_CENT/(EC50_OLZ + OLZ_CENT);
double olz_cog  = EMAX_OLZ_COG * OLZ_CENT/(EC50_OLZ + OLZ_CENT);
double sert     = (FLX_CENT + FLX_NOR)/(EC50_SERT + FLX_CENT + FLX_NOR);
double tptd_eff = EMAX_TPTD * TPTD/(EC50_TPTD + TPTD);
double bis_eff  = EMAX_BIS  * BIS /(EC50_BIS  + BIS);
double tx_eff   = EMAX_TX * THERAPY/(EC50_TX + THERAPY)
                  * ((FBT>0 && ADOLESCENT>0) ? FBT_BONUS : 1.0);
if (tx_eff > 0.85) tx_eff = 0.85;

//=========================================================================
// 2. Anthropometrics, expenditure and the starvation index
//=========================================================================
double WT    = FM + FFM;
double BMIv  = WT/(HT*HT);
double pmBMI = BMIv/MEDIAN_BMI;
double fmfrac = FM/WT;

double ree_raw = RMR_FFM*FFM + RMR_FM*FM + RMR_CONST;
double surge0  = (EI - EI_ADAPT)/K_SURGE;
if (surge0 < 0) surge0 = 0;
double REE     = ree_raw*(1 - ADAPT)*(1 + K_HYPERMET*surge0);   // refeeding hypermetabolism

// Restriction capacity fails at extreme emaciation (hunger, weakness, care)
double rcap = (pmBMI - RESTRICT_FLOOR)/(RESTRICT_FULL - RESTRICT_FLOOR);
if (rcap < 0) rcap = 0;
if (rcap > 1) rcap = 1;

double sih = 1 + K_SIH*(1 - LEP/LEP_NORM);
if (sih < 1) sih = 1;
double EXER = K_EXER * DRIVE * sih * (inpt>0 ? 0.10 : 1.0) * rcap;

double need  = REE*(1 + PAL0) + EXER;         // requirement excluding TEF
double TEF   = TEF_FRAC*EI;
double TEE   = need + TEF;
double EB    = EI - TEE;                      // kcal/day

// Starvation index: depleted stores (slow) + acute energy-flow deficit (fast)
double store_def = (1 - pmBMI)/STORE_REF;
if (store_def < 0) store_def = 0;
if (store_def > 1) store_def = 1;
double flow_def = 1 - EI/(need/(1 - TEF_FRAC));
if (flow_def < FLOW_MIN) flow_def = FLOW_MIN;
if (flow_def > 1) flow_def = 1;
double fdef = W_STORE*store_def + W_FLOW*flow_def;
if (fdef < 0) fdef = 0;
if (fdef > 1) fdef = 1;

//=========================================================================
// 3. Eating-disorder cognition drive
//=========================================================================
double starve_gain = K_STARVE_DRV*(1 - pmBMI/0.95);
if (starve_gain < 0) starve_gain = 0;

// SSRI efficacy is GATED by nutritional restoration (Attia 1998; Walsh 2006)
double gate    = pow(pmBMI, GATE_HILL)/(pow(GATE_MBMI50, GATE_HILL) + pow(pmBMI, GATE_HILL));
double flx_eff = EMAX_FLX * sert * gate;

double drive_target = SEV*(1 + starve_gain)*(1 - tx_eff)*(1 - olz_cog)*(1 - flx_eff);
if (drive_target < DRIVE_FLOOR) drive_target = DRIVE_FLOOR;
if (drive_target > 1) drive_target = 1;
dxdt_DRIVE = KOUT_DRIVE*(drive_target - DRIVE);

//=========================================================================
// 4. Energy intake behavior
//=========================================================================
// Without a meal plan the patient eats a self-imposed fraction of need;
// a structured (especially supervised) plan can push intake above need.
double maint = need/(1 - TEF_FRAC);
double free_intake = maint*(1 - REL_DEF_MAX*DRIVE*rcap);
double adhere = (inpt>0) ? ADHERE_IN : (1 - ADHERE_OUT*DRIVE);
if (adhere < 0.15) adhere = 0.15;
double plan_intake = plan*adhere;

// A meal plan is written to restore weight and is then tapered to maintenance
// as the goal weight is reached — without this the plan would overshoot.
double taper = (pmBMI - GOAL_LO)/(GOAL_HI - GOAL_LO);
if (taper < 0) taper = 0;
if (taper > 1) taper = 1;
plan_intake = plan_intake*(1 - taper) + maint*taper;

// Gastroparesis/early satiety limits how far intake can be pushed ABOVE what
// the patient would eat on their own; it does not push intake below that.
double gi_pen = GI_SAT_MAX*(1 - pmBMI);
if (gi_pen < 0) gi_pen = 0;
double excess = plan_intake - free_intake;
if (excess < 0) excess = 0;
double purge_act = (PURGE>0) ? DRIVE : 0.0;

double ei_target = (free_intake + excess*(1 - gi_pen))*(1 + olz_app)*(1 - PURGE_LOSS*purge_act);
if (ei_target < 150) ei_target = 150;
dxdt_EI       = KOUT_EI*(ei_target - EI);
dxdt_EI_ADAPT = KOUT_EIA*(EI - EI_ADAPT);

//=========================================================================
// 5. Body composition (Forbes partition, asymmetric tissue energy cost)
//=========================================================================
// Forbes: dFFM/dFM = C/FM (mass ratio), closed with energy conservation
//   EB = rho_FM*dFM + rho_FFM*dFFM  ->  dFM = EB/(rho_FM + rho_FFM*ratio)
double ratio = FORBES_C/FM;
double cort_relx = CORT/CORT_NORM - 1;
if (cort_relx < 0) cort_relx = 0;
if (EB < 0) ratio *= (1 + K_CORT_PART*cort_relx);   // cortisol spares fat, wastes lean
if (ratio < RATIO_MIN) ratio = RATIO_MIN;
if (ratio > RATIO_MAX) ratio = RATIO_MAX;

double rho_fm  = (EB >= 0) ? RHO_FM_GAIN  : RHO_FM_LOSS;
double rho_ffm = (EB >= 0) ? RHO_FFM_GAIN : RHO_FFM_LOSS;
double dFM = EB/(rho_fm + rho_ffm*ratio);
dxdt_FM  = dFM;
dxdt_FFM = ratio*dFM;
if (FM  < 0.4 && dxdt_FM  < 0) dxdt_FM  = 0;    // physiologic floors
if (FFM < 20  && dxdt_FFM < 0) dxdt_FFM = 0;

double adapt_target = ADAPT_MAX*fdef;
dxdt_ADAPT = KOUT_ADAPT*(adapt_target - ADAPT);

//=========================================================================
// 6. Adipose & gut hormones
//=========================================================================
double lep_target = K_LEP_FM*FM*(1 - LEP_ACUTE*fdef);
if (lep_target < 0.1) lep_target = 0.1;
dxdt_LEP = KOUT_LEP*(lep_target - LEP);

double ghrl_target = GHRL_NORM + (GHRL_MAX - GHRL_NORM)*(1 - pmBMI);
if (ghrl_target < 200) ghrl_target = 200;
dxdt_GHRL = KOUT_GHRL*(ghrl_target - GHRL);

//=========================================================================
// 7. Thyroid & HPA
//=========================================================================
dxdt_T3   = KOUT_T3*(T3_NORM*(1 - T3_SUPP*fdef) - T3);
dxdt_CORT = KOUT_CORT*(CORT_NORM*(1 + K_CORT_DEF*fdef + K_CORT_STRESS*DRIVE) - CORT);

//=========================================================================
// 8. HPG axis — leptin/adiposity-gated GnRH pulse generator
//=========================================================================
double lepgate = pow(LEP, LEP_HILL)/(pow(LEP50_GNRH, LEP_HILL) + pow(LEP, LEP_HILL));
double fatgate = pow(fmfrac, FAT_HILL)/(pow(FM_FRAC_GATE, FAT_HILL) + pow(fmfrac, FAT_HILL));
double cortbrk = 1.0/(1 + K_CORT_GNRH*(CORT/CORT_NORM - 1));
if (cortbrk > 1) cortbrk = 1;
dxdt_GNRH = KOUT_GNRH*(lepgate*fatgate*cortbrk - GNRH);
dxdt_E2   = KOUT_E2*((E2_MAX*GNRH + E2_PATCH_GAIN*E2_EXO) - E2);

//=========================================================================
// 9. GH resistance / IGF-1
//=========================================================================
dxdt_IGF1 = KOUT_IGF1*(IGF1_NORM*(1 - IGF_SUPP*fdef)*(1 - OCP_ORAL*OCP_IGF_SUPP) - IGF1);

//=========================================================================
// 10. Bone remodeling — low formation, high resorption
//=========================================================================
double cort_rel = CORT/CORT_NORM - 1;  if (cort_rel < 0) cort_rel = 0;
double lep_def  = 1 - LEP/LEP_NORM;    if (lep_def  < 0) lep_def  = 0;
double e2_def   = 1 - E2/E2_NORM;      if (e2_def   < 0) e2_def   = 0;

double p1np_target = P1NP_NORM * pow(IGF1/IGF1_NORM, K_P1NP_IGF)
                     * (1 - K_P1NP_CORT*cort_rel)
                     * (1 - K_P1NP_LEP*lep_def)
                     * (1 + tptd_eff);
if (p1np_target < 3) p1np_target = 3;
dxdt_P1NP = KOUT_P1NP*(p1np_target - P1NP);

double ctx_target = CTX_NORM*(1 + K_CTX_E2*e2_def)*(1 + K_CTX_CORT*cort_rel)*(1 - bis_eff);
if (ctx_target < 0.05) ctx_target = 0.05;
dxdt_CTX = KOUT_CTX*(ctx_target - CTX);

double accrue = (ADOLESCENT>0 && pmBMI > 0.92) ? K_BMD_ACCRUE : 0.0;
dxdt_BMD = K_BMD_TURN*(P1NP/P1NP_NORM - CTX/CTX_NORM) + accrue;

//=========================================================================
// 11. Cardiac adaptation
//=========================================================================
double hr_target = HR_NORM - HR_BRADY_MAX*(0.6*(1 - T3/T3_NORM) + 0.4*fdef);
if (hr_target < 32) hr_target = 32;
dxdt_HR = KOUT_HR*(hr_target - HR);

//=========================================================================
// 12. Refeeding: insulin surge, electrolyte shifts, thiamine
//=========================================================================
// The surge is driven by intake ABOVE what the tissues are adapted to, so the
// RATE of escalation onto an occult deficit — not absolute calories — sets
// the hypophosphatemia risk.
double surge = (EI - EI_ADAPT)/K_SURGE;
if (surge < 0) surge = 0;

double repl_drive = (EB > 0) ? EB/1000.0 : 0.0;
dxdt_DEPL = K_DEPL_ON*fdef*(1 - DEPL) - K_DEPL_OFF*repl_drive*DEPL;

dxdt_PHOS = KIN_PHOS - KOUT_PHOS*PHOS - K_SHIFT_PHOS*surge*DEPL + PHOS_SUP;
dxdt_POT  = KIN_K    - KOUT_K*POT     - K_SHIFT_K*surge*DEPL
            - K_PURGE_LOSS*purge_act  + K_SUP;
dxdt_MG   = KIN_MG   - KOUT_MG*MG     - K_SHIFT_MG*surge*DEPL + MG_SUP;

dxdt_THIA = THIA_SUP*(1 - THIA) + THIA_DIET*EI*(1 - THIA)
            - K_THIA_GLYC*EI*surge - KOUT_THIA*THIA;
if (THIA < 0.02 && dxdt_THIA < 0) dxdt_THIA = 0;

[TABLE]
double WTt    = FM + FFM;
double BMIt   = WTt/(HT*HT);
double pmBMIt = 100.0*BMIt/MEDIAN_BMI;

double plan_t = EI_START + EI_ESCAL*TIME;
if (plan_t > EI_PLAN_MAX) plan_t = EI_PLAN_MAX;
if (DISCHARGE_DAY > 0 && TIME > DISCHARGE_DAY) plan_t = EI_PLAN_MAX*POST_DC_FAC;

double ree_rawt = RMR_FFM*FFM + RMR_FM*FM + RMR_CONST;
double surge0t  = (EI - EI_ADAPT)/K_SURGE;  if (surge0t < 0) surge0t = 0;
double REEt     = ree_rawt*(1 - ADAPT)*(1 + K_HYPERMET*surge0t);
double rcapt    = (BMIt/MEDIAN_BMI - RESTRICT_FLOOR)/(RESTRICT_FULL - RESTRICT_FLOOR);
if (rcapt < 0) rcapt = 0;
if (rcapt > 1) rcapt = 1;
double siht = 1 + K_SIH*(1 - LEP/LEP_NORM);
if (siht < 1) siht = 1;
double inptt = (DISCHARGE_DAY > 0 && TIME > DISCHARGE_DAY) ? 0.0 : INPATIENT;
double EXERt = K_EXER*DRIVE*siht*(inptt>0 ? 0.10 : 1.0)*rcapt;
double TEEt  = REEt*(1 + PAL0) + EXERt + TEF_FRAC*EI;
double EBt   = EI - TEEt;
double surget = (EI - EI_ADAPT)/K_SURGE;  if (surget < 0) surget = 0;

// QTc: bradycardia + hypokalemia + hypomagnesemia
double qtc = QTC_BASE + K_QTC_K*(4.0 - POT) + K_QTC_MG*(2.0 - MG) + K_QTC_BRADY*(60 - HR);
if (qtc < 360) qtc = 360;

// Refeeding-syndrome composite risk (0-1); hypophosphatemia dominates
double rs_phos = (PHOS_NORM - PHOS)/1.6;  if (rs_phos < 0) rs_phos = 0;
double rs_k    = (4.0 - POT)/1.2;         if (rs_k    < 0) rs_k    = 0;
double rs_mg   = (2.0 - MG)/0.6;          if (rs_mg   < 0) rs_mg   = 0;
double rs_thia = (0.6 - THIA)/0.6;        if (rs_thia < 0) rs_thia = 0;
double rs = 0.45*rs_phos + 0.20*rs_k + 0.15*rs_mg + 0.20*rs_thia;
if (rs > 1) rs = 1;

// Medical instability (adolescent-medicine admission-criteria proxy)
double unstable = 0;
if (HR < 50 || pmBMIt < 75 || POT < 3.0 || PHOS < 2.5 || qtc > 460) unstable = 1;

// Menses resumption probability (logistic in estradiol and %mBMI)
double p_menses = 1.0/(1.0 + exp(-(-8.5 + 0.085*E2 + 0.075*pmBMIt)));

double restored  = (pmBMIt >= 95) ? 1 : 0;
double remission = (pmBMIt >= 95 && 6.0*DRIVE < 2.77) ? 1 : 0;

capture Prescribed_plan     = plan_t;
capture Energy_intake       = EI;
capture Energy_expenditure  = TEEt;
capture Resting_EE          = REEt;
capture Exercise_kcal       = EXERt;
capture Energy_balance      = EBt;
capture Adaptive_thermogen  = ADAPT;
capture Fat_mass_kg         = FM;
capture Fat_free_mass_kg    = FFM;
capture Body_weight_kg      = WTt;
capture BMI                 = BMIt;
capture Percent_median_BMI  = pmBMIt;
capture ED_drive            = DRIVE;
capture EDEQ_global         = 6.0*DRIVE;
capture Therapy_effect      = EMAX_TX*THERAPY/(EC50_TX + THERAPY)*((FBT>0 && ADOLESCENT>0) ? FBT_BONUS : 1.0);
capture Olanzapine_exposure = OLZ_CENT;
capture Fluoxetine_total    = FLX_CENT + FLX_NOR;
capture SSRI_gate           = pow(BMIt/MEDIAN_BMI, GATE_HILL)/(pow(GATE_MBMI50, GATE_HILL) + pow(BMIt/MEDIAN_BMI, GATE_HILL));
capture Leptin              = LEP;
capture Ghrelin             = GHRL;
capture Free_T3             = T3;
capture Cortisol            = CORT;
capture GnRH_index          = GNRH;
capture Estradiol           = E2;
capture IGF1_level          = IGF1;
capture P1NP_marker         = P1NP;
capture CTX_marker          = CTX;
capture BMD_Zscore          = BMD;
capture Heart_rate          = HR;
capture QTc_ms              = qtc;
capture Phosphate           = PHOS;
capture Potassium           = POT;
capture Magnesium           = MG;
capture Thiamine            = THIA;
capture Phos_depletion_idx  = DEPL;
capture Refeed_surge        = surget;
capture Refeeding_risk      = rs;
capture Medically_unstable  = unstable;
capture Menses_probability  = p_menses;
capture Weight_restored     = restored;
capture Remission           = remission;

[CAPTURE]
Prescribed_plan Energy_intake Energy_expenditure Resting_EE Exercise_kcal
Energy_balance Adaptive_thermogen Fat_mass_kg Fat_free_mass_kg Body_weight_kg
BMI Percent_median_BMI ED_drive EDEQ_global Therapy_effect Olanzapine_exposure
Fluoxetine_total SSRI_gate Leptin Ghrelin Free_T3 Cortisol GnRH_index Estradiol
IGF1_level P1NP_marker CTX_marker BMD_Zscore Heart_rate QTc_ms Phosphate
Potassium Magnesium Thiamine Phos_depletion_idx Refeed_surge Refeeding_risk
Medically_unstable Menses_probability Weight_restored Remission


##  ============================================================================
##  R-side scenario helpers (read by users, not by mrgsolve)
##  ============================================================================
##
##  library(mrgsolve); library(dplyr); library(purrr); library(ggplot2)
##  mod <- mread_cache("an_mrgsolve_model.R")
##
##  # ---------- 10 prebuilt scenarios ----------
##
##  AN_simulate_scenarios <- function(end_d = 365) {
##
##    wk <- function(cmt, amt, n = floor(end_d/7), t0 = 0)
##      ev(amt = amt, cmt = cmt, time = t0, ii = 7, addl = max(n - 1, 0))
##    qd <- function(cmt, amt, n = end_d, t0 = 0)
##      ev(amt = amt, cmt = cmt, time = t0, ii = 1, addl = max(n - 1, 0))
##
##    sc <- list(
##      # 1 — no plan, no therapy: drive stays high, axes stay suppressed
##      list(lab = "1. Untreated natural history",
##           ev  = ev(amt = 0, cmt = "THERAPY"),
##           par = list(EI_START = 0, EI_ESCAL = 0, INPATIENT = 0)),
##
##      # 2 — inpatient higher-calorie refeeding (Golden 2013; Garber 2021)
##      list(lab = "2. Inpatient higher-calorie refeeding (2000 kcal start)",
##           ev  = wk("THERAPY", 1.4),
##           par = list(EI_START = 2000, EI_ESCAL = 200, EI_PLAN_MAX = 3400,
##                      INPATIENT = 1)),
##
##      # 3 — the historical "start low, go slow" comparator
##      list(lab = "3. Conservative slow refeeding (1000 kcal start)",
##           ev  = wk("THERAPY", 1.4),
##           par = list(EI_START = 1000, EI_ESCAL = 60, EI_PLAN_MAX = 3000,
##                      INPATIENT = 1)),
##
##      # 4 — steep escalation onto a large occult deficit, NO prophylaxis
##      list(lab = "4. Steep escalation, no phosphate prophylaxis",
##           ev  = wk("THERAPY", 1.4),
##           par = list(EI_START = 2400, EI_ESCAL = 400, EI_PLAN_MAX = 3600,
##                      INPATIENT = 1, ILLNESS_DUR = 4, BASE_BMI = 12.5)),
##
##      # 5 — the same escalation WITH prophylaxis (safety contrast to #4)
##      list(lab = "5. Steep escalation + PO4/Mg/thiamine prophylaxis",
##           ev  = wk("THERAPY", 1.4),
##           par = list(EI_START = 2400, EI_ESCAL = 400, EI_PLAN_MAX = 3600,
##                      INPATIENT = 1, ILLNESS_DUR = 4, BASE_BMI = 12.5,
##                      PHOS_SUP = 0.9, MG_SUP = 0.25, THIA_SUP = 0.10)),
##
##      # 6 — outpatient adolescent FBT (Lock 2010)
##      list(lab = "6. Outpatient FBT (adolescent)",
##           ev  = wk("THERAPY", 1.6),
##           par = list(EI_START = 2200, EI_ESCAL = 40, ADOLESCENT = 1, FBT = 1)),
##
##      # 7 — adult CBT-E, no family leverage over the meal plan
##      list(lab = "7. Outpatient CBT-E (adult)",
##           ev  = wk("THERAPY", 1.6),
##           par = list(EI_START = 2200, EI_ESCAL = 40, ADOLESCENT = 0, FBT = 0)),
##
##      # 8 — olanzapine add-on (Attia 2019: modest BMI gain, cognition ~flat)
##      list(lab = "8. Olanzapine 10 mg + outpatient therapy",
##           ev  = wk("THERAPY", 1.6) + qd("OLZ_GUT", 1.0),
##           par = list(EI_START = 2200, EI_ESCAL = 40)),
##
##      # 9 — fluoxetine: gate closed while underweight, opens once restored
##      list(lab = "9. Fluoxetine 60 mg (nutritional gate demonstration)",
##           ev  = wk("THERAPY", 1.6) + qd("FLX_CENT", 1.0),
##           par = list(EI_START = 2200, EI_ESCAL = 40)),
##
##      # 10 — transdermal E2 for bone (Misra 2011) + discharge relapse risk
##      list(lab = "10. Transdermal E2 + discharge at day 90",
##           ev  = wk("THERAPY", 1.4, n = 13) + wk("E2_PATCH", 1.0, n = 104),
##           par = list(EI_START = 2000, EI_ESCAL = 200, INPATIENT = 1,
##                      DISCHARGE_DAY = 90, POST_DC_FAC = 0.72))
##    )
##
##    purrr::map_dfr(sc, function(s) {
##      mod %>% param(s$par) %>%
##        mrgsim(events = s$ev, end = end_d, delta = 0.25) %>%
##        as_tibble() %>% mutate(scenario = s$lab)
##    })
##  }
##
##  # ---------- Purging-subtype variant ----------
##  # mod %>% param(PURGE = 1, K_SUP = 0.6, EI_START = 2200) %>%
##  #   mrgsim(ev(amt = 1.6, cmt = "THERAPY", ii = 7, addl = 51), end = 365)
##
##  # ---------- Adult with fractures: teriparatide vs risedronate ----------
##  # tptd <- ev(amt = 1.0, cmt = "TPTD", ii = 1, addl = 364)
##  # bisp <- ev(amt = 1.0, cmt = "BIS",  ii = 7, addl = 51)
##
##  # ---------- Calibration anchors ----------
##  # Energy partition: Forbes 1987 / Hall 2011 Lancet 378:826 — the MASS ratio
##  #   of lean to fat change follows dFFM/dFM = C/FM with C = 10.4 kg, closed
##  #   against energy conservation (EB = rho_FM*dFM + rho_FFM*dFFM). A patient
##  #   presenting with only 3-4 kg of fat therefore puts most early refeeding
##  #   weight into lean/fluid mass, and the split shifts toward fat as fat
##  #   mass is restored — the documented pattern in AN weight restoration.
##  #   The tissue energy costs are EFFECTIVE values (RHO_FFM_GAIN 5200 kcal/kg
##  #   vs the ~1800 kcal/kg composition-only figure) because refeeding weight
##  #   gain must also pay for tissue-synthesis work; the remaining gap is
##  #   carried explicitly by K_HYPERMET, the refeeding hypermetabolism term
##  #   that raises REE in proportion to the insulin-surge index. With these
##  #   values a 3000-3400 kcal/day inpatient plan reproduces ~1.2 kg/week and
##  #   an outpatient plan ~0.4 kg/week, and the meal plan tapers to
##  #   maintenance between GOAL_LO and GOAL_HI %mBMI so weight plateaus at the
##  #   goal instead of overshooting.
##  # Adaptive thermogenesis: Dulloo 2015 Obes Rev 16(S1):25 — REE runs
##  #   ~15-25% below the value predicted from body composition in
##  #   semi-starvation and normalizes over weeks (ADAPT_MAX 0.22, KOUT_ADAPT
##  #   0.08/day), which is why the meal plan must keep escalating to hold a
##  #   positive balance.
##  # Starvation index: every endocrine axis is driven by one composite signal
##  #   with a slow body-store term and a fast energy-flow term, so refeeding
##  #   normalizes T3/IGF-1/cortisol within days-weeks (flow) while leptin,
##  #   GnRH and BMD follow the slow store term over months.
##  # Hypoleptinemia and menses: Kopp 1997 Mol Psychiatry 2:335; Audi 2002
##  #   Horm Res 58:65 — menses resumes around leptin ~1.85 ng/mL, modeled as a
##  #   Hill gate (LEP50_GNRH 1.85, n = 4) feeding a slow pulse generator
##  #   (KOUT_GNRH 0.03/day), reproducing the 3-6 month lag between weight
##  #   restoration and menses.
##  # Low-T3 syndrome: free T3 falls ~40-55% with a normal TSH and recovers
##  #   within weeks of refeeding; T3 carries 60% of the bradycardia term and
##  #   the residual energy deficit the other 40%.
##  # GH resistance: Grinspoon 1996 JCEM 81:3861; Misra 2004 — GH is high while
##  #   hepatic IGF-1 is low and rebounds within days of caloric intake
##  #   (IGF_SUPP 0.65, KOUT_IGF1 0.35/day).
##  # Bone: Misra & Klibanski 2014 Lancet Diabetes Endocrinol 2:581 — AN is a
##  #   LOW-formation/HIGH-resorption state (P1NP down, CTX up), unlike
##  #   post-menopausal high-turnover loss, so BMD moves with the DIFFERENCE of
##  #   normalized markers. Misra 2011 JBMR 26:2430: physiologic TRANSDERMAL
##  #   estradiol improves BMD Z-score over 18 months while oral contraceptives
##  #   do not — reproduced via the E2 -> CTX arm, with OCP_ORAL instead
##  #   suppressing IGF-1 (hepatic first pass) and therefore bone formation.
##  #   Fazeli 2014 JCEM 99:1322: teriparatide raises P1NP and spine BMD in
##  #   adults with AN (EMAX_TPTD 0.55).
##  # Refeeding syndrome: the insulin surge is intake ABOVE the tissue
##  #   adaptation state (EI - EI_ADAPT), not absolute calories — reproducing
##  #   the modern evidence (Golden 2013; O'Connor 2016; Garber 2021 J Adolesc
##  #   Health 68:1) that higher starting calories are safe when escalation is
##  #   controlled and phosphate is replaced, while steep escalation onto a
##  #   large occult deficit (DEPL, scaled by illness duration and %mBMI)
##  #   produces the classic day 3-7 phosphate nadir.
##  # Pharmacotherapy: Attia 2019 Am J Psychiatry 176:449 — olanzapine gives
##  #   ~0.26 kg/month extra weight gain with NO improvement in eating-disorder
##  #   psychopathology, hence EMAX_OLZ_APP (0.22) >> EMAX_OLZ_COG (0.12).
##  #   Attia 1998 Am J Psychiatry 155:548 / Walsh 2006 JAMA 295:2605 —
##  #   fluoxetine is ineffective in the underweight state and did not prevent
##  #   relapse when added to CBT after weight restoration; modeled as a steep
##  #   %mBMI gate (GATE_MBMI50 0.90, Hill 8) on an already modest EMAX.
##  # Psychotherapy: Lock 2010 Arch Gen Psychiatry 67:1025 — FBT beats
##  #   individual adolescent therapy at follow-up (FBT_BONUS 1.25);
##  #   Fairburn 2009 Behav Res Ther 47:R5 for CBT-E in adults.
##
##  # ---------- Quick sanity plots ----------
##  # df <- AN_simulate_scenarios(365)
##  # ggplot(df, aes(time, BMI, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Phosphate, colour = scenario)) + geom_line() +
##  #   geom_hline(yintercept = 2.5, linetype = 2)
##  # ggplot(df, aes(time, BMD_Zscore, colour = scenario)) + geom_line()
##  # ggplot(df, aes(time, Menses_probability, colour = scenario)) + geom_line()
